### ISSUE TITLE
Modularise jOOQ-meta, jOOQ-codegen and others

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10149]
Most value of modularising jOOQ is achieved by modularising the core library `jOOQ` (#6612). There may be valid use-cases where users would like to build upon `jOOQ-meta`, `jOOQ-codegen`, and other modules, and would wish for them to be modularised as well.

This issue is to track interest in such an extension, and possibly implement it, later.

**Comment by lukaseder** [comment]
I gave this a short attempt, by modularising `jOOQ-meta`. Immediate findings:

- Tests in the usual `src/test/java` location cause issues again. I'd have to move the tests out of the module into a new project again, and run them on the classpath (I guess). That's what I did with jOOQ
- Tweaking something (who knows what) produced this fatal error in the build:

```
13:25:31,864 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project jooq-meta: There are test failures.
13:25:31,872 [ERROR]
13:25:31,874 [ERROR] Please refer to C:\Users\lukas\jOOQ\3.15\workspace\jOOQ-pro\jOOQ-meta\target\surefire-reports for the individual test results.
13:25:31,880 [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
13:25:31,885 [ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
13:25:31,890 [ERROR] Command was cmd.exe /X /C ""C:\Program Files\Java\jdk-14\bin\java" @C:\Users\lukas\AppData\Local\Temp\surefire4570263643886195449\surefireargs17993951327206704995 C:\Users\lukas\AppData\Local\Temp\surefire4570263643886195449 2020-11-20T13-25-31_345-jvmRun1 surefire1936436808108813418tmp surefire_012556220088556085016tmp"
13:25:31,905 [ERROR] Error occurred in starting fork, check output in log
13:25:31,908 [ERROR] Process Exit Code: 1
13:25:31,910 [ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
13:25:31,916 [ERROR] Command was cmd.exe /X /C ""C:\Program Files\Java\jdk-14\bin\java" @C:\Users\lukas\AppData\Local\Temp\surefire4570263643886195449\surefireargs17993951327206704995 C:\Users\lukas\AppData\Local\Temp\surefire4570263643886195449 2020-11-20T13-25-31_345-jvmRun1 surefire1936436808108813418tmp surefire_012556220088556085016tmp"
13:25:31,930 [ERROR] Error occurred in starting fork, check output in log
13:25:31,933 [ERROR] Process Exit Code: 1
13:25:31,935 [ERROR]    at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:669)
13:25:31,940 [ERROR]    at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
13:25:31,944 [ERROR]    at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
13:25:31,947 [ERROR]    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
```

I guess we can live for another few years without a modular code generator.

**Comment by cowwoc** [comment]
@lukaseder The surefire maven plugin has made major JPMS changes (improving support) in the past 6 months. I could point you to the relevant JIRA discussion but I'll provide you with a quick summary to save you some time.

First, I would upgrade to the latest version. Second, you need to decide whether you are doing white box or black box testing. If you are doing white box testing, you are expected to run your tests on the classpath. If you are doing black box testing, you can add `module-info.java` to `src/test/java` or move your tests into a separate Maven module. Either approach works.

The dumps you see above are not real crashes. If you open the dump file you will see the underlying cause is Surefire receiving a simple error message (from `java`) while trying to launch a new JVM. Newer versions of surefire simply output these errors to the console (in most but not all cases). Usually the errors involve simple mistakes in your `module-info.java` like missing imports.

**Comment by lukaseder** [comment]
I already regret having looked at this 😁

See you (in the context of this issue) again in a few years

**Comment by ascertrobw** [comment]
Would definitely be cool to have the Kotlin module as optional - just upgrading to 3.15.2, and the OSGi manifest has an import for the Jackson kotlin module, which rapidly escalates into needing to include the kotlin JARs themselves in our app stack even though we have no need/use of kotlin. 

An alternative, which is purely a workaround for the OSGi use case, would be to make the Jackson kotlin import optional in the OSGi headers (probably the workaround we'll adopt to hacking in locally).

**Comment by lukaseder** [comment]
@ascertrobw Can you please create a new issue

**Comment by lukaseder** [comment]
Additional work in the future: https://github.com/jOOQ/jOOQ/issues/12526

**Comment by ascertrobw** [comment]
> 
> 
> I'm looking at this again. jOOQ 3.15's baseline for the Open Source Edition is Java 11, so all distributions (except the now commercial Java 8 one) are now modular.
> 
> I think that `jOOQ-meta` and `jOOQ-codegen` should be easy to make modular.

Cool - sounds good.
