### ISSUE TITLE
java.nio.file.InvalidPathException: Illegal char <*> when using FilePattern on module path

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10143]
Not sure if this depends on jOOQ being modularised first (#6612), or if it happens already if the existing jOOQ distributions are put on the module path, but it seems that the implementation of `Class.getResource()` has been changed to throw an `InvalidPathException`, instead of just returning `null` in case a path is invalid:

```
java.nio.file.InvalidPathException: Illegal char <*> at index 9: org\jooq\**\2.sql
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/jdk.internal.module.Resources.toSafeFilePath(Resources.java:143)
	at java.base/jdk.internal.module.Resources.toFilePath(Resources.java:97)
	at java.base/jdk.internal.module.ModulePatcher$ExplodedResourceFinder.find(ModulePatcher.java:505)
	at java.base/jdk.internal.module.ModulePatcher$PatchedModuleReader.findResourceInPatch(ModulePatcher.java:301)
	at java.base/jdk.internal.module.ModulePatcher$PatchedModuleReader.find(ModulePatcher.java:357)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findResource(BuiltinClassLoader.java:439)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findResource(BuiltinClassLoader.java:225)
	at java.base/java.lang.Class.getResource(Class.java:2728)
	at org.jooq/org.jooq.FilePattern.load(FilePattern.java:209)
```

The fix for this should not apply to the Java 6 distribution, which does not yet have a `InvalidPathException`.

**Comment by lukaseder** [comment]
The exception could also be thrown in `MiniJAXB.getSchema()`
