### ISSUE TITLE
Runtime compilation error when compiling enum types on module path

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10144]
When trying to modularise jOOQ (#6612), there is a compilation error from compiling enum types at runtime for usage in e.g. MySQL:

```
Caused by: org.jooq.tools.reflect.ReflectException: Compilation error: /org/jooq/impl/GeneratedEnum4066.java:2: error: cannot find symbol
enum GeneratedEnum4066 implements org.jooq.EnumType {
                                          ^
  symbol:   class EnumType
  location: package org.jooq
/org/jooq/impl/GeneratedEnum4066.java:8: error: method does not override or implement a method from a supertype
  @Override
  ^
/org/jooq/impl/GeneratedEnum4066.java:12: error: method does not override or implement a method from a supertype
  @Override
  ^
3 errors

	at org.jooq/org.jooq.tools.reflect.Compile.compile(Compile.java:100)
	at org.jooq/org.jooq.tools.reflect.Reflect.compile(Reflect.java:104)
	at org.jooq/org.jooq.tools.reflect.Reflect.compile(Reflect.java:79)
	at org.jooq/org.jooq.impl.ParserImpl.parseDataTypeEnum(ParserImpl.java:10466)
```

**Comment by lukaseder** [comment]
Looks like jOOR needs to add the `jdk.module.path` to the classpath as well for in-memory compilation...

**Comment by lukaseder** [comment]
While this has to be done, it seems it's not enough, at least for unit tests, which have jOOQ as compiled classes on their module path: `C:\Users\lukas\jOOQ\master\workspace\jOOQ-pro\jOOQ\target\classes`

Not sure if this needs fixing. We might be able to move these unit tests in a different project, where jOOQ is available as a `.jar` file, not as a set of classes. After all, this is about finding a jOOQ type (`org.jooq.EnumType`), not a user type.

**Comment by lukaseder** [comment]
Fixing this in jOOR as well: https://github.com/jOOQ/jOOR/issues/104
