### ISSUE TITLE
Support foreign keys referencing unique indexes in interpreter

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10206]
When interpreting a schema where a foreign key references a unique index, we get an exception:

```
org.jooq.exception.DataDefinitionException: Primary key does not exist
	at org.jooq.impl.Interpreter.primaryKeyNotExists(Interpreter.java:1091)
	at org.jooq.impl.Interpreter.addForeignKey0(Interpreter.java:372)
	at org.jooq.impl.Interpreter.addForeignKey(Interpreter.java:327)
	at org.jooq.impl.Interpreter.addConstraint(Interpreter.java:745)
	at org.jooq.impl.Interpreter.accept0(Interpreter.java:536)
	at org.jooq.impl.Interpreter.accept(Interpreter.java:181)
	at org.jooq.impl.InterpreterMetaProvider.provide(InterpreterMetaProvider.java:94)
	at org.jooq.impl.DefaultDSLContext.meta(DefaultDSLContext.java:470)
	at org.jooq.impl.AbstractMeta.apply(AbstractMeta.java:340)
	at org.jooq.impl.AbstractMeta.apply(AbstractMeta.java:325)
	at org.jooq.test.all.testcases.MetaDataTests.testMetaApply(MetaDataTests.java:794)
	at org.jooq.test.jOOQAbstractTest.testMetaApply(jOOQAbstractTest.java:2243)
```

----
See also: #5972

**Comment by lukaseder** [comment]
The actual problem here is that schemas can have foreign keys referencing non-primary unique constraints, which are not exported currently by JDBC `DatabaseMetaData` backed `Meta` implementations, see: #5179.

This issue here is merely a side effect of that limitation

**Comment by lukaseder** [comment]
This raises another question. Should we better proceed with replacing the `DatabaseMetaData` backed implementation by one that uses `jOOQ-meta`? #8655
