### ISSUE TITLE
DataDefinitionException: Table can only have one identity when using Meta.apply() on PostgreSQL

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10207]
On PostgreSQL, when creating tables like these (see #9200):

```sql
create table t_9200 (
  id  int generated always as identity,
  id2 serial
)
```

And then using `DSLContext.meta().apply(...)` on it, to invoke the interpreter, the following exception is thrown:

```
org.jooq.exception.DataDefinitionException: Table can only have one identity: "public"."t_9200"."id"
	at org.jooq.impl.Interpreter.addField(Interpreter.java:725)
	at org.jooq.impl.Interpreter.newTable(Interpreter.java:1194)
	at org.jooq.impl.Interpreter.accept0(Interpreter.java:312)
	at org.jooq.impl.Interpreter.accept(Interpreter.java:179)
	at org.jooq.impl.InterpreterMetaProvider.provide(InterpreterMetaProvider.java:94)
	at org.jooq.impl.DefaultDSLContext.meta(DefaultDSLContext.java:470)
	at org.jooq.test.all.testcases.MetaDataTests.testMetaApply(MetaDataTests.java:795)
	at org.jooq.test.jOOQAbstractTest.testMetaApply(jOOQAbstractTest.java:2243)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

Just like in the code generator, we should just issue a log message and silently discard the second identity column.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.14. Backport scheduled for 3.13.3 (#10209)
