### ISSUE TITLE
Support parsing CHECK constraints without parentheses

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#10220]
### Expected behavior and actual behavior:

The following DDL fails to parse when using DDLDatabase:

```sql
CREATE TABLE user
(
    id   UUID DEFAULT random_uuid() NOT NULL PRIMARY KEY,
    name VARCHAR                    NOT NULL
);

CREATE TABLE race
(
    id             UUID               NOT NULL DEFAULT random_uuid() PRIMARY KEY,
    organizer      UUID               NOT NULL REFERENCES user,
    meters         INT                NOT NULL DEFAULT 10000 CHECK meters BETWEEN 1 AND 100000,
    cutoff_seconds INT                NOT NULL DEFAULT 4*60*60 CHECK cutoff_seconds BETWEEN 1 AND 100000,
    start          SMALLDATETIME      NOT NULL,
    public_id      INT AUTO_INCREMENT NOT NULL UNIQUE CHECK public_id BETWEEN 1 AND 999999999
);

CREATE TABLE participant
(
    id               UUID          NOT NULL DEFAULT random_uuid() PRIMARY KEY,
    race             UUID          NOT NULL REFERENCES race,
    user             UUID          NOT NULL REFERENCES user,
    joined           SMALLDATETIME NOT NULL,
    progress_meters  INT           NOT NULL DEFAULT 0 CHECK progress_meters BETWEEN 0 AND 100000,
    progress_seconds INT           NOT NULL DEFAULT 0 CHECK progress_seconds BETWEEN 0 AND 100000
);

CREATE TABLE position
(
    id             UUID           NOT NULL DEFAULT random_uuid() PRIMARY KEY,
    participant_id UUID           NOT NULL REFERENCES participant,
    longitude      DECIMAL(9, 6) NOT NULL,
    latitude       DECIMAL(9, 6) NOT NULL,
    accuracy       INT            NOT NULL CHECK accuracy BETWEEN 0 AND 40075017 /* earth circumference at the equator */,
    time           SMALLDATETIME  NOT NULL
);
```

and results in

```
ERROR org.jooq.meta.extensions.ddl.DDLDatabase - An exception occurred while
 parsing script source : src/main/resources/database.sql. Please report this error to https://gi
thub.com/jOOQ/jOOQ/issues/new
org.jooq.impl.ParserException: Token '(' expected: [11:68] ...  INT                NOT NULL DEFA
ULT 10000 CHECK [*]meters BETWEEN 1 AND 100000,
    cutoff_seconds INT                NOT NULL DEF...
        at org.jooq.impl.ParserContext.expected(ParserImpl.java:11088)
        at org.jooq.impl.ParserImpl.parse(ParserImpl.java:10530)
        at org.jooq.impl.ParserImpl.parse(ParserImpl.java:10525)
        at org.jooq.impl.ParserImpl.parseCheckSpecification(ParserImpl.java:3848)
        at org.jooq.impl.ParserImpl.parseInlineConstraints(ParserImpl.java:3720)
        at org.jooq.impl.ParserImpl.parseCreateTable(ParserImpl.java:3339)
        at org.jooq.impl.ParserImpl.parseCreate(ParserImpl.java:2207)
        at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:859)
        at org.jooq.impl.ParserImpl.parse(ParserImpl.java:556)
        at org.jooq.impl.ParserImpl.parse(ParserImpl.java:543)
        at org.jooq.meta.extensions.ddl.DDLDatabase.load(DDLDatabase.java:170)
        at org.jooq.meta.extensions.ddl.DDLDatabase.access$000(DDLDatabase.java:86)
        at org.jooq.meta.extensions.ddl.DDLDatabase$2.load(DDLDatabase.java:155)
        at org.jooq.FilePattern.load0(FilePattern.java:297)
        at org.jooq.FilePattern.load(FilePattern.java:277)
        at org.jooq.FilePattern.load(FilePattern.java:223)
        at org.jooq.meta.extensions.ddl.DDLDatabase.export(DDLDatabase.java:152)
        at org.jooq.meta.extensions.AbstractInterpretingDatabase.connection(AbstractInterpreting
Database.java:100)
        at org.jooq.meta.extensions.AbstractInterpretingDatabase.create0(AbstractInterpretingDat
abase.java:77)
        at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:274)
        at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:263)
        at org.jooq.meta.AbstractDatabase.setConnection(AbstractDatabase.java:253)
        at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:521)
        at org.jooq.codegen.GenerationTool.run(GenerationTool.java:222)
        at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:217)
        at org.jooq.codegen.GenerationTool.main(GenerationTool.java:189)
19:40:25.099 [main] ERROR org.jooq.codegen.GenerationTool - Cannot read C:\Workspaces\raceparty\
server\build\tmp\generateDbJooqSchemaSource\config.xml. Error : Error while exporting schema
org.jooq.exception.DataAccessException: Error while exporting schema
        at org.jooq.meta.extensions.AbstractInterpretingDatabase.connection(AbstractInterpreting
Database.java:103)
        at org.jooq.meta.extensions.AbstractInterpretingDatabase.create0(AbstractInterpretingDat
abase.java:77)
        at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:274)
        at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:263)
        at org.jooq.meta.AbstractDatabase.setConnection(AbstractDatabase.java:253)
        at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:521)
        at org.jooq.codegen.GenerationTool.run(GenerationTool.java:222)
        at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:217)
        at org.jooq.codegen.GenerationTool.main(GenerationTool.java:189)
Caused by: org.jooq.impl.ParserException: Token '(' expected: [11:68] ...  INT                NO
T NULL DEFAULT 10000 CHECK [*]meters BETWEEN 1 AND 100000,
    cutoff_seconds INT                NOT NULL DEF...
        at org.jooq.impl.ParserContext.expected(ParserImpl.java:11088)
        at org.jooq.impl.ParserImpl.parse(ParserImpl.java:10530)
        at org.jooq.impl.ParserImpl.parse(ParserImpl.java:10525)
        at org.jooq.impl.ParserImpl.parseCheckSpecification(ParserImpl.java:3848)
        at org.jooq.impl.ParserImpl.parseInlineConstraints(ParserImpl.java:3720)
        at org.jooq.impl.ParserImpl.parseCreateTable(ParserImpl.java:3339)
        at org.jooq.impl.ParserImpl.parseCreate(ParserImpl.java:2207)
        at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:859)
        at org.jooq.impl.ParserImpl.parse(ParserImpl.java:556)
        at org.jooq.impl.ParserImpl.parse(ParserImpl.java:543)
        at org.jooq.meta.extensions.ddl.DDLDatabase.load(DDLDatabase.java:170)
        at org.jooq.meta.extensions.ddl.DDLDatabase.access$000(DDLDatabase.java:86)
        at org.jooq.meta.extensions.ddl.DDLDatabase$2.load(DDLDatabase.java:155)
        at org.jooq.FilePattern.load0(FilePattern.java:297)
        at org.jooq.FilePattern.load(FilePattern.java:277)
        at org.jooq.FilePattern.load(FilePattern.java:223)
        at org.jooq.meta.extensions.ddl.DDLDatabase.export(DDLDatabase.java:152)
        at org.jooq.meta.extensions.AbstractInterpretingDatabase.connection(AbstractInterpreting
Database.java:100)
        ... 8 common frames omitted
```

Note that commenting out the CHECK constraints triggers a second parser bug with the `AUTO_INCREMENT` column definition.

### Versions:

- jOOQ: 3.13.2
- Java: 14
- Database (include vendor): H2 1.4.200
- OS: Win 10 x64 1909

**Comment by katzyn** [comment]
Just couple of comments about syntax of H2 itself (not about jOOQ):

1. `CHECK meters BETWEEN 1 AND 100000` is not valid, it should be `CHECK (meters BETWEEN 1 AND 100000)`. Current documentation of H2 is not correct, it was already fixed for the next not yet released version. H2 will continue to accept such invalid constraints without parentheses, but they should not be used.

2. `AUTO_INCREMENT` is a deprecated compatibility-only clause in H2, it should be replaced with standard `GENERATED BY DEFAULT AS IDENTITY`

**Comment by lukaseder** [comment]
Thanks for your report, @axelfontaine, and for your comment, @katzyn.

I'm trying to think of a syntactic reason why we should require the parentheses (other than this being required by most RDBMS), but I cannot think of one. I think they could be optional in our parser as well... If there was a syntactic edge case where the lack of parentheses is a problem, users can always just add them (which I also recommend)

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.14. Backport scheduled for 3.13.3 (#10222)

**Comment by axelfontaine** [comment]
Thanks for fixing the CHECK parsing. Did you have the chance to look at the AUTO_INCREMENT problem as well?

**Comment by lukaseder** [comment]
I have not, sorry for the oversight. Will look into this separately, as it's not related to `CHECK` constraint syntax: #10223

**Comment by lukaseder** [comment]
That `AUTO_INCREMENT` problem appears whenever there is a column that has a `DEFAULT` expression, which precedes the identity column. If you put the `public_id` column first, the problem goes away (as a workaround)
