### ISSUE TITLE
NPE in Interpreter when foreign key references table from other schema that does not exist

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10272]
The following DDL script should throw `DataDefinitionException`:

```sql
create schema s2; create table s2.t2 (i int references s1.t1)
```

The schema `s1` does not exist. However, it throws a NPE, instead:

```
Caused by: java.lang.NullPointerException
	at org.jooq.impl.Interpreter.addForeignKey0(Interpreter.java:366)
	at org.jooq.impl.Interpreter.addForeignKey(Interpreter.java:336)
	at org.jooq.impl.Interpreter.addConstraint(Interpreter.java:754)
	at org.jooq.impl.Interpreter.accept0(Interpreter.java:324)
	at org.jooq.impl.Interpreter.accept(Interpreter.java:181)
	at org.jooq.impl.InterpreterMetaProvider.loadSource(InterpreterMetaProvider.java:106)
	at org.jooq.impl.InterpreterMetaProvider.provide(InterpreterMetaProvider.java:91)
	at org.jooq.impl.SourceMetaProvider.provide(SourceMetaProvider.java:80)
	at org.jooq.impl.DefaultDSLContext.meta(DefaultDSLContext.java:461)
	at org.jooq.test.InterpreterTest.meta(InterpreterTest.java:2285)
	at org.jooq.test.InterpreterTest.meta(InterpreterTest.java:2280)
	at org.jooq.test.InterpreterTest.lambda$36(InterpreterTest.java:606)
	at org.jooq.test.util.BaseTest.assertThrows(BaseTest.java:150)
	... 31 more
```

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.14.0. Backport scheduled for 3.13.3 (#10273)
