### ISSUE TITLE
Error in Sybase ASE INSERT .. DEFAULT VALUES emulation when used with identity column

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10408]
An error is raised when emulating `INSERT .. DEFAULT VALUES` in Sybase ASE in the presence of an identity column:

```
org.jooq.exception.DataAccessException: SQL [insert into [dbo].[t_triggers] values (default, default, default)]; An explicit value for the identity field in table 'dbo.t_triggers' can only be specified in an insert statement when a field list is used.

	at org.jooq_3.14.0-SNAPSHOT.ASE.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2790)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:757)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:385)
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:119)
	at org.jooq.test.all.testcases.InsertUpdateTests.testInsertDefaultValues(InsertUpdateTests.java:433)
	at org.jooq.test.jOOQAbstractTest.testInsertDefaultValues(jOOQAbstractTest.java:1292)
```

Example table:

```sql
CREATE TABLE t_triggers (
  id_generated int IDENTITY not null,
  id int null,
  counter int null,

  CONSTRAINT pk_t_triggers PRIMARY KEY (id_generated)
);
```

Test case:

```java
assertEquals(1,
create().insertInto(TTriggers())
        .defaultValues()
        .execute());
```

Current emulation:

```sql
insert into [dbo].[t_triggers]
values (
  default,
  default,
  default
)
```

This also doesn't work:

```sql
insert into t_triggers (id_generated, id, counter)
values (
  default,
  default,
  default
);
```

It produces:

> SQL-Fehler [233] [23000]: The column id_generated in table t_triggers does not allow null values.

We must exclude the identity column from the column list:

```sql
insert into t_triggers (id, counter)
values (
  default,
  default
);
```

Curiously enough, the behaviour is inconsistent with other types of default expressions, e.g. this works:

```sql
create table xyz (i int default 1 not null);
insert into xyz (i) values (default);
```

**Comment by lukaseder** [comment]
Just omitting one of the `default` values seems to work as well o_O:

```sql
insert into [dbo].[t_triggers]
values (
  default,
  default
);
```

**Comment by lukaseder** [comment]
That's too risky. Perhaps a bug in Sybase ASE that accidentally leads to the expected result? Better play safe and list the columns explicitly.

**Comment by lukaseder** [comment]
On the other hand, if the table has only a single identity column (see #6935), then we have to generate this syntax:

```sql
insert into [dbo].[t_identity_pk_only]
values ()
```
