### ISSUE TITLE
Support lazy DataType lookups in DSL.val() and DSL.inline()

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10438]
Currently, it is not possible to write things like:

```java
enum E { A, B }

inline(E.A);
val(E.A);
```

Unless there is a converted data type for `E` being registered statically by the classloader prior to using the above API. The static type registry is not very sound (there are many issues because of it), and cusotm data types should not end up in the static type registry. Fixing this (and a few other things related to converted data types, see e.g. https://github.com/jOOQ/jOOQ/issues/10312#issuecomment-651143792), will lead to the above code *never* working. 

Currently, it works when a data type is created for `E` before a bind variable, e.g.:

```java
VARCHAR.asConvertedDataType(new EnumConverter<>(String.class, E.class));
```

The solution is to look up the data type lazily, when generating SQL, not eagerly, when creating the `Param`, which would also allow to register two separate converters for the same `<U>` type, which might currently not be possible for these reasons, unless the type is provided explicitly.

The type can always be provided explicitly, of course:

```java
inline(E.A, convertedType)
```

**Comment by lukaseder** [comment]
We already have a mutable `DataTypeProxy` introduced with #9061, which might be reusable here.

**Comment by lukaseder** [comment]
We would want to use `DSL.coerce()` to coerce existing bind values to contextual data types and thus apply their converters and bindings. For this, we need to fix https://github.com/jOOQ/jOOQ/issues/10440 first.

**Comment by lukaseder** [comment]
With the new changes, this will now work:

```java
@Test
public void testImplicitConverterOnBindValues() {
    Param<E> i = inline(E.A);
    Param<E> v = val(E.B);

    Condition ci1 = inline((E) null).eq(i);
    Condition cv1 = val((E) null).eq(v);

    DataType<E> ts = VARCHAR.asConvertedDataType(new EnumConverter<>(String.class, E.class));
    DataType<E> ti = INTEGER.asConvertedDataType(new EnumConverter<>(Integer.class, E.class));

    i.coerce(ti).toString();

    Condition ci2 = inline((E) null, ts).eq(i);
    Condition cv2 = val((E) null, ts).eq(v);
    Condition ci3 = inline((E) null, ti).eq(i);
    Condition cv3 = val((E) null, ti).eq(v);

    DSLContext ctx = DSL.using(DEFAULT);

    assertEquals("null = 'A'", ctx.render(ci1));
    assertEquals("? = ?", ctx.render(cv1));
    assertEquals("null = 'A'", ctx.render(ci2));
    assertEquals("? = ?", ctx.render(cv2));
    assertEquals("null = 0", ctx.render(ci3));
    assertEquals("? = ?", ctx.render(cv3));
}
```

Previously, the above test would have raised an exception on `inline(E.A)`. However, we must be careful not to create a backwards incompatibility. A test like this would have failed only on the last assertions:

```java
@Test
public void testImplicitConverterOnBindValues() {
    DataType<E> ts = VARCHAR.asConvertedDataType(new EnumConverter<>(String.class, E.class));
    DataType<E> ti = INTEGER.asConvertedDataType(new EnumConverter<>(Integer.class, E.class));
    
    Param<E> i = inline(E.A);
    Param<E> v = val(E.B);

    Condition ci1 = inline((E) null).eq(i);
    Condition cv1 = val((E) null).eq(v);

    i.coerce(ti).toString();

    Condition ci2 = inline((E) null, ts).eq(i);
    Condition cv2 = val((E) null, ts).eq(v);
    Condition ci3 = inline((E) null, ti).eq(i);
    Condition cv3 = val((E) null, ti).eq(v);

    DSLContext ctx = DSL.using(DEFAULT);

    assertEquals("null = 'A'", ctx.render(ci1));
    assertEquals("? = ?", ctx.render(cv1));
    assertEquals("null = 'A'", ctx.render(ci2));
    assertEquals("? = ?", ctx.render(cv2));
    assertEquals("null = 0", ctx.render(ci3)); // failure here
    assertEquals("? = ?", ctx.render(cv3));
}
```

Likewise


```java
@Test
public void testImplicitConverterOnBindValues() {
    DataType<E> ti = INTEGER.asConvertedDataType(new EnumConverter<>(Integer.class, E.class));
    DataType<E> ts = VARCHAR.asConvertedDataType(new EnumConverter<>(String.class, E.class));
    
    Param<E> i = inline(E.A);
    Param<E> v = val(E.B);

    Condition ci1 = inline((E) null).eq(i);
    Condition cv1 = val((E) null).eq(v);

    i.coerce(ti).toString();

    Condition ci2 = inline((E) null, ts).eq(i);
    Condition cv2 = val((E) null, ts).eq(v);
    Condition ci3 = inline((E) null, ti).eq(i);
    Condition cv3 = val((E) null, ti).eq(v);

    DSLContext ctx = DSL.using(DEFAULT);

    assertEquals("null = 'A'", ctx.render(ci1)); // failure here
    assertEquals("? = ?", ctx.render(cv1));
    assertEquals("null = 'A'", ctx.render(ci2));
    assertEquals("? = ?", ctx.render(cv2));
    assertEquals("null = 0", ctx.render(ci3));
    assertEquals("? = ?", ctx.render(cv3));
}
```

This is due to the static type registry which registers the first data type (and converter / binding), which is associated with `E.class` for all `E.class` usages: https://github.com/jOOQ/jOOQ/issues/9492

This was of course wrong, because there was no way to register a second such type without always having to explicitly provide it with `inline(E, DataType<E>)` or `val(E, DataType<E>)`

**Comment by lukaseder** [comment]
I've found a (not so pretty) implementation that allows for maintaining the current behaviour (logging a warning if it is encountered), while supporting lazy data type lookups going forward.

The deprecation of the static type registry is now active: https://github.com/jOOQ/jOOQ/issues/9492

**Comment by lukaseder** [comment]
This test still fails:

```java
@Test
public void testImplicitConverterOnBindValuesForBuiltInTypes() {
    DSLContext ctx = DSL.using(DEFAULT);

    Param<Integer> i = inline(1);
    Param<Integer> v = val(1);

    Condition ci1 = inline((Integer) null).eq(i);
    Condition cv1 = val((Integer) null).eq(v);

    DataType<Integer> ts = VARCHAR.asConvertedDataType(Converter.ofNullable(String.class, Integer.class, Integer::valueOf, Object::toString));
    DataType<Integer> ti = INTEGER.asConvertedDataType(Converter.ofNullable(Integer.class, Integer.class, x -> x - 1, x -> x + 1));

    Condition ci2 = inline((Integer) null, ts).eq(i);
    Condition cv2 = val((Integer) null, ts).eq(v);
    Condition ci3 = inline((Integer) null, ti).eq(i);
    Condition cv3 = val((Integer) null, ti).eq(v);

    assertEquals("null = 1", ctx.render(ci1));
    assertEquals("? = ?", ctx.render(cv1));
    assertEquals("null = '1'", ctx.render(ci2));
    assertEquals("? = ?", ctx.render(cv2));
    assertEquals("null = 2", ctx.render(ci3));
    assertEquals("? = ?", ctx.render(cv3));
}
```

It failed also in jOOQ 3.13:

```
      org.junit.ComparisonFailure: expected:<null = ['1']> but was:<null = [1]>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.jooq.test.AbstractTest.assertEquals(AbstractTest.java:204)
	at org.jooq.test.ConverterTest.testImplicitConverterOnBindValuesForBuiltInTypes(ConverterTest.java:255)
```

The behaviour was inconsistent with this one here, where jOOQ internally wraps `T` in `DSL.val(T)`. The following version of the test passes already in 3.13:

```java
@Test
public void testImplicitConverterOnBindValuesForBuiltInTypes() {
    DSLContext ctx = DSL.using(DEFAULT);

    Condition ci1 = inline((Integer) null).eq(1);
    Condition cv1 = val((Integer) null).eq(1);

    DataType<Integer> ts = VARCHAR.asConvertedDataType(Converter.ofNullable(String.class, Integer.class, Integer::valueOf, Object::toString));
    DataType<Integer> ti = INTEGER.asConvertedDataType(Converter.ofNullable(Integer.class, Integer.class, x -> x - 1, x -> x + 1));

    Condition ci2 = inline((Integer) null, ts).eq(1);
    Condition cv2 = val((Integer) null, ts).eq(1);
    Condition ci3 = inline((Integer) null, ti).eq(1);
    Condition cv3 = val((Integer) null, ti).eq(1);

    assertEquals("null = 1", ctx.renderInlined(ci1));
    assertEquals("? = ?", ctx.render(cv1));
    assertEquals("null = '1'", ctx.renderInlined(ci2));
    assertEquals("? = ?", ctx.render(cv2));
    assertEquals("null = 2", ctx.renderInlined(ci3));
    assertEquals("? = ?", ctx.render(cv3));
}
```

Which leads us back to the original motivation of this issue: To be able to explicitly wrap values in `DSL::val` or more specifically, in `DSL::inline`, without having to provide an explicit data type every time.
