### ISSUE TITLE
Firebird arithmetic exception, numeric overflow, or string truncation; numeric value is out of range, when using Field.add(DayToSecond) with large millisecond numbers

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10448]
Firebird's `DATEADD()` function takes an integer as the amount to be added to a timestamp, which makes using `MILLISECOND` as a datepart risky:

```
org.jooq.exception.DataAccessException: SQL [select dateadd(millisecond, cast(? as bigint), cast(? as timestamp)) "ts8a", dateadd(millisecond, cast(? as bigint), cast(? as timestamp)) "ts8b", dateadd(millisecond, cast(? as bigint), cast(? as timestamp)) "ts8c", dateadd(millisecond, cast(? as bigint), cast(? as timestamp)) "ts8d" from RDB$DATABASE -- SQL rendered with a free trial version of jOOQ 3.14.0-SNAPSHOT]; arithmetic exception, numeric overflow, or string truncation; numeric value is out of range [SQLState:22003, ISC error code:335544916]
	at org.jooq_3.14.0-SNAPSHOT.FIREBIRD_2_5.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2794)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:757)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1618)
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1577)
	at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:349)
	at org.jooq.impl.Tools.fetchOne(Tools.java:2177)
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:641)
	at org.jooq.impl.SelectImpl.fetchOne(SelectImpl.java:3074)
	at org.jooq.test.all.testcases.DataTypeTests.lambda$13(DataTypeTests.java:2666)
	at org.jooq.test.jOOQAbstractTest.bindAndInline(jOOQAbstractTest.java:1127)
	at org.jooq.test.BaseTest.bindAndInline(BaseTest.java:1628)
	at org.jooq.test.all.testcases.DataTypeTests.testDateTimeArithmetic_ADD_SUB(DataTypeTests.java:2561)
	at org.jooq.test.jOOQAbstractTest.testDateTimeArithmetic_ADD_SUB(jOOQAbstractTest.java:4008)
```

We should add seconds instead, and only add milliseconds in addition if they're present in the interval.

**Comment by lukaseder** [comment]
This was discovered via #10374.
