### ISSUE TITLE
Add support for Interval precision and scale

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10452]
Dialects that support interval data types usually also support precision and "scale" on the data type. For example, it is possible to specify `INTERVAL DAY (9) TO SECOND (6)`.

This is currently not possible in jOOQ. See also: #8971

**Comment by lukaseder** [comment]
While in some dialects (e.g. H2), interval values are truncated to fit the interval type (e.g. `1-1` is truncated to `1-0` when the type is `INTERVAL YEAR`), this truncation isn't done in some other dialects, e.g. H2, where an exception is raised:

```
Caused by: org.hsqldb.HsqlException: data exception: invalid interval format
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.Scanner.newInterval(Unknown Source)
	at org.hsqldb.Scanner.convertToDatetimeInterval(Unknown Source)
	at org.hsqldb.types.IntervalType.convertToType(Unknown Source)
	at org.hsqldb.types.IntervalType.convertToDefaultType(Unknown Source)
	... 54 more
```

This means that precision, scale, and the different interval types are a necessary prerequisite to support such types in those dialects at all.
