### ISSUE TITLE
Error while running MetaFunction

### ISSUE THREAD

**Issue by arunkumargit** [jOOQ/jOOQ#10485]
Getting the error when I try to access `getTables()`

**Sample Code:**
 
```java
Connection conDev = DriverManager.getConnection(connectionUrlDev);
Connection conProd = DriverManager.getConnection(connectionUrlProd);

DSLContext dslContextDev = DSL.using(conDev, SQLDialect.SQLSERVER2017);
DSLContext dslContextProd = DSL.using(conProd, SQLDialect.SQLSERVER2017);

Meta metaDev = dslContextDev.meta(conDev.getMetaData());
Meta metaProd = dslContextProd.meta(conProd.getMetaData());

List<Table<?>> tables = metaDev.getTables(); // error thrown here
```

**Stack trace:**
```
Exception in thread "main" org.jooq.exception.DataAccessException: Error while running MetaFunction
	at org.jooq.impl.MetaImpl.meta(MetaImpl.java:148)
	at org.jooq.impl.MetaImpl.access$100(MetaImpl.java:109)
	at org.jooq.impl.MetaImpl$MetaCatalog.getSchemas(MetaImpl.java:255)
	at org.jooq.impl.MetaImpl.getSchemas0(MetaImpl.java:191)
	at org.jooq.impl.AbstractMeta$2.iterator(AbstractMeta.java:144)
	at org.jooq.impl.AbstractMeta.get(AbstractMeta.java:284)
	at org.jooq.impl.AbstractMeta.initSchemas(AbstractMeta.java:141)
	at org.jooq.impl.AbstractMeta.getSchemas(AbstractMeta.java:133)
	at org.jooq.impl.MetaImpl.getTables0(MetaImpl.java:200)
	at org.jooq.impl.AbstractMeta$4.iterator(AbstractMeta.java:186)
	at org.jooq.impl.AbstractMeta.get(AbstractMeta.java:284)
	at org.jooq.impl.AbstractMeta.initTables(AbstractMeta.java:183)
	at org.jooq.impl.AbstractMeta.getTables(AbstractMeta.java:175)
	at Main4.main(Main4.java:36)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Reference to database and/or server name in 'master.sys.schemas' is not supported in this version of SQL Server.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:254)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1608)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:578)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:508)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7240)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2869)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:243)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:218)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQueryInternal(SQLServerPreparedStatement.java:448)
	at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getSchemasInternal(SQLServerDatabaseMetaData.java:1275)
	at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getSchemas(SQLServerDatabaseMetaData.java:1285)
	at org.jooq.impl.MetaImpl$MetaCatalog$1.run(MetaImpl.java:262)
	at org.jooq.impl.MetaImpl.meta(MetaImpl.java:145)
``` 

### Versions:

- jOOQ: 3.13.4 (trial version)
- Java: 1.8
- Database (include vendor): mssql 
- OS: mac
- JDBC Driver (include name if inofficial driver): mssql-jdbc / 7.0.0.jre8

**Comment by lukaseder** [comment]
Thank you very much for your message.

Can you try calling the `getTables()` method like this?

```java
metaDev
  .getCatalog(desiredCatalogName).
  .schemaStream()
  .flatMap(s -> s.tableStream())
  .collect(Collectors.toList());
```

**Comment by arunkumargit** [comment]
@lukaseder Thanks a lot, that really helped, **but** now i'm getting a similar error when I try to use `migrateTo`

**Sample code:**

```
           Connection conDev = DriverManager.getConnection(connectionUrlDev);
            Connection conProd = DriverManager.getConnection(connectionUrlProd);

            DSLContext dslContextDev = DSL.using(conDev, SQLDialect.SQLSERVER2017);
            DSLContext dslContextProd = DSL.using(conProd, SQLDialect.SQLSERVER2017);

            Meta metaDev = dslContextDev.meta(conDev.getMetaData());
            Meta metaProd = dslContextProd.meta(conProd.getMetaData());

            String catalogName = conDev.getCatalog();

            System.out.println(metaDev.getCatalog(catalogName).schemaStream().flatMap(s -> s.tableStream()).collect(Collectors.toList()));
            System.out.println(metaDev.migrateTo(metaProd));  // error thrown here
```


**Stacktrace:**

`Exception in thread "main" org.jooq.exception.DataAccessException: Error while running MetaFunction
	at org.jooq.impl.MetaImpl.meta(MetaImpl.java:148)
	at org.jooq.impl.MetaImpl.access$100(MetaImpl.java:109)
	at org.jooq.impl.MetaImpl$MetaCatalog.getSchemas(MetaImpl.java:255)
	at org.jooq.impl.Diff$1.merge(Diff.java:123)
	at org.jooq.impl.Diff$1.merge(Diff.java:120)
	at org.jooq.impl.Diff.append(Diff.java:625)
	at org.jooq.impl.Diff.append(Diff.java:569)
	at org.jooq.impl.Diff.appendCatalogs(Diff.java:112)
	at org.jooq.impl.Diff.queries(Diff.java:108)
	at org.jooq.impl.AbstractMeta.migrateTo(AbstractMeta.java:350)
	at org.jooq.impl.AbstractMeta.migrateTo(AbstractMeta.java:345)
	at Main4.main(Main4.java:39)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Reference to database and/or server name in 'master.sys.schemas' is not supported in this version of SQL Server.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:254)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1608)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:578)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:508)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7240)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2869)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:243)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:218)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQueryInternal(SQLServerPreparedStatement.java:448)
	at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getSchemasInternal(SQLServerDatabaseMetaData.java:1275)
	at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getSchemas(SQLServerDatabaseMetaData.java:1285)
	at org.jooq.impl.MetaImpl$MetaCatalog$1.run(MetaImpl.java:262)
	at org.jooq.impl.MetaImpl.meta(MetaImpl.java:145)
	... 11 more`

**Comment by lukaseder** [comment]
I see. In jOOQ 3.14, there will be a `Meta.filterCatalog()` method that allows you to filter out some catalogs from all interactions with the `Meta` type: https://github.com/jOOQ/jOOQ/issues/10204. Unfortunately, that is not yet available in the free trial version.

I've noticed you're using a relatively old JDBC driver. Does the problem still persist with version `8.4.0.jre8`?
https://search.maven.org/artifact/com.microsoft.sqlserver/mssql-jdbc/8.4.0.jre8/jar

**Comment by arunkumargit** [comment]
I have updated JDBC driver to `8.4.0.jre8` and the issue still persists. 

Any workaround to make `migrateTo ` work? I'm actually trying to create a "diff" between two versions of my schema  by following this [link](https://www.jooq.org/doc/3.13/manual/sql-building/schema-diff/)

**Comment by lukaseder** [comment]
What version and/or distribution of SQL Server are you using? SQL Azure? This looks similar: https://github.com/dbeaver/dbeaver/issues/5258#issuecomment-500038510

A workaround could be to override jOOQ's `MetaProvider`: https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/Configuration.html#derive(org.jooq.MetaProvider) and override its `getCatalogs()` implementation to prevent the `migrateTo()` method (and others) from trying to iterate all the catalogs. Let me know if you need any help with that.

**Comment by arunkumargit** [comment]
I'm using `Microsoft SQL Azure (RTM) - 12.0.2000.8`.

**Comment by arunkumargit** [comment]
Sure, `MetaProvider ` worked for us. Thanks
