### ISSUE TITLE
Add parser support for the PostgreSQL CREATE INDEX .. ON .. USING syntax

### ISSUE THREAD

**Issue by anushreegupta44** [jOOQ/jOOQ#10497]
Expected Behaviour:
Should parse and create GIST index on code generation.

Actual Behaviour:

```
org.jooq.impl.ParserException: Unexpected token or missing query delimiter: [3:69] ...t exists location_shape_index on location (shape) [*]using gist;
        at org.jooq.impl.ParserContext.exception(ParserImpl.java:11128)
        at org.jooq.impl.ParserContext.done(ParserImpl.java:11248)
        at org.jooq.impl.ParserImpl.parse(ParserImpl.java:567)
        at org.jooq.impl.ParserImpl.parse(ParserImpl.java:546)
        at org.jooq.meta.extensions.ddl.DDLDatabase.load(DDLDatabase.java:170)
        at org.jooq.meta.extensions.ddl.DDLDatabase.access$000(DDLDatabase.java:86)
        at org.jooq.meta.extensions.ddl.DDLDatabase$2.load(DDLDatabase.java:155)
        at org.jooq.FilePattern.load0(FilePattern.java:297)
        at org.jooq.FilePattern.load(FilePattern.java:277)
        at org.jooq.FilePattern.load(FilePattern.java:290)
        at org.jooq.FilePattern.load(FilePattern.java:223)
        at org.jooq.meta.extensions.ddl.DDLDatabase.export(DDLDatabase.java:152)
        at org.jooq.meta.extensions.AbstractInterpretingDatabase.connection(AbstractInterpretingDatabase.java:100)
        at org.jooq.meta.extensions.AbstractInterpretingDatabase.create0(AbstractInterpretingDatabase.java:77)
        at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:274)
        at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:263)
        at org.jooq.meta.AbstractDatabase.setConnection(AbstractDatabase.java:253)
        at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:521)
        at org.jooq.codegen.GenerationTool.run(GenerationTool.java:222)
        at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:217)
        at org.jooq.codegen.GenerationTool.main(GenerationTool.java:189)
20:08:03.653 [main] ERROR org.jooq.codegen.GenerationTool - Cannot read /Users/ganu/xyz/P-DealerLocator/dealer-locator-service/build/tmp/generateSampleJooqSchemaSource/config.xml. Error : Error while exporting schema
org.jooq.exception.DataAccessException: Error while exporting schema
        at org.jooq.meta.extensions.AbstractInterpretingDatabase.connection(AbstractInterpretingDatabase.java:103)
        at org.jooq.meta.extensions.AbstractInterpretingDatabase.create0(AbstractInterpretingDatabase.java:77)
        at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:274)
        at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:263)
        at org.jooq.meta.AbstractDatabase.setConnection(AbstractDatabase.java:253)
        at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:521)
        at org.jooq.codegen.GenerationTool.run(GenerationTool.java:222)
        at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:217)
        at org.jooq.codegen.GenerationTool.main(GenerationTool.java:189)
Caused by: org.jooq.impl.ParserException: Unexpected token or missing query delimiter: [3:69] ...t exists location_shape_index on location (shape) [*]using gist;
        at org.jooq.impl.ParserContext.exception(ParserImpl.java:11128)
        at org.jooq.impl.ParserContext.done(ParserImpl.java:11248)
        at org.jooq.impl.ParserImpl.parse(ParserImpl.java:567)
        at org.jooq.impl.ParserImpl.parse(ParserImpl.java:546)
        at org.jooq.meta.extensions.ddl.DDLDatabase.load(DDLDatabase.java:170)
        at org.jooq.meta.extensions.ddl.DDLDatabase.access$000(DDLDatabase.java:86)
        at org.jooq.meta.extensions.ddl.DDLDatabase$2.load(DDLDatabase.java:155)
        at org.jooq.FilePattern.load0(FilePattern.java:297)
        at org.jooq.FilePattern.load(FilePattern.java:277)
        at org.jooq.FilePattern.load(FilePattern.java:290)
        at org.jooq.FilePattern.load(FilePattern.java:223)
        at org.jooq.meta.extensions.ddl.DDLDatabase.export(DDLDatabase.java:152)
        at org.jooq.meta.extensions.AbstractInterpretingDatabase.connection(AbstractInterpretingDatabase.java:100)
```

Steps to reproduce:

Could not generate code successfully with org.jooq.codegen.DefaultGenerator and org.jooq.meta.extensions.ddl.DDLDatabase on potgres/postgis using the following gradle code

```
jooq {
    version = '3.13.4'
    edition = 'OSS'
    generateSchemaSourceOnCompilation = true
    sample(sourceSets.main) {
        generator {
            name = 'org.jooq.codegen.DefaultGenerator'
            strategy {
                name = 'org.jooq.codegen.DefaultGeneratorStrategy'
            }
            database {
                name = 'org.jooq.meta.extensions.ddl.DDLDatabase'
                inputSchema = 'PUBLIC'
                properties {
                    property {
                        key = 'scripts'
                        value = 'src/main/resources/db/migration'
                    }

                }
                forcedTypes {
                    forcedType {
                        includeExpression = '.*SHAPE.*'
                        includeTypes = '.*'
                        userType = 'org.postgis.PGgeometry'
                        binding = 'com.xyz.digital.dealerlocator.repository.binding.GeometryBinding'
                    }
                }
            }
            generate {
                relations = true
                deprecated = false
                records = true
                immutablePojos = true
                fluentSetters = true
            }
            target {
                packageName = 'com.xyz.digital.dealerlocator.domain'
            }
        }
    }
}
```

### Versions:

- jOOQ: 3.13.4
- Java: 11
- Database (include vendor): psql (PostgreSQL) 11.2 (Debian 11.2-1.pgdg90+1) - mdillon/postgis image - Postgresql with postgis extension
- OS: 
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.2.12

**Comment by lukaseder** [comment]
Thanks for your report.

We could easily parse and ignore the `USING` clause. Just to be sure, according to the documentation, the syntax would be:

```sql
-- Correct, according to docs
create index i if not exists location_shape_index on location using gist (shape);

-- Wrong, or using an undocumented syntax according to docs
create index i if not exists location_shape_index on location (shape) using gist;
```

Can be reproduced like this:

```sql
create table t (i int);
-- Works
create index i on t using btree (i);
-- Doesn't work
create index i on t (i) using btree;
```

**Comment by lukaseder** [comment]
We already support MySQL's syntax:

```sql
create index i using btree on t (i);
```

**Comment by anushreegupta44** [comment]
The issue is with **gist** index of postgis. Other index types are getting parsed.

**Comment by lukaseder** [comment]
Indeed, I've just noticed, too. Currently, we're parsing only `btree` and `hash`, we should parse any identifier with this clause.
