### ISSUE TITLE
Postgresql timestamp values +-infinity fail to parse

### ISSUE THREAD

**Issue by F1rst-Unicorn** [jOOQ/jOOQ#10517]
### Expected behavior and actual behavior:

Timestamp values `infinity` or `-infinity` should map to a reasonable value in Java, e.g. `OffsetDateTime.MAX` when fetching them from the database.

Instead jooq fails when parsing the string as `LocalDate`:

```
org.jooq.exception.DataAccessException: SQL [select "public"."User"."ID", "public"."User"."name", "public"."User"."version", "public"."User"."valid_time_start", "public"."User"."valid_time_end", "public"."User"."transaction_time_start", "public"."User"."transaction_time_end" from "public"."User" where 1 = 1]; Error while reading field: "public"."User"."valid_time_end", at JDBC index: 5

	at org.jooq_3.13.4.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2753)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:755)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1630)
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1581)
	at java.util.Iterator.forEachRemaining(Iterator.java:115)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:272)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at de.njsm.stocks.server.v2.db.Test.test(Test.java:44)
Caused by: java.sql.SQLException: Error while reading field: "public"."User"."valid_time_end", at JDBC index: 5
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1735)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.operate(CursorImpl.java:1685)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.operate(CursorImpl.java:1650)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:130)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1614)
	... 42 more
Caused by: java.lang.IllegalArgumentException: Expected '-' at position 0 in infinity
	at org.jooq.impl.DefaultBinding$OffsetDateTimeParser.parseChar(DefaultBinding.java:2712)
	at org.jooq.impl.DefaultBinding$OffsetDateTimeParser.parseLocalDate(DefaultBinding.java:2612)
	at org.jooq.impl.DefaultBinding$OffsetDateTimeParser.offsetDateTime(DefaultBinding.java:2593)
	at org.jooq.impl.DefaultBinding$DefaultOffsetDateTimeBinding.get0(DefaultBinding.java:2815)
	at org.jooq.impl.DefaultBinding$DefaultOffsetDateTimeBinding.get0(DefaultBinding.java:2742)
	at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:837)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1725)
	... 46 more
```

### Steps to reproduce the problem

Have a table with infinity in it, e.g.

```sql
create table test (
    value timestamp(6) with time zone
);
insert into test (value) values ('infinity');
```

Generate jooq code and try to fetch them:
```Java
context
                    .selectFrom(TEST)
                    .stream()
                    .forEach(v -> v.toString());
```
AFAICT jooq fetches the value as string and tries to parse it without special-casing the infinity value.

I am aware of #7126 which states that this has been solved before. So maybe I'm just doing a stupid mistake.

### Versions:

- jOOQ: 3.13.4
- Java: OpenJDK 1.8.0_262
- Database (include vendor): Postgresql 12.3
- OS: Arch Linux
- JDBC Driver: org.postgresql 42.2.10

**Comment by lukaseder** [comment]
Thanks a lot for your report. It looks like some oversight in https://github.com/jOOQ/jOOQ/issues/7126, which allows for bypassing the logic implemented in https://github.com/jOOQ/jOOQ/issues/7126

**Comment by mschout** [comment]
Is there a workaround here meanwhile that doesn't involve blowing up when jooq encounters infinity?

**Comment by F1rst-Unicorn** [comment]
I wrote a custom binding for OffsetDateTime which handles infinity correctly and works for all my needs. See https://github.com/F1rst-Unicorn/stocks/blob/master/server/src/main/java/org/jooq/impl/OffsetDateTimeBinding.java

**Comment by lukaseder** [comment]
I'm not convinced that jOOQ should arbitrarily map well defined concepts (within PG) like `infinity` to some arbitrary values like `MAX`, out of the box. Take this example in PostgreSQL:

```sql
select 'infinity'::timestamp - interval '1 day'
```

It returns `infinity` (because what else). This isn't the case for `MAX`:

```
jshell> OffsetDateTime.MAX.minusDays(1)
$2 ==> +999999999-12-30T23:59:59.999999999-18:00
```

I mean, it does appear to be a "clever" mapping at first, but let's not forget all the criticism of MySQL's `0000-00-00 00:00:00` timestamp, which is a terrible thing. Making `MAX` something special, because *"some"* Java library said so is equally terrible, in my opinion.

Note, it is different with `Double`, which has

```
jshell> Double.POSITIVE_INFINITY + 1.0
$4 ==> Infinity
```

The magic values are well defined in IEEE 754:

- https://en.wikipedia.org/wiki/IEEE_754-1985#Positive_and_negative_infinity

Which is equally weird, but it has been standardised and most systems agree on this.

If jOOQ is ever going to support these special values out of the box, we'd need yet another jOOQ specific wrapper type, just like the `JSON`, `JSONB`, `XML`, `Interval` types...

**Comment by lukaseder** [comment]
To be clear, it is a different thing if users define their own `Binding` that implements *their* convention. But for a library like jOOQ to impose such a convention is tough. There will be tons of edge cases, bugs, oversights, etc.

**Comment by F1rst-Unicorn** [comment]
I recognize your concerns to do such a mapping in a general-purpose library. I'm completely fine to have the bug rejected on that ground, given I have previously mentioned workaround. Just one more point: The Postgres JDBC driver, when required, maps infinity to a different special date value based on https://jdbc.postgresql.org/documentation/publicapi/org/postgresql/PGStatement.html#DATE_POSITIVE_INFINITY
So maybe the decision you want to avoid has already been made by them.

**Comment by lukaseder** [comment]
> I recognize your concerns to do such a mapping in a general-purpose library. I'm completely fine to have the bug rejected on that ground, given I have previously mentioned workaround. 

I'll keep it open. From experience, eventually, new options appear with time. How's the saying? Good things come to those who wait.

> Just one more point: The Postgres JDBC driver, when required, maps infinity to a different special date value based on https://jdbc.postgresql.org/documentation/publicapi/org/postgresql/PGStatement.html#DATE_POSITIVE_INFINITY

Great to know, thanks for sharing!

> So maybe the decision you want to avoid has already been made by them.

No, they made it worse! There are now several infinities!
https://github.com/pgjdbc/pgjdbc/blob/master/pgjdbc/src/main/java/org/postgresql/PGStatement.java#L21
