### ISSUE TITLE
org.jooq.impl.ParserException: Keyword 'SELECT' expected: [2:1] CREATE OR REPLACE VIEW

### ISSUE THREAD

**Issue by antoniogomezalvarado** [jOOQ/jOOQ#10584]
Hi, i'm running a `CREATE OR REPLACE VIEW` statement against my postgresql db - and it works. This is the full statement:

```
CREATE OR REPLACE VIEW myview as
WITH calculated as (
    SELECT *, row_number() OVER (PARTITION BY id ORDER BY row_added_timestamp_in_seconds DESC) as rn
    FROM mytable
  ),
 second_calculated as (
    SELECT * FROM calculated
    WHERE rn = 1
    AND EXTRACT (EPOCH FROM now()) BETWEEN start_timestamp_in_seconds AND expire_timestamp_in_seconds
  )
SELECT * FROM second_calculated;
```
However, it seems JOOQ can't parse it since i'm getting this exception:
```
14:06:28.586 [ERROR] [org.jooq.meta.extensions.ddl.DDLDatabase] DDLDatabase Error        : Your SQL string could not be parsed or simulated. This may have a variety of reasons, including:
- The jOOQ parser doesn't understand your SQL
- The jOOQ DDL simulation logic (translating to H2) cannot simulate your SQL

If you think this is a bug or a feature worth requesting, please report it here: https://github.com/jOOQ/jOOQ/issues/new/choose

As a workaround, you can use the Settings.parseIgnoreComments syntax documented here:
https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/settings-parser/
14:06:28.586 [ERROR] [org.jooq.meta.extensions.ddl.DDLDatabase] An exception occurred while parsing script source : roadview/src/main/resources/db/**/*.sql. Please report this error to https://github.com/jOOQ/jOOQ/issues/new
org.jooq.impl.ParserException: Keyword 'SELECT' expected: [2:1] CREATE OR REPLACE VIEW active_policies as
[*]WITH policies_with_row_number as (
    SELECT *, row_number() OVER (PARTITION BY...
        at org.jooq.impl.ParserContext.expected(ParserImpl.java:10649)
        at org.jooq.impl.ParserImpl.parseKeyword(ParserImpl.java:10171)
        at org.jooq.impl.ParserImpl.parseQueryPrimary(ParserImpl.java:1219)
        at org.jooq.impl.ParserImpl.parseQueryTerm(ParserImpl.java:1185)
        at org.jooq.impl.ParserImpl.parseQueryExpressionBody(ParserImpl.java:1156)
        at org.jooq.impl.ParserImpl.parseSelect(ParserImpl.java:1024)
        at org.jooq.impl.ParserImpl.parseSelect(ParserImpl.java:1016)
        at org.jooq.impl.ParserImpl.parseCreateView(ParserImpl.java:2935)
        at org.jooq.impl.ParserImpl.parseCreate(ParserImpl.java:2160)
        at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:844)
        at org.jooq.impl.ParserImpl.parse(ParserImpl.java:542)
        at org.jooq.impl.ParserImpl.parse(ParserImpl.java:529)
        at org.jooq.meta.extensions.ddl.DDLDatabase.load(DDLDatabase.java:188)
        at org.jooq.meta.extensions.ddl.DDLDatabase.access$100(DDLDatabase.java:91)
        at org.jooq.meta.extensions.ddl.DDLDatabase$2.load(DDLDatabase.java:169)
        at org.jooq.meta.tools.FilePattern.load(FilePattern.java:165)
        at org.jooq.meta.tools.FilePattern.load(FilePattern.java:178)
        at org.jooq.meta.tools.FilePattern.load(FilePattern.java:178)
        at org.jooq.meta.tools.FilePattern.load(FilePattern.java:138)
```

Using the following package versions:
```
        classpath 'org.jooq:jooq-codegen:3.12.3'
        classpath 'org.postgresql:postgresql:42.2.10'
        classpath 'org.jooq:jooq:3.12.3'
        classpath 'org.jooq:jooq-meta:3.12.3'
        classpath group: 'org.jooq', name: 'jooq-meta-extensions', version: '3.12.3'
```
Any idea why this is happening?
Thanks!

**Comment by lukaseder** [comment]
Thanks for your report. This parses just fine with jOOQ 3.13.4 or 3.14.0, see https://github.com/jOOQ/jOOQ/issues/9545
