### ISSUE TITLE
Error when mocking Oracle routines that have VARRAY or TABLE parameters

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10718]
The following integration test fails:

```java
@Test
public void testOracleMockProceduresWithArrayOutParameters() throws Exception {
    UBookTableRecord expected = new UBookTableRecord(new UBookTypeRecord(2, "B"));

    Configuration c = new DefaultConfiguration().set(SQLDialect.ORACLE).set(new MockConnection(Mock.of(
        create().newRecord(field("OUT_TABLE", PTables4.OUT_TABLE.getDataType())).values(expected)
    )));

    UBookTableRecord actual = Routines.pTables4(c, new UBookTableRecord(new UBookTypeRecord(1, "A")));
    assertEquals(expected, actual);
}
```

With this error:

```
org.jooq.exception.DataAccessException: SQL [null]; Error while writing value at JDBC bind index: 1
	at org.jooq_3.14.0-SNAPSHOT.ORACLE.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2890)
	at org.jooq.impl.AbstractBindContext.bindValue(AbstractBindContext.java:127)
	at org.jooq.impl.ArrayConstant.bind0(ArrayConstant.java:155)
	at org.jooq.impl.ArrayConstant.accept(ArrayConstant.java:90)
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:279)
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:88)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:270)
	at org.jooq.impl.AbstractRoutine.bind1(AbstractRoutine.java:680)
	at org.jooq.impl.AbstractRoutine.bind0(AbstractRoutine.java:642)
	at org.jooq.impl.AbstractRoutine.accept(AbstractRoutine.java:582)
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:279)
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:88)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:270)
	at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:519)
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:369)
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:346)
	at org.jooq.test.oracle.generatedclasses.test.Routines.pTables4(Routines.java:1756)
	at org.jooq.test.OracleTest.testOracleMockProceduresWithArrayOutParameters(OracleTest.java:4436)
Caused by: java.sql.SQLException: Error while writing value at JDBC bind index: 1
	at org.jooq.impl.DefaultBindContext.bindValue0(DefaultBindContext.java:67)
	at org.jooq.impl.AbstractBindContext.bindValue(AbstractBindContext.java:124)
	... 47 more
Caused by: org.jooq.tools.reflect.ReflectException: java.lang.NoSuchMethodException: No similar method createARRAY with params [class java.lang.String, class [Ljava.lang.Object;] could be found on type class org.jooq.tools.jdbc.MockConnection.
	at org.jooq.tools.reflect.Reflect.call(Reflect.java:585)
	at org.jooq.impl.DefaultBinding$DefaultArrayRecordBinding.createOracleARRAY(DefaultBinding.java:1381)
	at org.jooq.impl.DefaultBinding$DefaultArrayRecordBinding.set0(DefaultBinding.java:1287)
	at org.jooq.impl.DefaultBinding$DefaultArrayRecordBinding.set0(DefaultBinding.java:1)
	at org.jooq.impl.DefaultBinding$AbstractBinding.set(DefaultBinding.java:848)
	at org.jooq.impl.DefaultBindContext.bindValue0(DefaultBindContext.java:62)
	... 48 more
Caused by: java.lang.NoSuchMethodException: No similar method createARRAY with params [class java.lang.String, class [Ljava.lang.Object;] could be found on type class org.jooq.tools.jdbc.MockConnection.
	at org.jooq.tools.reflect.Reflect.similarMethod(Reflect.java:652)
	at org.jooq.tools.reflect.Reflect.call(Reflect.java:582)
	... 53 more
```

----
Related: https://github.com/jOOQ/jOOQ/issues/10704

**Comment by lukaseder** [comment]
A more generic issue has been created here: https://github.com/jOOQ/jOOQ/issues/10719.

This issue here might be easy to fix and backport. The other may not be.

**Comment by lukaseder** [comment]
Fix implemented through commit https://github.com/jOOQ/jOOQ/commit/6898989f8431961781df268a02f63f6086fd7089 in #10719
