### ISSUE TITLE
Generated DAO tries to use INSERT...RETURNING on unsupported MariaDB version

### ISSUE THREAD

**Issue by sargue** [jOOQ/jOOQ#10892]
MariaDB has introduced INSERT...RETURNING support on version 10.5 (https://mariadb.com/kb/en/insertreturning/).

The generated DAO tries to use it over a MariaDB 10.3 instance, thus failing.

### Expected behavior

The generated DAO should not try to use the feature on MariaDB 10.5

### Actual behavior

Code is generated fine but when I try to insert a new record using generated DAO and POJO, with the PK set to null I get this error:

```
org.jooq.exception.DataAccessException: 
SQL [insert into `mail` (`message_id`, `mailgun_delivery_message`, `remitent`, `assumpte`, `enviat`, `origen`, `revisar`) 
values (?, ?, ?, ?, ?, ?, ?) returning `id`]; (conn=293) 
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server 
version for the right syntax to use near 'returning `id`' at line 1
```

See full stack traces at the end of the message.

If I just switch to jOOQ 3.13.6 on my build gradle config it just works, no other change required.

### Steps to reproduce the problem

I have this table on the database:

```
create table mail
(
	id int auto_increment primary key,
	message_id varchar(800) not null,
	mailgun_delivery_message varchar(800) not null,
	remitent varchar(800) not null,
	assumpte varchar(800) not null,
	enviat datetime not null,
	origen varchar(10) not null,
	revisar tinyint(1) not null
);
```

The failing line of my code is just:

```
Mail mail = new Mail(null, ... non null rest of columns ...);
new MailDao(ctx).insert(mail);
```

Mail is the generated POJO. MailDao is the generated DAO. Keep in mind that there is a MailDAO (notice the caps) in the stacktraces that is another different class not generated, just wrote by me, which encapsulates the access and has the above code. The code later fetches the Mail record id just by querying `mail.getId()`.

### Versions

- jOOQ: 3.14.1
- Java: AdoptOpenJDK 11.0.6+10
- Database (include vendor): MariaDB 10.3.25 (Debian stable)
- OS: Debian stable for database, Windows 10 for Java code / IDE
- JDBC Driver (include name if inofficial driver): 
For code generation: org.mariadb.jdbc:mariadb-java-client:2.4.4
Runtime library when running the code: 2.3.0

I use gradle to build the project and generate the code. I use the nu.studer.jooq plugin, version 5.2 over gradle 6.7.

Full stacktraces:

```
javax.ws.rs.ProcessingException: org.jooq.exception.DataAccessException: SQL [insert into `mail` (`message_id`, `mailgun_delivery_message`, `remitent`, `assumpte`, `enviat`, `origen`, `revisar`) values (?, ?, ?, ?, ?, ?, ?) returning `id`]; (conn=293) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'returning `id`' at line 1
	at org.glassfish.jersey.client.ClientRuntime.processFailure(ClientRuntime.java:247)
	at org.glassfish.jersey.client.ClientRuntime.processFailure(ClientRuntime.java:242)
	at org.glassfish.jersey.client.ClientRuntime.access$100(ClientRuntime.java:62)
	at org.glassfish.jersey.client.ClientRuntime$2.lambda$failure$1(ClientRuntime.java:178)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:288)
	at org.glassfish.jersey.client.ClientRuntime$2.failure(ClientRuntime.java:178)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:273)
	at org.glassfish.jersey.client.ClientRuntime.lambda$null$6(ClientRuntime.java:182)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:288)
	at org.glassfish.jersey.client.ClientRuntime.lambda$createRunnableForAsyncProcessing$7(ClientRuntime.java:156)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.jooq.exception.DataAccessException: SQL [insert into `mail` (`message_id`, `mailgun_delivery_message`, `remitent`, `assumpte`, `enviat`, `origen`, `revisar`) values (?, ?, ?, ?, ?, ?, ?) returning `id`]; (conn=293) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'returning `id`' at line 1
	at org.jooq_3.14.1.MARIADB.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2898)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:757)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:389)
	at org.jooq.impl.TableRecordImpl.storeInsert0(TableRecordImpl.java:218)
	at org.jooq.impl.TableRecordImpl$1.operate(TableRecordImpl.java:183)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:131)
	at org.jooq.impl.TableRecordImpl.storeInsert(TableRecordImpl.java:179)
	at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:167)
	at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:162)
	at org.jooq.impl.DAOImpl.insert(DAOImpl.java:179)
	at org.jooq.impl.DAOImpl.insert(DAOImpl.java:155)
	at net.sargue.alcodos.server.persistencia.MailDAO.insert(MailDAO.java:177)
	at net.sargue.alcodos.server.persistencia.MailDAO.lambda$insert$4(MailDAO.java:173)
	at org.jooq.impl.DefaultDSLContext$3.run(DefaultDSLContext.java:615)
	at org.jooq.impl.DefaultDSLContext$3.run(DefaultDSLContext.java:612)
	at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$0(DefaultDSLContext.java:543)
	at org.jooq.impl.Tools$34$1.block(Tools.java:5209)
	at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
	at org.jooq.impl.Tools$34.get(Tools.java:5206)
	at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:595)
	at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:512)
	at org.jooq.impl.DefaultDSLContext.transaction(DefaultDSLContext.java:612)
	at net.sargue.alcodos.server.persistencia.MailDAO.insert(MailDAO.java:173)
	at net.sargue.alcodos.server.correu.Callback.completed(Callback.java:39)
	at net.sargue.mailgun.Mail$1.completed(Mail.java:99)
	at net.sargue.mailgun.Mail$1.completed(Mail.java:96)
	at org.glassfish.jersey.client.JerseyInvocation$1.completed(JerseyInvocation.java:814)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:229)
	at org.glassfish.jersey.client.ClientRuntime.access$200(ClientRuntime.java:62)
	at org.glassfish.jersey.client.ClientRuntime$2.lambda$response$0(ClientRuntime.java:173)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:288)
	at org.glassfish.jersey.client.ClientRuntime$2.response(ClientRuntime.java:173)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:269)
	... 13 common frames omitted
Caused by: java.sql.SQLSyntaxErrorException: (conn=293) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'returning `id`' at line 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:236)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:165)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:232)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeQuery(MariaDbPreparedStatementClient.java:174)
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122)
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.executeQuery(DefaultPreparedStatement.java:99)
	at org.jooq.impl.AbstractDMLQuery.executeReturningQuery(AbstractDMLQuery.java:1225)
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:1034)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:375)
	... 48 common frames omitted
```

**Comment by lukaseder** [comment]
Thank you very much for your support request.

Please use the `SQLDialect.MARIADB_10_3` dialect

**Comment by lukaseder** [comment]
See also: https://github.com/jOOQ/jOOQ/issues/10799

**Comment by sargue** [comment]
I see. Thanks for your answer and sorry that I didn't found the previous issue (I searched but somehow managed to miss that).

It worries me that jOOQ is supporting less and less OSS variants so it makes the OSS version mostly unusable. For example, Debian stable uses 10.3 and the latest Ubuntu versions package 10.3 and 10.1. With the above matrix you cannot use any jOOQ OSS. You can only use 10.0 or 10.5.

Or am I missing something on that matrix?

**Comment by sargue** [comment]
Oh, I see now, it's a minimum version, not a strict required version. Unless there's some incompatible change in the DB engine itself, which is unlikely.

**Comment by lukaseder** [comment]
> Oh, I see now, it's a minimum version, not a strict required version. Unless there's some incompatible change in the DB engine itself, which is unlikely.

It's the version we use for integration testing the jOOQ Open Source Edition, and the minimum version that we guarantee the jOOQ Open Source Edition works on. E.g. if you find a bug in jOOQ 3.14 with MariaDB 10.6, we'll try to get that fixed, if possible.

I'll fix that right away on the website, to make it more clear.

**Comment by arekqq** [comment]
Walkaround for those ones which use OpenSource Edition and don't want to upgrade MariaDB version
There is a flag in configuration responsible for generating returning statement `returnIdentityOnUpdatableRecord`
There where you specify SQLDialect, you cant set this flag to false
In my case it looks like this:
`DefaultConfiguration jooqConfiguration = new DefaultConfiguration();`
`jooqConfiguration.set(SQLDialect.MARIADB);`
`jooqConfiguration.settings().setReturnIdentityOnUpdatableRecord(false);`
