### ISSUE TITLE
java.lang.ClassCastException: class java.lang.Class cannot be cast to class java.lang.reflect.ParameterizedType when custom data type extends List

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10910]
Create a table in PostgreSQL:

```sql
CREATE TABLE mcve.test_table_1
(
    column1 integer[] NOT NULL
);
```

Create this kotlin code:

```kotlin
package org.jooq.mcve

import org.jooq.Converter

interface IThing : List<String>
class Thing(val items: List<String>) : IThing, List<String> by items
class IntArrayIThingConverter : Converter<Array<Int>, IThing> {
    override fun from(databaseObject: Array<Int>?): IThing? =
            databaseObject?.let { Thing(it.map { it.toString() }) }

    override fun to(userObject: IThing?): Array<Int>? =
            userObject?.map { it.toInt() }?.toTypedArray()

    override fun fromType(): Class<Array<Int>> =
            Array<Int>::class.java

    override fun toType(): Class<IThing> =
            IThing::class.java
}
```

Attach the converter using a forced type:

```xml
<forcedTypes>
    <forcedType>
        <userType>org.jooq.mcve.IThing</userType>
        <converter>org.jooq.mcve.IntArrayIThingConverter</converter>
        <includeExpression>.*\..*column1.*</includeExpression>
    </forcedType>
</forcedTypes>
```

And then run this test:

```kotlin
package org.jooq.mcve.test.kotlin

import org.jooq.impl.DSL.value
import org.jooq.mcve.IThing
import org.jooq.mcve.Thing
import org.jooq.mcve.kotlin.tables.references.*
import org.jooq.mcve.kotlin.tables.pojos.*
import org.jooq.mcve.test.java.AbstractTest
import org.junit.Assert.assertEquals
import org.junit.Test

class KotlinTest : AbstractTest() {

    @Test
    fun mcveTest() {
        ctx.delete(TEST_TABLE_1).execute();
        ctx.insertInto(TEST_TABLE_1).columns(TEST_TABLE_1.COLUMN1).values(value(Thing(listOf("1", "2")) as IThing, TEST_TABLE_1.COLUMN1.dataType)).execute()
        assertEquals(
                listOf("1", "2"),
                ctx.selectFrom(TEST_TABLE_1).fetchInto(TestTable_1::class.java)[0].column1
        )
    }
}
```

This produces the following ClassCastException:

```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.008 sec <<< FAILURE!
mcveTest(org.jooq.mcve.test.kotlin.KotlinTest)  Time elapsed: 0.95 sec  <<< ERROR!
org.jooq.exception.MappingException: An error ocurred when mapping record to class org.jooq.mcve.kotlin.tables.pojos.TestTable_1
        at org.jooq.impl.DefaultRecordMapper$MutablePOJOMapper.map(DefaultRecordMapper.java:877)
        at org.jooq.impl.DefaultRecordMapper.map(DefaultRecordMapper.java:543)
        at org.jooq.impl.ResultImpl.into(ResultImpl.java:1285)
        at org.jooq.impl.AbstractResultQuery.fetchInto(AbstractResultQuery.java:1545)
        at org.jooq.impl.SelectImpl.fetchInto(SelectImpl.java:3936)
        at org.jooq.mcve.test.kotlin.KotlinTest.mcveTest(KotlinTest.kt:20)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.ClassCastException: class java.lang.Class cannot be cast to class java.lang.reflect.ParameterizedType (java.lang.Class and java.lang.reflect.ParameterizedType are in module java.base of loader 'bootstrap')
        at org.jooq.impl.DefaultRecordMapper$MutablePOJOMapper.map(DefaultRecordMapper.java:909)
        at org.jooq.impl.DefaultRecordMapper$MutablePOJOMapper.map(DefaultRecordMapper.java:829)
        ... 39 more
```

----

This MCVE helps reproduce the issue:
https://github.com/lukaseder/jOOQ-mcve/tree/1FOcoG5G9BU

See also:
https://groups.google.com/g/jooq-user/c/1FOcoG5G9BU

**Comment by lukaseder** [comment]
This use-case conflicts with a fix made some time ago #3082. We wanted to be able to map between `T[]` and `List<T>` in `DefaultRecordMapper`. Now, if a user decides to implement a custom type extending `List<?>`, and attaches a converter (or binding) to their data type, then the fix in #3082 should not apply.

**Comment by lukaseder** [comment]
In fact, this isn't strictly about having custom converters. The logic is simply wrong:

```java
if (value instanceof Collection && List.class.isAssignableFrom(mType)) {
    Class componentType = (Class) ((ParameterizedType) method.getGenericParameterTypes()[0]).getActualTypeArguments()[0];
    method.invoke(result, Convert.convert((Collection) value, componentType));
}
```

We're assuming the target type is of type `List`, but if an explicit custom `List` type is given, we don't know how to convert the source collection to it.

So, we should do this only if the target type is `List` or `ArrayList`, not a subtype thereof.

**Comment by lukaseder** [comment]
This actually isn't kotlin specific. It could have happened with Java as well. Also, the array type isn't really needed. Any data type that converts to the user-defined `List` type with the user-defined converter would have worked.

**Comment by lukaseder** [comment]
Fixed in 3.15.0 and 3.14.4 (#10911)

**Comment by mel4tonin4** [comment]
Thanks, Lukas!

**Comment by lukaseder** [comment]
A recent change related to https://github.com/jOOQ/jOOQ/issues/9288, https://github.com/jOOQ/jOOQ/issues/11893 has brought a regression in this area here, affecting jOOQ 3.15.0-SNAPSHOT only. I'll investigate whether it's an actual regression, or whether this fix here was implemented at the wrong spot.

It seems that `RecordMapperProvider` and `ConverterProvider` have conflicting interests in `into(Class)` calls.

**Comment by lukaseder** [comment]
It's not strictly a regression, just a new execution path, which helped surface this bug here: https://github.com/jOOQ/jOOQ/issues/11897
