### ISSUE TITLE
Parser cannot look up column from tables by same name from different schemas

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11000]
Given a database like this:

```sql
create table a.t (i int);
create table b.t (j int);
```

The following statement:

```sql
select i, j from a.t, b.t
```

Fails to parse with this error:

```
org.jooq.impl.ParserException: Unknown field identifier: [1:9] select i[*], j from a.t, b.t
	at org.jooq.impl.ParserContext.exception(ParserImpl.java:12274)
	at org.jooq.impl.ParserContext.unknownField(ParserImpl.java:12529)
	at org.jooq.impl.ParserContext.scopeEnd(ParserImpl.java:12514)
	at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:1042)
	at org.jooq.impl.ParserImpl.parseSelect(ParserImpl.java:735)
	at org.jooq.impl.ParserImpl.parseSelect(ParserImpl.java:729)
	at org.jooq.impl.ParserMetaTest.testUnqualifiedFieldFromTableList(ParserMetaTest.java:454)
```

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.15.0 and 3.14.4 (#11001)
