### ISSUE TITLE
Code generator(3.14.x) fails using PostgresDatabase.java in CockroachDB

### ISSUE THREAD

**Issue by giger85** [jOOQ/jOOQ#11027]
### Expected behavior
- java code generation produces java class files.
### Actual behavior
Using 3.13.4 version, java code generation works for me.
After using 3.14.3 version(lastest), java code generation fails with following error message.
```
Caused by: org.postgresql.util.PSQLException: ERROR: unknown function: information_schema._pg_char_max_length()
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
```
Related sql is below.
```sql
with recursive domains(domain_id, base_id, typbasetype, src) as (
  select
    d.oid,
    d.oid,
    d.typbasetype,
    case
      when c.oid is not null then array[pg_get_constraintdef(c.oid)]
    end
  from pg_catalog.pg_type as d
    join pg_catalog.pg_namespace as n
      on n.oid = d.typnamespace
    left outer join pg_catalog.pg_constraint as c
      on d.oid = c.contypid
  where (
    d.typtype = 'd'
    and n.nspname in ('public')
  )
  union all
  select
    domains.domain_id,
    d.oid,
    d.typbasetype,
    case
      when c.conbin is null then domains.src
      else array_append(
        domains.src,
        pg_get_constraintdef(c.oid)
      )
    end
  from domains
    join pg_catalog.pg_type as d
      on domains.typbasetype = d.oid
    left outer join pg_catalog.pg_constraint as c
      on d.oid = c.contypid
)
select
  n.nspname,
  d.typname,
  d.typnotnull,
  d.typdefault,
  b.typname,
  information_schema._pg_char_max_length(d.typbasetype, d.typtypmod) as character_maximum_length,
  information_schema._pg_numeric_precision(d.typbasetype, d.typtypmod) as numeric_precision,
  information_schema._pg_numeric_scale(d.typbasetype, d.typtypmod) as numeric_scale,
  domains.src
from pg_catalog.pg_type as d
  join domains
    on (
      domains.typbasetype = 0
      and domains.domain_id = d.oid
    )
  join pg_catalog.pg_type as b
    on domains.base_id = b.oid
  join pg_catalog.pg_namespace as n
    on n.oid = d.typnamespace
where (
  d.typtype = 'd'
  and n.nspname in ('public')
)
order by
  n.nspname,
  d.typname
```

### Steps to reproduce the problem
- code generation config is below.
```kotlin
jooq {
  version.set("3.14.3")
  configurations {
    create("main") {
      jooqConfiguration.apply {
        logging = org.jooq.meta.jaxb.Logging.DEBUG
        jdbc.apply {
          driver = "org.testcontainers.jdbc.ContainerDatabaseDriver"
          url = "jdbc:tc:cockroach:v20.1.8:///postgres?TC_INITSCRIPT=file:src/main/resources/schema-postgres.sql"
          user = "root"
        }
        generator.apply {
          database.apply {
            name = "org.jooq.meta.postgres.PostgresDatabase"
            inputSchema = "public"
            includes = ".*"
            generate.apply {
              isJavaTimeTypes = true
              isKeys = false
            }
            target.apply {
              packageName = "com.demo.entity"
              directory = "build/generated/sources/jooq"
            }
          }
        }
      }
    }
  }
}
```
### Versions

- jOOQ: 3.14.3
- Java: 11.0.9
- Database (include vendor): CorkaochDB v20.1.8
- OS: Mac 10.15.7
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.2.14

**Comment by lukaseder** [comment]
This seems to work for me with

```
name = "org.jooq.meta.cockroachdb.CockroachDBDatabase"
```

Any error in the code generator resulting from failing queries is usually cosmetic if you don't rely on the feature that produces the query. In this case, since CockroachDB doesn't support `DOMAIN` types yet (https://github.com/cockroachdb/cockroach/issues/27796), the query just fails and the failure can be ignored using the `onError` configuration.

Of course, I still recommend using `CockroachDBDatabase` to have a fully supported integration also in the future.

**Comment by giger85** [comment]
@lukaseder 
Thanks for your help.
