### ISSUE TITLE
Non-deterministic BadSqlGrammarException

### ISSUE THREAD

**Issue by pawelhulek** [jOOQ/jOOQ#11040]
### Expected behavior
Deterministic behavior. Either fail or work fine.
### Actual behavior
We are receiving the below exception or similar but for other queries in a non-deterministic way. 
By non-deterministic, I mean that after JVM restart it can be thrown for all requests or none.

```
org.springframework.jdbc.BadSqlGrammarException: jOOQ; bad SQL grammar [select "event"."id", "event"."retried", "event"."status", "event"."version", "event"."lastupdated", "event"."created", "event"."event_msg" from "event" where ("event"."status" = ? or ("event"."lastupdated" < ? and "event"."status" = ?)) order by "event"."created" limit ?]; nested exception is org.postgresql.util.PSQLException: ERROR: operator does not exist: timestamp with time zone < character varying
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 294
	at org.jooq_3.13.5.DEFAULT.debug(Unknown Source)
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:101)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.translate(JooqExceptionTranslator.java:92)
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.handle(JooqExceptionTranslator.java:81)
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.exception(JooqExceptionTranslator.java:55)
	at org.jooq.impl.ExecuteListeners.exception(ExecuteListeners.java:274)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:386)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:354)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:1565)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:3761)
	
Caused by: org.postgresql.util.PSQLException: ERROR: operator does not exist: timestamp with time zone < character varying
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 294
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:153)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:3992)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:295)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:371)
	... 18 common frames omitted
```

After enabling org.jooq.tools.LoggerListener we can see the following queries generated:

``` 
-> with bind values      : select "event"."id", "event"."retried", "event"."status", "event"."version", "event"."lastupdated", "event"."created", "event"."event_msg" from "event" where ("event"."status" = 'PENDING' or ("event"."lastupdated" < timestamp with time zone '2020-11-25 12:59:51.009977+00:00' and "event"."status" = 'IN_PROGRESS')) order by "event"."created" limit 75`
It looks correct.
```

Table DDL is:

```sql
create table event
(
    id          varchar(255)             not null
        constraint "eventPK"
            primary key,
    retried     integer                  not null,
    status      varchar(255)             not null,
    version     bigint                   not null,
    lastupdated timestamp with time zone not null,
    created     timestamp with time zone not null,
    event_msg       "jsonb"                  not null
);
``` 

We are using DSL. The code looks like this:

```java
context
        .selectFrom(Event.EVENT)
        .where(Event.EVENT.STATUS.eq(of(PENDING))
        .or(Event.EVENT.LASTUPDATED
                .lessThan(OffsetDateTime.ofInstant(Instant.now().minus(Duration.ofMinutes(3)), ZoneOffset.UTC))
                .and(Event.EVENT.STATUS.eq(of(IN_PROGRESS)))))
        .orderBy(Event.EVENT.CREATED)
        .limit(75)
        .fetch(this::toEvent);
```

Generated jooq class is:
```java
public class Event extends TableImpl<EventRecord> {

    private static final long serialVersionUID = 1179302902;

    public static final Event EVENT = new Event();

    @Override
    public Class<EventRecord> getRecordType() {
        return EventRecord.class;
    }

    public final TableField<EventRecord, String> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    public final TableField<EventRecord, Integer> RETRIED = createField(DSL.name("retried"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    public final TableField<EventRecord, String> STATUS = createField(DSL.name("status"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    public final TableField<EventRecord, Long> VERSION = createField(DSL.name("version"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    public final TableField<EventRecord, OffsetDateTime> LASTUPDATED = createField(DSL.name("lastupdated"), org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE.nullable(false), this, "");

    public final TableField<EventRecord, OffsetDateTime> CREATED = createField(DSL.name("created"), org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE.nullable(false), this, "");

    public final TableField<EventRecord, String> EVENT_MSG = createField(DSL.name("event_msg"), org.jooq.impl.DefaultDataType.getDefaultDataType("\"pg_catalog\".\"jsonb\"").nullable(false), this, "", new BinaryJsonToString());

    public Event() {
        this(DSL.name("event"), null);
    }

    public Event(String alias) {
        this(DSL.name(alias), EVENT);
    }

    public Event(Name alias) {
        this(alias, EVENT);
    }

    private Event(Name alias, Table<EventRecord> aliased) {
        this(alias, aliased, null);
    }

    private Event(Name alias, Table<EventRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Event(Table<O> child, ForeignKey<O, EventRecord> key) {
        super(child, key, EVENT);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.EVENT_INDEX_CREATED, Indexes.EVENT_INDEX_STATUS);
    }

    @Override
    public UniqueKey<EventRecord> getPrimaryKey() {
        return Keys.EVENTPK;
    }

    @Override
    public List<UniqueKey<EventRecord>> getKeys() {
        return Arrays.<UniqueKey<EventRecord>>asList(Keys.EVENTPK);
    }

    @Override
    public TableField<EventRecord, Long> getRecordVersion() {
        return VERSION;
    }

    @Override
    public Event as(String alias) {
        return new Event(DSL.name(alias), this);
    }

    @Override
    public Event as(Name alias) {
        return new Event(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Event rename(String name) {
        return new Event(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Event rename(Name name) {
        return new Event(name, null);
    }
    @Override
    public Row7<String, Integer, String, Long, OffsetDateTime, OffsetDateTime, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
``` 

### Steps to reproduce the problem

- If the problem relates to code generation, please post your code generation configuration
- A complete set of DDL statements can help re-create the setup you're having
- An MCVE can be helpful to provide a complete reproduction case: https://github.com/jOOQ/jOOQ-mcve

### Versions

- jOOQ: 3.13.5
- Java 14
- Database (include vendor): Postgre
- OS: alpine
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql -> 42.2.18

**Comment by lukaseder** [comment]
Thanks a lot for your report.

I don't think I'll be able to reproduce this easily on my side. It seems that some static initialisation has gone wrong, which leads to the "100% or 0%" behaviour, a race condition when jOOQ and/or your generated code is initialised. Can you try to track this down on your side? Does the problem persist with jOOQ 3.14.4?

**Comment by lukaseder** [comment]
Such race conditions are very hard to reproduce. I'll be happy to look into an MCVE (template here: https://github.com/jOOQ/jOOQ-mcve) that allows for reliably reproducing this issue.
