### ISSUE TITLE
Tests failed for jooq-spring-boot-example

### ISSUE THREAD

**Issue by snuyanzin** [jOOQ/jOOQ#11066]
### Expected behavior
tests should be passed
### Actual behavior
tests fail with
```
Dec 01, 2020 7:59:00 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'junit-vintage' failed to discover tests
org.junit.platform.commons.JUnitException: Failed to parse version of junit:junit: 4.13.1
	at org.junit.vintage.engine.JUnit4VersionCheck.parseVersion(JUnit4VersionCheck.java:54)
	at org.junit.vintage.engine.JUnit4VersionCheck.checkSupported(JUnit4VersionCheck.java:37)
	at org.junit.vintage.engine.JUnit4VersionCheck.checkSupported(JUnit4VersionCheck.java:32)
	at org.junit.vintage.engine.VintageTestEngine.discover(VintageTestEngine.java:61)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:168)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:155)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```
### Steps to reproduce the problem
```
[serg@localhost jOOQ]$ cd jOOQ-examples/jOOQ-spring-boot-example/ && mvn clean install
```
### Versions

- jOOQ: master branch (3.15.0-SNAPSHOT)
- Java: OpenJDK Runtime Environment (build 1.8.0_275-b01)
- OS: Fedora 32

**Comment by snuyanzin** [comment]
it seems there are at least 2 ways to fix it
1) update spring-boot as it was fixed there (in fact dependencies to junit-vintage were updated)
2) use newer dependences in `jOOQ-examples/jOOQ-spring-boot-example/pom.xml` something like that
```
 <dependency>
     <groupId>org.springframework.boot</groupId>
     <artifactId>spring-boot-starter-test</artifactId>
     <version>${spring.boot.version}</version>
     <scope>test</scope>
     <exclusions>
           <exclusion>
           <groupId>org.junit.vintage</groupId>
           <artifactId>junit-vintage-engine</artifactId>
 </dependency>
 <dependency>
         <groupId>org.junit.vintage</groupId>
         <artifactId>junit-vintage-engine</artifactId>
         <version>5.6.3</version>
         <scope>test</scope>
 </dependency>
``

**Comment by lukaseder** [comment]
Thanks a lot for your report. I'll look into this right away.

**Comment by lukaseder** [comment]
Thanks for your suggestions. I'd rather not complicate this example here with some exclusions that won't be necessary if this were a standalone example. I'll try the upgrading path.

**Comment by lukaseder** [comment]
Upgrading Spring Boot *and* Spring *and* adding additional, missing Spring dependencies seems to work

**Comment by lukaseder** [comment]
Should work now, thanks again for your report!
