### ISSUE TITLE
Add support for ZonedDateTime

### ISSUE THREAD

**Issue by jiuli** [jOOQ/jOOQ#11072]
planTaskTable.PLANENDTIME.cast(ZonedDateTime.class)  Type class java.time.ZonedDateTime is not supported in dialect null

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. What dialect are you using? Many SQL dialects (except e.g. Oracle) don't have a good representation for a `ZonedDateTime` type. The best types are usually `Instant` (PostgreSQL) or `OffsetDateTime` (others). Can you please describe your use-case a bit more?

**Comment by lukaseder** [comment]
Adding and testing a new data type is a lot of work, compared to the relatively easy way of adding a converter on the user side. I'd like to understand first why this type needs to be supported out of the box.

Postponing for now.

**Comment by lukaseder** [comment]
Closing this as "won't fix", for now. I don't think there's a good way to implement support for this type in most RDBMS. Usually, users should prefer `Instant`

**Comment by khauser** [comment]
Hi,

till version 3.12.4 (with postgres 42.3.1, testcontainers 1.16.3 and liquibase 3.10.0) I am able to use ZonedDateTime in my entities with e.g.:
```
    @Column(name = "ts_test_run_end_date_time")
    @JsonFormat(pattern = JsonSerializer.JSON_ZONED_DATE_TIME)
    private ZonedDateTime testRunEndDateTime;
```

In a jooqGenerator task I was able to define a mapping:
```
    private static final String TIMESTAMP = ".*TIMESTAMP.*";
    private static final String ZONEDDATETIME_CONVERTER = "com.intershop.iste.bi.util.ZonedDateTimeConverter";
    private static final String ZONEDDATETIME = "java.time.ZonedDateTime";
    ...
    forcedTypes.add(new ForcedType().withUserType(ZONEDDATETIME).withConverter(ZONEDDATETIME_CONVERTER)
                        .withIncludeExpression(DOT_STAR).withIncludeTypes(TIMESTAMP));
```

With this a valid table class was generated having e.g. this line:
```
public final TableField<StgTestSuiteRecord, ZonedDateTime> TS_TEST_RUN_END_DATE_TIME = createField(DSL.name("ts_test_run_end_date_time"), org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new ZonedDateTimeConverter());
```

But if I now upgrade my project the generated table complains about missing methods:
```
persistence\tables\StgTestSuite.java:158: error: no suitable method found for createField(Name,DataType<LocalDateTime>,StgTestSuite,String,ZonedDateTimeConverter)
    public final TableField<StgTestSuiteRecord, ZonedDateTime> TS_TEST_RUN_END_DATE_TIME = createField(DSL.name("ts_test_run_end_date_time"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "", new ZonedDateTimeConverter());
                                                                                           ^
    method AbstractTable.<R#1,T#1>createField(String,DataType<T#1>,Table<R#1>) is not applicable
      (cannot infer type-variable(s) R#1,T#1
        (actual and formal argument lists differ in length))
    method AbstractTable.<R#2,T#2>createField(String,DataType<T#2>,Table<R#2>,String) is not applicable
      (cannot infer type-variable(s) R#2,T#2
        (actual and formal argument lists differ in length))
    method AbstractTable.<R#3,T#3,U#1>createField(String,DataType<T#3>,Table<R#3>,String,Converter<T#3,U#1>) is not applicable
      (cannot infer type-variable(s) R#3,T#3,U#1
        (argument mismatch; Name cannot be converted to String))
    method AbstractTable.<R#4,T#4,U#2>createField(String,DataType<T#4>,Table<R#4>,String,Binding<T#4,U#2>) is not applicable
      (cannot infer type-variable(s) R#4,T#4,U#2
        (argument mismatch; Name cannot be converted to String))
    method AbstractTable.<R#5,T#5,X#1,U#3>createField(String,DataType<T#5>,Table<R#5>,String,Converter<X#1,U#3>,Binding<T#5,X#1>) is not applicable
      (cannot infer type-variable(s) R#5,T#5,X#1,U#3
        (actual and formal argument lists differ in length))
    method AbstractTable.<T#6>createField(String,DataType<T#6>) is not applicable
      (cannot infer type-variable(s) T#6
        (actual and formal argument lists differ in length))
    method AbstractTable.<T#7>createField(String,DataType<T#7>,String) is not applicable
      (cannot infer type-variable(s) T#7
        (actual and formal argument lists differ in length))
    method AbstractTable.<T#8,U#4>createField(String,DataType<T#8>,String,Converter<T#8,U#4>) is not applicable
      (cannot infer type-variable(s) T#8,U#4
        (actual and formal argument lists differ in length))
    method AbstractTable.<T#9,U#5>createField(String,DataType<T#9>,String,Binding<T#9,U#5>) is not applicable
      (cannot infer type-variable(s) T#9,U#5
        (actual and formal argument lists differ in length))
    method AbstractTable.<T#10,X#2,U#6>createField(String,DataType<T#10>,String,Converter<X#2,U#6>,Binding<T#10,X#2>) is not applicable
      (cannot infer type-variable(s) T#10,X#2,U#6
        (argument mismatch; Name cannot be converted to String))
    method AbstractTable.<R#7,T#11>createField(Name,DataType<T#11>,Table<R#7>) is not applicable
      (cannot infer type-variable(s) R#7,T#11
        (actual and formal argument lists differ in length))
    method AbstractTable.<R#8,T#12>createField(Name,DataType<T#12>,Table<R#8>,String) is not applicable
      (cannot infer type-variable(s) R#8,T#12
        (actual and formal argument lists differ in length))
    method AbstractTable.<R#9,T#13,U#7>createField(Name,DataType<T#13>,Table<R#9>,String,Converter<T#13,U#7>) is not applicable
      (inference variable T#13 has incompatible equality constraints Timestamp,LocalDateTime)
    method AbstractTable.<R#10,T#14,U#8>createField(Name,DataType<T#14>,Table<R#10>,String,Binding<T#14,U#8>) is not applicable
      (cannot infer type-variable(s) R#10,T#14,U#8
        (argument mismatch; ZonedDateTimeConverter cannot be converted to Binding<T#14,U#8>))
    method AbstractTable.<R#11,T#15,X#3,U#9>createField(Name,DataType<T#15>,Table<R#11>,String,Converter<X#3,U#9>,Binding<T#15,X#3>) is not applicable
      (cannot infer type-variable(s) R#11,T#15,X#3,U#9
        (actual and formal argument lists differ in length))
    method AbstractTable.<T#16>createField(Name,DataType<T#16>) is not applicable
      (cannot infer type-variable(s) T#16
        (actual and formal argument lists differ in length))
    method AbstractTable.<T#17>createField(Name,DataType<T#17>,String) is not applicable
      (cannot infer type-variable(s) T#17
        (actual and formal argument lists differ in length))
    method AbstractTable.<T#18,U#10>createField(Name,DataType<T#18>,String,Converter<T#18,U#10>) is not applicable
      (cannot infer type-variable(s) T#18,U#10
        (actual and formal argument lists differ in length))
    method AbstractTable.<T#19,U#11>createField(Name,DataType<T#19>,String,Binding<T#19,U#11>) is not applicable
      (cannot infer type-variable(s) T#19,U#11
        (actual and formal argument lists differ in length))
    method AbstractTable.<T#20,X#4,U#12>createField(Name,DataType<T#20>,String,Converter<X#4,U#12>,Binding<T#20,X#4>) is not applicable
      (cannot infer type-variable(s) T#20,X#4,U#12
        (argument mismatch; StgTestSuite cannot be converted to String))
  where R#1,T#1,R#2,T#2,R#3,T#3,U#1,R#4,T#4,U#2,R#5,T#5,X#1,U#3,T#6,R#6,T#7,T#8,U#4,T#9,U#5,T#10,X#2,U#6,R#7,T#11,R#8,T#12,R#9,T#13,U#7,R#10,T#14,U#8,R#11,T#15,X#3,U#9,T#16,T#17,T#18,U#10,T#19,U#11,T#20,X#4,U#12 are type-variables:
    R#1 extends Record declared in method <R#1,T#1>createField(String,DataType<T#1>,Table<R#1>)
    T#1 extends Object declared in method <R#1,T#1>createField(String,DataType<T#1>,Table<R#1>)
    R#2 extends Record declared in method <R#2,T#2>createField(String,DataType<T#2>,Table<R#2>,String)
    T#2 extends Object declared in method <R#2,T#2>createField(String,DataType<T#2>,Table<R#2>,String)
    R#3 extends Record declared in method <R#3,T#3,U#1>createField(String,DataType<T#3>,Table<R#3>,String,Converter<T#3,U#1>)
    T#3 extends Object declared in method <R#3,T#3,U#1>createField(String,DataType<T#3>,Table<R#3>,String,Converter<T#3,U#1>)
    U#1 extends Object declared in method <R#3,T#3,U#1>createField(String,DataType<T#3>,Table<R#3>,String,Converter<T#3,U#1>)
    R#4 extends Record declared in method <R#4,T#4,U#2>createField(String,DataType<T#4>,Table<R#4>,String,Binding<T#4,U#2>)
    T#4 extends Object declared in method <R#4,T#4,U#2>createField(String,DataType<T#4>,Table<R#4>,String,Binding<T#4,U#2>)
    U#2 extends Object declared in method <R#4,T#4,U#2>createField(String,DataType<T#4>,Table<R#4>,String,Binding<T#4,U#2>)
    R#5 extends Record declared in method <R#5,T#5,X#1,U#3>createField(String,DataType<T#5>,Table<R#5>,String,Converter<X#1,U#3>,Binding<T#5,X#1>)
    T#5 extends Object declared in method <R#5,T#5,X#1,U#3>createField(String,DataType<T#5>,Table<R#5>,String,Converter<X#1,U#3>,Binding<T#5,X#1>)
    X#1 extends Object declared in method <R#5,T#5,X#1,U#3>createField(String,DataType<T#5>,Table<R#5>,String,Converter<X#1,U#3>,Binding<T#5,X#1>)
    U#3 extends Object declared in method <R#5,T#5,X#1,U#3>createField(String,DataType<T#5>,Table<R#5>,String,Converter<X#1,U#3>,Binding<T#5,X#1>)
    T#6 extends Object declared in method <T#6>createField(String,DataType<T#6>)
    R#6 extends Record declared in class AbstractTable
    T#7 extends Object declared in method <T#7>createField(String,DataType<T#7>,String)
    T#8 extends Object declared in method <T#8,U#4>createField(String,DataType<T#8>,String,Converter<T#8,U#4>)
    U#4 extends Object declared in method <T#8,U#4>createField(String,DataType<T#8>,String,Converter<T#8,U#4>)
    T#9 extends Object declared in method <T#9,U#5>createField(String,DataType<T#9>,String,Binding<T#9,U#5>)
    U#5 extends Object declared in method <T#9,U#5>createField(String,DataType<T#9>,String,Binding<T#9,U#5>)
    T#10 extends Object declared in method <T#10,X#2,U#6>createField(String,DataType<T#10>,String,Converter<X#2,U#6>,Binding<T#10,X#2>)
    X#2 extends Object declared in method <T#10,X#2,U#6>createField(String,DataType<T#10>,String,Converter<X#2,U#6>,Binding<T#10,X#2>)
    U#6 extends Object declared in method <T#10,X#2,U#6>createField(String,DataType<T#10>,String,Converter<X#2,U#6>,Binding<T#10,X#2>)
    R#7 extends Record declared in method <R#7,T#11>createField(Name,DataType<T#11>,Table<R#7>)
    T#11 extends Object declared in method <R#7,T#11>createField(Name,DataType<T#11>,Table<R#7>)
    R#8 extends Record declared in method <R#8,T#12>createField(Name,DataType<T#12>,Table<R#8>,String)
    T#12 extends Object declared in method <R#8,T#12>createField(Name,DataType<T#12>,Table<R#8>,String)
    R#9 extends Record declared in method <R#9,T#13,U#7>createField(Name,DataType<T#13>,Table<R#9>,String,Converter<T#13,U#7>)
    T#13 extends Object declared in method <R#9,T#13,U#7>createField(Name,DataType<T#13>,Table<R#9>,String,Converter<T#13,U#7>)
    U#7 extends Object declared in method <R#9,T#13,U#7>createField(Name,DataType<T#13>,Table<R#9>,String,Converter<T#13,U#7>)
    R#10 extends Record declared in method <R#10,T#14,U#8>createField(Name,DataType<T#14>,Table<R#10>,String,Binding<T#14,U#8>)
    T#14 extends Object declared in method <R#10,T#14,U#8>createField(Name,DataType<T#14>,Table<R#10>,String,Binding<T#14,U#8>)
    U#8 extends Object declared in method <R#10,T#14,U#8>createField(Name,DataType<T#14>,Table<R#10>,String,Binding<T#14,U#8>)
    R#11 extends Record declared in method <R#11,T#15,X#3,U#9>createField(Name,DataType<T#15>,Table<R#11>,String,Converter<X#3,U#9>,Binding<T#15,X#3>)
    T#15 extends Object declared in method <R#11,T#15,X#3,U#9>createField(Name,DataType<T#15>,Table<R#11>,String,Converter<X#3,U#9>,Binding<T#15,X#3>)
    X#3 extends Object declared in method <R#11,T#15,X#3,U#9>createField(Name,DataType<T#15>,Table<R#11>,String,Converter<X#3,U#9>,Binding<T#15,X#3>)
    U#9 extends Object declared in method <R#11,T#15,X#3,U#9>createField(Name,DataType<T#15>,Table<R#11>,String,Converter<X#3,U#9>,Binding<T#15,X#3>)
    T#16 extends Object declared in method <T#16>createField(Name,DataType<T#16>)
    T#17 extends Object declared in method <T#17>createField(Name,DataType<T#17>,String)
    T#18 extends Object declared in method <T#18,U#10>createField(Name,DataType<T#18>,String,Converter<T#18,U#10>)
    U#10 extends Object declared in method <T#18,U#10>createField(Name,DataType<T#18>,String,Converter<T#18,U#10>)
    T#19 extends Object declared in method <T#19,U#11>createField(Name,DataType<T#19>,String,Binding<T#19,U#11>)
    U#11 extends Object declared in method <T#19,U#11>createField(Name,DataType<T#19>,String,Binding<T#19,U#11>)
    T#20 extends Object declared in method <T#20,X#4,U#12>createField(Name,DataType<T#20>,String,Converter<X#4,U#12>,Binding<T#20,X#4>)
    X#4 extends Object declared in method <T#20,X#4,U#12>createField(Name,DataType<T#20>,String,Converter<X#4,U#12>,Binding<T#20,X#4>)
    U#12 extends Object declared in method <T#20,X#4,U#12>createField(Name,DataType<T#20>,String,Converter<X#4,U#12>,Binding<T#20,X#4>)
```

So in my opinion I was able to add support of ZoneDateTime to my project. Do you have any suggestion how I can add this support again? Or do you have another solution?

Thanks for your help
Karsten

**Comment by lukaseder** [comment]
Thanks for your report, @khauser. I'm assuming this is because jOOQ 3.13 switched the default value for `<javaTimeTypes/>`? https://github.com/jOOQ/jOOQ/issues/5714. You can either revert that change by making it explicitly `false`, or change your converters to stop using `java.sql.Timestamp` and start using `java.time.LocalDateTime`, instead.

**Comment by lukaseder** [comment]
(I'm hiding these comments, as they aren't really related to this issue. You can always create new issues for your questions, for the future).

**Comment by khauser** [comment]
Thanks for building such a great tool.

With `generate().withJavaTimeTypes(false)` it works till version 3.14.15.

When setting 3.15.0 or higher integration tests complain about a missing bean, but the Bean is declared:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field testPlanRepository in com.intershop.iste.bi.service.DwhTestPlanService required a bean of type 'com.intershop.iste.bi.repository.DwhTestPlanRepository' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)


Action:

Consider defining a bean of type 'hululu.MyRepository' in your configuration.

2022-02-24 20:13:56.363 ERROR 708 --- [    Test worker] o.s.test.context.TestContextManager      : Caught exception while allowing TestExecutionListener [com.github.springtestdbunit.TransactionDbUnitTestExecutionListener@12b66c89] to prepare test instance [myTest@844c080]

java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:132) ~[spring-test-5.3.14.jar:5.3.14]
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:124) ~[spring-test-5.3.14.jar:5.3.14]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
```
Do you have something in mind here too?

**Comment by lukaseder** [comment]
Maybe this? https://stackoverflow.com/q/68297295/521799
