### ISSUE TITLE
NullPointerException when GenerationTool is not properly initialised

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11105]
It is possible for a `NullPointerException` to be logged as a side-effect of an improperly initialised `GenerationTool`:

```
java.lang.NullPointerException
	at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:900)
	at org.jooq.codegen.GenerationTool.run(GenerationTool.java:233)
	at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:228)
	at org.jooq.codegen.GenerationTool.main(GenerationTool.java:200)
```

The most probably cause I can see is that the `GenerationTool` is configured programmatically using a `GenerationTool::setConnection` call, and any of these holds true:

- The JDBC URL is not recognised, and the `SQLDialect` can thus not be derived
- The jOOQ Open Source Edition is used by accident, rather than a commercial edition

While the NPE is a side-effect, and the actual cause of the problem should be logged before it, it is still an unnecessary distraction and could be avoided.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.15.0 and 3.14.5 (#11106)
