### ISSUE TITLE
TableDataType and Cast(Native) should render the schema if renderSchema = true

### ISSUE THREAD

**Issue by mkurz** [jOOQ/jOOQ#11114]
### Steps to reproduce the problem

When a ctx's settings has `withRenderSchema(true)`:

```java
ctx.renderInlined(table);
ctx.renderInlined(table.getDataType());
ctx.renderInlined(DSL.castNull(table.getDataType()));
```

### Expected behavior

```
"public"."my_table"
"public"."my_table"
cast(null as "public"."my_table")
```

### Actual behavior

```
"public"."my_table" // correct
my_table
cast(null as my_table)
```

I think when visiting the `accept` methods of `TableDataType` or the `Cast`/`CastNative` they should also render the current schema of the ctx.

### Versions

- jOOQ: 3.14.4
- Java: openjdk version "11.0.8" 2020-07-14
- Database (include vendor): Postgres 13
- OS: Ubuntu 18.04.5 LTS

**Comment by lukaseder** [comment]
Thanks for your report. That looks like a similar issue. This isn't only about `renderSchema`: https://github.com/jOOQ/jOOQ/issues/9347

**Comment by lukaseder** [comment]
Hmm, nope, too quick. The test doesn't pass yet. But I'll fix it right away.

**Comment by lukaseder** [comment]
I guess the `UDT` cast doesn't work either, as the `UDTDataType` logic is similar. I'll fix both in one go

**Comment by lukaseder** [comment]
As mentioned in #9347, 2 test cases have been added, which now pass in jOOQ 3.17.0:

```java
@Test
public void testPostgresCastTableType() throws Exception {
    bindAndInline(ctx -> {
        try {
            ctx.setSchema(PUBLIC).execute();
            assertEquals(new TBookStoreRecord("A"),
                ctx.fetchValue(select(cast(row("A"), T_BOOK_STORE.getDataType()))));

            ctx.setSchema(MULTI_SCHEMA).execute();
            assertEquals(new TBookStoreRecord("A"),
                ctx.fetchValue(select(cast(row("A"), T_BOOK_STORE.getDataType()))));
        }
        finally {
            ctx.setSchema(PUBLIC).execute();
        }
    });
}

@Test
public void testPostgresCastUDTType() throws Exception {
    bindAndInline(ctx -> {
        try {
            ctx.setSchema(PUBLIC).execute();
            assertEquals(new U_7068Record(1, 2),
                ctx.fetchValue(select(cast(row(1, 2), U_7068.getDataType()))));

            ctx.setSchema(MULTI_SCHEMA).execute();
            assertEquals(new U_7068Record(1, 2),
                ctx.fetchValue(select(cast(row(1, 2), U_7068.getDataType()))));
        }
        finally {
            ctx.setSchema(PUBLIC).execute();
        }
    });
}
```

The backport to 3.16 has failed with this exception:

```
java.lang.IllegalArgumentException: Cannot interpret argument of type class org.jooq.impl.RowImpl1 as a Field: ('A')
	at org.jooq.impl.Tools.fieldExpected(Tools.java:1546)
	at org.jooq.impl.Tools.field(Tools.java:1615)
	at org.jooq.impl.DSL.cast(DSL.java:15465)
	at org.jooq.test.PostgresTest.lambda$33(PostgresTest.java:3970)
	at org.jooq.test.jOOQAbstractTest.withDSLContext(jOOQAbstractTest.java:1976)
	at org.jooq.test.jOOQAbstractTest.bindAndInline(jOOQAbstractTest.java:1963)
	at org.jooq.test.PostgresTest.testPostgresCastTableType(PostgresTest.java:3966)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:30)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

In order for the backport to work, I suspect we'll have to backport https://github.com/jOOQ/jOOQ/issues/13251 as well, first.

**Comment by lukaseder** [comment]
OK, now the tests work. Thanks again for the ping and report, @mkurz.
