### ISSUE TITLE
ParserWithMetaLookups reports ambiguous column in correlated subquery, when there is none

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11143]
Assuming a schema:

```sql
create table u (col1 int);
create table a (col1 int);
```

The following query doesn't parse with meta lookups turned on:

```sql
select COL1 from U where (select COL1 from A) = 1
```

The exception is:

```
org.jooq.impl.ParserException: Ambiguous field identifier: [1:39] select COL1 from U where (select COL1 [*]from A) = 1
	at org.jooq.impl.ParserContext.exception(ParserImpl.java:12305)
	at org.jooq.impl.ParserContext.resolveInTableScope(ParserImpl.java:12586)
	at org.jooq.impl.ParserContext.scopeEnd(ParserImpl.java:12543)
	at org.jooq.impl.ParserContext.parseQuery(ParserImpl.java:1053)
	at org.jooq.impl.ParserContext.parseSelect0(ParserImpl.java:801)
	at org.jooq.impl.ParserImpl.parseSelect(ParserImpl.java:658)
	at org.jooq.impl.ParserImpl.parseSelect(ParserImpl.java:653)
	at org.jooq.impl.ParserMetaTest.assertProjectionEquals(ParserMetaTest.java:1060)
	at org.jooq.impl.ParserMetaTest.testUnqualifiedFieldFromCorrelatedSubqueries(ParserMetaTest.java:408)
```

The nested scope hides identifiers from the outer scope. There is no ambiguity here.

**Comment by lukaseder** [comment]
To solve this, `ScopeStack` needs an additional `Iterable<Value<V>>`, where `Value(int scopeLevel, V value)` allows for accessing the scope level of each value. That way, we can throw ambiguity errors only if there are ambiguities on the same scope level, not on different ones.
