### ISSUE TITLE
Record.from() and into() don't work for renamed columns in embeddable records

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11178]
With an embeddable configuration like this:

```sql
CREATE TABLE embeddable_pojos (
  a INT,
  b INT,
  c INT
);
```

And

```xml
<embeddables>
    <embeddable>
        <name>EMBEDDABLE</name>
        <tables>EMBEDDABLE_POJOS</tables>
        <fields>
            <field><expression>A</expression></field>
            <field><name>X</name><expression>B</expression></field>
        </fields>
    </embeddable>
</embeddables>
```

The following test fails:

```java
@Test
public void testMeta() {
    EmbeddableRecord e = new EmbeddableRecord(1, 2);
    Embeddable p = e.into(Embeddable.class);

    assertEquals(1, p.getA());
    assertEquals(2, p.getX());

    p.setA(3);
    p.setX(4);

    e.from(p);

    assertEquals(3, p.getA());
    assertEquals(4, p.getX());
    assertEquals(3, e.getA());
    assertEquals(4, e.getX());
}
```

The error is:

```
java.lang.AssertionError: expected:<2> but was:<null>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.jooq.test.util.BaseTest.assertEquals(BaseTest.java:95)
	at org.jooq.codegen.test.embeddablepojos.EmbeddablePojosTest.testMeta(EmbeddablePojosTest.java:54)
```

It appears that the value for `X` (which is really `B`) is set to `null`

**Comment by lukaseder** [comment]
There's a fundamental disconnect between the original table and the produced embeddable. The embeddable is designed to be table agnostic - it can be referenced from several tables, even several times from the same table. As a POJO, this disconnect is complete. There are no hints in the generated POJO (apart from package name and Javadoc) about the POJO `(X, Y)` being connected to the table rows `(A, B)`.

The embeddable record, on the other hand, just pretends to have properties (X, Y), when behind the scenes, it still references the columns `(A, B)`, and probably wrongly so, in case it is being reused from columns `(A", B")`. It does not expose those columns as properties `(A, B)`,  but again `(X, Y)`, meaning that some reflection utilities can work well with the POJO, but not the `Record.from()` method, which uses reflection only on the POJO, but field information on the record.

The field information has been added to the embeddable record only as a means to attach `DataType` information from the source table. There's no reason why we should maintain the actual field reference. The fix will not be trivial, though.
