### ISSUE TITLE
ForcedType mapped to Kotlin inline class confuses record to POJO mapping logic

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#11199]
### Expected behavior

Inline classes work just like data classes with a single property.

### Actual behavior

Mapping fails with

```
Caused by: org.jooq.exception.DataTypeException: No Converter found for types java.time.Instant and com.veturanto.server.track.model.TrackId
	at org.jooq.impl.Tools.converterOrFail(Tools.java:1156)
	at org.jooq.impl.Tools.converterOrFail(Tools.java:1172)
	at org.jooq.impl.AbstractRecord.get(AbstractRecord.java:282)
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.set(DefaultRecordMapper.java:1057)
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.mapNonnested(DefaultRecordMapper.java:1031)
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.map(DefaultRecordMapper.java:1016)
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.map(DefaultRecordMapper.java:1019)
	at org.jooq.impl.DefaultRecordMapper.map(DefaultRecordMapper.java:544)
	at org.jooq.impl.AbstractRecord.into(AbstractRecord.java:743)
```

Offending line that triggers this: `myRecord.into(MyPojo::class.java)`

### Steps to reproduce the problem

Create a table with a few columns in random order: c, b, d, a
Create a Kotlin POJO data class with properties matching those columns in order: a, b, c, d
Create a data class for one of those types such as `data class D(val num: Int)` and map it using a `ForcedType`

Attempting to convert it using a statement like `myRecord.into(MyPojo::class.java)` should work as expected.

Now change the data class to an inline class: `inline class D(val num: Int)`

Now the same conversion will fail with the exception above. It appears that the field matching logic gets confused and subsequently attempts to match by index, which in turn fails as the table column order and the pojo property order are different.

### Versions

- jOOQ: 3.14.4
- Java: 14
- Database (include vendor): PG 13.1

**Comment by lukaseder** [comment]
Thanks a lot for your report. I'll investigate shortly...

**Comment by lukaseder** [comment]
Oh, I see. The constructor is private, but we're calling `Class.getConstructor(...)` to reflect on it, when everywhere else we use `accessible(type.getDeclaredConstructor(...))`.

**Comment by lukaseder** [comment]
Ah no! I'm chasing another issue (unrelated?): https://github.com/jOOQ/jOOQ/issues/11228

**Comment by lukaseder** [comment]
Nope, it seems to be the same issue as #11228, when I use your various code snippets to try to reproduce the issue. I hope I got it right. For more reproduction accuracy, the MCVE template now supports kotlin as well: https://github.com/jOOQ/jOOQ-mcve

Fixed in jOOQ 3.15.0 and 3.14.5 via #11228
