### ISSUE TITLE
ArrayStoreException when calling ResultQuery<Record[N]>.fetchArray()

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11208]
This code:

```java
Record2<AType, BType>[] result =
ctx.select(T.A, T.B)
   .from(T)
   .fetchArray();
```

Compiles fine but throws an exception at runtime:

```
java.lang.ArrayStoreException: arraycopy: element type mismatch: can not cast one of the elements of java.lang.Object[] to the type of the destination array, org.jooq.impl.RecordImplN
	at java.base/java.util.ArrayList.toArray(ArrayList.java:433)
	at org.jooq.impl.ResultImpl.toArray(ResultImpl.java:1479)
	at org.jooq.impl.AbstractFetchable.fetchArray(AbstractFetchable.java:1049)
	at org.jooq.test.all.testcases.FetchTests.testFetchArray0(FetchTests.java:451)
	at org.jooq.test.all.testcases.FetchTests.testFetchArrayOfRecordN(FetchTests.java:418)
	at org.jooq.test.jOOQAbstractTest.testFetchArrayOfRecordN(jOOQAbstractTest.java:1632)
```

This went undetected so far, because we only have integration tests for mapping to `TableRecord[]` subtypes, e.g.:

```java
TRecord[] result =
ctx.selectFrom(T)
   .fetchArray();
```

Probably a 3.14 regression introduced with #4695, as before, all record type implementations were compatible

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.15.0 and 3.14.5 (#11209)
