### ISSUE TITLE
Settings.isMapConstructorParameterNamesInKotlin doesn't work for kotlin inline classes

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11228]
This test fails, currently.

```
internal inline class I(val i: Int)

@Test
public fun testIntoInlineClass(): Unit {
    insertRow()
    val x: I = ctx.selectFrom(POJOS_AS_KOTLIN_DATA_CLASSES).fetchSingleInto(I::class.java)
    assertEquals(1, x.i);
}
```

The reason is that inline classes seem to produce a private primary constructor, yielding this exception:

```
org.jooq.exception.MappingException: No matching constructor found on type class org.jooq.codegen.test.pojosaskotlindataclasses.I for row type 
  "POJOS_AS_KOTLIN_DATA_CLASSES"."I",
  "POJOS_AS_KOTLIN_DATA_CLASSES"."J",
  "POJOS_AS_KOTLIN_DATA_CLASSES"."K"

	at org.jooq.impl.DefaultRecordMapper.init(DefaultRecordMapper.java:516)
	at org.jooq.impl.DefaultRecordMapper.<init>(DefaultRecordMapper.java:353)
	at org.jooq.impl.DefaultRecordMapper.<init>(DefaultRecordMapper.java:344)
	at org.jooq.impl.DefaultRecordMapperProvider.lambda$provide$0(DefaultRecordMapperProvider.java:83)
	at org.jooq.impl.Tools$Cache.run(Tools.java:3294)
	at org.jooq.impl.DefaultRecordMapperProvider.provide(DefaultRecordMapperProvider.java:83)
	at org.jooq.impl.AbstractRecord.into(AbstractRecord.java:816)
	at org.jooq.impl.AbstractFetchable.fetchSingleInto(AbstractFetchable.java:398)
```

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.15.0 and 3.14.5 (#11229)
