### ISSUE TITLE
Parser throws IllegalArgumentException instead of ParserException when date_trunc() is parsed with invalid DatePart

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11233]
Parsing this wrong function:

```sql
date_trunc('x', a)
```

Throws an `IllegalArgumentException` instead of a meaningful `ParserException`:

```
java.lang.AssertionError: Expected : class org.jooq.impl.ParserException
	at org.jooq.test.util.BaseTest.ignoreThrows(BaseTest.java:215)
	at org.jooq.impl.ParserFunctionDiscoveryTest.testFindOmittedFunctions(ParserFunctionDiscoveryTest.java:211)
Caused by: java.lang.IllegalArgumentException: No enum constant org.jooq.DatePart.A
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at org.jooq.DatePart.valueOf(DatePart.java:1)
	at org.jooq.impl.ParserContext.parseFieldDateTruncIf(ParserImpl.java:8498)
```

As a side effect, the translator shows this:

![image](https://user-images.githubusercontent.com/734593/104585117-e04fa880-5663-11eb-9656-ac789abdb6d9.png)

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.15.0 and 3.14.5 (#11234)
