### ISSUE TITLE
NullPointerException when using table valued function without explicit parameters

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11259]
Given a table valued function like this:

```sql
CREATE FUNCTION f_tables4 (in_id INTEGER)
RETURNS TABLE (
    id INTEGER,
    title VARCHAR(400)
)
AS $$
BEGIN
    RETURN QUERY
    SELECT b.id, b.title
    FROM t_book b
    WHERE in_id IS NULL OR b.id = in_id
    ORDER BY b.id;
END
$$ LANGUAGE plpgsql;
```

It should be possible to call it without any explicit parameters:

```java
ctx.selectFrom(F_TABLES4).fetch();
ctx.fetch(F_TABLES4);
ctx.fetchCount(F_TABLES4);
```

Which should be the same thing as calling them as such:

```java
ctx.selectFrom(F_TABLES4(null)).fetch();
ctx.fetch(F_TABLES4(null));
ctx.fetchCount(F_TABLES4(null));
```

Yet, we're getting an NPE:

```
Exception in thread "main" java.lang.NullPointerException
	at org.jooq_3.15.0-SNAPSHOT.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.QueryPartCollectionView.accept(QueryPartCollectionView.java:120)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:609)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:242)
	at org.jooq.impl.TableImpl.accept0(TableImpl.java:323)
	at org.jooq.impl.TableImpl.accept(TableImpl.java:291)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:609)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:271)
	at org.jooq.impl.QueryPartCollectionView.accept(QueryPartCollectionView.java:178)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:609)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:271)
	at org.jooq.impl.SelectQueryImpl.toSQLReference0(SelectQueryImpl.java:2000)
	at org.jooq.impl.SelectQueryImpl.lambda$3(SelectQueryImpl.java:1575)
	at org.jooq.impl.AbstractContext.toggle(AbstractContext.java:308)
	at org.jooq.impl.AbstractContext.data(AbstractContext.java:324)
	at org.jooq.impl.SelectQueryImpl.toSQLReferenceLimitDefault(SelectQueryImpl.java:1575)
	at org.jooq.impl.SelectQueryImpl.accept0(SelectQueryImpl.java:1478)
	at org.jooq.impl.SelectQueryImpl.lambda$1(SelectQueryImpl.java:1262)
	at org.jooq.impl.AbstractContext.toggle(AbstractContext.java:308)
	at org.jooq.impl.AbstractContext.data(AbstractContext.java:324)
	at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:1262)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:609)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:271)
	at org.jooq.impl.AbstractQuery.getSQL0(AbstractQuery.java:528)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:328)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:315)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2805)
```

**Comment by lukaseder** [comment]
This is a code generation problem. The code generator currently generates this constructor:

```java
    private FTables4(Name alias, Table<FTables4Record> aliased) {
        this(alias, aliased, new Field[1]);
    }
```

When it should generate this one, instead:

```java
    private FTables4(Name alias, Table<FTables4Record> aliased) {
        this(alias, aliased, new Field[] { DSL.val(null, SQLDataType.INTEGER) });
    }
```

We have to solve this with the code generator, because there's currently no runtime meta information about parameter types in table valued functions when `<tableValuedFunctions>true</tableValuedFunctions>`
