### ISSUE TITLE
Interpreter cannot find unique key if foreign key references columns in different order

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11261]
The test table introduced in #8553 causes trouble also when interpreting the SQL:

```sql
CREATE TABLE t_8553_a (
  c1 INT NOT NULL,
  c2 INT NOT NULL,
  
  CONSTRAINT pk_t_8553_a PRIMARY KEY (c1, c2)
);

CREATE TABLE t_8553_b (
  c1 INT NOT NULL,
  c2 INT NOT NULL,
  
  CONSTRAINT fk_t_8553_b FOREIGN KEY (c2, c1) REFERENCES t_8553_a (c2, c1)
);
```

We get this exception:

```
org.jooq.exception.DataDefinitionException: Primary key does not exist on table: T_8553_A
	at org.jooq.impl.Interpreter.primaryKeyNotExists(Interpreter.java:1181)
	at org.jooq.impl.Interpreter.addForeignKey0(Interpreter.java:386)
	at org.jooq.impl.Interpreter.addForeignKey(Interpreter.java:338)
	at org.jooq.impl.Interpreter.addConstraint(Interpreter.java:750)
	at org.jooq.impl.Interpreter.accept0(Interpreter.java:326)
	at org.jooq.impl.Interpreter.accept(Interpreter.java:183)
	at org.jooq.impl.InterpreterMetaProvider.loadSource(InterpreterMetaProvider.java:106)
	at org.jooq.impl.InterpreterMetaProvider.provide(InterpreterMetaProvider.java:91)
	at org.jooq.impl.SourceMetaProvider.provide(SourceMetaProvider.java:80)
	at org.jooq.impl.DefaultDSLContext.meta(DefaultDSLContext.java:249)
	at org.jooq.test.AbstractInterpreterTest.meta(AbstractInterpreterTest.java:102)
	at org.jooq.test.AbstractInterpreterTest.meta(AbstractInterpreterTest.java:98)
	at org.jooq.test.InterpreterMetaTest.testTablesWithForeignKeysUnmatchedColumnOrder(InterpreterMetaTest.java:147)
```

----
See also: https://github.com/jOOQ/jOOQ/issues/11258

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.15.0 and 3.14.5 (#11262)
