### ISSUE TITLE
ParserException when parsing row value expression DISTINCT predicate with subquery

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11419]
Trying to parse this:

```sql
(a.a, a.b) is distinct from (select 0, 1)
```

Leads to the following exception:

```
org.jooq.impl.ParserException: Expected row of degree: 2. Got: 1: [1:37] (a.a, a.b) is distinct from (select [*]0, 1)
	at org.jooq.impl.ParserContext.exception(ParserImpl.java:13042)
	at org.jooq.impl.ParserContext.parseTuple(ParserImpl.java:6664)
	at org.jooq.impl.ParserContext.parseRow(ParserImpl.java:6918)
	at org.jooq.impl.ParserContext.parsePredicate(ParserImpl.java:6060)
	at org.jooq.impl.ParserContext.parseNot(ParserImpl.java:5900)
	at org.jooq.impl.ParserContext.parseAnd(ParserImpl.java:5890)
	at org.jooq.impl.ParserContext.parseOr(ParserImpl.java:5881)
	at org.jooq.impl.ParserContext.parseCondition(ParserImpl.java:5877)
	at org.jooq.impl.ParserContext.parseCondition0(ParserImpl.java:859)
	at org.jooq.impl.ParserImpl.parseCondition(ParserImpl.java:736)
	at org.jooq.impl.ParserImpl.parseCondition(ParserImpl.java:731)
	at org.jooq.impl.AbstractParserTest.lambda$assertConditionEquals$10(AbstractParserTest.java:346)
	at org.jooq.impl.AbstractParserTest.assertEquality(AbstractParserTest.java:422)
	at org.jooq.impl.AbstractParserTest.assertConditionEquals(AbstractParserTest.java:346)
	at org.jooq.impl.AbstractParserTest.assertConditionEqualsAll(AbstractParserTest.java:359)
	at org.jooq.impl.ParserPredicateTest.testDistinctPredicateWithCorrelatedSubqueries(ParserPredicateTest.java:582)
```

**Comment by lukaseder** [comment]
It's actually not specific to the `DISTINCT` predicate. This also doesn't parse:

```sql
(a, b) = (select 1, 2)
```

**Comment by lukaseder** [comment]
The fix leads to a regression when parsing this predicate, mixing row value expressions with subqueries:

```sql
select 1 where ((select 1 union select 2) + 1, 1 + (select 1 union select 2)) 
  = ((select 1 union select 2) + 1, 1 + (select 1 union select 2))
```
