### ISSUE TITLE
NullPointerException when Parser meta lookup cannot connect to a JDBC connection

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11496]
The parser's meta lookup seems to require an active JDBC connection in the following test:

```java
var settings = new Settings()
    .withParseDialect(SQLDialect.ORACLE20C)
    .withParseWithMetaLookups(ParseWithMetaLookups.IGNORE_ON_FAILURE);

var configuration = new DefaultConfiguration()
    .set(SQLDialect.POSTGRES_11)
    .set(settings);

var schema = ""
    +"create table  qbo.companies_1 (\n"
    +"    company_id numeric(22,0)   \n"
    +")                              \n"
;

var localConf = configuration.derive((MetaProvider) () -> DSL.using(configuration).meta(schema));
var localContext = DSL.using(localConf);
var queryStr = ""
    +"select                           \n"
    +"    COMPANIES.COMPANY_ID         \n"
    +"from QBO.COMPANIES_1 as COMPANIES\n"
    +"where COMPANIES.COMPANY_ID = ?   \n"
;
var query = localContext.parser().parseQuery(queryStr);
System.out.println(query);
```

The exception is:

```
Exception in thread "main" java.lang.NullPointerException
	at org.jooq.impl.MetaImpl.lambda$meta$0(MetaImpl.java:191)
	at org.jooq.impl.DefaultDSLContext.connectionResult(DefaultDSLContext.java:443)
	at org.jooq.impl.MetaImpl.meta(MetaImpl.java:191)
	at org.jooq.impl.MetaImpl$MetaCatalog.getSchemas(MetaImpl.java:303)
	at org.jooq.impl.MetaImpl.getSchemas0(MetaImpl.java:249)
	at org.jooq.impl.AbstractMeta.lambda$initSchemas$1(AbstractMeta.java:151)
	at org.jooq.impl.AbstractMeta.get(AbstractMeta.java:405)
	at org.jooq.impl.AbstractMeta.initSchemas(AbstractMeta.java:151)
	at org.jooq.impl.AbstractMeta.getSchemas(AbstractMeta.java:143)
	at org.jooq.impl.MetaImpl.getTables0(MetaImpl.java:258)
	at org.jooq.impl.AbstractMeta.lambda$initTables$3(AbstractMeta.java:185)
	at org.jooq.impl.AbstractMeta.get(AbstractMeta.java:405)
	at org.jooq.impl.AbstractMeta.initTables(AbstractMeta.java:185)
	at org.jooq.impl.AbstractMeta.getTables(AbstractMeta.java:171)
	at org.jooq.impl.ParserContext.lookupTable(ParserImpl.java:13548)
	at org.jooq.impl.ParserContext.parseTableName(ParserImpl.java:11027)
	at org.jooq.impl.ParserContext.parseCreateTable(ParserImpl.java:4074)
	at org.jooq.impl.ParserContext.parseCreate(ParserImpl.java:2643)
	at org.jooq.impl.ParserContext.parseQuery(ParserImpl.java:971)
	at org.jooq.impl.ParserContext.parse(ParserImpl.java:770)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:641)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:636)
	at org.jooq.impl.InterpreterMetaProvider.loadSource(InterpreterMetaProvider.java:105)
	at org.jooq.impl.InterpreterMetaProvider.provide(InterpreterMetaProvider.java:91)
	at org.jooq.impl.SourceMetaProvider.provide(SourceMetaProvider.java:80)
	at org.jooq.impl.DefaultDSLContext.meta(DefaultDSLContext.java:244)
	at org.jooq.testscripts.JDBC.lambda$0(JDBC.java:36)
	at org.jooq.impl.DefaultDSLContext.meta(DefaultDSLContext.java:209)
	at org.jooq.impl.ParserImpl.<init>(ParserImpl.java:623)
	at org.jooq.impl.DefaultDSLContext.parser(DefaultDSLContext.java:159)
	at org.jooq.testscripts.JDBC.main(JDBC.java:44)
```

**Comment by lukaseder** [comment]
The problem is that both the actual parsing of the query, as well as the meta definition, are using meta lookups. This solves the problem:

```java
var settings = new Settings()
    .withParseDialect(SQLDialect.ORACLE20C);

var configuration = new DefaultConfiguration()
    .set(SQLDialect.POSTGRES_11)
    .set(settings);

var schema = ""
    +"create table  qbo.companies_1 (\n"
    +"    company_id numeric(22,0)   \n"
    +")                              \n"
;

var meta = DSL.using(configuration).meta(schema);
var localConf = configuration.set((MetaProvider) () -> meta);
var localContext = DSL.using(localConf);
// Setting moved down here:
localContext.settings().withParseWithMetaLookups(ParseWithMetaLookups.IGNORE_ON_FAILURE);
var queryStr = ""
    +"select                           \n"
    +"    COMPANIES.COMPANY_ID         \n"
    +"from QBO.COMPANIES_1 as COMPANIES\n"
    +"where COMPANIES.COMPANY_ID = ?   \n"
;
var query = localContext.parser().parseQuery(queryStr);
System.out.println(query);
```

**Comment by lukaseder** [comment]
The NPE is not really related to the parser lookup, and can be improved independently: https://github.com/jOOQ/jOOQ/issues/11498

**Comment by lukaseder** [comment]
Related issue: https://github.com/jOOQ/jOOQ/issues/9071

**Comment by lukaseder** [comment]
A shorter reproduction case:

```java
// Test passes
@Test
public void testMetaLookupOnMetaWithoutMetaLookup() {
    Configuration c1 = new DefaultConfiguration();
    Configuration c2 = c1.derive((MetaProvider) () -> c1.dsl().meta("create table t (i int)"));
    c2.settings().withParseWithMetaLookups(ParseWithMetaLookups.IGNORE_ON_FAILURE);
    Select<?> query = c2.dsl().parser().parseSelect("select i from t where i = 1");
    assertSelectDataTypeEquals(INTEGER, query);
}

// Test fails
@Test
public void testMetaLookupOnMetaWithIgnoreOnFailure() {
    Configuration c1 = new DefaultConfiguration();
    c1.settings().withParseWithMetaLookups(ParseWithMetaLookups.IGNORE_ON_FAILURE);
    Configuration c2 = c1.derive((MetaProvider) () -> c1.dsl().meta("create table t (i int)"));
    Select<?> query = c2.dsl().parser().parseSelect("select i from t where i = 1");
    assertSelectDataTypeEquals(INTEGER, query);
}
```

**Comment by lukaseder** [comment]
So, with #11498, jOOQ 3.15.0 throws `DetachedException` whereas 3.14.x continues to throw a `NullPointerException`

While the NPE was a bit harsh, I'm not convinced that we should change anything about the existing behaviour. We're telling jOOQ to look up meta data during parsing, but we're not actually providing any (JDBC backed, by default) meta data. Hence, lookups should fail.

There are numerous issues to improve the parser / meta lookup experience (e.g. https://github.com/jOOQ/jOOQ/issues/9091), but here, I don't think we can really do much, unless we change the default of trying to connect to JDBC to a new default of using a `meta("")` as a base meta implementation.
