### ISSUE TITLE
Parser exception when index references UDF

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11611]
The fix #11047 introduced in jOOQ 3.15 and 3.14.5 to parse quoted identifiers in index definitions in the `PostgresDatabase` has caused a new issue with indexes referencing user-defined functions (UDFs). See original report here:
https://groups.google.com/g/jooq-user/c/oQTLLmOVpSA

```
INFO: Parse error              : Error when parsing column name : pv(events_less, events_equal, events_greater, 0)
org.jooq.impl.ParserException: Unknown function: [1:4] pv([*]events_less, events_equal, events_greater, 0)
    at org.jooq.impl.ParserContext.exception(ParserImpl.java:12259)
    at org.jooq.impl.ParserImpl.parseUnaryOps(ParserImpl.java:6558)
    at org.jooq.impl.ParserImpl.parseExp(ParserImpl.java:6522)
    at org.jooq.impl.ParserImpl.parseFactor(ParserImpl.java:6499)
    at org.jooq.impl.ParserImpl.parseSum(ParserImpl.java:6445)
    at org.jooq.impl.ParserImpl.parseNumericOp(ParserImpl.java:6430)
    at org.jooq.impl.ParserImpl.parseCollated(ParserImpl.java:6404)
    at org.jooq.impl.ParserImpl.parseConcat(ParserImpl.java:6394)
    at org.jooq.impl.ParserImpl.parsePredicate(ParserImpl.java:5323)
    at org.jooq.impl.ParserImpl.parseNot(ParserImpl.java:5253)
    at org.jooq.impl.ParserImpl.parseAnd(ParserImpl.java:5243)
    at org.jooq.impl.ParserImpl.parseOr(ParserImpl.java:5234)
    at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:6311)
    at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:6236)
    at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:764)
    at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:758)
    at org.jooq.meta.postgres.PostgresDatabase.tryParseColumnName(PostgresDatabase.java:266)
    at org.jooq.meta.postgres.PostgresDatabase.getIndexes0(PostgresDatabase.java:226)
    at org.jooq.meta.AbstractDatabase$14.run(AbstractDatabase.java:2338)
    at org.jooq.meta.AbstractDatabase.onError(AbstractDatabase.java:3094)
    at org.jooq.meta.AbstractDatabase.getIndexes(AbstractDatabase.java:2335)
    at org.jooq.meta.AbstractDatabase.getIndexes(AbstractDatabase.java:2369)
    at org.jooq.meta.AbstractTableDefinition.getIndexes(AbstractTableDefinition.java:99)
    at org.jooq.codegen.JavaGenerator.generateTable(JavaGenerator.java:5327)
    at org.jooq.codegen.JavaGenerator.generateTable(JavaGenerator.java:5038)
    at org.jooq.codegen.JavaGenerator.generateTables(JavaGenerator.java:5012)
    at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:582)
    at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:537)
    at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:436)
    at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:879)
    at org.jooq.codegen.GenerationTool.run(GenerationTool.java:233)
    at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:228)
    at org.jooq.codegen.GenerationTool.main(GenerationTool.java:200)
```

**Comment by dwilches** [comment]
Hello,
Is there a workaround for this issue? I just hit the same today.
Thanks.

**Comment by jbristow** [comment]
Is this error message being caused by the same issue?

```
[INFO] Parse error              : Error when parsing column name : date_trunc('day'::text, timezone('UTC'::text, fetched_at))
org.jooq.impl.ParserException: Token ',' expected: [1:17] date_trunc('day'[*]::text, timezone('UTC'::text, fetched_at))
```

from the debug log:
```
 nspname |      relname       |            relname            | indisunique |                                columns                                  | asc_or_desc 
---------+--------------------+-------------------------------+-------------+-----------------------------------------------------------------------+-------------
 report  | my_table           | owner_begin_day_index         | t           | {owner_id,"date_trunc('day'::text, timezone('UTC'::text, fetched_at))"} | [0:1]={0,0}
```

sample sql to generate this error:
```
CREATE TABLE my_table (
  id BIGSERIAL PRIMARY KEY,
  owner_id UUID NOT NULL,
  fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
);

CREATE UNIQUE INDEX owner_begin_day_index ON my_table(owner_id, date_trunc('day', fetched_at AT TIME ZONE 'UTC'));
```

Version switching implies it was introduced at the same time as the UDF problem, but this doesn't seem to be having a problem with the UDF, but the type casting?

**Comment by lukaseder** [comment]
> @ dwilches Is there a workaround for this issue? I just hit the same today.

You can turn off the generation of indexes. On the other hand, it's just an exception in the logs, which generates noise and prevents the generation of this particular index.

> @jbristow Is this error message being caused by the same issue?

Same underlying cause, namely the insufficient parsing of column expressions. But yours is different and could be fixed separately, at least the first problem: https://github.com/jOOQ/jOOQ/issues/12645

Once that's fixed, the parser would still run into issues with that `timezone` expression.

In all of these cases, there isn't really much that can be done about it. The exception is there mainly to get feedback from users what else the parser is missing. You can mute it by turning off info logging in the code generator...

**Comment by lukaseder** [comment]
> @dwilches Is there a workaround for this issue? I just hit the same today.

You can turn off the generation of indexes. On the other hand, it's just an exception in the logs, which generates noise and prevents the generation of this particular index.

> @jbristow Is this error message being caused by the same issue?

Same underlying cause, namely the insufficient parsing of column expressions. But yours is different and could be fixed separately, at least the first problem: https://github.com/jOOQ/jOOQ/issues/12645

Once that's fixed, the parser would still run into issues with that `timezone` expression.

In all of these cases, there isn't really much that can be done about it. The exception is there mainly to get feedback from users what else the parser is missing. You can mute it by turning off info logging in the code generator...
