### ISSUE TITLE
Parser wrongly recognises VERSIONS table alias as keyword

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11621]
The parser fails on this query:

```sql
select versions.a, versions.b from s.t versions
```

The error being:

```
org.jooq.impl.ParserException: Keyword 'BETWEEN' expected: [1:113] ...versions.b from s.t versions[*]
                at org.jooq.impl.ParserContext.expected(ParserImpl.java:12225)
                at org.jooq.impl.ParserImpl.parseKeyword(ParserImpl.java:11687)
                at org.jooq.impl.ParserImpl.parseTableFactor(ParserImpl.java:5733)
                at org.jooq.impl.ParserImpl.parseLateral(ParserImpl.java:5591)
                at org.jooq.impl.ParserImpl.parseTable(ParserImpl.java:5576)
                at org.jooq.impl.ParserImpl.parseTables(ParserImpl.java:5568)
                at org.jooq.impl.ParserImpl.parseQueryPrimary(ParserImpl.java:1503)
                at org.jooq.impl.ParserImpl.parseQueryTerm(ParserImpl.java:1390)
                at org.jooq.impl.ParserImpl.parseQueryExpressionBody(ParserImpl.java:1357)
                at org.jooq.impl.ParserImpl.parseSelect(ParserImpl.java:1136)
                at org.jooq.impl.ParserImpl.parseSelect(ParserImpl.java:1131)
                at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:988)
                at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:672)
                at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:666)
                at org.jooq.impl.ParsingConnection.translate(ParsingConnection.java:72)
```

The keyword we should expect here is `"VERSIONS BETWEEN"`, not just `"VERSIONS"`

A workaround would be to use the `AS` keyword, or a different alias. Both of these work:

```sql
select versions.a, versions.b from s.t as versions
select versions_.a, versions_.b from s.t versions_

```

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.15.0 and 3.14.9 (#11622)
