### ISSUE TITLE
Cannot fetch inline NULL value as array type in HSQLDB

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11679]
It seems we can't do this with HSQLDB:

```java
ctx.select(inline(null, String[].class)).fetch();
```

We're getting:

```
Exception in thread "main" org.jooq.exception.DataAccessException: SQL [select null from (values(1)) as dual(dual) -- SQL rendered with a free trial version of jOOQ 3.15.0-SNAPSHOT]; Error while reading field: null, at JDBC index: 1
	at org.jooq_3.15.0-SNAPSHOT.HSQLDB.debug(Unknown Source)
	at org.jooq_3.15.0-SNAPSHOT.HSQLDB.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2877)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:695)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1436)
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1397)
	at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:217)
	at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:182)
	at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:93)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:289)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:374)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:314)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2818)
	at org.jooq.testscripts.JDBC.main(JDBC.java:25)
Caused by: java.sql.SQLException: Error while reading field: null, at JDBC index: 1
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1548)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1497)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:145)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1421)
	... 9 more
Caused by: java.sql.SQLSyntaxErrorException: incompatible data type in conversion
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCResultSet.getArray(Unknown Source)
	at org.jooq.tools.jdbc.DefaultResultSet.getArray(DefaultResultSet.java:688)
	at org.jooq.impl.CursorImpl$CursorResultSet.getArray(CursorImpl.java:437)
	at org.jooq.impl.DefaultBinding$DefaultArrayBinding.get0(DefaultBinding.java:1203)
	at org.jooq.impl.DefaultBinding$DefaultArrayBinding.get0(DefaultBinding.java:1)
	at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:910)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1538)
	... 13 more
Caused by: org.hsqldb.HsqlException: incompatible data type in conversion
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	... 21 more
```

I've reported this as a bug: https://sourceforge.net/p/hsqldb/bugs/1620. Let's see if Fred Toussi agrees if it's a bug. If he doesn't, we'll work around this in jOOQ.

**Comment by lukaseder** [comment]
Duplicate of https://github.com/jOOQ/jOOQ/issues/13965
