### ISSUE TITLE
Parser can't parse functions receiving operator based string expressions

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11703]
The following is valid syntax in PostgreSQL:

```sql
select lpad(row_number() over (order by c)::text, 10, ' ') from (values(1)) as t(c);
select lpad(row_number() over (order by c) || '', 10, ' ') from (values(1)) as t(c);
select lpad('' || row_number() over (order by c), 10, ' ') from (values(1)) as t(c);
```

But our parser can't parse it:

```
Token ',' expected: [1:26] select lpad(row_number() [*]over (order by c)::text, 10, ' ') from (values(1)) as t(c);
Token ',' expected: [1:26] select lpad(row_number() [*]over (order by c) || '', 10, ' ') from (values(1)) as t(c);
Token ',' expected: [1:32] select lpad('' || row_number() [*]over (order by c), 10, ' ') from (values(1)) as t(c);
```

The problem is that `LPAD()` expects a `Type.S` expression as its first argument (for `String`), and the operators don't seem to transform the type in time. The `Type.S` flag is passed down to `parseTerm()` to prevent considering some expression syntaxes. The motivation here was increased performance, but it's just wrong now.

As a workaround, this works, because it wraps the numeric expression in a string expression:

```sql
select lpad(cast(row_number() over (order by c) as text), 10, ' ') from (values(1)) as t(c);
```

This will probably require a significant change, and will thus not be backported.

**Comment by lukaseder** [comment]
A trivial fix would just remove these type checks, but it will create regressions with ambiguous syntax, e.g. when parsing `POSITION(a IN b)`, where `IN` is parsed eagerly as the `a IN (b)` operator (only to fail later because of a missing `(`). Nothing that can't be solved, just a bug exposing other bugs.

**Comment by lukaseder** [comment]
It seems that a quick fix for this particular case that doesn't lead to regressions in existing tests is to type check only `Type.B`, which causes most trouble in tests. That's not a robust fix. We'll probably have to look ahead a bit, or find a way to give some variant of ambiguous syntax priority. To be investigated if this appears again.

For now, I'm fine with the quick fix.

**Comment by lukaseder** [comment]
E.g. this still doesn't parse:

```sql
lpad((true or false)::text, 2)
```

With:

```
org.jooq.impl.ParserException: Token ')' expected: [1:12] lpad((true [*]or false)::text, 2)
	at org.jooq.impl.DefaultParseContext.expected(ParserImpl.java:13069)
	at org.jooq.impl.DefaultParseContext.parse(ParserImpl.java:12392)
	at org.jooq.impl.DefaultParseContext.parse(ParserImpl.java:12387)
	at org.jooq.impl.DefaultParseContext.parseTerm(ParserImpl.java:7792)
	at org.jooq.impl.DefaultParseContext.parseUnaryOps(ParserImpl.java:6986)
	at org.jooq.impl.DefaultParseContext.parseExp(ParserImpl.java:6963)
	at org.jooq.impl.DefaultParseContext.parseFactor(ParserImpl.java:6940)
	at org.jooq.impl.DefaultParseContext.parseSum(ParserImpl.java:6886)
	at org.jooq.impl.DefaultParseContext.parseNumericOp(ParserImpl.java:6871)
	at org.jooq.impl.DefaultParseContext.parseCollated(ParserImpl.java:6845)
	at org.jooq.impl.DefaultParseContext.parseConcat(ParserImpl.java:6835)
	at org.jooq.impl.DefaultParseContext.parseField(ParserImpl.java:6748)
	at org.jooq.impl.DefaultParseContext.parseFieldLpadIf(ParserImpl.java:9402)
	at org.jooq.impl.DefaultParseContext.parseTerm(ParserImpl.java:7364)
	at org.jooq.impl.DefaultParseContext.parseUnaryOps(ParserImpl.java:6986)
	at org.jooq.impl.DefaultParseContext.parseExp(ParserImpl.java:6963)
	at org.jooq.impl.DefaultParseContext.parseFactor(ParserImpl.java:6940)
	at org.jooq.impl.DefaultParseContext.parseSum(ParserImpl.java:6886)
	at org.jooq.impl.DefaultParseContext.parseNumericOp(ParserImpl.java:6871)
	at org.jooq.impl.DefaultParseContext.parseCollated(ParserImpl.java:6845)
	at org.jooq.impl.DefaultParseContext.parseConcat(ParserImpl.java:6835)
	at org.jooq.impl.DefaultParseContext.parsePredicate(ParserImpl.java:5804)
	at org.jooq.impl.DefaultParseContext.parseNot(ParserImpl.java:5706)
	at org.jooq.impl.DefaultParseContext.parseAnd(ParserImpl.java:5696)
	at org.jooq.impl.DefaultParseContext.parseOr(ParserImpl.java:5687)
	at org.jooq.impl.DefaultParseContext.parseField(ParserImpl.java:6746)
	at org.jooq.impl.DefaultParseContext.parseField(ParserImpl.java:6678)
	at org.jooq.impl.DefaultParseContext.parseField0(ParserImpl.java:568)
	at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:433)
	at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:428)
```

**Comment by lukaseder** [comment]
I'll think about this again. The quick fix still feels too wrong.

**Comment by lukaseder** [comment]
Here's what PostgreSQL does when `IN` is used ambiguously in a function like `POSITION`:

```sql
select position('a' in ('a')::text in 'true')
-- [42601]: ERROR: syntax error at or near "in" Position: 36

select position(('a' in ('a')::text) in 'true')
-- 1
```

So, it seems that the PG parser is in some mode where the function "argument keyword" `IN` is forbidden in all non-parenthesised expressions.

**Comment by lukaseder** [comment]
To make sure that:

- this is fixed correctly
- doesn't lead to new edge case regressions

... I'll implement a test that systematically (or randomly) combines expressions, renders their SQL, and parses the SQL again.
