### ISSUE TITLE
Parsing Bind variables 

### ISSUE THREAD

**Issue by wal1dcha1b** [jOOQ/jOOQ#11734]
### Your question:
Is there a way to cast the bind variable based on the column type ? 
In fact, Oracle does this implicitly, so in our framework we use setString for all the binb variables as described below :

```java
   public static void fillParameters(final String sql, final PreparedStatement pStmt, final Map<String, String> parameters) throws SQLException {
        final char[] statement = sql.toCharArray();
        int i = 0;
        int curs = 1;
        while (i < statement.length) {
            final int skipToPosition = skipCommentsAndQuotes(statement, i);
            if (i != skipToPosition) {
                if (skipToPosition >= statement.length) {
                    break;
                }
                i = skipToPosition;
            }
            final char c = statement[i];
            if (c == ':' || c == '&') {
                int j = i + 1;
                if (j < statement.length && statement[j] == ':' && c == ':') {
                    // Postgres-style "::" casting operator - to be skipped.
                    i = i + 2;
                    continue;
                }
                while (j < statement.length && !isParameterSeparator(statement[j])) {
                    j++;
                }
                if (j - i > 1) {
                    pStmt.setString(curs++, parameters.get(sql.substring(i + 1, j)));
                }
                i = j - 1;
            }
            i++;
        }
    }
```
So i get this postgresql Exception :

```
Caused by: org.postgresql.util.PSQLException: ERREUR: l'opérateur n'existe pas : smallint = character varying
  Indice : Aucun opérateur ne correspond au nom donné et aux types d'arguments.
Vous devez ajouter des conversions explicites de type.
  Position : 1122
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122)
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122)
	at org.jooq.impl.ParsingStatement.executeQuery(ParsingStatement.java:339)
	at com.tbs.bo.services.TbsQueryGeneric.execQuery(TbsQueryGeneric.java:108)
	at com.tbs.bo.services.TbsQueryGeneric.execQuery(TbsQueryGeneric.java:60)
	at com.tbs.bo.services.TbsQueryGeneric.execQuery(TbsQueryGeneric.java:190)
	at com.tbs.sql.TbsExecReq.execReq(TbsExecReq.java:48)
	at com.tbs.sql.TbsExecReq.ExecReq(TbsExecReq.java:73)
	at com.tbs.sql.TbsExecReq.ExecReq(TbsExecReq.java:97)
	at com.tbs.utils.search.SearchPersonne.search(SearchPersonne.java:39)
	at com.tbs.utils.search.SearchPersonne.search(SearchPersonne.java:22)
	at com.tbs.trt.FRechPerWTrt.onFilterCombo(FRechPerWTrt.java:509)
	... 45 more
```

Before asking your question, please check out the FAQ too: https://www.jooq.org/faq

### Versions:

- jOOQ: 3.15
- Java: 1.8
- Database (include vendor): Postgresql
- OS: Open suse
- JDBC Driver (include name if inofficial driver): 4.2

**Comment by lukaseder** [comment]
One solution that I can think of is to use a `VisitListener`. It will allow you to cast a bind variable to a given type. You can access the context of the bind variable using `VisitContext::queryParts`, but it won't lead to very robust solutions, and you'll need reflection or to open up the jOOQ module to access the internals (specifically, `org.jooq.impl.CompareCondition` for most cases).

Another option is to patch the `CompareCondition` and make sure it casts automatically. Of course, this feature would help: https://github.com/jOOQ/jOOQ/issues/11628
