### ISSUE TITLE
Named parameter mapping doesn't work with missing or excess source column values

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11783]
Assuming the following immutable types with `@ConstructorProperties` for named parameter mapping (alternatively, turn on named parameter mapping for records in jOOQ 3.15 in the JDK 17 distribution: https://github.com/jOOQ/jOOQ/issues/11778)

```java
record Team(String name, int rank) {
    @ConstructorProperties({ "name", "rank" })
    Team {}
}

record Player (String firstName, String lastName, Team team) {
    @ConstructorProperties({ "firstName", "lastName", "team" })
    Player {}
}
```

The following doesn't work, because there's an extra column which cannot be mapped.

```java
var result =
// Alternatively, turn on new feature: https://github.com/jOOQ/jOOQ/issues/11778
DSL.using(connection, new Settings().withMapRecordComponentParameterNames(false))
   .select(
       val("X").as("firstName"),
       val("Y").as("lastName"),
       val("Z").as("team.name"),
       val("1").as("team.rank"),
       val("10").as("_count"))
   .fetchInto(Player.class);

System.out.println(result);
```

The exception is:

```
Exception in thread "main" org.jooq.exception.MappingException: An error ocurred when mapping record to class org.jooq.testscripts.JDBC$1Player
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.map(DefaultRecordMapper.java:993)
	at org.jooq.impl.DefaultRecordMapper.map(DefaultRecordMapper.java:549)
	at org.jooq.impl.ResultImpl.into(ResultImpl.java:1190)
	at org.jooq.impl.ResultQueryTrait.fetchInto(ResultQueryTrait.java:1360)
	at org.jooq.testscripts.JDBC.main(JDBC.java:48)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.mapNested(DefaultRecordMapper.java:1015)
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.map(DefaultRecordMapper.java:990)
	... 4 more
```

The extra column should just be ignored.

As reported here https://github.com/jOOQ/jOOQ/issues/11782 by @archerz

**Comment by lukaseder** [comment]
A similar exception is thrown when we're missing source fields:

```
org.jooq.exception.MappingException: An error ocurred when mapping record to class org.jooq.test.RecordMappingTest$ImmutableWithCPOuter
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.map(DefaultRecordMapper.java:993)
	at org.jooq.impl.DefaultRecordMapper.map(DefaultRecordMapper.java:549)
	at org.jooq.impl.AbstractRecord.into(AbstractRecord.java:813)
	at org.jooq.test.RecordMappingTest.testNestedConstructorPropertiesWithMissingSourceFields(RecordMappingTest.java:866)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:768)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: org.jooq.exception.MappingException: An error ocurred when mapping record to class org.jooq.test.RecordMappingTest$ImmutableWithCPInner1
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.map(DefaultRecordMapper.java:993)
	at org.jooq.impl.DefaultRecordMapper.map(DefaultRecordMapper.java:549)
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.mapNested(DefaultRecordMapper.java:1020)
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.map(DefaultRecordMapper.java:990)
	... 32 more
Caused by: org.jooq.exception.DataTypeException: No Converter found for types java.lang.String and org.jooq.test.RecordMappingTest$ImmutableWithCPInner2
	at org.jooq.impl.Tools.converterOrFail(Tools.java:1161)
	at org.jooq.impl.Tools.converterOrFail(Tools.java:1170)
	at org.jooq.impl.AbstractRecord.get(AbstractRecord.java:358)
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.mapNested(DefaultRecordMapper.java:1015)
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.map(DefaultRecordMapper.java:990)
	... 35 more
```

**Comment by lukaseder** [comment]
This bug was created as a bug assuming that missing source fields were OK, and thus excess source fields should be OK as well. But if both are currently not working, let's reconsider if this is really a bug or a breaking change / feature request.

**Comment by lukaseder** [comment]
It does look like a bug. The nesting logic doesn't work at all when source fields don't match expected constructors.

**Comment by lukaseder** [comment]
Things also don't work if we shuffle the mapped prefixes, so the order of field names seems important! This is clearly not the intention of the named parameter mapping, and specific to the nesting algorithm.

**Comment by lukaseder** [comment]
The fix is rather delicate, introducing a risk for regressions, which is why I won't backport the fix to 3.14.

**Comment by lukaseder** [comment]
The fix will get this to work:

```java
@Test
public void testMapNestedRecordsShufflePrefixes() {
    record RecordInner2(String c) {}
    record RecordInner1(String b, RecordInner2 inner, String d) {}
    record RecordOuter(String a, RecordInner1 inner, String e) {}

    Field<String> a = field("a", VARCHAR);
    Field<String> x = field("x", VARCHAR);
    Field<String> b = field("inner.b", VARCHAR);
    Field<String> c = field("inner.inner.c", VARCHAR);
    Field<String> y = field("inner.inner.y", VARCHAR);
    Field<String> z = field("inner.z", VARCHAR);
    Field<String> d = field("inner.d", VARCHAR);
    Field<String> e = field("e", VARCHAR);

    // Shuffle
    @SuppressWarnings("unchecked")
    Field<String>[] a1 = new Field[] { a, b, c, d, e };

    forPermutationsOf(a1, fields -> {
        RecordOuter record = record(fields).into(RecordOuter.class);

        assertEquals("a", record.a);
        assertEquals("b", record.inner.b);
        assertEquals("c", record.inner.inner.c);
        assertEquals("d", record.inner.d);
        assertEquals("e", record.e);
    });

    // Excess columns
    @SuppressWarnings("unchecked")
    Field<String>[] a2 = new Field[] { a, b, c, d, e, x, y, z };

    forPermutationsOf(a2, fields -> {
        RecordOuter record = record(fields).into(RecordOuter.class);

        assertEquals("a", record.a);
        assertEquals("b", record.inner.b);
        assertEquals("c", record.inner.inner.c);
        assertEquals("d", record.inner.d);
        assertEquals("e", record.e);
    });

    // Missing columns
    @SuppressWarnings("unchecked")
    Field<String>[] a3 = new Field[] { a, c, d };

    forPermutationsOf(a3, fields -> {
        RecordOuter record = record(fields).into(RecordOuter.class);

        assertEquals("a", record.a);
        assertNull(record.inner.b);
        assertEquals("c", record.inner.inner.c);
        assertEquals("d", record.inner.d);
        assertNull(record.e);
    });
}
```

The `forPermutationsOf()` utility is similar to what can be found here: https://www.baeldung.com/java-array-permutations, producing all permutations of the fields array.

**Comment by archerz** [comment]
Ah-mazing! 🎉 Thanks a lot for the prompt fix, @lukaseder.
