### ISSUE TITLE
Invalid MySQL SQL syntax for UNION after updating to 3.13.x

### ISSUE THREAD

**Issue by cheister** [jOOQ/jOOQ#11827]
### Expected behavior
I'm updating from JOOQ 3.12.2 to 3.13.6 and getting a MySQL syntax error from a query with a UNION in the where clause

### Actual behavior
When updating to JOOQ 3.13.6 or 3.14.9 I get the error:
```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'values row ('ITEM-ID-4')) as `v`
            ) as `v`
          ) as `itemTokens' at line 85
```

The SQL generated in 3.12.2 is
```
from `generic_orders`
  join (
    `line_items`
      join (
        select item_token
        from (
          (
            select `label_memberships`.`item_token`
            from `labels`
              join `label_memberships`
                on `labels`.`id` = `label_memberships`.`label_id`
            where `labels`.`token` in ('75c983f8-0b8a-462d-8690-8f8d19c56522')
          )
          union (
            select `itemTokens`.`token`
            from (
              (
                select null as `token`
                from dual
                where 1 = 0
              )
              union all (
                select `v`.`c1`
                from (
                  (
                    select null as `c1`
                    from dual
                    where 1 = 0
                  )
                  union all (
                    select *
                    from (
                      select 'ITEM-ID-4'
                      from dual
                    ) as `v`
                  )
                ) as `v`
              )
            ) as `itemTokens`
          )
        ) as `alias_17570417`
      ) as `alias_132811240`
        on `line_items`.`item_id` = `alias_132811240`.`item_token`
  )
    on `generic_orders`.`id` = `line_items`.`generic_order_id`
where (
  `generic_orders`.`merchant_token` = 'MERCHANT-TOKEN'
  and `generic_orders`.`fulfillment_type` = 'ELECTRONIC'
  and `generic_orders`.`created_at` >= {ts '2021-04-28 19:21:13.276'}
  and `generic_orders`.`created_at` < {ts '2021-04-28 19:23:13.276'}
)
```

The SQL generated in 3.13.6 and 3.14.9 is
```
from `generic_orders`
  join (
    `line_items`
      join (
        select item_token
        from (
          select `label_memberships`.`item_token`
          from `labels`
            join `label_memberships`
              on `labels`.`id` = `label_memberships`.`label_id`
          where `labels`.`token` in ('f8ad3432-ab90-451d-b439-e8102ab245b0')
          union
          select `itemTokens`.`token`
          from (
            select null as `token`
            from dual
            where false
            union all
            select `v`.`c1`
            from (
              select null as `c1`
              from dual
              where false
              union all
              select *
              from (values row ('ITEM-ID-4')) as `v`
            ) as `v`
          ) as `itemTokens`
        ) as `alias_95684067`
      ) as `alias_16145839`
        on `line_items`.`item_id` = `alias_16145839`.item_token
  )
    on `generic_orders`.`id` = `line_items`.`generic_order_id`
where (
  `generic_orders`.`merchant_token` = 'MERCHANT-TOKEN'
  and `generic_orders`.`fulfillment_type` = 'ELECTRONIC'
  and `generic_orders`.`created_at` >= {ts '2021-05-01 20:23:44.05'}
  and `generic_orders`.`created_at` < {ts '2021-05-01 20:25:44.05'}
)
```

And the exception is

```
from `generic_orders`
  join (
    `line_items`
      join (
        select item_token
        from (
          select `label_memberships`.`item_token`
          from `labels`
            join `label_memberships`
              on `labels`.`id` = `label_memberships`.`label_id`
          where `labels`.`token` in (?)
          union
          select `itemTokens`.`token`
          from (
            select null as `token`
            from dual
            where false
            union all
            select `v`.`c1`
            from (
              select null as `c1`
              from dual
              where false
              union all
              select *
              from (values row (?)) as `v`
            ) as `v`
          ) as `itemTokens`
        ) as `alias_95684067`
      ) as `alias_16145839`
        on `line_items`.`item_id` = `alias_16145839`.item_token
  )
    on `generic_orders`.`id` = `line_items`.`generic_order_id`
where (
  `generic_orders`.`merchant_token` = ?
  and `generic_orders`.`fulfillment_type` = ?
  and `generic_orders`.`created_at` >= ?
  and `generic_orders`.`created_at` < ?
)]; You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'values row ('ITEM-ID-4')) as `v`
            ) as `v`
          ) as `itemTokens' at line 85
org.jooq.exception.DataAccessException: 
	at org.jooq_3.14.9.MYSQL.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2903)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:757)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:389)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:332)
	at org.jooq.impl.AbstractResultQuery.fetchInto(AbstractResultQuery.java:1508)
	at org.jooq.impl.SelectImpl.fetchInto(SelectImpl.java:3941)
```

### Steps to reproduce the problem

I'll work on creating a jooq-MCVE and post back here if I can reproduce the error there.

### Versions

- jOOQ: 3.13.6 or 3.14.9
- Java: openjdk 11.0.9
- Database (include vendor): mysql  Ver 14.14 Distrib 5.7.27-30, for osx10.15 (x86_64)
- OS: macOS Big Sur (11.3)
- JDBC Driver (include name if inofficial driver): com.mysql.cj.jdbc.Driver

**Comment by lukaseder** [comment]
Thanks a lot for your support request. I'm assuming you're using the jOOQ Open Source Edition. The last version of the jOOQ Open Source Edition that officially supported MySQL 5.7 was jOOQ 3.9. Starting from jOOQ 3.10, the jOOQ Open Source Edition required MySQL 8
https://www.jooq.org/download/support-matrix

Some things may still have worked after jOOQ 3.9 on MySQL 5.7, but there was no guarantee for them to work. This particular feature was changed with the introduction of `SQLDialect.MYSQL_8_0_19` (https://github.com/jOOQ/jOOQ/issues/9772) in jOOQ 3.13, which allowed us to finally support the `VALUES()` constructor natively in MySQL as well (https://github.com/jOOQ/jOOQ/issues/9776), which avoids this very verbose emulation that you still require on MySQL 5.7.

From how I see it, you have these options:

- Upgrade to the jOOQ Professional Edition which still supports MySQL 5.7 (recommended, as it will be the least intrusive option).
- Upgrade your MySQL version to 8.0.19 or newer (also recommended, you get a vast array of new MySQL features, but is obviously more effort than upgrading jOOQ)
- Downgrade your jOOQ version to the last version that was known to produce the old syntax
- Avoid this particular syntax, or emulate it manually (not recommended as other, similar limitations of jOOQ no longer supporting MySQL 5.7 may surface, e.g. this improvement due for jOOQ 3.15 will have quite some impact: https://github.com/jOOQ/jOOQ/issues/7421)
