### ISSUE TITLE
Implement improved INSERT .. ON DUPLICATE KEY UPDATE emulation via MERGE

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11880]
A few SQL dialects seem to have trouble when executing `MERGE` statements that don't actually `JOIN` the target table and the `USING` table. Our current emulation of `INSERT .. ON DUPLICATE KEY UPDATE` (and also `ON CONFLICT DO UPDATE`) looks like this:

```sql
merge into "TEST"."T_DATES"
using (
  select 1 "one"
)
on "TEST"."T_DATES"."ID" = 1
when matched then update set
  "TEST"."T_DATES"."TS" = timestamp '1970-01-01 00:00:00.0'
when not matched then insert ("ID", "TS")
values (
  1, 
  timestamp '1970-01-01 00:00:00.0'
)
```

In Exasol, this produces the following error:

```
org.jooq.exception.DataAccessException: SQL [merge into "TEST"."T_DATES" using (select 1 "one") on "TEST"."T_DATES"."ID" = cast(? as int) when matched then update set "TEST"."T_DATES"."TS" = ? when not matched then insert ("ID", "TS") values (?, ?)]; such a merge condition is not supported! Join-condition needed (Session: 1699556181301460992)
	at org.jooq_3.15.0-SNAPSHOT.EXASOL.debug(Unknown Source) ~[?:?]
	at org.jooq.impl.Tools.translate(Tools.java:2832) ~[classes/:?]
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:661) ~[classes/:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:346) [classes/:?]
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:111) [classes/:?]
	at org.jooq.test.all.testcases.InsertUpdateTests.testInsertOnConflictDoUpdate(InsertUpdateTests.java:702) [test-classes/:?]
	at org.jooq.test.jOOQAbstractTest.testInsertOnConflictDoUpdate(jOOQAbstractTest.java:1599) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.13.1.jar:4.13.1]
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) [junit-4.13.1.jar:4.13.1]
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:768) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
Caused by: java.sql.SQLException: such a merge condition is not supported! Join-condition needed (Session: 1699556181301460992)
	at com.exasol.jdbc.ExceptionFactory.createSQLException(ExceptionFactory.java:242) ~[exasol-jdbc-7.0.7.jar:1.0]
	at com.exasol.jdbc.ExceptionFactory.createSQLException(ExceptionFactory.java:21) ~[exasol-jdbc-7.0.7.jar:1.0]
	at com.exasol.jdbc.AbstractEXAPreparedStatement.<init>(AbstractEXAPreparedStatement.java:68) ~[exasol-jdbc-7.0.7.jar:1.0]
	at com.exasol.jdbc.EXAPreparedStatement.<init>(EXAPreparedStatement.java:14) ~[exasol-jdbc-7.0.7.jar:1.0]
	at com.exasol.jdbc.DialectGeneric.createPreparedStatement(DialectGeneric.java:10) ~[exasol-jdbc-7.0.7.jar:1.0]
	at com.exasol.jdbc.AbstractEXAConnection.prepareStatement(AbstractEXAConnection.java:1084) ~[exasol-jdbc-7.0.7.jar:1.0]
	at org.jooq.tools.jdbc.DefaultConnection.prepareStatement(DefaultConnection.java:95) ~[classes/:?]
	at org.jooq.test.utils.LoggingConnection.prepareStatement(LoggingConnection.java:68) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.springframework.jdbc.datasource.SingleConnectionDataSource$CloseSuppressingInvocationHandler.invoke(SingleConnectionDataSource.java:325) ~[spring-jdbc-5.3.2.jar:5.3.2]
	at jdk.proxy2.$Proxy29.prepareStatement(Unknown Source) ~[?:?]
	at org.jooq.impl.ProviderEnabledConnection.prepareStatement(ProviderEnabledConnection.java:109) ~[classes/:?]
	at org.jooq.impl.SettingsEnabledConnection.prepareStatement(SettingsEnabledConnection.java:82) ~[classes/:?]
	at org.jooq.impl.AbstractQuery.prepare(AbstractQuery.java:395) ~[classes/:?]
	at org.jooq.impl.AbstractDMLQuery.prepare0(AbstractDMLQuery.java:834) ~[classes/:?]
	at org.jooq.impl.AbstractDMLQuery.prepare(AbstractDMLQuery.java:825) ~[classes/:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:299) ~[classes/:?]
	... 34 more
```

This, on the other hand, would work:

```sql
merge into "TEST"."T_DATES"
using (
  select 1 "ID",  timestamp '1970-01-01 00:00:00.0' "TS" from (values (1)) t
) "s"
on "TEST"."T_DATES"."ID" = "s"."ID"
when matched then update set
  "TEST"."T_DATES"."TS" = "s"."TS"
when not matched then insert ("ID", "TS")
values ("s"."ID", "s"."TS")
```

As a side-effect, we'd also avoid repeating the bind values, which reduces network traffic, see https://github.com/jOOQ/jOOQ/issues/11770

**Comment by lukaseder** [comment]
Interestingly enough, we're already moving the inserted data into the `USING` clause when emulating a multi row `INSERT .. ON DUPLICATE KEY UPDATE` query, e.g.

```sql
INSERT INTO t (a, b)
VALUES (1, 2), (3, 4)
ON DUPLICATE KEY UPDATE SET b = ...
```

**Comment by lukaseder** [comment]
Related issue: https://github.com/jOOQ/jOOQ/issues/8937

**Comment by lukaseder** [comment]
The change doesn't work in a few dialects, including e.g. Derby
