### ISSUE TITLE
Get Redshift dialect up to date

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11961]
A variety of recently added features / improvements have not yet been applied to the `REDSHIFT` dialect. These include:

**Queries**

- [x] It seems there's a regression when using bind values in `LIMIT` with `ORDER BY`, which produces an error (https://github.com/jOOQ/jOOQ/issues/11961#issuecomment-853965930)
- [x] Oracle `(+)` operator for outer joins is supported: https://docs.aws.amazon.com/redshift/latest/dg/r_WHERE_oracle_outer.html
- [x] `OFFSET` is now supported

**DDL**

- [x] `CREATE SCHEMA`, `ALTER SCHEMA`, `DROP SCHEMA`

**Function support**

- [x] Bitwise aggregate function support
- [x] Bitwise function support
- [x] `CURRENT_TIME()` doesn't exist, it's `CURRENT_TIME` instead
- [x] `LISTAGG()` aggregate function: https://docs.aws.amazon.com/redshift/latest/dg/r_LISTAGG.html
- [x] `MEDIAN()` aggregate function: https://docs.aws.amazon.com/redshift/latest/dg/r_MEDIAN.html

**Comment by lukaseder** [comment]
There seems to be a regression when using bind values in `LIMIT` with `ORDER BY`. Many tests are now failing with an exception like this:

```
org.jooq.exception.DataAccessException: SQL [select * from t_book order by id limit ? -- SQL rendered with a free trial version of jOOQ 3.15.0-SNAPSHOT]; ERROR: Not implemented
  Detail: 
  -----------------------------------------------
  error:  Not implemented
  code:      1001
  context:   'IsA(cons, Const)' - 
  query:     23918
  location:  pg_utils.cpp:6030
  process:   padbmaster [pid=1324]
  -----------------------------------------------

	at org.jooq_3.15.0-SNAPSHOT.REDSHIFT.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2888)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:661)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:346)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:284)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2812)
	at org.jooq.test.all.testcases.PlainSQLTests.testPlainSQLLimit(PlainSQLTests.java:652)
	at org.jooq.test.jOOQAbstractTest.testPlainSQLLimit(jOOQAbstractTest.java:3673)
```

**Comment by lukaseder** [comment]
The limit issue has been fixed already, the problem no longer reproduces in integration tests.
