### ISSUE TITLE
Add support for nested collections in SYS_REFCURSOR OUT parameters

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11962]
It seems this kind of procedure result can't be handled by jOOQ:

```sql
PROCEDURE read_accountHierarchy(
            in_period IN VARCHAR2,
            out_hierarchy OUT sys_refcursor )
    AS
    BEGIN
    OPEN out_hierarchy FOR 
       SELECT hierarchy_type ( top_level_bank_id,top_level_account_number, hierarchy_type , 
        CAST ( MULTISET (SELECT hierarchy_account_type( hierarchies.bank_id,hierarchies.account_number,hierarchies.acc_level,
             		                                       hierarchies.account_path_ids  ) FROM ...
```

An error similar to this one appears:

```
Caused by: org.jooq.exception.DataTypeException: Cannot cast from class java.lang.Object (instance type: class oracle.sql.STRUCT to class java.lang.Object
	at org.jooq.impl.DefaultConverterProvider$2.from(DefaultConverterProvider.java:155)
	at org.jooq.impl.AbstractRecord.get(AbstractRecord.java:284)
	at org.jooq.impl.DefaultRecordMapper$ValueTypeMapper.map(DefaultRecordMapper.java:605)
	at org.jooq.impl.DefaultRecordMapper.map(DefaultRecordMapper.java:548)
```

Workarounds may include:

- Declaring the result as a view and returning that instead
- Returning a table type with nested table types, instead of a `SYS_REFCURSOR`

----
See also: 
https://groups.google.com/g/jooq-user/c/-K20FspfhvE

**Comment by lukaseder** [comment]
This no longer reproduces. Given:

```sql
CREATE OR REPLACE PROCEDURE p_rc (i IN NUMBER, o OUT sys_refcursor)
AS 
BEGIN
  OPEN o FOR SELECT u_number_array(1, 2);
END;
```

Calling:

```java
println(Routines.pRc(configuration, 1));
```

Simply yields:

```
+-------------------------+
|U_NUMBER_ARRAY(1,2)      |
+-------------------------+
|oracle.sql.ARRAY@34be065a|
+-------------------------+
```

Which is acceptable
