### ISSUE TITLE
PostgresDatabase should ignore unknown functions when parsing index column expressions

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11977]
When trying to parse index column expressions in PostgreSQL to handle quoted identifiers and other things (https://github.com/jOOQ/jOOQ/issues/11047), we get the following error:

```
INFO: Generating table         : Alias.java [input=alias, output=alias, pk=alias_pkey]
Jun 08, 2021 4:45:35 PM org.jooq.tools.JooqLogger info
INFO: Parse error              : Error when parsing column name : pv(events_less, events_equal, events_greater, 0)
org.jooq.impl.ParserException: Unknown function: [1:4] pv([*]events_less, events_equal, events_greater, 0)
    at org.jooq.impl.ParserContext.exception(ParserImpl.java:12258)
    at org.jooq.impl.ParserImpl.parseUnaryOps(ParserImpl.java:6557)
    at org.jooq.impl.ParserImpl.parseExp(ParserImpl.java:6521)
    at org.jooq.impl.ParserImpl.parseFactor(ParserImpl.java:6498)
    at org.jooq.impl.ParserImpl.parseSum(ParserImpl.java:6444)
    at org.jooq.impl.ParserImpl.parseNumericOp(ParserImpl.java:6429)
    at org.jooq.impl.ParserImpl.parseCollated(ParserImpl.java:6403)
    at org.jooq.impl.ParserImpl.parseConcat(ParserImpl.java:6393)
    at org.jooq.impl.ParserImpl.parsePredicate(ParserImpl.java:5323)
    at org.jooq.impl.ParserImpl.parseNot(ParserImpl.java:5253)
    at org.jooq.impl.ParserImpl.parseAnd(ParserImpl.java:5243)
    at org.jooq.impl.ParserImpl.parseOr(ParserImpl.java:5234)
    at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:6310)
    at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:6235)
    at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:764)
    at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:758)
    at org.jooq.meta.postgres.PostgresDatabase.tryParseColumnName(PostgresDatabase.java:266)
    at org.jooq.meta.postgres.PostgresDatabase.getIndexes0(PostgresDatabase.java:226)
    at org.jooq.meta.AbstractDatabase$14.run(AbstractDatabase.java:2338)
    at org.jooq.meta.AbstractDatabase.onError(AbstractDatabase.java:3094)
    at org.jooq.meta.AbstractDatabase.getIndexes(AbstractDatabase.java:2335)
    at org.jooq.meta.AbstractDatabase.getIndexes(AbstractDatabase.java:2369)
    at org.jooq.meta.AbstractTableDefinition.getIndexes(AbstractTableDefinition.java:99)
    at org.jooq.codegen.JavaGenerator.generateTable(JavaGenerator.java:5327)
    at org.jooq.codegen.JavaGenerator.generateTable(JavaGenerator.java:5038)
    at org.jooq.codegen.JavaGenerator.generateTables(JavaGenerator.java:5012)
    at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:582)
    at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:537)
    at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:436)
    at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:879)
    at org.jooq.codegen.GenerationTool.run(GenerationTool.java:233)
    at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:228)
    at org.jooq.codegen.GenerationTool.main(GenerationTool.java:200)
```

Unknown functions should be ignored by the parser at first, and later on, supported via function based index support: https://github.com/jOOQ/jOOQ/issues/6310

----
See also:
https://groups.google.com/g/jooq-user/c/fl-dUpRT42s

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.15
