### ISSUE TITLE
Caused by: org.jooq.exception.DataTypeException: No Converter found for types java.lang.Object and java.util.Map

### ISSUE THREAD

**Issue by sothavirak** [jOOQ/jOOQ#12024]
### Your question:

From 3.14.0 version onward, above error starts to throw when mapping Collection to into Map inside a POJO class. Is it a bug or manual mapper is required?

### Versions:

- jOOQ: 3.14.0
- Java: 1.8
- Database (include vendor): Postgres
- OS: Window
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks a lot for your message. Hard to say. Can you show actual code?

**Comment by sothavirak** [comment]
List<Config> updatedConfig = jooq.update(CONFIG_TABLE)
                .set(...)
                .where(whereCondition)
                .returning(FIELD_IDENTIFIERS)
                .fetch()
                .into(Student.class);   // error thrown from here

public class Student {
    private final Map<String, String> identifiers;
}

Stacktrace:
An error ocurred when mapping record to class com.demo.Student
org.jooq.exception.MappingException: An error ocurred when mapping record to class com.demo.Student
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.map(DefaultRecordMapper.java:1019)
	at org.jooq.impl.DefaultRecordMapper.map(DefaultRecordMapper.java:548)
	at org.jooq.impl.ResultImpl.into(ResultImpl.java:1280)
Caused by: org.jooq.exception.DataTypeException: No Converter found for types java.lang.Object and java.util.Map
	at org.jooq.impl.Tools.converterOrFail(Tools.java:1149)
	at org.jooq.impl.Tools.converterOrFail(Tools.java:1165)
	at org.jooq.impl.AbstractRecord.get(AbstractRecord.java:285)
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.set(DefaultRecordMapper.java:1062)
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.mapNonnested(DefaultRecordMapper.java:1031)
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.map(DefaultRecordMapper.java:1016)
	... 55 more

**Comment by lukaseder** [comment]
Thanks. I'm assuming you used the PostgreSQL `hstore` data type and were expecting that to be automatically mapped to a `Map<String, String>`? jOOQ 3.14 doesn't support  `hstore` out of the box yet. The soon-to-be-released version 3.15 will ship with an extension module that contains a `Converter` and a `Binding`, which you can use, see:

- https://github.com/jOOQ/jOOQ/issues/994
- https://github.com/jOOQ/jOOQ/issues/5507

Even with those extensions, you'll need to configure the code generator accordingly, see: https://www.jooq.org/doc/latest/manual/code-generation/custom-data-type-bindings

I hope this helps
