### ISSUE TITLE
Timestamp Arithmetic fails with ConvertedDataType

### ISSUE THREAD

**Issue by Skym0sh0** [jOOQ/jOOQ#12036]
### Expected behavior
The query in the example code runs successfully and the assertions are fulfilled. More detailed, I expect the timestamp arithmetic to work properly with a converted datatype.

### Actual behavior
A conversion from an DayToSecond to LocalDateTime fails.
```
org.jooq.exception.DataTypeException: Cannot convert from +0 00:00:00.000000000 (class org.jooq.types.DayToSecond) to class java.time.LocalDateTime

	at org.jooq.tools.Convert$ConvertAll.fail(Convert.java:1315)
	at org.jooq.tools.Convert$ConvertAll.from(Convert.java:1214)
	at org.jooq.tools.Convert.convert0(Convert.java:394)
	at org.jooq.tools.Convert.convert(Convert.java:467)
	at org.jooq.impl.AbstractDataType.convert(AbstractDataType.java:534)
	at org.jooq.impl.DefaultDataType.convert(DefaultDataType.java:92)
	at org.jooq.impl.ConvertedDataType.convert(ConvertedDataType.java:197)
	at org.jooq.impl.Val.convertTo0(Val.java:114)
	at org.jooq.impl.Val.convertTo(Val.java:102)
	at org.jooq.impl.DSL.nullSafe(DSL.java:26243)
	at org.jooq.impl.AbstractField.sub(AbstractField.java:360)
	at org.jooq.impl.AbstractField.sub(AbstractField.java:355)
	at org.jooq.impl.AbstractField.minus(AbstractField.java:419)
	at de.foobar.MyJooqTest.testReproduce(CumulatedThresholdApplicationTests.java:74)
```

Interestingly, this does not fail during query execution but before during java-sided timestamp arithmetics.

### Steps to reproduce the problem

```
@ParameterizedTest
@ValueSource(ints = {0, 4, 10, 24, 26, 50, 72})
void testReproduce(int hours) {
    try (CloseableDSLContext ctx = DSL.using("jdbc:h2:mem:")) {
        var ts = ZonedDateTime.now(TimeUtils.ZONE_UTC).withNano(0);
        var dur = Duration.ofHours(hours);
        var dayToSecond = DayToSecond.valueOf(dur);

        var type = DSL.getDataType(LocalDateTime.class)
                .asConvertedDataType(Converter.ofNullable(
                        LocalDateTime.class, ZonedDateTime.class,
                        t -> t.atZone(ZoneOffset.UTC),
                        ZonedDateTime::toLocalDateTime
                ));

        var tsField = DSL.value(ts, type);
        var rec = ctx.select(tsField.as("ts"), tsField.minus(dayToSecond).as("calc"))
                .from(DSL.table("dual"))
                .fetchOne();

        Assertions.assertNotNull(rec);
        Assertions.assertEquals(ts, rec.getValue("ts", ZonedDateTime.class));
        Assertions.assertEquals(ts.minus(dur), rec.getValue("calc", ZonedDateTime.class));
    }
}
```
This is a reproducing but synthetic example. In my actual work I have several tables with timestamp columns for which I have registered a converter to ZonedDateTime.
For earlier jOOQ version (3.12.1) the jOOQ code generation had not yet adopted the java.util.time Classes where this converter converted a java.util.Timestamp to java.time.ZonedDatetime. Now it has to convert LocalDateTime to ZonedDateTime.
This is why I used the `asConvertedDataType`.
When I directly use `var tsField = DSL.value(ts);` everything works as expected.

### Versions

- jOOQ: 3.14.11-pro
- Java: 11
- Database (include vendor): H2
- OS: Windows
- JDBC Driver (include name if inofficial driver): h2 1.4.200

**Comment by lukaseder** [comment]
Thanks a lot for your report. A related issue is https://github.com/jOOQ/jOOQ/issues/11959.

The idea is that for many operators, we're trying to apply the `Converter` or `Binding` of the expressions left side to the right side as well (e.g. `x.eq(y)`). This is incorrect for `+`, `-`, and `*` when intervals are involved. I don't think it's related to using `java.sql` or `java.time` types, it would happen in both cases.

**Comment by austermann** [comment]
One of our Microservices is stucked to jooq 3.12 due to this bug.
I would really appreciate it if the next release would contain a fix for this.

**Comment by lukaseder** [comment]
Thanks for the ping, @austermann. I think this can be fixed for those cases in https://github.com/jOOQ/jOOQ/issues/11959 where the `<T>` type is already correct, such as the expression shown here.

Note that for every such limitation, there's always an escape hatch via plain SQL templating: https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating

In any case, I'll look into this right away.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.17.0, 3.16.4 (https://github.com/jOOQ/jOOQ/issues/12946), and 3.15.8 (https://github.com/jOOQ/jOOQ/issues/12947)

**Comment by austermann** [comment]
Thanks, @lukaseder +1
