### ISSUE TITLE
Informix can't handle bind values as arguments to NVL() or COALESCE()

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12064]
It seems this doesn't work in Informix:

```java
static void jdbc(Connection connection) throws SQLException {
    try (PreparedStatement s = connection.prepareStatement("select nvl('a', ?)")) {
        s.setString(1, "b");

        try (ResultSet rs = s.executeQuery()) {
            while (rs.next()) {
                System.out.println(rs.getString(1));
                System.out.println(rs.wasNull());
            }
        }
    }
}
```

There's an error:

```
Exception in thread "main" java.sql.SQLException: A syntax error has occurred.
	at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:413)
	at com.informix.jdbc.IfxSqli.a(IfxSqli.java:3127)
	at com.informix.jdbc.IfxSqli.E(IfxSqli.java:3407)
	at com.informix.jdbc.IfxSqli.dispatchMsg(IfxSqli.java:2324)
	at com.informix.jdbc.IfxSqli.receiveMessage(IfxSqli.java:2249)
	at com.informix.jdbc.IfxSqli.executePrepare(IfxSqli.java:1225)
	at com.informix.jdbc.IfxPreparedStatement.f(IfxPreparedStatement.java:326)
	at com.informix.jdbc.IfxPreparedStatement.a(IfxPreparedStatement.java:306)
	at com.informix.jdbc.IfxPreparedStatement.<init>(IfxPreparedStatement.java:176)
	at com.informix.jdbc.IfxSqliConnect.h(IfxSqliConnect.java:6023)
	at com.informix.jdbc.IfxSqliConnect.prepareStatement(IfxSqliConnect.java:2391)
	at org.jooq.testscripts.JDBC.jdbc(JDBC.java:43)
	at org.jooq.testscripts.JDBC.main(JDBC.java:36)
Caused by: java.sql.SQLException
	at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:413)
	at com.informix.jdbc.IfxSqli.E(IfxSqli.java:3412)
	... 10 more
```

**Comment by lukaseder** [comment]
The usual cast (which we're generating) doesn't work either:

```sql
select nvl('a', cast(? as lvarchar(1)))
```

But this seems to work!

```sql
select nvl('a', (select cast(? as lvarchar(1))))
```

Absurd 😀

**Comment by lukaseder** [comment]
Let's try upgrading the JDBC driver first. Ours is very old

**Comment by lukaseder** [comment]
Nope, still fails with the newer driver
