### ISSUE TITLE
Postgres dialect changes

### ISSUE THREAD

**Issue by MirkoTeran** [jOOQ/jOOQ#12114]
### Your question:

I have a connection to PostgreSQL 9.6. With setting SQLDialect to POSTGRES_9_5 it works great:

Log 1:
```
08:37:23.502 [Main] DEBUG o.j.t.LoggerListener - Executing query          : 
SELECT configuration.id, configuration.created, configuration.code, configuration.value, configuration.account_id, configuration.workspace_id
FROM configuration
WHERE (
  configuration.code = ?
  AND configuration.workspace_id IS NULL
)
ORDER BY configuration.id ASC
LIMIT ?
08:37:23.502 [Main] DEBUG o.j.t.LoggerListener - -> with bind values      : 
SELECT configuration.id, configuration.created, configuration.code, configuration.value, configuration.account_id, configuration.workspace_id
FROM configuration
WHERE (
  configuration.code = 'geo.core'
  AND configuration.workspace_id IS NULL
)
ORDER BY configuration.id ASC
LIMIT 1
08:37:23.518 [Main] TRACE o.j.t.LoggerListener - Record fetched           : +----+--------------------------+--------+--------------------------------------------------+----------+------------+
08:37:23.518 [Main] TRACE o.j.t.LoggerListener -                          : |  id|created                   |code    |value                                             |account_id|workspace_id|
```

Changing dialect to POSTGRES (without specific version) we are getting errors:

Log 2:
```
08:30:14.415 [Main] DEBUG o.j.t.LoggerListener - Executing query          : 
SELECT configuration.id, configuration.created, configuration.code, configuration.value, configuration.account_id, configuration.workspace_id
FROM configuration
WHERE (
  configuration.code = ?
  AND configuration.workspace_id IS NULL
)
ORDER BY configuration.id ASC
FETCH NEXT ? ROWS ONLY
08:30:14.415 [Main] DEBUG o.j.t.LoggerListener - -> with bind values      : 
SELECT configuration.id, configuration.created, configuration.code, configuration.value, configuration.account_id, configuration.workspace_id
FROM configuration
WHERE (
  configuration.code = 'geo.core'
  AND configuration.workspace_id IS NULL
)
ORDER BY configuration.id ASC
FETCH NEXT 1 ROWS ONLY
08:30:14.415 [Main] DEBUG o.j.t.LoggerListener - Exception                
org.jooq.exception.DataAccessException: SQL [SELECT configuration.id, configuration.created, configuration.code, configuration.value, configuration.account_id, configuration.workspace_id
FROM configuration
WHERE (
  configuration.code = ?
  AND configuration.workspace_id IS NULL
)
ORDER BY configuration.id ASC
FETCH NEXT ? ROWS ONLY]; ERROR: syntax error at or near "$2"
  Position: 280
	at org.jooq_3.15.0.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2945)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:643)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:349)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:295)
	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:316)
	at org.jooq.impl.SelectImpl.fetchLazyNonAutoClosing(SelectImpl.java:2866)
	at org.jooq.impl.ResultQueryTrait.fetchAny(ResultQueryTrait.java:793)
...
```

There are 2 strange issues with this:
- Both rendered/value-bound queries execute just fine when pasted to PgAdmin.
- It used to work with dialect set to just postgres in 3.14.x version. So I'm not sure if this is a bug, or I have something misconfigured?

I will set the dialect to correct version for now.

### Versions:

- jOOQ: 3.15
- Java: 11/16
- Database (include vendor): Postgres 9.6
- OS: Windows
- JDBC Driver (include name if inofficial driver): 42.2.22

**Comment by lukaseder** [comment]
Thanks for your report. The reason for the change that was introduced in jOOQ 3.15 is because PostgreSQL 13 (the latest supported PG version in jOOQ) supports `FETCH .. WITH TIES`, see https://github.com/jOOQ/jOOQ/issues/10645. It would be too complicated to use the old proprietary `OFFSET .. LIMIT` syntax only with `ROWS`, in the absence of `WITH TIES`.

I can't reproduce this problem on my side, but yes, if you're using an old PostgreSQL version, by all means, please use the most appropriate dialect version, because that's what we're integration testing. We're not integration testing `SQLDialect.POSTGRES` on PostgreSQL 9.6, and it will continue to break as we introduce new features. The unversioned dialect always corresponds to the latest supported version as can be seen here: https://www.jooq.org/download/support-matrix

I hope this helps
