### ISSUE TITLE
IndexOutOfBoundsException when deserialising MULTISET as XML emulation with NULLs

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12136]
When we interleave `NULL` values with non-`NULL` values, it seems the `MULTISET` as `XML` emulation produces an `IndexOutOfBoundsException`. This was not yet discovered in integration tests, as most queries didn't produce `NULL` values, or didn't mix them with non-`NULL` values (see also https://github.com/jOOQ/jOOQ/issues/12135)

For example, this test:

```java
Result<Record5<T, T, T, T, T>> r2 = ctx2.fetchValue(select(multiset(
    select(
        val(null, type).as("a"),
        val(value).as("b"),
        val(null, type).as("c"),
        val(value).as("d"),
        val(null, type).as("e"))
)));

assertEquals(1, r2.size());
assertEquals(5, r2.get(0).size());
assertNull(r2.get(0).value1());
assertEquals(forCompare.apply(value), r2.get(0).value2());
assertNull(r2.get(0).value3());
assertEquals(forCompare.apply(value), r2.get(0).value4());
assertNull(r2.get(0).value5());
```

Produces this query in PostgreSQL:

```xml
select (
  select xmlelement(
    name result,
    xmlagg(xmlelement(
      name record,
      xmlelement(
        name "a",
        "v0"
      ),
      xmlelement(
        name "b",
        "v1"
      ),
      xmlelement(
        name "c",
        "v2"
      ),
      xmlelement(
        name "d",
        "v3"
      ),
      xmlelement(
        name "e",
        "v4"
      )
    ))
  )
  from (
    select
      null as "v0",
      1 as "v1",
      null as "v2",
      1 as "v3",
      null as "v4"
  ) as "t"
)
```

And this XML document:

```xml
<result>
	<record>
		<a/>
		<b>1</b>
		<c/>
		<d>1</d>
		<e/>
	</record>
</result>
```

With this exception when deserialising:

```
org.jooq.exception.DataAccessException: SQL [select (select xmlelement(name result, xmlagg(xmlelement(name record, xmlelement(name "a", "v0"), xmlelement(name "b", "v1"), xmlelement(name "c", "v2"), xmlelement(name "d", "v3"), xmlelement(name "e", "v4")))) from (select ? as "v0", ? as "v1", ? as "v2", ? as "v3", ? as "v4") as "t") -- SQL rendered with a free trial version of jOOQ 3.16.0-SNAPSHOT]; Error while reading field: multiset(
  select
    null "a",
    1 "b",
    null "c",
    1 "d",
    null "e"
), at JDBC index: 1
	at org.jooq_3.16.0-SNAPSHOT.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2951)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:643)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1439)
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1400)
	at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:220)
	at org.jooq.impl.Tools.fetchOne(Tools.java:2315)
	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:506)
	at org.jooq.impl.Tools.attach(Tools.java:1247)
	at org.jooq.impl.DefaultDSLContext.fetchOne(DefaultDSLContext.java:4598)
	at org.jooq.impl.DefaultDSLContext.lambda$53(DefaultDSLContext.java:4618)
	at org.jooq.impl.Tools.attach(Tools.java:1247)
	at org.jooq.impl.DefaultDSLContext.fetchValue(DefaultDSLContext.java:4618)
	at org.jooq.test.all.testcases.MultisetTests.lambda$96(MultisetTests.java:664)
	at org.jooq.test.jOOQAbstractTest.withDSLContext(jOOQAbstractTest.java:1603)
	at org.jooq.test.jOOQAbstractTest.bindAndInlineWithDSLContexts(jOOQAbstractTest.java:1596)
	at org.jooq.test.BaseTest.bindAndInlineWithDSLContexts(BaseTest.java:1637)
	at org.jooq.test.all.testcases.MultisetTests.lambda$95(MultisetTests.java:657)
	at org.jooq.test.all.testcases.MultisetTests.testMultisetEmulations(MultisetTests.java:1038)
	at org.jooq.test.all.testcases.MultisetTests.assertMultisetDataType(MultisetTests.java:656)
	at org.jooq.test.all.testcases.MultisetTests.assertMultisetDataType(MultisetTests.java:652)
	at org.jooq.test.all.testcases.MultisetTests.testMultisetProjectionDataTypeNumber(MultisetTests.java:685)
	at org.jooq.test.jOOQAbstractTest.testMultisetProjectionDataTypeNumber(jOOQAbstractTest.java:4300)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.sql.SQLException: Error while reading field: multiset(
  select
    null "a",
    1 "b",
    null "c",
    1 "d",
    null "e"
), at JDBC index: 1
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1561)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1500)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1424)
	... 50 more
Caused by: org.jooq.exception.DataAccessException: Could not read the XML string
	at org.jooq.impl.XMLHandler.read(XMLHandler.java:147)
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.readMultiset(DefaultBinding.java:3811)
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:3793)
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:1)
	at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:931)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1551)
	... 54 more
Caused by: java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at org.jooq.impl.XMLHandler.characters(XMLHandler.java:311)
	at oracle.xml.parser.v2.NonValidatingParser.reportCharacters(NonValidatingParser.java:2170)
	at oracle.xml.parser.v2.NonValidatingParser.parseText(NonValidatingParser.java:1846)
	at oracle.xml.parser.v2.NonValidatingParser.parseElement(NonValidatingParser.java:1718)
	at oracle.xml.parser.v2.NonValidatingParser.parseRootElement(NonValidatingParser.java:461)
	at oracle.xml.parser.v2.NonValidatingParser.parseDocument(NonValidatingParser.java:407)
	at oracle.xml.parser.v2.XMLParser.parse(XMLParser.java:254)
	at oracle.xml.jaxp.JXSAXParser.parse(JXSAXParser.java:298)
	at oracle.xml.jaxp.JXSAXParser.parse(JXSAXParser.java:236)
	at org.jooq.impl.XMLHandler.read(XMLHandler.java:143)
	... 59 more
```

----
See also: https://github.com/jOOQ/jOOQ/issues/12135

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.16.0 and 3.15.1 (https://github.com/jOOQ/jOOQ/issues/12138)
