### ISSUE TITLE
The XML MULTISET_AGG emulation doesn't work with unnamed bind values in Db2

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12187]
A query like this:

```java
Record2<
    Integer,
    Result<Record2<
        Integer,
        Result<Record2<
            Integer,
            Result<Record2<
                Integer,
                Result<Record1<Integer>>
            >>
        >>
    >>
> record =
ctx.select(
        val(1),
        multisetAgg(
            val(2),
            field(select(multisetAgg(
                val(3),
                field(select(multisetAgg(
                    val(4),
                    field(select(multisetAgg(val(5))))
                )))
            )))
        )
    )
   .fetchOne();
```

Produces this generated SQL:

```sql
select
  1,
  xmlelement(
    name result,
    xmlagg(xmlelement(
      name record,
      xmlelement(
        name "2",
        2
      ),
      xmlelement(
        name "select",
        (
          select xmlelement(
            name result,
            xmlagg(xmlelement(
              name record,
              xmlelement(
                name "3",
                3
              ),
              xmlelement(
                name "select",
                (
                  select xmlelement(
                    name result,
                    xmlagg(xmlelement(
                      name record,
                      xmlelement(
                        name "4",
                        4
                      ),
                      xmlelement(
                        name "select",
                        (
                          select xmlelement(
                            name result,
                            xmlagg(xmlelement(
                              name record,
                              xmlelement(
                                name "5",
                                5
                              )
                            ))
                          )
                          from SYSIBM.DUAL
                        )
                      )
                    ))
                  )
                  from SYSIBM.DUAL
                )
              )
            ))
          )
          from SYSIBM.DUAL
        )
      )
    ))
  )
from SYSIBM.DUAL
```

Which currently doesn't work in Db2:

```
org.jooq.exception.DataAccessException: SQL [select cast(? as integer), xmlelement(name result, xmlagg(xmlelement(name record, xmlelement(name "2", cast(? as integer)), xmlelement(name "select", (select xmlelement(name result, xmlagg(xmlelement(name record, xmlelement(name "3", cast(? as integer)), xmlelement(name "select", (select xmlelement(name result, xmlagg(xmlelement(name record, xmlelement(name "4", cast(? as integer)), xmlelement(name "select", (select xmlelement(name result, xmlagg(xmlelement(name record, xmlelement(name "5", cast(? as integer))))) from SYSIBM.DUAL))))) from SYSIBM.DUAL))))) from SYSIBM.DUAL))))) from SYSIBM.DUAL -- SQL rendered with a free trial version of jOOQ 3.16.0-SNAPSHOT]; The XML name "2" is not valid. Reason code = "3".. SQLCODE=-20275, SQLSTATE=42634, DRIVER=4.29.24
	at org.jooq_3.16.0-SNAPSHOT.DB2.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2993)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:643)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:349)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:295)
	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:316)
	at org.jooq.impl.SelectImpl.fetchLazyNonAutoClosing(SelectImpl.java:2866)
	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:506)
	at org.jooq.test.all.testcases.MultisetTests.lambda$121(MultisetTests.java:940)
	at org.jooq.test.all.testcases.MultisetTests.testMultisetEmulations(MultisetTests.java:1227)
	at org.jooq.test.all.testcases.MultisetTests.testMultisetAggDeeplyNestedProjectionRecordMapping(MultisetTests.java:913)
	at org.jooq.test.jOOQAbstractTest.testMultisetAggDeeplyNestedProjectionRecordMapping(jOOQAbstractTest.java:4374)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: com.ibm.db2.jcc.am.SqlSyntaxErrorException: The XML name "2" is not valid. Reason code = "3".. SQLCODE=-20275, SQLSTATE=42634, DRIVER=4.29.24
	at com.ibm.db2.jcc.am.b7.a(b7.java:810)
	at com.ibm.db2.jcc.am.b7.a(b7.java:66)
	at com.ibm.db2.jcc.am.b7.a(b7.java:140)
	at com.ibm.db2.jcc.am.k9.c(k9.java:2844)
	at com.ibm.db2.jcc.am.k9.d(k9.java:2828)
	at com.ibm.db2.jcc.am.k9.a(k9.java:2254)
	at com.ibm.db2.jcc.am.k_.a(k_.java:8277)
	at com.ibm.db2.jcc.t4.ab.i(ab.java:204)
	at com.ibm.db2.jcc.t4.ab.b(ab.java:94)
	at com.ibm.db2.jcc.t4.p.a(p.java:32)
	at com.ibm.db2.jcc.t4.av.i(av.java:150)
	at com.ibm.db2.jcc.am.k9.al(k9.java:2223)
	at com.ibm.db2.jcc.am.k_.bq(k_.java:3763)
	at com.ibm.db2.jcc.am.k_.a(k_.java:4642)
	at com.ibm.db2.jcc.am.k_.b(k_.java:4215)
	at com.ibm.db2.jcc.am.k_.bg(k_.java:2886)
	at com.ibm.db2.jcc.am.k_.execute(k_.java:2861)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4145)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:230)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:335)
	... 39 more
```

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.16.0 and 3.15.1 (https://github.com/jOOQ/jOOQ/issues/12188)
