### ISSUE TITLE
Upgrade R2DBC dependency to 0.9.0.RELEASE

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12193]
For the next iteration of R2DBC support in jOOQ (https://github.com/jOOQ/jOOQ/issues/11717), see: https://github.com/r2dbc/r2dbc-spi/issues/233

**Comment by lukaseder** [comment]
The r2dbc-pool is not yet ready, see: https://github.com/r2dbc/r2dbc-pool/issues/131

**Comment by lukaseder** [comment]
Some drivers are also not ready yet.

**Comment by lukaseder** [comment]
So now, they seem to be available: https://r2dbc.io/2021/08/31/r2dbc-0.9.m2-available

**Comment by lukaseder** [comment]
Nope, still too early. `oracle-r2dbc:0.3.0` isn't ready yet: https://search.maven.org/search?q=oracle-r2dbc

**Comment by lukaseder** [comment]
There seems to be a regression in `r2dbc-postgresql:0.9.0.M2`: https://github.com/pgjdbc/r2dbc-postgresql/issues/440

**Comment by lukaseder** [comment]
3 SQL Server integration tests related to `INSERT .. RETURNING` now pass (related to this, perhaps? https://github.com/r2dbc/r2dbc-mssql/issues/197)

**Comment by lukaseder** [comment]
The upgrade is successful for jOOQ 3.16.0. Further work will be implemented via https://github.com/jOOQ/jOOQ/issues/11717 (e.g. stored procedure support)

**Comment by lukaseder** [comment]
Many H2 issues are also fixed, e.g. https://github.com/r2dbc/r2dbc-h2/issues/180, https://github.com/r2dbc/r2dbc-h2/issues/189

**Comment by lukaseder** [comment]
The `oracle-r2dbc:0.3.0` driver is now ready: https://twitter.com/kmensah/status/1433096805911257091?s=20, https://github.com/oracle/oracle-r2dbc/releases/tag/0.3.0

**Comment by lukaseder** [comment]
Tons of integration tests now fail with version 0.3.0. Will report issues to Oracle...

**Comment by lukaseder** [comment]
The error is:

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.util.ArrayDeque.size()" because "this.implicitResultSetStatements" is null
	at oracle.jdbc.driver.OracleStatement.getMoreResults(OracleStatement.java:5851)
	at oracle.jdbc.driver.OracleStatementWrapper.getMoreResults(OracleStatementWrapper.java:298)
	at oracle.r2dbc.impl.OracleStatementImpl.lambda$publishSqlResult$8(OracleStatementImpl.java:831)
	at oracle.r2dbc.impl.OracleR2dbcExceptions.fromJdbc(OracleR2dbcExceptions.java:277)
	at oracle.r2dbc.impl.OracleStatementImpl.lambda$publishSqlResult$10(OracleStatementImpl.java:830)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:163)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at org.reactivestreams.FlowAdapters$FlowToReactiveSubscriber.onNext(FlowAdapters.java:218)
	at oracle.jdbc.internal.CompletionStageUtil$IteratorSubscription.emitItem(CompletionStageUtil.java:648)
	at oracle.jdbc.internal.CompletionStageUtil$IteratorSubscription.emitItems(CompletionStageUtil.java:622)
	at oracle.jdbc.driver.PhysicalConnection.lambda$createUserCodeExecutor$10(PhysicalConnection.java:11713)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at oracle.jdbc.driver.PhysicalConnection.lambda$createUserCodeExecutor$11(PhysicalConnection.java:11711)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1703)
		at org.jooq.testscripts.R2DBC.main(R2DBC.java:45)
```

Maybe the bug is in ojdbc? Let's try upgrading the ojdbc dependency as well, it seems a new version 21.3.0.0 has been published:
https://search.maven.org/artifact/com.oracle.database.jdbc/ojdbc11

**Comment by lukaseder** [comment]
Yep, that fixes the issue

**Comment by mp911de** [comment]
You might want to wait a few days until R2DBC 0.9 GA is released (https://github.com/r2dbc/r2dbc-spi/milestone/19).

**Comment by lukaseder** [comment]
Thanks, @mp911de. The 3.16 release is due for the end of 2021, so there's still time :)

**Comment by lukaseder** [comment]
OK, trying again with `0.9.0.RELEASE` and the latest available driver for each currently supported dialect, and it seems that all our integration tests still pass, so I'm integrating this for jOOQ 3.16.
