### ISSUE TITLE
Deeply nested MULTISET mappings with ad-hoc conversion doesn't work when using reflection

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12208]
Given:

```java
static record NestA (Integer a, List<NestB> b) {}
static record NestB (Integer b, List<NestC> c) {}
static record NestC (Integer c, List<NestD> d) {}
static record NestD (Integer d, List<NestE> e) {}
static record NestE (Integer e) {}
```

This currently doesn't work:

```java
testMultisetDeeplyNestedProjectionRecordMapping0(
    ctx.select(
        val(1),
        multisetAgg(
            val(2),
            field(select(multisetAgg(
                val(3),
                field(select(multisetAgg(
                    val(4),
                    field(select(multisetAgg(val(5)))).convertFrom(r -> r.into(NestE.class))
                ))).convertFrom(r -> r.into(NestD.class))
            ))).convertFrom(r -> r.into(NestC.class))
        ).convertFrom(r -> r.into(NestB.class))
    )
   .fetchOneInto(NestA.class));
```

The stack trace being:

```
org.jooq.exception.DataAccessException: SQL [select ?, xmlelement(name result, xmlagg(xmlelement(name record, xmlelement(name "v0", ?), xmlelement(name "v1", (select xmlelement(name result, xmlagg(xmlelement(name record, xmlelement(name "v0", ?), xmlelement(name "v1", (select xmlelement(name result, xmlagg(xmlelement(name record, xmlelement(name "v0", ?), xmlelement(name "v1", (select xmlelement(name result, xmlagg(xmlelement(name record, xmlelement(name "v0", ?))))))))))))))))))) -- SQL rendered with a free trial version of jOOQ 3.16.0-SNAPSHOT]; Error while reading field: multiset_agg(2), at JDBC index: 2
	at org.jooq_3.16.0-SNAPSHOT.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2993)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:643)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1439)
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1400)
	at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:220)
	at org.jooq.impl.Tools.fetchOne(Tools.java:2331)
	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:506)
	at org.jooq.impl.ResultQueryTrait.fetchOneInto(ResultQueryTrait.java:529)
	at org.jooq.test.all.testcases.MultisetTests.lambda$125(MultisetTests.java:1022)
	at org.jooq.test.all.testcases.MultisetTests.testMultisetEmulations(MultisetTests.java:1289)
	at org.jooq.test.all.testcases.MultisetTests.testMultisetAggDeeplyNestedProjectionRecordMapping(MultisetTests.java:957)
	at org.jooq.test.jOOQAbstractTest.testMultisetAggDeeplyNestedProjectionRecordMapping(jOOQAbstractTest.java:4379)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.sql.SQLException: Error while reading field: multiset_agg(2), at JDBC index: 2
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1561)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1500)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1424)
	... 40 more
Caused by: org.jooq.exception.DataAccessException: Could not read the XML string
	at org.jooq.impl.XMLHandler.read(XMLHandler.java:148)
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.readMultiset(DefaultBinding.java:3822)
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:3804)
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:1)
	at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:942)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1551)
	... 44 more
Caused by: org.jooq.exception.MappingException: An error ocurred when mapping record to class org.jooq.test.all.testcases.MultisetTests$NestD
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.map(DefaultRecordMapper.java:1127)
	at org.jooq.impl.DefaultRecordMapper.map(DefaultRecordMapper.java:610)
	at org.jooq.RecordMapper.apply(RecordMapper.java:80)
	at org.jooq.impl.DefaultRecordMapper.apply(DefaultRecordMapper.java:1)
	at java.base/java.util.stream.Collectors.lambda$mapping$13(Collectors.java:469)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:1003)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.jooq.impl.ResultImpl.collect(ResultImpl.java:150)
	at org.jooq.impl.ResultImpl.into(ResultImpl.java:923)
	at org.jooq.test.all.testcases.MultisetTests.lambda$136(MultisetTests.java:1018)
	at org.jooq.Converter$1.from(Converter.java:178)
	at org.jooq.impl.ConvertedDataType.convert(ConvertedDataType.java:224)
	at org.jooq.impl.Tools.setValue(Tools.java:3073)
	at org.jooq.impl.DefaultRecordUnmapper$IterableUnmapper.unmap(DefaultRecordUnmapper.java:189)
	at org.jooq.impl.DefaultRecordUnmapper.unmap(DefaultRecordUnmapper.java:102)
	at org.jooq.impl.AbstractRecord.from0(AbstractRecord.java:909)
	at org.jooq.impl.AbstractRecord.from(AbstractRecord.java:939)
	at org.jooq.impl.XMLHandler.lambda$0(XMLHandler.java:245)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143)
	at org.jooq.impl.XMLHandler.endElement(XMLHandler.java:244)
	at oracle.xml.parser.v2.NonValidatingParser.parseElement(NonValidatingParser.java:1734)
	at oracle.xml.parser.v2.NonValidatingParser.parseRootElement(NonValidatingParser.java:461)
	at oracle.xml.parser.v2.NonValidatingParser.parseDocument(NonValidatingParser.java:407)
	at oracle.xml.parser.v2.XMLParser.parse(XMLParser.java:254)
	at oracle.xml.jaxp.JXSAXParser.parse(JXSAXParser.java:298)
	at oracle.xml.jaxp.JXSAXParser.parse(JXSAXParser.java:236)
	at org.jooq.impl.XMLHandler.read(XMLHandler.java:144)
	... 49 more
Caused by: org.jooq.exception.DataTypeException: No Converter found for types org.jooq.Converters$UnknownType and java.util.List
	at org.jooq.impl.Tools.converterOrFail(Tools.java:1217)
	at org.jooq.impl.Tools.converterOrFail(Tools.java:1226)
	at org.jooq.impl.AbstractRecord.get(AbstractRecord.java:351)
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.set(DefaultRecordMapper.java:1146)
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.mapNonnested(DefaultRecordMapper.java:1137)
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.map(DefaultRecordMapper.java:1124)
	... 81 more
```

This problem is caused by the new ad-hoc converters that don't know the `U` type

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.16.0 and 3.15.3 (https://github.com/jOOQ/jOOQ/issues/12391)
