### ISSUE TITLE
DataTypeException "Conversion function not implemented" when using write-only ad-hoc converters

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12228]
The write-only ad-hoc converter example from the blog post doesn't actually work:
https://blog.jooq.org/2021/07/20/ad-hoc-data-type-conversion-with-jooq-3-15/

The example is:

```java
ctx.insertInto(furniture)
   .columns(height.convertTo(Dimension::value))
   .values(new Dimension(BigDecimal.ONE))
   .execute();
```

It produces:

```
Exception in thread "main" org.jooq.exception.DataTypeException: Conversion function not implemented
	at org.jooq.Converters.lambda$2(Converters.java:217)
	at org.jooq.Converter$1.from(Converter.java:178)
	at org.jooq.impl.ConvertedDataType.convert(ConvertedDataType.java:224)
	at org.jooq.impl.InsertImpl.addValue(InsertImpl.java:835)
	at org.jooq.impl.InsertImpl.values(InsertImpl.java:815)
	at org.jooq.impl.InsertImpl.values(InsertImpl.java:214)
	at org.jooq.impl.InsertImpl.values(InsertImpl.java:1)
	at org.jooq.testscripts.JDBC.main(JDBC.java:49)
```

The integration test ad-converts between `String` and `Integer`, which is why the internal default conversion utilities apply instead. The problem in the example is the usage of a user-defined type.

**Comment by lukaseder** [comment]
Some more investigation needed. This doesn't seem to fail in the integration tests, which are based on generated code
