### ISSUE TITLE
NoClassDefFoundError thrown when doing a date add functionality in REDSHIFT

### ISSUE THREAD

**Issue by ghoshrahul** [jOOQ/jOOQ#12234]
### Expected behavior
It should add the number/column to the date

### Actual behavior

Throwing java.lang.NoClassDefFoundError: com/amazon/redshift/util/RedshiftInterval 

Stack trace:-

### Steps to reproduce the problem

```java
String sqlQuery = "select cast(\"users\".\"created\" as date) \"Created\", \"users\".\"frequency\" \"Frequency\", " +
                   "coalesce((\"users\".\"created\" + (\"users\".\"frequency\" - 1E0) * interval '1 day'), '1970-01-01 00:00:00') \"Date Add\" from \"users\" \"users\"";
ResultQuery jooqQuery = DSL.using(dslContext.configuration()).parser().parseResultQuery(sqlQuery);
```
**Result**:

```
Caused by: java.lang.NoClassDefFoundError: com/amazon/redshift/util/RedshiftInterval
	at org.jooq.util.postgres.PostgresUtils.toRedshiftInterval(PostgresUtils.java:270)
	at org.jooq.impl.DefaultBinding$DefaultYearToSecondBinding.sqlInline0(DefaultBinding.java:4658)
	at org.jooq.impl.DefaultBinding$DefaultYearToSecondBinding.sqlInline0(DefaultBinding.java:4643)
	at org.jooq.impl.DefaultBinding$AbstractBinding.sql(DefaultBinding.java:871)
	at org.jooq.impl.DefaultBinding$AbstractBinding.sqlCast(DefaultBinding.java:836)
	at org.jooq.impl.DefaultBinding$AbstractBinding.sqlCast(DefaultBinding.java:806)
	at org.jooq.impl.DefaultBinding$AbstractBinding.sql(DefaultBinding.java:859)
	at org.jooq.impl.Val.accept(Val.java:174)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:711)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:294)
	at org.jooq.impl.Expression$DefaultExpression.accept1(Expression.java:1029)
	at org.jooq.impl.Expression$DefaultExpression.accept0(Expression.java:1016)
	at org.jooq.impl.Expression$DefaultExpression.accept(Expression.java:999)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:711)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:294)
	at org.jooq.impl.Expression.accept0(Expression.java:298)
	at org.jooq.impl.AbstractTransformable.accept(AbstractTransformable.java:70)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:711)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:294)
	at org.jooq.impl.Expression$DefaultExpression.accept1(Expression.java:1029)
	at org.jooq.impl.Expression$DefaultExpression.accept0(Expression.java:1016)
	at org.jooq.impl.Expression$DefaultExpression.accept(Expression.java:999)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:711)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:294)
	at org.jooq.impl.Expression.accept0(Expression.java:298)
	at org.jooq.impl.AbstractTransformable.accept(AbstractTransformable.java:70)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:711)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:294)
	at org.jooq.impl.QueryPartCollectionView.acceptElement(QueryPartCollectionView.java:221)
	at org.jooq.impl.QueryPartCollectionView.accept(QueryPartCollectionView.java:199)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:711)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:294)
	at org.jooq.impl.Function.accept(Function.java:74)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:711)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:294)
	at org.jooq.impl.Coalesce.accept(Coalesce.java:78)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:711)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:245)
	at org.jooq.impl.Alias.toSQLWrapped(Alias.java:360)
	at org.jooq.impl.Alias.acceptDeclareAliasStandard(Alias.java:284)
	at org.jooq.impl.Alias.accept(Alias.java:175)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:711)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:294)
	at org.jooq.impl.FieldAlias.accept(FieldAlias.java:61)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:711)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:294)
	at org.jooq.impl.QueryPartCollectionView.acceptElement(QueryPartCollectionView.java:221)
	at org.jooq.impl.QueryPartCollectionView.accept(QueryPartCollectionView.java:199)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:711)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:294)
	at org.jooq.impl.SelectQueryImpl.toSQLReference0(SelectQueryImpl.java:2192)
	at org.jooq.impl.SelectQueryImpl.lambda$toSQLReferenceLimitDefault$21(SelectQueryImpl.java:1856)
	at org.jooq.impl.AbstractContext.toggle(AbstractContext.java:331)
	at org.jooq.impl.AbstractContext.data(AbstractContext.java:342)
	at org.jooq.impl.SelectQueryImpl.toSQLReferenceLimitDefault(SelectQueryImpl.java:1856)
	at org.jooq.impl.SelectQueryImpl.accept0(SelectQueryImpl.java:1763)
	at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:1426)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:711)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:294)
	at org.jooq.impl.AbstractQuery.getSQL0(AbstractQuery.java:479)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:287)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:295)
	at org.jooq.impl.ResultQueryTrait.lambda$fetchStream$1(ResultQueryTrait.java:326)
```

### Versions

- jOOQ: 3.15 (extended trial version)
- Java: 11
- Database (include vendor): Amazon Redshift
- OS: Ubuntu 18.04

Let me know if any other information is required

**Comment by lukaseder** [comment]
Thank you very much for your message. Starting with jOOQ 3.15.0, the previously implicit, optional dependencies on JDBC drivers have been made explicit with https://github.com/jOOQ/jOOQ/issues/11738. This is to accommodate future projects where we want to improve the experience for people running jOOQ in AOP environments, where reflection should be avoided, see e.g.:

- https://github.com/jOOQ/jOOQ/issues/8779
- https://github.com/jOOQ/jOOQ/issues/12222

This means that what was previously implemented using reflection, and happened to work with both pgjdbc and redshift now requires explicit dependencies on the relevant drivers. You can see this in the `pom.xml` of the jOOQ artifact, where there's an optional/provided dependency on the redshift driver:

```xml
<dependency>
    <groupId>com.amazon.redshift</groupId>
    <artifactId>redshift-jdbc42</artifactId>
    <scope>provided</scope>
    <optional>true</optional>
</dependency>
```

Most Redshift users will have this dependency on their classpath automatically, so this won't be a problem for them. Of course, if you're using jOOQ only to translate queries, then the driver may be absent. However, I recommend you still add it for now.

We're gathering experience to see whether the tradeoff for https://github.com/jOOQ/jOOQ/issues/11738 was worth it. The benefits are getting rid of reflection and making driver dependencies explicit (though optional). The cost is that people will have to discover this through such exceptions.

I hope this helps
