### ISSUE TITLE
NullPointerException when reading empty results for MULTISET_AGG / JSON emulation

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12260]
The test introduced for https://github.com/jOOQ/jOOQ/issues/12259:

```java
Result<Record2<Integer, String>> r2 =
ctx.fetchValue(
    ctx.select(multisetAgg(TBook_ID(), TBook_TITLE()))
       .from(TBook())
       .where(falseCondition())
);
```

Produces an error when `MULTISET_AGG` is emulated with JSON, rather than XML:

```
org.jooq.exception.DataAccessException: SQL [select json_agg(json_build_array("public"."t_book"."id", "public"."t_book"."title")) from "public"."t_book" where false -- SQL rendered with a free trial version of jOOQ 3.16.0-SNAPSHOT]; Error while reading field: multiset_agg("public"."t_book"."id"), at JDBC index: 1
	at org.jooq_3.16.0-SNAPSHOT.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3046)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:639)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1439)
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1400)
	at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:220)
	at org.jooq.impl.Tools.fetchOne(Tools.java:2384)
	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:506)
	at org.jooq.impl.Tools.attach(Tools.java:1303)
	at org.jooq.impl.DefaultDSLContext.fetchOne(DefaultDSLContext.java:4598)
	at org.jooq.impl.DefaultDSLContext.lambda$53(DefaultDSLContext.java:4618)
	at org.jooq.impl.Tools.attach(Tools.java:1303)
	at org.jooq.impl.DefaultDSLContext.fetchValue(DefaultDSLContext.java:4618)
	at org.jooq.test.all.testcases.MultisetTests.lambda$10(MultisetTests.java:205)
	at org.jooq.test.all.testcases.MultisetTests.testMultisetEmulations(MultisetTests.java:1566)
	at org.jooq.test.all.testcases.MultisetTests.testMultisetAggEmpty(MultisetTests.java:203)
	at org.jooq.test.jOOQAbstractTest.testMultisetAggEmpty(jOOQAbstractTest.java:4245)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.sql.SQLException: Error while reading field: multiset_agg("public"."t_book"."id"), at JDBC index: 1
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1561)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1500)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1424)
	... 44 more
Caused by: java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
	at java.base/java.io.StringReader.<init>(StringReader.java:51)
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.readMultiset(DefaultBinding.java:3821)
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:3806)
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:1)
	at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:944)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1551)
	... 48 more
```

The SQL query is:

```sql
select json_agg(json_build_array("public"."t_book"."id", "public"."t_book"."title"))
from "public"."t_book"
where false
```

The XML query does not produce `NULL` values, but `<result/>` values, which is why it currently doesn't fail. See https://github.com/jOOQ/jOOQ/issues/12259:

```sql
select xmlelement(
  name result,
  xmlagg(xmlelement(
    name record,
    xmlelement(name "v0", "public"."t_book"."id"),
    xmlelement(name "v1", "public"."t_book"."title")
  ))
)
from "public"."t_book"
where false
```

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.16.0 and 3.15.2 (https://github.com/jOOQ/jOOQ/issues/12261)
