### ISSUE TITLE
IllegalArgumentException: Minimum abbreviation width is 4 when TXTFormat::minColWidth is less than 4

### ISSUE THREAD

**Issue by baev** [jOOQ/jOOQ#12281]
### Expected behavior

No exception occurs

### Actual behavior

```
java.lang.IllegalArgumentException: Minimum abbreviation width is 4
	at org.jooq_3.15.1.POSTGRES_11.debug(Unknown Source)
	at org.jooq.tools.StringUtils.abbreviate(StringUtils.java:650)
	at org.jooq.tools.StringUtils.abbreviate(StringUtils.java:607)
	at org.jooq.impl.AbstractResult.format(AbstractResult.java:236)
	at org.jooq.impl.AbstractFormattable.format(AbstractFormattable.java:80)
	at org.jooq.tools.LoggerListener.log(LoggerListener.java:181)
	at org.jooq.tools.LoggerListener.resultEnd(LoggerListener.java:164)
	at org.jooq.impl.ExecuteListeners.resultEnd(ExecuteListeners.java:245)
	at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:224)
	at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:177)
	at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:88)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:259)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:335)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:284)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2842)
```

### Steps to reproduce the problem

First time I'm seeing this, have no idea how to reproduce

### Versions

- jOOQ:
- Java: 11.0.x
- Database (include vendor): PostgreSQL 12.6.0
- OS: ubuntu (GH Actions) 
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.2.23

**Comment by lukaseder** [comment]
Thanks a lot for your report.

I can't see how this could happen either. There `TXTFormat.DEFAULT.minColWidth()` is set to `4`, which should prevent this from happening in the `LoggerListener`. But if you change this value manually, then the stack trace is easy to reproduce:

```java
DSLContext dsl = DSL.using(SQLDialect.DEFAULT);
Field<String> f = DSL.field("f", SQLDataType.CHAR(1));
System.out.println(dsl.newRecord(f).values("a").format(TXTFormat.DEFAULT.minColWidth(0)));
```

Producing:

```
Exception in thread "main" java.lang.IllegalArgumentException: Minimum abbreviation width is 4
	at org.jooq.tools.StringUtils.abbreviate(StringUtils.java:650)
	at org.jooq.tools.StringUtils.abbreviate(StringUtils.java:607)
	at org.jooq.impl.AbstractResult.format(AbstractResult.java:236)
	at org.jooq.impl.AbstractRecord.format(AbstractRecord.java:1031)
	at org.jooq.impl.AbstractFormattable.format(AbstractFormattable.java:80)
	at org.jooq.testscripts.JDBC.main(JDBC.java:35)
```

I'm curious, when you debug-step through the formatting (in case you can create breakpoints on the machine that reproduces this issue), can you see what the `TXTFormat::minColWidth` value is, and why?

In any case, I'll fix the exception for the case where the formatting value is lowered manually.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.16.0 and 3.15.2 (#12282), which should be released next week. Thanks again for your report.

**Comment by baev** [comment]
I got this failure in PR build without backend code changes. There was around 50 other builds with same code and all green. And I can't reproduce it locally as well. 

The settings we are using to run tests:

```java
new Settings()
                .withExecuteWithOptimisticLockingExcludeUnversioned(true)
                .withExecuteLogging(true)
                .withInlineThreshold(99);
```

**Comment by lukaseder** [comment]
Yeah, who knows what's causing this on your end... In any case, the actual problem is clear, and the fix should remove the issue in your environments as well.

**Comment by baev** [comment]
The issue reproduced once again in completely different place. I guess, I turning LoggingListener off until fix is released
