### ISSUE TITLE
resultQuery(sql).fetch() 别名不起作用

### ISSUE THREAD

**Issue by accumulate-ceaseless** [jOOQ/jOOQ#12317]
### Steps to reproduce the problem

- If the problem relates to code generation, please post your code generation configuration
- If the problem relates to upgrades, please check if your RDBMS version is still supported by jOOQ: https://www.jooq.org/download/support-matrix
- A complete set of DDL statements can help re-create the setup you're having
- An MCVE can be helpful to provide a complete reproduction case: https://github.com/jOOQ/jOOQ-mcve

### Versions

- jOOQ: 3.14.13
- Java: 11
- Database (include vendor): mysql 8.0.16
- OS: windows 7
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks a lot for your message. I might be able to help, but please do provide a bit more information.

Cheers!

**Comment by accumulate-ceaseless** [comment]
var sql = "select sql_calc_found_rows `daily_newspaper`.`read_code`.`id`,\n" +
                "                           `daily_newspaper`.`read_code`.`batch`,\n" +
                "                           `daily_newspaper`.`read_code`.`plain_code`,\n" +
                "                           `daily_newspaper`.`read_code`.`secret_code`,\n" +
                "                           `daily_newspaper`.`read_code`.`order_number`,\n" +
                "                           `daily_newspaper`.`read_code`.`create_time`,\n" +
                "                           `daily_newspaper`.`read_code`.`bind_identity`,\n" +
                "                           `daily_newspaper`.`read_code`.`active_bind_identity`,\n" +
                "                           `daily_newspaper`.`read_code`.`effective_time`,\n" +
                "                           `daily_newspaper`.`read_code`.`active_state`,\n" +
                "                           `daily_newspaper`.`read_code`.`active_time`,\n" +
                "                           `daily_newspaper`.`read_code`.`active_user_id`,\n" +
                "                           `daily_newspaper`.`read_code`.`create_user_id`,\n" +
                "                           `daily_newspaper`.`read_code`.`generate_user_id`,\n" +
                "                           `daily_newspaper`.`users`.`id`,\n" +
                "                           `daily_newspaper`.`users`.`account`,\n" +
                "                           `daily_newspaper`.`users`.`nickname`,\n" +
                "                           `daily_newspaper`.`users`.`password`,\n" +
                "                           `daily_newspaper`.`users`.`salt`,\n" +
                "                           `daily_newspaper`.`users`.`mobile_phone_number`,\n" +
                "                           `daily_newspaper`.`users`.`create_time`,\n" +
                "                           `daily_newspaper`.`users`.`locked`,\n" +
                "                           `daily_newspaper`.`users`.`real_name`,\n" +
                "                           `daily_newspaper`.`users`.`sex`,\n" +
                "                           `daily_newspaper`.`users`.`identity_card`,\n" +
                "                           `daily_newspaper`.`users`.`unit_name`,\n" +
                "                           `daily_newspaper`.`users`.`department`,\n" +
                "                           `daily_newspaper`.`users`.`post`,\n" +
                "                           `daily_newspaper`.`users`.`professional_title`,\n" +
                "                           `daily_newspaper`.`users`.`contact_address`,\n" +
                "                           `daily_newspaper`.`users`.`postal_code`,\n" +
                "                           `daily_newspaper`.`users`.`comboIds`,\n" +
                "                           `active_user`.`id`,\n" +
                "                           `active_user`.`account`,\n" +
                "                           `active_user`.`nickname`,\n" +
                "                           `active_user`.`password`,\n" +
                "                           `active_user`.`salt`,\n" +
                "                           `active_user`.`mobile_phone_number`,\n" +
                "                           `active_user`.`create_time`,\n" +
                "                           `active_user`.`locked`,\n" +
                "                           `active_user`.`real_name`,\n" +
                "                           `active_user`.`sex`,\n" +
                "                           `active_user`.`identity_card`,\n" +
                "                           `active_user`.`unit_name`,\n" +
                "                           `active_user`.`department`,\n" +
                "                           `active_user`.`post`,\n" +
                "                           `active_user`.`professional_title`,\n" +
                "                           `active_user`.`contact_address`,\n" +
                "                           `active_user`.`postal_code`,\n" +
                "                           `active_user`.`comboIds`\n" +
                "from `daily_newspaper`.`read_code`\n" +
                "         left outer join `daily_newspaper`.`users`\n" +
                "                         on `daily_newspaper`.`read_code`.`create_user_id` = `daily_newspaper`.`users`.`id`\n" +
                "         left outer join `daily_newspaper`.`users` as `active_user`\n" +
                "                         on `daily_newspaper`.`read_code`.`active_user_id` = `active_user`.`id`\n" +
                "where `daily_newspaper`.`read_code`.`batch` = 'GSCBS'\n" +
                "order by `daily_newspaper`.`read_code`.`create_time` desc\n" +
                "limit 5 offset 0;";

        var records = dslContext.fetch(sql);
        if (!records.isEmpty()) {
            records.get(0).get(USERS.as("active_user").ID);
        }

执行后异常：
    2021-08-18 09:10:30.502  INFO 5860 --- [           main] org.jooq.impl.Fields                     : Ambiguous match found for id. Both "read_code"."id" and "users"."id" match.

java.sql.SQLWarning: null
	at org.jooq.impl.Fields.field0(Fields.java:150) ~[jooq-3.14.13.jar:na]
	at org.jooq.impl.Fields.indexOf(Fields.java:301) ~[jooq-3.14.13.jar:na]
	at org.jooq.impl.AbstractRow.indexOf(AbstractRow.java:225) ~[jooq-3.14.13.jar:na]
	at org.jooq.impl.AbstractRecord.get(AbstractRecord.java:255) ~[jooq-3.14.13.jar:na]
	at com.hz.newspaper.JooqTest.t(JooqTest.java:80) ~[test-classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688) ~[junit-platform-commons-1.7.2.jar:1.7.2]
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60) ~[junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131) ~[junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149) ~[junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140) ~[junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84) ~[junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115) ~[junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105) ~[junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106) ~[junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64) ~[junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45) ~[junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37) ~[junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104) ~[junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98) ~[junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210) ~[junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206) ~[junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131) ~[junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65) ~[junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541) ~[na:na]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541) ~[na:na]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51) ~[junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108) ~[junit-platform-launcher-1.7.2.jar:1.7.2]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88) ~[junit-platform-launcher-1.7.2.jar:1.7.2]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54) ~[junit-platform-launcher-1.7.2.jar:1.7.2]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67) ~[junit-platform-launcher-1.7.2.jar:1.7.2]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52) ~[junit-platform-launcher-1.7.2.jar:1.7.2]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96) ~[junit-platform-launcher-1.7.2.jar:1.7.2]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75) ~[junit-platform-launcher-1.7.2.jar:1.7.2]
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71) ~[junit5-rt.jar:na]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33) ~[junit-rt.jar:na]
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235) ~[junit-rt.jar:na]
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54) ~[junit-rt.jar:na]

**Comment by accumulate-ceaseless** [comment]
期望是：通过别名拿到内容

**Comment by accumulate-ceaseless** [comment]
![image](https://user-images.githubusercontent.com/58628923/129821396-388cfcc7-86ed-408c-872b-a5f42b8657cf.png)

**Comment by accumulate-ceaseless** [comment]
配置useOldAliasMetadataBehavior=true后解决了该问题！

**Comment by lukaseder** [comment]
Thanks a lot for documenting this. I wasn't aware of the `useOldAliasMetadataBehavior` flag.

When using plain SQL, jOOQ can only work with what JDBC's `ResultSetMetaData` provides, so ideally, you should avoid ambiguous column names such as `ID`. For example, you could provide column aliases to each column in order to disambiguate them, such as

```sql
`active_user`.`id` as `active_user_id`
```

Since you're using jOOQ's code generator already (your `USERS.as("active_user").ID` usage hints at this), I suggest you re-write your plain SQL query to jOOQ to profit from the entire tool chain. When jOOQ knows the exact column references, then the ambiguous column names can be disambiguated.

An alternative, if you can't rewrite your query to using jOOQ, is to:

1. Access columns by index rather than by name. This never fails on the jOOQ side (but of course, you'll have to correctly count indexes again)
2. Use `ResultQuery.coerce()` to tell jOOQ a bit more about your projection *before* executing the query. This prevents having to use `ResultSetMetaData`
