### ISSUE TITLE
IndexOutOfBoundsException when calling Result.formatChart() on an empty result

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12333]
Calling `result.formatChart()` on an empty result produces this exception:

```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at org.jooq.impl.AbstractResult.formatChart(AbstractResult.java:960)
	at org.jooq.impl.AbstractFormattable.formatChart(AbstractFormattable.java:334)
	at org.jooq.impl.AbstractFormattable.formatChart(AbstractFormattable.java:311)
	at org.jooq.test.FormatChartTest.result4x3(FormatChartTest.java:425)
	at org.jooq.test.FormatChartTest.testFormatChart4x3Default(FormatChartTest.java:243)
```

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.16.0, 3.15.2 (https://github.com/jOOQ/jOOQ/issues/12334), and 3.14.14 (https://github.com/jOOQ/jOOQ/issues/12335)
