### ISSUE TITLE
DSLContext.fetchXYZ() methods should uniformly attach argument query to DSLContext.configuration()

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12331]
Currently, every `DSLContext.fetchXYZ()` convenience method might behave a bit differently as far as attaching the `Configuration` is concerned:

- Some attach the argument query to the `DSLContext::configuration` prior to execution, then restore the old one again
- Some just use the argument query's configuration (meaning the argument can't be created from `DSL`, only from `DSLContext`)

The behaviour should be uniform across the API, always attaching the  `DSLContext::configuration`.

This is an incompatible change of behaviour, in case someone relied on the existing ad-hoc behaviour.

**Comment by lukaseder** [comment]
At second sight, lots of methods are already doing this attachment. Perhaps this isn't a real problem...

**Comment by lukaseder** [comment]
The `DSLContext.fetchStream(ResultQuery)` method currently throws, if the argument `ResultQuery` isn't attached:

```
org.jooq.exception.DetachedException: Cannot execute query. No JDBC Connection configured
	at org.jooq_3.16.0-SNAPSHOT.DEFAULT.debug(Unknown Source)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:297)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:295)
	at org.jooq.impl.SelectImpl.fetchLazy(SelectImpl.java:2844)
	at org.jooq.impl.ResultQueryTrait.lambda$2(ResultQueryTrait.java:326)
	at java.base/java.util.stream.AbstractPipeline.sourceSpliterator(AbstractPipeline.java:405)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.jooq.test.FetchFromUnattachedTest.testFetchResultQuery(FetchFromUnattachedTest.java:109)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
```

**Comment by lukaseder** [comment]
The reason is in the implementation and the lazy nature of the execution:

```java
    @Override
    public <R extends Record> Stream<R> fetchStream(ResultQuery<R> query) {
        return Tools.attach(query, configuration(), query::stream);
    }
```

The attachment must happen when the `fetchLazy()` call is made. Difficult to say how this should be fixed. We can't unattach the query *after* the execution, because we can't control the `Stream` consumption and termination...
