### ISSUE TITLE
I'm trying out the trial version with oracle and I'm getting a slow query also a NPE after that

### ISSUE THREAD

**Issue by johnlabarge** [jOOQ/jOOQ#12366]
EVERE: Error in file: /Users/jlabarge/card-production/build/tmp/generateJooq/config.xml. Error : Error generating code for catalog 
org.jooq.codegen.GeneratorException: Error generating code for catalog 
        at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:487)
        at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:873)
        at org.jooq.codegen.GenerationTool.run(GenerationTool.java:233)
        at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:228)
        at org.jooq.codegen.GenerationTool.main(GenerationTool.java:200)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
        at org.jooq.meta.AbstractDatabase.onError(AbstractDatabase.java:3279)
        at org.jooq.meta.AbstractDatabase.getArrays(AbstractDatabase.java:2293)
        at org.jooq.codegen.JavaGenerator.generateSchemaIfEmpty(JavaGenerator.java:524)
        at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
        at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1631)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
        at org.jooq.codegen.JavaGenerator.generateCatalogIfEmpty(JavaGenerator.java:519)
        at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:481)
        ... 4 more
Caused by: java.lang.NullPointerException
        at org.jooq.meta.oracle.OracleDatabase.getArrays0(OracleDatabase.java:830)
        at org.jooq.meta.AbstractDatabase.lambda$getArrays$15(AbstractDatabase.java:2294)
        at org.jooq.meta.AbstractDatabase.onError(AbstractDatabase.java:3269)
        ... 18 more

**Comment by lukaseder** [comment]
Thanks a lot for your report. May I ask you to please provide the following additional information on versions?

- jOOQ:
- Java:
- Database (include vendor):
- OS:
- JDBC Driver (include name if inofficial driver):

Also, can you see from your logs what specific collection type is causing this? It's either a SQL `TABLE` or `VARRAY` type, or a PL/SQL table type of some sorts.

**Comment by lukaseder** [comment]
I can't seem to reproduce the NPE problem on either Oracle 11g or 18c. I'll add a probe to the code that at least displays a better error than a NPE, including a hint about what array type is causing the problem: https://github.com/jOOQ/jOOQ/issues/12375

**Comment by lukaseder** [comment]
A new 3.15.3-SNAPSHOT version has been published here, which should avoid the NPE by skipping the respective data type, and log which data type is causing it. If you're interested in testing this snapshot version, please get in touch by email, and I'll send you an extended trial license key which gives access to the snapshot downloads here: https://www.jooq.org/download/versions
