### ISSUE TITLE
DDLDatabase errors in generating code using enums and defaultNameCase=lower

### ISSUE THREAD

**Issue by JackOfMostTrades** [jOOQ/jOOQ#12362]
Using the latest release and master branch I'm unable to generate jOOQ classes using DDLDatabase, setting defaultNameCase=false (to generate classes for usage with Postgres) using a script that has a custom enum type. Example script:

```
CREATE TYPE my_color AS ENUM ('RED', 'GREEN');
CREATE TABLE my_table (
    color my_color NOT NULL
);
```

When generating jOOQ I get the following log:

```
Aug 27, 2021 1:29:24 PM org.jooq.tools.JooqLogger info
INFO: create type "my_color" as enum ('RED', 'GREEN')
Aug 27, 2021 1:29:24 PM org.jooq.tools.JooqLogger info
INFO: Update count: 0          
Aug 27, 2021 1:29:24 PM org.jooq.tools.JooqLogger info
INFO: create table "my_table" (
  "color" MY_COLOR not null
)
Aug 27, 2021 1:29:24 PM org.jooq.tools.JooqLogger error
SEVERE: DDLDatabase Error        : Your SQL string could not be parsed or interpreted. This may have a variety of reasons, including:
- The jOOQ parser doesn't understand your SQL
- The jOOQ DDL simulation logic (translating to H2) cannot simulate your SQL

If you think this is a bug or a feature worth requesting, please report it here: https://github.com/jOOQ/jOOQ/issues/new/choose

As a workaround, you can use the Settings.parseIgnoreComments syntax documented here:
https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/settings-parser/
Aug 27, 2021 1:29:24 PM org.jooq.tools.JooqLogger error
SEVERE: Error while loading file: /home/ihaken/src/squassh/squassh-embedded-db/src/main/resources/squassh.sql
Aug 27, 2021 1:29:24 PM org.jooq.tools.JooqLogger error
SEVERE: Error in file: /home/ihaken/src/squassh/squassh-common/build/tmp/generateJooq/config.xml. Error : Error while exporting schema
org.jooq.exception.DataAccessException: Error while exporting schema
        at org.jooq.meta.extensions.AbstractInterpretingDatabase.connection(AbstractInterpretingDatabase.java:103)
        at org.jooq.meta.extensions.AbstractInterpretingDatabase.create0(AbstractInterpretingDatabase.java:77)
        at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:332)
        at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:322)
        at org.jooq.meta.AbstractDatabase.setConnection(AbstractDatabase.java:312)
        at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:527)
        at org.jooq.codegen.GenerationTool.run(GenerationTool.java:233)
        at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:228)
        at org.jooq.codegen.GenerationTool.main(GenerationTool.java:200)
Caused by: org.jooq.exception.DataAccessException: SQL [create table "my_table" ("color" MY_COLOR not null)]; Unknown data type: "MY_COLOR"; SQL statement:
create table "my_table" ("color" MY_COLOR not null) [50004-200]
        at org.jooq_3.16.0-SNAPSHOT.H2.debug(Unknown Source)
        at org.jooq.impl.Tools.translate(Tools.java:3049)
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:639)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:349)
        at org.jooq.meta.extensions.ddl.DDLDatabase.load(DDLDatabase.java:199)
        at org.jooq.meta.extensions.ddl.DDLDatabase.lambda$export$0(DDLDatabase.java:172)
        at org.jooq.FilePattern.load0(FilePattern.java:307)
        at org.jooq.FilePattern.load(FilePattern.java:287)
        at org.jooq.FilePattern.load(FilePattern.java:234)
        at org.jooq.meta.extensions.ddl.DDLDatabase.export(DDLDatabase.java:172)
        at org.jooq.meta.extensions.AbstractInterpretingDatabase.connection(AbstractInterpretingDatabase.java:100)
        ... 8 more
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Unknown data type: "MY_COLOR"; SQL statement:
create table "my_table" ("color" MY_COLOR not null) [50004-200]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
        at org.h2.message.DbException.get(DbException.java:205)
        at org.h2.message.DbException.get(DbException.java:181)
        at org.h2.command.Parser.parseColumnWithType(Parser.java:5971)
        at org.h2.command.Parser.parseColumnForTable(Parser.java:5697)
        at org.h2.command.Parser.parseTableColumnDefinition(Parser.java:8442)
        at org.h2.command.Parser.parseCreateTable(Parser.java:8379)
        at org.h2.command.Parser.parseCreate(Parser.java:6276)
        at org.h2.command.Parser.parsePrepared(Parser.java:903)
        at org.h2.command.Parser.parse(Parser.java:843)
        at org.h2.command.Parser.parse(Parser.java:815)
        at org.h2.command.Parser.prepareCommand(Parser.java:738)
        at org.h2.engine.Session.prepareLocal(Session.java:657)
        at org.h2.engine.Session.prepareCommand(Session.java:595)
        at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
        at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:212)
        at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
        at org.jooq.tools.jdbc.DefaultStatement.execute(DefaultStatement.java:102)
        at org.jooq.impl.SettingsEnabledPreparedStatement.execute(SettingsEnabledPreparedStatement.java:227)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:414)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:335)
        ... 15 more


```

By the looks of it, I think the "defaultNameCase" behavior just isn't being applied to the named type in the TableField part of the query.

**Comment by lukaseder** [comment]
Thanks for your report. It looks like the name case is not applied correctly to user defined data type references.

**Comment by RichieAHB** [comment]
Is there any combination of cases that could mitigate this issue (without `defaultNameCase` being changed from `lower`)?
