### ISSUE TITLE
NullPointerException in OracleDatabase.getArrays0()

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12375]
As reported here #12366, there's a possibility of a NPE in `OracleDatabase.getArrays0()`:

```
org.jooq.codegen.GeneratorException: Error generating code for catalog 
        at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:487)
        at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:873)
        at org.jooq.codegen.GenerationTool.run(GenerationTool.java:233)
        at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:228)
        at org.jooq.codegen.GenerationTool.main(GenerationTool.java:200)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
        at org.jooq.meta.AbstractDatabase.onError(AbstractDatabase.java:3279)
        at org.jooq.meta.AbstractDatabase.getArrays(AbstractDatabase.java:2293)
        at org.jooq.codegen.JavaGenerator.generateSchemaIfEmpty(JavaGenerator.java:524)
        at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
        at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1631)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
        at org.jooq.codegen.JavaGenerator.generateCatalogIfEmpty(JavaGenerator.java:519)
        at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:481)
        ... 4 more
Caused by: java.lang.NullPointerException
        at org.jooq.meta.oracle.OracleDatabase.getArrays0(OracleDatabase.java:830)
        at org.jooq.meta.AbstractDatabase.lambda$getArrays$15(AbstractDatabase.java:2294)
        at org.jooq.meta.AbstractDatabase.onError(AbstractDatabase.java:3269)
        ... 18 more
```

I don't know the cause of the NPE yet (the query produces `NULL` for either `ALL_PLSQL_COLL_TYPES.ELEM_TYPE_NAME` or `ALL_COLL_TYPES.ELEM_TYPE_NAME`), but we could log a more useful error and just skip the type, continuing with the others.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.16.0 and 3.15.3 (https://github.com/jOOQ/jOOQ/issues/12376)
