### ISSUE TITLE
Create Index with H2 Dialect generates invalid SQL due to double-quotes

### ISSUE THREAD

**Issue by blacelle** [jOOQ/jOOQ#12422]
### Expected behavior
An SQL like:

    create index if not exists "aaa_transactions_start_desc" on table_name(transaction_start desc)

### Actual behavior
An SQL Like:

    create index if not exists "aaa_transactions_start_desc" on "table_name"("transaction_start" desc)

It is rejected by H2 with:

```
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "table_name" not found; SQL statement:
create index if not exists "aaa_transactions_start_desc" on "table_name"("transaction_start" desc) [42102-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.command.ddl.CreateIndex.update(CreateIndex.java:70)
	at org.h2.command.CommandContainer.update(CommandContainer.java:198)
	at org.h2.command.Command.executeUpdate(Command.java:251)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:240)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:214)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:458)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:375)
	... 39 common frames omitted
```

By fixing manually the issue around the table name, there is the same unexpected double-quotes around the field `transaction_start`.

### Steps to reproduce the problem
I consider code like:

    try (CreateIndexIncludeStep createIndexNotConcurrently = dsl.createIndexIfNotExists(t + "_start_desc")
        .on(DSL.table(DSL.name(t)), DSL.field(DSL.name("transaction_start")).desc())) {
        String sql = createIndexNotConcurrently.getSQL();  
    }

### Versions

- jOOQ: 3.14.13
- Java: 1.11
- Database (include vendor): H2

**Comment by lukaseder** [comment]
Thanks a lot for your message.

The behaviour of `DSL.name()` is governed by `RenderQuotedNames` and `RenderNameCase`, see:
https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/settings-name-style/

Instead of using the default, you can also be explicit in your name generation using `DSL.unquotedName()`, or use the appropriate case in your client code

**Comment by blacelle** [comment]
Following https://github.com/jOOQ/jOOQ/issues/9333, I tried replacing DSL.name(XXX) to DSL.sql(XXX) and it worked:

> .on(DSL.table(DSL.sql(t)), DSL.field(DSL.sql("transaction_start")).desc())

Unclear to me if this is normal behaviour or not.

---

You answered in the meantine. Thanks

**Comment by lukaseder** [comment]
> Unclear to me if this is normal behaviour or not.

See:
https://blog.jooq.org/whats-a-string-in-the-jooq-api/
