### ISSUE TITLE
Ambiguous match found when using aliases with implicit join and joining the same table twice

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12456]
Using the reproducer from a previous issue (https://github.com/jOOQ/jOOQ/issues/12455), then this query here:

```java
@Test
public void testMultisetMappingIntoJavaRecords() {
    String atsType = "foobar";

    AmPushRunMatch push_run_match = Tables.AM_PUSH_RUN_MATCH.as("push_run_match");
    AmPushRun push_run = push_run_match.amPushRun().as("push_run");
    AmRun run = push_run.amRun().as("run");
    Am am = run.am().as("am");
    Ats sourceAts = am.amSourceAtsUidFkey().as("source_ats");
    Ats targetAts = am.amTargetAtsUidFkey().as("target_ats");

     println(ctx.select(targetAts.UID, targetAts.ID)
            .from(push_run_match)
            .where(
                    sourceAts.TYPE.eq(atsType),
                    targetAts.TYPE.eq(atsType),
                    push_run_match.STATUS.eq(AmPushRunMatchStatus.NEW)
            )
            .groupBy(targetAts.UID)
            .orderBy(targetAts.UID)
            .limit(10))
            .fetch(record -> new AtsRef(atsType, record.get(targetAts.UID), record.get(targetAts.ID)));

}
```

which:

- Uses aliased implicit joins (see https://github.com/jOOQ/jOOQ/issues/12210)
- Joins the same table twice using distinct aliases (`Ats` as `"source_ats"` and `"target_ats"`)

Then, the query is generated correctly:

```sql
select "target_ats"."uid", "target_ats"."id"
from (
  "public"."am_push_run_match" as "push_run_match"
    join (
      "public"."am_push_run" as "push_run"
        join (
          "public"."am_run" as "run"
            join (
              "public"."am" as "am"
                join "public"."ats" as "target_ats"
                  on "am"."target_ats_uid" = "target_ats"."uid"
                join "public"."ats" as "source_ats"
                  on "am"."source_ats_uid" = "source_ats"."uid"
            )
              on "run"."am_uid" = "am"."uid"
        )
          on "push_run"."am_run_uid" = "run"."uid"
    )
      on "push_run_match"."am_push_run_uid" = "push_run"."uid"
  )
where (
  "source_ats"."type" = 'foobar'
  and "target_ats"."type" = 'foobar'
  and "push_run_match"."status" = 'NEW'
)
group by "target_ats"."uid"
order by "target_ats"."uid"
fetch next 10 rows only
```

But a warning is logged, which hints at there possibly being a hidden bug somewhere, e.g. if the order of join path references is changed, etc:

```
09:24:12,929  INFO [org.jooq.impl.FieldsImpl                          ] - Ambiguous match found for uid. Both "am"."uid" and "source_ats"."uid" match.
java.sql.SQLWarning: null
        at org.jooq.impl.FieldsImpl.field0(FieldsImpl.java:274) [jooq-3.15.3.jar:?]
        at org.jooq.impl.FieldsImpl.field(FieldsImpl.java:213) [jooq-3.15.3.jar:?]
        at org.jooq.impl.AbstractRow.field(AbstractRow.java:238) [jooq-3.15.3.jar:?]
        at org.jooq.impl.FieldsTrait.field(FieldsTrait.java:67) [jooq-3.15.3.jar:?]
        at org.jooq.impl.JoinTable.onKey(JoinTable.java:748) [jooq-3.15.3.jar:?]
        at org.jooq.impl.JoinTable.onKey(JoinTable.java:732) [jooq-3.15.3.jar:?]
        at org.jooq.impl.JoinTable.onKey(JoinTable.java:148) [jooq-3.15.3.jar:?]
        at org.jooq.impl.AbstractContext$JoinNode.joinTree(AbstractContext.java:1049) [jooq-3.15.3.jar:?]
        at org.jooq.impl.AbstractContext$JoinNode.joinTree(AbstractContext.java:1049) [jooq-3.15.3.jar:?]
        at org.jooq.impl.AbstractContext$JoinNode.joinTree(AbstractContext.java:1049) [jooq-3.15.3.jar:?]
        at org.jooq.impl.DefaultRenderContext.scopeEnd0(DefaultRenderContext.java:306) [jooq-3.15.3.jar:?]
        at org.jooq.impl.AbstractContext.scopeEnd(AbstractContext.java:739) [jooq-3.15.3.jar:?]
        at org.jooq.impl.SelectQueryImpl.accept0(SelectQueryImpl.java:1850) [jooq-3.15.3.jar:?]
        at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:1435) [jooq-3.15.3.jar:?]
        at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:720) [jooq-3.15.3.jar:?]
        at org.jooq.impl.AbstractContext.visit(AbstractContext.java:296) [jooq-3.15.3.jar:?]
        at org.jooq.impl.AbstractQuery.getSQL0(AbstractQuery.java:469) [jooq-3.15.3.jar:?]
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:287) [jooq-3.15.3.jar:?]
        at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:295) [jooq-3.15.3.jar:?]
        at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:316) [jooq-3.15.3.jar:?]
        at org.jooq.impl.SelectImpl.fetchLazyNonAutoClosing(SelectImpl.java:2866) [jooq-3.15.3.jar:?]
        at org.jooq.impl.ResultQueryTrait.collect(ResultQueryTrait.java:357) [jooq-3.15.3.jar:?]
        at org.jooq.impl.ResultQueryTrait.fetch(ResultQueryTrait.java:1454) [jooq-3.15.3.jar:?]
        at org.jooq.example.test.containers.TestContainersTest.testMultisetMappingIntoJavaRecords(TestContainersTest.java:75) [test-classes/:?]
```

There doesn't seem to be anything wrong with the query usage, just yet another issue where aliased implicit join paths may cause some trouble.

The workaround is to remove all the aliases

**Comment by alf** [comment]
We're hitting this one a lot. The suggested workaround makes the problem go away, however the developer experience here is a bit frustrating.

Can you confirm that the generated query is correct even with the aliases, or can this lead to wrong queries?

**Comment by alf** [comment]
Just to be clear, the problem seems to be the following:

```java
        var kull_studieprogram_sisteopptakstermin = KULL.studieprogram().studieprogram_SisteOpptak_Termin_Fk().as("kull_studieprogram_sisteopptakstermin");
        var kull_studieprogram_studieansvarligorganisasjonsenhet = KULL.studieprogram().studieprogram_Studieansv_Organisasjonsenhet_Fk().as("kull_studieprogram_studieansvarligorganisasjonsenhet");
```

Here we alias the table with the assumption that this will produce SQL that is easier for us to read/connect to the jOOQ source.

If we remove the aliases, the problem disappears:

```java
        var kull_studieprogram_sisteopptakstermin = KULL.studieprogram().studieprogram_SisteOpptak_Termin_Fk();
        var kull_studieprogram_studieansvarligorganisasjonsenhet = KULL.studieprogram().studieprogram_Studieansv_Organisasjonsenhet_Fk();
```

**Comment by lukaseder** [comment]
Thanks for the ping, @alf. I think the problem at the time was that I didn't manage to reproduce the warning. Can you provide a simple reproducer, perhaps? If not, what does your query look like, exactly?

**Comment by lukaseder** [comment]
Ah yes, I see it now. Key here is that the path is aliased twice, e.g. this query reproduces it:

```java
TBookToBookStore bs = T_BOOK_TO_BOOK_STORE;
TBook b = bs.tBook().as("b");
TAuthor a = b.fkTBookAuthorId().as("author");
TAuthor ca = b.fkTBookCoAuthorId().as("co_author");

Result<Record4<Integer, String, Integer, Integer>> result =
create().select(b.ID, bs.BOOK_STORE_NAME, a.ID, ca.ID)
        .from(bs)
        .orderBy(bs.BOOK_STORE_NAME, bs.BOOK_ID)
        .fetch();
```

Producing these warnings:

```
14:09:38,387  INFO [FieldsImpl                    ] - Ambiguous match found for ID. Both "b"."ID" and "co_author"."ID" match.
java.sql.SQLWarning: null
	at org.jooq.impl.FieldsImpl.field0(FieldsImpl.java:310) ~[classes/:?]
	at org.jooq.impl.FieldsImpl.field(FieldsImpl.java:225) ~[classes/:?]
	at org.jooq.impl.AbstractRow.field(AbstractRow.java:315) ~[classes/:?]
	at org.jooq.impl.FieldsTrait.field(FieldsTrait.java:69) ~[classes/:?]
	at org.jooq.impl.JoinTable.onKey0(JoinTable.java:755) ~[classes/:?]
	at org.jooq.impl.AbstractContext$JoinNode.joinTree(AbstractContext.java:1213) ~[classes/:?]
	at org.jooq.impl.DefaultRenderContext.scopeEnd0(DefaultRenderContext.java:323) ~[classes/:?]
	at org.jooq.impl.AbstractContext.scopeEnd(AbstractContext.java:873) ~[classes/:?]
	at org.jooq.impl.SelectQueryImpl.accept0(SelectQueryImpl.java:2008) ~[classes/:?]
	at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:1550) ~[classes/:?]
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:736) ~[classes/:?]
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:354) ~[classes/:?]
	at org.jooq.impl.DefaultRenderContext.render(DefaultRenderContext.java:417) ~[classes/:?]
	at org.jooq.test.all.listeners.PrettyPrinter.lambda$0(PrettyPrinter.java:131) ~[classes/:?]
	at org.jooq.test.agent.SupportVerificationDispatcher.deactivated(SupportVerificationDispatcher.java:125) [classes/:?]
	at org.jooq.test.all.listeners.PrettyPrinter.renderEnd(PrettyPrinter.java:80) [classes/:?]
	at org.jooq.impl.ExecuteListeners.renderEnd(ExecuteListeners.java:188) [classes/:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:304) [classes/:?]
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:290) [classes/:?]
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2938) [classes/:?]
	at org.jooq.test.all.testcases.ImplicitJoinTests.testImplicitJoinWithAliasedJoinPathsAndAmbiguities(ImplicitJoinTests.java:281) [test-classes/:?]
	at org.jooq.test.jOOQAbstractTest.testImplicitJoinWithAliasedJoinPathsAndAmbiguities(jOOQAbstractTest.java:11866) [test-classes/:?]

14:09:38,392  INFO [FieldsImpl                    ] - Ambiguous match found for ID. Both "b"."ID" and "co_author"."ID" match.
java.sql.SQLWarning: null
	at org.jooq.impl.FieldsImpl.field0(FieldsImpl.java:310) ~[classes/:?]
	at org.jooq.impl.FieldsImpl.field(FieldsImpl.java:225) ~[classes/:?]
	at org.jooq.impl.AbstractRow.field(AbstractRow.java:315) ~[classes/:?]
	at org.jooq.impl.FieldsTrait.field(FieldsTrait.java:69) ~[classes/:?]
	at org.jooq.impl.JoinTable.onKey0(JoinTable.java:755) ~[classes/:?]
	at org.jooq.impl.AbstractContext$JoinNode.joinTree(AbstractContext.java:1213) ~[classes/:?]
	at org.jooq.impl.DefaultRenderContext.scopeEnd0(DefaultRenderContext.java:323) ~[classes/:?]
	at org.jooq.impl.AbstractContext.scopeEnd(AbstractContext.java:873) ~[classes/:?]
	at org.jooq.impl.SelectQueryImpl.accept0(SelectQueryImpl.java:2008) ~[classes/:?]
	at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:1550) ~[classes/:?]
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:736) ~[classes/:?]
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:354) ~[classes/:?]
	at org.jooq.impl.DefaultDSLContext.renderInlined(DefaultDSLContext.java:746) ~[classes/:?]
	at org.jooq.impl.AbstractQueryPart.toString(AbstractQueryPart.java:192) ~[classes/:?]
	at org.jooq.test.jOOQAbstractTest$JavaDialectListener.lambda$0(jOOQAbstractTest.java:469) ~[test-classes/:?]
	at org.jooq.test.agent.SupportVerificationDispatcher.deactivated(SupportVerificationDispatcher.java:125) [classes/:?]
	at org.jooq.test.jOOQAbstractTest$JavaDialectListener.renderEnd(jOOQAbstractTest.java:451) [test-classes/:?]
	at org.jooq.impl.ExecuteListeners.renderEnd(ExecuteListeners.java:188) [classes/:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:304) [classes/:?]
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:290) [classes/:?]
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2938) [classes/:?]
	at org.jooq.test.all.testcases.ImplicitJoinTests.testImplicitJoinWithAliasedJoinPathsAndAmbiguities(ImplicitJoinTests.java:281) [test-classes/:?]
	at org.jooq.test.jOOQAbstractTest.testImplicitJoinWithAliasedJoinPathsAndAmbiguities(jOOQAbstractTest.java:11866) [test-classes/:?]
```

**Comment by lukaseder** [comment]
I'll investigate this more thoroughly next week. I can't tell you for sure yet, whether the ambiguity is real (there could be a wrong query generated) or not.

It does seem like this usage should work, and that there shouldn't be any ambiguity. The paths don't look ambiguous.

**Comment by lukaseder** [comment]
Probably, the problem is in `TableImpl`, where the constructor just copies the argument `path` information instead of re-applying aliasing to the key. The jOOQ 3.18 version does this:

```java
if (child != null) {
    this.child = child;
    this.childPath = path == null ? null : Tools.aliasedKey((ForeignKey) path, child, this);
}
else if (aliased instanceof TableImpl t) {
    this.child = t.child;
    this.childPath = t.childPath; // Problem here, I suspect
}
else {
    this.child = null;
    this.childPath = null;
}
```

**Comment by alf** [comment]
Here's a cut down example of one of our queries that cause the problem:

```java
        var kull_studieprogram_sisteopptakstermin = KULL.studieprogram().studieprogram_SisteOpptak_Termin_Fk().as("kull_studieprogram_sisteopptakstermin");
        var kull_studieprogram_studieansvarligorganisasjonsenhet = KULL.studieprogram().studieprogram_Studieansv_Organisasjonsenhet_Fk().as("kull_studieprogram");
        var result = ctx
            .select(
                        kull_studieprogram_sisteopptakstermin.TERMINKODE,
                        kull_studieprogram_studieansvarligorganisasjonsenhet.GRUPPENR,
                        kull_studieprogram_studieansvarligorganisasjonsenhet.institusjon().INSTITUSJONSNR,
                        kull_studieprogram_studieansvarligorganisasjonsenhet.INSTITUTTNR,
                        kull_studieprogram_studieansvarligorganisasjonsenhet.fakultet().FAKNR
                    )
                .from(KULL)
            .fetch();
```

This generates the following SQL:

```sql
select
  "kull_studieprogram_sisteopptakstermin"."TERMINKODE",
  "kull_studieprogram"."GRUPPENR",
  "alias_72594251"."INSTITUSJONSNR",
  "kull_studieprogram"."INSTITUTTNR",
  "alias_108484041"."FAKNR"
from "KJERNEAPI"."KULL"
  join (
    "KJERNEAPI"."STUDIEPROGRAM" "alias_43753674"
      left outer join "KJERNEAPI"."TERMIN" "kull_studieprogram_sisteopptakstermin"
        on (
          "alias_43753674"."INSTITUSJONSNR_EIER" = "kull_studieprogram_sisteopptakstermin"."INSTITUSJONSNR_EIER"
          and "alias_43753674"."TERMINKODE_SISTE_OPPTAK" = "kull_studieprogram_sisteopptakstermin"."TERMINKODE"
          and "alias_43753674"."ARSTALL_SISTE_OPPTAK" = "kull_studieprogram_sisteopptakstermin"."ARSTALL"
        )
      join (
        "KJERNEAPI"."ORGANISASJONSENHET" "kull_studieprogram"
          join "KJERNEAPI"."INSTITUSJON" "alias_72594251"
            on "kull_studieprogram"."INSTITUSJONSNR" = "alias_72594251"."INSTITUSJONSNR"
          join "KJERNEAPI"."FAKULTET" "alias_108484041"
            on (
              "kull_studieprogram"."INSTITUSJONSNR_EIER" = "alias_108484041"."INSTITUSJONSNR_EIER"
              and "kull_studieprogram"."INSTITUSJONSNR" = "alias_108484041"."INSTITUSJONSNR"
              and "kull_studieprogram"."FAKNR" = "alias_108484041"."FAKNR"
            )
      )
        on (
          "alias_43753674"."INSTITUSJONSNR_EIER" = "kull_studieprogram"."INSTITUSJONSNR_EIER"
          and "alias_43753674"."INSTITUSJONSNR_STUDIEANSV" = "kull_studieprogram"."INSTITUSJONSNR"
          and "alias_43753674"."FAKNR_STUDIEANSV" = "kull_studieprogram"."FAKNR"
          and "alias_43753674"."INSTITUTTNR_STUDIEANSV" = "kull_studieprogram"."INSTITUTTNR"
          and "alias_43753674"."GRUPPENR_STUDIEANSV" = "kull_studieprogram"."GRUPPENR"
        )
  )
    on (
      "KJERNEAPI"."KULL"."INSTITUSJONSNR_EIER" = "alias_43753674"."INSTITUSJONSNR_EIER"
      and "KJERNEAPI"."KULL"."STUDIEPROGRAMKODE" = "alias_43753674"."STUDIEPROGRAMKODE"
    )
```

And the following warnings in the log:

```
15:14:39,598 INFO  [org.jooq.impl.FieldsImpl] (default task-4) Ambiguous match found for INSTITUSJONSNR_EIER. Both "kull_studieprogram"."INSTITUSJONSNR_EIER" and "alias_108484041"."INSTITUSJONSNR_EIER" match.: java.sql.SQLWarning
...
15:14:39,598 INFO  [org.jooq.impl.FieldsImpl] (default task-4) Ambiguous match found for INSTITUSJONSNR. Both "kull_studieprogram"."INSTITUSJONSNR" and "alias_108484041"."INSTITUSJONSNR" match.: java.sql.SQLWarning
...
15:14:39,601 INFO  [org.jooq.impl.FieldsImpl] (default task-4) Ambiguous match found for FAKNR. Both "kull_studieprogram"."FAKNR" and "alias_108484041"."FAKNR" match.: java.sql.SQLWarning
```

**Comment by lukaseder** [comment]
> Probably, the problem is in `TableImpl`, where the constructor just copies the argument `path` information instead of re-applying aliasing to the key.

Fixing this does indeed seem to fix the issue. Your full example confirms this. From the previous one, I couldn't reproduce it, but in your example, you're creating more paths from a previously aliased path:

```java
kull_studieprogram_sisteopptakstermin.TERMINKODE,
kull_studieprogram_studieansvarligorganisasjonsenhet.GRUPPENR,

// Problem here:                                     vvvvvvvvvvvvv
kull_studieprogram_studieansvarligorganisasjonsenhet.institusjon().INSTITUSJONSNR,
kull_studieprogram_studieansvarligorganisasjonsenhet.INSTITUTTNR,

// And here:                                         vvvvvvvvvv
kull_studieprogram_studieansvarligorganisasjonsenhet.fakultet().FAKNR
```

I'll check the regression test output, but it does seem promising.

**Comment by lukaseder** [comment]
Yep, can confirm, that seems to be it.

**Comment by alf** [comment]
Awesome. Thank you!
