### ISSUE TITLE
PostgreSQL BadGrammarException with R2DBC executor

### ISSUE THREAD

**Issue by ylemoigne** [jOOQ/jOOQ#12466]
### Expected behavior
Working query
It is working when using inlined parameter and running directly the generated sql :
```sql
insert into "authentication" ("login", "hashed_password", "authorizations", "enabled", "nom", "email")
values ('admindev',
        'somehashedpassword',
        cast('[{"foo":"bar"}]' as jsonb),
        true,
        'Default User',
        'none@none.com')
on conflict ("login") do update set "enabled" = true
where not (exists(select 1
                  from "authentication"))
returning (xmax = '0') as "upsert_is_insert";
```

### Actual behavior
`Caused by: io.r2dbc.postgresql.ExceptionFactory$PostgresqlBadGrammarException: [42883] operator does not exist: xid = character varying`

### Steps to reproduce the problem
Given table :
```sql
CREATE TABLE authentication
(
    login             CHARACTER VARYING NOT NULL,
    hashed_password   CHARACTER VARYING NOT NULL,
    authorizations    JSONB             NOT NULL,
    enabled           BOOLEAN           NOT NULL,
    nom               CHARACTER VARYING NOT NULL,
    email             CHARACTER VARYING NOT NULL,
    zoneinfo          CHARACTER VARYING,
    locale            CHARACTER VARYING,
    PRIMARY KEY (login)
);
```

```kotlin
val connectionFactory = ConnectionFactories.get("r2dbc:postgresql://...")
val con: Connection = connectionFactory.create().awaitSingle()
val dsl = DSL.using(con, SQLDialect.POSTGRES, Settings().withRenderSchema(false))

dsl.insertInto(AUTHENTICATION)
                .set(AUTHENTICATION.LOGIN, "admindev")
                .set(AUTHENTICATION.HASHED_PASSWORD, hashedPassword)
                .set(AUTHENTICATION.AUTHORIZATIONS, JSONB.valueOf("""[{"foo":"bar"}]"""))
                .set(AUTHENTICATION.ENABLED, true)
                .set(AUTHENTICATION.NOM, "Default User")
                .set(AUTHENTICATION.EMAIL, "none@none.com")
                .onDuplicateKeyUpdate()
                .set(AUTHENTICATION.ENABLED, true)
                .whereNotExists(select(value(1)).from(AUTHENTICATION))
                .returning(DSL.field(DSL.field("xmax").eq("0")).`as`("upsert_is_insert"))

```

The debug from r2dbc driver
```
09:58:35.690 [main] DEBUG io.r2dbc.postgresql.PARAM - Bind parameter [0] to: admindev
09:58:35.692 [main] DEBUG io.r2dbc.postgresql.PARAM - Bind parameter [1] to: somehashedpassword
09:58:35.692 [main] DEBUG io.r2dbc.postgresql.PARAM - Bind parameter [2] to: [{"foo":"bar"}]
09:58:35.692 [main] DEBUG io.r2dbc.postgresql.PARAM - Bind parameter [3] to: true
09:58:35.692 [main] DEBUG io.r2dbc.postgresql.PARAM - Bind parameter [4] to: Default User
09:58:35.692 [main] DEBUG io.r2dbc.postgresql.PARAM - Bind parameter [5] to: none@none.com
09:58:35.692 [main] DEBUG io.r2dbc.postgresql.PARAM - Bind parameter [6] to: true
09:58:35.692 [main] DEBUG io.r2dbc.postgresql.PARAM - Bind parameter [7] to: 1
09:58:35.692 [main] DEBUG io.r2dbc.postgresql.PARAM - Bind parameter [8] to: 0
09:58:35.704 [main] DEBUG io.r2dbc.postgresql.QUERY - Executing query: insert into "authentication" ("login", "hashed_password", "authorizations", "enabled", "nom", "email") values ($1, $2, cast($3 as jsonb), $4, $5, $6) on conflict ("login") do update set "enabled" = $7 where not (exists (select $8 from "authentication")) returning (xmax = $9) as "upsert_is_insert"
```

Complete stacktrace:
```
Exception in thread "main" org.jooq.exception.DataAccessException: SQL [insert into "authentication" ("login", "hashed_password", "authorizations", "enabled", "nom", "email") values ($1, $2, cast($3 as jsonb), $4, $5, $6) on conflict ("login") do update set "enabled" = $7 where not (exists (select $8 from "authentication")) returning (xmax = $9) as "upsert_is_insert"]; operator does not exist: xid = character varying
	at org.jooq.impl.Tools.translate(Tools.java:2978)
	at org.jooq.impl.Tools.translate(Tools.java:2962)
	at org.jooq.impl.R2DBC$Forwarding.onError(R2DBC.java:236)
	at reactor.core.publisher.StrictSubscriber.onError(StrictSubscriber.java:106)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onError(FluxHandle.java:203)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onError(MonoFlatMapMany.java:255)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:191)
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:337)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)
	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)
	at io.r2dbc.postgresql.util.FluxDiscardOnCancel$FluxDiscardOnCancelSubscriber.onNext(FluxDiscardOnCancel.java:86)
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793)
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718)
	at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:154)
	at io.r2dbc.postgresql.client.ReactorNettyClient$Conversation.emit(ReactorNettyClient.java:717)
	at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.emit(ReactorNettyClient.java:968)
	at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:842)
	at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:749)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:119)
	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220)
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:279)
	at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:388)
	at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:404)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.r2dbc.postgresql.ExceptionFactory$PostgresqlBadGrammarException: [42883] operator does not exist: xid = character varying
	at io.r2dbc.postgresql.ExceptionFactory.createException(ExceptionFactory.java:95)
	at io.r2dbc.postgresql.ExceptionFactory.createException(ExceptionFactory.java:64)
	at io.r2dbc.postgresql.ExceptionFactory.handleErrorResponse(ExceptionFactory.java:131)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:169)
	... 43 more
```

### Versions

- jOOQ: `3.15.3`
- Java: `eclipse temurin 11.0.12`
- Database (include vendor): `PostgreSQL 13.3`
- OS: `Windows 11`
- JDBC Driver (include name if inofficial driver): `org.postgresql:r2dbc-postgresql:0.9.0.M2` and `io.r2dbc:r2dbc-postgresql:0.8.10.RELEASE`

**Comment by ylemoigne** [comment]
Sorry... fixed with a cast :

```kotlin
dsl.insertInto(AUTHENTICATION)
                .set(AUTHENTICATION.LOGIN, "admindev")
                .set(AUTHENTICATION.HASHED_PASSWORD, hashedPassword)
                .set(AUTHENTICATION.AUTHORIZATIONS, JSONB.valueOf("""[{"foo":"bar"}]"""))
                .set(AUTHENTICATION.ENABLED, true)
                .set(AUTHENTICATION.NOM, "Default User")
                .set(AUTHENTICATION.EMAIL, "none@none.com")
                .onDuplicateKeyUpdate()
                .set(AUTHENTICATION.ENABLED, true)
                .whereNotExists(select(value(1)).from(AUTHENTICATION))
                .returning(DSL.field(DSL.field("xmax").cast(String::class.java).eq("0")).`as`("upsert_is_insert"))
```

**Comment by lukaseder** [comment]
Thanks for your message. The problem is that without any explicit type information on `DSL.field("xmax")`, jOOQ doesn't know much what to do about it, though it does know that `.eq("0")` translates to a `varchar` bind value. The ideal approach here is to use the same data type management as in generated code, with a data type binding attached to your `DSL.field("xmax", type)` expression.
