### ISSUE TITLE
Cannot map JSON(B) in MULTISET when mapping with Jackson from DefaultConverterProvider

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12508]
When using a `JSON` or `JSONB` column in a `MULTISET`, and mapping the `MULTISET` with Jackson from the `DefaultConverterProvider`, then an exception occurs.

This test currently fails:

```java
public static record RecordMappingNestedJSON(int id, JSONB j) {}
public static record RecordMappingNestedJSONWrapper(int id, List<RecordMappingNestedJSON> ms) {}

public void testMultisetProjectionRecordMappingNestedJSON() throws Exception {
    testMultisetEmulations(ctx -> {
        JSONB jsonb = jsonb(
            """
            {"a": 1, "b": "x"}
            """
        );
        List<RecordMappingNestedJSONWrapper> list =
        ctx.select(
                TAuthor_ID(),
                multiset(
                    select(
                        TBook_ID(),
                        val(jsonb).as("j")
                    )
                    .from(TBook())
                    .where(TBook_AUTHOR_ID().eq(TAuthor_ID()))
                ).as("ms").convertFrom(r -> r.into(RecordMappingNestedJSON.class))
            )
           .from(TAuthor())
           .orderBy(TAuthor_ID())
           .fetchInto(RecordMappingNestedJSONWrapper.class);

        assertEquals(2, list.size());
        assertEquals(asList(1, 2), seq(list).map(l -> l.id).toList());
        assertEquals(
            asList(asList(1, 2), asList(3, 4)),
            seq(list).map(l -> seq(l.ms).map(m -> m.id).toList()).toList());
        assertEquals(
            asList(asList(jsonb, jsonb), asList(jsonb, jsonb)),
            seq(list).map(l -> seq(l.ms).map(m -> m.j).toList()).toList());

    });
}
```

It fails with this exception:

```
org.jooq.exception.DataAccessException: SQL [select "public"."t_author"."id", (select coalesce(json_agg(json_build_array("v0", "v1")), json_build_array()) from (select "public"."t_book"."id" as "v0", cast(? as jsonb) as "v1" from "public"."t_book" where "public"."t_book"."author_id" = "public"."t_author"."id") as "t") as "ms" from "public"."t_author" order by "public"."t_author"."id" -- SQL rendered with a free trial version of jOOQ 3.16.0-SNAPSHOT]; Error while reading field: "ms", at JDBC index: 2
	at org.jooq_3.16.0-SNAPSHOT.POSTGRES.debug(Unknown Source) ~[?:?]
	at org.jooq.impl.Tools.translate(Tools.java:3075) ~[classes/:?]
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:639) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1455) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1416) ~[classes/:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:132) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at org.jooq.impl.AbstractCursor.collect(AbstractCursor.java:78) ~[classes/:?]
	at org.jooq.impl.ResultQueryTrait.collect(ResultQueryTrait.java:358) ~[classes/:?]
	at org.jooq.impl.ResultQueryTrait.fetchInto(ResultQueryTrait.java:1423) ~[classes/:?]
	at org.jooq.test.all.testcases.MultisetTests.lambda$147(MultisetTests.java:950) ~[test-classes/:?]
	at org.jooq.test.all.testcases.MultisetTests.testMultisetEmulations(MultisetTests.java:1784) [test-classes/:?]
	at org.jooq.test.all.testcases.MultisetTests.testMultisetProjectionRecordMappingNestedJSON(MultisetTests.java:930) [test-classes/:?]
	at org.jooq.test.jOOQAbstractTest.testMultisetProjectionRecordMappingNestedJSON(jOOQAbstractTest.java:4364) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.13.1.jar:4.13.1]
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) [junit-4.13.1.jar:4.13.1]
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
Caused by: java.sql.SQLException: Error while reading field: "ms", at JDBC index: 2
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1577) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1516) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1) ~[classes/:?]
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1440) ~[classes/:?]
	... 46 more
Caused by: java.lang.RuntimeException: org.jooq.exception.DataTypeException: Error while mapping JSON to POJO using Jackson
	at org.jooq.impl.JSONReader.read(JSONReader.java:113) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.readMultiset(DefaultBinding.java:3837) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:3816) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:1) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:951) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1567) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1516) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1) ~[classes/:?]
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1440) ~[classes/:?]
	... 46 more
Caused by: org.jooq.exception.DataTypeException: Error while mapping JSON to POJO using Jackson
	at org.jooq.impl.Convert$ConvertAll.from(Convert.java:1142) ~[classes/:?]
	at org.jooq.impl.Convert.convert0(Convert.java:426) ~[classes/:?]
	at org.jooq.impl.Convert.convert(Convert.java:501) ~[classes/:?]
	at org.jooq.impl.AbstractDataType.convert(AbstractDataType.java:547) ~[classes/:?]
	at org.jooq.impl.DefaultDataType.convert(DefaultDataType.java:1) ~[classes/:?]
	at org.jooq.impl.Tools.setValue(Tools.java:3155) ~[classes/:?]
	at org.jooq.impl.DefaultRecordUnmapper$IterableUnmapper.unmap(DefaultRecordUnmapper.java:188) ~[classes/:?]
	at org.jooq.impl.DefaultRecordUnmapper.unmap(DefaultRecordUnmapper.java:102) ~[classes/:?]
	at org.jooq.impl.AbstractRecord.from0(AbstractRecord.java:910) ~[classes/:?]
	at org.jooq.impl.AbstractRecord.from(AbstractRecord.java:938) ~[classes/:?]
	at org.jooq.impl.JSONReader.lambda$3(JSONReader.java:201) ~[classes/:?]
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143) ~[classes/:?]
	at org.jooq.impl.JSONReader.read(JSONReader.java:200) ~[classes/:?]
	at org.jooq.impl.JSONReader.read(JSONReader.java:110) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.readMultiset(DefaultBinding.java:3837) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:3816) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:1) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:951) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1567) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1516) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1) ~[classes/:?]
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1440) ~[classes/:?]
	... 46 more
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.jooq.impl.Convert$ConvertAll.from(Convert.java:1139) ~[classes/:?]
	at org.jooq.impl.Convert.convert0(Convert.java:426) ~[classes/:?]
	at org.jooq.impl.Convert.convert(Convert.java:501) ~[classes/:?]
	at org.jooq.impl.AbstractDataType.convert(AbstractDataType.java:547) ~[classes/:?]
	at org.jooq.impl.DefaultDataType.convert(DefaultDataType.java:1) ~[classes/:?]
	at org.jooq.impl.Tools.setValue(Tools.java:3155) ~[classes/:?]
	at org.jooq.impl.DefaultRecordUnmapper$IterableUnmapper.unmap(DefaultRecordUnmapper.java:188) ~[classes/:?]
	at org.jooq.impl.DefaultRecordUnmapper.unmap(DefaultRecordUnmapper.java:102) ~[classes/:?]
	at org.jooq.impl.AbstractRecord.from0(AbstractRecord.java:910) ~[classes/:?]
	at org.jooq.impl.AbstractRecord.from(AbstractRecord.java:938) ~[classes/:?]
	at org.jooq.impl.JSONReader.lambda$3(JSONReader.java:201) ~[classes/:?]
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143) ~[classes/:?]
	at org.jooq.impl.JSONReader.read(JSONReader.java:200) ~[classes/:?]
	at org.jooq.impl.JSONReader.read(JSONReader.java:110) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.readMultiset(DefaultBinding.java:3837) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:3816) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:1) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:951) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1567) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1516) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1) ~[classes/:?]
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1440) ~[classes/:?]
	... 46 more
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `org.jooq.JSONB` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{"a":1,"b":"x"}"; line: 1, column: 2]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63) ~[jackson-databind-2.12.1.jar:2.12.1]
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1588) ~[jackson-databind-2.12.1.jar:2.12.1]
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1213) ~[jackson-databind-2.12.1.jar:2.12.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1400) ~[jackson-databind-2.12.1.jar:2.12.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362) ~[jackson-databind-2.12.1.jar:2.12.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195) ~[jackson-databind-2.12.1.jar:2.12.1]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322) ~[jackson-databind-2.12.1.jar:2.12.1]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593) ~[jackson-databind-2.12.1.jar:2.12.1]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548) ~[jackson-databind-2.12.1.jar:2.12.1]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3516) ~[jackson-databind-2.12.1.jar:2.12.1]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.jooq.impl.Convert$ConvertAll.from(Convert.java:1139) ~[classes/:?]
	at org.jooq.impl.Convert.convert0(Convert.java:426) ~[classes/:?]
	at org.jooq.impl.Convert.convert(Convert.java:501) ~[classes/:?]
	at org.jooq.impl.AbstractDataType.convert(AbstractDataType.java:547) ~[classes/:?]
	at org.jooq.impl.DefaultDataType.convert(DefaultDataType.java:1) ~[classes/:?]
	at org.jooq.impl.Tools.setValue(Tools.java:3155) ~[classes/:?]
	at org.jooq.impl.DefaultRecordUnmapper$IterableUnmapper.unmap(DefaultRecordUnmapper.java:188) ~[classes/:?]
	at org.jooq.impl.DefaultRecordUnmapper.unmap(DefaultRecordUnmapper.java:102) ~[classes/:?]
	at org.jooq.impl.AbstractRecord.from0(AbstractRecord.java:910) ~[classes/:?]
	at org.jooq.impl.AbstractRecord.from(AbstractRecord.java:938) ~[classes/:?]
	at org.jooq.impl.JSONReader.lambda$3(JSONReader.java:201) ~[classes/:?]
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143) ~[classes/:?]
	at org.jooq.impl.JSONReader.read(JSONReader.java:200) ~[classes/:?]
	at org.jooq.impl.JSONReader.read(JSONReader.java:110) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.readMultiset(DefaultBinding.java:3837) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:3816) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:1) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:951) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1567) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1516) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1) ~[classes/:?]
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1440) ~[classes/:?]
	... 46 more
```

----
See also:
- https://stackoverflow.com/q/69536758/521799

**Comment by lukaseder** [comment]
Hmm, it's probably not possible to fix this without completely implementing #12509. Since this doesn't work with Jackson or Gson, I guess the regression risk is really slim.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.16.0 and 3.15.4 (https://github.com/jOOQ/jOOQ/issues/12511)
