### ISSUE TITLE
NullPointerException when Row[N].mapping() returns null in ROW nested in MULTISET

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12519]
This query:

```java
System.out.println(ctx.select(multiset(select(row(val(1), val(2)).mapping(String.class, (a, b) -> null)))).fetch());
```

Produces this NPE:

```
09:43:37,032 DEBUG [org.jooq.tools.LoggerListener                     ] - Executing query          : select (select coalesce(json_arrayagg(json_array("v0" null on null)), json_array(null on null)) from (select json_array(cast(? as int), cast(? as int) null on null) "v0") "t")
09:43:37,033 DEBUG [org.jooq.tools.LoggerListener                     ] - -> with bind values      : select (select coalesce(json_arrayagg(json_array("v0" null on null)), json_array(null on null)) from (select json_array(1, 2 null on null) "v0") "t")
09:43:37,077 DEBUG [org.jooq.tools.LoggerListener                     ] - Exception
org.jooq.exception.DataAccessException: SQL [select (select coalesce(json_arrayagg(json_array("v0" null on null)), json_array(null on null)) from (select json_array(cast(? as int), cast(? as int) null on null) "v0") "t")]; Error while reading field: multiset(
  select row (1, 2)
), at JDBC index: 1
        at org.jooq_3.15.2.H2.debug(Unknown Source) ~[?:?]
        at org.jooq.impl.Tools.translate(Tools.java:2980) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:639) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1439) [jooq-3.15.2.jar:?]
        at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1400) [jooq-3.15.2.jar:?]
        at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:220) [jooq-3.15.2.jar:?]
        at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:177) [jooq-3.15.2.jar:?]
        at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:88) [jooq-3.15.2.jar:?]
        at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:259) [jooq-3.15.2.jar:?]
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:335) [jooq-3.15.2.jar:?]
        at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:284) [jooq-3.15.2.jar:?]
        at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2842) [jooq-3.15.2.jar:?]
        at org.jooq.mcve.test.java.JavaTest.mcveTest(JavaTest.java:37) [test-classes/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.1.jar:4.13.1]
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.1.jar:4.13.1]
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.1.jar:4.13.1]
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.1.jar:4.13.1]
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.13.1.jar:4.13.1]
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.13.1.jar:4.13.1]
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.1.jar:4.13.1]
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) [junit-4.13.1.jar:4.13.1]
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) [junit-4.13.1.jar:4.13.1]
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) [junit-4.13.1.jar:4.13.1]
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) [junit-4.13.1.jar:4.13.1]
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) [junit-4.13.1.jar:4.13.1]
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) [junit-4.13.1.jar:4.13.1]
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) [junit-4.13.1.jar:4.13.1]
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) [junit-4.13.1.jar:4.13.1]
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) [junit-4.13.1.jar:4.13.1]
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.1.jar:4.13.1]
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413) [junit-4.13.1.jar:4.13.1]
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252) [surefire-junit4-2.12.4.jar:2.12.4]
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141) [surefire-junit4-2.12.4.jar:2.12.4]
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112) [surefire-junit4-2.12.4.jar:2.12.4]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189) [surefire-api-2.12.4.jar:2.12.4]
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165) [surefire-booter-2.12.4.jar:2.12.4]
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85) [surefire-booter-2.12.4.jar:2.12.4]
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115) [surefire-booter-2.12.4.jar:2.12.4]
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) [surefire-booter-2.12.4.jar:2.12.4]
Caused by: java.sql.SQLException: Error while reading field: multiset(
  select row (1, 2)
), at JDBC index: 1
        at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1561) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1500) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1459) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1424) ~[jooq-3.15.2.jar:?]
        ... 43 more
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "org.jooq.Record2.value1()" because "r" is null
        at org.jooq.impl.JSONReader.read(JSONReader.java:113) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.DefaultBinding$DefaultResultBinding.readMultiset(DefaultBinding.java:3821) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:3805) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:3783) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:943) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1551) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1500) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1459) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1424) ~[jooq-3.15.2.jar:?]
        ... 43 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.jooq.Record2.value1()" because "r" is null
        at org.jooq.Records.lambda$mapping$12(Records.java:595) ~[jooq-3.15.2.jar:?]
        at org.jooq.RecordMapper.apply(RecordMapper.java:80) ~[jooq-3.15.2.jar:?]
        at org.jooq.RecordMapper.apply(RecordMapper.java:65) ~[jooq-3.15.2.jar:?]
        at org.jooq.Converter$1.from(Converter.java:178) ~[jooq-3.15.2.jar:?]
        at org.jooq.Converters.from(Converters.java:178) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.ConvertedDataType.convert(ConvertedDataType.java:224) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.Tools.setValue(Tools.java:3060) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.Tools.setValue(Tools.java:3053) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.AbstractRecord.from(AbstractRecord.java:1021) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.AbstractRecord.from0(AbstractRecord.java:909) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.AbstractRecord.from(AbstractRecord.java:939) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.JSONReader.lambda$read$1(JSONReader.java:201) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.JSONReader.read(JSONReader.java:200) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.JSONReader.read(JSONReader.java:110) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.DefaultBinding$DefaultResultBinding.readMultiset(DefaultBinding.java:3821) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:3805) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:3783) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:943) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1551) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1500) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1459) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1424) ~[jooq-3.15.2.jar:?]
        ... 43 more
09:43:37,084 DEBUG [org.jooq.tools.LoggerListener                     ] - Exception
org.jooq.exception.DataAccessException: SQL [select (select coalesce(json_arrayagg(json_array("v0" null on null)), json_array(null on null)) from (select json_array(cast(? as int), cast(? as int) null on null) "v0") "t")]; Error while reading field: multiset(
  select row (1, 2)
), at JDBC index: 1
        at org.jooq_3.15.2.H2.debug(Unknown Source) ~[?:?]
        at org.jooq_3.15.2.H2.debug(Unknown Source) ~[?:?]
        at org.jooq.impl.Tools.translate(Tools.java:2980) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:639) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1439) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1400) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:220) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:177) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:88) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:259) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:335) [jooq-3.15.2.jar:?]
        at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:284) [jooq-3.15.2.jar:?]
        at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2842) [jooq-3.15.2.jar:?]
        at org.jooq.mcve.test.java.JavaTest.mcveTest(JavaTest.java:37) [test-classes/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.1.jar:4.13.1]
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.1.jar:4.13.1]
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.1.jar:4.13.1]
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.1.jar:4.13.1]
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.13.1.jar:4.13.1]
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.13.1.jar:4.13.1]
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.1.jar:4.13.1]
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) [junit-4.13.1.jar:4.13.1]
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) [junit-4.13.1.jar:4.13.1]
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) [junit-4.13.1.jar:4.13.1]
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) [junit-4.13.1.jar:4.13.1]
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) [junit-4.13.1.jar:4.13.1]
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) [junit-4.13.1.jar:4.13.1]
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) [junit-4.13.1.jar:4.13.1]
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) [junit-4.13.1.jar:4.13.1]
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) [junit-4.13.1.jar:4.13.1]
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.1.jar:4.13.1]
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413) [junit-4.13.1.jar:4.13.1]
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252) [surefire-junit4-2.12.4.jar:2.12.4]
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141) [surefire-junit4-2.12.4.jar:2.12.4]
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112) [surefire-junit4-2.12.4.jar:2.12.4]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189) [surefire-api-2.12.4.jar:2.12.4]
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165) [surefire-booter-2.12.4.jar:2.12.4]
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85) [surefire-booter-2.12.4.jar:2.12.4]
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115) [surefire-booter-2.12.4.jar:2.12.4]
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) [surefire-booter-2.12.4.jar:2.12.4]
Caused by: java.sql.SQLException: Error while reading field: multiset(
  select row (1, 2)
), at JDBC index: 1
        at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1561) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1500) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1459) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1424) ~[jooq-3.15.2.jar:?]
        ... 43 more
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "org.jooq.Record2.value1()" because "r" is null
        at org.jooq.impl.JSONReader.read(JSONReader.java:113) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.DefaultBinding$DefaultResultBinding.readMultiset(DefaultBinding.java:3821) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:3805) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:3783) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:943) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1551) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1500) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1459) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1424) ~[jooq-3.15.2.jar:?]
        ... 43 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.jooq.Record2.value1()" because "r" is null
        at org.jooq.Records.lambda$mapping$12(Records.java:595) ~[jooq-3.15.2.jar:?]
        at org.jooq.RecordMapper.apply(RecordMapper.java:80) ~[jooq-3.15.2.jar:?]
        at org.jooq.RecordMapper.apply(RecordMapper.java:65) ~[jooq-3.15.2.jar:?]
        at org.jooq.Converter$1.from(Converter.java:178) ~[jooq-3.15.2.jar:?]
        at org.jooq.Converters.from(Converters.java:178) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.ConvertedDataType.convert(ConvertedDataType.java:224) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.Tools.setValue(Tools.java:3060) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.Tools.setValue(Tools.java:3053) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.AbstractRecord.from(AbstractRecord.java:1021) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.AbstractRecord.from0(AbstractRecord.java:909) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.AbstractRecord.from(AbstractRecord.java:939) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.JSONReader.lambda$read$1(JSONReader.java:201) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.JSONReader.read(JSONReader.java:200) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.JSONReader.read(JSONReader.java:110) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.DefaultBinding$DefaultResultBinding.readMultiset(DefaultBinding.java:3821) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:3805) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:3783) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:943) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1551) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1500) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1459) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143) ~[jooq-3.15.2.jar:?]
        at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1424) ~[jooq-3.15.2.jar:?]
        ... 43 more
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.989 sec <<< FAILURE!
mcveTest(org.jooq.mcve.test.java.JavaTest)  Time elapsed: 0.952 sec  <<< ERROR!
org.jooq.exception.DataAccessException: SQL [select (select coalesce(json_arrayagg(json_array("v0" null on null)), json_array(null on null)) from (select json_array(cast(? as int), cast(? as int) null on null) "v0") "t")]; Error while reading field: multiset(
  select row (1, 2)
), at JDBC index: 1
        at org.jooq_3.15.2.H2.debug(Unknown Source)
        at org.jooq_3.15.2.H2.debug(Unknown Source)
        at org.jooq.impl.Tools.translate(Tools.java:2980)
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:639)
        at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1439)
        at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1400)
        at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:220)
        at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:177)
        at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:88)
        at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:259)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:335)
        at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:284)
        at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2842)
        at org.jooq.mcve.test.java.JavaTest.mcveTest(JavaTest.java:37)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.sql.SQLException: Error while reading field: multiset(
  select row (1, 2)
), at JDBC index: 1
        at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1561)
        at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1500)
        at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1459)
        at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143)
        at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1424)
        ... 43 more
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "org.jooq.Record2.value1()" because "r" is null
        at org.jooq.impl.JSONReader.read(JSONReader.java:113)
        at org.jooq.impl.DefaultBinding$DefaultResultBinding.readMultiset(DefaultBinding.java:3821)
        at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:3805)
        at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:3783)
        at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:943)
        at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1551)
        ... 47 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.jooq.Record2.value1()" because "r" is null
        at org.jooq.Records.lambda$mapping$12(Records.java:595)
        at org.jooq.RecordMapper.apply(RecordMapper.java:80)

        at org.jooq.RecordMapper.apply(RecordMapper.java:65)
        at org.jooq.Converter$1.from(Converter.java:178)
        at org.jooq.Converters.from(Converters.java:178)
        at org.jooq.impl.ConvertedDataType.convert(ConvertedDataType.java:224)
        at org.jooq.impl.Tools.setValue(Tools.java:3060)
        at org.jooq.impl.Tools.setValue(Tools.java:3053)
        at org.jooq.impl.AbstractRecord.from(AbstractRecord.java:1021)
        at org.jooq.impl.AbstractRecord.from0(AbstractRecord.java:909)
        at org.jooq.impl.AbstractRecord.from(AbstractRecord.java:939)
        at org.jooq.impl.JSONReader.lambda$read$1(JSONReader.java:201)
        at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143)
        at org.jooq.impl.JSONReader.read(JSONReader.java:200)
        at org.jooq.impl.JSONReader.read(JSONReader.java:110)
        ... 52 more
```

**Comment by lukaseder** [comment]
It no longer reproduces once https://github.com/jOOQ/jOOQ/issues/12413 is fixed, so this is probably a duplicate.
