### ISSUE TITLE
Field with Converter<String, Boolean> inside multiset causes JSON parsing error on Oracle  

### ISSUE THREAD

**Issue by alf** [jOOQ/jOOQ#12516]
### Expected behavior

Field should be converted as specified, should not cause runtime error.

### Actual behavior

Crashes with traceback:

```
22:14:00,689 DEBUG [org.jooq.tools.LoggerListener] (default task-1) Exception                : org.jooq.exception.DataAccessException: SQL [select (select coalesce(json_arrayagg(json_array("v0" format json null on null returning clob) format json returning clob), json_array(returning clob)) from (select "A"."B"."AKTIV___S" "v0" from "A"."B" fetch next ? rows only) "t" having count(*) = count(*)) from "A"."B" fetch next ? rows only]; Error while reading field: multiset(
  select "A"."B"."AKTIV___S"
  from "A"."B"
  limit 1
), at JDBC index: 1
	at org.jooq_3.15.2.ORACLE18C.debug(Unknown Source)
	at deployment.ROOT.war//org.jooq.impl.Tools.translate(Tools.java:2980)
	at deployment.ROOT.war//org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:639)
	at deployment.ROOT.war//org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1439)
	at deployment.ROOT.war//org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1400)
	at deployment.ROOT.war//org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:220)
	at deployment.ROOT.war//org.jooq.impl.Tools.fetchOne(Tools.java:2318)
	at deployment.ROOT.war//org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:506)
	at deployment.ROOT.war//org.jooq.impl.ResultQueryTrait.fetchOptional(ResultQueryTrait.java:691)
	at deployment.ROOT.war//com.example.TestController.crashing(TestController.java:42)
[... snip ...]
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.sql.SQLException: Error while reading field: multiset(
  select "A"."B"."AKTIV___S"
  from "A"."B"
  limit 1
), at JDBC index: 1
	at deployment.ROOT.war//org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1561)
	at deployment.ROOT.war//org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1494)
	at deployment.ROOT.war//org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1459)
	at deployment.ROOT.war//org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143)
	at deployment.ROOT.war//org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1424)
	... 107 more
Caused by: java.lang.RuntimeException: org.jooq.tools.json.ParseException: Unexpected character (J) at position 2.
	at deployment.ROOT.war//org.jooq.impl.JSONReader.read(JSONReader.java:113)
	at deployment.ROOT.war//org.jooq.impl.DefaultBinding$DefaultResultBinding.readMultiset(DefaultBinding.java:3821)
	at deployment.ROOT.war//org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:3805)
	at deployment.ROOT.war//org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:3783)
	at deployment.ROOT.war//org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:943)
	at deployment.ROOT.war//org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1551)
	... 111 more
Caused by: org.jooq.tools.json.ParseException: Unexpected character (J) at position 2.
	at deployment.ROOT.war//org.jooq.tools.json.Yylex.yylex(Yylex.java:609)
	at deployment.ROOT.war//org.jooq.tools.json.JSONParser.nextToken(JSONParser.java:263)
	at deployment.ROOT.war//org.jooq.tools.json.JSONParser.parse(JSONParser.java:112)
	at deployment.ROOT.war//org.jooq.impl.JSONReader.read(JSONReader.java:98)
	... 116 more
```

### Steps to reproduce the problem

We use the following converter:

```public class StatusConverter implements Converter<String, Boolean> {
    @Override
    public Boolean from(String databaseObject) {
        return Optional.ofNullable(databaseObject)
                .map("J"::equals)
                .orElse(null);
    }

    @Override
    public String to(Boolean userObject) {
        if (userObject == null) {
            return null;
        }

        return userObject ? "J" : "N";
    }

    @Override
    public Class<String> fromType() {
        return String.class;
    }

    @Override
    public Class<Boolean> toType() {
        return Boolean.class;
    }
}
```

Configured like so:

```
<forcedtype>
    <userType>java.lang.Boolean</userType>
    <includeExpression>.*\..*___S</includeExpression>
    <converter>com.example.StatusConverter</converter>
</forcedtype>
```

Then we crash with the following query:

```
var x = create.select(
                multiset(
                        select(
                                B.AKTIV___S
                        )
                                .from(B)
                                .limit(1)
                )
        )
        .from(B)
        .limit(1)
        .fetchOptional();
```

### Versions

- jOOQ: 3.15.2
- Java: 11
- Database (include vendor): Oracle 18c XE
- OS: Linux
- JDBC Driver (include name if inofficial driver): oracle

**Comment by alf** [comment]
The following might be relevant:

```
    public final TableField<BRecord, String> C = createField(DSL.name("C___S"), SQLDataType.VARCHAR(1).nullable(false), this, "...");
```

**Comment by lukaseder** [comment]
> The following might be relevant:

How so? You weren't using the column `C`...

**Comment by lukaseder** [comment]
(Fix should again be included in the next nightly build)

**Comment by alf** [comment]
Awesome. I’ll test both fixes tomorrow then.
