### ISSUE TITLE
Problem with Query-Parser and DB2 VARCHAR-function

### ISSUE THREAD

**Issue by marco135** [jOOQ/jOOQ#12540]
When I parse a query that uses the VARCHAR function, an error is thrown. I have a minimal setup below to reproduce this problem.

It works with the CAST operator. 
However, we have the problem that we have to be able to receive SQL written by the user and parse it. Currently, the parsing fails when the VARCHAR function is used in the query.

### Expected behavior
The statement can be parsed successfully.

### Actual behavior
The following error is currently thrown
`org.jooq.impl.ParserException: Unknown function: [1:66] ... TBCREATOR from sysibm.syscolumns WHERE VARCHAR ( [*]TBCREATOR ) like 'SYS%' 

	at org.jooq.impl.DefaultParseContext.exception(ParserImpl.java:13494)
	at org.jooq.impl.DefaultParseContext.parseUnaryOps(ParserImpl.java:7102)
	at org.jooq.impl.DefaultParseContext.parseExp(ParserImpl.java:7057)
	at org.jooq.impl.DefaultParseContext.parseFactor(ParserImpl.java:7034)
	at org.jooq.impl.DefaultParseContext.parseSum(ParserImpl.java:6980)
	at org.jooq.impl.DefaultParseContext.parseNumericOp(ParserImpl.java:6965)
	at org.jooq.impl.DefaultParseContext.parseCollated(ParserImpl.java:6907)
	at org.jooq.impl.DefaultParseContext.parseConcat(ParserImpl.java:6897)
	at org.jooq.impl.DefaultParseContext.parsePredicate(ParserImpl.java:5864)
	at org.jooq.impl.DefaultParseContext.parseNot(ParserImpl.java:5766)
	at org.jooq.impl.DefaultParseContext.parseAnd(ParserImpl.java:5756)
	at org.jooq.impl.DefaultParseContext.parseOr(ParserImpl.java:5747)
	at org.jooq.impl.DefaultParseContext.parseCondition(ParserImpl.java:5743)
	at org.jooq.impl.DefaultParseContext.parseQueryPrimaryWhere(ParserImpl.java:1420)
	at org.jooq.impl.DefaultParseContext.parseQueryPrimary(ParserImpl.java:1384)
	at org.jooq.impl.DefaultParseContext.parseQueryTerm(ParserImpl.java:1197)
	at org.jooq.impl.DefaultParseContext.parseQueryExpressionBody(ParserImpl.java:1163)
	at org.jooq.impl.DefaultParseContext.parseSelect(ParserImpl.java:932)
	at org.jooq.impl.DefaultParseContext.parseSelect(ParserImpl.java:927)
	at org.jooq.impl.DefaultParseContext.parseQuery(ParserImpl.java:772)
	at org.jooq.impl.DefaultParseContext.parseQuery0(ParserImpl.java:525)
	at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:360)
	at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:355)`

### Steps to reproduce the problem

`        DefaultConfiguration config = new DefaultConfiguration();
        config.setSQLDialect(SQLDialect.DB2_10);
        DSLContext dslContextDb2 = new DefaultDSLContext(config);

        // works successfully
        String queryWithCastVarchar =
                "select distinct TBCREATOR "
                        + "from sysibm.syscolumns "
                        + "WHERE cast ( TBCREATOR as varchar(255) ) like 'SYS%' ";
        Query sqlStepCast = dslContextDb2.parser().parseQuery(queryWithCastVarchar);
        Assertions.assertNotNull(sqlStepCast);

        // fails with exception: org.jooq.impl.ParserException: Unknown function: [1:66] ... TBCREATOR from sysibm.syscolumns WHERE VARCHAR ( [*]TBCREATOR ) like 'SYS%'
        String queryWithVarcharFunction =
                "select distinct TBCREATOR "
                        + "from sysibm.syscolumns "
                        + "WHERE VARCHAR ( TBCREATOR ) like 'SYS%' ";
        Query sqlStepFunction = dslContextDb2.parser().parseQuery(queryWithVarcharFunction);
        Assertions.assertNotNull(sqlStepFunction);`

### Versions

- jOOQ: 3.15.3 pro
- Java: 1.8
- Database (include vendor): IBM DB2 v10.5.0.7 
- OS: Windows 10
- JDBC Driver (include name if inofficial driver): 4.29.24
But it also occurred in the customer environment in a db2 version > 11.0

**Comment by marco135** [comment]
Thanks a lot for the hint. I didn't know about the ParseListener feature. I was able to implement a workaround with it.
