### ISSUE TITLE
StatementType.STATIC_STATEMENT doesn't work when calling procedures with IN/OUT parameters

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12619]
We're currently integration testing stored procedure calls only with `PreparedStatement` not also with `StatementType.STATIC_STATEMENT`. In cases where we have INOUT or OUT parameters, using a static statement doesn't make much sense, but the exception we're getting isn't useful either, e.g. we might get something like this:

```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jooq.test.BaseTest.invoke0(BaseTest.java:1448)
	at org.jooq.test.BaseTest.invoke0(BaseTest.java:1460)
	at org.jooq.test.BaseTest.invoke(BaseTest.java:1436)
	at org.jooq.test.all.testcases.RoutineAndUDTTests.lambda$0(RoutineAndUDTTests.java:190)
	at org.jooq.test.jOOQAbstractTest.withDSLContext(jOOQAbstractTest.java:1747)
	at org.jooq.test.jOOQAbstractTest.bindAndInline(jOOQAbstractTest.java:1735)
	at org.jooq.test.BaseTest.bindAndInline(BaseTest.java:1607)
	at org.jooq.test.all.testcases.RoutineAndUDTTests.testStoredProcedure(RoutineAndUDTTests.java:177)
	at org.jooq.test.jOOQAbstractTest.testStoredProcedure(jOOQAbstractTest.java:7546)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at org.jooq_3.16.0-SNAPSHOT.MYSQL.debug(Unknown Source)
	at com.mysql.cj.jdbc.CallableStatement.setInOutParamsOnServer(CallableStatement.java:1983)
	at com.mysql.cj.jdbc.CallableStatement.execute(CallableStatement.java:842)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4278)
	at org.jooq.impl.AbstractRoutine.execute0(AbstractRoutine.java:583)
	at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:543)
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:384)
	at org.jooq.impl.Tools.attach(Tools.java:1323)
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:364)
	at org.jooq.test.mysql.generatedclasses.test.Routines.p391(Routines.java:313)
	... 44 more
```

There are two things that should be improved here:

- [ ] Throw a better exception when we can't get things to work (e.g. with `INOUT` parameters, which cannot be inlined)
- [ ] Get things to work where it makes sense (e.g. with `OUT` params, we could still create a `CallableStatement` and inline all the `IN` params)

**Comment by lukaseder** [comment]
> * Get things to work where it makes sense (e.g. with `OUT` params, we could still create a `CallableStatement` and inline all the `IN` params)

It appears we're already doing this. I cannot reproduce the exception anymore.
