### ISSUE TITLE
INSERT .. RETURNING emulation using data change delta tables doesn't work with embeddables

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12689]
The integration test that uses H2 now fails:

```java
    @Test
    public void testEmbeddableRecords() {
        KeyRecord key11 = new KeyRecord(1, 1);
        KeyRecord key12 = new KeyRecord(1, 2);

        BRecord b1 = ctx.newRecord(B);
        b1.setKey(key11);
        b1.setX(1);
        b1.setY(1);
        assertEquals(1, b1.insert());
        b1 = ctx.fetchOne(B, B.KEY.eq(key11));
        assertEquals(1, (int) b1.getKey().getKey1());
        assertEquals(1, (int) b1.getKey().getKey2());

        BRecord b2 = ctx.newRecord(B);
        b2.set(B.KEY, k1);
        b2.setX(2);
        b2.setY(2);
        assertEquals(1, b2.insert());
        b2 = ctx.fetchOne(B, B.KEY.eq(key12));
        assertEquals(k1, b2.get(B.KEY));
    }
```

With this exception:

```
java.lang.IllegalArgumentException: Field ("B"."KEY1") is not contained in Row (
  "B"."KEY1", "B"."KEY2",
  "B"."X",
  "B"."Y"
)
	at org.jooq.impl.Tools.indexFail(Tools.java:1856)
	at org.jooq.impl.Tools.indexOrFail(Tools.java:1863)
	at org.jooq.impl.TableRecordImpl.getReturningIfNeeded(TableRecordImpl.java:215)
	at org.jooq.impl.TableRecordImpl.storeInsert0(TableRecordImpl.java:201)
	at org.jooq.impl.TableRecordImpl.lambda$storeInsert$0(TableRecordImpl.java:157)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143)
	at org.jooq.impl.TableRecordImpl.storeInsert(TableRecordImpl.java:156)
	at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:144)
	at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:139)
	at org.jooq.codegen.test.embeddables.EmbeddablesTest.testEmbeddableRecords(EmbeddablesTest.java:513)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

This should probably affect H2 and Db2

**Comment by lukaseder** [comment]
Duplicate of https://github.com/jOOQ/jOOQ/issues/15873
