### ISSUE TITLE
Cannot nest MULTISET in top level ROW in PostgreSQL

### ISSUE THREAD

**Issue by huuff** [jOOQ/jOOQ#12706]
Unsure whether this is by design or not yet supported

### Expected behavior
The query succeeds

### Actual behavior
Throws:

```
org.jooq.exception.DataAccessException: SQL [select row ((select coalesce(jsonb_agg(jsonb_build_array("v0")), jsonb_build_array()) from (select 1 as "v0") as "t"))]; Error while reading field: row (multiset(
  select 1
)), at JDBC index: 1
	at org.jooq_3.15.5.POSTGRES.debug(Unknown Source) ~[?:?]
	at org.jooq.impl.Tools.translate(Tools.java:2988) ~[jooq-3.15.5.jar:?]
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:639) ~[jooq-3.15.5.jar:?]
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1446) ~[jooq-3.15.5.jar:?]
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1407) ~[jooq-3.15.5.jar:?]
	at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:220) ~[jooq-3.15.5.jar:?]
	at org.jooq.impl.Tools.fetchOne(Tools.java:2326) ~[jooq-3.15.5.jar:?]
	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:506) ~[jooq-3.15.5.jar:?]
	at example.IssueTest.dateTimeFormatExceptionTest(IssueTest.java:27) ~[test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725) ~[junit-platform-commons-1.8.2.jar:1.8.2]
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107) ~[junit-platform-launcher-1.8.2.jar:1.8.2]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88) ~[junit-platform-launcher-1.8.2.jar:1.8.2]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54) ~[junit-platform-launcher-1.8.2.jar:1.8.2]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67) [junit-platform-launcher-1.8.2.jar:1.8.2]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52) [junit-platform-launcher-1.8.2.jar:1.8.2]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114) [junit-platform-launcher-1.8.2.jar:1.8.2]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86) [junit-platform-launcher-1.8.2.jar:1.8.2]
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86) [junit-platform-launcher-1.8.2.jar:1.8.2]
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53) [junit-platform-launcher-1.8.2.jar:1.8.2]
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71) [junit5-rt.jar:?]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54) [junit-rt.jar:?]
Caused by: java.sql.SQLException: Error while reading field: row (multiset(
  select 1
)), at JDBC index: 1
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1568) ~[jooq-3.15.5.jar:?]
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1507) ~[jooq-3.15.5.jar:?]
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1466) ~[jooq-3.15.5.jar:?]
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143) ~[jooq-3.15.5.jar:?]
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1431) ~[jooq-3.15.5.jar:?]
	... 72 more
Caused by: java.lang.UnsupportedOperationException: Class interface org.jooq.Result is not supported
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.pgFromString(DefaultBinding.java:3708) ~[jooq-3.15.5.jar:?]
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.pgSetValue(DefaultBinding.java:3753) ~[jooq-3.15.5.jar:?]
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.lambda$pgNewRecord$0(DefaultBinding.java:3746) ~[jooq-3.15.5.jar:?]
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143) ~[jooq-3.15.5.jar:?]
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.pgNewRecord(DefaultBinding.java:3742) ~[jooq-3.15.5.jar:?]
	at org.jooq.impl.RowField.lambda$new$0(RowField.java:125) ~[jooq-3.15.5.jar:?]
	at org.jooq.Converters.lambda$nullable$0(Converters.java:213) ~[jooq-3.15.5.jar:?]
	at org.jooq.Converter$1.from(Converter.java:178) ~[jooq-3.15.5.jar:?]
	at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:947) ~[jooq-3.15.5.jar:?]
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1558) ~[jooq-3.15.5.jar:?]
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1507) ~[jooq-3.15.5.jar:?]
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1466) ~[jooq-3.15.5.jar:?]
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143) ~[jooq-3.15.5.jar:?]
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1431) ~[jooq-3.15.5.jar:?]
	... 72 more
```

### Steps to reproduce the problem
Minimal example using testcontainers

```java
        try (Connection conn = DriverManager.getConnection("jdbc:tc:postgresql:14.1:///")) {
            var dsl = DSL.using(conn, SQLDialect.POSTGRES);
            var query = dsl.select(
                    row(
                            multiset(
                                    select(inline(1))
                            )
                    )
            );

            var result = query.fetchOne();
            System.out.println(result);
        }
```

### Versions

- jOOQ: 3.15.5
- Java: 17
- Database (include vendor): PostgreSQL 14.1
- OS: GNU/Linux 5.10.76
- JDBC Driver (include name if inofficial driver): postgresql 42.3.1

**Comment by lukaseder** [comment]
Thanks for your report. That's a bug. The current implementation of `ROW` uses a native implementation in PostgreSQL, when it's at the top level. But it shouldn't do that in case we have nested `MULTISET` expressions, because the emulation of `MULTISET` using `ARRAY` and `ARRAY_AGG` isn't implemented yet.

This should be an easy fix, similar to the fix that generates an XML or JSON emulation when `ROW` is nested in `MULTISET`, see https://github.com/jOOQ/jOOQ/issues/12021

**Comment by lukaseder** [comment]
As always, the fix isn't so easy as initially thought 😅. But definitely doable and worth doing. I think the only way forward here is to not make `ROW` a special case in comparison with `MULTISET`. It must follow the `MULTISET` emulation strategy, irrespective if it's at the top level or not, and irrespective if there's native `ROW` support as in PostgreSQL.

Once we do support `MULTISET` natively, or using the array emulation, we can revert to the current generation of `ROW` expressions in PostgreSQL, which will then be much more integration tested than it is today.

Fixing things this way will also have synergies with the fix for your other bug report: https://github.com/jOOQ/jOOQ/issues/12699

**Comment by lukaseder** [comment]
Following up on my underestimation before. If this is to be fixed thoroughly, then it might require a complete refactoring of the entire `EmbeddableRecord` implementation, which is currently assuming that an `EmbeddableRecord` is always flattened. But this isn't the case, and embeddables can also be placed inside of `ROW` or `MULTISET`, etc, see also https://github.com/jOOQ/jOOQ/issues/12021, https://github.com/jOOQ/jOOQ/issues/12237.

So, it might be a good idea to re-implement embeddable records to be nothing other than typed `ROW` expressions (which produce some `EmbeddableRecord` subtype rather than e.g. `Record2<T1, T2>`), and that they follow the same XML/JSON/ARRAY/Native emulation strategy as `MULTISET`/`ROW`.

This is a risky fix, and I don't see a backport to 3.15 possible for any of this, but definitely worth exploring for 3.16, still. Might fix a few open issues.

**Comment by lukaseder** [comment]
Anyway, always good to have a long(er) term perspective for improving things in the context of #12021, but perhaps, there *is* a fix possible just for this particular usage, by supporting nesting XML or JSON inside of PostgreSQL's object notation, which could be backported.

It seems that the fix I'm about to commit will make this test work for all emulations (XML/JSON/JSONB):

```java
public void testMultisetNestedInTopLevelRow() throws Exception {
    assertThrowsUnlessSupportsCorrelatedDerivedTables(() -> {
        testMultisetEmulations(ctx -> {
            Field<Result<Record1<Integer>>> ms = multiset(
                select(TBook_ID())
                .from(TBook())
                .where(TBook_AUTHOR_ID().eq(TAuthor_ID()))
                .orderBy(TBook_ID())
            );

            Result<Record3<
                Integer,
                Record1<Result<Record1<Integer>>>,
                Record3<
                    Integer,
                    Result<Record1<Integer>>,
                    Record2<
                        Integer,
                        Result<Record1<Integer>>
                    >
                >
            >> result =
            ctx.select(
                    TAuthor_ID(),
                    row(field(select(ms))),
                    row(TAuthor_ID(), ms, row(TAuthor_ID(), ms))
                )
               .from(TAuthor())
               .orderBy(TAuthor_ID())
               .fetch();

            assertEquals(asList(1, 2), result.map(r -> r.value1()));
            assertEquals(asList(asList(1, 2), asList(3, 4)), result.map(r1 -> r1.value2().value1().map(r2 -> r2.value1())));
            assertEquals(asList(1, 2), result.map(r -> r.value3().value1()));
            assertEquals(asList(asList(1, 2), asList(3, 4)), result.map(r1 -> r1.value3().value2().map(r2 -> r2.value1())));
            assertEquals(asList(1, 2), result.map(r -> r.value3().value3().value1()));
            assertEquals(asList(asList(1, 2), asList(3, 4)), result.map(r1 -> r1.value3().value3().value2().map(r2 -> r2.value1())));
        });
    });
}
```

That ought to cover about enough edge cases related to top level `ROW` expressions?

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.16.0 and 3.15.6 (https://github.com/jOOQ/jOOQ/issues/12707). Thanks again for your report!

**Comment by moxit0** [comment]
Hi, where can fixed versions (3.16.0 and 3.15.6 ) be found on Maven repository because I am unable to find them in Maven central repo?

**Comment by lukaseder** [comment]
The fix hasn't been released yet. You can download snapshot builds from here, if you're licensed: https://www.jooq.org/download/versions, or build from github

**Comment by moxit0** [comment]
Ok, Thank you.
