### ISSUE TITLE
Problem with truncate method

### ISSUE THREAD

**Issue by RenBrand** [jOOQ/jOOQ#12739]
Hi,

first of all you did a great job on jOOQ and it makes data queries a lot easier, but I think I've found an error in the truncate function if you add casts to it.

Here is my problem I have table containing lengths in kilometers and in my query I need it as meters.
```
create table station {
  id bigint primary key,
  lengthkm numeric(10, 7)
}
```
This is the SQL Query which I would like to run:
```
SELECT "station"."id"
       CAST(TRUNC(("station"."lengthkm" * 100000), 0) AS int) AS "station_length_cm"
  FROM "station";
```
So first convert the kilometers to meters and the truncate the decimal places, so the DB doesn't round. And last but not least I want to return it as integer. (Don't worry the possible overflow, it's a legacy database and the values in there hold only values from 0 - 1000 kilometer which can easily be held in an integer.)

This is the jOOQ code I use and which was also returned from you translate-service
```
DSL.select( STATION.ID,
            cast( trunc( STATION.LENGTHKM.multiply( inline( 100_000 ) ), inline(0) ), SQLDataType.INTEGER ).as( "station_length_cm" ))
     .from( STATION )
    .fetch();
```
The query jOOQ generates for a Postgres 13 looks like this:
```
select "station"."id",
       cast(cast(trunc(cast(("station"."lengthkm" * 100000) as numeric), 0) as numeric(10, 7)) as int) as "station_length_cm"
  from "station"
```
And causes this error:
```
org.springframework.dao.DataIntegrityViolationException: jOOQ; SQL [select "station"."id", cast(cast(trunc(cast(("station"."lengthkm" * 100000) as numeric), 0) as numeric(10, 7)) as int) as "station_length_cm" from "station"]; ERROR: numeric field overflow
  Detail: A field with precision 10, scale 7 must round to an absolute value less than 10^3.; nested exception is org.postgresql.util.PSQLException: ERROR: numeric field overflow
  Detail: A field with precision 10, scale 7 must round to an absolute value less than 10^3.
	at org.jooq_3.15.1.POSTGRES.debug(Unknown Source)
....
Caused by: org.postgresql.util.PSQLException: ERROR: numeric field overflow
  Detail: A field with precision 10, scale 7 must round to an absolute value less than 10^3.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:132)
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:94)
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:94)
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:94)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4131)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:230)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:335)
	... 
```

**Comment by lukaseder** [comment]
Thanks for your report. I'll investigate why that extra cast is happening.

In the meantime, try multiplying by `1000` instead of `100000`, and cast your column to `NUMERIC` (without precision / scale) explicitly

**Comment by RenBrand** [comment]
Thanks for the fast response.

The result would still be a BigDecimal but in meters instead of centimeter, but I've tried it and the same error happened. In the meantime I do the truncate in JAVA by simply calling Number#intValue().

```
jooqCtx.select( STATION.ID,
                DSL.cast( DSL.trunc( STATION.LENGTHKM.multiply( inline( 1000 ) ), inline( 0) ), NUMERIC).as( "station_length_cm" )
              )
         .from( STATION )
        .fetch();
```
Results in the SQL:
```
select "station"."id",
       cast(cast(trunc(cast(("station"."lengthkm" * 1000) as numeric), 0) as numeric(10, 7)) as numeric) as "station_length_cm"
  from "station"
```
and afterwards into the same Exception:
```
org.jooq.tools.LoggerListener org.jooq.exception.DataAccessException: SQL [select "station"."id", cast(cast(trunc(cast(("station"."lengthkm" * 1000) as numeric), 0) as numeric(10, 7)) as numeric) as "station_length_cm" from "station"]; ERROR: numeric field overflow
  Detail: A field with precision 10, scale 7 must round to an absolute value less than 10^3.
	at org.jooq_3.15.1.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2979)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:643)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:349)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:284)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2842)
...
Caused by: org.postgresql.util.PSQLException: ERROR: numeric field overflow
  Detail: A field with precision 10, scale 7 must round to an absolute value less than 10^3.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:132)
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:94)
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:94)
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:94)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4131)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:230)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:335)
```
