### ISSUE TITLE
How could a get ont to one relationship object once?

### ISSUE THREAD

**Issue by leeaee** [jOOQ/jOOQ#12763]
### Your question:
I have two object ```Admin``` and ```Role```, and they are one to one relationship, now, how could get them from one query?

```java
public class Admin {

	private Integer id;
	private String username;
	@JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
	private String password;
	private String mobile;
	private String email;
	private String truename;
	private String avatar;
	private AdminRole role;
	private Boolean isBuiltIn;
	private AdminState state;
	private LocalDateTime createTime;
	private LocalDateTime updateTime;
	private Integer version;

}
```
```java
public class AdminRole {

	private Integer id;
	private String name;
	private String code;
	private Boolean isBuiltIn;
	private List<String> permissions;
	private String note;
	private LocalDateTime createTime;
	private LocalDateTime updateTime;
	private Integer version;

}
```
my jooq dao access as:
```java
    public Optional<Admin> find(String username) {
        Admin admin = ctx.select(T_ADMIN.fields()).select(field(select(jsonObject(T_ADMIN_ROLE.fields())).from(T_ADMIN_ROLE).where(T_ADMIN_ROLE.CODE.eq(T_ADMIN.ROLE_CODE)).asField()).as("role")).from(T_ADMIN).where(T_ADMIN.USERNAME.eq(username))
                .fetchOne(r -> r.into(Admin.class));
        return Optional.ofNullable(admin);
    }
```
the respones show the sql return as
``` log
2021-12-23 23:56:06.542 DEBUG 6033 --- [nio-8080-exec-1] org.jooq.tools.LoggerListener            : Fetched result           : +----+--------+--------------------------------------------------+-----------+------+-------------+----------------------+-------------+-----------+------+--------------------------+--------------------------+-------+--------------------------------------------------+
2021-12-23 23:56:06.543 DEBUG 6033 --- [nio-8080-exec-1] org.jooq.tools.LoggerListener            :                          : |  id|username|password                                          |mobile     |email |truename     |avatar                |role_code    |is_built_in|state |create_time               |update_time               |version|role                                              |
2021-12-23 23:56:06.543 DEBUG 6033 --- [nio-8080-exec-1] org.jooq.tools.LoggerListener            :                          : +----+--------+--------------------------------------------------+-----------+------+-------------+----------------------+-------------+-----------+------+--------------------------+--------------------------+-------+--------------------------------------------------+
2021-12-23 23:56:06.544 DEBUG 6033 --- [nio-8080-exec-1] org.jooq.tools.LoggerListener            :                          : |   1|admin   |{bcrypt}$2a$10$gUoHGXKUNlURDHhFd8nVSOSrxzqXBB0Z...|10000000000|{null}|Administrator|/assets/img/avatar.png|administrator|true       |normal|2021-12-23T18:37:51.545012|2021-12-23T18:37:51.545012|      0|{"id" : 3, "code" : "administrator", "name" : "...|
2021-12-23 23:56:06.545 DEBUG 6033 --- [nio-8080-exec-1] org.jooq.tools.LoggerListener            :                          : +----+--------+--------------------------------------------------+-----------+------+-------------+----------------------+-------------+-----------+------+--------------------------+--------------------------+-------+--------------------------------------------------+
2021-12-23 23:56:06.545 DEBUG 6033 --- [nio-8080-exec-1] org.jooq.tools.LoggerListener            : Fetched row(s)           : 1
```
but it could not mapping into ```Admin``` as the error shows
```log
Caused by: org.jooq.exception.DataTypeException: Error while mapping JSON to POJO using Jackson
	at org.jooq.impl.Convert$ConvertAll.from(Convert.java:1191)
	at org.jooq.impl.Convert.convert0(Convert.java:432)
	at org.jooq.impl.Convert.convert(Convert.java:507)
	at org.jooq.impl.DefaultConverterProvider$1.from(DefaultConverterProvider.java:123)
	at org.jooq.impl.AbstractRecord.get(AbstractRecord.java:353)
	at org.jooq.impl.DefaultRecordMapper$MutablePOJOMapper.map(DefaultRecordMapper.java:943)
	at org.jooq.impl.DefaultRecordMapper$MutablePOJOMapper.map(DefaultRecordMapper.java:873)
	... 78 common frames omitted
```

how could mapping the result into javabean or is there any other way better?

### Versions:

- jOOQ: 3.15.5
- Java: 11
- Database (include vendor): postgresql
- OS: MacOS
- JDBC Driver (include name if inofficial driver): postgresql-42.2.23

**Comment by lukaseder** [comment]
Can you please post the complete stack trace including the reason why Jackson couldn't map your JSON?

> how could mapping the result into javabean or is there any other way better?

Starting from jOOQ 3.15, a better way is to let jOOQ manage the whole JSON mapping for you transparently, and type safely, using:

- `MULTISET`: https://www.jooq.org/doc/latest/manual/sql-building/column-expressions/multiset-value-constructor/
- `ROW`: https://www.jooq.org/doc/latest/manual/sql-building/column-expressions/nested-records/
- Ad hoc converters: https://www.jooq.org/doc/latest/manual/sql-execution/fetching/ad-hoc-converter/

Wrapped up in a blog post: https://blog.jooq.org/jooq-3-15s-new-multiset-operator-will-change-how-you-think-about-sql/

**Comment by leeaee** [comment]
The complete stact trace is here
```log
Caused by: org.jooq.exception.DataTypeException: Error while mapping JSON to POJO using Jackson
	at org.jooq.impl.Convert$ConvertAll.from(Convert.java:1191)
	at org.jooq.impl.Convert.convert0(Convert.java:432)
	at org.jooq.impl.Convert.convert(Convert.java:507)
	at org.jooq.impl.DefaultConverterProvider$1.from(DefaultConverterProvider.java:123)
	at org.jooq.impl.AbstractRecord.get(AbstractRecord.java:353)
	at org.jooq.impl.DefaultRecordMapper$MutablePOJOMapper.map(DefaultRecordMapper.java:943)
	at org.jooq.impl.DefaultRecordMapper$MutablePOJOMapper.map(DefaultRecordMapper.java:873)
	... 78 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jooq.impl.Convert$ConvertAll.from(Convert.java:1188)
	... 84 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "is_built_in" (class com.houlolo.houmart.bean.domain.pojo.AdminRole), not marked as ignorable (8 known properties: "note", "permissions", "updateTime", "version", "createTime", "id", "code", "name"])
 at [Source: (String)"{"id" : 3, "code" : "administrator", "name" : "Admin", "is_built_in" : true, "permissions" : ["admin:retrieve","admin:create","admin:update","admin:delete","arole:retrieve","arole:create","arole:update","arole:delete","apermission:retrieve","apermission:create","apermission:update","apermission:delete"], "note" : null, "create_time" : "2021-11-27T15:41:44.265044", "update_time" : "2021-11-27T15:41:44.265044", "version" : 0}"; line: 1, column: 74] (through reference chain: com.houlolo.houmart.bean.domain.pojo.AdminRole["is_built_in"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1989)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1678)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:319)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4675)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3630)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3598)
	... 89 common frames omitted
```
And the SQL response JSON string of role is
```
{"id" : 3, "code" : "administrator", "name" : "Admin", "is_built_in" : true, "permissions" : ["admin:retrieve","admin:create","admin:update","admin:delete","arole:retrieve","arole:create","arole:update","arole:delete","apermission:retrieve","apermission:create","apermission:update","apermission:delete"], "note" : null, "create_time" : "2021-11-27T15:41:44.265044", "update_time" : "2021-11-27T15:41:44.265044", "version" : 0}
```
I think the Jackson could not mapping ```is_built_in``` to ```isBuiltIn```.
When I use ```MULTISET```, it could mapping to List<AdminRole> correctly. I will try using ```row``` and I think it could better to mapping the object with ```field```.

Merry Christmas :)

**Comment by lukaseder** [comment]
Well, it seems your `T_ADMIN_ROLE` table doesn't contain any `is_built_in` columns and Jackson seems to require an exact mapping (whereas jOOQ's `DefaultRecordMapper` is more lenient). Anyway, with `MULTISET` and ad-hoc converters, everything is type safe, and you can detect such mismatches at compile time...
