### ISSUE TITLE
Avoid vendor specific JDBC driver logic when using the parser

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12786]
jOOQ currently has a few JDBC driver dependencies to access vendor specific functionality for:

- Oracle (UDTs, LOBs, etc.)
- PostgreSQL (Intervals, etc.)
- SQL Server (TVPs)

This is certainly acceptable when running queries with jOOQ, since the queries have to be run on those JDBC drivers. But when generating SQL, we should avoid the dependencies, because parser users might be generating SQL but don't have a driver on their classpath.

An example error stacktrace from a customer is:

```
Exception in thread "main" java.lang.RuntimeException: A class definition could not be found when running the CLI utility.

This is mostly due to a missing dependency. Make sure you have added the right dependencies
as according to the manual for https://www.jooq.org/doc/3.16/manual/sql-building/sql-parser/sql-parser-cli/

     at org.jooq.CLIUtil.main(CLIUtil.java:64)
     at org.jooq.ParserCLI.main(ParserCLI.java:72)
     at parserpro.main(parserpro.java:12)
Caused by: java.lang.NoClassDefFoundError: org/postgresql/util/PGInterval
     at org.jooq.util.postgres.PostgresUtils.toPGInterval(PostgresUtils.java:214)
     at org.jooq.impl.DefaultBinding$DefaultDayToSecondBinding.sqlInline0(DefaultBinding.java:2334)
     at org.jooq.impl.DefaultBinding$DefaultDayToSecondBinding.sqlInline0(DefaultBinding.java:2315)
     at org.jooq.impl.DefaultBinding$AbstractBinding.sql(DefaultBinding.java:922)
     at org.jooq.impl.DefaultBinding$AbstractBinding.sqlCast(DefaultBinding.java:887)
     at org.jooq.impl.DefaultBinding$AbstractBinding.sqlCast(DefaultBinding.java:857)
     at org.jooq.impl.DefaultBinding$AbstractBinding.sql(DefaultBinding.java:910)
     at org.jooq.impl.Val.accept(Val.java:186)
     at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:720)
     at org.jooq.impl.AbstractContext.visit(AbstractContext.java:295)
     at org.jooq.impl.Sub.accept0(Sub.java:106)
     at org.jooq.impl.AbstractTransformable.accept(AbstractTransformable.java:70)
     at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:720)
     at org.jooq.impl.AbstractContext.visit(AbstractContext.java:246)
     at org.jooq.impl.QueryPartCollectionView.acceptElement(QueryPartCollectionView.java:224)
     at org.jooq.impl.QueryPartCollectionView.lambda$accept$1(QueryPartCollectionView.java:198)
     at org.jooq.impl.AbstractContext.toggle(AbstractContext.java:338)
     at org.jooq.impl.AbstractContext.data(AbstractContext.java:349)
     at org.jooq.impl.QueryPartCollectionView.accept(QueryPartCollectionView.java:195)
     at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:720)
     at org.jooq.impl.AbstractContext.visit(AbstractContext.java:295)
     at org.jooq.impl.SelectQueryImpl.toSQLReference0(SelectQueryImpl.java:2197)
     at org.jooq.impl.SelectQueryImpl.lambda$toSQLReferenceLimitDefault$29(SelectQueryImpl.java:1861)
     at org.jooq.impl.AbstractContext.toggle(AbstractContext.java:338)
     at org.jooq.impl.AbstractContext.data(AbstractContext.java:349)
     at org.jooq.impl.SelectQueryImpl.toSQLReferenceLimitDefault(SelectQueryImpl.java:1861)
     at org.jooq.impl.SelectQueryImpl.accept0(SelectQueryImpl.java:1775)
     at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:1430)
     at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:720)
     at org.jooq.impl.AbstractContext.visit(AbstractContext.java:295)
     at org.jooq.impl.InsertQueryImpl.toSQLInsert(InsertQueryImpl.java:694)
     at org.jooq.impl.InsertQueryImpl.accept0(InsertQueryImpl.java:624)
     at org.jooq.impl.AbstractDMLQuery.accept(AbstractDMLQuery.java:648)
     at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:720)
     at org.jooq.impl.AbstractContext.visit(AbstractContext.java:295)
     at org.jooq.impl.AbstractDelegatingQuery.accept(AbstractDelegatingQuery.java:90)
     at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:720)
     at org.jooq.impl.AbstractContext.visit(AbstractContext.java:295)
     at org.jooq.impl.QueriesImpl.accept(QueriesImpl.java:167)
     at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:720)
     at org.jooq.impl.AbstractContext.visit(AbstractContext.java:295)
     at org.jooq.impl.DefaultDSLContext.render(DefaultDSLContext.java:710)
     at org.jooq.ParserCLI.render(ParserCLI.java:481)
     at org.jooq.ParserCLI.lambda$main$0(ParserCLI.java:90)
     at org.jooq.CLIUtil.main(CLIUtil.java:55)
     ... 2 more
Caused by: java.lang.ClassNotFoundException: org.postgresql.util.PGInterval
     at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
     at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
     ... 47 more
```

It's obviously possible to solve this (by adding the pgjdbc dependency), but it would be better if it can never happen.

**Comment by lukaseder** [comment]
The PostgreSQL specific parts have been implemented here: https://github.com/jOOQ/jOOQ/issues/13053

Closing this as a duplicate of https://github.com/jOOQ/jOOQ/issues/13053
