### ISSUE TITLE
Parser and code generator does not recognise H2 2.0's BINARY VARYING and other standard SQL data type synonyms

### ISSUE THREAD

**Issue by oflege** [jOOQ/jOOQ#12794]
### Expected behavior
h2 column w/ type BINARY VARYING (http://h2database.com/html/datatypes.html#binary_varying_type)
mapped to byte[]

### Actual behavior
mapped to java.lang.Object

### Steps to reproduce the problem
```  
       val create = DSL.using("jdbc:h2:mem:test")
        create.execute("create table t(id BINARY VARYING)")
        GenerationTool().apply {
            setConnection(create.parsingConnection())
        }.run(Configuration().withGenerator(Generator().withDatabase(Database().withInputSchema("PUBLIC"))))
```
### Versions

- jOOQ: 3.16.0
- Database (include vendor): h2 2.0.202

**Comment by lukaseder** [comment]
Thanks a lot for your report. I can reproduce this:

```
org.jooq.impl.ParserException: Token ')' expected: [1:26] create table t (c binary [*]varying)
	at org.jooq.impl.DefaultParseContext.expected(ParserImpl.java:13926)
	at org.jooq.impl.DefaultParseContext.parse(ParserImpl.java:13186)
	at org.jooq.impl.DefaultParseContext.parse(ParserImpl.java:13181)
	at org.jooq.impl.DefaultParseContext.parseCreateTable(ParserImpl.java:4322)
	at org.jooq.impl.DefaultParseContext.parseCreate(ParserImpl.java:2757)
	at org.jooq.impl.DefaultParseContext.parseQuery(ParserImpl.java:1052)
	at org.jooq.impl.DefaultParseContext.lambda$2(ParserImpl.java:891)
	at org.jooq.impl.DefaultParseContext.wrap(ParserImpl.java:14138)
	at org.jooq.impl.DefaultParseContext.parseQuery0(ParserImpl.java:891)
	at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:712)
	at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:707)
	at org.jooq.impl.AbstractParserTest.lambda$14(AbstractParserTest.java:312)
	at org.jooq.impl.AbstractParserTest.assertEquality(AbstractParserTest.java:473)
	at org.jooq.impl.AbstractParserTest.assertQueryEquals(AbstractParserTest.java:312)
	at org.jooq.impl.AbstractParserTest.assertQueryEqualsAll(AbstractParserTest.java:317)
	at org.jooq.impl.ParserDDLStatementTest.testCreateTableDataTypes(ParserDDLStatementTest.java:498)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

There are numerous data type names in H2 (and standard SQL) that jOOQ's parser doesn't currently recognise. I will fix all of them via this ticket.

**Comment by lukaseder** [comment]
Affected data type names (list will be amended):

- [x] `BINARY VARYING`

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.17.0 and 3.16.1 (https://github.com/jOOQ/jOOQ/issues/12797).

Thanks again for the report!

**Comment by lukaseder** [comment]
Note, forgot to mention the workaround: You can use `VARBINARY` instead...

**Comment by oflege** [comment]
I'm not sure about whether this fixes my issue. My problem is that columns in a h2 2.0.202 database declared as VARYING BINARY (or VARBINARY or BYTEA)  are not mapped correctly by the GenerationTool. I did not encounter any problems with the Parser. Instead, the generated classes contain columns declared with type `java.lang.Object` instead of `byte[]`. That's because the meta information from h2 returns the column's type as `VARYING BINARY` and there is no matching DataType in `org.jooq.util.h2.H2DataType`

**Comment by lukaseder** [comment]
Yes, the parser, which you were using (`create.parsingConnection()`) didn't recognise the data types and in your case, ignored the unknown data type.

**Comment by lukaseder** [comment]
Oh, I see what you mean, H2 has changed what they report in the `INFORMATION_SCHEMA`, and that, too, isn't recognised by jOOQ.

**Comment by lukaseder** [comment]
Yeah, our integration tests only cover the `BLOB` type for some reason. Should start testing the other binary types too, explicitly.

**Comment by lukaseder** [comment]
Fixed `H2DataType` as well

**Comment by lukaseder** [comment]
A 3.16.1 release has been published (including a security patch for the H2 dependency: https://github.com/jOOQ/jOOQ/issues/12795)
