### ISSUE TITLE
Improve parser error message when encountering unterminated quoted identifier

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12832]
In a parser test case that I'm looking int, jOOQ is digesting some third party generated SQL, which is invalid, e.g.

```sql
INSERT INTO `a` (`b`) VALUES ([B@7bcbf479);
```

The bind value is binary and inlined, and produces the usual not too useful Java `byte[].toString()` content. jOOQ's parser trips over the `[` character, which opens up a T-SQL quoted identifier, which might never be terminated in the same script. A sample error message is:

```
Caused by: org.jooq.impl.ParserException: Quoted identifier must terminate in ]: [3895:1] ...;[*]
	at org.jooq.impl.DefaultParseContext.exception(ParserImpl.java:14059)
	at org.jooq.impl.DefaultParseContext.parseIdentifierIf(ParserImpl.java:11826)
	at org.jooq.impl.DefaultParseContext.parseIdentifierIf(ParserImpl.java:11795)
	at org.jooq.impl.DefaultParseContext.parseNameIf(ParserImpl.java:11717)
	at org.jooq.impl.DefaultParseContext.parseName(ParserImpl.java:11707)
	at org.jooq.impl.DefaultParseContext.parseFieldNameOrSequenceExpression(ParserImpl.java:11621)
	at org.jooq.impl.DefaultParseContext.parseTerm(ParserImpl.java:8904)
	at org.jooq.impl.DefaultParseContext.parseUnaryOps(ParserImpl.java:7789)
	at org.jooq.impl.DefaultParseContext.parseExp(ParserImpl.java:7763)
	at org.jooq.impl.DefaultParseContext.parseFactor(ParserImpl.java:7740)
	at org.jooq.impl.DefaultParseContext.parseSum(ParserImpl.java:7686)
	at org.jooq.impl.DefaultParseContext.parseNumericOp(ParserImpl.java:7671)
	at org.jooq.impl.DefaultParseContext.parseCollated(ParserImpl.java:7534)
	at org.jooq.impl.DefaultParseContext.parseConcat(ParserImpl.java:7524)
	at org.jooq.impl.DefaultParseContext.parsePredicate(ParserImpl.java:6393)
	at org.jooq.impl.DefaultParseContext.parseNot(ParserImpl.java:6250)
	at org.jooq.impl.DefaultParseContext.parseAnd(ParserImpl.java:6240)
	at org.jooq.impl.DefaultParseContext.parseOr(ParserImpl.java:6231)
	at org.jooq.impl.DefaultParseContext.parseField(ParserImpl.java:7435)
	at org.jooq.impl.DefaultParseContext.lambda$36(ParserImpl.java:2218)
	at org.jooq.impl.DefaultParseContext.parseList(ParserImpl.java:12892)
	at org.jooq.impl.DefaultParseContext.parseList(ParserImpl.java:12879)
	at org.jooq.impl.DefaultParseContext.parseInsert(ParserImpl.java:2218)
	at org.jooq.impl.DefaultParseContext.parseQuery(ParserImpl.java:1134)
	at org.jooq.impl.DefaultParseContext.lambda$0(ParserImpl.java:874)
	at org.jooq.impl.DefaultParseContext.wrap(ParserImpl.java:14252)
	at org.jooq.impl.DefaultParseContext.parse(ParserImpl.java:854)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:732)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:727)
	at org.jooq.impl.ParseFilesTest.parse(ParseFilesTest.java:138)
	... 36 more
```

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.17.0 and 3.16.2 (https://github.com/jOOQ/jOOQ/issues/12833)
