### ISSUE TITLE
NullPointerException in MetaDataFieldProvider when reading plain SQL column without a name in MySQL

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12966]
A recently added integration test for https://github.com/jOOQ/jOOQ/issues/12666 has failed on MySQL when we try to parse and translate `SELECT ?`, and then fetch the result via the `ParsingConnection`:

The assumption that `java.sql.ResultSetMetaData::getColumnName` always returns a non-`null` value is wrong. The ensuing exception is:

```
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "columnName" is null
	at org.jooq.impl.MetaDataFieldProvider.init(MetaDataFieldProvider.java:103)
	at org.jooq.impl.MetaDataFieldProvider.<init>(MetaDataFieldProvider.java:77)
	at org.jooq.impl.DefaultDSLContext.fetchLazy(DefaultDSLContext.java:1267)
	at org.jooq.impl.DefaultDSLContext.fetch(DefaultDSLContext.java:1126)
	at org.jooq.test.all.testcases.ParserTests.testResult(ParserTests.java:595)
	at org.jooq.test.all.testcases.ParserTests.testTranslateSQLExecuteJDBCDirectlyWithBindVariablesInputStreamAndReader(ParserTests.java:568)
	at org.jooq.test.jOOQAbstractTest.testTranslateSQLExecuteJDBCDirectlyWithBindVariablesInputStreamAndReader(jOOQAbstractTest.java:9451)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:30)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.17.0, 3.16.4 (https://github.com/jOOQ/jOOQ/issues/12967), and 3.15.8 (https://github.com/jOOQ/jOOQ/issues/12968)
