### ISSUE TITLE
java.lang.StackOverflowError at org.jooq.tools.Convert.convert

### ISSUE THREAD

**Issue by twinkelmann** [jOOQ/jOOQ#13022]
### Expected behavior

Our API Endpoint is supposed to recieve a DTO as JSON, do very simple logic, then insert it into the database.
Here is the API endpoint for reference.

```java
  @PostMapping(API_URL)
  public ResponseEntity<ScenariosDto> insertScenarios(@PathVariable Long projectId,
      @RequestBody ScenariosDto dto) {

    ScenariosDto resp = null;
    var httpStatus = HttpStatus.CREATED;

    dto.setId(null);

    try {
      if (this.service.exists(dto)) {
        httpStatus = HttpStatus.CONFLICT;
      } else if (!projectId.equals(dto.getProjectId())) {
        httpStatus = HttpStatus.BAD_REQUEST;
      } else {
        if (scenarioSettingsService.fetchByProjectId(projectId).isEmpty()) {
          ScenarioSettingsDto scenarioSettingsDto = new ScenarioSettingsDto();
          scenarioSettingsDto.setProjectId(projectId);
          scenarioSettingsService.insert(scenarioSettingsDto);
        }
        this.service.insert(dto);
        resp = dto;
      }
    } catch (Exception e) {
      httpStatus = HttpStatus.INTERNAL_SERVER_ERROR;
      e.printStackTrace();
    }

    return new ResponseEntity<ScenariosDto>(resp, this.jsonHeaders, httpStatus);
  }
```

### Actual behavior

Before even reaching the endpoint, the app crashes and returns a 500 error.
The error message is as follows (cut short because it repeast the last 3 lines for a good while):

```log
2022-02-08 13:10:37 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.StackOverflowError] with root cause
java.lang.StackOverflowError: null
        at java.base/java.lang.Class.reflectionData(Class.java:2978)
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3126)
        at java.base/java.lang.Class.getConstructors(Class.java:1943)
        at org.jooq.tools.Convert$ConvertAll.from(Convert.java:1186)
        at org.jooq.tools.Convert.convert0(Convert.java:394)
        at org.jooq.tools.Convert.convert(Convert.java:467)
        at org.jooq.tools.Convert$ConvertAll.from(Convert.java:1191)
        at org.jooq.tools.Convert.convert0(Convert.java:394)
        at org.jooq.tools.Convert.convert(Convert.java:467)
[...]
```

The same error occurs in the "export" feature of our app. This feature turns all data into JSON, then zips it.
If we delete a certain part of the data in the database, the "export" feature works. The data we have to delete before it works is as follows (extract from the Jooq DTO, and from the DTOs of 2 custom associated types):

```java
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScenarioSettingsDto implements Serializable {

  private static final long serialVersionUID = 1L;

  private Long        id;
  private Long        projectId;
  private EtElevRow[] etElevs;
  private PElevRow[]  pElevs;
  private Boolean     etInterCubic;
  private Boolean     pInterCubic;
  private Double[]    etPerMonth;

  public ScenarioSettingsDto() {}
[...]

@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EtElevRow implements Serializable {

  private static final long serialVersionUID = 1L;

  private Double elevation;
  private Double et;

  public EtElevRow() {}
[...]

SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PElevRow implements Serializable {

  private static final long serialVersionUID = 1L;

  private Double elevation;
  private Double p;

  public PElevRow() {}
[...]
```

Here is the SQL for the corresponding table:

```sql
CREATE TABLE public.scenario_settings (
	id bigserial NOT NULL,
	project_id int8 NOT NULL,
	et_elevs _et_elev_row NULL,
	p_elevs _p_elev_row NULL,
	et_inter_cubic bool NULL DEFAULT false,
	p_inter_cubic bool NULL DEFAULT false,
	et_per_month _float8 NULL,
	CONSTRAINT scenario_settings_pkey PRIMARY KEY (id)
);

CREATE TYPE et_elev_row AS (
	elevation float8,
	et float8);

CREATE TYPE p_elev_row AS (
	elevation float8,
	p float8);
```

We cannot figure out what produces the infinite loop, and it is very hard to debug, because we don't know where it starts.

### Steps to reproduce the problem

Our app is medium sized and has been in development for multiple years, so I don't really know what to share here. 

### Versions

- jOOQ: `3.15.1`
- Java: `openjdk version "11.0.13" 2021-10-19`
- Database (include vendor): `psql (PostgreSQL) 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)` with Postgis
- OS: `Ubuntu 20.04.3 LTS 64-bit`
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks a lot for your report.

> We cannot figure out what produces the infinite loop, and it is very hard to debug, because we don't know where it starts.

Yes, unfortunately, `StackOverflowError` shows only the irrelevant last bits of the stack, not the initial entry point. But you could place a breakpoint here:

```
at org.jooq.tools.Convert.convert(Convert.java:467)
```

And look at the call stack in the debugger. I can try to reproduce this, but it might take a while. Any more specific information you can provide would still be helpful. E.g. what is this doing?

```java
scenarioSettingsService.insert(scenarioSettingsDto);
```

**Comment by lukaseder** [comment]
To rule out existing fixes, have you tried upgrading to the latest 3.15.x or 3.16.x versions?

**Comment by twinkelmann** [comment]
Thanks for your answer.

> To rule out existing fixes, have you tried upgrading to the latest 3.15.x or 3.16.x versions?

Since we assumed the error was on our side, we haven't tried upgrading jOOQ yet.
My colleague suggested we report this here, in case it either is a common mistake on our side that you would be able to point out, or in case it actually is a bug in jOOQ.

> And look at the call stack in the debugger. I can try to reproduce this, but it might take a while. Any more specific information you can provide would still be helpful. E.g. what is this doing?

It pretty much just inserts the data using the jOOQ DAO.
This is necessary because this particular object might be inexistent for that "project".

```java
public ScenarioSettingsDto insert(ScenarioSettingsDto scenarioSettingsDto) {
    scenarioSettingsDto.setId(null);
    dao.insert(scenarioSettingsDto);
    return scenarioSettingsDto;
  }
```

I'm going to try setting a debug point in the convert method.
Here is the data structure for the "Scenario", in case it provides insights. Together with ScenarioSettingsDto, ScenarioDto is very likely to be causing the error, since it is the type that has to be parsed when we call the API endpoint.

```java
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScenariosDto implements Serializable {

  private static final long serialVersionUID = 1L;

  private Long                  id;
  private Long                  projectId;
  private String                name;
  private ScenarioTimescale     scenarioTimescale;
  private ScenarioPrecipitation precipitation;
  private ScenarioCloud         cloud;

  public ScenariosDto() {}
[...]

@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum ScenarioTimescale implements EnumType {

  FewDays("FewDays"),

  FewSeasons("FewSeasons"),

  FewDecades("FewDecades");

  private final String literal;

  private ScenarioTimescale(String literal) {
    this.literal = literal;
  }
[...]

@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScenarioPrecipitation implements Serializable {

  private static final long serialVersionUID = 1L;

  private OffsetDateTime precipitationStartDate;
  private Double[]       rainFalls;
  private String         comment;

  public ScenarioPrecipitation() {}
[...]

@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScenarioCloud implements Serializable {

  private static final long serialVersionUID = 1L;

  private Double  cloudElevation;
  private Double  xMin;
  private Double  xMax;
  private Double  yMin;
  private Double  yMax;
  private Boolean isFullExtent;
  private String  comment;

  public ScenarioCloud() {}
[...]
```

And the equivalent SQL

```sql
CREATE TABLE public.scenarios (
	id bigserial NOT NULL,
	project_id int8 NOT NULL,
	"name" varchar(100) NOT NULL,
	scenario_timescale scenario_timescale NULL,
	precipitation scenario_precipitation NULL,
	cloud scenario_cloud NULL,
	CONSTRAINT scenarios_pkey PRIMARY KEY (id)
);

CREATE TYPE scenario_timescale AS ENUM (
	'FewDays',
	'FewSeasons',
	'FewDecades');

CREATE TYPE scenario_precipitation AS (
	precipitation_start_date timestamptz,
	rain_falls _float8,
	"comment" varchar(200));

CREATE TYPE scenario_cloud AS (
	cloud_elevation float8,
	x_min float8,
	x_max float8,
	y_min float8,
	y_max float8,
	is_full_extent bool,
	"comment" varchar(200));
```

**Comment by twinkelmann** [comment]
I've got a nice stack trace for you. Hand tight:

```log
Convert.convert(Object,Class) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:467)
Convert$ConvertAll.from(Object) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:1191)
Convert.convert0(Object,Converter) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:394)
Convert.convert(Object,Class) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:467)
Convert$ConvertAll.from(Object) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:1191)
Convert.convert0(Object,Converter) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:394)
Convert.convert(Object,Class) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:467)
Convert$ConvertAll.from(Object) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:1191)
Convert.convert0(Object,Converter) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:394)
Convert.convert(Object,Class) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:467)
Convert$ConvertAll.from(Object) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:1191)
Convert.convert0(Object,Converter) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:394)
Convert.convert(Object,Class) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:467)
Convert$ConvertAll.from(Object) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:1191)
Convert.convert0(Object,Converter) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:394)
Convert.convert(Object,Class) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:467)
Convert$ConvertAll.from(Object) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:1191)
Convert.convert0(Object,Converter) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:394)
Convert.convert(Object,Class) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:467)
Convert$ConvertAll.from(Object) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:1191)
Convert.convert0(Object,Converter) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:394)
Convert.convert(Object,Class) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:467)
Convert$ConvertAll.from(Object) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:1191)
Convert.convert0(Object,Converter) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:394)
Convert.convert(Object,Class) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:467)
Convert$ConvertAll.from(Object) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:1191)
Convert.convert0(Object,Converter) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:394)
Convert.convert(Object,Class) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:467)
Convert.convertArray(Object[],Class) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:356)
Convert$ConvertAll.from(Object) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:607)
Convert.convert0(Object,Converter) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:394)
Convert.convert(Object,Class) (/jooq-3.14.11.jar/org.jooq.tools/Convert.class:467)
DefaultBinding$DefaultArrayBinding.convertArray(Array,Class) (/jooq-3.14.11.jar/org.jooq.impl/DefaultBinding.class:1268)
DefaultBinding$DefaultArrayBinding.pgGetArray(Scope,ResultSet,DataType,int) (/jooq-3.14.11.jar/org.jooq.impl/DefaultBinding.class:1212)
DefaultBinding$DefaultArrayBinding.get0(BindingGetResultSetContext) (/jooq-3.14.11.jar/org.jooq.impl/DefaultBinding.class:1165)
DefaultBinding$DefaultArrayBinding.get0(BindingGetResultSetContext) (/jooq-3.14.11.jar/org.jooq.impl/DefaultBinding.class:1019)
DefaultBinding$AbstractBinding.get(BindingGetResultSetContext) (/jooq-3.14.11.jar/org.jooq.impl/DefaultBinding.class:871)
CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(AbstractRecord,Field,int) (/jooq-3.14.11.jar/org.jooq.impl/CursorImpl.class:1725)
CursorImpl$CursorIterator$CursorRecordInitialiser.operate(AbstractRecord) (/jooq-3.14.11.jar/org.jooq.impl/CursorImpl.class:1684)
CursorImpl$CursorIterator$CursorRecordInitialiser.operate(Record) (/jooq-3.14.11.jar/org.jooq.impl/CursorImpl.class:1643)
RecordDelegate.operate(RecordOperation) (/jooq-3.14.11.jar/org.jooq.impl/RecordDelegate.class:149)
CursorImpl$CursorIterator.fetchNext() (/jooq-3.14.11.jar/org.jooq.impl/CursorImpl.class:1608)
CursorImpl$CursorIterator.hasNext() (/jooq-3.14.11.jar/org.jooq.impl/CursorImpl.class:1584)
CursorImpl.fetchNext(int) (/jooq-3.14.11.jar/org.jooq.impl/CursorImpl.class:349)
CursorImpl.fetch(int) (/jooq-3.14.11.jar/org.jooq.impl/CursorImpl.class:336)
CursorImpl.fetch() (/jooq-3.14.11.jar/org.jooq.impl/CursorImpl.class:243)
AbstractResultQuery.execute(ExecuteContext,ExecuteListener) (/jooq-3.14.11.jar/org.jooq.impl/AbstractResultQuery.class:312)
AbstractQuery.execute() (/jooq-3.14.11.jar/org.jooq.impl/AbstractQuery.class:375)
AbstractResultQuery.fetch() (/jooq-3.14.11.jar/org.jooq.impl/AbstractResultQuery.class:337)
AbstractResultQuery.fetch(RecordMapper) (/jooq-3.14.11.jar/org.jooq.impl/AbstractResultQuery.class:1537)
SelectImpl.fetch(RecordMapper) (/jooq-3.14.11.jar/org.jooq.impl/SelectImpl.class:3951)
DAOImpl.fetch(Field,Object[]) (/jooq-3.14.11.jar/org.jooq.impl/DAOImpl.class:353)
ScenarioSettingsDao.fetchByProjectId(Long[]) (/home/isska/VISKAR/src/server/jooq/src/main/java/ch/isska/viskar/jooq/public_/tables/daos/ScenarioSettingsDao.java:56)
ScenarioSettingsDao$$FastClassBySpringCGLIB$$d4c719b6.invoke(int,Object,Object[]) (Unknown Source:-1)
MethodProxy.invoke(Object,Object[]) (/spring-core-5.3.8.jar/org.springframework.cglib.proxy/MethodProxy.class:218)
CglibAopProxy$CglibMethodInvocation.invokeJoinpoint() (/spring-aop-5.3.8.jar/org.springframework.aop.framework/CglibAopProxy.class:779)
ReflectiveMethodInvocation.proceed() (/spring-aop-5.3.8.jar/org.springframework.aop.framework/ReflectiveMethodInvocation.class:163)
CglibAopProxy$CglibMethodInvocation.proceed() (/spring-aop-5.3.8.jar/org.springframework.aop.framework/CglibAopProxy.class:750)
PersistenceExceptionTranslationInterceptor.invoke(MethodInvocation) (/spring-tx-5.3.8.jar/org.springframework.dao.support/PersistenceExceptionTranslationInterceptor.class:137)
ReflectiveMethodInvocation.proceed() (/spring-aop-5.3.8.jar/org.springframework.aop.framework/ReflectiveMethodInvocation.class:186)
CglibAopProxy$CglibMethodInvocation.proceed() (/spring-aop-5.3.8.jar/org.springframework.aop.framework/CglibAopProxy.class:750)
CglibAopProxy$DynamicAdvisedInterceptor.intercept(Object,Method,Object[],MethodProxy) (/spring-aop-5.3.8.jar/org.springframework.aop.framework/CglibAopProxy.class:692)
ScenarioSettingsDao$$EnhancerBySpringCGLIB$$e8617ba3.fetchByProjectId(Long[]) (Unknown Source:-1)
ScenarioSettingsService.fetchByProjectId(long) (/home/isska/VISKAR/src/server/spring-restAPI/src/main/java/ch/isska/viskar/spring/service/jooq/ScenarioSettingsService.java:25)
ScenarioController.insertScenarios(Long,ScenariosDto) (/home/isska/VISKAR/src/server/spring-restAPI/src/main/java/ch/isska/viskar/spring/controller/ScenarioController.java:83)
```

This is what I captured in my initially described case, calling the API Endpoint.
Turns out it does enter the endpoint. And at the line `if (scenarioSettingsService.fetchByProjectId(projectId).isEmpty()) {`, it gets the object from the database (fetchByProjectId is just a wrapper for the DAO's fetchByProjectId).
From there, it starts converting the data, and it gets stuck converting the following data type: `et_elev_row` (visible in my initial post)

A view of the debugger running:
![debugger-running-on-convert](https://user-images.githubusercontent.com/26815785/153017438-822a6c17-bca1-4961-a53c-0556e98cf48b.png)

![image](https://user-images.githubusercontent.com/26815785/153017874-63d942c4-d595-4a48-8c56-971fbcbce91f.png)

Seems like all the converter if cases fail, so it enters `// [#10229] Try public, single argument, applicable constructors first` (Convert.class:1187), after which it calls convert again, and the loop continues.

![image](https://user-images.githubusercontent.com/26815785/153024837-dc8341cf-c6fe-499a-b9c0-574247a3249d.png)

**Comment by lukaseder** [comment]
That's very helpful, thanks a lot for the updated info. I'll try to reproduce this tomorrow. One more thing, maybe, the stack trace hints at the problem happening with `jooq-3.14.11.jar`. I'd love to hear if this still reproduces in a more recent jOOQ version. Quite a few things have changed in the area of data type conversion...

**Comment by twinkelmann** [comment]
Hey,

As mentioned, we are using jOOQ 3.15.1, so if it is a bug that was in 3.14.11, in theory we should not be impacted.
I will still try to upgrade jOOQ, because it will make sure we don't spend time fixing a bug twice.

**Comment by twinkelmann** [comment]
I have upgraded to jOOQ 3.15.7 for real this time.
So far, the issue seems to have gone away.

I am building the app on our CI and will update you when it is done, to confirm whether or not it is actually resolved.

**Comment by lukaseder** [comment]
Thanks, @twinkelmann. That would be great news!

**Comment by twinkelmann** [comment]
@lukaseder I can confirm the problem disappeared by upgrading from jOOQ 3.14.11 to jOOQ 3.15.7.
Thank you for your quick responses and sorry for the trouble.
