### ISSUE TITLE
SQLDataType.XYZ.getArrayDataType().getTypeName() and getCastTypeName() should produce standard SQL XYZ ARRAY type

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13029]
The following program:

```java
System.out.println(INTEGER.getArrayDataType().getTypeName());
System.out.println(INTEGER.getArrayDataType().getTypeName(using(HSQLDB).configuration()));
```

Currently prints:

```
integer
int array
```

With a dialect attached, we can generate the correct dialect specific type name, but without a dialect, we're producing the wrong type name for arrays. It should be `integer array`.

See also: https://github.com/jOOQ/jOOQ/issues/12975

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.17.0. As this change alters behaviour which user assumptions may be based upon, I won't backport this fix.

**Comment by lukaseder** [comment]
`DataType::getCastTypeName` is also affected

**Comment by lukaseder** [comment]
Given that this issue causes a hard-to-workaround regression when mocking data (see https://github.com/jOOQ/jOOQ/issues/12975), I'll backport this fix to 3.16.5 (https://github.com/jOOQ/jOOQ/issues/12975) nonetheless

**Comment by lukaseder** [comment]
There are regressions in integration tests that seemed to have relied on the previous behaviour, including:

```java
array = new Integer[] { null, 1 };
result = create().select().from(table(array)).fetch();
```

Producing:

```
org.jooq.exception.DataAccessException: SQL [select "array_table"."COLUMN_VALUE" from table("COLUMN_VALUE" integer array = cast(? as int array)) "array_table" -- SQL rendered with a free trial version of jOOQ 3.17.0-SNAPSHOT]; Error while reading field: "array_table"."COLUMN_VALUE", at JDBC index: 1
	at org.jooq_3.17.0-SNAPSHOT.H2.debug(Unknown Source)
	at org.jooq_3.17.0-SNAPSHOT.H2.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3089)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:670)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1462)
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1423)
	at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:236)
	at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:177)
	at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:88)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:259)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:340)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:284)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2820)
	at org.jooq.test.all.testcases.RoutineAndUDTTests.testArrayTableEmulation(RoutineAndUDTTests.java:1483)
	at org.jooq.test.jOOQAbstractTest.testArrayTableEmulation(jOOQAbstractTest.java:7969)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.sql.SQLException: Error while reading field: "array_table"."COLUMN_VALUE", at JDBC index: 1
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1584)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1523)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1447)
	... 41 more
Caused by: org.h2.jdbc.JdbcSQLDataException: Datenumwandlungsfehler beim Umwandeln von "ARRAY to INTEGER"
Data conversion error converting "ARRAY to INTEGER" [22018-210]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:525)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at org.h2.message.DbException.get(DbException.java:227)
	at org.h2.message.DbException.get(DbException.java:203)
	at org.h2.value.Value.getDataConversionError(Value.java:2551)
	at org.h2.value.Value.convertToInt(Value.java:1606)
	at org.h2.value.Value.getInt(Value.java:858)
	at org.h2.jdbc.JdbcResultSet.getIntInternal(JdbcResultSet.java:348)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:319)
	at org.jooq.tools.jdbc.DefaultResultSet.getInt(DefaultResultSet.java:144)
	at org.jooq.tools.jdbc.DefaultResultSet.getInt(DefaultResultSet.java:144)
	at org.jooq.tools.jdbc.DefaultResultSet.getInt(DefaultResultSet.java:144)
	at org.jooq.impl.CursorImpl$CursorResultSet.getInt(CursorImpl.java:615)
	at org.jooq.impl.DefaultBinding$DefaultIntegerBinding.get0(DefaultBinding.java:2875)
	at org.jooq.impl.DefaultBinding$DefaultIntegerBinding.get0(DefaultBinding.java:1)
	at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:997)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1574)
	... 45 more

```

And 

```java
Integer[] values = { 1, 2, 3 };
Field<Integer> y = field(name("y"), int.class);
Field<Integer> columnValue = field(name("COLUMN_VALUE"), int.class);


Result<Record2<String, Integer>> r1 = create
    .select(
        val("a"),
        columnValue)
    .from(unnest(values).as("x"))
    .fetch();
```

Producing:

```
org.jooq.exception.DataAccessException: SQL [select 'a', "COLUMN_VALUE" from table("COLUMN_VALUE" integer array = array[1, 2, 3]) "x" -- SQL rendered with a free trial version of jOOQ 3.17.0-SNAPSHOT]; Error while reading field: "COLUMN_VALUE", at JDBC index: 2
	at org.jooq_3.17.0-SNAPSHOT.H2.debug(Unknown Source)
	at org.jooq_3.17.0-SNAPSHOT.H2.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3089)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:670)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1462)
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1423)
	at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:236)
	at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:177)
	at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:88)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:259)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:340)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:284)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2820)
	at org.jooq.test.all.testcases.TableFunctionTests.testUnnest0(TableFunctionTests.java:270)
	at org.jooq.test.all.testcases.TableFunctionTests.testUnnest(TableFunctionTests.java:256)
	at org.jooq.test.jOOQAbstractTest.testUnnest(jOOQAbstractTest.java:8005)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.sql.SQLException: Error while reading field: "COLUMN_VALUE", at JDBC index: 2
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1584)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1523)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1447)
	... 42 more
Caused by: org.h2.jdbc.JdbcSQLDataException: Datenumwandlungsfehler beim Umwandeln von "ARRAY to INTEGER"
Data conversion error converting "ARRAY to INTEGER" [22018-210]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:525)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at org.h2.message.DbException.get(DbException.java:227)
	at org.h2.message.DbException.get(DbException.java:203)
	at org.h2.value.Value.getDataConversionError(Value.java:2551)
	at org.h2.value.Value.convertToInt(Value.java:1606)
	at org.h2.value.Value.getInt(Value.java:858)
	at org.h2.jdbc.JdbcResultSet.getIntInternal(JdbcResultSet.java:348)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:319)
	at org.jooq.tools.jdbc.DefaultResultSet.getInt(DefaultResultSet.java:144)
	at org.jooq.tools.jdbc.DefaultResultSet.getInt(DefaultResultSet.java:144)
	at org.jooq.impl.CursorImpl$CursorResultSet.getInt(CursorImpl.java:615)
	at org.jooq.impl.DefaultBinding$DefaultIntegerBinding.get0(DefaultBinding.java:2875)
	at org.jooq.impl.DefaultBinding$DefaultIntegerBinding.get0(DefaultBinding.java:1)
	at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:997)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1574)
	... 46 more
```

Maybe the same regression with two manifestations

**Comment by lukaseder** [comment]
This invalidates a previous fix that was introduced in jOOQ 3.15: https://github.com/jOOQ/jOOQ/issues/11309

**Comment by lalithsuresh** [comment]
@lukaseder thank you so much for the quick response. I'll try to test these.

**Comment by lukaseder** [comment]
This test still fails:

```java
Configuration h2 = using(H2).configuration();
Configuration pg = using(POSTGRES).configuration();

Converter<Integer, String> is = Converter.ofNullable(Integer.class, String.class, Object::toString, Integer::valueOf);
Converter<String, Integer> si = is.inverse();

Converter<Integer[], String[]> isa = is.forArrays();
Converter<String[], Integer[]> sia = si.forArrays();

assertEquals("integer array", INTEGER.getArrayDataType().asConvertedDataType(isa).getTypeName());
assertEquals("integer array", INTEGER.asConvertedDataType(is).getArrayDataType().getTypeName());
assertEquals("int array", INTEGER.getArrayDataType().asConvertedDataType(isa).getTypeName(h2));
assertEquals("int array", INTEGER.asConvertedDataType(is).getArrayDataType().getTypeName(h2));
assertEquals("int[]", INTEGER.getArrayDataType().asConvertedDataType(isa).getTypeName(pg));
assertEquals("int[]", INTEGER.asConvertedDataType(is).getArrayDataType().getTypeName(pg));

assertEquals("integer array", INTEGER.getArrayDataType().asConvertedDataType(isa).getCastTypeName());
assertEquals("integer array", INTEGER.asConvertedDataType(is).getArrayDataType().getCastTypeName());
assertEquals("int array", INTEGER.getArrayDataType().asConvertedDataType(isa).getCastTypeName(h2));
assertEquals("int array", INTEGER.asConvertedDataType(is).getArrayDataType().getCastTypeName(h2));
assertEquals("int[]", INTEGER.getArrayDataType().asConvertedDataType(isa).getCastTypeName(pg));
assertEquals("int[]", INTEGER.asConvertedDataType(is).getArrayDataType().getCastTypeName(pg));
```

Will include the relevant fix also for this issue, and in the backports to 3.16.5 (https://github.com/jOOQ/jOOQ/issues/13030) and 3.15.9 (https://github.com/jOOQ/jOOQ/issues/13092)

**Comment by lukaseder** [comment]
The test from the previous comment works now in 3.17.0, 3.16.5, and 3.15.9

**Comment by lukaseder** [comment]
The fix here interacts with the `LegacyConvertedDataType` introduced with https://github.com/jOOQ/jOOQ/issues/9492 in jOOQ 3.14. Depending on the initialisation order of custom data types, it may happen that converted array types are registered statically before the built-in array types are made available.

As #9492 promised to maintain the old behaviour for a while in order not to break client code that relies on it, we need to fix this carefully.

**Comment by lukaseder** [comment]
The solution is #13107
