### ISSUE TITLE
Reinserting an unchanged record (with defaults) generates an exception

### ISSUE THREAD

**Issue by AnghelLeonard** [jOOQ/jOOQ#13112]
### Expected behavior
No exception, working `INSERT`

### Actual behavior
`"Field 'foo' doesn't have a default value"`

### Steps to reproduce the problem
Code:

```Java
SaleRecord sr = new SaleRecord();
sr.setFiscalYear(2021);
sr.setSale(4500.25);
sr.setEmployeeNumber(1504L);

sr.insert(); // works

// SQL: insert into `classicmodels`.`sale` values (default, default, default)
sr.insert(); // Field 'fiscal_year' doesn't have a default value
```

### Versions

- jOOQ:3.16.2
- Java:17
- Database (include vendor):MySQL
- OS: -
- JDBC Driver (include name if inofficial driver):-

**Comment by lukaseder** [comment]
Thanks for your report. Can you please share your `CREATE TABLE` for the `SALE` table, as well as the stack trace you're seeing?

**Comment by AnghelLeonard** [comment]
```sql
CREATE TABLE `sale` (
  `sale_id`         BIGINT   NOT NULL AUTO_INCREMENT
  `fiscal_year`     INT      NOT NULL,   -- there is no default value indeed (I forgot to mention this)
  ...
);
```

Stacktrace:
```Java
Caused by: org.springframework.dao.DataIntegrityViolationException: jOOQ; SQL [insert into `classicmodels`.`sale` values (default, default, default, default, default, default, default, default, default, default)]; Field 'fiscal_year' doesn't have a default value; nested exception is java.sql.SQLException: Field 'fiscal_year' doesn't have a default value
	at org.jooq_3.16.2.MYSQL.debug(Unknown Source) ~[na:na]
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:251) ~[spring-jdbc-5.3.13.jar:5.3.13]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70) ~[spring-jdbc-5.3.13.jar:5.3.13]
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.translate(JooqExceptionTranslator.java:94) ~[spring-boot-autoconfigure-2.5.7.jar:2.5.7]
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.handle(JooqExceptionTranslator.java:81) ~[spring-boot-autoconfigure-2.5.7.jar:2.5.7]
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.exception(JooqExceptionTranslator.java:55) ~[spring-boot-autoconfigure-2.5.7.jar:2.5.7]
	at org.jooq.impl.ExecuteListeners.exception(ExecuteListeners.java:276) ~[jooq-3.16.2.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:350) ~[jooq-3.16.2.jar:na]
	at org.jooq.impl.TableRecordImpl.storeInsert0(TableRecordImpl.java:191) ~[jooq-3.16.2.jar:na]
	at org.jooq.impl.TableRecordImpl.lambda$storeInsert$0(TableRecordImpl.java:157) ~[jooq-3.16.2.jar:na]
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143) ~[jooq-3.16.2.jar:na]
	at org.jooq.impl.TableRecordImpl.storeInsert(TableRecordImpl.java:156) ~[jooq-3.16.2.jar:na]
	at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:144) ~[jooq-3.16.2.jar:na]
	at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:139) ~[jooq-3.16.2.jar:na]
	at com.classicmodels.repository.ClassicModelsRepository.insertNewRecord(ClassicModelsRepository.java:162) ~[classes/:na]
	at com.classicmodels.repository.ClassicModelsRepository$$FastClassBySpringCGLIB$$328d95c1.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.13.jar:5.3.13]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783) ~[spring-aop-5.3.13.jar:5.3.13]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.13.jar:5.3.13]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.13.jar:5.3.13]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-5.3.13.jar:5.3.13]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.13.jar:5.3.13]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.13.jar:5.3.13]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.13.jar:5.3.13]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.13.jar:5.3.13]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.13.jar:5.3.13]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.13.jar:5.3.13]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.13.jar:5.3.13]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698) ~[spring-aop-5.3.13.jar:5.3.13]
	at com.classicmodels.repository.ClassicModelsRepository$$EnhancerBySpringCGLIB$$8daa0d2f.insertNewRecord(<generated>) ~[classes/:na]
	at com.classicmodels.service.ClassicModelsService.insertNewRecord(ClassicModelsService.java:17) ~[classes/:na]
	at com.classicmodels.MainApplication.lambda$init$0(MainApplication.java:27) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:793) ~[spring-boot-2.5.7.jar:2.5.7]
	... 5 common frames omitted
Caused by: java.sql.SQLException: Field 'fiscal_year' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1046) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1371) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1031) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-4.0.3.jar:na]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.executeUpdate(DefaultPreparedStatement.java:109) ~[jooq-3.16.2.jar:na]
	at org.jooq.impl.AbstractDMLQuery.executeReturningGeneratedKeysFetchAdditionalRows(AbstractDMLQuery.java:1207) ~[jooq-3.16.2.jar:na]
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:1041) ~[jooq-3.16.2.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:335) ~[jooq-3.16.2.jar:na]
	... 30 common frames omitted
```

**Comment by lukaseder** [comment]
Interesting, and you don't do anything in between your `insert()` calls? If the record isn't changed, then it should ignore the call... What `Settings` do you use? Did you specify `Settings.insertUnchangedRecords`?

**Comment by AnghelLeonard** [comment]
Nothing between the inserts, so default settings. But, if I do this then is ok:

```Java
        // Prevent unchanged records to be inserted.
        // By default, isInsertUnchangedRecords() returns true.        
        DSLContext derivedCtx = ctx.configuration().derive(new Settings()
                .withInsertUnchangedRecords(false)).dsl();
        derivedCtx.attach(sr); // or, sr.attach(derivedCtx.configuration());
        sr.insert();
```

**Comment by lukaseder** [comment]
> ```java
> // By default, isInsertUnchangedRecords() returns true.        
> ```

Ah yes, my bad. The default is `true`. See details here: https://github.com/jOOQ/jOOQ/issues/10386

So, I suspect things work as "expected"?

**Comment by lukaseder** [comment]
The default behaviour is based on a twitter poll, with quite clear results: https://twitter.com/lukaseder/status/1281600147575775232
