### ISSUE TITLE
ClobBinding shouldn't call Clob.length() in Firebird

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13144]
Jaybird hasn't implemented `FBClob.length()` (yet):

```java
	@Override
	public long length() throws SQLException {
		throw new FBDriverNotCapableException("Cannot determine length for CLOB");
	}
```

The relevant stack trace from the integration test is:

```
org.jooq.exception.DataAccessException: SQL [select "c", "b" from "t" order by "i" -- SQL rendered with a free trial version of jOOQ 3.17.0-SNAPSHOT]; Error while reading field: "c", at JDBC index: 1
	at org.jooq_3.17.0-SNAPSHOT.FIREBIRD.debug(Unknown Source)
	at org.jooq_3.17.0-SNAPSHOT.FIREBIRD.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3106)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:670)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1462)
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1423)
	at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:236)
	at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:177)
	at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:88)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:259)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:340)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:284)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2820)
	at org.jooq.test.all.testcases.DataTypeTests.testLargeLOBsWithClobBindingOrBlobBinding0(DataTypeTests.java:1999)
	at org.jooq.test.all.testcases.DataTypeTests.testLargeLOBsWithClobBindingOrBlobBinding(DataTypeTests.java:1973)
	at org.jooq.test.jOOQAbstractTest.testLargeLOBsWithClobBindingOrBlobBinding(jOOQAbstractTest.java:4065)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.sql.SQLException: Error while reading field: "c", at JDBC index: 1
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1588)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1523)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1447)
	... 42 more
Caused by: org.firebirdsql.jdbc.FBDriverNotCapableException: Cannot determine length for CLOB
	at org.firebirdsql.jdbc.FBClob.length(FBClob.java:53)
	at org.jooq.impl.ClobBinding.get(ClobBinding.java:104)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1578)
	... 46 more
```

Though it is implemented for `FBBlob.length()`. We should avoid calling it. Instead, we can use `Clob.getCharacterStream()` and consume the entire `Reader`

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.17.0, 3.16.5 (https://github.com/jOOQ/jOOQ/issues/13145), and 3.15.9 (https://github.com/jOOQ/jOOQ/issues/13146)
