### ISSUE TITLE
UDTRecord::equals and ::hashCode shouldn't depend on whether the record is attached

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13175]
After attempting a fix of https://github.com/jOOQ/jOOQ/issues/13174, another problem appeared in the new integration test:

```java
UStreetTypeRecord b1 = new UStreetTypeRecord("null", "null", null, null);
UStreetTypeRecord b2 = ctx.fetchValue(select(val(b1)));

assertEquals(b1, b2);
```

The test currently fails with:

```
java.lang.AssertionError: expected:<"public"."u_street_type"('null', 'null', null, null)> but was:<row(null, null, null, null)::"public"."u_street_type">
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.jooq.test.util.BaseTest.assertEquals(BaseTest.java:196)
	at org.jooq.test.PostgresTest.lambda$219(PostgresTest.java:4258)
	at org.jooq.test.jOOQAbstractTest.withDSLContext(jOOQAbstractTest.java:1962)
	at org.jooq.test.jOOQAbstractTest.bindAndInline(jOOQAbstractTest.java:1949)
	at org.jooq.test.PostgresTest.testPostgresUDTsWithNulls(PostgresTest.java:4249)
```

This appears to be the case because the expected UDT is not attached to any configuration (just created with `new`) whereas the actual UDT is attached.

The `null` vs `'null'` difference is another bug: https://github.com/jOOQ/jOOQ/issues/13169

**Comment by lukaseder** [comment]
Nevermind. That's just the `toString()` behaviour, which is different depending on whether the record is attached, which is fine. The actual `equals()` failure stems from `null` vs `'null'` itself: https://github.com/jOOQ/jOOQ/issues/13169
