### ISSUE TITLE
Select unnest on Postgres

### ISSUE THREAD

**Issue by juriad** [jOOQ/jOOQ#13176]
### Your question:

I am just trying to express this with jOOQ:
```
postgres=# select distinct unnest(a) from aaa;
 unnest 
--------
      2
      4
      3
      1
(4 rows)
```

To reproduce:
```
create table aaa(a int[]);
insert into aaa values (array[1]), (array[2,1]), (array[3,2,1]), (array[4,3,2,1]);
```

I have a solution that uses an SQL template. But seeing the new feature (https://github.com/jOOQ/jOOQ/issues/4727) in 3.17, I was wondering how it will work there.

```
        ctx.createTableIfNotExists("aaa").column("a", SQLDataType.INTEGER.getArrayDataType()).execute();
        ctx.insertInto(DSL.table("aaa"))
                .values((Object) new Integer[]{1})
                .values((Object) new Integer[]{2, 1})
                .values((Object) new Integer[]{3, 2, 1})
                .values((Object) new Integer[]{4, 3, 2, 1})
                .execute();

        Table<?> unnest = DSL.unnest(DSL.field("a", int[].class));

        Result<? extends Record1<?>> result = ctx
                .selectDistinct(DSL.field("unnest({0})", DSL.field("a"))) // works great
                //.selectDistinct(unnest) // fails
                .from(DSL.table("aaa"))
                .fetch();

        System.out.println(result);
```

When it fails the exception is:
```
org.jooq.exception.DataAccessException: SQL [select distinct "array_table" from aaa]; ERROR: column "array_table" does not exist
  Position: 17

	at org.jooq_3.17.0-SNAPSHOT.POSTGRES_13.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3106)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:670)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:355)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:290)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2821)
	at org.jooq.mcve.test.java.UnnestTest.test1(UnnestTest.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.postgresql.util.PSQLException: ERROR: column "array_table" does not exist
  Position: 17
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2552)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2284)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:153)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4338)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:236)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:341)
	... 32 more
```

Also, changing `DSL.unnest(DSL.field("a", int[].class))` to `DSL.unnest(DSL.field("a"))` fails with the SQLDialectNotSupportedException in `org.jooq.impl.DSL#unnest0`. 

### Versions:

- jOOQ: 3.16 and 3.17
- Java: 11
- Database (include vendor): Postgres
- OS: Linux
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks very much for your message. You'll probably find an answer here?
https://stackoverflow.com/q/67840701/521799

Let me know if that doesn't suffice as answer...

**Comment by juriad** [comment]
My use case is actually returning unique ids of ancestors (that is what the arrays hold), so no containment.

Using it in FROM (that is cross join lateral) works:
```
        Result<? extends Record1<?>> result = ctx
                .selectDistinct(DSL.field("id"))
                .from(DSL.table("aaa"))
                .crossApply(unnest.as("anc", "id"))
                .fetch();
```

Even this works:
```
        Result<? extends Record1<?>> result = ctx
                .selectDistinct(DSL.field("id"))
                .from(DSL.table("aaa"), unnest.as("anc", "id"))
                .fetch();
```

I duplicated the data to 1M rows in the table `aaa`. The two queries lead to different plans:
```
postgres=# analyze aaa;
ANALYZE
postgres=# select count(*) from aaa;
  count  
---------
 1048576
(1 row)

postgres=# explain analyze select distinct unnest(a) from aaa;
                                                        QUERY PLAN                                                         
---------------------------------------------------------------------------------------------------------------------------
 HashAggregate  (cost=105250.28..105250.78 rows=40 width=4) (actual time=601.986..601.987 rows=4 loops=1)
   Group Key: unnest(a)
   Batches: 1  Memory Usage: 24kB
   ->  ProjectSet  (cost=0.00..79035.88 rows=10485760 width=4) (actual time=0.041..384.763 rows=2621440 loops=1)
         ->  Seq Scan on aaa  (cost=0.00..18742.76 rows=1048576 width=31) (actual time=0.035..64.265 rows=1048576 loops=1)
 Planning Time: 0.259 ms
 Execution Time: 602.030 ms
(7 rows)

postgres=# explain analyze select distinct id from aaa cross join lateral unnest(a) as "anc" ("id");
                                                         QUERY PLAN                                                         
----------------------------------------------------------------------------------------------------------------------------
 HashAggregate  (cost=254672.36..254672.46 rows=10 width=4) (actual time=1141.268..1141.270 rows=4 loops=1)
   Group Key: anc.id
   Batches: 1  Memory Usage: 24kB
   ->  Nested Loop  (cost=0.00..228457.96 rows=10485760 width=4) (actual time=0.049..917.370 rows=2621440 loops=1)
         ->  Seq Scan on aaa  (cost=0.00..18742.76 rows=1048576 width=31) (actual time=0.033..57.949 rows=1048576 loops=1)
         ->  Function Scan on unnest anc  (cost=0.00..0.10 rows=10 width=4) (actual time=0.000..0.001 rows=2 loops=1048576)
 Planning Time: 0.160 ms
 Execution Time: 1141.315 ms
(8 rows)

postgres=# explain analyze select distinct id from aaa, unnest(a) as "anc" ("id");
                                                         QUERY PLAN                                                         
----------------------------------------------------------------------------------------------------------------------------
 HashAggregate  (cost=254672.36..254672.46 rows=10 width=4) (actual time=1106.286..1106.287 rows=4 loops=1)
   Group Key: anc.id
   Batches: 1  Memory Usage: 24kB
   ->  Nested Loop  (cost=0.00..228457.96 rows=10485760 width=4) (actual time=0.032..894.508 rows=2621440 loops=1)
         ->  Seq Scan on aaa  (cost=0.00..18742.76 rows=1048576 width=31) (actual time=0.020..56.420 rows=1048576 loops=1)
         ->  Function Scan on unnest anc  (cost=0.00..0.10 rows=10 width=4) (actual time=0.000..0.001 rows=2 loops=1048576)
 Planning Time: 0.076 ms
 Execution Time: 1106.348 ms
(8 rows)
```

The difference is time pretty striking. My question was mostly targeted to version 3.17, where `Table` is `SelectField` and unnest produces a `Table`, yet the combination does not work "as expected". I have my solution (it is also documented here), no need to solve anything from your side. :smile:

**Comment by lukaseder** [comment]
> The difference is time pretty striking

It's always very bad news when the weird feature is faster than the normal one 😔

> My question was mostly targeted to version 3.17, where `Table` is `SelectField` and unnest produces a `Table`, yet the combination does not work "as expected".

Yeah, I'm aware that starting with jOOQ 3.17, it will be possible to use this feature, even if in a slightly unexpected way

I keep forgetting this very weird PostgreSQL feature, where projections are allowed to produce sets, which are magically unnested - not by cross joining, but by joining on ordinality: https://twitter.com/lukaseder/status/1491785022163996676

**Comment by lukaseder** [comment]
I've created a feature request to formally support these syntaxes. `UNNEST` might be the most popular one because it's ubiquitous in blog posts etc, but in fact, any table valued function can be used in `SELECT` as well, e.g. `SELECT generate_series(1, 10)`: https://github.com/jOOQ/jOOQ/issues/13187
