### ISSUE TITLE
Batching Records via MERGE in Oracle(18c) result in exception

### ISSUE THREAD

**Issue by AnghelLeonard** [jOOQ/jOOQ#13170]
### Expected behavior
No exception

### Actual behavior
```Java
Caused by: java.lang.NullPointerException: Cannot invoke "org.jooq.QueryPartInternal.rendersContent(org.jooq.Context)" because "e" is null
	at org.jooq_3.16.4.ORACLE.debug(Unknown Source) ~[na:na]
	at org.jooq.impl.QueryPartCollectionView.accept(QueryPartCollectionView.java:155) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:720) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:295) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.AbstractRow.accept(AbstractRow.java:217) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:720) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:295) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.RowCondition.accept(RowCondition.java:229) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:720) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:295) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.Expression.acceptAssociative(Expression.java:906) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.Expression.acceptAssociative(Expression.java:880) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.Or.accept(Or.java:113) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:720) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:295) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.ConditionProviderImpl.accept(ConditionProviderImpl.java:139) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:720) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:295) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.MergeImpl.toSQLStandard(MergeImpl.java:1564) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.MergeImpl.accept(MergeImpl.java:1350) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:720) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:295) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.InsertQueryImpl.accept0(InsertQueryImpl.java:420) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.AbstractDMLQuery.accept(AbstractDMLQuery.java:642) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:720) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:295) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.AbstractQuery.getSQL0(AbstractQuery.java:474) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:287) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.UpdatableRecordImpl.storeMergeOrUpdate0(UpdatableRecordImpl.java:351) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.UpdatableRecordImpl.storeMerge0(UpdatableRecordImpl.java:268) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.UpdatableRecordImpl.lambda$storeMerge$2(UpdatableRecordImpl.java:248) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.UpdatableRecordImpl.storeMerge(UpdatableRecordImpl.java:247) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.UpdatableRecordImpl.merge(UpdatableRecordImpl.java:183) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.UpdatableRecordImpl.merge(UpdatableRecordImpl.java:178) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.BatchCRUD.executeAction(BatchCRUD.java:191) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.BatchCRUD.executePrepared(BatchCRUD.java:109) ~[jooq-3.16.4.jar:na]
	at org.jooq.impl.BatchCRUD.execute(BatchCRUD.java:88) ~[jooq-3.16.4.jar:na]
```

### Steps to reproduce the problem
```Java
SaleRecord sr = new SaleRecord();
        sr.setFiscalYear(2005);
        sr.setSale(1223.23);
        sr.setEmployeeNumber(1370L);
        sr.setFiscalMonth(1);
        sr.setRevenueGrowth(0.0);
        sr.setTrend("UP"); 

int[] result = ctx.batchMerge(sr)
                .execute();
```

**Note that if I add an explicit id `sr.setSaleId(1L);` then it works. `INSERT` (`batchInsert()`) works in both cases.**

The `SALE` DDL:

```sql
CREATE SEQUENCE sale_seq START WITH 1000000 INCREMENT BY 1;

CREATE TABLE sale (
  sale_id         NUMBER(10)   DEFAULT sale_seq.nextval NOT NULL, 
  fiscal_year     NUMBER(5)    NOT NULL, 
  sale            FLOAT        NOT NULL,    
  employee_number NUMBER(10)   DEFAULT NULL,  
  hot             CHAR(1)      DEFAULT '1' CHECK (hot IN('1', '0')), -- or, 'Y'/'N'
  rate            VARCHAR2(10) DEFAULT NULL CHECK (rate IN('SILVER', 'GOLD', 'PLATINUM')),
  vat             VARCHAR2(10) DEFAULT NULL CHECK (vat IN('NONE', 'MIN', 'MAX')),
  fiscal_month    NUMBER(5)    NOT NULL,
  revenue_growth  FLOAT        NOT NULL,
  trend           VARCHAR2(10) DEFAULT NULL,  
  CONSTRAINT sale_pk PRIMARY KEY (sale_id),  
  CONSTRAINT sale_employee_fk FOREIGN KEY (employee_number) REFERENCES employee (employee_number)
);
```
Also tried for id, `GENERATED BY DEFAULT ON NULL AS IDENTITY`. But, the same exception.

### Versions

- jOOQ:3.16.4
- Java:17
- Database (include vendor):Oracle 18c
- OS:Windows
- JDBC Driver (include name if inofficial driver):ojdbc8

**Comment by lukaseder** [comment]
Thanks a lot for your detailed report. I'll look into this soon.

**Comment by lukaseder** [comment]
Looking into this now. I can reproduce the problem with Oracle, not with H2, for example. Will attempt to fix this right away.

**Comment by lukaseder** [comment]
The issue isn't related to `batchMerge` (the batching part), or even to `UpdatableRecord::merge` but can also be reproduced with this table:

```sql
CREATE TABLE t_13170 (
  cd INTEGER,
  id INTEGER DEFAULT 1,
  
  CONSTRAINT t_13170_pk PRIMARY KEY (id)
);
```

And then this query:

```java
ctx.insertInto(T_13170).columns(T_13170.CD).values(3).onDuplicateKeyIgnore().execute();
```

The `INSERT .. ON DUPLICATE / ON CONFLICT` emulation using `MERGE` doesn't work when the primary key value isn't set.

There are several measures to be taken here:

1. The idea of merging a record that clearly hasn't been inserted yet is kind of an edge case. Using an actual insert seems better, so perhaps this isn't such a high prio bug after all.
2. The existing error is not very helpful in debugging what's going wrong. At least, we should have some detection that a `MERGE` can't be formed
3. A fix seems to be to simply ignore the `ON DUPLICATE / ON CONFLICT` clause and run a simple `INSERT`. This isn't entirely correct, depending on the `DEFAULT` expression, though. E.g. in my example (`DEFAULT 1`), it would be wrong. But the `MERGE` statement's `USING` clause can't access the `DEFAULT` expression, so I'm not quite sure how else this could be solved.

Probably, 3) with the known caveat seems to be the most reasonable solution here?

**Comment by lukaseder** [comment]
Only Oracle is affected because of the workaround for #8158

**Comment by lukaseder** [comment]
`RowN::compare` isn't affected, only `Row[N]::compare`

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.17.0, 3.16.5 (https://github.com/jOOQ/jOOQ/issues/13242), and 3.15.9 (https://github.com/jOOQ/jOOQ/issues/13243).

Thanks again for your report!
