### ISSUE TITLE
Db2 RowAsField emulation using JSON_OBJECT is lacking RETURNING BLOB when using the JSONB emulation

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13196]
Various recent improvements around nesting records via `RowAsField` (https://github.com/jOOQ/jOOQ/issues/12930), as well as the nested record convenience introduced with (#13069) have shown that the Db2 `RowAsField` emulation using JSON_OBJECT is lacking a `RETURNING BLOB` clause when using the JSONB emulation (this fails with an exception).

No `RETURNING CLOB` clause is required for `JSON` emulations, as in Oracle.

An example exception stacktrace is:

```
org.jooq.exception.DataAccessException: SQL [select T_BOOK.ID, (select json_object(key cast(? as varchar(32672)) value T_LANGUAGE.CD, key cast(? as varchar(32672)) value T_LANGUAGE.DESCRIPTION, key cast(? as varchar(32672)) value T_LANGUAGE.DESCRIPTION_ENGLISH, key cast(? as varchar(32672)) value T_LANGUAGE.ID) T_LANGUAGE from T_LANGUAGE where T_BOOK.LANGUAGE_ID = T_LANGUAGE.ID) from T_BOOK order by T_BOOK.ID -- SQL rendered with a free trial version of jOOQ 3.17.0-SNAPSHOT]; Error while reading field: (
  select "T_LANGUAGE"
  from "PUBLIC"."T_LANGUAGE"
  where "PUBLIC"."T_BOOK"."LANGUAGE_ID" = "PUBLIC"."T_LANGUAGE"."ID"
), at JDBC index: 2
	at org.jooq_3.17.0-SNAPSHOT.DB2.debug(Unknown Source)
	at org.jooq_3.17.0-SNAPSHOT.DB2.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3106)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:670)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1462)
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1423)
	at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:236)
	at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:177)
	at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:88)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:265)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:341)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:290)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2821)
	at org.jooq.test.all.testcases.ImplicitJoinTests.lambda$8(ImplicitJoinTests.java:637)
	at org.jooq.test.all.testcases.ImplicitJoinTests.lambda$7(ImplicitJoinTests.java:628)
	at org.jooq.test.all.testcases.MultisetTests.lambda$389(MultisetTests.java:2504)
	at org.jooq.test.all.testcases.MultisetTests.testRecordLevelListenerResults(MultisetTests.java:2532)
	at org.jooq.test.all.testcases.MultisetTests.testRecordLevelListenerResults(MultisetTests.java:2520)
	at org.jooq.test.all.testcases.MultisetTests.testMultisetEmulations(MultisetTests.java:2504)
	at org.jooq.test.all.testcases.ImplicitJoinTests.testMultisetEmulations(ImplicitJoinTests.java:628)
	at org.jooq.test.all.testcases.ImplicitJoinTests.testRowConvenienceToOneFetchAll(ImplicitJoinTests.java:632)
	at org.jooq.test.jOOQAbstractTest.testRowConvenienceToOneFetchAll(jOOQAbstractTest.java:10064)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.sql.SQLException: Error while reading field: (
  select "T_LANGUAGE"
  from "PUBLIC"."T_LANGUAGE"
  where "PUBLIC"."T_BOOK"."LANGUAGE_ID" = "PUBLIC"."T_LANGUAGE"."ID"
), at JDBC index: 2
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1588)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1523)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1447)
	... 49 more
Caused by: com.ibm.db2.jcc.am.SqlSyntaxErrorException: [jcc][t4][1092][11638][4.29.24] Invalid data conversion: Wrong result column type for requested conversion. ERRORCODE=-4461, SQLSTATE=42815
	at com.ibm.db2.jcc.am.b7.a(b7.java:810)
	at com.ibm.db2.jcc.am.b7.a(b7.java:66)
	at com.ibm.db2.jcc.am.b7.a(b7.java:133)
	at com.ibm.db2.jcc.am.bi.Q(bi.java:1939)
	at com.ibm.db2.jcc.am.ResultSet.getBytes(ResultSet.java:1270)
	at org.jooq.tools.jdbc.DefaultResultSet.getBytes(DefaultResultSet.java:170)
	at org.jooq.tools.jdbc.DefaultResultSet.getBytes(DefaultResultSet.java:170)
	at org.jooq.tools.jdbc.DefaultResultSet.getBytes(DefaultResultSet.java:170)
	at org.jooq.impl.CursorImpl$CursorResultSet.getBytes(CursorImpl.java:545)
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.readMultiset(DefaultBinding.java:4037)
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.readMultiset(DefaultBinding.java:3794)
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.get0(DefaultBinding.java:3770)
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.get0(DefaultBinding.java:1)
	at org.jooq.impl.DefaultBinding$InternalBinding.get(DefaultBinding.java:1017)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1578)
	... 53 more
```

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.17.0, 3.16.5 (https://github.com/jOOQ/jOOQ/issues/13197), and 3.15.9 (https://github.com/jOOQ/jOOQ/issues/13198)
