### ISSUE TITLE
ORA-00918: Column ambiguously defined when using DSLContext::fetchCount with LIMIT in Oracle

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13233]
This query:

```java
assertEquals(2, create().fetchCount(
    select()
    .from(TBook())
    .join(TAuthor())
    .on(TBook_AUTHOR_ID().eq(TAuthor_ID()))
    .orderBy(TBook_ID())
    .limit(2)));
```

Fails in Oracle with this error:

```
org.jooq.exception.DataAccessException: SQL [select count(*) "c" from ((select null "v0", null "v1", null "v2", null "v3", null "v4", null "v5", null "v6", null "v7", null "v8", null "v9", null "v10", null "v11", null "v12", null "v13", null "v14", null "v15", null "v16", null "v17" from DUAL where 1 = 0) union all (select "TEST"."T_BOOK"."ID", "TEST"."T_BOOK"."AUTHOR_ID", "TEST"."T_BOOK"."CO_AUTHOR_ID", "TEST"."T_BOOK"."DETAILS_ID", "TEST"."T_BOOK"."TITLE", "TEST"."T_BOOK"."PUBLISHED_IN", "TEST"."T_BOOK"."LANGUAGE_ID", "TEST"."T_BOOK"."CONTENT_TEXT", "TEST"."T_BOOK"."CONTENT_PDF", "TEST"."T_BOOK"."STATUS", "TEST"."T_BOOK"."REC_VERSION", "TEST"."T_BOOK"."REC_TIMESTAMP", "TEST"."T_AUTHOR"."ID", "TEST"."T_AUTHOR"."FIRST_NAME", "TEST"."T_AUTHOR"."LAST_NAME", "TEST"."T_AUTHOR"."DATE_OF_BIRTH", "TEST"."T_AUTHOR"."YEAR_OF_BIRTH", "TEST"."T_AUTHOR"."ADDRESS" from "TEST"."T_BOOK" join "TEST"."T_AUTHOR" on "TEST"."T_BOOK"."AUTHOR_ID" = "TEST"."T_AUTHOR"."ID" order by "TEST"."T_BOOK"."ID" fetch next ? rows only)) "t"]; ORA-00918: Spalte nicht eindeutig definiert

	at org.jooq_3.17.0-SNAPSHOT.ORACLE21C.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3109)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:670)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:355)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:301)
	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:322)
	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:509)
	at org.jooq.impl.DefaultDSLContext.fetchCount(DefaultDSLContext.java:4707)
	at org.jooq.test.all.testcases.AggregateWindowFunctionTests.testFetchCountWithAmbiguousColumnNames(AggregateWindowFunctionTests.java:781)
	at org.jooq.test.jOOQAbstractTest.testFetchCountWithAmbiguousColumnNames(jOOQAbstractTest.java:7101)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00918: Spalte nicht eindeutig definiert

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:630)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:564)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1231)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:772)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:299)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:512)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:163)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:1010)
	at oracle.jdbc.driver.OracleStatement.prepareDefineBufferAndExecute(OracleStatement.java:1271)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1149)
	at oracle.jdbc.driver.OracleStatement.executeSQLSelect(OracleStatement.java:1661)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1470)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3761)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:4136)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1014)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4275)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:236)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:341)
	... 38 more
Caused by: Error : 918, Position : 0, Sql = select count(*) "c" from ((select null "v0", null "v1", null "v2", null "v3", null "v4", null "v5", null "v6", null "v7", null "v8", null "v9", null "v10", null "v11", null "v12", null "v13", null "v14", null "v15", null "v16", null "v17" from DUAL where 1 = 0) union all (select "TEST"."T_BOOK"."ID", "TEST"."T_BOOK"."AUTHOR_ID", "TEST"."T_BOOK"."CO_AUTHOR_ID", "TEST"."T_BOOK"."DETAILS_ID", "TEST"."T_BOOK"."TITLE", "TEST"."T_BOOK"."PUBLISHED_IN", "TEST"."T_BOOK"."LANGUAGE_ID", "TEST"."T_BOOK"."CONTENT_TEXT", "TEST"."T_BOOK"."CONTENT_PDF", "TEST"."T_BOOK"."STATUS", "TEST"."T_BOOK"."REC_VERSION", "TEST"."T_BOOK"."REC_TIMESTAMP", "TEST"."T_AUTHOR"."ID", "TEST"."T_AUTHOR"."FIRST_NAME", "TEST"."T_AUTHOR"."LAST_NAME", "TEST"."T_AUTHOR"."DATE_OF_BIRTH", "TEST"."T_AUTHOR"."YEAR_OF_BIRTH", "TEST"."T_AUTHOR"."ADDRESS" from "TEST"."T_BOOK" join "TEST"."T_AUTHOR" on "TEST"."T_BOOK"."AUTHOR_ID" = "TEST"."T_AUTHOR"."ID" order by "TEST"."T_BOOK"."ID" fetch next :1  rows only)) "t", OriginalSql = select count(*) "c" from ((select null "v0", null "v1", null "v2", null "v3", null "v4", null "v5", null "v6", null "v7", null "v8", null "v9", null "v10", null "v11", null "v12", null "v13", null "v14", null "v15", null "v16", null "v17" from DUAL where 1 = 0) union all (select "TEST"."T_BOOK"."ID", "TEST"."T_BOOK"."AUTHOR_ID", "TEST"."T_BOOK"."CO_AUTHOR_ID", "TEST"."T_BOOK"."DETAILS_ID", "TEST"."T_BOOK"."TITLE", "TEST"."T_BOOK"."PUBLISHED_IN", "TEST"."T_BOOK"."LANGUAGE_ID", "TEST"."T_BOOK"."CONTENT_TEXT", "TEST"."T_BOOK"."CONTENT_PDF", "TEST"."T_BOOK"."STATUS", "TEST"."T_BOOK"."REC_VERSION", "TEST"."T_BOOK"."REC_TIMESTAMP", "TEST"."T_AUTHOR"."ID", "TEST"."T_AUTHOR"."FIRST_NAME", "TEST"."T_AUTHOR"."LAST_NAME", "TEST"."T_AUTHOR"."DATE_OF_BIRTH", "TEST"."T_AUTHOR"."YEAR_OF_BIRTH", "TEST"."T_AUTHOR"."ADDRESS" from "TEST"."T_BOOK" join "TEST"."T_AUTHOR" on "TEST"."T_BOOK"."AUTHOR_ID" = "TEST"."T_AUTHOR"."ID" order by "TEST"."T_BOOK"."ID" fetch next ? rows only)) "t", Error Msg = ORA-00918: Spalte nicht eindeutig definiert

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:637)
	... 57 more
```

The problem can be simplified as this:

```sql
select 1 x, 2 y
from dual
where 1 = 0
union all (
  select 1 a, 2 a
  from dual
  fetch first row only
);
```

This raises the same ORA-00918 error, and in my opinion, is a bug in Oracle's `FETCH FIRST` implementation

**Comment by lukaseder** [comment]
Even worse, while trying to find a workaround for this bug, this query here seems to crash the connection (the server seems to be able to recover, though):

```sql
select 1 x, 2 y
from dual
where 1 = 0
union all (
  select 1 a, 2 a
  from dual
  union all
  select null a, null b
  from dual
  fetch first row only
);
```

**Comment by lukaseder** [comment]
Might be the same issue as https://github.com/jOOQ/jOOQ/issues/11473

**Comment by lukaseder** [comment]
It appears that this will be fixed in Oracle in the near future, so I'm not sure if this is something that jOOQ needs to work around.

**Comment by lukaseder** [comment]
This no longer fails once we support `QUALIFY`:

- https://github.com/jOOQ/jOOQ/issues/19684
