### ISSUE TITLE
Error when nesting ROW() expressions with values instead of with fields, with degree > 22

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13251]
This bug is similar as https://github.com/jOOQ/jOOQ/issues/13250, but the difference is that we've removed type safety:

```java
@Test
public void testNestedRowsWithValuesForRowN() {
    RowN r1 = row(asList(1));
    RowN r2 = row(asList(1, row(asList(2))));
    RowN r3 = row(asList(1, row(asList(2, row(asList(3))))));

    assertEquals("(1)", r1.toString());
    assertEquals("""
        (
          1,
          row (2)
        )
        """.trim(), r2.toString());
    assertEquals("""
        (
          1,
          row (
            2,
            row (3)
          )
        )
        """.trim(), r3.toString());
}
```

Unlike in https://github.com/jOOQ/jOOQ/issues/13250, where we get the wrong type `Row2<Integer, Row1<Integer>>` instead of `Row2<Integer, Record1<Integer>>`, here the resulting type doesn't have any type information attached to it, so there's no reason for this not to work.

If this is fixed, parts of #13250 will be fixed as well (the exception), but the type is still unexpected, which is why this here is a separate issue from #13250

**Comment by lukaseder** [comment]
The exception is a bit different now:

```
java.lang.IllegalArgumentException: Cannot interpret argument of type class org.jooq.impl.RowImpl1 as a Field: ("PUBLIC"."T_BOOK_STORE"."NAME")
	at org.jooq.impl.Tools.fieldExpected(Tools.java:1549)
	at org.jooq.impl.Tools.field(Tools.java:1618)
	at org.jooq.impl.Tools.lambda$54(Tools.java:1838)
	at org.jooq.impl.Tools.map(Tools.java:2034)
	at org.jooq.impl.Tools.fieldsArray(Tools.java:1838)
	at org.jooq.impl.DSL.row(DSL.java:30300)
	at org.jooq.impl.DSL.row(DSL.java:30616)
	at org.jooq.impl.TableImpl.projectRow(TableImpl.java:395)
	at org.jooq.impl.TableImpl.toOneRow(TableImpl.java:303)
	at org.jooq.test.h2.generatedclasses.public_.tables.TBookToBookStore.tBookStoreRow(TBookToBookStore.java:155)
	at org.jooq.test.all.testcases.ImplicitJoinTests.lambda$34(ImplicitJoinTests.java:722)
	at org.jooq.test.all.testcases.ImplicitJoinTests.lambda$7(ImplicitJoinTests.java:633)
	at org.jooq.test.all.testcases.MultisetTests.lambda$381(MultisetTests.java:2499)
	at org.jooq.test.all.testcases.MultisetTests.testRecordLevelListenerResults(MultisetTests.java:2532)
	at org.jooq.test.all.testcases.MultisetTests.testRecordLevelListenerResults(MultisetTests.java:2520)
	at org.jooq.test.all.testcases.MultisetTests.testMultisetEmulations(MultisetTests.java:2499)
	at org.jooq.test.all.testcases.ImplicitJoinTests.testMultisetEmulations(ImplicitJoinTests.java:633)
	at org.jooq.test.all.testcases.ImplicitJoinTests.testRowConvenienceToOneFetchMappedNestedWithNestedRows(ImplicitJoinTests.java:714)
	at org.jooq.test.jOOQAbstractTest.testRowConvenienceToOneFetchMappedNestedWithNestedRows(jOOQAbstractTest.java:10103)
```

**Comment by lukaseder** [comment]
The problem is a bit of an edge case. It appeared due to more internal `ROW` usage in a new test for multiset and row convenience (see #13069) when transforming a `Select` using its `Select::$select` accessor.

As such, I won't backport the fix for now. Fixed in jOOQ 3.17.0

**Comment by lukaseder** [comment]
Another use-case where this fix here could be useful: https://github.com/jOOQ/jOOQ/issues/11114

**Comment by lukaseder** [comment]
Backported to 3.16.6 (https://github.com/jOOQ/jOOQ/issues/13372), and 3.15.10 (https://github.com/jOOQ/jOOQ/issues/13373)
