### ISSUE TITLE
Cannot insert data into PostgreSQL XML column due to missing cast

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13252]
Our SQL/XML support is mostly geared around supporting the functions required to run `MULTISET` emulations. There are currently no tests to cover ordinary XML data type usage. E.g. there hasn't been a test trying to `INSERT` into an `XML` column or to run DDL with the `XML` type (see https://github.com/jOOQ/jOOQ/issues/11331).

In PostgreSQL, it's currently not possible to insert data to an `XML` column. The following error is raised:

```
org.jooq.exception.DataAccessException: SQL [insert into "t" ("i", "a") values (?, ?)]; ERROR: column "a" is of type xml but expression is of type character varying
  Hinweis: You will need to rewrite or cast the expression.
  Position: 40
	at org.jooq_3.17.0-SNAPSHOT.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3078)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:670)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:355)
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:116)
	at org.jooq.test.all.testcases.DDLTests.lambda$392(DDLTests.java:4453)
	at org.jooq.test.jOOQAbstractTest.withDSLContext(jOOQAbstractTest.java:1982)
	at org.jooq.test.jOOQAbstractTest.bindAndInline(jOOQAbstractTest.java:1969)
	at org.jooq.test.BaseTest.bindAndInline(BaseTest.java:1686)
	at org.jooq.test.all.testcases.DDLTests.testCreateTableWithXMLTypes(DDLTests.java:4452)
	at org.jooq.test.jOOQAbstractTest.testCreateTableWithXMLTypes(jOOQAbstractTest.java:3509)
```

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.17.0, 3.16.6 (https://github.com/jOOQ/jOOQ/issues/13253), and 3.15.10 (https://github.com/jOOQ/jOOQ/issues/13254)
