### ISSUE TITLE
Error when nesting ROW() expressions with values instead of with fields

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13250]
This test fails:

```java
@Test
public void testNestedRowsWithValues() {
    Row1<Integer> r1 = row(1);
    Row2<Integer, Row1<Integer>> r2 = row(1, row(2));
    Row2<Integer, Row2<Integer, Row1<Integer>>> r3 = row(1, row(2, row(3)));

    assertEquals("(1)", r1.toString());
    assertEquals("""
        (
          1,
          row (2)
        )
        """.trim(), r2.toString());
    assertEquals("""
        (
          1,
          row (
            2,
            row (3)
          )
        )
        """.trim(), r3.toString());
}
```

With the following exception:

```
java.lang.IllegalArgumentException: Cannot interpret argument of type class org.jooq.impl.RowImpl1 as a Field: (2)
	at org.jooq.impl.Tools.fieldExpected(Tools.java:1549)
	at org.jooq.impl.Tools.field(Tools.java:1618)
	at org.jooq.impl.DSL.row(DSL.java:30025)
	at org.jooq.test.RowsTest.testNestedRows(RowsTest.java:92)
```

The problem is one of API misuse. Users shouldn't combine `T` types with `SelectField<T>` types in `row()` constructors. The correct way to nest `ROW` expressions is this, which works:

```java
@Test
public void testNestedRowsWithFields() {
    Row1<Integer> r1 = row(val(1));
    Row2<Integer, Record1<Integer>> r2 = row(val(1), row(val(2)));
    Row2<Integer, Record2<Integer, Record1<Integer>>> r3 = row(val(1), row(val(2), row(val(3))));

    assertEquals("(1)", r1.toString());
    assertEquals("""
        (
          1,
          row (2)
        )
        """.trim(), r2.toString());
    assertEquals("""
        (
          1,
          row (
            2,
            row (3)
          )
        )
        """.trim(), r3.toString());
}
```

**Comment by lukaseder** [comment]
I'm not sure how this could be fixed. It's really a problem of API mis-use. In cases where users call functions passing `Field<T>` instead of `T` types (e.g. to `coalesce()`), we just quietly ignore the wrong data types and do the "expected" thing. But with such nested row expressions, users probably expect to use these for projections, and it's not possible to project a type like `Row2<Integer, Row1<Integer>>`. It's only possible to project `Row2<Integer, Record1<Integer>>`.

Perhaps a better exception message could be the solution here? Let's wait until some user runs into this, to collect feedback and expectations.

**Comment by lukaseder** [comment]
Related issue for `RowN` types: https://github.com/jOOQ/jOOQ/issues/13251

**Comment by lukaseder** [comment]
#13251 fixes the exception observed in the above test as well, though at runtime, the projection doesn't work correctly, now leading to a `ClassCastException`:

```java
Record2<Integer, Row2<Integer, Row1<Integer>>> v = ctx.fetchValue(row(1, row(2, row(3))));
System.out.println(v.value1());
System.out.println(v.value2().field1());
System.out.println(v.value2().field2());
```

Raises:

```
1
Exception in thread "main" java.lang.ClassCastException: class org.jooq.impl.RecordImpl2 cannot be cast to class org.jooq.Row2 (org.jooq.impl.RecordImpl2 and org.jooq.Row2 are in unnamed module of loader 'app')
	at org.jooq.testscripts.JDBC.main(JDBC.java:40)
```
