### ISSUE TITLE
Class loading deadlock between Limit and AbstractField

### ISSUE THREAD

**Issue by privateJiangyaokai** [jOOQ/jOOQ#13323]
### Expected behavior
org.jooq.impl.Limit and subclasses of org.jooq.impl.AbstractField can be simultaneously loaded by the class loader. 
### Actual behavior
Deadlock occurs, where both threads get stuck. Sample stacktrace:

```
"http-nio-8080-exec-2" #89 daemon prio=5 os_prio=0 cpu=986.30ms elapsed=58679.17s tid=0x00007fa5a27bc800 nid=0x5b in Object.wait()  [0x00007fa47bef6000]
   java.lang.Thread.State: RUNNABLE
        at org.jooq.impl.DSL.val(DSL.java:24409)
        at org.jooq.impl.DSL.inline(DSL.java:23926)
        at org.jooq.impl.DSL.inline(DSL.java:23191)
        at org.jooq.impl.DSL.zero(DSL.java:26155)
        at org.jooq.impl.Limit.<clinit>(Limit.java:84)
        at org.jooq.impl.SelectQueryImpl.<init>(SelectQueryImpl.java:379)
        at org.jooq.impl.SelectQueryImpl.<init>(SelectQueryImpl.java:356)
        at org.jooq.impl.SelectImpl.<init>(SelectImpl.java:278)
        at org.jooq.impl.SelectImpl.<init>(SelectImpl.java:274)
        at org.jooq.impl.DefaultDSLContext.select(DefaultDSLContext.java:2159)

"http-nio-8080-exec-1" #88 daemon prio=5 os_prio=0 cpu=5686.35ms elapsed=58679.17s tid=0x00007fa5a2bb8800 nid=0x5a in Object.wait()  [0x00007fa47bff8000]
   java.lang.Thread.State: RUNNABLE
        at org.jooq.impl.DSL.val(DSL.java:24409)
        at org.jooq.impl.DSL.val(DSL.java:23959)
        at org.jooq.impl.DSL.inline(DSL.java:23035)
        at org.jooq.impl.Tools.inline(Tools.java:1981)
        at org.jooq.impl.AbstractField.<clinit>(AbstractField.java:117)
        at org.jooq.impl.DSL.field(DSL.java:12796)
        at org.jooq.impl.DSL.field(DSL.java:12860)
        at org.jooq.impl.DSL.field(DSL.java:12765)
        at org.jooq.impl.DSL.field(DSL.java:12670)
        at org.jooq.impl.DSL.field(DSL.java:12638)
```

### Steps to reproduce the problem
minimum code to reproduce:

```java
public class K {
  public static void main(String... args) {
    Thread[] threads = {
        new Thread(() -> {
          try {
            Class.forName("org.jooq.impl.Limit");
          } catch (ClassNotFoundException e1) {
            e1.printStackTrace();
          }
        }),
        new Thread(() -> {
          try {
            Class.forName("org.jooq.impl.AbstractField");
          } catch (ClassNotFoundException e) {
            e.printStackTrace();
          }
        })
    };
    threads[0].start();
    threads[1].start();
  }
}
```

### Versions

- jOOQ:3.14.3
- Java:11
- Database (include vendor):N/A
- OS:N/A
- JDBC Driver (include name if inofficial driver):N/A

**Comment by lukaseder** [comment]
Thanks for your report. This should have already been addressed, see https://github.com/jOOQ/jOOQ/issues/11200, which was backported to 3.14.5. Please upgrade.
