### ISSUE TITLE
ORA-00933 when attempting to run INSERT .. SELECT via ojdbc's Connection.prepareStatement(String, String[]) for stored client side computed columns

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13476]
The default in Oracle when attempting to fetch generated keys is to run the JDBC `Connection.prepareStatement(String, String[])`. However, if the jOOQ generated query is an `INSERT .. SELECT` query, this doesn't work. E.g. for this query:

```sql
insert into T_AUDIT (ID, VAL, CREATED_AT, CREATED_BY, CREATED_OR_MODIFIED_AT, CREATED_OR_MODIFIED_BY) 
select ID, VAL, ?, ?, ?, ?
from (select ? ID, ? VAL from DUAL) t
```

I'm getting the following exception:

```
org.jooq.exception.DataAccessException: SQL [insert into T_AUDIT (ID, VAL, CREATED_AT, CREATED_BY, CREATED_OR_MODIFIED_AT, CREATED_OR_MODIFIED_BY) select ID, VAL, ?, ?, ?, ? from (select ? ID, ? VAL from DUAL) t]; ORA-00933: SQL-Befehl wurde nicht korrekt beendet

	at org.jooq_3.17.0-SNAPSHOT.ORACLE21C.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3119)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:678)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:355)
	at org.jooq.impl.TableRecordImpl.storeInsert0(TableRecordImpl.java:190)
	at org.jooq.impl.TableRecordImpl.lambda$0(TableRecordImpl.java:156)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144)
	at org.jooq.impl.TableRecordImpl.storeInsert(TableRecordImpl.java:155)
	at org.jooq.impl.UpdatableRecordImpl.store0(UpdatableRecordImpl.java:222)
	at org.jooq.impl.UpdatableRecordImpl.lambda$0(UpdatableRecordImpl.java:149)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144)
	at org.jooq.impl.UpdatableRecordImpl.store(UpdatableRecordImpl.java:148)
	at org.jooq.impl.UpdatableRecordImpl.store(UpdatableRecordImpl.java:140)
	at org.jooq.test.all.testcases.AuditTests.lambda$12(AuditTests.java:193)
	at org.jooq.test.all.testcases.AuditTests.testAuditUpdatableRecord0(AuditTests.java:173)
	at org.jooq.test.all.testcases.AuditTests.testAuditUpdatableRecordStore(AuditTests.java:192)
	at org.jooq.test.jOOQAbstractTest.testAuditUpdatableRecordStore(jOOQAbstractTest.java:10960)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00933: SQL-Befehl wurde nicht korrekt beendet

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:630)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:564)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1231)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:772)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:299)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:512)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:163)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1241)
	at oracle.jdbc.driver.OracleStatement.executeSQLStatement(OracleStatement.java:1820)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1472)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3761)
	at oracle.jdbc.driver.OraclePreparedStatement.executeLargeUpdate(OraclePreparedStatement.java:4062)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:4037)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:996)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.executeUpdate(DefaultPreparedStatement.java:109)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.executeUpdate(DefaultPreparedStatement.java:109)
	at org.jooq.impl.AbstractDMLQuery.executeReturningGeneratedKeys(AbstractDMLQuery.java:1204)
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:1168)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:341)
	... 45 more
Caused by: [SQL INCLUDES EXPRESSIONS ADDED BY THE ORACLE JDBC DRIVER],Error : 933, Position : 179, Sql = insert into T_AUDIT (ID, VAL, CREATED_AT, CREATED_BY, CREATED_OR_MODIFIED_AT, CREATED_OR_MODIFIED_BY) select ID, VAL, :1 , :2 , :3 , :4  from (select :5  ID, :6  VAL from DUAL) t RETURNING ID INTO :7 , OriginalSql = insert into T_AUDIT (ID, VAL, CREATED_AT, CREATED_BY, CREATED_OR_MODIFIED_AT, CREATED_OR_MODIFIED_BY) select ID, VAL, ?, ?, ?, ? from (select ? ID, ? VAL from DUAL) t RETURNING ID INTO ?, Error Msg = ORA-00933: SQL-Befehl wurde nicht korrekt beendet

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:637)
	... 63 more
```

The jOOQ query is certainly correct, but the bottom most "caused by" message shows the actual query that is generated by ojdbc, which is incorrect:

```sql
insert into T_AUDIT (ID, VAL, CREATED_AT, CREATED_BY, CREATED_OR_MODIFIED_AT, CREATED_OR_MODIFIED_BY) 
select ID, VAL, :1 , :2 , :3 , :4 
from (select :5  ID, :6  VAL from DUAL) t
RETURNING ID INTO :7
```

Or, specifically, it should be correct, but ojdbc or Oracle itself doesn't support `INSERT .. SELECT .. RETURNING`. Hence, we need to trigger our usual emulation for this.

**Comment by lukaseder** [comment]
This is actually a new 3.17 problem, only. User-defined `INSERT .. SELECT .. RETURNING` queries already properly handle this (see #5863, #7452), but we now also produce a `SELECT` in `FieldMapsForInsert`, when we have stored client side computed columns (see #9879)

**Comment by lukaseder** [comment]
The `InsertQueryImpl::estimatedRowCount` value must be `Integer.MAX_VALUE` to trigger the `BULK COLLECT INTO` emulation.

**Comment by lukaseder** [comment]
Hmm, nope, that still produces the same `ORA-00933`

**Comment by lukaseder** [comment]
That's a bummer. This quite invalidates a lot of use-cases of stored client side computed columns, including audit columns, for Oracle! Specifically, because this `RETURNING` clause is produced by `UpdatableRecord` methods.

**Comment by lukaseder** [comment]
It's not really a different issue than https://github.com/jOOQ/jOOQ/issues/11731. Closing as duplicate.
