### ISSUE TITLE
HstoreConverter::from bug

### ISSUE THREAD

**Issue by Rattenkrieg** [jOOQ/jOOQ#13478]
First, thanks @lukaseder and jooq team for awesome library. ❤️ 

### Expected behavior
`from(Object)` constructing `Hstore` from param.

### Actual behavior
`from(Object)` fails as parameter runtime type appears to be `Map<String, String>` while method presumably expects it to be `java.lang.String` in a form of `"key0"=>"value0", "key1"=>"value1"`.

### Steps to reproduce the problem
here is relevant part of my generator config
```kotlin
            generator.database.withForcedTypes(
                ForcedType()
                    .withUserType("org.jooq.postgres.extensions.types.Hstore")
                    .withBinding("org.jooq.postgres.extensions.bindings.HstoreBinding")
                    .withIncludeTypes("hstore")
                    .withPriority(Integer.MAX_VALUE)
                )
```

### Versions

- jOOQ: 3.16.6
- Java: 17.0.2
- Database (include vendor): Postgres 13,14
- OS: docker 20.10.11, pg container debian 
- JDBC Driver (include name if inofficial driver): pgjdbc 42.3.3; vertx-pg-client 4.2.7

**Comment by Rattenkrieg** [comment]
This is the workaround I'm using at the moment.
```kotlin
class HstoreConverter : AbstractConverter<Any, Hstore>(Any::class.java, Hstore::class.java) {
    override fun from(t: Any?): Hstore? {
        @Suppress("UNCHECKED_CAST")
        return when (t) {
            null -> null
            is String -> hstore(HStoreConverter.fromString("" + t))
            is Map<*, *> -> hstore(t as Map<String, String>)
            else -> throw IllegalArgumentException("Unsupported type [${t::class.simpleName}]")
        }
    }

    override fun to(u: Hstore?): Any? {
        return if (u == null) null else HStoreConverter.toString(u.data())
    }
}
```

**Comment by lukaseder** [comment]
Thanks for your report. But how *exactly* does it fail? It doesn't fail in our integration tests. Can you please provide a complete example to help reproduce what you're seeing? We have a template here to help build such examples: https://github.com/jOOQ/jOOQ-mcve

**Comment by Rattenkrieg** [comment]
I've adapted jooq usage to way I use it in my [framework](https://github.com/razz-team/eva/blob/main/eva-persistence-jdbc/src/main/kotlin/com/razz/eva/persistence/jdbc/executor/JdbcQueryExecutor.kt), I believe there is a bug in conversion of returned rows for insert queries.

https://github.com/Rattenkrieg/jOOQ-mcve/blob/3ab8c16d3c22eda06d422d747f9b2da4c079972b/jOOQ-mcve-java/src/test/java/org/jooq/mcve/test/java/JavaTest.java#L50-L58

**Comment by lukaseder** [comment]
Thanks a lot for your MCVE, I'm glad I asked for it. I would not have been able to reproduce exactly this problem, otherwise. I'm assuming, this is the exception that I was supposed to be seeing?

```
org.jooq.exception.MappingException: An error ocurred when mapping record to class org.jooq.mcve.java.tables.records.TestRecord

	at org.jooq.impl.DefaultRecordMapper$RecordToRecordMapper.map(DefaultRecordMapper.java:753)
	at org.jooq.impl.DefaultRecordMapper$RecordToRecordMapper.map(DefaultRecordMapper.java:742)
	at org.jooq.impl.DefaultRecordMapper.map(DefaultRecordMapper.java:611)
	at org.jooq.RecordMapper.apply(RecordMapper.java:87)
	at org.jooq.RecordMapper.apply(RecordMapper.java:72)
	at java.base/java.util.stream.Collectors.lambda$mapping$13(Collectors.java:469)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:1003)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.jooq.impl.ResultImpl.collect(ResultImpl.java:137)
	at org.jooq.impl.ResultImpl.into(ResultImpl.java:910)
	at org.jooq.mcve.test.java.JavaTest.mcveTest(JavaTest.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.jooq.exception.MappingException: An error ocurred when mapping record to +----+------+
|  id|data  |
+----+------+
|   2|{null}|
+----+------+

	at org.jooq.impl.AbstractRecord$TransferRecordState.apply(AbstractRecord.java:897)
	at org.jooq.impl.AbstractRecord$TransferRecordState.apply(AbstractRecord.java:849)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143)
	at org.jooq.impl.AbstractRecord.intoRecord(AbstractRecord.java:846)
	at org.jooq.impl.DefaultRecordMapper$RecordToRecordMapper.map(DefaultRecordMapper.java:748)
	... 43 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 17
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
	at java.base/java.lang.String.charAt(String.java:1512)
	at org.postgresql.util.HStoreConverter.fromString(HStoreConverter.java:132)
	at org.jooq.postgres.extensions.converters.HstoreConverter.from(HstoreConverter.java:64)
	at org.jooq.postgres.extensions.converters.HstoreConverter.from(HstoreConverter.java:51)
	at org.jooq.impl.ConvertedDataType.convert(ConvertedDataType.java:298)
	at org.jooq.impl.AbstractRecord$TransferRecordState.apply(AbstractRecord.java:876)
	... 47 more
```

The problem is that there is no data type information available on your plain SQL query when you run `ctx.fetch()`, so jOOQ doesn't actually use your converter at the exact time when it should be using it, namely when reading data from the JDBC `ResultSet`.

When you map your plain SQL result set (which contains an unspecified pgjdbc type representing the `hstore`), you're mapping it to the `TEST.getRecordType()`, but at that moment, it is too late to use `Converter` types. A field's `Converter` is used by the internal data type `Binding` right after reading a value from JDBC.

You can register global converters using the `ConverterProvider` SPI: https://www.jooq.org/doc/latest/manual/sql-execution/fetching/converter-provider/

But in your specific case, a much better approach would be to either:

- Directly execute your `insertQuery` instead of rendering it and extracting the params manually. Your example doesn't show why you're doing that, but it's usually better not to, to prevent issues like this one.
- To use `ResultQuery::coerce` to specify the resulting `Record` type and corresponding column types on a plain SQL query, i.e. instead of:

```java
final var insertRes = ctx.fetch(
    ctx.render(insertQuery),
    ctx.extractParams(insertQuery).values().stream().filter(param -> !param.isInline()).toArray(Param[]::new)
).into(TEST.getRecordType());

// ...
final var res = ctx.fetch(
    ctx.render(query),
    ctx.extractParams(query).values().stream().filter(param -> !param.isInline()).toArray()
).into(query.getRecordType());
```

Write this instead


```java
final var insertRes = ctx.fetch(
    ctx.render(insertQuery),
    ctx.extractParams(insertQuery).values().stream().filter(param -> !param.isInline()).toArray(Param[]::new)
).into(TEST.getRecordType());

// ...
final var res = ctx.fetch(
    ctx.render(query),
    ctx.extractParams(query).values().stream().filter(param -> !param.isInline()).toArray()
).into(query.getRecordType());
```

The assertion should be this:

```java
assertEquals(res.get(0).get(TEST.DATA).data(), Map.of("k0", "v0", "k1", "v1"));
```

**Comment by lukaseder** [comment]
This patch fixes the issue in your MCVE:

```patch
diff --git a/jOOQ-mcve-java/src/test/java/org/jooq/mcve/test/java/JavaTest.java b/jOOQ-mcve-java/src/test/java/org/jooq/mcve/test/java/JavaTest.java
index 0af527b..7b24cf0 100644
--- a/jOOQ-mcve-java/src/test/java/org/jooq/mcve/test/java/JavaTest.java
+++ b/jOOQ-mcve-java/src/test/java/org/jooq/mcve/test/java/JavaTest.java
@@ -28,7 +28,7 @@ public class JavaTest {

     @Before
     public void setup() throws Exception {
-        connection = DriverManager.getConnection("jdbc:postgresql:postgres", "postgres", "postgres");
+        connection = DriverManager.getConnection("jdbc:postgresql:postgres", "postgres", "test");
         ctx = DSL.using(
             connection,
             SQLDialect.POSTGRES,
@@ -52,10 +52,10 @@ public class JavaTest {
         final var insertQuery = ctx.insertQuery(TEST);
         insertQuery.setRecord(record);
         insertQuery.setReturning(); // this setting is crucial to make test failing
-        final var insertRes = ctx.fetch(
+        final var insertRes = ctx.resultQuery(
             ctx.render(insertQuery),
             ctx.extractParams(insertQuery).values().stream().filter(param -> !param.isInline()).toArray(Param[]::new)
-        ).into(TEST.getRecordType());
+        ).coerce(TEST).fetch();

         assertEquals(1, insertRes.size());

@@ -64,11 +64,11 @@ public class JavaTest {
             .from(TEST)
             .where(TEST.DATA.eq(Hstore.hstore(Map.of("k0", "v0", "k1", "v1"))));

-        final var res = ctx.fetch(
+        final var res = ctx.resultQuery(
             ctx.render(query),
             ctx.extractParams(query).values().stream().filter(param -> !param.isInline()).toArray()
-        ).into(query.getRecordType());
+        ).coerce(query.getSelect()).fetch();

-        assertEquals(res.get(0).get(TEST.DATA), Map.of("k0", "v0", "k1", "v1"));
+        assertEquals(res.get(0).get(TEST.DATA).data(), Map.of("k0", "v0", "k1", "v1"));
     }
 }
```

**Comment by Rattenkrieg** [comment]
Thank you @lukaseder for concise explanation and useful examples!
Some feedback regarding your suggestions:
> Directly execute your insertQuery instead of rendering it and extracting the params manually. Your example doesn't show why you're doing that, but it's usually better not to, to prevent issues like this one.

I want to maintain simple interface which allows me to separate query building from execution. I've committed to jooq on quey building side but I want to have pluggable query executor. I use jdbc and vertx-sql at the moment. [Here](https://github.com/razz-team/eva/blob/main/eva-persistence-vertx/src/main/kotlin/com/razz/eva/persistence/vertx/executor/VertxQueryExecutor.kt#L62-L64) is vertx code for reference. 

I've patched my code according to your suggestions (`resultQuery` + `coerce` api), thanks a lot!

**Comment by lukaseder** [comment]
> I've committed to jooq on quey building side but I want to have pluggable query executor.

OK, just know that you will keep running into such limitations because jOOQ implements quite a few features during the execution stage, including e.g. most of the `MULTISET` / nested `ROW` magic / ad-hoc conversion, etc.
