### ISSUE TITLE
SQLException when calling oracle.jdbc.driver.ArrayDataResultSet.getMetaData()

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13473]
The following exception appears in a customer log after an upgrade from jOOQ 3.14.11 to 3.16.5:

```
Exception while accessing ResultSetMetaData java.sql.SQLException: Nicht unterstützte Funktion: getMetaData 
  at oracle.jdbc.driver.ArrayDataResultSet.getMetaData(ArrayDataResultSet.java:1098) 
  at com.zaxxer.hikari.pool.HikariProxyResultSet.getMetaData(HikariProxyResultSet.java) 
  at org.jooq.tools.jdbc.DefaultResultSet.getMetaData(DefaultResultSet.java:303) 
  at org.jooq.impl.CursorImpl$CursorResultSet.getMetaData(CursorImpl.java:307) 
  at org.jooq.impl.CursorImpl.initLongIndexes(CursorImpl.java:174) 
  at org.jooq.impl.CursorImpl.<init>(CursorImpl.java:135) 
  at org.jooq.impl.CursorImpl.<init>(CursorImpl.java:120) 
  at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:1169) 
  at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:340) 
  at org.jooq.impl.UpdatableRecordImpl.storeMergeOrUpdate0(UpdatableRecordImpl.java:351) 
  at org.jooq.impl.UpdatableRecordImpl.storeMerge0(UpdatableRecordImpl.java:268) 
  at org.jooq.impl.UpdatableRecordImpl.lambda$storeMerge$2(UpdatableRecordImpl.java:248) 
  at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143) 
  at org.jooq.impl.UpdatableRecordImpl.storeMerge(UpdatableRecordImpl.java:247) 
  at org.jooq.impl.UpdatableRecordImpl.merge(UpdatableRecordImpl.java:183) 
  at org.jooq.impl.UpdatableRecordImpl.merge(UpdatableRecordImpl.java:178)
```

Since #4820 and jOOQ 3.8.0, we've been reading the `ResultSet::getMetaData` to prioritise fetching `LONG` data, which must be read first from a `ResultSet`.

The problem appears with `UpdatableRecord.merge()`, which may produce array `OUT` parameters to fetch returned values. I'll try to create a minimal reproducer and document this here.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.17.0, 3.16.7 (https://github.com/jOOQ/jOOQ/issues/13474), and 3.15.11 (https://github.com/jOOQ/jOOQ/issues/13475)
