### ISSUE TITLE
NPE in PlainSQLChecker

### ISSUE THREAD

**Issue by db2222** [jOOQ/jOOQ#13483]
### Expected behavior
Maven build works ;-)

### Actual behavior
It stops and jOOQ creates an error.txt file:
```
This is probably a bug in jOOQ-checker.
If you think this is a bug in jOOQ, please report it here: https://github.com/jOOQ/jOOQ/issues/new
---------------------------------------------------------------------
java.lang.NullPointerException
    at org.jooq.checker.Tools.checkPlainSQL(Tools.java:168)
    at org.jooq.checker.PlainSQLChecker$1.visitMethodInvocation(PlainSQLChecker.java:62)
    at org.jooq.checker.PlainSQLChecker$1.visitMethodInvocation(PlainSQLChecker.java:58)
    at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1477)
    at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
    at org.checkerframework.framework.source.SourceVisitor.scan(SourceVisitor.java:91)
    at com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:243)
    at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1302)
    at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
    at org.checkerframework.framework.source.SourceVisitor.scan(SourceVisitor.java:91)
    at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:81)
    at com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
    at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:162)
    at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:918)
    at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
    at org.checkerframework.framework.source.SourceVisitor.scan(SourceVisitor.java:91)
    at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:81)
    at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:144)
    at org.checkerframework.framework.source.SourceVisitor.visitMethod(SourceVisitor.java:109)
    at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:800)
    at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
    at org.checkerframework.framework.source.SourceVisitor.scan(SourceVisitor.java:91)
    at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:81)
    at com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
    at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:99)
    at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:133)
    at org.checkerframework.framework.source.SourceVisitor.visitClass(SourceVisitor.java:97)
    at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
    at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
    at org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:85)
    at org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:972)
    at org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:182)
    at com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:681)
    at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:111)
    at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1342)
    at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
    at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
    at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
    at com.sun.tools.javac.main.Main.compile(Main.java:523)
    at com.sun.tools.javac.main.Main.compile(Main.java:381)
    at com.sun.tools.javac.main.Main.compile(Main.java:370)
    at com.sun.tools.javac.main.Main.compile(Main.java:361)
    at com.sun.tools.javac.Main.compile(Main.java:56)
    at com.sun.tools.javac.Main.main(Main.java:42)
```

### Steps to reproduce the problem
- Add PlainSqlChecker like described in https://www.jooq.org/doc/latest/manual/tools/checker-framework/#plainsqlchecker.
- It is maybe only reproducible with our code. However I cannot post/upload it (copyright).
- Is there maybe more logging possible?
- Or can a simple null check be added? I could create a merge request sometime this week.

Thanks in advance.

### Versions

- jOOQ: 3.16.5
- Java: 8
- Database (include vendor): irrelevant
- OS: Windows
- JDBC Driver (include name if inofficial driver): irrelevant

**Comment by lukaseder** [comment]
Thanks for your report.

Can you please provide a reproducer? It doesn't have to be your specific copyrighted code, but we have a template to create reproducers here: https://github.com/jOOQ/jOOQ-mcve

It's unlikely I will easily be able to reproduce this problem. We don't have it in our integration tests.

> Is there maybe more logging possible?

Is this a feature request? Can you be specific about it? (Preferably in a new, separate issue)

> Or can a simple null check be added? I could create a merge request sometime this week.

Maybe that is the fix, maybe it just hides the problem. Without a reproducer and a clear picture of why the NPE is happening, I wouldn't want to just patch something.

**Comment by db2222** [comment]
I'll close this ticket for now. Other build problems occurred with Lombok (log) when PlainSQLChecker was added. A bit of a confusing state (lots of dependencies/projects).

However now I was unfortunately planned for completely other tasks in my company so I can't find further time to investigate this. But I'm hoping I can come back to it in the future.

In case I can cleanly reproduce it in the future I would contact you again.

Regarding the logging. I meant more logging of the PlainSQLChecker during build to better pin-point which source code element it is currently trying to process which then lead it to fail. This would narrow it down more easily. No need of a feature request if this doesn't exist.

**Comment by lukaseder** [comment]
Thanks for your feedback, makes sense.

> Regarding the logging. I meant more logging of the PlainSQLChecker during build to better pin-point which source code element it is currently trying to process which then lead it to fail.

I'm not sure if that's something compiler plugins really do? What API would we do it with? I mean, we can emit compiler warnings or write to files, but that doesn't seem to be desirable...
