### ISSUE TITLE
org.jooq.tools.json.JSONParser fails to parse certain jsons

### ISSUE THREAD

**Issue by ivyazmitinov** [jOOQ/jOOQ#13547]
### Expected behavior
When using JSONB, the following query executed correctly:

```
final var value = JSONB.valueOf("""
    {
      "type": "OBJECT",
      "fields": {
        "gametime": {
          "type": "VALUES",
          "reachedThreshold": false,
          "values": [
            {
              "type": "NUMBER",
              "value": 18446681938112752000,
              "count": 30
            }
          ]
        }
      }
    }
    """);
dslContext.insertInto(METAINFO_CACHE)
    .set(METAINFO_CACHE.CACHE_PART_NAME, "test")
    .set(METAINFO_CACHE.VALUE, value)
    .set(METAINFO_CACHE.TENANT_ID, "t")
    .execute();
```

### Actual behavior

```
For input string: "18446681938112752000"
java.lang.NumberFormatException: For input string: "18446681938112752000"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Long.parseLong(Long.java:711)
	at java.base/java.lang.Long.valueOf(Long.java:1163)
	at org.jooq.tools.json.Yylex.yylex(Yylex.java:659)
	at org.jooq.tools.json.JSONParser.nextToken(JSONParser.java:263)
	at org.jooq.tools.json.JSONParser.parse(JSONParser.java:112)
	at org.jooq.tools.json.JSONParser.parse(JSONParser.java:75)
	at org.jooq.tools.json.JSONParser.parse(JSONParser.java:69)
	at org.jooq.JSONB.parsed(JSONB.java:104)
	at org.jooq.JSONB.toString(JSONB.java:131)
	at java.base/java.lang.String.valueOf(String.java:4215)
	at org.jooq.impl.AbstractParam.name(AbstractParam.java:127)
	at org.jooq.impl.AbstractParam.name(AbstractParam.java:115)
	at org.jooq.impl.AbstractParam.<init>(AbstractParam.java:81)
	at org.jooq.impl.AbstractParam.<init>(AbstractParam.java:77)
	at org.jooq.impl.Val.<init>(Val.java:100)
	at org.jooq.impl.DSL.val(DSL.java:29670)
	at org.jooq.impl.DSL.val(DSL.java:29638)
	at org.jooq.impl.Tools.lambda$field$54(Tools.java:1774)
	at org.jooq.impl.Tools.field(Tools.java:1766)
	at org.jooq.impl.Tools.field(Tools.java:1774)
	at org.jooq.impl.AbstractStoreQuery.addValue(AbstractStoreQuery.java:90)
	at org.jooq.impl.AbstractStoreQuery.addValue(AbstractStoreQuery.java:75)
	at org.jooq.impl.InsertImpl.set(InsertImpl.java:1196)
	at org.jooq.impl.InsertImpl.set(InsertImpl.java:146)
```

### Steps to reproduce the problem

MCVE can be found [here](https://github.com/ivyazmitinov/jooq-jsonb-bug)

### Versions

- jOOQ: 3.16.6
- Java: 17
- Database (include vendor): PostgreSQL 14.2
- OS: Linux
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.3.4

**Comment by lukaseder** [comment]
Thanks for your report. There are multiple problems here:

1. The fact that large integers aren't handled by the third party library jOOQ uses for JSON parsing (json-simple, which isn't maintained anymore, and which we might replace: https://github.com/jOOQ/jOOQ/issues/12176). A related problem is this: https://github.com/jOOQ/jOOQ/issues/12173
2. The fact that `AbstractParam` calls `JSONB::toString`, because for your usage of `JSONB`, there's no need to parse the contents. I think there's already an issue for this, but I cannot seem to find it.

Will investigate further. Clearly, even if json-simple might not be easy to patch, it should be possible to insert this JSON into the database.

**Comment by SFelon** [comment]
Hi,
I've run into same problem with NumberFormatException while migrating from older jooq version to 3.17. I had to rewrite my custom converter from Object -> JsonNode to explicit JSONB -> JsonNode version. 

With that I started receiving mentioned NumberFormatExceptions with json's containing long numeric fields like "254716739847254700423792". I was following the example in:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types/codegen-database-forced-types-binding/

and found out that this my happen when running the line:
**ctx.render().visit(DSL.inline(ctx.convert(converter()).value())).sql("::json");** 
Or
**ctx.statement().setString(ctx.index(), Objects.toString(ctx.convert(converter()).value(), null));**

as both these functions call underneath JSONB.toString() method which causes the problems.

For first line I did not needed to find solution as I was always falling into else part of the example. 

For the second one I managed to fix it by changing Objects.toString(...) call to ctx.convert(converter()).value()**.data()** with some null validation.

As the fix doesn't seem to arrive any time soon I believe it would be beneficial to update the example on manual to avoid JSON/JSONB.toString() call whether possible.

**Comment by lukaseder** [comment]
> As the fix doesn't seem to arrive anytime soon I believe it would be beneficial to update the example on manual to avoid JSON/JSONB.toString() call whenever possible.

You're right, that example is flawed. Even with the fix to this issue here, calling `data()` is much faster than calling `toString()`...

**Comment by lukaseder** [comment]
It's probably a historic example problem. Before jOOQ 3.12 introduced `JSON` and `JSONB` types, the `T` type variable of `Binding<T, U>` was bound to `Object`, and it was effectively a `PGobject` from the jdbc driver. Calling `toString()` was the most reasonable thing to do on that type. On `JSON`, it still works as expected. But in jOOQ 3.15, the semantics of `JSONB::toString` was changed with #12023

**Comment by lukaseder** [comment]
Manual fix here: https://github.com/jOOQ/jOOQ/issues/14094

**Comment by ivyazmitinov** [comment]
JFYI, after #17578 the example query works (and we can use new versions of jooq 🎉 ), so the issue is partially fixed, or, at least, not that severe
