### ISSUE TITLE
NullPointerException when rendering CTE without a top level context

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13543]
Under some test conditions that are documented here: https://github.com/jOOQ/jOOQ/issues/13541, I could produce a NPE which arises when the `DATA_TOP_LEVEL_CTE` object isn't available in the `Context::data` map. This may be a test-only artifact that is hard to reproduce in ordinary user code. I couldn't quickly create a test case that doesn't depend on #13541 and related tests.

Nevertheless, it should be worth fixing this. In the absence of a `TopLevelCte` object, we should simply not produce any such CTE.

```
java.lang.RuntimeException: QueryPart of type class org.jooq.impl.Unique should be parenthesised in dialect SQLSERVER
	at org.jooq.impl.InternalAccess.lambda$0(InternalAccess.java:141)
	at org.jooq.Traversers.lambda$9(Traversers.java:123)
	at org.jooq.impl.CachingTraverser.lambda$3(CachingTraverser.java:103)
	at org.jooq.impl.QOM.traverse(QOM.java:6421)
	at org.jooq.impl.Unique.$traverse(Unique.java:174)
	at org.jooq.impl.InternalAccess.qomAssertionsParentheses(InternalAccess.java:117)
	at org.jooq.test.util.BaseTest.qomAssertions(BaseTest.java:713)
	at org.jooq.impl.AbstractParserTest.additionalAssertions(AbstractParserTest.java:511)
	at org.jooq.impl.AbstractParserTest.assertConditionEquals(AbstractParserTest.java:400)
	at org.jooq.impl.ParserPredicateTest.testUniquePredicate(ParserPredicateTest.java:557)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.NullPointerException: Cannot invoke "org.jooq.impl.TopLevelCte.addAll(java.util.Collection)" because "cte" is null
	at org.jooq.impl.WithImpl.accept(WithImpl.java:226)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:739)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:307)
	at org.jooq.impl.SelectQueryImpl.accept0(SelectQueryImpl.java:1625)
	at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:1449)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:739)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:307)
	at org.jooq.impl.Tools.visitSubquery(Tools.java:2693)
	at org.jooq.impl.DerivedTable.accept(DerivedTable.java:111)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:739)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:267)
	at org.jooq.impl.Alias.toSQLWrapped(Alias.java:392)
	at org.jooq.impl.Alias.lambda$5(Alias.java:385)
	at org.jooq.impl.AbstractContext.toggle(AbstractContext.java:350)
	at org.jooq.impl.AbstractContext.data(AbstractContext.java:361)
	at org.jooq.impl.Alias.toSQLWrapped(Alias.java:385)
	at org.jooq.impl.Alias.acceptDeclareAliasStandard(Alias.java:309)
	at org.jooq.impl.Alias.accept(Alias.java:181)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:739)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:307)
	at org.jooq.impl.TableAlias.accept(TableAlias.java:151)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:739)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:307)
	at org.jooq.impl.QueryPartCollectionView.acceptElement(QueryPartCollectionView.java:243)
	at org.jooq.impl.TableList.acceptElement(TableList.java:92)
	at org.jooq.impl.TableList.acceptElement(TableList.java:1)
	at org.jooq.impl.QueryPartCollectionView.accept(QueryPartCollectionView.java:221)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:739)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:307)
	at org.jooq.impl.SelectQueryImpl.toSQLReference0(SelectQueryImpl.java:2307)
	at org.jooq.impl.SelectQueryImpl.accept0(SelectQueryImpl.java:1708)
	at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:1449)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:739)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:307)
	at org.jooq.impl.AbstractDelegatingQuery.accept(AbstractDelegatingQuery.java:90)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:739)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:307)
	at org.jooq.impl.Tools.visitSubquery(Tools.java:2693)
	at org.jooq.impl.Tools.visitSubquery(Tools.java:2664)
	at org.jooq.impl.Exists.accept(Exists.java:113)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:739)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:307)
	at org.jooq.impl.Not.accept(Not.java:113)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:739)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:307)
	at org.jooq.impl.Unique.accept(Unique.java:124)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:739)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:307)
	at org.jooq.impl.DefaultDSLContext.render(DefaultDSLContext.java:724)
	at org.jooq.impl.InternalAccess.lambda$0(InternalAccess.java:128)
	... 39 more
```

**Comment by lukaseder** [comment]
Given that I cannot reproduce this with ordinary client code, I won't backport the fix.
