### ISSUE TITLE
Converter / Binding not found with InsertValuesStep#valuesOfRows() (works with #values())

### ISSUE THREAD

**Issue by uwolfer** [jOOQ/jOOQ#13620]
### Expected behavior

The same logic written in a different way works as expected:

```java
var query = database
  .getContext()
  .insertInto(SOME_TABLE)
  .columns(SOME_TABLE.JSONB_DATA);
data.forEach(d -> query.values(d.getData());
query.execute();
```

### Actual behavior

The following code fails with the following exception:

```java
database
  .getContext()
  .insertInto(SOME_TABLE)
  .columns(SOME_TABLE.JSONB_DATA)
  .valuesOfRows(data.stream().map(d -> DSL.row(d.getData())).collect(toList()))
  .execute();
```

SOME_TABLE.JSONB_DATA field is of type JSONB, and for JSONB, I have a custom binding registered which converts from and to Gson JsonElement.

Data#getData() return an instance of JsonObject, which extends JsonElement.

```
org.jooq.exception.SQLDialectNotSupportedException: Type class com.google.gson.JsonObject is not supported in dialect POSTGRES
  at org.jooq_3.16.6.POSTGRES.debug(Unknown Source)
  at app//org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:811)
  at app//org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:755)
  at app//org.jooq.impl.DefaultBinding$InternalBinding.sqlCast(DefaultBinding.java:839)
  at app//org.jooq.impl.DefaultBinding$InternalBinding.sql(DefaultBinding.java:944)
  at app//org.jooq.impl.Val.accept(Val.java:186)
  at app//org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:721)
  at app//org.jooq.impl.AbstractContext.visit(AbstractContext.java:295)
  at app//org.jooq.impl.FieldMapsForInsert.toSQL92Values(FieldMapsForInsert.java:326)
  at app//org.jooq.impl.FieldMapsForInsert.toSQL92Values(FieldMapsForInsert.java:278)
  at app//org.jooq.impl.FieldMapsForInsert.accept(FieldMapsForInsert.java:203)
  at app//org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:721)
  at app//org.jooq.impl.AbstractContext.visit(AbstractContext.java:295)
  at app//org.jooq.impl.InsertQueryImpl.toSQLInsert(InsertQueryImpl.java:740)
  at app//org.jooq.impl.InsertQueryImpl.accept0(InsertQueryImpl.java:625)
  at app//org.jooq.impl.AbstractDMLQuery.accept(AbstractDMLQuery.java:642)
  at app//org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:721)
  at app//org.jooq.impl.AbstractContext.visit(AbstractContext.java:295)
  at app//org.jooq.impl.AbstractQuery.getSQL0(AbstractQuery.java:474)
  at app//org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:287)
  at app//org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
```

### Steps to reproduce the problem

The following forced type is set up for JSONB (I also tried it with a binding instead of a converter, but it results in the same issue):

```java
  ForcedType jsonbType = new ForcedType();
  jsonbType.setUserType("com.google.gson.JsonElement");
  jsonbType.setConverter("com.example.JsonbConverter");
  jsonbType.setIncludeTypes("jsonb");
  return jsonbType;
```

### Versions

- jOOQ: 3.16.6
- Java: 15.0.2 OpenJDK
- Database (include vendor): postgres:11.15
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.3.6

**Comment by lukaseder** [comment]
Thanks for your report. There are a few issues where we'd like to "infer" the type of `Row[N]` contents in case they haven't been provided explicitly. Of course, providing the type explicitly is always the soundest option, e.g.

```java
row(val(d.getData(), SOME_TABLE.JSONB_DATA))
```

Note that starting with jOOQ 3.15 and #10775, you can construct such `Row[N]` lists also using our collectors from `org.jooq.Rows`, e.g.

```java
data.stream().collect(Rows.toRowList(d -> val(d.getData(), SOME_TABLE.JSONB_DATA)))
```

**Comment by lukaseder** [comment]
This appears to have been fixed with:

- https://github.com/jOOQ/jOOQ/issues/14694

In:

- 3.18.0
- 3.17.9
- 3.16.15

Closing as a duplicate
