### ISSUE TITLE
Issue while casting the datetime value from database to Jooq pojo for the timestamp "2022-03-13 02:00:00.000" getting error

### ISSUE THREAD

**Issue by rdyseenu** [jOOQ/jOOQ#13652]
Issue while casting the datetime value from database to Jooq pojo for the timestamp "2022-03-13 02:00:00.000" 

Getting below error for the 2022-03-13 02:00:00.000

```
Error while reading field: \"question\".\"start_date\", at JDBC index: 2","error.stack":"  at 
org.jooq_3.14.8.MYSQL.debug(Unknown Source)\n  at org.jooq_3.14.8.MYSQL.debug(Unknown Source)\n  at 
org.jooq.impl.Tools.translate(Tools.java:2903)\n  at 
org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:757)\n  at 
org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1623)\n  at 
org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1584)\n  at 
org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:349)\n  at 
org.jooq.impl.CursorImpl.fetch(CursorImpl.java:336)\n  at 
org.jooq.impl.CursorImpl.fetch(CursorImpl.java:243)\n  at 
org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:308)\n"} 
```

**Comment by lukaseder** [comment]
Thanks for your report.

- Does the problem persist in the latest jOOQ versions?
- If so, can you please provide a complete reproducer? The information you provided does not suffice to reproduce the bug you may have experienced.

**Comment by rdyseenu** [comment]
Issue is there with latest jooq versions too

**Comment by rdyseenu** [comment]
complete stack trace
`{"message":"error occurred while executing db archive job error details: ","timestamp":1654755567292,"log.level":"ERROR","logger.name":"com.exam.question.archive.job.service.impl.DBArchiveServiceImpl","thread.name":"main","error.class":"org.jooq.exception.DataAccessException","error.message":"SQL [select `examquestion`.`exam_prod_table`.`exam_id`, `examquestion`.`exam_prod_table`.`start_date`, `examquestion`.`exam_prod_table`.`end_date`, `examquestion`.`exam_prod_table`.`created_date`, `examquestion`.`exam_prod_table`.`updated_date`, `examquestion`.`exam_prod_table`.`ticket_id`, `examquestion`.`exam_prod_table`.`exam_status` from `examquestion`.`exam_prod_table` where `examquestion`.`exam_prod_table`.`end_date` < ? order by `examquestion`.`exam_prod_table`.`exam_id` limit ?]; Error while reading field: \"examquestion\".\"exam_prod_table\".\"start_date\", at JDBC index: 2","error.stack":"  at org.jooq_3.14.8.MYSQL.debug(Unknown Source)\n  at org.jooq_3.14.8.MYSQL.debug(Unknown Source)\n  at org.jooq.impl.Tools.translate(Tools.java:2903)\n  at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:757)\n  at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1623)\n  at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1584)\n  at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:349)\n  at org.jooq.impl.CursorImpl.fetch(CursorImpl.java:336)\n  at org.jooq.impl.CursorImpl.fetch(CursorImpl.java:243)\n  at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:308)\n"}`

`ExampProdTable.class` is JOOQ generated POJO 

Below is the generated POJO
`/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExamProdTable implements Serializable {

    private static final long serialVersionUID = 1L;

    private String                  examId;
    private Timestamp               startDate;
    private Timestamp               endDate;
    private Timestamp               createdDate;
    private Timestamp               updatedDate;
    private String                  ticketId;
    private ExamProdTableExamStatus examStatus;

    public ExamProdTable() {}

    public ExamProdTable(ExamProdTable value) {
        this.examId = value.examId;
        this.startDate = value.startDate;
        this.endDate = value.endDate;
        this.createdDate = value.createdDate;
        this.updatedDate = value.updatedDate;
        this.ticketId = value.ticketId;
        this.examStatus = value.examStatus;
    }

    public ExamProdTable(
        String                  examId,
        Timestamp               startDate,
        Timestamp               endDate,
        Timestamp               createdDate,
        Timestamp               updatedDate,
        String                  ticketId,
        ExamProdTableExamStatus examStatus
    ) {
        this.examId = examId;
        this.startDate = startDate;
        this.endDate = endDate;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
        this.ticketId = ticketId;
        this.examStatus = examStatus;
    }

    /**
     * Getter for <code>examquestion.exam_prod_table.exam_id</code>.
     */
    @NotNull
    @Size(max = 60)
    public String getExamId() {
        return this.examId;
    }

    /**
     * Setter for <code>examquestion.exam_prod_table.exam_id</code>.
     */
    public void setExamId(String examId) {
        this.examId = examId;
    }

    /**
     * Getter for <code>examquestion.exam_prod_table.start_date</code>.
     */
    @NotNull
    public Timestamp getStartDate() {
        return this.startDate;
    }

    /**
     * Setter for <code>examquestion.exam_prod_table.start_date</code>.
     */
    public void setStartDate(Timestamp startDate) {
        this.startDate = startDate;
    }

    /**
     * Getter for <code>examquestion.exam_prod_table.end_date</code>.
     */
    @NotNull
    public Timestamp getEndDate() {
        return this.endDate;
    }

    /**
     * Setter for <code>examquestion.exam_prod_table.end_date</code>.
     */
    public void setEndDate(Timestamp endDate) {
        this.endDate = endDate;
    }

    /**
     * Getter for <code>examquestion.exam_prod_table.created_date</code>.
     */
    public Timestamp getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>examquestion.exam_prod_table.created_date</code>.
     */
    public void setCreatedDate(Timestamp createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Getter for <code>examquestion.exam_prod_table.updated_date</code>.
     */
    public Timestamp getUpdatedDate() {
        return this.updatedDate;
    }

    /**
     * Setter for <code>examquestion.exam_prod_table.updated_date</code>.
     */
    public void setUpdatedDate(Timestamp updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * Getter for <code>examquestion.exam_prod_table.ticket_id</code>.
     */
    @Size(max = 45)
    public String getTicketId() {
        return this.ticketId;
    }

    /**
     * Setter for <code>examquestion.exam_prod_table.ticket_id</code>.
     */
    public void setTicketId(String ticketId) {
        this.ticketId = ticketId;
    }

    /**
     * Getter for <code>examquestion.exam_prod_table.exam_status</code>.
     */
    @NotNull
    public ExamProdTableExamStatus getExamStatus() {
        return this.examStatus;
    }

    /**
     * Setter for <code>examquestion.exam_prod_table.exam_status</code>.
     */
    public void setExamStatus(ExamProdTableExamStatus examStatus) {
        this.examStatus = examStatus;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ExamProdTable (");

        sb.append(examId);
        sb.append(", ").append(startDate);
        sb.append(", ").append(endDate);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(updatedDate);
        sb.append(", ").append(ticketId);
        sb.append(", ").append(examStatus);

        sb.append(")");
        return sb.toString();
    }
}`

**Comment by lukaseder** [comment]
Thanks, well, seems like your logger truncates the root cause. A complete stack trace usually has several sections of "caused by" sub-stacktraces, which I cannot see in your case. It's usually a good idea to keep these around, because in Java, exceptions tend to wrap other exceptions and the root cause is often wrapped.

Another option of being able to help you would be if you could provide a complete reproducer using the MCVE template that was suggested initially when creating this issue: https://github.com/jOOQ/jOOQ-mcve

I currently can't see why this could be happening on your end, so I need to be able to reproduce the issue first.

**Comment by lukaseder** [comment]
I couldn't reproduce this problem at the time. I will be happy to look at a complete reproducer, when available.
