### ISSUE TITLE
CodeGen: ExceptionInInitializerError when accessing static fields for the first time

### ISSUE THREAD

**Issue by LightSystem** [jOOQ/jOOQ#13651]
### Expected behavior
Static fields from codegen should be initialized without errors.

### Actual behavior
When code is generated for certain specific objects that exist in the DB and accessing a table through a static field (`Tables.*`) a fatal ExceptionInInitializerError is thrown.

### Steps to reproduce the problem
When having two tables with columns whose type is a PostgreSQL Domain, static fields fail to initialize and throw ExceptionInInitializerError.
Here are the Domains where I've encountered the issue thought the constraints of the Domains do not seem to matter:
```
set search_path = nudge;

CREATE TYPE trial_reward_details AS(
trial_id uuid,
trial_name text,
trial_group_id uuid,
trial_group_name text
);

CREATE domain trial_reward_details_domain as trial_reward_details
check (
value is null or (
(value).trial_id is not null and
(value).trial_name is not null and
(value).trial_group_id is not null and
(value).trial_group_name is not null
)
);

alter TABLE reward_history
add COLUMN trial_reward_details trial_reward_details_domain default null;
```
```
set search_path = nudge;

create type sequential_cycle as (count int, cycle int);
create domain sequential_cycle_domain as sequential_cycle check (
    value is null or (
        (value).count is not null and (value).count > 0 and (value).cycle >= (value).count
    )
);
alter table reminders add column offer_validated_count_cycle sequential_cycle_domain;
```
Stack trace when accessing `Tables.REMINDERS`:
```
java.lang.ExceptionInInitializerError
	at nudge.db.schema.nudge.Nudge.<init>(Nudge.java:108)
	at nudge.db.schema.nudge.Nudge.<clinit>(Nudge.java:48)
	at nudge.db.schema.nudge.udt.SequentialCycle.getSchema(SequentialCycle.java:58)
	at org.jooq.impl.AbstractDataType.lazyName(AbstractDataType.java:606)
	at org.jooq.impl.UDTDataType.lambda$new$db692576$1(UDTDataType.java:54)
	at org.jooq.impl.LazyName.name(LazyName.java:66)
	at org.jooq.impl.LazyName.last(LazyName.java:87)
	at org.jooq.impl.DefaultDataType.<init>(DefaultDataType.java:316)
	at org.jooq.impl.UDTDataType.<init>(UDTDataType.java:51)
	at org.jooq.impl.UDTImpl.getDataType(UDTImpl.java:159)
	at nudge.db.schema.nudge.Domains.<clinit>(Domains.java:29)
	at nudge.db.schema.nudge.tables.Reminders.<init>(Reminders.java:101)
	at nudge.db.schema.nudge.tables.Reminders.<init>(Reminders.java:104)
	at nudge.db.schema.nudge.tables.Reminders.<init>(Reminders.java:129)
	at nudge.db.schema.nudge.tables.Reminders.<clinit>(Reminders.java:43)
	at nudge.db.schema.nudge.Tables.<clinit>(Tables.java:79)
	at nudge.adapters.sql.jOOQInitializationSpec.$anonfun$new$1(jOOQInitializationSpec.scala:8)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
Caused by: java.lang.NullPointerException
	at nudge.db.schema.nudge.tables.RewardHistory.<init>(RewardHistory.java:102)
	at nudge.db.schema.nudge.tables.RewardHistory.<init>(RewardHistory.java:105)
	at nudge.db.schema.nudge.tables.RewardHistory.<init>(RewardHistory.java:130)
	at nudge.db.schema.nudge.tables.RewardHistory.<clinit>(RewardHistory.java:43)
	... 18 more
```
Problem does not occur if schema static field is accessed first, in this case a call to `nudge.db.schema.nudge.Nudge.NUDGE` done before trying to access tables resolves the issue (this is my current workaround).
Problem does not occur with only one of these domains.

Code generation configuration:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<configuration xmlns="http://www.jooq.org/xsd/jooq-codegen-3.13.0.xsd">
  <jdbc>
    <url>${dbUrl}</url>
    <user>${dbUser}</user>
    <password>${dbPassword}</password>
  </jdbc>
  <generator>
    <database>
      <name>org.jooq.meta.postgres.PostgresDatabase</name>
      <excludes>information_schema.* | pg_catalog.* | public.*</excludes>
      <includeIndexes>false</includeIndexes> <!-- jOOQ is unable to parse the syntax of some indexes anyway -->
    </database>
    <target>
      <packageName>nudge.db.schema</packageName>
      <directory>${sourceManaged}</directory>
    </target>
  </generator>
</configuration>
```

### Versions

- jOOQ: 3.16.6
- Java: multiple editions of Java 11
- Database (include vendor): PostgreSQL 12.4 and 12.10
- OS: MacOS/Ubuntu
- JDBC Driver (include name if inofficial driver): postgresql 42.3.4

**Comment by samueldlightfoot** [comment]
Following as we are also seeing this behaviour with PostgreSQL

**Comment by lukaseder** [comment]
One of the main reasons why this might happen is when multiple threads access generated code before it has been fully initialised.

**Comment by samueldlightfoot** [comment]
Thanks, Lukas. Do you have a suggestion of where to place this manual piece of code? I thought it would be a trivial change but we still see this in some of our builds.

**Comment by lukaseder** [comment]
@samueldlightfoot A good place would be wherever the `main(String[])` method is located, or the `@SpringBootApplication` class if you're using Spring Boot. If you're loading the schema when that class is loaded, you should be fine.

Alternatively, you might have a jOOQ configuration like this for Spring Boot:

```java
@Configuration
public class Config {

	@Bean
	public DefaultConfigurationCustomizer configurationCustomiser() {
		return c -> c.settings().whatever();
	}
}
```

That would also be a good location, since Spring already takes care of initialising things in the right order, and nothing jOOQ related can run before that customizer is initialised.
