### ISSUE TITLE
Cannot project unnamed MULTISET or ROW from derived table

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13665]
As reported by @juriad in this issue here:
https://github.com/jOOQ/jOOQ/issues/13664#issuecomment-1154175824

Tests like these currently fail:

```java
public void testDerivedTablesProjectingMultiset() throws Exception {
    testMultisetEmulations(c1 -> {
        Select<Record1<Integer>> b = select(TBook_ID()).from(TBook()).orderBy(TBook_ID());

        Result<Record1<Integer>> r1 = create().fetchValue(
            selectFrom(select(multiset(b)))
        );

        assertEquals(BOOK_IDS, r1.map(x -> x.value1()));

        List<Integer> r2 = create().fetchValue(
            selectFrom(select(multiset(b).convertFrom(r -> r.map(x -> x.value1()))))
        );

        assertEquals(BOOK_IDS, r2);
    });
}

static final record IdTitle(int id, String title) {}

public void testDerivedTablesProjectingRow() throws Exception {
    testMultisetEmulations(c1 -> {
        List<Record2<Integer, String>> r1 = create().fetchValues(selectFrom(
            select(row(TBook_ID(), TBook_TITLE())).from(TBook())
        ));

        assertEquals(BOOK_IDS, seq(r1).sorted(x -> x.value1()).map(x -> x.value1()).toList());
        assertEquals(BOOK_TITLES, seq(r1).sorted(x -> x.value1()).map(x -> x.value2()).toList());

        List<IdTitle> r2 = create().fetchValues(selectFrom(
            select(row(TBook_ID(), TBook_TITLE()).mapping(IdTitle::new)).from(TBook()).orderBy(TBook_ID())
        ));

        assertEquals(BOOK_IDS, seq(r2).sorted(x -> x.id()).map(x -> x.id()).toList());
        assertEquals(BOOK_TITLES, seq(r2).sorted(x -> x.id()).map(x -> x.title()).toList());
    });
}
```

The projections don't work correctly. E.g. the `MULTISET` test fails with:

```
org.jooq.exception.DataAccessException: SQL [select "alias_124434926".multiset from (select (select coalesce(json_agg(json_build_array("v0")), json_build_array()) from (select "public"."t_book"."id" as "v0" from "public"."t_book" order by "public"."t_book"."id") as "t")) as "alias_124434926" -- SQL rendered with a free trial version of jOOQ 3.17.0-SNAPSHOT]; ERROR: column alias_124434926.multiset does not exist
  Position: 8
	at org.jooq_3.17.0-SNAPSHOT.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3298)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:678)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:355)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:301)
	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:322)
	at org.jooq.impl.SelectImpl.fetchLazyNonAutoClosing(SelectImpl.java:2861)
	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:509)
	at org.jooq.impl.Tools.attach(Tools.java:1516)
	at org.jooq.impl.DefaultDSLContext.fetchOne(DefaultDSLContext.java:4631)
	at org.jooq.impl.DefaultDSLContext.lambda$54(DefaultDSLContext.java:4651)
	at org.jooq.impl.Tools.attach(Tools.java:1516)
	at org.jooq.impl.DefaultDSLContext.fetchValue(DefaultDSLContext.java:4651)
	at org.jooq.test.all.testcases.MultisetTests.lambda$428(MultisetTests.java:2863)
	at org.jooq.test.all.testcases.MultisetTests.lambda$446(MultisetTests.java:2929)
	at org.jooq.test.all.testcases.MultisetTests.lambda$449(MultisetTests.java:2947)
	at org.jooq.test.all.testcases.MultisetTests.testRecordLevelListenerResults(MultisetTests.java:2986)
	at org.jooq.test.all.testcases.MultisetTests.testRecordLevelListenerResults(MultisetTests.java:2974)
	at org.jooq.test.all.testcases.MultisetTests.testMultisetEmulations(MultisetTests.java:2947)
	at org.jooq.test.all.testcases.MultisetTests.testMultisetEmulations(MultisetTests.java:2929)
	at org.jooq.test.all.testcases.MultisetTests.testDerivedTablesProjectingMultiset(MultisetTests.java:2860)
	at org.jooq.test.jOOQAbstractTest.testDerivedTablesProjectingMultiset(jOOQAbstractTest.java:5375)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: org.postgresql.util.PSQLException: ERROR: column alias_124434926.multiset does not exist
  Position: 8
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:166)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:155)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4524)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:236)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:341)
	... 50 more
```

The `ROW` test fails with:

```
org.jooq.exception.DataAccessException: SQL [select "alias_92276707"."nested" from (select row ("public"."t_book"."id", "public"."t_book"."title") from "public"."t_book") as "alias_92276707" -- SQL rendered with a free trial version of jOOQ 3.17.0-SNAPSHOT]; ERROR: column alias_92276707.nested does not exist
  Position: 8
	at org.jooq_3.17.0-SNAPSHOT.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3298)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:678)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:355)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:290)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2837)
	at org.jooq.impl.Tools.attach(Tools.java:1516)
	at org.jooq.impl.DefaultDSLContext.fetch(DefaultDSLContext.java:4598)
	at org.jooq.impl.DefaultDSLContext.fetchValues(DefaultDSLContext.java:4685)
	at org.jooq.test.all.testcases.MultisetTests.lambda$432(MultisetTests.java:2881)
	at org.jooq.test.all.testcases.MultisetTests.lambda$446(MultisetTests.java:2929)
	at org.jooq.test.all.testcases.MultisetTests.lambda$449(MultisetTests.java:2947)
	at org.jooq.test.all.testcases.MultisetTests.testRecordLevelListenerResults(MultisetTests.java:2986)
	at org.jooq.test.all.testcases.MultisetTests.testRecordLevelListenerResults(MultisetTests.java:2974)
	at org.jooq.test.all.testcases.MultisetTests.testMultisetEmulations(MultisetTests.java:2947)
	at org.jooq.test.all.testcases.MultisetTests.testMultisetEmulations(MultisetTests.java:2929)
	at org.jooq.test.all.testcases.MultisetTests.testDerivedTablesProjectingRow(MultisetTests.java:2880)
	at org.jooq.test.jOOQAbstractTest.testDerivedTablesProjectingRow(jOOQAbstractTest.java:5380)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: org.postgresql.util.PSQLException: ERROR: column alias_92276707.nested does not exist
  Position: 8
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:166)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:155)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4524)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:236)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:341)
	... 46 more
```

There are 2 problems:

- [ ] Derived tables can't currently handle unnamed expressions: https://github.com/jOOQ/jOOQ/issues/10541
- [ ] Aliasing `TableAsField` seems to be ignored in derived tables (?)

**Comment by lukaseder** [comment]
It appears that this will be fixed with:

- https://github.com/jOOQ/jOOQ/issues/579

**Comment by lukaseder** [comment]
Fixed with https://github.com/jOOQ/jOOQ/issues/579. Since that change is rather delicate, with some regression risk, I won't backport this fix.
