### ISSUE TITLE
Add support for Oracle SYS.XMLTYPE in plain SQL templates

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13670]
When running SQL/XML queries in Oracle, the resulting type is `oracle.xdb.XMLType`. But we know how to bind and read this type, so we should read our own version, instead:

```
      org.junit.ComparisonFailure: expected:<[<row a="1"/>]> but was:<[oracle.xdb.XMLType@7439940d]>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.jooq.test.util.BaseTest.assertEquals(BaseTest.java:285)
	at org.jooq.test.BaseTest.assertSame(BaseTest.java:1584)
	at org.jooq.test.BaseTest.assertSame(BaseTest.java:1598)
	at org.jooq.test.BaseTest.assertSame(BaseTest.java:1573)
	at org.jooq.test.BaseTest.assertSame(BaseTest.java:1590)
	at org.jooq.test.all.testcases.ParserTests.lambda$39(ParserTests.java:875)
	at org.jooq.test.all.testcases.ParserTests.assertions(ParserTests.java:846)
	at org.jooq.test.all.testcases.ParserTests.test(ParserTests.java:867)
	at org.jooq.test.all.testcases.ParserTests.test(ParserTests.java:858)
	at org.jooq.test.all.testcases.ParserTests.testTranslateSQLFile0(ParserTests.java:958)
	at org.jooq.test.all.testcases.ParserTests.testTranslateSQLFile_ForXML(ParserTests.java:944)
	at org.jooq.test.jOOQAbstractTest.testTranslateSQLFile_ForXML(jOOQAbstractTest.java:10117)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

**Comment by lukaseder** [comment]
A more thorough solution might be desirable in the future, e.g. in case similar issues arise with spatial types.
