### ISSUE TITLE
Code generation fails in MariaDB and MySQL when code gen user doesn't have necessary GRANTS to read the MYSQL.PROC table

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13705]
When using an arbitrary user in older MySQL version / MariaDB, who may not have `SELECT` grants on the `mysql` schema, then there might be an error like the following one:

```sql
Exception in thread "main" org.jooq.codegen.GeneratorException: Error generating code for catalog 
	at org.jooq.codegen.JavaGenerator.generate0(JavaGenerator.java:487)
	at org.jooq.codegen.AbstractGenerator.generate(AbstractGenerator.java:182)
	at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:201)
	at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:912)
	at org.jooq.codegen.GenerationTool.run(GenerationTool.java:239)
	at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:230)
	at org.toys.util.GenerateJOOQClasses.main(GenerateJOOQClasses.java:47)
Caused by: java.lang.RuntimeException: org.jooq.exception.DataAccessException: SQL [select mysql.proc.db as ROUTINE_SCHEMA, mysql.proc.name as ROUTINE_NAME, mysql.proc.comment as ROUTINE_COMMENT, mysql.proc.param_list, mysql.proc.returns, mysql.proc.type as ROUTINE_TYPE from mysql.proc where mysql.proc.db in (?) order by 1, 2, 6 -- SQL rendered with a free trial version of jOOQ 3.16.7]; (conn=3) SELECT command denied to user 'prospring6'@'172.17.0.1' for table 'proc'
	at org.jooq.meta.AbstractDatabase.onError(AbstractDatabase.java:3369)
	at org.jooq.meta.AbstractDatabase.getRoutines(AbstractDatabase.java:2494)
	at org.jooq.codegen.JavaGenerator.generateSchemaIfEmpty(JavaGenerator.java:529)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
	at org.jooq.codegen.JavaGenerator.generateCatalogIfEmpty(JavaGenerator.java:519)
	at org.jooq.codegen.JavaGenerator.generate0(JavaGenerator.java:481)
	... 6 more
Caused by: org.jooq.exception.DataAccessException: SQL [select mysql.proc.db as ROUTINE_SCHEMA, mysql.proc.name as ROUTINE_NAME, mysql.proc.comment as ROUTINE_COMMENT, mysql.proc.param_list, mysql.proc.returns, mysql.proc.type as ROUTINE_TYPE from mysql.proc where mysql.proc.db in (?) order by 1, 2, 6 -- SQL rendered with a free trial version of jOOQ 3.16.7]; (conn=3) SELECT command denied to user 'prospring6'@'172.17.0.1' for table 'proc'
	at org.jooq_3.16.7.MARIADB_10_6.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3095)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:670)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:354)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:284)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2843)
	at org.jooq.meta.mysql.MySQLDatabase.getRoutines0(MySQLDatabase.java:566)
	at org.jooq.meta.AbstractDatabase.lambda$getRoutines$20(AbstractDatabase.java:2495)
	at org.jooq.meta.AbstractDatabase.onError(AbstractDatabase.java:3359)
	... 20 more
Caused by: java.sql.SQLSyntaxErrorException: (conn=3) SELECT command denied to user 'prospring6'@'172.17.0.1' for table 'proc'
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:280)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:368)
	at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:137)
	at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:819)
	at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:758)
	at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:677)
	at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:620)
	at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:93)
	at org.mariadb.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:256)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4354)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:230)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:340)
	... 25 more

Process finished with exit code 1
```

It is easy to work around this either:

- By supplying the required grants or using the `root` user, instead
- By turning down the `onError` level from `FAIL`  to `LOG`

But for new users, the current out of the box experience can be quite harsh. Difficult to assess why this isn't working, might even be a show stopper in an evaluation.

We should:

- [ ] Maintain a list of tables that are known to cause such privilege problems in different dialects
- [ ] Intercept privilege related exceptions and warn users about missing access rights

**Comment by apatrida** [comment]
I just got hit by this with my move to 3.18.0-SNAPSHOT.  Codegen prior did not read this table.

**Comment by lukaseder** [comment]
@apatrida Did you get the same stack trace?

**Comment by apatrida** [comment]
I didn't retain it, but I can remove the permission and redo the error.
