### ISSUE TITLE
Upgrade hibernate dependency in jOOQ-meta-extensions-hibernate to 6.1.0.Final

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13721]

**Comment by lukaseder** [comment]
Hmm, it seems to have a Java 11 baseline, so this isn't suitable for our Java 8 distribution yet. Probably, we should wait.

**Comment by jokefaker** [comment]
Spring Boot 2.x will end support on 2023-11 , and 3.x use hibernate 6.x, any update about this issue ?

**Comment by lukaseder** [comment]
@jokefaker Do you have any *specific* need for an upgrade?

**Comment by DeadHeadRussell** [comment]
Hey @lukaseder I've recently run into an error trying to update to Spring Boot 3.x / hibernate 6.x in the JPADatabase.  We do have the codegen's classpath isolated so it is using `jooq-meta-extensions-hibernate`'s hibernate version.  However, we also had to update Vlad's hypersistence hibernate utils to `hypersistence-utils-hibernate-63` 3.7.5, which requires Hibernate 6.x.  We get the following error:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'org.hibernate.type.descriptor.java.ImmutableMutabilityPlan org.hibernate.type.descriptor.java.ImmutableMutabilityPlan.instance()'
        at org.hibernate.type.descriptor.java.AbstractClassJavaType.<init>(AbstractClassJavaType.java:40)
        at io.hypersistence.utils.hibernate.type.basic.internal.Iso8601MonthMonthTypeDescriptor.<init>(Iso8601MonthMonthTypeDescriptor.java:17)
        ...
        at io.hypersistence.utils.hibernate.type.HibernateTypesContributor.contribute(HibernateTypesContributor.java:111)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.handleTypes(MetadataBuildingProcess.java:391)
        ...
        at org.hibernate.boot.MetadataSources.buildMetadata(MetadataSources.java:202)
        at org.jooq.meta.extensions.jpa.JPADatabase.export(JPADatabase.java:176)
        ...
        at org.jooq.codegen.GenerationTool.main(GenerationTool.java:211)
```

I confirmed that this function exists in Hibernate 6.x but does not exist in 5.6.  Do you have any ideas on if this is something we can work around?  I might have a hack workaround but wanted to check in with you before I go too deep just to wind up with no progress..

Potential workaround:
It looks like the hypersistence library has a property to turn off registering the types that cause this issue (and we happen to not use these types).  However, we cannot provide the hypersistence property since the JPADatabase code only passes through properties that start with a few hardcoded prefixes.  I noticed the `userSettings` map is marked as package-private, so I was thinking of creating a child class of JPADatabase in the same package, hardcoding in the hypersistence setting and using the child class for the codegen.  However, this might be the first of a million little issues.

**Comment by lukaseder** [comment]
> Do you have any ideas on if this is something we can work around?

I'd say, just downgrade hypersistence for your usage of `jooq-meta-extensions-hibernate`, or maybe, use the distribution of hypersistence that still supports Hibernate 5, at least for jOOQ code generation?
https://github.com/vladmihalcea/hypersistence-utils/tree/master/hypersistence-utils-hibernate-55

Of course, you don't *have to* use jOOQ's `JPADatabase`. You can always work with actual DDL as well, which you probably generate and maintain somewhere, e.g. when exporting increments using Flyway / Liquibase. In that case, a much more reliable approach would be to use testcontainers to generate an ad-hoc schema for jOOQ code generation (and integration tests!):

https://blog.jooq.org/using-testcontainers-to-generate-jooq-code/

**Comment by DeadHeadRussell** [comment]
Thanks for recommending a better option.  I've gotten testcontainers up and running and think this will be much better for us in the long run.
