### ISSUE TITLE
ERROR: unknown function: nameconcatoid() in CockroachDBDatabase on CockroachDB 22 - Merge [#13780]

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13784]

**Comment by vvstej** [comment]
This is still happening on CRDB V22.1.16.1 using jooq 3.18.2 @lukaseder , can you please help?

Here is the stacktrace
`Exception in thread "main" org.jooq.codegen.GeneratorException: Error generating code for catalog 
	at org.jooq.codegen.JavaGenerator.generate0(JavaGenerator.java:518)
	at org.jooq.codegen.AbstractGenerator.generate(AbstractGenerator.java:191)
	at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:221)
	at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:957)
	at org.jooq.codegen.GenerationTool.run(GenerationTool.java:240)
	at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:235)
	at com.netflix.ectagsservice.crdb.codegen.utils.GenerateTablePojosFromDBSchema.main(GenerateTablePojosFromDBSchema.java:38)
Caused by: java.lang.RuntimeException: org.jooq.exception.DataAccessException: SQL [select r1.routine_schema, r1.routine_name, r1.specific_name, r1.routine_type, case when (r1.data_type = 'USER-DEFINED' and r1.type_udt_name = 'geometry') then 'geometry' when (pg_catalog.pg_proc.proargmodes && ARRAY['o','b']::"char"[]) then 'void' when r1.data_type = 'ARRAY' then (substring(r1.type_udt_name, 2) || ' ARRAY') else r1.data_type end as data_type, r1.character_maximum_length, case when (r1.numeric_precision is null and r1.data_type in ('time', 'timetz', 'time without time zone', 'time with time zone', 'timestamp', 'timestamptz', 'timestamp without time zone', 'timestamp with time zone')) then 6 else r1.numeric_precision end as numeric_precision, r1.numeric_scale, r1.type_udt_schema, case when r1.data_type = 'ARRAY' then substring(r1.type_udt_name, 2) else r1.type_udt_name end as type_udt_name, case when count(*) over (partition by r1.routine_schema, r1.routine_name) > 1 then row_number() over (partition by r1.routine_schema, r1.routine_name order by r1.specific_name) end as overload, (pg_catalog.pg_proc.prokind = 'a') as is_agg from information_schema.routines as r1 join (pg_catalog.pg_proc join pg_catalog.pg_namespace as alias_120026365 on pg_catalog.pg_proc.pronamespace = alias_120026365.oid) on (alias_120026365.nspname = r1.specific_schema and (nameconcatoid(pg_catalog.pg_proc.proname, pg_catalog.pg_proc.oid) = r1.specific_name)) left outer join pg_catalog.pg_type as rett on pg_catalog.pg_proc.prorettype = rett.oid where (r1.routine_schema in (?) and not (pg_catalog.pg_proc.proretset) and r1.data_type is distinct from 'trigger') order by r1.routine_schema asc, r1.routine_name asc, overload asc]; ERROR: unknown function: nameconcatoid()
	at org.jooq.meta.AbstractDatabase.onError(AbstractDatabase.java:3801)
	at org.jooq.meta.AbstractDatabase.getRoutines(AbstractDatabase.java:2852)
	at org.jooq.codegen.JavaGenerator.generateSchemaIfEmpty(JavaGenerator.java:560)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
	at org.jooq.codegen.JavaGenerator.generateCatalogIfEmpty(JavaGenerator.java:550)
	at org.jooq.codegen.JavaGenerator.generate0(JavaGenerator.java:512)
	... 6 more
Caused by: org.jooq.exception.DataAccessException: SQL [select r1.routine_schema, r1.routine_name, r1.specific_name, r1.routine_type, case when (r1.data_type = 'USER-DEFINED' and r1.type_udt_name = 'geometry') then 'geometry' when (pg_catalog.pg_proc.proargmodes && ARRAY['o','b']::"char"[]) then 'void' when r1.data_type = 'ARRAY' then (substring(r1.type_udt_name, 2) || ' ARRAY') else r1.data_type end as data_type, r1.character_maximum_length, case when (r1.numeric_precision is null and r1.data_type in ('time', 'timetz', 'time without time zone', 'time with time zone', 'timestamp', 'timestamptz', 'timestamp without time zone', 'timestamp with time zone')) then 6 else r1.numeric_precision end as numeric_precision, r1.numeric_scale, r1.type_udt_schema, case when r1.data_type = 'ARRAY' then substring(r1.type_udt_name, 2) else r1.type_udt_name end as type_udt_name, case when count(*) over (partition by r1.routine_schema, r1.routine_name) > 1 then row_number() over (partition by r1.routine_schema, r1.routine_name order by r1.specific_name) end as overload, (pg_catalog.pg_proc.prokind = 'a') as is_agg from information_schema.routines as r1 join (pg_catalog.pg_proc join pg_catalog.pg_namespace as alias_120026365 on pg_catalog.pg_proc.pronamespace = alias_120026365.oid) on (alias_120026365.nspname = r1.specific_schema and (nameconcatoid(pg_catalog.pg_proc.proname, pg_catalog.pg_proc.oid) = r1.specific_name)) left outer join pg_catalog.pg_type as rett on pg_catalog.pg_proc.prorettype = rett.oid where (r1.routine_schema in (?) and not (pg_catalog.pg_proc.proretset) and r1.data_type is distinct from 'trigger') order by r1.routine_schema asc, r1.routine_name asc, overload asc]; ERROR: unknown function: nameconcatoid()
	at org.jooq_3.18.0.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3465)
	at org.jooq.impl.Tools.translate(Tools.java:3453)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:765)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:371)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:301)
	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:322)
	at org.jooq.impl.SelectImpl.fetchLazyNonAutoClosing(SelectImpl.java:2862)
	at org.jooq.impl.ResultQueryTrait.collect(ResultQueryTrait.java:360)
	at org.jooq.meta.postgres.PostgresDatabase.getRoutines0(PostgresDatabase.java:1036)
	at org.jooq.meta.AbstractDatabase.lambda$getRoutines$21(AbstractDatabase.java:2853)
	at org.jooq.meta.AbstractDatabase.onError(AbstractDatabase.java:3775)
	... 20 more
Caused by: org.postgresql.util.PSQLException: ERROR: unknown function: nameconcatoid()
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:177)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4754)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:236)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:357)
	... 27 more`

**Comment by vvstej** [comment]
But this is the heading for this issue, so I assumed I was in the right place.
`ERROR: unknown function: nameconcatoid() in CockroachDBDatabase on CockroachDB 22`

**Comment by lukaseder** [comment]
Your stack trace hints at your using the `PostgresDatabase` in your code generation configuration:

```
org.jooq_3.18.0.POSTGRES.debug(Unknown Source) at org.jooq.impl.Tools.translate(Tools.java:3465) at 
...
org.jooq.meta.postgres.PostgresDatabase.getRoutines0(PostgresDatabase.java:1036) at 
```

This doesn't work. You need to use the `CockraochDBDatabase`. Can you confirm you're using the correct code generation configuration? I could have a look, if you posted it here...
