### ISSUE TITLE
ERROR: unknown function: nameconcatoid() in CockroachDBDatabase on CockroachDB 22

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13780]
jOOQ's usage of the PostgreSQL 12 `nameconcatoid()` function breaks code generation in `CockroachDBDatabase` with this exception:

```
Caused by: org.jooq.exception.DataAccessException: SQL [select r1.routine_schema, r1.routine_name, r1.specific_name, r1.routine_type, case when (r1.data_type = 'USER-DEFINED' and r1.type_udt_name = 'geometry') then 'geometry' else case when (pg_catalog.pg_proc.proargmodes && ARRAY['o','b']::"char"[]) then 'void' else r1.data_type end end as data_type, r1.character_maximum_length, case when (r1.numeric_precision is null and r1.data_type in ('time', 'timetz', 'time without time zone', 'time with time zone', 'timestamp', 'timestamptz', 'timestamp without time zone', 'timestamp with time zone')) then 6 else r1.numeric_precision end as numeric_precision, r1.numeric_scale, r1.type_udt_schema, r1.type_udt_name, case when count(*) over (partition by r1.routine_schema, r1.routine_name) > 1 then row_number() over (partition by r1.routine_schema, r1.routine_name order by r1.specific_name) end as overload, (pg_catalog.pg_proc.prokind = 'a') as is_agg from information_schema.routines as r1 join pg_catalog.pg_namespace on pg_catalog.pg_namespace.nspname = r1.specific_schema join pg_catalog.pg_proc on (pg_catalog.pg_proc.pronamespace = pg_catalog.pg_namespace.oid and (nameconcatoid(pg_catalog.pg_proc.proname, pg_catalog.pg_proc.oid) = r1.specific_name)) where (r1.routine_schema in (?) and not (pg_catalog.pg_proc.proretset) and r1.data_type is distinct from 'trigger') order by r1.routine_schema asc, r1.routine_name asc, overload asc]; ERROR: unknown function: nameconcatoid()
        at org.jooq_3.17.1.COCKROACHDB.debug(Unknown Source)
        at org.jooq.impl.Tools.translate(Tools.java:3298)
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:678)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:355)
        at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:301)
        at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:322)
        at org.jooq.impl.SelectImpl.fetchLazyNonAutoClosing(SelectImpl.java:2861)
        at org.jooq.impl.ResultQueryTrait.collect(ResultQueryTrait.java:360)
        at org.jooq.meta.postgres.PostgresDatabase.getRoutines0(PostgresDatabase.java:1013)
        at org.jooq.meta.AbstractDatabase.lambda$getRoutines$21(AbstractDatabase.java:2844)
        at org.jooq.meta.AbstractDatabase.onError(AbstractDatabase.java:3749)
        ... 20 more
Caused by: org.postgresql.util.PSQLException: ERROR: unknown function: nameconcatoid()
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
        at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:153)
        at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
        at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4524)
        at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:236)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:341)
        ... 27 more
```

The exception does not appear in our own integration tests, where the `CockroachDBDatabase` uses the `PostgresDatabase`'s check to see if `column_column_usage` is present. It used to be absent, but now is present:
https://www.cockroachlabs.com/docs/stable/information-schema.html#empty-tables

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.18.0, 3.17.2 (https://github.com/jOOQ/jOOQ/issues/13782), 3.16.8 (https://github.com/jOOQ/jOOQ/issues/13783), and 3.15.12 (https://github.com/jOOQ/jOOQ/issues/13784)

**Comment by luispollo** [comment]
Hi! I came across this error with a CockroachDB v22 container and jOOQ 3.18.6, which should have had the fix from 3.18.0 mentioned above -- is that a regression possibly? Any way to turn off that particular code path in the codegen if not critical?

**Comment by lukaseder** [comment]
Thanks for your  message, @luispollo. I cannot reproduce this problem in the latest 3.18 version. Are you sure you have *only* this jOOQ version on your classpath, and that you're using the `CockroachDBDatabase` in your code generation configuration, and not the `PostgresDatabase`?

E.g. as indicated in the stack trace, jOOQ tends to add this synthetic stack line, containing the version and dialect information:

```
Caused by: org.jooq.exception.DataAccessException: SQL [...]
        at org.jooq_3.17.1.COCKROACHDB.debug(Unknown Source)
```

In your `CockroachDBDatabase` implementation, you should see an override for the `nameconcatoid()` method, which should apply here.

```java
    @Override
    protected Condition nameconcatoid(Routines r1) {
        ...
    }
```

**Comment by luispollo** [comment]
Thanks for getting back to me! I am indeed using `PostgresDatabase`, but it works with CockroachDB v21.

**Comment by lukaseder** [comment]
> I am indeed using `PostgresDatabase`, but it works with CockroachDB v21.

We're not integration testing that combination. In the past, there have been too many subtle differences in behaviour, especially when it comes to the `information_schema` and `pg_catalog` support.

The reason why it may have worked can be seen in the `PostgresDatabase::nameconcatoid` method:

```java
    protected Condition nameconcatoid(Routines r1) {
        return is12()
              ? condition("nameconcatoid({0}, {1}) = {2}", PG_PROC.PRONAME, PG_PROC.OID, r1.SPECIFIC_NAME)
              : PG_PROC.PRONAME.concat("_").concat(PG_PROC.OID).eq(r1.SPECIFIC_NAME);
    }
```

`is12()` runs a PostgreSQL 12 compatibility check:

```java
    boolean is12() {

        // [#11325] column_column_usage was added in PostgreSQL 12 only
        if (is12 == null)
            is12 = configuredDialectIsNotFamilyAndSupports(asList(POSTGRES_12), () -> exists(table("column_column_usage")));

        return is12;
    }
```

Apparently, that accidentally worked for CockroachDB 21, but that's merely accidental. We've never tested this. I recommend using the `CockroachDBDatabase`.
