### ISSUE TITLE
DataAccessException: \u0000 cannot be converted to text

### ISSUE THREAD

**Issue by dwilches** [jOOQ/jOOQ#13903]
### Expected behavior

I have a column of type JSONB where I'm inserting an object that has a NULL character (which is valid JSON) like this:
    
        final JsonElement jsonElem = new Gson().toJsonTree(Map.of("a", "\0"));
        ctx.insertInto(TEST, TEST.OBJ).values(jsonElem).execute();

I expected the data to be inserted in Postgres just fine, I was thinking jOOQ would escape that NULL character before inserting it in the JSONB column.

### Actual behavior

jOOQ is throwing the following DataAccessException:

```
13:58:39,209 DEBUG [org.jooq.tools.LoggerListener                     ] - Exception                
org.jooq.exception.DataAccessException: SQL [insert into "mcve"."test" ("obj") values (cast(? as jsonb))]; ERROR: unsupported Unicode escape sequence
  Detail: \u0000 cannot be converted to text.
  Where: JSON data, line 1: {"a":...
	at org.jooq_3.15.8.POSTGRES.debug(Unknown Source) ~[?:?]
	at org.jooq.impl.Tools.translate(Tools.java:2997) ~[jooq-3.15.8.jar:?]
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:639) ~[jooq-3.15.8.jar:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:354) [jooq-3.15.8.jar:?]
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:111) [jooq-3.15.8.jar:?]
	at org.jooq.mcve.test.java.JavaTest.mcveTest(JavaTest.java:49) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.Suite.runChild(Suite.java:128) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.Suite.runChild(Suite.java:27) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) [junit-4.13.2.jar:4.13.2]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.13.2.jar:4.13.2]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69) [junit-rt.jar:?]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11) [idea_rt.jar:?]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54) [junit-rt.jar:?]
Caused by: org.postgresql.util.PSQLException: ERROR: unsupported Unicode escape sequence
  Detail: \u0000 cannot be converted to text.
  Where: JSON data, line 1: {"a":...
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553) ~[postgresql-42.2.20.jre7.jar:42.2.20.jre7]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285) ~[postgresql-42.2.20.jre7.jar:42.2.20.jre7]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323) ~[postgresql-42.2.20.jre7.jar:42.2.20.jre7]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481) ~[postgresql-42.2.20.jre7.jar:42.2.20.jre7]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401) ~[postgresql-42.2.20.jre7.jar:42.2.20.jre7]
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164) ~[postgresql-42.2.20.jre7.jar:42.2.20.jre7]
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:153) ~[postgresql-42.2.20.jre7.jar:42.2.20.jre7]
```
 

### Steps to reproduce the problem

Run the Java test in the MCVE: https://github.com/dwilches/jOOQ-mcve

In that MCVE I have a `JsonbConverter` ([here](https://github.com/dwilches/jOOQ-mcve/blob/master/jOOQ-mcve-java/src/main/java/org/jooq/mcve/MyJsonbConverter.java)), I wonder if I have a problem there or if it's something inside of jOOQ.

### Versions

- jOOQ: 3.15.8
- Java: 11
- Database (include vendor): Postgres 11
- OS: Ubuntu 22.04
- JDBC Driver (include name if unofficial driver): org.postgresql.postgresql 42.2.20.jre7

**Comment by lukaseder** [comment]
Thanks for your report. How does one encode the `NULL` character in PostgreSQL, in general? Try this, for example, with PG directly:

```sql
select '{"a":"\u0000"}'::jsonb;
```

Result:

>

Background:

- https://www.commandprompt.com/blog/null-characters-workarounds-arent-good-enough/
- https://stackoverflow.com/q/28813409/521799
- https://dba.stackexchange.com/a/166167/2512

I don't think this is a jOOQ problem. Note, the `\u0000` encoding stems from Gson, and doesn't have much to do with JSON directly. The `NULL` character is encoded within the JSON document. It's not actually a binary `NULL` byte within the string.

> In that MCVE I have a `JsonbConverter` ([here](https://github.com/dwilches/jOOQ-mcve/blob/master/jOOQ-mcve-java/src/main/java/org/jooq/mcve/MyJsonbConverter.java)), I wonder if I have a problem there or if it's something inside of jOOQ.

This is something different. `JsonNull.INSTANCE` represents the JSON `null` *value*, not the binary null byte. For example, this is valid JSON (in PG):

```sql
select 
  'null'::jsonb,
  '[null]'::jsonb,
  '{"a":null}'::jsonb
```
