### ISSUE TITLE
"Ambiguous match found" warning is logged multiple times

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13996]
A simple piece of code like this:

```java
Record r = ctx.fetchOne("select a.id, 2 as id, 3 as id from (values (1)) a (id)");
println(r.getValue("ID"));
```

Produces the following output:

```
15:46:34,336 DEBUG [LoggerListener                ] - Executing query          : select a.id, 2 as id, 3 as id from (values (1)) a (id)
15:46:34,381 DEBUG [LoggerListener                ] - Fetched result           : +----+----+----+
15:46:34,381 DEBUG [LoggerListener                ] -                          : |  ID|  ID|  ID|
15:46:34,381 DEBUG [LoggerListener                ] -                          : +----+----+----+
15:46:34,381 DEBUG [LoggerListener                ] -                          : |   1|   2|   3|
15:46:34,381 DEBUG [LoggerListener                ] -                          : +----+----+----+
15:46:34,381 DEBUG [LoggerListener                ] - Fetched row(s)           : 1
15:46:34,384  INFO [FieldsImpl                    ] - Ambiguous match found for ID. Both "PUBLIC"."VALUES"."ID" and "ID" match.
java.sql.SQLWarning: null
	at org.jooq.impl.FieldsImpl.field0(FieldsImpl.java:325) ~[classes/:?]
	at org.jooq.impl.FieldsImpl.indexOf(FieldsImpl.java:438) ~[classes/:?]
	at org.jooq.impl.AbstractRow.indexOf(AbstractRow.java:384) ~[classes/:?]
	at org.jooq.impl.Tools.indexOrFail(Tools.java:2081) ~[classes/:?]
	at org.jooq.impl.AbstractRecord.get(AbstractRecord.java:365) ~[classes/:?]
	at org.jooq.impl.AbstractRecord.getValue(AbstractRecord.java:1301) ~[classes/:?]
	at org.jooq.testscripts.JDBC.main(JDBC.java:54) ~[test-classes/:?]
15:46:34,384  INFO [FieldsImpl                    ] - Ambiguous match found for ID. Both "PUBLIC"."VALUES"."ID" and "ID" match.
java.sql.SQLWarning: null
	at org.jooq.impl.FieldsImpl.field0(FieldsImpl.java:325) ~[classes/:?]
	at org.jooq.impl.FieldsImpl.indexOf(FieldsImpl.java:438) ~[classes/:?]
	at org.jooq.impl.AbstractRow.indexOf(AbstractRow.java:384) ~[classes/:?]
	at org.jooq.impl.Tools.indexOrFail(Tools.java:2081) ~[classes/:?]
	at org.jooq.impl.AbstractRecord.get(AbstractRecord.java:365) ~[classes/:?]
	at org.jooq.impl.AbstractRecord.getValue(AbstractRecord.java:1301) ~[classes/:?]
	at org.jooq.testscripts.JDBC.main(JDBC.java:54) ~[test-classes/:?]
15:46:34,393  INFO [FieldsImpl                    ] - Ambiguous match found for ID. Both "PUBLIC"."VALUES"."ID" and "ID" match.
java.sql.SQLWarning: null
	at org.jooq.impl.FieldsImpl.field0(FieldsImpl.java:325) ~[classes/:?]
	at org.jooq.impl.FieldsImpl.indexOf(FieldsImpl.java:438) ~[classes/:?]
	at org.jooq.impl.AbstractRow.indexOf(AbstractRow.java:384) ~[classes/:?]
	at org.jooq.impl.Tools.indexOrFail(Tools.java:2081) ~[classes/:?]
	at org.jooq.impl.AbstractRecord.get(AbstractRecord.java:365) ~[classes/:?]
	at org.jooq.impl.AbstractRecord.getValue(AbstractRecord.java:1301) ~[classes/:?]
	at org.jooq.testscripts.JDBC.main(JDBC.java:54) ~[test-classes/:?]
15:46:34,393  INFO [FieldsImpl                    ] - Ambiguous match found for ID. Both "PUBLIC"."VALUES"."ID" and "ID" match.
java.sql.SQLWarning: null
	at org.jooq.impl.FieldsImpl.field0(FieldsImpl.java:325) ~[classes/:?]
	at org.jooq.impl.FieldsImpl.indexOf(FieldsImpl.java:438) ~[classes/:?]
	at org.jooq.impl.AbstractRow.indexOf(AbstractRow.java:384) ~[classes/:?]
	at org.jooq.impl.Tools.indexOrFail(Tools.java:2081) ~[classes/:?]
	at org.jooq.impl.AbstractRecord.get(AbstractRecord.java:365) ~[classes/:?]
	at org.jooq.impl.AbstractRecord.getValue(AbstractRecord.java:1301) ~[classes/:?]
	at org.jooq.testscripts.JDBC.main(JDBC.java:54) ~[test-classes/:?]
1
```

There's a loop that unnecessarily prints the warning 4x:

```java
private final <U> U field0(String fieldName, FieldOrIndex<U> result) {
    if (fieldName == null)
        return result.resultNull();

    Field<?> columnMatch = null;
    int indexMatch = -1;

    for (int i = 0; i < fields.length; i++) {
        Field<?> f = fields[i];

        if (f.getName().equals(fieldName)) {
            if (columnMatch == null) {
                columnMatch = f;
                indexMatch = i;
            }

            // [#4476] [#4477] [#5046] This might be unintentional from a user
            // perspective, e.g. when ambiguous ID columns are present.
            else {
                log.info("Ambiguous match found for " + fieldName + ". Both " + columnMatch + " and " + f + " match.", new SQLWarning());
            }
        }
    }

    return result.result(columnMatch, indexMatch);
}
```

**Comment by lukaseder** [comment]
At the same time, this produces no such warning:

```java
Record r = ctx.fetchOne("select 2 as id, 3 as id, a.id from a");
println(r.getValue(name( "ID")));
```

**Comment by lukaseder** [comment]
All the implementations that use these `Fields::field` methods should also have their javadoc updated, to link to the relevant `Fields::field` method. E.g. `Result::intoMap`

**Comment by lukaseder** [comment]
A recent fix seems to have improved this:

```
13:18:37,793 DEBUG [LoggerListener                ] - Fetched result           : +----+----+----+
13:18:37,793 DEBUG [LoggerListener                ] -                          : |  id|  id|  id|
13:18:37,793 DEBUG [LoggerListener                ] -                          : +----+----+----+
13:18:37,794 DEBUG [LoggerListener                ] -                          : |   1|   2|   3|
13:18:37,794 DEBUG [LoggerListener                ] -                          : +----+----+----+
13:18:37,794 DEBUG [LoggerListener                ] - Fetched row(s)           : 1
13:18:37,796  INFO [FieldsImpl                    ] - Ambiguous match found for id. Both "id" and "id" match.
java.sql.SQLWarning: null
	at org.jooq.impl.FieldsImpl.field0(FieldsImpl.java:350) [classes/:?]
	at org.jooq.impl.FieldsImpl.indexOf(FieldsImpl.java:463) [classes/:?]
	at org.jooq.impl.AbstractRow.indexOf(AbstractRow.java:419) [classes/:?]
	at org.jooq.impl.Tools.indexOrFail(Tools.java:2170) [classes/:?]
	at org.jooq.impl.AbstractRecord.get(AbstractRecord.java:365) [classes/:?]
	at org.jooq.impl.AbstractRecord.getValue(AbstractRecord.java:1308) [classes/:?]
	at org.jooq.testscripts.JDBC.main(JDBC.java:48) [test-classes/:?]
13:18:37,800  INFO [FieldsImpl                    ] - Ambiguous match found for id. Both "id" and "id" match.
java.sql.SQLWarning: null
	at org.jooq.impl.FieldsImpl.field0(FieldsImpl.java:350) [classes/:?]
	at org.jooq.impl.FieldsImpl.indexOf(FieldsImpl.java:463) [classes/:?]
	at org.jooq.impl.AbstractRow.indexOf(AbstractRow.java:419) [classes/:?]
	at org.jooq.impl.Tools.indexOrFail(Tools.java:2170) [classes/:?]
	at org.jooq.impl.AbstractRecord.get(AbstractRecord.java:365) [classes/:?]
	at org.jooq.impl.AbstractRecord.getValue(AbstractRecord.java:1308) [classes/:?]
	at org.jooq.testscripts.JDBC.main(JDBC.java:48) [test-classes/:?]
1
```

There are now only 2 entries (given that there are 2 matches).
