### ISSUE TITLE
Plain SQL queries should read java.sql.Struct values into org.jooq.Record

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14040]
There's a test that currently fails in the Oracle test suit where we fetch a `ResultSet` that has been retrieved from a JDBC query and assert equality with a plain SQL query.

Both results contain an `oracle.sql.STRUCT` reference, which can't be compared because it doesn't implement `equals()` and `hashCode()`, nor `toString()` for that matter:

```
java.lang.AssertionError: expected:<+----+----------+---------+-------------+-------------+-------------------------+
|  ID|FIRST_NAME|LAST_NAME|DATE_OF_BIRTH|YEAR_OF_BIRTH|ADDRESS                  |
+----+----------+---------+-------------+-------------+-------------------------+
|   1|George    |Orwell   |1903-06-25   |         1903|oracle.sql.STRUCT@c353e4d|
|   2|Paulo     |Coelho   |1947-08-24   |         1947|oracle.sql.STRUCT@511d6ac|
+----+----------+---------+-------------+-------------+-------------------------+
> but was:<+----+----------+---------+-------------+-------------+--------------------------+
|  ID|FIRST_NAME|LAST_NAME|DATE_OF_BIRTH|YEAR_OF_BIRTH|ADDRESS                   |
+----+----------+---------+-------------+-------------+--------------------------+
|   1|George    |Orwell   |1903-06-25   |         1903|oracle.sql.STRUCT@2c2bcd35|
|   2|Paulo     |Coelho   |1947-08-24   |         1947|oracle.sql.STRUCT@56858ed2|
+----+----------+---------+-------------+-------------+--------------------------+
>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.jooq.test.util.BaseTest.assertEquals(BaseTest.java:295)
	at org.jooq.test.all.testcases.FetchTests.testFetchResultSet(FetchTests.java:1736)
	at org.jooq.test.jOOQAbstractTest.testFetchResultSet(jOOQAbstractTest.java:2579)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

By default, jOOQ fetches all JDBC types into an equivalent jOOQ type, without any JDBC dependency, or open `Connection`, etc. The `STRUCT` type as such isn't really very useful. It would be better to have a `Record` type available (or `UDTRecord`, but those can't be generated on the fly at runtime)

**Comment by lukaseder** [comment]
We've already done this for lobs: https://github.com/jOOQ/jOOQ/issues/2534

**Comment by lukaseder** [comment]
It seems the test here is flaky. When executed on its own, then the test passes. When executed in the context of the entire test suite, it fails.

**Comment by lukaseder** [comment]
The flakiness seems to come from the internal static type registry (again). The `UDT` type registers itself in the single test execution. Perhaps this registration gets overwritten somehow.
