### ISSUE TITLE
Misleading parser error message when table list has excess comma

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14091]
When trying to parse this wrong query:

```sql
SELECT * 
FROM a, b, 
WHERE b.x = c
```

There's a misleading error message:

```
Unsupported query type: [3:8] SELECT * 
FROM a, b, 
WHERE b[*].x = c
```

**Comment by lukaseder** [comment]
The problem is the `WHERE` clause. Without it, there is no problem:

```
org.jooq.impl.ParserException: Identifier expected: [1:20] select * from a, b,[*]
	at org.jooq.impl.DefaultParseContext.expected(ParserImpl.java:14700)
	at org.jooq.impl.DefaultParseContext.parseName(ParserImpl.java:12351)
	at org.jooq.impl.DefaultParseContext.parseTableName(ParserImpl.java:12232)
	at org.jooq.impl.DefaultParseContext.parseTableFactor(ParserImpl.java:7154)
	at org.jooq.impl.DefaultParseContext.parseLateral(ParserImpl.java:6932)
	at org.jooq.impl.DefaultParseContext.parseJoinedTable(ParserImpl.java:7565)
	at org.jooq.impl.DefaultParseContext.parseTable(ParserImpl.java:6925)
	at org.jooq.impl.DefaultParseContext.parseList(ParserImpl.java:13553)
	at org.jooq.impl.DefaultParseContext.parseList(ParserImpl.java:13540)
	at org.jooq.impl.DefaultParseContext.parseQueryPrimary(ParserImpl.java:1838)
	at org.jooq.impl.DefaultParseContext.parseQueryTerm(ParserImpl.java:1690)
	at org.jooq.impl.DefaultParseContext.parseQueryExpressionBody(ParserImpl.java:1656)
	at org.jooq.impl.DefaultParseContext.parseSelect(ParserImpl.java:1416)
	at org.jooq.impl.DefaultParseContext.parseSelect(ParserImpl.java:1411)
	at org.jooq.impl.DefaultParseContext.parseQuery(ParserImpl.java:1225)
	at org.jooq.impl.DefaultParseContext.lambda$parseQuery0$2(ParserImpl.java:968)
	at org.jooq.impl.DefaultParseContext.wrap(ParserImpl.java:14927)
	at org.jooq.impl.DefaultParseContext.parseQuery0(ParserImpl.java:968)
	at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:779)
	at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:774)
	at org.jooq.impl.AbstractParserTest.failAll(AbstractParserTest.java:229)
	at org.jooq.impl.AbstractParserTest.failAllQueries(AbstractParserTest.java:256)
	at org.jooq.impl.ParserErrorTest.testTrailingCommaTableList(ParserErrorTest.java:72)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

But with `WHERE`, the parser thinks that we're looking at a table name. This is a general problem of our parser, which is a hand-written, recursive descent parser that runs everything in a single pass. There are no actual keywords, tokens, or whatever, so all actual keywords are purely contextual.

This is great when we support syntax that is supported by some RDBMS that are like this as well, but makes a lot of error messages weirder, especially because we support T-SQL's optional `;`, so the parser thinks the next query starts at `b.x`.

If we parse only a single query, then we can tell that the clause is unsupported:

```
Unexpected clause: [1:28] select * from a, b, where a[*].x = 1
```

This is already a bit better.

I'm not sure how to best fix this...
