### ISSUE TITLE
Cannot pass null values as arguments for associative arrays

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14097]
A procedure accepting associative array types should accept `null` arguments. Currently, this isn't possible:

```
java.lang.ClassCastException: class org.jooq.impl.Val cannot be cast to class org.jooq.impl.AssociativeArrayConstant (org.jooq.impl.Val and org.jooq.impl.AssociativeArrayConstant are in unnamed module of loader 'app')
	at org.jooq_3.18.0-SNAPSHOT.ORACLE21C.debug(Unknown Source) ~[?:?]
	at org.jooq.impl.AbstractRoutine.bind1(AbstractRoutine.java:715) ~[classes/:?]
	at org.jooq.impl.AbstractRoutine.bind0(AbstractRoutine.java:668) ~[classes/:?]
	at org.jooq.impl.AbstractRoutine.accept(AbstractRoutine.java:618) ~[classes/:?]
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:258) ~[classes/:?]
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:68) ~[classes/:?]
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:346) ~[classes/:?]
	at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:555) ~[classes/:?]
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:392) ~[classes/:?]
	at org.jooq.impl.Tools.attach(Tools.java:1581) ~[classes/:?]
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:372) ~[classes/:?]
	at org.jooq.test.oracle.generatedclasses.test.packages.Srb.abc(Srb.java:48) ~[test-classes/:?]
	at org.jooq.testscripts.JDBC.main(JDBC.java:81) ~[test-classes/:?]
Exception in thread "main" java.lang.ClassCastException: class org.jooq.impl.Val cannot be cast to class org.jooq.impl.AssociativeArrayConstant (org.jooq.impl.Val and org.jooq.impl.AssociativeArrayConstant are in unnamed module of loader 'app')
	at org.jooq_3.18.0-SNAPSHOT.ORACLE21C.debug(Unknown Source)
	at org.jooq.impl.AbstractRoutine.bind1(AbstractRoutine.java:715)
	at org.jooq.impl.AbstractRoutine.bind0(AbstractRoutine.java:668)
	at org.jooq.impl.AbstractRoutine.accept(AbstractRoutine.java:618)
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:258)
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:68)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:346)
	at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:555)
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:392)
	at org.jooq.impl.Tools.attach(Tools.java:1581)
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:372)
	at org.jooq.test.oracle.generatedclasses.test.packages.Srb.abc(Srb.java:48)
	at org.jooq.testscripts.JDBC.main(JDBC.java:81)
```

It's not possible in PL/SQL either:

```sql
DECLARE
  TYPE t IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
  PROCEDURE p (i t) IS BEGIN dbms_output.put_line(i.count); END;
BEGIN
  p(null);
END;
```

Producing:

```
SQL Error [6550] [65000]: ORA-06550: line 5, column 5:
PLS-00567: cannot pass NULL to a NOT NULL constrained formal parameter
ORA-06550: line 5, column 3:
PL/SQL: Statement ignored
```

This works:

```sql
DECLARE
  TYPE t IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
  PROCEDURE p (i t) IS BEGIN dbms_output.put_line(i.count); END;
BEGIN
  p(CAST(null as t));
END;
```

But that's just the same as passing an empty table:

```sql
DECLARE
  TYPE t IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
  PROCEDURE p (i t) IS BEGIN dbms_output.put_line(i.count); END;
BEGIN
  p(t());
END;
```

Perhaps, we should patch the argument to become an empty table, although, I'm not entirely convinced this is the right approach as I might be overlooking an edge case where `NULL` and `T()` are not the same thing.

**Comment by lukaseder** [comment]
Hmm, yes it's a more generic bug, not just related to associative arrays. The logic in `DSL.val()` only uses `instanceof` checks on the `value`, not `Class::isAssignableFrom` checks on the `DataType`:

```java
    public static <T> Param<T> val(Object value, DataType<T> type) {

        // Advanced data types have dedicated constant types
        if (value instanceof QualifiedRecord)
            return new QualifiedRecordConstant((QualifiedRecord<?>) value);
        /* [pro] */
        else if (value instanceof ArrayRecord<?> a)
            return new ArrayConstant(a);
        else if (value instanceof AssociativeArrayRecord<?, ?> a)
            return new AssociativeArrayConstant(a);
        /* [/pro] */

        // The default behaviour
        T converted = type.convert(value);
        return new Val<>(converted, mostSpecific(converted, type));
    }
```

That's why a `Val` is instanciated, instead of an `AssociativeArrayConstant`. But I still think there are cases where `NULL` and an empty table/record aren't the same thing. E.g. in PostgreSQL:

```sql
select null::t is distinct from row(null)::t
```

Yields `true`. It may be different in Oracle...

**Comment by lukaseder** [comment]
This is really just about associative arrays... This doesn't work:

```sql
DECLARE
  TYPE tt IS TABLE OF NUMBER(10) INDEX BY PLS_INTEGER;
  t tt := null;
BEGIN
  NULL;
END;
/
```

Raising

```
ORA-06550: Zeile 3, Spalte 11:
PLS-00382: Dieser Ausdruck hat den falschen Typ
ORA-06550: Zeile 0, Spalte 0:
PL/SQL: Compilation unit analysis terminated
06550. 00000 -  "line %s, column %s:\n%s"
*Cause:    Usually a PL/SQL compilation error.
*Action:
```

But this works just fine:

```sql
DECLARE
  TYPE tt IS TABLE OF NUMBER(10);
  t tt := null;
BEGIN
  NULL;
END;
/
```

And so does this:

```sql
CREATE TYPE tt AS TABLE OF NUMBER(10);
/

DECLARE
  t tt := null;
BEGIN
  NULL;
END;
/
```

I feel this is a flaw in the PL/SQL language, which might be fixed in the future, in case of which any current workaround implemented in jOOQ (e.g. an explicit `CAST(NULL AS TT)`) will have to be removed again once PL/SQL is fixed?

**Comment by lukaseder** [comment]
On the other hand, the associative array is the only possible cast target for `NULL`. This is valid:

```sql
DECLARE
  TYPE tt IS TABLE OF NUMBER(10) INDEX BY PLS_INTEGER;
  t tt := CAST(NULL AS TT);
BEGIN
  NULL;
END;
/
```

Both of these fail:

```sql
DECLARE
  TYPE tt IS TABLE OF NUMBER(10);
  t tt := CAST(NULL AS TT);
BEGIN
  NULL;
END;
/

```

With 

```
ORA-06550: Zeile 3, Spalte 16:
PLS-00382: Dieser Ausdruck hat den falschen Typ
ORA-06550: Zeile 0, Spalte 0:
PL/SQL: Compilation unit analysis terminated
06550. 00000 -  "line %s, column %s:\n%s"
*Cause:    Usually a PL/SQL compilation error.
*Action:
```

**Comment by lukaseder** [comment]
After giving this some additional thought, I think it's unlikely for PL/SQL to change the behaviour of `CAST(NULL AS TT)`. A `NULL` associative array seems to be equivalent to an empty one.

After all, it's documented this way, here:
https://docs.oracle.com/en/database/oracle/oracle-database/19/lnpls/plsql-collections-and-records.html#GUID-7E9034D5-0D33-43A1-9012-918350FE148C

<img width="832" alt="image" src="https://user-images.githubusercontent.com/734593/196979033-25db337d-90dc-4b73-8dcc-0f78c25149b5.png">

This is unlikely to change, so it's safe to say that a Java `null` value should be bound as equivalent to an empty associative array, i.e. the uninitialised value.

**Comment by lukaseder** [comment]
An important detail is when we have a `null` procedure parameter value that is defaulted, and hasn't been set by the user explicitly. In that case, we must implement the `DEFAULT` behaviour, not the `NULL` (empty) behaviour.
