### ISSUE TITLE
Cannot pass null values as arguments for PL/SQL RECORD types

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14112]
Related to https://github.com/jOOQ/jOOQ/issues/14097, this is less controversial than https://github.com/jOOQ/jOOQ/issues/14097, because the behaviour of a `NULL` record in PL/SQL is defined, as can be seen here:

```sql
SET SERVEROUTPUT ON
DECLARE
  TYPE r IS RECORD (i VARCHAR2(10) DEFAULT 'A');
  PROCEDURE p (i r := r()) IS BEGIN
    dbms_output.put_line(NVL(i.i, 'NULL'));
  END;
BEGIN
  p();
  p(null);
END;
```

This prints:

```
A
NULL
```

A similar `ClassCastException` as in #14097 is thrown, currently:

```
java.lang.ClassCastException: class org.jooq.impl.Val cannot be cast to class org.jooq.impl.QualifiedRecordConstant (org.jooq.impl.Val and org.jooq.impl.QualifiedRecordConstant are in unnamed module of loader 'app')
	at org.jooq_3.18.0-SNAPSHOT.ORACLE21C.debug(Unknown Source)
	at org.jooq.impl.AbstractRoutine.toSQLBegin(AbstractRoutine.java:1076)
	at org.jooq.impl.AbstractRoutine.toSQL0(AbstractRoutine.java:778)
	at org.jooq.impl.AbstractRoutine.accept(AbstractRoutine.java:617)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:346)
	at org.jooq.impl.DefaultDSLContext.render(DefaultDSLContext.java:755)
	at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:540)
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:451)
	at org.jooq.impl.Tools.attach(Tools.java:1581)
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:373)
	at org.jooq.test.oracle.generatedclasses.test.packages.PlsObjects.plsFRdefault(PlsObjects.java:1190)
	at org.jooq.test.OracleTest.testOracleRecordDefaultsInFlatRecords(OracleTest.java:4991)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

**Comment by lukaseder** [comment]
Note that a `RECORD` itself cannot be `NULL` in Oracle, but assigning `NULL` to a record variable assigns `NULL` to all of its attributes, explicitly.

**Comment by lukaseder** [comment]
Fix depends on a variety of improvements from jOOQ 3.18, so I won't backport.
