### ISSUE TITLE
"Cannot commit when autoCommit is enabled" when multiple transactions are running simultaneously

### ISSUE THREAD

**Issue by SebastianKG** [jOOQ/jOOQ#14115]
### Your question

# The problem

When I make multiple simultaneous requests to my Ktor server, and the resulting transactional database queries are run, I see the error `org.postgresql.util.PSQLException: Cannot commit when autoCommit is enabled` is returned. All transactions fail and throw exceptions. The queries do include both reads and writes. Is PGSimpleDataSource appropriately threadsafe for Ktor to run multiple transactions in parallel? Is there another way to set up the datasource/connection to avoid this type of issue? Thank you for your help.

# Context

## Setting up jooq DSLContext

```
val config = PostgresConfig.fromEnv()
val ds = PGSimpleDataSource()
ds.setURL(config.uri)
config.sslCert?.let {
    ds.ssl = true
    ds.sslRootCert = it
}
ds.user = config.username
ds.password = config.password
val db = DSL.using(ds.connection)
```
## The resulting error

```
2022-10-20 06:56:28.328 [eventLoopGroupProxy-4-1] ERROR ktor.application - Unhandled: POST - /api/questions
org.postgresql.util.PSQLException: Cannot commit when autoCommit is enabled.
	at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:872)
	at org.jooq.impl.DefaultConnectionProvider.commit(DefaultConnectionProvider.java:98)
	at org.jooq.impl.DefaultTransactionProvider.commit(DefaultTransactionProvider.java:174)
	at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:554)
	at org.jooq.impl.Tools$3$1.block(Tools.java:5589)
	at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3137)
	at org.jooq.impl.Tools$3.get(Tools.java:5586)
	at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:598)
	at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:522)
	at com.memo.infra.services.Neo4jQuestionService.newTextualQuestion(PostgresQuestionService.kt:195)
	at com.memo.infra.services.Neo4jQuestionService.create(PostgresQuestionService.kt:39)
	at com.memo.ApplicationKt$routes$1$2$3.invokeSuspend(Application.kt:137)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
```

### jOOQ Version

jOOQ 3.16.6

### Database product and version

PostgreSQL 14.5 on x86_64-pc-linux-gnu, compiled by gcc, a b58be71e41 p 4c988a90c7, 64-bit

### Java Version

openjdk 11 2018-09-25

### OS Version

Ubuntu 20.04.4 LTS

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.4.0

**Comment by lukaseder** [comment]
Thanks for your message. I've never used any JDBC driver's built-in `DataSource`, having seen them always as a "dummy" implementation for quick interoperability (e.g. testing). In the past, I've usually worked e.g. with WLS's own `DataSource` or hikari.

You can look at the code of `PGSimpleDataSource`. It's not a connection pool. It creates a new `Connection` every time you call `DataSource::getConnection`. So, concurrency doesn't seem to be the problem here. At least not from the DS perspective.

Maybe, if you can share a more complete example?

**Comment by SebastianKG** [comment]
Hi @lukaseder, thank you for your prompt reply. I have put together a more complete example, please see below:

`Main.kt`
``` kotlin
// ...

object ExampleApp {
    @JvmStatic
    fun main(args: Array<String>) {
        val config = PostgresConfig.fromEnv()
        val ds = HikariDataSource()
        ds.jdbcUrl = config.uri
        ds.username = config.username
        ds.password = config.password
        val db = DSL.using(ds.connection, Settings().withExecuteLogging(false))

        embeddedServer(Netty, 3472) {
            install(ContentNegotiation) {
                jackson {
                    enable(SerializationFeature.INDENT_OUTPUT)
                }
            }

            routing {
                static("/") {
                    staticRootFolder = File("static")
                    files(".")
                }

                post("test") {
                    val result = db.transactionResult { txConfig ->
                        val tx = txConfig.dsl()
                        val userId = tx
                            .insertInto(USERS, USERS.EXTERNAL_ID, USERS.USERNAME)
                            .values(UUID.randomUUID().toString(), UUID.randomUUID().toString())
                            .returning(USERS.EXTERNAL_ID).fetchOne()!!.value1()
                        val topicTitles = tx
                            .selectFrom(TOPICS)
                            .limit(300)
                            .fetch()
                            .map { it.title }
                        Pair(userId, topicTitles)
                    }

                    call.respond(result)
                }
            }
        }.start(true)
    }
}
```
`build.gradle.kts`
``` kotlin
// ...

val ktorVersion: String by project
val kotlinVersion: String by project

// ...

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion")
    implementation("io.ktor:ktor-server-netty:$ktorVersion")
    implementation("ch.qos.logback:logback-classic:$logbackVersion")
    implementation("io.ktor:ktor-server-core:$ktorVersion")
    implementation("io.ktor:ktor-locations:$ktorVersion")
    implementation("io.ktor:ktor-metrics:$ktorVersion")
    implementation("io.ktor:ktor-auth:$ktorVersion")
    implementation("io.ktor:ktor-auth-jwt:$ktorVersion")
    implementation("io.ktor:ktor-jackson:$ktorVersion")
    implementation("io.ktor:ktor-client-core:$ktorVersion")
    implementation("io.ktor:ktor-client-core-jvm:$ktorVersion")
    implementation("io.ktor:ktor-client-apache:$ktorVersion")
    implementation("io.ktor:ktor-client-auth-jvm:$ktorVersion")
    implementation("io.ktor:ktor-client-json-jvm:$ktorVersion")
    implementation("io.ktor:ktor-client-gson:$ktorVersion")
    implementation("io.ktor:ktor-client-logging-jvm:$ktorVersion")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.9.8")
    implementation("org.jooq:jooq:3.16.6")
    implementation("org.flywaydb:flyway-core:8.5.12")
    implementation("org.jooq:jooq-meta:3.16.6")
    implementation("org.jooq:jooq-codegen-maven:3.16.6")
    implementation("org.testcontainers:postgresql:1.17.2")
    implementation("org.postgresql:postgresql:42.4.0")
    implementation("com.zaxxer:HikariCP:5.0.1")
}

//...
```

`gradle.properties`
```
ktorVersion=1.6.7
kotlin.code.style=official
kotlinVersion=1.6.10
```

`static/index.html`
``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
    <script>
        const fetchIt = () => window.fetch("/test", {
            method: "POST"
        }).then(it => it.json());

        Promise.allSettled([
            fetchIt(),
            fetchIt(),
            fetchIt(),
            fetchIt(),
            fetchIt(),
            fetchIt(),
            fetchIt(),
            fetchIt(),
            fetchIt(),
            fetchIt(),
            fetchIt(),
            fetchIt()
        ]).then(console.log).catch(console.log);
    </script>
</head>
<body>
    <p>Testing...</p>
</body>
</html>
```

`migration.sql`
``` sql
CREATE SCHEMA IF NOT EXISTS memo;

CREATE TABLE IF NOT EXISTS memo.topics(
    id BIGSERIAL PRIMARY KEY,
    uri TEXT UNIQUE,
    title TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS memo.users(
    external_id TEXT PRIMARY KEY,
    username TEXT NOT NULL
);

-- ...
```

`JooqGenerator.kt`
``` kotlin
import org.flywaydb.core.Flyway
import org.jooq.codegen.GenerationTool
import org.jooq.meta.jaxb.Configuration
import org.jooq.meta.jaxb.Database
import org.jooq.meta.jaxb.Generator
import org.jooq.meta.postgres.PostgresDatabase
import org.postgresql.ds.PGSimpleDataSource
import org.testcontainers.containers.PostgreSQLContainer
import java.sql.SQLException


object JooqGenerator {
    @JvmStatic
    fun main(args: Array<String>) {
        val postgres = PostgreSQLContainer("postgres:alpine3.16")
        postgres.start()

        val ds = PGSimpleDataSource()
        ds.setURL(postgres.jdbcUrl)
        ds.user = postgres.username
        ds.password = postgres.password

        val flywayConfig =
            org.flywaydb.core.api.configuration.FluentConfiguration()
                .dataSource(ds)
                .locations("classpath:migrations")
        val flyway = Flyway(flywayConfig)
        flyway.migrate()

        try {
            ds.connection.use { c ->
                val configuration: Configuration = Configuration()
                    .withGenerator(
                        Generator()
                            .withDatabase(
                                Database()
                                    .withName(PostgresDatabase::class.java.canonicalName)
                                    .withIncludes(".*")
                                    .withExcludes("")
                                    .withInputSchema("memo")
                            )
                            .withTarget(
                                org.jooq.meta.jaxb.Target()
                                    .withPackageName("com.memo.generated")
                                    .withDirectory("back/src")
                            )
                    )
                val tool = GenerationTool()
                tool.setConnection(c)
                tool.run(configuration)
            }
        } catch (e: SQLException) {
            e.printStackTrace()
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
}
```

`.env`
```
POSTGRES_PASSWORD=password
POSTGRES_URI=jdbc:postgresql://localhost:5432/memo
POSTGRES_USERNAME=username
```

**Comment by SebastianKG** [comment]
Now, that isn't _quite_ a runnable set of files, but it should be enough to be complete for reading purposes. I can probably slap together a whole repo if desired.

# (In Theory) Repro Steps

1. Run `JooqGenerator.kt`
2. Actually run the migration against the local database, and insert at least 300 entries in memo.topics
3. Run `Main.kt`
4. Go to `localhost:3472/index.html` in the browser

Then, in the browser console you should see that only some % of the promises were fulfilled, and in the Kotlin logs you should see a whole bunch of 

```
org.jooq.exception.DataAccessException: Cannot commit transaction
	at org.jooq.impl.DefaultConnectionProvider.commit(DefaultConnectionProvider.java:101)
	at org.jooq.impl.DefaultTransactionProvider.commit(DefaultTransactionProvider.java:174)
	at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:554)
	at org.jooq.impl.Tools$3$1.block(Tools.java:5589)
	at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3137)
	at org.jooq.impl.Tools$3.get(Tools.java:5586)
	at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:598)
	at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:522)
	at com.memo.ExampleApp$main$1$2$2.invokeSuspend(Application.kt:80)
	at com.memo.ExampleApp$main$1$2$2.invoke(Application.kt)
	at com.memo.ExampleApp$main$1$2$2.invoke(Application.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:78)
	at io.ktor.routing.Routing.executeResult(Routing.kt:155)
	at io.ktor.routing.Routing.interceptor(Routing.kt:39)
	at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:107)
	at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
	at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
	at io.ktor.features.ContentNegotiation$Feature$install$1.invokeSuspend(ContentNegotiation.kt:145)
	at io.ktor.features.ContentNegotiation$Feature$install$1.invoke(ContentNegotiation.kt)
	at io.ktor.features.ContentNegotiation$Feature$install$1.invoke(ContentNegotiation.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:78)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:127)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:78)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invokeSuspend(NettyApplicationCallHandler.kt:123)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:43)
	at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:34)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:370)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda-1$lambda-0(NettyApplicationEngine.kt:251)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:830)
	Suppressed: org.jooq.exception.DataAccessException: Cannot rollback transaction
		at org.jooq.impl.DefaultConnectionProvider.rollback(DefaultConnectionProvider.java:114)
		at org.jooq.impl.DefaultTransactionProvider.rollback(DefaultTransactionProvider.java:194)
		at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:574)
		... 54 common frames omitted
	Caused by: org.postgresql.util.PSQLException: Cannot rollback when autoCommit is enabled.
		at org.postgresql.jdbc.PgConnection.rollback(PgConnection.java:893)
		at com.zaxxer.hikari.pool.ProxyConnection.rollback(ProxyConnection.java:385)
		at com.zaxxer.hikari.pool.HikariProxyConnection.rollback(HikariProxyConnection.java)
		at org.jooq.impl.DefaultConnectionProvider.rollback(DefaultConnectionProvider.java:111)
		... 56 common frames omitted
Caused by: org.postgresql.util.PSQLException: Cannot commit when autoCommit is enabled.
	at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:872)
	at com.zaxxer.hikari.pool.ProxyConnection.commit(ProxyConnection.java:377)
	at com.zaxxer.hikari.pool.HikariProxyConnection.commit(HikariProxyConnection.java)
	at org.jooq.impl.DefaultConnectionProvider.commit(DefaultConnectionProvider.java:98)
	... 56 common frames omitted
```

**Comment by SebastianKG** [comment]
(Also to note, you'll see that I did switch to HikariCP)

**Comment by SebastianKG** [comment]
Oh, and here are the Hikari startup logs

```
2022-10-21 05:14:10.636 [main] DEBUG com.zaxxer.hikari.HikariConfig - HikariPool-1 - configuration:
2022-10-21 05:14:10.670 [main] DEBUG com.zaxxer.hikari.HikariConfig - allowPoolSuspension.............false
2022-10-21 05:14:10.671 [main] DEBUG com.zaxxer.hikari.HikariConfig - autoCommit......................true
2022-10-21 05:14:10.671 [main] DEBUG com.zaxxer.hikari.HikariConfig - catalog.........................none
2022-10-21 05:14:10.671 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionInitSql...............none
2022-10-21 05:14:10.672 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionTestQuery.............none
2022-10-21 05:14:10.672 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionTimeout...............30000
2022-10-21 05:14:10.672 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSource......................none
2022-10-21 05:14:10.673 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceClassName.............none
2022-10-21 05:14:10.673 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceJNDI..................none
2022-10-21 05:14:10.674 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceProperties............{password=<masked>}
2022-10-21 05:14:10.675 [main] DEBUG com.zaxxer.hikari.HikariConfig - driverClassName.................none
2022-10-21 05:14:10.675 [main] DEBUG com.zaxxer.hikari.HikariConfig - exceptionOverrideClassName......none
2022-10-21 05:14:10.676 [main] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckProperties...........{}
2022-10-21 05:14:10.676 [main] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckRegistry.............none
2022-10-21 05:14:10.676 [main] DEBUG com.zaxxer.hikari.HikariConfig - idleTimeout.....................600000
2022-10-21 05:14:10.676 [main] DEBUG com.zaxxer.hikari.HikariConfig - initializationFailTimeout.......1
2022-10-21 05:14:10.677 [main] DEBUG com.zaxxer.hikari.HikariConfig - isolateInternalQueries..........false
2022-10-21 05:14:10.678 [main] DEBUG com.zaxxer.hikari.HikariConfig - jdbcUrl.........................jdbc:postgresql://localhost:5432/memo
2022-10-21 05:14:10.679 [main] DEBUG com.zaxxer.hikari.HikariConfig - keepaliveTime...................0
2022-10-21 05:14:10.679 [main] DEBUG com.zaxxer.hikari.HikariConfig - leakDetectionThreshold..........0
2022-10-21 05:14:10.680 [main] DEBUG com.zaxxer.hikari.HikariConfig - maxLifetime.....................1800000
2022-10-21 05:14:10.680 [main] DEBUG com.zaxxer.hikari.HikariConfig - maximumPoolSize.................10
2022-10-21 05:14:10.680 [main] DEBUG com.zaxxer.hikari.HikariConfig - metricRegistry..................none
2022-10-21 05:14:10.680 [main] DEBUG com.zaxxer.hikari.HikariConfig - metricsTrackerFactory...........none
2022-10-21 05:14:10.681 [main] DEBUG com.zaxxer.hikari.HikariConfig - minimumIdle.....................10
2022-10-21 05:14:10.681 [main] DEBUG com.zaxxer.hikari.HikariConfig - password........................<masked>
2022-10-21 05:14:10.685 [main] DEBUG com.zaxxer.hikari.HikariConfig - poolName........................"HikariPool-1"
2022-10-21 05:14:10.685 [main] DEBUG com.zaxxer.hikari.HikariConfig - readOnly........................false
2022-10-21 05:14:10.685 [main] DEBUG com.zaxxer.hikari.HikariConfig - registerMbeans..................false
2022-10-21 05:14:10.686 [main] DEBUG com.zaxxer.hikari.HikariConfig - scheduledExecutor...............none
2022-10-21 05:14:10.686 [main] DEBUG com.zaxxer.hikari.HikariConfig - schema..........................none
2022-10-21 05:14:10.686 [main] DEBUG com.zaxxer.hikari.HikariConfig - threadFactory...................internal
2022-10-21 05:14:10.686 [main] DEBUG com.zaxxer.hikari.HikariConfig - transactionIsolation............default
2022-10-21 05:14:10.687 [main] DEBUG com.zaxxer.hikari.HikariConfig - username........................"memo"
2022-10-21 05:14:10.687 [main] DEBUG com.zaxxer.hikari.HikariConfig - validationTimeout...............5000
2022-10-21 05:14:10.687 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2022-10-21 05:14:10.744 [main] DEBUG c.z.hikari.util.DriverDataSource - Loaded driver with class name org.postgresql.Driver for jdbcUrl=jdbc:postgresql://localhost:5432/memo
2022-10-21 05:14:11.287 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@2af004b
2022-10-21 05:14:11.290 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2022-10-21 05:14:11.390 [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=1, active=1, idle=0, waiting=0)
```

**Comment by lukaseder** [comment]
That's your mistake:

```kotlin
val db = DSL.using(ds.connection, Settings().withExecuteLogging(false))
```

Replace this by:

```kotlin
val db = DSL.using(ds, dialect, Settings().withExecuteLogging(false))
```

Otherwise, all threads are working on the same JDBC `Connection`, and you're not even using your `DataSource`.
