### ISSUE TITLE
Wrong SQL generated when calling procedure with OUT parameter of type TABLE OF RECORD, where RECORD contains BOOLEAN attributes in Oracle

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14119]
Our current implementation of `AbstractRoutine` fails when trying to fetch an `OUT` parameter of the following type:

```sql
TYPE pls_default IS RECORD (
  a NUMBER(10) := 1,
  b VARCHAR2(10) := 'A',
  c BOOLEAN := TRUE
);
TYPE pls_tab_rdefault IS TABLE OF pls_default;
```

The relevant procedure call is:

```sql
-- [ ... ]
"TEST"."PLS_OBJECTS"."PLS_P_RDEFAULT" (
  "O_R" => "r2", 
  "O_ASSOC_I" => "a4", 
  "O_ASSOC_V" => "a6", 
  "O_TAB" => ?, 
  "O_VARR" => ?
);
-- [ ... ]
```

As can be seen, while associative arrays are decomposed into indiviual collections of scalars (`a4` and `a6`), the `TABLE` and `VARRAY` types are just ordinary bind values, because that's been possible for a few years, since 18c.

But if the `RECORD` type contains a PL/SQL `BOOLEAN` type, then the JDBC driver doesn't know what to do (this should be fixed in 23c, though, see https://github.com/jOOQ/jOOQ/issues/14011). The exception is:

```
org.jooq.exception.DataAccessException: SQL [declare "r2" "TEST"."PLS_OBJECTS"."PLS_DEFAULT"; "a4" "TEST"."PLS_OBJECTS"."PLS_ASSOC_I_RDEFAULT"; "e4" number(10); "i4" pls_integer := 1; "k4" DBMS_SQL.NUMBER_TABLE; "v41" DBMS_SQL.NUMBER_TABLE; "v42" DBMS_SQL.VARCHAR2_TABLE; "v43" DBMS_SQL.VARCHAR2_TABLE; "a6" "TEST"."PLS_OBJECTS"."PLS_ASSOC_V_RDEFAULT"; "e6" varchar2(4000); "i6" pls_integer := 1; "k6" DBMS_SQL.VARCHAR2_TABLE; "v61" DBMS_SQL.NUMBER_TABLE; "v62" DBMS_SQL.VARCHAR2_TABLE; "v63" DBMS_SQL.VARCHAR2_TABLE; begin "TEST"."PLS_OBJECTS"."PLS_P_RDEFAULT" ("O_R" => "r2", "O_ASSOC_I" => "a4", "O_ASSOC_V" => "a6", "O_TAB" => ?, "O_VARR" => ?); ? := "r2"."A"; ? := "r2"."B"; ? := case "r2"."C" when false then 0 when true then 1 end; "e4" := "a4".first; while "e4" is not null loop "k4"("i4") := "e4"; "v41"("i4") := "a4"("e4")."A"; "v42"("i4") := "a4"("e4")."B"; "v43"("i4") := case "a4"("e4")."C" when false then '0' when true then '1' end; "i4" := "i4" + 1; "e4" := "a4".next("e4"); end loop; ? := "k4"; ? := "v41"; ? := "v42"; ? := "v43"; "e6" := "a6".first; while "e6" is not null loop "k6"("i6") := "e6"; "v61"("i6") := "a6"("e6")."A"; "v62"("i6") := "a6"("e6")."B"; "v63"("i6") := case "a6"("e6")."C" when false then '0' when true then '1' end; "i6" := "i6" + 1; "e6" := "a6".next("e6"); end loop; ? := "k6"; ? := "v61"; ? := "v62"; ? := "v63"; end;]; Conversion to boolean failed
	at org.jooq_3.18.0-SNAPSHOT.ORACLE21C.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3363)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:686)
	at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:589)
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:393)
	at org.jooq.impl.Tools.attach(Tools.java:1581)
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:373)
	at org.jooq.test.OracleTest.testOraclePLSQLRecordDefaultsCombinedPassNothing(OracleTest.java:5116)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.sql.SQLException: Conversion to boolean failed
	at oracle.sql.Datum.booleanValue(Datum.java:339)
	at oracle.sql.OracleJdbc2SQLInput.readBoolean(OracleJdbc2SQLInput.java:156)
	at org.jooq.impl.DefaultBinding$DefaultBooleanBinding.get0(DefaultBinding.java:1955)
	at org.jooq.impl.DefaultBinding$DefaultBooleanBinding.get0(DefaultBinding.java:1)
	at org.jooq.impl.DefaultBinding$InternalBinding.get(DefaultBinding.java:1052)
	at org.jooq.impl.AbstractQualifiedRecord.readSQL(AbstractQualifiedRecord.java:128)
	at oracle.sql.STRUCT.toClass(STRUCT.java:629)
	at oracle.sql.STRUCT.toJdbc(STRUCT.java:580)
	at oracle.jdbc.oracore.OracleTypeUPT.unpickle81UPT(OracleTypeUPT.java:301)
	at oracle.jdbc.oracore.OracleTypeUPT.unpickle81rec(OracleTypeUPT.java:257)
	at oracle.jdbc.oracore.OracleTypeCOLLECTION.unpickle81ImgBodyElements(OracleTypeCOLLECTION.java:626)
	at oracle.jdbc.oracore.OracleTypeCOLLECTION.unpickle81ImgBody(OracleTypeCOLLECTION.java:548)
	at oracle.jdbc.oracore.OracleTypeCOLLECTION.unpickle81(OracleTypeCOLLECTION.java:368)
	at oracle.jdbc.oracore.OracleTypeCOLLECTION.unlinearizeInternal(OracleTypeCOLLECTION.java:242)
	at oracle.jdbc.oracore.OracleTypeCOLLECTION.unlinearize(OracleTypeCOLLECTION.java:221)
	at oracle.sql.ArrayDescriptor.toJavaArray(ArrayDescriptor.java:937)
	at oracle.jdbc.driver.OracleArray.getArray(OracleArray.java:291)
	at oracle.sql.ARRAY.getArray(ARRAY.java:396)
	at org.jooq.impl.DefaultBinding$DefaultArrayRecordBinding.set0(DefaultBinding.java:1604)
	at org.jooq.impl.DefaultBinding$DefaultArrayRecordBinding.set(DefaultBinding.java:1592)
	at org.jooq.impl.DefaultBinding$DefaultArrayRecordBinding.set(DefaultBinding.java:1)
	at org.jooq.impl.DefaultBinding$AbstractArrayOrAssociativeArrayRecordBinding.lambda$2(DefaultBinding.java:1523)
	at org.jooq.impl.DefaultExecuteContext.localExecuteContext(DefaultExecuteContext.java:254)
	at org.jooq.impl.DefaultBinding$AbstractArrayOrAssociativeArrayRecordBinding.getArrayRecord(DefaultBinding.java:1523)
	at org.jooq.impl.DefaultBinding$AbstractArrayOrAssociativeArrayRecordBinding.get0(DefaultBinding.java:1492)
	at org.jooq.impl.DefaultBinding$AbstractArrayOrAssociativeArrayRecordBinding.get0(DefaultBinding.java:1)
	at org.jooq.impl.DefaultBinding$InternalBinding.get(DefaultBinding.java:1042)
	at org.jooq.impl.AbstractRoutine.fetchOutParameter(AbstractRoutine.java:1650)
	at org.jooq.impl.AbstractRoutine.fetchOutParameters(AbstractRoutine.java:1614)
	at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:573)
	... 36 more
```

The solution will be to implement the same algorithm as with associative arrays, instead.

**Comment by lukaseder** [comment]
I've signed up for an Oracle 23c beta access. I want to play around with the new `BOOLEAN` type support. This shouldn't be a thing anymore in future Oracle versions, so perhaps, we can omit any workaround for older Oracle versions. So far, customers haven't requested this. Might be an edge case they've been accepting to work around using `NUMBER(1)`?
