### ISSUE TITLE
Override BlockImpl::equals() and hashCode()

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14151]
This fails for certain dialects:

```java
assertEquals(ctx.begin(), ctx.begin());
```

Specifically for H2 or MySQL, where we generate random block IDs:

```
Exception in thread "main" java.lang.AssertionError: expected:<create alias block_1666972495876_5148542 as $$
  void x(Connection c) throws SQLException {
  }
$$;
call block_1666972495876_5148542();
drop alias block_1666972495876_5148542;> but was:<create alias block_1666972495876_6091265 as $$
  void x(Connection c) throws SQLException {
  }
$$;
call block_1666972495876_6091265();
drop alias block_1666972495876_6091265;>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.jooq.testscripts.JDBC.main(JDBC.java:66)
```

**Comment by lukaseder** [comment]
To properly fix this, we need to make `DSL::nullStatement`  public API:
https://github.com/jOOQ/jOOQ/issues/14152

**Comment by lukaseder** [comment]
Hmm, I'm not sure yet. It feels weird to make the `NULL` statement first class. It really serves no purpose other than satisfying some arcane syntax requirement. It should be ignored by the parser, rather than creating a dummy `NullStatement` internally.

If we're using a dialect that doesn't support/require it, then two equally looking blocks might not be equal and it would be very hard to debug why that is...

**Comment by lukaseder** [comment]
Here's the better fix for the `NullStatement` problem. We stop maintaining it in our expression tree: https://github.com/jOOQ/jOOQ/issues/14153

The only way it can be created, currently, is when parsing.

**Comment by lukaseder** [comment]
There are more problems than just the `NullStatement`. E.g., so far, these may have been equal:

```sql
BEGIN
  DECLARE @i, @j INT
END

BEGIN
  DECLARE @i INT
  DECLARE @j INT
END
```

But now, they no longer are. They probably shouldn't be equal, but that's a bigger fix.
