### ISSUE TITLE
DefaultDiagnosticsContext shouldn't call ResultSet::getMetaData on already closed ResultSet

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14236]
There's a bug in the SQLite JDBC driver, which has been exposed by one of jOOQ's integration tests:
https://github.com/xerial/sqlite-jdbc/issues/808

The bug causes:

```
java.lang.IllegalStateException: SQLite JDBC: inconsistent internal state
	at org.sqlite.core.CoreResultSet.checkCol(CoreResultSet.java:95)
	at org.sqlite.jdbc3.JDBC3ResultSet.getColumnCount(JDBC3ResultSet.java:602)
	at org.jooq.impl.DefaultDiagnosticsContext.resultSetColumnNames(DefaultDiagnosticsContext.java:202)
	at org.jooq.impl.DefaultDiagnosticsContext.resultSetFetchedColumnNames(DefaultDiagnosticsContext.java:192)
	at org.jooq.impl.LoggingDiagnosticsListener.tooManyColumnsFetched(LoggingDiagnosticsListener.java:102)
	at org.jooq.impl.DiagnosticsListeners.tooManyColumnsFetched(DiagnosticsListeners.java:99)
	at org.jooq.impl.DiagnosticsResultSet.close(DiagnosticsResultSet.java:767)
	at org.jooq.test.all.testcases.DiagnosticsTests.test(DiagnosticsTests.java:1168)
	at org.jooq.test.all.testcases.DiagnosticsTests.test(DiagnosticsTests.java:1150)
	at org.jooq.test.all.testcases.DiagnosticsTests.testExpression(DiagnosticsTests.java:1033)
	at org.jooq.test.all.testcases.DiagnosticsTests.lambda$43(DiagnosticsTests.java:978)
	at org.jooq.test.all.testcases.DiagnosticsTests.lambda$1(DiagnosticsTests.java:128)
	at org.jooq.test.all.testcases.DiagnosticsTests.diagnosticsTest(DiagnosticsTests.java:159)
	at org.jooq.test.all.testcases.DiagnosticsTests.diagnosticsTest(DiagnosticsTests.java:128)
	at org.jooq.test.all.testcases.DiagnosticsTests.testDiagnosticsConcatenationInPredicate(DiagnosticsTests.java:972)
	at org.jooq.test.jOOQAbstractTest.testDiagnosticsConcatenationInPredicate(jOOQAbstractTest.java:3055)
```

The xerial driver bug is caused by the fact that their `ResultSet` eager closes automatically, when fully consumed, and we're too late reading the `ResultSetMetaData`. Even if that behaviour is debatable, there might be other reasons why the `ResultSet` might be already closed, including some user `ExecuteListener`.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.18.0, 3.17.6 (https://github.com/jOOQ/jOOQ/issues/14237), and 3.16.12 (https://github.com/jOOQ/jOOQ/issues/14238)
