### ISSUE TITLE
Cannot query geometry value in a nested ROW

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14231]
Similar to https://github.com/jOOQ/jOOQ/issues/14195, when producing this query from the jOOQ API:

```sql
select row (cast(null as geometry), cast('point(1 1)' as geometry)) as "nested"
```

Then we get an exception:

```
12:08:10,822 DEBUG [LoggerListener                ] - Exception                
org.jooq.exception.DataAccessException: SQL [select row (cast(? as geometry), cast(? as geometry)) as "nested" -- SQL rendered with a free trial version of jOOQ 3.18.0-SNAPSHOT]; Error while reading field: row (null, 'point(1 1)'), at JDBC index: 1
	at org.jooq_3.18.0-SNAPSHOT.POSTGRES.debug(Unknown Source) ~[?:?]
	at org.jooq.impl.Tools.translate(Tools.java:3369) ~[classes/:?]
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:746) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1465) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1426) ~[classes/:?]
	at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:239) ~[classes/:?]
	at org.jooq.impl.Tools.fetchOne(Tools.java:2661) ~[classes/:?]
	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:509) ~[classes/:?]
	at org.jooq.impl.Tools.attach(Tools.java:1582) ~[classes/:?]
	at org.jooq.impl.DefaultDSLContext.fetchOne(DefaultDSLContext.java:4672) ~[classes/:?]
	at org.jooq.impl.DefaultDSLContext.lambda$55(DefaultDSLContext.java:4692) ~[classes/:?]
	at org.jooq.impl.Tools.attach(Tools.java:1582) ~[classes/:?]
	at org.jooq.impl.DefaultDSLContext.fetchValue(DefaultDSLContext.java:4692) ~[classes/:?]
	at org.jooq.test.all.testcases.MultisetTests.lambda$207(MultisetTests.java:1511) ~[test-classes/:?]
	at org.jooq.test.jOOQAbstractTest.withDSLContext(jOOQAbstractTest.java:2154) ~[test-classes/:?]
	at org.jooq.test.jOOQAbstractTest.bindAndInline(jOOQAbstractTest.java:2137) ~[test-classes/:?]
	at org.jooq.test.BaseTest.bindAndInline(BaseTest.java:1806) ~[test-classes/:?]
	at org.jooq.test.all.testcases.MultisetTests.assertMultisetDataType(MultisetTests.java:1504) ~[test-classes/:?]
	at org.jooq.test.all.testcases.MultisetTests.assertMultisetDataType(MultisetTests.java:1496) ~[test-classes/:?]
	at org.jooq.test.all.testcases.MultisetTests.assertMultisetDataType(MultisetTests.java:1492) ~[test-classes/:?]
	at org.jooq.test.all.testcases.MultisetTests.testMultisetProjectionDataTypeGeometry(MultisetTests.java:1730) ~[test-classes/:?]
	at org.jooq.test.jOOQAbstractTest.testMultisetProjectionDataTypeGeometry(jOOQAbstractTest.java:5553) ~[test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) ~[junit-4.13.2.jar:4.13.2]
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93) ~[.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) ~[.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) ~[.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) ~[.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) ~[.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) ~[.cp/:?]
Caused by: java.sql.SQLException: Error while reading field: row (null, 'point(1 1)'), at JDBC index: 1
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1591) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1526) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1) ~[classes/:?]
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1450) ~[classes/:?]
	... 50 more
Caused by: java.lang.UnsupportedOperationException: Class class org.jooq.Geometry is not supported
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.pgFromString(DefaultBinding.java:4013) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.pgSetValue(DefaultBinding.java:4060) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.lambda$13(DefaultBinding.java:4052) ~[classes/:?]
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.pgNewRecord(DefaultBinding.java:4048) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.get0(DefaultBinding.java:3844) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.get0(DefaultBinding.java:1) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$InternalBinding.get(DefaultBinding.java:1032) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1581) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1526) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1) ~[classes/:?]
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1450) ~[classes/:?]
	... 50 more
```

The returned `ROW` value by PostgreSQL looks like this:

```
(,0101000000000000000000F03F000000000000F03F)
```

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.18.0 and 3.17.6 (https://github.com/jOOQ/jOOQ/issues/14234). A backport to 3.16 was omitted, as the related changes from https://github.com/jOOQ/jOOQ/issues/14195 are too significant and too much has been changed in the area of `MULTISET`
