### ISSUE TITLE
ClassCastException in WithImpl::$replace

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14258]
A new test is running into a `ClassCastException`:

```
Caused by: java.lang.ClassCastException: class org.jooq.impl.QueryPartList cannot be cast to class org.jooq.impl.CommonTableExpressionList (org.jooq.impl.QueryPartList and org.jooq.impl.CommonTableExpressionList are in unnamed module of loader 'app')
	at org.jooq.impl.QOM.replace(QOM.java:7539)
	at org.jooq.impl.WithImpl.$replace(WithImpl.java:1208)
	at org.jooq.impl.QOM.replace(QOM.java:7416)
	at org.jooq.impl.QOM.replace(QOM.java:8113)
	at org.jooq.impl.SelectQueryImpl.$replace(SelectQueryImpl.java:4819)
	at org.jooq.impl.QOM.replace(QOM.java:7416)
	at org.jooq.impl.QOM.replace(QOM.java:7398)
	at org.jooq.impl.QOM.replace(QOM.java:7519)
	at org.jooq.impl.QueriesImpl.$replace(QueriesImpl.java:195)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:275)
	at org.jooq.impl.DefaultDSLContext.renderInlined(DefaultDSLContext.java:770)
	at org.jooq.impl.AbstractQueryPart.toString(AbstractQueryPart.java:192)
	at java.base/java.lang.String.valueOf(String.java:4218)
	at java.base/java.io.PrintStream.println(PrintStream.java:1047)
	at org.jooq.test.util.BaseTest.println(BaseTest.java:937)
	at org.jooq.impl.ParseFilesTest.parse(ParseFilesTest.java:138)
	... 33 more
```

The compiler infers a type that is too specific in the replacement lambda. There might be other similar errors, which haven't yet been discovered. Will think about a better test suite.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.18.0 and 3.17.6 (https://github.com/jOOQ/jOOQ/issues/14259)
