### ISSUE TITLE
Upgrade liquibase-core dependency to 4.17 in jooq-meta-extensions-liquibase

### ISSUE THREAD

**Issue by mattupstate** [jOOQ/jOOQ#14267]
### Expected behavior

Jooq Liquibase extension to be compatible with recent version of Liquibase

### Actual behavior

The Jooq liquibase extension uses `FileSystemResourceAccessor` which was [removed](https://github.com/liquibase/liquibase/issues/3478) in Liquibase  4.17.

### Steps to reproduce the problem

Log output from an attempt to run the Gradle plugin `generateJooq` task:

```
matt @ ghost-s1 in ~/Workspace/github.com/mattupstate/acme (⎈k3d-acme-dev/default) on git:main+
$ ./gradlew acme-data:acme-data-sql:generateJooq                                                                   

> Task :acme-data:acme-data-sql:generateJooq FAILED
Exception in thread "main" java.lang.NoClassDefFoundError: liquibase/resource/FileSystemResourceAccessor
        at org.jooq.meta.extensions.liquibase.LiquibaseDatabase.export(LiquibaseDatabase.java:155)
        at org.jooq.meta.extensions.AbstractInterpretingDatabase.connection(AbstractInterpretingDatabase.java:100)
        at org.jooq.meta.extensions.AbstractInterpretingDatabase.create0(AbstractInterpretingDatabase.java:77)
        at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:369)
        at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:359)
        at org.jooq.meta.AbstractDatabase.setConnection(AbstractDatabase.java:337)
        at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:553)
        at org.jooq.codegen.GenerationTool.run(GenerationTool.java:240)
        at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:235)
        at org.jooq.codegen.GenerationTool.main(GenerationTool.java:207)
Caused by: java.lang.ClassNotFoundException: liquibase.resource.FileSystemResourceAccessor
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 10 more
```

### jOOQ Version

3.17.4

### Database product and version

N/A

### Java Version

N/A

### OS Version

N/A

### JDBC driver name and version (include name if unofficial driver)

N/A

**Comment by lukaseder** [comment]
Thanks for your report.

We're still on Liquibase 4.8, which is from this year as well. Would not have expected a breaking change with so little time to prepare in a minor release?

I guess we'll have to upgrade, but that will be an incompatible change on our end as well. As a workaround, do you need Liquibase 4.17 for your jOOQ code generation? Or can you downgrade that specific usage?

**Comment by lukaseder** [comment]
Even Liquibase 4.16 seems to still have the class. Perhaps downgrade to that version for the time being?

**Comment by lukaseder** [comment]
Well, our integration tests still seem to work when simply replacing `FileSystemResourceAccessor` by `DirectoryResourceAccessor`. We probably don't cover all the possible ways people may have used the `LiquibaseDatabase` so far? Do you have time to test the fix on jOOQ 3.18.0-SNAPSHOT to see if that works on your end?

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.18.0. As this constitutes a possibly backwards incompatible change on our end as well, I won't backport this fix to 3.17 and earlier minor releases.

**Comment by mattupstate** [comment]
Thanks @lukaseder! :bow:

**Comment by lukaseder** [comment]
Not sure why I chose 4.17.0 when 4.17.2 was already out. It addresses 2 CVEs in transitive dependencies:

- `org.yaml:snakeyaml:1.32`
- `org.apache.commons:commons-text:1.9.0`

**Comment by lukaseder** [comment]
Related issue:

- https://stackoverflow.com/q/75250415/521799
