### ISSUE TITLE
DSL::noField doesn't work in SEEK clause

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14395]
The jOOQ 3.17 `DSL::noField` (https://github.com/jOOQ/jOOQ/issues/2333) doesn't work yet for the `SEEK` clause. This test fails:

```java
assertRenders("select 1 order by 1", select(one()).orderBy(one()).seek(noField(one())));
```

With:

```
org.junit.ComparisonFailure: expected:<select 1 []order by 1> but was:<select 1 [where 1 > null ]order by 1>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.jooq.test.AbstractTest.assertEquals(AbstractTest.java:195)
	at org.jooq.test.AbstractTest.assertRenders(AbstractTest.java:206)
	at org.jooq.test.FieldTest.testNoFieldInSelect(FieldTest.java:106)
```

**Comment by lukaseder** [comment]
This way, it should be possible to have `ORDER BY` clauses with more criteria than the `SEEK` clause (even if the use-cases are very rare). E.g.

```java
select(...)
.from(T)
.orderBy(T.A, T.B, T.C)
.seek(a, b, noField(T.C)) // Ignore the last part
.fetch();
```

**Comment by lukaseder** [comment]
The policy of `NoField` is normally to not add it to any lists, e.g. `GROUP BY` or `ORDER BY`. But in this case, we have to maintain the reference in the query object model, in order to remember the position within the list (compared to the `ORDER BY` expressions), where we had the `NoField`

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.18.0 and 3.17.7 (https://github.com/jOOQ/jOOQ/issues/14396)
