### ISSUE TITLE
fetchLazy support of big resultsets with CockroachDB

### ISSUE THREAD

**Issue by ecff** [jOOQ/jOOQ#14392]
### Your question

I'm trying to do a relatively simple fetch of a large number of records via fetchLazy so as not to waste memory. Here is a minimal example:

```java
	public static void main(final String[] args) {
		PGSimpleDataSource dataSource = new PGSimpleDataSource();
		dataSource.setUrl("jdbc:postgresql://localhost:5432/postgres?user=postgres&password=hunter2");
		DSLContext dsl = DSL.using(new DefaultConfiguration().set(SQLDialect.COCKROACHDB).set(new DataSourceConnectionProvider(dataSource)));

		Name testTable = DSL.name("test");

		dsl.execute("DROP TABLE IF EXISTS test");
		dsl.createTable("test").column("id", SQLDataType.INTEGER.nullable(false)).execute();
		BatchBindStep ins = dsl.batch(dsl.insertInto(table(testTable)).values((Integer) null));
		IntStream.range(0, 100).forEach(ins::bind);
		ins.execute();

		dsl.transaction(conf ->
			DSL.using(conf).selectFrom(testTable).fetchSize(10).resultSetType(ResultSet.TYPE_FORWARD_ONLY).fetchLazy());
	}

```

which unfortunately runs into this:

```
Exception in thread "main" org.jooq.exception.DataAccessException: SQL [null]; ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.jooq_3.17.5.COCKROACHDB.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3307)
	at org.jooq.impl.MetaDataFieldProvider.init(MetaDataFieldProvider.java:163)
	at org.jooq.impl.MetaDataFieldProvider.<init>(MetaDataFieldProvider.java:78)
	at org.jooq.impl.SelectQueryImpl.getFields(SelectQueryImpl.java:750)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:261)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:341)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:301)
	at cdbjooq.App.lambda$main$1(App.java:33)
	at org.jooq.impl.DefaultDSLContext.lambda$transaction$5(DefaultDSLContext.java:614)
	at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:552)
	at org.jooq.impl.Tools$3$1.block(Tools.java:5839)
	at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
	at org.jooq.impl.Tools$3.get(Tools.java:5836)
	at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:600)
	at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:524)
	at org.jooq.impl.DefaultDSLContext.transaction(DefaultDSLContext.java:613)
	at cdbjooq.App.main(App.java:32)
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:244)
	at org.postgresql.jdbc.PgResultSetMetaData.fetchFieldMetaData(PgResultSetMetaData.java:251)
	at org.postgresql.jdbc.PgResultSetMetaData.isAutoIncrement(PgResultSetMetaData.java:61)
	at org.postgresql.jdbc.PgResultSetMetaData.getColumnTypeName(PgResultSetMetaData.java:326)
	at org.jooq.impl.MetaDataFieldProvider.init(MetaDataFieldProvider.java:131)
	... 15 more
Caused by: org.postgresql.util.PSQLException: ERROR: unimplemented: multiple active portals not supported
  Detail: cannot perform operation sql.PrepareStmt while a different portal is open
  Hint: You have attempted to use a feature that is not yet implemented.
See: https://go.crdb.dev/issue-v/40195/v22.2
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:244)
	at org.postgresql.jdbc.PgResultSetMetaData.fetchFieldMetaData(PgResultSetMetaData.java:251)
	at org.postgresql.jdbc.PgResultSetMetaData.getBaseTableName(PgResultSetMetaData.java:296)
	at org.postgresql.jdbc.PgResultSetMetaData.getTableName(PgResultSetMetaData.java:292)
	at org.jooq.impl.MetaDataFieldProvider.init(MetaDataFieldProvider.java:107)
	... 15 more
```

which seems related to cockroachdb/cockroach#40195

Am I using it wrong? If yes, How do I fetch large result sets without slurping them into memory?

### jOOQ Version

jooq trial 3.17.5

### Database product and version

CockroachDB v22.2

### Java Version

openjdk version "11.0.17" 2022-10-18

### OS Version

Arch Linux

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.0

**Comment by lukaseder** [comment]
Curiously, this query is generated only when calling `getTableName()`, not when calling `getSchemaName()` (which jOOQ also calls). The reason can be seen here: https://github.com/pgjdbc/pgjdbc/issues/538
