### ISSUE TITLE
"You can't specify target table '...' for update in FROM clause" when target table has index hint in MySQL

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14403]
When using the `USE INDEX` clause, or a similar index hint in MySQL, then the fix for #6583 doesn't work.

The reason is the same as #14387. We only traverse the join tree to find "unaliased" tables, not also "unwrapped" ones. Thus, this query is produced in an integration test:

```sql
update `test`.`t_author`
set `test`.`t_author`.`LAST_NAME` = (
  select min(`test`.`t_author`.`FIRST_NAME`) 
  from `test`.`t_author` use index (`i_author_name`)
) 
where `test`.`t_author`.`ID` = (
  select max(`test`.`t_author`.`ID`) 
  from `test`.`t_author` use index (`i_author_name`)
)
```

Instead of:

```sql
update `test`.`t_author`
set `test`.`t_author`.`LAST_NAME` = (
  select *
  from (
    select min(`test`.`t_author`.`FIRST_NAME`) 
    from `test`.`t_author` use index (`i_author_name`)
  ) t
) 
where `test`.`t_author`.`ID` = (
  select *
  from (
    select max(`test`.`t_author`.`ID`) 
    from `test`.`t_author` use index (`i_author_name`)
  ) t
)
```

Exception:

```
org.jooq.exception.DataAccessException: SQL [update `test`.`t_author` set `test`.`t_author`.`LAST_NAME` = (select min(`test`.`t_author`.`FIRST_NAME`) from `test`.`t_author` use index (`i_author_name`)) where `test`.`t_author`.`ID` = (select max(`test`.`t_author`.`ID`) from `test`.`t_author` use index (`i_author_name`))]; You can't specify target table 't_author' for update in FROM clause
	at org.jooq_3.18.0-SNAPSHOT.MYSQL.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3389)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:746)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:357)
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
	at org.jooq.test.all.testcases.InsertUpdateTests.testDMLIntoTWithSubqueryFromT0(InsertUpdateTests.java:390)
	at org.jooq.test.all.testcases.InsertUpdateTests.testDMLIntoTWithSubqueryFromTWithTableHints(InsertUpdateTests.java:359)
	at org.jooq.test.jOOQAbstractTest.testDMLIntoTWithSubqueryFromTWithTableHints(jOOQAbstractTest.java:2391)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.sql.SQLException: You can't specify target table 't_author' for update in FROM clause
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:422)
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:980)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:343)
	... 36 more
```

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.18.0, 3.17.7 (https://github.com/jOOQ/jOOQ/issues/14404), and 3.16.13 (https://github.com/jOOQ/jOOQ/issues/14405)
