### ISSUE TITLE
Code generator should properly qualify H2 domain enums - Merge [#13936]

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14401]

**Comment by lukaseder** [comment]
The backport has produced an important regression:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.jooq.test.h2.generatedclasses.public_.Tables.<clinit>(Tables.java:224)
	at org.jooq.testscripts.JDBC.main(JDBC.java:39)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1769)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:415)
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:252)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1134)
	at org.jooq.impl.DefaultDataType.<init>(DefaultDataType.java:349)
	at org.jooq.impl.AbstractDataType.asEnumDataType(AbstractDataType.java:672)
	at org.jooq.test.h2.generatedclasses.public_.tables.TBook.<init>(TBook.java:103)
	at org.jooq.test.h2.generatedclasses.public_.tables.TBook.<init>(TBook.java:116)
	at org.jooq.test.h2.generatedclasses.public_.tables.TBook.<init>(TBook.java:141)
	at org.jooq.test.h2.generatedclasses.public_.tables.TBook.<clinit>(TBook.java:40)
	... 2 more
```

We can't publish 3.17.7 with this regression.

**Comment by lukaseder** [comment]
The `NPE` can be prevented by backporting a part of https://github.com/jOOQ/jOOQ/issues/13934

**Comment by lukaseder** [comment]
Definitely related. I'll backport #13934
