### ISSUE TITLE
StackOverflowError when nesting scalar subquery 1024 times

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14418]
This currently runs into a `StackOverflowError`:

```java
@Test
public void testScalarSubquery() {
    Select<Record1<Integer>> q = select(one());

    for (int i = 0; i < 1024; i++)
        q = select(field(q));

    println(create.renderInlined(q));
}
```

I've noticed many times in the past, that the stack depth has increased quite a bit per subquery level, given all the abstractions and utilities. Below, I've highlighted the length of one scope level. It's 23 frames:

```
java.lang.StackOverflowError
	at org.jooq.impl.ScopeStack.iterable(ScopeStack.java:118)
	at org.jooq.impl.ScopeStack.iterator(ScopeStack.java:110)
	at org.jooq.impl.DefaultRenderContext.scopeStart0(DefaultRenderContext.java:269)
	at org.jooq.impl.AbstractContext.scopeStart(AbstractContext.java:813)
	at org.jooq.impl.AbstractContext.subquery0(AbstractContext.java:787)
	at org.jooq.impl.AbstractContext.subquery(AbstractContext.java:807)
	at org.jooq.impl.Tools.visitSubquery(Tools.java:2805)
	at org.jooq.impl.Tools.visitSubquery(Tools.java:2784)


	at org.jooq.impl.ScalarSubquery.accept(ScalarSubquery.java:92)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:301)
	at org.jooq.impl.QueryPartCollectionView.acceptElement(QueryPartCollectionView.java:253)
	at org.jooq.impl.SelectFieldList.lambda$1(SelectFieldList.java:93)
	at org.jooq.impl.Tools.visitAutoAliased(Tools.java:2769)
	at org.jooq.impl.SelectFieldList.acceptElement0(SelectFieldList.java:93)
	at org.jooq.impl.SelectFieldList.acceptElement(SelectFieldList.java:89)
	at org.jooq.impl.SelectFieldList.acceptElement(SelectFieldList.java:1)
	at org.jooq.impl.QueryPartCollectionView.accept(QueryPartCollectionView.java:223)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:350)
	at org.jooq.impl.SelectQueryImpl.toSQLReference0(SelectQueryImpl.java:2277)
	at org.jooq.impl.SelectQueryImpl.lambda$34(SelectQueryImpl.java:1931)
	at org.jooq.impl.AbstractContext.toggle(AbstractContext.java:393)
	at org.jooq.impl.AbstractContext.data(AbstractContext.java:404)
	at org.jooq.impl.SelectQueryImpl.toSQLReferenceLimitDefault(SelectQueryImpl.java:1931)
	at org.jooq.impl.SelectQueryImpl.accept0(SelectQueryImpl.java:1810)
	at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:1483)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:350)
	at org.jooq.impl.Tools.visitSubquery(Tools.java:2811)
	at org.jooq.impl.Tools.visitSubquery(Tools.java:2784)


	at org.jooq.impl.ScalarSubquery.accept(ScalarSubquery.java:92)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:301)
	at org.jooq.impl.QueryPartCollectionView.acceptElement(QueryPartCollectionView.java:253)
	at org.jooq.impl.SelectFieldList.lambda$1(SelectFieldList.java:93)
	at org.jooq.impl.Tools.visitAutoAliased(Tools.java:2769)
	at org.jooq.impl.SelectFieldList.acceptElement0(SelectFieldList.java:93)
	at org.jooq.impl.SelectFieldList.acceptElement(SelectFieldList.java:89)
	at org.jooq.impl.SelectFieldList.acceptElement(SelectFieldList.java:1)
	at org.jooq.impl.QueryPartCollectionView.accept(QueryPartCollectionView.java:223)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:350)
	at org.jooq.impl.SelectQueryImpl.toSQLReference0(SelectQueryImpl.java:2277)
	at org.jooq.impl.SelectQueryImpl.lambda$34(SelectQueryImpl.java:1931)
	at org.jooq.impl.AbstractContext.toggle(AbstractContext.java:393)
	at org.jooq.impl.AbstractContext.data(AbstractContext.java:404)
	at org.jooq.impl.SelectQueryImpl.toSQLReferenceLimitDefault(SelectQueryImpl.java:1931)
	at org.jooq.impl.SelectQueryImpl.accept0(SelectQueryImpl.java:1810)
	at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:1483)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:350)
	at org.jooq.impl.Tools.visitSubquery(Tools.java:2811)
	at org.jooq.impl.Tools.visitSubquery(Tools.java:2784)


	at org.jooq.impl.ScalarSubquery.accept(ScalarSubquery.java:92)
```

Surely, this can be improved. It won't be possible to nest 64k levels, but 1000 should probably be OK.

The same is true for derived tables:

```java
@Test
public void testDerivedTable() {
    Select<Record1<Integer>> q = select(one());

    for (int i = 0; i < 1024; i++)
        q = select(one()).from(q.asTable("t"));

    println(create.renderInlined(q));
}
```

The error being (one scope level is 33 frames!):

```
java.lang.StackOverflowError
	at org.jooq.impl.AbstractContext.subquery0(AbstractContext.java:768)
	at org.jooq.impl.AbstractContext.subquery(AbstractContext.java:807)
	at org.jooq.impl.Tools.visitSubquery(Tools.java:2805)


	at org.jooq.impl.DerivedTable.accept(DerivedTable.java:112)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:310)
	at org.jooq.impl.Alias.toSQLWrapped(Alias.java:421)
	at org.jooq.impl.Alias.lambda$5(Alias.java:404)
	at org.jooq.impl.AbstractContext.toggle(AbstractContext.java:393)
	at org.jooq.impl.AbstractContext.data(AbstractContext.java:404)
	at org.jooq.impl.Alias.toSQLWrapped(Alias.java:404)
	at org.jooq.impl.Alias.acceptDeclareAliasStandard(Alias.java:328)
	at org.jooq.impl.Alias.accept(Alias.java:198)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:350)
	at org.jooq.impl.TableAlias.accept(TableAlias.java:146)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:350)
	at org.jooq.impl.QueryPartCollectionView.acceptElement(QueryPartCollectionView.java:253)
	at org.jooq.impl.TableList.lambda$1(TableList.java:87)
	at org.jooq.impl.Tools.visitAutoAliased(Tools.java:2769)
	at org.jooq.impl.TableList.acceptElement(TableList.java:87)
	at org.jooq.impl.TableList.acceptElement(TableList.java:1)
	at org.jooq.impl.QueryPartCollectionView.accept(QueryPartCollectionView.java:223)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:350)
	at org.jooq.impl.SelectQueryImpl.toSQLReference0(SelectQueryImpl.java:2375)
	at org.jooq.impl.SelectQueryImpl.lambda$34(SelectQueryImpl.java:1931)
	at org.jooq.impl.AbstractContext.toggle(AbstractContext.java:393)
	at org.jooq.impl.AbstractContext.data(AbstractContext.java:404)
	at org.jooq.impl.SelectQueryImpl.toSQLReferenceLimitDefault(SelectQueryImpl.java:1931)
	at org.jooq.impl.SelectQueryImpl.accept0(SelectQueryImpl.java:1810)
	at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:1483)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:350)
	at org.jooq.impl.Tools.visitSubquery(Tools.java:2811)


	at org.jooq.impl.DerivedTable.accept(DerivedTable.java:112)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:310)
	at org.jooq.impl.Alias.toSQLWrapped(Alias.java:421)
	at org.jooq.impl.Alias.lambda$5(Alias.java:404)
	at org.jooq.impl.AbstractContext.toggle(AbstractContext.java:393)
	at org.jooq.impl.AbstractContext.data(AbstractContext.java:404)
	at org.jooq.impl.Alias.toSQLWrapped(Alias.java:404)
	at org.jooq.impl.Alias.acceptDeclareAliasStandard(Alias.java:328)
	at org.jooq.impl.Alias.accept(Alias.java:198)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:350)
	at org.jooq.impl.TableAlias.accept(TableAlias.java:146)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:350)
	at org.jooq.impl.QueryPartCollectionView.acceptElement(QueryPartCollectionView.java:253)
	at org.jooq.impl.TableList.lambda$1(TableList.java:87)
	at org.jooq.impl.Tools.visitAutoAliased(Tools.java:2769)
	at org.jooq.impl.TableList.acceptElement(TableList.java:87)
	at org.jooq.impl.TableList.acceptElement(TableList.java:1)
	at org.jooq.impl.QueryPartCollectionView.accept(QueryPartCollectionView.java:223)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:350)
	at org.jooq.impl.SelectQueryImpl.toSQLReference0(SelectQueryImpl.java:2375)
	at org.jooq.impl.SelectQueryImpl.lambda$34(SelectQueryImpl.java:1931)
	at org.jooq.impl.AbstractContext.toggle(AbstractContext.java:393)
	at org.jooq.impl.AbstractContext.data(AbstractContext.java:404)
	at org.jooq.impl.SelectQueryImpl.toSQLReferenceLimitDefault(SelectQueryImpl.java:1931)
	at org.jooq.impl.SelectQueryImpl.accept0(SelectQueryImpl.java:1810)
	at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:1483)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:350)
	at org.jooq.impl.Tools.visitSubquery(Tools.java:2811)


	at org.jooq.impl.DerivedTable.accept(DerivedTable.java:112)
```

Obviously no user ever reported this so far, though I have a feeling, @GavinRay97 might, so let's fix this in time before he runs into it 😅

**Comment by lukaseder** [comment]
Maybe, this is all a bit theoretical. jOOQ can render 128 nest levels without a problem, but MySQL can't process that:

![image](https://user-images.githubusercontent.com/734593/208146905-8cc6c298-e0b4-4b72-a753-3f32d87ae08c.png)

**Comment by lukaseder** [comment]
Though, PostgreSQL can.

**Comment by lukaseder** [comment]
There are some no-brainers, like removing some internal convenience methods like:

```
	at org.jooq.impl.Tools.visitSubquery(Tools.java:2811)
	at org.jooq.impl.Tools.visitSubquery(Tools.java:2784)
```

Or avoid the data toggle, which is certainly convenient, but an imperative `try - finally` approach does just fine as well:

```
	at org.jooq.impl.Alias.toSQLWrapped(Alias.java:421)
	at org.jooq.impl.Alias.lambda$5(Alias.java:404)
	at org.jooq.impl.AbstractContext.toggle(AbstractContext.java:393)
	at org.jooq.impl.AbstractContext.data(AbstractContext.java:404)
	at org.jooq.impl.Alias.toSQLWrapped(Alias.java:404)
```

This indirection appears between each pair of `QueryPart` types, and is caused by the `VisitListener` logic as well as the declaration toggle logic. Perhaps it can be simplified?

```
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:350)
```

There are others.
