### ISSUE TITLE
BigQuery stored procedures can't be called with the JDBC escape syntax

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14449]
This statement:

```java
CallableStatement c = connection.prepareCall("{ call `TEST.proc_IfElse` () }");
```

Seems to fail (though I'm not convinced this used to fail earlier?). The error is:

```
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
POST https://bigquery.googleapis.com/bigquery/v2/projects/curious-domain-305108/jobs
{
  "code": 400,
  "errors": [
    {
      "domain": "global",
      "location": "q",
      "locationType": "parameter",
      "message": "Syntax error: Expected end of input but got \"{\" at [1:1]",
      "reason": "invalidQuery"
    }
  ],
  "message": "Syntax error: Expected end of input but got \"{\" at [1:1]",
  "status": "INVALID_ARGUMENT"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)
```

It seems we just have to use the native `call` syntax:

```java
CallableStatement c = connection.prepareCall("call TEST.proc_IfElse()");
```

**Comment by lukaseder** [comment]
Ah, this is an integration test only problem, where we use JDBC directly to call the procedure (see #3426)
