### ISSUE TITLE
inline(null, multisetType) doesn't work

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14462]
While probably rarely used by end users, `inline(null, multiset(s).getDataType())` currently cannot be used. For example:

```java
Result<Record1<Integer>> r = ctx.fetchValue(select(inline(null, multiset(selectOne()).getDataType())));
```

It should produce a `null` multiset, but the executed query is:

```sql
select '+----+
| one|
+----+
'
```

And the result looks like this:

```
+---------------------+
|+----+                
| one|                 
+----+                 
|                      
+---------------------+
|[({null})]           |
+---------------------+
```

Using `coerce()` also doesn't work (but should):

```java
inline(null, OTHER).coerce(multiset(select).getDataType())
```

Produces:

```
java.sql.SQLException: Error while reading field: null, at JDBC index: 2
	at org.jooq.impl.CursorImpl$CursorRecordInitialiser.setValue(CursorImpl.java:1575)
	at org.jooq.impl.CursorImpl$CursorRecordInitialiser.apply(CursorImpl.java:1506)
	at org.jooq.impl.CursorImpl$CursorRecordInitialiser.apply(CursorImpl.java:1)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1382)
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1358)
	at org.jooq.impl.Tools.collect(Tools.java:6997)
	at org.jooq.impl.AbstractCursor.collect(AbstractCursor.java:78)
	at org.jooq.impl.ResultQueryTrait.collect(ResultQueryTrait.java:360)
	at org.jooq.impl.ResultQueryTrait.fetch(ResultQueryTrait.java:1464)
	at org.jooq.testscripts.JDBC.main(JDBC.java:72)
Caused by: java.lang.NullPointerException: Cannot invoke "java.sql.ResultSet.getMetaData()" because "rs" is null
	at org.jooq.impl.DefaultDSLContext.fetchLazy(DefaultDSLContext.java:1357)
	at org.jooq.impl.DefaultDSLContext.fetch(DefaultDSLContext.java:1216)
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:4937)
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:1)
	at org.jooq.impl.DefaultBinding$InternalBinding.get(DefaultBinding.java:1284)
	at org.jooq.impl.CursorImpl$CursorRecordInitialiser.setValue(CursorImpl.java:1565)
	... 10 more
```

See also:

- https://stackoverflow.com/q/79780754/521799

**Comment by lukaseder** [comment]
This is a bigger task. We would also have to be able to bind `MULTISET` types using `val(x, t)` (including non-`NULL` values), but that just produces this exception:

```
org.jooq.exception.DataAccessException: SQL [null]; Error while writing value at JDBC bind index: 1
	at org.jooq_3.18.0-SNAPSHOT.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3406)
	at org.jooq.impl.AbstractBindContext.bindValue(AbstractBindContext.java:77)
	at org.jooq.impl.Val.accept(Val.java:198)
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:258)
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:68)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:350)
	at org.jooq.impl.QueryPartCollectionView.acceptElement(QueryPartCollectionView.java:253)
	at org.jooq.impl.QueryPartCollectionView.accept(QueryPartCollectionView.java:223)
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:258)
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:68)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:350)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:353)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:301)
	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:322)
	at org.jooq.impl.SelectImpl.fetchLazyNonAutoClosing(SelectImpl.java:2861)
	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:509)
	at org.jooq.impl.Tools.attach(Tools.java:1583)
	at org.jooq.impl.DefaultDSLContext.fetchOne(DefaultDSLContext.java:4706)
	at org.jooq.impl.DefaultDSLContext.lambda$55(DefaultDSLContext.java:4726)
	at org.jooq.impl.Tools.attach(Tools.java:1583)
	at org.jooq.impl.DefaultDSLContext.fetchValue(DefaultDSLContext.java:4726)
	at org.jooq.test.all.testcases.MultisetTests.lambda$209(MultisetTests.java:1515)
	at org.jooq.test.jOOQAbstractTest.withDSLContext(jOOQAbstractTest.java:2230)
	at org.jooq.test.jOOQAbstractTest.bindAndInline(jOOQAbstractTest.java:2213)
	at org.jooq.test.BaseTest.bindAndInline(BaseTest.java:1876)
	at org.jooq.test.all.testcases.MultisetTests.assertMultisetDataType(MultisetTests.java:1508)
	at org.jooq.test.all.testcases.MultisetTests.assertMultisetDataType(MultisetTests.java:1490)
	at org.jooq.test.all.testcases.MultisetTests.assertMultisetDataType(MultisetTests.java:1486)
	at org.jooq.test.all.testcases.MultisetTests.testMultisetProjectionDataTypeMultiset(MultisetTests.java:1712)
	at org.jooq.test.jOOQAbstractTest.testMultisetProjectionDataTypeMultiset(jOOQAbstractTest.java:5652)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.sql.SQLException: Error while writing value at JDBC bind index: 1
	at org.jooq.impl.DefaultBindContext.bindValue0(DefaultBindContext.java:68)
	at org.jooq.impl.AbstractBindContext.bindValue(AbstractBindContext.java:74)
	... 60 more
Caused by: java.lang.UnsupportedOperationException: Cannot bind a value of type Result to a PreparedStatement
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.set0(DefaultBinding.java:4107)
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.set0(DefaultBinding.java:1)
	at org.jooq.impl.DefaultBinding$InternalBinding.set(DefaultBinding.java:1018)
	at org.jooq.impl.DefaultBindContext.bindValue0(DefaultBindContext.java:63)
	... 61 more
```

The underlying regression that helped discover this is https://github.com/jOOQ/jOOQ/issues/14245#issuecomment-1375841300. It's easy to work around this problem and avoid said regression. But fixing this issue here is much harder. I'll postpone.

**Comment by lukaseder** [comment]
This is being requested here:

- https://stackoverflow.com/q/79780754/521799

**Comment by lukaseder** [comment]
Using `coerce()` also doesn't work

**Comment by lukaseder** [comment]
A more generic case is:

- https://github.com/jOOQ/jOOQ/issues/19137

**Comment by lukaseder** [comment]
Interestingly, due to the implementation of `MultisetDataType.convert(null)`, which produces an empty `ResultImpl` of the `MULTISET` type, rather than a `NULL` value, we cannot actually return a `NULL` value here easily. I'll investigate if this is a desirable behaviour. `multisetAgg()` also never returns `NULL`

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.21.0
- 3.20.9 (https://github.com/jOOQ/jOOQ/issues/19174)
- 3.19.28 (https://github.com/jOOQ/jOOQ/issues/19175)
- 3.18.35 (https://github.com/jOOQ/jOOQ/issues/19176)
