### ISSUE TITLE
SQL Server RETURNING clause emulation for fetching trigger generated values generates incorrect SQL if no columns are fetched

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14479]
As mentioned in another issue about virtual client side computed columns (https://github.com/jOOQ/jOOQ/issues/14477#issuecomment-1377544733), there is an invalid `MERGE` statement being generated in the emulation of `RETURNING`, in case a `RETURNING` clause fetches no additional columns from the table.

While this is most likely to happen with virtual client side computed columns (which don't exist in the table), it could also happen for other reasons, so it's not 100% related to #14477. The generated `MERGE` statement may look like this:

```sql
merge into @result r
using (
  select
    1 alias_63,
    (t_comp_client_virtual_1.VAL * 2) alias_22869988,
    t_comp_client_virtual_1.ID
  from t_comp_client_virtual_1
) s
on r.ID = s.ID
when matched then update set -- Here, we're missing content!
;
```

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.18.0 and 3.17.7 (https://github.com/jOOQ/jOOQ/issues/14480)

**Comment by lukaseder** [comment]
Regrettably, we can omit this logic only in the absence of triggers! Otherwise, this error ensues:

```
org.jooq.exception.DataAccessException: SQL [insert into [test].[dbo].[t_triggers] ([id], [counter]) output inserted.[id_generated] values (?, ?)]; The target table 'test.dbo.t_triggers' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.
	at org.jooq_3.18.0-SNAPSHOT.SQLSERVER2022.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3414)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:746)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:371)
	at org.jooq.impl.TableRecordImpl.storeInsert0(TableRecordImpl.java:192)
	at org.jooq.impl.TableRecordImpl.lambda$0(TableRecordImpl.java:158)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144)
	at org.jooq.impl.TableRecordImpl.storeInsert(TableRecordImpl.java:157)
	at org.jooq.impl.UpdatableRecordImpl.store0(UpdatableRecordImpl.java:222)
	at org.jooq.impl.UpdatableRecordImpl.lambda$0(UpdatableRecordImpl.java:149)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144)
	at org.jooq.impl.UpdatableRecordImpl.store(UpdatableRecordImpl.java:148)
	at org.jooq.impl.UpdatableRecordImpl.store(UpdatableRecordImpl.java:140)
	at org.jooq.test.all.testcases.ConnectionProviderTests.testConnectionProviderForUpdatableRecordInsert(ConnectionProviderTests.java:105)
	at org.jooq.test.jOOQAbstractTest.testConnectionProviderForUpdatableRecordInsert(jOOQAbstractTest.java:10142)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The target table 'test.dbo.t_triggers' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1673)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:620)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:540)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7627)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3912)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:268)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:242)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:459)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.executeQuery(DefaultPreparedStatement.java:104)
	at org.jooq.impl.AbstractDMLQuery.executeReturningQuery(AbstractDMLQuery.java:1322)
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:1090)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:357)
	... 43 more
```

Since we don't know anything about the presence of triggers yet, no further optimisation can be implemented prior to https://github.com/jOOQ/jOOQ/issues/13912

**Comment by lukaseder** [comment]
The error being:

> The target table 'test.dbo.t_triggers' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.

**Comment by lukaseder** [comment]
A related bug: https://github.com/jOOQ/jOOQ/issues/14703
