### ISSUE TITLE
Wrong SQL generated in SQL Server RETURNING emulation, when generated aliases conflict

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14482]
Somewhat related to recent issues that were fixed in the context of https://github.com/jOOQ/jOOQ/issues/14477

In SQL Server's `RETURNING` emulation, it can happen that generated aliases of the `@result` table create a conflict, such as in this instance:

```sql
declare @result table (
  alias_63 int,
  alias_22869988 int,
  alias_128594141 int,
  alias_63 int,
  ID int
);
insert into t_comp_client_virtual_1 (ID, VAL)
output 
  1,
  (inserted.VAL * 2),
  (1 + (inserted.VAL * 2) + 1),
  1,
  inserted.ID
into @result
values (
  1, 
  1
);
select alias_63, alias_22869988, alias_128594141, alias_63
from @result r;
```

This produces an error:

```
org.jooq.exception.DataAccessException: SQL [declare @result table (alias_63 int, alias_22869988 int, alias_128594141 int, alias_63 int, ID int); insert into t_comp_client_virtual_1 (ID, VAL) output ?, (inserted.VAL * ?), (? + (inserted.VAL * ?) + ?), ?, inserted.ID into @result values (?, ?); select alias_63, alias_22869988, alias_128594141, alias_63 from @result r;]; Column names in each table must be unique. Column name 'alias_63' in table '@result' is specified more than once.
	at org.jooq_3.18.0-SNAPSHOT.SQLSERVER2022.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3406)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:746)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:371)
	at org.jooq.impl.AbstractDMLQueryAsResultQuery.fetch(AbstractDMLQueryAsResultQuery.java:140)
	at org.jooq.impl.ResultQueryTrait.fetchLazy(ResultQueryTrait.java:281)
	at org.jooq.impl.ResultQueryTrait.fetchLazyNonAutoClosing(ResultQueryTrait.java:290)
	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:509)
	at org.jooq.test.all.testcases.ComputedClientSideVirtualTests.testComputedClientSideVirtualDMLInsertReturningProjectionExpressions(ComputedClientSideVirtualTests.java:579)
	at org.jooq.test.jOOQAbstractTest.testComputedClientSideVirtualDMLInsertReturningProjectionExpressions(jOOQAbstractTest.java:11872)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Column names in each table must be unique. Column name 'alias_63' in table '@result' is specified more than once.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1673)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:620)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:540)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7627)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3912)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:268)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:242)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:459)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.executeQuery(DefaultPreparedStatement.java:104)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.executeQuery(DefaultPreparedStatement.java:104)
	at org.jooq.impl.AbstractDMLQuery.executeReturningQuery(AbstractDMLQuery.java:1313)
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:1081)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:357)
	... 38 more
```

We don't have to generate aliases based on some `hashCode` in this case, which is guaranteed to create conflicts for identical expressions (which is an edge case, but can still happen often enough). It's probably better to enumerate the aliases, instead.

In this particular case, because there's no `MERGE` statement due to the fixes in https://github.com/jOOQ/jOOQ/issues/14479, we might also work around the edge case by removing the `@result` table entirely. Without `MERGE`, we can revert to running only the `INSERT` statement without `INTO`.

But this shows that we need another integration test that combines `MERGE` with duplicate aliases.

**Comment by lukaseder** [comment]
https://github.com/jOOQ/jOOQ/issues/13912 helps work around this issue for tables without triggers
