### ISSUE TITLE
"Merge" in Postgres ("INSERT...ON CONFLICT...UPDATE...) can update the wrong row

### ISSUE THREAD

**Issue by lucapino-kobalt** [jOOQ/jOOQ#14568]
### Expected behavior

The merge should throw an exception

### Actual behavior

Merge succeeds and corrupts a different row

### Steps to reproduce the problem

When the auto-increment/sequence is going to return a value for the PK that was already in the DB (i.e. the sequence is not up to date for some reason), I would expect for a MERGE without a value for the PK to fail, as it should try to insert using a PK that already exists.

The merge emulation currently does something like this:
```
insert into "mcve"."test" 
("cd") values (42) 
on conflict ("id") do 
update set "cd" = excluded."cd" 
returning "mcve"."test"."id"
```
but that means that in case of a sequence that is going to return an existing value, there's going to be a conflict on that `id`, and so it is going to replace the values on that existing unrelated row instead.

Created MCVE here: https://github.com/lucapino-kobalt/jOOQ-mcve

### jOOQ Version

3.17.7

### Database product and version

Postgres 12

### Java Version

17

**Comment by lukaseder** [comment]
Thanks a lot for your report. I will look into this, soon.

**Comment by lukaseder** [comment]
I've looked at your MCVE, and can confirm the observed behaviour.

However, I'm not sure if there's really anything that needs to be fixed. If you do not provide an explicit `ID` value, then the sequence (or identity) attached with the `ID` column will provide it. Since you're in control of your database, you're "aware" of the next sequence value being in conflict with existing data, for whatever reason. This conflict may or may not be desired (i.e. by design or by accident).

If you had used a natural key that was already present to your "surprise", then this `UpdatableRecord::merge` behaviour would be perfectly sound. The fact that this is a surrogate key shouldn't matter, nor should it produce a different behaviour. To illustrate this, you could have also written:

```java
TestRecord testRecord = ctx.newRecord(TEST);
testRecord.setId(ctx.nextval(name("mcve", "test_id_seq")).intValue());
testRecord.setCd(42);

assertEquals(1,
    testRecord.merge()
);
```

Now, you're making the implicit behaviour explicit, and it would be wrong for jOOQ to "correct" you. Imagine if you had a trigger that sets the `ID` value to anything based on any of your assumptions. How should jOOQ be able to detect what you may or may not have wanted to do?

In any schema where sequences are used, it is the schema maintainer's responsibility to keep sequences in sync with the data. If we wanted to expect any out-of-sync cases, we'd have to "fix" other statements as well, e.g. `INSERT`, etc.

**Comment by lucapino-kobalt** [comment]
Thank you for looking into this.

I tend to disagree with the verdict and would beg you to reconsider, as this is making the behaviour of `UpdatableRecord::merge` different from what you would obtain with a normal `MERGE` behaviour, as I would expect in the presence of `MERGE` the query would be something like this:
```
merge into "mcve"."test" 
using (select null as "id", 42 as "cd") v
on (v."id" = "mcve"."test"."id")
when matched then update set
"cd" = excluded."cd" 
when not matched then insert
("id", "cd")
values
(v."id", v."cd")
```
which in the case of a sequence with a value that already exists, would throw an exception, since there is no `null` id in the DB, but the `INSERT` on a PK that already exists fails on standard SQL. having different behaviours based on the absence or presence of `MERGE` support would be quite confusing and not deterministic.

also I would suspect jOOQ users tend to expect standard SQL behaviour from jOOQ, but this seem to contradict that

When merging multiple rows (e.g. using the `DAOImpl::merge` or the `DSLContext::batchMerge`), some of which just need updating and some of which need to be inserting, I guess the workaround would be to have to split the two data sets and insert and update them separately instead of merging them: a bit counter intuitive in my opinion and unknown to most of the API users.

Finally the potential to corrupt existing rows is quite a severe impact that I am sure a non starter for many users and companies

**Comment by lukaseder** [comment]
> as I would expect in the presence of `MERGE` the query would be something like this [...]:

But that new query uses an explicit `NULL`, which is different from the implicit `DEFAULT`. You changed the query to get the behaviour you wanted. You didn't do that in your original example, i.e. you didn't set the `ID` to `NULL` explicitly. You left it to be `DEFAULT` (sequence value) implicitly, and that's precisely what happened.

Again, keep in mind, this isn't really much different from:

- Working with surrogate keys
- Working with any other means of `DEFAULT` identity (e.g. UUID values)
- Working with trigger generated identities

The exposed behaviour is weird indeed, but consistent with the above.

> since there is no null id in the DB, but the INSERT on a PK that already exists fails on standard SQL.

I'm not sure what you mean by "standard SQL". When you run this in PostgreSQL:

```sql
create table t (i serial primary key, j int);
insert into t (j) values (1) on conflict (i) do update set j = excluded.j returning *;
alter sequence t_i_seq restart;
insert into t (j) values (2) on conflict (i) do update set j = excluded.j returning *;
```

Then you get the exact same behaviour. You're saying, we *shouldn't* follow these semantics?

> Finally the potential to corrupt existing rows is quite a severe impact

A sequence that is out of sync with the table it is attached to is the culprit. And I agree, this is quite severe, but I'm not convinced this has anything to do with jOOQ? All of your manually written `MERGE` or `INSERT .. ON CONFLICT` statements would be affected in the exact same way.

This is actually a *significant* fault in the schema with tons of undesired behaviour following from it.

> that I am sure a non starter for many users and companies

Well, that is a level of argumentative escalation way beyond what I would have expected. :)

It's a tricky edge case, yes. But a show stopper? Hardly. Let's not forget that the cause for all of this is a sequence that is out of sync with the table. Whenever this happened in production systems back where I worked in the past, it was terrible, and we would have immediately patched the sequence to be incremented by something like `1000000000`. We would have never expected individual queries to continue working.

Now, I can tell you an equal "non-continuer" for many users and companies. Changing existing behaviour of an ORM. Imagine someone actually relies on the current behaviour and does

```sql
alter sequence t_i_seq restart
```

Because, why not? The `restart` clause exists in sequences. What now? Would they get a regression?

The tradeoff between ...

- Regressions (of edge cases, granted)
- "Weird" (but consistent) behaviour (of edge cases, again)

... continues to convince me we shouldn't change anything in this area. What if we overlook more edge cases and introduce subtle inconsistencies? The worst that can happen is that `merge()` behaves differently for:

- Identities generated from `DEFAULT` expressions
- Identities generated from `GENERATED ALWAYS` expressions
- Identities generated from triggers
- Identities generated explicitly

Also, I invite you to spell out the formal rules where we distinguish between the behaviour of sequence based identities and UUID based identities. Why should jOOQ be the arbiter of what is truly a unique identity value? Wasn't that up to the schema designer to choose?

Anyway. `merge()` does what it says, and maybe, you just wanted to use `store()`, instead...

**Comment by lucapino-kobalt** [comment]
thank you for your comprehensive answer and sorry for the pressure in my previous response, I might have misread your previous comment as dismissive

> But that new query uses an explicit `NULL`, which is different from the implicit `DEFAULT`. You changed the query to get the behaviour you wanted. You didn't do that in your original example, i.e. you didn't set the `ID` to `NULL` explicitly. You left it to be `DEFAULT` (sequence value) implicitly, and that's precisely what happened.

I added the explicit `null` because without it I did not know how to build the condition to merge upon, probably should have been:
```
merge into "mcve"."test" 
using (select 42 as "cd") v
on (null = "mcve"."test"."id")
when matched then update set
"cd" = excluded."cd" 
when not matched then insert
("cd")
values
(v."cd")
```
which still needs to contain a `null` somewhere

I guess this is one of the main semantic difference between a `MERGE` and a `INSERT ... ON CONFLICT` approach: checking for conflicts is different than attempting to find a row and so the condition needs to be different to some extent 

I can see that the `merge()` method tries to document this (you may want to update also the overloaded methods to state the same), the only observation I have is that naming-wise though it is not that intuitive, but I can see how there might not be a better solution and alternative, especially since we are talking about problems in some edge cases

I had the wrong impression that with Postgres 15 `MERGE` support added to 3.18 the semantic of `merge()` would be closer to the above, but I can see that using `INSERT ... ON CONFLICT` is a deliberate choice as explained in the documentation

> A sequence that is out of sync with the table it is attached to is the culprit. And I agree, this is quite severe, but I'm not convinced this has anything to do with jOOQ? All of your manually written `MERGE` or `INSERT .. ON CONFLICT` statements would be affected in the exact same way.

one throws an exception, which means that we can be alerted about the underlying error, the other doesn't and actually changes some data while proceeding undetected, so they would not be affected in the same way

in the end of the day I guess it is just unfortunate that naming wise it reminds of `MERGE`, so I guess it is ok for this to stay closed

> Anyway. `merge()` does what it says, and maybe, you just wanted to use `store()`, instead...

I might end up using that, only issue being that we are using POJOs and DAOs everywhere else, and `store` is not present at that level

as far as I understand from https://github.com/jOOQ/jOOQ/issues/5984 DAOs are not actively worked on, and I can see that a `store` operator on them would only make partial sense, as the one on Records relies on information that is not present in the POJO

thanks for the clarifications and keep up the good work

**Comment by lukaseder** [comment]
> thank you for your comprehensive answer and sorry for the pressure in my previous response, I might have misread your previous comment as dismissive

Things are never as simple as they first appear. The Java language and platform engineers keep saying that all the time. Their biggest hate word is "just." Users always want to "just" have this thing (I'm guilty of this, myself).

Being told that is obviously disappointing. But I think it's important to set expectations straight, not just for you, but also for everyone who visits this issue in the future because of a similar situation.

There's a thin line between choosing the understanding tone of customer support, and the harsh tone of product management. Regrettably, an issue tracker mixes both concerns, so I'm trying to wear both hats here. Taking the time to explain, but also be very clear about what can and cannot be expected from a product like jOOQ.

> I added the explicit `null` because without it I did not know how to build the condition to merge upon, probably should have been:

You "cheated" to coerce the SQL statement's behaviour into your expectation. But the resulting statement isn't not correct in the sense of what `UpdatableRecord::merge` should do. Putting a `NULL` there just works around your specific undesired case, but if you put a `NULL` there, then you will override the sequence value in the `MERGE`'s `INSERT` clause, meaning, you'll *never* insert anything, breaking *everything*. Clearly not what you expected? Try this:

```sql
create table t (i serial primary key, j int);

merge into t 
using (select null::int i, 1 j) s 
on (t.i = s.i)
when matched then update set j = s.j
when not matched then insert (i, j) values (s.i, s.j);
```

You're now getting:

> SQL Error [23502]: ERROR: null value in column "i" of relation "t" violates not-null constraint

Obviously, because this statement is now *always* overriding the desired `DEFAULT` semantics of using a sequence.

What I tried to say with the example shown here:
https://github.com/jOOQ/jOOQ/issues/14568#issuecomment-1422398427

Is that the sequence value is fetched implicitly, before adding the row to the table. So if you want to emulate this with an explicit `MERGE`, rather than with Java code, then you have to do this:

```sql
merge into "mcve"."test" 
using (
  select 
    -- This is what's happening!
    nextval('test_id_seq') as "id",
    42 as "cd"
) v
on (v."id" = "mcve"."test"."id")
when matched then update set "cd" = excluded."cd" 
when not matched then insert ("id", "cd") values (v."id", v."cd")
```

I mean, why pretend there "should have been" a magic `NULL`, when in fact, the omission of an *explicit* value just means *implicit `DEFAULT`*, i.e. sequence value. Of course, we could make `UpdatableRecord::merge` do whatever we want, but this does seem to be the most consistent with all the other operations, including `UpdatableRecord::insert`, and expectations:

- Explicit changed value in record = inclusion in statement (overrides defaults)
- Unchanged or absent value in record = exclusion from statement (applies defaults in `INSERT`)

I understand that this is surprising in the context of this edge case at first, but it's perfectly logical and expected.

I couldn't resist creating a poll from this case on Twitter:
https://twitter.com/lukaseder/status/1623675087520948224

Most (of the few who answered) got it right. This is really what is supposed to happen! Fun additional example:

```sql
create sequence s minvalue 1 maxvalue 100 cycle;
```

Who is jOOQ to judge users and their intents, however rare and edge casey they may be? If you have a sequence like this, then you absolutely *want* the many fun and weird behaviours of sequences in all of your queries. jOOQ cannot be the arbiter of these things.

While unlikely, people who design such sequences would *want* `UpdatableRecord::merge` to behave the way it does.

> the only observation I have is that naming-wise though it is not that intuitive

Well, the choice was between `MERGE` and `UPSERT` and I didn't want to introduce a new term. Both are equivalent.

Now, what does it mean to `MERGE` into a table that has a default, sequence generated surrogate key? That's a fun question, and it has a single logical answer in my opinion (though, this is a great reminder to add some integration tests to cover these cases). So, I'd say `MERGE` is a perfectly fine name, even in this particular case.

Of course, having `insert()`, `update()`, `store()`, `merge()` as options does create cognitivie friction, like any vocabulary of any API that has to be learned. `store()` may be the unexpected historic name here, but I think `MERGE` seems quite obvious? It merges client data with whatever is on the server, moving the decision of whether to `INSERT` or `UPDATE` to the server, just like the `MERGE` statement.

> I had the wrong impression that with Postgres 15 `MERGE` support added to 3.18 the semantic of `merge()` would be closer to the above, but I can see that using `INSERT ... ON CONFLICT` is a deliberate choice as explained in the documentation

jOOQ 3.17 does not yet support PostgreSQL 15 (https://github.com/jOOQ/jOOQ/issues/13758), so it cannot use `MERGE` yet. It will, soon, because `ON CONFLICT` cannot use multiple conflict targets, and the semantics of MySQL's `ON DUPLICATE KEY UPDATE` is that of using all the unique keys.

> one throws an exception, which means that we can be alerted about the underlying error, the other doesn't and actually changes some random data while proceeding undetected, so they would not be affected in the same way

But there is no error!

Don't get me wrong, I can see how there's a mismatch in expectations and edge cases. But I really want to argue here that there is no error:

- You didn't specify the ID explicitly, so it must be generated implicitly
- There's no formal technical distinction between a sequence that is out of sync, and a sequence that is designed to produce duplicate values. There's no way for jOOQ to decide this.

You want it to be an error on your end, but others may expect things to work exactly as it does. I think this kind of error detection can only be implemented with monitoring and knowledge of your schema design.

**Comment by lukaseder** [comment]
Well, lacking integration test cases for such edge cases thus far, I can (regrettably) confirm that what you're expecting is what's currently being generated for RDBMS that don't have an `INSERT .. ON DUPLICATE KEY UPDATE` equivalent, but support `MERGE`. E.g. for H2:

```java
ctx.delete(T_IDENTITY_PK).execute();
ctx.execute("alter table t_identity_pk alter column id restart");
//ctx.alterSequence("t_identity_pk_id_seq").restart().execute();
TIdentityPkRecord r1 = ctx.newRecord(T_IDENTITY_PK);
r1.setVal(1);
r1.merge();

ctx.fetch(T_IDENTITY_PK);
ctx.execute("alter table t_identity_pk alter column id restart");
//ctx.alterSequence("t_identity_pk_id_seq").restart().execute();

TIdentityPkRecord r2 = ctx.newRecord(T_IDENTITY_PK);
r2.setVal(2);
r2.merge();
```

This produces the `MERGE` statement that you're expecting, and thus the constraint violation error:

```
10:55:46,227 DEBUG [LoggerListener                ] - Exception                
org.jooq.exception.DataAccessException: SQL [select id from final table (/* [#12925] cee1a451-63b9-4011-977e-f16e64060a68 */ merge into public.t_identity_pk using (select cast(? as int) val) t on public.t_identity_pk.id = cast(? as int) when matched then update set public.t_identity_pk.val = t.val when not matched then insert (val) values (t.val)) t_identity_pk]; Eindeutiger Index oder Primärschlüssel verletzt: "PRIMARY KEY ON PUBLIC.T_IDENTITY_PK(ID) ( /* key:1 */ 1, 1)"
Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.T_IDENTITY_PK(ID) ( /* key:1 */ 1, 1)"; SQL statement:
select id from final table (/* [#12925] cee1a451-63b9-4011-977e-f16e64060a68 */ merge into public.t_identity_pk using (select cast(? as int) val) t on public.t_identity_pk.id = cast(? as int) when matched then update set public.t_identity_pk.val = t.val when not matched then insert (val) values (t.val)) t_identity_pk [23505-214]
	at org.jooq_3.18.0-SNAPSHOT.H2_2_1_214.debug(Unknown Source) ~[?:?]
	at org.jooq.impl.Tools.translate(Tools.java:3423) ~[classes/:?]
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:746) ~[classes/:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:371) ~[classes/:?]
	at org.jooq.impl.UpdatableRecordImpl.storeMergeOrUpdate0(UpdatableRecordImpl.java:354) ~[classes/:?]
	at org.jooq.impl.UpdatableRecordImpl.storeMerge0(UpdatableRecordImpl.java:268) ~[classes/:?]
	at org.jooq.impl.UpdatableRecordImpl.lambda$2(UpdatableRecordImpl.java:248) ~[classes/:?]
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144) ~[classes/:?]
	at org.jooq.impl.UpdatableRecordImpl.storeMerge(UpdatableRecordImpl.java:247) ~[classes/:?]
	at org.jooq.impl.UpdatableRecordImpl.merge(UpdatableRecordImpl.java:183) ~[classes/:?]
	at org.jooq.impl.UpdatableRecordImpl.merge(UpdatableRecordImpl.java:178) ~[classes/:?]
	at org.jooq.testscripts.JDBC.main(JDBC.java:54) ~[test-classes/:?]
Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Eindeutiger Index oder Primärschlüssel verletzt: "PRIMARY KEY ON PUBLIC.T_IDENTITY_PK(ID) ( /* key:1 */ 1, 1)"
Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.T_IDENTITY_PK(ID) ( /* key:1 */ 1, 1)"; SQL statement:
select id from final table (/* [#12925] cee1a451-63b9-4011-977e-f16e64060a68 */ merge into public.t_identity_pk using (select cast(? as int) val) t on public.t_identity_pk.id = cast(? as int) when matched then update set public.t_identity_pk.val = t.val when not matched then insert (val) values (t.val)) t_identity_pk [23505-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:508) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.message.DbException.get(DbException.java:223) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.message.DbException.get(DbException.java:199) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.mvstore.db.MVPrimaryIndex.add(MVPrimaryIndex.java:120) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:519) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.dml.MergeUsing$WhenNotMatched.merge(MergeUsing.java:509) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.dml.MergeUsing.merge(MergeUsing.java:154) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.dml.MergeUsing.update(MergeUsing.java:135) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.table.DataChangeDeltaTable.getResult(DataChangeDeltaTable.java:120) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.index.VirtualConstructedTableIndex.find(VirtualConstructedTableIndex.java:38) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.index.IndexCursor.find(IndexCursor.java:161) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.table.TableFilter.next(TableFilter.java:394) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.query.Select$LazyResultQueryFlat.fetchNextRow(Select.java:1832) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.result.LazyResult.hasNext(LazyResult.java:78) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.result.FetchedResult.next(FetchedResult.java:34) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.query.Select.queryFlat(Select.java:728) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.query.Select.queryWithoutCache(Select.java:833) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.query.Query.queryWithoutCacheLazyCheck(Query.java:197) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.query.Query.query(Query.java:512) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.query.Query.query(Query.java:475) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.CommandContainer.query(CommandContainer.java:251) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.Command.executeQuery(Command.java:190) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:128) ~[h2-2.1.214.jar:2.1.214]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.executeQuery(DefaultPreparedStatement.java:104) ~[classes/:?]
	at org.jooq.impl.AbstractDMLQuery.executeReturningQuery(AbstractDMLQuery.java:1314) ~[classes/:?]
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:1119) ~[classes/:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:357) ~[classes/:?]
	... 8 more
```

And, starting with jOOQ 3.18, that same `MERGE` statement style is applied also on PostgreSQL 15+, if there are multiple unique keys on the table, and `RETURNING` is absent: https://github.com/jOOQ/jOOQ/issues/7552

So, starting with jOOQ 3.18, there will be subtly different behaviour even between PostgreSQL versions and/or tables, which is clearly worth looking at, again.

The inconsistency arises out of the emulation of `INSERT .. ON DUPLICATE KEY UPDATE`, which is used for many purposes behind the scenes in jOOQ. One example where any `MERGE` emulation falls short is when we apply `DEFAULT VALUES` as in:

```sql
INSERT INTO t
DEFAULT VALUES
ON DUPLICATE KEY UPDATE SET ..
```

See: https://github.com/jOOQ/jOOQ/issues/8937

This is another nice example illustrating that what *should be* done in the absence of explicit values, in my opinion, is what I suggested, namely the implicit or explicit application of column defaults. What could possibly be the semantics of `DEFAULT VALUES`, other than generating that identity sequence value (for whatever reason a user would write this particular query).

However, to address the above dialect version inconsistencies, I'll reopen this and give this another thought. In my opinion, to be consistent with a lot of other expectations, `INSERT .. ON DUPLICATE KEY UPDATE` (or `INSERT .. ON CONFLICT`), when emulated as `MERGE`, should produce the table's `DEFAULT` values where applicable (see again also https://github.com/jOOQ/jOOQ/issues/8937).

But this might not be simple to achieve, e.g. in SQL Server, it's not always possible to insert explicit values into identities (another example showing that things are never as simple as they appear).

**Comment by lukaseder** [comment]
The PostgreSQL specific inconsistency only appears when:

- PostgreSQL 15 is configured
- `RETURNING` is present (i.e. `Settings.returnIdentityOnUpdatableRecord` is set, which is the default, so by default, we keep generating `INSERT .. ON CONFLICT`, because PG 15 doesn't yet have a `RETURNING` clause on `MERGE`)
- More than 1 unique key is present
