### ISSUE TITLE
Update third party dependencies

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14586]
For the upcoming release of jOOQ 3.18.0, let's upgrade a few third party dependencies including:

- [x] `org.apache.logging.log4j:log4j-core` 2.18.0 -> 2.19.0
  - [x] `log4j-slf4j18-impl` to `log4j-slf4j2-impl` 2.18.0 -> 2.19.0 (see also https://logging.apache.org/log4j/2.x/log4j-slf4j-impl/)
- [x] `com.fasterxml.jackson.core:jackson-core` 2.13.4 -> 2.14.2
- [x] `com.fasterxml.jackson.core:jackson-databind` 2.13.4.2 -> 2.14.2
- [x] `com.fasterxml.jackson.datatype:jackson-datatype-jsr310` 2.13.4 -> 2.14.2
- [x] `com.fasterxml.jackson.module:jackson-module-kotlin` 2.13.4 -> 2.14.2
- [x] `org.hibernate:hibernate-core-jakarta` 5.6.5.Final -> 5.6.14.Final
- [x] `org.jetbrains:annotations` 23.0.0 -> 24.0.0
- [x] `org.jetbrains.kotlin:kotlin-reflect` 1.7.20 -> 1.8.0
- [x] `org.jetbrains.kotlin:kotlin-stdlib` 1.7.20 -> 1.8.0
- [x] `org.jetbrains.kotlin:kotlin-stdlib-jdk8` 1.7.20 -> 1.8.0
- [x] `org.postgresql:postgresql` 42.5.1 -> 42.5.3
- [x] `org.slf4j:slf4j-api` 1.8.0-beta4 -> 2.0.6

This issue will be amended

**Comment by lukaseder** [comment]
Hmm, there seems to be a problem when starting integration tests, though it doesn't seem to have any serious effects otherwise:

```
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Unexpected problem occured during version sanity check
Reported exception:
java.lang.AbstractMethodError: Receiver class org.apache.logging.slf4j.SLF4JServiceProvider does not define or inherit an implementation of the resolved method 'abstract java.lang.String getRequestedApiVersion()' of interface org.slf4j.spi.SLF4JServiceProvider.
	at org.slf4j.LoggerFactory.versionSanityCheck(LoggerFactory.java:331)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:172)
	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:455)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:441)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:390)
	at org.jooq.tools.JooqLogger.getLogger(JooqLogger.java:121)
	at org.jooq.tools.JooqLogger.getLogger(JooqLogger.java:80)
	at org.jooq.test.agent.SupportVerificationTransformer.<clinit>(SupportVerificationTransformer.java:78)
	at org.jooq.test.agent.SupportVerificationAgent.premain(SupportVerificationAgent.java:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
```

**Comment by lukaseder** [comment]
We have to rename the artifact from `log4j-slf4j18-impl` to `log4j-slf4j2-impl` in order to upgrade it from 2.18.0 to 2.19.0

**Comment by lukaseder** [comment]
See https://logging.apache.org/log4j/2.x/log4j-slf4j-impl/
