### ISSUE TITLE
DetachedException using r2dbc

### ISSUE THREAD

**Issue by jbrwn** [jOOQ/jOOQ#14605]
### Expected behavior

Execute a query with r2dbc-pool connection.   Not sure this is related specifically r2dbc-pool as i seem to run into the same issue with a regular r2dbc-postgresql connection as well.  Executing a query directly with the r2dbc-pool ConnectionFactory appears to work.

Appreciate the work on this.  I am excited to get started with non blocking io. 

### Actual behavior

After application start up, the first jooq query i execute i get the following exception and stack trace

```
org.jooq.exception.DetachedException: Cannot execute query. No JDBC Connection configured
	at org.jooq_3.17.7.DEFAULT.debug(Unknown Source)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:298)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:301)
	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:322)
	at org.jooq.impl.R2DBC$BlockingRecordSubscription.request0(R2DBC.java:1452)
	at org.jooq.impl.ThreadGuard.lambda$run$0(ThreadGuard.java:74)
	at org.jooq.impl.ThreadGuard.run(ThreadGuard.java:87)
	at org.jooq.impl.ThreadGuard.run(ThreadGuard.java:74)
	at org.jooq.impl.R2DBC$AbstractSubscription.request(R2DBC.java:182)
	at kotlinx.coroutines.reactive.AwaitKt$awaitOne$2$1$onSubscribe$3.invoke(Await.kt:213)
	at kotlinx.coroutines.reactive.AwaitKt$awaitOne$2$1$onSubscribe$3.invoke(Await.kt:212)
	at kotlinx.coroutines.reactive.AwaitKt$awaitOne$2$1.withSubscriptionLock(Await.kt:310)
	at kotlinx.coroutines.reactive.AwaitKt$awaitOne$2$1.onSubscribe(Await.kt:212)
	at org.jooq.impl.ResultQueryTrait.subscribe(ResultQueryTrait.java:372)
	at org.jooq.impl.SelectImpl.subscribe(SelectImpl.java:2851)
	at kotlinx.coroutines.reactive.AwaitKt.awaitOne(Await.kt:190)
	at kotlinx.coroutines.reactive.AwaitKt.awaitOne$default(Await.kt:183)
	at kotlinx.coroutines.reactive.AwaitKt.awaitFirstOrNull(Await.kt:45)
	at dog.catfood.dao.UserDao$getUserByUsername$2.invokeSuspend(UserDao.kt:27)
	at dog.catfood.dao.UserDao$getUserByUsername$2.invoke(UserDao.kt)
	at dog.catfood.dao.UserDao$getUserByUsername$2.invoke(UserDao.kt)
	at org.jooq.kotlin.coroutines.CoroutineExtensionsKt$transactionCoroutine$2$1.invokeSuspend(CoroutineExtensions.kt:16)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

### Steps to reproduce the problem

In build.gradle.kts:

```
implementation("org.jooq:jooq:3.17.7")
implementation("org.jooq:jooq-kotlin:3.17.7")
implementation("org.jooq:jooq-kotlin-coroutines:3.17.7")
implementation("io.r2dbc:r2dbc-pool:1.0.0.RELEASE")
implementation("org.postgresql:r2dbc-postgresql:1.0.0.RELEASE")
```

At application startup i build a `ConnectionFactory` and `DSLContext`

```
val connectionFactory: ConnectionFactory = ConnectionFactories.get(
    ConnectionFactoryOptions.builder()
        .option(DRIVER,"pool")
        .option(PROTOCOL,"postgresql")
        .option(HOST, "localhost")
        .option(PORT, 6000)
        .option(USER, "catfood")
        .option(PASSWORD, "catfood")
        .option(DATABASE, "catfood")
        .build()
)
val context = DSL.using(connectionFactory)
```

In a DAO class i use the `DSLContext` to execute a query.

```
class UserDao(private val context: DSLContext) {
    suspend fun getUserByUsername(username: String): User? {
        return context.transactionCoroutine {
            select(
                USERS.ID,
                USERS.USERNAME,
                USERS.CREATED_ON,
                USERS.MODIFIED_ON
            )
                .from(USERS)
                .where(USERS.USERNAME.eq(username))
                .awaitFirstOrNull()
                ?.map { it.toUser() }
        }
    }
}

fun Record.toUser(): User =
    User(
        getValue(USERS.ID),
        getValue(USERS.USERNAME)
    )
```

### jOOQ Version

3.17.7

### Database product and version

Postgresql 15 (postgres:alpine docker image)

### Java Version

Azul Zulu Community version 17.0.6

### OS Version

macOS 10.15.7

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:r2dbc-postgresql:1.0.0.RELEASE

**Comment by lukaseder** [comment]
Thanks a lot for your report.

The problem is here:

```kotlin
return context.transactionCoroutine {
    select(...)
}
```

That `select()` method is a static `DSL.select()` call, with no `Configuration` attached, which is what the `DetachedException` says, essentially. Do this, instead:

```kotlin
return context.transactionCoroutine { c ->
    c.dsl().select(...)
}
```

**Comment by jbrwn** [comment]
lmao I just realized this as well about two minutes ago.  Came back here to close the issue myself 💀 .   Anyways thanks for the quick response and community support. 👍
