### ISSUE TITLE
Wrong ON KEY JOIN generated when aliased table appears twice in the JOIN tree

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14668]
This simple query produces a wrong `JOIN` tree:

```java
TLanguage l = T_LANGUAGE.as("l");
TBook b1 = T_BOOK.as("b1");
TBook b2 = T_BOOK.as("b2");

Result<Record3<Integer, Integer, Integer>> r1 =
create().select(l.ID, b1.ID, b2.ID)
        .from(l)
        .leftJoin(b1).onKey(b1.LANGUAGE_ID)
        .leftJoin(b2).onKey(b2.LANGUAGE_ID)
        .orderBy(1, 2, 3)
        .fetch();
```

Unlike with other reported issues, like:

- https://github.com/jOOQ/jOOQ/issues/13517

There is no ambiguity in the join tree, yet this is produced

```sql
select "l"."ID", "b1"."ID", "b2"."ID"
from "PUBLIC"."T_LANGUAGE" "l"
  left outer join "PUBLIC"."T_BOOK" "b1"
    on "b1"."LANGUAGE_ID" = "l"."ID"     -- Correct JOIN predicate
  left outer join "PUBLIC"."T_BOOK" "b2"
    on "b1"."LANGUAGE_ID" = "b2"."ID"    -- Wrong JOIN predicate
order by 1, 2, 3
```

This might be a duplicate of https://github.com/jOOQ/jOOQ/issues/12214

**Comment by lukaseder** [comment]
The problem is that we're looking for the unaliased table on the `lhs` of the `JOIN`, first (in `JoinTable::onKey`):

```java
if (containsUnaliasedTable(lhs, keyFields[0].getTable())) {
    for (ForeignKey<?, ?> key : lhs.getReferences())
        if (key.getFields().containsAll(unaliased) && unaliased.containsAll(key.getFields()))
            return onKey(key);

    for (ForeignKey<?, ?> key : lhs.getReferences())
        if (key.getFields().containsAll(unaliased))
            return onKey(key);
}
else if (containsUnaliasedTable(rhs, keyFields[0].getTable())) {
    for (ForeignKey<?, ?> key : rhs.getReferences())
        if (key.getFields().containsAll(unaliased) && unaliased.containsAll(key.getFields()))
            return onKey(key);

    for (ForeignKey<?, ?> key : rhs.getReferences())
        if (key.getFields().containsAll(unaliased))
            return onKey(key);
}
```

This is being done to allow for "fuzzy" matches where tables are aliased, but `onKey()` field references aren't.

As always with these fuzzy matches, we must try to find exact matches first.

**Comment by lukaseder** [comment]
While this is related to https://github.com/jOOQ/jOOQ/issues/12214 (which uses `onKey(ForeignKey)`) it is not exactly the same. Similar problems are caused by the fact that `ForeignKey` of aliased tables isn't itself aliased as well (there's an issue for this, which I can't find right now).

But here, the user explicitly passes aliased column references, so it should be possible to produce the right `JOIN`

**Comment by lukaseder** [comment]
Reusing `onKey(ForeignKey)` is not just currently wrong because of #12214, it's also a bit inefficient, as we're re-traversing the `JOIN` tree again to look up the right `JOIN` order for the key, when in fact the loops above have already done the work.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.18.0, 3.17.9 (https://github.com/jOOQ/jOOQ/issues/14669), and 3.16.15 (https://github.com/jOOQ/jOOQ/issues/14670)

**Comment by lukaseder** [comment]
There's still a warning in the logs:

```
11:40:19,247  INFO [FieldsImpl                    ] - Ambiguous match found for ID. Both "l"."ID" and "b1"."ID" match.
java.sql.SQLWarning: null
	at org.jooq.impl.FieldsImpl.field0(FieldsImpl.java:285) ~[classes/:?]
	at org.jooq.impl.FieldsImpl.field(FieldsImpl.java:224) ~[classes/:?]
	at org.jooq.impl.AbstractRow.field(AbstractRow.java:312) ~[classes/:?]
	at org.jooq.impl.FieldsTrait.field(FieldsTrait.java:69) ~[classes/:?]
	at org.jooq.impl.JoinTable.onKey0(JoinTable.java:800) ~[classes/:?]
	at org.jooq.impl.JoinTable.onKey(JoinTable.java:788) ~[classes/:?]
	at org.jooq.impl.JoinTable.onKey(JoinTable.java:765) ~[classes/:?]
	at org.jooq.impl.JoinTable.onKey(JoinTable.java:1) ~[classes/:?]
	at org.jooq.impl.SelectQueryImpl.addJoinOnKey(SelectQueryImpl.java:4676) ~[classes/:?]
	at org.jooq.impl.SelectImpl.onKey(SelectImpl.java:2203) ~[classes/:?]
	at org.jooq.impl.SelectImpl.onKey(SelectImpl.java:1) ~[classes/:?]
	at org.jooq.test.all.testcases.JoinTests.testJoinOnKeyWithAliasAmbiguousPaths(JoinTests.java:1040) ~[test-classes/:?]
	at org.jooq.test.jOOQAbstractTest.testJoinOnKeyWithAliasAmbiguousPaths(jOOQAbstractTest.java:7911) ~[test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) ~[junit-4.13.2.jar:4.13.2]
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93) ~[.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) ~[.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) ~[.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) ~[.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) ~[.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) ~[.cp/:?]
```

That problem is still related to https://github.com/jOOQ/jOOQ/issues/12214, where the `ForeignKey` reference can't be used to find exact field matches.

**Comment by lukaseder** [comment]
The warning hints at the `JOIN` order being relevant to resolving the columns correctly. In the test, it worked by accident:


```java
TLanguage l = T_LANGUAGE.as("l");
TBook b1 = T_BOOK.as("b1");
TBook b2 = T_BOOK.as("b2");

Result<Record3<Integer, Integer, Integer>> r1 =
create().select(l.ID, b1.ID, b2.ID)
        .from(l)
        .leftJoin(b1).onKey(b1.LANGUAGE_ID)
        .leftJoin(b2).onKey(b2.LANGUAGE_ID)
        .orderBy(1, 2, 3)
        .fetch();
```

But if we switch the `JOIN` order to this:


```java
TLanguage l = T_LANGUAGE.as("l");
TBook b1 = T_BOOK.as("b1");
TBook b2 = T_BOOK.as("b2");

Result<Record3<Integer, Integer, Integer>> r1 =
create().select(l.ID, b1.ID, b2.ID)
        .from(b1)
        .rightJoin(l).onKey(b1.LANGUAGE_ID)
        .leftJoin(b2).onKey(b2.LANGUAGE_ID)
        .orderBy(1, 2, 3)
        .fetch();
```

Then, the resulting query is wrong again:

```sql
select "l"."ID", "b1"."ID", "b2"."ID"
from "PUBLIC"."T_BOOK" "b1"
  right outer join "PUBLIC"."T_LANGUAGE" "l"
    on "b1"."LANGUAGE_ID" = "l"."ID"
  left outer join "PUBLIC"."T_BOOK" "b2"
    on "b2"."LANGUAGE_ID" = "b1"."ID"        -- Wrong predicate here
order by 1, 2, 3
```

**Comment by lukaseder** [comment]
Yes, https://github.com/jOOQ/jOOQ/issues/14671 fixed this issue
