### ISSUE TITLE
Wrong column resolved by JoinTable.field(Field), when JoinTable contains aliased tables and lookup uses unaliased tables

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14671]
The following code produces the wrong output:

```java
TLanguage l = T_LANGUAGE.as("l");
TBook b = T_BOOK.as("b");

Table<?> t = b.rightJoin(l).onKey();
println(t.field(l.ID));          // Correct result
println(t.field(T_LANGUAGE.ID)); // Wrong result
```

It prints:

```
"l"."ID"
11:57:53,572  INFO [FieldsImpl                    ] - Ambiguous match found for ID. Both "b"."ID" and "l"."ID" match.
java.sql.SQLWarning: null
	at org.jooq.impl.FieldsImpl.field0(FieldsImpl.java:285) ~[classes/:?]
	at org.jooq.impl.FieldsImpl.field(FieldsImpl.java:224) ~[classes/:?]
	at org.jooq.impl.AbstractRow.field(AbstractRow.java:312) ~[classes/:?]
	at org.jooq.impl.FieldsTrait.field(FieldsTrait.java:69) ~[classes/:?]
	at org.jooq.testscripts.JDBC.main(JDBC.java:48) ~[test-classes/:?]
"b"."ID"
```

There is an ambiguity detected:

- There are two `ID` columns in the `JoinTable` (`b.ID` and `l.ID`)
- There is no exact match when using unaliased references to look up the aliased reference

While there is indeed no exact match based on the name alone, there's still a possibility to disambiguate the lookup in this case, given that there's only one version of the aliased `T_LANGUAGE` table, so the user can only have meant to dereference `l.ID`, not `b.ID`, which is returned, because it's the first ambiguous match.

Users are unlikely to write this code themselves. They'll re-use the correct exact match, even if just to get rid of the warning. But this may happen by jOOQ's internals, e.g. when using `ForeignKey` references for `ON KEY` joins, which cannot be aliased, see:

- https://github.com/jOOQ/jOOQ/issues/12214
- https://github.com/jOOQ/jOOQ/issues/14668#issuecomment-1439799310

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.18.0, 3.17.9 (https://github.com/jOOQ/jOOQ/issues/14673), and 3.16.15 (https://github.com/jOOQ/jOOQ/issues/14674)
