### ISSUE TITLE
DefaultRenderContext::scopeMapping should avoid possibly expensive ScopeStack lookups

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14729]
`DefaultRenderContext::scopeMapping` has been used so far mainly for 2 purposes:

- To register implicit joins *per scope* (see https://github.com/jOOQ/jOOQ/issues/1502)
- To register `QUALIFY` emulated window function expressions *per scope* (see https://github.com/jOOQ/jOOQ/issues/5810)

Both features are used relatively rarely (especially the latter), meaning that the overhead of looking up things in the `ScopeStack` should be avoided whenever possible. The lookup is usually not *that* expensive, but it can happen that `JSONB` content needs to be parsed because of https://github.com/jOOQ/jOOQ/issues/12023:

```
java.lang.Throwable
	at org.jooq.JSONB.parsed(JSONB.java:102)
	at org.jooq.JSONB.hashCode(JSONB.java:116)
	at org.jooq.impl.AbstractParam.hashCode(AbstractParam.java:278)
	at java.base/java.util.HashMap.hash(HashMap.java:338)
	at java.base/java.util.HashMap.getNode(HashMap.java:568)
	at java.base/java.util.LinkedHashMap.get(LinkedHashMap.java:441)
	at org.jooq.impl.ScopeStack.listOrNull(ScopeStack.java:233)
	at org.jooq.impl.ScopeStack.get(ScopeStack.java:198)
	at org.jooq.impl.DefaultRenderContext.scopeMapping(DefaultRenderContext.java:204)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:292)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:260)
	at org.jooq.impl.Eq.lambda$2(Eq.java:104)
	at org.jooq.impl.Eq.acceptCompareCondition(Eq.java:155)
	at org.jooq.impl.Eq.accept(Eq.java:104)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:350)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:255)
	at org.jooq.impl.ConditionAsField.accept(ConditionAsField.java:129)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:301)
	at org.jooq.impl.QueryPartCollectionView.acceptElement(QueryPartCollectionView.java:251)
	at org.jooq.impl.SelectFieldList.lambda$1(SelectFieldList.java:93)
	at org.jooq.impl.Tools.visitAutoAliased(Tools.java:2811)
	at org.jooq.impl.SelectFieldList.acceptElement0(SelectFieldList.java:93)
	at org.jooq.impl.SelectFieldList.acceptElement(SelectFieldList.java:89)
	at org.jooq.impl.SelectFieldList.acceptElement(SelectFieldList.java:1)
	at org.jooq.impl.QueryPartCollectionView.accept(QueryPartCollectionView.java:223)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:350)
	at org.jooq.impl.SelectQueryImpl.toSQLReference0(SelectQueryImpl.java:2327)
	at org.jooq.impl.SelectQueryImpl.lambda$36(SelectQueryImpl.java:1981)
	at org.jooq.impl.AbstractContext.toggle(AbstractContext.java:393)
	at org.jooq.impl.AbstractContext.data(AbstractContext.java:404)
	at org.jooq.impl.SelectQueryImpl.toSQLReferenceLimitDefault(SelectQueryImpl.java:1981)
	at org.jooq.impl.SelectQueryImpl.accept0(SelectQueryImpl.java:1876)
	at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:1504)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:350)
	at org.jooq.impl.DefaultDSLContext.render(DefaultDSLContext.java:734)
	at org.jooq.impl.AbstractAttachableQueryPart.getSQL(AbstractAttachableQueryPart.java:121)
	at org.jooq.impl.AbstractAttachableQueryPart.getSQL(AbstractAttachableQueryPart.java:114)
	at org.jooq.impl.AbstractDelegatingQuery.getSQL(AbstractDelegatingQuery.java:95)
	at org.jooq.test.benchmarks.ci.BenchmarkRenderingJSONBBinds.testRender(BenchmarkRenderingJSONBBinds.java:52)
	at org.jooq.test.benchmarks.ci.BenchmarkRenderingJSONBBinds.main(BenchmarkRenderingJSONBBinds.java:64)
```

Perhaps, given the rareness of such an object being in the `ScopeStack`, we can short circuit the negative outcome *before* calling `hashCode()` on the argument, somehow.

**Comment by lukaseder** [comment]
The nice part about the `ScopeStack` is that it's completely generic. It doesn't know anything about the types of object that are being placed in it.

Adding a guard based on the `key.getClass()` might be an option, but creates its own regression risk, specifically because values of two distinct types can still be equal (e.g. `LinkedList` and `ArrayList`). Besides, the overhead of adding a new `HashSet` (or whatever data structure) to the `ScopeStack` will impose additional overhead. So, let's not pursue this idea for now.
