### ISSUE TITLE
performace regression after upgrade from 3.14.16 to 3.17.8

### ISSUE THREAD

**Issue by fkowal** [jOOQ/jOOQ#14721]
### Expected behavior

No performance regressions
no more garbage

### Actual behavior

After upgrading the jooq dependecy

I noticed a performance hit to my whole application

The G1 Survivor Space & Gc Pauses ~+- doubled
which overall resulted in app response durations

The constant the changes was jooq version 3.14.16 -> org.jooq:jooq:3.17.8

Other settings remained the same, that is why i am reaching out.

Asking what might have changed in the jooq internals.

Overall i am only using jooq `dsl` + generated (java) `Record` classes for mapping

### Steps to reproduce the problem

I am happy to help with a debug session

### jOOQ Version

3.17.8

### Database product and version

PostgreSQL 13.7 on gcloud

### Java Version

azul/zulu-openjdk:17-jre

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.4

**Comment by lukaseder** [comment]
Thanks a lot for your report.

> Asking what might have changed in the jooq internals.

A ton :)

It's impossible to answer your question as it is now. There could be many reasons for this to happen, including only a *very* particular API usage on your end. You'll need to isolate the problem(s) to the specific regression on your end.

This doesn't mean you have to search for the specific regression (though that would be even better). But if you can find bottlenecks using a profiler, that would be quite helpful. An example report showing a specific problem is this one: https://github.com/jOOQ/jOOQ/issues/14371

Let me know if you need any help with setting up profilers, etc.

**Comment by dawidworobiec** [comment]
Hi @lukaseder

I ran profiler on few methods for above case.
Both below are connected with some JSONB parsing.

Some examples:
(UpdateImpl.set(Record))
 3.14.x
<img width="1656" alt="image" src="https://user-images.githubusercontent.com/21061610/221903696-db9ffffc-da71-4def-82cd-98a2e4f0ed02.png">

vs 3.17:
![image](https://user-images.githubusercontent.com/21061610/221904173-95accc23-5ec3-4c2a-b366-830e1c0a666d.png)

AbstractField.eq:
3.14.x
![image](https://user-images.githubusercontent.com/21061610/221904719-b7c286fa-9be7-4b6e-918d-c90551c7f66c.png)

vs 3.17
![image](https://user-images.githubusercontent.com/21061610/221904546-065b918d-b5ac-43db-90a0-b51e2025f392.png)

**Comment by lukaseder** [comment]
Thanks a lot, that's very helpful as a first hint. I'll investigate this more thoroughly tomorrow.

**Comment by dawidworobiec** [comment]
Added code samples above.

where
```
private inline fun <reified A> A.asJSONB(): JSONB = JSONB.valueOf(objectMapper.writeValueAsString(this))
````

So it's already converted to org.jooq.JSONB on our side

**Comment by fkowal** [comment]
```
// from JSONB.java
    private final Object parsed() {
        if (parsed == null) {
            try {
                parsed = new JSONParser().parse(data);
            }
            catch (ParseException e) {
                parsed = data;
            }
        }

        return parsed;
    }

    @Override
    public int hashCode() {
        Object p = parsed();
        return p == null ? 0 : p.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj instanceof JSONB j)
            return Objects.equals(parsed(), (j.parsed()));
        return false;
    }

    @Override
    public String toString() {
        return JSONValue.toJSONString(parsed());
    }
```

here is a snippet from the `JSONB` class, that didn't exist in `3.14.x`

i find it very hard to figure out intention behind parsing and serializing back to string

but for sure it will generate a ton for garbage and have a performance hit

**Comment by lukaseder** [comment]
> i find it very hard to figure out intention behind parsing and serializing back to string

It's not all that hard, see:

- #12023

But that implementation isn't the real problem here. The real problem is that it is being called at all in your stack trace. So, the underlying problem is this:

- https://github.com/jOOQ/jOOQ/issues/11682

**Comment by lukaseder** [comment]
Looking into this, even if `toString()` calls may be avoidable, there is a risk of `hashCode()` and `equals()` calls in some call stacks.

One such call stack is when `ScopeMappable` internal functionality is applied to any `AbstractField`. This was introduced with #5810, and can produce a call stack like this:

```
java.lang.Throwable
	at org.jooq.JSONB.parsed(JSONB.java:102)
	at org.jooq.JSONB.hashCode(JSONB.java:116)
	at org.jooq.impl.AbstractParam.hashCode(AbstractParam.java:278)
	at java.base/java.util.HashMap.hash(HashMap.java:338)
	at java.base/java.util.HashMap.getNode(HashMap.java:568)
	at java.base/java.util.LinkedHashMap.get(LinkedHashMap.java:441)
	at org.jooq.impl.ScopeStack.listOrNull(ScopeStack.java:233)
	at org.jooq.impl.ScopeStack.get(ScopeStack.java:198)
	at org.jooq.impl.DefaultRenderContext.scopeMapping(DefaultRenderContext.java:204)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:292)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:260)
	at org.jooq.impl.Eq.lambda$2(Eq.java:104)
	at org.jooq.impl.Eq.acceptCompareCondition(Eq.java:155)
	at org.jooq.impl.Eq.accept(Eq.java:104)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:350)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:255)
	at org.jooq.impl.ConditionAsField.accept(ConditionAsField.java:129)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:301)
	at org.jooq.impl.QueryPartCollectionView.acceptElement(QueryPartCollectionView.java:251)
	at org.jooq.impl.SelectFieldList.lambda$1(SelectFieldList.java:93)
	at org.jooq.impl.Tools.visitAutoAliased(Tools.java:2811)
	at org.jooq.impl.SelectFieldList.acceptElement0(SelectFieldList.java:93)
	at org.jooq.impl.SelectFieldList.acceptElement(SelectFieldList.java:89)
	at org.jooq.impl.SelectFieldList.acceptElement(SelectFieldList.java:1)
	at org.jooq.impl.QueryPartCollectionView.accept(QueryPartCollectionView.java:223)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:350)
	at org.jooq.impl.SelectQueryImpl.toSQLReference0(SelectQueryImpl.java:2327)
	at org.jooq.impl.SelectQueryImpl.lambda$36(SelectQueryImpl.java:1981)
	at org.jooq.impl.AbstractContext.toggle(AbstractContext.java:393)
	at org.jooq.impl.AbstractContext.data(AbstractContext.java:404)
	at org.jooq.impl.SelectQueryImpl.toSQLReferenceLimitDefault(SelectQueryImpl.java:1981)
	at org.jooq.impl.SelectQueryImpl.accept0(SelectQueryImpl.java:1876)
	at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:1504)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:350)
	at org.jooq.impl.DefaultDSLContext.render(DefaultDSLContext.java:734)
	at org.jooq.impl.AbstractAttachableQueryPart.getSQL(AbstractAttachableQueryPart.java:121)
	at org.jooq.impl.AbstractAttachableQueryPart.getSQL(AbstractAttachableQueryPart.java:114)
	at org.jooq.impl.AbstractDelegatingQuery.getSQL(AbstractDelegatingQuery.java:95)
	at org.jooq.test.benchmarks.ci.BenchmarkRenderingJSONBBinds.testRender(BenchmarkRenderingJSONBBinds.java:52)
	at org.jooq.test.benchmarks.ci.BenchmarkRenderingJSONBBinds.main(BenchmarkRenderingJSONBBinds.java:64)
```

Making all `AbstractField` implement `ScopeMappable` may be a bit exaggerated, especially since this change was implemented only for #5810 (`QUALIFY` emulation).

Anyway. I'm sure I can get this sorted, soon.

**Comment by lukaseder** [comment]
So, the 2 main reasons for the regression are:

- https://github.com/jOOQ/jOOQ/issues/14730
- https://github.com/jOOQ/jOOQ/issues/14731

In a benchmark that does something similar to your query, I've achieved a very significant improvement (more is better):

**Before**:

```
Benchmark               Mode  Cnt       Score       Error  Units
JSONBBinds.testRender  thrpt    7  176464.389 ± 19017.534  ops/s
```

**After**:

```
Benchmark               Mode  Cnt       Score       Error  Units
JSONBBinds.testRender  thrpt    7  395067.232 ± 16402.558  ops/s
```

The benchmark being:

```java
@Fork(value = 1, jvmArgsAppend = "-Dorg.jooq.no-logo=true")
@Warmup(iterations = 3, time = 3)
@Measurement(iterations = 7, time = 3)
@State(Scope.Benchmark)
public class JSONBBinds {

    @State(Scope.Benchmark)
    public static class BenchmarkState {

        DSLContext ctx;

        @Setup(Level.Trial)
        public void setup() {
            ctx = DSL.using(SQLDialect.H2);
        }
    }

    static Query query(DSLContext ctx) {
        return ctx.update(table(name("t")))
                  .set(field(name("f"), SQLDataType.JSONB), JSONB.jsonb("[]"));
    }

    @Benchmark
    public String testRender(BenchmarkState state) {
        return query(state.ctx).getSQL();
    }
}
```

I'll continue investigating more cases, tomorrow. While I still think that the improvements in https://github.com/jOOQ/jOOQ/issues/12023 were valuable (though risky) in terms of usability of the `JSONB` type in jOOQ, we obviously shouldn't normalise the input JSON content unless strictly necessary.

I'll keep this issue open for further investigation, so you get notifications. You can already try building the latest snapshot builds yourself (3.18.0, 3.17.9, or 3.16.15), or download them from here after tonight, if your licensed: https://www.jooq.org/download/versions. Would love to hear your confirmation of the fix (or further feedback about remaining issues).

**Comment by lukaseder** [comment]
Fixed via:


- https://github.com/jOOQ/jOOQ/issues/14730
- https://github.com/jOOQ/jOOQ/issues/14731

**Comment by lukaseder** [comment]
Possibly related: https://github.com/jOOQ/jOOQ/issues/14935
