### ISSUE TITLE
Avoid dialect version lookup in AbstractDatabase, if unnecessary

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14764]
jOOQ 3.14 introduced an automatic dialect version lookup in `AbstractDatabase` to override the default: https://github.com/jOOQ/jOOQ/issues/9834

This may be unnecessary:

- The user already configured a versioned dialect, as opposed to the family
- The dialect isn't versioned

Some dialects may be potentially slow to look up versions, e.g. Trino has a bug here:

- https://github.com/trinodb/trino/issues/16464

Producing:

<img width="875" alt="image" src="https://user-images.githubusercontent.com/734593/223979740-9da2e715-f090-4ddd-a535-f25b87e6e257.png">

**Comment by djarnis73** [comment]
I'm not sure if this is related to this issue, but I have a unit test that uses a MockConnection/MockProvider that now logs a stack trace:
```
09:35:52.665 [main] ERROR org.jooq.impl.DefaultExecuteContext.logVersionSupport - Error reading database version
java.sql.SQLFeatureNotSupportedException: Unsupported Operation
	at org.jooq.tools.jdbc.MockConnection.getMetaData(MockConnection.java:417) ~[jooq-3.16.16.jar:na]
	at org.jooq.impl.DefaultExecuteContext.connection(DefaultExecuteContext.java:571) ~[jooq-3.16.16.jar:na]
	at org.jooq.impl.DefaultExecuteContext.connection(DefaultExecuteContext.java:553) ~[jooq-3.16.16.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:295) ~[jooq-3.16.16.jar:na]
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:295) ~[jooq-3.16.16.jar:na]
	at org.jooq.impl.SelectImpl.fetchLazy(SelectImpl.java:2862) ~[jooq-3.16.16.jar:na]
	at org.jooq.impl.DefaultDSLContext.fetchLazy(DefaultDSLContext.java:5004) ~[jooq-3.16.16.jar:na]
	at org.jooq.impl.DefaultDSLContext.fetchOne(DefaultDSLContext.java:4800) ~[jooq-3.16.16.jar:na]
	at org.jooq.impl.DefaultDSLContext.fetchOne(DefaultDSLContext.java:4795) ~[jooq-3.16.16.jar:na]
```
when doing:
```
        MockProvider mockProvider = new MyMockProvider();
        MockConnection connection = new MockConnection(mockProvider);
        DSLContext create = DSL.using(connection, SQLDialect.H2);
        create.fetchOne(MY_TABLE);
```
It started doing it after I moved from 3.16.14 to 3.16.15 but still shows it on 3.16.16.

Would it make sense to also not query version for mock connections?

**Comment by lukaseder** [comment]
> Thanks, @djarnis73. can you please create a new issue?

Nevermind, I've seen that github now has a new feature to turn a comment into an issue: https://github.com/jOOQ/jOOQ/issues/14833
