### ISSUE TITLE
Version support check shouldn't fail for MockConnection

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14833]
I'm not sure if this is related to this issue, but I have a unit test that uses a MockConnection/MockProvider that now logs a stack trace:
```
09:35:52.665 [main] ERROR org.jooq.impl.DefaultExecuteContext.logVersionSupport - Error reading database version
java.sql.SQLFeatureNotSupportedException: Unsupported Operation
	at org.jooq.tools.jdbc.MockConnection.getMetaData(MockConnection.java:417) ~[jooq-3.16.16.jar:na]
	at org.jooq.impl.DefaultExecuteContext.connection(DefaultExecuteContext.java:571) ~[jooq-3.16.16.jar:na]
	at org.jooq.impl.DefaultExecuteContext.connection(DefaultExecuteContext.java:553) ~[jooq-3.16.16.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:295) ~[jooq-3.16.16.jar:na]
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:295) ~[jooq-3.16.16.jar:na]
	at org.jooq.impl.SelectImpl.fetchLazy(SelectImpl.java:2862) ~[jooq-3.16.16.jar:na]
	at org.jooq.impl.DefaultDSLContext.fetchLazy(DefaultDSLContext.java:5004) ~[jooq-3.16.16.jar:na]
	at org.jooq.impl.DefaultDSLContext.fetchOne(DefaultDSLContext.java:4800) ~[jooq-3.16.16.jar:na]
	at org.jooq.impl.DefaultDSLContext.fetchOne(DefaultDSLContext.java:4795) ~[jooq-3.16.16.jar:na]
```
when doing:
```
        MockProvider mockProvider = new MyMockProvider();
        MockConnection connection = new MockConnection(mockProvider);
        DSLContext create = DSL.using(connection, SQLDialect.H2);
        create.fetchOne(MY_TABLE);
```
It started doing it after I moved from 3.16.14 to 3.16.15 but still shows it on 3.16.16.

Would it make sense to also not query version for mock connections?

_Originally posted by @djarnis73 in https://github.com/jOOQ/jOOQ/issues/14764#issuecomment-1479256652_

**Comment by lukaseder** [comment]
This is not really related to `MockConnection`. Any `SQLException` that arises from trying to read that meta information should be ignored. (i.e. `INFO` logged with the message, rather than `ERROR` logged, with the stack trace).

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.19.0, 3.18.2 (https://github.com/jOOQ/jOOQ/issues/14834), 3.17.11 (https://github.com/jOOQ/jOOQ/issues/14835), and 3.16.17 (https://github.com/jOOQ/jOOQ/issues/14836)
