### ISSUE TITLE
Implement BatchCRUD::subscribe

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14874]
This is currently not possible:

```java
Flux.from(r2dbc().batchInsert(a3, a4));
```

We're getting:

```
java.lang.UnsupportedOperationException
	at org.jooq.impl.AbstractBatch.subscribe(AbstractBatch.java:72)
	at reactor.core.publisher.FluxSource.subscribe(FluxSource.java:67)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4485)
	at reactor.core.publisher.Mono.block(Mono.java:1709)
	at org.jooq.test.all.testcases.R2DBCTests.testR2DBCBatchCRUD(R2DBCTests.java:955)
	at org.jooq.test.jOOQAbstractTest.testR2DBCBatchCRUD(jOOQAbstractTest.java:3090)
```

The implementation shows it's not implemented yet:

```java
@Override
public void subscribe(Subscriber<? super Integer> s) {

    // [#11700] TODO: Implement this
    throw new UnsupportedOperationException();
}
```

**Comment by therealansh** [comment]
@lukaseder hey, is this WIP or any specific blocker to implement this?

**Comment by lukaseder** [comment]
No "blocker" but:

1. It's quite some work
2. It's not a high priority in itself
3. R2DBC support as a whole has proven to be the temporary clutch that it is, especially now that Loom has shipped with the JDK and I'm expecting more and more users to move back to a "blocking," JDBC based approach (which further decreases the priority of this)

**Comment by krloxz** [comment]
Hi @lukaseder, I'm doing the following to overcome this limitation, is this an approach you would recommend?
```java
Flux.from(
  r2dbc().batch(
    r2dbc().insertInto(TABLE).set(record1),
    r2dbc().insertInto(TABLE).set(record2)));

**Comment by lukaseder** [comment]
I don't recommend any specific approach. I've never benchmarked various approaches to `INSERT` queries with R2DBC across dialects. Yours is one possibility (sending multiple queries). There's also the possibility of sending only one query with multiple bind variable sets. Then, there's bulk insertions, i.e. multiple records in a single insert.

**Comment by krloxz** [comment]
Thank you @lukaseder. Not that it has to, because by the way JOOQ is already an awesome library, but still a question I have; do you see JOOQ support for R2DBC incresing in the future?

**Comment by lukaseder** [comment]
> do you see JOOQ support for R2DBC incresing in the future?

Obviously, bugs should be fixed as they cause issues with existing integrations, but for more complex features like this one here, or things like stored procedure support, DAO integration, import / export, etc., it's hard to be optimistic about cost/benefit in the mid-term, knowing jOOQ will never cover 100% feature parity between JDBC and R2DBC integrations. I personally believe that project Loom, which has started delivering to the JDK, will render most of the "reasonable" benefits of reactive programming models obsolete, i.e. getting better concurrency behaviour without giving up on structured, sequential programming. Not today, but within the next 10 years.

Looking at all the very complicated past bugs of the jOOQ / R2DBC integration, I will be very glad to remove this experiment again in the mid/far future, when JDBC drivers start adopting Loom APIs internally. 

The main reason for adoption at the time was marketing (jOOQ had to offer *something*), not a personal conviction. R2DBC did seem quite promising at the time. I was hoping, the (mostly) Spring folks would be able to establish a new de-facto standard similar to JDBC for this topic. I was glad to help review their early API drafts from a jOOQ perspective. But the Quarkus (Vertx) folks proved them wrong, and this strategic divide was never overcome so far, contributing to what I think turned into a "stalemate," where both R2DBC and Vertx have stopped adding new drivers. The most popular RDBMS are covered, but only very few others are integrating. This isn't a good sign, and it hasn't been for years.

I've always been very skeptical of the reactive programming model. Push instead of pull puts a very heavy burden upon the programmer, making the simplest things incredibly complicated. Every simple `for` loop turns into a stream full of map/flatMap/etc. operations. Without first class language support (such as e.g. in Scala with its `for` comprehension), this syntactic overhead means that infrastructure logic takes up way more space than business logic, which is a terrible thing, similar to what EJB 2 did, at the time.

So, to answer your question, I doubt that jOOQ support for R2DBC will increase significantly in the future.

**Comment by krloxz** [comment]
Thank you @lukaseder, I appreciate the detailed answer.
