### ISSUE TITLE
Migration issue from jooq 3.6.4 to 3.18.1: org.jooq.exception.DataAccessException: Key ambiguous between tables

### ISSUE THREAD

**Issue by pietrol83** [jOOQ/jOOQ#14870]
hi I have the same problem. I've migrating my code with jooq form version 3.6.4 to 3.18.1. The queries in my code are the same in both versions but with version 3.6.4 of jooq it work and with version 3.18.1 doesn't. one of the queries is:

```java
SelectConditionStep<Record6<Long, Long, Long,Long,String,Short>>  qry=DSLUtil.getContext()
				.select(MP_OPERATION.AMOUNT_1,
						MP_OPERATION.AMOUNT_2,
						MP_OPERATION.AMOUNT_3,
						MP_CART.CR_ID,
						MP_CART.SOURCE_ACCESS,
						MP_PRODUCT_TYPE.PT_ID
						)
                .from(MP_OPERATION)
                .join(MP_CART).onKey()                
                .join(MP_PAYMENT).onKey()
                .join(MP_PRODUCT_TYPE).onKey()
                .where(buildPaymentInstrumentCondition(paymentInstruments)
                        .and(buildAccessSourceCondition(sources))
                        .and(MP_PRODUCT_TYPE.PT_CATEGORY.equal(paymentCategory.name()))
                        .and(MP_PAYMENT.PYS_CODE.equal(Configuration.PaymentStatus.CON.toString()))
                        .and(MP_PAYMENT.TS_EXE.between(interval[0], interval[1])));
```
and the exception is:

```
org.jooq.exception.DataAccessException: Key ambiguous between tables ["MDP"."MP_OPERATION"
  join "MDP"."MP_CART"
    on "MDP"."MP_OPERATION"."CR_ID" = "MDP"."MP_CART"."CR_ID"] and ["MDP"."MP_PAYMENT"]. Found: null and null
	at org.jooq.impl.JoinTable.onKeyException(JoinTable.java:829) ~[jooq-3.18.1.jar:na]
	at org.jooq.impl.JoinTable.onKey(JoinTable.java:738) ~[jooq-3.18.1.jar:na]
	at org.jooq.impl.JoinTable.onKey(JoinTable.java:158) ~[jooq-3.18.1.jar:na]
	at org.jooq.impl.SelectQueryImpl.addJoinOnKey(SelectQueryImpl.java:4674) ~[jooq-3.18.1.jar:na]
	at org.jooq.impl.SelectImpl.onKey(SelectImpl.java:2191) ~[jooq-3.18.1.jar:na]
	at org.jooq.impl.SelectImpl.onKey(SelectImpl.java:144) ~[jooq-3.18.1.jar:na]
	at eu.sia.mdp.batch.tasks.vposdb.Calculate.execute(Calculate.java:96) ~[_wl_cls_gen.jar:na]
	at eu.sia.mdp.batch.Batch.executeTask(Batch.java:136) ~[_wl_cls_gen.jar:na]
	at eu.sia.mdp.batch.Batch.execute(Batch.java:79) ~[_wl_cls_gen.jar:na]
	at eu.sia.mdp.batch.VPOS_DB.execute(VPOS_DB.java:16) [_wl_cls_gen.jar:na]
	at eu.sia.mdp.batch.scheduler.Job.doCall(Job.java:89) [_wl_cls_gen.jar:na]
	at eu.sia.mdp.batch.scheduler.Job.doCall(Job.java:25) [_wl_cls_gen.jar:na]
	at eu.sia.mdp.batch.factory.BaseCallable.call(BaseCallable.java:26) [_wl_cls_gen.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_331]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_331]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_331]
	at java.lang.Thread.run(Thread.java:750) [na:1.8.0_331]
```
how can resolve this problem? I'm using a trial version for evaluate the correct behavior of the code before buy the professional version.

the crate table for the first three tables are

```sql
CREATE TABLE "MDP"."MP_OPERATION" 
   (	"OP_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10053 CACHE 20 NOORDER  NOCYCLE  NOT NULL ENABLE, 
	"CR_ID" NUMBER NOT NULL ENABLE, 
	"PY_ID" NUMBER NOT NULL ENABLE, 
	"PT_ID" NUMBER(3,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_OPERATION" PRIMARY KEY ("OP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MDP_DATA"  ENABLE, 
	 CONSTRAINT "MP_CART_OPERATION_FK" FOREIGN KEY ("CR_ID")
	  REFERENCES "MDP"."MP_CART" ("CR_ID") DEFERRABLE ENABLE, 
	 CONSTRAINT "MP_PROD_TYPE_PAYMENTS_FK" FOREIGN KEY ("PT_ID")
	  REFERENCES "MDP"."MP_PRODUCT_TYPE" ("PT_ID") DEFERRABLE ENABLE, 
	 CONSTRAINT "MP_PAYMENT_OPERATION_FK" FOREIGN KEY ("PY_ID")
	  REFERENCES "MDP"."MP_PAYMENT" ("PY_ID") DEFERRABLE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MDP_DATA" 
  PARTITION BY RANGE ("TS_INS") INTERVAL (NUMTOYMINTERVAL(1,'MONTH')) 
 (PARTITION "MP_OPERATION_01"  VALUES LESS THAN (TIMESTAMP' 2015-11-01 00:00:00') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MDP_DATA" ) ;
```

```sql
CREATE TABLE "MDP"."MP_CART" 
   (	"CR_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 8594 CACHE 20 NOORDER  NOCYCLE  NOT NULL ENABLE, 
	 CONSTRAINT "PK_CART" PRIMARY KEY ("CR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MDP_DATA"  ENABLE, 
	 ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MDP_DATA" 
  PARTITION BY RANGE ("TS_INS") INTERVAL (NUMTOYMINTERVAL(1,'MONTH')) 
 (PARTITION "MP_CART_01"  VALUES LESS THAN (TIMESTAMP' 2015-11-01 00:00:00') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MDP_DATA" ) ;
```

```sql
CREATE TABLE "MDP"."MP_PAYMENT" 
   (	"PY_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 8594 CACHE 20 NOORDER  NOCYCLE  NOT NULL ENABLE, 
	"CR_ID" NUMBER NOT NULL ENABLE, 
	CONSTRAINT "PK_PAYMENT" PRIMARY KEY ("PY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MDP_DATA"  ENABLE, 
	 CONSTRAINT "MP_CART_PAYMENT_FK" FOREIGN KEY ("CR_ID")
	  REFERENCES "MDP"."MP_CART" ("CR_ID") DEFERRABLE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MDP_DATA" 
  PARTITION BY RANGE ("TS_INS") INTERVAL (NUMTOYMINTERVAL(1,'MONTH')) 
 (PARTITION "MP_PAYMENT_01"  VALUES LESS THAN (TIMESTAMP' 2015-11-01 00:00:00') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MDP_DATA" ) ;
```

**Comment by lukaseder** [comment]
Thanks a lot for your report. I'll try to reproduce this, soon and will get back to you.

**Comment by lukaseder** [comment]
I see, I'm not sure if this is a bug or if it happened to "work" by accident before? We've fixed numerous problems in the area of correctly resolving the `ON KEY` clause. In your case, there's really an ambiguity between these tables:

```sql
CREATE TABLE "MDP"."MP_OPERATION" (
	"OP_ID" NUMBER, 
	"CR_ID" NUMBER NOT NULL ENABLE, 
	"PY_ID" NUMBER NOT NULL ENABLE, 
	"PT_ID" NUMBER(3,0) NOT NULL ENABLE, 
        -- ...
	 CONSTRAINT "MP_CART_OPERATION_FK" FOREIGN KEY ("CR_ID")
	  REFERENCES "MDP"."MP_CART" ("CR_ID") DEFERRABLE ENABLE, 
	 CONSTRAINT "MP_PAYMENT_OPERATION_FK" FOREIGN KEY ("PY_ID")
	  REFERENCES "MDP"."MP_PAYMENT" ("PY_ID") DEFERRABLE ENABLE
);

CREATE TABLE "MDP"."MP_CART" (
	"CR_ID" NUMBER, 
);

CREATE TABLE "MDP"."MP_PAYMENT" (
	"PY_ID" NUMBER, 
	"CR_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "MP_CART_PAYMENT_FK" FOREIGN KEY ("CR_ID")
	  REFERENCES "MDP"."MP_CART" ("CR_ID") DEFERRABLE ENABLE
);
```

As you can see, 

- `MP_OPERATION(PY_ID)` points to `MP_PAYMENT`
- `MP_OPERATION(CR_ID)` points to `MP_CART`
- `MP_PAYMENT(CR_ID)` also points to `MP_CART`

So when you write

```java
.join(MP_PAYMENT).onKey()
```

Should that produce

- `MP_PAYMENT JOIN MP_CART USING (CR_ID)` 
- `MP_PAYMENT JOIN MP_OPERATION USING (PY_ID)`

It's ambiguous, so jOOQ rejects it.

Some additional notes:

- There's a weak case to be made in favour of joining using both paths, but that quickly falls apart when such joins are not intentional / nonsensical.
- I'm not sure if this really worked correctly in jOOQ 3.6.4. Did it? What query did you get from this? What would be your intention here?
- You can explicitly disambiguate the join by passing the foreign key to `onKey()`, or using an ordinary `on(Condition)` clause
- Starting from jOOQ 3.11, we support implicit, path based joins: https://blog.jooq.org/using-jooqs-implicit-join-from-within-the-join-on-clause/. These are much more powerful and convenient, and never run into ambiguities.

I hope this helps.

**Comment by pietrol83** [comment]
``> ```sql
> 	"CR_ID" NUMBER, 
> ```

I apologize, but in copying and pasting the CREATE TABLES from the DB (I eliminated a few fields from the code that are not needed for the case) I may have missed some constraints: the appropriate CREATE TABLES are the following:

```
CREATE TABLE "MDP"."MP_OPERATION" 
   (	"OP_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10053 CACHE 20 NOORDER  NOCYCLE  NOT NULL ENABLE, 
	"CR_ID" NUMBER NOT NULL ENABLE, 
	"PY_ID" NUMBER NOT NULL ENABLE, 
	"PT_ID" NUMBER(3,0) NOT NULL ENABLE, 
	"TS_UPD" TIMESTAMP (6), 
	"TS_EXE" TIMESTAMP (6), 
	"TS_INS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 CONSTRAINT "PK_OPERATION" PRIMARY KEY ("OP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MDP_DATA"  ENABLE, 
	 CONSTRAINT "MP_CART_OPERATION_FK" FOREIGN KEY ("CR_ID")
	  REFERENCES "MDP"."MP_CART" ("CR_ID") DEFERRABLE ENABLE, 
	 CONSTRAINT "MP_PROD_TYPE_PAYMENTS_FK" FOREIGN KEY ("PT_ID")
	  REFERENCES "MDP"."MP_PRODUCT_TYPE" ("PT_ID") DEFERRABLE ENABLE, 
	 CONSTRAINT "MP_PAYMENT_OPERATION_FK" FOREIGN KEY ("PY_ID")
	  REFERENCES "MDP"."MP_PAYMENT" ("PY_ID") DEFERRABLE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MDP_DATA" 
  PARTITION BY RANGE ("TS_INS") INTERVAL (NUMTOYMINTERVAL(1,'MONTH')) 
 (PARTITION "MP_OPERATION_01"  VALUES LESS THAN (TIMESTAMP' 2015-11-01 00:00:00') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MDP_DATA" ) ;
```

```
CREATE TABLE "MDP"."MP_CART" 
   (	"CR_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 8594 CACHE 20 NOORDER  NOCYCLE  NOT NULL ENABLE, 
	"TS_INS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 CONSTRAINT "PK_CART" PRIMARY KEY ("CR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MDP_DATA"  ENABLE, ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MDP_DATA" 
  PARTITION BY RANGE ("TS_INS") INTERVAL (NUMTOYMINTERVAL(1,'MONTH')) 
 (PARTITION "MP_CART_01"  VALUES LESS THAN (TIMESTAMP' 2015-11-01 00:00:00') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MDP_DATA" ) ;
```

```
CREATE TABLE "MDP"."MP_PAYMENT" 
   (	"PY_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 8594 CACHE 20 NOORDER  NOCYCLE  NOT NULL ENABLE, 
	"CR_ID" NUMBER NOT NULL ENABLE, 
	"TS_INS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"TS_UPD" TIMESTAMP (6), 
	"TS_EXE" TIMESTAMP (6), 
	 CONSTRAINT "PK_PAYMENT" PRIMARY KEY ("PY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MDP_DATA"  ENABLE, 
	 CONSTRAINT "MP_CART_PAYMENT_FK" FOREIGN KEY ("CR_ID")
	  REFERENCES "MDP"."MP_CART" ("CR_ID") DEFERRABLE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MDP_DATA" 
  PARTITION BY RANGE ("TS_INS") INTERVAL (NUMTOYMINTERVAL(1,'MONTH')) 
 (PARTITION "MP_PAYMENT_01"  VALUES LESS THAN (TIMESTAMP' 2015-11-01 00:00:00') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MDP_DATA" ) ;
```

**Comment by lukaseder** [comment]
> I apologize, but in copying and pasting the CREATE TABLES from the DB (I eliminated a few fields from the code that are not needed for the case) I may have missed some constraints: the appropriate CREATE TABLES are the following:

I removed them on my end to show only the relevant bits to illustrate the case. Check out the `FOREIGN KEY` declarations between the tables. They form a triangle, meaning by the time you add the second join, the triangle produces an ambiguity.

Does this make sense?

**Comment by pietrol83** [comment]
> 

to answer the second point you listed, below is the log of the same query that was performed with jooq version 3.6.4. As you can see, even though no matching records were found, the query was executed.

```
select "MDP"."MP_OPERATION"."AMOUNT_1", 
"MDP"."MP_OPERATION"."AMOUNT_2", "MDP"."MP_OPERATION"."AMOUNT_3", "MDP"."MP_CART"."CR_ID", "MDP"."MP_CART"."SOURCE_ACCESS", "MDP"."MP_PRODUCT_TYPE"."PT_ID" 
from "MDP"."MP_OPERATION" 
	join "MDP"."MP_CART" on "MDP"."MP_OPERATION"."CR_ID" = "MDP"."MP_CART"."CR_ID" 
	join "MDP"."MP_PAYMENT" on "MDP"."MP_OPERATION"."PY_ID" = "MDP"."MP_PAYMENT"."PY_ID" 
	join "MDP"."MP_PRODUCT_TYPE" on "MDP"."MP_OPERATION"."PT_ID" = "MDP"."MP_PRODUCT_TYPE"."PT_ID" 
where ("MDP"."MP_PAYMENT"."PI_CODE" = 'BTN' 
	and "MDP"."MP_CART"."SOURCE_ACCESS" = 'PNT' 
	and "MDP"."MP_PRODUCT_TYPE"."PT_CATEGORY" = 'BOL' 
	and "MDP"."MP_PAYMENT"."PYS_CODE" = 'CON' 
	and "MDP"."MP_PAYMENT"."TS_EXE" between timestamp '2022-09-26 00:00:00.0' 
	and timestamp '2022-09-26 23:59:59.999') (0 row(s) returned)
```

**Comment by lukaseder** [comment]
Thanks for the confirmation. I see, so the `ON KEY` join algorithm just picked 1 of the 2 possible foreign keys, probably depending on the order of appearance, but that must have been incidental.

I've created an issue to add some documentation warnings about this API, discouraging its broad use for queries where ambiguities can arise: https://github.com/jOOQ/jOOQ/issues/14876

It also lists all the past bugs that have been fixed for the `ON KEY` clause:


- https://github.com/jOOQ/jOOQ/issues/2870
- https://github.com/jOOQ/jOOQ/issues/4637
- https://github.com/jOOQ/jOOQ/issues/5209
- https://github.com/jOOQ/jOOQ/issues/6266
- https://github.com/jOOQ/jOOQ/issues/7626
- https://github.com/jOOQ/jOOQ/issues/12200
- https://github.com/jOOQ/jOOQ/issues/12214
- https://github.com/jOOQ/jOOQ/issues/14668
- https://github.com/jOOQ/jOOQ/issues/14671
- https://github.com/jOOQ/jOOQ/issues/14870

One of these bugs must have added the ambiguity exception in your case.

Please let me know if I can be of any further assistance in this matter.
