### ISSUE TITLE
Unable to use stream or cursor against Postgres timestamp/timestamptz - not using codegen

### ISSUE THREAD

**Issue by simon-mottram-cucumber** [jOOQ/jOOQ#14936]
### Expected behavior

Return a valid timestamp

### Actual behavior

When I try to stream or use a cursor with a timestamp or timestamptz column.  I get the exception below:

I am not using codegen,  I am generating SQL programmatically, codegen is not an option.

I'm creating the dsl using the following code, I have tried SQLDialect.YUGABYTEDB same result
    
    private static final SQLDialect dialect = SQLDialect.POSTGRES;

    public AutoCloseableDSLContext getDSL() throws SQLException {
        return new AutoCloseableDSLContext(new ClosingConnectionProvider(dataSource.getConnection()), dialect);    
    }

The code I'm using to get the stream is simple.

    public static Stream<Record> fetchJDBCResultSetAsStream(SelectForUpdateStep<Record> select) {
        return select.fetchStream();
    }

The query is super simple, if I copy the query generated it is 

```sql
select 
  "observation_date" as "OBSERVATION_DATE", 
  "trial_name" as "TRIAL_NAME", 
  "biomaterial_name" as "BIOMATERIAL_NAME", 
  "biomaterial_type" as "BIOMATERIAL_TYPE", 
  "observation_name" as "OBSERVATION_NAME", 
  "observation_value" as "OBSERVATION_VALUE" 
from "observation"
```

If I run this in say Dbeaver all is fine, I get a result set.
If I use Jooq fetchResultSet() then all is fine and I get a result set.

If I try to use stream or cursor the very first fetchNext() causes the exception below.  I can see various examples of configuring Codegen to handle custom bindings (but why should timestamp need a custom binding??).  I have scoured google but I see no mention of how to change binding behaviour for fetchNext() when NOT using codegen;

How can I work around this?  I am out of ideas.  I just need a Map of values really.  I've tried using a RecordMapper but the call to fetchNext deep in jooq code is executed before the mapper is called.

The DDL for the table (truncated as it's quite long)

```sql
CREATE TABLE public.observation (
	tsid int8 NOT NULL,
	biomaterial_id uuid NOT NULL,
	biomaterial_name varchar NOT NULL,
	biomaterial_type varchar NOT NULL,
	observation_date timestamp NOT NULL,
...
```

```
Caused by: java.sql.SQLException: Error while reading field: "OBSERVATION_DATE", at JDBC index: 1
	at org.jooq.impl.CursorImpl$CursorRecordInitialiser.setValue(CursorImpl.java:1591) ~[jooq-3.18.3.jar:na]
	at org.jooq.impl.CursorImpl$CursorRecordInitialiser.apply(CursorImpl.java:1517) ~[jooq-3.18.3.jar:na]
	at org.jooq.impl.CursorImpl$CursorRecordInitialiser.apply(CursorImpl.java:1432) ~[jooq-3.18.3.jar:na]
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144) ~[jooq-3.18.3.jar:na]
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1389) ~[jooq-3.18.3.jar:na]
	... 63 common frames omitted
Caused by: org.jooq.exception.DataTypeException: Cannot convert from 1652144039 (class java.lang.Long) to class java.util.UUID
	at org.jooq.impl.Convert$ConvertAll.fail(Convert.java:1591) ~[jooq-3.18.3.jar:na]
	at org.jooq.impl.Convert$ConvertAll.toDate(Convert.java:1536) ~[jooq-3.18.3.jar:na]
	at org.jooq.impl.Convert$ConvertAll.from(Convert.java:977) ~[jooq-3.18.3.jar:na]
	at org.jooq.impl.Convert.convert0(Convert.java:442) ~[jooq-3.18.3.jar:na]
	at org.jooq.impl.Convert.convert(Convert.java:517) ~[jooq-3.18.3.jar:na]
	at org.jooq.impl.DefaultBinding$DefaultUUIDBinding.get0(DefaultBinding.java:4844) ~[jooq-3.18.3.jar:na]
	at org.jooq.impl.DefaultBinding$DefaultUUIDBinding.get0(DefaultBinding.java:4778) ~[jooq-3.18.3.jar:na]
	at org.jooq.impl.DefaultBinding$InternalBinding.get(DefaultBinding.java:1071) ~[jooq-3.18.3.jar:na]
	at org.jooq.impl.CursorImpl$CursorRecordInitialiser.setValue(CursorImpl.java:1581) ~[jooq-3.18.3.jar:na]
	... 67 common frames omitted
```

### Steps to reproduce the problem

When trying to 

### jOOQ Version

Jooq Community 3.18.3

### Database product and version

YugabyteDB  PostgreSQL 11.2-YB-2.17.2.0-b0 on x86_64-pc-linux-gnu, compiled by clang version 15.0.3 (https://github.com/yugabyte/llvm-project.git 0b8d1183745fd3998d8beffeec8cbe99c1b20529), 64-bit

### Java Version

Open JDK 17

### OS Version

Windows 10

### JDBC driver name and version (include name if unofficial driver)

com.yugabyte.jdbc-yugabytedb.42.3.4

**Comment by lukaseder** [comment]
Thanks for your message. My intuition tells me that your column indexes are off for some reason. This doesn't have to do anything with the timestamp column it seems. You're getting a `Long` value and you're expecting a `UUID` column instead.

How did you write the query? Can you post a complete, self contained example that helps reproduce the issue?

**Comment by simon-mottram-cucumber** [comment]
Hi, thanks very much for taking the time to help, that sounds reasonable except that there are no UUID columns in that query.   

I'm expecting a timestamp value, the field observation_date is a timestamp column, it was a timestamptz column, same issue.   If I remove the observation_date column from the query then it all works fine.   The same query also works fine  if i use fetchResultSet().  It's only breaking with fetchNext(), when used via cursor or stream.  Let me see if I can make a small project

**Comment by simon-mottram-cucumber** [comment]
The only numeric column in the table is the int8 tsid column which is the primary key, but it's never referenced as UUID and not included in the query given

**Comment by simon-mottram-cucumber** [comment]
Well that's a pain, was an error in the construction of the Field<> object.  Closing

**Comment by lukaseder** [comment]
Glad to hear you found the cause of the issue.
