### ISSUE TITLE
Wrong emulation of DISTINCT ON with UNION

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14965]
This test here fails:

```java
public void testDistinctOnQueryWithUnion() {
    Result<Record2<Integer, Integer>> r1 =
    create().selectDistinct(TBook_ID(), TBook_AUTHOR_ID())
            .on(TBook_AUTHOR_ID())
            .from(TBook())
            .unionAll(
                selectDistinct(TBook_ID(), TBook_AUTHOR_ID())
                .on(TBook_AUTHOR_ID())
                .from(TBook()))
            .orderBy(TBook_AUTHOR_ID(), TBook_ID())
            .fetch();

    assertEquals(asList(1, 1, 3, 3), r1.getValues(TBook_ID()));
    assertEquals(asList(1, 1, 2, 2), r1.getValues(TBook_AUTHOR_ID()));
}
```

The query produced is this one, on MySQL:

```sql
select `t`.`ID`, `t`.`AUTHOR_ID`
from (
  select distinct
    `test`.`t_book`.`ID`,
    `test`.`t_book`.`AUTHOR_ID`,
    row_number() over (partition by `test`.`t_book`.`AUTHOR_ID`) as `rn`
  from `test`.`t_book`
  union all
  select `t`.`ID`, `t`.`AUTHOR_ID`
  from (
    select distinct
      `test`.`t_book`.`ID`,
      `test`.`t_book`.`AUTHOR_ID`,
      row_number() over (partition by `test`.`t_book`.`AUTHOR_ID`) as `rn`
    from `test`.`t_book`
  ) as `t`
  where `rn` = 1
  order by `AUTHOR_ID`, `ID`
) as `t`
where `rn` = 1
```

The error is:

> The used SELECT statements have a different number of columns

Stack trace:

```
12:50:05,614 DEBUG [LoggerListener                ] - Exception                
org.jooq.exception.DataAccessException: SQL [select `t`.`ID`, `t`.`AUTHOR_ID` from (select distinct `test`.`t_book`.`ID`, `test`.`t_book`.`AUTHOR_ID`, row_number() over (partition by `test`.`t_book`.`AUTHOR_ID`) as `rn` from `test`.`t_book` union all select `t`.`ID`, `t`.`AUTHOR_ID` from (select distinct `test`.`t_book`.`ID`, `test`.`t_book`.`AUTHOR_ID`, row_number() over (partition by `test`.`t_book`.`AUTHOR_ID`) as `rn` from `test`.`t_book`) as `t` where `rn` = 1 order by `AUTHOR_ID`, `ID`) as `t` where `rn` = 1 -- SQL rendered with a free trial version of jOOQ 3.19.0-SNAPSHOT]; 
The used SELECT statements have a different number of columns
	at org.jooq_3.19.0-SNAPSHOT.MYSQL.debug(Unknown Source) ~[?:?]
	at org.jooq.impl.Tools.translate(Tools.java:3467) ~[classes/:?]
	at org.jooq.impl.Tools.translate(Tools.java:3455) ~[classes/:?]
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:772) ~[classes/:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:371) [classes/:?]
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:290) [classes/:?]
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2838) [classes/:?]
	at org.jooq.test.all.testcases.SelectTests.testDistinctOnQueryWithUnion(SelectTests.java:262) [test-classes/:?]
	at org.jooq.test.jOOQAbstractTest.testDistinctOnQueryWithUnion(jOOQAbstractTest.java:6149) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.13.2.jar:4.13.2]
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61) [junit-4.13.2.jar:4.13.2]
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) [junit-4.13.2.jar:4.13.2]
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
Caused by: java.sql.SQLException: The used SELECT statements have a different number of columns
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-j-8.0.31.jar:8.0.31]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-j-8.0.31.jar:8.0.31]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916) ~[mysql-connector-j-8.0.31.jar:8.0.31]
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354) ~[mysql-connector-j-8.0.31.jar:8.0.31]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219) ~[classes/:?]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219) ~[classes/:?]
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4758) ~[classes/:?]
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:236) ~[classes/:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:357) ~[classes/:?]
	... 36 more
```

**Comment by lukaseder** [comment]
Interestingly, the `LIMIT` emulation works correctly!

```java
public void testDistinctOnQueryWithLimitExpression() {
    Result<Record2<Integer, Integer>> r1 =
    create().selectDistinct(TBook_ID(), TBook_AUTHOR_ID())
            .on(TBook_AUTHOR_ID())
            .from(TBook())
            .orderBy(TBook_AUTHOR_ID(), TBook_ID())
            .limit(field(selectOne()))
            .fetch();

    assertEquals(asList(1), r1.getValues(TBook_ID()));
    assertEquals(asList(1), r1.getValues(TBook_AUTHOR_ID()));

    Result<Record2<Integer, Integer>> r2 =
    create().selectDistinct(TBook_ID(), TBook_AUTHOR_ID())
            .on(TBook_AUTHOR_ID())
            .from(TBook())
            .orderBy(TBook_AUTHOR_ID(), TBook_ID())
            .limit(field(selectOne()))
            .offset(field(selectOne()))
            .fetch();

    assertEquals(asList(3), r2.getValues(TBook_ID()));
    assertEquals(asList(2), r2.getValues(TBook_AUTHOR_ID()));
}
```

The two consecutive `ROW_NUMBER()` calculations are nested correctly:

```sql
select
  `v0` as `ID`,
  `v1` as `AUTHOR_ID`
from (
  select
    `t`.`ID` as `v0`,
    `t`.`AUTHOR_ID` as `v1`,
    row_number() over (order by `AUTHOR_ID`, `ID`) as `rn`
  from (
    select distinct
      `test`.`t_book`.`ID`,
      `test`.`t_book`.`AUTHOR_ID`,
      row_number() over (
        partition by `test`.`t_book`.`AUTHOR_ID`
        order by `test`.`t_book`.`AUTHOR_ID`, `test`.`t_book`.`ID`
      ) as `rn`
    from `test`.`t_book`
  ) as `t`
  where `rn` = 1
  order by `AUTHOR_ID`, `ID`
) `x`
where `rn` > (
  select 1 as `one`
)
and `rn` <= ((
  select 1 as `one`
) + (
  select 1 as `one`
))
order by `rn`
```
