### ISSUE TITLE
Allow for specifying explicit path joins

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14985]
Path joins are done implicitly since jOOQ 3.11's implicit join feature:
https://www.jooq.org/doc/latest/manual/sql-building/sql-statements/select-statement/implicit-join/

For example:

```java
ctx.select(
        BOOK.TITLE,
        BOOK.author().FIRST_NAME,
        BOOK.author().LAST_NAME)
   .from(BOOK)
   .fetch();
```

This produces a query similar to this one:

```sql
select
  t_book.TITLE,
  alias_33683684.FIRST_NAME,
  alias_33683684.LAST_NAME
from (
  t_book
    join t_author as alias_33683684
      on t_book.AUTHOR_ID = alias_33683684.ID
  )
```

Whether this produces a `JOIN` or a `LEFT JOIN` is currently governed by:

- Whether the foreign key is optional/nullable (optional = `LEFT JOIN`)
- The `Settings.renderImplicitJoinType` flag

See #10616 for details.

Users may want to be in control of the join type explicitly, per query, and maybe even specify using table lists, or any other type of join, so these should be possible:

**Table list**:

```java
ctx.select(
        BOOK.TITLE,
        BOOK.author().FIRST_NAME,
        BOOK.author().LAST_NAME)
   .from(BOOK, BOOK.author())
   .fetch();
```

**Join expression**

```java
ctx.select(
        BOOK.TITLE,
        BOOK.author().FIRST_NAME,
        BOOK.author().LAST_NAME)
   .from(BOOK.leftJoin(BOOK.author())
   .fetch();
```

Currently, this isn't possible. The table list example produces something like:

```sql
select t_book.TITLE, alias_33683684.FIRST_NAME
from
  (
    t_book
      join t_author as alias_33683684
        on t_book.AUTHOR_ID = alias_33683684.ID
    ),
  t_author as alias_33683684
```

And thus an error:

```
Caused by: org.postgresql.util.PSQLException: ERROR: table name "alias_33683684" specified more than once
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676) ~[postgresql-42.5.4.jar:42.5.4]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366) ~[postgresql-42.5.4.jar:42.5.4]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356) ~[postgresql-42.5.4.jar:42.5.4]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496) ~[postgresql-42.5.4.jar:42.5.4]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413) ~[postgresql-42.5.4.jar:42.5.4]
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190) ~[postgresql-42.5.4.jar:42.5.4]
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:177) ~[postgresql-42.5.4.jar:42.5.4]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219) ~[classes/:?]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219) ~[classes/:?]
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4759) ~[classes/:?]
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:236) ~[classes/:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:359) ~[classes/:?]
	... 36 more
```

The generated query should be, instead:

```sql
select t_book.TITLE, alias_33683684.FIRST_NAME
from
  t_book,
  t_author as alias_33683684
where t_book.AUTHOR_ID = alias_33683684.ID
```

### Specification:

There are two ways to implement this:

**Support this for all "reasonable" `JOIN` types**

Depending on the `JOIN` type, we should Do The Right Thing&trade;

- [ ] Table list and `CROSS JOIN`: The generated `JOIN` predicate gets prepended to the `WHERE` clause.
- [ ] `INNER JOIN` (including `STRAIGHT JOIN`), `LEFT JOIN`: The generated `JOIN` predicate gets prepended to the (optional?) `ON` clause.
- [ ] `LEFT SEMI JOIN` and `LEFT ANTI JOIN`: These are very elegant. Again the generated `JOIN` predicate gets prepended to the (optional?) `ON` clause.
- [ ] `CROSS APPLY` and `OUTER APPLY`: The joined table is queried from a derived table and the generated `JOIN` predicate gets pushed into the derived table.

`JOIN` features that have weird interactions with path joins:

- [ ] `NATURAL JOIN` or `JOIN USING` have conflicting semantics and don't really make sense, though it might be possible to support them
- [ ] `RIGHT JOIN`, `FULL JOIN`: The generated `JOIN` predicate gets prepended to the (optional?) `ON` clause, but the semantics is dubious because the path root may not be easy to resolve.
  - [ ] `RIGHT JOIN` could require `book.author RIGHT JOIN book` (reversing order)
  - [ ] `FULL JOIN` doesn't have any reasonable order resolution

**Support this only for dedicated `JOIN` types**

The above discussion shows that there are tons of edge cases. Explicit path joins have a strong `CROSS APPLY` / `OUTER APPLY` semantics attached to them, so it might make sense to support them only for:

- `CROSS APPLY` / `INNER JOIN` / `CROSS JOIN` / table lists
- `OUTER APPLY` / `LEFT OUTER JOIN`

**API design**

Irrespective of the chosen design, there are at least 3 ways to implement support for this in the API:

- [ ] Keep `ON` a mandatory (dummy) clause, forcing users to pass `true` to the `ON` clause. This would be a PITA, similar to SQL's `LEFT JOIN LATERAL (..) ON TRUE`
- [ ] Make `ON` an optional clause in general. This is the easiest approach, especially if all `JOIN` types are to be supported, but it would remove some type safety
- [ ] Introduce a new `PATH` keyword, such as `LEFT PATH JOIN`, which has an optional `ON` keyword in case additional `ON` conditions are to be added to the generated one
- [ ] Let path tables implement a marker interface (e.g. `AUTHOR.book()` would return `Book & Path<Book>`), and add new `JOIN` method overloads accepting that type

Some of the above options can be combined.

**Comment by lukaseder** [comment]
The specifications of this feature are very fuzzy, still. What should be done for this query, for example?

```sql
SELECT
  customer.first_name,
  customer.last_name,
  customer.address.street,
  customer.address.city.name,
  customer.address.city.country.name
FROM
  customer,
  customer.address.city
```

Or also:

```sql
```sql
SELECT
  customer.first_name,
  customer.last_name,
  customer.address.street,
  c.name,
  c.country.name
FROM
  customer,
  customer.address.city AS c
```

It mixes implicit path joins with explicit path joins, partially. It seems that the `FROM` table list should contain `customer` and `address`, and all other tables continue to be joined implicitly, as follows:

```sql
SELECT
  customer.first_name,
  customer.last_name,
  customer.address.street,
  customer.address.city.name,
  customer.address.city.country.name
FROM
  customer 
    LEFT JOIN address 
      ON customer.address_id = address.address_id,
  city 
    LEFT JOIN country 
      ON city.country_id = country.country_id
WHERE
  address.city_id = city.city_id
```

The `WHERE` clause effectively turns the `customer LEFT JOIN address` into a `customer JOIN address` operation, though in a more complex case, the syntactic subtleties might still produce a difference here.

**Comment by lukaseder** [comment]
As the implementation matures (it's not just a prototype, the very simple implementation works very well!), it becomes clear that this feature will be available for all `JOIN` types as well as correlated subqueries.

See examples here:

- `MULTISET`: https://github.com/jOOQ/jOOQ/issues/13639#issuecomment-1525749947
- Skipping path segment declarations: https://github.com/jOOQ/jOOQ/issues/13639#issuecomment-1525792978

**Comment by lukaseder** [comment]
I've been writing a few integration tests now with the mandatory `ON` condition. That's such a PITA:

```java
Result<Record1<Integer>> r1 =
create().select(a.A)
        .from(a)
        .leftAntiJoin(a.tA()).on(noCondition())
        .orderBy(a.A)
        .fetch();
```

It's clear that won't be the main approach here (though it's certainly an *option*)

Will experiment with type based API, but could also live with making `ON` optional for all `JOIN` types. After all:

- Some RDBMS also do this (e.g. MySQL for `JOIN` but not for `LEFT JOIN`)
- While a bit weird, the semantics of using `noCondition()` is clear

**Comment by lukaseder** [comment]
The generated `Path` subclasses have to override the `as()` methods, or we'll lose type safety there.

**Comment by lukaseder** [comment]
I've been able to implement this in the `JavaGenerator` and the `KotlinGenerator`. It seems much harder to do in the `ScalaGenerator`, as it's probably not possible to make explicit super constructor calls, so the `Path` subtype needs a different primary constructor, regrettably: https://github.com/jOOQ/jOOQ/issues/15265#issuecomment-1600459911

**Comment by lukaseder** [comment]
The `ScalaGenerator` improvement might be done later: https://github.com/jOOQ/jOOQ/issues/15266
