### ISSUE TITLE
Use awaitSingle instead of awaitFirstOrNull in transactionCoroutine to correctly sequence transaction script

### ISSUE THREAD

**Issue by jonathanswenson** [jOOQ/jOOQ#14997]
### Expected behavior

Wait for transaction to commit before returning (async) control back to to consumer. 

### Actual behavior

Control is returned back to consumer before transaction has committed.

### Steps to reproduce the problem

I've been using the transactionCoroutine wrapper to manage a transaction against a postgres database connection pool with r2dbc and r2dbc pool. 

I have some integration tests that run (in a transaction) some commands before committing. Something along the lines of: 
```
val config = DefaultConfiguration()
    .set(pool)
    .set(JDBCUtils.dialect(pool))

val dsl = DSL.using(config)

val updatedCount = dsl.transactionCoroutine { config ->
    val transactionDsl = config.dsl()
    ... some stuff
    transactionalDsl.update(...).awaitLast()
}

verifyTransactionResults(dsl)
```

Intermittently, the verification of the results will fail in a way that indicates that the transaction hadn't committed. If I turn OFF connection pooling I find that the intermittency goes away and the tests pass as expected. If I delay / sleep for a few MS before checking the intermittency goes away. 

An alternative implementation of transactionCoroutine using `.awaitLast()` rather than `.awaitFirstOrNull()` seems to solve the problem. 

In a tight loop, I can reproduce this every time. However, when trying against h2 I was unable to reproduce (though could be a function of removing the network latency). With H2, the transactionCoroutine implementation finished significantly faster. 

I tried to get set up with an jooq-mcve repro, but was unable to build the template -- got an error during `mvn verify`

didn't look too closely into what was happening, can work to get something working if that would be helpful.
```
[WARNING] The POM for org.jooq:jooq-mcve-utils:jar:1.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.242 s
[INFO] Finished at: 2023-05-01T17:42:35-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project jooq-mcve-kotlin-postgres: Could not resolve dependencies for project org.jooq:jooq-mcve-kotlin-postgres:jar:1.0: The following artifacts could not be resolved: org.jooq:jooq-mcve-utils:jar:1.0 (absent): org.jooq:jooq-mcve-utils:jar:1.0 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```

<details>
  <summary>full repro code here</summary>
dependencies:

```
    implementation("io.r2dbc:r2dbc-postgresql:0.8.13.RELEASE")
    implementation("io.r2dbc:r2dbc-pool:1.0.0.RELEASE")

    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.6.4")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.6.4")

    implementation("org.jooq:jooq-kotlin:3.18.0")
    implementation("org.jooq:jooq:3.18.0")
    implementation("org.jooq:jooq-kotlin-coroutines:3.18.0")
    implementation("org.jooq:jooq-postgres-extensions:3.18.0")

    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.9.2")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.2")
```

test code: 
```
import io.r2dbc.pool.ConnectionPool
import io.r2dbc.pool.ConnectionPoolConfiguration
import io.r2dbc.spi.ConnectionFactories
import io.r2dbc.spi.ConnectionFactoryOptions
import kotlinx.coroutines.reactive.awaitFirstOrNull
import kotlinx.coroutines.reactive.awaitLast
import kotlinx.coroutines.reactor.mono
import kotlinx.coroutines.runBlocking
import org.jooq.DSLContext
import org.jooq.impl.DSL
import org.jooq.impl.DSL.count
import org.jooq.impl.DSL.field
import org.jooq.impl.DSL.inline
import org.jooq.impl.DSL.table
import org.jooq.impl.DefaultConfiguration
import org.jooq.impl.SQLDataType.INTEGER
import org.jooq.impl.SQLDataType.VARCHAR
import org.jooq.kotlin.coroutines.transactionCoroutine
import org.jooq.tools.jdbc.JDBCUtils
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Test
import java.time.Duration
import java.util.UUID

class ConnectionWrapperTest {
    private val connectionFactoryOptions = ConnectionFactoryOptions.builder()
        .option(ConnectionFactoryOptions.DRIVER, "postgresql")
        .option(ConnectionFactoryOptions.HOST, "localhost")
        .option(ConnectionFactoryOptions.PORT, 5432)
        .option(ConnectionFactoryOptions.USER, "user")
        .option(ConnectionFactoryOptions.DATABASE, "test")
        .build()

    private val tableName = "testing12345"
    private val idCol = "id"
    private val valueCol = "val"

    private suspend fun validate(wrapper: ConnectionWrapper, tableName: String, uuid: String) {
        val returned = wrapper.dbQuery {
            select(field(idCol), field(valueCol))
                .from(table(tableName))
                .where(field(valueCol).eq(inline(uuid)))
                .awaitFirstOrNull()
        }

        assertNotNull(returned)
    }

    private suspend fun updateValue(dsl: DSLContext, tableName: String, uuid: String): Int? {
        return dsl.update(table(tableName))
            .set(field(valueCol), uuid)
            .awaitLast()
    }

    @Test
    fun `transaction using transactionCoroutine`() {
        val connectionWrapper = ConnectionWrapper(connectionFactoryOptions)

        runBlocking {
            setup(connectionWrapper, tableName)
        }

        repeat(1_000) {
            runBlocking {
                val uuid = UUID.randomUUID().toString()

                val updated = connectionWrapper.dbQuery {
                    transactionCoroutine { config ->
                        val transactionDsl = config.dsl()
                        updateValue(transactionDsl, tableName, uuid)
                    }
                }
                assertEquals(1, updated)
                validate(connectionWrapper, tableName, uuid)
            }
        }

        connectionWrapper.shutdown()
    }

    @Test
    fun `transaction using alternative`() = runBlocking {
        val connectionWrapper = ConnectionWrapper(connectionFactoryOptions)

        runBlocking {
            setup(connectionWrapper, tableName)
        }

        repeat(1_000) {
            val uuid = UUID.randomUUID().toString()
            val updated = connectionWrapper.dbQuery {
                transactionPublisher { config ->
                    val transactionDsl = config.dsl()
                    mono {
                        updateValue(transactionDsl, tableName, uuid)
                    }
                    // use await last instead of await first
                }.awaitLast()
            }
            assertEquals(1, updated)

            validate(connectionWrapper, tableName, uuid)
        }

        connectionWrapper.shutdown()
    }

    private suspend fun setup(wrapper: ConnectionWrapper, tableName: String) {
        wrapper.dbQuery {
            createTableIfNotExists(tableName)
                .column(idCol, INTEGER)
                .column(valueCol, VARCHAR(255))
                .awaitFirstOrNull()

            val field = count().`as`("COUNT")
            val record = select(field)
                .from(table(tableName))
                .awaitFirstOrNull()

            if (record == null || record[field] == 0) {
                insertInto(table(tableName))
                    .columns(field(idCol), field(valueCol))
                    .values(1, "old value")
                    .awaitFirstOrNull()
            }
        }
    }
}

class ConnectionWrapper(options: ConnectionFactoryOptions) {
    private val factory = ConnectionFactories.get(options)
    private val configuration = ConnectionPoolConfiguration.builder(factory)
        .maxIdleTime(Duration.ofMillis(60000)) // 1 min
        .maxSize(10)
        .initialSize(10)
        .minIdle(10)
        .build()
    private val pool = ConnectionPool(configuration)

    suspend fun <T> dbQuery(block: suspend DSLContext.() -> T): T {
        val config = DefaultConfiguration()
            .set(pool)
            .set(JDBCUtils.dialect(pool))

        val context = DSL.using(config)

        return block(context)
    }

    fun shutdown() {
        pool.dispose()
    }
}
```

</details>

### jOOQ Version

3.18.0, 3.18.3, 3.17.8

### Database product and version

PostgreSQL 14.7 (Homebrew) on aarch64-apple-darwin22.1.0

### Java Version

17

### OS Version

Mac

### JDBC driver name and version (include name if unofficial driver)

io.r2dbc:r2dbc-postgres:0.8.13.RELEASE

**Comment by jonathanswenson** [comment]
Perhaps a duplicate of or very much related to https://github.com/jOOQ/jOOQ/issues/13825 -- 
However I still see it is still happening in 3.18.

**Comment by lukaseder** [comment]
Thanks for your report and for the reproducer. I can reproduce the issue, will investigate now.

**Comment by lukaseder** [comment]
Looking at a failing iteration of the loop, we can see this in the logs:

```
13:31:38,163 DEBUG [io.r2dbc.pool.ConnectionPool                      ] - Obtaining new connection from the pool
13:31:38,163 DEBUG [io.r2dbc.postgresql.QUERY                         ] - [cid: 0xa][pid: 230] Executing query: BEGIN
13:31:38,163 DEBUG [r2dbc.postgresql.client.ReactorNettyClient        ] - [cid: 0xa][pid: 230] Request:  Query{query='BEGIN'}
13:31:38,165 DEBUG [r2dbc.postgresql.client.ReactorNettyClient        ] - [cid: 0xa][pid: 230] Response: CommandComplete{command=BEGIN, rowId=null, rows=null}
13:31:38,165 DEBUG [r2dbc.postgresql.client.ReactorNettyClient        ] - [cid: 0xa][pid: 230] Response: ReadyForQuery{transactionStatus=TRANSACTION}
13:31:38,166 DEBUG [io.r2dbc.postgresql.PARAM                         ] - [cid: 0xa][pid: 230] Bind parameter [0] to: c6aedc3b-7ec1-4c68-9d64-f50526e3b4f0
13:31:38,166 DEBUG [io.r2dbc.postgresql.QUERY                         ] - [cid: 0xa][pid: 230] Executing query: update testing12345 set val = $1
13:31:38,166 DEBUG [r2dbc.postgresql.client.ReactorNettyClient        ] - [cid: 0xa][pid: 230] Request:  [Bind{name='B_1', parameterFormats=[FORMAT_TEXT], parameters=[CompositeByteBuf(ridx: 0, widx: 36, cap: 36, components=1)], resultFormats=[], source='S_0'}, Describe{name='B_1', type=PORTAL}, Execute{name='B_1', rows=0}, Close{name='B_1', type=PORTAL}, Sync{}]
13:31:38,168 DEBUG [r2dbc.postgresql.client.ReactorNettyClient        ] - [cid: 0xa][pid: 230] Response: BindComplete{}
13:31:38,168 DEBUG [r2dbc.postgresql.client.ReactorNettyClient        ] - [cid: 0xa][pid: 230] Response: NoData{}
13:31:38,168 DEBUG [r2dbc.postgresql.client.ReactorNettyClient        ] - [cid: 0xa][pid: 230] Response: CommandComplete{command=UPDATE, rowId=null, rows=1}
13:31:38,168 DEBUG [r2dbc.postgresql.client.ReactorNettyClient        ] - [cid: 0xa][pid: 230] Response: CloseComplete{}
13:31:38,168 DEBUG [r2dbc.postgresql.client.ReactorNettyClient        ] - [cid: 0xa][pid: 230] Response: ReadyForQuery{transactionStatus=TRANSACTION}
13:31:38,168 DEBUG [r2dbc.postgresql.util.FluxDiscardOnCancel         ] - received cancel signal
13:31:38,168 DEBUG [io.r2dbc.postgresql.QUERY                         ] - [cid: 0xa][pid: 230] Executing query: COMMIT
13:31:38,168 DEBUG [r2dbc.postgresql.client.ReactorNettyClient        ] - [cid: 0xa][pid: 230] Request:  Query{query='COMMIT'}
13:31:38,169 DEBUG [io.r2dbc.pool.ConnectionPool                      ] - Obtaining new connection from the pool
13:31:38,169 DEBUG [io.r2dbc.postgresql.QUERY                         ] - [cid: 0x9][pid: 229] Executing query: select id, val from testing12345 where val = 'c6aedc3b-7ec1-4c68-9d64-f50526e3b4f0'
13:31:38,169 DEBUG [r2dbc.postgresql.client.ReactorNettyClient        ] - [cid: 0x9][pid: 229] Request:  Query{query='select id, val from testing12345 where val = 'c6aedc3b-7ec1-4c68-9d64-f50526e3b4f0''}
13:31:38,171 DEBUG [r2dbc.postgresql.client.ReactorNettyClient        ] - [cid: 0x9][pid: 229] Response: RowDescription{fields=[Field{column=1, dataType=23, dataTypeModifier=-1, dataTypeSize=4, format=FORMAT_TEXT, name='id', table=1191063}, Field{column=2, dataType=1043, dataTypeModifier=259, dataTypeSize=-1, format=FORMAT_TEXT, name='val', table=1191063}]}
13:31:38,171 DEBUG [r2dbc.postgresql.client.ReactorNettyClient        ] - [cid: 0x9][pid: 229] Response: CommandComplete{command=SELECT, rowId=null, rows=0}
13:31:38,171 DEBUG [r2dbc.postgresql.client.ReactorNettyClient        ] - [cid: 0x9][pid: 229] Response: ReadyForQuery{transactionStatus=IDLE}
13:31:38,172 DEBUG [io.r2dbc.pool.PooledConnection                    ] - Releasing connection
13:31:38,172 DEBUG [r2dbc.postgresql.client.ReactorNettyClient        ] - [cid: 0xa][pid: 230] Response: CommandComplete{command=COMMIT, rowId=null, rows=null}
13:31:38,172 DEBUG [r2dbc.postgresql.client.ReactorNettyClient        ] - [cid: 0xa][pid: 230] Response: ReadyForQuery{transactionStatus=IDLE}
13:31:38,172 DEBUG [io.r2dbc.pool.PooledConnection                    ] - Releasing connection
```

Particularly interesting: The `SELECT` query is issued *before* the `COMMIT` returns a response, in a different transaction, so obviously, it can't see the transaction content yet.

**Comment by lukaseder** [comment]
Hmm, indeed, the `awaitFirst()` semantics allows the coroutine-reactive bridge to return the first result early even before the completion of the underlying publishers. This is desired in some streams, but not in a transaction script, which may be suspending/reactive/async, yet still correctly sequenced.

I suspect, however, that `awaitSingle()` would be more appropriate than `awaitLast()`. We expect only a single return value from the `transactional` block, not multiple ones.

**Comment by lukaseder** [comment]
An integration test using H2 fails less reliably. E.g. only at iteration 1447, 3513, etc.

**Comment by lukaseder** [comment]
> I suspect, however, that `awaitSingle()` would be more appropriate than `awaitLast()`. We expect only a single return value from the `transactional` block, not multiple ones.

Hmm, nope. `awaitSingle()` doesn't allow  `null` results, it seems. The following integration test:

```kotlin
```

Produces this exception:

```
java.util.NoSuchElementException: No value received via onNext for awaitSingle

	at kotlinx.coroutines.reactive.AwaitKt$awaitOne$2$1.onComplete(Await.kt:282)
	at org.jooq.impl.R2DBC$TransactionSubscription$1.lambda$onNext0$14(R2DBC.java:747)
	at org.jooq.impl.Internal$1.onComplete(Internal.java:496)
	at reactor.core.publisher.StrictSubscriber.onComplete(StrictSubscriber.java:123)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2205)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:209)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:209)
	at reactor.pool.SimpleDequePool.maybeRecycleAndDrain(SimpleDequePool.java:533)
	at reactor.pool.SimpleDequePool$QueuePoolRecyclerInner.onComplete(SimpleDequePool.java:765)
	at reactor.core.publisher.Operators.complete(Operators.java:137)
	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4485)
	at reactor.pool.SimpleDequePool$QueuePoolRecyclerMono.subscribe(SimpleDequePool.java:877)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:240)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
	at reactor.core.publisher.Operators.complete(Operators.java:137)
	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4485)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:240)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203)
	at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:89)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:222)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:85)
	at reactor.core.publisher.MonoCallable$MonoCallableSubscription.request(MonoCallable.java:159)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2341)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2215)
	at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:48)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4485)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4485)
	at org.jooq.impl.R2DBC$AbstractNonBlockingSubscription.lambda$cancel0$4(R2DBC.java:642)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
	at org.jooq.impl.R2DBC$AbstractNonBlockingSubscription.cancel0(R2DBC.java:626)
	at org.jooq.impl.R2DBC$TransactionSubscription$1.lambda$onNext0$15(R2DBC.java:747)
	at org.jooq.impl.Internal$1.onComplete(Internal.java:496)
	at reactor.core.publisher.StrictSubscriber.onComplete(StrictSubscriber.java:123)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2205)
	at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:89)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2205)
	at reactor.core.publisher.Operators.complete(Operators.java:137)
	at reactor.core.publisher.FluxEmpty.subscribe(FluxEmpty.java:42)
	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4485)
	at org.jooq.impl.R2DBC$TransactionSubscription$1.lambda$onNext0$16(R2DBC.java:743)
	at org.jooq.impl.Internal$1.onComplete(Internal.java:496)
	at reactor.core.publisher.StrictSubscriber.onComplete(StrictSubscriber.java:123)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:140)
	at kotlinx.coroutines.reactor.MonoCoroutine.onCompleted(Mono.kt:101)
	at kotlinx.coroutines.AbstractCoroutine.onCompletionInternal(AbstractCoroutine.kt:93)
	at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:294)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:856)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:828)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
	at |b|b|b(Coroutine boundary.|b(|b)
	at org.jooq.kotlin.test.coroutines.CoroutinesTest$testTransactionalCoroutine0$r2$1.invokeSuspend(CoroutinesTest.kt:42)
Caused by: java.util.NoSuchElementException: No value received via onNext for awaitSingle
	at kotlinx.coroutines.reactive.AwaitKt$awaitOne$2$1.onComplete(Await.kt:282)
	at org.jooq.impl.R2DBC$TransactionSubscription$1.lambda$onNext0$14(R2DBC.java:747)
	at org.jooq.impl.Internal$1.onComplete(Internal.java:496)
	at reactor.core.publisher.StrictSubscriber.onComplete(StrictSubscriber.java:123)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2205)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:209)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:209)
	at reactor.pool.SimpleDequePool.maybeRecycleAndDrain(SimpleDequePool.java:533)
	at reactor.pool.SimpleDequePool$QueuePoolRecyclerInner.onComplete(SimpleDequePool.java:765)
	at reactor.core.publisher.Operators.complete(Operators.java:137)
	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4485)
	at reactor.pool.SimpleDequePool$QueuePoolRecyclerMono.subscribe(SimpleDequePool.java:877)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:240)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
	at reactor.core.publisher.Operators.complete(Operators.java:137)
	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4485)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:240)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203)
	at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:89)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:222)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:85)
	at reactor.core.publisher.MonoCallable$MonoCallableSubscription.request(MonoCallable.java:159)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2341)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2215)
	at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:48)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4485)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4485)
	at org.jooq.impl.R2DBC$AbstractNonBlockingSubscription.lambda$cancel0$4(R2DBC.java:642)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
	at org.jooq.impl.R2DBC$AbstractNonBlockingSubscription.cancel0(R2DBC.java:626)
	at org.jooq.impl.R2DBC$TransactionSubscription$1.lambda$onNext0$15(R2DBC.java:747)
	at org.jooq.impl.Internal$1.onComplete(Internal.java:496)
	at reactor.core.publisher.StrictSubscriber.onComplete(StrictSubscriber.java:123)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2205)
	at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:89)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2205)
	at reactor.core.publisher.Operators.complete(Operators.java:137)
	at reactor.core.publisher.FluxEmpty.subscribe(FluxEmpty.java:42)
	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4485)
	at org.jooq.impl.R2DBC$TransactionSubscription$1.lambda$onNext0$16(R2DBC.java:743)
	at org.jooq.impl.Internal$1.onComplete(Internal.java:496)
	at reactor.core.publisher.StrictSubscriber.onComplete(StrictSubscriber.java:123)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:140)
	at kotlinx.coroutines.reactor.MonoCoroutine.onCompleted(Mono.kt:101)
	at kotlinx.coroutines.AbstractCoroutine.onCompletionInternal(AbstractCoroutine.kt:93)
	at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:294)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:856)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:828)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

I don't see a reason why jOOQ's `transactionCoroutine` should be opinionated about returning `null` values

**Comment by lukaseder** [comment]
The same exception is thrown with `awaitLast()`. I guess we'll just wrap the `T` value in a wrapper that can contain the `null` value, instead.

**Comment by lukaseder** [comment]
Fixed for jOOQ:

- 3.19.0
- 3.18.5 (https://github.com/jOOQ/jOOQ/issues/15133)
- 3.17.14 (https://github.com/jOOQ/jOOQ/issues/15134)
