### ISSUE TITLE
QueryPartCollectionView::$replace should produce actual collection type, not generic QueryPartList

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15019]
I'm not sure if this is a problem for users or only for jOOQ's internals, but when calling `TableList::$replace`, I had a `ClassCastException`:

```
java.lang.ClassCastException: class org.jooq.impl.QueryPartList cannot be cast to class org.jooq.impl.TableList (org.jooq.impl.QueryPartList and org.jooq.impl.TableList are in unnamed module of loader 'app')
	at org.jooq_3.19.0-SNAPSHOT.ORACLE23C.debug(Unknown Source)
	at org.jooq.impl.DeleteQueryImpl.accept0(DeleteQueryImpl.java:299)
	at org.jooq.impl.AbstractDMLQuery.accept(AbstractDMLQuery.java:671)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:736)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:354)
	at org.jooq.impl.DefaultDSLContext.renderInlined(DefaultDSLContext.java:749)
	at org.jooq.impl.AbstractQueryPart.equals(AbstractQueryPart.java:170)
	at org.jooq.Traversers.lambda$11(Traversers.java:147)
	at org.jooq.impl.CachingTraverser.lambda$4(CachingTraverser.java:108)
	at org.jooq.impl.QOM.traverse(QOM.java:8929)
	at org.jooq.impl.DeleteQueryImpl.$traverse(DeleteQueryImpl.java:497)
	at org.jooq.test.util.BaseTest.qomAssertions(BaseTest.java:752)
	at org.jooq.test.jOOQAbstractTest$QOMAssertionListener.start(jOOQAbstractTest.java:419)
	at org.jooq.impl.ExecuteListeners.start(ExecuteListeners.java:160)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:283)
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
	at org.jooq.test.all.testcases.InsertUpdateTests.testDeleteUsingMySQLStyleJoinRepeatFromTable(InsertUpdateTests.java:301)
	at org.jooq.test.jOOQAbstractTest.testDeleteUsingMySQLStyleJoinRepeatFromTable(jOOQAbstractTest.java:2587)
```

The reason is that the `QueryPartCollectionView::$replace` implementation isn't overridden by subclasses, nor is there a generic constructor to instantiate subtypes as template methods. So, the `$replace()` call simply returns a `QueryPartList`.

Again, this is certainly not good, but perhaps not an urgent issue, as users aren't affected. Users can't see this type, and thus shouldn't worry about it. E.g. when they replace the `FROM` clause in a `SELECT` statement, then jOOQ will wrap the resulting list again in a `TableList`

**Comment by lukaseder** [comment]
I vaguely remember omitting this deliberately, because again:

1. Users aren't affected
2. The effects on the `QueryPartCollectionView` type hierarchy are non-negligible

So, I'll wait. At least now, we have an issue to collect use-cases.
