### ISSUE TITLE
Replacer and Traverse should recurse into TableField's Table reference

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15020]
`TableFieldImpl` currently doesn't allow for automatically recursing into its `Table` reference, which seems to be wrong, given that `TableImpl` does the same thing already with its `Schema` reference.

For a `Replacer` based multi tenancy implementation, as well as for a variety of use-cases where we rename a table or alias it within a query, it should be possible to just:

```java
u = u.$replace(p -> {
    if (p instanceof Table<?> t && something)
        return t.as(someAlias);
    return p;
}));
```

This may affect existing `Replacer` or `Traverser` implementations, so it won't  be backported.

**Comment by lukaseder** [comment]
This produces a `StackOverflowError`:

```
java.lang.StackOverflowError
	at org.jooq.impl.DataMap.<init>(DataMap.java:69)
	at org.jooq.impl.AbstractScope.<init>(AbstractScope.java:70)
	at org.jooq.impl.AbstractScope.<init>(AbstractScope.java:59)
	at org.jooq.impl.AbstractContext.<init>(AbstractContext.java:172)
	at org.jooq.impl.DefaultRenderContext.<init>(DefaultRenderContext.java:122)
	at org.jooq.impl.DefaultDSLContext.renderContext(DefaultDSLContext.java:729)
	at org.jooq.impl.DefaultDSLContext.renderInlined(DefaultDSLContext.java:749)
	at org.jooq.impl.AbstractQueryPart.hashCode(AbstractQueryPart.java:183)
	at java.base/java.util.HashMap.hash(HashMap.java:338)
	at java.base/java.util.HashMap.getNode(HashMap.java:568)
	at java.base/java.util.HashMap.containsKey(HashMap.java:594)
	at java.base/java.util.HashSet.contains(HashSet.java:205)
	at org.jooq.impl.FieldMapForUpdate.lambda$14(FieldMapForUpdate.java:478)
	at org.jooq.impl.QOM$UEmpty.$replace(QOM.java:8844)
	at org.jooq.impl.QOM.replace(QOM.java:8896)
	at org.jooq.impl.QOM.replace(QOM.java:9016)
```

**Comment by lukaseder** [comment]
I'll look into this later. The original feature (some specifics in Oracle's `DELETE FROM .. FROM` clause, which requires some aliasing of a table) can do without this improvement.

**Comment by lukaseder** [comment]
Looking at this again, it's surprising we didn't already get the `StackOverflowError` before! The `val = val + 1` style substitution that we're doing here in `FieldMapForUpdate.computeOnClientStoredReplace0` never stops

**Comment by lukaseder** [comment]
I don't have a good feeling about this change. Will think about it again.

**Comment by lukaseder** [comment]
Rather than making things consistent in favour of more recursing into `Named` parts, I'll revert the behaviour of `SchemaImpl` and `TableImpl`, see https://github.com/jOOQ/jOOQ/issues/15046
