### ISSUE TITLE
Let SchemaImpl and TableImpl implement UEmpty

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15046]
One of the open questions of the new query object model was whether object references like `TableField` should allow for recursing traversal and replacement into their parent objects:

- https://github.com/jOOQ/jOOQ/issues/15020

I.e. a `TableField` is a `Table` and a `Field`, whereas a `Table` is a `Schema` and a `Table`, etc.

Such recursion could help simplify implementing multitenancy and other types of features. But the price is high:

- The recursion is a bit counter intuitive. A `TableField` isn't "composed" of a `Table` and a `Field`. Much rather, the `Table` is just a property of the `Field`. When a `Field` is expected (e.g. `x = 1`), then it it counter-intuitive to traverse into a `Table`
- Since most `Field` expressions are probably `TableField` expressions, the overhead of recursion is quite significant, even when that is hardly ever needed
- Consistency dictates that we should treat all `Named` objects alike. Currently, only `SchemaImpl` and `TableImpl` traverse into their parent objects (`TableImpl` still implements `UNotYetImplemented`, so this isn't strictly a documented feature)

Implementing this means https://github.com/jOOQ/jOOQ/issues/15020 will get rejected.

**Comment by lukaseder** [comment]
There are no regressions in unit or integration tests after this change. It appears that I haven't ever worked with the design of the status quo, yet.

However, obviously, some customers may have already started using the existing design, so this is an incompatible change without a backport.

**Comment by lukaseder** [comment]
(The change is acceptable because the traversal / replacement feature is still experimental)

**Comment by lukaseder** [comment]
Without this change, the backport of #17965 and #17972 causes a `StackOverflowError` as the `TableImpl` attempts to replace itself:

```
Exception in thread "Thread-1" java.lang.StackOverflowError
	at org.jooq.impl.CatalogImpl.getQualifiedName(CatalogImpl.java:1)
	at org.jooq.test.sqlserver.generatedclasses.test.Test.getQualifiedName(Test.java:1)
	at org.jooq.impl.CatalogImpl.$replace(CatalogImpl.java:136)
	at org.jooq.impl.QOM.replace(QOM.java:9024)
	at org.jooq.impl.QOM.replace(QOM.java:9162)
	at org.jooq.impl.SchemaImpl.$replace(SchemaImpl.java:363)
	at org.jooq.impl.QOM.replace(QOM.java:9024)
	at org.jooq.impl.QOM.replace(QOM.java:9127)
	at org.jooq.impl.TableImpl.$replace(TableImpl.java:531)
	at org.jooq.impl.QOM.replace(QOM.java:9024)
	at org.jooq.impl.QOM.replace(QOM.java:9127)
	at org.jooq.impl.WithTable.$replace(WithTable.java:144)
	at org.jooq.impl.QOM.replaceUntilStable(QOM.java:9926)
	at org.jooq.impl.QOM.replace(QOM.java:9132)
	at org.jooq.impl.TableImpl.$replace(TableImpl.java:531)
	at org.jooq.impl.QOM.replace(QOM.java:9024)
	at org.jooq.impl.QOM.replace(QOM.java:9127)
	at org.jooq.impl.WithTable.$replace(WithTable.java:144)
	at org.jooq.impl.QOM.replaceUntilStable(QOM.java:9926)
	at org.jooq.impl.QOM.replace(QOM.java:9132)
	at org.jooq.impl.TableImpl.$replace(TableImpl.java:531)
```

As such, I will backport this change here as well

**Comment by lukaseder** [comment]
Backported to versions:

- 3.18.26 (https://github.com/jOOQ/jOOQ/issues/18025)
- 3.17.35 (https://github.com/jOOQ/jOOQ/issues/18026)
