### ISSUE TITLE
Translator reports internal error when parsing SQL Server CONVERT() with GETDATE() expression

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15163]
This expression is valid in SQL Server:

```sql
select CONVERT(DATE,DATEADD(wk,-2,DATEADD(dd, 1-DATEPART(dw, getdate()),getdate())))
```

On the translator, it results in an *"Internal Error"*

<img width="924" alt="image" src="https://github.com/jOOQ/jOOQ/assets/734593/4c22528e-428b-4d74-a893-6d39ac4e3848">

The stack trace is:

```
java.lang.UnsupportedOperationException: Unknown date part : WEEK
	at org.jooq.impl.DateAdd.unsupported(DateAdd.java:406)
	at org.jooq.impl.DateAdd.standardKeyword(DateAdd.java:401)
	at org.jooq.impl.DateAdd.accept0(DateAdd.java:384)
	at org.jooq.impl.DateAdd.accept(DateAdd.java:119)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:736)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:348)
	at org.jooq.impl.Cast$CastNative.lambda$0(Cast.java:332)
	at org.jooq.impl.Cast.renderCast(Cast.java:361)
	at org.jooq.impl.Cast$CastNative.accept(Cast.java:331)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:736)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:354)
	at org.jooq.impl.Cast.accept(Cast.java:122)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:736)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:305)
	at org.jooq.impl.QueryPartCollectionView.acceptElement(QueryPartCollectionView.java:256)
	at org.jooq.impl.SelectFieldList.lambda$1(SelectFieldList.java:93)
	at org.jooq.impl.Tools.visitAutoAliased(Tools.java:2874)
	at org.jooq.impl.SelectFieldList.acceptElement0(SelectFieldList.java:93)
	at org.jooq.impl.SelectFieldList.acceptElement(SelectFieldList.java:89)
	at org.jooq.impl.SelectFieldList.acceptElement(SelectFieldList.java:1)
	at org.jooq.impl.QueryPartCollectionView.accept(QueryPartCollectionView.java:226)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:736)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:354)
	at org.jooq.impl.SelectQueryImpl.toSQLReference0(SelectQueryImpl.java:2383)
	at org.jooq.impl.SelectQueryImpl.lambda$38(SelectQueryImpl.java:2035)
	at org.jooq.impl.AbstractContext.toggle(AbstractContext.java:397)
	at org.jooq.impl.AbstractContext.data(AbstractContext.java:408)
	at org.jooq.impl.SelectQueryImpl.toSQLReferenceLimitDefault(SelectQueryImpl.java:2035)
	at org.jooq.impl.SelectQueryImpl.accept0(SelectQueryImpl.java:1930)
	at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:1548)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:736)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:354)
	at org.jooq.impl.DefaultDSLContext.renderInlined(DefaultDSLContext.java:749)
	at org.jooq.impl.AbstractQueryPart.equals(AbstractQueryPart.java:169)
	at org.junit.Assert.isEquals(Assert.java:133)
	at org.junit.Assert.equalsRegardingNull(Assert.java:129)
	at org.junit.Assert.assertEquals(Assert.java:112)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.jooq.test.util.BaseTest.assertEquals(BaseTest.java:319)
	at org.jooq.impl.AbstractParserTest.additionalAssertions(AbstractParserTest.java:520)
```

Apart from the fact that we should support `WEEK`, eventually, the error shouldn't be an *"Internal Error"* in the translator, so users can better trouble shoot the unsupported feature.

**Comment by lukaseder** [comment]
That's better:

<img width="913" alt="image" src="https://github.com/jOOQ/jOOQ/assets/734593/aebfd1c7-c431-4c6f-83b9-38c58c9b87ea">
