### ISSUE TITLE
NullPointerException in AbstractMeta::lookupTable and other methods, when there is no DefaultCatalog

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15218]
So far, we could always assume a `DefaultCatalog` in generated code. Effectively, a `Table::getCatalog` method never returned null if the table was generated. This has changed now with https://github.com/jOOQ/jOOQ/issues/15207, and now a `NullPointerException` shows up in an integration test:

```
java.lang.NullPointerException: Cannot invoke "org.jooq.Catalog.getName()" because the return value of "org.jooq.Table.getCatalog()" is null
	at org.jooq.impl.AbstractMeta.lookupTable(AbstractMeta.java:592)
	at org.jooq.impl.AbstractMeta.lookupUniqueKey(AbstractMeta.java:615)
	at org.jooq.impl.FilteredMeta$FilteredTable.getReferences(FilteredMeta.java:441)
	at org.jooq.test.all.testcases.MetaDataTests.testMetaFilter(MetaDataTests.java:207)
	at org.jooq.test.jOOQAbstractTest.testMetaFilter(jOOQAbstractTest.java:4523)
```

This NPE was *very* unlikely to appear before #15207, which is why it hasn't been reported yet. With the new option of omitting the `DefaultCatalog`, however, it is far less unlikely.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.19.0
- 3.18.5 (https://github.com/jOOQ/jOOQ/issues/15219)
- 3.17.14 (https://github.com/jOOQ/jOOQ/issues/15220)
- 3.16.20 (https://github.com/jOOQ/jOOQ/issues/15221)

**Comment by lukaseder** [comment]
There's another method that throws a similar NPE for dialects that don't have any schemas (e.g. Firebird or SQLite):

```
java.lang.NullPointerException: Cannot invoke "org.jooq.Schema.getCatalog()" because "schema" is null
	at org.jooq_3.19.0-SNAPSHOT.FIREBIRD.debug(Unknown Source)
	at org.jooq.impl.CatalogMetaImpl.filterSchemas(CatalogMetaImpl.java:99)
	at org.jooq.impl.CatalogMetaImpl.filterSchemas(CatalogMetaImpl.java:91)
	at org.jooq.impl.DefaultDSLContext.meta(DefaultDSLContext.java:418)
	at org.jooq.test.jOOQAbstractTest$JavaDialectListener.lambda$0(jOOQAbstractTest.java:458)
	at org.jooq.test.agent.SupportVerificationDispatcher.deactivated(SupportVerificationDispatcher.java:125)
	at org.jooq.test.jOOQAbstractTest$JavaDialectListener.renderEnd(jOOQAbstractTest.java:451)
	at org.jooq.impl.ExecuteListeners.renderEnd(ExecuteListeners.java:188)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:304)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:301)
	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:322)
	at org.jooq.impl.SelectImpl.fetchLazyNonAutoClosing(SelectImpl.java:2962)
	at org.jooq.impl.ResultQueryTrait.collect(ResultQueryTrait.java:360)
	at org.jooq.impl.ResultQueryTrait.fetch(ResultQueryTrait.java:377)
	at org.jooq.test.all.testcases.PredicateTests.testPredicates_QuantifiedArray(PredicateTests.java:1484)
	at org.jooq.test.jOOQAbstractTest.testPredicates_QuantifiedArray(jOOQAbstractTest.java:5375)
```

**Comment by lukaseder** [comment]
The NPE is caused by the test, though:

```
at org.jooq.test.jOOQAbstractTest$JavaDialectListener.lambda$0(jOOQAbstractTest.java:458)
```

The `CatalogMetaImpl` method in question accepts a `Set<Schema>`, where I think a `null` schema is quite unexpected.
