### ISSUE TITLE
MetaImpl::ddl() should produce plain SQL CREATE VIEW statements if it can't parse the view contents

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15238]
If we can't parse view contents, we should produce plain SQL `CREATE VIEW` statements in `MetaImpl::ddl`, as a fallback for those cases where parsing isn't necessary.

In fact, we could make parsing configurable in general. It's not always useful. There's already a `Settings.parseMetaDefaultExpressions` (see #8469), so why not add this as well `Settings.parseMetaViewSource`

----
See also:
- https://github.com/jOOQ/jOOQ/issues/15236
- https://github.com/jOOQ/jOOQ/issues/15239

**Comment by lukaseder** [comment]
This test now passes:

```java
    @Test
    public void testPostgresMetaUnsupportedViewSyntax() throws Exception {
        try {
            create().execute("create view v (i) as select json_typeof(cast('1' as json))");

            Queries q =
            create().meta()
                    .filterSchemas(s -> s.getName().equals(schema().getName()))
                    .filterTables(t -> t.getName().equals("v"))
                    .ddl(new DDLExportConfiguration().flags(DDLFlag.TABLE));

            assertEquals(1, q.$queries().size());
            assertFalse(((CreateView<?>) q.$queries().get(0)).$query() instanceof Select);
        }
        finally {
            ignoreThrows(() -> create().execute("drop view if exists v"));
        }
    }
```

There's still log information to make sure users understand the tradeoff:

```
13:20:15,506  INFO [DDL                           ] - Cannot parse view source: create view "v" as  SELECT json_typeof('1'::json) AS i;
org.jooq.impl.ParserException: Unknown function: [1:40] create view "v" as  SELECT json_typeof([*]'1'::json) AS i;
	at org.jooq.impl.DefaultParseContext.exception(ParserImpl.java:14809) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.parseUnaryOps(ParserImpl.java:8251) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.parseExp(ParserImpl.java:8203) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.parseFactor(ParserImpl.java:8180) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.parseSum(ParserImpl.java:8121) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.parseNumericOp(ParserImpl.java:8070) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.parseCollated(ParserImpl.java:7919) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.parseConcat(ParserImpl.java:7902) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.parsePredicate(ParserImpl.java:6612) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.parseNot(ParserImpl.java:6466) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.parseAnd(ParserImpl.java:6456) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.parseXor(ParserImpl.java:6447) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.parseOr(ParserImpl.java:6438) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.parseFieldOrRow(ParserImpl.java:7813) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.parseSelectField(ParserImpl.java:7786) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.parseSelectList(ParserImpl.java:7736) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.parseQueryPrimary(ParserImpl.java:1786) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.parseQueryTerm(ParserImpl.java:1690) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.parseQueryExpressionBody(ParserImpl.java:1656) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.parseSelect(ParserImpl.java:1416) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.parseWithOrSelect(ParserImpl.java:1407) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.parseWithOrSelect(ParserImpl.java:1403) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.parseCreateView(ParserImpl.java:4188) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.parseCreate(ParserImpl.java:2957) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.parseQuery(ParserImpl.java:1133) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.lambda$2(ParserImpl.java:903) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.wrap(ParserImpl.java:15002) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.parse(ParserImpl.java:891) ~[classes/:?]
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:769) ~[classes/:?]
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:764) ~[classes/:?]
	at org.jooq.impl.DDL.applyAs(DDL.java:175) [classes/:?]
	at org.jooq.impl.DDL.createTableOrView(DDL.java:122) [classes/:?]
	at org.jooq.impl.DDL.queries(DDL.java:403) [classes/:?]
	at org.jooq.impl.AbstractMeta.ddl(AbstractMeta.java:549) [classes/:?]
	at org.jooq.test.PostgresTest.testPostgresMetaUnsupportedViewSyntax(PostgresTest.java:4924) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.13.2.jar:4.13.2]
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61) [junit-4.13.2.jar:4.13.2]
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) [junit-4.13.2.jar:4.13.2]
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
```

I.e., if they want to avoid this particular issue, they can also just turn off parsing entirely with https://github.com/jOOQ/jOOQ/issues/15239, starting in jOOQ 3.19

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.19.0
- 3.18.5 (https://github.com/jOOQ/jOOQ/issues/15240)
- 3.17.14 (https://github.com/jOOQ/jOOQ/issues/15241)
- 3.16.20 (https://github.com/jOOQ/jOOQ/issues/15242)
