### ISSUE TITLE
Remove JSON_ARRAYAGG workaround again for Oracle 23c

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15309]
jOOQ 3.15 introduced a workaround for the Oracle `MULTISET` and `FOR JSON` implementations, because of a bug in Oracle where `JSON_ARRAYAGG(DISTINCT ..)` didn't seem to work correctly:

- https://github.com/jOOQ/jOOQ/issues/12085

It appears that in Oracle 23c, this workaround is no longer needed, so we can remove it.

The workaround produces a funky `having count(*) = count(*)` clause, that may appear puzzling to readers of generated SQL.

**Comment by lukaseder** [comment]
Nope, the workaround is still necessary. There are still integration test failures without it:

```
org.jooq.exception.DataAccessException: SQL [select (select coalesce(json_arrayagg(json_array("t"."v0" format json null on null returning clob) format json returning clob), json_array(returning clob)) from (select json_array((select coalesce(json_arrayagg(json_array("t"."v0" format json null on null returning clob) format json returning clob), json_array(returning clob)) from (select json_array(nvl(null, ?), nvl(null, ?) null on null returning clob) "v0") "t") format json null on null returning clob) "v0") "t") -- SQL rendered with a free trial version of jOOQ 3.19.0-SNAPSHOT]; ORA-00978: Verschachtelte Gruppenfunktion ohne GROUP BY

	at org.jooq_3.19.0-SNAPSHOT.ORACLE23C.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3523)
	at org.jooq.impl.Tools.translate(Tools.java:3511)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:811)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:373)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:301)
	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:322)
	at org.jooq.impl.SelectImpl.fetchLazyNonAutoClosing(SelectImpl.java:2962)
	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:509)
	at org.jooq.test.all.testcases.MultisetTests.testMultisetNestedProjectionNestedRows(MultisetTests.java:2559)
	at org.jooq.test.jOOQAbstractTest.testMultisetNestedProjectionNestedRows(jOOQAbstractTest.java:6033)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00978: Verschachtelte Gruppenfunktion ohne GROUP BY

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:629)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:563)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1230)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:771)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:511)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:162)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:1009)
	at oracle.jdbc.driver.OracleStatement.prepareDefineBufferAndExecute(OracleStatement.java:1270)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1148)
	at oracle.jdbc.driver.OracleStatement.executeSQLSelect(OracleStatement.java:1660)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1469)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3760)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:4135)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1013)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4748)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:236)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:359)
	... 38 more
Caused by: Error : 978, Position : 211, Sql = select (select coalesce(json_arrayagg(json_array("t"."v0" format json null on null returning clob) format json returning clob), json_array(returning clob)) from (select json_array((select coalesce(json_arrayagg(json_array("t"."v0" format json null on null returning clob) format json returning clob), json_array(returning clob)) from (select json_array(nvl(null, :1 ), nvl(null, :2 ) null on null returning clob) "v0") "t") format json null on null returning clob) "v0") "t") -- SQL rendered with a free trial version of jOOQ 3.19.0-SNAPSHOT, OriginalSql = select (select coalesce(json_arrayagg(json_array("t"."v0" format json null on null returning clob) format json returning clob), json_array(returning clob)) from (select json_array((select coalesce(json_arrayagg(json_array("t"."v0" format json null on null returning clob) format json returning clob), json_array(returning clob)) from (select json_array(nvl(null, ?), nvl(null, ?) null on null returning clob) "v0") "t") format json null on null returning clob) "v0") "t") -- SQL rendered with a free trial version of jOOQ 3.19.0-SNAPSHOT, Error Msg = ORA-00978: Verschachtelte Gruppenfunktion ohne GROUP BY

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:636)
	... 57 more
```
