### ISSUE TITLE
Exception thrown for BigDecimal objects in tests with a composite type

### ISSUE THREAD

**Issue by bernardofs** [jOOQ/jOOQ#15395]
### Expected behavior

Mock result should be able to parse a `Bigdecimal` string in a composite type.

### Actual behavior

When attempting to parse a BigDecimal within a composite type, the following error is thrown:

```java
Caused by: java.lang.NumberFormatException: Character   is neither a decimal digit number, decimal point, nor "e" notation exponential mark.
```

This error is caused by an issue in parsing the string returned by the database. For instance, when the database returns `"table"."column"(EUR, 0)`, the mocked database splits the values into "EUR" and " 0" (with a leading space).

Consequently, an error occurs when the BigDecimal type attempts to parse the string " 0" as an integer value.

![image](https://github.com/jOOQ/jOOQ/assets/26277944/06f72146-189c-443d-afb1-e9eaba2755aa)

### Steps to reproduce the problem

Here's an improved version of the text:

- Define a user-defined type (UDT) named `MONETARY_AMOUNT` with a `BigDecimal` attribute, ensuring it is not the first attribute in the order. Use the following SQL statement:

```sql
CREATE TYPE MONETARY_AMOUNT AS (
    currency    text,
    amount      numeric
);
```

- Generate the necessary code.

- Write tests that return a column of the defined UDT type and execute them.

```java
Result<Record1<MonetaryAmountRecord>> result = context.newResult(Table.COLUMN);
result.add(context.newRecord(Table.COLUMN)
    .values(new MonetaryAmountRecord("EUR", BigDecimal.valueOf(0))));
return new MockResult[]{ new MockResult(1, result) };
```

### jOOQ Version

Community 3.15.5

### Database product and version

PostgreSQL 14.5

### Java Version

java version "19.0.2" 2023-01-17

### OS Version

Microsoft Windows [22621.1848]

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.1

**Comment by lukaseder** [comment]
Thanks a lot for your report and for your patience. I'll have a look at this issue shortly.

**Comment by lukaseder** [comment]
I can confirm, I'm getting this exception, when trying to reproduce this:

```java
    public void testMockUDT() throws Exception {
        assumeNotNull(TAuthor_ADDRESS());

        U_15395Record u = new U_15395Record("EUR", BigDecimal.ZERO);
        Result<Record1<U_15395Record>> result = create().newResult(T_15395.U);
        result.add(create().newRecord(T_15395.U).values(u));
        MockDataProvider p = Mock.of(new MockResult(1, result));
        DSLContext ctx = DSL.using(new MockConnection(p), create().dialect());
        assertEquals(u, ctx.select(T_15395.U).from(T_15395).fetchSingle().value1());
    }
```

Exception:

```
org.jooq.exception.DataAccessException: SQL [select "public"."t_15395"."u" from "public"."t_15395" -- SQL rendered with a free trial version of jOOQ 3.19.0-SNAPSHOT]; Error while reading field: "public"."t_15395"."u", at JDBC index: 1
	at org.jooq_3.19.0-SNAPSHOT.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3523)
	at org.jooq.impl.Tools.translate(Tools.java:3511)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:811)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1404)
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1365)
	at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:173)
	at org.jooq.impl.Tools.fetchSingle(Tools.java:2835)
	at org.jooq.impl.ResultQueryTrait.fetchSingle(ResultQueryTrait.java:605)
	at org.jooq.test.all.testcases.MockTests.testMockUDT(MockTests.java:227)
	at org.jooq.test.jOOQAbstractTest.testMockUDT(jOOQAbstractTest.java:10632)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.sql.SQLException: Error while reading field: "public"."t_15395"."u", at JDBC index: 1
	at org.jooq.impl.CursorImpl$CursorRecordInitialiser.setValue(CursorImpl.java:1591)
	at org.jooq.impl.CursorImpl$CursorRecordInitialiser.apply(CursorImpl.java:1517)
	at org.jooq.impl.CursorImpl$CursorRecordInitialiser.apply(CursorImpl.java:1)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1389)
	... 38 more
Caused by: java.lang.NumberFormatException: Character   is neither a decimal digit number, decimal point, nor "e" notation exponential mark.
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:586)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:471)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:900)
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.pgFromString(DefaultBinding.java:4048)
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.pgSetValue(DefaultBinding.java:4188)
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.lambda$13(DefaultBinding.java:4180)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144)
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.pgNewRecord(DefaultBinding.java:4176)
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.get0(DefaultBinding.java:3958)
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.get0(DefaultBinding.java:1)
	at org.jooq.impl.DefaultBinding$InternalBinding.get(DefaultBinding.java:1105)
	at org.jooq.impl.CursorImpl$CursorRecordInitialiser.setValue(CursorImpl.java:1581)
	... 42 more
```

**Comment by lukaseder** [comment]
In order to support UDTs in `MockResult`, we'd have to re-implement the entire serialisation logic of a UDT into the `PGobject` notation. This includes not just the UDT, but also various nested object types. 

I'm not convinced that we should make this a priority, though it's definitely a bug (or missing feature).

In any case, if you're using vendor specific functionality, it's very likely you'll be better off testing your code with testcontainers.org, rather than using mocking. See also the disclaimer in our manual's mocking sections:
https://www.jooq.org/doc/latest/manual/sql-execution/mocking-connection/

> Disclaimer: The general idea of mocking a JDBC connection with this jOOQ API is to provide quick workarounds, injection points, etc. using a very simple JDBC abstraction. It is NOT RECOMMENDED to emulate an entire database (including complex state transitions, transactions, locking, etc.) using this mock API. Once you have this requirement, please consider using an actual database product instead for integration testing, rather than implementing your test database inside of a MockDataProvider.

**Comment by lukaseder** [comment]
Hmm, I just recalled, we already have `PostgresUtils::toPGString`, which should have significant test coverage as we use that to inline bind values (including UDTs). I'll give it a shot.

**Comment by lukaseder** [comment]
It seems much simpler than this. `MockResultSet` already returns your own `UDTRecord`, and the call to `pgNewRecord` can be prevented in this case.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.19.0
- 3.18.6 (https://github.com/jOOQ/jOOQ/issues/15444)
- 3.17.15 (https://github.com/jOOQ/jOOQ/issues/15445)
- 3.16.21 (https://github.com/jOOQ/jOOQ/issues/15446)

**Comment by bernardofs** [comment]
Thanks a lot!
