### ISSUE TITLE
ArrayIndexOutOfBoundsException when rendering mysql plain SQL template containing "\

### ISSUE THREAD

**Issue by wxlfight** [jOOQ/jOOQ#15460]
### Steps to reproduce the problem

this code:
`println(DSL.using(SQLDialect.MYSQL).render(DSL.table("select REPLACE(\"abc\", \"\\\"\", \"B\") from example")))`

Produces an ArrayIndexOutOfBoundsException:

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 45 out of bounds for length 45
        at org.jooq.impl.Tools.renderAndBind(Tools.java:2092)
	at org.jooq.impl.SQLImpl.accept(SQLImpl.java:66)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:462)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:444)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:205)
	at org.jooq.impl.SQLTable.accept(SQLTable.java:82)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:462)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:444)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:205)
	at org.jooq.impl.DefaultDSLContext.render(DefaultDSLContext.java:585)

### jOOQ Version

JOOQ pro 3.11.11

### Database product and version

mysql 8.0.11

**Comment by lukaseder** [comment]
Probably a duplicate of https://github.com/jOOQ/jOOQ/issues/7706.

You're using a very old jOOQ version. Please try upgrading. If any issue still persists in the latest versions, I'll be happy to have a look.

**Comment by wxlfight** [comment]
> 
I'm sorry for bothering you. after test for a multi versions, i found this issue has been fixed in #9648
