### ISSUE TITLE
Issue parsing schema with a DEFAULT field.

### ISSUE THREAD

**Issue by sbrossie** [jOOQ/jOOQ#15486]
### Expected behavior

We have a use case where we added a new `Non Null` field to a table and therefore had to specify a `default` value.

We end up with the following in our table `updated_date datetime NOT NULL DEFAULT '1970-01-01 00:00:00',` and jOOQ seems to choke on this:

```
2023-07-17T19:39:52,634+0000 lvl='INFO', log='Metadata', th='Thread-8', xff='', rId='', tok='', aRId='', tRId='', Started priming caches...
2023-07-17T19:39:53,550+0000 lvl='INFO', log='MetaImpl', th='Thread-8', xff='', rId='', tok='', aRId='', tRId='', Cannot parse default expression: 1970-01-01 00:00:00
2023-07-17T19:39:53.551213716Z org.jooq.impl.ParserException: Unexpected content after end of field input: [1:12] 1970-01-01 [*]00:00:00
2023-07-17T19:39:53.551217132Z  at org.jooq.impl.DefaultParseContext.exception(ParserImpl.java:13544)
2023-07-17T19:39:53.551219216Z  at org.jooq.impl.DefaultParseContext.done(ParserImpl.java:13704)
2023-07-17T19:39:53.551220924Z  at org.jooq.impl.DefaultParseContext.parseField0(ParserImpl.java:563)
2023-07-17T19:39:53.551222632Z  at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:428)
2023-07-17T19:39:53.551224174Z  at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:423)
2023-07-17T19:39:53.551225882Z  at org.jooq.impl.MetaImpl$MetaTable.initColumns(MetaImpl.java:1084)
2023-07-17T19:39:53.551227591Z  at org.jooq.impl.MetaImpl$MetaTable.<init>(MetaImpl.java:679)
2023-07-17T19:39:53.551229382Z  at org.jooq.impl.MetaImpl$MetaSchema.lambda$getTables$2(MetaImpl.java:425)
2023-07-17T19:39:53.551231674Z  at org.jooq.impl.Tools.map(Tools.java:2020)
2023-07-17T19:39:53.551233341Z  at org.jooq.impl.MetaImpl$MetaSchema.getTables(MetaImpl.java:397)
```

### Actual behavior

Expect the schema to be parsed correctly as it looks like value DDL.

### Steps to reproduce the problem

For more context, see original bug report in our [repo](https://github.com/killbill/killbill/issues/1900)

### jOOQ Version

3.15.12

### Database product and version

Mysql 8.0.33_3

### Java Version

openjdk 11

### OS Version

linux, macos

### JDBC driver name and version (include name if unofficial driver)

mysql-connector-java:8:0:30

**Comment by lukaseder** [comment]
This works for me in jOOQ 3.19.0 or 3.18.6. I'll be happy to look at a complete reproducer, if the problem persists after an upgrade.

**Comment by lukaseder** [comment]
For the record:

```java
System.out.println(ctx.parser().parseQuery("""
    create table t (
      updated_date datetime NOT NULL DEFAULT '1970-01-01 00:00:00'
    )
    """));
```

Prints:

```sql
create table t (
  updated_date timestamp not null default '1970-01-01 00:00:00'
)
```
