### ISSUE TITLE
DefaultRecordMapper should be able to reflectively map multisets into Sets of POJOs

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15488]
As discussed here:

- https://github.com/jOOQ/jOOQ/issues/15477

There should be no difference between `List<P>` and `Set<P>` usage in `DefaultRecordMapper`:

```java
    static class MultisetPojo {
        int id2;
        int id3;

        MultisetPojo() {}
        MultisetPojo(int id2, int id3) {
            this.id2 = id2;
            this.id3 = id3;
        }
        @Override
        public int hashCode() {
            return Objects.hash(id2, id3);
        }
        @Override
        public boolean equals(Object obj) {
            if (this == obj)
                return true;
            if (obj == null)
                return false;
            if (getClass() != obj.getClass())
                return false;
            MultisetPojo other = (MultisetPojo) obj;
            return id2 == other.id2 && id3 == other.id3;
        }
    }

    static class MultisetListOfPojo {
        int id1;
        List<MultisetPojo> m;
    }

    static class MultisetSetOfPojo {
        int id1;
        Set<MultisetPojo> m;
    }

    // This test passes
    @Test
    public void testMultisetIntoListOfPojo() {
        List<MultisetListOfPojo> list = multiset().into(MultisetListOfPojo.class);

        assertEquals(2, list.size());
        assertEquals(asList(1, 2), seq(list).map(p -> p.id1).toList());
        assertEquals(asList(null, asList(new MultisetPojo(3, 4))), seq(list).map(p -> p.m).toList());
    }

    // This test fails
    @Test
    public void testMultisetIntoSetOfPojo() {
        List<MultisetSetOfPojo> set = multiset().into(MultisetSetOfPojo.class);

        assertEquals(2, set.size());
        assertEquals(asList(1, 2), seq(set).map(p -> p.id1).toList());
        assertEquals(asList(null, asList(new MultisetPojo(3, 4))), seq(set).map(p -> p.m).toList());
    }
```

The failure is:

```
org.jooq.exception.MappingException: An error occurred when mapping record to class org.jooq.test.RecordMappingTest$MultisetSetOfPojo
	at org.jooq.impl.DefaultRecordMapper$MutablePOJOMapper.map(DefaultRecordMapper.java:905)
	at org.jooq.impl.DefaultRecordMapper.map(DefaultRecordMapper.java:639)
	at org.jooq.RecordMapper.apply(RecordMapper.java:87)
	at org.jooq.impl.DefaultRecordMapper.apply(DefaultRecordMapper.java:1)
	at java.base/java.util.stream.Collectors.lambda$mapping$13(Collectors.java:469)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:1003)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.jooq.impl.ResultImpl.collect(ResultImpl.java:137)
	at org.jooq.impl.ResultImpl.into(ResultImpl.java:910)
	at org.jooq.test.RecordMappingTest.testMultisetIntoSetOfPojo(RecordMappingTest.java:1636)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: org.jooq.exception.DataTypeException: Cannot convert from +----+----+
| ID2| ID3|
+----+----+
|  *3|  *4|
+----+----+
 (class org.jooq.impl.ResultImpl) to interface java.util.Set
	at org.jooq.impl.Convert$ConvertAll.fail(Convert.java:1593)
	at org.jooq.impl.Convert$ConvertAll.from(Convert.java:1434)
	at org.jooq.impl.Convert.convert0(Convert.java:442)
	at org.jooq.impl.Convert.convert(Convert.java:517)
	at org.jooq.impl.DefaultConverterProvider.lambda$1(DefaultConverterProvider.java:121)
	at org.jooq.Converter$1.from(Converter.java:181)
	at org.jooq.impl.AbstractRecord.get(AbstractRecord.java:355)
	at org.jooq.impl.DefaultRecordMapper$MutablePOJOMapper.map(DefaultRecordMapper.java:932)
	at org.jooq.impl.DefaultRecordMapper$MutablePOJOMapper.map(DefaultRecordMapper.java:862)
	... 43 more
```

----
See also:
- https://github.com/jOOQ/jOOQ/issues/15477

**Comment by lukaseder** [comment]
The logic from any of theses makes the `List` mapping work:

- #3082
- #10910 
- #11213

In fact, the `Convert` utility just returns the `Result` itself, given it's already a `List`. It doesn't bother converting the `List` contents, given that the conversion type is just the raw type `List`. So, `DefaultRecordMapper` itself adds some additional reflection patching, because it still has a reference to the `java.lang.reflect.Field` or `java.lang.reflect.Method`, which have more generics information available through `Field::getGenericType` or `Method::getGenericParameterTypes` access.
