### ISSUE TITLE
Liquibase codegen: Class loading error when using CustomChanges

### ISSUE THREAD

**Issue by ZwoCa** [jOOQ/jOOQ#15512]
### Expected behavior

I'm using jooq-meta-extensions-liquibase to do code generation for a schema defined within a Liquibase changelog XML file.

The Liquibase changelog I use contains some [customChange type](https://docs.liquibase.com/change-types/custom-change.html) change sets. They reference a Java class (using it's fully qualified name), which is called by Liquibase when processing the changelog.

I'd expect this to not be a problem when using the jooq-meta-extensions-liquibase code generator, Liquibase should be able to execute the changesets, calling the referenced classes.

### Actual behavior

However, this causes problems when using the code generation in Mavens generate-sources phase. The class loader used by Liquibase will not find the referenced Java classes and accordingly, a ClassNotFoundException will be thrown:

```
[ERROR] Failed to execute goal org.jooq:jooq-codegen-maven:3.18.6:generate (default) on project jOOQ-liquibase-customchange-mcve: Error running jOOQ code generation tool: Error while exporting schema: liquibase.parser.core.ParsedNodeException: liquibase.exception.CustomChangeException: java.lang.ClassNotFoundException: customChanges.CustomChange -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jooq:jooq-codegen-maven:3.18.6:generate (default) on project jOOQ-liquibase-customchange-examplem: Error running jOOQ code generation tool
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:347)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:330)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:175)
	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:76)
	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:163)
	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:160)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:827)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:272)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:195)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error running jOOQ code generation tool
	at org.jooq.codegen.maven.Plugin.execute(Plugin.java:219)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:342)
	... 25 more
Caused by: org.jooq.exception.DataAccessException: Error while exporting schema
	at org.jooq.meta.extensions.AbstractInterpretingDatabase.connection(AbstractInterpretingDatabase.java:103)
	at org.jooq.meta.extensions.AbstractInterpretingDatabase.create0(AbstractInterpretingDatabase.java:77)
	at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:370)
	at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:360)
	at org.jooq.meta.AbstractDatabase.setConnection(AbstractDatabase.java:338)
	at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:551)
	at org.jooq.codegen.GenerationTool.run(GenerationTool.java:244)
	at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:239)
	at org.jooq.codegen.maven.Plugin.execute(Plugin.java:216)
	... 27 more
Caused by: liquibase.exception.ChangeLogParseException: liquibase.parser.core.ParsedNodeException: liquibase.exception.CustomChangeException: java.lang.ClassNotFoundException: customChanges.CustomChange
	at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:25)
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:408)
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:393)
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:249)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Liquibase.runInScope(Liquibase.java:2447)
	at liquibase.Liquibase.update(Liquibase.java:236)
	at liquibase.Liquibase.update(Liquibase.java:221)
	at liquibase.Liquibase.update(Liquibase.java:207)
	at liquibase.Liquibase.update(Liquibase.java:197)
	at org.jooq.meta.extensions.liquibase.LiquibaseDatabase.export(LiquibaseDatabase.java:158)
	at org.jooq.meta.extensions.AbstractInterpretingDatabase.connection(AbstractInterpretingDatabase.java:100)
	... 35 more
Caused by: liquibase.parser.core.ParsedNodeException: liquibase.exception.CustomChangeException: java.lang.ClassNotFoundException: customChanges.CustomChange
	at liquibase.change.custom.CustomChangeWrapper.load(CustomChangeWrapper.java:300)
	at liquibase.changelog.ChangeSet.toChange(ChangeSet.java:535)
	at liquibase.changelog.ChangeSet.handleChildNode(ChangeSet.java:460)
	at liquibase.changelog.ChangeSet.load(ChangeSet.java:384)
	at liquibase.changelog.DatabaseChangeLog.createChangeSet(DatabaseChangeLog.java:761)
	at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:395)
	at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:364)
	at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:23)
	... 49 more
Caused by: liquibase.exception.CustomChangeException: java.lang.ClassNotFoundException: customChanges.CustomChange
	at liquibase.change.custom.CustomChangeWrapper.setClass(CustomChangeWrapper.java:89)
	at liquibase.change.custom.CustomChangeWrapper.load(CustomChangeWrapper.java:298)
	... 56 more
Caused by: java.lang.ClassNotFoundException: customChanges.CustomChange
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at liquibase.change.custom.CustomChangeWrapper.setClass(CustomChangeWrapper.java:79)
	... 57 more
```

### Steps to reproduce the problem

Please see the following MCVE: https://github.com/ZwoCa/jOOQ-liquibase-customchange-mcve

The codegen configuration is pretty basic:
```
<configuration>
	<generator>
		<database>
			<name>org.jooq.meta.extensions.liquibase.LiquibaseDatabase</name>
			<properties>
				<property>
					<key>rootPath</key>
					<value>${basedir}/src/main/resources</value>
				</property>
				<property>
					<key>scripts</key>
					<value>liquibase-changelog.xml</value>
				</property>
			</properties>
		</database>
	</generator>
</configuration>
```

When commenting out the customChange in [Liquibase changelog](https://github.com/ZwoCa/jOOQ-liquibase-customchange-mcve/blob/master/src/main/resources/liquibase-changelog.xml), it will work.

### jOOQ Version

All editions

### Database product and version

unrelated

### Java Version

openjdk 17.0.7 2023-04-18

### OS Version

Microsoft Windows [Version 10.0.19045.3324]

**Comment by lukaseder** [comment]
Thanks for your message. That's probably a new Liquibase feature? Can you try upgrading the transitive dependency on the jOOQ code generation plugin to see if tha fixes it on your end?

We currently have a `4.21.0` dependency. I'll check if we can upgrade to `4.23.1` in the next release.

Note, there's also this third party contribution that runs the liquibase migration in testcontainers, instead of simulating it using H2 as we do:
https://github.com/testcontainers/testcontainers-jooq-codegen-maven-plugin

Perhaps that will work better for you? You can also easily do this yourself, directly in your maven build. Here's an example of doing that with Flyway. It should work the same way with Liquibase:
https://blog.jooq.org/using-testcontainers-to-generate-jooq-code/

**Comment by lukaseder** [comment]
Ah no, I'm sorry, I get it now. `CustomChange` is your own custom class. Well, you have to compile that before generating jOOQ code in order to put it on the jOOQ classpath. jOOQ doesn't know what this is, nor how to compile it for you.

It works the same way as what's documented here for the `JPADatabase`, which needs JPA entities to be compiled *before* you start code generation:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-jpa/

See this chart for an explanation:

```
                        +-------------------+
                        | Your JPA entities |
                        +-------------------+
                             ^         ^
                  depends on |         | depends on
                             |         |
          +---------------------+   +---------------------+
          | jOOQ codegen plugin |   | Your application    |
          +---------------------+   +---------------------+
                             |         |
                   generates |         | depends on
                             v         v
                     +-------------------------+
                     | jOOQ generated classes  |
                     +-------------------------+
```
