### ISSUE TITLE
MutablePOJOMapper should be able to map to instance, even if there isn't a default constructor

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15564]
In the context of https://github.com/jOOQ/jOOQ/issues/15563, I attempted to write a unit test like this:

```java
class X {
    Integer i;

    X(Integer i) {
        this.i = i;
    }
}

X x = new X(null);
XRecord r = new XRecord(1);
r.into(x);
```

But this mapping failed. The POJO is mutable, though it lacks a default constructor, so jOOQ tries to invoke the `ImmutablePOJOMapper`. However, since we already have an instance, no constructor call is necessary.

I'm not sure if this needs to be fixed yet. It's certainly confusing, though.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.19.0
- 3.18.7 (https://github.com/jOOQ/jOOQ/issues/15579)
- 3.17.16 (https://github.com/jOOQ/jOOQ/issues/15580)
- 3.16.22 (https://github.com/jOOQ/jOOQ/issues/15581)

**Comment by lukaseder** [comment]
I'm reverting the change for now. This accessibility issue is really weird:

```
[ERROR] org.jooq.codegen.test.nullability.NullabilityTest.testDAO  Time elapsed: 0.016 s  <<< ERROR!
org.jooq.exception.MappingException: An error occurred when mapping record to class org.jooq.codegen.test.nullability.db.tables.pojos.Nullability
        at org.jooq.impl.DefaultRecordMapper$MutablePOJOMapper.map(DefaultRecordMapper.java:922)
        at org.jooq.impl.DefaultRecordMapper.map(DefaultRecordMapper.java:646)
        at org.jooq.impl.AbstractRecord.into(AbstractRecord.java:826)
        at org.jooq.impl.TableRecordImpl.into(TableRecordImpl.java:110)
        at org.jooq.impl.DAOImpl.lambda$records$0(DAOImpl.java:461)
        at org.jooq.impl.CallbackRecordListener.insertEnd(CallbackRecordListener.java:134)
        at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:173)
        at org.jooq.impl.TableRecordImpl.storeInsert(TableRecordImpl.java:162)
        at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:150)
        at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:145)
        at org.jooq.impl.DAOImpl.insert(DAOImpl.java:181)
        at org.jooq.impl.DAOImpl.insert(DAOImpl.java:157)
        at org.jooq.codegen.test.nullability.NullabilityTest.testDAO(NullabilityTest.kt:129)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Caused by: java.lang.IllegalAccessException: class org.jooq.impl.DefaultRecordMapper$MutablePOJOMapper cannot access a member of class org.jooq.codegen.test.nullability.db.tables.pojos.Nullability with modifiers "private"
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
        at java.base/java.lang.reflect.Field.checkAccess(Field.java:1102)
        at java.base/java.lang.reflect.Field.setInt(Field.java:982)
        at org.jooq.impl.DefaultRecordMapper$MutablePOJOMapper.map(DefaultRecordMapper.java:986)
        at org.jooq.impl.DefaultRecordMapper$MutablePOJOMapper.map(DefaultRecordMapper.java:935)
        at org.jooq.impl.DefaultRecordMapper$MutablePOJOMapper.map(DefaultRecordMapper.java:879)
        ... 42 more
```

It's probably `DAO` specific, but seeing how many folks use these DAOs (and kotlin), I don't want to risk such an important regression for a bug that hasn't been discovered in 10 years.

**Comment by lukaseder** [comment]
I see now why the accessibility problem happens. We first initialise an `ImmutablePOJOMapper` for this data class (due to the lack of default constructor as there are non-nullable members).

Then later on, the reflection cache kicks in when we should use the `MutablePOJOMapper`, and we're no longer looking up members nor making them accessible.

**Comment by lukaseder** [comment]
If I add the `makeAccessible` flag to the reflection cache key, then we are able to do a second reflection lookup, and the regression goes away, as well as the bugs reported here:

- https://github.com/jOOQ/jOOQ/issues/15559
- https://github.com/jOOQ/jOOQ/issues/15655

**Comment by lukaseder** [comment]
So, as originally planned:

Fixed in versions:

- 3.19.0
- 3.18.7 (https://github.com/jOOQ/jOOQ/issues/15579)
- 3.17.16 (https://github.com/jOOQ/jOOQ/issues/15580)
- 3.16.22 (https://github.com/jOOQ/jOOQ/issues/15581)
