### ISSUE TITLE
Record::merge should bind to temporary clobs for strings > 4000 chars in oracle

### ISSUE THREAD

**Issue by theodiefenthal** [jOOQ/jOOQ#15595]
### Expected behavior

I first reported my problem on StackOverflow as question thinking it was a usage problem on how to merge into oracle with a CLOB column ( https://stackoverflow.com/questions/77100531/jooq-how-to-merge-with-oracle-clob-column-fitting-into-a-string ) but now I have spent some more thoughts on this and would consider the current behavior as a bug or at least a JOOQ feature request.

Given I have a  table `ASSETINFO` with the columns `IP` (varchar) and `REPORT` (CLOB) in an Oracle 19 database. The reports have a size of 100 to 100.000 characters and hence fit well into a Java string. The IP column is my primary key. I now want to merge incoming reports into the table: If not exists insert, otherwise overwrite the existing one. 

If I use JOOQ Record style API for this like:

```java
final AssetInfoRecord record = ctx.newRecord(ASSET_INFO);
            record.setIpAddr("1.1.1.1");
            record.setReport("*".repeat(60000));
            record.merge();
```

I receive an ORA-04161 error for strings greater 4000 characters in my CLOB column. 

Under the hood, JOOQ transforms the record merge into an oracle merge statement with style `MERGE INTO ASSET_INFO USING (SELECT <hardcoded values>) WHEN MATCHED THEN UPDATE ...`  

The solution should hence be that as JOOQ knows the merge is going to happen to a CLOB column, jooq should check the length of the string and if it is longter then 4000 characters, bind a temp clob (at least if JOOQ ClobBinding is active for that column)). 

Ideally, JOOQ would also make the following queries work as well with temp clob bindings:
```java
ctx.insertInto(ASSET_INFO)
        .set(ASSET_INFO.IP_ADDR, "1.1.1.1")
        .set(ASSET_INFO.REPORT, "*".repeat(60000))
        .onDuplicateKeyUpdate()
        .set(ASSET_INFO.REPORT, "*".repeat(60000))
        .execute();
```

```java
Table<Record2<String, String>> toMerge = DSL
		.values(DSL.row("1.1.1.1", "*".repeat(60000)))
		.as("toMerge", ASSET_INFO.IP_ADDR.getName(),  ASSET_INFO.REPORT.getName());

ctx
		.mergeInto(ASSET_INFO)
		.using(toMerge)
		.on(ASSET_INFO.IP_ADDR.eq(toMerge.field(ASSET_INFO.IP_ADDR)))
		.whenMatchedThenUpdate()
		.set(ASSET_INFO.REPORT, toMerge.field(ASSET_INFO.REPORT))
		.whenNotMatchedThenInsert()
		.set(ASSET_INFO.IP_ADDR, toMerge.field(ASSET_INFO.IP_ADDR))
		.set(ASSET_INFO.REPORT, toMerge.field(ASSET_INFO.REPORT))
		.execute();
```

### Actual behavior

For all 3 queries above, I receive an ORA-10461 error if I use strings > 4000 charts, with and without ForcedType of ClobBinding on the REPORT CLOB column. 

### Steps to reproduce the problem

Create above table and execute mentioned queries

### jOOQ Version

jOOQ Professional Edition 3.17

### Database product and version

Oracle 19

### Java Version

OpenJDK 11

**Comment by lukaseder** [comment]
Thanks for your report. This seems related:

- https://github.com/jOOQ/jOOQ/issues/13840

**Comment by lukaseder** [comment]
Finally looking into this now. I can reproduce the following exception:

```
org.jooq.exception.DataAccessException: SQL [merge into "TEST"."T_BOOK" using ((select ? "ID", ? "AUTHOR_ID", ? "TITLE", ? "PUBLISHED_IN", ? "LANGUAGE_ID", ? "CONTENT_TEXT", ? "REC_VERSION", ? "REC_TIMESTAMP")) "t" on ((("TEST"."T_BOOK"."ID", 1) = (("t"."ID", 1)) or 1 = 0)) when matched then update set "TEST"."T_BOOK"."ID" = "t"."ID", "TEST"."T_BOOK"."AUTHOR_ID" = "t"."AUTHOR_ID", "TEST"."T_BOOK"."TITLE" = "t"."TITLE", "TEST"."T_BOOK"."PUBLISHED_IN" = "t"."PUBLISHED_IN", "TEST"."T_BOOK"."LANGUAGE_ID" = "t"."LANGUAGE_ID", "TEST"."T_BOOK"."CONTENT_TEXT" = "t"."CONTENT_TEXT", "TEST"."T_BOOK"."REC_VERSION" = "t"."REC_VERSION", "TEST"."T_BOOK"."REC_TIMESTAMP" = "t"."REC_TIMESTAMP" when not matched then insert ("ID", "AUTHOR_ID", "TITLE", "PUBLISHED_IN", "LANGUAGE_ID", "CONTENT_TEXT", "REC_VERSION", "REC_TIMESTAMP") values ("t"."ID", "t"."AUTHOR_ID", "t"."TITLE", "t"."PUBLISHED_IN", "t"."LANGUAGE_ID", "t"."CONTENT_TEXT", "t"."REC_VERSION", "t"."REC_TIMESTAMP")]; ORA-01461: The value at bind position 6 exceeded the maximum VARCHAR2 length.

	at org.jooq_3.19.0-SNAPSHOT.ORACLE23C.debug(Unknown Source) ~[?:?]
	at org.jooq.impl.Tools.translate(Tools.java:3509) ~[classes/:?]
	at org.jooq.impl.Tools.translate(Tools.java:3497) ~[classes/:?]
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:812) ~[classes/:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:362) ~[classes/:?]
	at org.jooq.impl.UpdatableRecordImpl.storeMergeOrUpdate0(UpdatableRecordImpl.java:354) ~[classes/:?]
	at org.jooq.impl.UpdatableRecordImpl.storeMerge0(UpdatableRecordImpl.java:268) ~[classes/:?]
	at org.jooq.impl.UpdatableRecordImpl.lambda$2(UpdatableRecordImpl.java:248) ~[classes/:?]
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144) [classes/:?]
	at org.jooq.impl.UpdatableRecordImpl.storeMerge(UpdatableRecordImpl.java:247) [classes/:?]
	at org.jooq.impl.UpdatableRecordImpl.merge(UpdatableRecordImpl.java:183) [classes/:?]
	at org.jooq.impl.UpdatableRecordImpl.merge(UpdatableRecordImpl.java:178) [classes/:?]
	at org.jooq.test.all.testcases.CRUDTests.testUpdatablesMergeLargeStrings(CRUDTests.java:473) [test-classes/:?]
	at org.jooq.test.jOOQAbstractTest.testUpdatablesMergeLargeStrings(jOOQAbstractTest.java:7694) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.13.2.jar:4.13.2]
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61) [junit-4.13.2.jar:4.13.2]
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) [junit-4.13.2.jar:4.13.2]
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
Caused by: java.sql.SQLException: ORA-01461: The value at bind position 6 exceeded the maximum VARCHAR2 length.

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:629) ~[ojdbc11-21.9.0.0.jar:21.9.0.0.0]
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:563) ~[ojdbc11-21.9.0.0.jar:21.9.0.0.0]
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1230) ~[ojdbc11-21.9.0.0.jar:21.9.0.0.0]
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:771) ~[ojdbc11-21.9.0.0.jar:21.9.0.0.0]
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298) ~[ojdbc11-21.9.0.0.jar:21.9.0.0.0]
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:511) ~[ojdbc11-21.9.0.0.jar:21.9.0.0.0]
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:162) ~[ojdbc11-21.9.0.0.jar:21.9.0.0.0]
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1240) ~[ojdbc11-21.9.0.0.jar:21.9.0.0.0]
	at oracle.jdbc.driver.OracleStatement.executeSQLStatement(OracleStatement.java:1819) ~[ojdbc11-21.9.0.0.jar:21.9.0.0.0]
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1471) ~[ojdbc11-21.9.0.0.jar:21.9.0.0.0]
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3760) ~[ojdbc11-21.9.0.0.jar:21.9.0.0.0]
	at oracle.jdbc.driver.OraclePreparedStatement.executeLargeUpdate(OraclePreparedStatement.java:4061) ~[ojdbc11-21.9.0.0.jar:21.9.0.0.0]
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:4036) ~[ojdbc11-21.9.0.0.jar:21.9.0.0.0]
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:995) ~[ojdbc11-21.9.0.0.jar:21.9.0.0.0]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.executeUpdate(DefaultPreparedStatement.java:109) ~[classes/:?]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.executeUpdate(DefaultPreparedStatement.java:109) ~[classes/:?]
	at org.jooq.impl.AbstractDMLQuery.executeReturningGeneratedKeys(AbstractDMLQuery.java:1241) ~[classes/:?]
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:1215) ~[classes/:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:348) ~[classes/:?]
	... 41 more
Caused by: oracle.jdbc.OracleDatabaseException: ORA-01461: The value at bind position 6 exceeded the maximum VARCHAR2 length.

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:636) ~[ojdbc11-21.9.0.0.jar:21.9.0.0.0]
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:563) ~[ojdbc11-21.9.0.0.jar:21.9.0.0.0]
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1230) ~[ojdbc11-21.9.0.0.jar:21.9.0.0.0]
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:771) ~[ojdbc11-21.9.0.0.jar:21.9.0.0.0]
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298) ~[ojdbc11-21.9.0.0.jar:21.9.0.0.0]
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:511) ~[ojdbc11-21.9.0.0.jar:21.9.0.0.0]
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:162) ~[ojdbc11-21.9.0.0.jar:21.9.0.0.0]
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1240) ~[ojdbc11-21.9.0.0.jar:21.9.0.0.0]
	at oracle.jdbc.driver.OracleStatement.executeSQLStatement(OracleStatement.java:1819) ~[ojdbc11-21.9.0.0.jar:21.9.0.0.0]
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1471) ~[ojdbc11-21.9.0.0.jar:21.9.0.0.0]
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3760) ~[ojdbc11-21.9.0.0.jar:21.9.0.0.0]
	at oracle.jdbc.driver.OraclePreparedStatement.executeLargeUpdate(OraclePreparedStatement.java:4061) ~[ojdbc11-21.9.0.0.jar:21.9.0.0.0]
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:4036) ~[ojdbc11-21.9.0.0.jar:21.9.0.0.0]
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:995) ~[ojdbc11-21.9.0.0.jar:21.9.0.0.0]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.executeUpdate(DefaultPreparedStatement.java:109) ~[classes/:?]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.executeUpdate(DefaultPreparedStatement.java:109) ~[classes/:?]
	at org.jooq.impl.AbstractDMLQuery.executeReturningGeneratedKeys(AbstractDMLQuery.java:1241) ~[classes/:?]
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:1215) ~[classes/:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:348) ~[classes/:?]
	... 41 more
```

I'm still investigating if we should implement any `MERGE` / `CLOB` specific logic. After all, binding strings works almost everywhere else, so I'm tempted to claim that these things are bugs in ojdbc or OCI, and it might be hard to reverse engineer the exact set of rules when a `String` should be bound as `Clob`. But if we do this too often, then there's risk for other types of regressions that might not yet be covered in our integration tests.

Blindly binding all `CLOB` values as `java.sql.Clob` automatically produces this regression, for example:

```
org.jooq.exception.DataAccessException: SQL [update "TEST"."T_LONG_AND_CLOB" set "TEST"."T_LONG_AND_CLOB"."LONGX" = ? where "TEST"."T_LONG_AND_CLOB"."ID" = ?]; ORA-22835: Buffer too small for CLOB to CHAR or BLOB to RAW conversion (actual: 21000, maximum: 4000)

	at org.jooq_3.19.0-SNAPSHOT.ORACLE23C.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3509)
	at org.jooq.impl.Tools.translate(Tools.java:3497)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:812)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:362)
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
	at org.jooq.test.OracleTest.testOracleLongAndClob(OracleTest.java:2911)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.sql.SQLException: ORA-22835: Buffer too small for CLOB to CHAR or BLOB to RAW conversion (actual: 21000, maximum: 4000)

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:629)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:563)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1230)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:771)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:511)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:162)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1240)
	at oracle.jdbc.driver.OracleStatement.executeSQLStatement(OracleStatement.java:1819)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1471)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3760)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:4135)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1013)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:458)
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:1016)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:348)
	... 34 more
Caused by: Error : 22835, Position : 72, Sql = update "TEST"."T_LONG_AND_CLOB" set "TEST"."T_LONG_AND_CLOB"."LONGX" = :1  where "TEST"."T_LONG_AND_CLOB"."ID" = :2 , OriginalSql = update "TEST"."T_LONG_AND_CLOB" set "TEST"."T_LONG_AND_CLOB"."LONGX" = ? where "TEST"."T_LONG_AND_CLOB"."ID" = ?, Error Msg = ORA-22835: Buffer too small for CLOB to CHAR or BLOB to RAW conversion (actual: 21000, maximum: 4000)

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:636)
	... 50 more
```

Very subtle, as it is using a `LONG` type (which is probably rare these days, but still...)

Then, there's the "new" `MAX_STRING_SIZE` flag that can be set to `EXTENDED` to make `VARCHAR2` accept 32kb strings. We currently don't detect any such server settings dynamically (which would require extra roundtrips, and possibly stale caches), so if any limit should be checked, then it would have to be made configurable (or we just make it 4000 bytes, ignoring the "new" `EXTENDED` value). I guess we can add such a configuration later, still.

Anyway, we already did something `CLOB` specific for inlined values (where it was necessary irrespective of the statement type): #6516, so we can definitely do something here as well.

**Comment by lukaseder** [comment]
We currently can't recognise a `MERGE` statement from the context provided to a bind variable when binding it to JDBC. The statement being executed is an `INSERT` (or rather `UPSERT`) statement:

```
java.lang.Throwable
	at org.jooq.impl.DefaultBinding$DefaultStringBinding.set0(DefaultBinding.java:4539)
	at org.jooq.impl.DefaultBinding$DefaultStringBinding.set0(DefaultBinding.java:1)
	at org.jooq.impl.DefaultBinding$InternalBinding.set(DefaultBinding.java:1107)
	at org.jooq.impl.DefaultBindContext.bindValue0(DefaultBindContext.java:65)
	at org.jooq.impl.AbstractBindContext.bindValue(AbstractBindContext.java:74)
	at org.jooq.impl.Val.accept(Val.java:216)
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:258)
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:68)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:360)
	at org.jooq.impl.QueryPartCollectionView.acceptElement(QueryPartCollectionView.java:256)
	at org.jooq.impl.QueryPartCollectionView.accept(QueryPartCollectionView.java:226)
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:258)
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:68)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:360)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:344)
	at org.jooq.impl.UpdatableRecordImpl.storeMergeOrUpdate0(UpdatableRecordImpl.java:354)
	at org.jooq.impl.UpdatableRecordImpl.storeMerge0(UpdatableRecordImpl.java:268)
	at org.jooq.impl.UpdatableRecordImpl.lambda$2(UpdatableRecordImpl.java:248)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144)
	at org.jooq.impl.UpdatableRecordImpl.storeMerge(UpdatableRecordImpl.java:247)
	at org.jooq.impl.UpdatableRecordImpl.merge(UpdatableRecordImpl.java:183)
	at org.jooq.impl.UpdatableRecordImpl.merge(UpdatableRecordImpl.java:178)
	at org.jooq.test.all.testcases.CRUDTests.testUpdatablesMergeLargeStrings(CRUDTests.java:472)
	at org.jooq.test.jOOQAbstractTest.testUpdatablesMergeLargeStrings(jOOQAbstractTest.java:7694)
```

It renders as `MERGE`, but this information is lost in the `ExecuteContext` / `BindingSetStatementContext`

**Comment by lukaseder** [comment]
So, when rendering the `MergeImpl` statement, we can communicate this fact to the `ExecuteContext::data` map, which can then be picked up later by the bind values.

This still doesn't distinguish between the actual `MERGE` statement (where we want to bind a `Clob`) and the `USING (...)` clause, for example (where we might not want to change behaviour). But I don't see an easy way to distinguish these, without tagging all bind values with some context information (which seems excessive just for this bug).

**Comment by lukaseder** [comment]
Another bug needs to be fixed first before this approach can be taken:

- https://github.com/jOOQ/jOOQ/issues/15724

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.19.0
- 3.18.8 (https://github.com/jOOQ/jOOQ/issues/15728)
- 3.17.17 (https://github.com/jOOQ/jOOQ/issues/15729)
- 3.16.23 (https://github.com/jOOQ/jOOQ/issues/15730)

**Comment by theodiefenthal** [comment]
Cool, thanks for fixing it :) That'll work for me. 

Just as a small addition, I found an article in the oracle support database about this issue. So the issue is not directly related to MERGE but more like a general issues with type interference I would say. But I don't know if I am allowed to share more details about it publically as Oracle put that article behind their support paywall...

Here is the link: https://support.oracle.com/knowledge/Middleware/1620109_1.html

**Comment by lukaseder** [comment]
Thanks for the additional info. Some folks at Oracle are open for feedback on their community forums as well: https://forums.oracle.com/ords/apexds/domain/dev-community. I've usually reported bugs there, and things then happen much more quickly than if done via the commercial support channels.

**Comment by lukaseder** [comment]
I might try to create an MCVE for Oracle to report there soon, based on this example:

- https://github.com/jOOQ/jOOQ/issues/13840#issuecomment-1256283295

Perhaps, they can fix this relatively easily.
