### ISSUE TITLE
RenderMapping doesn't apply to QualifiedRowid

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15639]
A generic integration test covering `RenderMapping` functionality discovered that `QualifiedRowid` doesn't apply the schema mapping:

```
java.lang.AssertionError: Query contains default schema, which should be mapped: delete from xyz.T_AUTHOR where PUBLIC.T_AUTHOR._rowid_ in (select PUBLIC.T_AUTHOR._rowid_ from xyz.T_AUTHOR where xyz.T_AUTHOR.ID = cast(? as int) order by T_AUTHOR.ID desc fetch next ? rows only)
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertFalse(Assert.java:65)
	at org.jooq.test.all.listeners.SchemaMappingListener.renderEnd(SchemaMappingListener.java:98)
	at org.jooq.impl.ExecuteListeners.renderEnd(ExecuteListeners.java:188)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:305)
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
	at org.jooq.test.all.testcases.InlineDerivedTableTests.testInlineDerivedTableInDeleteOrderByLimit(InlineDerivedTableTests.java:769)
	at org.jooq.test.jOOQAbstractTest.testInlineDerivedTableInDeleteOrderByLimit(jOOQAbstractTest.java:12246)
```

(See the `PUBLIC.T_AUTHOR._rowid_`)

The implementation does this:

```java
ctx.visit(table.getQualifiedName().append(systemName("_rowid_")));
```

**Comment by lukaseder** [comment]
I'm fixing it only for jOOQ 3.19 because:

- It's an unlikely thing for anyone to run into
- The fix depends on new internal API from jOOQ 3.19 (which was introduced at first due to UDT paths)

If a user runs into this limitation, they can still request a backport.
