### ISSUE TITLE
Using forceIntegerTypesOnZeroScaleDecimals = false incorrectly generates java type for numeric types

### ISSUE THREAD

**Issue by jaroslav-sagan-evooq** [jOOQ/jOOQ#15778]
### Expected behavior

I want to have `decimal` and `numeric` type with zero scale decimals generated as `BigDecimal`, to achieve that I'm using:
```
<forceIntegerTypesOnZeroScaleDecimals>false</forceIntegerTypesOnZeroScaleDecimals>
```
The expected behaviour is correct for `decimal` types but incorrect for `numeric` types.

Since this is already applied schema, as a workaround I have to create a new change set to change the type to `decimal`.

It seems like this issue is fixed in the version `3.18.7`, unfortunately I can't use this version, since it is targeting PostgreSQL 15 (and also using features from it). We are using PostgreSQL 14 and the latest version of jOOQ makes some of our queries incompatible.

### Actual behavior

Numeric types are generated as `Object` type in Java:
<img width="1178" alt="Screenshot 2023-10-31 at 11 22 30" src="https://github.com/jOOQ/jOOQ/assets/117176666/1cc5f94a-a1ee-4d49-b47b-f63f7b293064">

### Steps to reproduce the problem

Use the follow setting with `numeric` type
```
<forceIntegerTypesOnZeroScaleDecimals>false</forceIntegerTypesOnZeroScaleDecimals>
```

Here is the Liquibase changeset:
<img width="301" alt="Screenshot 2023-10-31 at 11 23 10" src="https://github.com/jOOQ/jOOQ/assets/117176666/6a0f9baf-47a5-4ec3-bce7-7d915b538823">

### jOOQ Version

3.17.16

### Database product and version

PostgreSQL 14

### Java Version

openjdk version "17.0.7" 2023-04-18 LTS

### OS Version

MacOS 14.0

### JDBC driver name and version (include name if unofficial driver)

org.postgresql.postgresql:42.3.8

**Comment by lukaseder** [comment]
Tried reproducing this with:

```sql
create table t_15778 (
  d decimal,
  n numeric
);
```

Doesn't seem to cause any issue in snapshot versions 3.19.0, 3.18.8, and 3.17.17:

```java
    /**
     * The column <code>public.t_15778.d</code>.
     */
    public final TableField<T_15778Record, BigDecimal> D = createField(DSL.name("d"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.t_15778.n</code>.
     */
    public final TableField<T_15778Record, BigDecimal> N = createField(DSL.name("n"), SQLDataType.NUMERIC, this, "");
```

Can you please provide a complete reproducer following the template here: https://github.com/jOOQ/jOOQ-mcve

**Comment by lukaseder** [comment]
Thanks a lot, I'll look into it right away

**Comment by lukaseder** [comment]
I can reproduce this test assertion error:

```
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.688 s <<< FAILURE! -- in org.jooq.mcve.java.h2.MyAppTest
[ERROR] org.jooq.mcve.java.h2.MyAppTest.testType -- Time elapsed: 0.661 s <<< FAILURE!
java.lang.AssertionError: expected:<class java.math.BigDecimal> but was:<class java.lang.Object>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:120)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at org.jooq.mcve.java.h2.MyAppTest.testType(MyAppTest.java:13)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at junit.framework.TestCase.runTest(TestCase.java:177)
        at junit.framework.TestCase.runBare(TestCase.java:142)
        at junit.framework.TestResult$1.protect(TestResult.java:122)
        at junit.framework.TestResult.runProtected(TestResult.java:142)
        at junit.framework.TestResult.run(TestResult.java:125)
        at junit.framework.TestCase.run(TestCase.java:130)
        at junit.framework.TestSuite.runTest(TestSuite.java:241)
        at junit.framework.TestSuite.run(TestSuite.java:236)
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
```

**Comment by lukaseder** [comment]
Ah, I see. This is using the `LiquibaseDatabase`, which in turn is using an in-memory H2 database to simulate the Liquibase migration, see:
https://blog.jooq.org/how-to-simulate-a-liquibase-migration-using-h2/

Though, the H2 dependency hasn't been upgraded between 3.17 and 3.18. The most recent upgrades were:

- 3.17: https://github.com/jOOQ/jOOQ/issues/13700
- 3.19: https://github.com/jOOQ/jOOQ/issues/15350 and https://github.com/jOOQ/jOOQ/issues/15608

But Liquibase was upgraded from `4.8.0` to `4.17.2`, so upgrading the transitive `liquibase-core` dependency of `jooq-meta-extensions-liquibase` solves the problem for me.

Also, using explicit precision and scale seems to help, e.g.:

![image](https://github.com/jOOQ/jOOQ/assets/734593/3f464143-f444-411a-9538-749e2db9ecd3)

I hope this helps
