### ISSUE TITLE
LazyVal::generatesCast should return true

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15799]
#4466 introduced a new `QueryPartInternal::generatesCast` method. This method isn't overridden by `LazyVal`, which extends `AbstractParamX`, not `AbstractParam`, which currently contains the method override:

```java
    @Override
    public final boolean generatesCast() {
        return true;
    }
```

This has produced a very subtle problem in a new QOM replacement API integration test with the following exception:

```
java.lang.AssertionError: expected:<insert into "TEST"."T_AUTHOR" ("ID", "LAST_NAME", "FIRST_NAME", "YEAR_OF_BIRTH")
values (
  37, 
  'Dürrenmatt', 
  cast(null as varchar(50)), 
  cast(null as int)
), (
  88, 
  'Schmitt', 
  'Eric Emmanuel', 
  cast(null as int)
), (
  93, 
  'Kaestner', 
  cast(null as varchar(50)), 
  1899
)> but was:<insert into "TEST"."T_AUTHOR" ("ID", "LAST_NAME", "FIRST_NAME", "YEAR_OF_BIRTH")
values (
  37, 
  'Dürrenmatt', 
  null, 
  null
), (
  88, 
  'Schmitt', 
  'Eric Emmanuel', 
  null
), (
  93, 
  'Kaestner', 
  null, 
  1899
)>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.jooq.test.util.BaseTest.assertEquals(BaseTest.java:334)
	at org.jooq.test.util.BaseTest.qomAssertions(BaseTest.java:860)
	at org.jooq.test.jOOQAbstractTest$QOMAssertionListener.start(jOOQAbstractTest.java:439)
	at org.jooq.impl.ExecuteListeners.start(ExecuteListeners.java:160)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:284)
	at org.jooq.test.all.testcases.InsertUpdateTests.testInsertMultipleTrailingNewRecordCall(InsertUpdateTests.java:1521)
	at org.jooq.test.jOOQAbstractTest.testInsertMultipleTrailingNewRecordCall(jOOQAbstractTest.java:7032)
```

The test asserts that an identity replacement shouldn't produce a new query:

```java
QueryPart r = p.$replace(x -> x);
assertEquals(p, r);
```

The underlying problem here is that there's something wrong with `InsertQueryImpl::$replace` as well, but the cast problem can be fixed independently.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.19.0
- 3.18.8 (https://github.com/jOOQ/jOOQ/issues/15800)
- 3.17.17 (https://github.com/jOOQ/jOOQ/issues/15801)
- 3.16.23 (https://github.com/jOOQ/jOOQ/issues/15802)
