### ISSUE TITLE
MetaImpl reports system indexes for Derby 10.16

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15803]
I've recently upgraded our Derby dependency from `10.14.2.0` -> `10.16.1.1`, see:

- https://github.com/jOOQ/jOOQ/issues/15442#issuecomment-1801607146

We're now getting regressions in `MetaImpl` integration tests, e.g.:

```java
Table<?> t = table(name(schema().getName(), "t"));
Field<?> id = metaDataIntField("id");
Field<?> ref = metaDataIntField("ref");

try {
    Query q = create()
        .createTable(t)
        .columns(id, ref)
        .constraints(
            constraint("pk").primaryKey(id),
            constraint("fk").foreignKey(ref).references(t, (Field) id)
        );
    q.execute();
    assertEmptyMigration(q, t);

    ...
```

The assertion error is:

```
java.lang.AssertionError: create index "TEST"."SQL0000000204-4e3c84a2-018b-aead-dd72-000006a4a5b0" on "TEST"."t"("ref" asc);
create unique index "TEST"."SQL0000000203-1bec44a0-018b-aead-dd72-000006a4a5b0" on "TEST"."t"("id" asc); expected:<0> but was:<2>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.jooq.test.util.BaseTest.assertEquals(BaseTest.java:338)
	at org.jooq.test.all.testcases.MetaDataTests.assertEmptyQueries(MetaDataTests.java:1581)
	at org.jooq.test.all.testcases.MetaDataTests.assertEmptyMigration(MetaDataTests.java:1576)
	at org.jooq.test.all.testcases.MetaDataTests.testMetaDataSystemIndexes_FK(MetaDataTests.java:1469)
	at org.jooq.test.jOOQAbstractTest.testMetaDataSystemIndexes_FK(jOOQAbstractTest.java:4996)
```

It seems that Derby's JDBC driver now reports system indexes for primary/unique/foreign key constraints. In other words, we're not correctly implementing `Settings.metaIncludeSystemIndexes`

**Comment by lukaseder** [comment]
The problem is the index name. We're matching:

```java
P_SYSINDEX_DERBY = Pattern.compile("^(?i:SQL\\d{14,}).*$");
```

It seems that the number preceding the UUID has been shortened.

**Comment by lukaseder** [comment]
Fixed in versions

- 3.19.0
- 3.18.8 (https://github.com/jOOQ/jOOQ/issues/15804)
- 3.17.17 (https://github.com/jOOQ/jOOQ/issues/15806)
- 3.16.23 (https://github.com/jOOQ/jOOQ/issues/15805)
