### ISSUE TITLE
GROUP_CONCAT in MySQL doesn't work, in Postgres its working

### ISSUE THREAD

**Issue by tkaryadis** [jOOQ/jOOQ#15838]
### Expected behavior

I try this simple example from JOOQ manual(4.11.21.23. GROUP_CONCAT) : 
```
create.select(groupConcat(BOOK.ID)).from(BOOK).fetch();
```
I use Clojure so i wrote it like that : 
```
(def query (-> @ctx   ;;the dsl context
               (.select
                 [(DSL/groupConcat (DSL/field "ID"))])
               (.from [(DSL/table "BOOK")])))

(prn (.getSQL query))
(.fetch query)
```
In Postgres this code is working fine i get (1,2,3,4), in MySQL, SQL string generated works, but .fetch doesnt.

The SQL string that i get is this and its working,i tested it : 
```
"set @t = @@group_concat_max_len; set @@group_concat_max_len = 4294967295; select group_concat(ID separator ',') from BOOK; set @@group_concat_max_len = @t;"
```

### Actual behavior

But the .fetch returns this :  (in MySQL only, in Postgres code is working fine)
```
Caused by: org.jooq.exception.DataAccessException: SQL [set @t = @@group_concat_max_len; set @@group_concat_max_len = 4294967295; select group_concat(ID separator ',') from BOOK; set @@group_concat_max_len = @t;]; You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'set @@group_concat_max_len = 4294967295; select group_concat(ID separator ',') f' at line 1
	at org.jooq_3.18.7.MYSQL.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3470)
	at org.jooq.impl.Tools.translate(Tools.java:3458)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:802)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:360)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:290)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2838)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:167)
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:438)
	at squery_jooq.c4_11column_expressions.t4_11_21accumulators.accumulators$eval731.invokeStatic(accumulators.clj:49)
	at squery_jooq.c4_11column_expressions.t4_11_21accumulators.accumulators$eval731.invoke(accumulators.clj:49)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	... 9 more
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'set @@group_concat_max_len = 4294967295; select group_concat(ID separator ',') f' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:912)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4734)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:236)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:346)
	... 21 more
```
**Versions**
MySql Server version: 8.0.35-0ubuntu0.22.04.1 (Ubuntu)
[com.mysql/mysql-connector-j "8.2.0"]
[org.jooq/jooq "3.18.7"]

I tried some other connectors also, but it didn't work.
Based on the support matrix for MySQL : 3.18 (latest)	5.6, 5.7, 8.0, 8.0.19, 8.0.20, 8.0.31	8.0.31 (minimun)
Looks like it should be able to run it, i am new to JOOQ i hope i don't ask something obvious.

### Steps to reproduce the problem

From manual , on MySQL and fetch

4.11.21.23. GROUP_CONCAT

create.select(
groupConcat(BOOK.ID),
groupConcat(BOOK.ID).orderBy(BOOK.ID),
groupConcat(BOOK.ID).separator("; "),
groupConcat(BOOK.ID).orderBy(BOOK.ID).separator("; "))
.from(BOOK).fetch();

### jOOQ Version

jooq "3.18.7"

### Database product and version

MySql Server version: 8.0.35-0ubuntu0.22.04.1 (Ubuntu)

### Java Version

correto 17.0.4

### OS Version

ubuntu 22.04 lts

### JDBC driver name and version (include name if unofficial driver)

[com.mysql/mysql-connector-j "8.2.0"]

**Comment by lukaseder** [comment]
Thanks for your message. You'll find all the background information here:
https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/settings-group-concat/
