### ISSUE TITLE
Oracle UDTs are sometimes inlined as [UDT] instead of IDENTIFIER(CONTENT)

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15832]
There are some call paths to the `DefaultRecordBinding::sqlInline0` method, which currently inlines non-PostgreSQL UDTs (i.e. Oracle) to `[UDT]`, which obviously is invalid SQL.

We have correct logic in `QualifiedRecordConstant::toSQLInline`, so there's room for a refactoring.

I think this call path may not have been triggered in older versions of jOOQ. It's related to UDT paths and converters, which is a new jOOQ 3.19 feature, see:

- https://github.com/jOOQ/jOOQ/issues/228

**Comment by lukaseder** [comment]
An example call stack is this:

```
java.lang.Throwable
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.lambda$3(DefaultBinding.java:3953)
	at org.jooq.impl.Cast.renderCastIf(Cast.java:421)
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.sqlInline0(DefaultBinding.java:3948)
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.sqlInline0(DefaultBinding.java:1)
	at org.jooq.impl.DefaultBinding$InternalBinding.sql(DefaultBinding.java:1062)
	at org.jooq.impl.DefaultBinding$InternalBinding.sql(DefaultBinding.java:1040)
	at org.jooq.impl.Val.accept(Val.java:203)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:740)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:360)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:270)
	at org.jooq.impl.FieldMapsForInsert.toSQL92Values(FieldMapsForInsert.java:492)
	at org.jooq.impl.FieldMapsForInsert.toSQLValues(FieldMapsForInsert.java:251)
	at org.jooq.impl.FieldMapsForInsert.accept(FieldMapsForInsert.java:187)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:740)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:360)
	at org.jooq.impl.InsertQueryImpl.toSQLInsert(InsertQueryImpl.java:902)
	at org.jooq.impl.InsertQueryImpl.accept1(InsertQueryImpl.java:744)
	at org.jooq.impl.AbstractDMLQuery.accept0(AbstractDMLQuery.java:665)
	at org.jooq.impl.InsertQueryImpl.accept(InsertQueryImpl.java:433)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:740)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:360)
	at org.jooq.impl.DefaultDSLContext.renderInlined(DefaultDSLContext.java:747)
	at org.jooq.impl.AbstractQueryPart.equals(AbstractQueryPart.java:170)
	at org.jooq.Traversers.lambda$11(Traversers.java:147)
	at org.jooq.impl.CachingTraverser.lambda$4(CachingTraverser.java:108)
	at org.jooq.impl.QOM.traverse(QOM.java:9021)
	at org.jooq.impl.InsertQueryImpl.$traverse(InsertQueryImpl.java:1436)
	at org.jooq.test.util.BaseTest.qomAssertions(BaseTest.java:797)
	at org.jooq.test.jOOQAbstractTest$QOMAssertionListener.start(jOOQAbstractTest.java:439)
	at org.jooq.impl.ExecuteListeners.start(ExecuteListeners.java:160)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:284)
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
	at org.jooq.test.all.testcases.UDTTests.insertUDTs(UDTTests.java:249)
	at org.jooq.test.all.testcases.UDTTests.withUDTs(UDTTests.java:208)
	at org.jooq.test.all.testcases.UDTTests.lambda$0(UDTTests.java:100)
	at org.jooq.test.jOOQAbstractTest.withDSLContext(jOOQAbstractTest.java:2496)
	at org.jooq.test.jOOQAbstractTest.bindAndInlineWithDSLContexts(jOOQAbstractTest.java:2490)
	at org.jooq.test.BaseTest.bindAndInlineWithDSLContexts(BaseTest.java:2213)
	at org.jooq.test.all.testcases.UDTTests.testUDTProjection(UDTTests.java:99)
	at org.jooq.test.jOOQAbstractTest.testUDTProjection(jOOQAbstractTest.java:9640)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```
