### ISSUE TITLE
Exception is passed to ExecuteListener twice in ResultQuery

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15869]
Due to a change in the implementation of `AbstractDMLQuery` (https://github.com/jOOQ/jOOQ/issues/13912), I've seen a regression where the `SQLExceptionLoggerListener` receives events twice, and thus a relevant integration test now fails, because it asserts that the log message arrives only once.

The two call stacks are:

```
java.lang.Throwable
	at org.jooq.impl.SQLExceptionLoggerListener.exception(SQLExceptionLoggerListener.java:80)
	at org.jooq.impl.ExecuteListeners.exception(ExecuteListeners.java:304)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1405)
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1365)
	at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:173)
	at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:177)
	at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:88)
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:1264)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:348)
	at org.jooq.impl.TableRecordImpl.storeInsert0(TableRecordImpl.java:198)
	at org.jooq.impl.TableRecordImpl.lambda$0(TableRecordImpl.java:163)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144)
	at org.jooq.impl.TableRecordImpl.storeInsert(TableRecordImpl.java:162)
	at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:150)
	at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:145)
	at org.jooq.test.util.BaseTest.assertThrowsIf(BaseTest.java:449)
	at org.jooq.test.util.BaseTest.assertThrows(BaseTest.java:421)
	at org.jooq.test.all.testcases.ErrorTests.lambda$4(ErrorTests.java:192)
	at org.jooq.test.util.BaseTest.assertLogs(BaseTest.java:294)
	at org.jooq.test.all.testcases.ErrorTests.testConstraintViolationLoggerListenerNullability(ErrorTests.java:188)
	at org.jooq.test.jOOQAbstractTest.testConstraintViolationLoggerListenerNullability(jOOQAbstractTest.java:11900)
```

And then:

```
java.lang.Throwable
	at org.jooq.impl.SQLExceptionLoggerListener.exception(SQLExceptionLoggerListener.java:80)
	at org.jooq.impl.ExecuteListeners.exception(ExecuteListeners.java:304)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:358)
	at org.jooq.impl.TableRecordImpl.storeInsert0(TableRecordImpl.java:198)
	at org.jooq.impl.TableRecordImpl.lambda$0(TableRecordImpl.java:163)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144)
	at org.jooq.impl.TableRecordImpl.storeInsert(TableRecordImpl.java:162)
	at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:150)
	at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:145)
	at org.jooq.test.util.BaseTest.assertThrowsIf(BaseTest.java:449)
	at org.jooq.test.util.BaseTest.assertThrows(BaseTest.java:421)
	at org.jooq.test.all.testcases.ErrorTests.lambda$4(ErrorTests.java:192)
	at org.jooq.test.util.BaseTest.assertLogs(BaseTest.java:294)
	at org.jooq.test.all.testcases.ErrorTests.testConstraintViolationLoggerListenerNullability(ErrorTests.java:188)
	at org.jooq.test.jOOQAbstractTest.testConstraintViolationLoggerListenerNullability(jOOQAbstractTest.java:11900)
```

The main reason why `CursorImpl` catches exceptions is because it can't re-throw the `SQLException`, being an `Iterator` implementation.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.22.0
- 3.21.8 (https://github.com/jOOQ/jOOQ/issues/20143)
- 3.20.19 (https://github.com/jOOQ/jOOQ/issues/20144)
- 3.19.38 (https://github.com/jOOQ/jOOQ/issues/20145)
