### ISSUE TITLE
NullPointerException in KotlinGenerator generated code when InlineDerivedTable constructor calls TableImpl.where(null)

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#16029]
As reported here:
https://groups.google.com/g/jooq-user/c/5oosTsLRrEU

Our various improvements releated to `InlineDerivedTable` and `Policy` in 3.19 produced a regression:

- https://github.com/jOOQ/jOOQ/issues/2682

We're now transforming `TableImpl` containing `where` into our internal `InlineDerivedTable` by calling `TableImpl.where(null)` to remove the predicate from the `TableImpl` instance. But `KotlinGenerator` generated code doesn't allow that:

```kotlin
override fun where(condition: Condition): MyTable = MyTable(qualifiedName, if (aliased()) this else null, condition)
```

This method should accept `Condition?` as does jOOQ's internals.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.2 (https://github.com/jOOQ/jOOQ/issues/16030)

**Comment by lukaseder** [comment]
Looks like we have to make more of these methods accepting nullable types:

![image](https://github.com/jOOQ/jOOQ/assets/734593/18d867a1-03b9-4c55-ab39-e52692714fb1)

Otherwise:

```
       at org.jooq.codegen.test.wheremethodoverrides.db.tables.WhereMethodOverrides.where(WhereMethodOverrides.kt:111)
        at org.jooq.codegen.test.wheremethodoverrides.db.tables.WhereMethodOverrides.where(WhereMethodOverrides.kt:111)
        at org.jooq.codegen.test.wheremethodoverrides.db.tables.WhereMethodOverrides.where(WhereMethodOverrides.kt:111)
        at org.jooq.codegen.test.wheremethodoverrides.db.tables.WhereMethodOverrides.where(WhereMethodOverrides.kt:111)
        at org.jooq.codegen.test.wheremethodoverrides.db.tables.WhereMethodOverrides.where(WhereMethodOverrides.kt:111)
        at org.jooq.codegen.test.wheremethodoverrides.db.tables.WhereMethodOverrides.where(WhereMethodOverrides.kt:111)
        at org.jooq.codegen.test.wheremethodoverrides.db.tables.WhereMethodOverrides.where(WhereMethodOverrides.kt:111)
        at org.jooq.codegen.test.wheremethodoverrides.db.tables.WhereMethodOverrides.where(WhereMethodOverrides.kt:111)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   WhereMethodOverridesTest.testQuerying ┬╗ StackOverflow
```

**Comment by lukaseder** [comment]
I'm wondering if we're doing this wrong elsewhere as well. All of jOOQ's internal APIs could, in principle, accept nullable types, unless explicitly declared otherwise with a `@NotNull T` annotation (which we're not doing too often yet for parameters, only for return types). So, when internals call other internals, there might be an assumption about the method parameters being nullable, which breaks in kotlin generated code. I'll investigate this a bit further, soon.
