### ISSUE TITLE
Remove unnecessary runtimeClasspath dependency of the jOOQ-codegen-gradle plugin

### ISSUE THREAD

**Issue by strindberg** [jOOQ/jOOQ#16075]
### Actual behavior

One of our projects was failing with the official Gradle plugin even though the configuration was virtually identical to other projects. This was the error:

```
* Exception is:
org.gradle.api.plugins.InvalidPluginException: An exception occurred applying plugin request [id: 'org.jooq.jooq-codegen-gradle', version: '3.19.2']
...
Caused by: org.gradle.api.artifacts.UnknownConfigurationException: Configuration with name 'runtimeClasspath' not found.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.createNotFoundException(DefaultConfigurationContainer.java:124)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.getByName(DefaultNamedDomainObjectCollection.java:334)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.getByName(DefaultConfigurationContainer.java:114)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.getByName(DefaultConfigurationContainer.java:54)
        at org.jooq.codegen.gradle.CodegenPlugin.apply(CodegenPlugin.java:73)
        at org.jooq.codegen.gradle.CodegenPlugin.apply(CodegenPlugin.java:65)
```

I believe the culprit can be that the jOOQ plugin depends on the Java plugin (which adds the configuration 'runtimeClasspath'), but doesn't make sure that the Java plugin has been configured first. Hence, in some cases, the jOOQ plugin is applied first, and since the Java plugin hasn't been applied, the configuration fails.

It seems to me this is the relevant part of the Gradle documentation:
https://docs.gradle.org/current/userguide/implementing_gradle_plugins.html#reacting_to_plugins

### Steps to reproduce the problem

I am not able to extract a working minimal example, since the error seems to not be entirely deterministic: it's probably semi-random in which order the plugins are configured.

### jOOQ Version

jOOQ 3.19.2

### Database product and version

Postgres 15

**Comment by lukaseder** [comment]
Thanks for your report. I don't think we actually need this dependency on the `runtimeClasspath`. I don't recall why I added it, perhaps it was necessary at some exploratory stage. Removing the lookup should fix the issue on your end.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.3 (https://github.com/jOOQ/jOOQ/issues/16079)
