### ISSUE TITLE
JOOQ logging + BYTEA causes jakarta/xml/bind/DatatypeConverter

### ISSUE THREAD

**Issue by nikolavojicic** [jOOQ/jOOQ#16089]
### Expected behavior

Fetching `BYTEA` column from a table should return `byte[]` in Java.

```java
public byte[] getDocumentById(int id) {
    return context
            .select(DOCUMENT.FILE)
            .from(DOCUMENT)
            .where(DOCUMENT.ID.eq(id))
            .fetchOptional(DOCUMENT.FILE)
            .orElseThrow(DocumentNotFoundEx.SUPPLIER);
}
```

JOOQ logging is enabled in `log4j2.xml`:

```xml
<Logger name="org.jooq.tools.LoggerListener" level="debug"/>
<Logger name="org.jooq" level="debug"/>
```

### Actual behavior

Exception is thrown:

```java
... jakarta/xml/bind/DatatypeConverter
java.lang.NoClassDefFoundError: jakarta/xml/bind/DatatypeConverter
	at org.jooq.impl.AbstractResult.format0(AbstractResult.java:1350) ~[jooq-3.16.4.jar:?]
	at org.jooq.impl.AbstractResult.format(AbstractResult.java:197) ~[jooq-3.16.4.jar:?]
	at org.jooq.impl.AbstractFormattable.format(AbstractFormattable.java:117) ~[jooq-3.16.4.jar:?]
	at org.jooq.tools.LoggerListener.log(LoggerListener.java:188) ~[jooq-3.16.4.jar:?]
	at org.jooq.tools.LoggerListener.resultEnd(LoggerListener.java:171) ~[jooq-3.16.4.jar:?]
	at org.jooq.impl.ExecuteListeners.resultEnd(ExecuteListeners.java:252) ~[jooq-3.16.4.jar:?]
	at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:240) ~[jooq-3.16.4.jar:?]
	at org.jooq.impl.Tools.fetchOne(Tools.java:2428) ~[jooq-3.16.4.jar:?]
	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:506) ~[jooq-3.16.4.jar:?]
	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:434) ~[jooq-3.16.4.jar:?]
	at org.jooq.impl.ResultQueryTrait.fetchOptional(ResultQueryTrait.java:633) ~[jooq-3.16.4.jar:?]
```

It works when logging is disabled.

### Steps to reproduce the problem

1. Add code that fetches BYTEA column from a table
2. Enable JOOQ logging
3. Run 1.

### jOOQ Version

JOOQ Open Source 3.16.4

### Database product and version

PostgreSQL 14.5

### Java Version

Amazon Corretto JDK 17.0.4.9.1

### OS Version

Microsoft Windows 11 Pro 10.0.22621

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.4

**Comment by lukaseder** [comment]
Thanks for your report. That looks like it wouldn't be an issue anymore starting with jOOQ 3.17:

- https://github.com/jOOQ/jOOQ/issues/13393

In any case, if you can't upgrade, just add the missing dependency.
