### ISSUE TITLE
The code generator should not uppercase all names when generating from DDL script

### ISSUE THREAD

**Issue by hupfdule** [jOOQ/jOOQ#16091]
### Expected behavior

The code generator should retain the casing from the DDL script.

### Actual behavior

The code generator generated all names in uppercase.
Since the default rendering strategy is EXPLICIT_DEFAULT_QUOTED, Jooq fails to execute any queries unless `new Settings().withRenderQuotedNames(RenderQuotedNames.EXPLICIT_DEFAULT_UNQUOTED)` is explicitly provided.

### Steps to reproduce the problem

This DDL script:

```sql
  CREATE TABLE person(                                                                                                                                                          
    id           SERIAL,                                                                                                                                                        
    name         VARCHAR,                                                                                                                                                       
    vorname      VARCHAR,                                                                                                                                        
    CONSTRAINT pk_person  PRIMARY KEY (id)                                                                                                                               
  );         
```

with this generation config (in maven):

```xml 
        <configuration>
          <generator>
            <database>
              <name>org.jooq.meta.extensions.ddl.DDLDatabase</name>
              <properties>
                <property>
                  <key>scripts</key>
                  <value>src/main/resources/sql/create.sql</value>
                </property>
                <property>
                  <key>sort</key>
                  <value>semantic</value>
                </property>
              </properties>
            </database>
          </generator>
          <target>
            <packageName>my.target.package</packageName>
          </target>
        </configuration>
```

generates a `Person` class like:

```java
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Person extends TableImpl<PersonRecord> {

[…]

    /**
     * The column <code>PERSON.ID</code>.
     */
    public final TableField<PersonRecord, Integer> ID = createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>PERSON.NAME</code>.
     */
    public final TableField<PersonRecord, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR(1000000000), this, "");

[…]
```

which fails with this SQL statement at runtime:

```java
try (final Connection conn = DriverManager.getConnection(this.connectionString, this.connectionProperties)) {
      final DSLContext create  = DSL.using(conn, SQLDialect.POSTGRES);
      final List<Person> result= create
        .select(
          PERSON.ID,
          PERSON.NAME,
          PERSON.VORNAME
        )
        .from(PERSON)
        .orderBy(PERSON.NAME, PERSON.VORNAME)
        .fetchInto(Person.class);

      return result;
    } catch (SQLException ex) {
      throw new DbException("Error requesting all persons from the database", ex);
    }
```

```
  org.jooq.exception.DataAccessException: SQL [select "PERSON"."ID", "PERSON"."NAME", "PERSON"."VORNAME" from "PERSON" order by "PERSON"."NAME", "PERSON"."VORNAME"]; ERROR:    
  relation "PERSON" does not exist                                                                                                                                              
   Position: 64                                                                                                                                                                  
   at org.jooq_3.19.2.POSTGRES.debug(Unknown Source) ~[?:?]                                                                                                                     
   at org.jooq.impl.Tools.translate(Tools.java:3539) ~[jooq-3.19.2.jar:?]                                                                                                       
   at org.jooq.impl.Tools.translate(Tools.java:3527) ~[jooq-3.19.2.jar:?]                                                                                                       
   at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:812) ~[jooq-3.19.2.jar:?]                                                                     
   at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:362) ~[jooq-3.19.2.jar:?]                                                                                          
   at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:301) ~[jooq-3.19.2.jar:?]                                                                            
   at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:322) ~[jooq-3.19.2.jar:?]                                                              
   at org.jooq.impl.SelectImpl.fetchLazyNonAutoClosing(SelectImpl.java:3256) ~[jooq-3.19.2.jar:?]                                                                               
   at org.jooq.impl.ResultQueryTrait.collect(ResultQueryTrait.java:360) ~[jooq-3.19.2.jar:?]                                                                                    
   at org.jooq.impl.ResultQueryTrait.fetchInto(ResultQueryTrait.java:1434) ~[jooq-3.19.2.jar:?]                                                                                 
   at my.project.MyClass.getPersonen(MyClass.java:72) ~[classes/:?]                                                                                                             
  Caused by: org.postgresql.util.PSQLException: ERROR: relation "PERSON" does not exist                                                                                         
    Position: 64                                                                                                                                                                
   at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2712) ~[postgresql-42.7.1.jar:42.7.1]                                                
   at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2400) ~[postgresql-42.7.1.jar:42.7.1]                                                      
   at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:367) ~[postgresql-42.7.1.jar:42.7.1]                                                              
   at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498) ~[postgresql-42.7.1.jar:42.7.1]                                                                     
   at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415) ~[postgresql-42.7.1.jar:42.7.1]                                                                             
   at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190) ~[postgresql-42.7.1.jar:42.7.1]                                                    
   at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:177) ~[postgresql-42.7.1.jar:42.7.1]                                                             
   at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219) ~[jooq-3.19.2.jar:?]                                                              
   at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4859) ~[jooq-3.19.2.jar:?]                                                                            
   at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:236) ~[jooq-3.19.2.jar:?]                                                                              
   at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:348) ~[jooq-3.19.2.jar:?]                                                                                          
   ... 41 more                               
```

### jOOQ Version

org.jooq:jooq-codegen-maven:3.19.2

### Database product and version

PostgreSQL 15.5 (Debian 15.5-0+deb12u1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit

### Java Version

openjdk version "21" 2023-09-19 LTS (OpenJDK Runtime Environment Corretto-21.0.0.35.1 (build 21+35-LTS))

### OS Version

Debian 12.4

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.1

**Comment by pareekdevanshu** [comment]
hi @lukaseder, is there any workaround for this issue? 
I cant use actual DB in my gradle script for code generation as I am using liquibase for DB migration in my project, its gradle plugin has a lot of issues with latest gradle.
