### ISSUE TITLE
Unnecessary static type registry warning when inlining custom converted enum value

### ISSUE THREAD

**Issue by mihalyr** [jOOQ/jOOQ#16090]
### Your question

After upgrading from jOOQ 3.18.6 to 3.19.2 I get the following warnings in the logs:

```
2024-01-16 19:51:32.063 [WARN] (ForkJoinPool-1-worker-1) : getDataType - Static type registry     : The deprecated static type registry was being accessed for a non-built-in data type: clob /* com.company.Job$Status */. It is strongly recommended not looking up DataType<T> references from Class<T> references by relying on the internal static type registry. See https://github.com/jOOQ/jOOQ/issues/15286 for details.
org.jooq.impl.DefaultDataType$DiscouragedStaticTypeRegistryUsage: null
	at org.jooq.impl.DefaultDataType.check(DefaultDataType.java:842) ~[jooq-3.19.2.jar:?]
	at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:835) ~[jooq-3.19.2.jar:?]
	at org.jooq.impl.DSL.getDataType0(DSL.java:35556) ~[jooq-3.19.2.jar:?]
	at org.jooq.impl.DSL.val0(DSL.java:33216) ~[jooq-3.19.2.jar:?]
	at org.jooq.impl.DSL.val(DSL.java:33211) ~[jooq-3.19.2.jar:?]
	at org.jooq.impl.DSL.inline(DSL.java:32228) ~[jooq-3.19.2.jar:?]
```

Everything works, but the logs are full of the new warning message with exception traces, which wasn't the case on 3.18.6. There were no changes to the code, the only change was the jOOQ version update.

My jOOQ config has the following forced type for automatic enum conversion:

```xml
        <forcedType>
          <userType>com.company.Job.Status</userType>
          <enumConverter>true</enumConverter>
          <includeExpression>.*\.JOB\.STATUS</includeExpression>
        </forcedType>
```

And the code has the following:

```java
        return dslContext.selectFrom(job)
                .where(job.USER_ID.eq(user.id))
                .and(job.STATUS.eq(DSL.inline(Job.Status.QUEUED)))
                .orderBy(job.CREATED_DATE)
                .limit(1)
                .fetchOne(NextJob::new);
```

Apparently, the new jOOQ version doesn't like inlined enum values. I use the inline here to make some partial indexes work better.

I checked the issue linked in the warning message, but couldn't see what am I doing wrong here and how to fix it. I didn't find related info in the release notes either. Could you please help me out what did I miss? 

### jOOQ Version

jOOQ 3.19.2 community

### Database product and version

PostgreSQL 15.3

### Java Version

openjdk version "21.0.1" 2023-10-17 LTS

### OS Version

Fedora 38

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.1

**Comment by lukaseder** [comment]
Thanks for your report. I see, the case is a bit different for `DSL.inline()`, especially if used in a way like you did. The call to `eq(Field<T>)` already applies the correct `DataType` from `job.STATUS`, similar to when you use `eq(T)`, so your usage is fine - you can ignore the warning.

Alternatively, as a workaround, you can write `DSL.inline(Job.Status.QUEUED, job.STATUS)`, giving the `DataType` context explicitly.

In any case, that warning is very annoying and misleading in this case, so I'll think about how to best turn that off again. Some options include:

- Avoiding the warning for `DSL.inline()`, which is usually fine (that's a heuristic)
- Delaying the warning until we're certain the `Param` won't be converted by the context, e.g. by `eq(Field<T>)` (that might make tracking down the wrong usage much harder)

**Comment by mihalyr** [comment]
Thank you @lukaseder for the response. I could add the type explicitly as you suggested, just need to track down the all the similar usages across projects. I was also considering turning off the logs on this logger (getDataType) in the log4j configuration to ignore the warnings if they are not relevant for my case, but wasn't sure if I would miss some important warnings in that case. 

The upgrade to 3.19 isn't urgent for us, I was just doing a general dependency bump as part of the JDK21 upgrade on the project, but 3.18.x works well, so there is no pressure on this matter and I can wait to see if there will be any updates in future releases that address the logging.

**Comment by lukaseder** [comment]
> I was also considering turning off the logs on this logger (getDataType) in the log4j configuration to ignore the warnings if they are not relevant for my case, but wasn't sure if I would miss some important warnings too.

Well, it's not like this historic feature will go away in the next 2-3 years (or even 5). jOOQ's way too backwards compatible for this. So if you keep an eye on this issue and turn on the warning again once it's fixed, you should be fine.

**Comment by lukaseder** [comment]
Probably the same issue:

- https://github.com/jOOQ/jOOQ/issues/16425

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.7 (https://github.com/jOOQ/jOOQ/issues/16430)

**Comment by lukaseder** [comment]
Hmm, no this is slightly different from https://github.com/jOOQ/jOOQ/issues/16425, and thus isn't fixed yet

**Comment by mihalyr** [comment]
Hi @lukaseder I see this is closed for some time and I just got around to upgrade jOOQ on my project from 3.18 to 3.19.8 (with a Spring Boot 3.3 update) and my logs are again full of this warning. It's the same enum again, but this time I don't have inline usage.

I've created a reproducer

*build.gradle*
```groovy
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.flywaydb:flyway-database-postgresql:10.10.0'
    }
}

plugins {
    id 'java'
    id 'application'
    id "org.jooq.jooq-codegen-gradle" version "3.19.8"
    id "org.flywaydb.flyway" version "10.10.0"
}

version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    jooqCodegen 'org.postgresql:postgresql:42.7.3'

    implementation 'org.flywaydb:flyway-core:10.10.0'
    implementation 'org.flywaydb:flyway-database-postgresql:10.10.0'
    implementation 'org.jooq:jooq:3.19.8'
    implementation 'org.postgresql:postgresql:42.7.3'

    implementation 'org.slf4j:slf4j-api:2.0.13'
    implementation 'org.slf4j:slf4j-simple:2.0.13'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

application {
    mainClass = 'com.example.Main'
}

flyway {
    url = 'jdbc:postgresql://localhost:5432/postgres'
    user = 'postgres'
    password = 'postgres'
}

jooq {
    configuration {
        jdbc {
            driver = 'org.postgresql.Driver'
            url = 'jdbc:postgresql://localhost:5432/postgres'
            user = 'postgres'
            password = 'postgres'
        }
        generator {
            database {
                name = 'org.jooq.meta.postgres.PostgresDatabase'
                inputSchema = 'public'
                includes = '.*'
                excludes = ''
                forcedTypes {
                    forcedType {
                        userType = 'com.example.JobStatus'
                        includeTypes = 'TEXT'
                        includeExpression = '.*\\.JOBS\\.STATUS'
                        converter = """org.jooq.Converter.ofNullable(
                          String.class,
                          com.example.JobStatus.class,
                          s -> com.example.JobStatus.valueOf(s),
                          t -> t.toString()
                        )
                        """
                    }
                }
            }
            target {
                packageName = 'com.example.jooq'
                directory = 'src/main/java'
            }
        }

    }
}

test {
    useJUnitPlatform()
}
```

*src/main/resources/db/migration/V1__init_schema.sql*
```sql
CREATE TABLE jobs (
    id int primary key,
	status text not null
);
```

*src/main/java/com/example/JobStatus.java*
```java
package com.example;

public enum JobStatus {
  IDLE, FAILED
}
```

*src/main/java/com/example/Main.java*
```java
package com.example;

import com.example.jooq.Tables;
import org.jooq.impl.DSL;

public class Main {
  public static void main(String[] args) {
    var db = DSL.using("jdbc:postgresql://localhost:5432/postgres", "postgres", "postgres");
    db.insertInto(Tables.JOBS)
        .set(Tables.JOBS.ID, 1)
        .set(Tables.JOBS.STATUS, JobStatus.IDLE)
        .onConflict(Tables.JOBS.ID)
        .doUpdate()
        .set(Tables.JOBS.STATUS,
            DSL.when(Tables.JOBS.STATUS.eq(JobStatus.FAILED), JobStatus.IDLE)
                .otherwise(Tables.JOBS.STATUS))
        .execute();
  }
}
```

Running this simple jOOQ query results in long exception traces (on production this is significant)

```
[main] WARN org.jooq.impl.DefaultDataType.getDataType - Static type registry     : The deprecated static type registry was being accessed for a non-built-in data type: clob /* com.example.JobStatus */.

It is strongly recommended not looking up DataType<T> references from Class<T> references by
relying on the internal static type registry. For example, avoid calling DSL.val(Object) or
DSL.val(Object, Class), and call DSL.val(Object, DataType), providing an explicit DataType
reference to jOOQ if your DataType uses a Converter or a Binding. If you think jOOQ should
be able to infer your user type in your particular query, please report a bug here:
https://jooq.org/bug

See https://github.com/jOOQ/jOOQ/issues/15286 for more details.

org.jooq.impl.DefaultDataType$DiscouragedStaticTypeRegistryUsage
	at org.jooq.impl.DefaultDataType.check(DefaultDataType.java:844)
	at org.jooq.impl.Val.accept(Val.java:192)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:731)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:381)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:291)
	at org.jooq.impl.CaseSearched.acceptNative(CaseSearched.java:254)
	at org.jooq.impl.CaseSearched.accept(CaseSearched.java:185)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:731)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:381)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:291)
	at org.jooq.impl.FieldMapForUpdate.acceptAssignmentClause(FieldMapForUpdate.java:347)
	at org.jooq.impl.FieldMapForUpdate.accept(FieldMapForUpdate.java:199)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:731)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:381)
	at org.jooq.impl.InsertQueryImpl.accept1(InsertQueryImpl.java:517)
	at org.jooq.impl.AbstractDMLQuery.accept0(AbstractDMLQuery.java:671)
	at org.jooq.impl.InsertQueryImpl.accept(InsertQueryImpl.java:433)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:731)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:381)
	at org.jooq.impl.DefaultRenderContext$Rendered.rendered(DefaultRenderContext.java:1078)
	at org.jooq.impl.AbstractQuery.getSQL0(AbstractQuery.java:498)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:303)
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
	at com.example.Main.main(Main.java:17)
[main] INFO org.jooq.impl.DefaultExecuteContext.logVersionSupport - Version                  : Database version is supported by dialect POSTGRES: 16.2
[main] WARN org.jooq.impl.DefaultDataType.getDataType - Static type registry     : The deprecated static type registry was being accessed for a non-built-in data type: clob /* com.example.JobStatus */.

It is strongly recommended not looking up DataType<T> references from Class<T> references by
relying on the internal static type registry. For example, avoid calling DSL.val(Object) or
DSL.val(Object, Class), and call DSL.val(Object, DataType), providing an explicit DataType
reference to jOOQ if your DataType uses a Converter or a Binding. If you think jOOQ should
be able to infer your user type in your particular query, please report a bug here:
https://jooq.org/bug

See https://github.com/jOOQ/jOOQ/issues/15286 for more details.

org.jooq.impl.DefaultDataType$DiscouragedStaticTypeRegistryUsage
	at org.jooq.impl.DefaultDataType.check(DefaultDataType.java:844)
	at org.jooq.impl.Val.accept(Val.java:192)
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:258)
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:68)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:381)
	at org.jooq.impl.QueryPartCollectionView.acceptElement(QueryPartCollectionView.java:256)
	at org.jooq.impl.QueryPartCollectionView.accept(QueryPartCollectionView.java:226)
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:258)
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:68)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:381)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:344)
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
	at com.example.Main.main(Main.java:17)
```


Am I missing something? Or this issue was closed by mistake perhaps? 

Thank you in advance.

**Comment by mihalyr** [comment]
I've moved this to a new issue https://github.com/jOOQ/jOOQ/issues/16750
