### ISSUE TITLE
Transaction rollback does not seem to work when using r2dbc and spring

### ISSUE THREAD

**Issue by sriram-wolt** [jOOQ/jOOQ#16109]
### Expected behavior

When an exception is thrown within a transaction, jOOQ should rollback the whole transaction

### Actual behavior

When an exception is thrown within a transaction, jOOQ does not rollback the whole transaction. The inserts before the exception are committed to the database.

### Steps to reproduce the problem

DemoRepository

```kotlin
suspend fun insert(id: String) {
    if (id == "b") {
        throw RuntimeException("error while inserting")
    }

    db.insertInto(DEMO_TABLE)
        .set(DEMO_TABLE.ID, id)
        .awaitSingle()
}
```

DemoService

```kotlin
suspend fun addRecords(): Unit = transactionalOperator.executeAndAwait {
    log.info("Inserting records")
    repo.insert("a")
    repo.insert("b")  // throws error
}
```

and then

```kotlin
repo.getAll() // returns ["a"] instead of []
```

Full code: https://github.com/linktosriram/r2dbc-jooq-rollback

Even-though the inserts are done within a transaction, it does not seem to be rolled back when an exception is thrown

Logs:
```
Executing query: BEGIN READ WRITE
Executing query: insert into demo_table (id) values ($1)
Executing query: ROLLBACK
Executing query: select demo_table.id from demo_table
```

When swapping jOOQ `DSLContext` to `DatabaseClient` the rollback works. Looks like a bug in jOOQ 🤔

```kotlin
suspend fun insert(id: String) {
    if (id == "b") {
        throw RuntimeException("error while inserting")
    }

    dbClient.sql("insert into demo_table (id) values ('$id')")
        .fetch()
        .awaitSingle()
}
```

Checking debug logs, found a difference after the insert statement was executed:

Using `DatabaseClient`

```
[demo-app] [actor-tcp-nio-1] i.r.p.client.ReactorNettyClient          : [cid: 0x1][pid: 60][id: 0xc218fdac, L:/127.0.0.1:52359 - R:/127.0.0.1:5559] Response: ReadyForQuery{transactionStatus=TRANSACTION}
```

Using `DSLContext`

```
[demo-app] [actor-tcp-nio-2] i.r.p.client.ReactorNettyClient          : [cid: 0x2][pid: 61][id: 0x4a0f6174, L:/127.0.0.1:52325 - R:/127.0.0.1:5559] Response: ReadyForQuery{transactionStatus=IDLE}
```

The `transactionStatus` is different when using `jOOQ`. Not sure if that's the reason

### jOOQ Version

3.18.7

### Database product and version

PostgreSQL 15.5

### Java Version

OpenJDK Runtime Environment Corretto-21.0.1.12.1

### OS Version

macOS Ventura 13.0

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:r2dbc-postgresql:1.0.3.RELEASE

**Comment by lukaseder** [comment]
Thanks a lot for your report. I'll have a look at your reproducer shortly.

**Comment by lukaseder** [comment]
Well, I guess you're expecting Spring to communicate its transaction to jOOQ, but this isn't happening. I don't see how this could be jOOQ's fault? Have you reported this issue / question to Spring as well? They seem to be putting objects into the coroutine context, but jOOQ isn't aware of such a context (nor do I think jOOQ should be).

**Comment by sriram-wolt** [comment]
I was not sure if this was a jOOQ or spring thing. Now created https://github.com/spring-projects/spring-data-r2dbc/issues/849

**Comment by lukaseder** [comment]
Well, I don't think it's a Spring Data R2DBC problem, why would it be? Why would Spring Data R2DBC know about jOOQ?

My point was that you're injecting a jOOQ `DSLContext` into your service, and that `DSLContext` is configured somewhere (not by jOOQ), and probably that "somewhere" (probably Spring Boot) might be able to give jOOQ an R2DBC `ConnectionFactory` that can communicate with its transactions?

**Comment by sriram-wolt** [comment]
Is this the correct way to configure jOOQ with a `ConnectionFactory` ?

```kotlin
    @Bean
    fun connectionFactory(properties: R2dbcProperties): ConnectionFactory =
        ConnectionFactoryBuilder.withUrl(properties.url)
            .username("postgres")
            .password("postgres")
            .build()

    @Bean
    fun dslContext(properties: JooqProperties, connectionFactory: ConnectionFactory): DSLContext =
        DSL.using(
            connectionFactory,
            properties.sqlDialect,
            Settings()
                .withBindOffsetTimeType(true)
                .withBindOffsetDateTimeType(true)
                .withRenderQuotedNames(RenderQuotedNames.EXPLICIT_DEFAULT_UNQUOTED)
        )
```

**Comment by lukaseder** [comment]
> Is this the correct way to configure jOOQ with a `ConnectionFactory` ?

Sure, why not?

> I tried wrapping the `ConnectionFactory` in a `TransactionAwareConnectionFactoryProxy` but that didn't work either 😞

I don't have any experience with `TransactionAwareConnectionFactoryProxy`, sorry.

**Comment by lukaseder** [comment]
What are you gaining from this reactive programming style? Is it really necessary? I personally doubt 98% of applications who use this approach really need it, but perhaps I'm overlooking something?

**Comment by sriram-wolt** [comment]
With r2dbc being reactive, it seemed very natural to do something like
```kotlin
suspend fun insert(id: String) {
    db.insertInto(DEMO_TABLE)
        .set(DEMO_TABLE.ID, id)
        .awaitSingle()
}
```

Is there a better / recommended way to use jOOQ?

**Comment by lukaseder** [comment]
I mean, yes jOOQ supports this, and it also has an R2DBC backed transaction API which works with kotlin `suspend`:
https://www.jooq.org/doc/latest/manual/sql-execution/transaction-management/

My point is more that I personally don't believe reactive is really needed in most applications. The sequential, blocking world is so much simpler, robust, and proven...

**Comment by lukaseder** [comment]
> My point is more that I personally don't believe reactive is really needed in most applications. The sequential, blocking world is so much simpler, robust, and proven...

Why is your application reactive?

**Comment by mp911de** [comment]
I second Lukas' opinion, especially when looking at inserts that do not benefit from a coroutine/reactive arrangement. Running inserts via JDBC on Virtual Threads is a much easier arrangement. I understand that you might want to hold on to a single connection when combining various tasks in the same flow. Also, Kotlin Coroutines suggests such an approach while the backend is highly involved into reactive adapters resulting in a massive overhead, both computational complexity and debug-wise.

**Comment by lukaseder** [comment]
And this from you, @mp911de 😅. Have you played with JDBC on Virtual Threads already? I'm very curious about this case, and I obviously hope it will be successful.

**Comment by mp911de** [comment]
It seems that the issue is caused by jOOQ's `AbstractSubscription` utils that do not participate in context propagation.

In Spring we use Reactor's [subscriber context](https://projectreactor.io/docs/core/release/api/reactor/core/CoreSubscriber.html#currentContext--) to associate contextual resources that are carried out-of-band. On the imperative code side, typically `ThreadLocal` is used for such purpose.

Therefore, connection requests to `TransactionAwareConnectionFactoryProxy` cannot provide the transactional context that was set up by `@Transactional` or `TransactionalOperator` and so each operation runs on its own connection.

**Comment by lukaseder** [comment]
Ah yes, I remember now, thanks for looking this up, @mp911de.

That context isn't part of the RS standard though, so jOOQ can't really use it directly. I wonder if jOOQ could offer some SPI to inject contexts to a `Configuration`. Spring Boot might be able to auto configure these things then on behalf of users.

This could also be useful to inject any kotlin coroutine context that is independent of Reactor. Despite there being a "standard," everyone seems to be inventing their own wheels in this area, and feature requests to the spec have so far not been implemented, e.g.:

- https://github.com/reactive-streams/reactive-streams-jvm/issues/542

But I'm still not 100% convinced that jOOQ should know *anything* about all of this. Every time I try to wrap my head around why a simple `ConnectionFactory.create()` isn't enough for jOOQ to do, I get headaches. Spring creates a transaction context, and that `ConnectionFactory` instance could know about it, because Spring could control it as well. So, why doesn't it know about it?

**Comment by mp911de** [comment]
Contexts are on a per `Publisher.subscribe(…)` basis, so nothing really we could place somewhere upfront. Reactor has utils that attempt to create a `CoreSubscriber` from a Reactive Streams `Subscriber` while Mutiny does a similar thing, just slightly different.

**Comment by lukaseder** [comment]
But somehow, `dbClient.sql(...).fetch(...)` can do this, despite `dbClient` being injected at the wrong level (into the singleton whatever-bean, rather than into the transaction)

**Comment by lukaseder** [comment]
Anyway, this is a frequent problem among jOOQ users, and people keep requesting similar things to this:

- https://github.com/jOOQ/jOOQ/issues/15474

So I'll spend a few hours investigating how this context could be propagated to jOOQ...

**Comment by git-josip** [comment]
@sriram-wolt I have found a way to work as descirbed in other thread. 

Instead of using `dslCOntext` this should be used: 

```kotlin
import io.r2dbc.spi.ConnectionFactory
import kotlinx.coroutines.reactive.awaitSingle
import org.jooq.generated.tables.records.FooTableRecord
import org.jooq.generated.tables.references.FOO_TABLE
import org.jooq.impl.DSL
import org.springframework.r2dbc.connection.ConnectionFactoryUtils
import org.springframework.stereotype.Repository
import reactor.core.publisher.Mono

@Repository
class Repository(private val cfi: ConnectionFactory) {
    suspend fun save(value: String): FooTableRecord {
        return ConnectionFactoryUtils.getConnection(cfi)
            .flatMap {
                val ctxt = DSL.using(it)
                Mono.from(ctxt.insertInto(FOO_TABLE).values(value).returning())
            }.map { it.into(FOO_TABLE) }
            .awaitSingle()!!
    }
}
```


This is described in this comment: https://github.com/jOOQ/jOOQ/issues/12218#issuecomment-1213929029

**Comment by lukaseder** [comment]
jOOQ 3.20 will ship with a new SPI to allow for propagating third party contexts through jOOQ. This should help resolve the issue here:

- https://github.com/jOOQ/jOOQ/issues/17920

Once it is published, I suspect Spring Boot can auto configure jOOQ using this SPI, so things will work out of the box for Spring Boot users.

**Comment by lukaseder** [comment]
While https://github.com/jOOQ/jOOQ/issues/17920 is certainly helpful getting this to work, there's a second challenge in play here, when kotlin coroutines are being used. The usage of `executeAndAwait` leads to the kotlin coroutine/reactive bridge being invoked, which produces again a different type of `Subscriber`, which doesn't directly expose its context:
https://github.com/Kotlin/kotlinx.coroutines/blob/1.10.1/reactive/kotlinx-coroutines-reactive/src/Await.kt#L186

I guess it's possible to hack around using reflection in order to extract the reactor context and thus the Spring transaction object:

![Image](https://github.com/user-attachments/assets/09b24e03-da76-4171-8cfe-7bc32904aeab)

But boy, this is all so brittle. Time and again, I keep wondering why all of these abstractions are being used, when vanilla jOOQ/JDBC would be so simple... ;-)

**Comment by lukaseder** [comment]
So, I can get reactor context propagation to work when using this API:

```kotlin
Mono.from(
        db.insertInto(DEMO_TABLE)
            .set(DEMO_TABLE.ID, idempotencyId))
            .awaitSingle()
```

Over this one:

```kotlin
        db.insertInto(DEMO_TABLE)
            .set(DEMO_TABLE.ID, idempotencyId)
            .awaitSingle()
```

This is really very subtle, and users are going to run into this issue time and again, but at least, it's a step forward. It appears that we should offer our own extension methods that will help avoid these pitfalls.

The reproducer from the original issue now rolls back the transaction and prints:

```
2025-01-23T15:53:21.440+01:00 DEBUG 22800 --- [demo-app] [actor-tcp-nio-2] io.r2dbc.postgresql.QUERY                : Executing query: delete from "demo_table"
2025-01-23T15:53:21.463+01:00  INFO 22800 --- [demo-app] [           main] com.example.demo.service.DemoService     : Inserting b
2025-01-23T15:53:21.516+01:00 DEBUG 22800 --- [demo-app] [           main] io.r2dbc.postgresql.QUERY                : Executing query: insert into "demo_table" ("id") values ($1)
2025-01-23T15:53:21.523+01:00  INFO 22800 --- [demo-app] [           main] com.example.demo.service.DemoService     : Inserting b
2025-01-23T15:53:21.529+01:00 ERROR 22800 --- [demo-app] [           main] o.s.t.r.TransactionalOperatorImpl        : Application exception overridden by rollback exception

java.lang.RuntimeException: error while inserting
	at com.example.demo.repository.DemoRepository.insert$suspendImpl(DemoRepository.kt:24) ~[main/:na]
	at com.example.demo.repository.DemoRepository.insert(DemoRepository.kt) ~[main/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97) ~[kotlin-reflect-1.9.21.jar:1.9.21-release-633]
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113) ~[kotlin-reflect-1.9.21.jar:1.9.21-release-633]
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:207) ~[kotlin-reflect-1.9.21.jar:1.9.21-release-633]
	at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74) ~[kotlin-reflect-1.9.21.jar:1.9.21-release-633]
	at org.springframework.core.CoroutinesUtils.lambda$invokeSuspendingFunction$2(CoroutinesUtils.java:124) ~[spring-core-6.1.2.jar:6.1.2]
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$4.invokeSuspend(IntrinsicsJvm.kt:270) ~[kotlin-stdlib-1.9.21.jar:1.9.21-release-633]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.9.21.jar:1.9.21-release-633]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108) ~[kotlinx-coroutines-core-jvm-1.7.3.jar:na]
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280) ~[kotlinx-coroutines-core-jvm-1.7.3.jar:na]
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85) ~[kotlinx-coroutines-core-jvm-1.7.3.jar:na]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) ~[kotlinx-coroutines-core-jvm-1.7.3.jar:na]
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.7.3.jar:na]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) ~[kotlinx-coroutines-core-jvm-1.7.3.jar:na]
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.7.3.jar:na]
	at com.example.demo.DemoApplication.runner$lambda$0(DemoApplication.kt:16) ~[main/:na]
	at org.springframework.boot.SpringApplication.lambda$callRunner$5(SpringApplication.java:798) ~[spring-boot-3.2.1.jar:3.2.1]
	at org.springframework.util.function.ThrowingConsumer$1.acceptWithException(ThrowingConsumer.java:83) ~[spring-core-6.1.2.jar:6.1.2]
	at org.springframework.util.function.ThrowingConsumer.accept(ThrowingConsumer.java:60) ~[spring-core-6.1.2.jar:6.1.2]
	at org.springframework.util.function.ThrowingConsumer$1.accept(ThrowingConsumer.java:88) ~[spring-core-6.1.2.jar:6.1.2]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:806) ~[spring-boot-3.2.1.jar:3.2.1]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:797) ~[spring-boot-3.2.1.jar:3.2.1]
	at org.springframework.boot.SpringApplication.lambda$callRunners$3(SpringApplication.java:782) ~[spring-boot-3.2.1.jar:3.2.1]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[na:na]
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:782) ~[spring-boot-3.2.1.jar:3.2.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:341) ~[spring-boot-3.2.1.jar:3.2.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1358) ~[spring-boot-3.2.1.jar:3.2.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1347) ~[spring-boot-3.2.1.jar:3.2.1]
	at com.example.demo.DemoApplicationKt.main(DemoApplication.kt:31) ~[main/:na]

Error while calling addRecords: Active Connection is required
2025-01-23T15:53:21.769+01:00 DEBUG 22800 --- [demo-app] [actor-tcp-nio-3] io.r2dbc.postgresql.QUERY                : Executing query: SHOW TRANSACTION ISOLATION LEVEL
2025-01-23T15:53:21.773+01:00 DEBUG 22800 --- [demo-app] [actor-tcp-nio-3] io.r2dbc.postgresql.QUERY                : Executing query: SELECT oid, typname, typarray FROM pg_catalog.pg_type WHERE typname IN ('hstore','geometry','vector')
2025-01-23T15:53:21.786+01:00 DEBUG 22800 --- [demo-app] [actor-tcp-nio-3] io.r2dbc.postgresql.QUERY                : Executing query: select "demo_table"."id" from "demo_table"
All IDs in DB : []
```

**Comment by lukaseder** [comment]
In other words: The spring problem can be solved now. The kotlinx.coroutines problem (which is an additional one on top of the spring problem) is still outstanding.

**Comment by T45K** [comment]
thank you for tackling this issue! it is great help for me 😄 

but i wonder [your comment](https://github.com/jOOQ/jOOQ/issues/16109#issuecomment-2610030715) is correct
since the stacktrace says `Active Connection is required`, looks inserting itself failed

i tried simple reproducer
https://github.com/T45K/jooq_rollback_trial/blob/9c8aae58d1ad7c5042900ce700011f6293b7af9a/src/main/kotlin/io/github/t45k/jooq_rollback/JooqRollbackApplication.kt#L74

i expect that the insertion is completed but actually `Active Connection is required` is thrown

<img width="1830" alt="Image" src="https://github.com/user-attachments/assets/79ac1eb5-d4da-4dfe-81c6-f7590b87c3e9" />

**Comment by lukaseder** [comment]
> but i wonder [your comment](https://github.com/jOOQ/jOOQ/issues/16109#issuecomment-2610030715) is incorrect
> since the stacktrace says `Active Connection is required`, looks inserting itself failed

I said that the issue here *can be solved*, not that it is solved already. I still don't know how to solve the Spring / Reactor integration *specifically*. In theory, it would be possible for Spring folks to implement glue code now that jOOQ allows for reactor contexts to be propagated, but I'm not sure yet if that is the right approach here.

The status quo is that while Spring propagates its transactions via reactor, it does so using internal API and I currently don't see how jOOQ could extract any transaction (or `ConnectionProvider`) from Spring without any strong assumptions about such internals.
