### ISSUE TITLE
jOOQ-codegen-gradle fails with UnknownDomainObjectException when java plugin isn't applied first

### ISSUE THREAD

**Issue by strindberg** [jOOQ/jOOQ#16113]
### Actual behavior

This is (probably) a continuation of #16075: the jOOQ Gradle plugin depends on the Java plugin having been applied, but does not make sure that this is the case. See the documentation I linked to in the previous issue.

With jOOQ 3.19.3, this is the exception when running a gradle build where the Java (or, in our case, Kotlin) plugin is not first in the list of plugins:

```
Caused by: org.gradle.api.UnknownDomainObjectException: Extension of type 'SourceSetContainer' does not exist. Currently registered extension types: [ExtraPropertiesExtension, LibrariesForLibs, VersionCatalogsExtension, FlywayExtension, CodegenPluginExtension]
        at org.gradle.internal.extensibility.ExtensionsStorage.getHolderByType(ExtensionsStorage.java:88)
        at org.gradle.internal.extensibility.ExtensionsStorage.getByType(ExtensionsStorage.java:74)
        at org.gradle.internal.extensibility.DefaultConvention.getByType(DefaultConvention.java:175)
        at org.gradle.internal.extensibility.DefaultConvention.getByType(DefaultConvention.java:170)
        at org.jooq.codegen.gradle.CodegenPlugin.apply(CodegenPlugin.java:78)
        at org.jooq.codegen.gradle.CodegenPlugin.apply(CodegenPlugin.java:65)
```

Putting the Kotlin plugin before the jOOQ plugin in the list of plugins in the build file solves the issue, but this is of course very fragile.

### Steps to reproduce the problem

See above

### jOOQ Version

3.19.3

### Database product and version

Postgresql 15

**Comment by lukaseder** [comment]
Thanks for your report. Interesting, there's no reason indeed why we should eagerly fetch the `SourceSetContainer` within the `Plugin::apply` implementation - that probably causes it.

Also, there might be a case where a code generation configuration is completely separate from the remaining build, which is unaware of code generation (for whatever reasons). In that case, even delaying the lookup will eventually produce the exception if the `SourceSetContainer` is never defined.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.3 (https://github.com/jOOQ/jOOQ/issues/16115)

Thanks again for your report!
