### ISSUE TITLE
Mismatch Bind Values for Grouping Function

### ISSUE THREAD

**Issue by saharathkleips** [jOOQ/jOOQ#16184]
### Steps to reproduce the problem

Imagine a (mocked) aggregation query that counts the number of `flight.id`s grouped by three grouping sets: no grouping, group by `flight.cancelled`, and  `flight.cancelled` and `flight.dayofweek` range. Written in Kotlin, the query looks like the following:

```kotlin
val caseDayOfWeek = `when`(FLIGHT.DAYOFWEEK.between(0, 1), "0-1")
    .`when`(FLIGHT.DAYOFWEEK.between(2, 5), "2-5")

dslContext
    .select(
        FLIGHT.CANCELLED,
        caseDayOfWeek.`as`("day of week"),
        count(FLIGHT.ID),
        grouping(FLIGHT.CANCELLED).`as`("cancelled group"),
        grouping(caseDayOfWeek).`as`("day of week group"),
    )
    .from(FLIGHT)
    .groupBy(
        rollup(
            inline(1),
            inline(2),
        )
    )
    .orderBy(
        inline(1),
        inline(2),
    )
    .fetch()
```

When printing the query jooq will output the following sql string:

```pgsql
select
    "flights"."flight"."cancelled",
    case
        when "flights"."flight"."dayofweek" between 0 and 1 then '0-1'
        when "flights"."flight"."dayofweek" between 2 and 5 then '2-5'
        end as "day of week",
    count("flights"."flight"."id"),
    grouping("flights"."flight"."cancelled") as "cancelled group",
    grouping(case
                 when "flights"."flight"."dayofweek" between 0 and 1 then '0-1'
                 when "flights"."flight"."dayofweek" between 2 and 5 then '2-5'
        end) as "day of week group"
from "flights"."flight"
group by rollup(1, 2)
order by 1, 2;
```

This is a valid sql query and works as expected when executed manually outside Jooq (in an IntelliJ console). However fails with the following error:

```
Caused by: org.springframework.jdbc.BadSqlGrammarException: jOOQ; bad SQL grammar [select "flights"."flight"."cancelled", case when "flights"."flight"."dayofweek" between ? and ? then ? when "flights"."flight"."dayofweek" between ? and ? then ? end as "day of week", count("flights"."flight"."id"), grouping("flights"."flight"."cancelled") as "cancelled group", grouping(case when "flights"."flight"."dayofweek" between ? and ? then ? when "flights"."flight"."dayofweek" between ? and ? then ? end) as "day of week group" from "flights"."flight" group by rollup (1, 2) order by 1, 2]; nested exception is org.postgresql.util.PSQLException: ERROR: arguments to GROUPING must be grouping expressions of the associated query level
  Position: 295
	at org.jooq_3.18.4.POSTGRES.debug(Unknown Source)
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:101)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:82)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:82)
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.translate(JooqExceptionTranslator.java:94)
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.handle(JooqExceptionTranslator.java:81)
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.exception(JooqExceptionTranslator.java:55)
	at org.jooq.impl.ExecuteListeners.exception(ExecuteListeners.java:304)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:372)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:290)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2838)
	...
Caused by: org.postgresql.util.PSQLException: ERROR: arguments to GROUPING must be grouping expressions of the associated query level
  Position: 295
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:167)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:156)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4761)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:236)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:357)
	... 30 common frames omitted
```

It seems that when PostgreSQL receives the query it interprets `caseDayOfWeek` as two _different_ expressions and fails the query. Within the PostgreSQL logs we see the following exception as well:

```
2024-01-26 00:08:19.589 UTC [666] ERROR:  arguments to GROUPING must be grouping expressions of the associated query level at character 295
2024-01-26 00:08:19.589 UTC [666] STATEMENT:  select "flights"."flight"."cancelled", case when "flights"."flight"."dayofweek" between $1 and $2 then $3 when "flights"."flight"."dayofweek" between $4 and $5 then $6 end as "day of week", count("flights"."flight"."id"), grouping("flights"."flight"."cancelled") as "cancelled group", grouping(case when "flights"."flight"."dayofweek" between $7 and $8 then $9 when "flights"."flight"."dayofweek" between $10 and $11 then $12 end) as "day of week group" from "flights"."flight" group by rollup (1, 2) order by 1, 2
```

The formatted SQL statement PostgreSQL gets is:
```pgsql
select "flights"."flight"."cancelled",
       case
           when "flights"."flight"."dayofweek" between $1 and $2 then $3
           when "flights"."flight"."dayofweek" between $4 and $5 then $6 end              as "day of week",
       count("flights"."flight"."id"),
       grouping("flights"."flight"."cancelled")                                           as "cancelled group",
       grouping(case
                    when "flights"."flight"."dayofweek" between $7 and $8 then $9
                    when "flights"."flight"."dayofweek" between $10 and $11 then $12 end) as "day of week group"
from "flights"."flight"
group by rollup (1, 2)
order by 1, 2
```

---

I believe the issue lies with what appears to be different bind value variables in the same case statement (the `$`#s?) that _should_ be the same (since they ultimately refer to the same value).

I'm not quite sure if this is _exactly_ a bug, but the printed SQL generated by the Jooq DSL _is_ the query we ultimately want to be able to generate and does work if it is interpreted literally (via the console).

Any workaround would be greatly appreciated!

### jOOQ Version

jOOQ Enterprise Edition 3.18.4

### Database product and version

PostgreSQL 16.1

### Java Version

Java 11

### OS Version

macOS Ventura 13.2.1

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.2.27

**Comment by lukaseder** [comment]
Thanks for your message. The error is here:

```kotlin
val caseDayOfWeek = `when`(FLIGHT.DAYOFWEEK.between(0, 1), "0-1")
    .`when`(FLIGHT.DAYOFWEEK.between(2, 5), "2-5")
```

jOOQ always defaults to rendering bind values for values like `0`, `1`, `"0-1"`, etc., see:
https://www.jooq.org/doc/latest/manual/sql-building/bind-values/

This is a good default, but sometimes causes problems with queries like yours where the RDBMS can't be sure that the bind value is really the same between two repeated expressions. The easiest way to work around this is to just use `DSL.inline()` instead:


```kotlin
val caseDayOfWeek = `when`(FLIGHT.DAYOFWEEK.between(inline(0), inline(1)), inline("0-1"))
    .`when`(FLIGHT.DAYOFWEEK.between(inline(2), inline(5)), inline("2-5"))
```

Other options include:

- Set the statement type to `STATIC_STATEMENT` to avoid prepared statements and bind values entirely (at least for this query): https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/settings-statement-type/
- Use a derived table to avoid repeating the group value in your query: https://www.jooq.org/doc/latest/manual/sql-building/table-expressions/derived-tables/
- Use a CTE or view (equivalent to derived table)

I hope this helps

**Comment by saharathkleips** [comment]
@lukaseder Our service generates these queries dynamically and as a result the values you point out come from end-users, so would inlining still be appropriate in this situation (ex. sql injection)? We were considering inlining only numeric and date values (we parse date strings into date objects first) as a workaround but I was not sure if this was appropriate as well.

**Comment by lukaseder** [comment]
`DSL.inline()` values are always escaped, see also the "SQL injection" remark on the manual page:
https://www.jooq.org/doc/latest/manual/sql-building/bind-values/inlined-parameters/

But you can still use the derived table approach to avoid the issue and continue using bind values

**Comment by saharathkleips** [comment]
This blog post was really informative: https://blog.jooq.org/when-to-use-bind-values-and-when-to-use-inline-values-in-sql/
Thanks for sharing it!
