### ISSUE TITLE
Parser not being able to parse: SELECT * FROM <Pipelined Table function>

### ISSUE THREAD

**Issue by jbpoquiz** [jOOQ/jOOQ#16200]
### Expected behavior

Jooq parser should be able to parse successfully a plain SQL query with a SELECT FROM a Pipelined Table Function.

### Actual behavior

org.jooq.impl.ParserException: Token ')' expected: [1:56] ...ALL_ACCT AS       (SELECT * FROM GetClientRelation[*]('00002001','00000015','00000094','1','20240202', 0, 0) a)     SELECT * FROM (    ...
	at org.jooq.impl.ParserContext.expected(ParserImpl.java:12225)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:11603)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:11598)
	at org.jooq.impl.ParserImpl.parseWith(ParserImpl.java:1081)
	at org.jooq.impl.ParserImpl.parseWith(ParserImpl.java:1054)
	at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:1018)
	at org.jooq.impl.ParserImpl.parseSelect(ParserImpl.java:736)
	at org.jooq.impl.ParserImpl.parseSelect(ParserImpl.java:730)
	
Encountered a ParserException when trying to run this line of code:
Table<?> table1 = DSLContext.parser().parseSelect(plainSQL).asTable();

It's expecting a ')' token and seems like it cannot recognize custom pipelined table functions.

### Steps to reproduce the problem

Using Java 11
1. Declare a plain SQL string:
String plainSQL = "WITH ALL_ACCT AS
	(SELECT * FROM GetClientRelation('00002001','00000015','00000094','1','20240202', 0, 0) a)
SELECT * FROM ALL_ACCT ACCT JOIN  INT_TRANSACTIONS TRN ON TRN.ACCT_NUMBER = ACCT.ACCT_NUMBER";

2. Try parsing the plain SQL string (which contains a pipelined table function, GetClientRelation) using the org.jooq.DSLContext.parser() and then call parseSelect method.

DSLContext dsl;
Table<?> table1 = dsl.parser().parseSelect(plainSQL).asTable();

It would encounter org.jooq.impl.ParserException at this line.

### jOOQ Version

org.jooq.pro:jooq:3.14.9

### Database product and version

Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production 

### Java Version

OpenJDK Runtime Environment Zulu11.66+15-CA (build 11.0.20+8-LTS)

### OS Version

Microsoft Windows [Version 10.0.14393]

### JDBC driver name and version (include name if unofficial driver)

com.oracle:ojdbc8:19.3.0.0

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. I've added the feature request to our list of known issues and missing features:

- https://github.com/jOOQ/jOOQ/issues/14682

You can work around this by implementing a `ParseListener`:

- https://www.jooq.org/doc/latest/manual/sql-building/sql-parser/sql-parser-listener/
