### ISSUE TITLE
Add support for ALTER TABLE ADD COLUMN IF NOT EXISTS in SQLite

### ISSUE THREAD

**Issue by KweezyCode** [jOOQ/jOOQ#16219]
### Expected behavior

working code

### Actual behavior

```
org.jooq.exception.DataAccessException: SQL [alter table authme add if not exists username varchar(255)]; [SQLITE_ERROR] SQL error or missing database (near "exists": syntax error)
        at org.jooq_3.19.3.SQLITE.debug(Unknown Source)
        at org.jooq.impl.Tools.translate(Tools.java:3539)
        at org.jooq.impl.Tools.translate(Tools.java:3527)
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:812)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:362)
        at com.kweezy.IceShield.SQLite.alterTable(SQLite.java:49)
        at com.kweezy.IceShield.SQLite.initColumns(SQLite.java:66)
        at com.kweezy.IceShield.IceShield.onEnable(IceShield.java:40)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:382)
        at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugin(CraftServer.java:285)
        at org.bukkit.craftbukkit.v1_5_R3.CraftServer.enablePlugins(CraftServer.java:267)
        at net.minecraft.server.v1_5_R3.MinecraftServer.j(MinecraftServer.java:310)
        at net.minecraft.server.v1_5_R3.MinecraftServer.e(MinecraftServer.java:289)
        at net.minecraft.server.v1_5_R3.MinecraftServer.a(MinecraftServer.java:249)
        at net.minecraft.server.v1_5_R3.DedicatedServer.init(DedicatedServer.java:160)
        at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:388)
        at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(Unknown Source)
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "exists": syntax error)
        at org.sqlite.core.DB.newSQLException(DB.java:1179)
        at org.sqlite.core.DB.newSQLException(DB.java:1190)
        at org.sqlite.core.DB.throwex(DB.java:1150)
        at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
        at org.sqlite.core.NativeDB.prepare(NativeDB.java:132)
        at org.sqlite.core.DB.prepare(DB.java:264)
        at org.sqlite.jdbc3.JDBC3Statement.lambda$execute$0(JDBC3Statement.java:54)
        at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454)
        at org.sqlite.jdbc3.JDBC3Statement.execute(JDBC3Statement.java:43)
        at org.jooq.tools.jdbc.DefaultStatement.execute(DefaultStatement.java:102)
        at org.jooq.impl.SettingsEnabledPreparedStatement.execute(SettingsEnabledPreparedStatement.java:227)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:458)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:348)
        ... 14 more
```

```java
    public void connect() throws SQLException {
        try {
            Class.forName("org.sqlite.JDBC");
        } catch (ClassNotFoundException e) {
            throw new IllegalStateException("Failed to load SQLite JDBC class", e);
        }
        
        Connection connection = DriverManager.getConnection("jdbc:sqlite:" + database);
        dsl = DSL.using(connection, SQLDialect.SQLITE);
    }


    public void createTableIfNotExists() {
        dsl.createTableIfNotExists(Authme.AUTHME)
                .column(Authme.AUTHME.ID, SQLDataType.INTEGER.identity(true))
                .execute();
    }
    
    private void alterTable(Field field, DataType type) {
        dsl.alterTable(Authme.AUTHME)
                .addColumnIfNotExists(field, type).execute();
    }
    
    ...

    connect()
    createTableIfNotExists()
    alterTable(Authme.AUTHME.USERNAME, SQLDataType.VARCHAR(255));
```

Database struct:
```
CREATE TABLE "authme" (
	"id"	INTEGER AUTOINCREMENT,
	"username"	VARCHAR(255) NOT NULL UNIQUE,
	"realname"	VARCHAR(255) NOT NULL DEFAULT 'Player',
	"password"	VARCHAR(255) NOT NULL,
	"ip"	VARCHAR(40) NOT NULL,
	"firstlogin"	BIGINT NOT NULL DEFAULT 0,
	"lastlogin"	BIGINT NOT NULL DEFAULT 0,
	"x"	DOUBLE NOT NULL DEFAULT '0.0',
	"y"	DOUBLE NOT NULL DEFAULT '0.0',
	"z"	DOUBLE NOT NULL DEFAULT '0.0',
	"world"	VARCHAR(255) NOT NULL DEFAULT 'world',
	"isLogged"	INT DEFAULT '0', verified INT NOT NULL DEFAULT 0, newsChecked INT NOT NULL DEFAULT 0
);
```

### Steps to reproduce the problem

execute 3 methods 
    connect()
    createTableIfNotExists()
    alterTable(Authme.AUTHME.USERNAME, SQLDataType.VARCHAR(255));
of the provided code

### jOOQ Version

OSS 3.19.3

### Database product and version

SQLite 3.45.1.0

### Java Version

openjdk 17

### OS Version

Kubuntu 23.10

### JDBC driver name and version (include name if unofficial driver)

org.xerial:sqlite-jdbc:3.45.1.0

**Comment by lukaseder** [comment]
Thank you very much for your message. SQLite doesn't support this syntax natively:
https://www.sqlite.org/lang_altertable.html

As you can see on the [`addColumnIfNotExists()`](https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/AlterTableStep.html#addColumnIfNotExists(org.jooq.Field)) method's `@Support` annotation, jOOQ doesn't currently support the method for SQLite:

```java
@Support({AURORA_POSTGRES,BIGQUERY,COCKROACHDB,DB2,DUCKDB,EXASOL,H2,HANA,IGNITE,MARIADB,ORACLE,POSTGRES_10,SQLDATAWAREHOUSE,SQLSERVER,TERADATA,TRINO,YUGABYTEDB})
``` 

We have a big task on our roadmap to offer alternative execution models where such `IF [ NOT ] EXISTS` clauses can be emulated using multiple JDBC statements:

- https://github.com/jOOQ/jOOQ/issues/9645

Currently, the idea is that a single jOOQ statement should only produce a single JDBC statement, and that means a RDBMS needs some sort of procedural anonymous block support in order to emulate `IF [ NOT ] EXISTS`.

Since this feature will be implemented once #9645 is out, I'm closing this as a duplicate.
