### ISSUE TITLE
AbstractScope::dsl, ::settings, ::dialect, and ::family should avoid unnecessary null-checks on Configuration - Merge [#16209]

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#16210]

**Comment by scottdfedorov** [comment]
Hey Lukas, I believe this broke our tests.... We were attempting to create a mock of a configuration `private val jooqConfig = mock<Configuration>()` which was being passed to a `DefaultRecordUnmapper` and it is now failing with an error:
```
Cannot invoke "java.time.Clock.instant()" because the return value of "org.jooq.Configuration.clock()" is null
java.lang.NullPointerException: Cannot invoke "java.time.Clock.instant()" because the return value of "org.jooq.Configuration.clock()" is null
	at org.jooq.impl.AbstractLazyScope.<init>(AbstractLazyScope.java:79)
	at org.jooq.impl.AbstractLazyScope.<init>(AbstractLazyScope.java:67)
	at org.jooq.impl.DefaultConverterContext.<init>(DefaultConverterContext.java:51)
	at org.jooq.impl.Tools.converterContext(Tools.java:7782)
	at org.jooq.impl.DefaultRecordUnmapper.<init>(DefaultRecordUnmapper.java:92)
```

Do you have any guidance here on how we can not bother with creating an actual "Configuration"?

**Comment by lukaseder** [comment]
@scottdfedorov If you're certain that there's an issue in jOOQ, please create a new issue with complete reproducer.
