### ISSUE TITLE
Upgrade DuckDB dialect to DuckDB 0.10.0

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#16287]
DuckDB 0.10.0 has been released with a few interesting improvements for jOOQ:
https://duckdb.org/2024/02/13/announcing-duckdb-0100

- [x] `COMMENT ON`: https://github.com/duckdb/duckdb/pull/10372
- [x] Window `EXCLUDE`: https://github.com/duckdb/duckdb/pull/9220
- [x] Window `DISTINCT`: https://github.com/duckdb/duckdb/pull/9754
- [x] `EXCEPT ALL` and `INTERSECT ALL`: https://github.com/duckdb/duckdb/pull/9636

Other changes:

- [x] `DUCKDB_COLUMNS` now reports a `NULL` type instead of an `""` type
- [x] JDBC batching is now supported

Tracked elsewhere:

- `UHUGEINT`: https://github.com/duckdb/duckdb/pull/8635 (see also https://github.com/jOOQ/jOOQ/issues/10328)
- Lambdas: https://github.com/jOOQ/jOOQ/issues/16288
- Fixed length arrays: https://github.com/duckdb/duckdb/pull/8983: https://github.com/jOOQ/jOOQ/issues/16291

**Comment by lukaseder** [comment]
DuckDB 0.9.0 didn't announce any news relevant to jOOQ:

https://duckdb.org/2023/09/26/announcing-duckdb-090.html

**Comment by lukaseder** [comment]
DuckDB is still following the beta versioning scheme `0.x`, and our support is still marked as "experimental," so we won't continue supporting 0.9.0 or older versions.

**Comment by lukaseder** [comment]
Upgrading to 0.10.2

**Comment by lukaseder** [comment]
See release notes:

- https://github.com/duckdb/duckdb/releases/tag/v0.10.1
- https://github.com/duckdb/duckdb/releases/tag/v0.10.2

**Comment by lukaseder** [comment]
I tried upgrading to 0.10.3 but there's another show stopping regression:

```
org.jooq.exception.IntegrityConstraintViolationException: SQL [create table t_directory (id int not null, parent_id int, is_directory int, label varchar(50), constraint pk_t_directory primary key (id))]; FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "Attempting to commit a transaction that is read-only but has made changes - this should not be possible""
	at org.jooq_3.20.0-SNAPSHOT.DUCKDB.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3639)
	at org.jooq.impl.Tools.translate(Tools.java:3620)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:827)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:362)
	at org.jooq.test.setup.DatabaseSetup$Script.handleExceptions(DatabaseSetup.java:1068)
	at org.jooq.test.setup.DatabaseSetup$Script.lambda$0(DatabaseSetup.java:1403)
	at org.jooq.test.agent.SupportVerificationDispatcher.deactivated(SupportVerificationDispatcher.java:125)
	at org.jooq.test.setup.DatabaseSetup$Script.executeForAllDialects(DatabaseSetup.java:1278)
	at org.jooq.test.setup.DatabaseSetup$Script.execute(DatabaseSetup.java:1057)
	at org.jooq.test.setup.DatabaseSetup.execute(DatabaseSetup.java:685)
	at org.jooq.test.jOOQAbstractTest.setUp(jOOQAbstractTest.java:704)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:757)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.sql.SQLException: FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "Attempting to commit a transaction that is read-only but has made changes - this should not be possible""
	at org.duckdb.DuckDBNative.duckdb_jdbc_execute(Native Method)
	at org.duckdb.DuckDBPreparedStatement.execute(DuckDBPreparedStatement.java:143)
	at org.duckdb.DuckDBPreparedStatement.execute(DuckDBPreparedStatement.java:197)
	at org.jooq.tools.jdbc.DefaultStatement.execute(DefaultStatement.java:102)
	at org.jooq.impl.SettingsEnabledPreparedStatement.execute(SettingsEnabledPreparedStatement.java:227)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:458)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:348)
	... 37 more
```

not really motivated to investigate this one

**Comment by lukaseder** [comment]
This error still persists with 1.0.0:
https://github.com/jOOQ/jOOQ/issues/16287#issuecomment-2137250656

**Comment by lukaseder** [comment]
The error is reported here:
https://github.com/duckdb/duckdb-java/issues/36
