### ISSUE TITLE
ExceptionInInitializerError when accessing UDT domain before other static fields

### ISSUE THREAD

**Issue by akervinen** [jOOQ/jOOQ#16296]
### Expected behavior

Given a schema with a custom UDT, a domain using that UDT, and a table using that domain, static fields in generated code should work correctly regardless of which field is first accessed.

### Actual behavior

When accessing a domain static field, static initialization fails, due to what seems like a loop in definitions.

```sql
CREATE SCHEMA mcve;

CREATE TYPE mcve.foo as (bar text);

CREATE DOMAIN mcve.baz mcve.foo;

CREATE TABLE mcve.test (
  quz mcve.baz,

  CONSTRAINT pk_test PRIMARY KEY (quz)
);
```

```java
@Test
public void mcveTest() {
    Domains.BAZ.toString();
}
```

> ExceptionInInitializerError: Cannot invoke "org.jooq.Domain.getDataType()" because "org.jooq.mcve.java.postgres.Domains.BAZ" is null

<details>
  <summary>Full stacktrace</summary>
  
  ```
java.lang.ExceptionInInitializerError
	at org.jooq.mcve.java.postgres.Mcve.<init>(Mcve.java:35)
	at org.jooq.mcve.java.postgres.Mcve.<clinit>(Mcve.java:30)
	at org.jooq.mcve.java.postgres.udt.Foo.getSchema(Foo.java:52)
	at org.jooq.impl.AbstractDataType.lazyName(AbstractDataType.java:742)
	at org.jooq.impl.UDTDataType.lambda$new$db692576$1(UDTDataType.java:58)
	at org.jooq.impl.LazyName.name(LazyName.java:66)
	at org.jooq.impl.LazyName.accept(LazyName.java:77)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:371)
	at org.jooq.impl.DefaultDSLContext.renderInlined(DefaultDSLContext.java:748)
	at org.jooq.impl.AbstractQueryPart.toString(AbstractQueryPart.java:192)
	at org.jooq.impl.DefaultDataType.<init>(DefaultDataType.java:361)
	at org.jooq.impl.DefaultDataType.<init>(DefaultDataType.java:353)
	at org.jooq.impl.DefaultDataType.<init>(DefaultDataType.java:349)
	at org.jooq.impl.DefaultDataType.<init>(DefaultDataType.java:337)
	at org.jooq.impl.UDTDataType.<init>(UDTDataType.java:55)
	at org.jooq.impl.UDTImpl.getDataType(UDTImpl.java:179)
	at org.jooq.mcve.java.postgres.Domains.<clinit>(Domains.java:28)
	at org.jooq.mcve.test.java.postgres.JavaTest.mcveTest(JavaTest.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Caused by: java.lang.NullPointerException: Cannot invoke "org.jooq.Domain.getDataType()" because "org.jooq.mcve.java.postgres.Domains.BAZ" is null
	at org.jooq.mcve.java.postgres.tables.Test.<init>(Test.java:55)
	at org.jooq.mcve.java.postgres.tables.Test.<init>(Test.java:58)
	at org.jooq.mcve.java.postgres.tables.Test.<init>(Test.java:83)
	at org.jooq.mcve.java.postgres.tables.Test.<clinit>(Test.java:42)
	... 51 more
```
</details>

Accessing any other field before domain works without error. It also works correctly if the domain doesn't wrap a UDT, or if the table uses the UDT without the domain in between.

### Steps to reproduce the problem

https://github.com/akervinen/jOOQ-mcve-udt-domain-codegen in `./jOOQ-mcve-java-postgres`

### jOOQ Version

jOOQ Open Source 3.19.3

### Database product and version

PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu

### Java Version

openjdk version "17.0.10" 2024-01-16 LTS

### OS Version

Microsoft Windows [Version 10.0.19045.4046]

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.6.0

**Comment by akervinen** [comment]
This may be related to #13651 or even a duplicate, but seems to trigger differently. In my project code I had no `Domains.FOO` references, the error was due to accessing a table, similarly to the existing issue, but I managed to narrow it down to the domain reference instead of possibly multi-thread access.

**Comment by lukaseder** [comment]
Thanks a lot for your report and MCVE. I'll look into this shortly.

**Comment by lukaseder** [comment]
I can reproduce this exception:

```
java.lang.ExceptionInInitializerError
	at org.jooq.mcve.java.postgres.Mcve.<init>(Mcve.java:35)
	at org.jooq.mcve.java.postgres.Mcve.<clinit>(Mcve.java:30)
	at org.jooq.mcve.java.postgres.udt.Foo.getSchema(Foo.java:52)
	at org.jooq.impl.AbstractDataType.lazyName(AbstractDataType.java:742)
	at org.jooq.impl.UDTDataType.lambda$new$db692576$1(UDTDataType.java:58)
	at org.jooq.impl.LazyName.name(LazyName.java:66)
	at org.jooq.impl.LazyName.accept(LazyName.java:77)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:371)
	at org.jooq.impl.DefaultDSLContext.renderInlined(DefaultDSLContext.java:748)
	at org.jooq.impl.AbstractQueryPart.toString(AbstractQueryPart.java:192)
	at org.jooq.impl.DefaultDataType.<init>(DefaultDataType.java:361)
	at org.jooq.impl.DefaultDataType.<init>(DefaultDataType.java:353)
	at org.jooq.impl.DefaultDataType.<init>(DefaultDataType.java:349)
	at org.jooq.impl.DefaultDataType.<init>(DefaultDataType.java:337)
	at org.jooq.impl.UDTDataType.<init>(UDTDataType.java:55)
	at org.jooq.impl.UDTImpl.getDataType(UDTImpl.java:179)
	at org.jooq.mcve.java.postgres.Domains.<clinit>(Domains.java:28)
	at org.jooq.mcve.test.java.postgres.JavaTest.mcveTest(JavaTest.java:82)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
Caused by: java.lang.NullPointerException: Cannot invoke "org.jooq.Domain.getDataType()" because "org.jooq.mcve.java.postgres.Domains.BAZ" is null
	at org.jooq.mcve.java.postgres.tables.Test.<init>(Test.java:55)
	at org.jooq.mcve.java.postgres.tables.Test.<init>(Test.java:58)
	at org.jooq.mcve.java.postgres.tables.Test.<init>(Test.java:83)
	at org.jooq.mcve.java.postgres.tables.Test.<clinit>(Test.java:42)
	... 48 more
```

**Comment by lukaseder** [comment]
Definitely not an easy fix.
