### ISSUE TITLE
Parser shouldn't fail with NumberFormatException

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#16336]
As shown here: https://github.com/jOOQ/jOOQ/issues/16330, it is possible for the parser to fail with a `NumberFormatException` (or something similar) when it would be expected to get a `ParserException`:

```
java.lang.NumberFormatException: For input string: "0.0000000000000000e"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:651)
	at org.jooq.impl.DefaultParseContext.parseUnsignedNumericLiteralIf(ParserImpl.java:13737)
	at org.jooq.impl.DefaultParseContext.parseFieldUnsignedNumericLiteralIf(ParserImpl.java:13716)
	at org.jooq.impl.DefaultParseContext.parseTerm(ParserImpl.java:9493)
	at org.jooq.impl.DefaultParseContext.parseUnaryOps(ParserImpl.java:8364)
	at org.jooq.impl.DefaultParseContext.parseExp(ParserImpl.java:8338)
	at org.jooq.impl.DefaultParseContext.parseFactor(ParserImpl.java:8315)
	at org.jooq.impl.DefaultParseContext.parseSum(ParserImpl.java:8256)
	at org.jooq.impl.DefaultParseContext.parseNumericOp(ParserImpl.java:8205)
	at org.jooq.impl.DefaultParseContext.parseCollated(ParserImpl.java:8054)
	at org.jooq.impl.DefaultParseContext.parseConcat(ParserImpl.java:8037)
	at org.jooq.impl.DefaultParseContext.parsePredicate(ParserImpl.java:6747)
	at org.jooq.impl.DefaultParseContext.parseNot(ParserImpl.java:6578)
	at org.jooq.impl.DefaultParseContext.parseAnd(ParserImpl.java:6568)
	at org.jooq.impl.DefaultParseContext.parseXor(ParserImpl.java:6559)
	at org.jooq.impl.DefaultParseContext.parseOr(ParserImpl.java:6550)
	at org.jooq.impl.DefaultParseContext.parseFieldOrRow(ParserImpl.java:7948)
	at org.jooq.impl.DefaultParseContext.parseTerm(ParserImpl.java:9552)
	at org.jooq.impl.DefaultParseContext.parseUnaryOps(ParserImpl.java:8364)
	at org.jooq.impl.DefaultParseContext.parseExp(ParserImpl.java:8338)
	at org.jooq.impl.DefaultParseContext.parseFactor(ParserImpl.java:8315)
	at org.jooq.impl.DefaultParseContext.parseSum(ParserImpl.java:8256)
	at org.jooq.impl.DefaultParseContext.parseNumericOp(ParserImpl.java:8205)
	at org.jooq.impl.DefaultParseContext.parseCollated(ParserImpl.java:8054)
	at org.jooq.impl.DefaultParseContext.parseConcat(ParserImpl.java:8037)
	at org.jooq.impl.DefaultParseContext.parsePredicate(ParserImpl.java:6747)
	at org.jooq.impl.DefaultParseContext.parseNot(ParserImpl.java:6578)
	at org.jooq.impl.DefaultParseContext.parseAnd(ParserImpl.java:6568)
	at org.jooq.impl.DefaultParseContext.parseXor(ParserImpl.java:6559)
	at org.jooq.impl.DefaultParseContext.parseOr(ParserImpl.java:6550)
	at org.jooq.impl.DefaultParseContext.parseFieldOrRow(ParserImpl.java:7948)
	at org.jooq.impl.DefaultParseContext.parseTerm(ParserImpl.java:9552)
	at org.jooq.impl.DefaultParseContext.parseUnaryOps(ParserImpl.java:8364)
	at org.jooq.impl.DefaultParseContext.parseExp(ParserImpl.java:8338)
	at org.jooq.impl.DefaultParseContext.parseFactor(ParserImpl.java:8315)
	at org.jooq.impl.DefaultParseContext.parseSum(ParserImpl.java:8256)
	at org.jooq.impl.DefaultParseContext.parseNumericOp(ParserImpl.java:8205)
	at org.jooq.impl.DefaultParseContext.parseCollated(ParserImpl.java:8054)
	at org.jooq.impl.DefaultParseContext.parseConcat(ParserImpl.java:8037)
	at org.jooq.impl.DefaultParseContext.parsePredicate(ParserImpl.java:6747)
	at org.jooq.impl.DefaultParseContext.parseNot(ParserImpl.java:6578)
	at org.jooq.impl.DefaultParseContext.parseAnd(ParserImpl.java:6568)
	at org.jooq.impl.DefaultParseContext.parseXor(ParserImpl.java:6559)
	at org.jooq.impl.DefaultParseContext.parseOr(ParserImpl.java:6550)
	at org.jooq.impl.DefaultParseContext.parseField(ParserImpl.java:7953)
	at org.jooq.impl.DefaultParseContext.lambda$parseField0$8(ParserImpl.java:1009)
	at org.jooq.impl.DefaultParseContext.wrap(ParserImpl.java:15244)
	at org.jooq.impl.DefaultParseContext.parseField0(ParserImpl.java:1009)
	at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:848)
	at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:843)
	at org.jooq.impl.MetaImpl$MetaTable.initColumns(MetaImpl.java:1399)
	at org.jooq.impl.MetaImpl$MetaTable.<init>(MetaImpl.java:941)
	at org.jooq.impl.MetaImpl$MetaSchema.lambda$getTables$2(MetaImpl.java:508)
	at org.jooq.impl.Tools.map(Tools.java:2520)
	at org.jooq.impl.MetaImpl$MetaSchema.getTables(MetaImpl.java:477)
	at org.jooq.impl.MetaImpl.lambda$getTables0$3(MetaImpl.java:309)
	at org.jooq.impl.Tools.flatMap(Tools.java:2535)
	at org.jooq.impl.MetaImpl.getTables0(MetaImpl.java:309)
	at org.jooq.impl.AbstractMeta.lambda$initTables$4(AbstractMeta.java:186)
	at org.jooq.impl.AbstractMeta.get(AbstractMeta.java:409)
	at org.jooq.impl.AbstractMeta.initTables(AbstractMeta.java:186)
	at org.jooq.impl.AbstractMeta.getTables(AbstractMeta.java:172)
	at org.jooq.impl.AbstractMeta.getTables(AbstractMeta.java:167)
```

The relevant `MetaImpl` logic doesn't expect the `NFE` either, which is why it fails for an otherwise cosmetic problem.

**Comment by lukaseder** [comment]
Possible trigger `'E\\Uasdf'` produces:

```
java.lang.StringIndexOutOfBoundsException: Range [4, 4 + 8) out of bounds for length 9
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromIndexSize(Preconditions.java:118)
	at java.base/jdk.internal.util.Preconditions.checkFromIndexSize(Preconditions.java:397)
	at java.base/java.lang.String.checkBoundsOffCount(String.java:4849)
	at java.base/java.lang.String.rangeCheck(String.java:307)
	at java.base/java.lang.String.<init>(String.java:303)
	at org.jooq.impl.DefaultParseContext.parseUnquotedStringLiteral(ParserImpl.java:13750)
	at org.jooq.impl.DefaultParseContext.parseStringLiteralIf(ParserImpl.java:13510)
	at org.jooq.impl.DefaultParseContext.parseStringLiteral(ParserImpl.java:13497)
	at org.jooq.impl.DefaultParseContext.parseTerm(ParserImpl.java:8866)
	at org.jooq.impl.DefaultParseContext.parseUnaryOps(ParserImpl.java:8389)
	at org.jooq.impl.DefaultParseContext.parseExp(ParserImpl.java:8363)
	at org.jooq.impl.DefaultParseContext.parseFactor(ParserImpl.java:8340)
	at org.jooq.impl.DefaultParseContext.parseSum(ParserImpl.java:8281)
	at org.jooq.impl.DefaultParseContext.parseNumericOp(ParserImpl.java:8230)
	at org.jooq.impl.DefaultParseContext.parseCollated(ParserImpl.java:8079)
	at org.jooq.impl.DefaultParseContext.parseConcat(ParserImpl.java:8060)
	at org.jooq.impl.DefaultParseContext.parsePredicate(ParserImpl.java:6770)
	at org.jooq.impl.DefaultParseContext.parseNot(ParserImpl.java:6601)
	at org.jooq.impl.DefaultParseContext.parseAnd(ParserImpl.java:6591)
	at org.jooq.impl.DefaultParseContext.parseXor(ParserImpl.java:6582)
	at org.jooq.impl.DefaultParseContext.parseOr(ParserImpl.java:6573)
	at org.jooq.impl.DefaultParseContext.parseField(ParserImpl.java:7976)
	at org.jooq.impl.DefaultParseContext.lambda$10(ParserImpl.java:1018)
	at org.jooq.impl.DefaultParseContext.wrap(ParserImpl.java:15356)
	at org.jooq.impl.DefaultParseContext.parseField0(ParserImpl.java:1018)
	at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:857)
	at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:852)
	at org.jooq.impl.AbstractParserTest.failAll(AbstractParserTest.java:230)
	at org.jooq.impl.AbstractParserTest.failAllFields(AbstractParserTest.java:273)
	at org.jooq.impl.ParserLiteralTest.testStringLiteral(ParserLiteralTest.java:217)
```

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.6 (https://github.com/jOOQ/jOOQ/issues/16351)
- 3.18.13 (https://github.com/jOOQ/jOOQ/issues/16352)
- 3.17.22 (https://github.com/jOOQ/jOOQ/issues/16353)
