### ISSUE TITLE
NumberFormatException in parser when encountering double value with implicit 0 exponent

### ISSUE THREAD

**Issue by MikePSQR** [jOOQ/jOOQ#16330]
### Expected behavior

`dslContext.meta().getTables()` does not throw

### Actual behavior

`dslContext.meta().getTables()` throws `NumberFormatException`

### Steps to reproduce the problem

Using SQLServer 2019:
```
jooq.createTable("bike").column("age", SQLDataType.DOUBLE.defaultValue(0.0)).execute();
try {
    Thread.sleep(500); // I noticed sometimes it does not see the table yet
} catch (InterruptedException e) {
    throw new RuntimeException(e);
}
jooq.meta().getTables("bike");
```
the `getTables()` throws the following exception:
```
java.lang.NumberFormatException: For input string: "0.0000000000000000e"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:651)
	at org.jooq.impl.DefaultParseContext.parseUnsignedNumericLiteralIf(ParserImpl.java:13737)
	at org.jooq.impl.DefaultParseContext.parseFieldUnsignedNumericLiteralIf(ParserImpl.java:13716)
	at org.jooq.impl.DefaultParseContext.parseTerm(ParserImpl.java:9493)
	at org.jooq.impl.DefaultParseContext.parseUnaryOps(ParserImpl.java:8364)
	at org.jooq.impl.DefaultParseContext.parseExp(ParserImpl.java:8338)
	at org.jooq.impl.DefaultParseContext.parseFactor(ParserImpl.java:8315)
	at org.jooq.impl.DefaultParseContext.parseSum(ParserImpl.java:8256)
	at org.jooq.impl.DefaultParseContext.parseNumericOp(ParserImpl.java:8205)
	at org.jooq.impl.DefaultParseContext.parseCollated(ParserImpl.java:8054)
	at org.jooq.impl.DefaultParseContext.parseConcat(ParserImpl.java:8037)
	at org.jooq.impl.DefaultParseContext.parsePredicate(ParserImpl.java:6747)
	at org.jooq.impl.DefaultParseContext.parseNot(ParserImpl.java:6578)
	at org.jooq.impl.DefaultParseContext.parseAnd(ParserImpl.java:6568)
	at org.jooq.impl.DefaultParseContext.parseXor(ParserImpl.java:6559)
	at org.jooq.impl.DefaultParseContext.parseOr(ParserImpl.java:6550)
	at org.jooq.impl.DefaultParseContext.parseFieldOrRow(ParserImpl.java:7948)
	at org.jooq.impl.DefaultParseContext.parseTerm(ParserImpl.java:9552)
	at org.jooq.impl.DefaultParseContext.parseUnaryOps(ParserImpl.java:8364)
	at org.jooq.impl.DefaultParseContext.parseExp(ParserImpl.java:8338)
	at org.jooq.impl.DefaultParseContext.parseFactor(ParserImpl.java:8315)
	at org.jooq.impl.DefaultParseContext.parseSum(ParserImpl.java:8256)
	at org.jooq.impl.DefaultParseContext.parseNumericOp(ParserImpl.java:8205)
	at org.jooq.impl.DefaultParseContext.parseCollated(ParserImpl.java:8054)
	at org.jooq.impl.DefaultParseContext.parseConcat(ParserImpl.java:8037)
	at org.jooq.impl.DefaultParseContext.parsePredicate(ParserImpl.java:6747)
	at org.jooq.impl.DefaultParseContext.parseNot(ParserImpl.java:6578)
	at org.jooq.impl.DefaultParseContext.parseAnd(ParserImpl.java:6568)
	at org.jooq.impl.DefaultParseContext.parseXor(ParserImpl.java:6559)
	at org.jooq.impl.DefaultParseContext.parseOr(ParserImpl.java:6550)
	at org.jooq.impl.DefaultParseContext.parseFieldOrRow(ParserImpl.java:7948)
	at org.jooq.impl.DefaultParseContext.parseTerm(ParserImpl.java:9552)
	at org.jooq.impl.DefaultParseContext.parseUnaryOps(ParserImpl.java:8364)
	at org.jooq.impl.DefaultParseContext.parseExp(ParserImpl.java:8338)
	at org.jooq.impl.DefaultParseContext.parseFactor(ParserImpl.java:8315)
	at org.jooq.impl.DefaultParseContext.parseSum(ParserImpl.java:8256)
	at org.jooq.impl.DefaultParseContext.parseNumericOp(ParserImpl.java:8205)
	at org.jooq.impl.DefaultParseContext.parseCollated(ParserImpl.java:8054)
	at org.jooq.impl.DefaultParseContext.parseConcat(ParserImpl.java:8037)
	at org.jooq.impl.DefaultParseContext.parsePredicate(ParserImpl.java:6747)
	at org.jooq.impl.DefaultParseContext.parseNot(ParserImpl.java:6578)
	at org.jooq.impl.DefaultParseContext.parseAnd(ParserImpl.java:6568)
	at org.jooq.impl.DefaultParseContext.parseXor(ParserImpl.java:6559)
	at org.jooq.impl.DefaultParseContext.parseOr(ParserImpl.java:6550)
	at org.jooq.impl.DefaultParseContext.parseField(ParserImpl.java:7953)
	at org.jooq.impl.DefaultParseContext.lambda$parseField0$8(ParserImpl.java:1009)
	at org.jooq.impl.DefaultParseContext.wrap(ParserImpl.java:15244)
	at org.jooq.impl.DefaultParseContext.parseField0(ParserImpl.java:1009)
	at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:848)
	at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:843)
	at org.jooq.impl.MetaImpl$MetaTable.initColumns(MetaImpl.java:1399)
	at org.jooq.impl.MetaImpl$MetaTable.<init>(MetaImpl.java:941)
	at org.jooq.impl.MetaImpl$MetaSchema.lambda$getTables$2(MetaImpl.java:508)
	at org.jooq.impl.Tools.map(Tools.java:2520)
	at org.jooq.impl.MetaImpl$MetaSchema.getTables(MetaImpl.java:477)
	at org.jooq.impl.MetaImpl.lambda$getTables0$3(MetaImpl.java:309)
	at org.jooq.impl.Tools.flatMap(Tools.java:2535)
	at org.jooq.impl.MetaImpl.getTables0(MetaImpl.java:309)
	at org.jooq.impl.AbstractMeta.lambda$initTables$4(AbstractMeta.java:186)
	at org.jooq.impl.AbstractMeta.get(AbstractMeta.java:409)
	at org.jooq.impl.AbstractMeta.initTables(AbstractMeta.java:186)
	at org.jooq.impl.AbstractMeta.getTables(AbstractMeta.java:172)
	at org.jooq.impl.AbstractMeta.getTables(AbstractMeta.java:167)
```
while trying to parse the default value for the column `((0.0000000000000000e+000))` (as shown in `INFORMATION_SCHEMA.COLUMNS`).

### jOOQ Version

3.19.3

### Database product and version

Microsoft SQL Server 2019 (RTM-CU25) (KB5033688) - 15.0.4355.3 (X64)

### Java Version

openjdk 17.0.9 2023-10-17

### OS Version

Ubuntu 22.04.3 LTS

### JDBC driver name and version (include name if unofficial driver)

Microsoft JDBC Driver 12.2 for SQL Server (ver. 12.2.0.0, JDBC4.2)

**Comment by lukaseder** [comment]
Thank you very much for your report. I can reproduce this. Will look into it right away.

**Comment by lukaseder** [comment]
There are two problems here:

- The fact that this format cannot be parsed (this issue)
- The fact that the `NumberFormatException` leaks out of `MetaImpl`, even if it should be ignored (and logged as a cosmetic problem). That's: https://github.com/jOOQ/jOOQ/issues/16336

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.5 (https://github.com/jOOQ/jOOQ/issues/16337)
- 3.18.12 (https://github.com/jOOQ/jOOQ/issues/16338)
- 3.19.21 (https://github.com/jOOQ/jOOQ/issues/16339)
