### ISSUE TITLE
Parser always parses NULL literal of type BOOLEAN

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#16368]
When parsing a statement like this:

```sql
INSERT INTO t_language (id, cd, description, description_english) VALUES (4, 'pt', null, null);
```

The data type associated with the two `NULL` literals is always `BOOLEAN`, despite the fact that this isn't the case here.

The call stack that leads to this behaviour is, for example:

```
java.lang.Throwable
	at org.jooq.impl.DefaultParseContext.parseTerm(ParserImpl.java:9614)
	at org.jooq.impl.DefaultParseContext.parseUnaryOps(ParserImpl.java:8389)
	at org.jooq.impl.DefaultParseContext.parseExp(ParserImpl.java:8363)
	at org.jooq.impl.DefaultParseContext.parseFactor(ParserImpl.java:8340)
	at org.jooq.impl.DefaultParseContext.parseSum(ParserImpl.java:8281)
	at org.jooq.impl.DefaultParseContext.parseNumericOp(ParserImpl.java:8230)
	at org.jooq.impl.DefaultParseContext.parseCollated(ParserImpl.java:8079)
	at org.jooq.impl.DefaultParseContext.parseConcat(ParserImpl.java:8060)
	at org.jooq.impl.DefaultParseContext.parsePredicate(ParserImpl.java:6770)
	at org.jooq.impl.DefaultParseContext.parseNot(ParserImpl.java:6601)
	at org.jooq.impl.DefaultParseContext.parseAnd(ParserImpl.java:6591)
	at org.jooq.impl.DefaultParseContext.parseXor(ParserImpl.java:6582)
	at org.jooq.impl.DefaultParseContext.parseOr(ParserImpl.java:6573)
	at org.jooq.impl.DefaultParseContext.parseField(ParserImpl.java:7976)
	at org.jooq.impl.DefaultParseContext.lambda$38(ParserImpl.java:2371)
	at org.jooq.impl.DefaultParseContext.parseList(ParserImpl.java:13939)
	at org.jooq.impl.DefaultParseContext.parseList(ParserImpl.java:13926)
	at org.jooq.impl.DefaultParseContext.parseInsert(ParserImpl.java:2371)
	at org.jooq.impl.DefaultParseContext.parseQuery(ParserImpl.java:1199)
	at org.jooq.impl.DefaultParseContext.lambda$2(ParserImpl.java:915)
	at org.jooq.impl.DefaultParseContext.wrap(ParserImpl.java:15385)
	at org.jooq.impl.DefaultParseContext.parse(ParserImpl.java:903)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:781)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:776)
	at org.jooq.test.setup.DatabaseSetup$Script.lambda$0(DatabaseSetup.java:1252)
```

We can see:

```java
        else if ((field = parseBooleanValueExpressionIf()) != null)
            return field;
```

And:

```java
    private final Field<Boolean> parseBooleanValueExpressionIf() {
        TruthValue truth = parseTruthValueIf();

        if (truth != null) {
            switch (truth) {
                case T_TRUE:
                    return inline(true);
                case T_FALSE:
                    return inline(false);
                case T_NULL:
                    return inline((Boolean) null);
                default:
                    throw exception("Truth value not supported: " + truth);
            }
        }

        return null;
    }
```

It's rarely the case that we need the `NULL` truth value in SQL, so it would be generally safer not to associate any data type with the value.

A future task that tries to auto-convert data types of `NULL` literals will be useful. We're going to need to tackle similar problems as the RDBMS themselves, see also the challenge of getting `NULL` literals right in PostgreSQL:

- https://github.com/jOOQ/jOOQ/issues/16367

**Comment by lukaseder** [comment]
Follow-up task to try to infer the type of `NULL` literals:

- https://github.com/jOOQ/jOOQ/issues/16369

**Comment by lukaseder** [comment]
There are some regressions when implementing this. I'll list them here:

- https://github.com/jOOQ/jOOQ/issues/16370

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.6 (https://github.com/jOOQ/jOOQ/issues/16371)
- 3.18.13 (https://github.com/jOOQ/jOOQ/issues/16372)
- 3.17.22 (https://github.com/jOOQ/jOOQ/issues/16373)
