### ISSUE TITLE
SQL Server's CREATE cannot fully qualify a sequence name

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#16479]
A recently added meta data test related to #12851 has uncovered the following problem:

```
org.jooq.exception.DataAccessException: SQL [create sequence [test].[dbo].[s64] as bigint start with 1]; 'CREATE SEQUENCE' does not allow specifying the database name as a prefix to the object name.
	at org.jooq_3.20.0-SNAPSHOT.SQLSERVER2022.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3593)
	at org.jooq.impl.Tools.translate(Tools.java:3581)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:827)
	at org.jooq.impl.BatchMultiple.execute(BatchMultiple.java:160)
	at org.jooq.impl.BatchMultiple.lambda$1(BatchMultiple.java:95)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.IntPipeline.toArray(IntPipeline.java:562)
	at org.jooq.impl.BatchMultiple.execute(BatchMultiple.java:97)
	at org.jooq.impl.QueriesImpl.executeBatch(QueriesImpl.java:145)
	at org.jooq.test.all.testcases.MetaDataTests.lambda$99(MetaDataTests.java:1592)
	at org.jooq.test.util.BaseTest.assertThrowsIf(BaseTest.java:458)
	at org.jooq.test.util.BaseTest.assertThrowsIf(BaseTest.java:446)
	at org.jooq.test.all.testcases.MetaDataTests.testMetaDataSequencesAsDataType(MetaDataTests.java:1589)
	at org.jooq.test.jOOQAbstractTest.testMetaDataSequencesAsDataType(jOOQAbstractTest.java:5089)
```

This isn't supported:

```sql
create sequence [test].[dbo].[s64] as bigint start with 1
```

But this is:

```sql
create sequence [dbo].[s64] as bigint start with 1
```

**Comment by lukaseder** [comment]
We already do this correctly for `ALTER SEQUENCE` and `DROP SEQUENCE`

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.7 (https://github.com/jOOQ/jOOQ/issues/16480)
- 3.18.14 (https://github.com/jOOQ/jOOQ/issues/16481)
- 3.17.23 (https://github.com/jOOQ/jOOQ/issues/16482)
