### ISSUE TITLE
Infer argument data types with more functions

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#16485]
We tend to infer data types from arguments of most functions or expressions, e.g. these are equivalent:

```java
// Type is inferred
USER_TYPED_FIELD.eq(new UserType());

// Type is explicit
USER_TYPED_FIELD.eq(val(new UserType(), USER_TYPED_FIELD));
```

This isn't yet being done for a few functions, e.g.:

- [ ] `DECODE`

The list will be amended. I'll implement a thorough test suite that checks all functions. Our integration tests tend not to use converted data types, except here and there. I just noticed this because of the new exception being thrown from integration tests (but not from user code) since #16090 #16425:

```
org.jooq.impl.DefaultDataType$DiscouragedStaticTypeRegistryUsage
	at org.jooq_3.20.0-SNAPSHOT.ORACLE23C.debug(Unknown Source)
	at org.jooq.impl.DefaultDataType.check(DefaultDataType.java:853)
	at org.jooq.impl.Val.accept(Val.java:195)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:733)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:382)
	at org.jooq.impl.QueryPartCollectionView.acceptElement(QueryPartCollectionView.java:251)
	at org.jooq.impl.QueryPartCollectionView.accept(QueryPartCollectionView.java:221)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:733)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:382)
	at org.jooq.impl.AbstractFunction.accept(AbstractFunction.java:75)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:733)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:382)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:292)
	at org.jooq.impl.Decode.accept0(Decode.java:144)
	at org.jooq.impl.AbstractCaseSimple.accept(AbstractCaseSimple.java:153)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:733)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:376)
	at org.jooq.impl.FieldMapForUpdate.lambda$0(FieldMapForUpdate.java:344)
	at org.jooq.impl.AbstractContext.data(AbstractContext.java:416)
	at org.jooq.impl.FieldMapForUpdate.acceptAssignmentClause(FieldMapForUpdate.java:344)
	at org.jooq.impl.FieldMapForUpdate.accept(FieldMapForUpdate.java:199)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:733)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:382)
	at org.jooq.impl.UpdateQueryImpl.accept2(UpdateQueryImpl.java:777)
	at org.jooq.impl.UpdateQueryImpl.accept1(UpdateQueryImpl.java:638)
	at org.jooq.impl.AbstractDMLQuery.accept0(AbstractDMLQuery.java:564)
	at org.jooq.impl.UpdateQueryImpl.accept(UpdateQueryImpl.java:595)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:733)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:382)
	at org.jooq.impl.DefaultDSLContext.renderInlined(DefaultDSLContext.java:748)
	at org.jooq.impl.AbstractQueryPart.equals(AbstractQueryPart.java:172)
	at org.jooq.Traversers.lambda$11(Traversers.java:147)
	at org.jooq.impl.CachingTraverser.lambda$4(CachingTraverser.java:108)
	at org.jooq.impl.QOM.traverse(QOM.java:18068)
	at org.jooq.impl.UpdateQueryImpl.$traverse(UpdateQueryImpl.java:997)
	at org.jooq.test.util.BaseTest.qomAssertions(BaseTest.java:806)
	at org.jooq.test.jOOQAbstractTest$QOMAssertionListener.start(jOOQAbstractTest.java:445)
	at org.jooq.impl.ExecuteListeners.start(ExecuteListeners.java:160)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:284)
	at org.jooq.impl.AbstractDMLQueryAsResultQuery.fetch(AbstractDMLQueryAsResultQuery.java:140)
	at org.jooq.test.OracleTest.testOracleInsertUpdateDeleteReturningBooleans(OracleTest.java:4130)
```

**Comment by lukaseder** [comment]
The failing test is:

```java
        create().update(T_BOOLEANS)
                .set(T_BOOLEANS.ONE_ZERO, decode(T_BOOLEANS.ONE_ZERO, Boolean_10.ZERO, Boolean_10.ONE, Boolean_10.ZERO))
                .where(T_BOOLEANS.ONE_ZERO.isNotNull())
                .returningResult(T_BOOLEANS.ID, T_BOOLEANS.ONE_ZERO)
                .fetch()
                .sortAsc(T_BOOLEANS.ID);
```

This won't be covered by the improvement here, as the `SET` clause should be used to infer the type of the `decode()` function, which is unlikely.
