### ISSUE TITLE
Intercept SQLFeatureNotSupportedException caused by DatabaseMetaData::getImportedKeys and other calls

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#16493]
When running some `DatabaseMetaData` queries against DuckDB, the following exception occurs:

```
org.jooq.exception.DataAccessException: Error while running ConnectionCallable
	at org.jooq.impl.DefaultDSLContext.connectionResult(DefaultDSLContext.java:663)
	at org.jooq.impl.MetaImpl.meta(MetaImpl.java:208)
	at org.jooq.impl.MetaImpl$MetaTable.getReferences(MetaImpl.java:1075)
	at org.jooq.impl.FilteredMeta$FilteredTable.getReferences(FilteredMeta.java:517)
	at org.jooq.impl.FilteredMeta$FilteredTable.getReferences(FilteredMeta.java:517)
	at org.jooq.impl.Diff$1.merge(Diff.java:303)
	at org.jooq.impl.Diff$1.merge(Diff.java:1)
	at org.jooq.impl.Diff.append(Diff.java:697)
	at org.jooq.impl.Diff.append(Diff.java:641)
	at org.jooq.impl.Diff.appendTables(Diff.java:329)
	at org.jooq.impl.Diff.lambda$3(Diff.java:177)
	at org.jooq.impl.Diff.append(Diff.java:697)
	at org.jooq.impl.Diff.append(Diff.java:641)
	at org.jooq.impl.Diff.appendSchemas(Diff.java:147)
	at org.jooq.impl.Diff.lambda$0(Diff.java:142)
	at org.jooq.impl.Diff.append(Diff.java:697)
	at org.jooq.impl.Diff.append(Diff.java:641)
	at org.jooq.impl.Diff.appendCatalogs(Diff.java:134)
	at org.jooq.impl.Diff.queries(Diff.java:130)
	at org.jooq.impl.AbstractMeta.migrateTo(AbstractMeta.java:665)
	at org.jooq.impl.AbstractMeta.migrateTo(AbstractMeta.java:660)
	at org.jooq.test.all.testcases.MetaDataTests.migrateTo(MetaDataTests.java:1414)
	at org.jooq.test.all.testcases.MetaDataTests.assertEmptyMigration(MetaDataTests.java:1717)
	at org.jooq.test.all.testcases.MetaDataTests.testMetaDataTimestampPrecisionDefault(MetaDataTests.java:1425)
	at org.jooq.test.jOOQAbstractTest.testMetaDataTimestampPrecisionDefault(jOOQAbstractTest.java:5068)
Caused by: java.sql.SQLFeatureNotSupportedException: getImportedKeys
	at org.duckdb.DuckDBDatabaseMetaData.getImportedKeys(DuckDBDatabaseMetaData.java:947)
	at org.jooq.impl.MetaImpl$MetaTable.lambda$8(MetaImpl.java:1076)
	at org.jooq.impl.MetaImpl.catalogSchema(MetaImpl.java:203)
	at org.jooq.impl.MetaImpl.catalogSchema(MetaImpl.java:188)
	at org.jooq.impl.MetaImpl$MetaTable.lambda$7(MetaImpl.java:1076)
	at org.jooq.impl.MetaImpl.lambda$0(MetaImpl.java:208)
	at org.jooq.impl.DefaultDSLContext.connectionResult(DefaultDSLContext.java:657)
	... 54 more
```

This happens even in cases where these keys are not necessary at all, breaking an unrelated feature. We should intercept these exceptions, and only debug log them.

**Comment by lukaseder** [comment]
Also, `getIndexInfo()`:

```
org.jooq.exception.DataAccessException: Error while running ConnectionCallable
	at org.jooq.impl.DefaultDSLContext.connectionResult(DefaultDSLContext.java:663)
	at org.jooq.impl.MetaImpl.meta(MetaImpl.java:210)
	at org.jooq.impl.MetaImpl$MetaTable.lambda$0(MetaImpl.java:955)
	at org.jooq.impl.Tools.ignoreNPE(Tools.java:7794)
	at org.jooq.impl.MetaImpl$MetaTable.getIndexes(MetaImpl.java:953)
	at org.jooq.impl.FilteredMeta$FilteredTable.getIndexes(FilteredMeta.java:466)
	at org.jooq.impl.FilteredMeta$FilteredTable.getIndexes(FilteredMeta.java:466)
	at org.jooq.impl.Diff$1.merge(Diff.java:305)
	at org.jooq.impl.Diff$1.merge(Diff.java:1)
	at org.jooq.impl.Diff.append(Diff.java:697)
	at org.jooq.impl.Diff.append(Diff.java:641)
	at org.jooq.impl.Diff.appendTables(Diff.java:329)
	at org.jooq.impl.Diff.lambda$3(Diff.java:177)
	at org.jooq.impl.Diff.append(Diff.java:697)
	at org.jooq.impl.Diff.append(Diff.java:641)
	at org.jooq.impl.Diff.appendSchemas(Diff.java:147)
	at org.jooq.impl.Diff.lambda$0(Diff.java:142)
	at org.jooq.impl.Diff.append(Diff.java:697)
	at org.jooq.impl.Diff.append(Diff.java:641)
	at org.jooq.impl.Diff.appendCatalogs(Diff.java:134)
	at org.jooq.impl.Diff.queries(Diff.java:130)
	at org.jooq.impl.AbstractMeta.migrateTo(AbstractMeta.java:665)
	at org.jooq.impl.AbstractMeta.migrateTo(AbstractMeta.java:660)
	at org.jooq.test.all.testcases.MetaDataTests.migrateTo(MetaDataTests.java:1414)
	at org.jooq.test.all.testcases.MetaDataTests.assertEmptyMigration(MetaDataTests.java:1717)
	at org.jooq.test.all.testcases.MetaDataTests.testMetaDataTimestampPrecisionDefault(MetaDataTests.java:1425)
	at org.jooq.test.jOOQAbstractTest.testMetaDataTimestampPrecisionDefault(jOOQAbstractTest.java:5068)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:757)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.sql.SQLFeatureNotSupportedException: getIndexInfo(
	at org.duckdb.DuckDBDatabaseMetaData.getIndexInfo(DuckDBDatabaseMetaData.java:970)
	at org.jooq.impl.MetaImpl$MetaTable.lambda$3(MetaImpl.java:956)
	at org.jooq.impl.MetaImpl.catalogSchema(MetaImpl.java:205)
	at org.jooq.impl.MetaImpl.catalogSchema(MetaImpl.java:190)
	at org.jooq.impl.MetaImpl$MetaTable.lambda$2(MetaImpl.java:956)
	at org.jooq.impl.MetaImpl.lambda$0(MetaImpl.java:210)
	at org.jooq.impl.DefaultDSLContext.connectionResult(DefaultDSLContext.java:657)
	... 56 more
```

Could be a new case for `MetaSQL` queries too.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.7 (https://github.com/jOOQ/jOOQ/issues/16495)
- 3.18.14 (https://github.com/jOOQ/jOOQ/issues/16496)
- 3.17.23 (https://github.com/jOOQ/jOOQ/issues/16497)
