### ISSUE TITLE
Parser fails to parse TIME[STAMP] WITH TIME ZONE literals

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#16535]
This query fails to parse:

```sql
select timestamp with time zone '2000-01-01 00:00:00.0Z'
```

The error is:

```
org.jooq.impl.ParserException: Unexpected content after end of query input: [1:18] select timestamp [*]with time zone '2000-01-01 00:00:00.0Z'
	at org.jooq.impl.DefaultParseContext.exception(ParserImpl.java:15452)
	at org.jooq.impl.DefaultParseContext.done(ParserImpl.java:15638)
	at org.jooq.impl.DefaultParseContext.lambda$8(ParserImpl.java:1017)
	at org.jooq.impl.DefaultParseContext.wrap(ParserImpl.java:15645)
	at org.jooq.impl.DefaultParseContext.parseSelect0(ParserImpl.java:1017)
	at org.jooq.impl.ParserImpl.parseSelect(ParserImpl.java:844)
	at org.jooq.impl.ParserImpl.parseSelect(ParserImpl.java:839)
	at org.jooq.testscripts.JDBC.main(JDBC.java:38)
```

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.7 (https://github.com/jOOQ/jOOQ/issues/16536)
- 3.18.14 (https://github.com/jOOQ/jOOQ/issues/16537)
- 3.17.23 (https://github.com/jOOQ/jOOQ/issues/16538)
