### ISSUE TITLE
Cannot configure matchers using jOOQ-codegen-gradle plugin

### ISSUE THREAD

**Issue by mvolf** [jOOQ/jOOQ#16560]
### Your question

My code generator configuration is as follows:

```
jooq {
    configuration {
        generator {
            strategy {
                matchers {
                    tables {
                        table {
                            pojoClass {
                                transform = 'PASCAL'
                                expression = '\$0_ENTITY'
                            }
                        }
                    }
                }
            }
            database {
                name = 'org.jooq.meta.postgres.PostgresDatabase'
                inputSchema = 'public'
                outputSchemaToDefault = true
                forcedTypes {
                    forcedType {
                        name = 'varchar'
                        expression = '.*'
                        types = 'JSONB?'
                    }
                    forcedType {
                        name = 'varchar'
                        expression = '.*'
                        types = 'INET'
                    }
                }
            }
            generate {
                pojosEqualsAndHashCode = true
                instanceFields = true
                pojos = true
                deprecationOnUnknownTypes = false
                relations = true
                fluentSetters = true
                daos = true
            }
            target {
                packageName = 'com.test'
                directory = 'src/main/kotlin'
                clean = false
            }
        }
        jdbc {
            driver = rootProject.gradlePostgresDriver
            url = gradlePostgresJdbc
            user = rootProject.gradlePostgresUsername
            password = rootProject.gradlePostgresPassword
        }
    }
}
```

As you can see, I've added the matcher to add the 'Entity' suffix to table POJO classes.
However, when I run jooqCodegen task I get the following error from Gradle:

```
build.gradle' line: 80

* What went wrong:
Execution failed for task ':test:jooqCodegen'.
> Value is null
```

Line 80 is the line containing 'pojoClass {'.
When I remove the strategy from the configuration, the task runs successfully and generates the code.
Please advise on what could be causing this issue.

### jOOQ Version

3.19.7

### Database product and version

PostgreSQL 12

### Java Version

21

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.3

**Comment by mvolf** [comment]
Thanks for the reply @lukaseder .
Of course, here's the stack trace:

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':test:jooqCodegen'.
        at org.gradle.api.internal.tasks.properties.DefaultTaskProperties.resolve(DefaultTaskProperties.java:85)
        at org.gradle.execution.plan.LocalTaskNode.resolveMutations(LocalTaskNode.java:231)
        at org.gradle.execution.plan.ResolveMutationsNode.doResolveMutations(ResolveMutationsNode.java:106)
        at org.gradle.execution.plan.ResolveMutationsNode.access$000(ResolveMutationsNode.java:31)
        at org.gradle.execution.plan.ResolveMutationsNode$1.run(ResolveMutationsNode.java:87)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
        at org.gradle.execution.plan.ResolveMutationsNode.execute(ResolveMutationsNode.java:83)
        at org.gradle.execution.plan.WorkNodeExecutor.execute(WorkNodeExecutor.java:27)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:331)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:318)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.lambda$execute$0(DefaultTaskExecutionGraph.java:314)
        at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:314)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
Caused by: java.lang.IllegalArgumentException: Value is null
        at org.gradle.internal.metaobject.BeanDynamicObject.<init>(BeanDynamicObject.java:105)
        at org.gradle.internal.metaobject.BeanDynamicObject.<init>(BeanDynamicObject.java:96)
        at org.gradle.internal.metaobject.DynamicObjectUtil.asDynamicObject(DynamicObjectUtil.java:28)
        at org.gradle.internal.extensibility.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:60)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:65)
        at build_6zby41y5233oyf2u0vl1v7zjd$_run_closure3$_closure11$_closure12$_closure14$_closure18$_closure19$_closure20.doCall$original(/home/mvolf/test/build.gradle:80)
        at build_6zby41y5233oyf2u0vl1v7zjd$_run_closure3$_closure11$_closure12$_closure14$_closure18$_closure19$_closure20.doCall(/home/mvolf/test/build.gradle)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at org.gradle.util.internal.ClosureBackedAction.execute(ClosureBackedAction.java:73)
        at org.gradle.util.internal.ConfigureUtil.configureTarget(ConfigureUtil.java:155)
        at org.gradle.util.internal.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.internal.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:167)
        at org.jooq.codegen.gradle.MetaExtensions$MatchersTableTypeListExtension.table(MetaExtensions.java:856)
        at org.jooq.codegen.gradle.MetaExtensions$MatchersTableTypeListExtension_Decorated.table(Unknown Source)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:541)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:218)
        at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:99)
        at org.gradle.internal.extensibility.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:38)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:65)
        at build_6zby41y5233oyf2u0vl1v7zjd$_run_closure3$_closure11$_closure12$_closure14$_closure18$_closure19.doCall$original(/home/mvolf/test/build.gradle:79)
        at build_6zby41y5233oyf2u0vl1v7zjd$_run_closure3$_closure11$_closure12$_closure14$_closure18$_closure19.doCall(/home/mvolf/test/build.gradle)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at org.gradle.util.internal.ClosureBackedAction.execute(ClosureBackedAction.java:73)
        at org.gradle.util.internal.ConfigureUtil.configureTarget(ConfigureUtil.java:155)
        at org.gradle.util.internal.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.internal.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:167)
        at org.jooq.codegen.gradle.MetaExtensions$MatchersExtension.tables(MetaExtensions.java:192)
        at org.jooq.codegen.gradle.MetaExtensions$MatchersExtension_Decorated.tables(Unknown Source)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:541)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:218)
        at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:99)
        at org.gradle.internal.extensibility.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:38)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:65)
        at build_6zby41y5233oyf2u0vl1v7zjd$_run_closure3$_closure11$_closure12$_closure14$_closure18.doCall$original(/home/mvolf/test/build.gradle:78)
        at build_6zby41y5233oyf2u0vl1v7zjd$_run_closure3$_closure11$_closure12$_closure14$_closure18.doCall(/home/mvolf/test/build.gradle)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at org.gradle.util.internal.ClosureBackedAction.execute(ClosureBackedAction.java:73)
        at org.gradle.util.internal.ConfigureUtil.configureTarget(ConfigureUtil.java:155)
        at org.gradle.util.internal.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.internal.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:167)
        at org.jooq.codegen.gradle.MetaExtensions$StrategyExtension.matchers(MetaExtensions.java:164)
        at org.jooq.codegen.gradle.MetaExtensions$StrategyExtension_Decorated.matchers(Unknown Source)
        at org.jooq.codegen.gradle.MetaExtensions$StrategyExtension_Decorated.matchers(Unknown Source)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:541)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:218)
        at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:99)
        at org.gradle.internal.extensibility.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:38)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:65)
        at build_6zby41y5233oyf2u0vl1v7zjd$_run_closure3$_closure11$_closure12$_closure14.doCall$original(/home/mvolf/test/build.gradle:77)
        at build_6zby41y5233oyf2u0vl1v7zjd$_run_closure3$_closure11$_closure12$_closure14.doCall(/home/mvolf/test/build.gradle)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at org.gradle.util.internal.ClosureBackedAction.execute(ClosureBackedAction.java:73)
        at org.gradle.util.internal.ConfigureUtil.configureTarget(ConfigureUtil.java:155)
        at org.gradle.util.internal.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.internal.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:167)
        at org.jooq.codegen.gradle.MetaExtensions$GeneratorExtension.strategy(MetaExtensions.java:130)
        at org.jooq.codegen.gradle.MetaExtensions$GeneratorExtension_Decorated.strategy(Unknown Source)
        at org.jooq.codegen.gradle.MetaExtensions$GeneratorExtension_Decorated.strategy(Unknown Source)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:541)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:218)
        at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:99)
        at org.gradle.internal.extensibility.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:38)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:65)
        at build_6zby41y5233oyf2u0vl1v7zjd$_run_closure3$_closure11$_closure12.doCall$original(/home/mvolf/test/build.gradle:76)
        at build_6zby41y5233oyf2u0vl1v7zjd$_run_closure3$_closure11$_closure12.doCall(/home/mvolf/test/build.gradle)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at org.gradle.util.internal.ClosureBackedAction.execute(ClosureBackedAction.java:73)
        at org.gradle.util.internal.ConfigureUtil.configureTarget(ConfigureUtil.java:155)
        at org.gradle.util.internal.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.internal.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:167)
        at org.jooq.codegen.gradle.MetaExtensions$ConfigurationExtension.generator(MetaExtensions.java:88)
        at org.jooq.codegen.gradle.MetaExtensions$ConfigurationExtension_Decorated.generator(Unknown Source)
        at org.jooq.codegen.gradle.MetaExtensions$ConfigurationExtension_Decorated.generator(Unknown Source)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:541)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:218)
        at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:99)
        at org.gradle.internal.extensibility.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:38)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:65)
        at build_6zby41y5233oyf2u0vl1v7zjd$_run_closure3$_closure11.doCall$original(/home/mvolf/test/build.gradle:75)
        at build_6zby41y5233oyf2u0vl1v7zjd$_run_closure3$_closure11.doCall(/home/mvolf/test/build.gradle)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at org.gradle.util.internal.ClosureBackedAction.execute(ClosureBackedAction.java:73)
        at org.gradle.util.internal.ConfigureUtil.configureTarget(ConfigureUtil.java:155)
        at org.gradle.util.internal.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.internal.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:167)
        at org.jooq.codegen.gradle.NamedConfiguration.executeAction(NamedConfiguration.java:134)
        at org.jooq.codegen.gradle.NamedConfiguration.getOutputDirectory(NamedConfiguration.java:103)
        at org.jooq.codegen.gradle.NamedConfiguration_Decorated.getOutputDirectory(Unknown Source)
        at org.jooq.codegen.gradle.CodegenTask.getOutputDirectory(CodegenTask.java:125)
        at org.jooq.codegen.gradle.CodegenTask_Decorated.getOutputDirectory(Unknown Source)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at org.gradle.internal.reflect.annotations.impl.DefaultPropertyAnnotationMetadata.getPropertyValue(DefaultPropertyAnnotationMetadata.java:97)
        at org.gradle.internal.properties.annotations.DefaultTypeMetadataStore$DefaultPropertyMetadata.getPropertyValue(DefaultTypeMetadataStore.java:284)
        at org.gradle.internal.properties.bean.DefaultPropertyWalker$1.lambda$visitLeaf$0(DefaultPropertyWalker.java:90)
        at org.gradle.internal.deprecation.DeprecationLogger.whileDisabled(DeprecationLogger.java:259)
        at org.gradle.internal.properties.bean.DefaultPropertyWalker$CachedPropertyValue.lambda$new$0(DefaultPropertyWalker.java:107)
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181)
        at org.gradle.internal.properties.bean.DefaultPropertyWalker$CachedPropertyValue.call(DefaultPropertyWalker.java:149)
        at org.gradle.api.internal.tasks.properties.OutputUnpacker.resolveOutputFilePropertySpecs(OutputUnpacker.java:113)
        at org.gradle.api.internal.tasks.properties.OutputUnpacker.visitOutputFileProperty(OutputUnpacker.java:86)
        at org.gradle.api.internal.tasks.properties.CompositePropertyVisitor.visitOutputFileProperty(CompositePropertyVisitor.java:73)
        at org.gradle.api.internal.tasks.properties.annotations.AbstractOutputPropertyAnnotationHandler.visitPropertyValue(AbstractOutputPropertyAnnotationHandler.java:46)
        at org.gradle.internal.properties.bean.DefaultPropertyWalker$1.visitLeaf(DefaultPropertyWalker.java:95)
        at org.gradle.internal.properties.annotations.AbstractTypeMetadataWalker$InstanceTypeMetadataWalker.walkLeaf(AbstractTypeMetadataWalker.java:202)
        at org.gradle.internal.properties.annotations.AbstractTypeMetadataWalker$InstanceTypeMetadataWalker.walkLeaf(AbstractTypeMetadataWalker.java:118)
        at org.gradle.internal.properties.annotations.AbstractTypeMetadataWalker.lambda$walkChildren$4(AbstractTypeMetadataWalker.java:87)
        at org.gradle.internal.properties.annotations.AbstractTypeMetadataWalker.walkChildren(AbstractTypeMetadataWalker.java:83)
        at org.gradle.internal.properties.annotations.AbstractTypeMetadataWalker.walk(AbstractTypeMetadataWalker.java:53)
        at org.gradle.internal.properties.bean.DefaultPropertyWalker.visitProperties(DefaultPropertyWalker.java:65)
        at org.gradle.api.internal.tasks.TaskPropertyUtils.visitAnnotatedProperties(TaskPropertyUtils.java:58)
        at org.gradle.api.internal.tasks.TaskPropertyUtils.visitProperties(TaskPropertyUtils.java:45)
        at org.gradle.api.internal.tasks.properties.DefaultTaskProperties.resolve(DefaultTaskProperties.java:75)
        at org.gradle.execution.plan.LocalTaskNode.resolveMutations(LocalTaskNode.java:231)
        at org.gradle.execution.plan.ResolveMutationsNode.doResolveMutations(ResolveMutationsNode.java:106)
        at org.gradle.execution.plan.ResolveMutationsNode.access$000(ResolveMutationsNode.java:31)
        at org.gradle.execution.plan.ResolveMutationsNode$1.run(ResolveMutationsNode.java:87)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
        at org.gradle.execution.plan.ResolveMutationsNode.execute(ResolveMutationsNode.java:83)
        at org.gradle.execution.plan.WorkNodeExecutor.execute(WorkNodeExecutor.java:27)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:331)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:318)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.lambda$execute$0(DefaultTaskExecutionGraph.java:314)
        at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:314)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)

```

**Comment by lukaseder** [comment]
Hm, what if you did this, instead? `transform = MatcherTransformType.PASCAL` (assuming you're using kotlin, not groovy)?

**Comment by mvolf** [comment]
Thanks for the suggestion. I just tried that and get the same error/stack trace.

**Comment by mvolf** [comment]
@lukaseder Just wanted to check if we have a confirmation that this is a defect? It's blocking me from migrating from third party generator to the stock one and would mean a lot to me to know the status of this issue, so I can plan accordingly.
Thanks for all the support and I apologise for bothering you.

**Comment by lukaseder** [comment]
@mvolf I will be able to confirm/deny this by next week. In the meantime, you could try:

- Debugging the gradle plugin
- Avoiding the gradle plugin and use programmatic standalone code generation configuration (works well in gradle)
- Using the maven plugin for the time being
- Using the programmatic generator strategy instead of the configurative one: https://www.jooq.org/doc/latest/manual/code-generation/codegen-generatorstrategy/

**Comment by mvolf** [comment]
@lukaseder Thanks for the reply and suggestions. I'll take a look at some of the workarounds you mentioned while waiting for the final conclusion regarding this issue.

**Comment by mvolf** [comment]
Hi @lukaseder . I've tried implementing programmatic generator strategy. Here's what I did:

```
jooq {
    configuration {
        generator {
            name = 'org.jooq.codegen.DefaultGenerator'
            strategy {
                name = "com.test.JooqGeneratorStrategy"
                java = """
                        package com.test;

                        import org.jooq.codegen.DefaultGeneratorStrategy;
                        import org.jooq.meta.Definition;
                        import java.util.Objects;

                        public class JooqGeneratorStrategy extends DefaultGeneratorStrategy {
                            @Override
                            public String getJavaClassName(Definition definition, Mode mode) {
                                if(Objects.equals(Mode.POJO, mode)) {
                                    return super.getJavaClassName(definition, mode) + "Entity";
                                } else {
                                    return super.getJavaClassName(definition, mode);
                                }
                            }
                        }
                """
            }
            database {
                name = 'org.jooq.meta.postgres.PostgresDatabase'
                inputSchema = 'public'
                outputSchemaToDefault = true
                forcedTypes {
                    forcedType {
                        name = 'varchar'
                        expression = '.*'
                        types = 'JSONB?'
                    }
                    forcedType {
                        name = 'varchar'
                        expression = '.*'
                        types = 'INET'
                    }
                }
            }
            generate {
                pojosEqualsAndHashCode = true
                instanceFields = true
                pojos = true
                deprecationOnUnknownTypes = false
                relations = true
                fluentSetters = true
                daos = true
            }
            target {
                packageName = 'com.test'
                directory = 'src/main/kotlin'
                clean = false
            }
        }
        jdbc {
            driver = rootProject.gradlePostgresDriver
            url = gradlePostgresJdbc
            user = rootProject.gradlePostgresUsername
            password = rootProject.gradlePostgresPassword
        }
    }
}
```

Unfortunately, this also fails with several errors.

The first one is:
```
org.xml.sax.SAXParseException; lineNumber: 15; columnNumber: 19; cvc-complex-type.2.4.d: Invalid content was found starting with element 'java'. No child element is expected at this point.
```

After that I get several compilation errors for the embedded Java code and it seems like all originate from this issue:
```
Caused by: org.jooq.tools.reflect.ReflectException: Compilation error: com/test/JooqGeneratorStrategy.java:3: error: package org.jooq.codegen does not exist import org.jooq.codegen.DefaultGeneratorStrategy;
```

I'm not sure what's causing this since I have all the necessary plugins (org.jooq.jooq-codegen-gradle) and dependencies (org.jooq:jooq, org.jooq:jooq-codegen, org.jooq:jooq-meta) defined in gradle.

**Comment by lukaseder** [comment]
> org.xml.sax.SAXParseException; lineNumber: 15; columnNumber: 19; cvc-complex-type.2.4.d: Invalid content was found starting with element 'java'. No child element is expected at this point.

I don't see how this could happen with the jOOQ code generation plugin. Are you using the official one, or are you using any third party plugin?

> After that I get several compilation errors for the embedded Java code and it seems like all originate from these two issues:

This looks like your various artifact versions aren't in sync.

Please provide your *complete* `build.gradle.kts` or `build.gradle` file.

**Comment by mvolf** [comment]
Thanks for your reply.

I am using the official generation plugin, of course. Please note that this first warning only occurs when I add the "java" tag in strategy for embedded Java code.

I doubt that jOOQ related artifact versions aren't in sync, since the version is configured in a variable and shared for all plugins/libraries, but maybe I'm missing something.

My project consists of several subprojects and most of the subprojects have their own database schema, hence they require separate generator configuration, I'll attach the root `build.gradle` file which contains common/shared dependencies, values and configuration and an additional `build.gradle` file from one of the subprojects. The files have been renamed as `root_build.gradle` and `subproject_build.gradle` only for purposes of this upload:  [gradle.zip](https://github.com/jOOQ/jOOQ/files/15033756/gradle.zip)

**Comment by lukaseder** [comment]
Thanks for your patience. I can see now why the `pojoClass` attribute didn't work. It is missing from the generated `org.jooq.codegen.gradle.MetaExtensions.MatchersTableTypeExtension` class.

So, this rules out other hypotheses that I've had as you've confirmed. Will look into this right away.

**Comment by mvolf** [comment]
Thanks for looking into it @lukaseder .

**Comment by mvolf** [comment]
Great, thank you!

**Comment by lukaseder** [comment]
I can reproduce a warning:

> org.xml.sax.SAXParseException; lineNumber: 9; columnNumber: 19; cvc-complex-type.2.4.d: Invalid content was found starting with element 'java'. No child element is expected at this point.

This seems to be cosmetic only. I've created an issue for this (it also happens with `matchers`, once this issue is fixed):

- https://github.com/jOOQ/jOOQ/issues/16576

But no error with the `java` approach, assuming that this extra dependency is added:

```
dependencies {
    // ...
    jooqCodegen("${group}:jooq-codegen:${version}")
}
```
