### ISSUE TITLE
Update using multi-column set clause with DSL.row and custom type logs warn on deprecated static type registry

### ISSUE THREAD

**Issue by runeflobakk** [jOOQ/jOOQ#16627]
### Expected behavior

Update using multi-column set clause executed without a warning.

### Actual behavior

The update is performed ay-OK, but jOOQ also warns with a reference to issue #15286 

```
WARN  o.j.impl.DefaultDataType.getDataType - Static type registry     : The deprecated static type registry was being accessed for a non-built-in data type: clob /* java.net.URI */.

It is strongly recommended not looking up DataType<T> references from Class<T> references by
relying on the internal static type registry. For example, avoid calling DSL.val(Object) or
DSL.val(Object, Class), and call DSL.val(Object, DataType), providing an explicit DataType
reference to jOOQ if your DataType uses a Converter or a Binding. If you think jOOQ should
be able to infer your user type in your particular query, please report a bug here:
https://jooq.org/bug

See https://github.com/jOOQ/jOOQ/issues/15286 for more details.

org.jooq.impl.DefaultDataType$DiscouragedStaticTypeRegistryUsage: null
	at org.jooq.impl.DefaultDataType.check(DefaultDataType.java:842)
	at org.jooq.impl.Val.accept(Val.java:192)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:731)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:381)
	at org.jooq.impl.QueryPartCollectionView.acceptElement(QueryPartCollectionView.java:256)
	at org.jooq.impl.QueryPartCollectionView.accept(QueryPartCollectionView.java:226)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:731)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:381)
	at org.jooq.impl.AbstractRow.accept(AbstractRow.java:261)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:731)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:381)
	at org.jooq.impl.FieldMapForUpdate.acceptAssignmentClause(FieldMapForUpdate.java:316)
	at org.jooq.impl.FieldMapForUpdate.accept(FieldMapForUpdate.java:199)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:731)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:381)
	at org.jooq.impl.UpdateQueryImpl.accept2(UpdateQueryImpl.java:772)
	at org.jooq.impl.UpdateQueryImpl.accept1(UpdateQueryImpl.java:633)
	at org.jooq.impl.AbstractDMLQuery.accept0(AbstractDMLQuery.java:671)
	at org.jooq.impl.UpdateQueryImpl.accept(UpdateQueryImpl.java:590)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:731)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:381)
	at org.jooq.impl.DefaultRenderContext$Rendered.rendered(DefaultRenderContext.java:1078)
	at org.jooq.impl.AbstractQuery.getSQL0(AbstractQuery.java:498)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:303)
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
...
```

### Steps to reproduce the problem

The following form causes the warning:

```java
dslContext.transaction(config -> using(config)
    .update(TABLE)
    .set(DSL.row(TABLE.TIMESTAMP, TABLE.URL), DSL.row(OffsetDateTime.now(), URI.create("url")))
    .where(..)
    .execute());
```

The type of `TABLE.URL` is `TableField<TableRecord, URI>`.
I also use `DSL.row()` other places, e.g. inserting rows including URIs using `.valuesOfRows(..)`, but I don't get any warning here.

The workaround in my case was to change to use two `.set(Field<T>, T)` invocations instead, which is all fine, and probably for the better anyway.

### jOOQ Version

3.19.7 (all versions >= 3.19.0)

### Database product and version

PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit

### Java Version

OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.3

**Comment by lukaseder** [comment]
Thanks a lot for your report. I will look into this soon. The workaround is the same as elsewhere: Explicitly wrap bind values in `DSL.val(T, DataType<T>)`, which helps associate your data type binding with the bind value explicitly.

Though, in this case, things should work automatically, of course.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.9 (https://github.com/jOOQ/jOOQ/issues/16672)
- 3.18.16 (https://github.com/jOOQ/jOOQ/issues/16673)
- 3.17.25 (https://github.com/jOOQ/jOOQ/issues/16674)
