### ISSUE TITLE
BlobBinding and ClobBinding should fall back to byte[] and String binding also in HANA

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#16646]
This was implemented in jOOQ 3.19.0 without backport:

- https://github.com/jOOQ/jOOQ/issues/14803

HANA is missing. It also doesn't support `Blob` and `Clob` bindings, see e.g. this stack trace:

```
org.jooq.exception.DataAccessException: SQL [null]; Error while writing value at JDBC bind index: 2
	at org.jooq_3.20.0-SNAPSHOT.HANA.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3621)
	at org.jooq.impl.Tools.translate(Tools.java:3597)
	at org.jooq.impl.AbstractBindContext.bindValue(AbstractBindContext.java:77)
	at org.jooq.impl.Val.accept(Val.java:250)
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:253)
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:68)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:382)
	at org.jooq.impl.QueryPartCollectionView.acceptElement(QueryPartCollectionView.java:251)
	at org.jooq.impl.QueryPartCollectionView.accept(QueryPartCollectionView.java:221)
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:253)
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:68)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:382)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:344)
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
	at org.jooq.test.all.testcases.DataTypeTests.testLargeLOBsWithClobBinding0(DataTypeTests.java:2140)
	at org.jooq.test.all.testcases.DataTypeTests.testLargeLOBsWithClobBinding(DataTypeTests.java:2117)
	at org.jooq.test.jOOQAbstractTest.testLargeLOBsWithClobBinding(jOOQAbstractTest.java:5264)
Caused by: java.sql.SQLException: Error while writing value at JDBC bind index: 2
	at org.jooq.impl.DefaultBindContext.bindValue0(DefaultBindContext.java:77)
	at org.jooq.impl.AbstractBindContext.bindValue(AbstractBindContext.java:74)
	... 44 more
Caused by: com.sap.db.jdbc.exceptions.SQLFeatureNotSupportedExceptionSapDB: Method createClob() of Connection is not supported.
	at com.sap.db.jdbc.exceptions.SQLExceptionSapDB._newInstance(SQLExceptionSapDB.java:150)
	at com.sap.db.jdbc.exceptions.SQLExceptionSapDB.newInstance(SQLExceptionSapDB.java:27)
	at com.sap.db.jdbc.ConnectionSapDB._getUnsupportedMethodException(ConnectionSapDB.java:2343)
	at com.sap.db.jdbc.ConnectionSapDB.createClob(ConnectionSapDB.java:1109)
	at org.jooq.tools.jdbc.DefaultConnection.createClob(DefaultConnection.java:274)
	at org.jooq.tools.jdbc.DefaultConnection.createClob(DefaultConnection.java:274)
	at org.jooq.impl.ClobBinding.newClob(ClobBinding.java:222)
	at org.jooq.impl.ClobBinding.set(ClobBinding.java:117)
	at org.jooq.impl.DefaultBindContext.bindValue0(DefaultBindContext.java:65)
	... 45 more
```

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.9 (https://github.com/jOOQ/jOOQ/issues/16647)
