### ISSUE TITLE
SQLite "Cannot parse or interpret sql for table" error with both unique columns and foreign key constraints

### ISSUE THREAD

**Issue by vptp** [jOOQ/jOOQ#16675]
### Expected behavior

Code generation maven plugin to run successfully without logging any errors.
Generate unique keys for all UNIQUE columns.
Generate `DAO.fetchOneByX` functions for all UNIQUE columns.

### Actual behavior

Error logged during code generation: 
```
[INFO] Cannot parse or interpret sql for table test2: CREATE TABLE test2
...
org.jooq.exception.DataDefinitionException: TableImpl does not exist: test
```
Unique keys missing for some tables.
`Test2Dao.fetchOneByCd` function generated.

### Steps to reproduce the problem

[MCVE](https://github.com/vptp/jOOQ-mcve) `jOOQ-mcve-kotlin-sqlite` directory

The problem appears to require the combination of columns with UNIQUE constraints and columns with FOREIGN KEY constraints in the same table.
It appears that while processing the unique keys for each table, parsing the foreign keys in the SQL causes an exception which results in aborting processing unique keys. Hence the DAO.fetchOneByX method is not generated.

jOOQ 3.14.16 generates the DAO.fetchOneByX as expected. jOOQ versions 3.15.0 to 3.19.8 omit the DAO.fetchOneByX in some cases.

### jOOQ Version

jOOQ 3.19.8

### Database product and version

SQLite 3.40.1.0

### Java Version

openjdk version "17.0.10" 2024-01-16

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.xerial:sqlite-jdbc:3.40.1.0

**Comment by lukaseder** [comment]
Thanks a lot for your report. I can reproduce the problem. Will look into this right away.

**Comment by lukaseder** [comment]
I see, we're interpreting meta DDL SQL table by table, with eager foreign key resolution. But the tables are ordered alphabetically, not in their key order (which can have cycles), so we should delay the foreign key checks, e.g. using `Settings.interpreterDelayForeignKeyDeclarations`

- #9508

**Comment by lukaseder** [comment]
It doesn't happen without the unique constraint, because that particular code path that interprets all the DDL is only invoked when looking up unique constraints.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.9 (https://github.com/jOOQ/jOOQ/issues/16676)
- 3.18.16 (https://github.com/jOOQ/jOOQ/issues/16677)
- 3.17.25 (https://github.com/jOOQ/jOOQ/issues/16678)

**Comment by lukaseder** [comment]
I've added more integration tests. There seem to be more cases where the current logic doesn't work.

**Comment by ydeng11** [comment]
Hi Dumb question - How can I set up InterpreterDelayForeignKeyDeclarations in the pom.xml? The jooq website shows this can be set in the code but I don't find an example about interpreter setting for maven. Thx!

**Comment by lukaseder** [comment]
It's a `Settings` flag:
https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/settings-interpreter/

The parent section talks about `Settings` in general:
https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/

**Comment by ydeng11** [comment]
> It's a `Settings` flag: https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/settings-interpreter/
> 
> The parent section talks about `Settings` in general: https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/

Thx for the answer. I'm using Quarkus so I normally just inject DslContext directly. Wonder if there is anyway to set up in maven pom.xml.

**Comment by blazmrak** [comment]
@lukaseder I'm losing my mind here... I'm running the generator standalone and am specifying settings via `-Dorg.jooq.settings`, (which I'm guessing is the only way to do it?) but I get the message ` Loading system wide default settings via org.jooq.settings system properties has been deprecated. Please use explicit Settings in your Configuration references, instead.` and a NPE

```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.jooq.impl.DefaultConfiguration.set(DefaultConfiguration.java:1838)
        at org.jooq.impl.DefaultConfiguration.<init>(DefaultConfiguration.java:352)
        at org.jooq.impl.DefaultConfiguration.<init>(DefaultConfiguration.java:191)
        at org.jooq.impl.DefaultConfiguration.<init>(DefaultConfiguration.java:180)
        at org.jooq.impl.DefaultConfiguration.<init>(DefaultConfiguration.java:173)
        at org.jooq.impl.DSL.dsl(DSL.java:38527)
        at org.jooq.impl.DSL.selectOne(DSL.java:5147)
        at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:276)
        at org.jooq.codegen.GenerationTool.run(GenerationTool.java:254)
        at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:249)
        at org.jooq.codegen.GenerationTool.main(GenerationTool.java:221)
Caused by: org.jooq.exception.ConfigurationException: Error while opening file
        at org.jooq.util.jaxb.tools.MiniJAXB.unmarshal(MiniJAXB.java:175)
        at org.jooq.conf.SettingsTools.<clinit>(SettingsTools.java:92)
        ... 11 more
Caused by: org.jooq.exception.ConfigurationException: Error while reading xml
        at org.jooq.util.jaxb.tools.MiniJAXB.unmarshal0(MiniJAXB.java:188)
        at org.jooq.util.jaxb.tools.MiniJAXB.unmarshal(MiniJAXB.java:172)
        ... 12 more
        at org.jooq.conf.SettingsTools.<clinit>(SettingsTools.java:92)
        ... 11 more
Caused by: org.jooq.exception.ConfigurationException: Error while reading xml
        at org.jooq.util.jaxb.tools.MiniJAXB.unmarshal0(MiniJAXB.java:188)
        at org.jooq.util.jaxb.tools.MiniJAXB.unmarshal(MiniJAXB.java:172)
        ... 12 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.jooq.conf.Settings.clone()" because "settings" is null
        at org.jooq.conf.SettingsTools.clone(SettingsTools.java:375)
        at org.jooq.conf.SettingsTools.defaultSettings(SettingsTools.java:368)
        at org.jooq.impl.DefaultConfiguration.set(DefaultConfiguration.java:1838)
        at org.jooq.impl.DefaultConfiguration.<init>(DefaultConfiguration.java:352)
        at org.jooq.impl.DefaultConfiguration.<init>(DefaultConfiguration.java:191)
        at org.jooq.impl.DefaultConfiguration.<init>(DefaultConfiguration.java:180)
        at org.jooq.impl.DefaultConfiguration.<init>(DefaultConfiguration.java:173)
        at org.jooq.impl.InternalConfiguration.<init>(InternalConfiguration.java:46)
        at org.jooq.impl.Tools.lambda$static$76(Tools.java:4042)
        at org.jooq.impl.Lazy.get(Lazy.java:83)
        at org.jooq.impl.Internal.lambda$static$0(Internal.java:1122)
        at org.jooq.impl.Lazy.get(Lazy.java:83)
        at org.jooq.impl.Internal.converterContext(Internal.java:1125)
        at org.jooq.impl.Convert.convert0(Convert.java:547)
        at org.jooq.impl.Convert.convert(Convert.java:622)
        at org.jooq.impl.Internal.convert(Internal.java:1227)
        at org.jooq.tools.Convert.convert(Convert.java:271)
        at org.jooq.util.jaxb.tools.MiniJAXB.unmarshal1(MiniJAXB.java:319)
        at org.jooq.util.jaxb.tools.MiniJAXB.unmarshal0(MiniJAXB.java:240)
        at org.jooq.util.jaxb.tools.MiniJAXB.unmarshal0(MiniJAXB.java:184)
        ... 13 more
```

What am I doing wrong here? I'm on the latest version - 3.20.9

**Comment by lukaseder** [comment]
@blazmrak Please create a new issue and provide a complete reproducer. Please don't comment on random, unrelated issues as this does not allow for tracking support cases and/or bugs.
