### ISSUE TITLE
Postgres enum arrays and R2DBC.

### ISSUE THREAD

**Issue by spheenik** [jOOQ/jOOQ#16684]
### Expected behavior

Querying a record which contains an enum array in R2DBC works.

### Actual behavior

Querying a record which contains an enum array using R2DBC fails with 

```
...
Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class [Ljava.lang.Object; (java.lang.String and [Ljava.lang.Object; are in module java.base of loader 'bootstrap')
	at org.jooq.impl.R2DBC$R2DBCResultSet.getArray(R2DBC.java:1311)
	at org.jooq.impl.DefaultBinding$DefaultArrayBinding.pgGetArray(DefaultBinding.java:1465)
	at org.jooq.impl.DefaultBinding$DefaultArrayBinding.get0(DefaultBinding.java:1419)
	at org.jooq.impl.DefaultBinding$DefaultArrayBinding.get0(DefaultBinding.java:1280)
	at org.jooq.impl.DefaultBinding$InternalBinding.get(DefaultBinding.java:1129)
	at org.jooq.impl.CursorImpl$CursorRecordInitialiser.setValue(CursorImpl.java:1582)
```

I've read the issue about the R2DBC restrictions here: 
https://github.com/jOOQ/jOOQ/issues/13590

It mentions an issue with enum arrays in R2DBC:
https://github.com/pgjdbc/r2dbc-postgresql/issues/391

But this issue has long been resolved.

### Steps to reproduce the problem

unfortunately none atm

### jOOQ Version

3.19.7 (OSS)

### Database product and version

Postgres 16.2

### Java Version

OpenJDK 17

### JDBC / R2DBC driver name and version (include name if unofficial driver)

postgresql 42.6.2 // r2dbc-postgresql 1.0.4.RELEASE

**Comment by lukaseder** [comment]
Thanks for your report. Neither enum types nor arrays are currently explicitly supported, see the list of known limitations here:

- https://github.com/jOOQ/jOOQ/issues/13590

**Comment by spheenik** [comment]
Thanks Lukas.
We settled on using JDBC for the affected queries for the time being, and will patiently wait for your fix.

**Comment by k163377** [comment]
I've discovered a workaround for `PostgreSQL` and would like to share it.
I apologize that the sample code is in `Kotlin`, but you can write it almost identically in `Java`.

By manually registering a `Codec` like the following, it seemed possible to process it without errors.

```kotlin
import io.r2dbc.postgresql.PostgresqlConnectionFactory
import io.r2dbc.postgresql.PostgresqlConnectionFactoryProvider
import io.r2dbc.postgresql.codec.EnumCodec
import io.r2dbc.spi.ConnectionFactoryOptions

val factoryOptions = PostgresqlConnectionFactoryProvider
    .builder(ConnectionFactoryOptions.parse(url))
    .codecRegistrar(
        EnumCodec.builder()
            .withEnum(
                YourEnum.FOO.getName(),
                YourEnum::class.java
            )
            .build()
    )
    .build()

val connectionFactory = PostgresqlConnectionFactory(factoryOptions)
```

Additionally, you can collect the necessary information for `codecRegistrar` from the generation results as follows:

```kotlin
val schemas: List<Schema> = listOf(...)
val enumArrayCols = schemas.flatMap { schema ->
    schema.tables.flatMap { table ->
        table.fields().mapNotNull { field ->
            field.takeIf {
                it.type.isArray && it.type.componentType.isEnum
            }
        }
    }
}
val defs: List<Pair<String, Class<Enum<*>>>> = enumArrayCols.map { field ->
    @Suppress("UNCHECKED_CAST")
    val type = field.type.componentType as Class<Enum<*>>
    val name = type
        .getEnumConstants()
        .first()
        .let { (it as EnumType).name }
    name!! to type
}
```

**Comment by lukaseder** [comment]
Thanks for documenting this here, @k163377

**Comment by lukaseder** [comment]
I'm trying to wrap my head around how jOOQ could help here, but I fail to see how a reasonable auto-registration of such codecs could work, given that jOOQ typically works with a `io.r2dbc.spi.Connection`, not a `ConnectionFactory`, let alone the pg specific one. There's no "standard" codec API, the `io.r2dbc.postgresql.codec.Codec` type is pg specific.

Of course, we can render explicit casts and bind the enum literals as strings as a workaround. We're doing this kind of emulation all the time with JDBC, when a data type isn't supported.

**Comment by lukaseder** [comment]
Binding the array might be more tricky than reading it. This issue here will only address reading the array. Binding will be dealt with in a separate issue:

- https://github.com/jOOQ/jOOQ/issues/19629

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.21.0
- 3.20.12 (https://github.com/jOOQ/jOOQ/issues/19630)
- 3.19.31 (https://github.com/jOOQ/jOOQ/issues/19631)
- 3.18.38 (https://github.com/jOOQ/jOOQ/issues/19632)

**Comment by lukaseder** [comment]
While I didn't add a regression test for the user-defined codec workaround illustrated here:

- https://github.com/jOOQ/jOOQ/issues/16684#issuecomment-3660413815

I do believe that this fix is compatible with any pre-existing codecs. If a codec is present for the type, then this fix's auto-conversion is simply skipped.
