### ISSUE TITLE
Error in CockroachDBDatabase when running SHOW INDEXES for table valued function

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#16686]
There's a flaky test in our CockroachDB integration test since a recent CockroachDB upgrade, where we run a `SHOW INDEXES` statement for a table valued function:

```
java.lang.RuntimeException: org.jooq.exception.DataAccessException: SQL [show indexes from public.f6078]; ERROR: relation "public.f6078" does not exist
	at org.jooq.meta.AbstractDatabase.onError(AbstractDatabase.java:4362)
	at org.jooq.meta.AbstractDatabase.getIndexes(AbstractDatabase.java:3124)
	at org.jooq.test.all.testcases.MetaDataTests.lambda$testCodegenDatabase$80(MetaDataTests.java:1904)
	at org.jooq.impl.DefaultDSLContext.lambda$connection$12(DefaultDSLContext.java:696)
	at org.jooq.impl.DefaultDSLContext.connectionResult(DefaultDSLContext.java:657)
	at org.jooq.impl.DefaultDSLContext.connection(DefaultDSLContext.java:695)
	at org.jooq.test.all.testcases.MetaDataTests.testCodegenDatabase(MetaDataTests.java:1857)
```

Probably a race condition of some sort in the test. In any case, we shouldn't run this statement for table valued functions.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.9 (https://github.com/jOOQ/jOOQ/issues/16687)
- 3.18.16 (https://github.com/jOOQ/jOOQ/issues/16688)
- 3.17.25 (https://github.com/jOOQ/jOOQ/issues/16689)
