### ISSUE TITLE
Settings.transformPatternsUnnecessaryScalarSubquery produces wrong SQL when subquery column is aliased

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#16702]
This test fails:

```sql
assertEquals(
    asList(1),
    ctx.fetchValues(ctx.select(when(condition("1 = 0"), 2).else_(field(selectOne()))))
);
```

From the logs:

```
Pattern replacement      : [select case when (1 = 0) then 2 else (select 1 "one") end] => [select case when (1 = 0) then 2 else "one" end]
Executing query          : select case when (1 = 0) then cast(? as int) else "one" end -- SQL rendered with a free trial version of jOOQ 3.20.0-SNAPSHOT
-> with bind values      : select case when (1 = 0) then 2 else "one" end
prepareStatement         : select case when (1 = 0) then cast(? as int) else "one" end -- SQL rendered with a free trial version of jOOQ 3.20.0-SNAPSHOT
```

The exception being:

```
org.jooq.exception.DataAccessException: SQL [select case when (1 = 0) then cast(? as int) else "one" end -- SQL rendered with a free trial version of jOOQ 3.20.0-SNAPSHOT]; Column "one" not found; SQL statement:
select case when (1 = 0) then cast(? as int) else "one" end -- SQL rendered with a free trial version of jOOQ 3.20.0-SNAPSHOT [42122-224]
	at org.jooq_3.20.0-SNAPSHOT.H2.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3621)
	at org.jooq.impl.Tools.translate(Tools.java:3597)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:827)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:362)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:263)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:3212)
	at org.jooq.impl.Tools.attach(Tools.java:1689)
	at org.jooq.impl.DefaultDSLContext.fetch(DefaultDSLContext.java:4986)
	at org.jooq.impl.DefaultDSLContext.fetchValues(DefaultDSLContext.java:5083)
	at org.jooq.test.all.testcases.TransformationTests.lambda$94(TransformationTests.java:698)
	at org.jooq.test.all.testcases.TransformationTests.lambda$233(TransformationTests.java:1487)
	at org.jooq.test.all.testcases.TransformationTests.assertTransformPatterns(TransformationTests.java:1524)
	at org.jooq.test.all.testcases.TransformationTests.assertTransformPatterns(TransformationTests.java:1486)
	at org.jooq.test.all.testcases.TransformationTests.testTransformPatternsUnnecessaryScalarSubquery(TransformationTests.java:676)
	at org.jooq.test.jOOQAbstractTest.testTransformPatternsUnnecessaryScalarSubquery(jOOQAbstractTest.java:13397)
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "one" not found; SQL statement:
select case when (1 = 0) then cast(? as int) else "one" end -- SQL rendered with a free trial version of jOOQ 3.20.0-SNAPSHOT [42122-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
```

Instead of this replacement:

```
[select case when (1 = 0) then 2 else (select 1 "one") end] => [select case when (1 = 0) then 2 else "one" end]
```

We should produce this:

```
[select case when (1 = 0) then 2 else (select 1 "one") end] => [select case when (1 = 0) then 2 else 1 end]
```

This doesn't happen if we project the subquery directly:

```java
assertEquals(
    asList(1),
    ctx.fetchValues(ctx.select(field(selectOne())))
);
```

Here, we get the correct result:

```
[select (select 1 "one")] => [select 1 "one"]
```

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.9 (https://github.com/jOOQ/jOOQ/issues/16703)
- 3.18.16 (https://github.com/jOOQ/jOOQ/issues/16704)

The feature hasn't been available in jOOQ 3.17 yet
