### ISSUE TITLE
DML ORDER BY .. LIMIT emulation shouldn't repeat WHERE predicate

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#16733]
When emulating the DML `ORDER BY .. LIMIT` clauses, the `WHERE` predicate gets repeated:

```java
ctx.update(T_BOOK)
   .set(T_BOOK.TITLE, "abc")
   .where(T_BOOK.ID.eq(5))
   .limit(1)
   .execute();
```

Produces, in PostgreSQL:

```sql
update "public"."t_book"
set
  "title" = 'abc'
where (
  "public"."t_book"."id" in (
    select "public"."t_book"."id"
    from "public"."t_book"
    where "public"."t_book"."id" = 5
    fetch next 1 rows only
  )
  and "public"."t_book"."id" = 5 -- Unnecessary
)
```

This is probably a regression caused by any of these many recent improvements:

- #13425
- #16631
- #16632
- #16633

And as such, it affects only jOOQ 3.20

**Comment by lukaseder** [comment]
Indeed a 3.20 regression only. In 3.19, the query renders:

```sql
update "public"."t_book"
set
  "title" = 'abc'
where "public"."t_book"."id" in (
  select "public"."t_book"."id"
  from "public"."t_book"
  where "public"."t_book"."id" = 5
  fetch next 1 rows only
)
```

**Comment by lukaseder** [comment]
While the predicate wasn't necessary in the example given, there's another example of a query like this:

```java
create().update(TBook())
        .set(TBook_TITLE(), concat(TAuthor_FIRST_NAME(), inline(" "), TAuthor_LAST_NAME(), inline(": "), TBook_TITLE()))
        .from(TAuthor())
        .where(TBook_AUTHOR_ID().eq(TAuthor_ID()))
        .orderBy(TBook_ID())
        .limit(2)
        .execute());
```

Which now renders this query:

```sql
update "TEST"."T_BOOK"
set
  "TEST"."T_BOOK"."TITLE" = (((("TEST"."T_AUTHOR"."FIRST_NAME" || ' ') || "TEST"."T_AUTHOR"."LAST_NAME") || ': ') || "TEST"."T_BOOK"."TITLE")
from "TEST"."T_AUTHOR" -- cartesian product!
where "TEST"."T_BOOK"."ID" in (
  select "TEST"."T_BOOK"."ID"
  from "TEST"."T_BOOK", "TEST"."T_AUTHOR"
  where "TEST"."T_BOOK"."AUTHOR_ID" = "TEST"."T_AUTHOR"."ID"
  order by "TEST"."T_BOOK"."ID"
  fetch next 2 rows only
)
```

Instead of this one:

```sql
update "TEST"."T_BOOK"
set
  "TEST"."T_BOOK"."TITLE" = (((("TEST"."T_AUTHOR"."FIRST_NAME" || ' ') || "TEST"."T_AUTHOR"."LAST_NAME") || ': ') || "TEST"."T_BOOK"."TITLE")
from "TEST"."T_AUTHOR"
where (
  "TEST"."T_BOOK"."ID" in (
    select "TEST"."T_BOOK"."ID"
    from "TEST"."T_BOOK", "TEST"."T_AUTHOR"
    where "TEST"."T_BOOK"."AUTHOR_ID" = "TEST"."T_AUTHOR"."ID"
    order by "TEST"."T_BOOK"."ID"
    fetch next 2 rows only
  )
  and "TEST"."T_BOOK"."AUTHOR_ID" = "TEST"."T_AUTHOR"."ID"
)
```

In other words, in the presence of a `FROM` clause, the repetition of predicates is clearly necessary!

Otherwise, we'll get an error like this, at least in Oracle, which detects this case:

```
org.jooq.exception.DataAccessException: SQL [update "TEST"."T_BOOK" set "TEST"."T_BOOK"."TITLE" = (((("TEST"."T_AUTHOR"."FIRST_NAME" || ' ') || "TEST"."T_AUTHOR"."LAST_NAME") || ': ') || "TEST"."T_BOOK"."TITLE") from "TEST"."T_AUTHOR" where "TEST"."T_BOOK"."ID" in (select "TEST"."T_BOOK"."ID" from "TEST"."T_BOOK", "TEST"."T_AUTHOR" where "TEST"."T_BOOK"."AUTHOR_ID" = "TEST"."T_AUTHOR"."ID" order by "TEST"."T_BOOK"."ID" fetch next ? rows only)]; ORA-30926: The operation attempted to update the same row (rowid: 'AAAToYAAPAAAAGmAAA') twice.

https://docs.oracle.com/error-help/db/ora-30926/
	at org.jooq_3.20.0-SNAPSHOT.ORACLE23AI.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3644)
	at org.jooq.impl.Tools.translate(Tools.java:3620)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:827)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:362)
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
	at org.jooq.test.all.testcases.InsertUpdateTests.lambda$79(InsertUpdateTests.java:5094)
	at org.jooq.test.util.BaseTest.assertThrowsIf(BaseTest.java:458)
	at org.jooq.test.util.BaseTest.assertThrowsIf(BaseTest.java:446)
	at org.jooq.test.all.testcases.InsertUpdateTests.testUpdateFromLimit(InsertUpdateTests.java:5083)
	at org.jooq.test.jOOQAbstractTest.testUpdateFromLimit(jOOQAbstractTest.java:7356)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:757)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.sql.SQLException: ORA-30926: The operation attempted to update the same row (rowid: 'AAAToYAAPAAAAGmAAA') twice.

https://docs.oracle.com/error-help/db/ora-30926/
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:702)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:608)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1330)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:1102)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:456)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:498)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:272)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1451)
	at oracle.jdbc.driver.OracleStatement.executeSQLStatement(OracleStatement.java:1958)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1594)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3754)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:4202)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1015)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:458)
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:1086)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:348)
	... 36 more
Caused by: Error : 30926, Position : 179, SQL = update "TEST"."T_BOOK" set "TEST"."T_BOOK"."TITLE" = (((("TEST"."T_AUTHOR"."FIRST_NAME" || ' ') || "TEST"."T_AUTHOR"."LAST_NAME") || ': ') || "TEST"."T_BOOK"."TITLE") from "TEST"."T_AUTHOR" where "TEST"."T_BOOK"."ID" in (select "TEST"."T_BOOK"."ID" from "TEST"."T_BOOK", "TEST"."T_AUTHOR" where "TEST"."T_BOOK"."AUTHOR_ID" = "TEST"."T_AUTHOR"."ID" order by "TEST"."T_BOOK"."ID" fetch next :1 rows only), Original SQL = update "TEST"."T_BOOK" set "TEST"."T_BOOK"."TITLE" = (((("TEST"."T_AUTHOR"."FIRST_NAME" || ' ') || "TEST"."T_AUTHOR"."LAST_NAME") || ': ') || "TEST"."T_BOOK"."TITLE") from "TEST"."T_AUTHOR" where "TEST"."T_BOOK"."ID" in (select "TEST"."T_BOOK"."ID" from "TEST"."T_BOOK", "TEST"."T_AUTHOR" where "TEST"."T_BOOK"."AUTHOR_ID" = "TEST"."T_AUTHOR"."ID" order by "TEST"."T_BOOK"."ID" fetch next ? rows only), Error Message = ORA-30926: The operation attempted to update the same row (rowid: 'AAAToYAAPAAAAGmAAA') twice.

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:710)
	... 52 more
```
