### ISSUE TITLE
JOOQ is filling logs with static type registry warnings

### ISSUE THREAD

**Issue by mihalyr** [jOOQ/jOOQ#16750]
Hi @lukaseder I see https://github.com/jOOQ/jOOQ/issues/16090 is closed for some time and I just got around to upgrade jOOQ on my project from 3.18 to 3.19.8 (with a Spring Boot 3.3 update) and my logs are again full of this warning. It's the same enum again, but this time I don't have inline usage.

I've created a reproducer

*build.gradle*
```groovy
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.flywaydb:flyway-database-postgresql:10.10.0'
    }
}

plugins {
    id 'java'
    id 'application'
    id "org.jooq.jooq-codegen-gradle" version "3.19.8"
    id "org.flywaydb.flyway" version "10.10.0"
}

version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    jooqCodegen 'org.postgresql:postgresql:42.7.3'

    implementation 'org.flywaydb:flyway-core:10.10.0'
    implementation 'org.flywaydb:flyway-database-postgresql:10.10.0'
    implementation 'org.jooq:jooq:3.19.8'
    implementation 'org.postgresql:postgresql:42.7.3'

    implementation 'org.slf4j:slf4j-api:2.0.13'
    implementation 'org.slf4j:slf4j-simple:2.0.13'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

application {
    mainClass = 'com.example.Main'
}

flyway {
    url = 'jdbc:postgresql://localhost:5432/postgres'
    user = 'postgres'
    password = 'postgres'
}

jooq {
    configuration {
        jdbc {
            driver = 'org.postgresql.Driver'
            url = 'jdbc:postgresql://localhost:5432/postgres'
            user = 'postgres'
            password = 'postgres'
        }
        generator {
            database {
                name = 'org.jooq.meta.postgres.PostgresDatabase'
                inputSchema = 'public'
                includes = '.*'
                excludes = ''
                forcedTypes {
                    forcedType {
                        userType = 'com.example.JobStatus'
                        includeTypes = 'TEXT'
                        includeExpression = '.*\\.JOBS\\.STATUS'
                        converter = """org.jooq.Converter.ofNullable(
                          String.class,
                          com.example.JobStatus.class,
                          s -> com.example.JobStatus.valueOf(s),
                          t -> t.toString()
                        )
                        """
                    }
                }
            }
            target {
                packageName = 'com.example.jooq'
                directory = 'src/main/java'
            }
        }

    }
}

test {
    useJUnitPlatform()
}
```

*src/main/resources/db/migration/V1__init_schema.sql*
```sql
CREATE TABLE jobs (
    id int primary key,
	status text not null
);
```

*src/main/java/com/example/JobStatus.java*
```java
package com.example;

public enum JobStatus {
  IDLE, FAILED
}
```

*src/main/java/com/example/Main.java*
```java
package com.example;

import com.example.jooq.Tables;
import org.jooq.impl.DSL;

public class Main {
  public static void main(String[] args) {
    var db = DSL.using("jdbc:postgresql://localhost:5432/postgres", "postgres", "postgres");
    db.insertInto(Tables.JOBS)
        .set(Tables.JOBS.ID, 1)
        .set(Tables.JOBS.STATUS, JobStatus.IDLE)
        .onConflict(Tables.JOBS.ID)
        .doUpdate()
        .set(Tables.JOBS.STATUS,
            DSL.when(Tables.JOBS.STATUS.eq(JobStatus.FAILED), JobStatus.IDLE)
                .otherwise(Tables.JOBS.STATUS))
        .execute();
  }
}
```

Running this simple jOOQ query results in long exception traces (on production this is significant)

```
[main] WARN org.jooq.impl.DefaultDataType.getDataType - Static type registry     : The deprecated static type registry was being accessed for a non-built-in data type: clob /* com.example.JobStatus */.

It is strongly recommended not looking up DataType<T> references from Class<T> references by
relying on the internal static type registry. For example, avoid calling DSL.val(Object) or
DSL.val(Object, Class), and call DSL.val(Object, DataType), providing an explicit DataType
reference to jOOQ if your DataType uses a Converter or a Binding. If you think jOOQ should
be able to infer your user type in your particular query, please report a bug here:
https://jooq.org/bug

See https://github.com/jOOQ/jOOQ/issues/15286 for more details.

org.jooq.impl.DefaultDataType$DiscouragedStaticTypeRegistryUsage
	at org.jooq.impl.DefaultDataType.check(DefaultDataType.java:844)
	at org.jooq.impl.Val.accept(Val.java:192)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:731)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:381)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:291)
	at org.jooq.impl.CaseSearched.acceptNative(CaseSearched.java:254)
	at org.jooq.impl.CaseSearched.accept(CaseSearched.java:185)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:731)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:381)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:291)
	at org.jooq.impl.FieldMapForUpdate.acceptAssignmentClause(FieldMapForUpdate.java:347)
	at org.jooq.impl.FieldMapForUpdate.accept(FieldMapForUpdate.java:199)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:731)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:381)
	at org.jooq.impl.InsertQueryImpl.accept1(InsertQueryImpl.java:517)
	at org.jooq.impl.AbstractDMLQuery.accept0(AbstractDMLQuery.java:671)
	at org.jooq.impl.InsertQueryImpl.accept(InsertQueryImpl.java:433)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:731)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:381)
	at org.jooq.impl.DefaultRenderContext$Rendered.rendered(DefaultRenderContext.java:1078)
	at org.jooq.impl.AbstractQuery.getSQL0(AbstractQuery.java:498)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:303)
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
	at com.example.Main.main(Main.java:17)
[main] INFO org.jooq.impl.DefaultExecuteContext.logVersionSupport - Version                  : Database version is supported by dialect POSTGRES: 16.2
[main] WARN org.jooq.impl.DefaultDataType.getDataType - Static type registry     : The deprecated static type registry was being accessed for a non-built-in data type: clob /* com.example.JobStatus */.

It is strongly recommended not looking up DataType<T> references from Class<T> references by
relying on the internal static type registry. For example, avoid calling DSL.val(Object) or
DSL.val(Object, Class), and call DSL.val(Object, DataType), providing an explicit DataType
reference to jOOQ if your DataType uses a Converter or a Binding. If you think jOOQ should
be able to infer your user type in your particular query, please report a bug here:
https://jooq.org/bug

See https://github.com/jOOQ/jOOQ/issues/15286 for more details.

org.jooq.impl.DefaultDataType$DiscouragedStaticTypeRegistryUsage
	at org.jooq.impl.DefaultDataType.check(DefaultDataType.java:844)
	at org.jooq.impl.Val.accept(Val.java:192)
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:258)
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:68)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:381)
	at org.jooq.impl.QueryPartCollectionView.acceptElement(QueryPartCollectionView.java:256)
	at org.jooq.impl.QueryPartCollectionView.accept(QueryPartCollectionView.java:226)
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:258)
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:68)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:381)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:344)
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
	at com.example.Main.main(Main.java:17)
```

Am I missing something? Or https://github.com/jOOQ/jOOQ/issues/16090 was closed perhaps too early? 

Thank you in advance.

_Originally posted by @mihalyr in https://github.com/jOOQ/jOOQ/issues/16090#issuecomment-2143089052_

**Comment by lukaseder** [comment]
Thanks for your message, @mihalyr. This is a different case, related to the `CASE` expression which prevents propagation of the explicit `DataType<U>` to your bind variable, so not exactly the same thing as #16090. You can try your `CASE` expression in a `SELECT` query at any location and you'll see that you'll get the same warning, so this isn't related to using it in `UPDATE`.

I'll have a look at this, soon. As a workaround, as mentioned in the warnings, use the `DSL.val(value, dataType)` method to create an explicit bind variable based on your column:

```java
val(IDLE, JOBS.STATUS)
```

Or probably even better, use `doUpdate().where()`!

```java
.doUpdate()
.set(JOBS.STATUS, JobStatus.IDLE)
.where(JOBS.STATUS.eq(JobStatus.FAILED))
```

**Comment by mihalyr** [comment]
Thank you @lukaseder

My quick reaction was to turn off the logger for getDataType as I noticed it on prod that logs suddenly jumped and didn't have much time to think. But the workaround with "val" looks like a good alternative in the meantime.

I can't move the case to where, since this isn't the complete query, I just reduced one to this for a reproducer, there are other fields updated and the status is the only conditional hence the case.

**Comment by lukaseder** [comment]
Similar issue:

- https://github.com/jOOQ/jOOQ/issues/15286#issuecomment-2197167368

**Comment by lukaseder** [comment]
Looking into this now. I wonder if there's a backwards compatible way to fix this due to the fact that the `CaseConditionStep::when` method is a mutable operation, and many users already rely on the mutable behaviour. Illustration:

```java
// This now has the DataType<T> from the static type registry
CaseConditionStep<U> c = when(condition, value1); 

// This should now have actualType as the c.getDataType(), which may be a different one than the one
// from the static type registry
c.else_(val(value2, actualType))
```

In particular, when there are multiple converters / bindings for the `U` type, then we would want the `actualType` to apply everywhere, including when reading the `CASE` expression from a `ResultSet`. We do have an internal `DataTypeProxy` that allows also for making `DataType` instances mutable as well, but I fear this is a rabbit hole I'll regret.

Also, this would address the problem only for the  `CASE` expression, and there are many other types of expression which will produce such a static type registry warning. I'll have to think about this a bit more...

**Comment by lukaseder** [comment]
Looking into this now along with https://github.com/jOOQ/jOOQ/issues/17786, which has already been fixed for jOOQ 3.20.

**Comment by lukaseder** [comment]
Ah yes, I forgot. This issue is way more complicated than #17786, I guess this won't make it into this year's work anymore, but I'll definitely try to address this still in 3.20.
