### ISSUE TITLE
Inconsistent formatting of HSQLDB DUAL table emulation

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#16792]
A recent change has exposed a (cosmetic) regression in a diagnostics test:

```
      org.junit.ComparisonFailure: expected:<...Coelho' from (values[(1)) as dual](dual))> but was:<...Coelho' from (values[ (1)) as dual ](dual))>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.jooq.test.util.BaseTest.assertEquals(BaseTest.java:344)
	at org.jooq.test.all.testcases.DiagnosticsTests.lambda$51(DiagnosticsTests.java:1026)
	at org.jooq.test.all.testcases.DiagnosticsTests.test(DiagnosticsTests.java:1153)
	at org.jooq.test.all.testcases.DiagnosticsTests.test(DiagnosticsTests.java:1136)
	at org.jooq.test.all.testcases.DiagnosticsTests.testExpression(DiagnosticsTests.java:1019)
	at org.jooq.test.all.testcases.DiagnosticsTests.lambda$43(DiagnosticsTests.java:962)
	at org.jooq.test.all.testcases.DiagnosticsTests.lambda$1(DiagnosticsTests.java:123)
	at org.jooq.test.all.testcases.DiagnosticsTests.diagnosticsTest(DiagnosticsTests.java:159)
	at org.jooq.test.all.testcases.DiagnosticsTests.diagnosticsTest(DiagnosticsTests.java:123)
	at org.jooq.test.all.testcases.DiagnosticsTests.testDiagnosticsConcatenationInPredicate(DiagnosticsTests.java:956)
	at org.jooq.test.jOOQAbstractTest.testDiagnosticsConcatenationInPredicate(jOOQAbstractTest.java:3681)
	at 
```

The test now compares implicit `DUAL` tables with explicit ones, where the HSQLDB rendering is different than what we parse, see above exception.

For end users, this is cosmetic only.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.10 (https://github.com/jOOQ/jOOQ/issues/16793)
- 3.18.17 (https://github.com/jOOQ/jOOQ/issues/16794)
- 3.17.26 (https://github.com/jOOQ/jOOQ/issues/16795)
