### ISSUE TITLE
jOOQ-codegen-gradle 3.19.10 assumes presence of a "main" source set, which isn't always the case

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#16842]
We mustn't assume the presence of a `main` source set, which we're doing since 3.19.10's various fixes:

```
Caused by: org.gradle.api.UnknownDomainObjectException: SourceSet with name 'main' not found.
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection.createNotFoundException(DefaultNamedDomainObjectCollection.java:529)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection.named(DefaultNamedDomainObjectCollection.java:385)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection.named(DefaultNamedDomainObjectCollection.java:393)
	at org.jooq.codegen.gradle.CodegenTask.registerSourceSet(CodegenTask.java:104)
	at org.jooq.codegen.gradle.CodegenPlugin.lambda$configureTask$2(CodegenPlugin.java:99)
	at org.gradle.api.internal.DefaultMutationGuard$1.execute(DefaultMutationGuard.java:45)
	at org.gradle.api.internal.DefaultMutationGuard$1.execute(DefaultMutationGuard.java:45)
	at org.gradle.internal.code.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:122)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:110)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction.execute(DefaultCollectionCallbackActionDecorator.java:107)
	at org.gradle.internal.ImmutableActionSet$SetWithManyActions.execute(ImmutableActionSet.java:329)
	at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:262)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection.doAdd(DefaultNamedDomainObjectCollection.java:125)
	at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:256)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection$AbstractDomainObjectCreatingProvider.tryCreate(DefaultNamedDomainObjectCollection.java:1011)
	... 312 more
```

Perhaps, we should create it if it doesn't exist?

See also:
https://groups.google.com/g/jooq-user/c/qfMVwzBcruc

**Comment by lukaseder** [comment]
I could have sworn I did a check if it exists, and created it lazily if not. Don't know why that version of the code no longer exists.

**Comment by lukaseder** [comment]
Don't know how to write a regression test for this, though, where the `main` source set is absent with the `java` plugin. Will investigate.

**Comment by lukaseder** [comment]
A regression test has kindly been provided here:

- https://groups.google.com/g/jooq-user/c/qfMVwzBcruc
- https://github.com/kevinrjones/jooqtest

**Comment by lukaseder** [comment]
I remember now why we don't lazily create the `main` source set. This attempted implementation:

```java
if (source != null) {
    SourceSet main = source.findByName("main");

    if (main == null)
        main = source.create("main");

    main.getJava().srcDir(task.getOutputDirectory());
}
```

Produces this error:

```
A problem occurred configuring project ':jOOQ-test-codegen-gradle-kotlin-only-configuration-android'.
> Could not create task ':jOOQ-test-codegen-gradle-kotlin-only-configuration-android:jooqCodegen'.
   > DefaultTaskContainer#register(String, Class, Action) on task set cannot be executed in the current context.
```

Let's delay potential creation of source sets until this is implemented:

- https://github.com/jOOQ/jOOQ/issues/16088

This bug will simply restore the logic where we do nothing in case we don't find the `main` source set.

**Comment by lukaseder** [comment]
I'm using this reproducer:

```kotlin
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import org.jooq.meta.jaxb.Logging

plugins {
    id("org.jetbrains.kotlin.multiplatform") version "2.0.0"
    id("org.jooq.trial.jooq-codegen-gradle")
}

kotlin {
    jvm("desktop")

    sourceSets {
        commonMain {
            dependencies {
                implementation("${group}:jooq:${version}")
            }
            kotlin {
                srcDir("${projectDir}/build/generated-sources/jooq")
            }
        }
        commonTest {
            dependencies {
                implementation("junit:junit:4.13.2")
            }
            kotlin {
                srcDir("${projectDir}/src/test/java")
            }
        }
    }
}

dependencies {
    jooqCodegen("${group}:jooq-meta-extensions:${version}")
}

jooq {
    configuration {
        logging = Logging.DEBUG
        generator {
            name = "org.jooq.codegen.KotlinGenerator"
            database {
                name = "org.jooq.meta.extensions.ddl.DDLDatabase"
                properties {
                    property {
                        key = "sql"
                        value = """
                        create schema s;
                        create table s.t (i int primary key, j int, k int)
                        """
                    }
                }
                inputSchema = "S"
            }
            target {
                packageName = "org.jooq.codegen.gradle.test.only.configuration.db"
            }
        }
    }
}

tasks.withType<KotlinCompile> {
    dependsOn(tasks["jooqCodegen"])
}

tasks.register("test") {
    dependsOn(tasks["allTests"])
}
```

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.11 (https://github.com/jOOQ/jOOQ/issues/16851)
