### ISSUE TITLE
Query query = DSL.using(SQLDialect.MYSQL).parser().parseQuery(sql);

### ISSUE THREAD

**Issue by arui3015** [jOOQ/jOOQ#16871]
### Your question

```
ALTER TABLE `user_info`
    ADD COLUMN `id` int NOT NULL AUTO_INCREMENT COMMENT 'id' AFTER `name`,
    ADD COLUMN `a_code` varchar(255) NOT NULL COMMENT 'code' AFTER `id`,
    ADD COLUMN `b_code` varchar(255) NOT NULL AFTER `a_code`,
    ADD COLUMN `c_code` varchar(255) NOT NULL AFTER `b_code`,
    ADD PRIMARY KEY (`id`, `a_code`),
    ADD INDEX(`b_code`) USING BTREE,
    ADD UNIQUE INDEX(`c_code`) USING BTREE
error:
Exception in thread "main" org.jooq.impl.ParserException: Unexpected clause: [8:14] ...DD UNIQUE KEY(`c_code`) USING BTREE,
    ADD INDEX[*](`b_code`) USING BTREE
    at org.jooq.impl.DefaultParseContext.exception(ParserImpl.java:15161)
    at org.jooq.impl.DefaultParseContext.done(ParserImpl.java:15347)
    at org.jooq.impl.DefaultParseContext.lambda$parseQuery0$2(ParserImpl.java:975)
    at org.jooq.impl.DefaultParseContext.wrap(ParserImpl.java:15354)
    at org.jooq.impl.DefaultParseContext.parseQuery0(ParserImpl.java:975)
    at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:786)
    at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:781)
    at org.jooq.impl.Jooq.main(Jooq.java:44)
```

### jOOQ Version

3.19.10

### Database product and version

mysql

### Java Version

17

**Comment by lukaseder** [comment]
Thanks for your message.

We'll eventually support multi-action `ALTER` statements, e.g. to alter multiple columns:

- https://github.com/jOOQ/jOOQ/issues/8846

This will also include combining other object alterations in the same query.

There's no workaround within jOOQ at the moment, other than you manually splitting the query into multiple queries in your own code prior to parsing.
