### ISSUE TITLE
Support BigQuery TIMESTAMP data type as SQLDataType.TIMESTAMPWITHTIMEZONE

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#16875]
In BigQuery, these timestamp data types are supported.

- `SQLDataType.TIMESTAMP`: `DATETIME` (already supported)
- `SQLDataType.TIMSTAMPWITHTIMEZONE`: `TIMESTAMP` (not yet supported)

We should add support for the latter. 

----
See also:
https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#datetime_type

**Comment by lukaseder** [comment]
This is funny 🫠 When writing bind values, we cannot pass the `OffsetDateTime` value, because of exceptions like these:

```
Caused by: java.lang.Exception: Unparseable query parameter `` in type `TYPE_TIMESTAMP`, Invalid timestamp: '1970-01-01T00:00Z' value: '1970-01-01T00:00Z'
	at com.simba.googlebigquery.googlebigquery.client.requests.jobs.JobsInsertRequest.execute(Unknown Source) ~[GoogleBigQueryJDBC42.jar:SimbaJDBCDriverforGoogleBigQuery_1.3.0.1001]
	at com.simba.googlebigquery.googlebigquery.client.requests.jobs.JobsInsertRequest.execute(Unknown Source) ~[GoogleBigQueryJDBC42.jar:SimbaJDBCDriverforGoogleBigQuery_1.3.0.1001]
	at com.simba.googlebigquery.googlebigquery.client.requests.AbstractRequestWithRetry.executeWithRetry(Unknown Source) ~[GoogleBigQueryJDBC42.jar:SimbaJDBCDriverforGoogleBigQuery_1.3.0.1001]
	at com.simba.googlebigquery.googlebigquery.client.queryclient.JobsInsertClient.executeQuery(Unknown Source) ~[GoogleBigQueryJDBC42.jar:SimbaJDBCDriverforGoogleBigQuery_1.3.0.1001]
	at com.simba.googlebigquery.googlebigquery.client.BQClient.executeQuery(Unknown Source) ~[GoogleBigQueryJDBC42.jar:SimbaJDBCDriverforGoogleBigQuery_1.3.0.1001]
	at com.simba.googlebigquery.googlebigquery.dataengine.BQAbstractExecutor.execute(Unknown Source) ~[GoogleBigQueryJDBC42.jar:SimbaJDBCDriverforGoogleBigQuery_1.3.0.1001]
	at com.simba.googlebigquery.googlebigquery.dataengine.BQSQLExecutor.execute(Unknown Source) ~[GoogleBigQueryJDBC42.jar:SimbaJDBCDriverforGoogleBigQuery_1.3.0.1001]
	at com.simba.googlebigquery.jdbc.common.SPreparedStatement.executeWithParams(Unknown Source) ~[GoogleBigQueryJDBC42.jar:SimbaJDBCDriverforGoogleBigQuery_1.3.0.1001]
	at com.simba.googlebigquery.jdbc.common.SPreparedStatement.execute(Unknown Source) ~[GoogleBigQueryJDBC42.jar:SimbaJDBCDriverforGoogleBigQuery_1.3.0.1001]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219) ~[classes/:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:458) ~[classes/:?]
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:1086) ~[classes/:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:348) ~[classes/:?]
```

Obviously, a bug. So, we'll have to write the string version, instead (which we already "sanitise" for other dialects that don't follow ISO standards).

When reading the value, however, we cannot read the string, or the time zone will be truncated.

**Comment by lukaseder** [comment]
Implemented for jOOQ 3.20.

I'll report that bug to Google tomorrow.

**Comment by lukaseder** [comment]
I was using the Simba driver version 1.3.0. With 1.5.4, the problem still persists

**Comment by lukaseder** [comment]
Here's the bug:
https://issuetracker.google.com/issues/350528338

It's specific to the abbreviated ISO 8601 timestamp format used by `java.time.OffsetDateTime.toString()` on the epoch timestamp `1970-01-01T00:00Z`, which hardly appears in user data, but does appear a lot in our tests.

```
