### ISSUE TITLE
Incorrect dialect detection on Oracle with r2dbc

### ISSUE THREAD

**Issue by wfhartford** [jOOQ/jOOQ#16911]
### Expected behavior

jOOQ detects the correct Oracle version and renders valid SQL when using r2dbc.

### Actual behavior

jOOQ always uses SQLDialect.ORACLE when connected to an oracle database via r2dbc and renders invalid SQL when connected to older versions of Oracle.

### Steps to reproduce the problem

1. Run an Oracle 23 database on port 1521 using the following command:
```
docker run -p 1521:1521 -e ORACLE_PWD=password container-registry.oracle.com/database/free:latest
```

2. Run an Oracle 18 database on port 1522 using the following command:
```
docker run -p 1522:1521 -e ORACLE_PASSWORD=password gvenzl/oracle-xe:18.4.0-slim
```

3. Run the following Kotlin code:
```
private val logger = KotlinLogging.logger {}
suspend fun main() {
  jdbcDslContext(1522, "XEPDB1").test("jdbc 18")
  r2dbcDslContext(1522, "XEPDB1").test("r2dbc 18")
  jdbcDslContext(1521, "FREE").test("jdbc 23")
  r2dbcDslContext(1521, "FREE").test("r2dbc 23")
}

fun r2dbcDslContext(port: Int, db: String): DSLContext =
  using(
    ConnectionFactories.get(
      ConnectionFactoryOptions.builder()
        .option(ConnectionFactoryOptions.DRIVER, "oracle")
        .option(ConnectionFactoryOptions.HOST, "localhost")
        .option(ConnectionFactoryOptions.PORT, port)
        .option(ConnectionFactoryOptions.DATABASE, db)
        .option(ConnectionFactoryOptions.USER, "SYSTEM")
        .option(ConnectionFactoryOptions.PASSWORD, "password")
        .build()
    )
  )

fun jdbcDslContext(port: Int, db: String): DSLContext =
  using("jdbc:oracle:thin:@//localhost:$port/$db", "SYSTEM", "password")

suspend fun DSLContext.test(name: String) {
  logger.info { "$name dialect: ${dialect()}" }
  val select = select(asterisk()).from(dual())
  logger.info { "$name select from dual: ${select.toString().replace(Regex("\\s+"), " ")}" }
  try {
    val result = select.asFlow().toList().firstOrNull()?.get("DUMMY")
    logger.info { "$name select from dual result: $result" }
  }
  catch (e: DataAccessException) {
    logger.info(e) { "$name select from dual failed" }
  }
}
```

Observe the output as follows:
```
INFO  com.ze.jooq.oracle.frombug.Main - jdbc 18 dialect: ORACLE18C
INFO  com.ze.jooq.oracle.frombug.Main - jdbc 18 select from dual: select * from ( select 'X' "DUMMY" from DUAL ) "DUAL"
INFO  o.j.i.D.logVersionSupport - Version                  : Database version is supported by dialect ORACLE18C: Oracle Database 18c Express Edition Release 18.0.0.0.0 - Production
Version 18.4.0.0.0
INFO  com.ze.jooq.oracle.frombug.Main - jdbc 18 select from dual result: X
INFO  com.ze.jooq.oracle.frombug.Main - r2dbc 18 dialect: ORACLE
INFO  com.ze.jooq.oracle.frombug.Main - r2dbc 18 select from dual: select * from ( select 'X' "DUMMY" ) "DUAL"
INFO  com.ze.jooq.oracle.frombug.Main - r2dbc 18 select from dual failed
org.jooq.exception.DataAccessException: SQL [select * from (select 'X' "DUMMY") "DUAL"]; ORA-00923: FROM keyword not found where expected

	at org.jooq.impl.Tools.translate(Tools.java:3607)
	at org.jooq.impl.Tools.translate(Tools.java:3585)
	at org.jooq.impl.Tools.translate(Tools.java:3569)
	at org.jooq.impl.R2DBC$Forwarding.lambda$onError$0(R2DBC.java:249)
	at org.jooq.impl.Internal$1.onComplete(Internal.java:759)
	at oracle.r2dbc.impl.AsyncLock$UsingConnectionSubscriber.onComplete(AsyncLock.java:523)
	at reactor.core.publisher.StrictSubscriber.onComplete(StrictSubscriber.java:123)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2205)
	at org.reactivestreams.FlowAdapters$FlowToReactiveSubscriber.onComplete(FlowAdapters.java:221)
	at oracle.jdbc.internal.CompletionStageUtil$IteratorSubscription.emitComplete(CompletionStageUtil.java:805)
	at oracle.jdbc.internal.CompletionStageUtil$BatchItemPublisher.subscribeToBatch(CompletionStageUtil.java:622)
	at oracle.jdbc.internal.CompletionStageUtil$BatchItemPublisher.lambda$subscribe$0(CompletionStageUtil.java:593)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
	at oracle.jdbc.driver.T4CTTIfun.lambda$doRPCAsync$0(T4CTTIfun.java:348)
	at oracle.jdbc.driver.T4CTTIfun.lambda$receiveRPCAsync$1(T4CTTIfun.java:474)
	at oracle.jdbc.driver.RestrictedLock.lambda$runUnrestricted$1(RestrictedLock.java:444)
	at oracle.jdbc.driver.RestrictedLock.callUnrestricted(RestrictedLock.java:463)
	at oracle.jdbc.driver.RestrictedLock.runUnrestricted(RestrictedLock.java:443)
	at oracle.jdbc.driver.PhysicalConnection.lambda$initializeAsyncExecutor$4(PhysicalConnection.java:1284)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: io.r2dbc.spi.R2dbcBadGrammarException: ORA-00923: FROM keyword not found where expected

	at oracle.r2dbc.impl.OracleR2dbcExceptions.toR2dbcException(OracleR2dbcExceptions.java:190)
	at oracle.r2dbc.impl.OracleR2dbcExceptions.toR2dbcException(OracleR2dbcExceptions.java:167)
	at reactor.core.publisher.Flux.lambda$onErrorMap$28(Flux.java:7236)
	at reactor.core.publisher.Flux.lambda$onErrorResume$29(Flux.java:7289)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
	at org.reactivestreams.FlowAdapters$FlowToReactiveSubscriber.onError(FlowAdapters.java:216)
	at oracle.jdbc.internal.CompletionStageUtil$BatchItemPublisher.subscribeToFailedBatch(CompletionStageUtil.java:636)
	at oracle.jdbc.internal.CompletionStageUtil$BatchItemPublisher.lambda$subscribe$0(CompletionStageUtil.java:591)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at oracle.jdbc.driver.OraclePreparedStatement.lambda$executeAsyncOracle$4(OraclePreparedStatement.java:4171)
	at oracle.jdbc.driver.OraclePreparedStatement.lambda$executeInternalAsync$0(OraclePreparedStatement.java:3814)
	at oracle.jdbc.driver.OracleStatement.lambda$doExecuteWithTimeoutAsync$2(OracleStatement.java:1556)
	at oracle.jdbc.driver.OracleStatement.lambda$executeSQLSelectAsync$3(OracleStatement.java:1727)
	at oracle.jdbc.driver.OracleStatement.lambda$executeMaybeDescribeAsync$0(OracleStatement.java:1211)
	at oracle.jdbc.driver.OracleStatement.lambda$prepareDefineBufferAndExecuteAsync$1(OracleStatement.java:1348)
	at oracle.jdbc.driver.T4CPreparedStatement.lambda$executeForDescribeAsync$2(T4CPreparedStatement.java:1109)
	at oracle.jdbc.driver.T4CPreparedStatement.lambda$doOall8Async$0(T4CPreparedStatement.java:236)
	at oracle.jdbc.driver.T4C8Oall.lambda$doOALLAsync$0(T4C8Oall.java:583)
	... 11 common frames omitted
Caused by: java.sql.SQLSyntaxErrorException: ORA-00923: FROM keyword not found where expected

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:630)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:564)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1231)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:772)
	at oracle.jdbc.driver.T4CTTIfun.lambda$receiveRPCAsync$1(T4CTTIfun.java:441)
	... 10 common frames omitted
Caused by: oracle.jdbc.OracleDatabaseException: ORA-00923: FROM keyword not found where expected

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:637)
	... 14 common frames omitted
INFO  com.ze.jooq.oracle.frombug.Main - jdbc 23 dialect: ORACLE23C
INFO  com.ze.jooq.oracle.frombug.Main - jdbc 23 select from dual: select * from ( select 'X' "DUMMY" ) "DUAL"
INFO  com.ze.jooq.oracle.frombug.Main - jdbc 23 select from dual result: X
INFO  com.ze.jooq.oracle.frombug.Main - r2dbc 23 dialect: ORACLE
INFO  com.ze.jooq.oracle.frombug.Main - r2dbc 23 select from dual: select * from ( select 'X' "DUMMY" ) "DUAL"
INFO  com.ze.jooq.oracle.frombug.Main - r2dbc 23 select from dual result: X
```

This output shows that for both database version, JDBC detects the correct dialect (ORACLE18C or ORACLE23C), however in the r2dbc case uses the dialect ORACLE, resulting in invalid SQL being produced when connected to the Oracle 18 database.

### jOOQ Version

jOOQ Pro 3.19.10

### Database product and version

Oracle versions 23C and 18C

### Java Version

OpenJDK 21

### JDBC / R2DBC driver name and version (include name if unofficial driver)

com.oracle.database.r2dbc:oracle-r2dbc:1.2.0

**Comment by wfhartford** [comment]
If it would be helpful, I can share the full project which demonstrates the error.

**Comment by lukaseder** [comment]
Thanks for your report, @wfhartford.

JDBC has useful methods like `DatabaseMetaData.getDatabaseMajorVersion()` that help clearly identify the database product version. 

R2DBC has 2 separate types for the same thing:

- `ConnectionFactoryMetadata` with only a single method, the `ConnectionFactoryMetadata.getName()` method
- `ConnectionMetadata` with `ConnectionMetadata.getDatabaseProductName()` and `ConnectionMetadata.getDatabaseVersion()`, both formatted strings

I vaguely recall that implementations didn't provide formally useful information when we first started integrating R2DBC. I can check if this has changed now, but I wouldn't have high hopes for this information to remain reliable in the future, since it's completely string based, and unformatting such strings is very brittle.

It is so much easier to just be explicit with jOOQ's own configuration for the time being.

Nevertheless, we can certainly attempt to reverse engineer things.

**Comment by lukaseder** [comment]
Please note also, when supplying a `ConnectionFactory` (the R2DBC equivalent of JDBC's `DataSource`), then jOOQ won't be able to look up the version. We could try to connect to the server (by blocking on `ConnectionFactory::create` (!)), but we're not doing that currently, as it may not be what users intend for jOOQ to do.

**Comment by wfhartford** [comment]
Thanks Lukas.

I should have mentioned, this isn't a high priority for me. I spent some time to write the code above to understand the problem myself and couldn't find an issue anywhere, so thought I should raise one. The application I'm working on has to interact with a few different Oracle versions, so I've set the dialect to 18C (the oldest version I expect to work with) and will probably just leave it at that.
