### ISSUE TITLE
Support emulating EXCLUDED in MySQL, when used in expressions

### ISSUE THREAD

**Issue by rafaelzig** [jOOQ/jOOQ#16942]
### Expected behavior

1. The following query is generated and executed by JooQ:
```sql
insert into
    `database`.`author` (`last_name`, `books_authored`)
values
    (?, ?),
    (?, ?) as `t`
on duplicate key update
    `database`.`author`.`books_authored` = (
        `database`.`author`.`books_authored` + `t`.`books_authored`
    )
```
2. No exception is raised

### Actual behavior

1. The following query is generated and executed by JooQ:
```sql
insert into
    `database`.`author` (`last_name`, `books_authored`)
values
    (?, ?),
    (?, ?)
on duplicate key update
    `database`.`author`.`books_authored` = (
        `database`.`author`.`books_authored` + `t`.`books_authored`
    )
```
2. BadSqlGrammarException is raised
```
jOOQ; bad SQL grammar [insert into `database`.`author` (`last_name`, `books_authored`) values (?, ?), (?, ?) on duplicate key update `database`.`author`.`books_authored` = (`database`.`author`.`books_authored` + `t`.`books_authored`)]
org.springframework.jdbc.BadSqlGrammarException: jOOQ; bad SQL grammar [insert into `database`.`author` (`last_name`, `books_authored`) values (?, ?), (?, ?) on duplicate key update `database`.`author`.`books_authored` = (`database`.`author`.`books_authored` + `t`.`books_authored`)]
	at org.jooq_3.18.9.MYSQL.debug(Unknown Source)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:243)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.translate(JooqExceptionTranslator.java:94)
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.handle(JooqExceptionTranslator.java:81)
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.exception(JooqExceptionTranslator.java:55)
	at org.jooq.impl.ExecuteListeners.exception(ExecuteListeners.java:304)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:361)
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
	...
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 't.books_authored' in 'field list'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:445)
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:1024)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:346)
	... 88 more
```

### Steps to reproduce the problem

1. Given the following database schema:
```sql
CREATE TABLE `AUTHOR` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `last_name` varchar(255) NOT NULL,
    `books_authored` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY (`last_name`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```
2. When the following code is executed ([reference](https://www.jooq.org/doc/latest/manual/sql-building/sql-statements/insert-statement/insert-on-duplicate-key-excluded/)):
```java
create.insertInto(AUTHOR.LAST_NAME, AUTHOR.BOOKS_AUTHORED)
      .values("Koontz", 3)
      .values("Shakespeare", 4)
      .onDuplicateKeyUpdate()
      .set(AUTHOR.BOOKS_AUTHORED, AUTHOR.BOOKS_AUTHORED.add(excluded(AUTHOR.BOOKS_AUTHORED)))
      .execute();
```

### jOOQ Version

3.18.9

### Database product and version

MySQL 8.0.31

### Java Version

Amazon Corretto 17.0.9

### JDBC / R2DBC driver name and version (include name if unofficial driver)

com.mysql:mysql-connector-j:8.0.33

**Comment by lukaseder** [comment]
Thanks for your report.

There was an omission in jOOQ 3.18's implementation of `EXCLUDED` for MySQL, when used in expressions, see:

- https://github.com/jOOQ/jOOQ/issues/13575#issuecomment-1137001437

Unfortunately, I forgot to make a new issue for that particular feature combination, so this will be the issue now.

There's a clean solution using `QueryPart::$traverse` for the commercial editions of jOOQ, where we can check whether the `VALUES` alias is needed or not. In the Open Source Edition, I suspect we'll just have to always render it, irrespective of whether `EXCLUDED` is used. It's possible to do this because our support matrix currently requires MySQL 8.0.31 for jOOQ 3.19, which has the feature. But given the importance of the change (for older MySQL versions), this won't be backported.

**Comment by lukaseder** [comment]
A workaround is to use an `ExecuteListener` and patch the rendered SQL by prepending the ``as `t` `` syntax to the `on duplicate key update` clause.

**Comment by lukaseder** [comment]
Revisiting this. Some ideas:

- The simplest solution that would work in all editions would be to just always add the ``AS `t` `` clause whenever `ON DUPLICATE KEY UPDATE` is rendered. That would break a test case where we're actually inserting into `t`, see:
 
  - https://github.com/jOOQ/jOOQ/issues/13576

- We could rename the `t` alias to `x`, or whatever, but there are quite a few assumptions about this table being called `t` in the jOOQ code base, so there's regression risk.
- Finally, we could introduce a new scope marker where the alias would be rendered, and then insert the missing SQL when we encounter a `Excluded` query part, if it hasn't already been inserted. This mechanism of patching the SQL string after the fact has been used a few times in jOOQ. I don't like this because this scope marker would be very rarely needed, and it incurs a bit of additional rendering cost. But it does appear to be the simplest fix.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.21.0
- 3.20.11 (https://github.com/jOOQ/jOOQ/issues/19603)
- 3.19.30 (https://github.com/jOOQ/jOOQ/issues/19604)
- 3.18.37 (https://github.com/jOOQ/jOOQ/issues/19605)

**Comment by lukaseder** [comment]
The fix will now always generate a `excluded` alias as soon as the `ON DUPLICATE KEY UPDATE` clause is being used
