### ISSUE TITLE
Force inline bind values after 2536 in Teradata

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#16968]
Teradata also has a limit of 2536 bind variables, similar to other dialects:

```
org.jooq.exception.DataAccessException: SQL [select count(*) from "test"."t_book" where "test"."t_book"."ID" in (cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer), [...] integer), cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer), cast(? as integer)) -- SQL rendered with a free trial version of jOOQ 3.20.0-SNAPSHOT]; [Teradata Database] [TeraJDBC 16.20.00.06] [Error 5793] [SQLState HY000] Limit on the number of host variables in USING modifier exceeded of 2536
	at org.jooq_3.20.0-SNAPSHOT.TERADATA.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3648)
	at org.jooq.impl.Tools.translate(Tools.java:3621)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:827)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:362)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:274)
	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:295)
	at org.jooq.impl.SelectImpl.fetchLazyNonAutoClosing(SelectImpl.java:3236)
	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:509)
	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:437)
	at org.jooq.test.all.testcases.PredicateTests.testLargeINCondition0(PredicateTests.java:861)
	at org.jooq.test.all.testcases.PredicateTests.testPredicates_IN_Large(PredicateTests.java:832)
	at org.jooq.test.jOOQAbstractTest.testPredicates_IN_Large(jOOQAbstractTest.java:6795)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:757)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.sql.SQLException: [Teradata Database] [TeraJDBC 16.20.00.06] [Error 5793] [SQLState HY000] Limit on the number of host variables in USING modifier exceeded of 2536
	at com.teradata.jdbc.jdbc_4.util.ErrorFactory.makeDatabaseSQLException(ErrorFactory.java:309)
	at com.teradata.jdbc.jdbc_4.statemachine.ReceiveInitSubState.action(ReceiveInitSubState.java:103)
	at com.teradata.jdbc.jdbc_4.statemachine.StatementReceiveState.subStateMachine(StatementReceiveState.java:311)
	at com.teradata.jdbc.jdbc_4.statemachine.StatementReceiveState.action(StatementReceiveState.java:200)
	at com.teradata.jdbc.jdbc_4.statemachine.StatementController.runBody(StatementController.java:137)
	at com.teradata.jdbc.jdbc_4.statemachine.StatementController.run(StatementController.java:128)
	at com.teradata.jdbc.jdbc_4.TDStatement.executeStatement(TDStatement.java:389)
	at com.teradata.jdbc.jdbc_4.TDStatement.prepareRequest(TDStatement.java:576)
	at com.teradata.jdbc.jdbc_4.TDPreparedStatement.<init>(TDPreparedStatement.java:131)
	at com.teradata.jdbc.jdk6.JDK6_SQL_PreparedStatement.<init>(JDK6_SQL_PreparedStatement.java:30)
	at com.teradata.jdbc.jdk6.JDK6_SQL_Connection.constructPreparedStatement(JDK6_SQL_Connection.java:82)
	at com.teradata.jdbc.jdbc_4.TDSession.prepareStatement(TDSession.java:1337)
	at com.teradata.jdbc.jdbc_4.TDSession.prepareStatement(TDSession.java:1381)
	at com.teradata.jdbc.jdbc_4.TDSession.prepareStatement(TDSession.java:1367)
	at org.jooq.tools.jdbc.DefaultConnection.prepareStatement(DefaultConnection.java:95)
	at org.jooq.test.utils.LoggingConnection.prepareStatement(LoggingConnection.java:68)
	at org.jooq.tools.jdbc.DefaultConnection.prepareStatement(DefaultConnection.java:95)
	at org.jooq.impl.ProviderEnabledConnection.prepareStatement(ProviderEnabledConnection.java:109)
	at org.jooq.impl.SettingsEnabledConnection.prepareStatement(SettingsEnabledConnection.java:91)
	at org.jooq.impl.AbstractResultQuery.prepare(AbstractResultQuery.java:189)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:315)
	... 38 more
```

We should handle this

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.11 (https://github.com/jOOQ/jOOQ/issues/16969)
- 3.18.18 (https://github.com/jOOQ/jOOQ/issues/16970)
- 3.17.27 (https://github.com/jOOQ/jOOQ/issues/16971)
