### ISSUE TITLE
Work around regression in MariaDB JDBC driver 3.4.0

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#16977]
There's a regression in MariaDB's JDBC driver when running DML `RETURNING` statements with "impossible" predicates:

- https://jira.mariadb.org/browse/CONJ-1192

E.g. this:

```java
try (Statement s = connection.createStatement()) {
    s.executeUpdate("create table t (i int primary key)");
 
    try (ResultSet rs = s.executeQuery("""
        delete from t
        where false
        returning i
        """)) {
        while (rs.next())
            System.out.println(rs.getInt(1));
    }
    finally {
        s.executeUpdate("drop table t");
    }
}
```

... produces this exception starting with MariaDB's JDBC driver version 3.4.0.

```
0
Statement.executeQuery() command does NOT return a result-set as expected. Either use Statement.execute(), Statement.executeUpdate(), or correct command
null
java.sql.SQLException: Statement.executeQuery() command does NOT return a result-set as expected. Either use Statement.execute(), Statement.executeUpdate(), or correct command
	at org.mariadb.jdbc.Statement.executeQuery(Statement.java:171)
	at org.jooq.testscripts.JDBC.main(JDBC.java:42)
```

It appears unlikely they'll retract this change, given it was intentional, and given that the server causes the regression by sending an `OkPacket` for this statement, rather than an empty result set.

As such, we should probably run `execute()` instead of `executeQuery()` and handle this gracefully.

**Comment by lukaseder** [comment]
The issue has been recognised as a MariaDB server issue, and might be fixed there:

- https://jira.mariadb.org/browse/MDEV-34585

I'll wait and see if we still need to address this on our end, then

**Comment by lukaseder** [comment]
There will even be a flag in the JDBC driver to revert to the previous behaviour for compatibility reasons:
https://jira.mariadb.org/browse/CONJ-1192?focusedCommentId=288459&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-288459

As such, there won't be any need to work around this issue from within jOOQ.
