### ISSUE TITLE
Exported array-type data with formatCSV() method can't be loaded by loadCSV() method

### ISSUE THREAD

**Issue by thesuppafila** [jOOQ/jOOQ#16985]
### Expected behavior

We have next table-structure:
![image](https://github.com/user-attachments/assets/90c1320e-5319-40be-9d8c-ecbd8f538877)

Result of exported data from table is csv-file contained next data, where first column 'keywords' is string-array:
![image](https://github.com/user-attachments/assets/7fe95d5c-49e4-4c5b-a401-73229242bf7c)

### Actual behavior

![image](https://github.com/user-attachments/assets/35fd5759-5b53-4ef0-93e6-d62c34f80ed4)

```
org.jooq.exception.DataTypeException: Cannot convert from [address, state ] (class java.lang.String) to class [Ljava.lang.String;
	at org.jooq.tools.Convert$ConvertAll.fail(Convert.java:1334)
	at org.jooq.tools.Convert$ConvertAll.from(Convert.java:1233)
	at org.jooq.tools.Convert.convert0(Convert.java:394)
	at org.jooq.tools.Convert.convert(Convert.java:467)
	at org.jooq.impl.AbstractDataType.convert(AbstractDataType.java:534)
	at org.jooq.impl.DefaultDataType.convert(DefaultDataType.java:92)
	at org.jooq.impl.LoaderImpl.addValue0(LoaderImpl.java:1021)
	at org.jooq.impl.LoaderImpl.executeSQL(LoaderImpl.java:859)
	at org.jooq.impl.LoaderImpl.access$300(LoaderImpl.java:110)
	at org.jooq.impl.LoaderImpl$3.run(LoaderImpl.java:787)
	at org.jooq.impl.DefaultDSLContext$4.run(DefaultDSLContext.java:683)
	at org.jooq.impl.DefaultDSLContext$4.run(DefaultDSLContext.java:680)
	at org.jooq.impl.DefaultDSLContext.connectionResult(DefaultDSLContext.java:662)
	at org.jooq.impl.DefaultDSLContext.connection(DefaultDSLContext.java:680)
	at org.jooq.impl.LoaderImpl.executeSQL(LoaderImpl.java:774)
	at org.jooq.impl.LoaderImpl.executeCSV(LoaderImpl.java:721)
	at org.jooq.impl.LoaderImpl.execute(LoaderImpl.java:673)
	at org.jooq.impl.LoaderImpl.execute(LoaderImpl.java:110)
```

### Steps to reproduce the problem

DDL for table:
```
create table test_keywords
(
    id          bigint generated by default as identity
        constraint pk_test_keywords_id
            primary key,
    keywords    character varying[] not null,
    description varchar,
    name        varchar             not null
        constraint uk_test_keywords_name
            unique,
    updated_at  timestamp default CURRENT_TIMESTAMP
);
```

Export data code example:
```
List<Field<?>> fields = Arrays.stream(context.select()
                .from(table(registryName))
                .fetch().fields())
        .filter(field -> !field.getName().equals("id"))
        .collect(Collectors.toList());
String csv = context.select(fields).from(table(registryName))
        .where(filterDefault())
        .fetch()
        .formatCSV(';');
```

Load data code example:
```
InputStream inputStream = new ByteArrayInputStream(convertCharsetTo(file, StandardCharsets.UTF_8));

List<Field<?>> fields = Arrays.stream(context.select().from(table(registryName)).fetch().fields())
        .filter(field -> !field.getName().equals("id"))
        .collect(Collectors.toList());

Loader<Record> result = context.loadInto(table(registryName))
                    .onErrorIgnore()
                    .loadCSV(inputStream)
                    .fields(fields)
                    .separator(';')
                    .execute();
```

### jOOQ Version

org.jooq:jooq:3.14.15

### Database product and version

PostgreSQL 13.9 (Debian 13.9-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

### Java Version

openjdk "18.0.2"

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.3.3

**Comment by lukaseder** [comment]
Thanks for your message. Does this reproduce with the latest jOOQ versions?

**Comment by thesuppafila** [comment]
@lukaseder I tried using spring-boot 3.3.2 which uses jOOQ:3.19.10 and the behavior is the same. But I haven't tried using the latest version.
![image](https://github.com/user-attachments/assets/f28448f9-1216-4523-9ab2-9981489526d7)

**Comment by lukaseder** [comment]
OK, thanks, I'll try reproducing this on my end.

**Comment by lukaseder** [comment]
I see now. We're exporting arrays as implemented by:

- #6545

```
id;number_array
1;""
2;[]
3;[1]
4;"[1, 2]"
```

Nested records are exported by recursing and generating nested CSV structures:

- #6545

But we don't support loading these formats yet. I'll look into this, for arrays at least.

**Comment by thesuppafila** [comment]
@lukaseder Thanks for the answer, we'll look forward to it in future releases :)
