### ISSUE TITLE
Gradle codegen fails when using Gradle daemon

### ISSUE THREAD

**Issue by zarebski-m** [jOOQ/jOOQ#16993]
### Expected behavior

My task setup:

- `:migration` – simple module with just Flyway migration scripts as resources under `db/migration`.
- `:migration-container` – module with custom implementation of `org.jooq.meta.postgres.PostgresDatabase` which runs Flyway migration at startup.
- `:model` – module with jOOQ model generated from migrations from `:migration` module executed in DB from `:migration-container`. This module includes dependency `jooqCodegen(project(":persistence:migration-container"))`.

This setup works great but as soon as I add a new migration script to `:migration` resources, build often fails with:

```
FileNotFoundException: JAR entry db/migration/V4__dummy.sql not found in [REDACTED]/migration/build/libs/migration-0.0.1-SNAPSHOT.jar
```

What helps is explicitly stopping Gradle daemon:

```
./gradlew --stop
./gradlew jooqCodegen
```

…or disabling the daemon alltogether:

```
./gradlew jooqCodegen --no-daemon
```

It might even pass as a workaround but unfortunately it is impossible to disable Gradle daemon when using IntelliJ IDEA.

### Actual behavior

Build should not fail.

### Steps to reproduce the problem

Please have a look at a reproduction project: https://github.com/zarebski-m/jooq-codegen-repro

### jOOQ Version

3.19.10

### Database product and version

Dockerized PostgreSQL 16

**Comment by lukaseder** [comment]
Thanks a lot for your report and reproducer. I'll have a look at this soon.

**Comment by lukaseder** [comment]
I don't really see how this is a jOOQ problem. The error happens with your configuration of when to run flyway scripts, not jOOQ code generation.

```
Caused by: org.flywaydb.core.api.FlywayException: JAR entry db/migration/V2__dummy.sql not found in C:\Users\lukas\jOOQ\mcve\16993\jooq-codegen-repro\migration\build\libs\migration.jar
        at org.flywaydb.core.internal.resource.classpath.ClassPathResource.read(ClassPathResource.java:119)
        at org.flywaydb.core.internal.resolver.ChecksumCalculator.calculateChecksumForResource(ChecksumCalculator.java:68)
        at org.flywaydb.core.internal.resolver.ChecksumCalculator.calculate(ChecksumCalculator.java:47)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.getChecksumForLoadableResource(SqlMigrationResolver.java:119)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.addMigrations(SqlMigrationResolver.java:158)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.resolveMigrations(SqlMigrationResolver.java:77)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.resolveMigrations(SqlMigrationResolver.java:55)
        at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.lambda$collectMigrations$0(CompositeMigrationResolver.java:134)
        at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.collectMigrations(CompositeMigrationResolver.java:135)
        at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.doFindAvailableMigrations(CompositeMigrationResolver.java:124)
        at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:114)
        at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:120)
        at org.flywaydb.core.internal.info.MigrationInfoServiceImpl.refresh(MigrationInfoServiceImpl.java:86)
        at org.flywaydb.core.internal.command.DbValidate.lambda$validate$0(DbValidate.java:112)
        at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:59)
        at org.flywaydb.core.internal.command.DbValidate.validate(DbValidate.java:105)
        at org.flywaydb.core.Flyway.doValidate(Flyway.java:451)
        at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:175)
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:210)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:164)
        at com.example.codegen.PostgresFlywayDatabase.create0(PostgresFlywayDatabase.kt:33)
        ... 126 more
Caused by: java.io.FileNotFoundException: JAR entry db/migration/V2__dummy.sql not found in C:\Users\lukas\jOOQ\mcve\16993\jooq-codegen-repro\migration\build\libs\migration.jar
        at org.flywaydb.core.internal.resource.classpath.ClassPathResource.read(ClassPathResource.java:114)
        ... 146 more
```

The hint is here:

```
> Task :migration:checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :migration:compileKotlin NO-SOURCE
> Task :migration:compileJava NO-SOURCE
> Task :migration:processResources UP-TO-DATE
> Task :migration:classes UP-TO-DATE
> Task :migration:jar UP-TO-DATE
```

The jar is considered `UP-TO-DATE` despite having added the relevant script. Then, for some reason, Flyway still knows that there's a new file, but can't find it in the jar file, which hasn't been re-built. None of this seems jOOQ specific.

I'm not really a gradle expert, I'm afraid, so I'm not sure what measures to take to solve this in your case.

But perhaps, our own MCVE templates can give you an idea how to do things differently with Flyway and Testcontainers?
https://github.com/jOOQ/jOOQ-mcve/tree/main/jOOQ-mcve-kotlin-postgres

**Comment by zarebski-m** [comment]
Hi @lukaseder, I've came around back to this issue. I have checked multiple times and the `:migration:jar` task is definitely _not_ up to date (nor cached) when a new migration file is added. And the `FileNotFoundException` is still there, unless I disable Gradle daemon.

Here is an excerpt from the build log of my reproduction:

```
$ ./gradlew classes
> Task :migration:compileKotlin NO-SOURCE
> Task :migration:compileJava NO-SOURCE
> Task :migration:processResources
> Task :migration:classes
> Task :migration:jar
> Task :migration-container:checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :migration-container:processResources NO-SOURCE
> Task :model:checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :model:processResources NO-SOURCE
> Task :migration-container:compileKotlin
> Task :migration-container:compileJava NO-SOURCE
> Task :migration-container:classes UP-TO-DATE
> Task :migration-container:jar
> Task :model:jooqCodegen
> Task :model:compileKotlin
> Task :model:compileJava NO-SOURCE
> Task :model:classes UP-TO-DATE

BUILD SUCCESSFUL in 23s
$ echo 'select * from dummy;'  >migration/src/main/resources/db/migration/V2__dummy.sql
$ ./gradlew classes --stacktrace
> Task :migration:compileKotlin NO-SOURCE
> Task :migration:compileJava NO-SOURCE
> Task :migration:processResources
> Task :migration:classes
> Task :migration:jar
> Task :migration-container:checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :migration-container:compileKotlin UP-TO-DATE
> Task :migration-container:compileJava NO-SOURCE
> Task :migration-container:processResources NO-SOURCE
> Task :migration-container:classes UP-TO-DATE
> Task :model:checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :migration-container:jar UP-TO-DATE
> **Task :model:jooqCodegen FAILED**

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':model:jooqCodegen'.
> Error while preparing schema for code generation

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':model:jooqCodegen'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:130)
        [...]
Caused by: org.jooq.exception.DataAccessException: Error while preparing schema for code generation
        at com.example.codegen.PostgresFlywayDatabase.create0(PostgresFlywayDatabase.kt:37)
        at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:408)
        [...]
Caused by: org.flywaydb.core.api.FlywayException: JAR entry db/migration/V2__dummy.sql not found in /[REDACTED]/jooq-codegen-repro/migration/build/libs/migration.jar
        at org.flywaydb.core.internal.resource.classpath.ClassPathResource.read(ClassPathResource.java:119)
        [...]
Caused by: java.io.FileNotFoundException: JAR entry db/migration/V2__dummy.sql not found in /[REDACTED]/jooq-codegen-repro/migration/build/libs/migration.jar
        at org.flywaydb.core.internal.resource.classpath.ClassPathResource.read(ClassPathResource.java:114)
        ... 146 more
```

And again, disabling Gradle daemon fixes the problem.

I think this issue should be reopened.

**Comment by lukaseder** [comment]
> I think this issue should be reopened.

What makes you think this is a issue caused by jOOQ, and not by your specific build?

**Comment by zarebski-m** [comment]
> What makes you think this is a issue caused by jOOQ, and not by your specific build?

There are several reasons:

1. Reproduction project shows that there is nothing really unusual with the setup, just several quite ordinary project dependencies.
2. The same issue is present when using either Flyway or Liquibase.
3. There is no issue when using different jOOQ codegen plugin: https://github.com/etiennestuder/gradle-jooq-plugin – this one works without problems with no changes to the setup.

**Comment by lukaseder** [comment]
Thanks for the clarifications, I'll have another look.

**Comment by lukaseder** [comment]
I'm still not sure why this should have anything to do with jOOQ and not with gradle and how Flyway interacts with jar files being managed by gradle's daemon.

Try removing Flyway and loading the SQL files directly from the classpath, executing them e.g. with jOOQ:

```patch
diff --git a/migration-container/src/main/java/com/example/codegen/PostgresFlywayDatabase.kt b/migration-container/src/main/java/com/example/codegen/PostgresFlywayDatabase.kt
index cb5e1af..728b6a3 100644
--- a/migration-container/src/main/java/com/example/codegen/PostgresFlywayDatabase.kt
+++ b/migration-container/src/main/java/com/example/codegen/PostgresFlywayDatabase.kt
@@ -1,14 +1,18 @@
 package com.example.codegen

-import org.flywaydb.core.Flyway
 import org.jooq.DSLContext
 import org.jooq.SQLDialect
+import org.jooq.Source
 import org.jooq.exception.DataAccessException
 import org.jooq.impl.DSL
 import org.jooq.meta.postgres.PostgresDatabase
 import org.testcontainers.containers.PostgreSQLContainer
 import org.testcontainers.utility.DockerImageName
-import java.nio.charset.StandardCharsets
+import java.io.BufferedReader
+import java.io.File
+import java.io.InputStream
+import java.io.InputStreamReader
+

 class PostgresFlywayDatabase : PostgresDatabase() {
     private lateinit var container: PostgreSQLContainer<*>
@@ -25,19 +29,38 @@ class PostgresFlywayDatabase : PostgresDatabase() {
             container.start()
             connection = container.createConnection("")

+            val ctx = DSL.using(connection, SQLDialect.POSTGRES);
+
+            execute(ctx, "/db/migration/V1__initial_setup.sql");
+            execute(ctx, "/db/migration/V2__dummy.sql");
+            execute(ctx, "/db/migration/V3__dummy.sql");
+
+            /*
             Flyway.configure()
                 .dataSource(container.getJdbcUrl(), "test", "test")
                 .locations("db/migration")
                 .encoding(StandardCharsets.UTF_8)
                 .load()
                 .migrate()
-
-            return DSL.using(connection, SQLDialect.POSTGRES)
+*/
+            return ctx
         } catch (e: Exception) {
             throw DataAccessException("Error while preparing schema for code generation", e)
         }
     }

+    private fun execute(ctx: DSLContext, path: String) {
+        val r = javaClass.getResource(path)
+
+        if (r != null) {
+            javaClass.getResourceAsStream(path).use {
+                val sql = Source.of(it).readString()
+                println("Executing: $sql")
+                ctx.parser().parse(sql).executeBatch()
+            }
+        }
+    }
+
     override fun close() {
         container.close()
         super.close()
```

Now, add your `V2__dummy.sql` script and re-run `./gradlew jooqCodegen --stacktrace`.

I'm not a gradle pro - I don't know what could be the conflict with the daemon here, but the library that reads from objects built with gradle (the jar file) isn't jOOQ, it's Flyway (or Liquibase), so I don't really know what you're expecting here.

You haven't shown a working example with the third party plugin. I don't know what could possibly be different there. If you can point me to the exact "mistake" jOOQ is making (you never know with gradle), then I'll be happy to have another look.
