### ISSUE TITLE
MULTISET not working in MySQL 8.4.0

### ISSUE THREAD

**Issue by julianomqs** [jOOQ/jOOQ#17003]
### Expected behavior

I expect the MULTISET construct work properly in jooq.

### Actual behavior

The construct did not work, and the following stacktrace was printed:

```
2024-07-31 21:43:11,372 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /invoices failed, error id: 0ac7ff89-3eb8-4b61-81c3-21550661ba9b-4: org.jooq.exception.DataAccessException: SQL [set @t = @@group_concat_max_len; set @@group_concat_max_len = 4294967295; select `invoice`.`id`, `invoice`.`datetime`, (select coalesce(json_merge_preserve('[]', concat('[', group_concat(json_array(t.`v0`, t.`v1`, t.`v2`) separator ','), ']')), json_array()) from (select `invoice_item`.`id` as `v0`, `invoice_item`.`quantity` as `v1`, `invoice_item`.`unit_value` as `v2` from `invoice_item` where `invoice_item`.`invoice_id` = `invoice`.`id`) as t) as `items` from `invoice`; set @@group_concat_max_len = @t;]; You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'set @@group_concat_max_len = 4294967295; select `invoice`.`id`, `invoice`.`datet' at line 1
server-1  |     at org.jooq_3.19.10.MYSQL.debug(Unknown Source)
server-1  |     at org.jooq.impl.Tools.translate(Tools.java:3607)
server-1  |     at org.jooq.impl.Tools.translate(Tools.java:3595)
server-1  |     at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:827)
server-1  |     at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:362)
server-1  |     at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:301)
server-1  |     at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:322)
server-1  |     at org.jooq.impl.SelectImpl.fetchLazyNonAutoClosing(SelectImpl.java:3256)
server-1  |     at org.jooq.impl.ResultQueryTrait.collect(ResultQueryTrait.java:360)
server-1  |     at org.jooq.impl.ResultQueryTrait.fetchInto(ResultQueryTrait.java:1434)
server-1  |     at org.acme.InvoiceResource.findAllInvoices(InvoiceResource.java:39)
server-1  |     at org.acme.InvoiceResource$quarkusrestinvoker$findAllInvoices_4d29e0589da157f4763f06674d34a95a626dc8c2.invoke(Unknown Source)
server-1  |     at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
server-1  |     at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
server-1  |     at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
server-1  |     at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
server-1  |     at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
server-1  |     at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
server-1  |     at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
server-1  |     at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
server-1  |     at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
server-1  |     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
server-1  |     at java.base/java.lang.Thread.run(Thread.java:1583)
server-1  | Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'set @@group_concat_max_len = 4294967295; select `invoice`.`id`, `invoice`.`datet' at line 1
server-1  |     at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
server-1  |     at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
server-1  |     at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:912)
server-1  |     at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354)
server-1  |     at io.agroal.pool.wrapper.PreparedStatementWrapper.execute(PreparedStatementWrapper.java:301)
server-1  |     at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
server-1  |     at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4941)
server-1  |     at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:236)
server-1  |     at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:348)
server-1  |     ... 18 more
```

### Steps to reproduce the problem

The problem can be seen in the mcve in https://github.com/julianomqs/jooq-mcve

Steps

1. Create a .env file with the configuration

```
DB_DATABASE=mcve
DB_USER=root
DB_PASSWORD=root
DB_EXTERNAL_PORT=3306

SERVER_EXTERNAL_PORT=3000
SERVER_DEBUG_PORT=5005
```

2. Run the command `docker compose build`

3. Run the command `docker compose up -d`

4. Access the url http://localhost:3000/invoices via Postman and see the error in console

### jOOQ Version

3.19.10

### Database product and version

MySQL 8.4.0

### Java Version

21

### JDBC / R2DBC driver name and version (include name if unofficial driver)

quarkus-jdbc-mysql 3.13.0

**Comment by lukaseder** [comment]
See any of these:

- https://stackoverflow.com/q/70351547/521799
- https://github.com/jOOQ/jOOQ/issues/15838
- https://github.com/jOOQ/jOOQ/issues/12119
- https://blog.jooq.org/mysqls-allowmultiqueries-flag-with-jdbc-and-jooq/
- https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/settings-group-concat/

In short, set the `allowMultiQueries=true` flag
