### ISSUE TITLE
Postgres: Creating a view of a column of type double precision[48][6] is generated as Double[], not Double[][] 

### ISSUE THREAD

**Issue by gromlin2** [jOOQ/jOOQ#17058]
### Expected behavior

I have this sample migration script:
```
DROP SCHEMA IF EXISTS mcve CASCADE;

CREATE SCHEMA mcve;

CREATE TABLE mcve.test (
  some_array  double precision[48][6]
);

CREATE VIEW mcve.test_view AS (
select * from mcve.test
);
```

I expect the generated records and tables for the view to be of type Double[][] and SQLDataType.FLOAT.array().array() (as they are for the table).

I also expect this test to pass:
```
    @Test
    public void mcveTest() {
        final Double[][] array =
            new Double[][] { new Double[] { 1.0, 2.0 }, new Double[] { 3.0, 4.0 } };

        // insert array into the Table
        assertEquals(1,
            ctx.insertInto(TEST)
               .columns(TEST.SOME_ARRAY)
               .values(array)
               .execute()
        );

        // read the array from the view
        TestViewRecord record = ctx.fetchOne(TEST_VIEW);

        assertArrayEquals(array, record.getSomeArray());
    }
```

### Actual behavior

The generated code for the view sees only Double[], not Double[][]:
```
public class TestViewRecord extends TableRecordImpl<TestViewRecord> {
...
    public void setSomeArray(Double[] value) {
        set(0, value);
    }
...
}
```
and
```
public class TestView extends TableImpl<TestViewRecord> {
...
    public final TableField<TestViewRecord, Double[]> SOME_ARRAY = createField(DSL.name("some_array"), SQLDataType.FLOAT.array(), this, "");
...
}
```

The test fails with the following logs:
```
09:25:44,768 DEBUG [org.jooq.impl.AbstractQuery                       ] - DELETE without WHERE     : A statement is executed without WHERE clause
09:25:44,781  INFO [org.jooq.Constants                                ] - 
                                      
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@  @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@        @@@@@@@@@@
@@@@@@@@@@@@@@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@  @@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@        @@  @  @  @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@  @@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  Thank you for using jOOQ 3.19.10 (Build date: 2024-06-14T07:35:03Z)
                                      
09:25:44,782  INFO [org.jooq.Constants                                ] - 

jOOQ tip of the day: Want to collect a flat representation of tree data into a hierarchy? Use this Collector based approach: https://blog.jooq.org/how-to-turn-a-list-of-flat-elements-into-a-hierarchy-in-java-sql-or-jooq/

09:25:44,821 DEBUG [org.jooq.tools.LoggerListener                     ] - Executing query          : delete from "mcve"."test"
09:25:44,827  INFO [jooq.impl.DefaultExecuteContext.logVersionSupport ] - Version                  : Database version is supported by dialect POSTGRES: 16.4 (Debian 16.4-1.pgdg120+1)
09:25:44,835 DEBUG [org.jooq.tools.LoggerListener                     ] - Affected row(s)          : 0
09:25:44,864 DEBUG [org.jooq.tools.LoggerListener                     ] - Executing query          : insert into "mcve"."test" ("some_array") values (cast(? as float8[][]))
09:25:44,867 DEBUG [org.jooq.tools.LoggerListener                     ] - -> with bind values      : insert into "mcve"."test" ("some_array") values (cast('{{1.0,2.0},{3.0,4.0}}' as float8[][]))
09:25:44,871 DEBUG [org.jooq.tools.LoggerListener                     ] - Affected row(s)          : 1
09:25:45,209 DEBUG [org.jooq.tools.LoggerListener                     ] - Executing query          : select "mcve"."test_view"."some_array" from "mcve"."test_view"
09:25:45,258 ERROR [org.jooq.impl.DefaultBinding                      ] - Cannot parse array       : {{1,2},{3,4}}
org.postgresql.util.PSQLException: Bad value for type double : {"1","2"}
	at org.postgresql.jdbc.PgResultSet.toDouble(PgResultSet.java:3441) ~[postgresql-42.7.2.jar:42.7.2]
	at org.postgresql.jdbc.PgResultSet.getDouble(PgResultSet.java:2748) ~[postgresql-42.7.2.jar:42.7.2]
	at org.jooq.impl.DefaultBinding$DefaultDoubleBinding.lambda$get0$2(DefaultBinding.java:2862) ~[jooq-3.19.10.jar:?]
	at org.jooq.impl.DefaultBinding$DefaultDoubleBinding.fixInfinity(DefaultBinding.java:2799) ~[jooq-3.19.10.jar:?]
	at org.jooq.impl.DefaultBinding$DefaultDoubleBinding.fixInfinity(DefaultBinding.java:2788) ~[jooq-3.19.10.jar:?]
	at org.jooq.impl.DefaultBinding$DefaultDoubleBinding.get0(DefaultBinding.java:2861) ~[jooq-3.19.10.jar:?]
	at org.jooq.impl.DefaultBinding$DefaultDoubleBinding.get0(DefaultBinding.java:2727) ~[jooq-3.19.10.jar:?]
	at org.jooq.impl.DefaultBinding$InternalBinding.get(DefaultBinding.java:1129) ~[jooq-3.19.10.jar:?]
	at org.jooq.impl.DefaultBinding$DefaultArrayBinding.pgGetArray(DefaultBinding.java:1501) [jooq-3.19.10.jar:?]
	at org.jooq.impl.DefaultBinding$DefaultArrayBinding.get0(DefaultBinding.java:1426) [jooq-3.19.10.jar:?]
	at org.jooq.impl.DefaultBinding$DefaultArrayBinding.get0(DefaultBinding.java:1280) [jooq-3.19.10.jar:?]
	at org.jooq.impl.DefaultBinding$InternalBinding.get(DefaultBinding.java:1129) [jooq-3.19.10.jar:?]
	at org.jooq.impl.CursorImpl$CursorRecordInitialiser.setValue(CursorImpl.java:1582) [jooq-3.19.10.jar:?]
	at org.jooq.impl.CursorImpl$CursorRecordInitialiser.apply(CursorImpl.java:1518) [jooq-3.19.10.jar:?]
	at org.jooq.impl.CursorImpl$CursorRecordInitialiser.apply(CursorImpl.java:1433) [jooq-3.19.10.jar:?]
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144) [jooq-3.19.10.jar:?]
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1390) [jooq-3.19.10.jar:?]
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1366) [jooq-3.19.10.jar:?]
	at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:174) [jooq-3.19.10.jar:?]
	at org.jooq.impl.Tools.fetchOne(Tools.java:2881) [jooq-3.19.10.jar:?]
	at org.jooq.impl.Tools.fetchOne(Tools.java:2857) [jooq-3.19.10.jar:?]
	at org.jooq.impl.DefaultDSLContext.fetchOne(DefaultDSLContext.java:5209) [jooq-3.19.10.jar:?]
	at org.jooq.impl.DefaultDSLContext.fetchOne(DefaultDSLContext.java:5204) [jooq-3.19.10.jar:?]
	at org.jooq.mcve.test.java.postgres.JavaTest.mcveTest(JavaTest.java:97) [test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) [junit-4.13.2.jar:4.13.2]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.13.2.jar:4.13.2]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69) [junit-rt.jar:?]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11) [idea_rt.jar:?]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55) [junit-rt.jar:?]
09:25:45,260 DEBUG [org.jooq.tools.LoggerListener                     ] - Fetched result           : +----------+
09:25:45,260 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : |some_array|
09:25:45,260 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : +----------+
09:25:45,260 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : |{null}    |
09:25:45,260 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : +----------+
09:25:45,260 DEBUG [org.jooq.tools.LoggerListener                     ] - Fetched row(s)           : 1

java.lang.AssertionError: actual array was null

	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:49)
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:28)
	at org.junit.Assert.internalArrayEquals(Assert.java:534)
	at org.junit.Assert.assertArrayEquals(Assert.java:285)
	at org.junit.Assert.assertArrayEquals(Assert.java:300)
	at org.jooq.mcve.test.java.postgres.JavaTest.mcveTest(JavaTest.java:99)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
```

### Steps to reproduce the problem

- Checkout https://github.com/jOOQ/jOOQ-mcve/tree/main/jOOQ-mcve-java-postgres
- Change init SQL to 
```DROP SCHEMA IF EXISTS mcve CASCADE;

CREATE SCHEMA mcve;

CREATE TABLE mcve.test (
  some_array  double precision[48][6]
);

CREATE VIEW mcve.test_view AS (
select * from mcve.test
);
```
- Update JavaTest to
```
    @Test
    public void mcveTest() {
        final Double[][] array =
            new Double[][] { new Double[] { 1.0, 2.0 }, new Double[] { 3.0, 4.0 } };

        // insert array into the Table
        assertEquals(1,
            ctx.insertInto(TEST)
               .columns(TEST.SOME_ARRAY)
               .values(array)
               .execute()
        );

        // read the array from the view
        TestViewRecord record = ctx.fetchOne(TEST_VIEW);

        assertArrayEquals(array, record.getSomeArray());
    }
```
- Generate code
- Run test & look at generated code

### jOOQ Version

3.19.10

### Database product and version

postgres:latest, postgres 12

### Java Version

17, 21

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.2

**Comment by lukaseder** [comment]
Thanks for your message.

PostgreSQL doesn't really support multi dimensional arrays. Its implementation is quite... wishy-washy :)

Try this, it works:

```sql
select array[1]::int[][], array[array[1]]::int[]
```

Anyway, we're trying to reverse engineer the `pg_attribute.attndims` value, but try this:

```sql
select pg_catalog.format_type(a.atttypid, a.atttypmod), a.attndims 
from pg_attribute a
where attname = 'some_array';
```

You'll get:

```
|format_type       |attndims|
|------------------|--------|
|double precision[]|2       |
|double precision[]|0       |
```

I.e. the dimension info is lost for the view. I don't think jOOQ can do much, here? You can apply a data type rewrite, of course:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types/codegen-database-forced-types-rewrite/

**Comment by gromlin2** [comment]
Thanks for the quick response.

I can confirm, this makes the test pass:
```
<forcedType>
    <name>double precision[][]</name>
    <userType>java.lang.Double[][]</userType>
    <includeExpression>test_view\.some_array</includeExpression>
</forcedType>
```

I'm not entirely certain, by entry for <name></name> is what's expected though.

**Comment by lukaseder** [comment]
> I'm not entirely certain, by entry for is what's expected though.

What do you mean by that?

**Comment by gromlin2** [comment]
Sorry, that was a typo.

Essentially, I'm not sure, what exact forcedType I need to use to tell jOOQ I'm dealing with a multidimensional double array.
Particularly, what has to go into the "name" tag?

**Comment by lukaseder** [comment]
The name element needs to declare a PostgreSQL compatible type, so e.g. `double precision[][]` is fine
