### ISSUE TITLE
Getting exception when trying to use generated field.getDataType() to create another field

### ISSUE THREAD

**Issue by anshuman-mor** [jOOQ/jOOQ#17062]
### Expected behavior

I am trying to create a table out an enum class on the fly with following code - 

```java
@UtilityClass
public class EnumTables {
    private static final String COLUMN_NAME = "type";

    public static final Field<ReleaseWindowStatusE> RW_STATUS = field("TBL_RW_STATUS", RW.STATUS.getDataType());
    public static final Table<Record1<ReleaseWindowStatusE>> TBL_RW_STATUS = table(RW_STATUS, ReleaseWindowStatusE.class);

    private static <T, E extends Enum<E>> Table<Record1<E>> table(Field<E> field, Class<E> clazz) {
        return table(field, clazz.getEnumConstants());
    }

    @SafeVarargs
    private static <T, E extends Enum<E>> Table<Record1<E>> table(Field<E> field, E...enums) {
        var tblName = field.getQualifiedName().first();
        var table = DSL.select(field).asTable(tblName);
        return Stream.of(enums)
            .map(e -> query(table, field, e))
            .reduce(Select::union)
            .get().asTable(table);
    }

    private static <E extends Enum<E>> Field<E> field(String tblName, DataType<E> dataType) {
        return DSL.field(DSL.name(tblName, COLUMN_NAME), dataType);
    }

    private static <E extends Enum<E>> Select<Record1<E>> query(Table<Record1<E>> table, Field<E> f, E v) {
        return DSL.select(DSL.inline(v).as(f));
    }
}

```
I am inserting ENUM constant directly in column, and using Jooq EnumConverter for Java to SQL data type conversion.

This all works fine but I get this exception everytime when the table and column gets initialized, why can't I refer the datatype of the column?

### Actual behavior

```
2024-08-14T14:20:37.619+05:30  WARN 3716 --- [mcat-handler-16] o.jooq.impl.DefaultDataType.getDataType  : Static type registry     : The deprecated static type registry was being accessed for a non-built-in data type: varchar(36) /* com.digicert.one.stm.enums.CertificateStatusE */.

It is strongly recommended not looking up DataType<T> references from Class<T> references by
relying on the internal static type registry. For example, avoid calling DSL.val(Object) or
DSL.val(Object, Class), and call DSL.val(Object, DataType), providing an explicit DataType
reference to jOOQ if your DataType uses a Converter or a Binding. If you think jOOQ should
be able to infer your user type in your particular query, please report a bug here:
https://jooq.org/bug

See https://github.com/jOOQ/jOOQ/issues/15286 for more details.
```

### Steps to reproduce the problem

```
2024-08-14T14:20:37.619+05:30  WARN 3716 --- [mcat-handler-16] o.jooq.impl.DefaultDataType.getDataType  : Static type registry     : The deprecated static type registry was being accessed for a non-built-in data type: varchar(36) /* com.digicert.one.stm.enums.CertificateStatusE */.

It is strongly recommended not looking up DataType<T> references from Class<T> references by
relying on the internal static type registry. For example, avoid calling DSL.val(Object) or
DSL.val(Object, Class), and call DSL.val(Object, DataType), providing an explicit DataType
reference to jOOQ if your DataType uses a Converter or a Binding. If you think jOOQ should
be able to infer your user type in your particular query, please report a bug here:
https://jooq.org/bug

See https://github.com/jOOQ/jOOQ/issues/15286 for more details.


org.jooq.impl.DefaultDataType$DiscouragedStaticTypeRegistryUsage: null
        at org.jooq.impl.DefaultDataType.check(DefaultDataType.java:844) ~[stm-app.exe:na]
        at org.jooq.impl.Val.accept(Val.java:192) ~[stm-app.exe:na]
        at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:731) ~[stm-app.exe:na]
        at org.jooq.impl.AbstractContext.visit(AbstractContext.java:332) ~[stm-app.exe:na]
        at org.jooq.impl.Alias.toSQLWrapped(Alias.java:431) ~[stm-app.exe:na]
        at org.jooq.impl.Alias.toSQLWrapped(Alias.java:416) ~[stm-app.exe:na]
        at org.jooq.impl.Alias.acceptDeclareAliasStandard(Alias.java:338) ~[stm-app.exe:na]
        at org.jooq.impl.Alias.accept(Alias.java:207) ~[stm-app.exe:na]
        at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:731) ~[stm-app.exe:na]
        at org.jooq.impl.AbstractContext.visit(AbstractContext.java:381) ~[stm-app.exe:na]
        at org.jooq.impl.FieldAlias.accept(FieldAlias.java:72) ~[stm-app.exe:na]
        at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:731) ~[stm-app.exe:na]
        at org.jooq.impl.AbstractContext.visit(AbstractContext.java:381) ~[stm-app.exe:na]
        at org.jooq.impl.QueryPartCollectionView.acceptElement(QueryPartCollectionView.java:256) ~[stm-app.exe:na]
        at org.jooq.impl.SelectFieldList.lambda$acceptElement0$0(SelectFieldList.java:99) ~[stm-app.exe:na]
        at org.jooq.impl.Tools.visitAutoAliased(Tools.java:2937) ~[stm-app.exe:na]
        at org.jooq.impl.SelectFieldList.acceptElement0(SelectFieldList.java:99) ~[stm-app.exe:na]
        at org.jooq.impl.SelectFieldList.acceptElement(SelectFieldList.java:90) ~[stm-app.exe:na]
        at org.jooq.impl.SelectFieldList.acceptElement(SelectFieldList.java:50) ~[stm-app.exe:na]
        at org.jooq.impl.QueryPartCollectionView.accept(QueryPartCollectionView.java:226) ~[stm-app.exe:na]
        at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:731) ~[stm-app.exe:na]
        at org.jooq.impl.AbstractContext.visit(AbstractContext.java:381) ~[stm-app.exe:na]
        at org.jooq.impl.SelectQueryImpl.toSQLReference0(SelectQueryImpl.java:2445) ~[stm-app.exe:na]
        at org.jooq.impl.SelectQueryImpl.lambda$toSQLReferenceLimitDefault$8(SelectQueryImpl.java:2063) ~[stm-app.exe:na]
        at org.jooq.impl.AbstractContext.data(AbstractContext.java:415) ~[stm-app.exe:na]
        at org.jooq.impl.SelectQueryImpl.toSQLReferenceLimitDefault(SelectQueryImpl.java:2063) ~[stm-app.exe:na]
        at org.jooq.impl.SelectQueryImpl.accept0(SelectQueryImpl.java:1905) ~[stm-app.exe:na]
        at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:1564) ~[stm-app.exe:na]
        at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:731) ~[stm-app.exe:na]
        at org.jooq.impl.AbstractContext.visit(AbstractContext.java:381) ~[stm-app.exe:na]
        at org.jooq.impl.AbstractDelegatingQuery.accept(AbstractDelegatingQuery.java:90) ~[stm-app.exe:na]
        at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:731) ~[stm-app.exe:na]
        at org.jooq.impl.AbstractContext.visit(AbstractContext.java:381) ~[stm-app.exe:na]
        at org.jooq.impl.SelectQueryImpl.toSQLReference0(SelectQueryImpl.java:2737) ~[stm-app.exe:na]
        at org.jooq.impl.SelectQueryImpl.lambda$toSQLReferenceLimitDefault$8(SelectQueryImpl.java:2063) ~[stm-app.exe:na]
        at org.jooq.impl.AbstractContext.data(AbstractContext.java:415) ~[stm-app.exe:na]
        at org.jooq.impl.SelectQueryImpl.toSQLReferenceLimitDefault(SelectQueryImpl.java:2063) ~[stm-app.exe:na]
        at org.jooq.impl.SelectQueryImpl.accept0(SelectQueryImpl.java:1905) ~[stm-app.exe:na]
        at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:1564) ~[stm-app.exe:na]
        at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:731) ~[stm-app.exe:na]
        at org.jooq.impl.AbstractContext.visit(AbstractContext.java:381) ~[stm-app.exe:na]
        at org.jooq.impl.Tools.visitSubquery(Tools.java:2979) ~[stm-app.exe:na]
        at org.jooq.impl.DerivedTable.accept(DerivedTable.java:112) ~[stm-app.exe:na]
        at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:731) ~[stm-app.exe:na]
        at org.jooq.impl.AbstractContext.visit(AbstractContext.java:341) ~[stm-app.exe:na]
        at org.jooq.impl.Alias.toSQLWrapped(Alias.java:431) ~[stm-app.exe:na]
        at org.jooq.impl.Alias.lambda$toSQLWrapped$4(Alias.java:414) ~[stm-app.exe:na]
        at org.jooq.impl.AbstractContext.data(AbstractContext.java:415) ~[stm-app.exe:na]
        at org.jooq.impl.Alias.toSQLWrapped(Alias.java:414) ~[stm-app.exe:na]
        at org.jooq.impl.Alias.acceptDeclareAliasStandard(Alias.java:338) ~[stm-app.exe:na]
        at org.jooq.impl.Alias.accept(Alias.java:207) ~[stm-app.exe:na]
        at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:731) ~[stm-app.exe:na]
        at org.jooq.impl.AbstractContext.visit(AbstractContext.java:381) ~[stm-app.exe:na]
        at org.jooq.impl.TableAlias.accept(TableAlias.java:152) ~[stm-app.exe:na]
        at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:731) ~[stm-app.exe:na]
        at org.jooq.impl.AbstractContext.visit(AbstractContext.java:381) ~[stm-app.exe:na]
        at org.jooq.impl.JoinTable.lambda$toSQLTable$0(JoinTable.java:513) ~[stm-app.exe:na]
        at org.jooq.impl.Tools.visitAutoAliased(Tools.java:2937) ~[stm-app.exe:na]
        at org.jooq.impl.JoinTable.toSQLTable(JoinTable.java:513) ~[stm-app.exe:na]
        at org.jooq.impl.JoinTable.accept0(JoinTable.java:270) ~[stm-app.exe:na]
        at org.jooq.impl.JoinTable.accept(JoinTable.java:262) ~[stm-app.exe:na]
        at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:731) ~[stm-app.exe:na]
        at org.jooq.impl.AbstractContext.visit(AbstractContext.java:381) ~[stm-app.exe:na]
        at org.jooq.impl.QueryPartCollectionView.acceptElement(QueryPartCollectionView.java:256) ~[stm-app.exe:na]
        at org.jooq.impl.TableList.lambda$acceptElement$0(TableList.java:87) ~[stm-app.exe:na]
        at org.jooq.impl.Tools.visitAutoAliased(Tools.java:2937) ~[stm-app.exe:na]
        at org.jooq.impl.TableList.acceptElement(TableList.java:87) ~[stm-app.exe:na]
        at org.jooq.impl.TableList.acceptElement(TableList.java:63) ~[stm-app.exe:na]
        at org.jooq.impl.QueryPartCollectionView.accept(QueryPartCollectionView.java:226) ~[stm-app.exe:na]
        at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:731) ~[stm-app.exe:na]
        at org.jooq.impl.AbstractContext.visit(AbstractContext.java:381) ~[stm-app.exe:na]
        at org.jooq.impl.SelectQueryImpl.toSQLReference0(SelectQueryImpl.java:2550) ~[stm-app.exe:na]
        at org.jooq.impl.SelectQueryImpl.lambda$toSQLReferenceLimitDefault$8(SelectQueryImpl.java:2063) ~[stm-app.exe:na]
        at org.jooq.impl.AbstractContext.data(AbstractContext.java:415) ~[stm-app.exe:na]
        at org.jooq.impl.SelectQueryImpl.toSQLReferenceLimitDefault(SelectQueryImpl.java:2063) ~[stm-app.exe:na]
        at org.jooq.impl.SelectQueryImpl.accept0(SelectQueryImpl.java:1905) ~[stm-app.exe:na]
        at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:1564) ~[stm-app.exe:na]
        at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:731) ~[stm-app.exe:na]
        at org.jooq.impl.AbstractContext.visit(AbstractContext.java:381) ~[stm-app.exe:na]
        at org.jooq.impl.DefaultRenderContext$Rendered.rendered(DefaultRenderContext.java:1078) ~[stm-app.exe:na]
        at org.jooq.impl.AbstractQuery.getSQL0(AbstractQuery.java:498) ~[stm-app.exe:na]
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:303) ~[stm-app.exe:na]
        at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:301) ~[stm-app.exe:na]
        at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:322) ~[stm-app.exe:na]
        at org.jooq.impl.SelectImpl.fetchLazyNonAutoClosing(SelectImpl.java:3256) ~[stm-app.exe:na]
        at org.jooq.impl.ResultQueryTrait.collect(ResultQueryTrait.java:360) ~[stm-app.exe:na]
        at org.jooq.impl.ResultQueryTrait.fetchInto(ResultQueryTrait.java:1434) ~[stm-app.exe:na]
```

### jOOQ Version

jooq-3.19.8

### Database product and version

MariadDB 10.6

### Java Version

openjdk 21

### JDBC / R2DBC driver name and version (include name if unofficial driver)

jdbc:mariadb://127.0.0.1:3306/my-database?serverTimezone=UTC

**Comment by lukaseder** [comment]
Just do this instead, and you should be fine:

```java
    private static <E extends Enum<E>> Select<Record1<E>> query(Table<Record1<E>> table, Field<E> f, E v) {
        return DSL.select(DSL.inline(v, f).as(f)); // Pass the Field to DSL.inline()
    }
```
