### ISSUE TITLE
Fix R2DBC support for TIMESTAMP WITH TIME ZONE types

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#17088]
We currently don't integration test `TIMESTAMP WITH TIME ZONE` type support via R2DBC. Thus, this may not work in some dialects, see:

- https://stackoverflow.com/q/78856811/521799

E.g.  in H2, this stack trace occurs:

```
org.jooq.exception.DataException: SQL [select cast($1 as timestamp with time zone), cast($2 as timestamp with time zone)]; Data conversion error converting "CHARACTER LARGE OBJECT to TIMESTAMP WITH TIME ZONE"; SQL statement:
select cast($1 as timestamp with time zone), cast($2 as timestamp with time zone) [22018-232]
	at org.jooq.impl.Tools.translate(Tools.java:3632)
	at org.jooq.impl.Tools.translate(Tools.java:3614)
	at org.jooq.impl.Tools.translate(Tools.java:3598)
	at org.jooq.impl.R2DBC$AbstractResultSubscriber.lambda$0(R2DBC.java:285)
	at org.jooq.impl.Internal$1.onComplete(Internal.java:828)
	at org.jooq.test.setup.DatabaseSetup$1$2.lambda$4(DatabaseSetup.java:450)
	at org.jooq.impl.Internal$1.onComplete(Internal.java:828)
	at reactor.core.publisher.StrictSubscriber.onComplete(StrictSubscriber.java:123)
	at reactor.core.publisher.Operators.complete(Operators.java:137)
	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4512)
	at org.jooq.test.setup.DatabaseSetup$1$2.lambda$0(DatabaseSetup.java:441)
	at org.jooq.tools.r2dbc.LoggingConnection.lambda$2(LoggingConnection.java:93)
	at org.jooq.impl.R2DBC$AbstractNonBlockingSubscription.lambda$6(R2DBC.java:660)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
	at org.jooq.impl.R2DBC$AbstractNonBlockingSubscription.cancel0(R2DBC.java:644)
	at org.jooq.impl.R2DBC$AbstractSubscription.complete(R2DBC.java:210)
	at org.jooq.impl.R2DBC$AbstractResultSubscriber.complete(R2DBC.java:300)
	at org.jooq.impl.R2DBC$AbstractResultSubscriber.onError(R2DBC.java:285)
	at reactor.core.publisher.StrictSubscriber.onError(StrictSubscriber.java:106)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:142)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
	at reactor.core.publisher.FluxIterable$IterableSubscription.fastPath(FluxIterable.java:402)
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:291)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:171)
	at reactor.core.publisher.StrictSubscriber.onSubscribe(StrictSubscriber.java:77)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:201)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:83)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8777)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:202)
	at reactor.core.publisher.FluxFlatMap.subscribeOrReturn(FluxFlatMap.java:94)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8762)
	at org.jooq.tools.r2dbc.LoggingStatement.lambda$0(LoggingStatement.java:112)
	at org.jooq.impl.R2DBC$QueryExecutionSubscriber.onNext0(R2DBC.java:456)
	at org.jooq.impl.R2DBC$ConnectionSubscriber.onNext(R2DBC.java:393)
	at org.jooq.impl.R2DBC$AbstractNonBlockingSubscription.lambda$1(R2DBC.java:605)
	at org.jooq.impl.Internal$1.onNext(Internal.java:818)
	at org.jooq.test.setup.DatabaseSetup$1.lambda$2(DatabaseSetup.java:422)
	at org.jooq.impl.Internal$1.onNext(Internal.java:818)
	at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.MonoSupplier$MonoSupplierSubscription.request(MonoSupplier.java:145)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:171)
	at reactor.core.publisher.StrictSubscriber.onSubscribe(StrictSubscriber.java:77)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96)
	at reactor.core.publisher.MonoSupplier.subscribe(MonoSupplier.java:48)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4512)
	at org.jooq.test.setup.DatabaseSetup$1.lambda$0(DatabaseSetup.java:418)
	at org.jooq.impl.R2DBC$AbstractNonBlockingSubscription.request0(R2DBC.java:602)
	at org.jooq.impl.ThreadGuard.lambda$0(ThreadGuard.java:74)
	at org.jooq.impl.ThreadGuard.run(ThreadGuard.java:87)
	at org.jooq.impl.ThreadGuard.run(ThreadGuard.java:74)
	at org.jooq.impl.R2DBC$AbstractSubscription.request(R2DBC.java:190)
	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.request(Operators.java:2067)
	at reactor.core.publisher.BlockingSingleSubscriber.onSubscribe(BlockingSingleSubscriber.java:53)
	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.onSubscribe(Operators.java:2051)
	at org.jooq.impl.ResultQueryTrait.subscribe(ResultQueryTrait.java:370)
	at org.jooq.impl.SelectImpl.subscribe(SelectImpl.java:3226)
	at reactor.core.publisher.FluxSource.subscribe(FluxSource.java:71)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4512)
	at reactor.core.publisher.Mono.block(Mono.java:1727)
	at org.jooq.test.all.testcases.R2DBCTests.lambda$12(R2DBCTests.java:361)
	at org.jooq.test.jOOQAbstractTest.withDSLContext(jOOQAbstractTest.java:2683)
	at org.jooq.test.jOOQAbstractTest.bindAndInlineWithDSLContexts(jOOQAbstractTest.java:2676)
	at org.jooq.test.BaseTest.bindAndInlineWithDSLContexts(BaseTest.java:2383)
	at org.jooq.test.all.testcases.R2DBCTests.testR2DBCFetchTypesTemporalJava8(R2DBCTests.java:352)
	at org.jooq.test.jOOQAbstractTest.testR2DBCFetchTypesTemporalJava8(jOOQAbstractTest.java:3403)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:757)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103)
		at reactor.core.publisher.Mono.block(Mono.java:1728)
		... 36 more
Caused by: io.r2dbc.h2.H2DatabaseExceptionFactory$H2R2dbcDataException: [22018] [22018] Data conversion error converting "CHARACTER LARGE OBJECT to TIMESTAMP WITH TIME ZONE"; SQL statement:
select cast($1 as timestamp with time zone), cast($2 as timestamp with time zone) [22018-232]
	at io.r2dbc.h2.H2DatabaseExceptionFactory.convert(H2DatabaseExceptionFactory.java:60)
	at io.r2dbc.h2.client.SessionClient.query(SessionClient.java:138)
	at io.r2dbc.h2.H2Statement.lambda$execute$2(H2Statement.java:145)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113)
	... 76 more
Caused by: org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "CHARACTER LARGE OBJECT to TIMESTAMP WITH TIME ZONE"; SQL statement:
select cast($1 as timestamp with time zone), cast($2 as timestamp with time zone) [22018-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:518)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.value.Value.getDataConversionError(Value.java:2591)
	at org.h2.value.Value.convertToTimestampTimeZone(Value.java:2076)
	at org.h2.value.Value.convertTo(Value.java:1181)
	at org.h2.value.Value.castTo(Value.java:1101)
	at org.h2.expression.function.CastSpecification.getValue(CastSpecification.java:52)
	at org.h2.expression.function.Function1_2.getValue(Function1_2.java:39)
	at org.h2.command.query.Select$LazyResultQueryFlat.fetchNextRow(Select.java:1897)
	at org.h2.result.LazyResult.hasNext(LazyResult.java:78)
	at org.h2.result.FetchedResult.next(FetchedResult.java:34)
	at org.h2.command.query.Select.readWithLimit(Select.java:778)
	at org.h2.command.query.Select.queryFlat(Select.java:771)
	at org.h2.command.query.Select.queryWithoutCache(Select.java:891)
	at org.h2.command.query.Query.queryWithoutCacheLazyCheck(Query.java:211)
	at org.h2.command.query.Query.query(Query.java:530)
	at org.h2.command.query.Query.query(Query.java:498)
	at org.h2.command.CommandContainer.query(CommandContainer.java:222)
	at org.h2.command.Command.executeQuery(Command.java:196)
	at io.r2dbc.h2.client.SessionClient.query(SessionClient.java:134)
	... 78 more
```

### Dialects to check:

- [x] H2 (fixed by this issue)
- [x] Oracle (fixed by this issue)
- [x] PostgreSQL (already works out of the box)
- [x] SQL Server (fixed by this issue)

Other R2DBC dialects don't have `TIMESTAMP WITH TIME ZONE` support at all, at the moment.

**Comment by lukaseder** [comment]
The problem doesn't appear in H2 when setting `Settings.setBindOffsetDateTimeType(true)`

**Comment by lukaseder** [comment]
The reason for this behaviour is that `r2dbc-h2` uses the `ClobToStringCodec` as a codec to work with for `String.class` first, before the far more appropriate `StringCodec`. It's not possible to tell R2DBC anything about the type (or codec) which it should prefer, at least not via the SPI, so we cannot solve this on the SPI level.

But we could render yet another cast around the bind variable, i.e.:

```sql
-- instead of:
cast($1 as timestamp with time zone)

-- do this:
cast(cast($1 as varchar) as timestamp with time zone)
```

At least, when we're not using `Settings.bindOffsetDateTimeType`

**Comment by lukaseder** [comment]
For SQL Server, we'll probably have to cast bind values to `datetimeoffset` explicitly in order to avoid hassles when converting between string and `OffsetDateTime`. It seems this would be generally more consistent, also for JDBC usage.

**Comment by lukaseder** [comment]
I'll fix this as a bug and backport the fix. Given that this worked for PostgreSQL out of the box, and that both R2DBC and `java.time` support have been around for ages, it would have been safe to assume that this should work out of the box for any dialect.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.12 (https://github.com/jOOQ/jOOQ/issues/17091)
- 3.18.19 (https://github.com/jOOQ/jOOQ/issues/17089)
- 3.17.28 (https://github.com/jOOQ/jOOQ/issues/17090)
