### ISSUE TITLE
 NPE while reading timestamp data type value for SAP SQL Anywhere 17 with jconn4

### ISSUE THREAD

**Issue by ravimergu1** [jOOQ/jOOQ#17203]
### Issue

While reading timestamp column value from Sap SQL Anyware, getting NPE
Error log:
```
java.lang.NullPointerException
		at org.jooq_3.9.1.DEFAULT.debug(Unknown Source)
		at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:739)
		at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:948)
		at org.jooq.impl.MetaDataFieldProvider.init(MetaDataFieldProvider.java:132)
		at org.jooq.impl.MetaDataFieldProvider.<init>(MetaDataFieldProvider.java:83)
		at org.jooq.impl.SQLResultQuery.getFields(SQLResultQuery.java:99)
		at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:285)
		at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:349)
		at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:368)`
```		
		
![Screenshot from 2024-09-04 13-24-44](https://github.com/user-attachments/assets/05cb867a-8f35-43de-b1fb-700ddc3c1154)
![Screenshot from 2024-09-04 13-26-04](https://github.com/user-attachments/assets/9e79051a-0b66-49b0-b1b3-89a2292e0c62)

In the above i used default dialect, if i use the sybase dialect also getting same issue.

_No response_

### Steps to reproduce the problem

Create a table in SAP SQL Anyware; I will have a timestamp column.
Insert a record with timestamp column data.
Read the timestamp column with result query:

```java
context.resultQuery("SELECT doj FROM \"DBA\".\"Test1\"");
```

### jOOQ Version

 jooq pro 3.9.1 and jooq pro 3.17.3

### Database product and version

SAP SQL Anyware 17

### Java Version

open jdk11

### JDBC / R2DBC driver name and version (include name if unofficial driver)

Jconnect4

**Comment by lukaseder** [comment]
Thanks a lot for your report. I'll try to reproduce this, soon.

**Comment by lukaseder** [comment]
I can reproduce this issue:

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because "typeName" is null
	at org.jooq_3.20.0-SNAPSHOT.SYBASE.debug(Unknown Source)
	at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:701)
	at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:1006)
	at org.jooq.impl.MetaDataFieldProvider.init(MetaDataFieldProvider.java:134)
	at org.jooq.impl.MetaDataFieldProvider.<init>(MetaDataFieldProvider.java:78)
	at org.jooq.impl.SQLResultQuery.getFields(SQLResultQuery.java:119)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:234)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:348)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:263)
	at org.jooq.impl.DefaultDSLContext.fetch(DefaultDSLContext.java:870)
	at org.jooq.testscripts.JDBC.main(JDBC.java:42)
```

**Comment by lukaseder** [comment]
It seems there's a bug in jconn4, which is an outdated JDBC driver for use with SQL Anywhere. Use `sajdbc4.jar`, which ships with your SQL Anywhere 17 installation instead, and the problem goes away.

We'll still handle the NPE from our side, just like when a data type cannot be looked up, which translates to `SQLDataType.OTHER`, and which logs a debug warning in jOOQ.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.12 (https://github.com/jOOQ/jOOQ/issues/17213)
- 3.18.19 (https://github.com/jOOQ/jOOQ/issues/17214)
- 3.17.28 (https://github.com/jOOQ/jOOQ/issues/17215)

**Comment by lukaseder** [comment]
This was also cross-posted here: https://stackoverflow.com/q/78956824/521799

**Comment by ravimergu1** [comment]
@lukaseder, What is the ETA for when this fix will be available?

**Comment by lukaseder** [comment]
We'll release the patch versions this or next week. You can access snapshot builds from here, starting tomorrow:
https://www.jooq.org/download/versions

**Comment by ravimergu1** [comment]
@lukaseder 3.17.28-SNAPSHOT is not released today, when will it be released.

**Comment by lukaseder** [comment]
There was an issue with the build for Java 11/8 distributions. The Java 17 distribution is available already. The build is currently running again. Thanks for your patience!

**Comment by lukaseder** [comment]
It is available now

**Comment by lukaseder** [comment]
@ravimergu1 You can see our complete release notes here:

- https://www.jooq.org/notes?version=3.17

Or here:

- https://github.com/jOOQ/jOOQ/releases

**Comment by lukaseder** [comment]
There are no known breaking changes between 3.17.3 and 3.17.28
