### ISSUE TITLE
Meta::filterCatalogs is applied too late for internal MetaImpl queries executed by Meta::ddl

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#17259]
As discovered in this issue's discussions here:

- https://github.com/jOOQ/jOOQ/issues/17255

Doing this:

```java
System.out.println(
    ctx.meta()
        .filterCatalogs(c -> c.getName().equals("test"))
        .ddl()
);
```

Can produce an exception like this, if run with a user that has no rights to access most catalogs:

```
com.microsoft.sqlserver.jdbc.SQLServerException: The server principal "NO_RIGHTS" is not able to access the database "db-10751" under the current security context.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:259)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1695)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:648)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:567)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7675)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:4137)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:272)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:246)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQueryInternal(SQLServerPreparedStatement.java:499)
	at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getSchemasInternal(SQLServerDatabaseMetaData.java:1511)
	at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getSchemas(SQLServerDatabaseMetaData.java:1521)
	at org.jooq.impl.MetaImpl$MetaCatalog.lambda$0(MetaImpl.java:360)
	at org.jooq.impl.MetaImpl.lambda$0(MetaImpl.java:217)
	at org.jooq.impl.DefaultDSLContext.connectionResult(DefaultDSLContext.java:657)
	at org.jooq.impl.MetaImpl.meta(MetaImpl.java:217)
	at org.jooq.impl.MetaImpl$MetaCatalog.getSchemas(MetaImpl.java:354)
	at org.jooq.impl.MetaImpl.lambda$2(MetaImpl.java:312)
	at org.jooq.impl.Tools.flatMap(Tools.java:2649)
	at org.jooq.impl.MetaImpl.getSchemas0(MetaImpl.java:312)
	at org.jooq.impl.AbstractMeta.lambda$1(AbstractMeta.java:157)
	at org.jooq.impl.AbstractMeta.get(AbstractMeta.java:409)
	at org.jooq.impl.AbstractMeta.initSchemas(AbstractMeta.java:157)
	at org.jooq.impl.AbstractMeta.getSchemas(AbstractMeta.java:149)
	at org.jooq.impl.MetaImpl$MetaTable.getReferences(MetaImpl.java:1197)
	at org.jooq.impl.MetaImpl$MetaTable.removeSystemIndexes(MetaImpl.java:1059)
	at org.jooq.impl.MetaImpl$MetaTable.lambda$0(MetaImpl.java:998)
	at org.jooq.impl.Tools.ignoreNPE(Tools.java:7685)
	at org.jooq.impl.MetaImpl$MetaTable.getIndexes(MetaImpl.java:996)
	at org.jooq.impl.FilteredMeta$FilteredTable.getIndexes(FilteredMeta.java:466)
	at org.jooq.impl.DDL.createIndex(DDL.java:326)
	at org.jooq.impl.DDL.queries(DDL.java:567)
	at org.jooq.impl.AbstractMeta.ddl(AbstractMeta.java:635)
	at org.jooq.impl.AbstractMeta.ddl(AbstractMeta.java:628)
	at org.jooq.testscripts.JDBC.main(JDBC.java:37)
```

While catalogs are filtered at the top level, some internal queries still load all the schemas without considering the catalog filter. This is definitely a bug independent of privileges (unlike #17255, which is about privileges on queries where we don't filter catalogs or other objects).

There are 2 problems here:

- We run into privilege related issues
- It's also a performance problem, since we're still loading the entire catalog and filtering it only later

**Comment by lukaseder** [comment]
In the above stack trace, the problem is that this line doesn't filter catalogs:

```
at org.jooq.impl.MetaImpl$MetaTable.getIndexes(MetaImpl.java:996)
```

It just calls `delegate.getIndexes()` and then applies the filter.

**Comment by lukaseder** [comment]
A first workaround appears to be to set `Settings.metaIncludeSystemIndexes = true` to avoid the `removeSystemIndexes()` call, but that just leads to a different stack trace and the same problem:

```
org.jooq.exception.DataAccessException: Error while running ConnectionCallable
	at org.jooq.impl.DefaultDSLContext.connectionResult(DefaultDSLContext.java:663)
	at org.jooq.impl.MetaImpl.meta(MetaImpl.java:217)
	at org.jooq.impl.MetaImpl$MetaCatalog.getSchemas(MetaImpl.java:354)
	at org.jooq.impl.MetaImpl.lambda$2(MetaImpl.java:312)
	at org.jooq.impl.Tools.flatMap(Tools.java:2649)
	at org.jooq.impl.MetaImpl.getSchemas0(MetaImpl.java:312)
	at org.jooq.impl.AbstractMeta.lambda$1(AbstractMeta.java:157)
	at org.jooq.impl.AbstractMeta.get(AbstractMeta.java:409)
	at org.jooq.impl.AbstractMeta.initSchemas(AbstractMeta.java:157)
	at org.jooq.impl.AbstractMeta.getSchemas(AbstractMeta.java:149)
	at org.jooq.impl.MetaImpl$MetaTable.getReferences(MetaImpl.java:1197)
	at org.jooq.impl.FilteredMeta$FilteredTable.getReferences(FilteredMeta.java:517)
	at org.jooq.impl.DDL.foreignKeys(DDL.java:473)
	at org.jooq.impl.DDL.queries(DDL.java:592)
	at org.jooq.impl.AbstractMeta.ddl(AbstractMeta.java:635)
	at org.jooq.impl.AbstractMeta.ddl(AbstractMeta.java:628)
	at org.jooq.test.all.testcases.MetaDataTests.testMetaFilterCatalogsNoRights(MetaDataTests.java:227)
	at org.jooq.test.jOOQAbstractTest.testMetaFilterCatalogsNoRights(jOOQAbstractTest.java:5150)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:757)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The server principal "NO_RIGHTS" is not able to access the database "db-10751" under the current security context.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:259)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1695)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:648)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:567)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7675)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:4137)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:272)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:246)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQueryInternal(SQLServerPreparedStatement.java:499)
	at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getSchemasInternal(SQLServerDatabaseMetaData.java:1511)
	at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getSchemas(SQLServerDatabaseMetaData.java:1521)
	at org.jooq.impl.MetaImpl$MetaCatalog.lambda$0(MetaImpl.java:360)
	at org.jooq.impl.MetaImpl.lambda$0(MetaImpl.java:217)
	at org.jooq.impl.DefaultDSLContext.connectionResult(DefaultDSLContext.java:657)
	... 47 more
```

That call stack still goes through the unfiltered call to:

```
at org.jooq.impl.MetaImpl$MetaTable.getReferences(MetaImpl.java:1197)
```

**Comment by lukaseder** [comment]
This problem is present in theory also for other implementations of `AbstractMeta`, but it doesn't matter there, because the information is static, e.g. in `CatalogMetaImpl` (mostly generated catalogs) or `InformationSchemaMetaImpl` (JAXB annotated objects). In the `CatalogMetaImpl` case, when there are custom `Catalog` implementations that dynamically generate content, then we'd be in a similar situation, but that's very unlikely.

`MetaImpl` is really special, because it requires a live DB connection to discover meta data, and that connection is

- Dependent on privileges
- Slow

**Comment by lukaseder** [comment]
Possible fixes:

- Put the `FilteredMeta` in some `ThreadLocal` that `MetaImpl` could use to override lookups, such as `Meta.getSchemas()` (dirty)
- Pass around the `Meta` object for lookups to all the query methods (lots of new internal API, easy to forget and revert to calling ordinary API)
- Move filtering logic into `AbstractMeta` (lots of work)

The thread local fix is very tempting, but really feels dirty.

**Comment by lukaseder** [comment]
Turns out that:

> * Move filtering logic into `AbstractMeta` (lots of work)

... isn't so much work if we only push the catalog and schema filters into `AbstractMeta`. It appears that these are the main things being looked up by `MetaImpl` contents

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.12 (https://github.com/jOOQ/jOOQ/issues/17260)
- 3.18.29 (https://github.com/jOOQ/jOOQ/issues/17261)
- 3.17.28 (https://github.com/jOOQ/jOOQ/issues/17262)
