### ISSUE TITLE
NullPointerException in MetaImpl::lookupTable when Schema isn't available for lookup of cross-schema foreign keys

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#17263]
As reported in https://github.com/jOOQ/jOOQ/issues/17255 by @vitaly-ivanov:

              > Can you share the stacktrace that you saw, when you called `filterCatalogs()`? Just to be sure there isn't yet another issue that appears only with your database setup, not with our integration test database...

As far as I can see, there is no exception on the `filterCatalogs()` call.

I did some more tests and there are some interesting results:
The meta successully exported after the third attempt:
```kotlin
val ddlExportConfiguration = DDLExportConfiguration()
  .flags(EnumSet.allOf(DDLFlag::class.java))
val meta = dslContext.meta()
  .filterCatalogs { it.name == "my" }

kotlin.runCatching {
   meta
       .ddl(ddlExportConfiguration)
       .queries()
}.onFailure {
     it.printStackTrace()
}
// Result - Exception from the issue description

kotlin.runCatching {
   meta
       .ddl(ddlExportConfiguration)
       .queries()
}.onFailure {
     it.printStackTrace()
}
// Result - Exception two


meta
   .ddl(ddlExportConfiguration)
   .queries()
// Result - success
```

The second exception:
```
java.lang.NullPointerException: Cannot invoke "org.jooq.Schema.getTable(String)" because "schema" is null
	at org.jooq.impl.MetaImpl.lookupTable(MetaImpl.java:302)
	at org.jooq.impl.MetaImpl$MetaTable.lambda$getReferences$9(MetaImpl.java:1203)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at org.jooq.impl.MetaImpl$MetaTable.getReferences(MetaImpl.java:1190)
	at org.jooq.impl.FilteredMeta$FilteredTable.getReferences(FilteredMeta.java:517)
	at org.jooq.impl.DDL.foreignKeys(DDL.java:462)
	at org.jooq.impl.DDL.queries(DDL.java:584)
	at org.jooq.impl.AbstractMeta.ddl(AbstractMeta.java:635)
```

_Originally posted by @vitaly-ivanov in https://github.com/jOOQ/jOOQ/issues/17255#issuecomment-2358299055_

**Comment by lukaseder** [comment]
A simple reproducer is this:

```sql
create schema s1;
create schema s2;
create table s1.t1(i int, constraint pk_t1 primary key (i)); 
create sequence s1.s1;
create table s2.t2(i int);
create sequence s2.s2;
alter table s2.t2 add constraint fk_t2 foreign key (i) references s1.t1;
```

With:

```java
ctx.meta()
    .filterSchemas(s -> s.getName().equals("s2"))
    .ddl()
```

**Comment by lukaseder** [comment]
A Java test case:

```java
Schema s1 = DSL.schema(name("s1"));
Schema s2 = DSL.schema(name("s2"));
Table<?> t1 = DSL.table(name("s1", "t1"));
Table<?> t2 = DSL.table(name("s2", "t2"));

try {
    create().createSchema(s1).execute();
    create().createSchema(s2).execute();
    create().createTable(t1).column("i", INTEGER).primaryKey("i").execute();
    create().createTable(t2).column("i", INTEGER).constraint(DSL.foreignKey("i").references(t1)).execute();

    assertEquals(2,
    create()
        .meta()
        .filterSchemas(s -> s.getName().equals("s2"))
        .ddl()
        .queries()
        .length);
}
finally {
    ignoreThrows(() -> create().dropTable(t2).execute());
    ignoreThrows(() -> create().dropTable(t1).execute());
    ignoreThrows(() -> create().dropSchema(s2).execute());
    ignoreThrows(() -> create().dropSchema(s1).execute());
}
```

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.12 (https://github.com/jOOQ/jOOQ/issues/17264)
- 3.18.19 (https://github.com/jOOQ/jOOQ/issues/17265)
- 3.17.28 (https://github.com/jOOQ/jOOQ/issues/17266)
