### ISSUE TITLE
Cannot parse default expression in Derby using MetaImpl when computed column is reported as DEFAULT

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#17284]
The Derby JDBC driver reports computed column expressions as expression defaults when calling `DatabaseMetaData::getColumns`. This is reported as an exception stack trace in the logs. It doesn't fail any `MetaImpl` queries:

The stack trace is:

```
org.jooq.impl.ParserException: Unexpected content after end of field input: [1:11] GENERATED [*]ALWAYS AS ( 1 )
	at org.jooq.impl.DefaultParseContext.exception(ParserImpl.java:15898) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.done(ParserImpl.java:16084) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.lambda$10(ParserImpl.java:1043) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.wrap(ParserImpl.java:16091) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.parseField0(ParserImpl.java:1043) ~[classes/:?]
	at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:882) ~[classes/:?]
	at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:877) ~[classes/:?]
	at org.jooq.impl.MetaImpl$MetaTable.initColumns(MetaImpl.java:1573) ~[classes/:?]
	at org.jooq.impl.MetaImpl$MetaTable.<init>(MetaImpl.java:1029) ~[classes/:?]
	at org.jooq.impl.MetaImpl$MetaSchema.lambda$2(MetaImpl.java:549) ~[classes/:?]
	at org.jooq.impl.Tools.map(Tools.java:2657) [classes/:?]
	at org.jooq.impl.MetaImpl$MetaSchema.getTables(MetaImpl.java:524) [classes/:?]
	at org.jooq.impl.DDL.queries(DDL.java:613) [classes/:?]
	at org.jooq.impl.AbstractMeta.ddl(AbstractMeta.java:693) [classes/:?]
	at org.jooq.impl.AbstractMeta.ddl(AbstractMeta.java:686) [classes/:?]
	at org.jooq.test.all.testcases.MetaDataTests.testMetaNoRights(MetaDataTests.java:228) [test-classes/:?]
	at org.jooq.test.jOOQAbstractTest.testMetaNoRights(jOOQAbstractTest.java:5150) [test-classes/:?]
```

We should be able to ignore these

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.12 (https://github.com/jOOQ/jOOQ/issues/17285)
- 3.18.19 (https://github.com/jOOQ/jOOQ/issues/17286)
- 3.17.28 (https://github.com/jOOQ/jOOQ/issues/17287)

**Comment by lukaseder** [comment]
It would obviously be interesting to report computed columns as well in `MetaImpl`, but that's an entirely new feature.
