### ISSUE TITLE
NullPointerException in MetaImpl.getUniqueKeys() query when unique key cannot look up column references

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#17288]
This test table:

```sql
CREATE TABLE t_11552 (
  id INTEGER NOT NULL AUTO_INCREMENT,
  cd INTEGER NOT NULL UNIQUE,
  xy INTEGER,
  
  CONSTRAINT t_11552_pk PRIMARY KEY (id)
);
```

Produces a `NullPointerException` when querying the `MetaImpl` and trying to generate DDL for it:

```
java.lang.NullPointerException
	at java.base/java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:473)
	at org.jooq.impl.Comparators$KeyComparator.compare(Comparators.java:85)
	at org.jooq.impl.Comparators$KeyComparator.compare(Comparators.java:1)
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.base/java.util.TimSort.sort(TimSort.java:220)
	at java.base/java.util.Arrays.sort(Arrays.java:1308)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1804)
	at org.jooq.impl.DDL.sortKeysIf(DDL.java:651)
	at org.jooq.impl.DDL.uniqueKeys(DDL.java:462)
	at org.jooq.impl.DDL.constraints(DDL.java:439)
	at org.jooq.impl.DDL.queries(DDL.java:556)
	at org.jooq.impl.AbstractMeta.ddl(AbstractMeta.java:693)
	at org.jooq.impl.AbstractMeta.ddl(AbstractMeta.java:686)
	at org.jooq.test.all.testcases.MetaDataTests.testMetaNoRights(MetaDataTests.java:227)
	at org.jooq.test.jOOQAbstractTest.testMetaNoRights(jOOQAbstractTest.java:5150)
```

There's an underlying bug specific to this table leading to the column of the key being `null` because the table doesn't list any columns:

![image](https://github.com/user-attachments/assets/0ab8e732-27eb-440b-af7c-053c94750aa5)

If this ever happens, we still shouldn't have unique keys with `null` columns. I'll create a follow up issue about the missing columns in this table after fixing this.

**Comment by nnimoyoefoki** [comment]
maybe this will help

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
If you don't have the c compliator, install it.(gcc or clang)

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.12 (https://github.com/jOOQ/jOOQ/issues/17289)
- 3.18.19 (https://github.com/jOOQ/jOOQ/issues/17290)
- 3.17.28 (https://github.com/jOOQ/jOOQ/issues/17291)

**Comment by lukaseder** [comment]
The problem is with the `performance_schema.global_status` table. When the database user doesn't have any privileges, then these columns aren't being reported. E.g. this query:

```sql
select t.table_name, c.column_name
from information_schema.tables t
left join information_schema.columns c on t.table_name = c.table_name
where t.table_name = 'global_status'
```

Produces this result if the database user doesn't have the required grants:

```
|TABLE_NAME   |COLUMN_NAME|
|-------------|-----------|
|global_status|           |
```

With grants, we're getting:

```
|TABLE_NAME   |COLUMN_NAME   |
|-------------|--------------|
|global_status|VARIABLE_NAME |
|global_status|VARIABLE_VALUE|
```

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.12 (https://github.com/jOOQ/jOOQ/issues/17292)
- 3.18.19 (https://github.com/jOOQ/jOOQ/issues/17293)
- 3.17.28 (https://github.com/jOOQ/jOOQ/issues/17294)
