### ISSUE TITLE
DataTypeException: Conversion function not implemented when using nested record ad-hoc converters with QOM replacement

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#17310]
A recently added test related to handling `null` values in ad-hoc converters for nested records fails when running our integration tests with `QOM` replacement (e.g. pattern transformation) active:

- #17298

When running this query:

```java
testFetchIntoRecordMapperBasedOnFunctionsWithAdHocConverterAndNullRows0(create()
    .select(
        TAuthor_ID().convertFrom(i -> i.longValue()),
        val(null, Integer.class).convertFrom(nullOnAnyNull(Integer::longValue)),
        field(
            select(row(
                TAuthor_FIRST_NAME(),
                TAuthor_LAST_NAME()
            ).mapping(FullName::new))
            .where(DSL.falseCondition())
        )
    )
    .from(TAuthor())
    .orderBy(TAuthor_ID())
    .fetch(mapping(AuthorLongId::new))
);
```

The following exception ensues:

```
org.jooq.exception.DataTypeException: Conversion function not implemented
	at org.jooq_3.20.0-SNAPSHOT.H2.debug(Unknown Source)
	at org.jooq.Converters.lambda$6(Converters.java:272)
	at org.jooq.Converter$1.to(Converter.java:253)
	at org.jooq.impl.DefaultBinding$InternalBinding.sql(DefaultBinding.java:1142)
	at org.jooq.impl.Val.accept0(Val.java:266)
	at org.jooq.impl.Val.accept(Val.java:248)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:712)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:363)
	at org.jooq.impl.DefaultDSLContext.renderInlined(DefaultDSLContext.java:748)
	at org.jooq.impl.Patterns.lambda$5(Patterns.java:254)
	at org.jooq.Replacers.lambda$0(Replacers.java:115)
	at org.jooq.impl.QOM.replaceUntilStable(QOM.java:11330)
	at org.jooq.impl.QOM.replace(QOM.java:10538)
	at org.jooq.impl.QOM$UOperator1.$replace(QOM.java:10125)
	at org.jooq.impl.QOM.replace(QOM.java:10430)
	at org.jooq.impl.QOM.replace(QOM.java:10412)
	at org.jooq.impl.QOM.replace(QOM.java:11128)
	at org.jooq.impl.SelectQueryImpl.$replace(SelectQueryImpl.java:5621)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:284)
	at org.jooq.impl.DefaultDSLContext.renderInlined(DefaultDSLContext.java:748)
	at org.jooq.impl.AbstractQueryPart.equals(AbstractQueryPart.java:172)
	at org.jooq.Traversers.lambda$11(Traversers.java:147)
	at org.jooq.impl.CachingTraverser.lambda$4(CachingTraverser.java:108)
	at org.jooq.impl.QOM.traverse(QOM.java:10463)
	at org.jooq.impl.SelectQueryImpl.$traverse(SelectQueryImpl.java:5602)
	at org.jooq.test.util.BaseTest.lambda$20(BaseTest.java:855)
	at org.jooq.test.agent.SupportVerificationDispatcher.deactivated(SupportVerificationDispatcher.java:126)
	at org.jooq.test.util.BaseTest.qomAssertions(BaseTest.java:840)
	at org.jooq.test.jOOQAbstractTest$QOMAssertionListener.start(jOOQAbstractTest.java:464)
	at org.jooq.impl.ExecuteListeners.start(ExecuteListeners.java:160)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:284)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:274)
	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:295)
	at org.jooq.impl.SelectImpl.fetchLazyNonAutoClosing(SelectImpl.java:3236)
	at org.jooq.impl.ResultQueryTrait.collect(ResultQueryTrait.java:360)
	at org.jooq.impl.ResultQueryTrait.fetch(ResultQueryTrait.java:1465)
	at org.jooq.test.all.testcases.RecordMapperTests.testFetchIntoRecordMapperBasedOnFunctionsWithAdHocConverterAndNullRows(RecordMapperTests.java:211)
	at org.jooq.test.jOOQAbstractTest.testFetchIntoRecordMapperBasedOnFunctionsWithAdHocConverterAndNullRows(jOOQAbstractTest.java:7217)
```

T happens only because we're trying to log the pattern replacement progress:

```java
log.debug("Pattern replacement", "[" + logger.renderInlined(p) + "] => [" + logger.renderInlined(q) + "]");
```

The reason is that we're replacing this query:

```sql
(
  select row ("PUBLIC"."T_AUTHOR"."FIRST_NAME", "PUBLIC"."T_AUTHOR"."LAST_NAME") "nested"
  where false
)
```

By a `ROW` bind value with value `NULL` of the same ad-hoc converted row type. Quite the edge case!

**Comment by lukaseder** [comment]
I guess we can construct a test case that is independent of using the pattern replacement where such a ad-hoc converted `NULL` record is created manually, in case of which the bug becomes a bit less edge-casey.
