### ISSUE TITLE
MetaImpl exceptions should indicate table and column if applicable, which caused the exception

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#17333]
I've just run into a stack trace like this:

```
org.jooq.exception.DataAccessException: Error while running ConnectionCallable
	at org.jooq.impl.DefaultDSLContext.connectionResult(DefaultDSLContext.java:663)
	at org.jooq.impl.MetaImpl.meta(MetaImpl.java:237)
	at org.jooq.impl.MetaImpl$MetaTable.lambda$0(MetaImpl.java:1040)
	at org.jooq.impl.Tools.ignoreNPE(Tools.java:7708)
	at org.jooq.impl.MetaImpl$MetaTable.getIndexes(MetaImpl.java:1038)
	at org.jooq.impl.DDL.hasConstraintsUsingIndexes(DDL.java:633)
	at org.jooq.impl.DDL.queries(DDL.java:554)
	at org.jooq.impl.AbstractMeta.ddl(AbstractMeta.java:693)
	at org.jooq.impl.AbstractMeta.ddl(AbstractMeta.java:686)
	at org.jooq.test.all.testcases.MetaDataTests.testMetaNoRights(MetaDataTests.java:232)
	at org.jooq.test.jOOQAbstractTest.testMetaNoRights(jOOQAbstractTest.java:5150)
Caused by: java.sql.SQLException: ORA-17068: Invalid arguments in call
https://docs.oracle.com/error-help/db/ora-17068/
	at oracle.jdbc.OracleDatabaseMetaData.getIndexInfo(OracleDatabaseMetaData.java:3856)
	at org.jooq.impl.MetaImpl$MetaTable.lambda$3(MetaImpl.java:1041)
	at org.jooq.impl.MetaImpl.catalogSchema(MetaImpl.java:232)
	at org.jooq.impl.MetaImpl.catalogSchema(MetaImpl.java:217)
	at org.jooq.impl.MetaImpl$MetaTable.lambda$2(MetaImpl.java:1041)
	at org.jooq.impl.MetaImpl.lambda$0(MetaImpl.java:237)
	at org.jooq.impl.DefaultDSLContext.connectionResult(DefaultDSLContext.java:657)
	... 40 more
```

This isn't very helpful for debugging. It would be nice if at least the table name (and the column name, if applicable) would be logged with the exception stack trace.

(There's also an underlying bug when reading Oracle dictionary views via JDBC `DatabaseMetaData`, but that will be dealt with in a separate issue)

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.13 (https://github.com/jOOQ/jOOQ/issues/17334)
- 3.18.20 (https://github.com/jOOQ/jOOQ/issues/17335)
- 3.17.29 (https://github.com/jOOQ/jOOQ/issues/17336)

**Comment by lukaseder** [comment]
The solution isn't satisfactory yet as the name is logged only for certain types of exceptions, not the one that is being displayed in this issue here. All `DatabaseMetaData` queries should have a dedicated exception message to help debug them, in case something goes wrong.

**Comment by lukaseder** [comment]
With the improved fix, the stack trace would have been:

```
java.sql.SQLException: ORA-17068: Invalid arguments in call
https://docs.oracle.com/error-help/db/ora-17068/
	at oracle.jdbc.OracleDatabaseMetaData.getIndexInfo(OracleDatabaseMetaData.java:3889)
	at org.jooq.impl.MetaImpl$MetaTable.lambda$4(MetaImpl.java:1071)
	at org.jooq.impl.MetaImpl.catalogSchema(MetaImpl.java:232)
	at org.jooq.impl.MetaImpl.catalogSchema(MetaImpl.java:217)
	at org.jooq.impl.MetaImpl$MetaTable.lambda$3(MetaImpl.java:1071)
	at org.jooq.impl.MetaImpl.meta0(MetaImpl.java:251)
	at org.jooq.impl.MetaImpl.lambda$0(MetaImpl.java:240)
	at org.jooq.impl.DefaultDSLContext.connectionResult(DefaultDSLContext.java:657)
	at org.jooq.impl.MetaImpl.meta(MetaImpl.java:240)
	at org.jooq.impl.MetaImpl$MetaTable.lambda$0(MetaImpl.java:1060)
	at org.jooq.impl.Tools.ignoreNPE(Tools.java:7708)
	at org.jooq.impl.MetaImpl$MetaTable.getIndexes(MetaImpl.java:1058)
	at org.jooq.impl.FilteredMeta$FilteredTable.getIndexes(FilteredMeta.java:476)
	at org.jooq.impl.DDL.hasConstraintsUsingIndexes(DDL.java:633)
	at org.jooq.impl.DDL.queries(DDL.java:554)
	at org.jooq.impl.AbstractMeta.ddl(AbstractMeta.java:693)
	at org.jooq.impl.AbstractMeta.ddl(AbstractMeta.java:686)
	at org.jooq.testscripts.JDBC.main(JDBC.java:50)
org.jooq.exception.DataAccessException: Error querying DatabaseMetaData: Error while fetching indexes for table: "TEST"."_t"
	at org.jooq.impl.MetaImpl.meta0(MetaImpl.java:259)
	at org.jooq.impl.MetaImpl.lambda$0(MetaImpl.java:240)
	at org.jooq.impl.DefaultDSLContext.connectionResult(DefaultDSLContext.java:657)
	at org.jooq.impl.MetaImpl.meta(MetaImpl.java:240)
	at org.jooq.impl.MetaImpl$MetaTable.lambda$0(MetaImpl.java:1060)
	at org.jooq.impl.Tools.ignoreNPE(Tools.java:7708)
	at org.jooq.impl.MetaImpl$MetaTable.getIndexes(MetaImpl.java:1058)
	at org.jooq.impl.FilteredMeta$FilteredTable.getIndexes(FilteredMeta.java:476)
	at org.jooq.impl.DDL.hasConstraintsUsingIndexes(DDL.java:633)
	at org.jooq.impl.DDL.queries(DDL.java:554)
	at org.jooq.impl.AbstractMeta.ddl(AbstractMeta.java:693)
	at org.jooq.impl.AbstractMeta.ddl(AbstractMeta.java:686)
	at org.jooq.testscripts.JDBC.main(JDBC.java:50)
```
