### ISSUE TITLE
ORA-17068: Invalid arguments in call when calling OracleDatabaseMetaData.getIndexInfo() with quoted object names

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#17337]
Given this schema:

```sql
create table "_t" (i int);
create index "_i" on "_t" (i);
```

One would expect this to be a valid meta data query:

```java
connection.getMetaData().getIndexInfo(null, "TEST", "_t", false, true);
```

But it throws:

```
org.jooq.exception.DataAccessException: Error while running ConnectionCallable
	at org.jooq.impl.DefaultDSLContext.connectionResult(DefaultDSLContext.java:663)
	at org.jooq.impl.MetaImpl.meta(MetaImpl.java:237)
	at org.jooq.impl.MetaImpl$MetaTable.lambda$0(MetaImpl.java:1040)
	at org.jooq.impl.Tools.ignoreNPE(Tools.java:7708)
	at org.jooq.impl.MetaImpl$MetaTable.getIndexes(MetaImpl.java:1038)
	at org.jooq.impl.FilteredMeta$FilteredTable.getIndexes(FilteredMeta.java:476)
	at org.jooq.impl.DDL.hasConstraintsUsingIndexes(DDL.java:633)
	at org.jooq.impl.DDL.queries(DDL.java:554)
	at org.jooq.impl.AbstractMeta.ddl(AbstractMeta.java:693)
	at org.jooq.impl.AbstractMeta.ddl(AbstractMeta.java:686)
	at org.jooq.test.all.testcases.MetaDataTests.testMetaNoRights(MetaDataTests.java:232)
	at org.jooq.test.jOOQAbstractTest.testMetaNoRights(jOOQAbstractTest.java:5150)
Caused by: java.sql.SQLException: ORA-17068: Invalid arguments in call
https://docs.oracle.com/error-help/db/ora-17068/
	at oracle.jdbc.OracleDatabaseMetaData.getIndexInfo(OracleDatabaseMetaData.java:3856)
	at org.jooq.impl.MetaImpl$MetaTable.lambda$3(MetaImpl.java:1043)
	at org.jooq.impl.MetaImpl.catalogSchema(MetaImpl.java:232)
	at org.jooq.impl.MetaImpl.catalogSchema(MetaImpl.java:217)
	at org.jooq.impl.MetaImpl$MetaTable.lambda$2(MetaImpl.java:1043)
	at org.jooq.impl.MetaImpl.lambda$0(MetaImpl.java:237)
	at org.jooq.impl.DefaultDSLContext.connectionResult(DefaultDSLContext.java:657)
	... 41 more
```

It appears that internally, `OracleSql.isValidObjectName()` is called, which suggests that quoting the identifier `"\"_t\""` is the way to go:

```java
connection.getMetaData().getIndexInfo(null, "TEST", "\"_t\"", false, true);
```

I don't want to replicate the internal regex from the `isValidObjectName()` method, or call that method (using reflection), so perhaps we can just quote all identifiers when calling that method?

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.13 (https://github.com/jOOQ/jOOQ/issues/17338)
- 3.18.20 (https://github.com/jOOQ/jOOQ/issues/17339)
- 3.17.29 (https://github.com/jOOQ/jOOQ/issues/17340)

**Comment by lukaseder** [comment]
I've reported this as a bug to ojdbc. I don't think it's necessary to quote such identifiers:
https://forums.oracle.com/ords/apexds/post/ora-17068-invalid-arguments-in-call-when-looking-up-quoted-4512

We can still quote them nonetheless
