### ISSUE TITLE
MethodTooLargeException in DSLContext lazy autowire

### ISSUE THREAD

**Issue by sourabh11112** [jOOQ/jOOQ#17381]
### Actual behavior

We are getting below error when we are trying to Lazy autowire DSLContext bean in our spring project. When we remove Lazy annotation it works fine. Issue is reproducible at runtime only when we put Lazy annotation. Lazy annonation is used for lazily autowiring many beans in our projects, it is working fine at other places , giving error only with DSLContext.

```java
  @Autowired
  @Lazy
  private DSLContext dslContext;


Full error stack trace: 
_jdk.internal.org.objectweb.asm.MethodTooLargeException: Method too large: jdk/proxy4/$Proxy145.<clinit> ()V
	at java.base/jdk.internal.org.objectweb.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2120)
	at java.base/jdk.internal.org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:543)
	at java.base/java.lang.reflect.ProxyGenerator.generateClassFile(ProxyGenerator.java:506)
	at java.base/java.lang.reflect.ProxyGenerator.generateProxyClass(ProxyGenerator.java:178)
	at java.base/java.lang.reflect.Proxy$ProxyBuilder.defineProxyClass(Proxy.java:544)
	at java.base/java.lang.reflect.Proxy$ProxyBuilder.build(Proxy.java:657)
	at java.base/java.lang.reflect.Proxy.lambda$getProxyConstructor$1(Proxy.java:440)
	at java.base/jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329)
	at java.base/jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205)
	at java.base/java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:438)
	at java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1034)
	at org.springframework.aop.framework.JdkDynamicAopProxy.getProxy(JdkDynamicAopProxy.java:124)
	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:110)
	at org.springframework.context.annotation.ContextAnnotationAutowireCandidateResolver.buildLazyResolutionProxy(ContextAnnotationAutowireCandidateResolver.java:136)
	at org.springframework.context.annotation.ContextAnnotationAutowireCandidateResolver.buildLazyResolutionProxy(ContextAnnotationAutowireCandidateResolver.java:84)
	at org.springframework.context.annotation.ContextAnnotationAutowireCandidateResolver.getLazyResolutionProxyIfNecessary(ContextAnnotationAutowireCandidateResolver.java:54)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1347)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:784)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:767)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:145)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:508)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1439)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:971)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:625)
	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:706)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:672)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:720)
	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:595)
	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:537)
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:169)
	at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
	at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:944)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:901)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:805)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4601)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4894)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
	at org.apache.catalina.core.StandardContext.reload(StandardContext.java:3546)
	at org.apache.catalina.loader.WebappLoader.backgroundProcess(WebappLoader.java:254)
	at org.apache.catalina.core.StandardContext.backgroundProcess(StandardContext.java:5222)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1301)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1305)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1305)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1283)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:1583)_
```

### Steps to reproduce the problem

JDK version : jdk21
springframework version : 6.1.11
Jooq version : 3.19.12

Below code give 'jdk.internal.org.objectweb.asm.MethodTooLargeException: Method too large:' exception at Runtime.

```java
  @Autowired
  @Lazy
  private DSLContext dslContext;
```

### jOOQ Version

3.19.12

### Database product and version

postgres14 and mysql8

### Java Version

oracle jdk 21

**Comment by lukaseder** [comment]
Thanks for your report.

> We are getting below error when we are trying to Lazy autowire DSLContext bean in our spring project. When we remove Lazy annotation it works fine.

I suggest reporting this to Spring and have them fix their implementation of whatever this annotation is supposed to mean.

**Comment by sourabh11112** [comment]
@lukaseder 
The JVM's method bytecode limit of 64KB is a hard limit and cannot be increased. To avoid the MethodTooLargeException, DSLContext large methods needs to be refactored to reduce the size of the method.
In spring @Lazy autowiring working for all other libs , failing only for jooq.

**Comment by sourabh11112** [comment]
@lukaseder it is still working with older version of jooq 3.14.16
we are getting this exception only after updating jooq to latest version.

**Comment by lukaseder** [comment]
> The JVM's method bytecode limit of 64KB is a hard limit and cannot be increased.

I'm aware of this limit. We have worked around it numerous times in our generated code. This isn't a limit that jOOQ itself has surpassed, but rather, a limit that was surpassed due to *instrumenting* jOOQ.

> To avoid the MethodTooLargeException, DSLContext large methods needs to be refactored to reduce the size of the method.

`DSLContext` doesn't have any large methods. The problem must lie elsewhere. Without a complete reproducer (ideally based on our template here https://github.com/jOOQ/jOOQ-mcve), I'm not sure how I could help you within a reasonable time frame.

> In spring @lazy autowiring working for all other libs , failing only for jooq.

That still doesn't change that *they* are doing something that doesn't work for jOOQ, so *they* have a problem, not necessarily jOOQ.

If *you* write instrumentation logic that produces methods that are too large, that also would mean that your logic has a bug, not jOOQ, I suspect?

> @lukaseder it is still working with older version of jooq 3.14.16
> we are getting this exception only after updating jooq to latest version.

Yes, jOOQ's API grew over time. But jOOQ works well out of the box, so if an integrator project tries to instrument jOOQ API and does something wrong, then I personally doubt that jOOQ can do anything about it?
