### ISSUE TITLE
DSLContext::fetchCount for selects with nested records causes DataAccessException

### ISSUE THREAD

**Issue by stefa-n-koegl** [jOOQ/jOOQ#17425]
### Expected behavior

fetchCount() with two SelectFields in the select is expected to provide the number of records that meet these criteria. After upgrading jOOQ PRO from 3.19.3 to 3.19.13 it causes a DataAccessException with SQL Server 2022. On other database system the exception is not raised.

### Actual behavior

Exception raised: "_'t' has more columns than were specified in the column list_"

```
15:44:00,421 DEBUG [org.jooq.tools.LoggerListener                     ] - Executing query          : select [master].[mcve].[foo].[id] [foo.id], [master].[mcve].[bar].[id] [bar.id], [master].[mcve].[bar].[foo_id] [bar.foo_id] from [master].[mcve].[foo] join [master].[mcve].[bar] on [master].[mcve].[bar].[foo_id] = [master].[mcve].[foo].[id]
15:44:00,442 DEBUG [org.jooq.tools.LoggerListener                     ] - Fetched result           : +----+----+
15:44:00,442 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : |foo |bar |
15:44:00,442 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : +----+----+
15:44:00,442 DEBUG [org.jooq.tools.LoggerListener                     ] - Fetched row(s)           : 0
15:44:00,479 DEBUG [org.jooq.tools.LoggerListener                     ] - Executing query          : select count(*) [c] from (select [master].[mcve].[foo].[id] [foo.id], [master].[mcve].[bar].[id] [bar.id], [master].[mcve].[bar].[foo_id] [bar.foo_id] from [master].[mcve].[foo] join [master].[mcve].[bar] on [master].[mcve].[bar].[foo_id] = [master].[mcve].[foo].[id]) [t] ([v0], [v1])
15:44:00,490 DEBUG [org.jooq.tools.LoggerListener                     ] - Exception                
org.jooq.exception.DataAccessException: SQL [select count(*) [c] from (select [master].[mcve].[foo].[id] [foo.id], [master].[mcve].[bar].[id] [bar.id], [master].[mcve].[bar].[foo_id] [bar.foo_id] from [master].[mcve].[foo] join [master].[mcve].[bar] on [master].[mcve].[bar].[foo_id] = [master].[mcve].[foo].[id]) [t] ([v0], [v1])]; 't' has more columns than were specified in the column list.
	at org.jooq_3.19.13.SQLSERVER.debug(Unknown Source) ~[?:?]
	at org.jooq.impl.Tools.translate(Tools.java:3640) ~[jooq-3.19.13.jar:?]
	at org.jooq.impl.Tools.translate(Tools.java:3628) ~[jooq-3.19.13.jar:?]
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:827) ~[jooq-3.19.13.jar:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:362) ~[jooq-3.19.13.jar:?]
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:301) ~[jooq-3.19.13.jar:?]
	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:322) ~[jooq-3.19.13.jar:?]
	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:509) ~[jooq-3.19.13.jar:?]
	at org.jooq.impl.DefaultDSLContext.fetchCount(DefaultDSLContext.java:5125) ~[jooq-3.19.13.jar:?]
	at org.jooq.mcve.test.java.sqlserver.JavaTest.lambda$mcveTest$0(JavaTest.java:89) ~[test-classes/:?]
	at org.junit.Assert.assertThrows(Assert.java:1001) [junit-4.13.2.jar:4.13.2]
	at org.junit.Assert.assertThrows(Assert.java:981) [junit-4.13.2.jar:4.13.2]
	at org.jooq.mcve.test.java.sqlserver.JavaTest.mcveTest(JavaTest.java:88) [test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) [junit-4.13.2.jar:4.13.2]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.13.2.jar:4.13.2]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69) [junit-rt.jar:?]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11) [idea_rt.jar:?]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55) [junit-rt.jar:?]
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: 't' has more columns than were specified in the column list.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:259) ~[mssql-jdbc-12.4.1.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1695) ~[mssql-jdbc-12.4.1.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:648) ~[mssql-jdbc-12.4.1.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:567) ~[mssql-jdbc-12.4.1.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7675) ~[mssql-jdbc-12.4.1.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:4137) ~[mssql-jdbc-12.4.1.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:272) ~[mssql-jdbc-12.4.1.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:246) ~[mssql-jdbc-12.4.1.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:544) ~[mssql-jdbc-12.4.1.jre11.jar:?]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219) ~[jooq-3.19.13.jar:?]
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:5001) ~[jooq-3.19.13.jar:?]
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:236) ~[jooq-3.19.13.jar:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:348) ~[jooq-3.19.13.jar:?]
```

### Steps to reproduce the problem

```java
ctx.fetchCount(ctx.select(FOO, BAR).from(FOO).join(BAR).onKey());
```

Full code can be found in JavaTest.java of https://github.com/stefa-n-koegl/jOOQ-mcve/tree/main/jOOQ-mcve-java-sqlserver

### jOOQ Version

jOOQ Pro 3.19.13

### Database product and version

SQL Server 2022

### Java Version

openjdk version "21.0.3" 2024-04-16 LTS

**Comment by lukaseder** [comment]
Thanks a lot for your report. I'll look into this soon.

**Comment by lukaseder** [comment]
I can reproduce the problem. It isn't strictly related to `DSLContext.fetchCount()`, but more to projecting nested records and then auto-aliasing all columns in a derived table (which is what `fetchCount()` does, internally). There are probably other ways to trigger this issue.

The workaround is to avoid `fetchCount()` in these cases and manually write a `COUNT(*)` query, or alternatively, calculate the `COUNT(*) OVER ()` value in a single query rather than running the same base query twice. We have a blog post for this topic:
https://blog.jooq.org/calculating-pagination-metadata-without-extra-roundtrips-in-sql/

**Comment by lukaseder** [comment]
A related issue that fixed this problem when projecting embeddables:

- #16326

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.14 (https://github.com/jOOQ/jOOQ/issues/17430)
- 3.18.21 (https://github.com/jOOQ/jOOQ/issues/17431)
- 3.17.30 (https://github.com/jOOQ/jOOQ/issues/17432)

The fix addresses the problem only when nested records are used with `FetchCount`, not with other ways of using this internal derived table mechanism. There might be other, similar bugs, which should be addressed in the future.

Thanks again for your report!
