### ISSUE TITLE
Suppressed NoSuchElementException from ThreadLocalTransactionProvider.rollback prevents rollback when commit fails

### ISSUE THREAD

**Issue by victorbr** [jOOQ/jOOQ#17517]
### Expected behavior

No superfluous suppressed exceptions.
This is really not a big deal, a very minor issue because it simply adds a suppressed exception, just a bit noisy.

### Actual behavior

Closely related to https://github.com/jOOQ/jOOQ/issues/8413, but the fix of that issue didn't take care of this specific situation.
When `ThreadLocalTransactionProvider` is used and `commit` fails for whatever reason, the stack is already popped (before calling `delegateTransactionProvider.commit(ctx)`). However, the `committed` boolean in `org.jooq.impl.DefaultDSLContext#transactionResult0` is not set because of the exception. So the logic inside the `catch` block there initiates a rollback that fails with `NoSuchElementException`.

### Steps to reproduce the problem

Here's the exception stack trace that demonstrates the flow:
```
org.postgresql.util.PSQLException: FATAL: terminating connection due to idle-in-transaction timeout
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2733)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2420)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:372)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:330)
	at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:981)
	at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:1003)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:131)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:107)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:93)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:107)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81)
	at jdk.proxy2/jdk.proxy2.$Proxy73.commit(Unknown Source)
	at org.jooq.impl.DefaultConnectionProvider.commit(DefaultConnectionProvider.java:98)
	... 90 common frames omitted
Wrapped by: org.jooq.exception.DataAccessException: Cannot commit transaction
	at org.jooq.impl.DefaultConnectionProvider.commit(DefaultConnectionProvider.java:101)
	at org.jooq.impl.DefaultTransactionProvider.commit(DefaultTransactionProvider.java:174)
	at org.jooq.impl.ThreadLocalTransactionProvider.commit(ThreadLocalTransactionProvider.java:104)
	at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:534)
	at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:578)
	at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:497)

< ... application stack trace frames redacted ... >

	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:256)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:235)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:397)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:349)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:379)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:312)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
	at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:36)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:46)
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:40)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:314)
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:267)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:89)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1580)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at io.dropwizard.metrics.jetty11.InstrumentedHandler.handle(InstrumentedHandler.java:313)
	at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:822)
	at io.dropwizard.jetty.ZipExceptionHandlingGzipHandler.handle(ZipExceptionHandlingGzipHandler.java:26)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:46)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.util.NoSuchElementException: null
		at java.base/java.util.ArrayDeque.removeFirst(Unknown Source)
		at java.base/java.util.ArrayDeque.pop(Unknown Source)
		at org.jooq.impl.ThreadLocalTransactionProvider.rollback(ThreadLocalTransactionProvider.java:111)
		at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:554)
		... 87 common frames omitted
```

### jOOQ Version

org.jooq:jooq:3.19.13

### Database product and version

PostgreSQL 15.7 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-12), 64-bit

### Java Version

eclipse-temurin:21.0.4_7-jre-alpine

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.3

**Comment by lukaseder** [comment]
Thanks for your report. How can this be reproduced? I tried this, and it threw the exception as expected:

```java
Connection c = new DefaultConnection(connection) {
    @Override
    public void commit() throws SQLException {
        throw new SQLException("fail");
    }
};
DSLContext ctx = DSL.using(c, SQLDialect.H2);
ctx.configuration().set(new ThreadLocalTransactionProvider(new DefaultConnectionProvider(c)));

ctx.transaction(() -> {
});
```

The exception being:

```
java.sql.SQLException: fail
	at org.jooq.testscripts.JDBC$1.commit(JDBC.java:38)
	at org.jooq.impl.DefaultConnectionProvider.commit(DefaultConnectionProvider.java:98)
	at org.jooq.impl.DefaultTransactionProvider.commit(DefaultTransactionProvider.java:174)
	at org.jooq.impl.ThreadLocalTransactionProvider.commit(ThreadLocalTransactionProvider.java:104)
	at org.jooq.impl.DefaultDSLContext.lambda$3(DefaultDSLContext.java:535)
	at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:579)
	at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:498)
	at org.jooq.impl.DefaultDSLContext.transaction(DefaultDSLContext.java:584)
	at org.jooq.testscripts.JDBC.main(JDBC.java:51)
```

**Comment by lukaseder** [comment]
Ah, interesting. Throwing a `DataAccessException` seems to reproduce it:

```java
Connection c = new DefaultConnection(connection) {
    @Override
    public void commit() throws SQLException {
        throw new DataAccessException("fail");
    }
};
DSLContext ctx = DSL.using(c, SQLDialect.H2);
ctx.configuration().set(new ThreadLocalTransactionProvider(new DefaultConnectionProvider(c)));

ctx.transaction(() -> {
});
```

Now, the exception is:

```
org.jooq.exception.DataAccessException: Cannot commit transaction
	at org.jooq.impl.DefaultConnectionProvider.commit(DefaultConnectionProvider.java:101)
	at org.jooq.impl.DefaultTransactionProvider.commit(DefaultTransactionProvider.java:174)
	at org.jooq.impl.ThreadLocalTransactionProvider.commit(ThreadLocalTransactionProvider.java:104)
	at org.jooq.impl.DefaultDSLContext.lambda$3(DefaultDSLContext.java:535)
	at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:579)
	at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:498)
	at org.jooq.impl.DefaultDSLContext.transaction(DefaultDSLContext.java:584)
	at org.jooq.testscripts.JDBC.main(JDBC.java:44)
	Suppressed: java.util.NoSuchElementException
		at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:361)
		at java.base/java.util.ArrayDeque.pop(ArrayDeque.java:592)
		at org.jooq.impl.ThreadLocalTransactionProvider.rollback(ThreadLocalTransactionProvider.java:111)
		at org.jooq.impl.DefaultDSLContext.lambda$3(DefaultDSLContext.java:555)
		... 4 more
Caused by: org.jooq.exception.DataAccessException: fail
	at org.jooq.testscripts.JDBC$1.commit(JDBC.java:38)
	at org.jooq.impl.DefaultConnectionProvider.commit(DefaultConnectionProvider.java:98)
	... 7 more
```

**Comment by lukaseder** [comment]
In fact, this also prevents the rollback itself! Rollback will typically happen in a connection pool (I hope), but that's not something we should rely upon.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.15 (https://github.com/jOOQ/jOOQ/issues/17522)
- 3.18.22 (https://github.com/jOOQ/jOOQ/issues/17523)
- 3.17.31 (https://github.com/jOOQ/jOOQ/issues/17524)

**Comment by victorbr** [comment]
Speechless! 😲 
Same day fix is something unheard of! 🙇 
Thank you!!! ❤️
