### ISSUE TITLE
Avoid calling JSONB::toString in jOOQ internals

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#17578]
Numerous issues have been reported regarding the performance of `JSONB::toString` calls:

- https://github.com/jOOQ/jOOQ/issues/15751
- https://github.com/jOOQ/jOOQ/issues/17497

The performance issues started with:

- https://github.com/jOOQ/jOOQ/issues/12023

The decision to make `toString()` dependent on the normalised `JSONB` document was controversial (less so for `equals()` and `hashCode()`, though faster implementations would be nice: https://github.com/jOOQ/jOOQ/issues/14954)

It seems clear that we should at least avoid calling `toString()` in jOOQ's internals, if it isn't strictly necessary. Some call stacks from integration tests if we add this instrumentation:

```java
if (isJSONB && "toString".equals(methodName)) {
    method.insertBefore("""
        if (true)
            throw new UnsupportedOperationException("Avoid calling JSONB.toString()");
        """);
}
```

Call stacks:

**`AbstractParam::name`** (mostly cosmetic)

```java.lang.RuntimeException
	at org.jooq_3.20.0-SNAPSHOT.POSTGRES.debug(Unknown Source)
	at org.jooq.JSONB.toString(JSONB.java:184)
	at java.base/java.lang.String.valueOf(String.java:4465)
	at org.jooq.impl.AbstractParam.name(AbstractParam.java:134)
	at org.jooq.impl.AbstractParam.lambda$0(AbstractParam.java:119)
	at org.jooq.impl.LazyName.name(LazyName.java:66)
	at org.jooq.impl.LazyName.qualified(LazyName.java:97)
	at org.jooq.impl.AbstractName.equals(AbstractName.java:376)
	at org.jooq.impl.AbstractNamed.equals(AbstractNamed.java:116)
```

**`AbstractResult::format0`** (mostly cosmetic, though currently misleading as the wrong thing is debug-logged)

```
java.lang.RuntimeException
	at org.jooq.JSONB.toString(JSONB.java:184)
	at org.jooq.impl.AbstractResult.format0(AbstractResult.java:1449)
	at org.jooq.impl.AbstractResult.format(AbstractResult.java:202)
	at org.jooq.impl.AbstractFormattable.format(AbstractFormattable.java:117)
	at org.jooq.tools.LoggerListener.log(LoggerListener.java:194)
```

**`Val::getJavaValueString`** (hardly ever used feature)

```
java.lang.RuntimeException
	at org.jooq_3.20.0-SNAPSHOT.POSTGRES.debug(Unknown Source)
	at org.jooq.JSONB.toString(JSONB.java:184)
	at java.base/java.lang.String.valueOf(String.java:4465)
	at org.jooq.impl.Val.getJavaValueString(Val.java:346)
	at org.jooq.impl.Val.getJavaValue(Val.java:302)
	at org.jooq.impl.Val.acceptJava(Val.java:280)
	at org.jooq.impl.Val.accept(Val.java:226)
```

**`PostgresUtils.toPGString()`** (separate bug: https://github.com/jOOQ/jOOQ/issues/17579)

```
java.lang.UnsupportedOperationException: Avoid calling JSONB.toString()
	at org.jooq_3.20.0-SNAPSHOT.POSTGRES.debug(Unknown Source)
	at org.jooq.JSONB.toString(JSONB.java)
	at java.base/java.lang.String.valueOf(String.java:4465)
	at org.jooq.util.postgres.PostgresUtils.toPGString(PostgresUtils.java:575)
	at org.jooq.util.postgres.PostgresUtils.toPGArrayString0(PostgresUtils.java:543)
	at org.jooq.util.postgres.PostgresUtils.toPGArrayString(PostgresUtils.java:511)
	at org.jooq.impl.DefaultBinding$DefaultArrayBinding.sqlInline0(DefaultBinding.java:1419)
	at org.jooq.impl.DefaultBinding$DefaultArrayBinding.sqlInline0(DefaultBinding.java:1)
	at org.jooq.impl.DefaultBinding$InternalBinding.sql(DefaultBinding.java:1180)
	at org.jooq.impl.DefaultBinding$InternalBinding.sql(DefaultBinding.java:1172)
	at org.jooq.impl.Val.accept0(Val.java:266)
	at org.jooq.impl.Val.accept(Val.java:248)
```

**`ConvertAll::from`** (separate bug: https://github.com/jOOQ/jOOQ/issues/17497)

```
java.lang.UnsupportedOperationException: Avoid calling JSONB.toString()
	at org.jooq.JSONB.toString(JSONB.java)
	at org.jooq.impl.Convert$ConvertAll.from(Convert.java:786)
	at org.jooq.impl.Convert.convert0(Convert.java:515)
	at org.jooq.impl.Convert.convert(Convert.java:590)
	at org.jooq.impl.DefaultConverterProvider.lambda$1(DefaultConverterProvider.java:125)
	at org.jooq.Converter$1.from(Converter.java:248)
	at org.jooq.impl.Convert.convert0(Convert.java:518)
	at org.jooq.impl.Convert.convert(Convert.java:504)
	at org.jooq.impl.AbstractRecord.get(AbstractRecord.java:241)
```

If we could avoid these, then most performance issues would already be gone.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.16 (https://github.com/jOOQ/jOOQ/issues/17584)
- 3.18.23 (https://github.com/jOOQ/jOOQ/issues/17585)
- 3.17.32 (https://github.com/jOOQ/jOOQ/issues/17586)

**Comment by lukaseder** [comment]
**`DefaultJSONBBinding.bytesConverter`**:

```
java.lang.UnsupportedOperationException: Avoid calling JSONB.toString()
	at org.jooq_3.20.0-SNAPSHOT.DB2.debug(Unknown Source)
	at org.jooq.JSONB.toString(JSONB.java)
	at org.jooq.impl.DefaultBinding$DefaultJSONBBinding.lambda$1(DefaultBinding.java:6298)
	at org.jooq.Converters.lambda$5(Converters.java:267)
	at org.jooq.ContextConverter$2.to(ContextConverter.java:277)
	at org.jooq.impl.DefaultBinding$DefaultJSONBBinding.sqlInline0(DefaultBinding.java:6226)
	at org.jooq.impl.DefaultBinding$DefaultJSONBBinding.sqlInline0(DefaultBinding.java:1)
	at org.jooq.impl.DefaultBinding$InternalBinding.sql(DefaultBinding.java:1180)
	at org.jooq.impl.DefaultBinding$InternalBinding.sql(DefaultBinding.java:1158)
	at org.jooq.impl.Val.accept0(Val.java:266)
	at org.jooq.impl.Val.accept(Val.java:248)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:728)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:363)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:269)
	at org.jooq.impl.FieldMapsForInsert.toSQL92Values(FieldMapsForInsert.java:520)
	at org.jooq.impl.FieldMapsForInsert.toSQLValues(FieldMapsForInsert.java:262)
	at org.jooq.impl.FieldMapsForInsert.accept(FieldMapsForInsert.java:194)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:728)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:363)
	at org.jooq.impl.InsertQueryImpl.toSQLInsert(InsertQueryImpl.java:898)
	at org.jooq.impl.InsertQueryImpl.accept1(InsertQueryImpl.java:740)
	at org.jooq.impl.AbstractDMLQuery.accept0(AbstractDMLQuery.java:694)
	at org.jooq.impl.InsertQueryImpl.accept(InsertQueryImpl.java:436)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:728)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:363)
	at org.jooq.impl.DefaultDSLContext.renderInlined(DefaultDSLContext.java:749)
	at org.jooq.tools.LoggerListener.renderEnd(LoggerListener.java:98)
	at org.jooq.impl.ExecuteListeners.renderEnd(ExecuteListeners.java:188)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:305)
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
	at org.jooq.test.all.testcases.DDLTests.lambda$485(DDLTests.java:5420)
	at org.jooq.test.jOOQAbstractTest.withDSLContext(jOOQAbstractTest.java:2707)
	at org.jooq.test.jOOQAbstractTest.bindAndInline(jOOQAbstractTest.java:2690)
	at org.jooq.test.BaseTest.bindAndInline(BaseTest.java:2389)
	at org.jooq.test.all.testcases.DDLTests.testCreateTableWithJSONTypes(DDLTests.java:5413)
	at org.jooq.test.jOOQAbstractTest.testCreateTableWithJSONTypes(jOOQAbstractTest.java:4744)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:757)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

From the Db2 integration tests. I'll expect other flow paths from dialect specific logic as the test suites complete.
