### ISSUE TITLE
Avoid CAST(? AS BLOB) in Oracle and render TO_BLOB(?) instead

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#17601]
I'm trying to add an integration test for this issue:

The test runs into this problem:

```
org.jooq.exception.DataAccessException: SQL [select ("DBMS_LOB"."COMPARE"(cast(? as blob), to_blob(?)) = 0) -- SQL rendered with a free trial version of jOOQ 3.20.0-SNAPSHOT]; ORA-22849: Type BLOB is not supported for this function or operator.

https://docs.oracle.com/error-help/db/ora-22849/
	at org.jooq_3.20.0-SNAPSHOT.ORACLE23AI.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3687)
	at org.jooq.impl.Tools.translate(Tools.java:3660)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:827)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:362)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:274)
	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:295)
	at org.jooq.impl.SelectImpl.fetchLazyNonAutoClosing(SelectImpl.java:3242)
	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:509)
	at org.jooq.impl.Tools.attach(Tools.java:1708)
	at org.jooq.impl.DefaultDSLContext.fetchOne(DefaultDSLContext.java:5172)
	at org.jooq.impl.DefaultDSLContext.lambda$61(DefaultDSLContext.java:5192)
	at org.jooq.impl.Tools.attach(Tools.java:1708)
	at org.jooq.impl.DefaultDSLContext.fetchValue(DefaultDSLContext.java:5192)
	at org.jooq.impl.DefaultDSLContext.fetchValue(DefaultDSLContext.java:5211)
	at org.jooq.test.all.testcases.DataTypeTests.assertBlobAndClobComparison(DataTypeTests.java:440)
	at org.jooq.test.all.testcases.DataTypeTests.lambda$1(DataTypeTests.java:389)
	at org.jooq.test.jOOQAbstractTest.withDSLContext(jOOQAbstractTest.java:2707)
	at org.jooq.test.jOOQAbstractTest.bindAndInline(jOOQAbstractTest.java:2690)
	at org.jooq.test.BaseTest.bindAndInline(BaseTest.java:2389)
	at org.jooq.test.all.testcases.DataTypeTests.testBlobAndClobComparison(DataTypeTests.java:388)
	at org.jooq.test.jOOQAbstractTest.testBlobAndClobComparison(jOOQAbstractTest.java:8118)
Caused by: Error : 22849, Position : 29, SQL = select ("DBMS_LOB"."COMPARE"(cast(:1 as blob), to_blob(:2 )) = 0) -- SQL rendered with a free trial version of jOOQ 3.20.0-SNAPSHOT, Original SQL = select ("DBMS_LOB"."COMPARE"(cast(? as blob), to_blob(?)) = 0) -- SQL rendered with a free trial version of jOOQ 3.20.0-SNAPSHOT, Error Message = ORA-22849: Type BLOB is not supported for this function or operator.

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:717)
	... 67 more
```

We've already been avoiding `CLOB` casts for a while:

- #7442

Let's to the same for `BLOB`

**Comment by lukaseder** [comment]
Yeah, it isn't supported as a target data type:
https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/CAST.html
