### ISSUE TITLE
Combining onDuplicateKeyUpdate with Policy causes invalid SQL

### ISSUE THREAD

**Issue by eralmansouri** [jOOQ/jOOQ#17630]
### Expected behavior

Let's say we have a table "PROJECT" that has a tenant id, and we create this policy:

```
configuration.set(new DefaultPolicyProvider()
                .append(PROJECT, PROJECT.tenant().ID.eq(UUID.randomUUID())));
```
Later, we **upsert** into the database:
```
dslContext.insertInto(PROJECT)
      .set(record)
      .onDuplicateKeyUpdate()
      .set(record)
      .execute();
```  
I would expect that to work just the same as when PROJECT has no policy.

### Actual behavior

It throws this error instead:
```
org.jooq.exception.DataAccessException: SQL [merge into "sp"."project" using (select "t"."id", "t"."tenant_id", "t"."project_number", "t"."title", "t"."status" from (select cast(? as uuid), cast(? as uuid), ?, ?, ?) as "t" ("id", "tenant_id", "project_number", "title", "status") where (select "alias_6178197"."id" from "sp"."tenant" as "alias_6178197" where "t"."tenant_id" = "alias_6178197"."id") = cast(? as uuid)) as "t" ("id", "tenant_id", "project_number", "title", "status") on (("project"."id" = "t"."id" or "project"."doc_id" = cast(? as uuid)) and (select "alias_6178197"."id" from "sp"."tenant" as "alias_6178197" where "project"."tenant_id" = "alias_6178197"."id") = cast(? as uuid)) when matched and (select "alias_6178197"."id" from "sp"."tenant" as "alias_6178197" where "project"."tenant_id" = "alias_6178197"."id") = cast(? as uuid) then update set "id" = cast(? as uuid), "tenant_id" = cast(? as uuid), "project_number" = ?, "title" = ?, "status" = ? when not matched and (select "alias_6178197"."id" from "sp"."tenant" as "alias_6178197" where "project"."tenant_id" = "alias_6178197"."id") = cast(? as uuid) then insert ("id", "tenant_id", "project_number", "title", "status") values ("t"."id", "t"."tenant_id", "t"."project_number", "t"."title", "t"."status")]; ERROR: invalid reference to FROM-clause entry for table "project"
  Detail: There is an entry for table "project", but it cannot be referenced from this part of the query.
  Position: 1038
	at org.jooq_3.19.10.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3607)
	at org.jooq.impl.Tools.translate(Tools.java:3595)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:827)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:362)
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
```

Another problem also occurs if you try to insert (instead of upsert) without setting the value of tenant id manually on the record first:
```
org.jooq.exception.DataAccessException: SQL [insert into "sp"."project" ("id", "project_number", "title", "status") select "t"."id", "t"."project_number", "t"."title", "t"."status" from (select cast(? as uuid), ?, ?, ?) as "t" ("id", "project_number", "title", "status") where (select "alias_6178197"."id" from "sp"."tenant" as "alias_6178197" where ("t"."tenant_id" = "alias_6178197"."id" and "alias_6178197"."id" = cast(? as uuid))) = cast(? as uuid)]; ERROR: column t.tenant_id does not exist
  Position: 311
	at org.jooq_3.19.10.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3607)
	at org.jooq.impl.Tools.translate(Tools.java:3595)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:827)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:362)
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
```

### Steps to reproduce the problem

```sql
CREATE TABLE tenant
(
    id             UUID PRIMARY KEY,
    name       VARCHAR(255)
);

CREATE TABLE project
(
    id             UUID PRIMARY KEY,
    tenant_id      UUID REFERENCES tenant (id) NOT NULL,
    title          VARCHAR(255)                NOT NULL
);
```

Use a policy that uses tenant path:
```
configuration.set(new DefaultPolicyProvider()
                .append(PROJECT, PROJECT.tenant().ID.eq(UUID.randomUUID())));
```

Use an insert with a onDuplicateKeyUpdate():
```
dslContext.insertInto(PROJECT)
      .set(record)
      .onDuplicateKeyUpdate()
      .set(record)
      .execute();
```

The problem is seems to be avoided if you use a policy that directly uses tenant id (eg):
```
configuration.set(new DefaultPolicyProvider()
                .append(PROJECT, PROJECT.TENANT_ID.eq(UUID.randomUUID())));
```

On an unrelated note: I really wish there was a better way to provide a tenant policy that is evaluated at query time instead of configuration so that I can have a single DSLContext bean that I can inject to all my repositories.
```
configuration.set(new DefaultPolicyProvider()
  .append(PROJECT.TENANT_ID.eq(DSL.val(() -> {
    var ctx = // read from security context holder or some other threadlocal
    return ctx.tenantId();
  }));
```
Instead, I feel like I have to re-implement the default policy so I can override condition(). And my homemade implementation is just not as nice to read without the same support for inheritance that the default policy has.

### jOOQ Version

Professional Edition 3.19.10

### Database product and version

postgres:16-alpine

### Java Version

21

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgres.postgresql:42.7.4

**Comment by lukaseder** [comment]
Thanks for your report. I'll have a look into this soon.

There's a task to offer join path elimination if it's unnecessary, at least offering it as a diagnostic:

- https://github.com/jOOQ/jOOQ/issues/13453

Nevertheless, I'll investigate your issue, soon. If you're adding other attributes of the parent table than the `ID`, then the path will be necessary, and should be supported, of course.

> On an unrelated note: I really wish there was a better way to provide a tenant policy that is evaluated at query time instead of configuration so that I can have a single DSLContext bean that I can inject to all my repositories.

You can call `Configuration.derive(policyProvider)` on an existing `Configuration`, or implement your own `PolicyProvider` that looks up context at query time. `PolicyProvider` isn't required to maintain static state. This is just the default implementation to show how things work.

**Comment by lukaseder** [comment]
Ah no, I couldn't reproduce it yet. I ran into an H2 bug:

- https://github.com/h2database/h2database/issues/4198

**Comment by lukaseder** [comment]
I've applied your reproducer to our MCVE template here: https://github.com/jOOQ/jOOQ-mcve. See below patch. Unfortunately, I couldn't reproduce any problems. The generated query is:

```sql
insert into "mcve"."project" ("id", "tenant_id", "title") 
select "t"."id", "t"."tenant_id", "t"."title" 
from (
  select 
    cast('8fa1513f-6214-41d5-8dfe-930cbe711d79' as uuid), 
    cast('73fbef92-e682-4884-9790-31e47a02991b' as uuid), 'x'
) as "t" ("id", "tenant_id", "title") 
where (select "alias_6178197"."id" 
from "mcve"."tenant" as "alias_6178197" 
where "t"."tenant_id" = "alias_6178197"."id") = cast('6ec4d11e-f4ac-4325-8e3b-43eacceb12b6' as uuid) 
on conflict ("id") do update set 
  "id" = cast('8fa1513f-6214-41d5-8dfe-930cbe711d79' as uuid), 
  "tenant_id" = cast('73fbef92-e682-4884-9790-31e47a02991b' as uuid), 
  "title" = 'x'
```

In your case, the generated query was different, and not against the reproducer table (from the error message):

```sql
insert into "sp"."project" ("id", "project_number", "title", "status") 
select "t"."id", "t"."project_number", "t"."title", "t"."status"
from (
  select cast(? as uuid), ?, ?, ?
) as "t" ("id", "project_number", "title", "status") 
where (
  select "alias_6178197"."id" 
  from "sp"."tenant" as "alias_6178197" 
  where ("t"."tenant_id" = "alias_6178197"."id" and "alias_6178197"."id" = cast(? as uuid))
) = cast(? as uuid)
```

You're not inserting any `tenant_id`, which is not legal if you have a policy on the tenant. I'd say, this is maybe not what you expected (i.e. a no-op `INSERT` statement), but perhaps even better as it shows a flaw in your query?

I'm closing this as "works for me." Let me know if I'm overlooking something, and I can reopen.

The `MERGE` issue is fixed in 3.20.0 and 3.19.19:

- https://github.com/jOOQ/jOOQ/issues/13453



Reproducer:

```patch
diff --git a/jOOQ-mcve-java-postgres/pom.xml b/jOOQ-mcve-java-postgres/pom.xml
index 0e0e958..8e71bee 100644
--- a/jOOQ-mcve-java-postgres/pom.xml
+++ b/jOOQ-mcve-java-postgres/pom.xml
@@ -15,7 +15,7 @@
     <properties>

         <!-- TODO: Change your jOOQ edition and version here -->
-        <org.jooq.groupId>org.jooq</org.jooq.groupId>
+        <org.jooq.groupId>org.jooq.pro</org.jooq.groupId>
         <org.jooq.version>3.19.18</org.jooq.version>
         <testcontainers.version>1.19.8</testcontainers.version>
         <postgres.version>42.7.5</postgres.version>
diff --git a/jOOQ-mcve-java-postgres/src/main/java/org/jooq/mcve/java/postgres/Keys.java b/jOOQ-mcve-java-postgres/src/main/java/org/jooq/mcve/java/postgres/Keys.java
index b97c8f2..f61a364 100644
--- a/jOOQ-mcve-java-postgres/src/main/java/org/jooq/mcve/java/postgres/Keys.java
+++ b/jOOQ-mcve-java-postgres/src/main/java/org/jooq/mcve/java/postgres/Keys.java
@@ -4,11 +4,16 @@
 package org.jooq.mcve.java.postgres;


+import org.jooq.ForeignKey;
 import org.jooq.TableField;
 import org.jooq.UniqueKey;
 import org.jooq.impl.DSL;
 import org.jooq.impl.Internal;
+import org.jooq.mcve.java.postgres.tables.Project;
+import org.jooq.mcve.java.postgres.tables.Tenant;
 import org.jooq.mcve.java.postgres.tables.Test;
+import org.jooq.mcve.java.postgres.tables.records.ProjectRecord;
+import org.jooq.mcve.java.postgres.tables.records.TenantRecord;
 import org.jooq.mcve.java.postgres.tables.records.TestRecord;


@@ -23,5 +28,13 @@ public class Keys {
     // UNIQUE and PRIMARY KEY definitions
     // -------------------------------------------------------------------------

+    public static final UniqueKey<ProjectRecord> PROJECT_PKEY = Internal.createUniqueKey(Project.PROJECT, DSL.name("project_pkey"), new TableField[] { Project.PROJECT.ID }, true);
+    public static final UniqueKey<TenantRecord> TENANT_PKEY = Internal.createUniqueKey(Tenant.TENANT, DSL.name("tenant_pkey"), new TableField[] { Tenant.TENANT.ID }, true);
     public static final UniqueKey<TestRecord> PK_TEST = Internal.createUniqueKey(Test.TEST, DSL.name("pk_test"), new TableField[] { Test.TEST.ID }, true);
+
+    // -------------------------------------------------------------------------
+    // FOREIGN KEY definitions
+    // -------------------------------------------------------------------------
+
+    public static final ForeignKey<ProjectRecord, TenantRecord> PROJECT__PROJECT_TENANT_ID_FKEY = Internal.createForeignKey(Project.PROJECT, DSL.name("project_tenant_id_fkey"), new TableField[] { Project.PROJECT.TENANT_ID }, Keys.TENANT_PKEY, new TableField[] { Tenant.TENANT.ID }, true);
 }
diff --git a/jOOQ-mcve-java-postgres/src/main/java/org/jooq/mcve/java/postgres/Mcve.java b/jOOQ-mcve-java-postgres/src/main/java/org/jooq/mcve/java/postgres/Mcve.java
index dfe2447..1a45b43 100644
--- a/jOOQ-mcve-java-postgres/src/main/java/org/jooq/mcve/java/postgres/Mcve.java
+++ b/jOOQ-mcve-java-postgres/src/main/java/org/jooq/mcve/java/postgres/Mcve.java
@@ -10,6 +10,8 @@ import java.util.List;
 import org.jooq.Catalog;
 import org.jooq.Table;
 import org.jooq.impl.SchemaImpl;
+import org.jooq.mcve.java.postgres.tables.Project;
+import org.jooq.mcve.java.postgres.tables.Tenant;
 import org.jooq.mcve.java.postgres.tables.Test;


@@ -26,6 +28,16 @@ public class Mcve extends SchemaImpl {
      */
     public static final Mcve MCVE = new Mcve();

+    /**
+     * The table <code>mcve.project</code>.
+     */
+    public final Project PROJECT = Project.PROJECT;
+
+    /**
+     * The table <code>mcve.tenant</code>.
+     */
+    public final Tenant TENANT = Tenant.TENANT;
+
     /**
      * The table <code>mcve.test</code>.
      */
@@ -47,6 +59,8 @@ public class Mcve extends SchemaImpl {
     @Override
     public final List<Table<?>> getTables() {
         return Arrays.asList(
+            Project.PROJECT,
+            Tenant.TENANT,
             Test.TEST
         );
     }
diff --git a/jOOQ-mcve-java-postgres/src/main/java/org/jooq/mcve/java/postgres/Tables.java b/jOOQ-mcve-java-postgres/src/main/java/org/jooq/mcve/java/postgres/Tables.java
index 8dc630e..4939b9a 100644
--- a/jOOQ-mcve-java-postgres/src/main/java/org/jooq/mcve/java/postgres/Tables.java
+++ b/jOOQ-mcve-java-postgres/src/main/java/org/jooq/mcve/java/postgres/Tables.java
@@ -4,6 +4,8 @@
 package org.jooq.mcve.java.postgres;


+import org.jooq.mcve.java.postgres.tables.Project;
+import org.jooq.mcve.java.postgres.tables.Tenant;
 import org.jooq.mcve.java.postgres.tables.Test;


@@ -13,6 +15,16 @@ import org.jooq.mcve.java.postgres.tables.Test;
 @SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
 public class Tables {

+    /**
+     * The table <code>mcve.project</code>.
+     */
+    public static final Project PROJECT = Project.PROJECT;
+
+    /**
+     * The table <code>mcve.tenant</code>.
+     */
+    public static final Tenant TENANT = Tenant.TENANT;
+
     /**
      * The table <code>mcve.test</code>.
      */
diff --git a/jOOQ-mcve-java-postgres/src/main/resources/db/migration/init.sql b/jOOQ-mcve-java-postgres/src/main/resources/db/migration/init.sql
index 0b6ca27..cfb4500 100644
--- a/jOOQ-mcve-java-postgres/src/main/resources/db/migration/init.sql
+++ b/jOOQ-mcve-java-postgres/src/main/resources/db/migration/init.sql
@@ -7,4 +7,17 @@ CREATE TABLE mcve.test (
   cd INT,

   CONSTRAINT pk_test PRIMARY KEY (id)
+);
+
+CREATE TABLE mcve.tenant
+(
+    id             UUID PRIMARY KEY,
+    name       VARCHAR(255)
+);
+
+CREATE TABLE mcve.project
+(
+    id             UUID PRIMARY KEY,
+    tenant_id      UUID REFERENCES mcve.tenant (id) NOT NULL,
+    title          VARCHAR(255)                NOT NULL
 );
\ No newline at end of file
diff --git a/jOOQ-mcve-java-postgres/src/test/java/org/jooq/mcve/test/java/postgres/JavaTest.java b/jOOQ-mcve-java-postgres/src/test/java/org/jooq/mcve/test/java/postgres/JavaTest.java
index 83a4ee9..7df9ac5 100644
--- a/jOOQ-mcve-java-postgres/src/test/java/org/jooq/mcve/test/java/postgres/JavaTest.java
+++ b/jOOQ-mcve-java-postgres/src/test/java/org/jooq/mcve/test/java/postgres/JavaTest.java
@@ -3,6 +3,8 @@ package org.jooq.mcve.test.java.postgres;
 import org.jooq.DSLContext;
 import org.jooq.SQLDialect;
 import org.jooq.impl.DSL;
+import org.jooq.impl.DefaultPolicyProvider;
+import org.jooq.mcve.java.postgres.tables.records.ProjectRecord;
 import org.jooq.mcve.java.postgres.tables.records.TestRecord;
 import org.jooq.tools.JooqLogger;
 import org.junit.After;
@@ -18,8 +20,9 @@ import java.sql.DriverManager;
 import java.sql.SQLException;
 import java.sql.Statement;
 import java.util.Properties;
+import java.util.UUID;

-import static org.jooq.mcve.java.postgres.Tables.TEST;
+import static org.jooq.mcve.java.postgres.Tables.*;
 import static org.junit.Assert.assertEquals;
 import static org.junit.Assert.assertNotNull;

@@ -82,14 +85,16 @@ public class JavaTest {

     @Test
     public void mcveTest() {
-        assertEquals(1,
-            ctx.insertInto(TEST)
-               .columns(TEST.CD)
-               .values(42)
-               .execute()
-        );

-        TestRecord record = ctx.fetchOne(TEST, TEST.CD.eq(42));
-        assertNotNull(record.getId());
+        ctx.configuration().set(new DefaultPolicyProvider()
+                .append(PROJECT, PROJECT.tenant().ID.eq(UUID.randomUUID())));
+
+        var record = new ProjectRecord(UUID.randomUUID(), UUID.randomUUID(), "x");
+
+        ctx.insertInto(PROJECT)
+                .set(record)
+                .onDuplicateKeyUpdate()
+                .set(record)
+                .execute();
     }
 }
```

**Comment by eralmansouri** [comment]
Awesome. I think the issue reported was fixed here and the issue with INSERT is potentially incorrect expectations from my part.

My expectation here would've been either a (1) no-op insert or (2) a narrower error that indicates I'm trying to insert a record that does not match the applied policies, or that we aren't able to apply the policy for some reason. To me, generating syntactically incorrect SQL where we're referencing t.tenant_id without first defining the tenant id is what seems wrong to me. 

Suppose the policy was that tenant_id should be NULL instead of a specific value? I would hope the query generated should still be valid with the same example above.

**Comment by lukaseder** [comment]
> My expectation here would've been either a (1) no-op insert or (2) a narrower error that indicates I'm trying to insert a record that does not match the applied policies, or that we aren't able to apply the policy for some reason. To me, generating syntactically incorrect SQL where we're referencing t.tenant_id without first defining the tenant id is what seems wrong to me.

There are different ways to go about this. In principle, you did define the tenant id via policy. If for some syntactic reason, a tenant id is unavailable, then a syntax error is a last resort, so it will never be completely unavoidable. Think of using plain SQL templates here and there, in case of which jOOQ might not be able to look up the exact tenant_id column specification to add to the query.

But I can obviously see how the existing error isn't really helpful when investigating such an issue. The *(1) no-op insert* would be desirable, but I don't think it can be done, generally. Your path may be "simple enough" to make assumptions about a dummy `t.tenant_id` column having to be added to the query, but this becomes quickly quite unmanageable when you have more complex paths in your policy, use inherited policies, or even use complex subqueries as policies (e.g. using `EXISTS`). It's probably always possible to look up all the requirements to make a no-op query work *somehow*, but it seems like an excessive effort to get right. The *(2) a narrower error* would also be desirable, but it would amount to almost the same amount of effort of finding out whether the unstructured, text-based syntax error message refers to a policy related error, or just any other syntax error. So, 2 is almost as complex as 1, except that we delay the analysis until an error occurs.

In any case, there's probably an 80/20 solution somewhere, given that in *your* case, the analysis might have been possible with reasonable efforts, because the concept of a `tenant_id` seems quite ubiquitous, so perhaps being able to declare that there are some columns in queries that are always mandatory would be in order. That wouldn't fix the issue directly, but it would prevent it, meaning that every query producing tenant-capable data *must* include a `tenant_id` in its insert column list or where clause somehow. This is probably mostly about `INSERT` statements. `UPDATE`, `DELETE`, and `SELECT` will always have a `tenant_id` simply because you have a policy. So, I wonder, should your `tenant_id` perhaps just be a stored client side computed column?
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types/codegen-database-forced-types-computed/

I'll add a few tests to check if this feature combination works as expected, but it does seem to be the perfect match.

> Suppose the policy was that tenant_id should be NULL instead of a specific value? I would hope the query generated should still be valid with the same example above.

Well, `NULL` isn't the same thing as `DEFAULT` in SQL. Your query uses `DEFAULT` (omitting the value, which, by default, happens to be `NULL` in most RDBMS). If you put an explicit `NULL`, then the `NULL` checking policy would work as expected.
