### ISSUE TITLE
NullPointerException in interpreter when trying to work with schema that doesn't exist

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#17637]
Exceptions like these can happen when the interpreter tries to work with schemas that don't exist in its meta data information:

```
org.jooq.exception.DataMigrationException: Exception during migration
	at org.jooq.impl.MigrationImpl.run(MigrationImpl.java:421)
	at org.jooq.impl.MigrationImpl.execute(MigrationImpl.java:242)
	at org.jooq.impl.MigrationsTest.testIncrementsAndSchemasMix(MigrationsTest.java:1051)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:757)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.NullPointerException: Cannot invoke "org.jooq.impl.Interpreter$MutableSchema.table(org.jooq.Named, boolean)" because "schema" is null
	at org.jooq.impl.Interpreter.accept0(Interpreter.java:555)
	at org.jooq.impl.Interpreter.accept(Interpreter.java:222)
	at org.jooq.impl.InterpreterMetaProvider.provide(InterpreterMetaProvider.java:95)
	at org.jooq.impl.DefaultDSLContext.meta(DefaultDSLContext.java:446)
	at org.jooq.impl.AbstractMeta.apply(AbstractMeta.java:814)
	at org.jooq.impl.VersionImpl.apply(VersionImpl.java:151)
	at org.jooq.impl.VersionImpl.apply(VersionImpl.java:146)
	at org.jooq.impl.CommitImpl.version(CommitImpl.java:435)
	at org.jooq.impl.CommitImpl.migrateTo0(CommitImpl.java:400)
	at org.jooq.impl.CommitImpl.migrateTo(CommitImpl.java:263)
	at org.jooq.impl.MigrationImpl.queries(MigrationImpl.java:122)
	at org.jooq.impl.MigrationImpl.migrationContext(MigrationImpl.java:232)
	at org.jooq.impl.MigrationImpl.init(MigrationImpl.java:370)
	at org.jooq.impl.MigrationImpl.run(MigrationImpl.java:399)
	... 28 more
```

**Comment by lukaseder** [comment]
The issue is probably present because some statements implictly create the schema

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.16 (https://github.com/jOOQ/jOOQ/issues/17638)
- 3.18.23 (https://github.com/jOOQ/jOOQ/issues/17639)
- 3.17.32 (https://github.com/jOOQ/jOOQ/issues/17640)
