### ISSUE TITLE
ORA-01790 when inserting CLOBs with mixture of null and non-null values into a table with auditing active

### ISSUE THREAD

**Issue by alexrkopp** [jOOQ/jOOQ#17656]
### Your question

We are running into an issue when performing a bulk insert containing a CLOB. When we update two records and one has a non-null CLOB value and the other has a null CLOB value, we are getting an error: 

> PL/SQL: ORA-01790: expression must have same datatype as corresponding expression

Here's some example code:

```java
var result = jooq.insertInto(TABLENAME)
                  .set(recordA, recordB)
                  .returningResult(TABLENAME.ID)
                  .fetch()
                  .into(Long.class)
```

`recordA` and `recordB` are of the same type and have TableField SUMMARY generated as follows:

`public final TableField<MyRecord, String> SUMMARY = createField(DSL.name("SUMMARY"), SQLDataType.CLOB, this, "");`

We did see the existence of `ClobBinding` on https://www.jooq.org/doc/latest/manual/reference/reference-data-types/data-types-lobs/ and using that seems to work around this issue, however it is not clear what the pros and cons are switching our code generation to use that binding for CLOBs. Presumably there is a reason for not making it the default.

So I guess there are two questions:
1. Is the ORA-01790 issue known or any way to work around it besides using `ClobBinding`?
2. Can you shed some more light on reasons to adopt or avoid `ClobBinding` with Oracle?

### jOOQ Version

jOOQ Professional 3.19.5

### Database product and version

Oracle 19c

### Java Version

openjdk version "21.0.3" 2024-04-16 LTS

### JDBC / R2DBC driver name and version (include name if unofficial driver)

com.oracle.database.jdbc:ojdbc11:21.9.0.0

**Comment by lukaseder** [comment]
Thanks for your report. Looks like a `UNION` is being generated in your case, instead of the `FORALL` loop in a PL/SQL block?

Can you provide a bit more information on how to reproduce this? I cannot, on my end. We have a template for reproducers here:

- https://github.com/jOOQ/jOOQ-mcve

It might not be necessary to use the template, you could also try:

- Upgrading to 3.19.15 (unlikely, but you never know)
- Provide the stack trace and generated SQL query
- Provide the `Configuration` you're using (in particular, the `SQLDialect` version)

**Comment by lukaseder** [comment]
> So I guess there are two questions:

I will be able to as soon as I can reproduce the issue...

**Comment by alexrkopp** [comment]
Thanks for the response, @lukaseder. Some other information that I discovered:

- The issue is still showing when `returningResult` is removed, so that would help narrow things down.
- The error happens if the first record being inserted has a null value for the clob and the second does not. If the first record has a non-null value, then it seems to work.
- Dialect is ORACLE18C

Here's an example that replicates the issue:

```java
var a = new MyTableRecord();
var b = new MyTableRecord().setSummary("test");

jooq.insertInto(MYTABLE).set(a, b).execute();
```

The generated sql:

`insert into "MYTABLE" ("SUMMARY", "CREATED", "CREATEDBY") select "SUMMARY", SYSDATE, ? from (select ? "SUMMARY" from DUAL union all select ? from DUAL) "t"`

(Note: the created/createdby columns are handled via the AuditProvider)

The relevant portion of the stack trace (up to the application code) is:

```
at org.jooq_3.19.5.ORACLE18C.debug(Unknown Source)
at org.jooq.impl.Tools.translate(Tools.java:3553)
at org.jooq.impl.Tools.translate(Tools.java:3541)
at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:827)
at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:362)
at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
```

Let me know if that helps reproduce.

**Comment by alexrkopp** [comment]
If not, I'll attempt to use the jOOQ-mcve

**Comment by alexrkopp** [comment]
Hi @lukaseder. Does the additional information I provided last week help replicate the issue? Or do you still need me to try replicating using https://github.com/jOOQ/jOOQ-mcve ?

**Comment by lukaseder** [comment]
Thanks for your patience. I will get to investigating this issue, soon.

**Comment by lukaseder** [comment]
Looking into this now. I see that the audit feature is involved, that would explain the `UNION ALL` clause. I'll try to reproduce it now, with that in mind.

**Comment by lukaseder** [comment]
OK, on the auditing test table, I can reproduce the problem with a test like this:

```java
assertEquals(2,
ctx.insertInto(T_AUDIT)
   .columns(T_AUDIT.ID, T_AUDIT.VAL, T_AUDIT.LOB, T_AUDIT.CREATED_BY)
   .values(1, 2, null, "x")
   .values(2, 3, "y", "x")
   .execute());
```

The stack trace being:

```
org.jooq.exception.DataAccessException: SQL [insert into TEST.T_AUDIT (ID, VAL, LOB, CREATED_AT, CREATED_BY, CREATED_OR_MODIFIED_AT, CREATED_OR_MODIFIED_BY) select ID, VAL, LOB, ?, ?, ?, ? from (select t.* from (select ? ID, ? VAL, ? LOB, ? CREATED_BY union all select ?, ?, ?, ?) t) t]; ORA-01790: expression must have same datatype as corresponding expression

https://docs.oracle.com/error-help/db/ora-01790/
	at org.jooq_3.20.0-SNAPSHOT.ORACLE23AI.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3697)
	at org.jooq.impl.Tools.translate(Tools.java:3670)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:827)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:362)
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
	at org.jooq.test.all.testcases.AuditTests.testAuditDMLBulkWithLobs(AuditTests.java:239)
	at org.jooq.test.jOOQAbstractTest.testAuditDMLBulkWithLobs(jOOQAbstractTest.java:14915)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:757)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.sql.SQLSyntaxErrorException: ORA-01790: expression must have same datatype as corresponding expression

https://docs.oracle.com/error-help/db/ora-01790/
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:709)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:609)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1347)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:1100)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:408)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:499)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:274)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1484)
	at oracle.jdbc.driver.OracleStatement.executeSQLStatement(OracleStatement.java:2008)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1621)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3955)
	at oracle.jdbc.driver.OraclePreparedStatement.doExecute(OraclePreparedStatement.java:4422)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:4408)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1015)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:458)
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:1112)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:348)
	... 33 more
Caused by: Error : 1790, Position : 197, SQL = insert into TEST.T_AUDIT (ID, VAL, LOB, CREATED_AT, CREATED_BY, CREATED_OR_MODIFIED_AT, CREATED_OR_MODIFIED_BY) select ID, VAL, LOB, :1 , :2 , :3 , :4 from (select t.* from (select :5 ID, :6 VAL, :7 LOB, :8 CREATED_BY union all select :9 , :10 , :11 , :12 ) t) t, Original SQL = insert into TEST.T_AUDIT (ID, VAL, LOB, CREATED_AT, CREATED_BY, CREATED_OR_MODIFIED_AT, CREATED_OR_MODIFIED_BY) select ID, VAL, LOB, ?, ?, ?, ? from (select t.* from (select ? ID, ? VAL, ? LOB, ? CREATED_BY union all select ?, ?, ?, ?) t) t, Error Message = ORA-01790: expression must have same datatype as corresponding expression

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:717)
	... 50 more
```

**Comment by lukaseder** [comment]
And to answer your questions regarding a workaround, indeed, the `ClobBinding` does seem to help here:

```java
assertEquals(2,
ctx.insertInto(T_AUDIT)
   .columns(T_AUDIT.ID, T_AUDIT.VAL, T_AUDIT.LOB.convert(new ClobBinding()), T_AUDIT.CREATED_BY)
   .values(1, 2, null, "x")
   .values(2, 3, "y", "x")
   .execute());
```

You can also attach the binding to the column itself, though that might have other side-effects throughout your application.

Another workaround is to omit bulk inserts until this is fixed.

**Comment by lukaseder** [comment]
Removing audit from the equation, this reproduces it as well:

```java
ctx.select(val("a").cast(CLOB))
   .unionAll(select(val((String) null)))
   .fetch();
```

Here, the workaround is to simply cast to `CLOB` explicitly

```java
ctx.select(val("a").cast(CLOB))
   .unionAll(select(val((String) null).cast(CLOB)))
   .fetch();
```

In your case, the cast shouldn't be necessary, though.

**Comment by lukaseder** [comment]
A similar issue: #15595

**Comment by lukaseder** [comment]
I've found a solution that minimises impact on these casts, namely whenever a `org.jooq.Param` is projected directly in a subquery, without any other expression involved (apart from aliasing). E.g.:

```sql
FROM (SELECT ? ...)
```

Turning this into:

```sql
FROM (SELECT to_clob(?) ...)
```

This should cover a few other edge cases where a `CLOB` bind value is involved, but not bound as a `Clob` by default.
