### ISSUE TITLE
JUnit concurrent execution causes NoClassDefFoundError "Tables"

### ISSUE THREAD

**Issue by AndreKoepke** [jOOQ/jOOQ#17701]
### Expected behavior

No errors.

### Actual behavior

On normal sequential execution all our tests are running fine. When we activate concurrent tests via `junit-platform.properties`:
```properties
junit.jupiter.execution.parallel.enabled=true
junit.jupiter.execution.parallel.mode.default=concurrent
junit.jupiter.execution.parallel.config.dynamic.factor=1
```

Then we get on different tests this error:
<details>
  <summary>Exception with stacktrace </summary>
  
```text
java.lang.NoClassDefFoundError: Could not initialize class OUR_PACKAGE.service.persistence.generated.Tables

	at OUR_PACKAGE.service.repository.WorkunitRepository.create(WorkunitRepository.java:139)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:392)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at OUR_PACKAGE.service.repository.WorkunitRepository$$SpringCGLIB$$0.create(<generated>)
	at OUR_PACKAGE.service.testing.WorkunitBuilder.persist(WorkunitBuilder.java:99)
	at OUR_PACKAGE.service.repository.planningcontext.PlanningContextObjectTrainRepositoryTest.countByContextIdWithErrorIssues_returnsNumberOfNonConvertedTrainsWithErrorIssuesForContext(PlanningContextObjectTrainRepositoryTest.java:470)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ExceptionInInitializerError [in thread "ForkJoinPool-1-worker-3"]
	at OUR_PACKAGE.service.persistence.generated.Tables.<clinit>(Tables.java:214)
	at OUR_PACKAGE.service.repository.planningcontext.CalculationOptionsRepositoryTest.duplicate_sourceCalculationOptionsExisting_duplicatesCalculationOptions(CalculationOptionsRepositoryTest.java:115)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at --- Async.Stack.Trace --- (captured by IntelliJ IDEA debugger)
	at java.base/java.util.concurrent.ForkJoinTask.fork(ForkJoinTask.java)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.forkConcurrentTasks(ForkJoinPoolHierarchicalTestExecutorService.java:161)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:151)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:202)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at --- Async.Stack.Trace --- (captured by IntelliJ IDEA debugger)
	at java.base/java.util.concurrent.ForkJoinTask.fork(ForkJoinTask.java)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.forkConcurrentTasks(ForkJoinPoolHierarchicalTestExecutorService.java:161)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:151)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:202)
	... 7 more
```
</details>

It looks like #14769.

### Steps to reproduce the problem

1. SpringBoot database tests with zonky.
2. Testcontainers as database provider.
3. Activate parallel execution.

### jOOQ Version

3.19.8, 3.19.15

### Database product and version

PostgreSQL 15.3

### Java Version

21.0.5

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:jar:42.7.3

**Comment by AndreKoepke** [comment]
Not sure how I can provide more information, because I posted the whole stackstrace. I just started the tests (it doesn't matter, if I run them directly with IntelliJ or with Maven).

**Comment by lukaseder** [comment]
What's on line 214 of that file?

```
Tables.<clinit>(Tables.java:214)
```

**Comment by AndreKoepke** [comment]
This is automatically generated by JOOQ. It's structure looks like this:

```java
/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>scenario</code>.
     */
    public static final Scenario SCENARIO = Scenario.SCENARIO;

    /**
     * The table <code>solution_request_status</code>.
     */
    public static final SolutionRequestStatus SOLUTION_REQUEST_STATUS = SolutionRequestStatus.SOLUTION_REQUEST_STATUS;

    // ... more, all our tables
}
```

Line 214 refers to our `solutionRequestStatus`-table.

**Comment by AndreKoepke** [comment]
If it helps: The constant `SolutionRequestStatus.SOLUTION_REQUEST_STATUS` is defined like this:

```java
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SolutionRequestStatus extends TableImpl<SolutionRequestStatusRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>solution_request_status</code>
     */
    public static final SolutionRequestStatus SOLUTION_REQUEST_STATUS = new SolutionRequestStatus();
}
```

And `SolutionRequestStatus` has this constructor:

```java
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SolutionRequestStatus extends TableImpl<SolutionRequestStatusRecord> {
    /**
     * Create a <code>solution_request_status</code> table reference
     */
    public SolutionRequestStatus() {
        this(DSL.name("solution_request_status"), null);
    }

   // ... more
}
```

**Comment by lukaseder** [comment]
Nothing out of the ordinary there.

It will not be easy to reproduce this, I'm not sure if I can prioritise an investigation right now. However, a workaround with these class initialisation problems is always to ensure they're initialised eagerly in tests. Perhaps, there's a possibility of extending a base test class that does some initialisation work in `@BeforeClass`?

**Comment by lukaseder** [comment]
> It will not be easy to reproduce this, I'm not sure if I can prioritise an investigation right now.

Just to be clear: I'll have a go nonetheless, of course. But if I'm not 100% certain I can reproduce the problem you're seeing, I'm also not 100% certain that a fix will truly address the issue.
