### ISSUE TITLE
Parser cannot handle Long.MIN_VALUE signed integer literal

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#17742]
When trying to parse a statement like this:

```sql
create sequence s minvalue -9223372036854775808
```

The parser cannot handle the `Long.MIN_VALUE` value:

```
java.lang.NumberFormatException: For input string: "9223372036854775808"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Long.parseLong(Long.java:713)
	at java.base/java.lang.Long.valueOf(Long.java:1157)
	at org.jooq.impl.DefaultParseContext.parseUnsignedIntegerLiteralIf(ParserImpl.java:14004)
	at org.jooq.impl.DefaultParseContext.parseUnsignedIntegerLiteral(ParserImpl.java:13986)
	at org.jooq.impl.DefaultParseContext.parseSignedIntegerLiteralIf(ParserImpl.java:13885)
	at org.jooq.impl.DefaultParseContext.parseSignedIntegerOrBindVariable(ParserImpl.java:13972)
	at org.jooq.impl.DefaultParseContext.parseSequenceMinvalueIf(ParserImpl.java:4503)
	at org.jooq.impl.DefaultParseContext.parseCreateSequence(ParserImpl.java:4373)
	at org.jooq.impl.DefaultParseContext.parseCreate(ParserImpl.java:2958)
	at org.jooq.impl.DefaultParseContext.parseQuery(ParserImpl.java:1140)
	at org.jooq.impl.DefaultParseContext.lambda$2(ParserImpl.java:910)
	at org.jooq.impl.DefaultParseContext.wrap(ParserImpl.java:15405)
	at org.jooq.impl.DefaultParseContext.parse(ParserImpl.java:898)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:776)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:771)
	at org.jooq.impl.InterpreterMetaProvider.loadSource(InterpreterMetaProvider.java:106)
	at org.jooq.impl.InterpreterMetaProvider.provide(InterpreterMetaProvider.java:92)
	at org.jooq.impl.SourceMetaProvider.provide(SourceMetaProvider.java:80)
	at org.jooq.impl.DefaultDSLContext.meta(DefaultDSLContext.java:440)
	at org.jooq.test.AbstractInterpreterTest.meta(AbstractInterpreterTest.java:103)
	at org.jooq.test.AbstractInterpreterTest.meta(AbstractInterpreterTest.java:99)
	at org.jooq.test.DiffTest.meta(DiffTest.java:1351)
	at org.jooq.test.DiffTest.testAlterSequenceFlagsStartWithDefault(DiffTest.java:275)
```

The reason is that we simply try to parse an unsigned integer literal as `Long` even if there's a `-` sign that should be part of the literal, not a negation operator.

**Comment by lukaseder** [comment]
This mostly only happens with sequence flags and a few other statements. We don't usually call this particular method, as we don't know the numeric type in most contexts.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.21.0
- 3.20.7 (https://github.com/jOOQ/jOOQ/issues/18911)
- 3.19.26 (https://github.com/jOOQ/jOOQ/issues/18912)
- 3.18.33 (https://github.com/jOOQ/jOOQ/issues/18913)
