### ISSUE TITLE
Parser doesn't support qualified identifiers in DROP TYPE statement

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#17808]
As reported here:

- https://github.com/jOOQ/jOOQ/issues/17804#issuecomment-2561611343

We should support parsing this syntax

```sql
DROP TYPE IF EXISTS "mjga"."oidc_platfrom";
```

Currently, there's an error:

```
Caused by: org.jooq.impl.ParserException: Unsupported query type: [15:27] ...ISTS mjga.oidc_id_seq;
DROP TYPE IF EXISTS "mjga"[*]."oidc_platfrom";
CREATE TYPE "mjga"."oidc_platfrom" AS ENUM ('oidc_name');

-...
	at org.jooq.impl.DefaultParseContext.exception(ParserImpl.java:15212)
	at org.jooq.impl.DefaultParseContext.parseQuery(ParserImpl.java:1291)
	at org.jooq.impl.DefaultParseContext.lambda$parse$0(ParserImpl.java:910)
```

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.17 (https://github.com/jOOQ/jOOQ/issues/17812)
- 3.18.24 (https://github.com/jOOQ/jOOQ/issues/17813)
- 3.17.33 (https://github.com/jOOQ/jOOQ/issues/17814)
