### ISSUE TITLE
Parse and ignore ALTER SEQUENCE .. OWNED BY syntax

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#17806]
As reported here:

- https://github.com/jOOQ/jOOQ/issues/17804

We should support parsing this syntax as per pg_dump exports:

```sql
ALTER SEQUENCE mjga.oidc_id_seq OWNED BY mjga.oidc.id;
```

Currently, there's an error:

```
*Caused by: org.jooq.impl.ParserException: CACHE, CYCLE, INCREMENT BY, MAXVALUE, MINVALUE, NO CACHE, NO CYCLE, NO MAXVALUE, NO MINVALUE, OWNER TO, RENAME TO, RESTART, or START WITH expected: [69:33] ...; Owner: -
--

ALTER SEQUENCE mjga.oidc_id_seq [*]OWNED BY mjga.oidc.id;

--
-- Name: permission; Type: TABLE; Schema: mjga; ...
	at org.jooq.impl.DefaultParseContext.expected(ParserImpl.java:15195)
	at org.jooq.impl.DefaultParseContext.parseAlterSequence(ParserImpl.java:4458)
	at org.jooq.impl.DefaultParseContext.parseAlter(ParserImpl.java:3072)
	at org.jooq.impl.DefaultParseContext.parseQuery(ParserImpl.java:1122)
	at org.jooq.impl.DefaultParseContext.lambda$parse$0(ParserImpl.java:910)
	at org.jooq.impl.DefaultParseContext.wrap(ParserImpl.java:15405)
	at org.jooq.impl.DefaultParseContext.parse(ParserImpl.java:898)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:776)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:771)
	at org.jooq.meta.extensions.ddl.DDLDatabase.load(DDLDatabase.java:179)
	at org.jooq.meta.extensions.ddl.DDLDatabase.lambda$export$0(DDLDatabase.java:166)
	at org.jooq.FilePattern.load0(FilePattern.java:310)
	at org.jooq.FilePattern.load(FilePattern.java:290)
	at org.jooq.FilePattern.load(FilePattern.java:303)
	at org.jooq.FilePattern.load(FilePattern.java:259)
	at org.jooq.meta.extensions.ddl.DDLDatabase.export(DDLDatabase.java:166)
	at org.jooq.meta.extensions.AbstractInterpretingDatabase.connection(AbstractInterpretingDatabase.java:100)
	... 127 more
```

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.17 (https://github.com/jOOQ/jOOQ/issues/17809)
- 3.18.24 (https://github.com/jOOQ/jOOQ/issues/17810)
- 3.17.33 (https://github.com/jOOQ/jOOQ/issues/17811)
