### ISSUE TITLE
Support parsing PostgreSQL nextval(sequence_name::regclass) syntax

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#17807]
As reported here:

- https://github.com/jOOQ/jOOQ/issues/17804

We should support parsing this syntax as per pg_dump exports:

```sql
ALTER TABLE ONLY mjga.oidc ALTER COLUMN id SET DEFAULT nextval('mjga.oidc_id_seq'::regclass);
```

Currently, there's an error:

```
Caused by: org.jooq.impl.ParserException: Token ')' expected: [199:82] ...R COLUMN id SET DEFAULT nextval('mjga.oidc_id_seq'[*]::regclass);


--
-- Name: purchase oder_no_uniq; Type: CONSTRAINT; Schema: ...
	at org.jooq.impl.DefaultParseContext.expected(ParserImpl.java:15178)
	at org.jooq.impl.DefaultParseContext.parse(ParserImpl.java:14339)
	at org.jooq.impl.DefaultParseContext.parse(ParserImpl.java:14334)
	at org.jooq.impl.DefaultParseContext.parseNextvalCurrvalIf(ParserImpl.java:9883)
	at org.jooq.impl.DefaultParseContext.parseTerm(ParserImpl.java:9082)
	at org.jooq.impl.DefaultParseContext.parseUnaryOps(ParserImpl.java:8376)
```

We can simply parse and ignore the `::regclass` cast, as it is optional also in PostgreSQL

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.17 (https://github.com/jOOQ/jOOQ/issues/17815)
- 3.18.24 (https://github.com/jOOQ/jOOQ/issues/17816)
- 3.17.33 (https://github.com/jOOQ/jOOQ/issues/17817)

**Comment by lukaseder** [comment]
We already support this syntax in `CREATE TABLE`, just not in `ALTER TABLE`, though it should probably be translated to a new statement type, instead of maintaining the `DEFAULT`:

- https://github.com/jOOQ/jOOQ/issues/8936
