### ISSUE TITLE
SQLDialect.AURORA_POSTGRES should cast JSONB and similar types in INSERT statements

### ISSUE THREAD

**Issue by Petersoj** [jOOQ/jOOQ#17818]
### Expected behavior

Inserting a jOOQ Codegen `Record` with a `JSONB` column should work as usual.

### Actual behavior

Aurora Postgres is throwing a casting error.

### Steps to reproduce the problem

1. Create a test table with a `JSONB` column:
    ```sql
    CREATE TABLE test_table
    (
        id       UUID PRIMARY KEY,
        metadata JSONB
    )
    ```
1. Run jOOQ Codegen with the following configuration:
    ```java
    .withGenerator(new Generator()
            .withDatabase(new Database()
                    .withName(AuroraPostgresDatabase.class.getCanonicalName())
                    .withInputSchema("public")
                    .withOutputSchema("public"))
            .withGenerate(new Generate()
                    .withRecords(true)
                    .withDaos(false)
                    .withJavaTimeTypes(true)
                    .withFluentSetters(true)
                    .withImplicitJoinPathsToOne(false)
                    .withImplicitJoinPathsToMany(false))
    ```
1. Run this code:
    ```java
    // This works
    db.insertInto(TEST_TABLE)
            .set(TEST_TABLE.ID, UUID.randomUUID())
            .set(TEST_TABLE.METADATA, cast("{\"a\":\"b\"}", SQLDataType.JSONB))
            .execute();
    
    // This fails
    final TestTableRecord testTableRecord = new TestTableRecord();
    testTableRecord.setId(UUID.randomUUID());
    testTableRecord.setMetadata(JSONB.jsonb("{\"a\":\"b\"}"));
    db.insertInto(TEST_TABLE)
            .set(testTableRecord)
            .execute();
    ```
1. The following is the output:
    ```
    DEBUG 2024-12-30 02:36:09.635 UTC [main] org.jooq.tools.LoggerListener - Executing query          : insert into "public"."test_table" ("id", "metadata") values (?, cast(? as jsonb))
    DEBUG 2024-12-30 02:36:09.640 UTC [main] org.jooq.tools.LoggerListener - -> with bind values      : insert into "public"."test_table" ("id", "metadata") values ('e311e4c9-94b1-4ab3-b2a4-bb253b6225d7', cast('{"a":"b"}' as jsonb))
    DEBUG 2024-12-30 02:36:09.675 UTC [main] org.jooq.tools.LoggerListener - Affected row(s)          : 1
    DEBUG 2024-12-30 02:36:09.688 UTC [main] org.jooq.tools.LoggerListener - Executing query          : insert into "public"."test_table" ("id", "metadata") values (?, ?)
    DEBUG 2024-12-30 02:36:09.689 UTC [main] org.jooq.tools.LoggerListener - -> with bind values      : insert into "public"."test_table" ("id", "metadata") values ('005b8ba2-d9de-4765-8186-759df7a978fe', '{"a":"b"}')
    DEBUG 2024-12-30 02:36:09.717 UTC [main] org.jooq.tools.LoggerListener - Exception
    org.jooq.exception.DataAccessException: SQL [insert into "public"."test_table" ("id", "metadata") values (?, ?)]; ERROR: column "metadata" is of type jsonb but expression is of type character varying
      Hint: You will need to rewrite or cast the expression.
      Position: 66
            at org.jooq_3.19.16.AURORA_POSTGRES.debug(Unknown Source)
            at org.jooq.impl.Tools.translate(Tools.java:3614)
            at org.jooq.impl.Tools.translate(Tools.java:3602)
            at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:827)
            at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:362)
            at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
    ```

### jOOQ Version

jOOQ Professional Edition 3.19.16 (also using `jooq-postgres-extensions` and `jooq-codegen`)

### Database product and version

PostgreSQL 16.6 on aarch64-unknown-linux-gnu, compiled by aarch64-unknown-linux-gnu-gcc (GCC) 9.5.0, 64-bit

### Java Version

openjdk version "21.0.5" 2024-10-15 LTS

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.4

**Comment by lukaseder** [comment]
Thanks a lot for your report. I can reproduce this with the `AURORA_POSTGRES` dialect, but not with the `POSTGRES` one. Will look into this right away.

**Comment by lukaseder** [comment]
Probably a side-effect of https://github.com/jOOQ/jOOQ/issues/10033

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.17 (https://github.com/jOOQ/jOOQ/issues/17824)
- 3.18.24 (https://github.com/jOOQ/jOOQ/issues/17825)
- 3.17.33 (https://github.com/jOOQ/jOOQ/issues/17826)
