### ISSUE TITLE
Make jOOQ an OSGi Bundle

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2292]
It may make sense to make jOOQ a proper OSGi bundle and build jOOQ accordingly. This might mean that a dependency on OSGi artefacts are inevitable.

Some hints can be found in the Apache Sling project, e.g. how to wrap the Postgres JDBC driver in a bundle:
http://sling.apache.org/site/jackrabbit-persistence.html

**Comment by gadieichhorn** [comment]
Hi Lukas,

I found this old open issue and wondered if there is a way to use JOOQ code generation as part of an OSGi project?

my existing plan is:
1. create a datasource with HikariCP 
2. generate the database tables with flyway (migration)
3. generate code (JOOQ) after migration is completed

1 & 2 works fine

I am using bndtools on eclipse
the JOOQ version available on JPM is 3.8.3

I am getting class not found exception when I try to call the tool (step 3) the configuration is from the JOOQ documentation.

`GenerationTool.generate(configuration);
`

I tested with or without the TccL Switch code. same error

```
public class TcclSwitch {

	public static <T> T executeWithTCCLSwitch(Callable<T> action) throws Exception {
		final ClassLoader original = Thread.currentThread().getContextClassLoader();
		try {
			Thread.currentThread().setContextClassLoader(TcclSwitch.class.getClassLoader());
			return action.call();
		} finally {
			Thread.currentThread().setContextClassLoader(original);
		}
	}

```

here is the full error

```
ERROR: osgi.example.data.jooq.provider (29): [osgi.example.data.jooq.provider.JooqDSLContextProvider(8)] The activate method has thrown an exception
java.lang.NoClassDefFoundError: org/jooq/util/GenerationTool
	at osgi.example.data.jooq.provider.JooqDSLContextProvider.lambda$0(JooqDSLContextProvider.java:55)
	at osgi.example.data.jooq.provider.TcclSwitch.executeWithTCCLSwitch(TcclSwitch.java:21)
	at osgi.example.data.jooq.provider.JooqDSLContextProvider.activate(JooqDSLContextProvider.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.felix.scr.impl.helper.BaseMethod.invokeMethod(BaseMethod.java:222)
	at org.apache.felix.scr.impl.helper.BaseMethod.access$500(BaseMethod.java:37)
	at org.apache.felix.scr.impl.helper.BaseMethod$Resolved.invoke(BaseMethod.java:615)
	at org.apache.felix.scr.impl.helper.BaseMethod.invoke(BaseMethod.java:499)
	at org.apache.felix.scr.impl.helper.ActivateMethod.invoke(ActivateMethod.java:295)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:302)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:113)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:866)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:833)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:774)
	at org.apache.felix.framework.ServiceRegistrationImpl.getFactoryUnchecked(ServiceRegistrationImpl.java:347)
	at org.apache.felix.framework.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:247)
	at org.apache.felix.framework.ServiceRegistry.getService(ServiceRegistry.java:344)
	at org.apache.felix.framework.Felix.getService(Felix.java:3699)
	at org.apache.felix.framework.BundleContextImpl.getService(BundleContextImpl.java:470)
	at org.apache.felix.scr.impl.manager.SingleRefPair.getServiceObject(SingleRefPair.java:72)
	at org.apache.felix.scr.impl.helper.FieldHandler$ReferenceMethodImpl.getServiceObject(FieldHandler.java:969)
	at org.apache.felix.scr.impl.manager.DependencyManager.getServiceObject(DependencyManager.java:2137)
	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.prebind(DependencyManager.java:1048)
	at org.apache.felix.scr.impl.manager.DependencyManager.prebind(DependencyManager.java:1457)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.collectDependencies(AbstractComponentManager.java:983)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:812)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:724)
	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:954)
	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:915)
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1215)
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1136)
	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:945)
	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:881)
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1167)
	at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:120)
	at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:991)
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:839)
	at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:546)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4557)
	at org.apache.felix.framework.Felix.registerService(Felix.java:3549)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:348)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:869)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:857)
	at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:133)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:915)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:715)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:399)
	at org.apache.felix.scr.impl.config.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:676)
	at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:339)
	at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:360)
	at org.apache.felix.scr.impl.Activator.access$000(Activator.java:53)
	at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:260)
	at org.apache.felix.utils.extender.AbstractExtender.createExtension(AbstractExtender.java:259)
	at org.apache.felix.utils.extender.AbstractExtender.modifiedBundle(AbstractExtender.java:232)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:482)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:415)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232)
	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:444)
	at org.apache.felix.framework.util.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:916)
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:835)
	at org.apache.felix.framework.util.EventDispatcher.fireBundleEvent(EventDispatcher.java:517)
	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4541)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2172)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
	at aQute.launcher.Launcher.update(Launcher.java:483)
	at aQute.launcher.Launcher$1.run(Launcher.java:233)
	at java.util.TimerThread.mainLoop(Unknown Source)
	at java.util.TimerThread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.jooq.util.GenerationTool not found by org.jooq.meta [28]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1574)
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2018)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.apache.felix.framework.BundleWiringImpl.getClassByDelegation(BundleWiringImpl.java:1415)
	at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1595)
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1525)
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2018)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 71 more
```

thanks in advance

**Comment by lukaseder** [comment]
Hi @gadieichhorn, thanks for your report.

Not being too experienced with OSGi, what would be the quickest, least intrusive path forward here? Would it be sufficient to just include a felix plugin declaration along the lines of this one here?
https://github.com/jOOQ/jOOQ/blob/version-3.9.0/jOOQ/pom.xml#L150

**Comment by gadieichhorn** [comment]
Hi @lukaseder 
eclipse & bndtools have a very specific way of working and I couldn't get this to work properly for now. I have more success with Karaf.
Thanks for your support.

**Comment by lukaseder** [comment]
Thanks for your feedback, @gadieichhorn. I see, well, only the jOOQ core library is currently published as a bundle using the Apache Felix `maven-bundle-plugin`, not jOOQ-meta or jOOQ-codegen.

My point was, instead of me blindly adding that plugin to all artefacts, I was wondering if you could do some validation on your side to see if that would work / be sufficient. This is what I mean:
https://github.com/jOOQ/jOOQ/blob/version-3.9.1/jOOQ/pom.xml#L149

Would you be interested in experimenting a custom build of jOOQ-meta and jOOQ-codegen with that plugin added, to see if that fixes the issue at your side?

Of course, I could try fixing this on my side as well, but for that, I would need more precise instructions regarding how to reproduce the issue.

Thanks,
Lukas

**Comment by gadieichhorn** [comment]
Hi @lukaseder 

with the maven _(maven-bundle-plugin)_ process there is no issue with these bundles because this is not runtime dependency. What I am working on now is a way to provide JOOQ as a pure OSGi service. this is the next level up than just making it OSGi friendly. I will share my findings once I have a better working prototype. Here is an example of an OSGI / JOOQ / Vert.x project I was using to get started with JOOQ -> http://qrman.github.io/posts/2015/10/05/vertx-guice-jooq-ultm

Regarding the bndtools/eclipse, the challenge is with code generation first and then the OSGi packaging. I think it will be better to ask the bndtools community. 

In Karaf I had to wrap jooq bundle feature like so:
`        <bundle start-level="80">wrap:mvn:org.jooq/jooq/${jooq.version}</bundle>
`
Then it is loaded into the runtime with no issues.

I don't know eclipse or bndtools well enough to be able to contribute anything useful for now. sorry.

**Comment by lukaseder** [comment]
OK, thank you very much for the explanations. Looking forward to your findings, then!

**Comment by lukaseder** [comment]
Hardly anyone is using OSGi anymore, and thus the cost/benefit ratio of this task here is not worth it.
