### ISSUE TITLE
Error in code generator when the sqlite_sequence table is missing

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2608]
The `sqlite_sequence` table seems to be created only once an `autoincrement` column is present on any table.

jOOQ's code generator fails in the absence of this table.

**Comment by brweaver** [comment]
Is this the same error?  

CREATE TABLE booklist (
    id INTEGER PRIMARY KEY,
    created DATETIME NOT NULL,
    last_modified DATETIME NOT NULL,
    listName varchar(255) NOT NULL
);


Apr 06, 2016 9:52:21 PM org.jooq.tools.JooqLogger info
INFO: Generating table         : Booklist.java
Apr 06, 2016 9:52:21 PM org.jooq.tools.JooqLogger error
SEVERE: Error while generating table booklist
org.jooq.exception.DataAccessException: SQL [select count(*) from sqlite_sequence where name = ?]; [SQLITE_ERROR] SQL error or missing database (no such table: sqlite_sequence)
	at org.jooq.impl.Util.translate(Util.java:621)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:360)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:176)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:252)
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:386)
	at org.jooq.impl.Factory.fetchOne(Factory.java:1621)
	at org.jooq.util.sqlite.SQLiteTableDefinition.getElements0(SQLiteTableDefinition.java:77)
	at org.jooq.util.AbstractElementContainerDefinition.getElements(AbstractElementContainerDefinition.java:80)
	at org.jooq.util.AbstractTableDefinition.getColumns(AbstractTableDefinition.java:135)
	at org.jooq.util.AbstractTableDefinition.getMainUniqueKey(AbstractTableDefinition.java:73)
	at org.jooq.util.DefaultGenerator.generateTable(DefaultGenerator.java:1530)
	at org.jooq.util.DefaultGenerator.generateTables(DefaultGenerator.java:1511)
	at org.jooq.util.DefaultGenerator.generate(DefaultGenerator.java:211)
	at org.jooq.util.DefaultGenerator.generate(DefaultGenerator.java:186)
	at org.jooq.util.GenerationTool.main(GenerationTool.java:405)
	at org.jooq.util.maven.Plugin.execute(Plugin.java:91)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: sqlite_sequence)
	at org.sqlite.core.DB.newSQLException(DB.java:890)
	at org.sqlite.core.DB.newSQLException(DB.java:901)
	at org.sqlite.core.DB.throwex(DB.java:868)
	at org.sqlite.core.NativeDB.prepare(Native Method)
	at org.sqlite.core.DB.prepare(DB.java:211)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:40)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:29)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:18)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:47)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:254)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
	at org.jooq.impl.ConnectionProxy.prepareStatement(ConnectionProxy.java:89)
	at org.jooq.impl.DataSourceConnection.prepareStatement(DataSourceConnection.java:141)
	at org.jooq.impl.AbstractResultQuery.prepare(AbstractResultQuery.java:130)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:162)
	... 40 more

**Comment by brweaver** [comment]
Ha; yes it was; but I was using a 2.* version of the maven plugin.
