### ISSUE TITLE
Impossible to inline "decimals" parameter of ROUND() function

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2967]
Currently, jOOQ only allows for `int` types as the "decimals" parameter of the `ROUND()` function. This prevents generating named/inlined parameters.

Other functions might also suffer from this flaw.

---

As reported here:
https://groups.google.com/forum/#!topic/jooq-user/43dF6Tv7aTc

**Comment by knutwannheden** [comment]
I just stumbled over this in the parser. Not only are bind variables always generated, but the parser also doesn't allow expressions for the "decimals" parameter as in `ROUND(x, 1+2)`.

**Comment by knutwannheden** [comment]
The Derby emulation will however only be possible if "decimals" is a `Param` object. I suppose that is acceptable.

**Comment by knutwannheden** [comment]
Emulating using `POWER()` doesn't work as that function itself is emulated (using `EXP()` and `LN()`) and thus causes rounding errors, which we might not want in `ROUND()` :rofl:

**Comment by lukaseder** [comment]
The current implementation produces a regression in SQL Server and other T-SQL dialects, where `decimals` is always generated as a `NULL` literal or bind variable, even if it is not present in user code.

The old behaviour of generating a `0` decimals argument instead will be restored for these dialects.

**Comment by lukaseder** [comment]
The regression can be seen e.g. in `testFunctionsOnNumbers_ROUND_FLOOR_CEIL_TRUNC`

```
org.jooq.exception.DataAccessException: SQL [select round(?, ?), round(?, ?), floor(?), ceiling(?), round(?, 0, 1), round(?, 2, 1), round(?, -1, 1) -- SQL rendered with a free trial version of jOOQ 3.13.0-SNAPSHOT]; Argument data type varbinary is invalid for argument 2 of round function.
	at org.jooq_3.13.0-SNAPSHOT.SQLSERVER2017.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2751)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:755)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:382)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:502)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:471)
	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:485)
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:654)
	at org.jooq.impl.SelectImpl.fetchOne(SelectImpl.java:2884)
	at org.jooq.test.all.testcases.FunctionTests.testFunctionsOnNumbers_ROUND_FLOOR_CEIL_TRUNC(FunctionTests.java:601)
	at org.jooq.test.jOOQAbstractTest.testFunctionsOnNumbers_ROUND_FLOOR_CEIL_TRUNC(jOOQAbstractTest.java:4452)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Argument data type varbinary is invalid for argument 2 of round function.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:600)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:522)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7225)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3053)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:503)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:3956)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:295)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:368)
	... 38 more
```

**Comment by lukaseder** [comment]
The regression only affects 3.13.0-SNAPSHOT, as this change here has not been backported to 3.12
