### ISSUE TITLE
Regression in handling of Oracle ARRAY types

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3687]
This is a regression because of an erroneous merge for #3639 (merge: #3640). Only Oracle clients are affected

**Comment by kauldeepak25** [comment]
Hi lukaseder,

I'm facing below error while trying to insert the collection using stored procedure in oracle using jooq 3.5.1 trial version.
org.jooq.tools.reflect.ReflectException: java.lang.NoSuchMethodException: com.jolbox.bonecp.ConnectionHandle.createARRAY(java.lang.String, [Lcom.tlc.dbcore.database.udt.records.MyObjectRecord;)
       at org.jooq.tools.reflect.Reflect.call(Reflect.java:368)
       at org.jooq.impl.DefaultBinding.set(DefaultBinding.java:1103)
       at org.jooq.impl.DefaultBindContext.bindValue0(DefaultBindContext.java:62)
       at org.jooq.impl.AbstractBindContext.bindValue(AbstractBindContext.java:127)
       at org.jooq.impl.ArrayConstant.bind0(ArrayConstant.java:104)
       at org.jooq.impl.ArrayConstant.accept(ArrayConstant.java:80)
       at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:256)
       at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:91)
       at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:353)
       at org.jooq.impl.AbstractContext.visit(AbstractContext.java:133)
       at org.jooq.impl.AbstractRoutine.bind0(AbstractRoutine.java:419)
       at org.jooq.impl.AbstractRoutine.accept(AbstractRoutine.java:404)
       at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:256)
       at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:91)
       at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:353)
       at org.jooq.impl.AbstractContext.visit(AbstractContext.java:133)
       at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:338)
       at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:270)
       at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:256)
       at com.tlc.dbcore.database.Routines.callInsertMydata(Routines.java:609)
       at com.db.tlc.dbcore.libs.CollectionInJooqService.start(CollectionInJooqService.java:49)
       at com.db.tlc.dbcore.libs.AbstractApplication.startService(AbstractApplication.java:65)
       at com.db.tlc.dbcore.libs.TestCollectionInJooq.start(TestCollectionInJooq.java:33)
       at com.db.tlc.dbcore.libs.TestCollectionInJooq.main(TestCollectionInJooq.java:58)
Caused by: java.lang.NoSuchMethodException: com.jolbox.bonecp.ConnectionHandle.createARRAY(java.lang.String, [Lcom.tlc.dbcore.database.udt.records.MyObjectRecord;)
       at java.lang.Class.getMethod(Class.java:1655)
       at org.jooq.tools.reflect.Reflect.call(Reflect.java:355)

**Comment by lukaseder** [comment]
@kauldeepak25 : Thank you very much for reporting this. We will look into this right away and keep you posted

**Comment by lukaseder** [comment]
I can reproduce this issue with bonecp. A temporary workaround would be to use DBCP instead, for which the fix in #3639 was implemented. We'll review #3639 as it was admittedly not fixed thoroughly

**Comment by lukaseder** [comment]
I've created a new issue for this problem: #3957

**Comment by lukaseder** [comment]
#3957 has been fixed for 3.6.0 and will be merged to 3.5.2. We're expecting the 3.5.2 release for next week. Let me know if the workaround helps for now, or if I can be of further assistance.

Thanks again for reporting this!

**Comment by kauldeepak25** [comment]
Hi Lukas

Thanks for your support.

Regards
Deepak kaul
