### ISSUE TITLE
NullPointerException when generating SQLite table with composite primary key

### ISSUE THREAD

**Issue by shovelknight** [jOOQ/jOOQ#4022]
the value of pk will be greater than 1. Thanks.
```java
boolean pk = record.getValue("pk", Boolean.class);
```

schema
```
CREATE TABLE ShareBal (
    _$topic text not null,
    _$mtime text not null,
    _$source text not null,
    Date text not null,
    Market text not null,
    Symbol text not null,
    NumSeq BIGINT not null,
    JobTitle text,
    Name text,
    AppointHoldVol BIGINT,
    HoldVol BIGINT,
    Pledge BIGINT,
    PledgeRatio DOUBLE,
    PartyHoldVol BIGINT,
    PartyPledgeVol BIGINT,
    PartyPledgeRatio DOUBLE,
    primary key (Date, Market, Symbol, NumSeq)
);
sqlite> pragma table_info(ShareBal);
0|_$topic|text|1||0
1|_$mtime|text|1||0
2|_$source|text|1||0
3|Date|text|1||1
4|Market|text|1||2
5|Symbol|text|1||3
6|NumSeq|BIGINT|1||4
7|JobTitle|text|0||0
8|Name|text|0||0
9|AppointHoldVol|BIGINT|0||0
10|HoldVol|BIGINT|0||0
11|Pledge|BIGINT|0||0
12|PledgeRatio|DOUBLE|0||0
13|PartyHoldVol|BIGINT|0||0
14|PartyPledgeVol|BIGINT|0||0
15|PartyPledgeRatio|DOUBLE|0||0
```

call stack
```
java.lang.NullPointerException: null
	at org.jooq.util.sqlite.SQLiteTableDefinition.getElements0(SQLiteTableDefinition.java:86) ~[jooq-meta-3.5.1.jar:na]
	at org.jooq.util.AbstractElementContainerDefinition.getElements(AbstractElementContainerDefinition.java:90) ~[jooq-meta-3.5.1.jar:na]
	at org.jooq.util.AbstractTableDefinition.getColumns(AbstractTableDefinition.java:138) ~[jooq-meta-3.5.1.jar:na]
	at org.jooq.util.AbstractTableDefinition.getPrimaryKey(AbstractTableDefinition.java:78) ~[jooq-meta-3.5.1.jar:na]
	at org.jooq.util.JavaGenerator.generateTable(JavaGenerator.java:2033) [jooq-codegen-3.5.1.jar:na]
	at org.jooq.util.JavaGenerator.generateTables(JavaGenerator.java:2022) [jooq-codegen-3.5.1.jar:na]
	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:289) [jooq-codegen-3.5.1.jar:na]
	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:247) [jooq-codegen-3.5.1.jar:na]
	at org.jooq.util.GenerationTool.run(GenerationTool.java:402) [jooq-codegen-3.5.1.jar:na]
	at org.jooq.util.GenerationTool.main(GenerationTool.java:167) [jooq-codegen-3.5.1.jar:na]
	at dwarf.db.Codegen.main(Codegen.java:84) [classes/:na]
```

**Comment by lukaseder** [comment]
Thanks a lot for reporting. This has gone unnoticed through our integration tests. We have composite primary keys, but we don't currently rely on them.
