### ISSUE TITLE
NullPointerException when generating source code for PostgreSQL table-valued function that returns nested arrays

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4052]
This function:

```sql
CREATE OR REPLACE FUNCTION f_array_tables(in_text IN text[], in_integer IN integer[])
RETURNS TABLE (
    out_text text[],
    out_integer integer[]
)
AS $$
BEGIN
    out_text := NULL;
    out_integer := NULL;
    RETURN NEXT;
    
    out_text := ARRAY[]::text[];
    out_integer := ARRAY[]::integer[];
    RETURN NEXT;
    
    out_text := ARRAY['a'];
    out_integer := ARRAY[1];
    RETURN NEXT;
    
    out_text := ARRAY['a', 'b'];
    out_integer := ARRAY[1, 2];
    RETURN NEXT;
END
$$ LANGUAGE plpgsql;
```

Generates

```
Error while generating table record public.f_array_tables
java.lang.NullPointerException
at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:637)
at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:828)
at org.jooq.impl.DefaultDataType.getType(DefaultDataType.java:841)
at org.jooq.util.JavaGenerator.getType(JavaGenerator.java:3220)
at org.jooq.util.JavaGenerator.getType(JavaGenerator.java:3185)
at org.jooq.util.JavaGenerator.getType(JavaGenerator.java:3194)
at org.jooq.util.JavaGenerator.getJavaType(JavaGenerator.java:3173)
at org.jooq.util.JavaGenerator.getJavaType(JavaGenerator.java:3169)
at org.jooq.util.JavaGenerator.getRowType(JavaGenerator.java:935)
at org.jooq.util.JavaGenerator.generateRecord(JavaGenerator.java:700)
at org.jooq.util.JavaGenerator.generateRecord(JavaGenerator.java:659)
at org.jooq.util.JavaGenerator.generateRecords(JavaGenerator.java:648)
at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:309)
at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:247)
at org.jooq.util.GenerationTool.run(GenerationTool.java:402)
at org.jooq.util.GenerationTool.main(GenerationTool.java:167)
at org.jooq.util.GenerationTool$main.call(Unknown Source)
```

----
See also original bug report:
http://stackoverflow.com/q/28410929/521799

**Comment by lukaseder** [comment]
This issue seems to have already been fixed implicitly in jOOQ 3.6.0 when implementing #3376
