### ISSUE TITLE
Exception when loading array results from plain SQL queries into a Record

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4065]
I tried another version of that test:

```
test=> \d testarray
                           Table "public.testarray"
┌────────┬───────────┬────────────────────────────────────────────────────────┐
│ Column │   Type    │                       Modifiers                        │
├────────┼───────────┼────────────────────────────────────────────────────────┤
│ id     │ integer   │ not null default nextval('testarray_id_seq'::regclass) │
│ a      │ integer[] │ not null                                               │
└────────┴───────────┴────────────────────────────────────────────────────────┘
```

```
test=> \sf get_testarray
CREATE OR REPLACE FUNCTION public.get_testarray(id_p integer)
 RETURNS SETOF testarray
 LANGUAGE plpgsql
AS $function$
BEGIN
  RETURN QUERY SELECT * FROM testarray WHERE id = id_p;
END;
$function$
```
Here is the code I run:

```java
            String sql = "SELECT * FROM get_testarray(?)";
            Result<Record> result = create.fetch(sql, 1);

            System.out.println("Result: ");
            System.out.println(result);

            List<TestarrayRecord> l = result.into(TestarrayRecord.class);
```

The array part makes the whole thing explode:

```                                   
Result: 
+----+-------+
|  id|a      |
+----+-------+
|   1|{1,2,3}|
+----+-------+
org.jooq.exception.MappingException: An error ocurred when mapping record to class com.ovh.osp.sql.tables.records.TestarrayRecord
    at org.jooq.impl.DefaultRecordMapper$RecordToRecordMapper.map(DefaultRecordMapper.java:430)
    at org.jooq.impl.DefaultRecordMapper$RecordToRecordMapper.map(DefaultRecordMapper.java:418)
    at org.jooq.impl.DefaultRecordMapper.map(DefaultRecordMapper.java:331)
    at org.jooq.impl.ResultImpl.into(ResultImpl.java:1502)
    at test.Test.main(Test.java:57)
Caused by: org.jooq.exception.MappingException: An error ocurred when mapping record to +----+------+
|  id|a     |
+----+------+
|   1|{null}|
+----+------+
    at org.jooq.impl.AbstractRecord$TransferRecordState.operate(AbstractRecord.java:754)
    at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:123)
    at org.jooq.impl.AbstractRecord.intoRecord(AbstractRecord.java:701)
    at org.jooq.impl.DefaultRecordMapper$RecordToRecordMapper.map(DefaultRecordMapper.java:424)
    ... 4 more
Caused by: org.jooq.exception.DataTypeException: Cannot convert from {1,2,3} (class org.postgresql.jdbc4.Jdbc4Array) to class [Ljava.lang.Integer;
    at org.jooq.tools.Convert$ConvertAll.fail(Convert.java:873)
    at org.jooq.tools.Convert$ConvertAll.from(Convert.java:811)
    at org.jooq.tools.Convert.convert0(Convert.java:300)
    at org.jooq.tools.Convert.convert(Convert.java:292)
    at org.jooq.tools.Convert.convert(Convert.java:360)
    at org.jooq.impl.DefaultDataType.convert(DefaultDataType.java:614)
    at org.jooq.impl.AbstractRecord$TransferRecordState.operate(AbstractRecord.java:732)
    ... 7 more
```

**Comment by timic** [comment]
@lukaseder Bug still reproduces with `org.postgresql:postgresql:9.3-1104-jdbc41` and `org.jooq:jooq:3.9.4`:

```
Caused by: org.jooq.exception.DataTypeException: Cannot convert from {1,2,3} (class org.postgresql.jdbc4.Jdbc4Array) to class [Ljava.lang.String;
	at org.jooq.tools.Convert$ConvertAll.fail(Convert.java:1118) ~[jooq-3.9.4.jar:na]
	at org.jooq.tools.Convert$ConvertAll.from(Convert.java:1007) ~[jooq-3.9.4.jar:na]
	at org.jooq.tools.Convert.convert0(Convert.java:316) ~[jooq-3.9.4.jar:na]
	at org.jooq.tools.Convert.convert(Convert.java:308) ~[jooq-3.9.4.jar:na]
	at org.jooq.tools.Convert.convert(Convert.java:380) ~[jooq-3.9.4.jar:na]
	at org.jooq.impl.AbstractRecord.get(AbstractRecord.java:245) ~[jooq-3.9.4.jar:na]
	at org.jooq.impl.DefaultRecordMapper$MutablePOJOMapper.map(DefaultRecordMapper.java:726) ~[jooq-3.9.4.jar:na]
	at org.jooq.impl.DefaultRecordMapper$MutablePOJOMapper.map(DefaultRecordMapper.java:646) ~[jooq-3.9.4.jar:na]
```

**Comment by lukaseder** [comment]
@timic: Thank you very much for reporting this. There might be a similar bug that is not strictly the same one as this one. Our integration tests include the following working test for the above function:

```java
    @Test
    public void testPostgresArraysInTableValuedFunctionResults() throws Exception {

        // [#4065] Plain SQL
        // UDT and Enum type arrays cannot be recognised via JDBC's ResultSetMetaData...
        Record record = create().fetchOne("select id, string_array, number_array, date_array from f_get_arrays(?)", 4);
        TArraysRecord into = record.into(TArraysRecord.class);

        assertEquals(4, (int) record.getValue(TArrays_ID()));
        assertEquals(4, (int) into.getId());

        assertEquals(asList("a", "b"), asList(record.getValue(TArrays_STRING().getName(), String[].class)));
        assertEquals(asList("a", "b"), asList(into.getStringArray()));

        assertEquals(asList(1, 2), asList(record.getValue(TArrays_NUMBER().getName(), Integer[].class)));
        assertEquals(asList(1, 2), asList(into.getNumberArray()));

        assertEquals(
            asList(Date.valueOf("1981-07-10"), Date.valueOf("2000-01-01")),
            asList(record.getValue(TArrays_DATE().getName(), Date[].class)));
        assertEquals(
            asList(Date.valueOf("1981-07-10"), Date.valueOf("2000-01-01")),
            asList(into.getDateArray()));

    }
```

Please feel free to open a new issue with steps to reproduce and we'll look at it ASAP.

**Comment by rusbob** [comment]
Still the same on Postgres 9.5:
```
Jul 05, 2020 11:48:39 PM org.jooq.tools.JooqLogger warn
WARNING: Error while freeing resource
org.postgresql.util.PSQLException: Method org.postgresql.jdbc4.Jdbc4Array.free() is not yet implemented.
        at org.postgresql.Driver.notImplemented(Driver.java:753)
        at org.postgresql.jdbc4.Jdbc4Array.free(Jdbc4Array.java:46)
        at org.jooq.tools.jdbc.JDBCUtils.safeFree(JDBCUtils.java:581)
        at org.jooq.impl.DefaultBinding$DefaultArrayBinding.pgGetArray(DefaultBinding.java:1189)
        at org.jooq.impl.DefaultBinding$DefaultArrayBinding.get0(DefaultBinding.java:1100)
        at org.jooq.impl.DefaultBinding$DefaultArrayBinding.get0(DefaultBinding.java:961)
        at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:824)
        at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1725)
        at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.operate(CursorImpl.java:1685)
        at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.operate(CursorImpl.java:1650)
        at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:130)
        at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1614)
        at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1581)
        at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:353)
        at org.jooq.impl.CursorImpl.fetch(CursorImpl.java:339)
        at org.jooq.impl.CursorImpl.fetch(CursorImpl.java:246)
        at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:323)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:368)
        at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:353)
        at org.jooq.impl.AbstractResultQuery.iterator(AbstractResultQuery.java:364)
        at org.jooq.impl.SelectImpl.iterator(SelectImpl.java:2703)
        at org.jooq.meta.postgres.PostgresDatabase.getIndexes0(PostgresDatabase.java:168)
        at org.jooq.meta.AbstractDatabase.getIndexes(AbstractDatabase.java:1942)
        at org.jooq.meta.AbstractDatabase.getIndexes(AbstractDatabase.java:1975)
        at org.jooq.meta.AbstractTableDefinition.getIndexes(AbstractTableDefinition.java:92)
        at org.jooq.codegen.JavaGenerator.generateTable(JavaGenerator.java:4037)
        at org.jooq.codegen.JavaGenerator.generateTable(JavaGenerator.java:3818)
        at org.jooq.codegen.JavaGenerator.generateTables(JavaGenerator.java:3805)
        at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:514)
        at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:468)
        at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:389)
        at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:800)
        at org.jooq.codegen.GenerationTool.run(GenerationTool.java:221)
        at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:216)
        at org.jooq.codegen.GenerationTool.main(GenerationTool.java:188)
```

**Comment by lukaseder** [comment]
@rusbob I don't think this is the same problem. So, as I said before: *"Please feel free to open a new issue with steps to reproduce and we'll look at it ASAP."*
