### ISSUE TITLE
ArrayIndexOutOfBoundsException in org.jooq.impl.Utils.renderAndBind

### ISSUE THREAD

**Issue by ooxi** [jOOQ/jOOQ#4182]
When trying to execute the following SQL

````sql
#
# `
#

CREATE	VIEW `myview` AS
SELECT	'1' AS `one`
````

I receive an `ArrayIndexOutOfBoundsException`

````
java.lang.ArrayIndexOutOfBoundsException: 53
	at org.jooq.impl.Utils.renderAndBind(Utils.java:1269)
	at org.jooq.impl.SQLTemplate$SQLTemplateQueryPart.accept(SQLTemplate.java:83)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:365)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:353)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:133)
	at org.jooq.impl.SQLQuery.accept(SQLQuery.java:73)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:365)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:353)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:133)
	at org.jooq.impl.AbstractQuery.getSQL0(AbstractQuery.java:451)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:302)
	at org.jooq.impl.DefaultDSLContext.execute(DefaultDSLContext.java:577)
	at MY CODE
````

I'm using jOOQ 3.5.3 and MySQL as database.

**Update**: a workaround seems to be using `--` instead of `#` as comment characters. But MySQL also supports `#` and the snipped aboth executes correctly if pasted into phpMyAdmin

**Comment by lukaseder** [comment]
Related: #3630

**Comment by lukaseder** [comment]
Thanks for reporting. I can reproduce this issue

**Comment by lukaseder** [comment]
... here's a contrived example of valid MySQL that fails in jOOQ:

```sql
Result<Record> r3 = create().fetch(
    " select 1--1 + ?"
  + "    , 2 + ?"
  + " from dual"
  , 10, 20
);
```

**Comment by lukaseder** [comment]
... of course, the MySQL connector has the same bug and interprets `--1` as a comment, thus throwing:

```
org.jooq.exception.DataAccessException: SQL [null]; Parameter index out of range (2 > number of parameters, which is 1).
```

I'll file a bug with MySQL for that

**Comment by ooxi** [comment]
I did not know hat `--` had to be followed by a whitespace. It's really interesting to see the development of this bug report :)

**Comment by lukaseder** [comment]
Here's the MySQL bug report: http://bugs.mysql.com/bug.php?id=76623

**Comment by lukaseder** [comment]
> I did not know hat -- had to be followed by a whitespace

Yeah, that's completely wacko. I hope they'll remove that non-feature in the future!

**Comment by ooxi** [comment]
Great work :)

**Comment by lukaseder** [comment]
I *know* ;-)
