### ISSUE TITLE
Invalid callable syntax when calling MariaDB stored procedures

### ISSUE THREAD

**Issue by itslayo** [jOOQ/jOOQ#4350]
I'm trying to use stored procedure but I catch such an exception

`org.jooq.exception.DataAccessException: SQL [{ call `issueracq`.`AddClient`(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) }]; invalid callable syntax`

Help me! I don't understand whats wrong(

Routines.addClient
```java
public static java.lang.Integer addclient(org.jooq.Configuration configuration, java.lang.Long inidclient, java.lang.Long inidmember, java.lang.String inclphone, java.lang.Integer inclstatus, java.sql.Timestamp signeddate, java.lang.Integer inkeytype, java.lang.String inlastname, java.lang.String infirstname, java.lang.String inpatronymic, java.lang.String inpassport, java.lang.String initn, java.lang.String inaddress, java.lang.String incodeword, java.lang.Long incard, java.lang.String inexpyear, java.lang.String inexpmonth) {
        Addclient p = new Addclient();
        p.setInidclient(inidclient);
        p.setInidmember(inidmember);
        p.setInclphone(inclphone);
        p.setInclstatus(inclstatus);
        p.setSigneddate(signeddate);
        p.setInkeytype(inkeytype);
        p.setInlastname(inlastname);
        p.setInfirstname(infirstname);
        p.setInpatronymic(inpatronymic);
        p.setInpassport(inpassport);
        p.setInitn(initn);
        p.setInaddress(inaddress);
        p.setIncodeword(incodeword);
        p.setIncard(incard);
        p.setInexpyear(inexpyear);
        p.setInexpmonth(inexpmonth);
        p.execute(configuration);
        return p.getOutresult();
    }
```

AddClient constructor
```java
    public Addclient() {
        super("AddClient", Issueracq.ISSUERACQ);
        addInParameter(INIDCLIENT);
        addInParameter(INIDMEMBER);
        addInParameter(INCLPHONE);
        addInParameter(INCLSTATUS);
        addInParameter(SIGNEDDATE);
        addInParameter(INKEYTYPE);
        addInParameter(INLASTNAME);
        addInParameter(INFIRSTNAME);
        addInParameter(INPATRONYMIC);
        addInParameter(INPASSPORT);
        addInParameter(INITN);
        addInParameter(INADDRESS);
        addInParameter(INCODEWORD);
        addInParameter(INCARD);
        addInParameter(INEXPYEAR);
        addInParameter(INEXPMONTH);
        addOutParameter(OUTRESULT);
    }
```

and code of stored procedure in database (I'm using MariaDB)
```sql
DROP PROCEDURE IF EXISTS issueracq.AddClient;
CREATE DEFINER=`issueracq`@`%` PROCEDURE `AddClient`(IN `InIdClient` BIGINT, IN `InIdMember` BIGINT, IN `InClPhone` VARCHAR(14), IN `InClStatus` INT, IN `InKeyType` INT, IN `InLastName` VARCHAR(40), IN `InFirstName` VARCHAR(20), IN `InPatronymic` VARCHAR(20), IN `InPassport` VARCHAR(20), IN `InITN` VARCHAR(20), IN `InAddress` VARCHAR(256), IN `InCodeWord` VARCHAR(40), IN `InCard` BIGINT, IN `InExpYear` VARCHAR(2), IN `InExpMonth` VARCHAR(2), OUT `OutResult` INT)
BEGIN



declare tmp bigint;
set tmp = -1;

select c.IdClient
into tmp
from clients c
where c.ClPhone = InClPhone;

set OutResult = -1;

if tmp = -1 THEN
	BEGIN
		insert into clients (IdClient, IdMember, ClPhone, ClStatus,SignedDate, KeyType, LastName, FirstName, Patronymic, Passport, ITN, Address, CodeWord, Card, ExpYear, ExpMonth) 			
		VALUES (InIdClient, InIdMember, InClPhone, 5,now(), InKeyType, InLastName, InFirstName, InPatronymic, InPassport, InITN, InAddress, InCodeWord, InCard, InExpYear, InExpMonth);
		set OutResult = 0;
		
		insert into balance (IdClient, Balance) values (InIdClient, 1000000);
	END;
ELSE
	BEGIN
		update clients
		set IdMember = InIdMember, ClStatus =  InClStatus, KeyType = InKeyType, LastName = InLastName, 
		FirstName = InFirstName, Patronymic = InPatronymic, Passport = InPassport, ITN = InITN, Address = InAddress, CodeWord = InCodeWord,
		Card = InCard, ExpYear = InExpYear, ExpMonth = InExpMonth 			
		where ClPhone = InClPhone;	
		set OutResult = 1;
	END;
END IF;

END;
```

**Comment by lukaseder** [comment]
Thank you very much for reporting. Could you please provide the full stack trace?

**Comment by itslayo** [comment]
Yes. Here it is

```java
org.jooq.exception.DataAccessException: SQL [{ call `issueracq`.`AddClient`(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) }]; invalid callable syntax
	at org.jooq.impl.Utils.translate(Utils.java:1644)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:661)
	at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:373)
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:271)
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:257)
	at com.nsmep.qr.db.Routines.addclient(Routines.java:69)
	at com.nsmep.qr.dao.client.ClientDaoImpl.save(ClientDaoImpl.java:113)
	at com.nsmep.qr.dao.client.ClientDaoImpl$$FastClassBySpringCGLIB$$33307ee5.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	at com.nsmep.qr.dao.client.ClientDaoImpl$$EnhancerBySpringCGLIB$$75c6c2da.save(<generated>)
	at com.nsmep.qr.service.client.ClientServiceImpl.save(ClientServiceImpl.java:44)
	at com.nsmep.qr.controller.ClientController.save(ClientController.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:868)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:644)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLSyntaxErrorException: invalid callable syntax
	at org.mariadb.jdbc.MySQLCallableStatement.<init>(MySQLCallableStatement.java:377)
	at org.mariadb.jdbc.MySQLConnection.prepareCall(MySQLConnection.java:181)
	at org.jooq.impl.ProviderEnabledConnection.prepareCall(ProviderEnabledConnection.java:148)
	at org.jooq.tools.jdbc.DefaultConnection.prepareCall(DefaultConnection.java:101)
	at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:335)
	... 56 more
```

**Comment by lukaseder** [comment]
OK, thanks. We'll look into it as soon as possible.

**Comment by lukaseder** [comment]
This is in fact a bug in the MariaDB JDBC driver, which I've reported now:
https://mariadb.atlassian.net/browse/CONJ-161

As a workaround, use jOOQ's `Settings` and use `RenderNameStyle.AS_IS` to prevent rendering of the backticks...
