### ISSUE TITLE
Remove Serializable from DefaultDSLContext

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4393]
`AbstractScope` must provide a default constructor in order to correctly adhere to the `Serializable` contract:

```
    java.io.InvalidClassException: org.jooq.impl.DefaultDSLContext; no valid constructor
    at java.io.ObjectStreamClass$ExceptionInfo.newInvalidClassException(ObjectStreamClass.java:150)
    at java.io.ObjectStreamClass.checkDeserialize(ObjectStreamClass.java:768)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1775)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
```

But in fact, there's no point in making `DefaultDSLContext` serializable. It shouldn't be.

---

See also:
https://groups.google.com/forum/#!topic/jooq-user/K9T6jwTtrw4

**Comment by lukaseder** [comment]
The plan is to remove `Serializable` from our type hierarchy, so this doesn't have to be addressed: https://github.com/jOOQ/jOOQ/issues/2359
