### ISSUE TITLE
Implement Table.getIdentity() for tables obtained via org.jooq.Meta

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4454]
Currently, `Table` objects obtained via `org.jooq.Meta` do not expose any `Identity` from `getIdentity()`. It would be useful if they did.

---

See also:
http://blog.jooq.org/2014/11/14/jooq-tip-of-the-day-discover-all-primary-keys/#comment-132986

**Comment by lukaseder** [comment]
In order to implement this, column 22 of `DatabaseMetaData::getColumns` needs to be accessed. From experience, I'm afraid this column might not be available in some JDBC drivers that are not up to date, or did not bother implement `DatabaseMetaData` completely.

To stay on the safe side, we should check if there are 22 columns in the result set, or implement #9740

**Comment by lukaseder** [comment]
A first implementation doesn't worry about the aforementioned potential JDBC problem. In case integration tests fail, I'll fix this with a more "cautious" algorithm.

**Comment by knutwannheden** [comment]
> A first implementation doesn't worry about the aforementioned potential JDBC problem. In case integration tests fail, I'll fix this with a more "cautious" algorithm.

Note: For DB2 this change appears to cause problems:

```
org.jooq.exception.DataAccessException: Error while running ConnectionCallable
	at org.jooq.impl.DefaultDSLContext.connectionResult(DefaultDSLContext.java:686)
	at org.jooq.impl.MetaImpl.meta(MetaImpl.java:172)
	at org.jooq.impl.MetaImpl$MetaSchema.getColumns0(MetaImpl.java:462)
	at org.jooq.impl.MetaImpl$MetaSchema.getColumns(MetaImpl.java:434)
	at org.jooq.impl.MetaImpl$MetaSchema.getTables(MetaImpl.java:413)
	at org.jooq.test.BaseTest.lambda$12(BaseTest.java:1214)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1631)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.jooq.test.BaseTest.metaTable(BaseTest.java:1216)
	at org.jooq.test.all.testcases.DDLTests.testAlterTableAddConstraint_PRIMARY_KEY(DDLTests.java:1987)
	...
Caused by: org.jooq.exception.DataAccessException: SQL [null]; Error while reading field: null, at JDBC index: 24
	at org.jooq_3.13.0-SNAPSHOT.DB2.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2752)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:755)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1630)
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1581)
	at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:353)
	at org.jooq.impl.CursorImpl.fetch(CursorImpl.java:339)
	at org.jooq.impl.CursorImpl.fetch(CursorImpl.java:246)
	at org.jooq.impl.DefaultDSLContext.fetch(DefaultDSLContext.java:1193)
	at org.jooq.impl.MetaImpl$MetaSchema$2.run(MetaImpl.java:474)
	at org.jooq.impl.MetaImpl$1.run(MetaImpl.java:175)
	at org.jooq.impl.MetaImpl$1.run(MetaImpl.java:1)
	at org.jooq.impl.DefaultDSLContext.connectionResult(DefaultDSLContext.java:683)
	... 49 more
Caused by: java.sql.SQLException: Error while reading field: null, at JDBC index: 24
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1735)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.operate(CursorImpl.java:1685)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.operate(CursorImpl.java:1)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:130)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1614)
	... 58 more
Caused by: java.lang.NullPointerException
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1725)
	... 62 more
```

**Comment by lukaseder** [comment]
Thanks. Will look into this on Friday

**Comment by lukaseder** [comment]
The issue I've linked could solve this: #9740. But I'm not convinced yet I should implement #9740 without further thorough thought. Instead, I'll do what I suggested here:

https://github.com/jOOQ/jOOQ/issues/4454#issuecomment-575134910

**Comment by lukaseder** [comment]
I see what the problem is, here. Over the course of JDBC versions, new columns were added to `DatabaseMetaData::getColumns`. The last one we're currently fetching is `IS_GENERATEDCOLUMN`, which has been added in Java 7 / JDBC 4.1. In Java 6 / JDBC 4.0, the column was not yet available, and in Java 4 / JDBC 3.0, not even `IS_AUTOINCREMENT` was available.

We definitely need more lenience, and eventually, #9740, when reading out JDBC `DatabaseMetaData`

**Comment by lukaseder** [comment]
... perhaps, we could upgrade our DB2 JDBC driver, but I'm glad we ran into this problem ourselves.

**Comment by lukaseder** [comment]
SQL Server doesn't return the correct columns from `DatabaseMetaData::getColumns` according to the JDBC spec, but instead lists a few vendor specific columns, and has wrong indexes for newer JDBC columns
