### ISSUE TITLE
Improper Restriction of XML External Entity References ('XXE') in XMLasDOMBinding

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4592]
As reported by a customer, `XMLasDOMBinding` exposes a vulnerability:

**Attack Vector**: javax.xml.parsers.DocumentBuilder.parse

**Description**: The resolution of external entity references is enabled. If attacker-controlled XML can be submitted to the XML parser here, then the attacker could gain access to information about an internal network, local filesystem, or other sensitive data. This is known as an XML eXternal Entity (XXE) attack.

**Remediation**: Configure the XML parser to disable external entity resolution.

**The fix**:

The fix for this issue is as outlined on the OWASP site at this URL: 
https://www.owasp.org/index.php/XML_External_Entity_%28XXE%29_Processing

It is recommended adding all of the fixes mentioned, with the resulting code looking similar to the following:

```
    DocumentBuilderFactory docFactory = DocumentBuilderFactory.newInstance();
    String feature = EMPTY;
    try {
      // BEGIN FIXES
      feature = "http://apache.org/xml/features/disallow-doctype-decl";
      docFactory.setFeature(feature, true);
      feature = "http://xml.org/sax/features/external-general-entities";
      docFactory.setFeature(feature, false);
      docFactory.setXIncludeAware(false);
      docFactory.setExpandEntityReferences(false);
      feature = "http://xml.org/sax/features/external-parameter-entities";
      docFactory.setFeature(feature, false);
      DocumentBuilder docBuilder = docFactory.newDocumentBuilder();
      // END FIXES
      ...
      InputStream is = new ByteArrayInputStream(xml.getBytes());
      document_ = docBuilder.parse(is);
      ...
```

**Comment by lukaseder** [comment]
In our integration tests, the above produces:

```
java.lang.RuntimeException: javax.xml.parsers.ParserConfigurationException
	at org.jooq.impl.XMLasDOMBinding.builder(XMLasDOMBinding.java:178)
	at org.jooq.impl.XMLasDOMBinding.fromString(XMLasDOMBinding.java:142)
	at org.jooq.impl.XMLasDOMBinding$1.from(XMLasDOMBinding.java:91)
	at org.jooq.impl.XMLasDOMBinding$1.from(XMLasDOMBinding.java:1)
	at org.jooq.impl.DefaultBindingGetResultSetContext$1.value(DefaultBindingGetResultSetContext.java:94)
	at org.jooq.impl.AbstractVarcharBinding.get(AbstractVarcharBinding.java:84)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1571)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.operate(CursorImpl.java:1541)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.operate(CursorImpl.java:1)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:128)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchOne(CursorImpl.java:1489)
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1456)
	at org.jooq.impl.CursorImpl.fetch(CursorImpl.java:278)
	at org.jooq.impl.CursorImpl.fetch(CursorImpl.java:231)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:275)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:342)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:305)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2466)
	at org.jooq.test.all.testcases.DataTypeTests.testXMLasDOM0(DataTypeTests.java:2283)
	at org.jooq.test.all.testcases.DataTypeTests.testXMLasDOM(DataTypeTests.java:2222)
	at org.jooq.test.jOOQAbstractTest.testXMLasDOM(jOOQAbstractTest.java:3532)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: javax.xml.parsers.ParserConfigurationException
	at oracle.xml.jaxp.JXDocumentBuilderFactory.setFeature(JXDocumentBuilderFactory.java:374)
	at org.jooq.impl.XMLasDOMBinding.builder(XMLasDOMBinding.java:164)
	... 47 more
```

We should be careful with what we're setting here...
