### ISSUE TITLE
Add MySQL IFNULL() support as a synonym for NVL()

### ISSUE THREAD

**Issue by sytolk** [jOOQ/jOOQ#4761]
I think that this DSL code can be optimised for MySQL

```java
DSL.when(REGIONS_DEPENDENCE.SUB_RATING.isNull(),0).otherwise(REGIONS_DEPENDENCE.SUB_RATING))
```

for example this: `DSL.ifNull(REGIONS_DEPENDENCE.SUB_RATING,0)`

will produce for MySQL SQL: `IFNULL(REGIONS_DEPENDENCE.SUB_RATING,0)`

http://www.mysqltutorial.org/mysql-ifnull/

for other DB will generate Case.

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. I agree that `DSL.ifnull()` could be added as a synonym for the existing `DSL.nvl()`, which is exactly the same thing in Oracle.

**Comment by sytolk** [comment]
Thanks Lukas
If I use DSL.nvl function with MySQL what SQL will be generated IFNULL or CASE ?

**Comment by lukaseder** [comment]
IFNULL: https://github.com/jOOQ/jOOQ/blob/version-3.7.1/jOOQ/src/main/java/org/jooq/impl/Nvl.java#L88

**Comment by sytolk** [comment]
Only synonym and don`t forget to add in documentation some keywords like IFNULL (I can`t find it). Thanks!

**Comment by lukaseder** [comment]
Don't forget to actually look at the documentation ;-)
http://www.jooq.org/javadoc/latest/org/jooq/impl/DSL.html#nvl-org.jooq.Field-org.jooq.Field-

> Gets the Oracle-style NVL(value, defaultValue) function.
> Returns the dialect's equivalent to NVL:
>
> - DB2 NVL
> - Derby COALESCE
> - H2 IFNULL
> - HSQLDB NVL
> - MySQL IFNULL
> - Oracle NVL
> - Postgres COALESCE
> - SQLite IFNULL

I guess we could improve it though. What was missing from the documentation for you?

**Comment by sytolk** [comment]
Ok but my keywords is a little bit different https://www.google.bg/search?q=jooq+ifnull

**Comment by lukaseder** [comment]
Google replaces that query by "jooq isnull". If you insist on searching for "jooq ifnull" instead, you will find that documentation as the first result:
https://www.google.bg/search?q=jooq+ifnull#q=jooq+ifnull&nfpr=1

**Comment by sytolk** [comment]
Yes its true. Thanks again!

**Comment by sytolk** [comment]
I have change it from CASE to DSL.nvl() but its have Exception:
```
15:03:36,875  WARN SQLDialectNotSupportedException:389 - Not supported by dialect : Type class org.jooq.impl.IsNull is not supported in dialect DEFAULT
org.jooq.exception.SQLDialectNotSupportedException: Type class org.jooq.impl.IsNull is not supported in dialect DEFAULT
	at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:757)
	at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:704)
	at org.jooq.impl.DSL.getDataType(DSL.java:14344)
	at org.jooq.impl.DSL.val(DSL.java:12732)
	at org.jooq.impl.Utils.field(Utils.java:799)
	at org.jooq.impl.DSL.nvl(DSL.java:8369)
	at com.stil.db.dao.CarsDAOImpl.getCarListX(CarsDAOImpl.java:288)
	at com.stil.db.dao.CarsDAOImpl.getCarListXForUpdate(CarsDAOImpl.java:363)
	at com.stil.db.service.CarsServiceImpl.getCarListXForUpdate(CarsServiceImpl.java:274)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:201)
	at com.sun.proxy.$Proxy43.getCarListXForUpdate(Unknown Source)
	at com.stil.db.service.NewRequestServiceImpl.getCarsListForUpdate(NewRequestServiceImpl.java:887)
	at com.stil.db.service.NewRequestServiceImpl.getCarsListForUpdate(NewRequestServiceImpl.java:836)
	at com.stil.db.service.NewRequestServiceImpl.greenRequest(NewRequestServiceImpl.java:335)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52)
	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:320)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:353)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:302)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy64.greenRequest(Unknown Source)
	at jaxrs.RequestsDetailsResource.lambda$newRequest$48(RequestsDetailsResource.java:221)
	at jaxrs.RequestsDetailsResource$$Lambda$12/883787480.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
This is my jooq config and I have set SQLDialect MYSQL it is not Default. What is wrong? 
```xml
<tx:annotation-driven transaction-manager="transactionManager"/>

    <bean id="hikariConfig" class="com.zaxxer.hikari.HikariConfig">
        <property name="poolName" value="springHikariCP"/>
        <!--<property name="connectionTestQuery" value="SELECT 1"/>-->
        <property name="dataSourceClassName" value="com.mysql.jdbc.jdbc2.optional.MysqlDataSource"/>
        <property name="maximumPoolSize" value="${jdbc.maxConnectionsPerPartition}"/>
        <!--<property name="autoCommit" value="false"/>-->

        <!--change binlog_format to MIXED first  default REPEATABLE READ-->
        <property name="transactionIsolation" value="TRANSACTION_READ_COMMITTED"/>

        <!--<property name="connectionInitSql" value="SET time_zone='${database.timezone}'"/>-->

        <property name="dataSourceProperties">
            <props>
                <prop key="url">${jdbc.url}</prop>
                <prop key="user">${jdbc.user}</prop>
                <prop key="password">${jdbc.pass}</prop>
                <prop key="cachePrepStmts">true</prop>
                <prop key="prepStmtCacheSize">250</prop>
                <prop key="prepStmtCacheSqlLimit">2048</prop>
                <!--<prop key="useServerPrepStmts">true</prop>-->
            </props>
        </property>
    </bean>
    <!-- HikariCP configuration -->
    <bean id="dataSource" class="com.zaxxer.hikari.HikariDataSource" destroy-method="close">
        <constructor-arg ref="hikariConfig"/>
    </bean>

    <!--<bean id="lazyConnectionDataSource" class="org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy">
        <constructor-arg ref="dataSource"/>
    </bean>-->


    <!-- Configure Spring's transaction manager to use a DataSource -->
    <bean id="transactionManager" class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
        <property name="dataSource" ref="dataSource"/>
    </bean>

    <!-- Configure jOOQ's TransactionProvider as a proxy to Spring's transaction manager -->
    <bean id="transactionProvider" class="com.stil.db.tx.SpringTransactionProvider">
    </bean>

    <!-- Configure jOOQ's ConnectionProvider to use Spring's TransactionAwareDataSourceProxy,
         which can dynamically discover the transaction context -->
    <bean id="transactionAwareDataSource" class="org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy">
        <constructor-arg ref="dataSource"/>
    </bean>

    <bean class="org.jooq.impl.DataSourceConnectionProvider" name="connectionProvider">
        <constructor-arg ref="transactionAwareDataSource"/>
    </bean>

    <!-- Configure the DSL object, optionally overriding jOOQ Exceptions with Spring Exceptions -->
    <bean id="dsl" class="org.jooq.impl.DefaultDSLContext">
        <constructor-arg ref="config"/>
    </bean>

    <bean id="exceptionTranslator" class="com.stil.db.exception.ExceptionTranslator"/>

    <!-- Invoking an internal, package-private constructor for the example
         Implement your own Configuration for more reliable behaviour -->
    <bean class="org.jooq.impl.DefaultConfiguration" name="config">
        <property name="SQLDialect">
            <value type="org.jooq.SQLDialect">MYSQL</value>
        </property>
        <property name="connectionProvider" ref="connectionProvider"/>
        <property name="transactionProvider" ref="transactionProvider"/>
        <property name="executeListenerProvider">
            <array>
                <bean class="org.jooq.impl.DefaultExecuteListenerProvider">
                    <constructor-arg index="0" ref="exceptionTranslator"/>
                </bean>
            </array>
        </property>
    </bean>
```

**Comment by lukaseder** [comment]
How are you calling `nvl()`?

**Comment by sytolk** [comment]
With this work: CARS.RATING.sub(DSL.when(REGIONS_DEPENDENCE.SUB_RATING.isNull(),0).otherwise(REGIONS_DEPENDENCE.SUB_RATING))
But if rewrite it with nvl() like this Exception appear:
CARS.RATING.sub(DSL.nvl(REGIONS_DEPENDENCE.SUB_RATING.isNull(),0))

**Comment by lukaseder** [comment]
Huh, you're passing the `IS NULL` predicate (`Condition`) to `nvl()`. It should be:

```java
CARS.RATING.sub(DSL.nvl(REGIONS_DEPENDENCE.SUB_RATING,0))
```

It looks like due to generics, there was no compilation error...

**Comment by sytolk** [comment]
I forget to remove .isNull() maybe this is the problem..

**Comment by lukaseder** [comment]
> But why Exception is org.jooq.impl.IsNull is not supported in dialect DEFAULT I think that my dialect is MYSQL ?

That's a bug. Thanks for the reminder, I forgot to create an issue for it: #4771

Essentially, the exception is simply misleading. The problem is not the `DEFAULT` dialect that is applied here (the call to `DSL.nvl()` doesn't have access to your dialect specification) but the fact that you passed a non-`Field` `QueryPart` where a `Field` or a bind value was expected.
