### ISSUE TITLE
Confusing SQLDialectNotSupportedException when passing wrong arguments to DSL.nvl() function, and others

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4771]
When users accidentally misuse the jOOQ API, jOOQ's internals will eventually throw a misleading `SQLDialectNotSupportedException` when an AST element is mistaken for a bind variable. For instance:

```java
CARS.RATING.sub(DSL.nvl(REGIONS_DEPENDENCE.SUB_RATING.isNull(),0))
```

Producing...

```
15:03:36,875  WARN SQLDialectNotSupportedException:389 - Not supported by dialect : Type class org.jooq.impl.IsNull is not supported in dialect DEFAULT
org.jooq.exception.SQLDialectNotSupportedException: Type class org.jooq.impl.IsNull is not supported in dialect DEFAULT
    at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:757)
    at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:704)
    at org.jooq.impl.DSL.getDataType(DSL.java:14344)
    at org.jooq.impl.DSL.val(DSL.java:12732)
    at org.jooq.impl.Utils.field(Utils.java:799)
    at org.jooq.impl.DSL.nvl(DSL.java:8369)
```

The mistake is that the user has passed a `Condition` instead of a bind variable `T`.

There are two things to be done here:

1. `Condition` should be wrapped in `Field` and passed to the relevant overload
2. Other `QueryPart` types should throw an explicit exception

----
See also:
https://github.com/jOOQ/jOOQ/issues/4761#issuecomment-160625659

**Comment by lukaseder** [comment]
This won't be merged to releases prior to 3.8, as some API usage might have worked accidentally before. We don't want to risk such regressions in a patch release.
