### ISSUE TITLE
Type handling issue when using a custom type with a Postgres UDT field

### ISSUE THREAD

**Issue by akobiakov** [jOOQ/jOOQ#4964]
When specifying a `<customType>` and `<forcedType>` for a type used in a field inside a Postgres UDT, querying for this UDT field yields a `UnsupportedOperationException`.

Sample type and table definitions:

```sql
CREATE TYPE custom_type AS (
  field TIMESTAMPTZ
);

CREATE TABLE some_table (
    myfield custom_type
);
```

Setting up a JOOQ mapping like this (note, this is using Joda Time):
```xml
<customTypes>
    <customType>
        <name>JodaDateTime</name>
        <type>org.joda.time.DateTime</type>
        <converter>jooq.bug.DateTimeConverter</converter>
    </customType>
</customTypes>
<forcedTypes>
    <forcedType>
        <!-- We prefer JodaTime's DateTime instead of javax.sql.Timestamp -->
        <name>JodaDateTime</name>
        <types>(?i:\Qtimestamp with time zone\E)</types>
    </forcedType>
</forcedTypes>
```

With some arbitrary implementation of `DateTimeConverter` (where `DateTime` is `org.joda.time.DateTime`):
```java
public class DateTimeConverter extends AbstractConverter<Timestamp, DateTime> {
    public DateTimeConverter() {
        super(Timestamp.class, DateTime.class);
    }

    @Override
    public DateTime from(Timestamp databaseObject) {
        return databaseObject == null ? null : new DateTime(databaseObject);
    }

    @Override
    public Timestamp to(DateTime userObject) {
        return userObject == null ? null : new Timestamp(userObject.toDateTime().getMillis());
    }
}
```

And query using:
```java
dsl.select(SOME_TABLE.MYFIELD)
        .from(SOME_TABLE)
        .forEach(System.out::println);
```

The full exception stack trace:
```
Exception in thread "main" java.lang.UnsupportedOperationException: Class class org.joda.time.DateTime is not supported
	at org.jooq.impl.DefaultBinding.pgFromString(DefaultBinding.java:2052)
	at org.jooq.impl.DefaultBinding.pgSetValue(DefaultBinding.java:2197)
	at org.jooq.impl.DefaultBinding$2.operate(DefaultBinding.java:2090)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:128)
	at org.jooq.impl.DefaultBinding.pgNewRecord(DefaultBinding.java:2082)
	at org.jooq.impl.DefaultBinding.get(DefaultBinding.java:1436)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1640)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.operate(CursorImpl.java:1611)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.operate(CursorImpl.java:1576)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:128)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchOne(CursorImpl.java:1540)
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1507)
	at org.jooq.impl.CursorImpl.fetch(CursorImpl.java:329)
	at org.jooq.impl.CursorImpl.fetch(CursorImpl.java:282)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:275)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:342)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:305)
	at org.jooq.impl.AbstractResultQuery.iterator(AbstractResultQuery.java:316)
	at org.jooq.impl.SelectImpl.iterator(SelectImpl.java:2587)
	at java.lang.Iterable.forEach(Iterable.java:74)
	at jooq.bug.UdtTest.main(UdtTest.java:27)
```

**Comment by lukaseder** [comment]
Thank you very much for reporting. Indeed, the data type binding and converter types don't seem to be applied when deserialising nested PostgreSQL types.

We'll look into this issue soon.

**Comment by lukaseder** [comment]
Thanks again for reporting this. This is now fixed for the next release. Do note:

- You can implement a data type binding to work around this issue, as it will allow you to access the JDBC API directly, rather than depending on jOOQ's internals. It'll be a bit of work to deserialise the composite type, though: http://www.jooq.org/doc/latest/manual/code-generation/custom-data-type-bindings
- `Converter` types are probably not good enough to deserialise `timestamptz` types, as jOOQ's code generator currently doesn't support the `timestamptz` type correctly. The timezone (UTC) information is lost while reading data from the database, which will produce wrong timestamps when your server is not running in UTC.

**Comment by akobiakov** [comment]
Thank you very much for the fix!

> The timezone (UTC) information is lost while reading data from the database, which will produce wrong timestamps when your server is not running in UTC.

Luckily, seems like we don't deal with any non-UTC timestamps behind the api endpoints. :)

**Comment by lukaseder** [comment]
> Luckily, seems like we don't deal with any non-UTC timestamps behind the api endpoints. :)

Until you do! :)
