### ISSUE TITLE
Postgresql returning from clauses are handled incorrectly

### ISSUE THREAD

**Issue by BrentDouglas** [jOOQ/jOOQ#5070]
jOOQ 3.7.2
JDK 1.8.0_66
Postgresql 9.4.5

I have the following code

```java

    private static final Field<UUID> REC_EVENT_IDENTIFIER = DSL.field("rec_event_identifier", UUID.class);
    private static final Field<DateTime> REC_UPDATED_AT = DSL.field("rec_updated_at", DateTime.class);
    private static final Field<Id> CHECKPOINT_ID = DSL.field("checkpoint_id", Id.class);
    private static final Field<JsonData> CHECKPOINT_DATA = DSL.field("checkpoint_data", JsonData.class);
    private static final Field<Id> REC_EDITOR = DSL.field("rec_editor", Id.class);
    private static final Field<String> USER_NAME = DSL.field("user_name", String.class);
    private static final Field<Id> TENANT_ID = DSL.field("tenant_id", Id.class);
    private static final Field<String> REC_COMMAND_SOURCE = DSL.field("rec_command_source", String.class);


    public List<Foo<?>> getFoos() {
        return db.update(PROCESS_INSTANCE)
                .set(PROCESS_INSTANCE.RETRY, false)
                .from(SEC_USER)
                .where(PROCESS_INSTANCE.RETRY.eq(true))
                .and(PROCESS_INSTANCE.CHECKPOINT_ID.isNotNull())
                .and(SEC_USER.ID.eq(PROCESS_INSTANCE.REC_EDITOR))
                .returning(
                        PROCESS_INSTANCE.REC_EDITOR,
                        SEC_USER.USER_NAME,
                        SEC_USER.TENANT_ID,
                        PROCESS_INSTANCE.CHECKPOINT_ID,
                        PROCESS_INSTANCE.CHECKPOINT_DATA,
                        PROCESS_INSTANCE.REC_EVENT_IDENTIFIER,
                        PROCESS_INSTANCE.REC_UPDATED_AT,
                        PROCESS_INSTANCE.REC_COMMAND_SOURCE
                )
                .fetch()
                .map(r -> new Foo<>(
                        r.getValue(REC_EVENT_IDENTIFIER),
                        r.getValue(REC_UPDATED_AT),
                        r.getValue(CHECKPOINT_ID),
                        r.getValue(CHECKPOINT_DATA),
                        r.getValue(REC_EDITOR),
                        r.getValue(USER_NAME),
                        r.getValue(TENANT_ID),
                        r.getValue(REC_COMMAND_SOURCE)
                ));
    }
```

Which throws this exception:
```
java.lang.IllegalArgumentException: Field (user_name) is not contained in Row ("production"."process_instance"."id", "production"."process_instance"."process_definition_id", "production"."process_instance"."user_id", "production"."process_instance"."data", "production"."process_instance"."checkpoint_id", "production"."process_instance"."checkpoint_data", "production"."process_instance"."retry", "production"."process_instance"."rec_event_identifier", "production"."process_instance"."rec_command_identifier", "production"."process_instance"."rec_created_at", "production"."process_instance"."rec_updated_at", "production"."process_instance"."rec_editor", "production"."process_instance"."rec_command_source")
	at org.jooq.impl.Utils.indexOrFail(Utils.java:1059)
	at org.jooq.impl.AbstractRecord.getValue(AbstractRecord.java:223)
	at MyCode.lambda$retry$108(MyCode.java:267)
	at org.jooq.impl.ResultImpl.map(ResultImpl.java:2113)
       ...
```

However the same query in psql returns the data as expected:
```
db=> begin; update "production"."process_instance" set "retry" = false from "production"."sec_user" where "production"."process_instance"."retry" = true and "production"."process_instance"."checkpoint_id" is not null and "production"."sec_user"."id"="production"."process_instance"."rec_editor" returning "production"."process_instance"."rec_editor", "production"."sec_user"."user_name", "production"."process_instance"."checkpoint_id", "production"."process_instance"."checkpoint_data", "production"."process_instance"."rec_event_identifier", "production"."process_instance"."rec_updated_at", "production"."process_instance"."rec_command_source"; rollback;
BEGIN
 rec_editor | user_name | checkpoint_id | checkpoint_data | rec_event_identifier | rec_updated_at | rec_command_source 
------------+-----------+---------------+-----------------+----------------------+----------------+--------------------
(0 rows)

UPDATE 0
ROLLBACK
```

I have also tried retrieving the values using the generated fields with the same result, which makes sense as it looks like the result is missing the joined columns outright.

**Comment by lukaseder** [comment]
Thank you very much for reporting. Interesting, the issue here is that jOOQ doesn't map columns from outside of the `<R>` table in the `RETURNING` clause. This is only a problem when the `UPDATE .. FROM` clause is used.

It looks as though this will need to be fixed backwards incompatibly by changing the `<R>` type from `ProcessInstanceRecord` (after `update(PROCESS_INSTANCE)`) to `Record` (after `from(...)`).

I will investigate this further...

**Comment by lukaseder** [comment]
As I feared, the result is fetched correctly from the database, but then mapped incorrectly into this `<R>` type, which ignores all columns that are not from the `<R>` type itself.

**Comment by lukaseder** [comment]
I'm afraid this cannot be fixed thoroughly without breaking the current API. I'm thus postponing the fix until jOOQ 4.0.

As a workaround, however, you can prevent jOOQ from knowing the `<R>` type of the updated table by using plain SQL:

```java
db.update(table(name(PROCESS_INSTANCE.getName())))
  .set(...)
```

This will create an `Update<Record>` instead of an `Update<ProcessInstanceRecord>` statement, and it will prevent losing the returned columns from the `SEC_USER` table...

**Comment by BrentDouglas** [comment]
Thanks Lucas,

The workaround posted solved my issue, or rather let me collapse the select + update I changed to back into one update. We aren't actually generating the table based records so instead of `ProcessInstanceRecord` in this context `<R>` would be something like `Record8<Id,String,Id,...>`) but I suppose that the generated record is just a wrapper around the same class?

**Comment by lukaseder** [comment]
Aha, well, the effet is the same if you're using a generated record or a `Record8`. The workaround works because it works around this current implementation here:
https://github.com/jOOQ/jOOQ/blob/e8e383317f55f1a9f9c3823bb72fd3057a2dfe5d/jOOQ/src/main/java/org/jooq/impl/AbstractDMLQuery.java#L412

I suspect for a workaround, this is good enough, but it might break any time...

**Comment by amc6** [comment]
Is there any possibility that this fix could be implemented with a new method? In other words `returning()` would continue to return something with type `<R>` but a new method `returningRecord` could return type `Record`? It might even be useful to keep both around long term.

**Comment by lukaseder** [comment]
@amc6 That is certainly an option, even if not very beautiful

**Comment by lukaseder** [comment]
Thanks again for the suggestion, @amc6. I don't know why this hasn't occurred to me earlier, but adding new API is a perfectly sound solution for the time being. In jOOQ 4.0, the new API can be deprecated again, and the old API fixed.

The new API will be introduced with jOOQ 3.11 as of #7475

**Comment by lukaseder** [comment]
There are numerous backwards incompatible changes in this area due for jOOQ 3.15, which will lead to the improvement of the feature set, such that I'll reconsider implementing this for 3.15 as well:

- https://github.com/jOOQ/jOOQ/issues/3185
- https://github.com/jOOQ/jOOQ/issues/11190
- https://github.com/jOOQ/jOOQ/issues/11720

**Comment by lukaseder** [comment]
The existing feature set can be maintained in a more consistent way using `returning(T.A, T.B).coerce(T)` as `returning()` methods will now return a `ResultQuery` subtype (#3185), which supports `ResultQuery.coerce(Table)`

**Comment by lukaseder** [comment]
Having a go at this, this is quite the backwards incompatible change. Not all cases where the behaviour changes can be detected at compile time. For example:

```java
// Users deliberately chose to not use TRecord, or didn't generate TRecord
Record r =
ctx.insertInto(T)
   .columns(T.C)
   .values(1)
   .returning(T.D)
   .fetchOne();

// Used to return null, now throws an exception
r.getValue(T.C);
```

This change is inacceptable in a minor release. If it would have produced compilation errors, fine, but there's no guarantee these regressions can be detected at compile time. I guess we'll continue offering `returning()` and `returningResult()` for now.
