### ISSUE TITLE
Settings.backslashEscaping is not applied to LIKE .. ESCAPE clause

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5150]
The following query doesn't work:

```java
assertEquals(
    asList(2, 3, 4),
    create(new Settings().withBackslashEscaping(BackslashEscaping.ON)).select(TBook.ID)
            .from(T_BOOK)
            .where(TBook.TITLE.like("%a%", '\\'))
            .fetch(TBook.ID));
```

The error reported is:

```
org.jooq.exception.DataAccessException: SQL [select `test`.`t_book`.`ID` from `test`.`t_book` where `test`.`t_book`.`TITLE` like ? escape '\' -- SQL rendered with a free trial version of jOOQ 3.8.0]; You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''\' -- SQL rendered with a free trial version of jOOQ 3.8.0' at line 1
	at org.jooq.impl.Tools.translate(Tools.java:1892)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:651)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:363)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:312)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:393)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2748)
	at org.jooq.test.MySQLTest.testMySQLLikePredicateWithBackslashInEscapeClause(MySQLTest.java:1183)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''\' -- SQL rendered with a free trial version of jOOQ 3.8.0' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.Util.getInstance(Util.java:372)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1203)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:194)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:269)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:349)
	... 31 more
```

Backslash escaping is not applied when the backslash is used for the `LIKE .. ESCAPE` clause.

----
See also:
https://groups.google.com/forum/#!topic/jooq-user/dRMaMc6Jf1s

**Comment by lukaseder** [comment]
Fixed in commit https://github.com/jOOQ/jOOQ/commit/6c7d9cf98be07f53d3ea68b6231aefeaabcf8de4
