### ISSUE TITLE
NullPointerException when calling Query.getSQL() on an unattached Query

### ISSUE THREAD

**Issue by collinpeters** [jOOQ/jOOQ#5174]
```
		SelectJoinStep<Record> wat = with("a").as(select(
				val(1).as("x"),
				val("a").as("y")))
				.select()
				.from(table(name("a")));
		wat.getSQL();
```
The CTE above is taken from the docs. If I try to `getSQL` on it, it throws a NPE.

```
Caused by: java.lang.NullPointerException
	at org.jooq.impl.AbstractQuery.getSQL(AbstractQuery.java:513)
	at org.jooq.impl.AbstractDelegatingQuery.getSQL(AbstractDelegatingQuery.java:107)
	at mycode.BaseJooqMapperLookup.getCoreQuery(BaseJooqMapperLookup.java:129)
```

Perhaps this is a usage error but I can use `getSQL` on my various other steps.

**Comment by lukaseder** [comment]
Thank you very much for reporting this. Truly... "wat". I can reproduce this. It happens because your query is not "attached" to any `Configuration`. This would work around the issue:

```java
        SelectJoinStep<Record> wat = DSL.using(configuration).with("a").as(select(
                val(1).as("x"),
                val("a").as("y")))
                .select()
                .from(table(name("a")));
        wat.getSQL();
```

Or this:

```java
        SelectJoinStep<Record> wat = with("a").as(select(
                val(1).as("x"),
                val("a").as("y")))
                .select()
                .from(table(name("a")));
        DSL.using(configuration).render(wat);
```

In any case, it is better to generate the SQL statement in the context of a `Configuration`, as the generated SQL will depend on the `SQLDialect`.
