### ISSUE TITLE
NullPointerException when generating code in single-uppercase-named-database setup on MariaDB and MySQL

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5213]
It appears that we (or MariaDB) have a case-sensitivity issue related to schema name cases. This issue produces a `NullPointerException`, as we do find tables for an upper case schema name, but we cannot find the schema itself.

Exception:

```
2016-04-21T16:08:52,356 [main] ERROR     org.jooq.util.AbstractDatabase - Error while fetching tables
java.lang.NullPointerException
    at org.jooq.util.AbstractElementContainerDefinition.<init>(AbstractElementContainerDefinition.java:75) ~[jooq-meta-3.7.3.jar:?]
    at org.jooq.util.AbstractTableDefinition.<init>(AbstractTableDefinition.java:68) ~[jooq-meta-3.7.3.jar:?]
    at org.jooq.util.mysql.MySQLTableDefinition.<init>(MySQLTableDefinition.java:69) ~[jooq-meta-3.7.3.jar:?]
    at org.jooq.util.mysql.MySQLDatabase.getTables0(MySQLDatabase.java:247) ~[jooq-meta-3.7.3.jar:?]
    at org.jooq.util.AbstractDatabase.getTables(AbstractDatabase.java:730) [jooq-meta-3.7.3.jar:?]
    at org.jooq.util.JavaGenerator.generateSchema(JavaGenerator.java:3346) [jooq-codegen-3.7.3.jar:?]
    at org.jooq.util.JavaGenerator.generateSchema(JavaGenerator.java:3303) [jooq-codegen-3.7.3.jar:?]
    at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:301) [jooq-codegen-3.7.3.jar:?]
    at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:268) [jooq-codegen-3.7.3.jar:?]
    at org.jooq.util.GenerationTool.run(GenerationTool.java:434) [jooq-codegen-3.7.3.jar:?]
    at org.jooq.util.GenerationTool.generate(GenerationTool.java:180) [jooq-codegen-3.7.3.jar:?]
    at org.jooq.util.GenerationTool.main(GenerationTool.java:151) [jooq-codegen-3.7.3.jar:?]
    at com.proquest.pqd.canon.GenerateJooqFiles.main(GenerateJooqFiles.java:31) [test-classes/:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_31]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) [idea_rt.jar:?]
```

Further analysis is required

---

See also:
https://groups.google.com/forum/#!topic/jooq-user/FFaXsjjQ4Ck

**Comment by BDF** [comment]
Here are some more details.

The tables are being built using Liquibase.   All of the tables names are upper cased in the create table SQL.  The database itself is being created in the jdbc connection string like so:
jdbc:mysql://localhost:3306/MNEMONICS?createDatabaseIfNotExist=true

On the suspicion that that the case mixup was in Maria itself I tried the creating the database manually first before running the liquibase but didn't that didn't make any difference in behavior.

If you need any other details or need a sample in github just let me know.   I have sometime to help out if needed.

**Comment by lukaseder** [comment]
Thank you very much. That JDBC URL is certainly a good pointer. I'll play around with various upper/lower case configurations, trying to reproduce this. Perhaps it's rather easy to reproduce. Certainly, there's something jOOQ needs to do with respect to schema case sensitivity in MySQL and MariaDB. We've already implemented a fix for Oracle, which also has case-insensitive user names, unfortunately.

**Comment by lukaseder** [comment]
This won't fit into this week's version 3.8 anymore, but we'll look at it ASAP for the upcoming releases

**Comment by lukaseder** [comment]
I've tried to reproduce this issue both with MySQL and MariaDB (on Windows). I've also included playing around with case sensitivity parameters, such as:
https://mariadb.com/kb/en/mariadb/server-system-variables/#lower_case_table_names

Unfortunately, I couldn't reproduce this so far. Are you running on linux?

**Comment by BDF** [comment]
My local machine is Mac (Yosemite 10.10.5) with MySQL version 5.7.12.
The problem might be interplay between Mac case insensitive file names and
mysql.

I will create a sample project in github and send it your way.   That might
take me a few days.

Brian F.


p.s.
The way I'm currently avoiding the problem is by dropping input schema
element.



That resulted in the package name being included in the generation of the
java files which was a bit of a pain.

**Comment by lukaseder** [comment]
Oh, I see. I've read that Mac distributions of MySQL do yet use another setting for the lower_case_table_names flag. What's your setting (if you're overriding that)? This can be found in your my.ini file.

**Comment by BDF** [comment]
I'm currently running with the default installation.  Current task is to
rebuild from the bottom up using liquibase in my Mac/Mysql environment and
see if I get the same behavior.  When I built a sample database by hand
(i.e. not using liquibase)  I was not able to reproduce the error.

>show variables like '%case%';

Variable_name          Value
---------------------- -----
lower_case_file_system ON
lower_case_table_names 2

**Comment by BDF** [comment]
Here is the sequence that causes the NPE for me:

Initial state;  schema does not exist.
Create the database through JDBC via:
jdbc:mysql://localhost:3306/MNEMONICS?createDatabaseIfNotExist=true

This is done when running the liquibase command.  Then when I run jooq
with <inputSchema>MNEMONICS</inputSchema> I get the NPE.


Creating the database via (lower case schema name):
jdbc:mysql://localhost:3306/mnemonics?createDatabaseIfNotExist=true
with <inputSchema>MNEMONICS</inputSchema>  does not cause any NPEs but
doesn't generate any files either.
with <inputSchema>mnemonics</inputSchema> succeeds.

**Comment by brunsman** [comment]
Having the same issue here on a mac with MySQL. It has to do with the database name being in UPPERCASE. That will not work.

**Comment by lukaseder** [comment]
Oh man, what the hell o_O

Thank you very much, @brunsman for analysing this. I kept chasing other queries where the database name is reported correctly.

Will report an issue to MySQL and try to work around this problem.

**Comment by lukaseder** [comment]
Found a workaround (to be confirmed):

```sql
SELECT DISTINCT information_schema.COLUMNS.TABLE_SCHEMA FROM information_schema.COLUMNS 
WHERE concat(information_schema.COLUMNS.TABLE_SCHEMA, '') IN ('UPPERCASE')
```

The `CONCAT()` function seems to do the trick here

**Comment by lukaseder** [comment]
Another workaround:

```sql
SELECT DISTINCT information_schema.COLUMNS.TABLE_SCHEMA FROM information_schema.COLUMNS 
WHERE information_schema.COLUMNS.TABLE_SCHEMA IN ('UPPERCASE', 'dummy')
```

**Comment by lukaseder** [comment]
Here's the MySQL bug: https://bugs.mysql.com/bug.php?id=86022. Feel free to vote on it :)

**Comment by lukaseder** [comment]
Aha, and with the workarounds in mind, I can now reproduce the problem. I've never tried generating only one schema for MySQL as our integration tests have several schemata, so the workaround for you would be to add an explicit dummy schema to your code generator configuration to produce this `IN()` predicate with more than one value. Perhaps that helps?

**Comment by BDF** [comment]
Thank you Lukas,
Thank you Brunsman,

Its good to see active involvement and support.

Brian F.
