### ISSUE TITLE
Add more meaningful error handling when Maven code generator is not configured correctly

### ISSUE THREAD

**Issue by stickfigure** [jOOQ/jOOQ#5286]
When running this command to generate code:

mvn -X org.jooq.pro-java-6:jooq-codegen-maven:3.8.1:generate

I get an NPE from the plugin. Dropping the pro-java-6 works as advertised. Here's the exception:

```
[ERROR] Failed to execute goal org.jooq.pro-java-6:jooq-codegen-maven:3.8.1:generate (default-cli) on project hub: Error running jOOQ code generation tool: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jooq.pro-java-6:jooq-codegen-maven:3.8.1:generate (default-cli) on project hub: Error running jOOQ code generation tool
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error running jOOQ code generation tool
	at org.jooq.util.maven.Plugin.execute(Plugin.java:141)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.NullPointerException
	at org.jooq.util.maven.Plugin.execute(Plugin.java:124)
	... 22 more
```

**Comment by stickfigure** [comment]
Update - the problem was that the version of the plugin in the POM had to exactly match the version of the plugin specified on the command line. They both had to be the pro-java-6 version.

If there's a way of improving the error message, that would be great, otherwise feel free to close this issue. Thanks!

**Comment by lukaseder** [comment]
Hmm, interesting, thanks for reporting!

The `NullPointerException` is on this line here:

```java
    /**
     * The generator settings
     */
    @Parameter
    private org.jooq.util.jaxb.Generator generator;

[...]

            // NPE here:
            String dir = generator.getTarget().getDirectory();
```

So, your setup leads to plugin parameters not being initialised correctly. Instead of running into the `NullPointerException`, we could check if everything is initialised correctly, and if not, log a list of possible causes that we encounter. It would certainly be much more helpful than a NPE!
