### ISSUE TITLE
Add support for ALTER TABLE .. ALTER IF EXISTS

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5316]
Native support is available in at least:

- [x] BigQuery: https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#alter_column_drop_default_statement
- [x] ClickHouse: https://clickhouse.com/docs/sql-reference/statements/alter/column#modify-column
- [x] H2: https://www.h2database.com/html/commands.html#alter_table_alter_column
- [x] MariaDB: https://mariadb.com/kb/en/alter-table/

**Comment by lukaseder** [comment]
Do any dialects actually support this? Neither H2, PostgreSQL, SQL Server seem to do. We'd have to emulate it everywhere...

**Comment by katzyn** [comment]
Do you mean `ALTER TABLE [ IF EXISTS ] tableName ALTER COLUMN [ IF EXISTS ] columnName`?

H2 supports `IF EXISTS` clause for a table for a long time and 1.4.200 will have such clause for a column, it was implemented in the last month.

**Comment by lukaseder** [comment]
This is about `ALTER COLUMN [ IF EXISTS ] columnName`. Great to hear that the next version of H2 will support it! :)

**Comment by katzyn** [comment]
H2 1.4.200 was released (not yet visible in Maven Central).

**Comment by lukaseder** [comment]
Yay! Thanks for the pointer and for the release! Will re-priorities a few issues for consideration in jOOQ 3.13.

**Comment by theHacker** [comment]
Just stumbled upon this.

jOOQ version: 3.19.8
Database: H2 2.2.224

See https://www.h2database.com/html/commands.html#alter_table_alter_column for DDL syntax.

Log with stacktrace:
```
DDLDatabase Error        : Your SQL string could not be parsed or interpreted. This may have a variety of reasons, including:
- The jOOQ parser doesn't understand your SQL
- The jOOQ DDL simulation logic (translating to H2) cannot simulate your SQL

If you think this is a bug or a feature worth requesting, please report it here: https://jooq.org/bug

As a workaround, you can use the Settings.parseIgnoreComments syntax documented here:
https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/settings-parser/
Error while loading file: src/main/resources/schema.sql
An exception occurred while parsing script source : src/main/resources/schema.sql. Please report this error to https://jooq.org/bug
org.jooq.impl.ParserException: Unsupported query type: [167:45] ...

ALTER TABLE my_table ALTER COLUMN IF EXISTS [*]my_old_column RENAME TO my_new_column;

	at org.jooq.impl.DefaultParseContext.exception(ParserImpl.java:15149)
	at org.jooq.impl.DefaultParseContext.parseQuery(ParserImpl.java:1289)
	at org.jooq.impl.DefaultParseContext.lambda$parse$0(ParserImpl.java:908)
	at org.jooq.impl.DefaultParseContext.wrap(ParserImpl.java:15342)
	at org.jooq.impl.DefaultParseContext.parse(ParserImpl.java:896)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:774)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:769)
	at org.jooq.meta.extensions.ddl.DDLDatabase.load(DDLDatabase.java:179)
[...]
```

**Comment by lukaseder** [comment]
Thanks for the ping. Sure, I can look into this now.

There are only 4 dialects supported by jOOQ that have native support for this kind of syntax, at least according to their docs. I've updated the issue description.

Please note that renaming if exists is a separate issue:

- https://github.com/jOOQ/jOOQ/issues/15037
