### ISSUE TITLE
hao can i user `group_concat` in mysql

### ISSUE THREAD

**Issue by keeleys** [jOOQ/jOOQ#5471]
like this.how to achieve

```sql
select 
g.f_id as id,g.f_create_time as create_time,
group_concat(u.f_username separator ',') as usernames,
group_concat(r.f_name separator ',') as rolenames,
group_concat(n.f_name separator ',') as nodenames
from t_grant g 
left join t_grant_detail gd on g.f_id = gd.f_grant_id
left join t_node n on gd.f_node_id = n.f_id
left join t_role r on gd.f_role_id = r.f_id
left join t_member u on gd.f_member_id = u.f_id
and g.f_node_id = '123123'
group by g.f_id

```

**Comment by lukaseder** [comment]
Thanks a lot for your enquiry. As always with jOOQ, just static import everything from `DSL` first:

```java
import static org.jooq.impl.DSL.*;
import static com.example.generated.code.Tables.*;
```

And then just translate your SQL 1:1 to jOOQ:

```java
TGrant g = T_GRANT;
TGrantDetail gd = T_GRANT_DETAIL;
TNode n = T_NODE;
TRole r = T_ROLE;
TMember u = T_MEMBER;

using(configuration)
  .select(
    g.F_ID.as("id"),
    g.F_CREATE_TIME.as("create_time"),
    groupConcat(u.F_USERNAME, ",").as("usernames"),
    groupConcat(r.F_NAME, ",").as("rolenames"),
    groupConcat(n.F_NAME, ",").as("nodenames"))
  .from(g)
  .leftJoin(gd).on(g.F_ID.eq(gd.F_GRANT_ID))
  .leftJoin(n).on(gd. ...
```

And so on. Hope this helps,
Lukas

**Comment by keeleys** [comment]
@lukaseder  Thank you for your reply so quickly!
I have another question

Conversion is particularly troublesome，Good writing it?

```java
public class Grant {
    private String id;
    private String members;
    private String rolenames;
    private String nodenames;
    private Long createTime;
     .....omission .get...set....
}
```

```java
public List<Grant> find(Optional<String> nodeId) {
        SelectWhereStep s =grantCommonDao.execute(x -> {
            return x.select(GRANT.ID.as("id"),
                    GRANT.CREATE_TIME.as("createTime"),
                    groupConcat( MEMBER.USERNAME).as("usernames"),
                    groupConcat(ROLE.NAME).as("rolenames"),
                    groupConcat( NODE.NAME).as("nodenames")
                ).from(GRANT).leftJoin(GRANT_DETAIL).on(GRANT.ID.eq(GRANT_DETAIL.GRANT_ID))
                    .leftJoin(NODE).on(GRANT_DETAIL.NODE_ID.eq(NODE.ID))
                    .leftJoin(ROLE).on(GRANT_DETAIL.ROLE_ID.eq(ROLE.ID))
                    .leftJoin(MEMBER).on(GRANT_DETAIL.MEMBER_ID.eq(MEMBER.ID)
                );
        });
        nodeId.ifPresent(x -> s.where(GRANT.NODE_ID.in(x.split(","))));
        s.groupBy(GRANT.ID);
        return s.fetch(new RecordMapper() {
            @Override
            public Object map(Record record) {
                Grant g = new Grant();
                g.setId(record.getValue(0,String.class));
                g.setCreateTime(record.getValue(1,Long.class));
                g.setMembers(record.getValue(2, String.class));
                g.setRolenames(record.getValue(3, String.class));
                g.setNodenames(record.getValue(4, String.class));
                return g;
            }
        });
    }
```

**Comment by keeleys** [comment]
I'm trying to get it automatically maps the time,like this.
```java
nodeId.ifPresent(x -> s.where(GRANT.NODE_ID.in(x.split(","))));
        s.groupBy(GRANT.ID);
//        return s.fetch(new RecordMapper() {
//            @Override
//            public Object map(Record record) {
//                Grant g = new Grant();
//                g.setId(record.getValue(0,String.class));
//                g.setCreateTime(record.getValue(1,Long.class));
//                g.setMembers(record.getValue(2, String.class));
//                g.setRolenames(record.getValue(3, String.class));
//                g.setNodenames(record.getValue(4, String.class));
//                return g;
//            }
//        });
        return s.fetchInto(Grant.class);
```

the throw is .
```
java.lang.NoSuchFieldException: MAPPER
	at java.lang.Class.getField(Class.java:1703)
	at org.jooq.impl.DefaultRecordMapperProvider.provide(DefaultRecordMapperProvider.java)
	at org.jooq.impl.ResultImpl.into(ResultImpl.java:2074)
	at org.jooq.impl.AbstractResultQuery.fetchInto(AbstractResultQuery.java:1243)
	at org.jooq.impl.SelectImpl.fetchInto(SelectImpl.java:3452)
	at com.zxy.demo.project.service.support.grant.GrantServiceSupport.find(GrantServiceSupport.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	```

**Comment by lukaseder** [comment]
Hmm, interesting. We're not looking up any `MAPPER` field via reflection in `org.jooq.impl.DefaultRecordMapper#provide()`. Given that this line in the stack trace does not mention any line number (unlike the others), I suspect that this might not be the original implementation in jOOQ? Did you patch that class, maybe?

**Comment by keeleys** [comment]
Thank you for your answer, if I fetchinto no problem writing to the class, I debugging to see if there are other reasons. I have patch class in some places.

**Comment by lukaseder** [comment]
OK, thank you very much for the feedback.
