### ISSUE TITLE
INSERT RETURNING with Sequence not working in Oracle 12c, ojdbc7

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5543]
As reported by @lasjen on a different issue (https://github.com/jOOQ/jOOQ/issues/2374#issuecomment-247355371):

> Have used codegen, and try this (which I thought should work against Oracle):
> 
> ```java
    DSLContext create = DSL.using(DatabaseUtil.getConnection(), SQLDialect.ORACLE);
    Record rec = create.insertInto(AUTHOR, AUTHOR.ID, AUTHOR.FIRST_NAME, AUTHOR.LAST_NAME)
                     .values(create.nextval(AUTHOR_SEQ), first_name, last_name).returning(AUTHOR.ID).fetchOne();
```
>
> Inserts works ok, but returning always returns NULL. Am I doing something wrong?
> Note! Using trial edition 3.8.4.

Still investigating and trying to reproduce. Perhaps related to the specific ojdbc version.

**Comment by lukaseder** [comment]
@lasjen: Just to be sure. Are you using the author table from the manual?
http://www.jooq.org/doc/latest/manual/getting-started/sample-database

**Comment by lukaseder** [comment]
Interesting. I ran the code with ojdbc6: works. With ojdbc7: NPE:

```
java.lang.NullPointerException
	at oracle.jdbc.driver.AutoKeyInfo.initMetaDataColumnIndexes(AutoKeyInfo.java:423)
	at oracle.jdbc.driver.AutoKeyInfo.initMetaData(AutoKeyInfo.java:396)
	at oracle.jdbc.driver.OracleReturnResultSet.getMetaData(OracleReturnResultSet.java:77)
	at org.jooq.impl.CursorImpl$CursorResultSet.getMetaData(CursorImpl.java:448)
	at org.jooq.impl.CursorImpl.initLongIndexes(CursorImpl.java:162)
	at org.jooq.impl.CursorImpl.<init>(CursorImpl.java:142)
	at org.jooq.impl.CursorImpl.<init>(CursorImpl.java:128)
```

Looks like a JDBC driver bug. Will investigate further

**Comment by lukaseder** [comment]
That was quick. Here's the bug (17082699):
https://community.oracle.com/thread/2558937

The functionality in `CursorImpl.initLongIndexes()` isn't all that important, though, so I guess we can skip it to work around this JDBC driver bug. I have created an issue for this: https://github.com/jOOQ/jOOQ/issues/5547

Once I worked around this problem, I'll continue investigating your reported issue, which may or may not be related (currently running ojdbc7 against Oracle 11gR2 XE)

**Comment by lukaseder** [comment]
OK, now also tried with Oracle 12c. Same NPE as before. But I couldn't reproduce the case where this statement returned `NULL`... @lasjen Did you mean throwing a NPE when you said "always returns NULL"?

**Comment by lukaseder** [comment]
I'm not sure if there's anything left to be done here. It seems that some comments have been deleted in this issue...
