### ISSUE TITLE
Dynamic type errors when using Postgres aggregate function with anyelement type

### ISSUE THREAD

**Issue by michaelsproul** [jOOQ/jOOQ#5591]
I'm trying to use a custom aggregate function with Postgres, which takes arguments of type `anyelement`. The function I want is a `last` aggregator to grab the last value of a column in each group. This is the definition I'm using:

```sql
-- Create a function that always returns the last non-NULL item
CREATE OR REPLACE FUNCTION public.last_agg ( anyelement, anyelement )
RETURNS anyelement LANGUAGE SQL IMMUTABLE STRICT AS $$
        SELECT $2;
$$;

-- And then wrap an aggregate around it
CREATE AGGREGATE public.LAST (
        sfunc    = public.last_agg,
        basetype = anyelement,
        stype    = anyelement
);
```

(code from [here](https://wiki.postgresql.org/wiki/First/last_(aggregate)))

I can successfully generate jOOQ code for this aggregate function, but when I use it, it crashes.

This is the query:

```java
List<Record2<Long, Object>> l = dsl.select(MESSAGE.CONVERSATION_ID, last(MESSAGE.END_STATE))
            .from(MESSAGE)
            .groupBy(MESSAGE.CONVERSATION_ID)
            .fetch().stream().collect(toList());
```

This is the exception thrown:

```
[main] WARN org.jooq.exception.SQLDialectNotSupportedException - Not supported by dialect : Type class org.jooq.impl.TableFieldImpl is not supported in dialect POSTGRES
Exception in thread "main" org.jooq.exception.SQLDialectNotSupportedException: Type class org.jooq.impl.TableFieldImpl is not supported in dialect POSTGRES
	at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:803)
	at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:747)
	at org.jooq.impl.DefaultBinding.toSQLCast(DefaultBinding.java:368)
	at org.jooq.impl.DefaultBinding.sql(DefaultBinding.java:268)
	at org.jooq.impl.Val.accept(Val.java:83)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:396)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:394)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:159)
	at org.jooq.impl.QueryPartList.accept(QueryPartList.java:104)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:396)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:394)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:159)
	at org.jooq.impl.Function.toSQLArguments(Function.java:455)
	at org.jooq.impl.Function.accept(Function.java:225)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:396)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:356)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:159)
	at org.jooq.impl.QueryPartList.accept(QueryPartList.java:104)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:396)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:394)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:159)
	at org.jooq.impl.SelectQueryImpl.toSQLReference0(SelectQueryImpl.java:1021)
	at org.jooq.impl.SelectQueryImpl.toSQLReference0(SelectQueryImpl.java:864)
	at org.jooq.impl.SelectQueryImpl.toSQLReferenceLimitDefault(SelectQueryImpl.java:666)
	at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:505)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:396)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:394)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:159)
	at org.jooq.impl.AbstractQuery.getSQL0(AbstractQuery.java:481)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:307)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:312)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2705)
	at rungopher.db_access.DbMessage.getConversationStatesBroken(DbMessage.java:130)
	at rungopher.db_access.DbMessage.main(DbMessage.java:156)
```

If I change the argument type in the SQL to `text`, it works for this one specific use-case but not in general.

**Comment by michaelsproul** [comment]
The result is the same with the [first_last_agg](http://www.pgxn.org/dist/first_last_agg/) Postgres extension.

**Comment by michaelsproul** [comment]
Another independent yet related issue is the lack of support for `ORDER BY` clauses within aggregate functions, as in:

```
SELECT LAST(col1 ORDER BY col2) FROM table GROUP BY col3;
```

**Comment by lukaseder** [comment]
Thank you very much for reporting. I'll look into this ASAP

**Comment by lukaseder** [comment]
Regarding that `ORDER BY` feature request, I've created a separate issue for this: https://github.com/jOOQ/jOOQ/issues/5604

**Comment by lukaseder** [comment]
I think this might be related to https://github.com/jOOQ/jOOQ/issues/5479 (lack of support for PostgreSQL's `any` pseudo-generic types). Can you confirm this should work if you overload your aggregate function for each individual type?

**Comment by michaelsproul** [comment]
Yes, if you create an aggregate for each type, and ignore the unspecified ordering problem, then it works

**Comment by michaelsproul** [comment]
Our workaround at the moment is to use a view and perform queries on that instead

**Comment by lukaseder** [comment]
> Our workaround at the moment is to use a view and perform queries on that instead

That always works, of course.

Thanks for the feedback. I hope we can implement this (and #5479) for some future release. Getting a thorough hold of the `any` semantics doesn't seem simple, though. The `any` types need to be mapped to some Java generics. I'm not fully sure yet that this can be done properly.
