### ISSUE TITLE
Error on code generation when schema name is a Windows reserved name like CON, AUX

### ISSUE THREAD

**Issue by ypconstante** [jOOQ/jOOQ#5596]
When the schema name is a Windows reserved name, like con and aux, the code generation throws an exception when it tries to create the schema file.

**Comment by lukaseder** [comment]
Thank you very much for reporting. I can reproduce this. Created the following tables:

```sql
CREATE SCHEMA IF NOT EXISTS CON;
CREATE SCHEMA IF NOT EXISTS AUX;
CREATE TABLE CON.AUX (CON INT);
CREATE TABLE AUX.CON (AUX INT);
```

... which results in the following exception:


```
Caused by: org.jooq.util.GeneratorException: Error generating code for schema CON
        at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:341)
        at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:263)
        ... 25 more
Caused by: org.jooq.util.GeneratorException: Error writing C:\Users\lukas\workspace\jOOQ\jOOQ-test\.\src\test\java\org\jooq\test\h2\generatedclasses\con\Con.java
        at org.jooq.util.GeneratorWriter.close(GeneratorWriter.java:288)
        at org.jooq.util.JavaGenerator.closeJavaWriter(JavaGenerator.java:5286)
        at org.jooq.util.JavaGenerator.generateSchema(JavaGenerator.java:3648)
        at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:371)
        at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:336)
        ... 26 more
Caused by: java.io.FileNotFoundException: C:\Users\lukas\workspace\jOOQ\jOOQ-test\.\src\test\java\org\jooq\test\h2\generatedclasses\con\Con.java (Das System kann den angegebenen Pfad nicht finden)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at org.jooq.util.GeneratorWriter.close(GeneratorWriter.java:277)
        ... 30 more
```

Interestingly, I can create such files using the git bash shell, but I guess if some API goes through windows native APIs, then these names are forbidden.

This is explained in some blog posts, such as this one here:
https://blog.onetechnical.com/2006/11/16/forbidden-file-and-folder-names-on-windows

Ideally, we'll just escape all of the following forbidden names:

- CON
- PRN
- AUX
- CLOCK$ (NT and older)
- NUL
- COM1
- COM2
- COM3
- COM4
- COM5
- COM6
- COM7
- COM8
- COM9
- LPT1
- LPT2
- LPT3
- LPT4
- LPT5
- LPT6
- LPT7
- LPT8
- LPT9

**Comment by brahtala-leovegas** [comment]
Hi,
If a package name contains the word `aux` a dir is generated with the name `aux_`. Is there any way the dir name can reflect the package name?
I am aware that this is a problem for Windows.
But if the code designers deiced on the word `aux` then they most probably are not Windows compliant.

**Comment by lukaseder** [comment]
Thanks for your message, @brahtala-leovegas. You can implement your own generator strategy to override any generated object name in jOOQ:

- Programmatic: https://www.jooq.org/doc/latest/manual/code-generation/codegen-generatorstrategy/
- Configurative: https://www.jooq.org/doc/latest/manual/code-generation/codegen-matcherstrategy/

I hope this helps.
