### ISSUE TITLE
NullPointerException on fetchLazy().stream() / MockStatement.execute() returns false on empty results

### ISSUE THREAD

**Issue by lanwen** [jOOQ/jOOQ#5617]
JOOQ v3.8.4
PG database (9.5)

In some cases i catch NPE:
```java
java.lang.NullPointerException: null
	at org.jooq.impl.AbstractResultQuery.stream(AbstractResultQuery.java:345)
	at org.jooq.impl.SelectImpl.stream(SelectImpl.java:2726)
```

Can't imagine when it fails.

My code looks like:
```java
try (Stream<Record<Long> stream = someDsl
                .select(
                        MESSAGES.ID
                )
                .from(MESSAGES)
                .stream()) {

                 stream
                    .map(record -> record.into(MessageMeta.class))
                    .forEach(msg -> {});
         }
```

**Comment by lukaseder** [comment]
Thank you very much for your report. May I ask you to provide a full stack trace, please? There will be a "caused by" message much further down, I suspect, which contains the interesting information.

**Comment by lanwen** [comment]
Doesn't think my stacktrace can give any info :(
I've catch it in production, so can't reproduce it manually in real env. 

```java
java.lang.NullPointerException: null
	at org.jooq.impl.AbstractResultQuery.stream(AbstractResultQuery.java:345)
	at org.jooq.impl.SelectImpl.stream(SelectImpl.java:2726)
	at my.package.service.pg.MailPgService.messages(MailPgService.java:95)
	at sun.reflect.GeneratedMethodAccessor122.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.camel.component.bean.MethodInfo.invoke(MethodInfo.java:435)
	at org.apache.camel.component.bean.MethodInfo$1.doProceed(MethodInfo.java:286)
	at org.apache.camel.component.bean.MethodInfo$1.proceed(MethodInfo.java:259)
	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:178)
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:542)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:120)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:120)
	at org.apache.camel.processor.Pipeline.access$100(Pipeline.java:44)
	at org.apache.camel.processor.Pipeline$1.done(Pipeline.java:138)
	at org.apache.camel.processor.ThreadsProcessor$ProcessCall.run(ThreadsProcessor.java:88)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

same exception can be reproduced with this snippet as datasource:

```java
new DataSource() {
                @Override
                public Connection getConnection() throws SQLException {
                    return new MockConnection(ctx -> {
                        DSLContext dsl = DSL.using(SQLDialect.POSTGRES_9_5);
                
                        return new MockResult[]{
//                               no any
                        };
                    });
                }
            };
```

**Comment by lukaseder** [comment]
Thanks for the hint. I can now reproduce the issue, very subtle. Will proceed with a fix ASAP

**Comment by lukaseder** [comment]
N.B: Strictly speaking, your `MockConnection` usage is not correct. You should always return a non-empty array for result queries. But that shouldn't result in a `NPE` of course.
