### ISSUE TITLE
Oracle AbstractDatabase - SQLPerformanceWarning

### ISSUE THREAD

**Issue by archenroot** [jOOQ/jOOQ#5686]
While using programmatically configured generator I try to generate all PUBLIC schema
 
I am facing:

```sql
(
  select 
    "alias_70968841"."OWNER", 
    "alias_70968841"."TABLE_NAME", 
    "alias_70968841"."COMMENTS", 
    "alias_70968841"."table_valued_function", 
    "alias_70968841"."OBJECT_ID", 
    "alias_70968841"."OVERLOAD"
  from (
    (
      select 
        "SYS"."ALL_TAB_COMMENTS"."OWNER", 
        "SYS"."ALL_TAB_COMMENTS"."TABLE_NAME", 
        "SYS"."ALL_TAB_COMMENTS"."COMMENTS", 
        0 "table_valued_function", 
        0 "OBJECT_ID", 
        '' "OVERLOAD"
      from "SYS"."ALL_TAB_COMMENTS"
      where (
        upper("SYS"."ALL_TAB_COMMENTS"."OWNER") in (
**LARGE CONTENT HERE**
        )
        or upper("SYS"."ALL_TAB_COMMENTS"."OWNER") in (
**LARGE CONTENT HERE**         
        )
        or upper("SYS"."ALL_TAB_COMMENTS"."OWNER") in (
**LARGE CONTENT HERE**
        )
        or upper("SYS"."ALL_TAB_COMMENTS"."OWNER") in (
**LARGE SAME CONTENT HERE**        )
        or upper("SYS"."ALL_TAB_COMMENTS"."OWNER") in (
**LARGE SAME CONTENT HERE**        )
        or upper("SYS"."ALL_TAB_COMMENTS"."OWNER") in (
**LARGE SAME CONTENT HERE**        )
        or upper("SYS"."ALL_TAB_COMMENTS"."OWNER") in (
**LARGE SAME CONTENT HERE**        )
        or upper("SYS"."ALL_TAB_COMMENTS"."OWNER") in (

--This block is repeated dozen of times until following:
  )
)

order by 
  "SYS"."ALL_SEQUENCES"."SEQUENCE_OWNER" asc, 
  "SYS"."ALL_SEQUENCES"."SEQUENCE_NAME" asc
```

```
org.jooq.util.AbstractDatabase$1$SQLPerformanceWarning
	at org.jooq.util.AbstractDatabase$1.executeEnd(AbstractDatabase.java:251)
	at org.jooq.impl.ExecuteListeners.executeEnd(ExecuteListeners.java:161)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:273)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:348)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:312)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2705)
	at org.jooq.util.oracle.OracleDatabase.getSequences0(OracleDatabase.java:298)
	at org.jooq.util.AbstractDatabase.getSequences(AbstractDatabase.java:894)
	at org.jooq.util.JavaGenerator.generateSchema(JavaGenerator.java:3698)
	at org.jooq.util.JavaGenerator.generateSchema(JavaGenerator.java:3622)
	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:372)
	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:335)
	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:290)
	at org.jooq.util.GenerationTool.run(GenerationTool.java:529)
	at org.jooq.util.GenerationTool.generate(GenerationTool.java:198)
	at org.archenroot.microservices.robotron.meta_info_processor.ConfigGenerator.generate(ConfigGenerator.java:34)
	at org.archenroot.microservices.robotron.meta_info_processor.Main.main(Main.java:9)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

Nov 24, 2016 2:55:45 PM org.jooq.tools.JooqLogger info
INFO: Sequences fetched        : 9366 (0 included, 9366 excluded)
```

**Comment by lukaseder** [comment]
Thank you very much for reporting. This exception is logged to indicate a possible code generation performance flaw with long-running queries. In this particular case, it looks as though the `IN` list passed to the `OWNER` column predicate is prohibitively large.

How many schemas do you have in your database? Do you really need to include all of those schemas for code generation?

I guess jOOQ should check how many schemas there are in total, and how many schemas the user requested for code generation, and if the ratio is more than 50% (or even more than maybe 20%), we just fetch all the schemas from the database and filter them in memory...

**Comment by archenroot** [comment]
Actually over 14000 :-) on Oracle Exadata

**Comment by archenroot** [comment]
I would like to limit this, and was adding .withIncludes("PUBLIC.*") to the generator Configuration

**Comment by lukaseder** [comment]
Oh wow, 14000. Well, at least the query works :)

The includes/excludes settings will include/exclude objects after fetching them into memory, by filtering their names using Java regular expressions. So that setting doesn't influence the query.

The correct setting is `<schemata>` as documented here in the manual:
http://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced

```xml
  <schemata>
    <schema>
      <inputSchema>...</inputSchema>
      <outputSchema>...</outputSchema>
      <outputSchemaToDefault>...</outputSchemaToDefault>
    </schema>
    [ <schema>...</schema> ... ]
  </schemata>
```

Or, with programmatic configuration

```java
.withSchemata(
  new Schema().withInputSchema("PUBLIC"),
  new Schema().withInputSchema("...")
)
```

**Comment by lukaseder** [comment]
Reviewing this issue: I'm not sure if we can drastically improve this query. The way forward is to make sure the schema containing so many objects is not even considered by the code generator, as documented in my previous comment.
