### ISSUE TITLE
JOOQ Store procedure call Exception Closed Statement

### ISSUE THREAD

**Issue by srilakshmibodireddy** [jOOQ/jOOQ#5719]
Hi,

We are using JOOQ 3.4.5 and we are occasionally getting an exception while invoking stored procedure. We are unable to figure the root cause for this intermittent behaviour. Please see the stack trace below.

Please note the exception is thrown after waiting for response for about 2mins. Any help is really appreciated as this issue is major roadblock in UAT.

```
org.jooq.exception.DataAccessException: SQL [{ call "SP_UPLD_DATA"(?, ?, ?, ?) }]; Closed Statement
	at org.jooq.impl.Tools.translate(Tools.java:1941) ~[jooq-3.8.4.jar:na]
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:659) ~[jooq-3.8.4.jar:na]
	at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:460) [jooq-3.8.4.jar:na]
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:298) [jooq-3.8.4.jar:na]
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:275) [jooq-3.8.4.jar:na]
	at com.nc.bfms.datasource.services.quartz.UploadBSSOSSDataService.invokeSPUpldBssOssData(UploadBSSOSSDataService.java:27) [nc-bfms-datasource-services-0.0.1-20161209.063108-491.jar:na]
	at com.nc.bfms.datasource.job.intf.BFMSBatch.invokeSQLLoaderGenerateLogFile(BFMSBatch.java:163) [classes/:na]
	at com.nc.bfms.datasource.job.intf.BSSOSSOrderAndServiceJob.execute(BSSOSSOrderAndServiceJob.java:146) [classes/:na]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [quartz-2.1.5.jar:na]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557) [quartz-2.1.5.jar:na]
Caused by: java.sql.SQLException: Closed Statement
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112) ~[ojdbc14-10.2.0.3.jar:Oracle JDBC Driver version - "10.2.0.3.0"]
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146) ~[ojdbc14-10.2.0.3.jar:Oracle JDBC Driver version - "10.2.0.3.0"]
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:208) ~[ojdbc14-10.2.0.3.jar:Oracle JDBC Driver version - "10.2.0.3.0"]
	at oracle.jdbc.driver.OracleCallableStatement.getString(OracleCallableStatement.java:390) ~[ojdbc14-10.2.0.3.jar:Oracle JDBC Driver version - "10.2.0.3.0"]
	at org.jooq.tools.jdbc.DefaultCallableStatement.getString(DefaultCallableStatement.java:100) ~[jooq-3.8.4.jar:na]
	at org.jooq.impl.DefaultBinding.get(DefaultBinding.java:1589) ~[jooq-3.8.4.jar:na]
	at org.jooq.impl.AbstractRoutine.fetchOutParameter(AbstractRoutine.java:783) [jooq-3.8.4.jar:na]
	at org.jooq.impl.AbstractRoutine.fetchOutParameters(AbstractRoutine.java:772) [jooq-3.8.4.jar:na]
	at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:444) [jooq-3.8.4.jar:na]
	... 7 common frames omitted
```

**Comment by lukaseder** [comment]
Thank you very much for your enquiry. Note: Your stack trace indicates that you're using jOOQ 3.8.4, not 3.4.5.

From the error message, I'm suspecting that some other thread (possibly the connection pool itself, or by quartz) is closing the connection that was given to jOOQ while jOOQ fetches out parameters. The issue might also be related to timeouts.

I'd suggest looking for the source of the problem in those `com.nc.bfms.datasource` packages. Let me know if I can be of any further assistance.

**Comment by srilakshmibodireddy** [comment]
Thank you very much Lukas for your reply. We are looking at many other possibilities. One more thing we noticed is jooq calls to stored procedures are taking longer time. In this case the sp execution time was around 7mins. Even other simple stored procedure calls in our application takes about 2-3mins. If we execute the same sp in oracle directly they are not taking more than 1min.

Has this been noticed in other jooq implementations ?

**Comment by lukaseder** [comment]
jOOQ doesn't add much of an overhead over JDBC, so I'm guessing that if there's any overhead at all, it might be caused by the time it takes to serialise / deserialise in and out parameters. Do you send any heavy SQL collections (`TABLE` or `VARRAY` or `REF CURSOR` types) over the wire?

**Comment by srilakshmibodireddy** [comment]
We are not sending any heavy collections, input parameters are just an id and string
ex:  { call "SP_UPLD_BSS_OSS_DATA"(189, 'BFMS SYSTEM USER', ?, ?) }

But this stored procedure internally processes around ~2-5 lakhs records (like by doing select, process rules, update, delete)


> 2016-12-20_13:13:40.665 [DefaultQuartzScheduler_Worker-3] DEBUG org.jooq.tools.LoggerListener - Calling routine          : { call "SP_UPLD_BSS_OSS_DATA"(?, ?, ?, ?) }
2016-12-20_13:13:40.665 [DefaultQuartzScheduler_Worker-3] DEBUG org.jooq.tools.LoggerListener - -> with bind values      : { call "SP_UPLD_BSS_OSS_DATA"(189, 'BFMS SYSTEM USER', ?, ?) }
2016-12-20_13:15:04.799 [DefaultQuartzScheduler_Worker-3] DEBUG org.jooq.tools.StopWatch - Query executed           : Total: 01:24
2016-12-20_13:15:04.799 [DefaultQuartzScheduler_Worker-3] DEBUG org.jooq.tools.StopWatch - Fetching out values      : Total: 01:24, +0.693ms
2016-12-20_13:15:05.465 [DefaultQuartzScheduler_Worker-3] DEBUG org.jooq.tools.LoggerListener - org.jooq.exception.DataAccessException: SQL [{ call "SP_UPLD_BSS_OSS_DATA"(?, ?, ?, ?) }]; Closed Statement

And then the exception followed.

**Comment by lukaseder** [comment]
OK, interesting. So, when you compare a JDBC/jOOQ call with a call from within the database, are the two calls really comparable? E.g.:

- Are you processing the same amount of records?
- Do you have the same transaction semantics?

It's hard to say from what I've seen thus far, but I'm pretty sure that the exception is probably due to a timeout.

One possible workaround to these problems would be to move the scheduling logic into the database by using Oracle AQ and `DBMS_SCHEDULER` instead. If you don't mix Java logic with the job logic, then that is probably a more interesting solution. You could also still use the Quartz scheduler from your client, but instead of running a blocking process call, just send an AQ message into the database that starts the job inside of the database in a database process, without the client blocking on it...

**Comment by lukaseder** [comment]
@srilakshmibodireddy : Is there still anything we can do to help you with respect to this issue?

**Comment by srilakshmibodireddy** [comment]
Thank you for the Enquiry. We solved the problem by adding a property in tomcat server org.apache.tomcat.jdbc.pool.interceptor.ResetAbandonedTimer . It will not block the application flow by closed connection exception but show a warning that the execution time is more and will reset.

**Comment by lukaseder** [comment]
Thank you very much for your feedback. I'm glad you've found a solution to this problem.
