### ISSUE TITLE
Insert using DAO API fails on MySQL

### ISSUE THREAD

**Issue by stayfool** [jOOQ/jOOQ#5730]
ENV: mysql, springboot, no transaction, all pojo and daos are generared by code-gen-maven
my code:
```
@Test
	public void contextLoads() {

        System.out.println(userDao.count());

        User u = new User();
        u.setUserName("jooq");
        u.setPassword("jooa");
        u.setRegWay("jooq");

        userDao.insert(u);
        System.out.println(userDao.count());
    }
```
error code:
```
org.jooq.exception.NoDataFoundException: Exactly one row expected for refresh. Record does not exist in database.

	at org.jooq.impl.UpdatableRecordImpl.refresh(UpdatableRecordImpl.java:342)
	at org.jooq.impl.TableRecordImpl.getReturningIfNeeded(TableRecordImpl.java:218)
	at org.jooq.impl.TableRecordImpl.storeInsert0(TableRecordImpl.java:194)
	at org.jooq.impl.TableRecordImpl$1.operate(TableRecordImpl.java:155)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:128)
	at org.jooq.impl.TableRecordImpl.storeInsert(TableRecordImpl.java:151)
	at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:139)
	at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:134)
	at org.jooq.impl.DAOImpl.insert(DAOImpl.java:165)
	at org.jooq.impl.DAOImpl.insert(DAOImpl.java:146)
	at org.jooq.impl.DAOImpl$$FastClassBySpringCGLIB$$8c936301.invoke(<generated>)
```

**Comment by stayfool** [comment]
I try in transaction, it's ok

**Comment by lukaseder** [comment]
Thank you very much for your report. Could you please also show the `USER` table's DDL to be able to reproduce this? Also, if you could turn on debug logging to show what SQL queries jOOQ sends to the database, that would be very helpful.

**Comment by stayfool** [comment]
@lukaseder  log:
```
2016-12-23 19:03:26.341 DEBUG 3292 --- [           main] org.jooq.tools.LoggerListener            : Executing query          : insert into `xy`.`user` (`user_name`, `email`, `tel`, `reg_ip`, `last_login_ip`, `reg_way`, `password`, `extend_data`) values (?, ?, ?, ?, ?, ?, ?, ?)
2016-12-23 19:03:26.342 DEBUG 3292 --- [           main] org.jooq.tools.LoggerListener            : -> with bind values      : insert into `xy`.`user` (`user_name`, `email`, `tel`, `reg_ip`, `last_login_ip`, `reg_way`, `password`, `extend_data`) values ('jooq11', null, null, null, null, 'jooq11', 'jooa11', null)
2016-12-23 19:03:26.342 DEBUG 3292 --- [           main] o.s.jdbc.datasource.DataSourceUtils      : Fetching JDBC Connection from DataSource
2016-12-23 19:03:26.346 DEBUG 3292 --- [           main] org.jooq.tools.LoggerListener            : Affected row(s)          : 1
2016-12-23 19:03:26.346 DEBUG 3292 --- [           main] org.jooq.tools.StopWatch                 : Query executed           : Total: 8.372ms
2016-12-23 19:03:26.350 DEBUG 3292 --- [           main] o.s.jdbc.datasource.DataSourceUtils      : Returning JDBC Connection to DataSource
2016-12-23 19:03:26.400 DEBUG 3292 --- [           main] org.jooq.tools.StopWatch                 : Finishing                : Total: 62.655ms, +54.283ms
2016-12-23 19:03:26.413 DEBUG 3292 --- [           main] org.jooq.tools.LoggerListener            : Executing query          : select `xy`.`user`.`user_id` from `xy`.`user` where `xy`.`user`.`user_id` = ?
2016-12-23 19:03:26.413 DEBUG 3292 --- [           main] org.jooq.tools.LoggerListener            : -> with bind values      : select `xy`.`user`.`user_id` from `xy`.`user` where `xy`.`user`.`user_id` = 38
2016-12-23 19:03:26.413 DEBUG 3292 --- [           main] o.s.jdbc.datasource.DataSourceUtils      : Fetching JDBC Connection from DataSource
2016-12-23 19:03:26.414 DEBUG 3292 --- [           main] org.jooq.tools.StopWatch                 : Query executed           : Total: 1.742ms
2016-12-23 19:03:26.415 DEBUG 3292 --- [           main] o.s.jdbc.datasource.DataSourceUtils      : Returning JDBC Connection to DataSource
2016-12-23 19:03:26.415 DEBUG 3292 --- [           main] org.jooq.tools.LoggerListener            : Fetched result           : +-------+
2016-12-23 19:03:26.415 DEBUG 3292 --- [           main] org.jooq.tools.LoggerListener            :                          : |user_id|
2016-12-23 19:03:26.415 DEBUG 3292 --- [           main] org.jooq.tools.LoggerListener            :                          : +-------+
2016-12-23 19:03:26.415 DEBUG 3292 --- [           main] org.jooq.tools.StopWatch                 : Finishing                : Total: 2.857ms, +1.115ms
```
DDL:
```
CREATE TABLE `user` (
  `user_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `type` smallint(6) NOT NULL DEFAULT '-1' COMMENT '1:个人，2：企业',
  `user_name` varchar(64) NOT NULL,
  `email` varchar(64) DEFAULT NULL,
  `tel` varchar(16) DEFAULT NULL,
  `reg_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `reg_ip` varchar(64) DEFAULT NULL,
  `last_login_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `last_login_ip` varchar(64) DEFAULT NULL,
  `reg_from` smallint(6) NOT NULL DEFAULT '-1' COMMENT '1:来自门户网站',
  `reg_way` varchar(8) NOT NULL COMMENT '填写tel、email等字符串',
  `password` varchar(32) DEFAULT NULL,
  `extend_data` json DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  KEY `user_name` (`user_name`)
) ENGINE=InnoDB AUTO_INCREMENT=39 DEFAULT CHARSET=utf8
```

**Comment by lukaseder** [comment]
Interesting, so is there any sort of trigger that removes the row again at the end of a transaction? From the jOOQ side, everything looks correct, but it appears that the second statement simply cannot see the record anymore that was created in the first statement...

**Comment by stayfool** [comment]
@lukaseder no, these tables are just use for learning jooq, no trigger, and this test is in none transaction environment, and in my debuging,   there is no data in database after first statement, but database's id sequence is increment

**Comment by lukaseder** [comment]
Interesting, thank you for the feedback. Will try to reproduce soon

**Comment by lukaseder** [comment]
Postponing this until we know what we'll do with these DAOs (#5984)

**Comment by stayfool** [comment]
@lukaseder This problem is that I forgot to set the jdbc's `autocommit` property to `true`, After I set `autocommit` property to `true`, it behaves well

**Comment by lukaseder** [comment]
Thank you very much for the feedback. I'm closing this, then.
