### ISSUE TITLE
Occasionally slow code generation query on Oracle 12c

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5836]
This `SQLPerformanceWarning` occasionally appears when generating code from Oracle 12c - not in 11g! (this might also be due to the fact that tests were run on 12c EE but 11g XE, which probably has less SYS objects)

Query:

```sql
select
  "SYS"."ALL_CONS_COLUMNS"."OWNER",
  "SYS"."ALL_CONS_COLUMNS"."CONSTRAINT_NAME",
  "SYS"."ALL_CONS_COLUMNS"."TABLE_NAME",
  "SYS"."ALL_CONS_COLUMNS"."COLUMN_NAME"
from "SYS"."ALL_CONS_COLUMNS"
  join "SYS"."ALL_CONSTRAINTS"
  on (
    "SYS"."ALL_CONS_COLUMNS"."OWNER" = "SYS"."ALL_CONSTRAINTS"."OWNER"
    and "SYS"."ALL_CONS_COLUMNS"."CONSTRAINT_NAME" = "SYS"."ALL_CONSTRAINTS"."CONSTRAINT_NAME"
  )
where (
  "SYS"."ALL_CONSTRAINTS"."CONSTRAINT_TYPE" = 'P'
  and "SYS"."ALL_CONSTRAINTS"."CONSTRAINT_NAME" not like 'BIN$%'
  and upper("SYS"."ALL_CONS_COLUMNS"."OWNER") in (
    'TEST', 'MULTI_SCHEMA', 'USR_2522', 'SYS'
  )
)
order by
  "SYS"."ALL_CONS_COLUMNS"."OWNER" asc,
  "SYS"."ALL_CONS_COLUMNS"."CONSTRAINT_NAME" asc,
  "SYS"."ALL_CONS_COLUMNS"."POSITION" asc
```

Exception:

```
org.jooq.util.AbstractDatabase$1$SQLPerformanceWarning
        at org.jooq.util.AbstractDatabase$1.executeEnd(AbstractDatabase.java:261)
        at org.jooq.impl.ExecuteListeners.executeEnd(ExecuteListeners.java:159)
        at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:275)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:346)
        at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:323)
        at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2705)
        at org.jooq.util.oracle.OracleDatabase.fetchKeys(OracleDatabase.java:196)
        at org.jooq.util.oracle.OracleDatabase.loadPrimaryKeys(OracleDatabase.java:148)
        at org.jooq.util.AbstractDatabase.getRelations0(AbstractDatabase.java:1661)
        at org.jooq.util.AbstractDatabase.getRelations(AbstractDatabase.java:1450)
        at org.jooq.util.DefaultColumnDefinition.getPrimaryKey(DefaultColumnDefinition.java:87)
        at org.jooq.util.AbstractTableDefinition.getPrimaryKey(AbstractTableDefinition.java:76)
        at org.jooq.util.JavaGenerator.generateTable(JavaGenerator.java:3281)
        at org.jooq.util.JavaGenerator.generateTable(JavaGenerator.java:3275)
        at org.jooq.util.JavaGenerator.generateTables(JavaGenerator.java:3262)
        at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:419)
        at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:373)
        at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:295)
        at org.jooq.util.GenerationTool.run(GenerationTool.java:607)
        at org.jooq.util.GenerationTool.generate(GenerationTool.java:196)
        at org.jooq.util.maven.Plugin.execute(Plugin.java:185)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by lukaseder** [comment]
Some heavy filtering seems to be going on inside of `ALL_CONS_COLUMNS`

![image](https://cloud.githubusercontent.com/assets/734593/22627277/643d3e4a-ebc0-11e6-9d41-b39dbb291f5d.png)

**Comment by lukaseder** [comment]
Transforming the unneeded to-one `JOIN` between `ALL_CONS_COLUMNS` and `ALL_CONSTRAINTS` to a semi `JOIN` seems to greatly help the execution plan. The following query produces an equivalent result

**Comment by lukaseder** [comment]
While the execution plan is significantly better (cost 1000), the execution time is only marginally better.

**Comment by lukaseder** [comment]
The improvement is not significant, unfortunately

**Comment by lukaseder** [comment]
A few things have been improved in jOOQ 3.18 already:

- https://github.com/jOOQ/jOOQ/issues/14014
- https://github.com/jOOQ/jOOQ/issues/14017
- https://github.com/jOOQ/jOOQ/issues/14021

Note sure if this here can still be reproduced? It hasn't shown up recently on Oracle 18c
