### ISSUE TITLE
Don't return null as Spring DB name when the DB is not supported by Spring

### ISSUE THREAD

**Issue by LukasMiedema** [jOOQ/jOOQ#5944]
In [`org.jooq.SQLDialect.ThirdParty.springDbName():549`](https://github.com/jOOQ/jOOQ/blob/master/jOOQ/src/main/java/org/jooq/SQLDialect.java#L549), jOOQ currently returns null when the database is not supported by Spring. This however makes for some very confusing stacktraces as Spring validates against null down the line and prints "Database product name must not be null" instead of anything related to the actual error. Additionally, Spring contains mechanisms for dealing with unsupported databases and prints a much more useful message when it simply doesn't recognize the name.

I propose returning `SQLDialect.this.family.getName()` and have Spring deal with it from there when the database is otherwise not supported.

For example, when using SQLite (supported by jOOQ but not by Spring)
With jOOQ returning null:
```
java.lang.IllegalArgumentException: Database product name must not be null
	at org.springframework.util.Assert.notNull(Assert.java:115) ~[spring-core-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.jdbc.support.SQLErrorCodesFactory.getErrorCodes(SQLErrorCodesFactory.java:162) ~[spring-jdbc-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.setDatabaseProductName(SQLErrorCodeSQLExceptionTranslator.java:146) ~[spring-jdbc-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.<init>(SQLErrorCodeSQLExceptionTranslator.java:110) ~[spring-jdbc-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.getTranslator(JooqExceptionTranslator.java:62) ~[spring-boot-autoconfigure-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.exception(JooqExceptionTranslator.java:48) ~[spring-boot-autoconfigure-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.jooq.impl.ExecuteListeners.exception(ExecuteListeners.java:245) ~[jooq-3.9.1.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:359) ~[jooq-3.9.1.jar:na]
	at org.jooq.impl.InsertImpl.fetchOne(InsertImpl.java:699) ~[jooq-3.9.1.jar:na]
	...
```

With jOOQ returning `SQLDialect.this.family.getName()`:
```
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: example_table)
	at org.sqlite.core.DB.newSQLException(DB.java:909) ~[sqlite-jdbc-3.16.1.jar:na]
	at org.sqlite.core.DB.newSQLException(DB.java:921) ~[sqlite-jdbc-3.16.1.jar:na]
	at org.sqlite.core.DB.throwex(DB.java:886) ~[sqlite-jdbc-3.16.1.jar:na]
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method) ~[sqlite-jdbc-3.16.1.jar:na]
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:127) ~[sqlite-jdbc-3.16.1.jar:na]
	at org.sqlite.core.DB.prepare(DB.java:227) ~[sqlite-jdbc-3.16.1.jar:na]
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:41) ~[sqlite-jdbc-3.16.1.jar:na]
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30) ~[sqlite-jdbc-3.16.1.jar:na]
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19) ~[sqlite-jdbc-3.16.1.jar:na]
	...
```

As you can see, the last error is infinitely more helpful, even though it's not nicely mapped to a Spring exception.
I could clone the repository and make a pull request if that is desired, but considering how minimal the change is (1 line + the javadoc) let me know if that helps.

**Comment by lukaseder** [comment]
Interesting, thanks for reporting.

Returning `null` has its caveats, but it's certainly more sensible than returning a random value that hides the fact that jOOQ cannot map the jOOQ dialect to a Spring dialect.

I'd say, we had rather solve this problem in Spring Boot, which calls the jOOQ logic:
https://github.com/spring-projects/spring-boot/blob/v1.5.2.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jooq/JooqExceptionTranslator.java#L62

I have created an issue there: https://github.com/spring-projects/spring-boot/issues/8521

**Comment by lukaseder** [comment]
This has just been fixed in Spring Boot. Thanks again for reporting!

**Comment by bachateraconfuego** [comment]
Was this released?

**Comment by LukasMiedema** [comment]
Yes, it was fixed in Spring. Spring Boot 1.5.3 was the first release to ship with the fix.
