### ISSUE TITLE
StackOverflowError when DefaultBinding.pgFromString() encounters unknown type

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6058]
There's a `StackOverflowError` in `DefaultBinding.pgFromString()`:

```
java.lang.StackOverflowError
	at org.jooq.impl.DefaultBinding.pgFromString(DefaultBinding.java:2259)
	at org.jooq.impl.DefaultBinding.pgFromString(DefaultBinding.java:2254)
	at org.jooq.impl.DefaultBinding.pgFromString(DefaultBinding.java:2346)
	at org.jooq.impl.DefaultBinding.pgFromString(DefaultBinding.java:2254)
	at org.jooq.impl.DefaultBinding.pgFromString(DefaultBinding.java:2346)
        ...
```

This results from the wrong logic here:

```java
        else {
            Converter<Object, T> c = (Converter<Object, T>) converter;
            return c.from(pgFromString(c.fromType(), string));
        }

        throw new UnsupportedOperationException("Class " + type + " is not supported");
```

When the converter is an identity converter, then `c.fromType()` is the same type as the previous `type` in `pgFromString()`, which means we'll never end (and never reach the `UOE`).

This can happen when nested records return types like `TIMESTAMP WITH TIME ZONE` (see: https://github.com/jOOQ/jOOQ/issues/6031)

**Comment by lukaseder** [comment]
This regression was introduced with https://github.com/jOOQ/jOOQ/issues/4964
