### ISSUE TITLE
javaTimeTypes: wrong type varbinary for sql date on jdbc side

### ISSUE THREAD

**Issue by dmiorandi** [jOOQ/jOOQ#6152]
- sqlserver 2016 with last jdbc driver (v6 /january) from ms.
- java8
- jooq 3.9.2
- sql update on date field with null value.

Using new jsr310 generator of jooq 3.9, classes are genereted right (with LocalDate type), but when executing the query (an update in my case) date type fields are passed as varbinary on jdbc side, generating this error:

Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: La conversione implicita del tipo di dati da varbinary a date non è consentita. Per eseguire la query, utilizzare la funzione CONVERT.

If I copy from debugger the complete query (with parameters resolved) as text and executing it
on sql server managment studio it works. It's just a jdbc parameter type issue.
This is just on date, datetime works fine instead (on same query). Actually solution to me is to recover
the old converter.

```xml
<database>
	<!-- <name>org.jooq.util.h2.H2Database</name> -->
	<!-- <name>org.jooq.util.sqlserver.SQLServerDatabase</name> -->
	<!-- <name>org.jooq.util.postgres.PostgresDatabase</name> -->
	<name>${jooq-database-name}</name>
	<dateAsTimestamp>false</dateAsTimestamp>
	<!-- <inputSchema>PUBLIC</inputSchema> -->
	<inputSchema>${spring.datasource.schema}</inputSchema>

	<customTypes>
		<!--<customType>-->
			<!--<name>LocalDateTime</name>-->
			<!--<type>java.time.LocalDateTime</type>-->
			<!--<converter>${company-package-prefix}.jooq.converters.LocalDateTimeConverter</converter>-->
		<!--</customType>-->
		<customType>
			<name>LocalDate</name>
			<type>java.time.LocalDate</type>
			<converter>${company-package-prefix}.jooq.converters.LocalDateConverter</converter>
		</customType>
		<!--<customType>-->
			<!--<name>LocalTime</name>-->
			<!--<type>java.time.LocalTime</type>-->
			<!--<converter>${company-package-prefix}.jooq.converters.LocalTimeConverter</converter>-->
		<!--</customType>-->
		<customType>
			<name>XmlSqlXmlBinding</name>
			<type>java.sql.SQLXML</type>
			<binding>${company-package-prefix}.jooq.bindings.XmlSqlXmlBinding</binding>
		</customType>
		<customType>
			<name>XmlStringBinding</name>
			<type>java.lang.String</type>
			<binding>${company-package-prefix}.jooq.bindings.XmlStringBinding</binding>
		</customType>
	</customTypes>
   <forcedTypes>
	  <!--<forcedType>-->
		<!--<name>LocalDateTime</name>-->
		<!--<expression>(\w+\.)?(?!UDT_PREFIX|PROC_PREFIX)\w+(\.\w+)?</expression>-->
		<!--<types>^datetime|dateTime|DateTime|DATETIME|smalldatetime$</types>-->
	  <!--</forcedType>-->
	  <!--<forcedType>-->
		<!--<name>LocalTime</name>-->
		<!--<expression>(\w+\.)?(?!UDT_PREFIX|PROC_PREFIX)\w+(\.\w+)?</expression>-->
		<!--<types>^time|Time|TIME$</types>-->
	  <!--</forcedType>-->
	  <forcedType>
		<name>LocalDate</name>
		<expression>(\w+\.)?(?!UDT_PREFIX|PROC_PREFIX)\w+(\.\w+)?</expression>
		<types>^date|Date|DATE$</types>
	  </forcedType>
	  <!--<forcedType>-->
		<!--<name>LocalDateTime</name>-->
		<!--<expression>(\w+\.)?(?!UDT_PREFIX|PROC_PREFIX)\w+(\.\w+)?</expression>-->
		<!--<types>(?i).*timestamp.*</types>-->
	  <!--</forcedType>-->
	  <forcedType>
		<name>XmlStringBinding</name>
		<expression>(\w+\.)?(?!UDT_PREFIX|PROC_PREFIX)\w+(\.\w+)?</expression>
		<types>XML</types>
	  </forcedType>
	</forcedTypes>										
</database>
<generate>
	<deprecated>false</deprecated>
	<instanceFields>true</instanceFields>
	<pojos>true</pojos>
	<validationAnnotations>true</validationAnnotations>
	<fluentSetters>true</fluentSetters>
	<javaTimeTypes>false</javaTimeTypes>
</generate>
```
```java
09:55:49.150 [qtp1161698234-21] ERROR com.smashit.common.api.exceptions.ApiUnhandledExceptionImpl - org.jooq.exception.DataAccessException: SQL [update [ORDE_Orders] set [ORDE_Orders].[id_companyseat_customer] = ?, [ORDE_Orders].[id_companyseat_mandant] = ?, [ORDE_Orders].[id_invoice] = ?, [ORDE_Orders].[payment_expiration] = ?, [ORDE_Orders].[notes] = ?, [ORDE_Orders].[ID_DB_ACCESS] = ?, [ORDE_Orders].[ID_PaymentAccount] = ?, [ORDE_Orders].[ID_PaymentTerms] = ?, [ORDE_Orders].[rec_date_insert] = ?, [ORDE_Orders].[rec_date_update] = ?, [ORDE_Orders].[rec_user_insert] = ?, [ORDE_Orders].[rec_user_update] = ?, [ORDE_Orders].[rec_state] = ? where [ORDE_Orders].[ID_Order] = ?]; La conversione implicita del tipo di dati da varbinary a date non è consentita. Per eseguire la query, utilizzare la funzione CONVERT.
	at org.jooq_3.9.2.SQLSERVER2012.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:1983)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:676)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:363)
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:135)
	at com.smashit.fralog.services.DbManagerImpl.storeToDb(DbManagerImpl.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy93.storeToDb(Unknown Source)
	at com.smashit.fralog.services.orders.OrderServiceImpl.save(OrderServiceImpl.java:1193)
	at com.smashit.fralog.services.orders.OrderServiceImpl.lambda$saveInvoices$154(OrderServiceImpl.java:1676)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.smashit.fralog.services.orders.OrderServiceImpl.saveInvoices(OrderServiceImpl.java:1654)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy113.saveInvoices(Unknown Source)
	at com.smashit.fralog.resources.OrdersResourceImpl.postOrdersInvoices(OrdersResourceImpl.java:211)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.springmvc.ResteasyHandlerAdapter.createModelAndView(ResteasyHandlerAdapter.java:96)
	at org.jboss.resteasy.springmvc.ResteasyHandlerAdapter.handle(ResteasyHandlerAdapter.java:82)
	at org.jboss.resteasy.springmvc.ResteasyHandlerAdapter.handle(ResteasyHandlerAdapter.java:26)
	at org.jboss.resteasy.springmvc.ResteasyWebHandlerTemplate.handle(ResteasyWebHandlerTemplate.java:39)
	at org.jboss.resteasy.springmvc.ResteasyHandlerAdapter.handle(ResteasyHandlerAdapter.java:47)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1712)
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1699)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:121)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1699)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:523)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: La conversione implicita del tipo di dati da varbinary a date non è consentita. Per eseguire la query, utilizzare la funzione CONVERT.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1655)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:440)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:385)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:191)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:166)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:367)
	at com.zaxxer.hikari.proxy.PreparedStatementProxy.execute(PreparedStatementProxy.java:44)
	at com.zaxxer.hikari.proxy.HikariPreparedStatementProxy.execute(HikariPreparedStatementProxy.java)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:195)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:431)
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:335)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:349)
	... 107 more
```

```java
update [ORDE_Orders]
set [ORDE_Orders].[id_companyseat_customer] = 1012, 
    [ORDE_Orders].[id_companyseat_mandant] = 2, 
    [ORDE_Orders].[id_invoice] = 12195, 
    **[ORDE_Orders].[payment_expiration] = null,** 
    [ORDE_Orders].[notes] = null, 
    [ORDE_Orders].[ID_DB_ACCESS] = null, 
    [ORDE_Orders].[ID_PaymentAccount] = null, 
    [ORDE_Orders].[ID_PaymentTerms] = null, 
    [ORDE_Orders].[rec_date_insert] = '2017-03-15T18:42:49.487', 
    [ORDE_Orders].[rec_date_update] = '2017-04-24T21:59:29.377', 
    [ORDE_Orders].[rec_user_insert] = null, 
    [ORDE_Orders].[rec_user_update] = null, 
    [ORDE_Orders].[rec_state] = 40
where [ORDE_Orders].[ID_Order] = 103116
```

**Comment by lukaseder** [comment]
Sorry for the delay in this matter. I've fixed quite a few other date/time related issues recently, and tomorrow, I'm planning to release 3.9.3.

I currently cannot reproduce this issue with jOOQ 3.10 or 3.9.2 when using ordinary `Field<LocalDate>` fields for updates. Could you perhaps show the generated class for `ORDE_Orders`? Perhaps, something went wrong in there, which I'm not aware of yet...

**Comment by lukaseder** [comment]
At the time, I was unable to reproduce this problem. If the issue still persists, in the meantime, we have a template project for creating minimal reproducers on a variety of database products, including SQL Server:

- https://github.com/jOOQ/jOOQ-mcve

I'll be happy to review a reproducer (against a more recent version of jOOQ).
