### ISSUE TITLE
how to set a global setting for converting timestamp to org.joda.time.DateTime

### ISSUE THREAD

**Issue by zzsoszz** [jOOQ/jOOQ#6157]
```java
@Service
public class ActivityService {
	@Autowired
	DSLContext create;
	@Transactional
	public List<Activity> findByCategory(Long categoryid) {
		return create.select().from(Tables.ACTIVITY).fetch().into(Activity.class);//here throw an Exception below;
	}
}

public class Activity   {
  private org.joda.time.DateTime begintime = null;
}
```

```
Caused by: org.jooq.exception.DataTypeException: Cannot convert from 1493121747589 (class java.lang.Long) to class org.joda.time.DateTime
	at org.jooq.tools.Convert$ConvertAll.fail(Convert.java:1118)
	at org.jooq.tools.Convert$ConvertAll.toDate(Convert.java:1070)
	at org.jooq.tools.Convert$ConvertAll.from(Convert.java:789)
	at org.jooq.tools.Convert.convert0(Convert.java:316)
	at org.jooq.tools.Convert.convert(Convert.java:308)
	at org.jooq.tools.Convert.convert(Convert.java:380)
	at org.jooq.impl.AbstractRecord.get(AbstractRecord.java:245)
	at org.jooq.impl.DefaultRecordMapper$MutablePOJOMapper.map(DefaultRecordMapper.java:726)
	at org.jooq.impl.DefaultRecordMapper$MutablePOJOMapper.map(DefaultRecordMapper.java:646)
	... 30 common frames omitted
```

**Comment by zzsoszz** [comment]
i have used the configuration to generate code,but still got that exception.
<database>
                                    <includes>.*</includes>
                                    <inputSchema>FLYWAY_TEST</inputSchema>
                                    <schemaVersionProvider>SELECT :schema_name || '_' || MAX("version") FROM "FLYWAY_TEST"."schema_version"</schemaVersionProvider>
                                    <customTypes>
									    <customType>
									      <name>DateTimeConverter</name>
									      <type>org.joda.time.DateTime</type>
									      <converter>io.swagger.service.DateTimeConverter</converter>
									    </customType>
									</customTypes>
									<forcedTypes>
									    <forcedType>
									      <name>DateTimeConverter</name>
									      <expression>.*DATE.*</expression>
									      <types>.*</types>
									    </forcedType>
									</forcedTypes>
                                </database>

**Comment by lukaseder** [comment]
Thank you very much for your enquiry.

jOOQ doesn't support JodaTime out of the box, which means that your `into(Activity.class)` call cannot work this way. I can see these options:

- You could use JSR-310 data types, which are supported out of the box (there might still be 1-2 bugs in version 3.9.2)
- You could fix your `<forcedType><expression>`, it only matches columns containing the letters `DATE`. Your column is called `BEGINTIME`
