### ISSUE TITLE
got failed when alias column name

### ISSUE THREAD

**Issue by zzsoszz** [jOOQ/jOOQ#6158]
-https://github.com/jOOQ/jOOQ/issues/4512

got failed when alias column name on h2database

java code
```java
JdbcMapper<Tuple2<AuthorRecord, List<BookRecord>>> mapper = 
	    JdbcMapperFactory
	        .newInstance()
	        .addKeys("id")
	        .newMapper(new TypeReference<Tuple2<AuthorRecord, List<BookRecord>>>() {});
		try (ResultSet rs =
		         ctx
		            .select()
		            .from(AUTHOR).leftJoin(BOOK.as("v1",field->"AUTHOR_"+field.getName())).on(BOOK.AUTHOR_ID.eq(AUTHOR.ID))
		            .orderBy(AUTHOR.ID)
		            .fetchResultSet()) {
			Stream<Tuple2<AuthorRecord, List<BookRecord>>> stream = mapper.stream(rs);
			stream.forEach(one->{
				System.out.println(one.v1);
			});
		}
```

generated sql 

```sql
SELECT
    "FLYWAY_TEST" . "AUTHOR" . "ID",
    "FLYWAY_TEST" . "AUTHOR" . "FIRST_NAME",
    "FLYWAY_TEST" . "AUTHOR" . "LAST_NAME",
    "FLYWAY_TEST" . "AUTHOR" . "DATE_OF_BIRTH",
    "FLYWAY_TEST" . "AUTHOR" . "YEAR_OF_BIRTH",
    "FLYWAY_TEST" . "AUTHOR" . "ADDRESS",
    "FLYWAY_TEST" . "AUTHOR" . "CREATEDATE",
    "v1" . "AUTHOR_ID",
    "v1" . "AUTHOR_AUTHOR_ID",
    "v1" . "AUTHOR_TITLE",
    "v1" . "AUTHOR_CREATEDATE"
FROM
    **"FLYWAY_TEST" . "AUTHOR" LEFT OUTER JOIN "FLYWAY_TEST" . "BOOK" "v1"(
        "AUTHOR_ID",
        "AUTHOR_AUTHOR_ID",
        "AUTHOR_TITLE",
        "AUTHOR_CREATEDATE"
    )**(h2database not supported this syntax)
        ON "FLYWAY_TEST" . "BOOK" . "AUTHOR_ID" = "FLYWAY_TEST" . "AUTHOR" . "ID"
ORDER BY
    "FLYWAY_TEST" . "AUTHOR" . "ID" ASC
```

got Exception
```java
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT ""FLYWAY_TEST"".""AUTHOR"".""ID"", ""FLYWAY_TEST"".""AUTHOR"".""FIRST_NAME"", ""FLYWAY_TEST"".""AUTHOR"".""LAST_NAME"", ""FLYWAY_TEST"".""AUTHOR"".""DATE_OF_BIRTH"", ""FLYWAY_TEST"".""AUTHOR"".""YEAR_OF_BIRTH"", ""FLYWAY_TEST"".""AUTHOR"".""ADDRESS"", ""FLYWAY_TEST"".""AUTHOR"".""CREATEDATE"", ""v1"".""AUTHOR_ID"", ""v1"".""AUTHOR_AUTHOR_ID"", ""v1"".""AUTHOR_TITLE"", ""v1"".""AUTHOR_CREATEDATE"" FROM ""FLYWAY_TEST"".""AUTHOR"" LEFT OUTER JOIN ""FLYWAY_TEST"".""BOOK"" ""v1""([*]""AUTHOR_ID"", ""AUTHOR_AUTHOR_ID"", ""AUTHOR_TITLE"", ""AUTHOR_CREATEDATE"") ON ""FLYWAY_TEST"".""BOOK"".""AUTHOR_ID"" = ""FLYWAY_TEST"".""AUTHOR"".""ID"" ORDER BY ""FLYWAY_TEST"".""AUTHOR"".""ID"" ASC "; SQL statement:
select "FLYWAY_TEST"."AUTHOR"."ID", "FLYWAY_TEST"."AUTHOR"."FIRST_NAME", "FLYWAY_TEST"."AUTHOR"."LAST_NAME", "FLYWAY_TEST"."AUTHOR"."DATE_OF_BIRTH", "FLYWAY_TEST"."AUTHOR"."YEAR_OF_BIRTH", "FLYWAY_TEST"."AUTHOR"."ADDRESS", "FLYWAY_TEST"."AUTHOR"."CREATEDATE", "v1"."AUTHOR_ID", "v1"."AUTHOR_AUTHOR_ID", "v1"."AUTHOR_TITLE", "v1"."AUTHOR_CREATEDATE" from "FLYWAY_TEST"."AUTHOR" left outer join "FLYWAY_TEST"."BOOK" "v1"("AUTHOR_ID", "AUTHOR_AUTHOR_ID", "AUTHOR_TITLE", "AUTHOR_CREATEDATE") on "FLYWAY_TEST"."BOOK"."AUTHOR_ID" = "FLYWAY_TEST"."AUTHOR"."ID" order by "FLYWAY_TEST"."AUTHOR"."ID" asc [42000-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.getSyntaxError(DbException.java:191)
	at org.h2.command.Parser.getSyntaxError(Parser.java:530)
	at org.h2.command.Parser.prepareCommand(Parser.java:257)
	at org.h2.engine.Session.prepareLocal(Session.java:561)
	at org.h2.engine.Session.prepareCommand(Session.java:502)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1203)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:287)
	at net.sf.log4jdbc.ConnectionSpy.prepareStatement(ConnectionSpy.java:388)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81)
	at com.sun.proxy.$Proxy82.prepareStatement(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy$TransactionAwareInvocationHandler.invoke(TransactionAwareDataSourceProxy.java:240)
	at com.sun.proxy.$Proxy83.prepareStatement(Unknown Source)
	at org.jooq.impl.ProviderEnabledConnection.prepareStatement(ProviderEnabledConnection.java:112)
	at org.jooq.impl.SettingsEnabledConnection.prepareStatement(SettingsEnabledConnection.java:76)
	at org.jooq.impl.AbstractResultQuery.prepare(AbstractResultQuery.java:232)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:321)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:368)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:355)
	at org.jooq.impl.AbstractResultQuery.fetchResultSet(AbstractResultQuery.java:321)
	at org.jooq.impl.SelectImpl.fetchResultSet(SelectImpl.java:2713)
	at io.swagger.service.ActivityService.findByCategory(ActivityService.java:60)
	at io.swagger.service.ActivityService$$FastClassBySpringCGLIB$$280d3621.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at io.swagger.service.ActivityService$$EnhancerBySpringCGLIB$$5c8fd128.findByCategory(<generated>)
	at io.swagger.Swagger2SpringBoot.onApplicationEvent(Swagger2SpringBoot.java:254)
	at io.swagger.Swagger2SpringBoot.onApplicationEvent(Swagger2SpringBoot.java:1)
	at io.swagger.Swagger2SpringBoot$$EnhancerBySpringCGLIB$$77bfc77b.onApplicationEvent(<generated>)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:337)
	at org.springframework.boot.context.event.EventPublishingRunListener.finished(EventPublishingRunListener.java:93)
	at org.springframework.boot.SpringApplicationRunListeners.callFinishedListener(SpringApplicationRunListeners.java:79)
	at org.springframework.boot.SpringApplicationRunListeners.finished(SpringApplicationRunListeners.java:72)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317)
	at io.swagger.Swagger2SpringBoot.main(Swagger2SpringBoot.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
```

**Comment by lukaseder** [comment]
Thank you very much for your report. I'll look at it immediately. On a side note: You don't have to go through fetching a JDBC `ResultSet` and wrapping that in a `Stream`. It's probably simpler to just call `ResultQuery.fetchStream()` instead...

**Comment by lukaseder** [comment]
Hmm, are you sure your `ctx` is correctly configured with the `SQLDialect.H2`? Derived column lists should be emulated correctly on H2 using the trick at the bottom of:
https://blog.jooq.org/2013/01/07/simulating-the-sql-standard

By the way, your `on()` clause is wrong. Since you're renaming both the `BOOK` table and its columns, you must use the renamed column `"v1"."AUTHOR_ID"` instead of the original, fully qualified `"FLYWAY_TEST" . "BOOK" . "AUTHOR_ID"`.

In that case, it works for me...

**Comment by zzsoszz** [comment]
Thanks for your reply!

but how to reference the renamed column?
renamedtable.field(BOOK.AUTHOR_ID)  will get java.lang.NullPointerException;

```java
@Transactional
	public List<Activity> findByCategory(Long categoryid) throws MappingException, SQLException {
		JdbcMapper<Tuple2<AuthorRecord, List<BookRecord>>> mapper = 
	    JdbcMapperFactory
	        .newInstance()
	        .addKeys("id")
	        .newMapper(new TypeReference<Tuple2<AuthorRecord, List<BookRecord>>>() {});
		Table<BookRecord> renamedtable = BOOK.as("v1",field->"BOOK_"+field.getName());
		try (ResultSet rs =
		         ctx
		            .select()
		            .from(AUTHOR)
		            .leftJoin(renamedtable).on(renamedtable.field(BOOK.AUTHOR_ID).eq(AUTHOR.ID))
		            .orderBy(AUTHOR.ID)
		            .fetchResultSet()) {
			Stream<Tuple2<AuthorRecord, List<BookRecord>>> stream = mapper.stream(rs);
			stream.forEach(one->{
				System.out.println(one.v1);
			});
		}
		return null;
	}

```

**Comment by lukaseder** [comment]
Yes, you renamed it to `"v1"."BOOK_AUTHOR_ID"`. The `Table.field(Field)` method cannot establish a link between `BOOK.AUTHOR_ID` and `"v1"."BOOK_AUTHOR_ID"`.

You could use `renamedtable.field("BOOK_" + BOOK.AUTHOR_ID.getName())`. If you want, you could factor out the concatenation in a new method / function:

```java
public static String prefix(TableField<?, ?> field) {
    return field.getTable().getName() + "_" + field.getName();
}
```
