### ISSUE TITLE
Error when using method overload with an array property

### ISSUE THREAD

**Issue by ypconstante** [jOOQ/jOOQ#6242]
When I have a method overload on the setter of an array column, jOOQ throws an exception during the record mapping.

```java
public void setRunTimes(OffsetDateTime... runTimes) {
    this.runTimes = runTimes;
}

public void setRunTimes(Collection<OffsetDateTime> runTimes) {
    this.runTimes = (OffsetDateTime[]) runTimes.toArray();
}
```

The error happens even when only one of the setters matches the column type.
```java
public void setRunTimes(OffsetDateTime[] runTimes) {
    this.runTimes = runTimes;
}

public void setRunTimes(String runTimes) {
}
```

Stack trace
```
org.jooq.exception.MappingException: An error ocurred when mapping record to class br.com.paripassu.dip.core.api.schedule.ScheduleEvent

	at org.jooq.impl.DefaultRecordMapper$MutablePOJOMapper.map(DefaultRecordMapper.java:690)
	at org.jooq.impl.DefaultRecordMapper.map(DefaultRecordMapper.java:368)
	at org.jooq.impl.AbstractRecord.into(AbstractRecord.java:688)
	at br.com.paripassu.dip.core.dao.impl.jdbc.ScheduleDAOImpl$ScheduleEventRecordMapper.map(ScheduleDAOImpl.java:191)
	at br.com.paripassu.dip.core.dao.impl.jdbc.ScheduleDAOImpl$ScheduleEventRecordMapper.map(ScheduleDAOImpl.java:1)
	at org.jooq.impl.ResultImpl.map(ResultImpl.java:2204)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:1285)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:3603)
	at br.com.paripassu.dip.core.dao.impl.jdbc.ScheduleDAOImpl.listEvent(ScheduleDAOImpl.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy49.listEvent(Unknown Source)
	at br.com.paripassu.dip.integration.ScheduleIntegrationTest.setup(ScheduleIntegrationTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jooq.impl.DefaultRecordMapper$MutablePOJOMapper.map(DefaultRecordMapper.java:662)
	... 50 more
```

**Comment by lukaseder** [comment]
Thanks for your report. We'll look into this. As per the current `DefaultRecordMapper` definition, indeed, all setters whose name and argument list *length* match are called, not just the "most specific" or "exact match". The benefit of this is that you can freely interchange `int` and `long` and the jOOQ auto-conversion will apply. The drawback is, you cannot overload. So, I'm currently not sure if we can fix this.

A workaround is of course not to overload your convenience method:

```java
public void setRunTimesCollection(Collection<OffsetDateTime> runTimes) {
    // Note, you need to pass an empty array here.
    this.runTimes = (OffsetDateTime[]) runTimes.toArray(new OffsetDateTime[0]);
}
```

**Comment by lukaseder** [comment]
I don't think there's a reasonable solution to this problem in the reflection based `DefaultRecordMapper`. Both setters match by name, and for convenience, we've always been lenient with respect to types (e.g. we also match `Long` parameters, even if the value is an `Integer`, as the conversion is straightforward). In other words, since we cannot *enforce* type safety (via reflection), why insist on it?

It's not usual to overload setters in JavaBeans style classes, so this seems to be an edge case. Besides, starting with jOOQ 3.15, we'll start moving away from reflection based mapping towards more functional approaches, see e.g. ad-hoc conversion: https://www.jooq.org/doc/latest/manual/sql-execution/fetching/ad-hoc-converter/

I'll close this issue as "won't fix"
