### ISSUE TITLE
SQLite code generation no longer generating foreign keys with latest Xerial driver version

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6343]
We're getting this exception now:

```
[ERROR] Error while fetching foreign keys
java.lang.IllegalArgumentException: Field (table) is not contained in Row ("UPDATE_COUNT")
        at org.jooq.impl.Tools.indexOrFail(Tools.java:1439)
        at org.jooq.impl.AbstractRecord.get(AbstractRecord.java:254)
        at org.jooq.util.sqlite.SQLiteDatabase.loadForeignKeys(SQLiteDatabase.java:213)
        at org.jooq.util.AbstractDatabase.getRelations0(AbstractDatabase.java:1779)
        at org.jooq.util.AbstractDatabase.getRelations(AbstractDatabase.java:1493)
        at org.jooq.util.DefaultColumnDefinition.getPrimaryKey(DefaultColumnDefinition.java:91)
        at org.jooq.util.AbstractTableDefinition.getPrimaryKey(AbstractTableDefinition.java:76)
        at org.jooq.util.JavaGenerator.generateTable(JavaGenerator.java:3403)
```

Further investigations needed.

**Comment by lukaseder** [comment]
Seems to work again with version 3.20.0 - probably an intermediate regression in the Xerial driver.
