### ISSUE TITLE
jOOQ Meta executed a slow query (slower than 5 seconds)

### ISSUE THREAD

**Issue by ckpleasure** [jOOQ/jOOQ#6346]
```sql
select
  `information_schema`.`REFERENTIAL_CONSTRAINTS`.`CONSTRAINT_SCHEMA`,
  `information_schema`.`REFERENTIAL_CONSTRAINTS`.`CONSTRAINT_NAME`,
  `information_schema`.`REFERENTIAL_CONSTRAINTS`.`TABLE_NAME`,
  `information_schema`.`REFERENTIAL_CONSTRAINTS`.`REFERENCED_TABLE_NAME`,
  `information_schema`.`REFERENTIAL_CONSTRAINTS`.`UNIQUE_CONSTRAINT_NAME`,
  `information_schema`.`REFERENTIAL_CONSTRAINTS`.`UNIQUE_CONSTRAINT_SCHEMA`,
  `information_schema`.`KEY_COLUMN_USAGE`.`COLUMN_NAME`
from `information_schema`.`REFERENTIAL_CONSTRAINTS`
  join `information_schema`.`KEY_COLUMN_USAGE`
  on (
    `information_schema`.`REFERENTIAL_CONSTRAINTS`.`CONSTRAINT_SCHEMA` = `information_schema`.`KEY_COLUMN_USAGE`.`CONSTRAINT_SCHEMA`
    and `information_schema`.`REFERENTIAL_CONSTRAINTS`.`CONSTRAINT_NAME` = `information_schema`.`KEY_COLUMN_USAGE`.`CONSTRAINT_NAME`
  )
where (
  `information_schema`.`REFERENTIAL_CONSTRAINTS`.`CONSTRAINT_SCHEMA` in ('jzmao')
  or `information_schema`.`REFERENTIAL_CONSTRAINTS`.`CONSTRAINT_SCHEMA` in ('jzmao')
)
order by
  `information_schema`.`KEY_COLUMN_USAGE`.`CONSTRAINT_SCHEMA` asc,
  `information_schema`.`KEY_COLUMN_USAGE`.`CONSTRAINT_NAME` asc,
  `information_schema`.`KEY_COLUMN_USAGE`.`ORDINAL_POSITION` asc
```

```
org.jooq.util.AbstractDatabase$1$SQLPerformanceWarning
        at org.jooq.util.AbstractDatabase$1.executeEnd(AbstractDatabase.java:273)
        at org.jooq.impl.ExecuteListeners.executeEnd(ExecuteListeners.java:162)
        at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:274)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:349)
        at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:315)
        at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2708)
        at org.jooq.util.mysql.MySQLDatabase.loadForeignKeys(MySQLDatabase.java:191)
        at org.jooq.util.AbstractDatabase.getRelations0(AbstractDatabase.java:1682)
        at org.jooq.util.AbstractDatabase.getRelations(AbstractDatabase.java:1457)
        at org.jooq.util.DefaultColumnDefinition.getPrimaryKey(DefaultColumnDefinition.java:90)
        at org.jooq.util.AbstractTableDefinition.getPrimaryKey(AbstractTableDefinition.java:79)
        at org.jooq.util.JavaGenerator.generateTable(JavaGenerator.java:3285)
        at org.jooq.util.JavaGenerator.generateTable(JavaGenerator.java:3279)
        at org.jooq.util.JavaGenerator.generateTables(JavaGenerator.java:3266)
        at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:422)
        at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:376)
        at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:298)
        at org.jooq.util.GenerationTool.run(GenerationTool.java:617)
        at org.jooq.util.GenerationTool.generate(GenerationTool.java:203)
        at org.jooq.util.GenerationTool.main(GenerationTool.java:175)

六月 14, 2017 4:36:07 下午 org.jooq.tools.JooqLogger info
```

**Comment by lukaseder** [comment]
Thank you very much for reporting this. In order to better assess what's going on, may I ask how many of these objects you have in your system?

- Databases
- Tables
- Foreign keys

**Comment by kiru** [comment]
Hi Lukas, 

I've got the same issue, my database is not huge. It only contains around 20 tables with around 5 columns in average ( max 20 columns). 
The problem is, that the database is just slow. Is there a way to increase this limit as a workaround?

Thank you,
Kiru

**Comment by lukaseder** [comment]
@kiru: No, the time cannot be configured right now, but I guess it makes sense to make it configurable. I've created a feature request for this: #7474

**Comment by lukaseder** [comment]
I don't really see an obvious way to improve this query.
