### ISSUE TITLE
NullPointerException when trying to get mvn help on goal generate

### ISSUE THREAD

**Issue by kubagruszka** [jOOQ/jOOQ#6406]
version: 3.9.3

When trying to get some details on the maven goal with this command: `mvn -X org.jooq:jooq-codegen-maven:help -Ddetail=true -Dgoal=generate` a NPE is thrown.

> [ERROR] Failed to execute goal org.jooq:jooq-codegen-maven:3.9.3:help (default-cli) on project storage-persistent: Execution default-cli of goal org.jooq:jooq-codegen-maven:3.9.3:help failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jooq:jooq-codegen-maven:3.9.3:help (default-cli) on project storage-persistent: Execution default-cli of goal org.jooq:jooq-codegen-maven:3.9.3:help failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.jooq:jooq-codegen-maven:3.9.3:help failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.NullPointerException
	at org.jooq.util.maven.HelpMojo.findNamedChild(HelpMojo.java:200)
	at org.jooq.util.maven.HelpMojo.findSingleChild(HelpMojo.java:215)
	at org.jooq.util.maven.HelpMojo.writeParameter(HelpMojo.java:273)
	at org.jooq.util.maven.HelpMojo.writeGoal(HelpMojo.java:261)
	at org.jooq.util.maven.HelpMojo.execute(HelpMojo.java:161)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by lukaseder** [comment]
Thank you very much for reporting. I can reproduce this problem. Upgrading the `maven-plugin-plugin` from version 3.3 to 3.5 fixed this as this was a bug in Maven: https://issues.apache.org/jira/browse/MPLUGIN-299
