### ISSUE TITLE
LoggerListener logs an Exception with DEBUG level instead of with ERROR level

### ISSUE THREAD

**Issue by rogerdielrton** [jOOQ/jOOQ#6464]
Hello.
Here is the Log4J execution trace of the case:
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  Thank you for using jOOQ 3.9.4
2017-07-27 10:07:03 DEBUG LoggerListener:264 - Executing query          : create schema if not exists "jsontest"
2017-07-27 10:07:03 DEBUG LoggerListener:296 - Exception                
org.jooq.exception.DataAccessException: SQL [create schema if not exists "jsontest"]; ERROR: permission denied for database database1
	at org.jooq_3.9.4.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:1994)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:676)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:363)
	at com.xyz.pgjsoningester.persistence.RepositoryImpl.createSchemaJsonTest(RepositoryImpl.java:19)
	at com.xyz.pgjsoningester.RepositoryTester.test1(RepositoryTester.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.postgresql.util.PSQLException: ERROR: permission denied for database database1
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2476)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2189)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:158)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:195)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:431)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:349)
	... 25 more
2017-07-27 10:07:03 DEBUG StopWatch:264 - Exception                : Total: 136.853ms
2017-07-27 10:07:03 DEBUG StopWatch:264 - Finishing                : Total: 150.001ms, +13.148ms
```
There is a PSQLException, and it's logged with a DEBUG level!

**Comment by lukaseder** [comment]
Thank you very much for your report. The built-in `LoggerListener` is a debugging tool as documented here: https://www.jooq.org/doc/latest/manual/sql-execution/logging. Being a debugging tool, it shouldn't unnecessarily spam your productive environments with `INFO`, `WARN`, or `ERROR` log messages.

This being an exception, it is quite likely that it will propagate up your call stack and trigger your own, more appropriate error logging logic.

I hope this helps.

**Comment by rogerdielrton** [comment]
Thank you Lukas for your quick reply.
I believe that an exception should be logged as ERROR level because I was wondering why the "jsontest" schema was not created and only setting the log4j config to DEBUG level I could discover the cause.

**Comment by lukaseder** [comment]
Where did the exception go? Did your client code (`RepositoryImpl.createSchemaJsonTest`) swallow it?
