### ISSUE TITLE
Cannot deserialize UDT using pgjdbc-ng driver

### ISSUE THREAD

**Issue by gregopet** [jOOQ/jOOQ#6547]
### Expected behavior and actual behavior:

Expecting insert & fetch of UDTs to work (see steps to reproduce below).

I'm not sure how supported pgjdbc-ng is supposed to be but if it helps I can provide more info, try things or reframe the report into something more suitable (just tell me what you need).

### Steps to reproduce the problem:
Create an UDT and a table:

    CREATE TYPE cardqty AS (card_id INTEGER, qty INTEGER);
    CREATE TABLE card_qty_test (
        id bigserial,
        card cardqty
    );

Run following unit test (Groovy code, we're using Spock for testing):

    def "Custom types can be serialized and deserialized back"() {
        given:
        def qty = new CardqtyRecord(5, 10)

        when:
        jooq.insertInto(CARD_QTY_TEST, CARD_QTY_TEST.CARD).values(qty).execute()
        def fetchback = jooq.selectFrom(CARD_QTY_TEST).fetchOne()

        then:
        fetchback.card.qty == 10
        fetchback.card.cardId == 5
    }

The following exception occurs:

    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.jooq.impl.DefaultBinding$2.operate(DefaultBinding.java:2385)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:128)
	at org.jooq.impl.DefaultBinding.pgNewRecord(DefaultBinding.java:2378)
	at org.jooq.impl.DefaultBinding.get(DefaultBinding.java:1595)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1653)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.operate(CursorImpl.java:1624)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.operate(CursorImpl.java:1589)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:128)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchOne(CursorImpl.java:1553)
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1520)
	at org.jooq.impl.CursorImpl.fetch(CursorImpl.java:342)
	at org.jooq.impl.CursorImpl.fetchOne(CursorImpl.java:300)
	at org.jooq.impl.Tools.fetchOne(Tools.java:1495)
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:520)
	at org.jooq.impl.SelectImpl.fetchOne(SelectImpl.java:2871)
	at com.blahblah.Custom types can be serialized and deserialized back(DaoProviderIntegrationTest.groovy:41)

### Versions:
- jOOQ: 3.9.5
- Database (include vendor): Postgres 9.5.5
- JDBC Driver (include name if inofficial driver): pgjdbc-ng 0.7.1

**Comment by lukaseder** [comment]
Thanks for your report. We're aware of the pgjdbc-ng driver but we currently do not support it. This reflects well in more advanced use-cases as this one, where the driver does not match the behaviour of the official driver.

Sure, it's a good choice by the pgjdbc-ng driver to implement the JDBC standard `SQLData` et al. APIs for user defined types, but as long as the standard driver doesn't follow suit, we currently cannot invest too much time in this (yet) - there are simply too many alternative JDBC drivers for PostgreSQL, each with their own caveats.

**Comment by lukaseder** [comment]
... having said so, you'll get very far using jOOQ with the standard JDBC driver, so if you intend to run all your database interactions through jOOQ, that would be the recommended way forward.

**Comment by gregopet** [comment]
Alright, thank you - we wanted to try pgjdbc-ng and maybe report a bug or two to them, but we are exclusively using jOOQ for data access and we would really like to use Postgres' advanced features so we will follow your advice and use the standard driver.

I should probably close this bug since it may no longer be of relevance once/if jOOQ starts supporting pgjdbc-ng?

**Comment by lukaseder** [comment]
We can leave this issue open. If we do support pgjdbc-ng, it's good to be reminded of what exactly fails with PostgreSQL UDT integration.
