### ISSUE TITLE
Timestamps with zone ids cannot be read

### ISSUE THREAD

**Issue by schroenser** [jOOQ/jOOQ#6581]
### Expected behavior and actual behavior:
When reading a timestamp column from [presto](https://prestodb.io/), we would expect to get a `Field` with the data type `SQLDataType.TIMESTAMP`.
Instead, we get the following exception:
````
java.time.format.DateTimeParseException: Text '2017-05-24T00:00:00.000 UTC' could not be parsed at index 23
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	at java.time.OffsetDateTime.parse(OffsetDateTime.java:402)
	at java.time.OffsetDateTime.parse(OffsetDateTime.java:387)
	at org.jooq.impl.DefaultBinding.offsetDateTime(DefaultBinding.java:1522)
	at org.jooq.impl.DefaultBinding.get(DefaultBinding.java:1362)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1640)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.operate(CursorImpl.java:1611)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.operate(CursorImpl.java:1576)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:128)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchOne(CursorImpl.java:1540)
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1507)
````
Note that our application architecture does not allow to use the ORM features of jOOQ, we simply use `DSL.using(connection, SETTINGS).fetchLazy(query)`.

### Steps to reproduce the problem:
Using a stock presto installation, issue the following query:
````sql
SELECT parse_datetime('2017-05-24 00:00:00;+00:00','yyyy-MM-dd HH:mm:ss;ZZ') AS some_timestamp;
````

When issuing the statement above against the presto CLI, one gets the following result:
```` 
       some_timestamp
-----------------------------
 2017-05-24 00:00:00.000 UTC
(1 row)

Query 20170915_100202_00235_ry3mj, FINISHED, 1 node
Splits: 3 total, 3 done (100.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]
````

### Versions:
- jOOQ: 3.8.3
- Database (include vendor): prestodb 0.150
- JDBC Driver (include name if inofficial driver): prestodb 0.150

**Comment by lukaseder** [comment]
Thank you very much for your report. While prestodb is not explicitly supported by jOOQ, this particular case might be recurring in other databases, and straightforward enough to implement a generic workaround for. In particular, this looks quite similar to an existing Oracle problem: #5662.

The workaround would be to convert the data type to an offset timestamp, such as `2017-05-24 00:00:00.0+00.00`

**Comment by lukaseder** [comment]
Would you mind trying this with the version 3.10-SNAPSHOT (built from GitHub) or even 3.9.5? This seems to work for me. We have implemented quite a few improvements in the recent months, related to the lenient parsing of such timestamps...

**Comment by schroenser** [comment]
Sorry, since result streaming is an integral part of our application, we decided to fall back to the `java.sql.ResultSet` and wrap that into a `java.util.stream.Stream` ourselves. We still use jOOQ for dynamic query building, but I can't switch back to jOOQ's `fetchLazy` at this point. But thank you for checking this out.
