### ISSUE TITLE
Avoid creating a new DefaultConfiguration in DSL.select() and similar methods

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6683]
Currently, `DSL.select()` and similar methods create attached queries by instantiating an empty `DefaultConfiguration`. This generates quite some GC pressure that would not really be necessary, probably.

There are two options to solve this:

1. Create a global `Configuration` that acts as a default configuration. This global configuration must either be immutable, or proxy to an actual `Configuration`, clone itself as soon as someone tries to change it.
2. The queries could be unattached. In principle, this is allowed, and probably preferred here. Let's check for possible side-effects.

**Comment by Allsimon** [comment]
We are using the `insertInto(...).valuesOfRecords(...)` a lot in our application like this:

```java
List<Dto> someDtos;

var records = someDtos.stream().map(dto -> new FooRecord(dto.foo(), dto.bar())).toList();

jooq.insertInto(table, table.fields()).valuesOfRecords(records)
    .onConflictDoNothing()
    .execute();
```

The `new XXXRecord(...)` method is very expensive and amounts to around 20% of our memory allocations

The allocations are caused by this method: https://github.com/jOOQ/jOOQ/blob/467f91a6efc132fba662853466c8b9ae1e686ce0/jOOQ/src/main/java/org/jooq/impl/AbstractRecord.java#L451

When creating a new Record `setting(this)` will return null, so it will create a new DefaultConfiguration for every DTOs, then clone the Settings (twice 😢 )

**Comment by lukaseder** [comment]
Thanks a lot for your comment, @Allsimon. Can you please create a new issue? This here is mainly about `DSL` methods (`DSL.select()`, vs `DSLContext.select()`). Any potential fix will probably be different from the one in your case, where you call `new XYZRecord()`.

Note, as a workaround you can call `jooq.newRecord(FOO)` to create a `FooRecord` that is attached to the `Configuration` from `jooq`.

**Comment by lukaseder** [comment]
> then clone the Settings (twice 😢 )

I'm particularly interested in this, any call stacks / profiling session output that you could provide would be very helpful.

**Comment by lukaseder** [comment]
Even when omitting execution and rendering only, I can't see any hotspot with the creation of records or attachment:

<img width="551" alt="image" src="https://user-images.githubusercontent.com/734593/233073834-4f9b0fe0-f3ad-4693-a429-1c71f3f6c821.png">

Obviously, there's always safepoint bias with such simple profiling sessions, but given your 20% allocation claim, I would have expected more significant impact here?

The `Settings` do appear in the allocation profile, though.

<img width="671" alt="image" src="https://user-images.githubusercontent.com/734593/233074317-aee3e9e5-70dd-4cf0-a8bb-9eb2abbd33d9.png">

So, I'll continue investigating.

**Comment by lukaseder** [comment]
OK, so just printing a stacktrace from  `SettingsTools::clone` shows that indeed, this call stack appears quite a few times in a loop:

```java
java.lang.Throwable
	at org.jooq.conf.SettingsBase.clone(SettingsBase.java:59)
	at org.jooq.conf.Settings.clone(Settings.java:1)
	at org.jooq.conf.SettingsTools.clone(SettingsTools.java:375)
	at org.jooq.impl.DefaultConfiguration.set(DefaultConfiguration.java:1522)
	at org.jooq.impl.DefaultConfiguration.<init>(DefaultConfiguration.java:327)
	at org.jooq.impl.DefaultConfiguration.<init>(DefaultConfiguration.java:212)
	at org.jooq.impl.DefaultConfiguration.<init>(DefaultConfiguration.java:174)
	at org.jooq.impl.DefaultConfiguration.<init>(DefaultConfiguration.java:164)
	at org.jooq.impl.DSL.dsl(DSL.java:34019)
	at org.jooq.impl.DSL.select(DSL.java:3239)
	at org.jooq.impl.FieldMapsForInsert.insertSelect(FieldMapsForInsert.java:392)
	at org.jooq.impl.InsertQueryImpl.acceptMerge0(InsertQueryImpl.java:923)
	at org.jooq.impl.InsertQueryImpl.lambda$19(InsertQueryImpl.java:904)
	at org.jooq.impl.AbstractContext.toggle(AbstractContext.java:393)
	at org.jooq.impl.AbstractContext.data(AbstractContext.java:404)
	at org.jooq.impl.InsertQueryImpl.acceptMerge(InsertQueryImpl.java:904)
	at org.jooq.impl.InsertQueryImpl.accept0(InsertQueryImpl.java:627)
	at org.jooq.impl.AbstractDMLQuery.accept(AbstractDMLQuery.java:673)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:350)
	at org.jooq.impl.DefaultDSLContext.render(DefaultDSLContext.java:734)
	at org.jooq.impl.AbstractAttachableQueryPart.getSQL(AbstractAttachableQueryPart.java:121)
	at org.jooq.impl.AbstractAttachableQueryPart.getSQL(AbstractAttachableQueryPart.java:114)
	at org.jooq.impl.AbstractDelegatingQuery.getSQL(AbstractDelegatingQuery.java:95)
	at org.jooq.test.benchmarks.local.ValuesOfRecordsBenchmark.valuesOfRecords(ValuesOfRecordsBenchmark.java:68)
	at org.jooq.test.benchmarks.local.ValuesOfRecordsBenchmark.main(ValuesOfRecordsBenchmark.java:77)
```

This is caused by internal usages of `DSL.select()`, which is indeed the issue description here, so no new issue will be needed.

**Comment by lukaseder** [comment]
So, indeed, when avoiding the creation of new `DefaultConfiguration` instances, we can get from this performance of a benchmark:

```java
ValuesOfRecordsBenchmark.valuesOfRecords  thrpt    7  1017.603 ┬▒ 14.404  ops/s
```

To this one:

```java
ValuesOfRecordsBenchmark.valuesOfRecords  thrpt    7  1143.818 ┬▒ 3.663  ops/s
```

The actual number of ops/s isn't relevant (the benchmark generates tons of SQL), but the percentage change is.

The reason new objects are being created is mostly because neither `Configuration`, nor `Settings` are immutable, so if we use a global object, then there might be very subtle bugs if someone changes `Configuration` or `Settings` randomly. Specifically, in the case of `Settings`, there's an ancient feature where users can load their global default settings from a `/jooq-settings.xml` file, so we can't just assume defaults.

I'm not sure if we can make `Configuration` unmodifiable easily (there's a feature request for this: https://github.com/jOOQ/jOOQ/issues/13079), but perhaps we can make a specific immutable `Settings` object, which we never have to clone. That would probably take away most of the GC pressure you're seeing.

**Comment by lukaseder** [comment]
While this issue is about avoiding creating new `DefaultConfiguration` (which may be tricky), I'll try to investigate first if we can just avoid the `clone()` call by adding a new global default `Settings` reference, which we make unmodifiable: https://github.com/jOOQ/jOOQ/issues/14959

**Comment by lukaseder** [comment]
Interesting remark also about the 2 consecutive clone calls. That can be avoided very easily, without any regression risk: https://github.com/jOOQ/jOOQ/issues/14960 (the more thorough fix of #14959 might be harder, and more difficult to backport).

**Comment by loicmathieu** [comment]
I opened #20104, which seems related; cloning Settings shows 5% memory allocation on a performance benchmark profile.
