### ISSUE TITLE
jOOQ-scala 2.11 cannot be built with JDK 9

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6733]
Probably a Scala compiler bug, see: https://github.com/scala/scala-dev/issues/139#issuecomment-338169134

The error as can be seen in this travis build https://travis-ci.org/jOOQ/jOOQ/jobs/290369630 is:

```
Downloaded: http://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.11.6/scala-library-2.11.6.pom (1.4 kB at 62 kB/s)
[[1;31mERROR[m] error: scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
[[1;31mERROR[m] 	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
[[1;31mERROR[m] 	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
[[1;34mINFO[m] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:53)
[[1;34mINFO[m] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
[[1;34mINFO[m] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
[[1;34mINFO[m] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:66)
[[1;34mINFO[m] 	at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:102)
[[1;34mINFO[m] 	at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:105)
[[1;34mINFO[m] 	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:257)
[[1;34mINFO[m] 	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:257)
[[1;34mINFO[m] 	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1390)
[[1;34mINFO[m] 	at scala.tools.nsc.Global$Run.<init>(Global.scala:1242)
[[1;34mINFO[m] 	at scala.tools.nsc.Driver.doCompile(Driver.scala:31)
[[1;34mINFO[m] 	at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
[[1;34mINFO[m] 	at scala.tools.nsc.Driver.process(Driver.scala:51)
[[1;34mINFO[m] 	at scala.tools.nsc.Driver.main(Driver.scala:64)
[[1;34mINFO[m] 	at scala.tools.nsc.Main.main(Main.scala)
[[1;34mINFO[m] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[[1;34mINFO[m] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[[1;34mINFO[m] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[[1;34mINFO[m] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[[1;34mINFO[m] 	at org_scala_tools_maven_executions.MainHelper.runMain(MainHelper.java:161)
[[1;34mINFO[m] 	at org_scala_tools_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
```

**Comment by lukaseder** [comment]
This seems to be fixed by upgrading the Scala dependency to 2.11.12
