### ISSUE TITLE
INSERT .. ON DUPLICATE KEY .. RETURNING .. Fails with fetchOne() on MySQL

### ISSUE THREAD

**Issue by billoneil** [jOOQ/jOOQ#6764]
### Expected behavior and actual behavior:
I followed the workaround here https://github.com/jOOQ/jOOQ/issues/2123#issuecomment-308343505. When calling `fetchOne` an exception is thrown when a single row is updated in MySQL.

`fetchOne` will throw an exception [here](https://github.com/jOOQ/jOOQ/blob/master/jOOQ/src/main/java/org/jooq/impl/InsertImpl.java#L868) if the rows updated > 1. However MySQL does the following.

> With ON DUPLICATE KEY UPDATE, the affected-rows value per row is 1 if the row is inserted as a new row, 2 if an existing row is updated, and 0 if an existing row is set to its current values.

https://dev.mysql.com/doc/refman/5.7/en/insert-on-duplicate.html

### Steps to reproduce the problem:
Should be reproducible by calling insert on duplicate key update .. returning on the same data twice.

### Versions:

- jOOQ: 3.10.1
- Java: 8
- Database (include vendor): MySQL 5.7
- JDBC Driver (include name if inofficial driver): 

I would be happy to try and fix this but it seems like it might need some kind of hacky solution specifically for MySQL.

Work around is to call `fetch().get(0)` instead of `fetchOne()`

```java
InsertOnDuplicateSetStep<OfferRecord> q = ProductDaos.getProcessing().create()
    .insertInto(offerTable,
        offerTable.MERCHANT_ID,
        offerTable.UNIQUE_HASH,
        offerTable.TITLE,
        offerTable.ACTIVE,
        offerTable.DESCRIPTION
    ).values(
        val(merchantId),
        val(hash),
        val(offer.getTitle()),
        val(offer.isActive()),
        val(offer.getDescription())
    ).onDuplicateKeyUpdate()
     .set(offerTable.TITLE, offer.getTitle())
     .set(offerTable.ACTIVE, offer.isActive())
     .set(offerTable.DESCRIPTION, offer.getDescription());
    // https://github.com/jOOQ/jOOQ/issues/2123#issuecomment-308343505
OfferRecord record = ((InsertReturningStep<OfferRecord>) q).returning(offerTable.OFFER_ID).fetch().get(0);
```

**Comment by lukaseder** [comment]
Thank you very much for your report. I'll look into is soon

**Comment by billoneil** [comment]
It's not very critical since there is a pretty easy work around. I'd love to see how its fixed though since it might need to be special cased to only MySQL and only if its an insert on duplicate key query.

**Comment by lukaseder** [comment]
It took me a moment but I could reproduce a similar issue

```sql
CREATE TABLE t_identity_pk_uk (
  id INT NOT NULL AUTO_INCREMENT,
  val int,

  CONSTRAINT pk_t_identity_pk PRIMARY KEY (id),
  CONSTRAINT uk_t_identity_pk UNIQUE (val)
)
```

And the test:

```java
    @Test
    public void testMySQLInsertOnDuplicateKeyUpdateReturningWithIdentity() throws Exception {
        clean(T_IDENTITY_PK_UK);

        // [#6764] Testing if fetchOne() works with updates
        Integer id1;
        Integer id2;
        
        {
            Record r =
            create().insertInto(T_IDENTITY_PK_UK, T_IDENTITY_PK_UK.VAL)
                    .values(1)
                    .onDuplicateKeyUpdate()
                    .set(T_IDENTITY_PK_UK.VAL, 2)
                    .returning()
                    .fetchOne();

            id1 = create().select(max(T_IDENTITY_PK_UK.ID)).from(T_IDENTITY_PK_UK).fetchOneInto(int.class);
            assertEquals(id1, r.getValue(T_IDENTITY_PK_UK.ID));
            assertEquals(1, (int) r.getValue(T_IDENTITY_PK_UK.VAL));
            assertEquals(1, create().select(count()).from(T_IDENTITY_PK_UK).fetchOne(0));
        }

        {
            Record r =
            create().insertInto(T_IDENTITY_PK_UK, T_IDENTITY_PK_UK.VAL)
                    .values(2)
                    .onDuplicateKeyUpdate()
                    .set(T_IDENTITY_PK_UK.VAL, 3)
                    .returning()
                    .fetchOne();

            id2 = create().select(max(T_IDENTITY_PK_UK.ID)).from(T_IDENTITY_PK_UK).fetchOneInto(int.class);
            assertEquals(id2, r.getValue(T_IDENTITY_PK_UK.ID));
            assertEquals(2, (int) r.getValue(T_IDENTITY_PK_UK.VAL));
            assertEquals(2, create().select(count()).from(T_IDENTITY_PK_UK).fetchOne(0));
        }

        {
            Record r =
            create().insertInto(T_IDENTITY_PK_UK, T_IDENTITY_PK_UK.VAL)
                    .values(1)
                    .onDuplicateKeyUpdate()
                    .set(T_IDENTITY_PK_UK.VAL, 3)
                    .returning()
                    .fetchOne();

            assertEquals(id1, r.getValue(T_IDENTITY_PK_UK.ID));
            assertEquals(3, (int) r.getValue(T_IDENTITY_PK_UK.VAL));
            assertEquals(2, create().select(count()).from(T_IDENTITY_PK_UK).fetchOne(0));
        }
    }
```

The third query fails with:

```
org.jooq.exception.TooManyRowsException: Too many rows selected : 2
	at org.jooq.impl.Tools.filterOne(Tools.java:1692)
	at org.jooq.impl.InsertImpl.fetchOne(InsertImpl.java:893)
	at org.jooq.test.MySQLTest.testMySQLInsertOnDuplicateKeyUpdateReturningWithIdentity(MySQLTest.java:1365)
```

I've traced this down to a bug in the MySQL JDBC driver (I'm using 8.0.11), where the `Statement.getGeneratedKeys()` call returns 2 rows (or more) instead of 1 when the rows are updated, not inserted:
https://github.com/jOOQ/jOOQ/blob/863ade3b3c7a004d477d54193ac5104435b9835b/jOOQ/src/main/java/org/jooq/impl/AbstractDMLQuery.java#L563

I can reproduce the problem with the following JDBC snippet, which illustrates the problem:

```java
try (Connection c = new com.mysql.cj.jdbc.Driver().connect(url, properties);
     Statement s = c.createStatement();
     PreparedStatement p = c.prepareStatement("INSERT INTO x (j) VALUES (?) ON DUPLICATE KEY UPDATE j = 3", Statement.RETURN_GENERATED_KEYS)) {
    try {
        s.execute("CREATE TABLE IF NOT EXISTS x (i INT AUTO_INCREMENT PRIMARY KEY, j INT UNIQUE)");

        p.setInt(1, 1);
        System.out.println("Statement 1:");
        System.out.println("------------");
        System.out.println("Rows: " + p.executeUpdate());
        try (ResultSet r = p.getGeneratedKeys()) {
            while (r.next())
                System.out.println("Key : " + r.getInt(1));
        }

        p.setInt(1, 2);
        System.out.println();
        System.out.println("Statement 2:");
        System.out.println("------------");
        System.out.println("Rows: " + p.executeUpdate());
        try (ResultSet r = p.getGeneratedKeys()) {
            while (r.next())
                System.out.println("Key : " + r.getInt(1));
        }

        p.setInt(1, 1);
        System.out.println();
        System.out.println("Statement 3:");
        System.out.println("------------");
        System.out.println("Rows: " + p.executeUpdate());
        try (ResultSet r = p.getGeneratedKeys()) {
            while (r.next())
                System.out.println("Key : " + r.getInt(1));
        }
    }
    finally {
        s.execute("DROP TABLE IF EXISTS x");
    }
}
```

When I run the above, I get:

```
Statement 1:
------------
Rows: 1
Key : 1

Statement 2:
------------
Rows: 1
Key : 2

Statement 3:
------------
Rows: 2
Key : 1
Key : 2 -- This is the problem!
```

It seems that this problem only happens with prepared statements, not with static statements.

I've filed an issue to MySQL:
https://bugs.mysql.com/bug.php?id=90688

**Comment by lukaseder** [comment]
We can't do much on the jOOQ side. The JDBC API must be implemented correctly, otherwise, it's hard to guess what the meaning of the results are.

**Comment by welkinbai** [comment]
same question. follow https://bugs.mysql.com/bug.php?id=90688. If JOOQ call `execute()` instead of `executeUpdate()` could solve this problem?

**Comment by lukaseder** [comment]
@welkinbai Thanks for the update. I had not seen that additional comment on the MySQL tracker. We could try that, we tend to call `execute()` instead of `executeUpdate()` on the base `AbstractQuery` type, since we don't necessarily know if any results are produced.

I'll try reproducing this again, and see if calling `execute()` fixes things without introducing new regressions.
