### ISSUE TITLE
Code generator doesn't work when Derby database uses non-standard collation

### ISSUE THREAD

**Issue by SwingGuy1024** [jOOQ/jOOQ#6797]
### Expected behavior and actual behavior:
I expect it to generate files according to my library.xml file. Instead, it generates this error message:

WARNING: SQL exception            : Exception while executing meta query: Comparisons between 'VARCHAR (UCS_BASIC)' and 'VARCHAR (TERRITORY_BASED:PRIMARY)' are not supported. Types must be comparable. String types must also have matching collation. If collation does not match, a possible solution is to cast operands to force them to the default collation (e.g. SELECT tablename FROM sys.systables WHERE CAST(tablename AS VARCHAR(128)) = 'T1')

Please report this bug here: https://github.com/jOOQ/jOOQ/issues/new

```sql
select 
  "SYS"."SYSSCHEMAS"."SCHEMANAME", 
  "SYS"."SYSTABLES"."TABLENAME", 
  "SYS"."SYSTABLES"."TABLEID"
from "SYS"."SYSTABLES"
  join "SYS"."SYSSCHEMAS"
  on "SYS"."SYSTABLES"."SCHEMAID" = "SYS"."SYSSCHEMAS"."SCHEMAID"
where "SYS"."SYSSCHEMAS"."SCHEMANAME" in (
  'APP', 'NULLID', 'SQLJ', 'SYS', 'SYSCAT', 'SYSCS_DIAG', 'SYSCS_UTIL', 'SYSFUN', 
  'SYSIBM', 'SYSPROC', 'SYSSTAT'
)
order by 
  "SYS"."SYSSCHEMAS"."SCHEMANAME", 
  "SYS"."SYSTABLES"."TABLENAME"
```

```
Nov 07, 2017 11:30:26 PM org.jooq.tools.JooqLogger error
SEVERE: Error while fetching tables
org.jooq.exception.DataAccessException: SQL [select "SYS"."SYSSCHEMAS"."SCHEMANAME", "SYS"."SYSTABLES"."TABLENAME", "SYS"."SYSTABLES"."TABLEID" from "SYS"."SYSTABLES" join "SYS"."SYSSCHEMAS" on "SYS"."SYSTABLES"."SCHEMAID" = "SYS"."SYSSCHEMAS"."SCHEMAID" where "SYS"."SYSSCHEMAS"."SCHEMANAME" in (cast(? as varchar(32672)), cast(? as varchar(32672)), cast(? as varchar(32672)), cast(? as varchar(32672)), cast(? as varchar(32672)), cast(? as varchar(32672)), cast(? as varchar(32672)), cast(? as varchar(32672)), cast(? as varchar(32672)), cast(? as varchar(32672)), cast(? as varchar(32672))) order by "SYS"."SYSSCHEMAS"."SCHEMANAME", "SYS"."SYSTABLES"."TABLENAME"]; Comparisons between 'VARCHAR (UCS_BASIC)' and 'VARCHAR (TERRITORY_BASED:PRIMARY)' are not supported. Types must be comparable. String types must also have matching collation. If collation does not match, a possible solution is to cast operands to force them to the default collation (e.g. SELECT tablename FROM sys.systables WHERE CAST(tablename AS VARCHAR(128)) = 'T1')
	at org.jooq_3.10.0.DERBY.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2199)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:677)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:358)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:314)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2594)
	at org.jooq.util.derby.DerbyDatabase.getTables0(DerbyDatabase.java:294)
	at org.jooq.util.AbstractDatabase.getTables(AbstractDatabase.java:1388)
	at org.jooq.util.JavaGenerator.generateSchemaIfEmpty(JavaGenerator.java:364)
	at org.jooq.util.JavaGenerator.generateCatalogIfEmpty(JavaGenerator.java:350)
	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:324)
	at org.jooq.util.GenerationTool.run(GenerationTool.java:639)
	at org.jooq.util.GenerationTool.generate(GenerationTool.java:200)
	at org.jooq.util.GenerationTool.main(GenerationTool.java:172)
Caused by: java.sql.SQLSyntaxErrorException: Comparisons between 'VARCHAR (UCS_BASIC)' and 'VARCHAR (TERRITORY_BASED:PRIMARY)' are not supported. Types must be comparable. String types must also have matching collation. If collation does not match, a possible solution is to cast operands to force them to the default collation (e.g. SELECT tablename FROM sys.systables WHERE CAST(tablename AS VARCHAR(128)) = 'T1')
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement42.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver42.newEmbedPreparedStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.jooq.impl.ProviderEnabledConnection.prepareStatement(ProviderEnabledConnection.java:106)
	at org.jooq.impl.SettingsEnabledConnection.prepareStatement(SettingsEnabledConnection.java:70)
	at org.jooq.impl.AbstractResultQuery.prepare(AbstractResultQuery.java:230)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:316)
	... 10 more
Caused by: ERROR 42818: Comparisons between 'VARCHAR (UCS_BASIC)' and 'VARCHAR (TERRITORY_BASED:PRIMARY)' are not supported. Types must be comparable. String types must also have matching collation. If collation does not match, a possible solution is to cast operands to force them to the default collation (e.g. SELECT tablename FROM sys.systables WHERE CAST(tablename AS VARCHAR(128)) = 'T1')
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.compile.ValueNodeList.comparable(Unknown Source)
	at org.apache.derby.impl.sql.compile.BinaryListOperatorNode.bindComparisonOperator(Unknown Source)
	at org.apache.derby.impl.sql.compile.BinaryListOperatorNode.bindExpression(Unknown Source)
	at org.apache.derby.impl.sql.compile.SelectNode.bindExpressions(Unknown Source)
	at org.apache.derby.impl.sql.compile.DMLStatementNode.bindExpressions(Unknown Source)
	at org.apache.derby.impl.sql.compile.DMLStatementNode.bind(Unknown Source)
	at org.apache.derby.impl.sql.compile.CursorNode.bindStatement(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
	... 19 more
```

### Steps to reproduce the problem:
I created a database with the following URLs. (There are two because I tried it both ways.)

```java
    String url = "jdbc:derby:skeleton;create=true;collation=TERRITORY_BASED:PRIMARY";
    String url = "jdbc:derby:skeleton2;create=true";
```

The database that I created this way works fine. I can save and load records. When I try to generate jOOQ source files for my tables, I get the error message above. Here's the library.xml file for the 2nd url above:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<configuration xmlns="http://www.jooq.org/xsd/jooq-codegen-3.10.0.xsd">
	<!-- Configure the database connection here -->
	<jdbc>
		<driver>org.apache.derby.jdbc.EmbeddedDriver</driver>
		<url>jdbc:derby:skeleton2;create=true;collation=TERRITORY_BASED:PRIMARY</url>
		<!--user and password are presumably not needed since we're embedded.-->
		<!--<user>root</user>-->
		<!--<password></password>-->
	</jdbc>

	<generator>
		<name>org.jooq.util.JavaGenerator</name>

		<database>
			<name>org.jooq.util.derby.DerbyDatabase</name>
			
			<!--I tried it both with and without these properties, which, frankly were a guess. 
			It failed both ways with the same message.-->
			<properties>
				<property>
					<key>collation</key>
					<value>TERRITORY_BASED:PRIMARY</value>
				</property>
			</properties>

			<!-- The database schema (or in the absence of schema support, in your RDBMS this
					 can be the owner, user, database name) to be generated -->
			<!-- This seems to be unnecessary and counterproductive in a Derby embedded DB -->
			<!--<inputSchema>skeleton2</inputSchema>-->

			<includes>.*</includes>

			<excludes></excludes>
		</database>

		<target>
			<!-- The destination package of your generated classes (within the destination directory) -->
			<packageName>com.neptunedreams.skeleton.data2</packageName>

			<!-- The destination directory of your generated classes. Using Maven directory layout here -->
			<directory>/Users/miguelmunoz/Documents/Skeleton2/src/main/java</directory>
		</target>
	</generator>
</configuration>
```

### Versions:

- jOOQ: 3.10.0
- Java: 1.8.0_77
- Database (include vendor): Derby embedded 10.14.1.0
- JDBC Driver (include name if inofficial driver): org.apache.derby.jdbc.EmbeddedDriver

**Comment by lukaseder** [comment]
Thank you very much for your detailed report. We'll look into this ASAP

**Comment by SwingGuy1024** [comment]
I was able to get that sql statement to work by changing it to this:

select "SYS"."SYSSCHEMAS"."SCHEMANAME", "SYS"."SYSTABLES"."TABLENAME", "SYS"."SYSTABLES"."TABLEID" from "SYS"."SYSTABLES" join "SYS"."SYSSCHEMAS" on "SYS"."SYSTABLES"."SCHEMAID" = "SYS"."SYSSCHEMAS"."SCHEMAID" where **cast(**"SYS"."SYSSCHEMAS"."SCHEMANAME" **as varchar(32672))** in (cast(? as varchar(32672)), cast(? as varchar(32672)), cast(? as varchar(32672)), cast(? as varchar(32672)), cast(? as varchar(32672)), cast(? as varchar(32672)), cast(? as varchar(32672)), cast(? as varchar(32672)), cast(? as varchar(32672)), cast(? as varchar(32672)), cast(? as varchar(32672))) order by "SYS"."SYSSCHEMAS"."SCHEMANAME", "SYS"."SYSTABLES"."TABLENAME"

**Comment by Miguel-mGage** [comment]
In my previous comment, I put the new code in bold face. (Looking at the code above, I don't notice the text in boldface unless I'm looking for it.)

**Comment by lukaseder** [comment]
Thanks for the hint. No worries about the bold face, the idea is clear. I'm looking into a solution right now...

**Comment by lukaseder** [comment]
I can reproduce the problem when I *create* the database on a connection that uses the aforementioned collation. In that case, it doesn't matter how I connect to the database, the error appears.

If I *create* the database without any specific collation, then it doesn't matter how I connect to it.

**Comment by lukaseder** [comment]
I couldn't find any better way to solve this than indeed cast the column references to a `varchar(32672)` type. It doesn't matter if the bind variable is cast or not, or even if we're using inline values. Truly a weird Derby feature... What's your use-case for using it?

**Comment by lukaseder** [comment]
Fixed on master for jOOQ 3.11. Will be merged to 3.10.2 (#6848) and 3.9.7 (#6849)

**Comment by SwingGuy1024** [comment]
Here's my use-case. I want my wildcard searches to be case insensitive. If I use the default collation, Derby's wildcard searches are case-sensitive, which makes them pretty useless. Hence, the specified collation. Why Derby thought the default should be case-sensitive is a mystery. My guess is they did it for speed.

**Comment by lukaseder** [comment]
Hmm, many databases default to collations that are case sensitive. In my experience, the few cases where insensitivity is desirable do not outnumber the many cases where case sensitivity is important. Think about base64 encoded hashes, for instance... So, mostly, I found it much more useful to specify a collation on a per-column basis, especially because of the implications that could arise for third party tools, as could be seen here.

Anyway, it's good to know that this can be a use-case. Future jOOQ versions will get this right for both cases.
