### ISSUE TITLE
SQLDialectNotSupportedException while using WEEKDAY function

### ISSUE THREAD

**Issue by jpomykala** [jOOQ/jOOQ#6952]
### Expected behavior and actual behavior:
Expected: get row grouped by week day
Actual: 
```
org.jooq.exception.SQLDialectNotSupportedException: Type class org.jooq.impl.TableFieldImpl is not supported in dialect DEFAULT
	at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:840) ~[jooq-3.9.6.jar:na]
	at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:784) ~[jooq-3.9.6.jar:na]
	at org.jooq.impl.DSL.getDataType(DSL.java:18664) ~[jooq-3.9.6.jar:na]
	at org.jooq.impl.DSL.val(DSL.java:16503) ~[jooq-3.9.6.jar:na]
	at org.jooq.impl.DSL.inline(DSL.java:15736) ~[jooq-3.9.6.jar:na]
```

### Steps to reproduce the problem:
```
Field<Integer> groupByWeekDay = DSL.field("WEEKDAY({0})", Integer.class, DSL.inline(TRANSACTION.CREATED));
//context.configuration() is set to mysql dialect properly 
	context
	.select(count(TRANSACTION.ID).as("uses"), groupByWeekDay.as("groupByValue"))
	.from(TRANSACTION)
	.groupBy(groupByWeekDay)
	.fetch();
```

`created` column is `datetime` type

### Versions:
- jOOQ: 3.9.6
- Java: 8
- Database (include vendor): MySQL 5.7.20

**Comment by lukaseder** [comment]
Thanks for your report. This is probably due to a misunderstanding of what `DSL.inline()` does. The solution is to remove that call and write the following instead:

```java
Field<Integer> groupByWeekDay = DSL.field("WEEKDAY({0})", Integer.class, TRANSACTION.CREATED);
```

More information about `DSL.inline()` can be found here:
https://www.jooq.org/doc/latest/manual/sql-building/bind-values/inlined-parameters/
