### ISSUE TITLE
DDLDatabase fails with MySQL DATETIME columns

### ISSUE THREAD

**Issue by anuraaga** [jOOQ/jOOQ#7021]
Parser seems to not handle DATETIME (error even after removing the `(6)`)

JOOQ 3.10.3

```
org.jooq.impl.ParserException: C42000_NO_SUBCLASS: Expected tokens: [AUTOINCREMENT, AUTO_INCREMENT, CHECK, DATE, DECIMAL, DEFAULT, DOUBLE, DOUBLE PRECISION, GENERATED, PRIMARY KEY, UNIQUE]: satellite_id BIGINT UNSIGNED NOT NULL,
  aos_time [*]DATETIME(6) NOT NULL,
  los_time DATETIME(6) NOT NULL,
  deleted TINYINT DEFAULT
        at org.jooq.impl.ParserImpl$ParserContext.unexpectedToken(ParserImpl.java:5791)
        at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:547)
        at org.jooq.impl.ParserImpl.parse(ParserImpl.java:345)
        at org.jooq.impl.ParserImpl.parse(ParserImpl.java:337)
        at org.jooq.util.ddl.DDLDatabase.create0(DDLDatabase.java:124)
        at org.jooq.util.AbstractDatabase.create(AbstractDatabase.java:237)
        at org.jooq.util.AbstractDatabase.create(AbstractDatabase.java:226)
        at org.jooq.util.AbstractDatabase.getDialect(AbstractDatabase.java:208)
        at org.jooq.util.AbstractGenerator.logDatabaseParameters(AbstractGenerator.java:131)
        at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:271)
        at org.jooq.util.GenerationTool.run(GenerationTool.java:642)
        at org.jooq.util.GenerationTool.generate(GenerationTool.java:203)
        at org.jooq.util.GenerationTool.main(GenerationTool.java:175)
  ```

**Comment by anuraaga** [comment]
Thanks for all the fixes last week! Noticed this is probably the last issue that I can't work around with forced types, so sent a PR it :)
