### ISSUE TITLE
onDuplicateKeyUpdate not considered in MariaDB

### ISSUE THREAD

**Issue by obirider** [jOOQ/jOOQ#7083]
### Expected behavior and actual behavior:

Column "key" is the primarykey of the table "Settings":
```
CREATE TABLE `Settings` (
  `key` varchar(64) COLLATE utf8mb4_bin NOT NULL,
  `value` varchar(2048) COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
```

This statement
```
            create() 
                .insertInto(SETTINGS, SETTINGS.KEY, SETTINGS.VALUE)
                .values("ORDERING_ACTIVATED", "false")
                .onDuplicateKeyUpdate()
                .set(SETTINGS.VALUE, "false")
                .execute();
```
throws following exception:
```
org.jooq.exception.DataAccessException: SQL [insert into `xxx`.`Settings` (`key`, `value`) values (?, ?)]; (conn=27) Duplicate entry 'ORDERING_ACTIVATED' for key 'PRIMARY'
        at org.jooq_3.10.4.MARIADB.debug(Unknown Source) ~[na:na]
        at org.jooq.impl.Tools.translate(Tools.java:2239) ~[jooq-3.10.4.jar:na]
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:704) ~[jooq-3.10.4.jar:na]
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:361) ~[jooq-3.10.4.jar:na]
        at org.jooq.impl.TableRecordImpl.storeInsert0(TableRecordImpl.java:197) ~[jooq-3.10.4.jar:na]
        at org.jooq.impl.TableRecordImpl$1.operate(TableRecordImpl.java:168) ~[jooq-3.10.4.jar:na]
        at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:125) ~[jooq-3.10.4.jar:na]
        at org.jooq.impl.TableRecordImpl.storeInsert(TableRecordImpl.java:164) ~[jooq-3.10.4.jar:na]
        at org.jooq.impl.UpdatableRecordImpl.store0(UpdatableRecordImpl.java:193) ~[jooq-3.10.4.jar:na]
        at org.jooq.impl.UpdatableRecordImpl.access$000(UpdatableRecordImpl.java:83) ~[jooq-3.10.4.jar:na]
        at org.jooq.impl.UpdatableRecordImpl$1.operate(UpdatableRecordImpl.java:133) ~[jooq-3.10.4.jar:na]
        at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:125) ~[jooq-3.10.4.jar:na]
        at org.jooq.impl.UpdatableRecordImpl.store(UpdatableRecordImpl.java:129) ~[jooq-3.10.4.jar:na]
        at org.jooq.impl.UpdatableRecordImpl.store(UpdatableRecordImpl.java:121) ~[jooq-3.10.4.jar:na]
...
Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=27) Duplicate entry 'ORDERING_ACTIVATED' for key 'PRIMARY'
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:171) ~[mariadb-java-client-2.2.0.jar:na]
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:110) ~[mariadb-java-client-2.2.0.jar:na]
        at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:235) ~[mariadb-java-client-2.2.0.jar:na]
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:224) ~[mariadb-java-client-2.2.0.jar:na]
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159) ~[mariadb-java-client-2.2.0.jar:na]
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeUpdate(MariaDbPreparedStatementClient.java:192) ~[mariadb-java-client-2.2.0.jar:na]
        at org.jooq.tools.jdbc.DefaultPreparedStatement.executeUpdate(DefaultPreparedStatement.java:99) ~[jooq-3.10.4.jar:na]
        at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:517) ~[jooq-3.10.4.jar:na]
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:347) ~[jooq-3.10.4.jar:na]
        ... 93 common frames omitted
Caused by: java.sql.SQLException: Duplicate entry 'ORDERING_ACTIVATED' for key 'PRIMARY'
Query is: insert into `xxx`.`Settings` (`key`, `value`) values (?, ?), parameters ['ORDERING_ACTIVATED','false']
        at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:153) ~[mariadb-java-client-2.2.0.jar:na]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:248) ~[mariadb-java-client-2.2.0.jar:na]
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:218) ~[mariadb-java-client-2.2.0.jar:na]
        ... 98 common frames omitted
```

### Versions:

- jOOQ: 3.10.4
- Java: 8
- Database (include vendor): MariaDB 10.3.2
- JDBC Driver (include name if inofficial driver): org.mariadb.jdbc.Driver

**Comment by obirider** [comment]
Sorry my fault!
There was another statement hidden in the code causing this error.

**Comment by lukaseder** [comment]
Thanks for the clarification, @obirider
