### ISSUE TITLE
Better SQLException chain handling

### ISSUE THREAD

**Issue by JanecekPetr** [jOOQ/jOOQ#7133]
### Expected behavior and actual behavior:
I'd hope that a SQLException thrown in a batch, when logged through something like `logger.error("DB error, bail!", e);`, would show the actual underlying error to help identify the problem. Instead, we get this:

```
org.jooq.exception.DataAccessException: SQL [insert into "public"."censored" ("censored") select ? where not exists (select 1 from "public"."censored" where "public"."censored"."censored" = ?)]; Batch entry 230 insert into "public"."censored" ("censored") select 'censored' where not exists (select 1 from "public"."censored" where "public"."censored"."censored" = 'censored') was aborted.  Call getNextException to see the cause.
	at org.jooq_3.10.0.POSTGRES_9_3.debug(Unknown Source) ~[?:?]
	at org.jooq.impl.Tools.translate(Tools.java:2199) ~[jooq-3.10.0.jar:?]
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:677) ~[jooq-3.10.0.jar:?]
	at org.jooq.impl.BatchSingle.executePrepared(BatchSingle.java:253) ~[jooq-3.10.0.jar:?]
	at org.jooq.impl.BatchSingle.execute(BatchSingle.java:176) ~[jooq-3.10.0.jar:?]
	at my.company.SomeClass.someMethod(SomeClass.java:311)
	at ...
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.sql.BatchUpdateException: Batch entry 230 insert into "public"."censored" ("censored") select 'censored' where not exists (select 1 from "public"."censored" where "public"."censored"."censored" = 'censored') was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2762) ~[postgresql-9.4-1201-jdbc4.jar:9.4]
	at org.postgresql.core.v3.QueryExecutorImpl$ErrorTrackingResultHandler.handleError(QueryExecutorImpl.java:362) ~[postgresql-9.4-1201-jdbc4.jar:9.4]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1999) ~[postgresql-9.4-1201-jdbc4.jar:9.4]
	at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1180) ~[postgresql-9.4-1201-jdbc4.jar:9.4]
	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1201) ~[postgresql-9.4-1201-jdbc4.jar:9.4]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:412) ~[postgresql-9.4-1201-jdbc4.jar:9.4]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2929) ~[postgresql-9.4-1201-jdbc4.jar:9.4]
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[HikariCP-2.7.2.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[HikariCP-2.7.2.jar:?]
	at org.jooq.tools.jdbc.DefaultStatement.executeBatch(DefaultStatement.java:97) ~[jooq-3.10.0.jar:?]
	at org.jooq.impl.BatchSingle.executePrepared(BatchSingle.java:233) ~[jooq-3.10.0.jar:?]
	... 36 more
```

Yes, knowing that the query failed and which query failed is important, but __I want to see if this was a syntax exception, a constraint violation (and which constraint!) or something else__.

This forces us to implement things like this:

```java
private static Throwable unwrapRootSqlException(Throwable t) {
    if (wrapsSqlException(t)) {
        SQLException sqlException = (SQLException)t.getCause();
        if (sqlException.getNextException() != null) {
            sqlException = sqlException.getNextException();
        }
        return sqlException;
    }
    return t;
}

private static boolean wrapsSqlException(Throwable t) {
    return (t instanceof DataAccessException) && (t.getCause() instanceof SQLException);
}
```

which is still not exactly safe nor correct, and has to plow through implementation deatils that we were exactly hoping to avoid by using jOOQ.

I can see how this is the intended behavior, it's just annoying having to deal with the JDBC layer directly as the API is so damn hard to use correctly.

Would you consider making `DataAccessException` somehow smarter to exatract this information on its own, or provide a method to do so?

### Steps to reproduce the problem:
Run a batch query with a constraint violation somewhere in it, try to log which constraint got assaulted. Cry in a corner as you forgot to specially handle the exception in the one single place where it was actually thrown.

### Versions:
- jOOQ: 3.10.1
- Java: 8u131
- Database (include vendor): Postgres 9.3
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.1.4

### Special remarks:
As always, thank you for your amazing work.

**Comment by lukaseder** [comment]
Thanks for your suggestion.

Unfortunately, we can't simply call `getNextException()` in all cases and on all drivers by default. Sometimes, this call is going to do a server round trip, which should be avoided by default.

However, you can easily implement an `ExecuteListener` as a workaround, and intercept the exception to do this yourself.

I'll think about your suggestion more thoroughly later.

**Comment by JanecekPetr** [comment]
>  call is going to do a server round trip

Oh. I had no idea. Let's close this then, there's nothing jOOQ can meaningfully do by default.
