### ISSUE TITLE
StackOverflowException when using except

### ISSUE THREAD

**Issue by lalithsuresh** [jOOQ/jOOQ#7236]
### Expected behavior and actual behavior:

I have two tables A and B, they have an identical schema. I want to do the following queries:

```java
String sql1 = "select * from A EXCEPT select * from B";
String sql2 = "select * from B EXCEPT select * from A";
```

This works if I use create.fetch(sql1) or create.fetch(sql2).

However, if I use the select().from().except() form, I get a StackOverflowException for the second query. In my test case, A is empty, and B has 10 rows.

```
Exception in thread "main" java.lang.StackOverflowError
	at java.lang.String.toUpperCase(String.java:2833)
	at org.jooq.impl.DefaultRenderContext.literal(DefaultRenderContext.java:368)
	at org.jooq.impl.DefaultRenderContext.literal(DefaultRenderContext.java:81)
	at org.jooq.impl.UnqualifiedName.accept(UnqualifiedName.java:74)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:415)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:423)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:184)
	at org.jooq.impl.TableImpl.accept0(TableImpl.java:210)
	at org.jooq.impl.TableImpl.accept(TableImpl.java:195)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:415)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:423)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:184)
	at org.jooq.impl.TableFieldImpl.accept(TableFieldImpl.java:92)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:415)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:385)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:184)
	at org.jooq.impl.QueryPartList.accept(QueryPartList.java:101)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:415)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:423)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:184)
	at org.jooq.impl.SelectQueryImpl.toSQLReference0(SelectQueryImpl.java:1135)
	at org.jooq.impl.SelectQueryImpl.toSQLReference0(SelectQueryImpl.java:978)
	at org.jooq.impl.SelectQueryImpl.toSQLReferenceLimitDefault(SelectQueryImpl.java:771)
	at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:612)

```

### Steps to reproduce the problem:

Test case with table A empty, and B having 10 rows. Each has two columns of integers with the names "colX1" and "colX2".
```

final SelectJoinStep<Record> recordsA = create.select().from(Tables.A);
final SelectJoinStep<Record> recordsB = create.select().from(Tables.B);
System.out.println(recordsA.fetch());
System.out.println(recordsB.fetch());
System.out.println(recordsA.except(recordsB).fetch());    // fine
System.out.println(recordsB.except(recordsA).fetch());    // Exception triggered here


```
```

+-----------+-----------+
|colX1|colX2|
+-----------+-----------+
+-----------+-----------+
|colX1|colX2|
+-----------+-----------+
|          1|          1|
|          2|          2|
|          3|          3|
|          4|          4|
|          5|          1|
|          6|          2|
|          7|          3|
|          8|          4|
|          9|          1|
+-----------+-----------+
+-----------+-----------+
|colX1|colX2|
+-----------+-----------+
Exception in thread "main" java.lang.StackOverflowError
	at java.lang.String.toUpperCase(String.java:2833)
	at org.jooq.impl.DefaultRenderContext.literal(DefaultRenderContext.java:368)
	at org.jooq.impl.DefaultRenderContext.literal(DefaultRenderContext.java:81)
	at org.jooq.impl.UnqualifiedName.accept(UnqualifiedName.java:74)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:415)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:423)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:184)
	at org.jooq.impl.TableImpl.accept0(TableImpl.java:210)
	at org.jooq.impl.TableImpl.accept(TableImpl.java:195)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:415)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:423)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:184)
	at org.jooq.impl.TableFieldImpl.accept(TableFieldImpl.java:92)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:415)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:385)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:184)
	at org.jooq.impl.QueryPartList.accept(QueryPartList.java:101)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:415)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:423)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:184)
	at org.jooq.impl.SelectQueryImpl.toSQLReference0(SelectQueryImpl.java:1135)
	at org.jooq.impl.SelectQueryImpl.toSQLReference0(SelectQueryImpl.java:978)
	at org.jooq.impl.SelectQueryImpl.toSQLReferenceLimitDefault(SelectQueryImpl.java:771)
	at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:612)

```
### Versions:

- jOOQ: 3.10.5
- Java: 1.8.0_101
- Database (include vendor): SQLite version 3.19.3
- OS: OSX High Sierra
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks for your report. This is due to a very regretful early decision to make the various DSL API `XYZStep` types mutable, rather than immutable. So, you're adding A to B and B to A, creating a cycle. A better solution would be:

```java
Select<Record> recordsA() {
  return create.select().from(Tables.A);
}
Select<Record> recordsB() {
  return create.select().from(Tables.B);
}

System.out.println(recordsA().fetch());
System.out.println(recordsB().fetch());
System.out.println(recordsA().except(recordsB()).fetch());    // fine
System.out.println(recordsB().except(recordsA()).fetch());    // Exception triggered here
```

Hope this helps
