### ISSUE TITLE
Add DSL.now() as a synonym for DSL.currentTimestamp()

### ISSUE THREAD

**Issue by jakubtutko** [jOOQ/jOOQ#7237]
### Expected behavior and actual behavior:

Hi, I'm trying to generate classes with `DDLDatabase` and I've noticed, that Postgres function `now()` for receiving current time is throwing `ParseException`.

### Steps to reproduce the problem:

Postgres SQL script:
```
CREATE SEQUENCE templates_id_seq;

CREATE TABLE template (
  id BIGINT PRIMARY KEY DEFAULT nextval('templates_id_seq') NOT NULL,
  created TIMESTAMP DEFAULT (now() AT TIME ZONE 'utc') NOT NULL
);
```

JOOQ error:
```
Feb 28, 2018 3:57:32 PM org.jooq.tools.JooqLogger error
SEVERE: Cannot read //build/tmp/jooq/config.xml. Error : Error while exporting schema
org.jooq.exception.DataAccessException: Error while exporting schema
        at org.jooq.util.ddl.DDLDatabase.create0(DDLDatabase.java:139)
        at org.jooq.util.AbstractDatabase.create(AbstractDatabase.java:234)
        at org.jooq.util.AbstractDatabase.create(AbstractDatabase.java:223)
        at org.jooq.util.AbstractDatabase.getDialect(AbstractDatabase.java:205)
        at org.jooq.util.AbstractGenerator.logDatabaseParameters(AbstractGenerator.java:128)
        at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:269)
        at org.jooq.util.GenerationTool.run(GenerationTool.java:639)
        at org.jooq.util.GenerationTool.generate(GenerationTool.java:200)
        at org.jooq.util.GenerationTool.main(GenerationTool.java:172)
Caused by: org.jooq.impl.ParserException: C42000_NO_SUBCLASS: Expected tokens: [!=, ::, <, <=, <=>, <>, =, >, >=, AND, BETWEEN, EXISTS, FALSE, IN, IS, LIKE, NEXT VALUE FOR, NOT, NULL, ON NULL, OR, TRUE, ||]: d_seq') NOT NULL,
  created TIMESTAMP DEFAULT (now[*]() AT TIME ZONE 'utc') NOT NULL
);
        at org.jooq.impl.ParserImpl$ParserContext.unexpectedToken(ParserImpl.java:5791)
        at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:547)
        at org.jooq.impl.ParserImpl.parse(ParserImpl.java:345)
        at org.jooq.impl.ParserImpl.parse(ParserImpl.java:337)
        at org.jooq.util.ddl.DDLDatabase.create0(DDLDatabase.java:119)
```

It's now working even without `AT TIME ZONE 'utc'`

### Versions:

- jOOQ: 3.10.4
- Java: 8
- Database (include vendor): Postgres
- OS: Ubuntu 17.10
- JDBC Driver (include name if inofficial driver): org.jooq.util.ddl.DDLDatabase

**Comment by lukaseder** [comment]
Thanks for your report. Good point - there are currently two missing features:

- Support for `now()`. Both in PostgreSQL and in MySQL, `now()` is essentially a synonym of `current_timestamp()`, so as a workaround you could use that instead. We'll implement support for `now()` nonetheless.
- Support for `AT TIME ZONE`. I've created a separate issue for this: #7238

**Comment by lukaseder** [comment]
This will be merged to 3.10.6: #7239

**Comment by jakubtutko** [comment]
@lukaseder thanks for fast response :slightly_smiling_face:. Meanwhile I was trying other statements and found out, that parser is not supporting postgres arrays as well.
```
CREATE TABLE template (
  id BIGINT PRIMARY KEY,
  fields VARCHAR[]
);
```
I've tried also dev version `3.11` and it's not supported there as well. Is it going to be supported or is there any workaround? Thanks.

**Comment by lukaseder** [comment]
Thanks for the pointer about array data types. That's a big oversight! I have added a bullet to the parser improvement ticket: #7171.

I don't think there's a workaround right now...

**Comment by lukaseder** [comment]
Array data types (PostgreSQL syntax) are now supported: https://github.com/jOOQ/jOOQ/commit/44ce8b3f23cc30c2e7400ad76e9502f59631286c

Let me know if you find any other missing features in the parser!

**Comment by jakubtutko** [comment]
Hi, thanks for insanely quick fix :slightly_smiling_face:. I haven't found any other missing features in the parser (except `JSON`, which will be supported in https://github.com/jOOQ/jOOQ/issues/7242).
