### ISSUE TITLE
NullPointerException in AbstractDMLQuery.execute()

### ISSUE THREAD

**Issue by naturefreshmilk** [jOOQ/jOOQ#7246]
I'm experiencing NullPointerExceptions after my application has started and run for some time, after 10 minutes up to 5 hours.

Setup:
* Raspberry PI 2 with custom Linux
* Docker with 2 Containers:
  * OpenJDK 8 with DB-Application
  * Postgresql Database

### Expected behavior and actual behavior:

Working inserts with `ctx.newRecord()` and `Record.insert()`

### Steps to reproduce the problem:

* Start DB and Application
* execute inserts and updates (max 50/s)
* wait some time (10 min to 5 hours)
* every query results now in an NPE on an unknown location

The failing logic (most of them look more or lessthe same):
```java
 NumbervalueRecord nv = ctx.newRecord(Numbervalue.NUMBERVALUE);
                                nv.setLogid(logId);
                                nv.setMetadataid(metadataId);
                                nv.setValue(value);
                                nv.insert();
```

The resulting Stack-Trace:
```
java.lang.NullPointerException: null                                                                                                                 
        at org.jooq_3.10.5.POSTGRES.debug(Unknown Source) ~[na:na]                                                                                   
        at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:661) ~[jooq-3.10.5.jar:na]                                                   
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:347) ~[jooq-3.10.5.jar:na]                                                         
        at org.jooq.impl.TableRecordImpl.storeInsert0(TableRecordImpl.java:197) ~[jooq-3.10.5.jar:na]                                                
        at org.jooq.impl.TableRecordImpl$1.operate(TableRecordImpl.java:168) ~[jooq-3.10.5.jar:na]                                                   
        at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:125) ~[jooq-3.10.5.jar:na]                                                       
        at org.jooq.impl.TableRecordImpl.storeInsert(TableRecordImpl.java:164) ~[jooq-3.10.5.jar:na]                                                 
        at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:152) ~[jooq-3.10.5.jar:na]                 
        at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:147) ~[jooq-3.10.5.jar:na]                                                      
        at io.rudin.arch.data.builder.LogBuilderImpl$BuilderImpl.withValue(LogBuilderImpl.java:145) ~[arch-data-impl-11.0.2-SNAPSHOT.jar:na]         
        at io.rudin.argus.schedule.ImuSchedule.execute(ImuSchedule.java:130) ~[argus-core-1.0-SNAPSHOT.jar:na]                
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.3.0.jar:na]                                                               
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.3.0.jar:na]  
```

I did some digging in the jooq-code, but the issue _seems_ to on this line:
* https://github.com/jOOQ/jOOQ/blob/a15218fee95b8a93edbb49123e626abd9b08f0df/jOOQ/src/main/java/org/jooq/impl/AbstractDMLQuery.java#L661

But i think there is an underlying issue to this, the jooq-code looks fine to me and should not result in an NPE:

```java
returned = new CursorImpl<R>(ctx2, listener2, fieldArray(returning), null, false, true).fetch();
// <---- lines omitted
 if (returned.size() > 0 || ctx.family() != HSQLDB) {
                result = returned.size();
                ctx.rows(result);
}
```

I've already tried the following:
* Enable tcpKeepAlive on the pgsql connection
* Set maxLifetime on the Connection-Pool to 60 seconds
* Set an initial connection script on the pool (select 1)
* Try/Catching on my code-side for more debug-logs

### Versions:

- jOOQ:3.10.5
- Java: OpenJDK 1.8.0_151 (armhf)
- Database (include vendor): Postgres 10.2  (Debian 10.2-1.pgdg90+1)
- OS: Linux/Buildroot  Kernel 4.13.16-v7
- Connection-Pool: HikariCP 2.7.8
- Docker: 17.05.0-ce
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.2.1

PS: I love jooq by the way, keep up the good work :smile: :+1:

**Comment by naturefreshmilk** [comment]
**Update:** I started testing with the Oracle VM instead of the OpenJDK provided by the debian repo.
The error did not show up again and it runs now smoothly since last friday (3 days)

Closing this, not an issue with jOOQ

**Comment by lukaseder** [comment]
Thanks for your nice words and for your report. I'm glad you've found a workaround for the issue. Something as non-deterministic as what you've described does sound scary, and I do hope jOOQ doesn't produce such non-deterministic behaviour :)
