### ISSUE TITLE
Parser should accept qualified field references in MERGE .. INSERT statement

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7263]
In some databases, it may be possible to qualify

```sql
MERGE INTO t
USING x
ON ...
WHEN NOT MATCHED THEN INSERT (t.a, t.b) -- Problem here
VALUES (x.a, x.b)
```

The parser currently rejects this syntax with the following exception:

```
org.jooq.impl.ParserException: Token ')' expected: [1:71] ...select 1) on 1 = 1 when not matched then insert (t[*].a) values (1)
	at org.jooq.impl.DefaultParseContext.expected(ParserImpl.java:15850)
	at org.jooq.impl.DefaultParseContext.parse(ParserImpl.java:14943)
	at org.jooq.impl.DefaultParseContext.parse(ParserImpl.java:14938)
	at org.jooq.impl.DefaultParseContext.parseMerge(ParserImpl.java:2658)
	at org.jooq.impl.DefaultParseContext.parseQuery(ParserImpl.java:1235)
	at org.jooq.impl.DefaultParseContext.lambda$4(ParserImpl.java:1004)
	at org.jooq.impl.DefaultParseContext.wrap(ParserImpl.java:16077)
	at org.jooq.impl.DefaultParseContext.parseQuery0(ParserImpl.java:1004)
	at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:815)
	at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:810)
	at org.jooq.impl.AbstractParserTest.lambda$14(AbstractParserTest.java:319)
	at org.jooq.impl.AbstractParserTest.additionalAssertions(AbstractParserTest.java:538)
	at org.jooq.impl.AbstractParserTest.assertQueryEquals(AbstractParserTest.java:319)
	at org.jooq.impl.ParserDMLStatementTest.testMergeWithQualifiedFieldIdentifiers(ParserDMLStatementTest.java:803)
```

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.12 (https://github.com/jOOQ/jOOQ/issues/17256)
- 3.18.19 (https://github.com/jOOQ/jOOQ/issues/17257)
- 3.17.28 (https://github.com/jOOQ/jOOQ/issues/17258)
