### ISSUE TITLE
Generating JOOQ-classes for CockroachDB fails when using PostgreSQLDatabase

### ISSUE THREAD

**Issue by codepitbull** [jOOQ/jOOQ#7270]
### Expected behavior and actual behavior:
Running **org.jooq.util.GenerationTool** against CockroachDB fails with the fol,lowing exception:
```
org.jooq.exception.DataAccessException: SQL [select 1 as "one" from "information_schema"."attributes" where 1 = 0]; ERROR: relation "information_schema.attributes" does not exist
	at org.jooq_3.10.5.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2239)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:704)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:361)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:317)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2597)
	at org.jooq.util.AbstractDatabase.exists(AbstractDatabase.java:326)
	at org.jooq.util.postgres.PostgresDatabase.getUDTs0(PostgresDatabase.java:709)
	at org.jooq.util.AbstractDatabase.getAllUDTs(AbstractDatabase.java:1648)
	at org.jooq.util.AbstractDatabase.getUDTs(AbstractDatabase.java:1679)
	at org.jooq.util.JavaGenerator.generateSchemaIfEmpty(JavaGenerator.java:367)
	at org.jooq.util.JavaGenerator.generateCatalogIfEmpty(JavaGenerator.java:352)
	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:326)
	at org.jooq.util.GenerationTool.run(GenerationTool.java:642)
	at org.jooq.util.GenerationTool.generate(GenerationTool.java:203)
	at org.jooq.util.GenerationTool.main(GenerationTool.java:175)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "information_schema.attributes" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2476)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2189)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:158)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:3248)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:262)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:347)
	... 12 common frames omitted
```

### Steps to reproduce the problem:
Get and install Cockroach v1.1.5.
Use the cockroach-commandline to execute **CREATE DATABASE vertx_test;**
After that run **org.jooq.util.GenerationTool** using the following jooq.xml (replace the ip-address used with yours):
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<configuration>
    <!-- Configure the database connection here -->
    <jdbc>
        <driver>org.postgresql.Driver</driver>
        <url>jdbc:postgresql://<IPADDRESS>:26257/</url>
        <user>root</user>
        <properties>
            <property><key>user</key><value>root</value></property>
        </properties>
    </jdbc>
    <generator>
        <database>
            <name>org.jooq.util.postgres.PostgresDatabase</name>
            <includes>.*</includes>
            <inputSchema>vertx_test</inputSchema>
        </database>
        <generate>
            <!-- Generation flags: See advanced configuration properties -->
        </generate>
        <target>
            <packageName>de.codepitbull.vertx.scala.jooq.tables</packageName>
            <directory>src/main/java</directory>
        </target>
    </generator>
</configuration>
```

Generation of the files can still be achieved by replacing **org.jooq.util.postgres.PostgresDatabase** with **org.jooq.util.jdbc.JDBCDatabase**.

### Versions:

- jOOQ: 3.10.5
- Java: 1.8.0_152
- Database (include vendor):CockroachDB 1.1.5
- OS: Mac OS X
- JDBC Driver (include name if inofficial driver): PostgreSQL Version 42.1.1

**Comment by lukaseder** [comment]
Thanks for your report.

What's your definition of "failing"? The exception is expected, jOOQ is checking if a given table exists in the catalog prior to running a query on it:
https://github.com/jOOQ/jOOQ/blob/version-3.10.5/jOOQ-meta/src/main/java/org/jooq/util/postgres/PostgresDatabase.java#L709

The existence check should fail silently:
https://github.com/jOOQ/jOOQ/blob/version-3.10.5/jOOQ-meta/src/main/java/org/jooq/util/AbstractDatabase.java#L326

How did you get the stack trace? From the debug log output?

In any case, that shouldn't be a reason why the code generation stops... Please let me know if there's anything else that could be improved...

**Comment by codepitbull** [comment]
There are no classes generated, unless I switch to JDBCDatabase.

I attached the full console output as a file.

[jooq.txt](https://github.com/jOOQ/jOOQ/files/1799293/jooq.txt)

**Comment by lukaseder** [comment]
I see, thanks. As I expected, the originally reported stack trace is logged on debug level, and not really a problem in this context. These are the two actual errors of interest:

```
ERROR: syntax error at or near "&"
  Detail: source SQL:
select "r1"."routine_schema", "r1"."routine_name", "r1"."specific_name", case when ("pg_catalog"."pg_proc"."proargmodes" && ARRAY['o','b']::"char"[]) then 'void' else "r1"."data_type" end as "data_type", "r1"."character_maximum_length", "r1"."numeric_precision", "r1"."numeric_scale", "r1"."type_udt_schema", "r1"."type_udt_name", case when count(*) over (partition by "r1"."routine_schema", "r1"."routine_name") > 1 then row_number() over (partition by "r1"."routine_schema", "r1"."routine_name" order by "r1"."specific_name") end as "overload", "pg_catalog"."pg_proc"."proisagg" from "information_schema"."routines" as "r1" join "pg_catalog"."pg_namespace" on "pg_catalog"."pg_namespace"."nspname" = "r1"."specific_schema" join "pg_catalog"."pg_proc" on ("pg_catalog"."pg_proc"."pronamespace" = "pg_catalog"."pg_namespace".oid and (("pg_catalog"."pg_proc"."proname" || $1) || cast("pg_catalog"."pg_proc".oid as varchar)) = "r1"."specific_name") where ("r1"."routine_schema" in ($2) and not("pg_catalog"."pg_proc"."proretset")) order by "r1"."routine_schema" asc, "r1"."routine_name" asc, "overload" asc
```

And:

> 11:48:44.090 [main] WARN org.jooq.util.AbstractDatabase - SQL exception            : Exception while executing meta query: ERROR: unsupported comparison operator: <tuple{string, string}> IN <tuple{name, name}>

```sql
select 
  "tables"."table_schema", 
  "tables"."table_name", 
  "tables"."specific_name", 
  "tables"."table_valued_function", 
  "tables"."materialized_view", 
  "tables"."description"
from (
  (
    select 
      "information_schema"."tables"."table_schema", 
      "information_schema"."tables"."table_name", 
      "information_schema"."tables"."table_name" as "specific_name", 
      false as "table_valued_function", 
      false as "materialized_view", 
      "pg_catalog"."pg_description"."description"
    from "information_schema"."tables"
      join "pg_catalog"."pg_namespace"
      on "information_schema"."tables"."table_schema" = "pg_catalog"."pg_namespace"."nspname"
      join "pg_catalog"."pg_class"
      on (
        "pg_catalog"."pg_class"."relname" = "information_schema"."tables"."table_name"
        and "pg_catalog"."pg_class"."relnamespace" = "pg_catalog"."pg_namespace".oid
      )
      left outer join "pg_catalog"."pg_description"
      on (
        "pg_catalog"."pg_description"."objoid" = "pg_catalog"."pg_class".oid
        and "pg_catalog"."pg_description"."objsubid" = 0
      )
    where (
      "information_schema"."tables"."table_schema" in ('vertx_test')
      and ("information_schema"."tables"."table_schema", "information_schema"."tables"."table_name") not in (
        select 
          "pg_catalog"."pg_namespace"."nspname", 
          "pg_catalog"."pg_class"."relname"
        from "pg_catalog"."pg_class"
          join "pg_catalog"."pg_namespace"
          on "pg_catalog"."pg_class"."relnamespace" = "pg_catalog"."pg_namespace".oid
        where "pg_catalog"."pg_class"."relkind" = 'm'
      )
    )
  )
  union all (
    select 
      "pg_catalog"."pg_namespace"."nspname", 
      "pg_catalog"."pg_class"."relname", 
      "pg_catalog"."pg_class"."relname", 
      false as "table_valued_function", 
      true as "materialized_view", 
      "pg_catalog"."pg_description"."description"
    from "pg_catalog"."pg_class"
      join "pg_catalog"."pg_namespace"
      on "pg_catalog"."pg_class"."relnamespace" = "pg_catalog"."pg_namespace".oid
      left outer join "pg_catalog"."pg_description"
      on (
        "pg_catalog"."pg_description"."objoid" = "pg_catalog"."pg_class".oid
        and "pg_catalog"."pg_description"."objsubid" = 0
      )
    where (
      "pg_catalog"."pg_namespace"."nspname" in ('vertx_test')
      and "pg_catalog"."pg_class"."relkind" = 'm'
    )
  )
  union all (
    select 
      "information_schema"."routines"."routine_schema", 
      "information_schema"."routines"."routine_name", 
      "information_schema"."routines"."specific_name", 
      true as "table_valued_function", 
      false as "materialized_view", 
      ''
    from "information_schema"."routines"
      join "pg_catalog"."pg_namespace"
      on "information_schema"."routines"."specific_schema" = "pg_catalog"."pg_namespace"."nspname"
      join "pg_catalog"."pg_proc"
      on (
        "pg_catalog"."pg_proc"."pronamespace" = "pg_catalog"."pg_namespace".oid
        and (("pg_catalog"."pg_proc"."proname" || '_') || cast("pg_catalog"."pg_proc".oid as varchar)) = "information_schema"."routines"."specific_name"
      )
    where (
      "information_schema"."routines"."routine_schema" in ('vertx_test')
      and "pg_catalog"."pg_proc"."proretset"
    )
  )
) as "tables"
order by 
  1, 
  2
```

I think these issues can be worked around rather easily. However, I will not be able to integration test the workarounds. Would you be interested in helping with that by building from GitHub master and verifying the fix?

**Comment by lukaseder** [comment]
Suggested fix here: https://github.com/jOOQ/jOOQ/commit/d9328672d6f470510801f1ac64bb657565f0cd67

**Comment by codepitbull** [comment]
I will check it but due to travelling won't be able before the end of the week, hope that's ok.

**Comment by lukaseder** [comment]
I'm not in a hurry :-)

**Comment by lukaseder** [comment]
Actual suggested fix here (previous link was another commit) https://github.com/jOOQ/jOOQ/commit/ec42a92708e0dc7836050bda26fd59a98d2e1c39

**Comment by lukaseder** [comment]
For the time being, this will be marked as fixed. Please create a new issue if you find further problems.
