### ISSUE TITLE
NPE with DSL.val(null, field) when custom Converter doesn't return null on null input

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7285]
Stack trace:

```
java.lang.NullPointerException
	at com.everydollar.type.ImmutableValue.toString(ImmutableValue.java:32)
	at java.lang.String.valueOf(String.java:2994)
	at org.jooq.impl.AbstractParam.name(AbstractParam.java:109)
	at org.jooq.impl.AbstractParam.<init>(AbstractParam.java:82)
	at org.jooq.impl.AbstractParam.<init>(AbstractParam.java:78)
	at org.jooq.impl.Val.<init>(Val.java:60)
	at org.jooq.impl.DSL.val(DSL.java:18569)
	at org.jooq.impl.DSL.val(DSL.java:18537)
	at org.jooq.impl.FieldMapsForInsert.addFields(FieldMapsForInsert.java:233)
	at org.jooq.impl.FieldMapsForInsert.set(FieldMapsForInsert.java:258)
	at org.jooq.impl.FieldMapsForInsert$2.put(FieldMapsForInsert.java:333)
	at org.jooq.impl.FieldMapsForInsert$2.put(FieldMapsForInsert.java:299)
	at org.jooq.impl.AbstractStoreQuery.addValue(AbstractStoreQuery.java:93)
	at org.jooq.impl.TableRecordImpl.addValue(TableRecordImpl.java:297)
	at org.jooq.impl.TableRecordImpl.addValue(TableRecordImpl.java:304)
	at org.jooq.impl.TableRecordImpl.addChangedValues(TableRecordImpl.java:288)
	at org.jooq.impl.TableRecordImpl.storeInsert0(TableRecordImpl.java:179)
	at org.jooq.impl.TableRecordImpl$1.operate(TableRecordImpl.java:168)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:125)
	at org.jooq.impl.TableRecordImpl.storeInsert(TableRecordImpl.java:164)
	at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:152)
	at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:147)
```

----
More details here:
https://groups.google.com/forum/#!topic/jooq-user/B1buFfEsLPU

**Comment by jlorenzen** [comment]
So we have a custom type class called `UserId`. It actually extends another custom class called `ImmutableValue`. It's just basically a wrapper around simple types (String, Long, Integer, etc) so we can have custom types in our codebase vs just passing around Strings, Longs, Integers, etc.
Here are the basics:
```java
public abstract class ImmutableValue<T> {
    private final T value;

    private ImmutableValue(final T value) {
        this.value = value;
    }

    public T getValue() {
        return value;
    }

    @Override
    public String toString() {
        return value.toString();
    }
}
```

Then here is our custom type class for `UserId`:
```java
public class UserId extends ImmutableValue<String> {
    public UserId(final String value) {
        super(value);
    }
}
```

Here is the custom converter:
```java
public class UserIdConverter implements Converter<String, UserId> {
    @Override
    public UserId from(final String databaseObject) {
        return new UserId(databaseObject);
    }

    @Override
    public String to(final UserId userObject) {
        return userObject.getValue();
    }

    @Override
    public Class<String> fromType() {
        return String.class;
    }

    @Override
    public Class<UserId> toType() {
        return UserId.class;
    }
}
```

Finally, here is the code that was causing the exception to be thrown. I've taken out some of the fields for simplicity but I think you should get the idea.
```java
dslContext.newRecord(TABLE)
        .setUserId(userId)
        .insert();
```

**Comment by lukaseder** [comment]
Thanks, @jlorenzen. Will try reproducing

**Comment by lukaseder** [comment]
OK, I can reproduce this issue. Full test case:

```java
import java.sql.Connection;
import java.sql.DriverManager;

import org.jooq.Converter;
import org.jooq.DSLContext;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.impl.TableRecordImpl;


public class H2 {
    public static void main(String[] args) throws Exception {
        Class.forName("org.h2.Driver");

        String url = "jdbc:h2:~/test";
        String user = "sa";
        String password = "";

        try (Connection c = DriverManager.getConnection(url, user, password)) {
            DSLContext ctx = DSL.using(c);
            ctx.newRecord(Table1.TABLE1)
               .setUserId(new UserId("1"))
               .insert();
        }
    }
}

abstract class ImmutableValue<T> {
    private final T value;

    ImmutableValue(final T value) {
        this.value = value;
    }

    public T getValue() {
        return value;
    }

    @Override
    public String toString() {
        return value.toString();
    }
}

class UserId extends ImmutableValue<String> {
    public UserId(final String value) {
        super(value);
    }
}

class UserIdConverter implements Converter<String, UserId> {
    @Override
    public UserId from(final String databaseObject) {
        return new UserId(databaseObject);
    }

    @Override
    public String to(final UserId userObject) {
        return userObject.getValue();
    }

    @Override
    public Class<String> fromType() {
        return String.class;
    }

    @Override
    public Class<UserId> toType() {
        return UserId.class;
    }
}

class Table1 extends TableImpl<Table1Record> {

    /**
     * Generated UID
     */
    private static final long                     serialVersionUID = 7621282509163949636L;

    public static final Table1                    TABLE1           = new Table1();

    public final TableField<Table1Record, UserId> USER_ID          = createField("USER_ID", SQLDataType.VARCHAR, this,
        "", new UserIdConverter());

    public Table1() {
        super("TABLE1");
    }

    @Override
    public Class<Table1Record> getRecordType() {
        return Table1Record.class;
    }
}

class Table1Record extends TableRecordImpl<Table1Record> {

    /**
     * Generated UID
     */
    private static final long serialVersionUID = 7621282509163949636L;

    public Table1Record() {
        super(Table1.TABLE1);
    }

    public Table1Record setUserId(UserId userId) {
        set(Table1.TABLE1.USER_ID, userId);
        return this;
    }
}
```

And I shall revert this bug to yourself. Your `toString()` implementation is simply wrong (i.e. not null safe) ;-)

How about this instead:

```java
    @Override
    public String toString() {
        return value == null ? "" : value.toString();
    }
```

**Comment by jlorenzen** [comment]
@lukaseder Hahaha. I can't disagree with that. My solution was just add a null check in the converter. What I do know was this code worked fine in 3.9.6 but was broken in 3.10.x.
And it seems odd to me to have to check for a null when I'm not even selecting data; the test was inserting the data. So that left me confused as to why the `from` converter method was being called. And the field in the database is `NOT NULL` so that was another reason I felt checking for `null` was not necessary.

**Comment by lukaseder** [comment]
Yeah, I don't know what triggered the change, but you cannot assume that your client side representation of a value is not `null` just because you have a `NOT NULL` constraint. The constraint could be deferred, for instance, or you could have a `DEFAULT` expression or a trigger generating a value if the client value provided is `NULL`...

This is similar to the `Option(al)` discussion. The `Option(al)` type simply doesn't make sense in the context of a SQL API. I've explained this in a blog post here:
https://blog.jooq.org/2017/07/25/5-things-you-may-not-have-known-about-jooq/#thing1

**Comment by jlorenzen** [comment]
@lukaseder Thanks Lukas. I appreciate your feedback and commitment to this project and the community. It's refreshing.

**Comment by lukaseder** [comment]
Thanks for your nice words :-)
