### ISSUE TITLE
Support parsing KEY/INDEX specifications in MySQL CREATE TABLE statements

### ISSUE THREAD

**Issue by galvinograd** [jOOQ/jOOQ#7347]
### Expected behavior and actual behavior:

INDEX keyword should be ignored in DDLDatabase.
Currently it's failing on :
```
SEVERE: An exception occurred while parsing script source : 
src/main/resources/db/migration/foo.sql. Please report this error to https://github.com/jOOQ/jOOQ/issues/new
org.jooq.impl.ParserException: C42000_NO_SUBCLASS: [13:3] (...),
  UNIQUE (foo, ...),
  [*]INDEX (bar),
  PRIMARY KEY (baz)
);

CREATE TABLE foo2 (
  id           
        at org.jooq.impl.ParserImpl$ParserContext.unexpectedToken(ParserImpl.java:6727)
        at org.jooq.impl.ParserImpl.parseCreateTable(ParserImpl.java:1735)
        at org.jooq.impl.ParserImpl.parseCreate(ParserImpl.java:1295)
        at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:531)
        at org.jooq.impl.ParserImpl.parse(ParserImpl.java:380)
        at org.jooq.impl.ParserImpl.parse(ParserImpl.java:367)
        at org.jooq.util.ddl.DDLDatabase.create0(DDLDatabase.java:129)
        at org.jooq.util.AbstractDatabase.create(AbstractDatabase.java:237)
        at org.jooq.util.AbstractDatabase.create(AbstractDatabase.java:226)
        at org.jooq.util.AbstractDatabase.getDialect(AbstractDatabase.java:208)
        at org.jooq.util.AbstractGenerator.logDatabaseParameters(AbstractGenerator.java:131)
        at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:271)
        at org.jooq.util.GenerationTool.run(GenerationTool.java:642)
        at org.jooq.util.GenerationTool.generate(GenerationTool.java:203)
        at org.jooq.util.GenerationTool.main(GenerationTool.java:175)
```
### Steps to reproduce the problem:

Just create a flyway migration script and use it for code generation:

build.gradle
```
jooq {
    version = jooqVersion
    foo(sourceSets.main) {
        generator {
            database {
                name = 'org.jooq.util.ddl.DDLDatabase'
                properties {
                    property {
                        key = 'scripts'
                        value = ifsFlywayScripts
                    }
                }
                includeTables = true
                includeRoutines = true
                includePackages = true
                includeUDTs = true
                includeSequences = true
                includePrimaryKeys = true
                includeUniqueKeys = true
                includeForeignKeys = true
            }
            generate {
                // see: https://www.jooq.org/doc/3.2/manual/code-generation/codegen-advanced/
                deprecated = false
                fluentSetters = true
                daos = true
            }
            target {
                packageName = foo_package
            }
        }
    }
}
```

### Versions:

- jOOQ: 3.10.5
- Java: 9
- Database (include vendor): DDLDatabase for code generation, MySQL on production
- OS: Mac OSX
- JDBC Driver (include name if inofficial driver): *

**Comment by lukaseder** [comment]
Thank you very much for your report. The parser currently doesn't ignore syntax that can be represented in one way or another by jOOQ, following a "fail fast" philosophy. This might change in the future, when we add parser configuration flags, including a flag that allows for parsing and ignoring known but unsupported syntax (see: #7336)

In any case, we should definitely support the MySQL syntax in jOOQ's API (and thus in the parser), emulating it in other databases by emitting an anonymous block. I have created a feature request for this: #7348

This issue will then resolve itself. As a workaround, you could use the more globally supported syntax by having separate `CREATE INDEX` statements.

**Comment by galvinograd** [comment]
Thanks, I'll check that out

**Comment by lukaseder** [comment]
Let's close this issue when it works.
