### ISSUE TITLE
Bad implementation of ALTER TABLE .. ALTER COLUMN .. SET DATA TYPE in HSQLDB

### ISSUE THREAD

**Issue by benallard** [jOOQ/jOOQ#7349]
### Expected behavior and actual behavior:

```
Caused by: org.jooq.exception.DataAccessException: SQL [alter table mp_fodder_delivery alter delivery_note_number varchar(255) not null]; unexpected token: NOT in statement [alter table mp_fodder_delivery alter delivery_note_number varchar(255) not null]
	at org.jooq_3.10.6.HSQLDB.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2241)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:704)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:361)
...
```

### Steps to reproduce the problem:

```
        aContext.alterTable(FODDER_DELIVERY_TABLE_NAME)
                .alterColumn("delivery_note_number")
                .set(SQLDataType.VARCHAR(255).nullable(false)).execute();
```

### Versions:

- jOOQ: 3.10.6
- Java: 1.8.0.152
- Database (include vendor): HSQLDB in memory
- OS: Win 10
- JDBC Driver (include name if inofficial driver): 2.4.0

Note: When using ``setNotNull()``, it's working fine.

**Comment by lukaseder** [comment]
Thanks a lot for your report. Will look into this ASAP

**Comment by lukaseder** [comment]
Yes, indeed, this doesn't work on HSQLDB. It should, according to the documentation:
http://www.hsqldb.org/doc/guide/ch09.html#alter_table-section

I have created a bug in HSQLDB's tracker to see whether the implementation or the documentation is wrong:
https://sourceforge.net/p/hsqldb/bugs/1507/

**Comment by lukaseder** [comment]
My bad, I was on the wrong version of the manual. The correct syntax is documented here:
http://hsqldb.org/doc/guide/databaseobjects-chapt.html#dbc_table_manupulation

E.g.:

```sql
ALTER TABLE x ALTER COLUMN i BIGINT SET NOT NULL
``

**Comment by lukaseder** [comment]
My bad, I was on the wrong version of the manual. The current version is here:
http://hsqldb.org/doc/guide/databaseobjects-chapt.html#dbc_table_manupulation

There's no possibility to modify multiple things in a column in a single statement, and to my knowledge, there's also no way to run an anonymous block in HSQLDB, so I'm currently not sure how this could be fixed.

**Comment by besquared** [comment]
I wanted to ask about a related issue with the HSQLB dialect which is that there is that nullable columns don't accept a NULL constraint in their definition. It should just be omitted according to the documentation. For example:

```
aContext.createTable(table("my_table"))
    .column(field("my_field", SQLDataType.INTEGER));

Produces

CREATE TABLE "my_table"("my_field" int NULL)
```

Which isn't a valid constraint in a column definition. This causes some HSQLDB dialects (in my case VoltDB) to fail with syntax errors. According to the documentation listed above only NOT NULL is valid in this context:

 <column definition> ::= <column name> [ <data type or domain name> ] [ <default clause> | <identity column specification> | <identity column sequence specification> | <generation clause> ] [ <update clause> ] [ <column constraint definition>... ] [ <collate clause> ]

<data type or domain name> ::= <data type> | <domain name>

<column constraint definition> ::= [ <constraint name definition> ] <column constraint> [ <constraint characteristics> ]

<column constraint> ::= NOT NULL | <unique specification> | <references specification> | <check constraint definition>

**Comment by lukaseder** [comment]
@besquared Thanks for the report. Not strictly related, I have created a new issue: https://github.com/jOOQ/jOOQ/issues/7392 (don't worry about issues, we don't run out of issue numbers any time soon)
