### ISSUE TITLE
SQLException when calling DSLContext.fetch(ResultSet) on array out parameters

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7450]
When calling `DSLContext.fetch(cstmt.getArray(n).getResultSet())` on an array out parameter, an exception may be thrown as `ResultSet.getMetaData()` might not have been implemented:

```
Exception in thread "main" org.jooq.exception.DataAccessException: Error while accessing ResultSet meta data
	at org.jooq.impl.DefaultDSLContext.fetchLazy(DefaultDSLContext.java:1257)
	at org.jooq.impl.DefaultDSLContext.fetch(DefaultDSLContext.java:1109)
	at o.Oracle.main(Oracle.java:57)
Caused by: java.sql.SQLException: Nicht unterstützte Funktion: getMetaData
	at oracle.jdbc.driver.ArrayDataResultSet.getMetaData(ArrayDataResultSet.java:1029)
	at org.jooq.impl.DefaultDSLContext.fetchLazy(DefaultDSLContext.java:1254)
	... 2 more
```

We should be able to work around that by calling `getObject()` until we no longer have any columns.

**Comment by lukaseder** [comment]
Could have used this today, to debug ojdbc output... Will implement this now
