### ISSUE TITLE
ArrayIndexOutOfBoundsException on terminal operation of sorted ResultQuery.stream()

### ISSUE THREAD

**Issue by mches** [jOOQ/jOOQ#7455]
### Expected behavior and actual behavior:

Should be able to sort a stream from a `ResultQuery`, but instead get an `ArrayIndexOutOfBoundsException` on the terminal operation

```
java.lang.ArrayIndexOutOfBoundsException: 0
	at java.util.stream.SortedOps$SizedRefSortingSink.accept(SortedOps.java:364) ~[?:1.8.0_152]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_152]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_152]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_152]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_152]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_152]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_152]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_152]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_152]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_152]
        ...
```

The `Spliterator` used in `CursorImpl.stream()` seems to be the culprit
```java
    /* [java-8] */
    @Override
    public final Stream<R> stream() throws DataAccessException {
        return StreamSupport.stream(
            Spliterators.spliterator(
                iterator(),
                0,
                Spliterator.ORDERED | Spliterator.NONNULL
            ),
            false
        ).onClose(() -> close());
    }
    /* [/java-8] */
```

I suggest the following alternative to create a `Stream` that can be sorted
```java
    /* [java-8] */
    @Override
    public final Stream<R> stream() throws DataAccessException {
        return StreamSupport.stream(
            Spliterators.spliteratorUnknownSize(
                iterator(),
                Spliterator.ORDERED | Spliterator.NONNULL
            ),
            false
        ).onClose(() -> close());
    }
    /* [/java-8] */
```

### Steps to reproduce the problem:

Construct a result query. Stream, map and sort the results before performing a terminal operation.

```java
ResultQuery<Record1<String>> query = ...
try (Stream<String> strings = query.fetchStream()
    .map(Record1::value1)
    .sorted())

  strings.forEach(System.out::println);
}
```

### Versions:

- jOOQ: 3.10.1 Pro
- Java: 1.8.0_152
- Database: SQL Server 2016 Developer Edition with Service Pack 2
- OS: Windows 10 Enterprise
- JDBC Driver:  6.2.2.jre8

**Comment by lukaseder** [comment]
Thanks a lot for the report and the suggested fix. I agree - the current implementation is wrong. It must have been taken from a wrong / early tutorial
