### ISSUE TITLE
arrayAgg() does not respect custom converters

### ISSUE THREAD

**Issue by xathien** [jOOQ/jOOQ#7471]
### Steps to reproduce the problem:
Generate code that has a UDT, e.g.
```sql
CREATE TABLE foo (
  id UUID
);
```

```xml
<forcedType>
  <userType>foo.SomeUuidWrapper</userType>
  <converter>foo.SomeUuidWrapperConverter</converter>
  <expression>foo\.id</expression>
</forcedType>
```

Then run:
```java
dslContext.insertInto(FOO, FOO.ID).values(new SomeUuidWrapper()).execute();
Record r = dslContext.select(arrayAgg(FOO.ID)).from(FOO).fetch();
```

Expected:
`Record` containing an array of `SomeUuidWrapperConverter`

Actual:
`org.jooq.exception.DataTypeException: Cannot convert from 0149a684-e15b-8c46-7a62-000100200001 (class java.util.UUID) to class foo.SomeUuidWrapper`

At a quick code glance, we _might_ just need a version of `arrayAgg` for a `TableField` that passes along its single-item `Converter`, but it's probably not that simple. 🙂 
### Versions:

- jOOQ: 3.10.2
- Java: 8u172
- Database (include vendor): Postgres 9.4
- OS: Mac
- JDBC Driver (include name if inofficial driver): Postgres official

**Comment by lukaseder** [comment]
Thanks for your report. Our integration tests indicate that `arrayAgg()` with converted data types work without any problems. How does this exception occur / how can it be reproduced? Can you share the full stack trace and some example client code?

Notice that your first line shouldn't compile if your converter is applied correctly:

```java
dslContext.insertInto(FOO, FOO.ID).values(UUID.randomUUID()).execute();
```

`FOO.ID` should be of type `Field<SomeUuidWrapper>`, so you shouldn't be able to pass a `UUID` type to the `values()` method. I'm assuming:

1) Your converter isn't applied correctly (try fully qualifying the table: `schema\.table\.column`)
2) You have an additional method call that isn't being shown here, which causes the error

**Comment by xathien** [comment]
Apparently I didn't get an email when you commented on this bug. Whoops!

Let me edit the report to reflect the correct `values` call, e.g. `.values(new SomeUuidWrapper(UUID.randomUUID())` .
The converter is definitely being applied correctly, since we've been using it for quite some time. Any time I try to run `array_agg` on a UDT column, I get the `org.jooq.DataTypeException`.

**Comment by xathien** [comment]
And, for your perusal, a full stack trace (with my company's internal data removed) since I realized you requested one earlier. 😅 

```
org.jooq.exception.DataAccessException: SQL [select "identity"."id", (*snip irrelevant fields*), array_agg("identity_member_of_user_groups"."member_of_user_groups") as "user_groups" from "identity" join "user" on "user"."id" = "identity"."id" left outer join "identity_member_of_user_groups" on "identity_member_of_user_groups"."members" = "identity"."id" where "user"."external_user_id" = ? group by "identity"."id", "user"."id"]; Error while reading field: "user_groups", at JDBC index: 16
	at org.jooq_3.10.2.POSTGRES.debug(Unknown Source)
	at org.jooq_3.10.2.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2194)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:701)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1625)
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1576)
	at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:398)
	at org.jooq.impl.CursorImpl.fetch(CursorImpl.java:384)
	at org.jooq.impl.CursorImpl.fetch(CursorImpl.java:291)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:288)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:344)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:314)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:1434)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:3639)
         *snip company-specific stacktrace*
Caused by: java.sql.SQLException: Error while reading field: "user_groups", at JDBC index: 16
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1721)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.operate(CursorImpl.java:1680)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.operate(CursorImpl.java:1645)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:122)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1609)
	... 86 common frames omitted
Caused by: org.jooq.exception.DataTypeException: Cannot convert from 0149a684-e15b-8c46-7a62-000100200001 (class java.util.UUID) to class com.jive.v5.pbx.services.identity.api.usergroup.UserGroupId
	at org.jooq.tools.Convert$ConvertAll.fail(Convert.java:1146)
	at org.jooq.tools.Convert$ConvertAll.from(Convert.java:1035)
	at org.jooq.tools.Convert.convert0(Convert.java:316)
	at org.jooq.tools.Convert.convert(Convert.java:308)
	at org.jooq.tools.Convert.convert(Convert.java:380)
	at org.jooq.tools.Convert.convertArray(Convert.java:287)
	at org.jooq.tools.Convert$ConvertAll.from(Convert.java:531)
	at org.jooq.tools.Convert.convert0(Convert.java:316)
	at org.jooq.tools.Convert.convert(Convert.java:308)
	at org.jooq.tools.Convert.convert(Convert.java:380)
	at org.jooq.impl.DefaultBinding.convertArray(DefaultBinding.java:2190)
	at org.jooq.impl.DefaultBinding.pgGetArray(DefaultBinding.java:2505)
	at org.jooq.impl.DefaultBinding.get(DefaultBinding.java:1611)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1711)
	... 90 common frames omitted
```

And the generated record shows that the converter is registering correctly:
```java
public final TableField<IdentityMemberOfUserGroupsRecord, UserGroupId> MEMBER_OF_USER_GROUPS = createField("member_of_user_groups", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "", new UserGroupIdConverter());
```

And the code that generated the query:
```java
    Field<UserGroupId[]> USER_GROUPS =
      arrayAgg(IDENTITY_MEMBER_OF_USER_GROUPS.MEMBER_OF_USER_GROUPS)
          .as(name("user_groups"));

    return getDbConnection()
        .select(IDENTITY.fields())
        .select(USER.fields())
        .select(USER_GROUPS)
        .from(IDENTITY)
        .join(USER).onKey()
        .leftOuterJoin(IDENTITY_MEMBER_OF_USER_GROUPS)
        .on(IDENTITY_MEMBER_OF_USER_GROUPS.MEMBERS.eq(IDENTITY.ID))
        .where(USER.EXTERNAL_USER_ID.eq(externalId))
        .groupBy(IDENTITY.ID, JIVE_USER.ID)
        .fetch(this::mapUser);
```

Hopefully this helps us track it down and helps you repro it. :)
... and before you judge the table schema too harshly, one of the guys early on in the company decided it'd be fun to let Hibernate generate the schema. 😐

**Comment by lukaseder** [comment]
Here's our integration test for this case:

```sql
CREATE TYPE u_6930 AS ENUM('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY');

create table t_6930 (
  id INT,
  weekday_normal u_6930,
  weekday_converter u_6930,
  weekday_binding u_6930,
  weekday_enumconverter u_6930,
  
  CONSTRAINT t_6930_pk PRIMARY KEY (id)
);
```

And then:

```xml
<forcedType>
    <enumConverter>true</enumConverter>
    <userType>java.time.DayOfWeek</userType>
    <includeExpression>(?i:(.*?\.)T_6930\.WEEKDAY_ENUMCONVERTER)</includeExpression>
</forcedType>
<forcedType>
    <converter>org.jooq.test.postgres.types.WeekdayEnumConverter</converter>
    <userType>java.time.DayOfWeek</userType>
    <includeExpression>(?i:(.*?\.)T_6930\.WEEKDAY_CONVERTER)</includeExpression>
</forcedType>
<forcedType>
    <converter>org.jooq.test.postgres.types.WeekdayEnumBinding</converter>
    <userType>java.time.DayOfWeek</userType>
    <includeExpression>(?i:(.*?\.)T_6930\.WEEKDAY_BINDING)</includeExpression>
</forcedType>
```

And then:

```java
    public static void testPostgresFunctionsOnConvertedDataTypes(PostgresTest t) {
        t.clean(T_6930);

        assertEquals(3,
            t.create().insertInto(T_6930)
                    .columns(T_6930.ID, T_6930.WEEKDAY_CONVERTER)
                    .values(1, null)
                    .values(2, DayOfWeek.MONDAY)
                    .values(3, DayOfWeek.TUESDAY)
                    .execute());

        assertEquals(
            asList(null, DayOfWeek.MONDAY, DayOfWeek.TUESDAY),
            asList(
                t.create().select(arrayAgg(T_6930.WEEKDAY_CONVERTER).orderBy(T_6930.ID))
                        .from(T_6930)
                        .fetchSingle()
                        .value1()));
    }
```

This is a test case mostly for https://github.com/jOOQ/jOOQ/issues/6930, with added `arrayAgg()` call, which works as expected. In order to reproduce this case, we'd need an MCVE (template here: https://github.com/jOOQ/jOOQ-mcve), or at least some information about:

- DDL of involved tables
- Forced type configuration
- User type implementation (i.e. `UserGroupId`)

I'll be happy to look at this again, should updated reproduction information be available.

**Comment by xathien** [comment]
[Here's](https://github.com/xathien/jOOQ-mcve/commit/5efbceddb3fbb1cc46bee7bfd919618cd60ea65c) the MCVE as requested!

**Comment by lukaseder** [comment]
See also: https://github.com/jOOQ/jOOQ/issues/10664
