### ISSUE TITLE
SEEK operations do not auto-convert bind variables to appropriate type

### ISSUE THREAD

**Issue by SzabKel** [jOOQ/jOOQ#7515]
### Expected behavior and actual behavior:
The seekBefore select query that gets generated seems valid, If I execute the step's `toString()` directly, it gives the expected result. However, the `fetch()` throws an exception:
```
org.postgresql.util.PSQLException: ERROR: operator does not exist: bigint > character varying
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 339
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:144) ~[postgresql-42.2.2.jar:42.2.2]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[HikariCP-3.1.0.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[HikariCP-3.1.0.jar:na]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209) ~[jooq-3.10.7.jar:na]
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:3250) ~[jooq-3.10.7.jar:na]
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:262) ~[jooq-3.10.7.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:347) ~[jooq-3.10.7.jar:na]
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:317) ~[jooq-3.10.7.jar:na]
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:1437) ~[jooq-3.10.7.jar:na]
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:3642) ~[jooq-3.10.7.jar:na]
	at ......JooqTest.publicManufacturerNames(JooqTest.java:44) ~[classes/:na]
	at ....PaginationTestController.MNPaginationTest(PaginationTestController.java:36) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209) ~[spring-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877) ~[spring-webmvc-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783) ~[spring-webmvc-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991) ~[spring-webmvc-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925) ~[spring-webmvc-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974) ~[spring-webmvc-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866) ~[spring-webmvc-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851) ~[spring-webmvc-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320) ~[spring-security-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127) ~[spring-security-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91) ~[spring-security-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119) ~[spring-security-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137) ~[spring-security-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) ~[spring-security-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170) ~[spring-security-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) ~[spring-security-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:100) ~[spring-security-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66) ~[spring-security-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) ~[spring-security-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) ~[spring-security-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215) ~[spring-security-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178) ~[spring-security-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357) ~[spring-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270) ~[spring-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109) ~[spring-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) ~[spring-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) ~[spring-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_144]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
```

### Steps to reproduce the problem (include example code if possible):
I am trying to use KeySet pagination somewhat dynamically in a Spring Boot project. The user passes in a Json model to the endpoint, which describes the Sorting and the last seen entries. Based on them, I generate the query.

I call the generation in my service class like this:
```java
public List<PublicManufacturerName> publicManufacturerNames(KeySetPageRequest p) {
	PubManufacturername PMN = PubManufacturername.PUB_MANUFACTURERNAME;
	SelectConditionStep<Record> where = dsl.select().from(PMN).where(trueCondition());
	SelectForUpdateStep<Record> records = p.addPagination(where, PMN);
	return records.fetch(record -> PublicManufacturerName.from(record));
}
```

And the code which applies the seek:
```java

@Value.Immutable
@JsonDeserialize(as = ImmutableLastSeenEntry.class)
@JsonSerialize(as = ImmutableLastSeenEntry.class)
public abstract class LastSeenEntry {
    public abstract String field();
    public abstract String value();
    public abstract Sort.Direction direction();
}

public class KeySetPageRequest implements KeySetPageable, Serializable {
    private int size;
    private KeySetPaginationDirection direction;// AFTER or BEFORE
    @JsonDeserialize(using = Base64Deserializer.class)
    private List<LastSeenEntry> lastSeenEntries;

    public KeySetPageRequest(int size, KeySetPaginationDirection direction, List<LastSeenEntry> lastSeenEntries) {
        this.size = size;
        this.direction = direction;
        this.lastSeenEntries = lastSeenEntries;
    }

    @Override
    public KeySetPaginationDirection direction() {
        return direction;
    }

    @Override
    public List<LastSeenEntry> lastSeenEntries() {
        return lastSeenEntries;
    }

    @Override
    public int getPageSize() {
        return size;
    }

    @Override
    public KeySetPageable first() {
        return new KeySetPageRequest(size, direction, new ArrayList<>());
    }

    public List<SortField<?>> asOrderBy(Table<?> table) {
        ArrayList<SortField<?>> sortFields = new ArrayList<>(lastSeenEntries.size());
        List<Field<?>> fields = Arrays.asList(table.fields());
        for (LastSeenEntry lastSeenEntry : lastSeenEntries) {
            Optional<Field<?>> foundField = fields.stream().filter(f -> f.getName().equals(lastSeenEntry.field()))
                    .findFirst();
            if (!foundField.isPresent()) {
                continue;
            }
            if (lastSeenEntry.direction().equals(Sort.Direction.ASC)) {
                sortFields.add(foundField.get().sort(SortOrder.ASC));
            } else {
                sortFields.add(foundField.get().sort(SortOrder.DESC));
            }
        }
        return sortFields;
    }
	
    public SelectForUpdateStep<Record> addPagination(SelectConditionStep<Record> select, Table<?> table) {
        List<SortField<?>> sortFields = asOrderBy(table);
        Object[] values = lastSeenEntries.stream().map(lse -> lse.value()).toArray();

        SelectSeekLimitStep<Record> selectSeekLimitStep;
        SelectSeekStepN<Record> seekStepN = select.orderBy(sortFields);
        if (direction == KeySetPaginationDirection.AFTER) {
            selectSeekLimitStep = seekStepN.seekAfter(values);
        } else {
            throw new UnsupportedOperationException("Direction BEFORE is not yet supported by jooq: https://github.com/jOOQ/jOOQ/issues/7461 ");
            // selectSeekLimitStep = seekStepN.seekBefore(values);
        }

        return selectSeekLimitStep.limit(size);
    }
}
```

This generates the query (runtime, with applicable agruments):
```sql
select
  "web"."pub_manufacturername"."id",
  "web"."pub_manufacturername"."createdAt",
  "web"."pub_manufacturername"."updatedAt",
  "web"."pub_manufacturername"."name"
from "web"."pub_manufacturername"
where (
  1 = 1
  and (
    "web"."pub_manufacturername"."name" < 'AUSA'
    or (
      "web"."pub_manufacturername"."name" = 'AUSA'
      and "web"."pub_manufacturername"."id" > '126'
    )
  )
)
order by
  "web"."pub_manufacturername"."name" desc,
  "web"."pub_manufacturername"."id" asc
```
(plus limit)

So the query works, but I still get validation error at runtime. (Dialect is 9_5)

### Versions:
- Spring 2.0.2.RELEASE
- jOOQ: 3.10.7
- Java: Compiling 1.8 on version "10.0.1" 2018-04-17
- Database (include vendor):  PostgreSQL-10.4-1-win64-bigsql
- OS: Windows Server 2016 for db, Win10 1709 for dev
- JDBC Driver (include name if inofficial driver): org.postgresql 42.2.2

**Comment by SzabKel** [comment]
If I pass the arguments as ` values = new Object[] { "AUSA", 126L };` I will not get the exception.

**Comment by SzabKel** [comment]
Okay, I ended up doing this:
```java
    public Object[] asFieldValues(Table<?> table) {
        List<Object> result = new ArrayList<>();
        List<Field<?>> fields = Arrays.asList(table.fields());
        for (LastSeenEntry lastSeenEntry : lastSeenEntries) {
            Optional<Field<?>> foundField = fields.stream().filter(f -> f.getName().equals(lastSeenEntry.field()))
                    .findFirst();
            if (!foundField.isPresent()) {
                continue;
            }
            Field<?> field = foundField.get();
            Object converted = field.getDataType().convert(lastSeenEntry.value());
            result.add(converted);
        }
        return result.toArray(new Object[result.size()]);
    }
```
And calling it in `addPagination`: `Object[] values = asFieldValues(table);`

**Comment by lukaseder** [comment]
Thanks for your report.

Do note that "seek before" is currently deprecated: #7461 due to a known issue: #6380. You've mentioned this in your code snippet as a comment, but it's worth mentioning it again, since you put "seekBefore" in the issue title.

I can reproduce the problem like this:

```java
assertEquals(
    asList(3),
    create().select(TBook_ID())
            .from(TBook())
            .orderBy(new Field[] { TBook_ID() })
            .seekAfter(new Object[] { "2" })
            .limit(1)
            .fetch(TBook_ID()));
```

It shouldn't be your job to explicitly convert data types to the expected column type. jOOQ usually auto-converts things behind the scenes.

Will reopen and fix this

**Comment by SzabKel** [comment]
@lukaseder Yes, I messed up the title, I was aware of the state of seekBefore when I opened the ticket. Thank you.

**Comment by lukaseder** [comment]
No worries at all :-)
