### ISSUE TITLE
Regression in UpdatableRecord.store() and update() methods when used with connection pools

### ISSUE THREAD

**Issue by dariokures** [jOOQ/jOOQ#7569]
### Expected behavior and actual behavior:
After upgrade from 3.10.6 to 3.11.0, Record.update() doesn't work with connections from jdbc data source.

### Steps to reproduce the problem (include example code if possible):
```java
DSLContext context = DSL.using(dataSource, SQLDialect.POSTGRES_9_5);
UsersRecord user = context.selectFrom(USERS).where(USERS.ID.eq(1)).fetchOne();
user.setFirstName("test");
user.update();
```

```
org.jooq.exception.DataAccessException: SQL [update "core"."users" set "first_name" = ? where "core"."users"."id" = ?]; Connection is closed
	at org.jooq_3.11.0.POSTGRES_9_5.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2380)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:737)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:364)
	at org.jooq.impl.UpdatableRecordImpl.storeUpdate0(UpdatableRecordImpl.java:253)
	at org.jooq.impl.UpdatableRecordImpl.access$100(UpdatableRecordImpl.java:84)
	at org.jooq.impl.UpdatableRecordImpl$2.operate(UpdatableRecordImpl.java:209)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:125)
	at org.jooq.impl.UpdatableRecordImpl.storeUpdate(UpdatableRecordImpl.java:205)
	at org.jooq.impl.UpdatableRecordImpl.update(UpdatableRecordImpl.java:155)
	at org.jooq.impl.UpdatableRecordImpl.update(UpdatableRecordImpl.java:150)
	....
Caused by: java.sql.SQLException: Connection is closed
	at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:489)
	at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection$$Lambda$2170/824175404.invoke(Unknown Source)
	at com.sun.proxy.$Proxy157.prepareStatement(Unknown Source)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:311)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
	at org.jooq.impl.ProviderEnabledConnection.prepareStatement(ProviderEnabledConnection.java:109)
	at org.jooq.impl.SettingsEnabledConnection.prepareStatement(SettingsEnabledConnection.java:73)
	at org.jooq.impl.ProviderEnabledConnection.prepareStatement(ProviderEnabledConnection.java:109)
	at org.jooq.impl.SettingsEnabledConnection.prepareStatement(SettingsEnabledConnection.java:73)
	at org.jooq.impl.AbstractQuery.prepare(AbstractQuery.java:416)
	at org.jooq.impl.AbstractDMLQuery.prepare(AbstractDMLQuery.java:511)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:322)
```

### Versions:

- jOOQ: 3.11.0
- Java: 1.8
- Database (include vendor): PostgreSQL 9.6
- OS: Windows 10
- JDBC Driver (include name if inofficial driver): 42.2.2

**Comment by ciaccia** [comment]
I can reproduce the problem as well. Here what happens:

1. a connection is retrieved from the DataSource using `getConnection`
2. the connection's `prepareStatement` method is called
3. the data from the ResultSet is fetched
4. the connection of point 1. is closed using `close`
5. connection's `prepareStatement` is called a second time
6. The exception is thrown

Here below a mini application to reproduce it:

    CREATE TABLE public.ds_connection_bug
    (
       "id" bigserial PRIMARY KEY,
       "data" text
    );
    insert into "public"."ds_connection_bug"("data") values ('bar');

Here the Java application:

    package org.jooq;
    
    import static org.jooq.Tables.DS_CONNECTION_BUG;
    
    import java.io.PrintWriter;
    import java.sql.Statement;
    import java.sql.*;
    import java.util.Map;
    import java.util.Properties;
    import java.util.concurrent.Executor;
    import java.util.logging.Logger;
    
    import javax.sql.DataSource;
    
    import org.jooq.conf.Settings;
    import org.jooq.impl.DSL;
    import org.jooq.tables.records.DsConnectionBugRecord;;
    
    public class JooqBug {
    
    	public static void main(String[] args) {
    	
    		String url = "jdbc:postgresql://localhost:5432/db";
    		String username = "postgres";
    		String password = "postgres";
    		
    		DataSource ds = new DataSource() {
    
    			@Override
    			public PrintWriter getLogWriter() throws SQLException {
    				throw new UnsupportedOperationException();
    			}
    
    			@Override
    			public void setLogWriter(PrintWriter out) throws SQLException {
    				throw new UnsupportedOperationException();
    				
    			}
    
    			@Override
    			public void setLoginTimeout(int seconds) throws SQLException {
    				throw new UnsupportedOperationException();
    			}
    
    			@Override
    			public int getLoginTimeout() throws SQLException {
    				throw new UnsupportedOperationException();
    			}
    
    			@Override
    			public Logger getParentLogger() throws SQLFeatureNotSupportedException {
    				throw new UnsupportedOperationException();
    			}
    
    			@Override
    			public <T> T unwrap(Class<T> iface) throws SQLException {
    				throw new UnsupportedOperationException();
    			}
    
    			@Override
    			public boolean isWrapperFor(Class<?> iface) throws SQLException {
    				throw new UnsupportedOperationException();
    			}
    
    			@Override
    			public Connection getConnection() throws SQLException {
    				System.out.println(">>> ds.getConnection");
    				final Connection con = DriverManager.getConnection(url,username,password);
    				con.setAutoCommit(false);
    				
    				return new Connection() {
    
    					@Override
    					public <T> T unwrap(Class<T> iface) throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public boolean isWrapperFor(Class<?> iface) throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public Statement createStatement() throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public PreparedStatement prepareStatement(String sql) throws SQLException {
    						System.out.println(">>> connection.prepareStatement()");
    						// This is the only supported method. 
    						return con.prepareStatement(sql);
    					}
    
    					@Override
    					public CallableStatement prepareCall(String sql) throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public String nativeSQL(String sql) throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public void setAutoCommit(boolean autoCommit) throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public boolean getAutoCommit() throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public void commit() throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public void rollback() throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public void close() throws SQLException {
    						System.out.println(">>> connection.close()");
    						// Delegate to the proxied object
    						con.close();
    					}
    
    					@Override
    					public boolean isClosed() throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public DatabaseMetaData getMetaData() throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public void setReadOnly(boolean readOnly) throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public boolean isReadOnly() throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public void setCatalog(String catalog) throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public String getCatalog() throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public void setTransactionIsolation(int level) throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public int getTransactionIsolation() throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public SQLWarning getWarnings() throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public void clearWarnings() throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency)
    							throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency)
    							throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public Map<String, Class<?>> getTypeMap() throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public void setTypeMap(Map<String, Class<?>> map) throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public void setHoldability(int holdability) throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public int getHoldability() throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public Savepoint setSavepoint() throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public Savepoint setSavepoint(String name) throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public void rollback(Savepoint savepoint) throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public void releaseSavepoint(Savepoint savepoint) throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public Statement createStatement(int resultSetType, int resultSetConcurrency,
    							int resultSetHoldability) throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency,
    							int resultSetHoldability) throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency,
    							int resultSetHoldability) throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public Clob createClob() throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public Blob createBlob() throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public NClob createNClob() throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public SQLXML createSQLXML() throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public boolean isValid(int timeout) throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public void setClientInfo(String name, String value) throws SQLClientInfoException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public void setClientInfo(Properties properties) throws SQLClientInfoException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public String getClientInfo(String name) throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public Properties getClientInfo() throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public Struct createStruct(String typeName, Object[] attributes) throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public void setSchema(String schema) throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public String getSchema() throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public void abort(Executor executor) throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    
    					@Override
    					public int getNetworkTimeout() throws SQLException {
    						throw new UnsupportedOperationException();
    					}
    					
    				};
    			}
    
    			@Override
    			public Connection getConnection(String username, String password) throws SQLException {
    				throw new SQLException("not implemented");
    			}
    		};
    		
    		try {
    			final DSLContext dslCtx = DSL.using(ds, SQLDialect.POSTGRES, new Settings().withExecuteLogging(true));
    			
    			DsConnectionBugRecord record = dslCtx.selectFrom(DS_CONNECTION_BUG).where(DS_CONNECTION_BUG.ID.eq(1L)).fetchSingle();
    			record.set(DS_CONNECTION_BUG.DATA, "foo");
    			record.store();
    			
    
    		} catch (Exception e) {
    			e.printStackTrace();
    		}
    	}
    }

**Comment by lukaseder** [comment]
Thanks a lot for the report. Will look into this soon!

**Comment by epkugelmass** [comment]
I built a 3.11.x patch that reverts https://github.com/jOOQ/jOOQ/commit/930cdb068451491aeb90af24c0f108752bf88eeb and https://github.com/jOOQ/jOOQ/commit/0fb8c29b1a373d98c39bfb19e5172797eef10602. Running my application with this patch resolves the condition described in this ticket.

**Comment by lukaseder** [comment]
Thanks again for the example @ciaccia. I can reproduce the problem.

 The problem appears with `UpdatableRecord` instances, which reference a "leaked" `org.jooq.impl.DefaultExecuteContext$ExecuteContextConnectionProvider` instance that still holds on to the closed connection. That instance should not escape the execution context lifecycle.

Indeed, @epkugelmass, this regression was introduced with https://github.com/jOOQ/jOOQ/commit/930cdb068451491aeb90af24c0f108752bf88eeb

Will investigate

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.12. Backport to 3.11.2 scheduled: #7618

**Comment by lukaseder** [comment]
jOOQ 3.11.2 was released yesterday. Would be great if you folks could provide feedback to see if this is indeed a duplicate

**Comment by lukaseder** [comment]
jOOQ 3.11.2 was released yesterday. Would be great if you folks could provide feedback to see if this is fixed

**Comment by dariokures** [comment]
Tested. The issue is fixed.

Thanks!

**Comment by epkugelmass** [comment]
Thank you. Works on my end too.

**Comment by ciaccia** [comment]
Hi Lukas, with some delay I confirm as well the issue is gone! 👍 Thanks a lot for the fix!

**Comment by lukaseder** [comment]
@ciaccia Perfect, great to hear. Thanks for the feedback, everyone!

**Comment by pilt** [comment]
Is this related? JOOQ 3.11.2, Postgres 10, Hikari from Spring Boot 2.0.4.

```kotlin
        var record = dsl.insertInto(Tables.STABLE)
            .set(Tables.STABLE.NAME, "Stall")
            .returning()
            .fetchOne()

        // Works:
        //record = dsl.selectFrom(Tables.STABLE).where(Tables.STABLE.ID.eq(record.id)).fetchSingle()

        record.refresh()
```` 

```
org.springframework.jdbc.UncategorizedSQLException: jOOQ; uncategorized SQLException for SQL [select "public"."stable"."id", "public"."stable"."created", "public"."stable"."modified", "public"."stable"."name" from "public"."stable" where "public"."stable"."id" = ?]; SQL state [null]; error code [0]; Connection is closed; nested exception is java.sql.SQLException: Connection is closed

	at org.jooq_3.11.2.POSTGRES.debug(Unknown Source)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:89)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.translate(JooqExceptionTranslator.java:93)
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.handle(JooqExceptionTranslator.java:82)
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.exception(JooqExceptionTranslator.java:55)
	at org.jooq.impl.ExecuteListeners.exception(ExecuteListeners.java:251)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:365)
	at org.jooq.impl.UpdatableRecordImpl.refresh(UpdatableRecordImpl.java:331)
	at org.jooq.impl.UpdatableRecordImpl.refresh(UpdatableRecordImpl.java:321)
	at io.pewpew.stables.StablesApplicationTests.database(StablesApplicationTests.kt:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.sql.SQLException: Connection is closed
	at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:490)
	at com.sun.proxy.$Proxy76.prepareStatement(Unknown Source)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:318)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy$TransactionAwareInvocationHandler.invoke(TransactionAwareDataSourceProxy.java:236)
	at com.sun.proxy.$Proxy85.prepareStatement(Unknown Source)
	at org.jooq.impl.ProviderEnabledConnection.prepareStatement(ProviderEnabledConnection.java:109)
	at org.jooq.impl.SettingsEnabledConnection.prepareStatement(SettingsEnabledConnection.java:73)
	at org.jooq.impl.ProviderEnabledConnection.prepareStatement(ProviderEnabledConnection.java:109)
	at org.jooq.impl.SettingsEnabledConnection.prepareStatement(SettingsEnabledConnection.java:73)
	at org.jooq.impl.AbstractResultQuery.prepare(AbstractResultQuery.java:239)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:322)
	... 33 more
````

**Comment by lukaseder** [comment]
@pilt: I don't think so. In your case, there seems to be a wrongly set up connection pool / data source / transaction manager.

I'll be happy to help you on the mailing list. Please provide some more details on how to reproduce your case:
https://groups.google.com/d/forum/jooq-user

**Comment by TheKSoni** [comment]
Still getting following exception for this code:
```
        DSL.using(connection).dsl()
                .fetchOne("select pg_try_advisory_lock(?)", 1)
                .get(0, Boolean.class);
``` 

``` org.jooq.exception.DataAccessException: SQL [select pg_try_advisory_lock(?)]; Connection is closed
        at org.jooq_3.12.1.DEFAULT.debug(Unknown Source) ~[?:?]
        at org.jooq.impl.Tools.translate(Tools.java:2717) ~[org.jooq.jooq-3.12.1.jar:?]
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:755) ~[org.jooq.jooq-3.12.1.jar:?]
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:383) ~[org.jooq.jooq-3.12.1.jar:?]
        at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:501) ~[org.jooq.jooq-3.12.1.jar:?]
        at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:470) ~[org.jooq.jooq-3.12.1.jar:?]
        at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:484) ~[org.jooq.jooq-3.12.1.jar:?]
        at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:653) ~[org.jooq.jooq-3.12.1.jar:?]
        at org.jooq.impl.DefaultDSLContext.fetchOne(DefaultDSLContext.java:992) ~[org.jooq.jooq-3.12.1.jar:?]
           .
	   ./// Removing Logs of personal codebase
	   .
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_191]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.42.Final.jar:4.1.42.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.sql.SQLException: Connection is closed
        at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:494) ~[com.zaxxer.HikariCP-3.4.1.jar:?]
        at com.sun.proxy.$Proxy49.prepareStatement(Unknown Source) ~[?:?]
        at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:316) ~[com.zaxxer.HikariCP-3.4.1.jar:?]
        at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java) ~[com.zaxxer.HikariCP-3.4.1.jar:?]
        at org.jooq.impl.ProviderEnabledConnection.prepareStatement(ProviderEnabledConnection.java:109) ~[org.jooq.jooq-3.12.1.jar:?]
        at org.jooq.impl.SettingsEnabledConnection.prepareStatement(SettingsEnabledConnection.java:73) ~[org.jooq.jooq-3.12.1.jar:?]
        at org.jooq.impl.AbstractResultQuery.prepare(AbstractResultQuery.java:273) ~[org.jooq.jooq-3.12.1.jar:?]
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:336) ~[org.jooq.jooq-3.12.1.jar:?]
        ... 13 more

```

**Comment by lukaseder** [comment]
@TheKSoni This is a very long discussion, and I think it's quite unlikely you ran into the exact same issue. There can be many reasons why a connection is closed. Can you please open a new issue?

**Comment by TheKSoni** [comment]
Thanks @lukaseder. Opened #9815 .
