### ISSUE TITLE
Accessing an aliased table's record generates a null pointer exception

### ISSUE THREAD

**Issue by er1c** [jOOQ/jOOQ#7625]
### Expected behavior and actual behavior:

Copied from: https://github.com/jOOQ/jOOQ/issues/6439#issuecomment-400931174

```
    val articleCountryFilterTable: TecdocCountryFilter = TECDOC_COUNTRY_FILTER.as("t1")
    val linkageCountryFilterTable: TecdocCountryFilter = TECDOC_COUNTRY_FILTER.as("t2")

...


        db.select(CATALOG.ID,
                CATALOG.SITE_KEY,
...
                articleCountryFilterTable.TECDOC_ID,
                articleCountryFilterTable.NAME,
                linkageCountryFilterTable.TECDOC_ID,
                linkageCountryFilterTable.NAME,
        )
        .from(CATALOG.leftOuterJoin(articleCountryFilterTable).on(CATALOG.TECDOC_ARTICLE_COUNTRY_FILTER_ID.eq(articleCountryFilterTable.ID))
                     .leftOuterJoin(linkageCountryFilterTable).on(CATALOG.TECDOC_LINKAGE_COUNTRY_FILTER_ID.eq(linkageCountryFilterTable.ID))
        .fetchIndexedSeq()

```

Doing a `record.get(articleCountryFilterTable.name)` will trigger a null point exception complaining about `Unknown column 'catalog_development.tecdoc_country_filter.name' in 'field list'` and the generated SQL has: 

```
`t1`.`tecdoc_id`, `t1`.`name`, `t2`.`tecdoc_id`, `t2`.`name`,
```

Stack trace:

```
20:08:48.290 [scala-execution-context-global-102] ERROR f.h.server.ErrorHandlerRequestRouter - Caught Exception
org.jooq.exception.DataAccessException: SQL [select `catalog_development`.`catalog`.`id`, `catalog_development`.`catalog`.`site_key`, `catalog_development`.`catalog`.`tecdoc_id`, `catalog_development`.`catalog`.`user_namespace_id`, `catalog_development`.`catalog`.`tecdoc_brand_filter_id`, `catalog_development`.`catalog`.`tecdoc_article_country_filter_id`, `catalog_development`.`catalog`.`tecdoc_article_country_filter_type_id`, `catalog_development`.`catalog`.`tecdoc_linkage_country_filter_id`, `catalog_development`.`catalog`.`tecdoc_linkage_country_filter_type_id`, `catalog_development`.`catalog`.`tecdoc_language_filter_id`, `catalog_development`.`catalog`.`tecdoc_vehicle_filter_id`, `catalog_development`.`catalog`.`autocare_brand_filter_id`, `catalog_development`.`catalog`.`name`, `catalog_development`.`catalog`.`notes`, `catalog_development`.`catalog`.`created_on`, `catalog_development`.`catalog`.`updated_on`, `catalog_development`.`tecdoc_brand_filter`.`tecdoc_id`, `catalog_development`.`tecdoc_brand_filter`.`name`, `t1`.`tecdoc_id`, `t1`.`name`, `t2`.`tecdoc_id`, `t2`.`name`, `catalog_development`.`tecdoc_country_filter`.`name`, `catalog_development`.`tecdoc_language_filter`.`tecdoc_id`, `catalog_development`.`tecdoc_language_filter`.`name`, `catalog_development`.`tecdoc_vehicle_filter`.`tecdoc_id`, `catalog_development`.`tecdoc_vehicle_filter`.`name`, `catalog_development`.`autocare_brand_filter`.`opticat_key`, `catalog_development`.`autocare_brand_filter`.`name` from `catalog_development`.`catalog` left outer join `catalog_development`.`tecdoc_brand_filter` on `catalog_development`.`catalog`.`tecdoc_brand_filter_id` = `catalog_development`.`tecdoc_brand_filter`.`id` left outer join `catalog_development`.`tecdoc_country_filter` as `t1` on `catalog_development`.`catalog`.`tecdoc_article_country_filter_id` = `t1`.`id` left outer join `catalog_development`.`tecdoc_country_filter` as `t2` on `catalog_development`.`catalog`.`tecdoc_linkage_country_filter_id` = `t2`.`id` left outer join `catalog_development`.`tecdoc_language_filter` on `catalog_development`.`catalog`.`tecdoc_language_filter_id` = `catalog_development`.`tecdoc_language_filter`.`id` left outer join `catalog_development`.`tecdoc_vehicle_filter` on `catalog_development`.`catalog`.`tecdoc_vehicle_filter_id` = `catalog_development`.`tecdoc_vehicle_filter`.`id` left outer join `catalog_development`.`autocare_brand_filter` on `catalog_development`.`catalog`.`autocare_brand_filter_id` = `catalog_development`.`autocare_brand_filter`.`id`]; Unknown column 'catalog_development.tecdoc_country_filter.name' in 'field list'
        at org.jooq_3.10.7.MYSQL.debug(Unknown Source)
        at org.jooq.impl.Tools.translate(Tools.java:2241)
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:704)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:361)
        at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:317)
        at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2597)
        at ta.jooq.rich.RichResultQuery$.fetchIndexedSeq$extension0(RichResultQuery.scala:16)
        at ta.db.mysql.impl.MySQLCatalogSummary$.all(MySQLCatalogSummary.scala:53)
        at ta.db.mysql.dao.MySQLCatalogSummaryDAO$.$anonfun$all$1(MySQLCatalogSummaryDAO.scala:12)
        at ta.db.mysql.MySQL$.$anonfun$asyncReadOnlyTransaction$2(MySQL.scala:67)
        at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$0(DefaultDSLContext.java:473)
        at org.jooq.impl.Tools$10$1.block(Tools.java:4002)
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
        at org.jooq.impl.Tools$10.get(Tools.java:3999)
        at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:518)
        at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:443)
        at ta.db.mysql.MySQL$.$anonfun$asyncReadOnlyTransaction$1(MySQL.scala:67)
        at fm.common.Resource$.using(Resource.scala:24)
        at ta.db.mysql.MySQL$.$anonfun$async$1(MySQL.scala:82)
        at fm.common.TaskRunnerBase$ClearingBlockRunnableWithResult.run(TaskRunnerBase.scala:48)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### Versions:

- jOOQ: "3.10.7"
- Java:
- Database (include vendor): MySQL
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks for your report. What does `fetchIndexedSeq` do?

**Comment by lukaseder** [comment]
Note that the formatted query from your exception seems invalid anyway:

```sql
SELECT
    catalog_development.catalog.id,
    catalog_development.catalog.site_key,
    catalog_development.catalog.tecdoc_id,
    catalog_development.catalog.user_namespace_id,
    catalog_development.catalog.tecdoc_brand_filter_id,
    catalog_development.catalog.tecdoc_article_country_filter_id,
    catalog_development.catalog.tecdoc_article_country_filter_type_id,
    catalog_development.catalog.tecdoc_linkage_country_filter_id,
    catalog_development.catalog.tecdoc_linkage_country_filter_type_id,
    catalog_development.catalog.tecdoc_language_filter_id,
    catalog_development.catalog.tecdoc_vehicle_filter_id,
    catalog_development.catalog.autocare_brand_filter_id,
    catalog_development.catalog.name,
    catalog_development.catalog.notes,
    catalog_development.catalog.created_on,
    catalog_development.catalog.updated_on,
    catalog_development.tecdoc_brand_filter.tecdoc_id,
    catalog_development.tecdoc_brand_filter.name,
    t1.tecdoc_id,
    t1.name,
    t2.tecdoc_id,
    t2.name,
    catalog_development.tecdoc_country_filter.name, -- E.g. this column should be undefined as the tecdoc_country_filter table doesn't exist. It has been renamed to t1/t2
    catalog_development.tecdoc_language_filter.tecdoc_id,
    catalog_development.tecdoc_language_filter.name,
    catalog_development.tecdoc_vehicle_filter.tecdoc_id,
    catalog_development.tecdoc_vehicle_filter.name,
    catalog_development.autocare_brand_filter.opticat_key,
    catalog_development.autocare_brand_filter.name
FROM
    catalog_development.catalog
    LEFT OUTER JOIN catalog_development.tecdoc_brand_filter ON catalog_development.catalog.tecdoc_brand_filter_id = catalog_development.tecdoc_brand_filter.id
    LEFT OUTER JOIN catalog_development.tecdoc_country_filter t1 ON catalog_development.catalog.tecdoc_article_country_filter_id = t1.id
    LEFT OUTER JOIN catalog_development.tecdoc_country_filter t2 ON catalog_development.catalog.tecdoc_linkage_country_filter_id = t2.id
    LEFT OUTER JOIN catalog_development.tecdoc_language_filter ON catalog_development.catalog.tecdoc_language_filter_id = catalog_development.tecdoc_language_filter.id
    LEFT OUTER JOIN catalog_development.tecdoc_vehicle_filter ON catalog_development.catalog.tecdoc_vehicle_filter_id = catalog_development.tecdoc_vehicle_filter.id
    LEFT OUTER JOIN catalog_development.autocare_brand_filter ON catalog_development.catalog.autocare_brand_filter_id = catalog_development.autocare_brand_filter.id
```

**Comment by er1c** [comment]
Mea culpa, I did have an old (non aliased) column still in the selected query, removing it the aliased fields/columns are working as intended.  Thanks!

**Comment by er1c** [comment]
@lukaseder It's simply `def fetchIndexedSeq(): IndexedSeq[R] = q.fetch().asScala.toIndexedSeq`
