### ISSUE TITLE
Cannot use Meta.getSchema() for DROP SCHEMA statement

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7679]
As reported on the jOOQ user group:
----

```java
Schema schema = // from a call to meta() and finding the right schema
 db.getDSLContext().dropSchema(schema.getName()).execute();// works
 db.getDSLContext().dropSchema(schema).execute(); // does not work, see exception below
 db.getDSLContext().execute("drop schema jsl_db"); // works
```

The name of my database is "test" and the schema is obviously "jsl_db"

```
Exception in thread "main" org.jooq.exception.DataAccessException: SQL [drop schema "test"."jsl_db"]; ERROR: syntax error at or near "."
  Position: 19
	at org.jooq_3.10.4.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2239)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:704)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:361)
	at jsl.utilities.reporting.JSLDatabase.dropJSLDbSchema(JSLDatabase.java:345)
	at jsl.utilities.reporting.JSLDatabase.createJSLDatabase(JSLDatabase.java:305)
	at jsl.utilities.reporting.JSLDatabase.createPostgresJSLDatabase(JSLDatabase.java:279)
	at jsl.utilities.reporting.JSLDatabase.createPostgresLocalHostJSLDatabase(JSLDatabase.java:253)
	at ex.queueing.DriverLicenseBureauWithQ.runExperiment(DriverLicenseBureauWithQ.java:264)
	at ex.queueing.DriverLicenseBureauWithQ.main(DriverLicenseBureauWithQ.java:207)
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "."
  Position: 19
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:144)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:429)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:347)
	... 6 more
```

----
See also:
https://groups.google.com/forum/#!topic/jooq-user/tnMjwO-p8sM

**Comment by lukaseder** [comment]
It doesn't work on SQL Server, where the schema is qualified as `[test].[x]` (test being the database), when it should be qualified as `[test].[dbo].[x]`

Will investigate.

**Comment by lukaseder** [comment]
The SQL Server issue is not related to the schema originating from `Meta`: https://github.com/jOOQ/jOOQ/issues/10271
