### ISSUE TITLE
onkey() - No matching Key found between tables when using table alias

### ISSUE THREAD

**Issue by PhilippSalvisberg** [jOOQ/jOOQ#7722]
#### actual
org.jooq.exception.DataAccessException: No matching Key found between tables (...) is thrown when join path is not unique and table aliases are used, even if the relevant join column is specified in the `onKey()` function

#### expected
No exception is thrown. Works as without using table aliases.

#### 1. Environment
according https://www.salvis.com/blog/2018/08/05/view-api-jooq-application/

#### 2. Test (NOT OK)

```
@Test
public void withAliasOnKey() {
   logger.info("--- withAliasOnKey ---");
   EmployeesV emp = EMPLOYEES_V.as("emp");
   DepartmentsV dept = DEPARTMENTS_V.as("dept");
   try { 
      final ResultQuery<?> query = ctx
            .select()
            .from(emp)
            .join(dept).onKey(dept.MANAGER_ID);
      logger.info("on clause: " + query.getSQL().split("on ")[1]);
   } catch (DataAccessException e) {
      // NOT OK, fails with following error message:
      // No matching Key found between tables ["emp"] and ["dept"]
      logger.error("NOT OK, should work", e);
   }
}
```

Output:

```
0    INFO  OnKeyTest          - --- withAliasOnKey ---
343  ERROR OnKeyTest          - NOT OK, should work
org.jooq.exception.DataAccessException: No matching Key found between tables ["emp"] and ["dept"]
	at org.jooq.impl.JoinTable.onKeyException(JoinTable.java:668)
	at org.jooq.impl.JoinTable.onKey(JoinTable.java:606)
	at org.jooq.impl.JoinTable.onKey(JoinTable.java:132)
	at org.jooq.impl.SelectQueryImpl.addJoinOnKey(SelectQueryImpl.java:2487)
	at org.jooq.impl.SelectImpl.onKey(SelectImpl.java:2102)
	at org.jooq.impl.SelectImpl.onKey(SelectImpl.java:139)
	at com.trivadis.jooq.pinkdb.tests.OnKeyTest.withAliasOnKey(OnKeyTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

#### 3. Test (OK)

```
@Test
public void withoutAliasOnKey() {
   logger.info("--- withoutAliasOnKey ---");
   EmployeesV emp = EMPLOYEES_V;
   DepartmentsV dept = DEPARTMENTS_V;
   final ResultQuery<?> query = ctx
         .select()
         .from(emp)
         .join(dept).onKey(dept.MANAGER_ID);
   logger.info("on clause: " + query.getSQL().split("on ")[1]);
}
```

Output:

```
346  INFO  OnKeyTest          - --- withoutAliasOnKey ---
389  INFO  OnKeyTest          - on clause: "HR"."DEPARTMENTS_V"."MANAGER_ID" = "HR"."EMPLOYEES_V"."EMPLOYEE_ID"
```

### Versions:

- jOOQ: 3.11.3
- Java: 1.8.0_161
- Database (include vendor): Oracle Database 18.3.0.0.180717 Enterprise Edition
- OS: macOS 10.13.6 (client), Oracle Linux 7.5 (server)
- JDBC Driver (include name if inofficial driver): ojdbc8.jar

**Comment by lukaseder** [comment]
Thank you very much for your report. On a high level, I think this is the same issue as #7626. Will confirm ASAP.

**Comment by lukaseder** [comment]
Looking into this now. This is indeed the same issue as #7626
