### ISSUE TITLE
Codegen: confusing error when xmlns points to a missing xsd

### ISSUE THREAD

**Issue by retoo** [jOOQ/jOOQ#7798]
When running the Gradle Codegen with a xsd url that does not exist, the codegen aborts with a confusing error.

```xml
<configuration xmlns='http://www.jooq.org/xsd/jooq-codegen-3.10.0.xsd'>
	<jdbc>
		...
	</jdbc>
	<generator>
		...
	</generator>
</configuration>
```
**Note the invalid xmlns: "http://www.jooq.org/xsd/jooq-codegen-3.10.0.xsd" !**

Error:
```
> The <generator/> tag is mandatory. For details, see http://www.jooq.org/xsd/jooq-codegen-3.10.0.xsd
```

When fixing the xsd url the code generator works. 

JOOQ Version: 3.10.7

**Comment by lukaseder** [comment]
Thanks for your report. Can you provide a stack trace and a way to reproduce this problem? I'm assuming you're not using Etienne Studer's third party Gradle plugin, but some other mechanism? https://github.com/etiennestuder/gradle-jooq-plugin

**Comment by retoo** [comment]
Ah, I didn't know about the plugin, nice! 

Here are the details:

Stacktrace

```
Caused by: org.jooq.util.GeneratorException: The <generator/> tag is mandatory. For details, see http://www.jooq.org/xsd/jooq-codegen-3.10.0.xsd
        at org.jooq.util.GenerationTool.run(GenerationTool.java:240)
        at org.jooq.util.GenerationTool.generate(GenerationTool.java:203)
        at org.jooq.util.GenerationTool$generate.call(Unknown Source)
        at build_vslypgi318x3lsnrbvzp$_run_closure4.doCall(/**redacted**:88)
```

build.gradle

```gradle
apply plugin: 'java'
apply plugin: 'idea'

sourceCompatibility = 1.8
version = '1.0'

repositories {
    /* redacted */

    mavenLocal()
    mavenCentral()
}

dependencies {
    runtime 'org.postgresql:postgresql:9.4-1206-jdbc42'
    runtime 'com.microsoft.sqlserver:7.0.0.jre8'

    compile 'com.google.code.gson:gson:2.6.2'
    compile 'org.jooq.pro:jooq:3.10.7'
    compile 'org.jooq.pro:jooq-meta:3.10.7'
    compile 'org.jooq.pro:jooq-codegen:3.10.7'
    compile group: 'com.google.guava', name:'guava', version: '26.0'
    testCompile group: 'junit', name: 'junit', version: '4.11'
}

sourceSets {
    main {
        java {
            srcDir 'src//gen/java/'
        }
    }
}

buildscript {
    repositories {
        /* redacted */

        mavenLocal()
        mavenCentral()
    }

    dependencies {
        classpath 'org.postgresql:postgresql:9.4-1206-jdbc42'
        classpath 'org.jooq.pro:jooq-codegen:3.10.7'

    }
}


task generateCode << {
    // Use your favourite XML builder to construct the code generation configuration file
    // ----------------------------------------------------------------------------------
    def writer = new StringWriter()
    def xml = new groovy.xml.MarkupBuilder(writer)
            .configuration('xmlns': 'http://www.jooq.org/xsd/jooq-codegen-3.10.7.xsd') {
        jdbc() {
            driver() { 'com.microsoft.sqlserver.jdbc.SQLServerDriver' }
            url() { 'redacted' }
            user() { 'redacted' }
            password() { 'redacted' }
        }
        generator() {
            database() {
                name() { 'org.jooq.meta.sqlserver.SQLServerDatabase' }
                schemata() {
                    schema() {
                        inputSchema("redacted")
                        outputSchema("redacted")
                    }
                }
            }
            generate() {
            }

            target() {
                packageName('redacted')
                directory('src/gen/java')
            }
        }
    }

    // Run the code generator
    // ----------------------
    org.jooq.util.GenerationTool.generate(
            javax.xml.bind.JAXB.unmarshal(new StringReader(writer.toString()),
                    org.jooq.util.jaxb.Configuration.class)
    )
}
```

**Comment by lukaseder** [comment]
Hm, there's not an awful lot that jOOQ can do here. The problem happens in your own code when you run:

```java
    org.jooq.util.GenerationTool.generate(
            javax.xml.bind.JAXB.unmarshal(new StringReader(writer.toString()),
                    org.jooq.util.jaxb.Configuration.class)
    )
```

`JAXB.unmarshal()` expects namespaces to be correct. If you call `GenerationTool.generate(String)`, passing the XML string directly, then you can profit from jOOQ's own xmlns lenience logic that can be seen here (i.e. you don't have to pass the correct namespace anymore, it will simply be patched by jOOQ, since no one cares about namespaces):

https://github.com/jOOQ/jOOQ/blob/version-3.10.7/jOOQ-codegen/src/main/java/org/jooq/util/GenerationTool.java#L771

I understand that you got your logic from the manual:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-gradle/

I will fix that section right away to make use of the string representation of the XML config, instead of JAXB: #7799

**Comment by lukaseder** [comment]
Still, I do recommend using the third party plugin. It is much better integrated with Gradle. The author happens to work for Gradle.

**Comment by lukaseder** [comment]
Just to be sure. The quick fix I'm suggesting is to call:

```java
org.jooq.util.GenerationTool.generate(writer.toString());
```

**Comment by retoo** [comment]
Perfect, thank you!

**Comment by retoo** [comment]
@lukaseder pleaes note, the class name is now wrong in 3.11:
https://www.jooq.org/doc/3.11/manual/code-generation/codegen-gradle/

```groovy
- org.jooq.util.GenerationTool.generate(writer.toString());
+ org.jooq.codegen.GenerationTool.generate(writer.toString());
```

**Comment by lukaseder** [comment]
Aw crap. Thank you. All that copy pasting between versioned manuals... Fixed

**Comment by lukaseder** [comment]
Commit here: https://github.com/jOOQ/jOOQ/commit/0569d816a2e07cf95118dcb2f80de5d7b8daaaa1. Building manual now...
