### ISSUE TITLE
Array binding does not use configured bindings per element

### ISSUE THREAD

**Issue by mjburghoffer** [jOOQ/jOOQ#7852]
### Expected behavior and actual behavior:
For array bindings in postgres, the actual binding for each element in the array is simply ignored, and jooq attempts to do the naive java `Object#toString()` method for the element, and then cast the result as the correct type in postgres.  I would expect the array binding to use the element binding instead.

### Steps to reproduce the problem (include example code if possible):
1. Create a table with a custom binding where the `toString` of the bound class is not the correct sql representation of the data.
1. Ensure the custom binding is used by an array type of that table
1. Insert a row into the table

```sql
CREATE TABLE array_binding_example (
  id_scalar uuid NOT NULL,
  id_array uuid[] NOT NULL
);
```

```kotlin
data class ObjectReference(val id: UUID)

class ObjectReferenceConverter : Converter<UUID, ObjectReference> {
    override fun from(databaseObject: UUID?): ObjectReference? = databaseObject?.let { ObjectReference(it) }
    override fun to(userObject: ObjectReference?): UUID? = userObject?.id
    override fun fromType(): Class<UUID> = UUID::class.java
    override fun toType(): Class<ObjectReference> = ObjectReference::class.java
}
```

### Cause
In `org.jooq.impl.DefaultBinding.set0(BindingSetStatementContext<U> ctx, Object[] value)`, in the case of `ctx.family() == POSTGRES`, `ctx.statement().setString(ctx.index(), toPGArrayString(value))` is called, rather than binding an array type.  If this is not possible, then `toPGArrayString()` should take the type as a parameter, so the rendered string uses the actual element binding instead of `Object.toString()`.

`sqlInline0()` has a similar problem, except that the default, HSQLDB syntax would work perfectly for postgres if it were just prepended with the keyword `ARRAY`, because in postgres `ARRAY[1, 2, 3, 4]::int[]` is a valid syntax for an integer array, for example.

### Stack Trace
```
org.jooq.exception.DataAccessException: SQL [insert into "692f9bbd_105f_494d_86e3_62e7fe53cf31"."f6047b9a_f01d_42d6_8f2f_617fc9cc41bd" ("__id", "__created", "employees", "manager") values (cast(? as uuid), cast(? as timestamp), ?::uuid[], cast(? as uuid)) on conflict ("__id") do update set "employees" = "excluded"."employees", "manager" = "excluded"."manager", "__modified" = cast(? as timestamp) returning "692f9bbd_105f_494d_86e3_62e7fe53cf31"."f6047b9a_f01d_42d6_8f2f_617fc9cc41bd"."__id", "692f9bbd_105f_494d_86e3_62e7fe53cf31"."f6047b9a_f01d_42d6_8f2f_617fc9cc41bd"."__created", "692f9bbd_105f_494d_86e3_62e7fe53cf31"."f6047b9a_f01d_42d6_8f2f_617fc9cc41bd"."__modified", "692f9bbd_105f_494d_86e3_62e7fe53cf31"."f6047b9a_f01d_42d6_8f2f_617fc9cc41bd"."__deleted", "692f9bbd_105f_494d_86e3_62e7fe53cf31"."f6047b9a_f01d_42d6_8f2f_617fc9cc41bd"."employees", "692f9bbd_105f_494d_86e3_62e7fe53cf31"."f6047b9a_f01d_42d6_8f2f_617fc9cc41bd"."manager", "692f9bbd_105f_494d_86e3_62e7fe53cf31"."f6047b9a_f01d_42d6_8f2f_617fc9cc41bd"."name"]; ERROR: invalid input syntax for uuid: "ObjectReference(id=36b40ce8-91de-4bdc-a4d6-5c6db2c3f3c8)"
	at org.jooq_3.11.4.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2384)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:811)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:364)
	at org.jooq.impl.InsertImpl.fetch(InsertImpl.java:1055)
    ...
Caused by: org.postgresql.util.PSQLException: ERROR: invalid input syntax for uuid: "ObjectReference(id=36b40ce8-91de-4bdc-a4d6-5c6db2c3f3c8)"
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:106)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.executeQuery(DefaultPreparedStatement.java:94)
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:726)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:350)
	... 72 common frames omitted
```

### Versions:

- jOOQ: 3.11.4
- Java: zulu-10
- Database (include vendor): postgres 9.6
- OS: mac osx

**Comment by lukaseder** [comment]
Thanks for your report. How did you configure your code generator to apply your converter? Do note that you have to create a converter for the `uuid` type *and* the `uuid[]` type, separately right now.

**Comment by lukaseder** [comment]
My guess here is that there was a missing, separate binding for the array type
