### ISSUE TITLE
ArrayStoreException with nested array queries in H2

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#7876]
### Expected behavior and actual behavior:
A query like the following should not result in any runtime exceptions:

```java
DSLContext create = DSL.using(conn, SQLDialect.H2);
create.select(array(1, 2, array(3, 4))).from(dual()).fetch();
```

At the moment this results in a `java.lang.ArrayStoreException`:

```java
Exception in thread "main" org.jooq.exception.DataAccessException: SQL [select (cast(? as int), cast(? as int), (cast(? as int), cast(? as int))) from (select 'X' "DUMMY") "DUAL"]; Error while reading field: array[
  1, 
  2, 
  array[
    3, 
    4
  ]
], at JDBC index: 1
	at org.jooq_3.12.0-SNAPSHOT.H2.debug(Unknown Source)
	at org.jooq_3.12.0-SNAPSHOT.H2.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2429)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:807)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1634)
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1585)
	at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:407)
	at org.jooq.impl.CursorImpl.fetch(CursorImpl.java:393)
	at org.jooq.impl.CursorImpl.fetch(CursorImpl.java:300)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:297)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:350)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:323)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2581)
	at test.Main.main(Main.java:28)
Caused by: java.sql.SQLException: Error while reading field: array[
  1, 
  2, 
  array[
    3, 
    4
  ]
], at JDBC index: 1
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1730)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.operate(CursorImpl.java:1689)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.operate(CursorImpl.java:1)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:125)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1618)
	... 9 more
Caused by: java.lang.ArrayStoreException
	at java.base/java.lang.System.arraycopy(Native Method)
	at java.base/java.util.Arrays.copyOf(Arrays.java:3721)
	at org.jooq.tools.Convert.convertArray(Convert.java:286)
	at org.jooq.tools.Convert$ConvertAll.from(Convert.java:536)
	at org.jooq.tools.Convert.convert0(Convert.java:321)
	at org.jooq.tools.Convert.convert(Convert.java:313)
	at org.jooq.tools.Convert.convert(Convert.java:385)
	at org.jooq.impl.DefaultBinding$DefaultArrayBinding.convertArray(DefaultBinding.java:1137)
	at org.jooq.impl.DefaultBinding$DefaultArrayBinding.get0(DefaultBinding.java:1038)
	at org.jooq.impl.DefaultBinding$DefaultArrayBinding.get0(DefaultBinding.java:1)
	at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:775)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1720)
	... 13 more
```

### Steps to reproduce the problem (include example code if possible):

```java
try (Connection conn = DriverManager.getConnection(url, userName, password)) {
  DSLContext create = DSL.using(conn, SQLDialect.H2);
  create.select(array(1, 2, array(3, 4))).from(dual()).fetch();
}
```

### Versions:

- jOOQ: 3.12
- Java: 10.0.2
- Database (include vendor): H2
- OS: OSX
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks a lot for your report. I can reproduce this from your example. Will investigate

**Comment by lukaseder** [comment]
Interesting that H2 supports this kind of mixed array type. I wish Java didn't support them :) There's no good way to describe such a type in Java, other than `Object[]`

PostgreSQL, for example, supports matrixes. E.g. this works in PostgreSQL:

```sql
select array[array[1, 2], array[3, 4]]
```

Yielding:

```
array         |
--------------|
{{1,2},{3,4}} |
```

But your example:

```sql
select array[1, 2, array[3, 4]]
```

Raises:

```
SQL Error [42804]: ERROR: ARRAY types integer and integer[] cannot be matched
  Position: 20
  ERROR: ARRAY types integer and integer[] cannot be matched
  Position: 20
  ERROR: ARRAY types integer and integer[] cannot be matched
  Position: 20
```

Anyway. Since the query can be expressed using jOOQ, and since jOOQ should have all the type information available in this particular case, jOOQ should definitely be able to read the resulting array from the JDBC driver.

**Comment by katzyn** [comment]
> Interesting that H2 supports this kind of mixed array type.

For a some weird historic reason; they currently create a lot of internal problems in H2 itself. The next version (201) will have typed arrays and the future of untyped (mixed) arrays is currently undecided.

> PostgreSQL, for example, supports matrixes.

Array can contain other arrays in H2 too.

> `select array[1, 2, array[3, 4]]`

In the current H2 attempt to cast such literal to the `INT ARRAY[optionalCardinality] ARRAY[optionalCardinality]` data type silently converts it to `ARRAY[ARRAY[1], ARRAY[2], ARRAY[3, 4]]`. This conversion is not currently performed during a cast to the untyped array, but such behavior can also be changed.

**Comment by lukaseder** [comment]
> > PostgreSQL, for example, supports matrixes.
> 
> Array can contain other arrays in H2 too.

What I meant by this is that in PostgreSQL, the type is declared as such, e.g. `int[][]`, and it shouldn't be possible to mix scalar elements with array elements (I think?).

Anyway, I doubt a lot of people use arrays this way, so this issue here will not be addressed soon, in jOOQ.

**Comment by lukaseder** [comment]
This exception no longer occurs, but we don't support this usage correctly yet. Also, the inferred type on the Java side is wrong.

I'll reject this issue for now, and we'll look into this more thoroughly in a future release via: https://github.com/jOOQ/jOOQ/issues/252
