### ISSUE TITLE
CockroachDB code generation error

### ISSUE THREAD

**Issue by devinrsmith** [jOOQ/jOOQ#7892]
Seems similar to https://github.com/jOOQ/jOOQ/issues/7270

jOOQ version: 3.11.2
CockroachDB version: 2.0.5

WARNING: SQL exception            : Exception while executing meta query: ERROR: relation "information_schema.routines" does not exist

```sql
select
  "r1"."routine_schema",
  "r1"."routine_name",
  "r1"."specific_name",
  "r1"."data_type" as "data_type",
  "r1"."character_maximum_length",
  "r1"."numeric_precision",
  "r1"."numeric_scale",
  "r1"."type_udt_schema",
  "r1"."type_udt_name",
  case
    when count(*) over (partition by
      "r1"."routine_schema",
      "r1"."routine_name"
    ) > 1 then row_number() over (partition by
      "r1"."routine_schema",
      "r1"."routine_name"
     order by "r1"."specific_name")
  end as "overload",
  "pg_catalog"."pg_proc"."proisagg"
from "information_schema"."routines" as "r1"
  join "pg_catalog"."pg_namespace"
  on "pg_catalog"."pg_namespace"."nspname" = "r1"."specific_schema"
  join "pg_catalog"."pg_proc"
  on (
    "pg_catalog"."pg_proc"."pronamespace" = "pg_catalog"."pg_namespace".oid
    and (("pg_catalog"."pg_proc"."proname" || '_') || cast("pg_catalog"."pg_proc".oid as varchar)) = "r1"."specific_name"
  )
where (
  "r1"."routine_schema" in ('public')
  and not("pg_catalog"."pg_proc"."proretset")
  and "r1"."data_type" <> 'trigger'
)
order by
  "r1"."routine_schema" asc,
  "r1"."routine_name" asc,
  "overload" asc
```

```
Sep 24, 2018 6:51:22 PM org.jooq.tools.JooqLogger error
SEVERE: Error while fetching functions
org.jooq.exception.DataAccessException: SQL [select "r1"."routine_schema", "r1"."routine_name", "r1"."specific_name", "r1"."data_type" as "data_type", "r1"."character_maximum_length", "r1"."numeric_precision", "r1"."numeric_scale", "r1"."type_udt_schema", "r1"."type_udt_name", case when count(*) over (partition by "r1"."routine_schema", "r1"."routine_name") > 1 then row_number() over (partition by "r1"."routine_schema", "r1"."routine_name" order by "r1"."specific_name") end as "overload", "pg_catalog"."pg_proc"."proisagg" from "information_schema"."routines" as "r1" join "pg_catalog"."pg_namespace" on "pg_catalog"."pg_namespace"."nspname" = "r1"."specific_schema" join "pg_catalog"."pg_proc" on ("pg_catalog"."pg_proc"."pronamespace" = "pg_catalog"."pg_namespace".oid and (("pg_catalog"."pg_proc"."proname" || ?) || cast("pg_catalog"."pg_proc".oid as varchar)) = "r1"."specific_name") where ("r1"."routine_schema" in (?) and not("pg_catalog"."pg_proc"."proretset") and "r1"."data_type" <> 'trigger') order by "r1"."routine_schema" asc, "r1"."routine_name" asc, "overload" asc]; ERROR: relation "information_schema.routines" does not exist
        at org.jooq_3.11.2.POSTGRES.debug(Unknown Source)
        at org.jooq.impl.Tools.translate(Tools.java:2380)
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:811)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:364)
        at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:323)
        at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2700)
        at org.jooq.meta.postgres.PostgresDatabase.getRoutines0(PostgresDatabase.java:791)
        at org.jooq.meta.AbstractDatabase.getRoutines(AbstractDatabase.java:1664)
        at org.jooq.codegen.JavaGenerator.generateSchemaIfEmpty(JavaGenerator.java:418)
        at org.jooq.codegen.JavaGenerator.generateCatalogIfEmpty(JavaGenerator.java:405)
        at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:379)
        at org.jooq.codegen.GenerationTool.run(GenerationTool.java:750)
        at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:220)
        at org.jooq.codegen.GenerationTool.main(GenerationTool.java:192)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "information_schema.routines" does not exist
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
        at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:132)
        at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
        at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:3479)
        at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:268)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:350)
        ... 10 more
```

Changing from `org.jooq.meta.postgres.PostgresDatabase` to `org.jooq.meta.jdbc.JDBCDatabase` fixes the problem.

**Comment by lukaseder** [comment]
Thanks for your report. I suspect we could test for the presence of the `information_schema.routines` table prior to actually querying it, in a non-logging manner. And in its absence, simply not generate any routines.
