### ISSUE TITLE
jOOQ checker fails with InternalUtils.symbol: tree is null error when checked code has no enclosing method

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7923]
When checking something like this using the `PlainSQLChecker`:

```java
package t;

import org.jooq.impl.DSL;

class PlainSQLFail {
  Object o = DSL.field("abc");
}

The following exception is thrown (but not reported as a compilation error):

```
Exception org.checkerframework.javacutil.BugInCF: InternalUtils.symbol: tree is null
        at org.checkerframework.javacutil.TreeUtils.elementFromTree(TreeUtils.java:423)
        at org.checkerframework.javacutil.TreeUtils.elementFromDeclaration(TreeUtils.java:484)
        at org.jooq.checker.PlainSQLChecker$1.visitMethodInvocation(PlainSQLChecker.java:79)
        at org.jooq.checker.PlainSQLChecker$1.visitMethodInvocation(PlainSQLChecker.java:68)
```

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.12. Backport scheduled for 3.11.6 (#7935) and 3.10.9 (#7936)
