### ISSUE TITLE
SQL with named parameters: PSQLException: Can't infer the SQL type to use for an instance of org.jooq.impl.Val

### ISSUE THREAD

**Issue by slavniyteo** [jOOQ/jOOQ#7940]
Hello. 

Previously I used jooq only with indexed parameters. But now I try named parameters and observe a kinda buggy behaviour. 

### Expected behavior and actual behavior:
Sql request with named parameters executes successfully.

### Steps to reproduce the problem (include example code if possible):
There is a test that explains everyting. When I build simple sql with indexed parameters, everything is ok. But if I use `NamedParameterJdbcTemplate` and `ParamType.NAMED`, I catch an PSQLException.
```java
import lombok.val;
import org.jooq.DSLContext;
import org.jooq.Query;
import org.junit.Before;
import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;

import static org.jooq.conf.ParamType.INDEXED;
import static org.jooq.conf.ParamType.NAMED;
import static org.jooq.impl.DSL.*;
import static org.junit.Assert.assertEquals;

public class JooqTest extends BaseTest {

    @Autowired
    DSLContext jooq;

    @Autowired
    NamedParameterJdbcTemplate namedJdbc;

    @Autowired
    JdbcTemplate jdbc;

    @Before
    public void before() {
        jdbc.update("" +
                "DROP TABLE IF EXISTS table1;" +

                "CREATE TABLE table1 (" +
                "   id INTEGER," +
                "   name VARCHAR" +
                ");" +

                "INSERT INTO table1 " +
                "VALUES (1, 'first'), (2, 'second'), (3, 'third');"
        );
    }

    @Test
    public void named() throws Exception {
        Query query = jooq.select(field("name")).from(table("table1"))
                .where(field("id").eq(param("id", 1)));

        String sql = query.getSQL(NAMED); // select name from table1 where id = :id

        String actual = namedJdbc.queryForObject(sql,
                query.getParams(),
                String.class
        );

        assertEquals("first", actual); // FAILS
    }

    @Test
    public void indexed() throws Exception {
        Query query = jooq.select(field("name")).from(table("table1"))
                .where(field("id").eq(1));

        val sql = query.getSQL(INDEXED); // select name from table1 where id = ?

        String actual = jdbc.queryForObject(sql,
                query.getBindValues().toArray(),
                String.class
        );

        assertEquals("first", actual); // PASSES
    }

}
```

Test `named` fails with following exception: 

```
Caused by: org.postgresql.util.PSQLException: Can't infer the SQL type to use for an instance of org.jooq.impl.Val. Use setObject() with an explicit Types value to specify the type to use.
	at org.postgresql.jdbc.PgPreparedStatement.setObject(PgPreparedStatement.java:949)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy135.setObject(Unknown Source)
	at org.springframework.jdbc.core.StatementCreatorUtils.setValue(StatementCreatorUtils.java:464)
	at org.springframework.jdbc.core.StatementCreatorUtils.setParameterValueInternal(StatementCreatorUtils.java:241)
	at org.springframework.jdbc.core.StatementCreatorUtils.setParameterValue(StatementCreatorUtils.java:156)
	at org.springframework.jdbc.core.PreparedStatementCreatorFactory$PreparedStatementCreatorImpl.setValues(PreparedStatementCreatorFactory.java:292)
	at org.springframework.jdbc.core.PreparedStatementCreatorFactory$PreparedStatementCreatorImpl.createPreparedStatement(PreparedStatementCreatorFactory.java:244)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
	... 44 more
```

### Versions:

- jOOQ: 3.11.5
- Java: 1.8.0_121
- Database (include vendor): Postgresql 9.6
- OS: Docker container based on Ubuntu 16.04 (
- JDBC Driver (include name if inofficial driver): I tested with `org.postgresql:postgresq` v9.4 and 42.2.5.

**Comment by lukaseder** [comment]
Thanks a lot for your report. It appears that this would be more of an issue you'd direct at Spring, as the generated SQL in jOOQ seems as expected, and the stack trace shows that you're getting this error from Spring.
