### ISSUE TITLE
Regression in OffsetDateTime parser when PostgreSQL timestamps have fractional seconds of 1, 2, 4, 5 digit precision

### ISSUE THREAD

**Issue by marshallpierce** [jOOQ/jOOQ#8013]
### Expected behavior and actual behavior:

Desired: OffsetDateTime binding always works.

Occasionally, `parseLocalTime` fails, seemingly because sometimes the fractional seconds are in an unexpected format with fewer than the normal number of digits.

```
Caused by: java.sql.SQLException: Error while reading field: "foo"."created_at", at JDBC index: 3
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1781)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.operate(CursorImpl.java:1740)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.operate(CursorImpl.java:1705)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:125)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1669)
	... 24 common frames omitted
Caused by: java.lang.NumberFormatException: Not a number: 2018-10-25 02:13:30.76066+00
	at org.jooq.impl.DefaultBinding$OffsetDateTimeParser.parseInt(DefaultBinding.java:2540)
	at org.jooq.impl.DefaultBinding$OffsetDateTimeParser.parseLocalTime(DefaultBinding.java:2467)
	at org.jooq.impl.DefaultBinding$OffsetDateTimeParser.offsetDateTime(DefaultBinding.java:2430)
	at org.jooq.impl.DefaultBinding$DefaultOffsetDateTimeBinding.get0(DefaultBinding.java:2606)
	at org.jooq.impl.DefaultBinding$DefaultOffsetDateTimeBinding.get0(DefaultBinding.java:2548)
	at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:773)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1771)
	... 28 common frames omitted

```

### Steps to reproduce the problem (include example code if possible):

- Create a table with a column like this: `  created_at               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`
- Insert some rows
- Fetch them

### Versions:

- jOOQ: 3.11.6
- Java: 11
- Database (include vendor): Postgres 9.6
- OS: Linux x64
- JDBC Driver (include name if inofficial driver): normal postgres 42.2.5

**Comment by marshallpierce** [comment]
I wonder if that representation (5 digit fractional) is actually permissible? `LocalDate#toString()` does 6 digits in that case:

```
jshell> java.time.LocalTime.now().withNano(760660000)
$4 ==> 09:41:36.760660
```

**Comment by marshallpierce** [comment]
Too bad my prior benchmarking managed to not tickle this bug :(

**Comment by lukaseder** [comment]
Thanks for your report. Oh noes... Here goes that release. I'll fix this on Monday with version 3.10.7

**Comment by marshallpierce** [comment]
FWIW plain old psql also uses the 5-digit form in that case, so it's probably not specific to the jdbc driver.

**Comment by lukaseder** [comment]
No, it isn't. I'm sure the old regex handled this and I had simply overlooked it, now expecting "reasonable" fractional second lengths, which is not lenient enough :(

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.12. Backport scheduled to 3.11.7 (#8015)

**Comment by lukaseder** [comment]
Version 3.11.7 has been released and should be available from Maven Central very soon

**Comment by marshallpierce** [comment]
Working well for me, thanks!
