### ISSUE TITLE
Add support for DataType.characterSet()

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8041]
Some databases allow for specifying the character set separately from the collation.

----
See:
https://www.jooq.org/doc/latest/manual/sql-building/ddl-statements/alter-statement/#comment-4191224883

**Comment by efossier** [comment]
This also happens on create table for example:
```sql
CREATE TABLE resource (
    `AutoId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `Name` CHAR(34) CHARACTER SET ascii NOT NULL,
    `DateCreated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `DateUpdated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`AutoId`)
) ENGINE=InnoDB DEFAULT CHARSET ascii;
```

produces the error:
```
org.jooq.impl.ParserException: Token ')' expected: [3:20] ...IGNED NOT NULL AUTO_INCREMENT,
    `Name` CHAR(34) [*]CHARACTER SET ascii NOT NULL,
    `DateCreated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ...
	at org.jooq.impl.ParserContext.expected(ParserImpl.java:8485)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:8052)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:8047)
	at org.jooq.impl.ParserImpl.parseCreateTable(ParserImpl.java:2466)
	at org.jooq.impl.ParserImpl.parseCreate(ParserImpl.java:1834)
	at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:674)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:445)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:432)
	at org.jooq.meta.extensions.ddl.DDLDatabase.load(DDLDatabase.java:207)
	at org.jooq.meta.extensions.ddl.DDLDatabase.load(DDLDatabase.java:181)
	at org.jooq.meta.extensions.ddl.DDLDatabase.create0(DDLDatabase.java:141)
	at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:231)
	at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:220)
	at org.jooq.meta.AbstractDatabase.getDialect(AbstractDatabase.java:202)
	at org.jooq.codegen.AbstractGenerator.logDatabaseParameters(AbstractGenerator.java:155)
	at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:297)
	at org.jooq.codegen.GenerationTool.run(GenerationTool.java:752)
	at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:222)
	at org.jooq.codegen.maven.Plugin.execute(Plugin.java:197)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by lukaseder** [comment]
@efossier Thank you very much for your comment. Indeed, this is a data type modifier, and as such can appear in many places where data types can appear, mostly DDL statements.

**Comment by lukaseder** [comment]
This feature has been requested a few times, and also been observed in the https://www.jooq.org/translate logs a few times. We've supported MySQL `CHARACTER SET` or `CHARSET` syntax in jOOQ 3.12 onwards.
