### ISSUE TITLE
Code generator on PostgreSQL 9.3.9

### ISSUE THREAD

**Issue by lazystone** [jOOQ/jOOQ#8072]
### Expected behavior and actual behavior:
Actual behavior is that code generation fails with following error message, when using `org.jooq.meta.postgres.PostgresDatabase` dialect:
```
SQL exception            : Exception while executing meta query: ERROR: could not determine interpretation of row comparison operator =
  Hint: Row comparison operators must be associated with btree operator families.
  Position: 1119
```
```sql
select 
  "tables"."table_schema", 
  "tables"."table_name", 
  "tables"."specific_name", 
  "tables"."table_valued_function", 
  "tables"."materialized_view", 
  "tables"."description"
from (
  (
    select 
      "information_schema"."tables"."table_schema", 
      "information_schema"."tables"."table_name", 
      "information_schema"."tables"."table_name" as "specific_name", 
      false as "table_valued_function", 
      false as "materialized_view", 
      "pg_catalog"."pg_description"."description"
    from "information_schema"."tables"
      join "pg_catalog"."pg_namespace"
      on "information_schema"."tables"."table_schema" = "pg_catalog"."pg_namespace"."nspname"
      join "pg_catalog"."pg_class"
      on (
        "pg_catalog"."pg_class"."relname" = "information_schema"."tables"."table_name"
        and "pg_catalog"."pg_class"."relnamespace" = "pg_catalog"."pg_namespace".oid
      )
      left outer join "pg_catalog"."pg_description"
      on (
        "pg_catalog"."pg_description"."objoid" = "pg_catalog"."pg_class".oid
        and "pg_catalog"."pg_description"."objsubid" = 0
      )
    where (
      "information_schema"."tables"."table_schema" in ('booking')
      and ("information_schema"."tables"."table_schema", "information_schema"."tables"."table_name") not in (
        select 
          "pg_catalog"."pg_namespace"."nspname", 
          "pg_catalog"."pg_class"."relname"
        from "pg_catalog"."pg_class"
          join "pg_catalog"."pg_namespace"
          on "pg_catalog"."pg_class"."relnamespace" = "pg_catalog"."pg_namespace".oid
        where "pg_catalog"."pg_class"."relkind" = 'm'
      )
    )
  )
  union all (
    select 
      "pg_catalog"."pg_namespace"."nspname", 
      "pg_catalog"."pg_class"."relname", 
      "pg_catalog"."pg_class"."relname", 
      false as "table_valued_function", 
      true as "materialized_view", 
      "pg_catalog"."pg_description"."description"
    from "pg_catalog"."pg_class"
      join "pg_catalog"."pg_namespace"
      on "pg_catalog"."pg_class"."relnamespace" = "pg_catalog"."pg_namespace".oid
      left outer join "pg_catalog"."pg_description"
      on (
        "pg_catalog"."pg_description"."objoid" = "pg_catalog"."pg_class".oid
        and "pg_catalog"."pg_description"."objsubid" = 0
      )
    where (
      "pg_catalog"."pg_namespace"."nspname" in ('booking')
      and "pg_catalog"."pg_class"."relkind" = 'm'
    )
  )
  union all (
    select 
      "information_schema"."routines"."routine_schema", 
      "information_schema"."routines"."routine_name", 
      "information_schema"."routines"."specific_name", 
      true as "table_valued_function", 
      false as "materialized_view", 
      ''
    from "information_schema"."routines"
      join "pg_catalog"."pg_namespace"
      on "information_schema"."routines"."specific_schema" = "pg_catalog"."pg_namespace"."nspname"
      join "pg_catalog"."pg_proc"
      on (
        "pg_catalog"."pg_proc"."pronamespace" = "pg_catalog"."pg_namespace".oid
        and (("pg_catalog"."pg_proc"."proname" || '_') || cast("pg_catalog"."pg_proc".oid as varchar)) = "information_schema"."routines"."specific_name"
      )
    where (
      "information_schema"."routines"."routine_schema" in ('booking')
      and "pg_catalog"."pg_proc"."proretset"
    )
  )
) as "tables"
order by 
  1, 
  2
```
```
Error while fetching tables
org.jooq.exception.DataAccessException: SQL [select "tables"."table_schema", "tables"."table_name", "tables"."specific_name", "tables"."table_valued_function", "tables"."materialized_view", "tables"."description" from ((select "information_schema"."tables"."table_schema", "information_schema"."tables"."table_name", "information_schema"."tables"."table_name" as "specific_name", false as "table_valued_function", false as "materialized_view", "pg_catalog"."pg_description"."description" from "information_schema"."tables" join "pg_catalog"."pg_namespace" on "information_schema"."tables"."table_schema" = "pg_catalog"."pg_namespace"."nspname" join "pg_catalog"."pg_class" on ("pg_catalog"."pg_class"."relname" = "information_schema"."tables"."table_name" and "pg_catalog"."pg_class"."relnamespace" = "pg_catalog"."pg_namespace".oid) left outer join "pg_catalog"."pg_description" on ("pg_catalog"."pg_description"."objoid" = "pg_catalog"."pg_class".oid and "pg_catalog"."pg_description"."objsubid" = ?) where ("information_schema"."tables"."table_schema" in (?) and ("information_schema"."tables"."table_schema", "information_schema"."tables"."table_name") not in (select "pg_catalog"."pg_namespace"."nspname", "pg_catalog"."pg_class"."relname" from "pg_catalog"."pg_class" join "pg_catalog"."pg_namespace" on "pg_catalog"."pg_class"."relnamespace" = "pg_catalog"."pg_namespace".oid where "pg_catalog"."pg_class"."relkind" = 'm'))) union all (select "pg_catalog"."pg_namespace"."nspname", "pg_catalog"."pg_class"."relname", "pg_catalog"."pg_class"."relname", false as "table_valued_function", true as "materialized_view", "pg_catalog"."pg_description"."description" from "pg_catalog"."pg_class" join "pg_catalog"."pg_namespace" on "pg_catalog"."pg_class"."relnamespace" = "pg_catalog"."pg_namespace".oid left outer join "pg_catalog"."pg_description" on ("pg_catalog"."pg_description"."objoid" = "pg_catalog"."pg_class".oid and "pg_catalog"."pg_description"."objsubid" = ?) where ("pg_catalog"."pg_namespace"."nspname" in (?) and "pg_catalog"."pg_class"."relkind" = 'm')) union all (select "information_schema"."routines"."routine_schema", "information_schema"."routines"."routine_name", "information_schema"."routines"."specific_name", true as "table_valued_function", false as "materialized_view", '' from "information_schema"."routines" join "pg_catalog"."pg_namespace" on "information_schema"."routines"."specific_schema" = "pg_catalog"."pg_namespace"."nspname" join "pg_catalog"."pg_proc" on ("pg_catalog"."pg_proc"."pronamespace" = "pg_catalog"."pg_namespace".oid and (("pg_catalog"."pg_proc"."proname" || ?) || cast("pg_catalog"."pg_proc".oid as varchar)) = "information_schema"."routines"."specific_name") where ("information_schema"."routines"."routine_schema" in (?) and "pg_catalog"."pg_proc"."proretset"))) as "tables" order by 1, 2]; ERROR: could not determine interpretation of row comparison operator =
  Hint: Row comparison operators must be associated with btree operator families.
  Position: 1119
        at org.jooq_3.11.7.POSTGRES.debug(Unknown Source)
        at org.jooq.impl.Tools.translate(Tools.java:2384)
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:811)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:364)
        at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:323)
        at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2700)
        at org.jooq.meta.postgres.PostgresDatabase.getTables0(PostgresDatabase.java:436)
        at org.jooq.meta.AbstractDatabase.getTables(AbstractDatabase.java:1274)
        at org.jooq.codegen.JavaGenerator.generateSchemaIfEmpty(JavaGenerator.java:419)
        at org.jooq.codegen.JavaGenerator.generateCatalogIfEmpty(JavaGenerator.java:405)
        at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:379)
        at org.jooq.codegen.GenerationTool.run(GenerationTool.java:750)
        at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:216)
```

When I try to execute SQL query above in pgAdmin I get slightly different error message:
```
ERROR:  could not determine interpretation of row comparison operator =
LINE 32: ...chema", "information_schema"."tables"."table_name") not in (
                                                                    ^
HINT:  Row comparison operators must be associated with btree operator families.
SQL state: 0A000
Character: 1298
```

If I use `org.jooq.meta.jdbc.JDBCDatabase` it generates code without exceptions.

### Versions:

- jOOQ: 3.11.7
- Java: 11.0.1
- Database (include vendor): `PostgreSQL 9.3.9 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11), 64-bit`
- OS: linux
- JDBC Driver: `org.postgresql:postgresql:42.2.5`

**Comment by lukaseder** [comment]
Thank you very much for your report. I see, this seems to be another variant of the previously fixed issue #7270, where these predicates didn't work on other databases, but in that case we were using `(a, b) in (select ..)`, not `(a, b) not in (select ..)`

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.12. Backport scheduled for 3.11.8 (#8073)

**Comment by lazystone** [comment]
OMG, guys, you rock! Thanks!

**Comment by lazystone** [comment]
Just tried code generation on 3.11.9 but it fails with exactly same stack trace and generates exactly same sql query.

@lukaseder can we reopen this issue? Or I can create a new one.

**Comment by lazystone** [comment]
Yep, it's 3.11.9 and the only difference in the stacktrace is version number:
```
  Hint: Row comparison operators must be associated with btree operator families.
  Position: 1119
        at org.jooq_3.11.9.POSTGRES.debug(Unknown Source)
        at org.jooq.impl.Tools.translate(Tools.java:2384)
 ```

**Comment by lukaseder** [comment]
I see now, the check we're running is this one:

```java
    boolean canUseTupleInPredicates() {
        if (canUseTupleInPredicates == null) {

            // [#7270] The tuple in predicate is not implemented in all PostgreSQL
            //         style databases, e.g. CockroachDB
            // [#8072] Some database versions might support in, but not not in
            try {
                create(true).select(field("(1, 2) in (select 1, 2)")).fetch();
                create(true).select(field("(1, 2) not in (select 1, 2)")).fetch();
                canUseTupleInPredicates = true;
            }
            catch (DataAccessException e) {
                canUseTupleInPredicates = false;
            }
        }

        return canUseTupleInPredicates;
    }
```

It seems that `(1, 2) not in (select 1, 2)` works in PostgreSQL 9.3, so this check isn't sufficient to validate whether the feature is available.

However, I just ran the entire query on the latest docker pull of PostgreSQL 9.3, which is:

```
 PostgreSQL 9.3.25 on x86_64-pc-linux-gnu (Debian 9.3.25-1.pgdg90+1), compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
```

And the query jOOQ runs ran perfectly. There had been tons of fixes in 9.3 since your version:
https://www.postgresql.org/docs/9.3/release.html

So, I simply suggest upgrading your PostgreSQL version.

**Comment by lazystone** [comment]
> So, I simply suggest upgrading your PostgreSQL version.

That's unfortunately the case where it's impossible: we write integration layer and have access to the read-only replicas of 3rd party databases(so we don't own those).

**Comment by lukaseder** [comment]
I understand, but this seems to be something rather difficult to work around in jOOQ - it seems to have been a bug in some patch release of PostgreSQL, which has been superseded by 14 newer patch releases. Would patching jOOQ or overriding the `PostgresDatabase` and reflectively setting this `canUseTupleInPredicates` flag to `false` be an option?

I mean, we're not going to support  PostgreSQL 9.3.9 explicitly by running integration tests on that specific version, so something like this will probably break again in the future as we add a new query to the `PostgresDatabase`...

**Comment by lazystone** [comment]
Yeah, understand that.

Thanks for help!
