### ISSUE TITLE
default non nullable columns not respected when using DAOs

### ISSUE THREAD

**Issue by pdeva** [jOOQ/jOOQ#8079]
### Expected behavior and actual behavior:
Using JOOQ generated pojo and DAO objects to insert a row.
If the 'default' column field is not assigned, JOOQ tries to insert null instead of default value.

### Steps to reproduce the problem
```
CREATE TABLE public.user
(
  user_id UUID DEFAULT  gen_random_uuid() UNIQUE NOT NULL ,
  email varchar (128) PRIMARY KEY NOT NULL,
  account_id varchar(24) NOT NULL
);
```

Code:

```
val u = User()
u.accountId = "xx"
u.email = "yy"
UserDao(jooqConfig).insert(u)
```

Exception:

```
Caused by: org.springframework.dao.DataIntegrityViolationException: jOOQ; SQL [insert into "public"."user" ("user_id", "email", "account_id" ) values (cast(? as uuid), ?, ?) returning "public"."user"."email"ERROR: null value in column "user_id" violates not-null constraint
  Detail: Failing row contains (null, xx, yy).; nested exception is org.postgresql.util.PSQLException: ERROR: null value in column "user_id" violates not-null constraint

at org.jooq_3.11.2.POSTGRES.debug(Unknown Source) ~[?:?]
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:246) ~[spring-jdbc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72) ~[spring-jdbc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.translate(JooqExceptionTranslator.java:93) ~[spring-boot-autoconfigure-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.handle(JooqExceptionTranslator.java:82) ~[spring-boot-autoconfigure-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.exception(JooqExceptionTranslator.java:55) ~[spring-boot-autoconfigure-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.jooq.impl.ExecuteListeners.exception(ExecuteListeners.java:251) ~[jooq-3.11.2.jar:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:365) ~[jooq-3.11.2.jar:?]
	at org.jooq.impl.TableRecordImpl.storeInsert0(TableRecordImpl.java:202) ~[jooq-3.11.2.jar:?]
	at org.jooq.impl.TableRecordImpl$1.operate(TableRecordImpl.java:173) ~[jooq-3.11.2.jar:?]
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:125) ~[jooq-3.11.2.jar:?]
	at org.jooq.impl.TableRecordImpl.storeInsert(TableRecordImpl.java:169) ~[jooq-3.11.2.jar:?]
	at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:157) ~[jooq-3.11.2.jar:?]
	at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:152) ~[jooq-3.11.2.jar:?]
	at org.jooq.impl.DAOImpl.insert(DAOImpl.java:174) ~[jooq-3.11.2.jar:?]
	at org.jooq.impl.DAOImpl.insert(DAOImpl.java:150) ~[jooq-3.11.2.jar:?]
```
### Versions:

- jOOQ: 3.11.2
- Java: 8
- Database (include vendor): Postgres 10
- OS: Linux
- JDBC Driver (include name if inofficial driver): official postgres driver

**Comment by pdeva** [comment]
invalid bug. seems like i had an outdated build which didnt use the latest schema to generate the code.
