### ISSUE TITLE
jOOQ Meta executed a slow query Postgres

### ISSUE THREAD

**Issue by aleksandar78** [jOOQ/jOOQ#8092]
I see this warning in the console when Jooq code generation task is executed.
Strange thing is that until today I've never seen this message. 
What could be the reason? 
Some change on data model or something else? 
A database is not huge, 233 tables and data with the blob at max 1gb. 
There is one big view with almost 380 columns, merged with 30 tables.  

### Versions:

- jOOQ: 3.11.7 Trial
- Java: Oracle 1.8.0_161
- Database (include vendor): Postgres 9.4
- OS: Linux
- JDBC Driver (include name if inofficial driver): postgres v.42.2.1

```log
Dec 06, 2018 2:56:33 PM org.jooq.tools.JooqLogger warn
WARNING: Slow SQL                 : Total: 01:35
Dec 06, 2018 2:56:33 PM org.jooq.tools.JooqLogger warn
WARNING: Slow SQL                 : jOOQ Meta executed a slow query (slower than 5 seconds, configured by configuration/generator/database/logSlowQueriesAfterSeconds)
```
```sql
select 
  "tables"."table_schema", 
  "tables"."table_name", 
  "tables"."specific_name", 
  "tables"."table_valued_function", 
  "tables"."materialized_view", 
  "tables"."description"
from (
  (
    select 
      "information_schema"."tables"."table_schema", 
      "information_schema"."tables"."table_name", 
      "information_schema"."tables"."table_name" as "specific_name", 
      false as "table_valued_function", 
      false as "materialized_view", 
      "pg_catalog"."pg_description"."description"
    from "information_schema"."tables"
      join "pg_catalog"."pg_namespace"
      on "information_schema"."tables"."table_schema" = "pg_catalog"."pg_namespace"."nspname"
      join "pg_catalog"."pg_class"
      on (
        "pg_catalog"."pg_class"."relname" = "information_schema"."tables"."table_name"
        and "pg_catalog"."pg_class"."relnamespace" = "pg_catalog"."pg_namespace".oid
      )
      left outer join "pg_catalog"."pg_description"
      on (
        "pg_catalog"."pg_description"."objoid" = "pg_catalog"."pg_class".oid
        and "pg_catalog"."pg_description"."objsubid" = 0
      )
    where (
      "information_schema"."tables"."table_schema" in ('eris')
      and ("information_schema"."tables"."table_schema", "information_schema"."tables"."table_name") not in (
        select 
          "pg_catalog"."pg_namespace"."nspname", 
          "pg_catalog"."pg_class"."relname"
        from "pg_catalog"."pg_class"
          join "pg_catalog"."pg_namespace"
          on "pg_catalog"."pg_class"."relnamespace" = "pg_catalog"."pg_namespace".oid
        where "pg_catalog"."pg_class"."relkind" = 'm'
      )
    )
  )
  union all (
    select 
      "pg_catalog"."pg_namespace"."nspname", 
      "pg_catalog"."pg_class"."relname", 
      "pg_catalog"."pg_class"."relname", 
      false as "table_valued_function", 
      true as "materialized_view", 
      "pg_catalog"."pg_description"."description"
    from "pg_catalog"."pg_class"
      join "pg_catalog"."pg_namespace"
      on "pg_catalog"."pg_class"."relnamespace" = "pg_catalog"."pg_namespace".oid
      left outer join "pg_catalog"."pg_description"
      on (
        "pg_catalog"."pg_description"."objoid" = "pg_catalog"."pg_class".oid
        and "pg_catalog"."pg_description"."objsubid" = 0
      )
    where (
      "pg_catalog"."pg_namespace"."nspname" in ('eris')
      and "pg_catalog"."pg_class"."relkind" = 'm'
    )
  )
  union all (
    select 
      "information_schema"."routines"."routine_schema", 
      "information_schema"."routines"."routine_name", 
      "information_schema"."routines"."specific_name", 
      true as "table_valued_function", 
      false as "materialized_view", 
      ''
    from "information_schema"."routines"
      join "pg_catalog"."pg_namespace"
      on "information_schema"."routines"."specific_schema" = "pg_catalog"."pg_namespace"."nspname"
      join "pg_catalog"."pg_proc"
      on (
        "pg_catalog"."pg_proc"."pronamespace" = "pg_catalog"."pg_namespace".oid
        and (("pg_catalog"."pg_proc"."proname" || '_') || cast("pg_catalog"."pg_proc".oid as varchar)) = "information_schema"."routines"."specific_name"
      )
    where (
      "information_schema"."routines"."routine_schema" in ('eris')
      and "pg_catalog"."pg_proc"."proretset"
    )
  )
) as "tables"
order by 
  1, 
  2
```
```log
org.jooq.meta.AbstractDatabase$1$SQLPerformanceWarning
	at org.jooq.meta.AbstractDatabase$1.executeEnd(AbstractDatabase.java:292)
	at org.jooq.impl.ExecuteListeners.executeEnd(ExecuteListeners.java:181)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:269)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:350)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:323)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2700)
	at org.jooq.meta.postgres.PostgresDatabase.getTables0(PostgresDatabase.java:436)
	at org.jooq.meta.AbstractDatabase.getTables(AbstractDatabase.java:1274)
	at org.jooq.meta.SchemaDefinition.getTables(SchemaDefinition.java:71)
	at org.jooq.codegen.JavaGenerator.generateSchema(JavaGenerator.java:4561)
	at org.jooq.codegen.JavaGenerator.generateSchema(JavaGenerator.java:4527)
	at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:497)
	at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:458)
	at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:380)
	at org.jooq.codegen.GenerationTool.run(GenerationTool.java:750)
	at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:220)
	at org.jooq.codegen.GenerationTool.main(GenerationTool.java:192)
```

**Comment by lukaseder** [comment]
Thank you very much for reporting this. There can be many reasons of course. Like any other tables these tables have indexes / statistics, etc. Perhaps there was a change to your schema that was not reflected in the statistics? Or some other reason why the execution plan was not optimal? Or perhaps the query just took 4.9 seconds before and now takes 5.1 seconds? Or do you have a large number of additional routines?

How can this be reproduced?

**Comment by lukaseder** [comment]
Alright, thanks for the feedback!
