### ISSUE TITLE
Support for Postgres jsonb type using Reactive PG Driver

### ISSUE THREAD

**Issue by sowmyark** [jOOQ/jOOQ#8106]
### Expected behavior and actual behavior:
Using JOOQ with Vertx-Jooq(https://github.com/jklingsporn/vertx-jooq) using Reactive Pg Client API (https://github.com/reactiverse/reactive-pg-client) 

Reactive PG API maps the jsonb column in postgres to type io.reactiverse.pgclient.data.Json. 
We have a converter in place which converts this to Vertx JsonObject.
While fetching data works with this converter, not able to insert/update data into this column due to the below exception.

Exception:

```
org.jooq.exception.SQLDialectNotSupportedException: Type class io.reactiverse.pgclient.impl.data.JsonImpl is not supported in dialect DEFAULT

[INFO] 	at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:884)
[INFO] 	at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:823)
[INFO] 	at org.jooq.impl.DSL.getDataType(DSL.java:21667)
[INFO] 	at org.jooq.impl.DSL.val(DSL.java:19460)
[INFO] 	at Model.ObjectToJsonObjectBinding.sql(ObjectToJsonObjectBinding.java:59)
[INFO] 	at org.jooq.impl.Val.accept(Val.java:80)
[INFO] 	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:509)
[INFO] 	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:446)
[INFO] 	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:207)
[INFO] 	at org.jooq.impl.FieldMapsForInsert.toSQL92Values(FieldMapsForInsert.java:255)
[INFO] 	at org.jooq.impl.FieldMapsForInsert.toSQL92Values(FieldMapsForInsert.java:226)
[INFO] 	at org.jooq.impl.FieldMapsForInsert.accept(FieldMapsForInsert.java:114)
[INFO] 	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:509)
[INFO] 	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:446)
[INFO] 	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:207)
[INFO] 	at org.jooq.impl.InsertQueryImpl.toSQLInsert(InsertQueryImpl.java:617)
[INFO] 	at org.jooq.impl.InsertQueryImpl.accept0(InsertQueryImpl.java:508)
[INFO] 	at org.jooq.impl.AbstractDMLQuery.accept(AbstractDMLQuery.java:396)
[INFO] 	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:509)
[INFO] 	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:446)
[INFO] 	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:207)
[INFO] 	at org.jooq.impl.DefaultDSLContext.renderNamedParams(DefaultDSLContext.java:692)
[INFO] 	at org.jooq.impl.AbstractQuery.getSQL(AbstractQuery.java:569)
[INFO] 	at org.jooq.impl.AbstractDelegatingQuery.getSQL(AbstractDelegatingQuery.java:112)
[INFO] 	at io.github.jklingsporn.vertx.jooq.shared.reactive.AbstractReactiveQueryExecutor.toPreparedQuery(AbstractReactiveQueryExecutor.java:52)
[INFO] 	at io.github.jklingsporn.vertx.jooq.classic.reactivepg.ReactiveClassicGenericQueryExecutor.execute(ReactiveClassicGenericQueryExecutor.java:65)
[INFO] 	at io.github.jklingsporn.vertx.jooq.classic.reactivepg.ReactiveClassicGenericQueryExecutor.execute(ReactiveClassicGenericQueryExecutor.java:24)
[INFO] 	at io.github.jklingsporn.vertx.jooq.shared.internal.AbstractVertxDAO.insert(AbstractVertxDAO.java:124)
[INFO] 	at io.github.jklingsporn.vertx.jooq.shared.internal.AbstractVertxDAO.insert(AbstractVertxDAO.java:118)
[INFO] 	at com.mahaswami.training.JsonTestVerticle.start(JsonTestVerticle.java:47)
```

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):
Converter Code

```java
public class ObjectToJsonObjectBinding implements Binding<Object, JsonObject> {

    private static final Converter<Object, JsonObject> CONVERTER = new Converter<Object, JsonObject>() {
        @Override
        public JsonObject from(Object databaseJsonObject) {
            Json pgJsonWrapper = convertobject(databaseJsonObject, Json.class);
            return convertobject(pgJsonWrapper.value(), toType());
        }

        private <U> U convertobject(Object object, Class<U> type) {
            if (!type.isInstance(object)) {
                throw new IllegalArgumentException("Expected Vert.x JSON type: " + type + ", but got: " + object);
            }
            return (U) object;
        }

        @Override
        public Object to(JsonObject vertxJsonObject) {
            return io.reactiverse.pgclient.data.Json.create(vertxJsonObject);
        }

        @Override
        public Class<Object> fromType() {
            return Object.class;
        }

        @Override
        public Class<JsonObject> toType() {
            return JsonObject.class;
        }
    };

    // The converter does all the work
    @Override
    public Converter<Object, JsonObject> converter() {
        return CONVERTER;
    }

    // Rending a bind variable for the binding context's value and casting it to the json type
    @Override
    public void sql(BindingSQLContext<JsonObject> ctx) throws SQLException {
        // Depending on how you generate your SQL, you may need to explicitly distinguish
        // between jOOQ generating bind variables or inlined literals. If so, use this check:
        // ctx.render().paramType() == INLINED
        ctx.render().visit(DSL.val(ctx.convert(converter()).value())).sql("::jsonb");
    }

    // Registering VARCHAR types for JDBC CallableStatement OUT parameters
    @Override
    public void register(BindingRegisterContext<JsonObject> ctx) throws SQLException {
        ctx.statement().registerOutParameter(ctx.index(), Types.VARCHAR);
    }

    // Converting the JsonObject to a String value and setting that on a JDBC PreparedStatement
    @Override
    public void set(BindingSetStatementContext<JsonObject> ctx) throws SQLException {
        ctx.statement().setString(ctx.index(), Objects.toString(ctx.convert(converter()).value(), null));
    }

    // Getting a String value from a JDBC ResultSet and converting that to a JsonObject
    @Override
    public void get(BindingGetResultSetContext<JsonObject> ctx) throws SQLException {
        ctx.convert(converter()).value(ctx.resultSet().getString(ctx.index()));
    }

    // Getting a String value from a JDBC CallableStatement and converting that to a JsonObject
    @Override
    public void get(BindingGetStatementContext<JsonObject> ctx) throws SQLException {
        ctx.convert(converter()).value(ctx.statement().getString(ctx.index()));
    }

    // Setting a value on a JDBC SQLOutput (useful for Oracle OBJECT types)
    @Override
    public void set(BindingSetSQLOutputContext<JsonObject> ctx) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    // Getting a value from a JDBC SQLInput (useful for Oracle OBJECT types)
    @Override
    public void get(BindingGetSQLInputContext<JsonObject> ctx) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }
}
```

### Versions:

- jOOQ: 3.11.5
- Java: 8
- Database (include vendor): Postgres 9.5
- OS: Linux Mint
- JDBC Driver (include name if inofficial driver): Not using JDBC. Using Reactive PG 0.10.6
(https://github.com/reactiverse/reactive-pg-client)

**Comment by lukaseder** [comment]
Thank you very much for your request. The problem is here:

```java
        @Override
        public Object to(JsonObject vertxJsonObject) {
            return io.reactiverse.pgclient.data.Json.create(vertxJsonObject);
        }
```

You cannot expect jOOQ or the JDBC driver to know what to do with an arbitrary third party Json object type. When you implement the `org.jooq.Binding` SPI, you have to implement the low level stuff yourself. This means that your `sql()` method may just as well only output a bind variable marker.

The example you've copied from the manual assumes that the converter returns a type that is understandable by the JDBC driver and by jOOQ, which is why wrapping it as a `DSL.val()` is possible. But in your case, why not just write:

```java
    @Override
    public void sql(BindingSQLContext<JsonObject> ctx) throws SQLException {
        ctx.render().sql("?::jsonb");
    }
```

Hope this helps

**Comment by mustang666** [comment]
Hello. 
Anyone there with a plausible solution for this? The solution above didn't work for me.

is there any working converter for JSONB to working with reactive-pg-client ?

I'm having this problem that I present below.

> ErrorResponse{severity='ERROR', code='42P18', message='could not determine data type of parameter $4', detail='null', hint='null', position='null', internalPosition='null', internalQuery='null', where='null', file='postgres.c', line='1350', routine='exec_parse_message', schema='null', table='null', column='null', dataType='null', constraint='null'}

However it's generating the right query and it works if I run it directly on database.
```
insert into "provision".
    "messages" ("device",
                "time",
                "duplicate",
                "encryption",
                "message_type")
values (
        '1B1801',
        timestamp with time zone '2019-05-14 11:05:58.656+01:00',
        false,
        '{"name": "John"}'::jsonb,
        'DAILY');
```


My Converter:
```
public class JSONBConverter extends AbstractConverter<Object, JsonObject> {

    private static final long serialVersionUID = 3766805191329452710L;

    public JSONBConverter() {
		super( Object.class, JsonObject.class );
	}

	@Override
	public JsonObject from( Object databaseObject ) {
		return databaseObject == null ? null : Json.decodeValue( "" + databaseObject, JsonObject.class );
	}

	@Override
	public String to( JsonObject userObject ) {
		return userObject == null ? null : Json.encode( userObject );
	}
}
```
My Binding:

```
public class JSONBBinding implements Binding<Object, JsonObject> {

    private static final long serialVersionUID = 170027875872398834L;

    @Override
	public Converter<Object, JsonObject> converter() {
		return new JSONBConverter();
	}

	// Rending a bind variable for the binding context's value and casting it to the json type
	@Override
	public void sql( BindingSQLContext<JsonObject> ctx ) {
		ctx.render().visit( DSL.val( ctx.convert( converter() ).value() ) ).sql( "::jsonb" );
	//	ctx.render().castMode( RenderContext.CastMode.NEVER).sql( DSL.val( ctx.convert( converter() ).value() )+"::jsonb" );
	}

	// Registering VARCHAR types for JDBC CallableStatement OUT parameters
	@Override
	public void register( BindingRegisterContext<JsonObject> ctx ) throws SQLException {
		ctx.statement().registerOutParameter( ctx.index(), Types.VARCHAR );
	}

	// Converting the JsonElement to a String value and setting that on a JDBC PreparedStatement
	@Override
	public void set( BindingSetStatementContext<JsonObject> ctx ) throws SQLException {
		ctx.statement().setString( ctx.index(), Objects.toString( ctx.convert( converter() ).value(), null ) );
	}

	// Getting a String value from a JDBC ResultSet and converting that to a JsonElement
	@Override
	public void get( BindingGetResultSetContext<JsonObject> ctx ) throws SQLException {
		ctx.convert( converter() ).value( ctx.resultSet().getString( ctx.index() ) );
	}

	// Getting a String value from a JDBC CallableStatement and converting that to a JsonElement
	@Override
	public void get( BindingGetStatementContext<JsonObject> ctx ) throws SQLException {
		ctx.convert( converter() ).value( ctx.statement().getString( ctx.index() ) );
	}

	// Setting a value on a JDBC SQLOutput (useful for Oracle OBJECT types)
	@Override
	public void set( BindingSetSQLOutputContext<JsonObject> ctx ) throws SQLException {
		throw new SQLFeatureNotSupportedException();
	}

	// Getting a value from a JDBC SQLInput (useful for Oracle OBJECT types)
	@Override
	public void get( BindingGetSQLInputContext<JsonObject> ctx ) throws SQLException {
		throw new SQLFeatureNotSupportedException();
	}
}
```
Jooq Xml Config:
```
                <forcedType>
                    <userType>io.vertx.core.json.JsonObject</userType>
                    <binding>pt.reactive.JSONBBinding</binding>
                    <expression>.*</expression>
                    <types>.*JSONB*</types>
                </forcedType>
```

**Comment by lukaseder** [comment]
Thank you for your message, @mustang666. I suspect that you have seen my previous answer and indication about what the original issue did wrong? https://github.com/jOOQ/jOOQ/issues/8106#issuecomment-446130836

You seem to do the same thing, so I suspect the same hint would work for you as well?

If not, can you please provide an https://github.com/jOOQ/jOOQ-mcve that helps reproduce the issue?
