### ISSUE TITLE
ClassCastException in H2 when calling returningResult() to fetch an identity when the generated record does not implement Record1

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8131]
When turning off `<recordsImplementingRecordN/>` in the code generator, the generated records will no longer implement `Record[N]`. In this case, a `ClassCastException` may occur in a use case like this:

```java
        Record1<Integer> r1 = create()
            .insertInto(TTriggers())
            .columns(TTriggers_COUNTER())
            .values(0)
            .returningResult(TTriggers_ID_GENERATED())
            .fetchOne();
```

Because the returned records will still (accidentally) be of the `TTriggersRecord` type, which no longer implements `Record1`.

The real bug here is to return `TTriggersRecord` types, of course. The whole point of `returningResult()` (#7475) was to no longer return these types, but the internal `RecordImpl` type.

The stack trace is:

```
java.lang.ClassCastException: class org.jooq.test.h2.generatedclasses.public_.tables.records.TTriggersRecord cannot be cast to class org.jooq.Record1 (org.jooq.test.h2.generatedclasses.public_.tables.records.TTriggersRecord and org.jooq.Record1 are in unnamed module of loader 'app')
	at org.jooq.test.all.testcases.InsertUpdateTests.testInsertReturningResult(InsertUpdateTests.java:1450)
	at org.jooq.test.jOOQAbstractTest.testInsertReturningResult(jOOQAbstractTest.java:3502)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
```

Not all SQL dialects are affected, and it only happens when fetching the identity *only*

**Comment by lukaseder** [comment]
This is another manifestation of the problem described in #8128
