### ISSUE TITLE
Modification of default SQL Dialect when looking up array data type

### ISSUE THREAD

**Issue by schmeedy** [jOOQ/jOOQ#8140]
### Expected behavior and actual behavior:
`DefaultDataType`.`getArrayDataType` has a side effect of modifying the default SQL dialect. Noticed this with `Postgres` driver: when selecting a value from an `int[]` column, the created `ArrayDataType` registers itself under `INT` key as default data type (in default dialect).

Relevant stack trace:

```
at org.jooq.impl.DefaultDataType.<init>(DefaultDataType.java:313) <- registration of the datatype here
at org.jooq.impl.DefaultDataType.<init>(DefaultDataType.java:276)
at org.jooq.impl.DefaultDataType.<init>(DefaultDataType.java:272)
at org.jooq.impl.DefaultDataType.<init>(DefaultDataType.java:260)
at org.jooq.impl.ArrayDataType.<init>(ArrayDataType.java:58)
at org.jooq.impl.DefaultDataType.getArrayDataType(DefaultDataType.java:720)
```

Only noticed this as we have 2 distinct db configurations in one app - one PG and the other using the dafault dialect. The one with the default dialect was failing, but only if a specific PG query has run before. As the effect of datatype registration upon instantiation is quite hidden, I'd expect there'd be other places where this kind of unintended modification happens.

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve): 

Issue a query against an `int[]` PG column.

### Versions:

- jOOQ: 3.11.7
- Java: any
- Database (include vendor): any
- OS: any
- JDBC Driver (include name if inofficial driver): any

**Comment by schmeedy** [comment]
Definitely, in this case it only happens because the default dialect doesn't have any `INT` data type (only `INTEGER`).
