### ISSUE TITLE
JBoss EAP + Oracle: java.lang.NoSuchMethodException when calling setBinaryDouble on WrappedPreparedStatementJDK8

### ISSUE THREAD

**Issue by problemzebra** [jOOQ/jOOQ#8143]
Jooq works with Oracle and JBoss EAP when using BINARY_DOUBLE data type

Fix for #8121 seems to be incomplete

- jOOQ: 3.11.8
- Java: 8u192
- JBoss EAP 7.1.5
- Database: Oracle 12.1
- JDBC Driver: OJDBC 7 12.1.0.2

> Caused by: java.sql.SQLException: Error while writing value at JDBC bind index: 7
at org.jooq.impl.DefaultBindContext.bindValue0(DefaultBindContext.java:67) [jooq-3.11.8.jar:]
at org.jooq.impl.AbstractBindContext.bindValue(AbstractBindContext.java:124) [jooq-3.11.8.jar:]
... 94 more
Caused by: org.jooq.tools.reflect.ReflectException: java.lang.NoSuchMethodException: No similar method setBinaryDouble with params [class java.lang.Integer, class java.lang.Double] could be found on type class org.jboss.jca.adapters.jdbc.jdk8.WrappedPreparedStatementJDK8.
at org.jooq.tools.reflect.Reflect.call(Reflect.java:465) [jooq-3.11.8.jar:]
at org.jooq.impl.DefaultBinding$DefaultDoubleBinding.set0(DefaultBinding.java:2097) [jooq-3.11.8.jar:]
at org.jooq.impl.DefaultBinding$DefaultDoubleBinding.set0(DefaultBinding.java:2067) [jooq-3.11.8.jar:]
at org.jooq.impl.DefaultBinding$AbstractBinding.set(DefaultBinding.java:759) [jooq-3.11.8.jar:]
at org.jooq.impl.DefaultBindContext.bindValue0(DefaultBindContext.java:62) [jooq-3.11.8.jar:]
... 95 more
Caused by: java.lang.NoSuchMethodException: No similar method setBinaryDouble with params [class java.lang.Integer, class java.lang.Double] could be found on type class org.jboss.jca.adapters.jdbc.jdk8.WrappedPreparedStatementJDK8.
at org.jooq.tools.reflect.Reflect.similarMethod(Reflect.java:532) [jooq-3.11.8.jar:]
at org.jooq.tools.reflect.Reflect.call(Reflect.java:462) [jooq-3.11.8.jar:]
... 99

**Comment by lukaseder** [comment]
Thanks a lot for the report. Indeed, that logic unfortunately doesn't seem to pass through the previously fixed logic to unwrap the native JDBC connection. I'll look into fixing this ASAP

**Comment by lukaseder** [comment]
N.B: As a workaround for these issues, might it be possible to manually unwrap the JDBC connection from your JBoss DataSource / Connection prior to passing it to jOOQ? For example, instead of initialising your `DSLContext` through `DSL.using(datasource)`, write:

```java
try (Connection con = datasource.getConnection()) {
  DSLContext ctx = DSL.using(((WrappedConnectionJDK8) con).getUnderlyingConnection(), SQLDialect.ORACLE);

...
}
```

Depending on how you set up your `DSLContext` (e.g. through dependency injection), you might need to do this only at exactly one location.

**Comment by lukaseder** [comment]
Alternatively, this logic could be implemented in a custom `org.jooq.ConnectionProvider`

**Comment by problemzebra2** [comment]
Unfortunately the workaround doesn't work. I guess JBoss does not like this workaround because there is more JBoss internal magic happening.

> 13:37:11,955 WARN  [com.arjuna.ats.jta] (XXX-Thread-2) ARJUNA016039: onePhaseCommit on < formatId=131077, gtrid_length=29, bqual_length=36, tx_uid=0:ffff0a140a3e:-66a5a0de:5c24c6b4:25, node_name=1, branch_uid=0:ffff0a140a3e:-66a5a0de:5c24c6b4:48, subordinatenodename=null, eis_name=java:jboss/datasources/XXX > (LocalXAResourceImpl@4bda534f[connectionListener=63ad6e00 connectionManager=66c4e8b0 warned=false currentXid=null productName=Oracle productVersion=Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, OLAP, Advanced Analytics and Real Application Testing options jndiName=java:jboss/datasources/XXX]) failed with exception XAException.XAER_RMFAIL: org.jboss.jca.core.spi.transaction.local.LocalXAException: IJ001156: Could not commit local transaction
	at org.jboss.jca.core.tx.jbossts.LocalXAResourceImpl.commit(LocalXAResourceImpl.java:177)
	at org.jboss.jca.core.tx.jbossts.LocalXAResourceStatImpl.commit(LocalXAResourceStatImpl.java:76)
	at com.arjuna.ats.internal.jta.resources.arjunacore.XAOnePhaseResource.commit(XAOnePhaseResource.java:120)
	at com.arjuna.ats.internal.arjuna.abstractrecords.LastResourceRecord.topLevelPrepare(LastResourceRecord.java:152)
	at com.arjuna.ats.arjuna.coordinator.AbstractRecord.topLevelOnePhaseCommit(AbstractRecord.java:428)
	at com.arjuna.ats.arjuna.coordinator.BasicAction.onePhaseCommit(BasicAction.java:2386)
	at com.arjuna.ats.arjuna.coordinator.BasicAction.End(BasicAction.java:1497)
	at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:96)
	at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:162)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1289)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:126)
	at com.arjuna.ats.jbossatx.BaseTransactionManagerDelegate.commit(BaseTransactionManagerDelegate.java:89)
	at org.wildfly.transaction.client.LocalTransaction.commitAndDissociate(LocalTransaction.java:73) [wildfly-transaction-client-1.0.4.Final-redhat-1.jar:1.0.4.Final-redhat-1]
	at org.wildfly.transaction.client.ContextTransactionManager.commit(ContextTransactionManager.java:71) [wildfly-transaction-client-1.0.4.Final-redhat-1.jar:1.0.4.Final-redhat-1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_172]
	at org.jboss.weld.util.reflection.Reflections.invokeAndUnwrap(Reflections.java:433) [weld-core-impl-2.4.7.Final-redhat-1.jar:2.4.7.Final-redhat-1]
	at org.jboss.weld.bean.builtin.CallableMethodHandler.invoke(CallableMethodHandler.java:42) [weld-core-impl-2.4.7.Final-redhat-1.jar:2.4.7.Final-redhat-1]
	at org.jboss.weld.bean.proxy.EnterpriseTargetBeanInstance.invoke(EnterpriseTargetBeanInstance.java:56) [weld-core-impl-2.4.7.Final-redhat-1.jar:2.4.7.Final-redhat-1]
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:100) [weld-core-impl-2.4.7.Final-redhat-1.jar:2.4.7.Final-redhat-1]
	at org.jboss.weldx.transaction.TransactionManager$653034586$Proxy$_$$_Weld$Proxy$.commit(Unknown Source) [jboss-transaction-api_1.2_spec-1.0.1.Final-redhat-1.jar:]
...
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [rt.jar:1.8.0_172]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [rt.jar:1.8.0_172]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [rt.jar:1.8.0_172]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [rt.jar:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [rt.jar:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [rt.jar:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_172]
Caused by: org.jboss.jca.core.spi.transaction.local.LocalResourceException: Getrennte Verbindung
	at org.jboss.jca.adapters.jdbc.local.LocalManagedConnection.commit(LocalManagedConnection.java:103)
	at org.jboss.jca.core.tx.jbossts.LocalXAResourceImpl.commit(LocalXAResourceImpl.java:172)
	... 40 more
Caused by: java.sql.SQLRecoverableException: Getrennte Verbindung
	at oracle.jdbc.driver.PhysicalConnection.getAutoCommit(PhysicalConnection.java:2254) [ojdbc7-12.1.0.2.0.jar:12.1.0.2.0]
	at oracle.jdbc.driver.PhysicalConnection.commit(PhysicalConnection.java:2357) [ojdbc7-12.1.0.2.0.jar:12.1.0.2.0]
	at oracle.jdbc.driver.PhysicalConnection.commit(PhysicalConnection.java:2407) [ojdbc7-12.1.0.2.0.jar:12.1.0.2.0]
	at org.jboss.jca.adapters.jdbc.local.LocalManagedConnection.commit(LocalManagedConnection.java:96)
	... 41 more

**Comment by lukaseder** [comment]
Here's a suggested patch to be applied to 3.11.8, that should solve this particular issue. Can you confirm, @problemzebra2 ?
[8143.patch.txt](https://github.com/jOOQ/jOOQ/files/2712531/8143.patch.txt)

**Comment by problemzebra2** [comment]
Here's our workaround attempt:

```java
@Default
@Produces
public JooqContext domainContextManaged(ConnectionProviderManaged connectionProviderManaged, TransactionManager transactionManager) {
    Settings settings = createJooqSettings();

    DefaultConfiguration configuration = new DefaultConfiguration();

    /* WORKAROUND*/
    ConnectionProvider workaround = new ConnectionProvider() {

        @Override
        public Connection acquire() throws DataAccessException {
            Connection conn = connectionProviderManaged.acquire();
            try {
                Method m = conn.getClass().getMethod("getUnderlyingConnection");
                return (Connection) m.invoke(conn);
            } catch (ReflectiveOperationException e) {
                logger.error(e.getMessage(), e);
            }
            return conn;
        }

        @Override
        public void release(Connection connection) throws DataAccessException {
            connectionProviderManaged.release(connection);
        }
    };

    configuration.set(workaround).set(settings).set(SQL_DIALECT);
    configuration.setExecuteListenerProvider(new DefaultExecuteListenerProvider(new LoggerListener()));

    return new JooqContextManaged(transactionManager, configuration);
}
```

**Comment by lukaseder** [comment]
Hm, I suspect there's a Connection lifecycle problem when acquiring connection A (The JBoss Connection) from your `connectionProviderManaged` and releasing connection B (the "physical" connection) to it again. 

What's the implementation of `connectionProviderManaged`? I suspect it closes the connection, which makes sense on connection A, but not on connection B. If your configuration is thread bound, you could remember the connection A after acquiring it from `connectionProviderManaged` (e.g. by storing it in a field inside of your anonymous `ConnectionProvider`), and then releasing A, rather than B in your `release` implementation. For example:

```java
@Default
@Produces
public JooqContext domainContextManaged(ConnectionProviderManaged connectionProviderManaged, TransactionManager transactionManager) {
    Settings settings = createJooqSettings();

    DefaultConfiguration configuration = new DefaultConfiguration();

    /* WORKAROUND*/
    ConnectionProvider workaround = new ConnectionProvider() {
        Connection conn;

        @Override
        public Connection acquire() throws DataAccessException {
            conn = connectionProviderManaged.acquire();
            try {
                Method m = conn.getClass().getMethod("getUnderlyingConnection");
                return (Connection) m.invoke(conn);
            } catch (ReflectiveOperationException e) {
                logger.error(e.getMessage(), e);
            }
            return conn;
        }

        @Override
        public void release(Connection connection) throws DataAccessException {
            connectionProviderManaged.release(conn);
        }
    };

    configuration.set(workaround).set(settings).set(SQL_DIALECT);
    configuration.setExecuteListenerProvider(new DefaultExecuteListenerProvider(new LoggerListener()));

    return new JooqContextManaged(transactionManager, configuration);
}
```

**Comment by problemzebra2** [comment]
The modified workaround does work:

```java
        /* WORKAROUND*/
        ConnectionProvider workaround = new ConnectionProvider() {
            Map<Connection, Connection> map = new WeakHashMap<>();

            @Override
            public Connection acquire() throws DataAccessException {
                Connection conn = connectionProviderManaged.acquire();
                try {
                    Method m = conn.getClass().getMethod("getUnderlyingConnection");
                    Connection realConn = (Connection) m.invoke(conn);
                    map.put(realConn, conn);
                    return realConn;
                } catch (ReflectiveOperationException e) {
                    logger.error(e.getMessage(), e);
                }
                return conn;
            }

            @Override
            public void release(Connection connection) throws DataAccessException {
                Connection wrappedConn = map.get(connection);
                connectionProviderManaged.release(wrappedConn);
            }
        };
```

But there's another problem. Inside the JBoss `WrappedConnection` there is another connection wrapper (`de.xxx.ConnectionSpy`, a custom library used inside our company) that logs e.g. slow sql queries and their execution plans to a log file. The same workaround applied again (for another method, in our case `ConnectionSpy.getRealConnection`) works. Might it be possible that Jooq unwraps connections without having a fixed list (JBoss, Spring, Apache DBCP, ...) of wrapper classes?

**Comment by lukaseder** [comment]
> The modified workaround does work

That's great to hear!

> But there's another problem. Inside the JBoss WrappedConnection there is another connection wrapper (de.xxx.ConnectionSpy, a custom library used inside our company) that logs e.g. slow sql queries and their execution plans to a log file. The same workaround applied again (for another method, in our case ConnectionSpy.getRealConnection) works.

Ideally, every connection wrapper should correctly implement the JDBC `java.sql.Wrapper` API. jOOQ first tries to unwrap an `oracle.jdbc.OraclePreparedStatement` by calling `statement.unwrap(oracle.jdbc.OraclePreparedStatement.class)`. If that fails, "known" methods like `getDelegate()` (from the DBCP library), or `getUnderlyingStatement()` (from JBoss) are called reflectively.

Your `ConnectionSpy` should definitely adhere to the `java.sql.Wrapper` API contract, as a lot of libraries like jOOQ will rely on this behaviour to unwrap vendor-specific JDBC types, in order to call vendor-specific methods on them.

Unfortunately, JBoss doesn't adhere to this contract, perhaps for historic reasons...

> Might it be possible that Jooq unwraps connections without having a fixed list (JBoss, Spring, Apache DBCP, ...) of wrapper classes?

That could be done indeed, thanks for the suggestion. We'll do it in jOOQ 3.12: #8145.

**Comment by lukaseder** [comment]
Notice, for symmetry reasons:

```java
/* WORKAROUND*/
ConnectionProvider workaround = new ConnectionProvider() {
    Map<Connection, Connection> map = new WeakHashMap<>();

    @Override
    public Connection acquire() throws DataAccessException {
        Connection conn = connectionProviderManaged.acquire();
        try {
            Method m = conn.getClass().getMethod("getUnderlyingConnection");
            Connection realConn = (Connection) m.invoke(conn);
            map.put(realConn, conn);
            return realConn;
        } catch (ReflectiveOperationException e) {
            logger.error(e.getMessage(), e);
        }
        return conn;
    }

    @Override
    public void release(Connection connection) throws DataAccessException {
        Connection wrappedConn = map.get(connection);
        connectionProviderManaged.release(wrappedConn != null ? wrappedConn : connection);
    }
};
```

The wrappedConnection in `release()` could be `null` in the ReflectiveOperationException case, in case of which the argument connection has to be released.

**Comment by lukaseder** [comment]
Unwrapping of `PreparedStatement` implemented for 3.12. Backport scheduled for 3.11.9 (#8146)

**Comment by lukaseder** [comment]
@problemzebra2 Can you work with the workaround for the time being? I new release 3.11.9 is scheduled but for logistic reasons, it cannot be shipped in 2018 anymore. Week 1 in 2019 is feasible. For the time being, a patch is available as well: https://github.com/jOOQ/jOOQ/files/2712531/8143.patch.txt

**Comment by problemzebra2** [comment]
Our Spy-Driver does implement `java.sql.Wrapper`. Will check later why it's not working.

A release in week 1 of January would be ok for us. The workaround will be used only internally for development.

**Comment by problemzebra2** [comment]
The reason why the unwrapping wasn't working was that a dependency to the Oracle driver JBoss module has been missing in the `jboss-deployment-structure.xml`. Without this dependency the Oracle driver classes cannot be found.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<jboss-deployment-structure>
    <deployment>
        <dependencies>
            <module name="com.oracle.ojdbc7"/>
            ...
        </dependencies>
    </deployment>
</jboss-deployment-structure>
```

**Comment by lukaseder** [comment]
That's great to know! Does this config also fix the original problem?

**Comment by problemzebra2** [comment]
The orignal problem ist still there. The missing dependency to the JBoss module breaks accessing Oracle driver classes directly. Sth. like `result.getClass().getMethod("createARRAY", String.class, Object.class);` would be ok.

**Comment by lukaseder** [comment]
The fix mentioned in this comment https://github.com/jOOQ/jOOQ/issues/8143#issuecomment-450152181 has now been released with jOOQ 3.11.9
