### ISSUE TITLE
ClassCastException in ClobBinding when ConnectionProvider provides wrapped Connection

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8151]
An exception may occur in `ClobBinding` when the `Connection` provided by the `ConnectionProvider` is not a native connection:

```
org.jooq.exception.DataAccessException: SQL [null]; Error while writing value at JDBC bind index: 1
	at org.jooq_3.12.0-SNAPSHOT.ORACLE.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2457)
	at org.jooq.impl.AbstractBindContext.bindValue(AbstractBindContext.java:127)
	at org.jooq.impl.Val.accept(Val.java:93)
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:254)
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:88)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:444)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:205)
	at org.jooq.impl.AbstractRoutine.bind1(AbstractRoutine.java:629)
	at org.jooq.impl.AbstractRoutine.bind0(AbstractRoutine.java:580)
	at org.jooq.impl.AbstractRoutine.accept(AbstractRoutine.java:540)
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:254)
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:88)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:444)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:205)
	at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:477)
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:344)
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:321)
	at org.jooq.test.OracleTest.testOracleSysRefcursorInOutParameter(OracleTest.java:3748)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: java.sql.SQLException: Error while writing value at JDBC bind index: 1
	at org.jooq.impl.DefaultBindContext.bindValue0(DefaultBindContext.java:67)
	at org.jooq.impl.AbstractBindContext.bindValue(AbstractBindContext.java:124)
	... 43 more
Caused by: org.jooq.tools.reflect.ReflectException: java.lang.reflect.InvocationTargetException
	at org.jooq.tools.reflect.Reflect.on(Reflect.java:838)
	at org.jooq.tools.reflect.Reflect.call(Reflect.java:520)
	at org.jooq.impl.ClobBinding.newClob(ClobBinding.java:153)
	at org.jooq.impl.ClobBinding.set(ClobBinding.java:93)
	at org.jooq.impl.DefaultBindContext.bindValue0(DefaultBindContext.java:62)
	... 44 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jooq.tools.reflect.Reflect.on(Reflect.java:834)
	... 48 more
Caused by: java.lang.ClassCastException: class com.sun.proxy.$Proxy30 cannot be cast to class oracle.jdbc.OracleConnection (com.sun.proxy.$Proxy30 and oracle.jdbc.OracleConnection are in unnamed module of loader 'app')
	at oracle.sql.CLOB.createTemporary(CLOB.java:1118)
	at oracle.sql.CLOB.createTemporary(CLOB.java:1078)
	... 53 more
```

**Comment by lukaseder** [comment]
There's a slight regression risk in this, so the fix will not be merged to 3.11
