### ISSUE TITLE
code generator is missing PostgreSQL 11 support?

### ISSUE THREAD

**Issue by jottyfan** [jOOQ/jOOQ#8160]
### Expected behavior and actual behavior:
Expected is the generation of the data model classes, but there is a bug; anyway, the classes have been generated, so no big deal, just for your information (I only need the tables and views, but sth. else does not have been generated).

### Steps to reproduce the problem
generate postgresql 11 database objects

### Versions:

- jOOQ: 3.11.2
- Java: 1.8.0_181 (openjdk, b13-2 (deb9u1)
- Database (include vendor): postgresql 11.1-1.pgdg90+1
- OS: Debian Stretch
- JDBC Driver (include name if inofficial driver): postgresql-42.2.2.jar

### Error message on generating classes:

> Jan 02, 2019 6:09:27 PM org.jooq.tools.JooqLogger warn
> WARNUNG: SQL exception            : Exception while executing meta query: FEHLER: Spalte pg_proc.proisagg existiert nicht
>  Hinweis: Vielleicht wurde beabsichtigt, auf die Spalte »pg_proc.prolang« zu verweisen.
> Position: 548
>
> Please report this bug here: https://github.com/jOOQ/jOOQ/issues/new
> 
```sql
select 
  "r1"."routine_schema", 
  "r1"."routine_name", 
  "r1"."specific_name", 
  case
    when ("pg_catalog"."pg_proc"."proargmodes" && ARRAY['o','b']::"char"[]) then 'void'
    else "r1"."data_type"
  end as "data_type", 
  "r1"."character_maximum_length", 
  "r1"."numeric_precision", 
  "r1"."numeric_scale", 
  "r1"."type_udt_schema", 
  "r1"."type_udt_name", 
  case
    when count(*) over (partition by 
      "r1"."routine_schema", 
      "r1"."routine_name"
    ) > 1 then row_number() over (partition by 
      "r1"."routine_schema", 
      "r1"."routine_name"
     order by "r1"."specific_name")
  end as "overload", 
  "pg_catalog"."pg_proc"."proisagg"
from "information_schema"."routines" as "r1"
  join "pg_catalog"."pg_namespace"
  on "pg_catalog"."pg_namespace"."nspname" = "r1"."specific_schema"
  join "pg_catalog"."pg_proc"
  on (
    "pg_catalog"."pg_proc"."pronamespace" = "pg_catalog"."pg_namespace".oid
    and (("pg_catalog"."pg_proc"."proname" || '_') || cast("pg_catalog"."pg_proc".oid as varchar)) = "r1"."specific_name"
  )
where (
  "r1"."routine_schema" in (
    'square', 'squareout'
  )
  and not("pg_catalog"."pg_proc"."proretset")
  and "r1"."data_type" <> 'trigger'
)
order by 
  "r1"."routine_schema" asc, 
  "r1"."routine_name" asc, 
  "overload" asc
```
> 
> Jan 02, 2019 6:09:27 PM org.jooq.tools.JooqLogger error
> SCHWERWIEGEND: Error while fetching functions
org.jooq.exception.DataAccessException: SQL [select "r1"."routine_schema", "r1"."routine_name", "r1"."specific_name", case when ("pg_catalog"."pg_proc"."proargmodes" && ARRAY['o','b']::"char"[]) then 'void' else "r1"."data_type" end as "data_type", "r1"."character_maximum_length", "r1"."numeric_precision", "r1"."numeric_scale", "r1"."type_udt_schema", "r1"."type_udt_name", case when count(*) over (partition by "r1"."routine_schema", "r1"."routine_name") > 1 then row_number() over (partition by "r1"."routine_schema", "r1"."routine_name" order by "r1"."specific_name") end as "overload", "pg_catalog"."pg_proc"."proisagg" from "information_schema"."routines" as "r1" join "pg_catalog"."pg_namespace" on "pg_catalog"."pg_namespace"."nspname" = "r1"."specific_schema" join "pg_catalog"."pg_proc" on ("pg_catalog"."pg_proc"."pronamespace" = "pg_catalog"."pg_namespace".oid and (("pg_catalog"."pg_proc"."proname" || ?) || cast("pg_catalog"."pg_proc".oid as varchar)) = "r1"."specific_name") where ("r1"."routine_schema" in (?, ?) and not("pg_catalog"."pg_proc"."proretset") and "r1"."data_type" <> 'trigger') order by "r1"."routine_schema" asc, "r1"."routine_name" asc, "overload" asc]; FEHLER: Spalte pg_proc.proisagg existiert nicht
  Hinweis: Vielleicht wurde beabsichtigt, auf die Spalte »pg_proc.prolang« zu verweisen.
  Position: 548
	at org.jooq_3.11.2.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2380)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:811)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:364)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:323)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2700)
	at org.jooq.meta.postgres.PostgresDatabase.getRoutines0(PostgresDatabase.java:791)
	at org.jooq.meta.AbstractDatabase.getRoutines(AbstractDatabase.java:1664)
	at org.jooq.codegen.JavaGenerator.generateSchemaIfEmpty(JavaGenerator.java:418)
	at org.jooq.codegen.JavaGenerator.generateCatalog(JavaGenerator.java:4472)
	at org.jooq.codegen.JavaGenerator.generateCatalog(JavaGenerator.java:4436)
	at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:452)
	at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:380)
	at org.jooq.codegen.GenerationTool.run(GenerationTool.java:750)
	at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:220)
	at org.jooq.codegen.GenerationTool.main(GenerationTool.java:192)
Caused by: org.postgresql.util.PSQLException: FEHLER: Spalte pg_proc.proisagg existiert nicht
  Hinweis: Vielleicht wurde beabsichtigt, auf die Spalte »pg_proc.prolang« zu verweisen.
  Position: 548
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:132)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:3479)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:268)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:350)
	... 12 more

> Jan 02, 2019 6:09:27 PM org.jooq.tools.JooqLogger info
> INFORMATION: Tables fetched           : 94 (94 included, 0 excluded)

**Comment by ebadta81** [comment]
I also get this message with JOOQ 3.11.8

Something went wrong...

**Comment by lukaseder** [comment]
@ebadta81 Are you sure you updated the jOOQ version for all artefacts, including jOOQ, jOOQ-meta, jOOQ-codegen?

**Comment by ebadta81** [comment]
Ahh you are right.

I use import com.rohanprabhu.gradle.plugins.kdjooq.* for generation in a build.gradle.kts file, and it's version is const val DefaultJooqVersion = "3.10.1"

Sorry for the false report.

**Comment by jottyfan** [comment]
same to me, but another project: using https://github.com/etiennestuder/gradle-jooq-plugin in version 3.0.2 (current active one), and there the jooq version is 3.11.2 (see https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/gradle.properties#L7 ). I'll generate a new issue in that project.

**Comment by ebadta81** [comment]
Hmm, it would be nice, if you could provide kts gradle build support within JOOQ distribution.
