### ISSUE TITLE
StringIndexOutOfBoundsException when parsing a PostgreSQL TIMESTAMPTZ with microseconds precision

### ISSUE THREAD

**Issue by berngp** [jOOQ/jOOQ#8221]
### Expected behavior and actual behavior:

The `DefaultBinding.OffsetDateTimeParser.offsetDateTime` method should be able to handle a timestamp with the following format `"2019-01-15 09:10:37.506683"`.

Calling `DefaultBinding.OffsetDateTimeParser.offsetDateTime` with the following inputs will cause a `StringIndexOutOfBoundsException`. 

```
"2019-01-15 09:10:37.506683",
"2019-01-15 09:15:19.152581"
```

The inputs are being generated by calling PostgreSQL 9.6.9
`SELECT now() at time zone 'utc';` which will return `'2019-01-15 17:57:27.702973'`

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

_MCVE in progress_

Attempt to create an OffsetDateTime from `"2019-01-15 17:57:27.702973"`.
e.g.
`DefaultBinding.OffsetDateTimeParser.offsetDateTime("2019-01-15 17:57:27.702973");`
Exception Thrown.
```
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 26
	at java.lang.String.charAt(String.java:658)
	at org.jooq.impl.DefaultBinding$OffsetDateTimeParser.parseInt(DefaultBinding.java:2544)
	at org.jooq.impl.DefaultBinding$OffsetDateTimeParser.parseLocalTime(DefaultBinding.java:2469)
	at org.jooq.impl.DefaultBinding$OffsetDateTimeParser.offsetDateTime(DefaultBinding.java:2435)
	at org.jooq.impl.DefaultBinding$DefaultOffsetDateTimeBinding.get0(DefaultBinding.java:2619)
	at org.jooq.impl.DefaultBinding$DefaultOffsetDateTimeBinding.get0(DefaultBinding.java:2561)
	at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:774)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1771)
```

### Versions:

- jOOQ: 3.11.9
- Java: 1.8
- Database (include vendor): PostgreSQL 9.6.9
- OS: Debian
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.2.5

**Comment by berngp** [comment]
https://github.com/jOOQ/jOOQ/pull/8222

**Comment by lukaseder** [comment]
Thanks a lot for your help. No MCVE needed in this case, I could reproduce the issue from your description. Fixed in jOOQ 3.12.

**Comment by lukaseder** [comment]
Backport scheduled for 3.11.10 (#8224) and 3.10.9 (#8225)

**Comment by berngp** [comment]
Thanks a lot @lukaseder !
