### ISSUE TITLE
Deadlock in generated code static initialization

### ISSUE THREAD

**Issue by tsiq-matthart** [jOOQ/jOOQ#8226]
### Expected behavior and actual behavior:
*Expected behavior:* Generated code static initializers can be run in separate threads.
*Actual behavior:* Generated code static initializers can deadlock when run in multiple threads.

The cycle in the MCVE generated code is as follows:
Public.PUBLIC
-> Public.CYCLE_TABLE
-> CycleTable.CYCLE_RECORD_COL
-> CycleRecord.CYCLE_RECORD.getDataType()
-(through a series of super class methods)-> CycleRecord.getSchema()
-> Public.PUBLIC

### Steps to reproduce the problem:
https://github.com/tsiq-matthart/jOOQ-mcve

I am not able to reproduce using H2, as it doesn't have UDTs. MCVE tested with postgres docker image. To setup postgres docker container:
```
docker pull postgres:11.1
docker run -p 5432:5432 -d postgres:11.1
```
Then one should be able to run the test and observe a deadlock.

### Versions:

- jOOQ: tested on 3.10.0 and 3.11.7
- Java: 1.8.0_172
- Database: Postgres 11.1
- OS: macos 10.14.1
- JDBC Driver: [pgjdbc-42.1.4](https://jdbc.postgresql.org/download/postgresql-42.1.4.jar)

**Comment by lukaseder** [comment]
Thank you very much for your report. 3.11.8 contains a fix related to that part of UDT code generation: #8059, #7496. Can you please try if you can reproduce this issue also on the latest version of jOOQ, which is 3.11.9?

**Comment by tsiq-matthart** [comment]
Thank you for the quick response. I was able to reproduce the issue with 3.11.9. See new [branch](https://github.com/tsiq-matthart/jOOQ-mcve/tree/jooq-3.9.11).

**Comment by knutwannheden** [comment]
This problem is still reproducible with jOOQ 3.13.1. As a workaround the code can be generated with `<generateGlobalTableReferences>false</generateGlobalTableReferences>`.

The problem is still that `UDT.getDataType()` transitively depends on an initialized `Schema` instance.

Also, the trick with the `getSchema()` method as generated by the generator doesn't help here:
```java
    @Override
    public Schema getSchema() {
        return Public.PUBLIC != null ? Public.PUBLIC : new SchemaImpl(DSL.name("public"));
    }
```

See also discussion in https://github.com/jOOQ/jOOQ/issues/7496.

**Comment by tsobe** [comment]
Hi @lukaseder ,

Was [this](https://github.com/jOOQ/jOOQ/issues/7496#issuecomment-441035737) supposed to work for this issue as well? I see this classloader deadlock still happening for UDT in 3.19.

Here are the stacktraces (`com.foo.bar` is our project-specific package)
```
"A" #88 [39179] daemon prio=5 os_prio=31 cpu=86.90ms elapsed=42.84s tid=0x000000014a859e00 nid=39179 in Object.wait()  [0x000000017cb57000]
   java.lang.Thread.State: RUNNABLE
	at com.foo.bar.infrastructure.db.cs.udt.ProductFamilyId.getSchema(ProductFamilyId.java:58)
	- waiting on the Class initialization monitor for com.foo.bar.infrastructure.db.cs.Public
	at org.jooq.impl.UDTDataType$$Lambda$817/0x00000008016a7df0.get(Unknown Source)
	at org.jooq.impl.AbstractDataType.lazyName(AbstractDataType.java:745)
	at org.jooq.impl.UDTDataType.lambda$new$db692576$1(UDTDataType.java:58)
	at org.jooq.impl.UDTDataType$$Lambda$815/0x00000008016af4a8.get(Unknown Source)
	at org.jooq.impl.LazyName.name(LazyName.java:66)
	at org.jooq.impl.LazyName.accept(LazyName.java:77)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:731)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:362)
	at org.jooq.impl.DefaultDSLContext.renderInlined(DefaultDSLContext.java:748)
	at org.jooq.impl.AbstractQueryPart.toString(AbstractQueryPart.java:192)
	at org.jooq.impl.DefaultDataType.<init>(DefaultDataType.java:369)
	at org.jooq.impl.DefaultDataType.<init>(DefaultDataType.java:361)
	at org.jooq.impl.DefaultDataType.<init>(DefaultDataType.java:357)
	at org.jooq.impl.DefaultDataType.<init>(DefaultDataType.java:345)
	at org.jooq.impl.UDTDataType.<init>(UDTDataType.java:55)
	at org.jooq.impl.UDTImpl.getDataType(UDTImpl.java:179)
	at com.foo.bar.infrastructure.db.cs.tables.Product.<init>(Product.java:144)
	at com.foo.bar.infrastructure.db.cs.tables.Product.<init>(Product.java:147)
	at com.foo.bar.infrastructure.db.cs.tables.Product.<init>(Product.java:172)
	at com.foo.bar.infrastructure.db.cs.tables.Product.<clinit>(Product.java:46)
	at com.foo.bar.infrastructure.db.cs.Keys.<clinit>(Keys.java:66)
	at com.foo.bar.infrastructure.db.cs.tables.PremiumRecipes.getPrimaryKey(PremiumRecipes.java:108)
	at org.jooq.impl.AbstractTable.getPrimaryKeyWithEmbeddables(AbstractTable.java:543)
	at org.jooq.impl.UpdatableRecordImpl.getPrimaryKey(UpdatableRecordImpl.java:139)
	at org.jooq.impl.AbstractRecord.set(AbstractRecord.java:441)
	at org.jooq.impl.AbstractRecord.set(AbstractRecord.java:408)
	
	
	
"B" #92 [34827] daemon prio=5 os_prio=31 cpu=12.53ms elapsed=42.57s tid=0x000000012901d200 nid=34827 in Object.wait()  [0x000000017d388000]
   java.lang.Thread.State: RUNNABLE
	at com.foo.bar.infrastructure.db.cs.Public.<init>(Public.java:110)
	- waiting on the Class initialization monitor for com.foo.bar.infrastructure.db.cs.tables.Product
	at com.foo.bar.infrastructure.db.cs.Public.<clinit>(Public.java:45)
	at com.foo.bar.infrastructure.db.cs.tables.PremiumRecipes.getSchema(PremiumRecipes.java:103)
	at org.jooq.impl.TableImpl.hashCode(TableImpl.java:646)
	at java.util.HashMap.hash(java.base@19.0.2/HashMap.java:338)
	at java.util.HashMap.computeIfAbsent(java.base@19.0.2/HashMap.java:1199)
	at org.jooq.impl.ScopeStack.list(ScopeStack.java:267)
	at org.jooq.impl.ScopeStack.create(ScopeStack.java:242)
	at org.jooq.impl.DefaultRenderContext.scopeRegister(DefaultRenderContext.java:254)
	at org.jooq.impl.DefaultRenderContext.scopeRegister(DefaultRenderContext.java:97)
	at org.jooq.impl.AbstractContext.scopeRegister(AbstractContext.java:918)
	at org.jooq.impl.SelectQueryImpl.lambda$toSQLReference0$15(SelectQueryImpl.java:2410)
	at org.jooq.impl.SelectQueryImpl$$Lambda$810/0x0000000801696328.accept(Unknown Source)
	at org.jooq.impl.Tools.lambda$traverseJoins$146(Tools.java:7605)
	at org.jooq.impl.Tools$$Lambda$811/0x0000000801696548.apply(Unknown Source)
	at org.jooq.impl.Tools.traverseJoins(Tools.java:7681)
	at org.jooq.impl.Tools.traverseJoins(Tools.java:7629)
	at org.jooq.impl.Tools.traverseJoins(Tools.java:7605)
	at org.jooq.impl.Tools.traverseJoins(Tools.java:7601)
	at org.jooq.impl.SelectQueryImpl.toSQLReference0(SelectQueryImpl.java:2408)
	at org.jooq.impl.SelectQueryImpl.lambda$toSQLReferenceLimitDefault$10(SelectQueryImpl.java:2101)
	at org.jooq.impl.SelectQueryImpl$$Lambda$809/0x0000000801696108.accept(Unknown Source)
	at org.jooq.impl.AbstractContext.data(AbstractContext.java:419)
	at org.jooq.impl.SelectQueryImpl.toSQLReferenceLimitDefault(SelectQueryImpl.java:2101)
	at org.jooq.impl.SelectQueryImpl.accept0(SelectQueryImpl.java:1953)
	at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:1598)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:731)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:362)
	at org.jooq.impl.DefaultRenderContext$Rendered.rendered(DefaultRenderContext.java:1082)
	at org.jooq.impl.AbstractQuery.getSQL0(AbstractQuery.java:498)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:303)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:290)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:3232)
	at org.jooq.impl.ResultQueryTrait$$Lambda$795/0x000000080163bba8.get(Unknown Source)
	at org.jooq.impl.Tools$3$1.block(Tools.java:6370)
	at java.util.concurrent.ForkJoinPool.compensatedBlock(java.base@19.0.2/ForkJoinPool.java:3705)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@19.0.2/ForkJoinPool.java:3688)
	at org.jooq.impl.Tools$3.get(Tools.java:6367)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(java.base@19.0.2/CompletableFuture.java:1768)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(java.base@19.0.2/CompletableFuture.java:1760)
	at java.util.concurrent.ForkJoinTask.doExec(java.base@19.0.2/ForkJoinTask.java:387)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(java.base@19.0.2/ForkJoinPool.java:1311)
	at java.util.concurrent.ForkJoinPool.scan(java.base@19.0.2/ForkJoinPool.java:1841)
	at java.util.concurrent.ForkJoinPool.runWorker(java.base@19.0.2/ForkJoinPool.java:1806)
	at java.util.concurrent.ForkJoinWorkerThread.run(java.base@19.0.2/ForkJoinWorkerThread.java:177)
```

In summary, `UDTImpl.getDataType` doesn't seem to evaluate schema lazily?
```
Thread A -> PremiumRecipe.getPrimaryKey -> Keys -> Product -> ProductFamilyId -> UDTImpl.getDataType -> ProductFamilyId
Thread B -> PremiumRecipes.getSchema -> Public -> Product
```

**Comment by lukaseder** [comment]
> Was [this](https://github.com/jOOQ/jOOQ/issues/7496#issuecomment-441035737) supposed to fix this issue as well? I see this classloader deadlock still happening for generated UDT in 3.19.

This may or may not be the same issue, hard to say without more evaluation.
