### ISSUE TITLE
Invalid SQL Error With Mock Data

### ISSUE THREAD

**Issue by dpatra1** [jOOQ/jOOQ#8305]
Hi,

I am trying to write test cases for my Repository where all my CRUD operations are there by defining mock data but my update/insert/delete test cases are failing with **java.sql.SQLException: Invalid SQL** exception.

My Insert query in the txt file is as below:
**#testCreateDeck**
```
insert into "public"."deck" ("foreign_id", "creator_id", "deck_type", "title") values ('12345', cast('283ea7fa-6a4b-43ba-b6f4-d8dd29ff9d5e' as uuid), 'DRAFT'::"public"."deck_type", 'title') returning "public"."deck"."id", "public"."deck"."title", "public"."deck"."deck_type", "public"."deck"."creator_id", "public"."deck"."created", "public"."deck"."updated";
> id                                      title   deck_type   creator_id                              created               updated               original_created      original_updated
> --------------------------------------  ------- ---------- --------------------------------------- --------------------- --------------------  --------------------  ---------------------
>  efb2d576-f2d3-4a8e-9715-dc95fdd14722    title    DRAFT      283ea7fa-6a4b-43ba-b6f4-d8dd29ff9d5e   2018-12-12 11:13:19  2018-12-12 11:13:19    2018-12-12 11:13:19   2018-12-12 11:13:19
@ rows: 1

```

My Jooq Mock DB connection is as below.

```java
MockDataProvider db = new MockFileDatabase(new File(getClass().getResource(getResourcePath()).toURI()));
        MockConnection deckConnection = new MockConnection(db);
        dslContext = DSL.using(deckConnection, SQLDialect.POSTGRES_10);
``` 

The error which i am getting is here:

```
Caused by: java.sql.SQLException: Invalid SQL: insert into "public"."deck" ("creator_id", "foreign_id", "deck_type", "title") values (cast(? as uuid), ?, ?::"public"."deck_type", ?) returning "public"."deck"."id", "public"."deck"."title", "public"."deck"."deck_type", "public"."deck"."creator_id", "public"."deck"."created", "public"."deck"."updated", "public"."deck"."original_created", "public"."deck"."original_updated"
        at org.jooq.tools.jdbc.MockFileDatabase.execute(MockFileDatabase.java:362)
        at org.jooq.tools.jdbc.MockStatement.execute0(MockStatement.java:187)
        at org.jooq.tools.jdbc.MockStatement.executeQuery(MockStatement.java:239)
        at org.jooq.tools.jdbc.MockStatement.executeQuery(MockStatement.java:234)
        at org.jooq.tools.jdbc.DefaultPreparedStatement.executeQuery(DefaultPreparedStatement.java:94)
        at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:738)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:350)
        ... 66 common frames omitted

com.chegg.deck.service.dao.DeckRepositoryCreateDeckTest > testCreateDeck() FAILED
    org.jooq.exception.DataAccessException: SQL [insert into "public"."deck" ("creator_id", "foreign_id", "deck_type", "title") values (cast(? as uuid), ?, ?::"public"."deck_type", ?) returning "public"."deck"."id", "public"."deck"."title", "public"."deck"."deck_type", "public"."deck"."creator_id", "public"."deck"."created", "public"."deck"."updated", "public"."deck"."original_created", "public"."deck"."original_updated"]; Invalid SQL: insert into "public"."deck" ("creator_id", "foreign_id", "deck_type", "title") values (cast(? as uuid), ?, ?::"public"."deck_type", ?) returning "public"."deck"."id", "public"."deck"."title", "public"."deck"."deck_type", "public"."deck"."creator_id", "public"."deck"."created", "public"."deck"."updated", "public"."deck"."original_created", "public"."deck"."original_updated"
        at org.jooq_3.11.5.POSTGRES_10.debug(Unknown Source)
        at org.jooq.impl.Tools.translate(Tools.java:2384)
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:811)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:364)

```

I am running my application using jooq 3.11.8 with JDK 10.

Please help me understanding the issue here.

Thanks,
Deba

**Comment by lukaseder** [comment]
Thank you very much for your message. "Invalid SQL" means that your `MockFileDatabase` was not able to match any of the configured SQL statements to the one you ran. jOOQ 3.12 will support regular expressions in the `MockFileDatabase` through #8124 to help match more statements more easily. For the time being, you must ensure that your database file contains the exact string that is sent to the JDBC driver, e.g.

```
insert into "public"."deck" ("creator_id", "foreign_id", "deck_type", "title") values (cast(? as uuid), ?, ?::"public"."deck_type", ?) returning "public"."deck"."id", "public"."deck"."title", "public"."deck"."deck_type", "public"."deck"."creator_id", "public"."deck"."created", "public"."deck"."updated", "public"."deck"."original_created", "public"."deck"."original_updated";
> id                                      title   deck_type   creator_id                              created               updated               original_created      original_updated
> --------------------------------------  ------- ---------- --------------------------------------- --------------------- --------------------  --------------------  ---------------------
>  efb2d576-f2d3-4a8e-9715-dc95fdd14722    title    DRAFT      283ea7fa-6a4b-43ba-b6f4-d8dd29ff9d5e   2018-12-12 11:13:19  2018-12-12 11:13:19    2018-12-12 11:13:19   2018-12-12 11:13:19
@ rows: 1
```

In particular, you have to replace your constant literals by bind variable placeholders `?`

I hope this helps

**Comment by lukaseder** [comment]
Note, if you want to profit from using regular expressions already now, you can backport the `MockFileDatabase` from jOOQ 3.12 manually:
- https://github.com/jOOQ/jOOQ/blob/master/jOOQ/src/main/java/org/jooq/tools/jdbc/MockFileDatabase.java
- https://github.com/jOOQ/jOOQ/blob/master/jOOQ/src/main/java/org/jooq/tools/jdbc/MockFileDatabaseConfiguration.java

**Comment by dpatra1** [comment]
Hi @lukaseder 

Thanks for replying to my query but the solution which you provided does not work as well.

Now with your suggestion i have changed my mock data txt file as below.
`
#testCreateDeck
#insert into "public"."deck" ("foreign_id", "creator_id", "deck_type", "title") values ('12345', cast('283ea7fa-6a4b-43ba-b6f4-d8dd29ff9d5e' as uuid), 'DRAFT'::"public"."deck_type", 'title') returning "public"."deck"."id", "public"."deck"."title", "public"."deck"."deck_type", "public"."deck"."creator_id", "public"."deck"."created", "public"."deck"."updated";
insert into "public"."deck" ("foreign_id", "creator_id", "deck_type", "title") values (?, cast(? as uuid), ?::"public"."deck_type", ?) returning "public"."deck"."id", "public"."deck"."title", "public"."deck"."deck_type", "public"."deck"."creator_id", "public"."deck"."created", "public"."deck"."updated";
> id                                      title   deck_type   creator_id                              created               updated               original_created      original_updated
> --------------------------------------  ------- ---------- --------------------------------------- --------------------- --------------------  --------------------  ---------------------
>  efb2d576-f2d3-4a8e-9715-dc95fdd14722    title    DRAFT      283ea7fa-6a4b-43ba-b6f4-d8dd29ff9d5e   2018-12-12 11:13:19  2018-12-12 11:13:19    2018-12-12 11:13:19   2018-12-12 11:13:19
@ rows: 1
`

After changing i am getting the same error.
`com.chegg.deck.service.dao.DeckRepositoryCreateDeckTest > testCreateDeck() STANDARD_OUT
    16:38:04.138 [Test worker] DEBUG org.jooq.tools.LoggerListener - Executing query          : insert into "public"."deck" ("creator_id", "foreign_id", "deck_type", "title") values (cast(? as uuid), ?, ?::"public"."deck_type", ?) returning "public"."deck"."id", "public"."deck"."title", "public"."deck"."deck_type", "public"."deck"."creator_id", "public"."deck"."created", "public"."deck"."updated", "public"."deck"."original_created", "public"."deck"."original_updated"
    16:38:04.139 [Test worker] DEBUG org.jooq.tools.LoggerListener - -> with bind values      : insert into "public"."deck" ("creator_id", "foreign_id", "deck_type", "title") values ('283ea7fa-6a4b-43ba-b6f4-d8dd29ff9d5e', '12345', 'DRAFT', 'Crazy Physics') returning "public"."deck"."id", "public"."deck"."title", "public"."deck"."deck_type", "public"."deck"."creator_id", "public"."deck"."created", "public"."deck"."updated", "public"."deck"."original_created", "public"."deck"."original_updated"
    16:38:04.147 [Test worker] DEBUG org.jooq.tools.LoggerListener - Exception                
    org.jooq.exception.DataAccessException: SQL [insert into "public"."deck" ("creator_id", "foreign_id", "deck_type", "title") values (cast(? as uuid), ?, ?::"public"."deck_type", ?) returning "public"."deck"."id", "public"."deck"."title", "public"."deck"."deck_type", "public"."deck"."creator_id", "public"."deck"."created", "public"."deck"."updated", "public"."deck"."original_created", "public"."deck"."original_updated"]; Invalid SQL: insert into "public"."deck" ("creator_id", "foreign_id", "deck_type", "title") values (cast(? as uuid), ?, ?::"public"."deck_type", ?) returning "public"."deck"."id", "public"."deck"."title", "public"."deck"."deck_type", "public"."deck"."creator_id", "public"."deck"."created", "public"."deck"."updated", "public"."deck"."original_created", "public"."deck"."original_updated"
        at org.jooq_3.11.5.POSTGRES_10.debug(Unknown Source)
        at org.jooq.impl.Tools.translate(Tools.java:2384)
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:811)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:364)
        at org.jooq.impl.InsertImpl.fetchOne(InsertImpl.java:1061)
        at com.chegg.deck.service.dao.DeckRepository.createDeck(DeckRepository.java:273)
        at com.chegg.deck.service.dao.DeckRepository.createDeck(DeckRepository.java:156)
        at com.chegg.deck.service.dao.DeckRepositoryCreateDeckTest.testCreateDeck(DeckRepositoryCreateDeckTest.java:50)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:515)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:105)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:110)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:110)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:92)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$100(JUnitPlatformTestClassProcessor.java:77)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:73)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy2.stop(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:131)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:844)
    Caused by: java.sql.SQLException: Invalid SQL: insert into "public"."deck" ("creator_id", "foreign_id", "deck_type", "title") values (cast(? as uuid), ?, ?::"public"."deck_type", ?) returning "public"."deck"."id", "public"."deck"."title", "public"."deck"."deck_type", "public"."deck"."creator_id", "public"."deck"."created", "public"."deck"."updated", "public"."deck"."original_created", "public"."deck"."original_updated"
        at org.jooq.tools.jdbc.MockFileDatabase.execute(MockFileDatabase.java:362)
        at org.jooq.tools.jdbc.MockStatement.execute0(MockStatement.java:187)
        at org.jooq.tools.jdbc.MockStatement.executeQuery(MockStatement.java:239)
        at org.jooq.tools.jdbc.MockStatement.executeQuery(MockStatement.java:234)
        at org.jooq.tools.jdbc.DefaultPreparedStatement.executeQuery(DefaultPreparedStatement.java:94)
        at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:738)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:350)
        ... 66 common frames omitted

com.chegg.deck.service.dao.DeckRepositoryCreateDeckTest > testCreateDeck() FAILED
    org.jooq.exception.DataAccessException: SQL [insert into "public"."deck" ("creator_id", "foreign_id", "deck_type", "title") values (cast(? as uuid), ?, ?::"public"."deck_type", ?) returning "public"."deck"."id", "public"."deck"."title", "public"."deck"."deck_type", "public"."deck"."creator_id", "public"."deck"."created", "public"."deck"."updated", "public"."deck"."original_created", "public"."deck"."original_updated"]; Invalid SQL: insert into "public"."deck" ("creator_id", "foreign_id", "deck_type", "title") values (cast(? as uuid), ?, ?::"public"."deck_type", ?) returning "public"."deck"."id", "public"."deck"."title", "public"."deck"."deck_type", "public"."deck"."creator_id", "public"."deck"."created", "public"."deck"."updated", "public"."deck"."original_created", "public"."deck"."original_updated"
        at org.jooq_3.11.5.POSTGRES_10.debug(Unknown Source)
        at org.jooq.impl.Tools.translate(Tools.java:2384)
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:811)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:364)
        at org.jooq.impl.InsertImpl.fetchOne(InsertImpl.java:1061)
        at com.chegg.deck.service.dao.DeckRepository.createDeck(DeckRepository.java:273)
        at com.chegg.deck.service.dao.DeckRepository.createDeck(DeckRepository.java:156)
        at com.chegg.deck.service.dao.DeckRepositoryCreateDeckTest.testCreateDeck(DeckRepositoryCreateDeckTest.java:50)

        Caused by:
        java.sql.SQLException: Invalid SQL: insert into "public"."deck" ("creator_id", "foreign_id", "deck_type", "title") values (cast(? as uuid), ?, ?::"public"."deck_type", ?) returning "public"."deck"."id", "public"."deck"."title", "public"."deck"."deck_type", "public"."deck"."creator_id", "public"."deck"."created", "public"."deck"."updated", "public"."deck"."original_created", "public"."deck"."original_updated"
            at org.jooq.tools.jdbc.MockFileDatabase.execute(MockFileDatabase.java:362)
            at org.jooq.tools.jdbc.MockStatement.execute0(MockStatement.java:187)
            at org.jooq.tools.jdbc.MockStatement.executeQuery(MockStatement.java:239)
            at org.jooq.tools.jdbc.MockStatement.executeQuery(MockStatement.java:234)
            at org.jooq.tools.jdbc.DefaultPreparedStatement.executeQuery(DefaultPreparedStatement.java:94)
            at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:738)
            at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:350)
            ... 4 more

`

**Comment by lukaseder** [comment]
It's easy to see what's going on. Just copy paste both your configured query and the executed query next to each other to compare them:

```
insert into "public"."deck" ("foreign_id", "creator_id", "deck_type", "title") values (?, cast(? as uuid), ?::"public"."deck_type", ?) returning "public"."deck"."id", "public"."deck"."title", "public"."deck"."deck_type", "public"."deck"."creator_id", "public"."deck"."created", "public"."deck"."updated";

insert into "public"."deck" ("creator_id", "foreign_id", "deck_type", "title") values (cast(? as uuid), ?, ?::"public"."deck_type", ?) returning "public"."deck"."id", "public"."deck"."title", "public"."deck"."deck_type", "public"."deck"."creator_id", "public"."deck"."created", "public"."deck"."updated", "public"."deck"."original_created", "public"."deck"."original_updated"
```

They're not the same. It is imperative that you put *exactly* the queries that you're running in the mock file database.

**Comment by dpatra1** [comment]
Hi @lukaseder 

After fixing that issue, its giving some other error and it seems like its not able to read the return value.
I am really not able make this update/delete/create operations work for me in my test. Only select queries i am able to test by mocking.

I really appreciate your help here. Please let me know if i need to do any other change to make this work.

Thanks,
Deba

**My Mock Data**
```
insert into "public"."deck" ("foreign_id", "deck_type", "title") values (?, ?::"public"."deck_type", ?) returning "public"."deck"."id", "public"."deck"."title", "public"."deck"."deck_type", "public"."deck"."created", "public"."deck"."updated", "public"."deck"."original_created", "public"."deck"."original_updated", "public"."deck"."confidential";
> id                                      title   deck_type      created               updated               original_created      original_updated   confidential
> --------------------------------------  ------- ----------  --------------------- --------------------  --------------------  --------------------- ------------
>  efb2d576-f2d3-4a8e-9715-dc95fdd14722    title    DRAFT      2018-12-12 11:13:19   2018-12-12 11:13:19     null                    null                 false
@ rows: 1
```



`21:07:24.253 [Test worker] DEBUG org.jooq.tools.LoggerListener - Executing query          : insert into "public"."deck" ("foreign_id", "deck_type", "title") values (?, ?::"public"."deck_type", ?) returning "public"."deck"."id", "public"."deck"."title", "public"."deck"."deck_type", "public"."deck"."created", "public"."deck"."updated", "public"."deck"."original_created", "public"."deck"."original_updated", "public"."deck"."confidential"`
`21:07:24.253 [Test worker] DEBUG org.jooq.tools.LoggerListener - -> with bind values      : insert into "public"."deck" ("foreign_id", "deck_type", "title") values ('12345', 'DRAFT', 'Crazy Physics') returning "public"."deck"."id", "public"."deck"."title", "public"."deck"."deck_type", "public"."deck"."created", "public"."deck"."updated", "public"."deck"."original_created", "public"."deck"."original_updated", "public"."deck"."confidential"`
```
21:07:24.261 [Test worker] DEBUG org.jooq.tools.LoggerListener - Exception                
org.jooq.exception.DataAccessException: SQL [null]; Error while reading field: "public"."deck"."id", at JDBC index: 1
    at org.jooq_3.11.5.POSTGRES_10.debug(Unknown Source)

```
```
com.chegg.deck.service.dao.DeckRepositoryCreateDeckTest > testCreateDeck() FAILED
    org.jooq.exception.DataAccessException: SQL [null]; Error while reading field: "public"."deck"."id", at JDBC index: 1
        at org.jooq_3.11.5.POSTGRES_10.debug(Unknown Source)
        at org.jooq_3.11.5.POSTGRES_10.debug(Unknown Source)
        at org.jooq.impl.Tools.translate(Tools.java:2384)
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:811)
        at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1634)
        at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1585)
        at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:407)
        at org.jooq.impl.CursorImpl.fetch(CursorImpl.java:393)
        at org.jooq.impl.CursorImpl.fetch(CursorImpl.java:300)
        at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:839)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:350)
        at org.jooq.impl.InsertImpl.fetchOne(InsertImpl.java:1061)
        at com.chegg.deck.service.dao.DeckRepository.createDeck(DeckRepository.java:151)
        at com.chegg.deck.service.dao.DeckRepositoryCreateDeckTest.testCreateDeck(DeckRepositoryCreateDeckTest.java:49)

```
       ```
 Caused by:
        java.sql.SQLException: Error while reading field: "public"."deck"."id", at JDBC index: 1
            at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1730)
            at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.operate(CursorImpl.java:1689)
            at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.operate(CursorImpl.java:1654)
            at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:125)
            at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1618)
            ... 9 more
```

            ```
Caused by:
            java.lang.ClassCastException: java.base/java.lang.String cannot be cast to java.base/java.util.UUID
                at org.jooq.impl.DefaultBinding$DefaultUUIDBinding.get0(DefaultBinding.java:3709)
                at org.jooq.impl.DefaultBinding$DefaultUUIDBinding.get0(DefaultBinding.java:3656)
                at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:774)
                at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1720)
                ... 13 more

```

**Comment by lukaseder** [comment]
I would need some help to reproduce what could be a bug. Would you mind creating a new issue with detailed instructions on reproduction, possibly creating an https://github.com/jOOQ/jOOQ-mcve ?
