### ISSUE TITLE
Add code generation configuration flag to set Connection.setAutoCommit()

### ISSUE THREAD

**Issue by galleog** [jOOQ/jOOQ#8407]
### Use case:

jOOQ code generator assumes that auto commit is set to true. Otherwise it doesn't work at least for PostgreSQL. But when using Testcontainers I can set an init function that will be invoked in the same connection before the code generator (e.g. to use Liquibase or Flyway to prepare a database). Liquibase sets explicitly auto commit to false. I suppose Flyway does the same. So I have to find out why the code generator doesn't work and then reset auto commit.

### Possible solution you'd like to see:

I think jOOQ code generator should explicitly set auto commit to true instead of assuming it.

### Possible workarounds:

Set auto commit to true manually.

### Versions:

- jOOQ: 3.11.9
- Java: 8
- Database (include vendor): PostgreSQL 10.7
- OS: Linux
- JDBC Driver (include name if inofficial driver): 42.2.5

**Comment by lukaseder** [comment]
Thank you very much for your request.

This is interesting. In 10 years of jOOQ's existence, this doesn't seem to have caused any issues at all. The code generator can work with any JDBC connection and the auto commit value shouldn't be of importance. Would you mind explaining (and perhaps showing how to reproduce this), why this is important to you?

Do note that you can pass the code generator any JDBC connection, or JDBC URL that initialises the connection to something different from the defaults.

**Comment by galleog** [comment]
The problem I faced is with check for Postgres version. PostgresDatabase#is11 throws a SQLException if there's no pg_proc.prokind column. After it all other queries are just rollbacked:
org.jooq.exception.DataAccessException: SQL [select array[1, 2] && array[2, 3]]; ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.jooq_3.11.9.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2384)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:832)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:364)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:323)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2700)
	at org.jooq.meta.postgres.PostgresDatabase.canCombineArrays(PostgresDatabase.java:891)
	at org.jooq.meta.postgres.PostgresDatabase.getRoutines0(PostgresDatabase.java:768)
	at org.jooq.meta.AbstractDatabase.getRoutines(AbstractDatabase.java:1664)
	at org.jooq.codegen.JavaGenerator.generateSchemaIfEmpty(JavaGenerator.java:418)
	at org.jooq.codegen.JavaGenerator.generateCatalogIfEmpty(JavaGenerator.java:405)
	at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:379)
	at org.jooq.codegen.GenerationTool.run(GenerationTool.java:752)
	at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:222)
	at org.jooq.codegen.GenerationTool.main(GenerationTool.java:194)
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:132)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:3494)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:268)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:350)
	... 11 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: column pg_proc.prokind does not exist
  Hint: Perhaps you meant to reference the column "pg_proc.probin".
  Position: 8
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:132)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:3494)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:268)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:350)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:323)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2700)
	at org.jooq.meta.postgres.PostgresDatabase.is11(PostgresDatabase.java:873)
	at org.jooq.meta.postgres.PostgresDatabase.getRoutines0(PostgresDatabase.java:757)
	... 7 common frames omitted

**Comment by galleog** [comment]
As I said the problem only occurs if I use Testcontainers with url like this:
`dbc:tc:postgresql:10.7-alpine://localhost/databasename?TC_INITFUNCTION=com.github.galleog.liquibase.tc.LiquibaseUpdater::update`
where the init function I use is:
```java
public static void update(Connection connection) throws LiquibaseException, SQLException {
        Liquibase liquibase = createLiquibase(connection);
        liquibase.update((String) null);
    }
```
If I add
```java
connection.setAutoCommit(true);
```
at the very end of the function everything works fine.

**Comment by lukaseder** [comment]
Interesting, thanks for the additional details. I see your point. We'll add a configuration flag to the `<jdbc>` configuration element regarding the autocommit JDBC flag.
