### ISSUE TITLE
PostgreSQL: array(<domain over UUID>) causes exception

### ISSUE THREAD

**Issue by pbillen** [jOOQ/jOOQ#8439]
jOOQ has problems with the following `array()` queries:

* `select array(<select query>)`
* `select array(<column in t>) from t`
* ...

This only happens when the columns are a domain over an UUID. Regular/direct UUIDs work fine. I did not verify, but maybe/probably this issue is also present in the `array_agg()` function.

We get the following exception:

```
org.jooq.exception.DataTypeException: Cannot convert from 4dd16c6d-8134-422e-9781-b4861b97f7a3 (class org.postgresql.util.PGobject) to class java.util.UUID
	at org.jooq.tools.Convert$ConvertAll.fail(Convert.java:1166)
	at org.jooq.tools.Convert$ConvertAll.from(Convert.java:1055)
```

### Versions:

- jOOQ: 3.11.9
- Java: 8
- Database (include vendor): PostgreSQL

**Comment by pbillen** [comment]
Please find a self-contained example in the referenced repository (https://github.com/pbillen/playground-jooq-8439).

You need a (local) Docker daemon to run this. Executing `mvn clean install -U` should be enough.

The relevant files are:

* https://github.com/pbillen/playground-jooq-8439/blob/master/src/test/docker/postgresql/schema.sql
* https://github.com/pbillen/playground-jooq-8439/blob/master/src/test/java/T.java

Let me know if you need more info from me ;).

**Comment by lukaseder** [comment]
Thank you very much for your report. We currently do not have any explicit support for PostgreSQL's domains yet, see #681. This means that our integration tests are unaware of any caveats that may appear when integrating with them.

In my opinion, however, the presence of a domain (which is really just a named, global check constraint) should not affect the data type that is produced by the JDBC driver. If the JDBC driver can produce `UUID` and `UUID[]` types without domains, I would suggest it is a bug for the JDBC driver to fall back to `PGobject` in this case.

Can you try to see what happens when you run similar queries with JDBC directly? And if you think there's wrong behaviour by the driver, perhaps report the issue here as well: https://github.com/pgjdbc/pgjdbc

As a workaround, you might probably be able to manually cast your `id_uuid` type to `uuid`, or `id_uuid[]` to `uuid[]`

**Comment by lukaseder** [comment]
Finally looking into this now. `DOMAIN` types have long been supported (#681), so it would be safe to expect this to work. Yet, I'm still getting this stack trace in the logs:

```
org.jooq.exception.DataTypeException: Cannot convert from 46e33c09-c0a9-4f4f-b379-15d53e5b8d81 (class org.postgresql.util.PGobject) to class java.util.UUID
	at org.jooq.impl.Convert$ConvertAll.fail(Convert.java:1591) ~[jooq-3.18.4.jar:?]
	at org.jooq.impl.Convert$ConvertAll.from(Convert.java:1432) ~[jooq-3.18.4.jar:?]
	at org.jooq.impl.Convert.convert0(Convert.java:442) ~[jooq-3.18.4.jar:?]
	at org.jooq.impl.Convert.convert(Convert.java:517) ~[jooq-3.18.4.jar:?]
	at org.jooq.impl.DefaultBinding$DefaultUUIDBinding.get0(DefaultBinding.java:4844) ~[jooq-3.18.4.jar:?]
	at org.jooq.impl.DefaultBinding$DefaultUUIDBinding.get0(DefaultBinding.java:4778) ~[jooq-3.18.4.jar:?]
	at org.jooq.impl.DefaultBinding$InternalBinding.get(DefaultBinding.java:1071) ~[jooq-3.18.4.jar:?]
	at org.jooq.impl.DefaultBinding$DefaultArrayBinding.pgGetArray(DefaultBinding.java:1430) [jooq-3.18.4.jar:?]
	at org.jooq.impl.DefaultBinding$DefaultArrayBinding.get0(DefaultBinding.java:1356) [jooq-3.18.4.jar:?]
	at org.jooq.impl.DefaultBinding$DefaultArrayBinding.get0(DefaultBinding.java:1217) [jooq-3.18.4.jar:?]
	at org.jooq.impl.DefaultBinding$InternalBinding.get(DefaultBinding.java:1071) [jooq-3.18.4.jar:?]
	at org.jooq.impl.CursorImpl$CursorRecordInitialiser.setValue(CursorImpl.java:1581) [jooq-3.18.4.jar:?]
	at org.jooq.impl.CursorImpl$CursorRecordInitialiser.apply(CursorImpl.java:1517) [jooq-3.18.4.jar:?]
	at org.jooq.impl.CursorImpl$CursorRecordInitialiser.apply(CursorImpl.java:1432) [jooq-3.18.4.jar:?]
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144) [jooq-3.18.4.jar:?]
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1389) [jooq-3.18.4.jar:?]
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1365) [jooq-3.18.4.jar:?]
	at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:173) [jooq-3.18.4.jar:?]
	at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:177) [jooq-3.18.4.jar:?]
	at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:88) [jooq-3.18.4.jar:?]
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:265) [jooq-3.18.4.jar:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:357) [jooq-3.18.4.jar:?]
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:290) [jooq-3.18.4.jar:?]
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2838) [jooq-3.18.4.jar:?]
	at org.jooq.mcve.test.java.postgres.JavaTest.mcveTest(JavaTest.java:130) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

And a result of all nulls. Looking into this now.

**Comment by lukaseder** [comment]
From the wire protocol, it looks like the encoding of the field types is this:

```
[Field(uuid,UUID,16,T), Field(array,UUID_ARRAY,65535,T), Field(array,<unknown:1787892>,65535,T)]
```

So, the jdbc driver can't really handle the domain type array. But jOOQ knows the expected type, so we can implement code that expects `PGobject`

**Comment by lukaseder** [comment]
Fixed in version:

- 3.19.0
- 3.18.5 (https://github.com/jOOQ/jOOQ/issues/15192)
- 3.17.14 (https://github.com/jOOQ/jOOQ/issues/15193)
- 3.16.20 (https://github.com/jOOQ/jOOQ/issues/15194)
