### ISSUE TITLE
jooq with ojdbc18.3, insert into table get sql exception "Invalid argument(s) in call"

### ISSUE THREAD

**Issue by yigongge** [jOOQ/jOOQ#8538]
### Your question:
We have the Professional version to support Oracle database. After updating to ojdbc driver 18.3, we are getting exception using record.insert() method to insert a a row. stacktrace as following:

<SQL [insert into "MEDORA"."SYS_LOGON_HISTORY" ("SYS_LOGON_HISTORY_ID", "SYLH_STAFF_MEMBER_ID", "SYLH_STAFF_MEMBER_CODE", "SYLH_STAFF_MEMBER_ACCOUNT_NAME", "SYLH_LOGON_FAILED_DATE") values (?, ?, ?, ?, cast(? as date))]; Invalid argument(s) in call> 
org.jooq.exception.DataAccessException: SQL [insert into "MEDORA"."SYS_LOGON_HISTORY" ("SYS_LOGON_HISTORY_ID", "SYLH_STAFF_MEMBER_ID", "SYLH_STAFF_MEMBER_CODE", "SYLH_STAFF_MEMBER_ACCOUNT_NAME", "SYLH_LOGON_FAILED_DATE") values (?, ?, ?, ?, cast(? as date))]; Invalid argument(s) in call
	at org.jooq.impl.Utils.translate(Utils.java:1553)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:609)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:355)
	at org.jooq.impl.TableRecordImpl.storeInsert0(TableRecordImpl.java:176)
	at org.jooq.impl.TableRecordImpl$1.operate(TableRecordImpl.java:142)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:123)
	at org.jooq.impl.TableRecordImpl.storeInsert(TableRecordImpl.java:138)
	at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:131)
	at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:126)
	at com.ge.med.medora.services.fiber.auth.core.DbOperationHandler$1.run(DbOperationHandler.java:187)
	at org.jooq.impl.DefaultDSLContext$1.run(DefaultDSLContext.java:342)
	at org.jooq.impl.DefaultDSLContext$1.run(DefaultDSLContext.java:339)
	at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:308)
	at org.jooq.impl.DefaultDSLContext.transaction(DefaultDSLContext.java:339)
	at com.ge.med.medora.services.fiber.auth.core.DbOperationHandler.logLoginFailure(DbOperationHandler.java:175)
	at com.ge.med.medora.services.fiber.auth.core.AuthenticationDelegator.authenticateUser(AuthenticationDelegator.java:134)
	at com.ge.med.medora.services.fiber.auth.UserAuthenticationServiceImpl.authenticate(UserAuthenticationServiceImpl.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at weblogic.wsee.jaxws.WLSInstanceResolver$WLSInvoker.invoke(WLSInstanceResolver.java:120)
	at weblogic.wsee.jaxws.WLSInstanceResolver$WLSInvoker.invoke(WLSInstanceResolver.java:93)
	at com.sun.xml.ws.server.InvokerTube$2.invoke(InvokerTube.java:149)
	at com.sun.xml.ws.server.sei.SEIInvokerTube.processRequest(SEIInvokerTube.java:88)
	at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:1136)
	at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:1050)
	at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:1019)
	at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:877)
	at com.sun.xml.ws.server.WSEndpointImpl$2.process(WSEndpointImpl.java:419)
	at com.sun.xml.ws.transport.http.HttpAdapter$HttpToolkit.handle(HttpAdapter.java:868)
	at com.sun.xml.ws.transport.http.HttpAdapter.handle(HttpAdapter.java:422)
	at com.sun.xml.ws.transport.http.servlet.ServletAdapter.handle(ServletAdapter.java:169)
	at weblogic.wsee.jaxws.WLSServletAdapter.handle(WLSServletAdapter.java:246)
	at weblogic.wsee.jaxws.HttpServletAdapter$AuthorizedInvoke.run(HttpServletAdapter.java:667)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:368)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:163)
	at weblogic.wsee.util.ServerSecurityHelper.authenticatedInvoke(ServerSecurityHelper.java:108)
	at weblogic.wsee.jaxws.HttpServletAdapter$3.run(HttpServletAdapter.java:286)
	at weblogic.wsee.jaxws.HttpServletAdapter.post(HttpServletAdapter.java:295)
	at weblogic.wsee.jaxws.JAXWSServlet.doRequest(JAXWSServlet.java:128)
	at weblogic.servlet.http.AbstractAsyncServlet.service(AbstractAsyncServlet.java:103)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:286)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:260)
	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:137)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:350)
	at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:25)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3701)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3667)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:326)
	at weblogic.security.service.SecurityManager.runAsForUserCode(SecurityManager.java:197)
	at weblogic.servlet.provider.WlsSecurityProvider.runAsForUserCode(WlsSecurityProvider.java:203)
	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:71)
	at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2443)
	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2291)
	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2269)
	at weblogic.servlet.internal.ServletRequestImpl.runInternal(ServletRequestImpl.java:1703)
	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1663)
	at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:272)
	at weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:352)
	at weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:337)
	at weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:57)
	at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
	at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:644)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:415)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:355)
Caused by: java.sql.SQLException: Invalid argument(s) in call
	at oracle.jdbc.driver.AutoKeyInfo.getNewSql(AutoKeyInfo.java:188)
	at oracle.jdbc.driver.PhysicalConnection.prepareStatement(PhysicalConnection.java:4821)
	at weblogic.jdbc.common.internal.ConnectionEnv.makeStatement(ConnectionEnv.java:2196)
	at weblogic.jdbc.common.internal.ConnectionEnv.getCachedStatement(ConnectionEnv.java:1902)
	at weblogic.jdbc.wrapper.Connection.prepareStatement(Connection.java:1059)
	at org.jooq.impl.ProviderEnabledConnection.prepareStatement(ProviderEnabledConnection.java:139)
	at org.jooq.impl.SettingsEnabledConnection.prepareStatement(SettingsEnabledConnection.java:128)
	at org.jooq.impl.AbstractStoreQuery.prepare(AbstractStoreQuery.java:310)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:315)
	... 67 more

We tried with plain JDBC preparestatement insert into this table, then it works, but with JOOQ layer it doesn't.
Any idea how to fix this?
### Versions:

- jOOQ: 3.5.3
- Java:.1.8.202
- Database (include vendor): oracle
- OS: windows server 2016
- JDBC Driver (include name if inofficial driver): ojdbc 18.3

**Comment by lukaseder** [comment]
Thank you very much for your report. Does the problem persist with newer versions of jOOQ? If yes, could you please provide us with a sample `CREATE TABLE` statement to reproduce your table definition, and the exact jOOQ code that you called that produced this problem?

**Comment by yigongge** [comment]
Hi, I am not allowed to publish the DDL, but I'll prepare a demo table.
yes, I tried with 3.11.10, the same error.

**Comment by yigongge** [comment]
Hi, one table:
CREATE TABLE jooq_test_table (
  test_id           NUMBER(22) NOT NULL PRIMARY KEY,
  user_id           NUMBER(22),
  user_name VARCHAR2(64) NOT NULL
)

CREATE SEQUENCE seq_id
  START WITH 1000000000000
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER
/


One thing I have to mention is that, the characterset of oracle is 'we8mswin1252'.

And the code snippet:
  try (Connection conn = DriverManager.getConnection(connectionUrl, user, password)) {
            DSLContext dslContext = DSL.using(conn, SQLDialect.ORACLE10G);
            BigDecimal seq = new BigDecimal(dslContext.nextval(Sequences.Seq_id));
            final JooqTestTableRecord someRecord = dslContext.newRecord(JOOQ_TEST_TABLE);
            someRecord.insert();
} catch (Exception e) {
            e.printStackTrace();
        }

**Comment by yigongge** [comment]
And the stacktrace:
org.jooq.exception.DataAccessException: SQL [insert into "MEDORA"."JOOQ_TEST_TABLE" ("TEST_ID", "USER_NAME") values (?, ?)]; Invalid argument(s) in call
	at org.jooq_3.11.9.ORACLE10G.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2429)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:832)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:364)
	at org.jooq.impl.TableRecordImpl.storeInsert0(TableRecordImpl.java:202)
	at org.jooq.impl.TableRecordImpl$1.operate(TableRecordImpl.java:173)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:125)
	at org.jooq.impl.TableRecordImpl.storeInsert(TableRecordImpl.java:169)
	at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:157)
	at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:152)
	at com.ge.med.medora.fiber.dbaccess.tables.JdbcDriverJooqDemoTableTest.main(JdbcDriverJooqDemoTableTest.java:51)
Caused by: java.sql.SQLException: Invalid argument(s) in call
	at oracle.jdbc.driver.AutoKeyInfo.getNewSql(AutoKeyInfo.java:187)
	at oracle.jdbc.driver.PhysicalConnection.prepareStatement(PhysicalConnection.java:4400)
	at org.jooq.impl.ProviderEnabledConnection.prepareStatement(ProviderEnabledConnection.java:136)
	at org.jooq.impl.SettingsEnabledConnection.prepareStatement(SettingsEnabledConnection.java:125)
	at org.jooq.impl.AbstractDMLQuery.prepare(AbstractDMLQuery.java:599)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:322)
	... 7 more

**Comment by lukaseder** [comment]
Thank you very much for providing this additional information. The interesting bit here for me is you're using `ORACLE10G` as a dialect (visibl from the stack trace). Does ojdbc18.3 really support Oracle 10g? In the past, we've noticed similar issues with server/client version mismatches, also related to insert statements and fetching of generated keys.

Of course, you could try turning of the fetching of generated keys using `Settings.returnIdentityOnUpdatableRecord` if you do not rely on this functionality.

Given that this is a fairly common operation among people using jOOQ and Oracle, I would suspect that this must be related to the driver version.

**Comment by yigongge** [comment]
Hi,
sorry for the oracle10g, I also used oracle12c for testing, the problem stays the same.
Settings.returnIdentityOnUpdatableRecord, I cannot find the setting in 3.11 but one for 3.12
https://www.jooq.org/doc/3.12/manual/sql-building/dsl-context/custom-settings/settings-return-identity-on-store/

Is it possible in the version 3.11 to turn off the setting somewhere?

**Comment by lukaseder** [comment]
You're right, I'm sorry for the confusion. That setting has only been introduced with jOOQ 3.12 (#7966). I will try to reproduce this with your character set configuration and provide further feedback here.

**Comment by lukaseder** [comment]
I cannot reproduce this issue with the code you've provided and ojdbc8 for Oracle 18.3 on Oracle 12c.

Would it be possible to provide an MCVE (e.g. starting from this template https://github.com/jOOQ/jooq-mcve) to help reproduce this?

Can you reproduce this kind of problem when using JDBC directly?

**Comment by yigongge** [comment]
Hi,
do you change the characterset of Oracle to we8mswin1252, I assume this is related to characterset.

Yes, I tried directly with JDBC using preparedstatement, the problem doesn't occurs.

I have to ask for permission if it is is allowed to provide an MCVE. I'll let you know as soon as possible.

**Comment by yigongge** [comment]
Hi Lukas,
one update from my side, I tried another method from DSLContext context.executeInsert( record ), it works without any exception, but still with record,insert(), it doesn't work.

Are these two methods totally different? or just some default configurations are different.

**Comment by yigongge** [comment]
Hi Lukas, 
I still working on this issue, and find out the place where the problem occurs.
Once the method prepare(ExecuteContext ctx) in AbstractDMLQuery at line 599  ctx.statement(connection.prepareStatement(ctx.sql(), names)); 
called, there will be an sqlexception.

if it goes to line 512, super.prepare(ctx), then will work
 /* [/pro] */if (returning.isEmpty()) {
            super.prepare(ctx);
            return;
        }

The version I'm working on is the 3.11.10

regards,
Yi

**Comment by lukaseder** [comment]
Hi @yigongge 

Sorry for the delay in this matter. The previous notifications seemed to get caught by an email filter. I will look at this again today.

**Comment by yigongge** [comment]
Hi Lukas, one thing, please don't forget to change the NLS_CHARACTERSET to "WE8MSWIN1252", if you want to test it.

regards,
Yi

**Comment by lukaseder** [comment]
> one update from my side, I tried another method from DSLContext context.executeInsert( record ), it works without any exception, but still with record,insert(), it doesn't work.

Indeed, they're not strictly the same. `DSLContext.executeInsert()` does not fetch any generated keys, whereas `TableRecord.insert()` does. As mentioned before, this can be turned off also for `TableRecord`, by using `Settings.returnIdentityOnUpdatableRecord`

> I still working on this issue, and find out the place where the problem occurs. Once the method prepare(ExecuteContext ctx) in AbstractDMLQuery at line 599 ctx.statement(connection.prepareStatement(ctx.sql(), names));

This is also again related to returning the identity via JDBC. Now that you mention this particular line (and I still wasn't able to reproduce this even with a different encoding), what is the name of your table / columns? Perhaps that's relevant, as this method uses a `String[]` with column names, which might be sent using the wrong encoding, perhaps?

**Comment by yigongge** [comment]
Hi Lukas, 
thank you very much for explaining the difference of those two methods.
I'll prepare and submit the example code to mcve the coming week. Actually the table column names are ASCII standard charactors.

**Comment by yigongge** [comment]
Hi Lukas, 
I tries also plain JDBC , find out a very interesting thing when using 
String[] strings = {"user_id"};
connection.prepareStatement(INSERT_RECORD_SQL, strings);

if the array strings has more than one entries, then java.sql.SQLException: Invalid argument(s) in call
	at oracle.jdbc.driver.AutoKeyInfo.getNewSql(AutoKeyInfo.java:187)
	at oracle.jdbc.driver.PhysicalConnection.prepareStatement(PhysicalConnection.java:4342)

I think this maybe the root cause

**Comment by lukaseder** [comment]
Indeed, that could be the link here. I've observed there seem to be similar issues on the web:

- https://coderanch.com/t/683517/databases/SQL-exception-ojdbc-Jar
- https://support.oracle.com/knowledge/Middleware/2278611_1.html

Could this be a JDBC driver bug? If I read your comments correctly, you have tried different database (server) versions. But have you also tried using different jdbc driver versions?

Since this only happens when you have several column names in that array: Do you happen to have `Settings.returnAllOnUpdatableRecord` set to true? If so, this could be turned off to produce single column arrays.

Another case when this could happen is when the identity and the primary key are not the same value, or when the primary key has multiple columns. This was not the case in your test table, though. I can't see how the example code you provided here can produce multiple columns in this array: https://github.com/jOOQ/jOOQ/issues/8538#issuecomment-484422495

But since in this example, you use a sequence and fill that sequence in the client, you could definitely live without fetching generated keys in this record, so turning off the feature `Settings.returnIdentityOnUpdatableRecord` entirely, or avoiding `UpdatableRecord` API would help in this case, as a workaround.

An entirely different workaround would be to proxy your JDBC driver before passing it to jOOQ, or alternatively, to proxy the JDBC Connection in an `ConnectionProvider`. Your proxy could override this particular JDBC method and replace the call that causes trouble by a call to `Connection.prepareStatement(String, int)`. Here's an example implementation of such a `ConnectionProvider`:

```java
package org.jooq;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import org.jooq.tools.jdbc.DefaultConnection;

public class ConnectionProviderWorkaround8538 implements ConnectionProvider {
    final ConnectionProvider delegate;

    public ConnectionProviderWorkaround8538(ConnectionProvider delegate) {
        this.delegate = delegate;
    }

    @Override
    public Connection acquire() {
        return new ConnectionWorkaround8538(delegate.acquire());
    }

    @Override
    public void release(Connection connection) {
        if (connection instanceof ConnectionWorkaround8538)
            release(((ConnectionWorkaround8538) connection).getDelegate());
        else
            release(connection);
    }

    static class ConnectionWorkaround8538 extends DefaultConnection {
        public ConnectionWorkaround8538(Connection delegate) {
            super(delegate);
        }

        @Override
        public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
            return super.prepareStatement(sql, PreparedStatement.RETURN_GENERATED_KEYS);
        }
    }
}
```

In your example code snippet, you could then use:

```java
try (Connection conn = DriverManager.getConnection(connectionUrl, user, password)) {
  DSLContext dslContext = DSL.using(new ConnectionWorkaround8538(conn), SQLDialect.ORACLE10G);
  BigDecimal seq = new BigDecimal(dslContext.nextval(Sequences.Seq_id));
  final JooqTestTableRecord someRecord = dslContext.newRecord(JOOQ_TEST_TABLE);
  someRecord.insert();
} catch (Exception e) {
  e.printStackTrace();
}
```

Does this work?
