### ISSUE TITLE
StackOverflowError when using same query instance on both sides of a set operation

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8557]
The following logic produces a `StackOverflowError`:

```java
SelectSelectStep<Record1<Integer>> one =
DSL.using(new DefaultConfiguration())
   .selectOne();

one.unionAll(one);
one.getSQL();
```

Error:

```
Exception in thread "main" java.lang.StackOverflowError
	at org.jooq.impl.Alias.accept(Alias.java:134)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:561)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:446)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:207)
	at org.jooq.impl.FieldAlias.accept(FieldAlias.java:62)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:561)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:446)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:207)
	at org.jooq.impl.QueryPartList.accept(QueryPartList.java:121)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:561)
```

The reason is that the DSL API is still mutable (to be fixed with #2198), so when calling `one.unionAll(one)`, the left instance is being modified and it will refer to itself on the right side, which leads to an infinite number of unions.

Putting a breakpoint in that path shows that we're generating this kind of SQL:

```sql
(select 1 "one") union all (
  (select 1 "one") union all (
    (select 1 "one") union all (
      (select 1 "one") union all (
        (select 1 "one") union all (
          (select 1 "one") union all (
            (select 1 "one") union all (...
```

We could fix this

- by returning a new object from the union call, moving towards immutability (backwards incompatible)
- by making a copy of the right side of the union (possibly not a thorough fix, and with other subtly backwards incompatible side effects if someone expects not to have their query copied)
- by checking identities of queries and throwing a more meaningful exception

The third option introduces the least amount of risk and fixes the problem of the unexpected `StackOverflowError`, which is difficult to debug.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.12. Backport scheduled for 3.11.12 (#8558)
