### ISSUE TITLE
not able to generate source file

### ISSUE THREAD

**Issue by nilgadia** [jOOQ/jOOQ#8565]
I am using oracle 18.0.0 and jooq - 3.11.5
select distinct "SYS"."ALL_USERS"."USERNAME"
from "SYS"."ALL_USERS"```

[ERROR] Could not load schemata
org.jooq.exception.DetachedException: Cannot execute query. No Connection configured
        at org.jooq_3.11.5.ORACLE.debug(Unknown Source)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:319)
        at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:323)
        at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:421)
        at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2759)
        at org.jooq.meta.oracle.OracleDatabase.getSchemata0(OracleDatabase.java:338)
        at org.jooq.meta.AbstractDatabase.getSchemata(AbstractDatabase.java:447)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[WARNING] No schemata were loaded  : Please check your connection settings, and whether your database (and your database version!) is really supported by jOOQ. Also, check the case-sensitivity in your configured <inputSchema/> elements : null

**Comment by lukaseder** [comment]
Thank you very much for your report. The error message indicates that your code generator is not connected to a database instance. What is your complete code generator configuration? Are there any other errors that precede this one in the log output?

**Comment by nilgadia** [comment]
Please let me know if JOOQ support oracle version 18.0.0. It was working with 12c. Any thought?

**Comment by lukaseder** [comment]
jOOQ supports Oracle 18, but I doubt that this is the source of your problem, as per the error message, which seems quite clear to me.

**Comment by nilgadia** [comment]
Thanks lukaseder for your input. There was problem with oracle image.

**Comment by lukaseder** [comment]
Thanks for your feedback. So I'm assuming everything is OK now.

**Comment by nilgadia** [comment]
Yes all ok
