### ISSUE TITLE
Code generation missing Redshift database

### ISSUE THREAD

**Issue by thiagoretondar** [jOOQ/jOOQ#8872]
### Your question:
When running **code generation** for a Redshift Database it throws the following Exception:

```
java.lang.ClassNotFoundException: Your configured database type was not found. This can have several reasons:
- You want to use a commercial jOOQ Edition, but you pulled the Open Source Edition from Maven Central.
- You have mis-typed your class name.
	at org.jooq.codegen.GenerationTool.loadClass(GenerationTool.java:857)
	at org.jooq.codegen.GenerationTool.run(GenerationTool.java:364)
	at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:222)
	at org.jooq.codegen.GenerationTool.main(GenerationTool.java:194)
Caused by: java.lang.ClassNotFoundException: org.jooq.meta.redshift.RedshiftDatabase
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.jooq.codegen.GenerationTool.loadClass(GenerationTool.java:821)
	... 3 more
```

I'm running **Jooq with Gradle on Spring Boot with Kotlin**. Here is my configuration on build.gradle:

```
jooq {
    mydb(sourceSets.main) {
        jdbc {
            driver = 'com.amazon.redshift.jdbc42.Driver'
            url = 'jdbc:redshift://host:5439/mydb'
            user = 'user'
            password = '****'
        }
        generator {
            name = 'org.jooq.codegen.DefaultGenerator'
            strategy {
                name = 'org.jooq.codegen.DefaultGeneratorStrategy'
            }
            database {
                name = 'org.jooq.meta.redshift.RedshiftDatabase'
                inputSchema = 'public'
                excludes = "flyway_.*"
            }
            generate {
                relations = true
                deprecated = false
                records = false
                immutablePojos = true
                fluentSetters = true
            }
            target {
                packageName = 'my.package.database.schema'
                directory = 'src/main/java'
            }
        }
    }
}
```

And here is how I install Jooq on build.gradle
```
plugins {
    id 'org.springframework.boot' version '2.1.4.RELEASE'
    id 'org.jetbrains.kotlin.jvm' version '1.2.71'
    id 'org.jetbrains.kotlin.plugin.spring' version '1.2.71'
    id 'nu.studer.jooq' version '3.0.3'
}

...

dependencies {
    // JDBC
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation('org.springframework.boot:spring-boot-starter-jooq') {
        exclude group: 'org.jooq', module: 'jooq'
    }
    compile 'org.jooq:jooq:3.11.11'
    compile 'org.jooq:jooq-codegen:3.11.11'
    compile 'org.jooq:jooq-meta:3.11.11'

    // REDSHIFT DRIVER
    compile 'com.amazon.redshift:redshift-jdbc42-no-awssdk:1.2.10.1009'
    jooqRuntime 'com.amazon.redshift:redshift-jdbc42-no-awssdk:1.2.10.1009'
}
```

Is Redshift supported on open source edition?

### Versions:

- jOOQ: 3.11.11
- Java: OpenJDK 11
- Database (include vendor): AWS Redshift
- OS: Mac OS
- JDBC Driver (include name if inofficial driver): com.amazon.redshift.jdbc42.Driver

**Comment by lukaseder** [comment]
Thank you very much for your report. You have closed this issue already - I take that you've found the solution.

If there's anything we can help you with, please let us know and we'll be very happy to assist.
