### ISSUE TITLE
Cannot use INSERT .. RETURNING in Oracle to fetch back a UDT

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8901]
When running an `INSERT .. RETURNING` statement on a table that contains UDTs, the standard implementation passing by `Statement.getGeneratedKeys()` produces an exception:

```
org.jooq.exception.DataAccessException: SQL [insert into TEST.T_AUTHOR (ID, LAST_NAME) values (?, ?)]; Nicht unterstützter Spaltentyp
	at org.jooq_3.12.0-SNAPSHOT.ORACLE.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2696)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:755)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:383)
	at org.jooq.impl.InsertImpl.fetchOne(InsertImpl.java:1059)
	at org.jooq.test.all.testcases.InsertUpdateTests.testInsertReturningWithRenderNameStyleAS_IS(InsertUpdateTests.java:1894)
	at org.jooq.test.jOOQAbstractTest.testInsertReturningWithRenderNameStyleAS_IS(jOOQAbstractTest.java:3065)
Caused by: java.sql.SQLException: Nicht unterstützter Spaltentyp
	at oracle.jdbc.driver.OracleStatement.checkTypeForAutoKey(OracleStatement.java:6134)
	at oracle.jdbc.driver.OraclePreparedStatement.registerReturnParamsForAutoKey(OraclePreparedStatement.java:11989)
	at oracle.jdbc.driver.PhysicalConnection.prepareStatement(PhysicalConnection.java:7781)
	at org.jooq.tools.jdbc.DefaultConnection.prepareStatement(DefaultConnection.java:269)
	at org.jooq.test.utils.LoggingConnection.prepareStatement(LoggingConnection.java:115)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.jdbc.datasource.SingleConnectionDataSource$CloseSuppressingInvocationHandler.invoke(SingleConnectionDataSource.java:333)
	at com.sun.proxy.$Proxy28.prepareStatement(Unknown Source)
	at org.jooq.impl.ProviderEnabledConnection.prepareStatement(ProviderEnabledConnection.java:136)
	at org.jooq.impl.SettingsEnabledConnection.prepareStatement(SettingsEnabledConnection.java:125)
	at org.jooq.impl.AbstractDMLQuery.prepare0(AbstractDMLQuery.java:776)
	at org.jooq.impl.AbstractDMLQuery.prepare(AbstractDMLQuery.java:671)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:336)
	... 32 more
```

If we *know* one of our columns produces such a data type, then we should implement the PL/SQL emulation of `INSERT .. RETURNING`, implemented in jOOQ 3.11 via #5863 and #7452

**Comment by lukaseder** [comment]
This is not easy to emulate as we don't have a `DBMS_SQL.XXX_TABLE` type to use for the emulation. We'd have to find a different solution for multi row inserts.

If we had a specialised emulation for single row inserts, it could work: #8899
