### ISSUE TITLE
ArrayStoreException occurred when generate code with jpa

### ISSUE THREAD

**Issue by findcoo** [jOOQ/jOOQ#9098]
### Expected behavior and actual behavior:
successfully  generate codes but failed
```16:58:23.449 [main] ERROR org.jooq.codegen.GenerationTool - Cannot read /Users/build/tmp/generateMainJooqSchemaSource/config.xml. Error : Error while exporting schema
org.jooq.exception.DataAccessException: Error while exporting schema
	at org.jooq.meta.extensions.jpa.JPADatabase.create0(JPADatabase.java:165)
	at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:231)
	at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:220)
	at org.jooq.meta.AbstractDatabase.getDialect(AbstractDatabase.java:202)
	at org.jooq.codegen.AbstractGenerator.logDatabaseParameters(AbstractGenerator.java:155)
	at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:299)
	at org.jooq.codegen.GenerationTool.run(GenerationTool.java:752)
	at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:222)
	at org.jooq.codegen.GenerationTool.main(GenerationTool.java:194)
Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:258)
	at java.lang.Class.isAnnotationPresent(Class.java:3425)
	at org.hibernate.annotations.common.reflection.java.JavaAnnotationReader.isAnnotationPresent(JavaAnnotationReader.java:33)
	at org.hibernate.annotations.common.reflection.java.JavaXAnnotatedElement.isAnnotationPresent(JavaXAnnotatedElement.java:43)
	at org.hibernate.boot.model.source.internal.annotations.AnnotationMetadataSourceProcessorImpl.categorizeAnnotatedClass(AnnotationMetadataSourceProcessorImpl.java:117)
	at org.hibernate.boot.model.source.internal.annotations.AnnotationMetadataSourceProcessorImpl.<init>(AnnotationMetadataSourceProcessorImpl.java:110)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess$1.<init>(MetadataBuildingProcess.java:156)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:150)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:84)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:474)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:85)
	at org.hibernate.boot.MetadataSources.buildMetadata(MetadataSources.java:180)
	at org.jooq.meta.extensions.jpa.JPADatabase.create0(JPADatabase.java:159)
	... 8 common frames omitted
```

``` kotlin
 configuration.apply {
        generator = Generator().apply {
            name = "org.jooq.codegen.DefaultGenerator"
            strategy = Strategy().apply {
                name = "org.jooq.codegen.DefaultGeneratorStrategy"
            }
            database = Database().apply {
                name = "org.jooq.meta.extensions.jpa.JPADatabase"
                properties = listOf(Property().apply {
                    key = "packages"
                    value = "com.common.domain"
                })
                includes = ".*"
            }
            target = Target().apply {
                packageName = "com.common.jooq"
                directory = "build/generated/jooq"
            }
        }
    }
```
as you see. it's a gradle build scirpt writed with kotlin dsl 

### Versions:
3.11.11

- jOOQ:
- Java: 8
- Database (include vendor): mysql
- OS: mac os
- JDBC Driver (include name if inofficial driver): optional because use a JPADatabase

**Comment by knutwannheden** [comment]
Based on this related [StackOverflow question](https://stackoverflow.com/questions/24352967/spring-boot-errorjava-lang-arraystoreexception-sun-reflect-annotation-typenotp) it looks like this is a classpath configuration issue. I suggest you look through the answers to this question and possibly also the linked pages:
* https://github.com/spring-projects/spring-boot/issues/1696
* https://stackoverflow.com/questions/25857126/spring-boot-requestmappinghandlermapping-java-lang-arraystoreexception

You should also be able to [use the debugger](https://stackoverflow.com/a/57416012/1732086) to find out which class isn't found.

This is most likely not a jOOQ issue. Please reopen if you find anything which suggests otherwise.

**Comment by lukaseder** [comment]
Can you check if there are conflicting versions of Hibernate on your classpath? It might be an issue that has already been fixed in Hibernate. We depend on Hibernate internally, in `jOOQ-meta-extensions`
