### ISSUE TITLE
Manual page about ParserCLI misses reactive-streams in classpath

### ISSUE THREAD

**Issue by JanecekPetr** [jOOQ/jOOQ#9145]
### Expected behavior and actual behavior:

The manual page about ParserCLI, https://www.jooq.org/doc/latest/manual/sql-building/sql-parser/sql-parser-cli/, contains an incomplete classpath. Since 3.12 it requires a reactive-streams jar, too.

I expect to simply copy-paste the CLI command from the manual page.

### Steps to reproduce the problem:

This is what I get when I run the command from the manual page:
```
$ java -cp jooq-3.12.1.jar org.jooq.ParserCLI -s "SELECT substring('abcde', 2, 3)"

Exception in thread "main" java.lang.NoClassDefFoundError: org/reactivestreams/Publisher
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.jooq.impl.DSL.using(DSL.java:473)
        at org.jooq.ParserCLI.ctx(ParserCLI.java:91)
        at org.jooq.ParserCLI.main(ParserCLI.java:70)
Caused by: java.lang.ClassNotFoundException: org.reactivestreams.Publisher
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 15 more
```

I have to run this to have a success:
```
$ java -cp "jooq-3.12.1.jar;reactive-streams-1.0.2.jar" \
        org.jooq.ParserCLI -s "SELECT substring('abcde', 2, 3)"

select substring('abcde', 2, 3);
```

### Versions:

- jOOQ: 3.12.1
- Java: 8u211
- Database: N/A
- OS: Cygwin on Windows 10
- JDBC Driver: N/A

**Comment by lukaseder** [comment]
Thanks a lot for your report. You're right, we'll have to add this to the manual, probably in various locations.

**Comment by lukaseder** [comment]
The great thing is, we now get to document both windows and linux classpath syntax everywhere... 🙄
