### ISSUE TITLE
ParserCLI -h parameter throws a RuntimeException

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9147]
When calling `-h` or `--help` on the `ParserCLI`, we get a `RuntimeException`, which isn't really necessary or nice:

```
Usage:
  -f / --formatted                        Format output SQL
  -h / --help                             Display this help
  -k / --keyword      <RenderKeywordCase> Specify the output keyword case (org.jooq.conf.RenderKeywordCase)
  -i / --identifier   <RenderNameCase>    Specify the output identifier case (org.jooq.conf.RenderNameCase)
  -f / --from-dialect <SQLDialect>        Specify the input dialect (org.jooq.SQLDialect)
  -t / --to-dialect   <SQLDialect>        Specify the output dialect (org.jooq.SQLDialect)
  -s / --sql          <String>            Specify the input SQL string

  -I / --interactive                      Start interactive mode
Mandatory arguments: -t and -s. Use -h for help
java.lang.RuntimeException
	at org.jooq.ParserCLI.main(ParserCLI.java:77)
	at org.jooq.test.ParserCLITest.testFlagFormatted(ParserCLITest.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)

```

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.13.0. Backport scheduled for 3.12.2 (#9149)
