### ISSUE TITLE
Parser throws exception on default null clause in modify column

### ISSUE THREAD

**Issue by codemonstur** [jOOQ/jOOQ#9247]
This sql:
```
CREATE TABLE `example` (
 `id` int(10) unsigned NOT NULL,
 `email` int(10) unsigned NOT NULL,
 PRIMARY KEY (`id`)
);

ALTER TABLE `example` MODIFY COLUMN `email` varchar(64) NULL DEFAULT NULL;
```
Generates this error from the parser (3.12.1):
```
Exception in thread "main" org.jooq.impl.ParserException: Unexpected token or missing query delimiter: [7:62] ... `example` MODIFY COLUMN `email` varchar(64) NULL [*]DEFAULT NULL;
	at org.jooq.impl.ParserContext.exception(ParserImpl.java:10667)
	at org.jooq.impl.ParserContext.done(ParserImpl.java:10787)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:550)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:529)
```

**Comment by knutwannheden** [comment]
Thanks for the report.

Indeed, the `DEFAULT` clause of the `ALTER TABLE ... MODIFY COLUMN` statement is currently not supported by the parser. We will look into fixing this.

**Comment by knutwannheden** [comment]
MySQL, and to some extent probably also other dialects, allows the `ALTER TABLE ... MODIFY COLUMN` statement to contain the same clauses as in `CREATE TABLE`:

![image](https://user-images.githubusercontent.com/408765/65314604-eb411880-db96-11e9-94f0-227055faf850.png)

The jOOQ parser currently allows for many of these clauses in `CREATE TABLE`, but not `ALTER TABLE ... MODIFY COLUMN`.

**Comment by lukaseder** [comment]
The problem we currently have here is that our representation of `DataType` does not allow for remembering if a DDL statement explicitly "touched" some flag (it needs to be modified).

**Comment by lukaseder** [comment]
Related: #9353
