### ISSUE TITLE
Support parsing ALTER TABLE .. ALTER COLUMN .. SET NULL syntax

### ISSUE THREAD

**Issue by taven** [jOOQ/jOOQ#9478]
### Expected behavior and actual behavior:
While parsing script source files an exception is thrown if trying to alter a table's column to be null. The parser should understand this line without throwing an exception.
### Steps to reproduce the problem:
Setup script parsing and parse in the following line:
```sql
ALTER TABLE TEST ALTER COLUMN NAME SET NULL;
```
When trying to run the generator the following exception is shown:
```
Error : Token '(' expected: [1:40] ALTER TABLE TEST ALTER COLUMN NAME SET [*]NULL;
	at org.jooq.impl.ParserContext.expected(ParserImpl.java:10649)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:10128)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:10123)
	at org.jooq.impl.ParserImpl.parseDataTypeEnum(ParserImpl.java:9361)
	at org.jooq.impl.ParserImpl.parseDataTypePrefix(ParserImpl.java:9173)
	at org.jooq.impl.ParserImpl.parseDataType(ParserImpl.java:9004)
	at org.jooq.impl.ParserImpl.parseAlterTableAlterColumn(ParserImpl.java:4009)
	at org.jooq.impl.ParserImpl.parseAlterTable(ParserImpl.java:3725)
	at org.jooq.impl.ParserImpl.parseAlter(ParserImpl.java:2197)
	at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:830)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:542)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:529)
	at org.jooq.meta.extensions.ddl.DDLDatabase.load(DDLDatabase.java:188)
	at org.jooq.meta.extensions.ddl.DDLDatabase.access$100(DDLDatabase.java:91)
	at org.jooq.meta.extensions.ddl.DDLDatabase$2.load(DDLDatabase.java:169)
	at org.jooq.meta.tools.FilePattern.load(FilePattern.java:165)
	at org.jooq.meta.tools.FilePattern.load(FilePattern.java:178)
	at org.jooq.meta.tools.FilePattern.load(FilePattern.java:184)
	at org.jooq.meta.tools.FilePattern.load(FilePattern.java:138)
	at org.jooq.meta.extensions.ddl.DDLDatabase.create0(DDLDatabase.java:166)
	at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:260)
	at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:249)
	at org.jooq.meta.AbstractDatabase.setConnection(AbstractDatabase.java:239)
	at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:501)
	at org.jooq.codegen.GenerationTool.run(GenerationTool.java:221)
	at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:216)
	at org.jooq.codegen.GenerationTool.main(GenerationTool.java:188)
```
### Versions:

- jOOQ: 3.12.2
- Java: 8
- Database: H2 1.4.200
- OS: Windows 10 x64

**Comment by lukaseder** [comment]
Thanks a lot for your report. Indeed, we currently don't support the `SET NULL` clause in the parser yet, but as a workaround, you can use `.. ALTER COLUMN c NULL` or `.. ALTER COLUMN c DROP NOT NULL`, the latter also being supported by H2: http://h2database.com/html/commands.html#alter_table_alter_column
