### ISSUE TITLE
DAO insert throws NPE

### ISSUE THREAD

**Issue by LeslieM98** [jOOQ/jOOQ#9489]
### Expected behavior and actual behavior:
Expected: Jooq should insert a generated Pojo which holds 2 foreign keys. 
Actual: Jooq throws NPE within 
### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):
Simply execute the linked test: 
https://github.com/LeslieM98/Generals-Server/blob/ef5e282eb64480a02c882e6adcdafd8b11e99156/Generals-Server/src/test/java/me/leslie/generals/server/repository/ArmyRepositoryTest.java#L50 on commit ef5e282eb64480a02c882e6adcdafd8b11e99156 on develop

### Versions:

- jOOQ: 3.12.2
- Java: openjdk 13.0.1 2019-10-15 \ OpenJDK Runtime Environment (build 13.0.1+9) \ OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode)
Java11 used in pom
- Database (include vendor): SQLite
- OS: 5.3.7-2-MANJARO
- JDBC Driver (include name if inofficial driver): org.xerial:sqlite-jdbc:3.28.0

**Comment by lukaseder** [comment]
Thank you very much for your report.

Unfortunately, it will not be possible to try to reproduce the problem by running your code, as it will not be possible to screen it for security issues in a reasonable amount of time, or debug any potential setup issues that may arise from running it on a different environment. Thanks for your understanding.

However, if you could provide a stack trace, I might be able to help track down the problem from looking at the sources alone.

Alternatively, our MCVE template could be useful to quickly setup a minimal example to help reproduce the case: https://github.com/jOOQ/jOOQ-mcve

**Comment by LeslieM98** [comment]
Thank you for your response.
I tried to create a MCVE yesterday but I thought that one test was sufficient. 
I haven't thought of any security concerns.
I will provide a stacktrace and later and then try to implement a small MCVE.

**Comment by lukaseder** [comment]
Thanks for your message. If the MCVE is too much hassle, a stack trace is already big help

**Comment by LeslieM98** [comment]
[Here](https://pastebin.com/maJbjuLh) is the Stacktrace.
I'll follow up with a MCVE soonish.

**Comment by lukaseder** [comment]
Thanks. Repeated here in case that link goes dead:

```
me.leslie.generals.server.repository.exception.UpdateFailedException: Could not insert Army (1, 3)
 
    at me.leslie.generals.server.repository.ArmyRepository.updateRelation(ArmyRepository.java:77)
    at me.leslie.generals.server.repository.ArmyRepositoryTest.createArmyAndGetArmy(ArmyRepositoryTest.java:55)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:567)
    at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
    at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
    at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:125)
    at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:132)
    at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:124)
    at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:74)
    at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
    at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
    at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:104)
    at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:62)
    at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:43)
    at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:35)
    at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
    at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:202)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:198)
    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
    at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
    at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
    at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
    at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
    at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
    at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
    at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
    at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
    at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
    at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
    at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
    at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
    at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
    at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
    at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.NullPointerException
    at org.jooq.impl.DAOImpl.records(DAOImpl.java:421)
    at org.jooq.impl.DAOImpl.insert(DAOImpl.java:176)
    at org.jooq.impl.DAOImpl.insert(DAOImpl.java:152)
    at me.leslie.generals.server.repository.ArmyRepository.updateRelation(ArmyRepository.java:75)
    ... 64 more
```

**Comment by LeslieM98** [comment]
I will fit it more to the requirements when I get the time.
I only added the classes that are relevant to the bug. Will also remove the already generated code and remove methods that are useless in this context.
https://github.com/LeslieM98/jOOQ-mcve

**Comment by lukaseder** [comment]
The thing that is `null` here is probably `Configuration`:
https://github.com/jOOQ/jOOQ/blob/version-3.12.2/jOOQ/src/main/java/org/jooq/impl/DAOImpl.java#L421

You're not setting a `Configuration` on your DAO constructor:
https://github.com/LeslieM98/Generals-Server/blob/ef5e282eb64480a02c882e6adcdafd8b11e99156/Generals-Server/src/main/java/me/leslie/generals/server/repository/ArmyRepository.java#L44

We could probably throw a more meaningful exception to help users debug this more easily: https://github.com/jOOQ/jOOQ/issues/9497

To fix this, initialise your `ArmyRepository` as follows:

```java
configuration = new DefaultConfiguration().set(SQL_DIALECT).set(database.getConnection());
jooqDao = new ArmyDao(configuration); // This fixes the issue
jooq = DSL.using(configuration); // This seems slightly cleaner, if you're reusing the configuration from above
```
