### ISSUE TITLE
Hang in jooq code generation - JavaGenerator.generate()

### ISSUE THREAD

**Issue by arrowwood49** [jOOQ/jOOQ#9500]
org.jooq.codegen.JavaGenerator.generate() hangs when running with version 3.11.12. The hang is not reproduced on every run though. There is no hang issue with previous version 3.11.11.

Thread dump using jstack shows that it is hanging while running PostgresDatabase.is11():

```
"main" #1 prio=5 os_prio=0 tid=0x00007f886c04c000 nid=0x1a7 runnable [0x00007f8874edb000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:140)
        at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:109)
        at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:67)
        at org.postgresql.core.PGStream.receiveChar(PGStream.java:306)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1952)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
        - locked <0x000000076d6efd40> (a org.postgresql.core.v3.QueryExecutorImpl)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
        at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:132)
        at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
        at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:3626)
        at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:268)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:350)
        at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:323)
        at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2700)
        at org.jooq.meta.postgres.PostgresDatabase.is11(PostgresDatabase.java:875)
        at org.jooq.meta.postgres.PostgresDatabase.getRoutines0(PostgresDatabase.java:759)
        at org.jooq.meta.AbstractDatabase.getRoutines(AbstractDatabase.java:1691)
        at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:574)
        at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:461)
        at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:382)
        at org.jooq.codegen.GenerationTool.run(GenerationTool.java:752)
        at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:222)
        at org.jooq.codegen.maven.Plugin.execute(Plugin.java:197)
        at com.gradle.maven.a.a.d.c.a(SourceFile:25)
        at com.gradle.maven.a.a.d.k.a(SourceFile:27)
        at com.gradle.maven.a.a.d.a.c(SourceFile:82)
        at com.gradle.maven.a.a.d.a.a(SourceFile:57)
        at com.gradle.maven.a.a.d.e.a(SourceFile:27)
        at com.gradle.maven.a.a.d.j.a(SourceFile:17)
        at com.gradle.maven.a.a.d.d.a(SourceFile:35)
        at com.gradle.maven.a.a.d.b.a(SourceFile:26)
        at com.gradle.maven.a.a.d.f.a(SourceFile:32)
        at com.gradle.maven.a.a.d.i.a(SourceFile:57)
        at com.gradle.maven.a.a.h.b.a(SourceFile:47)
        at com.gradle.maven.a.a.h.b$$Lambda$135/951000054.invoke(Unknown Source)
        at com.sun.proxy.$Proxy74.execute(Unknown Source)
        at com.gradle.maven.scan.extension.a.c.a.executeMojo(SourceFile:131)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
....
``` 

Postgres pg_stat_activity shows the last SQL executed on DB session:

```sql
select "pg_catalog"."pg_proc"."prokind" from "pg_catalog"."pg_proc" where 1 = 0
```

Running this SQL manually produces error on Postgers v10.7. 
```
postgres=# select "pg_catalog"."pg_proc"."prokind" from "pg_catalog"."pg_proc" where 1 = 0;
ERROR:  column pg_proc.prokind does not exist
LINE 1: select "pg_catalog"."pg_proc"."prokind" from "pg_catalog"."p...
               ^
HINT:  Perhaps you meant to reference the column "pg_proc.probin".
``` 

### Versions:

- jOOQ: 3.11.12
- Java: 8.0
- Database (include vendor):  Postgres 10.7
- OS:  Linux
- JDBC Driver (include name if inofficial driver):  Postgres jdbc driver

**Comment by lukaseder** [comment]
Thank you very much for your report. We're no longer running this particular query to check whether we're running on PostgreSQL 11+, starting with jOOQ 3.12.0: https://github.com/jOOQ/jOOQ/issues/8972

I don't see how this query could cause your JDBC connection to hang, though. This does not look like something we could prevent. Perhaps there's some uncommitted transaction which blocks the code generator?

I'll be happy to look into this a bit further if you can provide instructions on how to reproduce this...

**Comment by arrowwood49** [comment]
Thanks @lukaseder for the quick response. It doesn't looks like this is related to connection hang. In another run, Postgres 'pg_stat_activity' showed different SQL as the last executed query and it is waiting for client to read the response with wait_event as 'ClientRead'.

`select state,wait_event, usename, query from pg_stat_activity ;
state  |     wait_event      | usename  |                              query                              
--------+---------------------+--------------------------------------------------------------
 idle   | ClientRead          | postgres | select array[1, 2] && array[2, 3]
`

The hang issue happens only when running the generator through maven-plugin. I couldn't reproduce the issue when running JavaGenerator in a standalone  java application.

**Comment by lukaseder** [comment]
I will close this issue as "works for me" as I cannot reproduce such a problem, and I haven't heard from anyone else yet that has a similar issue on PostgreSQL.

Please let us know if we can be of any further assistance in this matter.

**Comment by dano** [comment]
We are hitting this issue intermittently as well on Postgres, also using version 3.11.12.

We see the exact same stack trace:
```
"main" #1 prio=5 os_prio=0 tid=0x00007f8e6404c000 nid=0x1ad runnable [0x00007f8e6c5b7000]
   java.lang.Thread.State: RUNNABLE
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
    at java.net.SocketInputStream.read(SocketInputStream.java:171)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:140)
    at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:109)
    at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:67)
    at org.postgresql.core.PGStream.receiveChar(PGStream.java:306)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1952)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
    - locked <0x000000076f703f30> (a org.postgresql.core.v3.QueryExecutorImpl)
    at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
    at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
    at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:132)
    at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
    at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:3626)
    at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:268)
    at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:350)
    at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:323)
    at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2700)
    at org.jooq.meta.postgres.PostgresDatabase.is11(PostgresDatabase.java:875)
    at org.jooq.meta.postgres.PostgresDatabase.getRoutines0(PostgresDatabase.java:759)
    at org.jooq.meta.AbstractDatabase.getRoutines(AbstractDatabase.java:1691)
    at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:574)
    at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:461)
    at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:382)
    at org.jooq.codegen.GenerationTool.run(GenerationTool.java:752)
    at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:222)
    at org.jooq.codegen.maven.Plugin.execute(Plugin.java:197)
    at com.gradle.maven.a.a.d.c.a(SourceFile:25)
    at com.gradle.maven.a.a.d.k.a(SourceFile:27)
    at com.gradle.maven.a.a.d.a.c(SourceFile:82)
    at com.gradle.maven.a.a.d.a.a(SourceFile:57)
    at com.gradle.maven.a.a.d.e.a(SourceFile:27)
    at com.gradle.maven.a.a.d.j.a(SourceFile:17)
    at com.gradle.maven.a.a.d.d.a(SourceFile:35)
    at com.gradle.maven.a.a.d.b.a(SourceFile:26)
    at com.gradle.maven.a.a.d.f.a(SourceFile:32)
    at com.gradle.maven.a.a.d.i.a(SourceFile:57)
    at com.gradle.maven.a.a.h.b.a(SourceFile:47)
    at com.gradle.maven.a.a.h.b$$Lambda$141/1886301021.invoke(Unknown Source)
    at com.sun.proxy.$Proxy74.execute(Unknown Source)
    at com.gradle.maven.scan.extension.a.c.a.executeMojo(SourceFile:131)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```
This is in an organization with a few hundred people, and probably a few dozen people have reported intermittently hitting it. Likely more are and are just not complaining about it.

Unfortunately I'm not sure how to reproduce it reliably - I have left a build running in a loop over night, and never hit the hang. But there was a time a few weeks earlier where I was hitting it every 3 or 4 build attempts. Other people have complained about hitting it over and over and being unable to get a build that doesn't hang without restarting a bunch of services, or rebooting their system.

It looks like version 3.12.0 removes this call altogether, so maybe upgrading is our best option?

**Comment by dano** [comment]
The last executed query I see in pg_stat_activity is also the same one that the OP reported:
```
 12994 | postgres |  88 |       10 | postgres | PostgreSQL JDBC Driver | <snip>  |                 |       4169
2 | 2019-11-19 20:03:38.879344+00 |                               | 2019-11-19 20:03:40.511273+00 | 2019-11-19 20:0
3:40.511585+00 | Client          | ClientRead          | idle   |             |              | select "pg_catalog".
"pg_proc"."prokind" from "pg_catalog"."pg_proc" where 1 = 0 | client backend
```

Our build process spins up a  postgres docker container, uses Flyway to build our DB schema in that postgres instance, and then runs jOOQ code generation on the schema. There are no other clients running queries against the DB.

**Comment by dano** [comment]
Interestingly, someone else hit this yesterday, and they got a slightly different stack trace, and different last query in pg_stat_activity. It actually matches the second query that @arrowwood49 shared.

```
"main" #1 prio=5 os_prio=0 tid=0x00007f78fc04c000 nid=0x19e runnable [0x00007f7904fed000]
   java.lang.Thread.State: RUNNABLE
                at java.net.SocketInputStream.socketRead0(Native Method)
                at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
                at java.net.SocketInputStream.read(SocketInputStream.java:171)
                at java.net.SocketInputStream.read(SocketInputStream.java:141)
                at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:140)
                at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:109)
                at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:67)
                at org.postgresql.core.PGStream.receiveChar(PGStream.java:306)
                at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1952)
                at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
                - locked <0x0000000782d57928> (a org.postgresql.core.v3.QueryExecutorImpl)
                at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
                at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
                at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
                at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:132)
                at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
                at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:3626)
                at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:268)
                at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:350)
                at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:323)
                at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2700)
                at org.jooq.meta.postgres.PostgresDatabase.canCombineArrays(PostgresDatabase.java:893)
                at org.jooq.meta.postgres.PostgresDatabase.getRoutines0(PostgresDatabase.java:770)
                at org.jooq.meta.AbstractDatabase.getRoutines(AbstractDatabase.java:1691)
                at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:574)
                at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:461)
                at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:382)
                at org.jooq.codegen.GenerationTool.run(GenerationTool.java:752)
                at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:222)
                at org.jooq.codegen.maven.Plugin.execute(Plugin.java:197)
                at com.gradle.maven.a.a.d.c.a(SourceFile:25)
                at com.gradle.maven.a.a.d.k.a(SourceFile:27)
                at com.gradle.maven.a.a.d.a.c(SourceFile:82)
                at com.gradle.maven.a.a.d.a.a(SourceFile:57)
                at com.gradle.maven.a.a.d.e.a(SourceFile:27)
                at com.gradle.maven.a.a.d.j.a(SourceFile:17)
                at com.gradle.maven.a.a.d.d.a(SourceFile:35)
                at com.gradle.maven.a.a.d.b.a(SourceFile:26)
                at com.gradle.maven.a.a.d.f.a(SourceFile:32)
                at com.gradle.maven.a.a.d.i.a(SourceFile:57)
                at com.gradle.maven.a.a.h.b.a(SourceFile:47)
                at com.gradle.maven.a.a.h.b$$Lambda$135/1605128733.invoke(Unknown Source)
                at com.sun.proxy.$Proxy75.execute(Unknown Source)
                at com.gradle.maven.scan.extension.a.c.a.executeMojo(SourceFile:131)
                at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
                at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
                at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
                at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
                at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
                at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
                at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
                at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
                at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
                at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
                at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
                at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
                at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
                at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
                at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
                at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

And the last query:
`select array[1, 2] && array[2, 3] 
`

**Comment by Gama11** [comment]
I think I've also just run into this issue, and it happens consistently at the moment. The last query according to `pg_stat_activity` is `select (1, 2) not in (select 1, 2)`. This is with jooq 3.15.1, PostgreSQL 13.3 and 42.2.23 of the JDBC driver.

The stacktrace matches the one from @dano:

```
"ai.vier.cvg.jooq.GeneratorKt.main()@3037" prio=5 tid=0x13 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at sun.nio.ch.SocketDispatcher.read0(SocketDispatcher.java:-1)
	  at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:47)
	  at sun.nio.ch.NioSocketImpl.tryRead(NioSocketImpl.java:261)
	  at sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:312)
	  at sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
	  at sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
	  at java.net.Socket$SocketInputStream.read(Socket.java:976)
	  at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:161)
	  at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:128)
	  at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:113)
	  at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:73)
	  at org.postgresql.core.PGStream.receiveChar(PGStream.java:443)
	  at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2056)
	  at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)
	  - locked <0x14ff> (a org.postgresql.core.v3.QueryExecutorImpl)
	  at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
	  at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
	  at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	  at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:153)
	  at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	  at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4131)
	  at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:230)
	  at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:335)
	  at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:284)
	  at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2842)
	  at org.jooq.meta.postgres.PostgresDatabase.getTables0(PostgresDatabase.java:560)
	  at org.jooq.meta.AbstractDatabase.lambda$getTables$11(AbstractDatabase.java:1770)
	  at org.jooq.meta.AbstractDatabase$$Lambda$185/0x000000080104ae40.run(Unknown Source:-1)
	  at org.jooq.meta.AbstractDatabase.onError(AbstractDatabase.java:3269)
	  at org.jooq.meta.AbstractDatabase.getTables(AbstractDatabase.java:1769)
	  at org.jooq.meta.AbstractDatabase.getEmbeddables0(AbstractDatabase.java:2043)
	  at org.jooq.meta.AbstractDatabase.lambda$getEmbeddables$13(AbstractDatabase.java:2002)
	  at org.jooq.meta.AbstractDatabase$$Lambda$184/0x000000080104ac18.run(Unknown Source:-1)
	  at org.jooq.meta.AbstractDatabase.onError(AbstractDatabase.java:3269)
	  at org.jooq.meta.AbstractDatabase.getEmbeddables(AbstractDatabase.java:2001)
	  at org.jooq.meta.AbstractDatabase.getEmbeddables(AbstractDatabase.java:2021)
	  at org.jooq.codegen.JavaGenerator.generateSchemaIfEmpty(JavaGenerator.java:526)
	  at org.jooq.codegen.JavaGenerator$$Lambda$149/0x0000000800fce690.test(Unknown Source:-1)
	  at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	  at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	  at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	  at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	  at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	  at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	  at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	  at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	  at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	  at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
	  at org.jooq.codegen.JavaGenerator.generateCatalogIfEmpty(JavaGenerator.java:519)
	  at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:481)
	  at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:873)
	  at org.jooq.codegen.GenerationTool.run(GenerationTool.java:233)
	  at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:228)
	  at ai.vier.cvg.jooq.GeneratorKt.main(Generator.kt:430)
	  at java.lang.invoke.LambdaForm$DMH/0x0000000800d9cc00.invokeStaticInit(LambdaForm$DMH:-1)
	  at java.lang.invoke.DelegatingMethodHandle$Holder.delegate(DelegatingMethodHandle$Holder:-1)
	  at java.lang.invoke.LambdaForm$MH/0x0000000800d9d000.invoke_MT(LambdaForm$MH:-1)
	  at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
	  at java.lang.Thread.run(Thread.java:831)
```

**Comment by Gama11** [comment]
This pgjdbc issue might be related: https://github.com/pgjdbc/pgjdbc/issues/1508

**Comment by dano** [comment]
FWIW, we ended up fixing this by upgrading our version of `io.fabric8.docker-maven-plugin` from 0.28.0 to 0.33.0. We are using that plugin to spin up the postgres instance we run the jooq code generation against, and execute Flyway migrations to build the DB schema. We have no idea what changed between the versions that fixed the issue, but it went away once we upgraded.

**Comment by lukaseder** [comment]
Thanks a lot for documenting the issues you've encountered, @Gama11 and @dano
