### ISSUE TITLE
NullPointerException in DefaultRecordMapperProvider when setting a new instance to a Configuration

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9621]
When using the following kind of `Configuration`:

```java
DSL.using(new DefaultConfiguration().set(new DefaultRecordMapperProvider()));
```

A `NullPointerException` may occur when calling `Result.into(Class)`:

```
java.lang.NullPointerException
    at org.jooq.impl.DefaultRecordMapperProvider.provide(DefaultRecordMapperProvider.java:83)
    at org.jooq.impl.ResultImpl.into(ResultImpl.java:1369)
```

See also:
https://stackoverflow.com/q/59163939/521799

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.13.0. Backport scheduled for 3.12.4 (#9622)
