### ISSUE TITLE
Mapping a JSONB-column to a list of POJOs using custom binding fails at runtime

### ISSUE THREAD

**Issue by jklingsporn** [jOOQ/jOOQ#9679]
### Expected behavior and actual behavior:
Prior to 3.12.3 (3.11.12) I was able to map a postgres JSONB-column containing a JSON-Array to a list of pojos using the following binding utilizing Jackson-mapper (note: the binding was updated to work with 3.12 to respect JSONB data type):
```
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.type.CollectionType;
import io.netty.buffer.ByteBufInputStream;
import io.vertx.core.buffer.Buffer;
import io.vertx.core.json.DecodeException;
import io.vertx.core.json.Json;
import org.jooq.*;
import org.jooq.impl.DSL;

import java.io.IOException;
import java.io.InputStream;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.type.CollectionType;
import org.jooq.*;
import org.jooq.exception.DataTypeException;
import org.jooq.impl.DSL;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

abstract class PojoListToJsonArrayBinding<O> implements Binding<JSONB, List<O>> {

    private final Class<O> destinationClass;

    private final Converter<JSONB, List<O>> converter = new Converter<JSONB, List<O>>() {
        @Override
        @SuppressWarnings("unchecked")
        public List<O> from(JSONB t) {
            if(t == null || t.data() == null){
                return null;
            }
            CollectionType collectionType = new ObjectMapper().getTypeFactory().constructCollectionType(ArrayList.class, destinationClass);
            try {
                return new ObjectMapper().readValue(new ByteArrayInputStream(t.toString().getBytes()), collectionType);
            } catch (IOException e) {
                throw new DataTypeException(e.getMessage(),e);
            }
        }

        @Override
        public JSONB to(List<O> u) {
            try {
                return u == null ? JSONB.valueOf(null) : JSONB.valueOf(new ObjectMapper().writeValueAsString(u));
            } catch (JsonProcessingException e) {
                throw new DataTypeException(e.getMessage(),e);
            }
        }

        @Override
        public Class<JSONB> fromType() {
            return JSONB.class;
        }

        @Override
        @SuppressWarnings("unchecked")
        public Class<List<O>> toType() {
            return (Class<List<O>>) destinationClass;
        }
    };

    protected PojoListToJsonArrayBinding(Class<O> destinationClass) {
        this.destinationClass = destinationClass;
    }

    // The converter does all the work
    @Override
    public Converter<JSONB, List<O>> converter() {
        return converter;
    }

    // Rending a bind variable for the binding context's value and casting it to the json type
    @Override
    public void sql(BindingSQLContext<List<O>> ctx) throws SQLException {
        // Depending on how you generate your SQL, you may need to explicitly distinguish
        // between jOOQ generating bind variables or inlined literals. If so, use this check:
        // ctx.render().paramType() == INLINED
        ctx.render().visit(DSL.val(ctx.convert(converter()).value())).sql("::jsonb");
    }

    // Registering VARCHAR types for JDBC CallableStatement OUT parameters
    @Override
    public void register(BindingRegisterContext<List<O>> ctx) throws SQLException {
        ctx.statement().registerOutParameter(ctx.index(), Types.VARCHAR);
    }

    // Converting the O to a String value and setting that on a JDBC PreparedStatement
    @Override
    public void set(BindingSetStatementContext<List<O>> ctx) throws SQLException {
        ctx.statement().setString(ctx.index(), Objects.toString(ctx.convert(converter()).value(), null));
    }

    // Getting a String value from a JDBC ResultSet and converting that to a O
    @Override
    public void get(BindingGetResultSetContext<List<O>> ctx) throws SQLException {
        ctx.convert(converter()).value(JSONB.valueOf(ctx.resultSet().getString(ctx.index())));
    }

    // Getting a String value from a JDBC CallableStatement and converting that to a O
    @Override
    public void get(BindingGetStatementContext<List<O>> ctx) throws SQLException {
        ctx.convert(converter()).value(JSONB.valueOf(ctx.statement().getString(ctx.index())));
    }

    // Setting a value on a JDBC SQLOutput (useful for Oracle JSONB types)
    @Override
    public void set(BindingSetSQLOutputContext<List<O>> ctx) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    // Getting a value from a JDBC SQLInput (useful for Oracle JSONB types)
    @Override
    public void get(BindingGetSQLInputContext<List<O>> ctx) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }
}

```
An actual implementation of that class is this:
```
public class MyPojoBinding extends PojoListToJsonArrayBinding<MyPojo>{

    public MatchInstanceDataBinding() {
        super(MyPojo.class);
    }
}
```
I've configured the mapper in the pom like so:
```
<forcedType>                                

<userType>java.util.List&#60;com.acme.MyPojo&#62;</userType>                             

<binding>com.acme.MyPojoBinding</binding>  

<includeExpression>my_pojo_column</includeExpression>                                      

<includeTypes>JSONB</includeTypes>
</forcedType>
```
The code generator correctly generates the field as an `List<com.acme.MyPojo>` however when performing the actual conversion fails with this stack trace:
```
Caused by: org.jooq.exception.DataTypeException: Cannot convert from com.acme.MyPojoListContainer (class com.acme.MyPojo) to class org.jooq.JSONB
	at org.jooq.tools.Convert$ConvertAll.fail(Convert.java:1194)
	at org.jooq.tools.Convert$ConvertAll.from(Convert.java:1083)
	at org.jooq.tools.Convert.convert0(Convert.java:324)
	at org.jooq.tools.Convert.convert(Convert.java:316)
	at org.jooq.tools.Convert.convert(Convert.java:387)
	at org.jooq.tools.Convert.convertArray(Convert.java:295)
	at org.jooq.tools.Convert.convertArray(Convert.java:277)
	at org.jooq.tools.Convert$ConvertAll.from(Convert.java:543)
	at org.jooq.tools.Convert.convert0(Convert.java:324)
	at org.jooq.tools.Convert.convert(Convert.java:316)
	at org.jooq.tools.Convert.convert(Convert.java:387)
	at org.jooq.impl.DefaultDataType.convert(DefaultDataType.java:825)
	at org.jooq.impl.ConvertedDataType.convert(ConvertedDataType.java:114)
	at org.jooq.impl.Tools.setValue(Tools.java:2787)
	at org.jooq.impl.DefaultRecordUnmapper.setValue(DefaultRecordUnmapper.java:141)
	at org.jooq.impl.DefaultRecordUnmapper.access$900(DefaultRecordUnmapper.java:72)
	at org.jooq.impl.DefaultRecordUnmapper$PojoUnmapper.unmap(DefaultRecordUnmapper.java:261)```

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):
Configure a code generator like above and try loading or writing data.

### Versions:

- jOOQ: 3.12.
- Java: 1.8.131
- Database (include vendor): postgres 10.5
- OS: MacOs 10.13.6
- JDBC Driver (include name if inofficial driver): 42.2.2

**Comment by lukaseder** [comment]
Thank you very much for your report. 

To be able to reproduce it on our side, an MCVE would really be helpful. I'm *guessing* that you have array types somewhere, but I don't know this. If an MCVE is not possible, could you please add these things to your report:

- The DDL of your table
- Your client code that produces this stack trace?

**Comment by jklingsporn** [comment]
Here you go: https://github.com/jklingsporn/jOOQ-mcve

**Comment by knutwannheden** [comment]
Thank you very much for the MCVE.

I analyzed this and found the problem to be related to the `toType()` implementation of your Converter: https://github.com/jklingsporn/jOOQ-mcve/blob/ed07da4938346739b9a41e689651d8c24717cf29/src/main/java/binding/PojoListToJsonArrayBinding.java#L54-L56.

The method here is expected to be returning a type compatible with `List<MyPojo>` and currently it returns `MyPojo`. As a result `ConvertedDataType#convert()` won't work as expected: https://github.com/jOOQ/jOOQ/blob/680cd20d0829f1ec3bb345d3e70e4e1eb3d31705/jOOQ/src/main/java/org/jooq/impl/ConvertedDataType.java#L109-L110.

I think you should be able to change the implementation of `toType()` to something like this:
```java
return (Class<List<O>>) (Class<?>) List.class;
```

If this code worked before, I think this is more by accident. Please reopen if I missed something.

**Comment by jklingsporn** [comment]
Wow, that's embarrassing. Thanks for fixing my code. 
Afaik this binding worked in 3.11.x though...
