### ISSUE TITLE
MariaDB regression in ParsingConnection

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9795]
The following test now fails in MariaDB:

```java
public void testTranslateSQLExecuteJDBCDirectly() throws Exception {
    String sql = "SELECT first_name || ' ' || last_name FROM t_author ORDER BY id ASC";

    try (Connection c = create(settings()).parsingConnection();
         Statement s1 = c.createStatement();
         ResultSet rs1 = s1.executeQuery(sql);
         PreparedStatement s2 = c.prepareStatement(sql);
         ResultSet rs2 = s2.executeQuery()) {

        Result<Record> r1 = create().fetch(rs1);
        Result<Record> r2 = create().fetch(rs2);

        assertEquals(
            asList("George Orwell", "Paulo Coelho"),
            r1.getValues(0));
        assertEquals(
            asList("George Orwell", "Paulo Coelho"),
            r2.getValues(0));
    }
}
```

The error message is:

```
java.sql.SQLSyntaxErrorException: (conn=9) Table 'test.T_AUTHOR' doesn't exist
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:242)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:171)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:327)
	at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:501)
	at org.jooq.tools.jdbc.DefaultStatement.executeQuery(DefaultStatement.java:117)
	at org.jooq.impl.ParsingStatement.executeQuery(ParsingStatement.java:62)
	at org.jooq.test.all.testcases.ParserTests.testTranslateSQLExecuteJDBCDirectly(ParserTests.java:103)
	at org.jooq.test.jOOQAbstractTest.testTranslateSQLExecuteJDBCDirectly(jOOQAbstractTest.java:5563)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:30)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.sql.SQLException: Table 'test.T_AUTHOR' doesn't exist
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1594)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1453)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1415)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:227)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:321)
	... 38 more
```

This is probably because of #9238 and the new `Settings.parseNameCase`, which transforms identifiers to upper case by default, in MariaDB (and MySQL). See remark in issue there, which says that the actual table name depends on the `lower_case_table_names` setting.

Perhaps, we should mimick that setting in jOOQ. The default behaviour is correct, but our integration tests seem not to set this setting to a "more reasonable" value.

**Comment by lukaseder** [comment]
This regression does not affect jOOQ 3.12 or prior releases.

**Comment by lukaseder** [comment]
In test containers, we can override this flag using:

```java
    public static MariaDBContainerExtension db = new MariaDBContainerExtension("mariadb:10.4")
        .withCommand("mysqld", "--lower_case_table_names=1");
```

So, this currently turns into a feature request, rather than a "bug" (the `Settings.renderNameCase` flag can be set to `AS_IS` to prevent any transformation)
