### ISSUE TITLE
Exception while executing meta query: ERROR: column pg_proc.proisagg does not exist

### ISSUE THREAD

**Issue by Akshaymisal5** [jOOQ/jOOQ#9828]
Postgres: 12
jooq-codegen-maven: 3.10.3
jooq-meta:  3.10.3
postgresql: 42.1.4

SQL exception: Exception while executing meta query: ERROR: column pg_proc.proisagg does not exist
  Hint: Perhaps you meant to reference the column "pg_proc.prolang".

```sql
select 
  "r1"."routine_schema", 
  "r1"."routine_name", 
  "r1"."specific_name", 
  case
    when ("pg_catalog"."pg_proc"."proargmodes" && ARRAY['o','b']::"char"[]) then 'void'
    else "r1"."data_type"
  end as "data_type", 
  "r1"."character_maximum_length", 
  "r1"."numeric_precision", 
  "r1"."numeric_scale", 
  "r1"."type_udt_schema", 
  "r1"."type_udt_name", 
  case
    when count(*) over (partition by 
      "r1"."routine_schema", 
      "r1"."routine_name"
    ) > 1 then row_number() over (partition by 
      "r1"."routine_schema", 
      "r1"."routine_name"
     order by "r1"."specific_name")
  end as "overload", 
  "pg_catalog"."pg_proc"."proisagg"
from "information_schema"."routines" as "r1"
  join "pg_catalog"."pg_namespace"
  on "pg_catalog"."pg_namespace"."nspname" = "r1"."specific_schema"
  join "pg_catalog"."pg_proc"
  on (
    "pg_catalog"."pg_proc"."pronamespace" = "pg_catalog"."pg_namespace".oid
    and (("pg_catalog"."pg_proc"."proname" || '_') || cast("pg_catalog"."pg_proc".oid as varchar)) = "r1"."specific_name"
  )
where (
  "r1"."routine_schema" in ( <schema_names_here>
  )
  and not("pg_catalog"."pg_proc"."proretset")
)
order by 
  "r1"."routine_schema" asc, 
  "r1"."routine_name" asc, 
  "overload" asc
```

[ERROR] Error while fetching functions
org.jooq.exception.DataAccessException: SQL [select "r1"."routine_schema", "r1"."routine_name", "r1"."specific_name", case when ("pg_catalog"."pg_proc"."proargmodes" && ARRAY['o','b']::"char"[]) then 'void' else "r1"."data_type" end as "data_type", "r1"."character_maximum_length", "r1"."numeric_precision", "r1"."numeric_scale", "r1"."type_udt_schema", "r1"."type_udt_name", case when count(*) over (partition by "r1"."routine_schema", "r1"."routine_name") > 1 then row_number() over (partition by "r1"."routine_schema", "r1"."routine_name" order by "r1"."specific_name") end as "overload", "pg_catalog"."pg_proc"."proisagg" from "information_schema"."routines" as "r1" join "pg_catalog"."pg_namespace" on "pg_catalog"."pg_namespace"."nspname" = "r1"."specific_schema" join "pg_catalog"."pg_proc" on ("pg_catalog"."pg_proc"."pronamespace" = "pg_catalog"."pg_namespace".oid and (("pg_catalog"."pg_proc"."proname" || ?) || cast("pg_catalog"."pg_proc".oid as varchar)) = "r1"."specific_name") where ("r1"."routine_schema" in (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) and not("pg_catalog"."pg_proc"."proretset")) order by "r1"."routine_schema" asc, "r1"."routine_name" asc, "overload" asc]; ERROR: column pg_proc.proisagg does not exist
  Hint: Perhaps you meant to reference the column "pg_proc.prolang".
  Position: 548
	at org.jooq_3.10.3.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2197)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:704)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:361)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:317)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2597)
	at org.jooq.util.postgres.PostgresDatabase.getRoutines0(PostgresDatabase.java:775)
	at org.jooq.util.AbstractDatabase.getRoutines(AbstractDatabase.java:1787)
	at org.jooq.util.JavaGenerator.generateSchemaIfEmpty(JavaGenerator.java:365)
	at org.jooq.util.JavaGenerator.generateCatalogIfEmpty(JavaGenerator.java:352)
	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:326)
	at org.jooq.util.GenerationTool.run(GenerationTool.java:642)
	at org.jooq.util.GenerationTool.generate(GenerationTool.java:203)
	at org.jooq.util.maven.Plugin.execute(Plugin.java:192)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.postgresql.util.PSQLException: ERROR: column pg_proc.proisagg does not exist
  Hint: Perhaps you meant to reference the column "pg_proc.prolang".
  Position: 548
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:158)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:3209)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:262)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:347)
	... 32 more

**Comment by lukaseder** [comment]
Thanks for your report. This has been fixed already: https://github.com/jOOQ/jOOQ/issues/7785

... and reported a few times :)
https://github.com/jOOQ/jOOQ/search?q=proisagg&state=closed&type=Issues

Please upgrade jOOQ.
