### ISSUE TITLE
How to translate lock dialect SQL?

### ISSUE THREAD

**Issue by luhui0928** [jOOQ/jOOQ#9880]
I want to translate lock dialect SQL。
For example:
MSSQL: select * from user with(ROWLOCK,UpdLock,nowait)
I'm trying to convert to oracle dialect,but is not support.
I expect result such as:  select * from user for update

Excuse me, is there any way to support?

**Comment by lukaseder** [comment]
Thank you very much for your request. This is currently not possible, I'm afraid.

A similar translation idea in the opposite direction is this: https://github.com/jOOQ/jOOQ/issues/8844

We should definitely consider this. Especially when there is only one table involved, the translation might be straightforward.

**Comment by lukaseder** [comment]
By now (jOOQ 3.18.0), we have enough infrastructure to execute such transformations reliably. However, there are a lot of questions here:

- What to do with conflicts? In T-SQL, it is (theoretically) possible to have conflicting locks (e.g. mix `WAIT` and `NOWAIT` semantics). Can we merge those? In my opinion, any `NOWAIT` is sufficient to produce `NOWAIT` also in standard SQL.
- What are the exact equivalences between T-SQL and standard SQL? You explicitly listed `ROWLOCK, UPDLOCK`, which seems to be what the manual claims: https://learn.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql-table?view=sql-server-ver16. I'll assume that exactly these two hints are required for `FOR UPDATE` to apply
- Can we apply an equivalent table scope? In T-SQL, locking is always table-based. In standard SQL, it is row based (`FOR UPDATE`, widely supported), and optionally table based (`FOR UPDATE OF`, occasionally supported). If we cannot implement the exact lock scope (because `OF` isn't supported), then we'll have to lock the the entire joined row.
  - A special case is a single table query, in case of which we can omit the `OF` clause.

**Comment by lukaseder** [comment]
One would be tempted to refactor the  `QOM.WithTable`, which currently contains arbitrary `org.jooq.SQL` in order to formally recognise these hints? The transformation can also be implemented by parsing (or even via regex) the SQL template...

**Comment by lukaseder** [comment]
The current implementation doesn't get scoping right yet. For example:

```java
assertFormattingEquals(
    "select * from t1, (select * from t1) as t2, t3 for update of t1, t3",
    """
    select *
    from
      t1,
      (
        select *
        from t1
      ) as t2,
      t3
    for update of t1, t3
    """.trim(),
    select().from(t1.with("rowlock, updlock"), select().from(t1).asTable(t2), t3.with("updlock, rowlock"))
);
```

This fails with:

```
org.junit.ComparisonFailure: Unformatted comparison expected:<...1, (select * from t1[]) as t2, t3 for upda...> but was:<...1, (select * from t1[ for update of t1]) as t2, t3 for upda...>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.jooq.test.AbstractTest.assertEquals(AbstractTest.java:202)
	at org.jooq.test.formatting.AbstractFormattingTest.assertFormattingEquals(AbstractFormattingTest.java:193)
	at org.jooq.test.formatting.FormattingTest.testSelectForUpdateWithTable(FormattingTest.java:1521)
```

In other words, this query is being generated:

```sql
select *
from
  t1,
  (
    select *
    from t1
    for update of t1 -- Erroneously matched
  ) as t2,
  t3
for update of t1, t3
```

On every scope level, the `WithTable.ScopeWithTableForUpdate` has to be reset.

**Comment by lukaseder** [comment]
Looks like the `DataKey::resetInSubqueryScope` flag wasn't set
