### ISSUE TITLE
DSLContext.nextval(Sequence) doesn't work with Postgres

### ISSUE THREAD

**Issue by mmatela** [jOOQ/jOOQ#9901]
Hello,
We have a sequence and try to get its next value like this:
`Long nextval = dsl.nextval(Sequences.TEST_SEQ);`
This works for example with H2, but not with Postgres, event though the method is annotated with `@Support(POSTGRES)`.

Exception:

	org.jooq.exception.DataAccessException: SQL [select public.test_seq.nextval]; ERROR: missing FROM-clause entry for table "test_seq"
	  Position: 8
		at org.jooq_3.13.1.DEFAULT.debug(Unknown Source) ~[na:na]
		at org.jooq.impl.Tools.translate(Tools.java:2751) ~[jooq-3.13.1.jar:na]
		at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:755) ~[jooq-3.13.1.jar:na]
		at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:385) ~[jooq-3.13.1.jar:na]
		at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:502) ~[jooq-3.13.1.jar:na]
		at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:471) ~[jooq-3.13.1.jar:na]
		at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:485) ~[jooq-3.13.1.jar:na]
		at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:654) ~[jooq-3.13.1.jar:na]
		at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:590) ~[jooq-3.13.1.jar:na]
		at org.jooq.impl.SelectImpl.fetchOne(SelectImpl.java:2824) ~[jooq-3.13.1.jar:na]
		at org.jooq.impl.DefaultDSLContext.nextval(DefaultDSLContext.java:3855) ~[jooq-3.13.1.jar:na]
		...

It seems that JOOQ should generate a query like `select nextval('test_seq')` instead.

As a workaround we redefined our columns to have default values so we don't need to retrieve sequence values directly.

**Comment by lukaseder** [comment]
Thank you very much for your message.

I'm really glad I had once created that synthetic stack trace element that contains the `SQLDialect` and the jOOQ version, because it contains the answer to your question :)

```
	at org.jooq_3.13.1.DEFAULT.debug(Unknown Source) ~[na:na]
```

You're using `SQLDialect.DEFAULT`, not `SQLDialect.POSTGRES`

I hope this helps.
