### ISSUE TITLE
SQL 无法识别

### ISSUE THREAD

**Issue by LeoHong123456** [jOOQ/jOOQ#9915]
```java
create.select(
	tableYBuser.SITE_ID,
	tableYBuser.USERNAME,
	tableYBuser.YUE,
	tableYBuser.INTEREST,
	tableYBuser.YUE_PREV_CACHE,
	tableYBuser.YUE_NEXT_CACHE,
	tableYBuser.DEMARCATE_DATE,
	tableYBuser.VERSION,
	tableYBuser.AUTHENT,
	tableYBuser.HISTORY_TOTAL_INTEREST,
	DSL.sum(tableTransfer.AFTER_YUE.mul(tableTransfer.RATE)).as("ayerRevenue")
	)
.from(tableYBuser).innerJoin(tableTransfer)
.on(tableYBuser.USERNAME.eq(tableTransfer.USERNAME).and(tableYBuser.SITE_ID.eq(tableTransfer.SITE_ID)))
.where(tableYBuser.USERNAME.eq(username).and(tableYBuser.SITE_ID.eq(siteId)))
.and(DSL.field("DATE_FORMAT("+tableTransfer.CREATE_TIME+",'%Y-%m-%d')")
		.eq(DSL.field("DATE_SUB(STR_TO_DATE(NOW(),'%Y-%m-%d'),INTERVAL 1 DAY)")));
where.groupBy(tableTransfer.CREATE_TIME);
where.orderBy(tableTransfer.ID.desc());
user = where.fetchInto(DsYuebaoUserDetailVO.class).get(0);
```

error info:

```
org.jooq.exception.DataAccessException: SQL [select `yuebao_center`.`ds_yuebao_user`.`site_id`, `yuebao_center`.`ds_yuebao_user`.`username`, `yuebao_center`.`ds_yuebao_user`.`yue`, `yuebao_center`.`ds_yuebao_user`.`interest`, `yuebao_center`.`ds_yuebao_user`.`yue_prev_cache`, `yuebao_center`.`ds_yuebao_user`.`yue_next_cache`, `yuebao_center`.`ds_yuebao_user`.`demarcate_date`, `yuebao_center`.`ds_yuebao_user`.`version`, `yuebao_center`.`ds_yuebao_user`.`authent`, `yuebao_center`.`ds_yuebao_user`.`history_total_interest`, sum((`yuebao_center`.`ds_yuebao_transfer_log`.`after_yue` * `yuebao_center`.`ds_yuebao_transfer_log`.`rate`)) as `ayerRevenue` from `yuebao_center`.`ds_yuebao_user` join `yuebao_center`.`ds_yuebao_transfer_log` on (`yuebao_center`.`ds_yuebao_user`.`username` = `yuebao_center`.`ds_yuebao_transfer_log`.`username` and `yuebao_center`.`ds_yuebao_user`.`site_id` = `yuebao_center`.`ds_yuebao_transfer_log`.`site_id`) where (`yuebao_center`.`ds_yuebao_user`.`username` = ? and `yuebao_center`.`ds_yuebao_user`.`site_id` = ? and DATE_FORMAT("yuebao_center"."ds_yuebao_transfer_log"."create_time",'%Y-%m-%d') = DATE_SUB(STR_TO_DATE(NOW(),'%Y-%m-%d'),INTERVAL 1 DAY)) group by `yuebao_center`.`ds_yuebao_transfer_log`.`create_time` order by `yuebao_center`.`ds_yuebao_transfer_log`.`id` desc]; You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '."ds_yuebao_transfer_log"."create_time",'%Y-%m-%d') = DATE_SUB(STR_TO_DATE(NOW()' at line 1
	at org.jooq_3.12.3.MYSQL.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2717)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:755)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:382)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:353)
	at org.jooq.impl.AbstractResultQuery.fetchInto(AbstractResultQuery.java:1549)
	at org.jooq.impl.SelectImpl.fetchInto(SelectImpl.java:3749)
```

**Comment by lukaseder** [comment]
Thank you very much for your message. You should never need to use string concatenation with jOOQ, for at least 3 reasons:

1. SQL injection
2. Syntax correctness
3. By embedding jOOQ `QueryPart` objects using `QueryPart.toString()`, you effectively prevent jOOQ from rendering vendor-specific SQL for that particular `QueryPart`

Regarding the 3rd bullet, here's the problem:

```java
DSL.field("DATE_FORMAT("+tableTransfer.CREATE_TIME+",'%Y-%m-%d')")
```

This calls `tableTransfer.CREATE_TIME.toString()`, which produces a vendor-agnostic SQL string fragment that might not work on MySQL (notice the names are `"double quoted"` rather than `` `backtick quoted` ``). Better use plain SQL templating instead:
https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating

```java
DSL.field("DATE_FORMAT({0}, '%Y-%m-%d')", tableTransfer.CREATE_TIME)
```
