### ISSUE TITLE
JdbcSQLSyntaxErrorException for nested select case

### ISSUE THREAD

**Issue by bzhou003** [jOOQ/jOOQ#9962]
### Expected behavior and actual behavior:

Here is the table I create: 
> CREATE TABLE `payment` (
    `id` BIGINT(20) auto_increment PRIMARY KEY,
    `user_id` BIGINT(20) NOT NULL,
    `interacting_user_id` BIGINT(20) NOT NULL,
    `mutual_interactions` BIGINT(20) NOT NULL,
    `date_modified` TIMESTAMP NOT NULL,
    `audience_visibility` TINYINT(3)  DEFAULT '0'
);

This is the query I user:
> SELECT COUNT(interacting_user_id)
> FROM (
>   SELECT interacting_user_id, SUM(mutual_interactions) AS interactions_per_user 
>   FROM payment 
>   WHERE user_id = $user_id
>   GROUP BY interacting_user_id HAVING interactions_per_user > 1
> )

Here is the code:

      DSLContext create = DSL.using(connection, SQLDialect.H2);
      Field<BigDecimal> interactions_per_user = sum(PAYMENT.MUTUAL_INTERACTIONS).as("interactions_per_user");

      Result<Record2<Long, BigDecimal>> inner = create.select(PAYMENT.INTERACTING_USER_ID, interactions_per_user)
              .from(PAYMENT)
              .where(PAYMENT.USER_ID.eq(userId))
              .groupBy(PAYMENT.INTERACTING_USER_ID)
              .having(interactions_per_user.greaterThan(BigDecimal.valueOf(1))).fetch();
      LOGGER.info("Inner table is: {}", inner);

      Table<?> nested = create.select(PAYMENT.INTERACTING_USER_ID, interactions_per_user)
              .from(PAYMENT)
              .where(PAYMENT.USER_ID.eq(userId))
              .groupBy(PAYMENT.INTERACTING_USER_ID)
              .having(interactions_per_user.greaterThan(BigDecimal.valueOf(1))).asTable("nested");
      Result<Record1<Integer>> result = create.select(count(PAYMENT.INTERACTING_USER_ID))
              .from(nested)
              .fetch();

For the inner part, I can get the result correctly:

> Inner table is:
>  [+-------------------+---------------------+
> |INTERACTING_USER_ID|interactions_per_user|
> +-------------------+---------------------+
> |                  2|                   12|
> +-------------------+---------------------+
> , +-------------------+---------------------+
> |INTERACTING_USER_ID|interactions_per_user|
> +-------------------+---------------------+
> |                  3|                   20|
> +-------------------+---------------------+
> ]

But for the nested query I got Exception:
```
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "PUBLIC.PAYMENT.INTERACTING_USER_ID" not found; SQL statement:
select count("PUBLIC"."PAYMENT"."INTERACTING_USER_ID") from (select "PUBLIC"."PAYMENT"."INTERACTING_USER_ID", sum("PUBLIC"."PAYMENT"."MUTUAL_INTERACTIONS") "interactions_per_user" from "PUBLIC"."PAYMENT" where "PUBLIC"."PAYMENT"."USER_ID" = cast(? as bigint) group by "PUBLIC"."PAYMENT"."INTERACTING_USER_ID" having "interactions_per_user" > cast(? as decimal)) "nested" [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:163)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:145)
	at org.h2.expression.aggregate.AbstractAggregate.optimize(AbstractAggregate.java:92)
	at org.h2.expression.aggregate.Aggregate.optimize(Aggregate.java:705)
	at org.h2.command.dml.Select.prepare(Select.java:1206)
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "PUBLIC.PAYMENT.INTERACTING_USER_ID" not found; SQL statement:

	at org.h2.command.Parser.prepareCommand(Parser.java:744)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:352)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:316)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
	at org.jooq.impl.ProviderEnabledConnection.prepareStatement(ProviderEnabledConnection.java:109)
	at org.jooq.impl.SettingsEnabledConnection.prepareStatement(SettingsEnabledConnection.java:73)
	at org.jooq.impl.AbstractResultQuery.prepare(AbstractResultQuery.java:274)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:338)
	... 12 more

```

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

I am following the instructions here: https://www.jooq.org/doc/3.13/manual/sql-building/table-expressions/nested-selects/
```
Table<?> nested =
    create.select(BOOK.AUTHOR_ID, count().as("books"))
          .from(BOOK)
          .groupBy(BOOK.AUTHOR_ID).asTable("nested");

create.select(nested.fields())
      .from(nested)
      .orderBy(nested.field("books"))
      .fetch();
``` 
I don't know why it cannot recognize the filed name, any suggestions? Thanks.

### Versions:

- jOOQ: 3.13.1
- Java: 8
- Database (include vendor): h2
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by bzhou003** [comment]
NVM, figured it out, use `count(nested.field("INTERACTING_USER_ID"))` solved the problem.

**Comment by lukaseder** [comment]
Thanks for your message. Your solution is indeed the solution I would have suggested in this case.
