### ISSUE TITLE
Error when reading or writing timestamps of year 10000+ in HSQLDB

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9968]
In HSQLDB, when using system versioned tables (see #9967), the `END_TS` timestamp will contain a value of `10000-01-01 00:00:00.000000+0:00` to model infinity. jOOQ currently cannot parse this timestamp but produces this exception:

```
Caused by: java.lang.IllegalArgumentException: Expected '-' at position 4 in 10000-01-01 00:00:00.000000+0:00
	at org.jooq.impl.DefaultBinding$OffsetDateTimeParser.parseChar(DefaultBinding.java:2711) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$OffsetDateTimeParser.parseLocalDate(DefaultBinding.java:2611) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$OffsetDateTimeParser.offsetDateTime(DefaultBinding.java:2592) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$DefaultOffsetDateTimeBinding.get0(DefaultBinding.java:2814) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$DefaultOffsetDateTimeBinding.get0(DefaultBinding.java:1) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:844) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1726) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.operate(CursorImpl.java:1685) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.operate(CursorImpl.java:1) ~[classes/:?]
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:130) ~[classes/:?]
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1614) ~[classes/:?]
	... 39 more
```

The problem may have been introduced with #7986

A similar exception may occur when binding a value:

```
org.jooq.exception.DataAccessException: SQL [null]; Error while writing value at JDBC bind index: 3
	at org.jooq_3.14.0-SNAPSHOT.HSQLDB.debug(Unknown Source) ~[?:?]
	at org.jooq.impl.Tools.translate(Tools.java:2862) ~[classes/:?]
	at org.jooq.impl.AbstractBindContext.bindValue(AbstractBindContext.java:127) ~[classes/:?]
	at org.jooq.impl.Val.accept(Val.java:103) ~[classes/:?]
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:269) ~[classes/:?]
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:88) ~[classes/:?]
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:457) ~[classes/:?]
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:218) ~[classes/:?]
	at org.jooq.impl.QueryPartList.accept(QueryPartList.java:121) ~[classes/:?]
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:269) ~[classes/:?]
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:88) ~[classes/:?]
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:457) ~[classes/:?]
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:218) ~[classes/:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:367) ~[classes/:?]
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:502) ~[classes/:?]
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:471) ~[classes/:?]
	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:485) ~[classes/:?]
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:654) ~[classes/:?]
	at org.jooq.impl.SelectImpl.fetchOne(SelectImpl.java:3025) ~[classes/:?]
	at org.jooq.test.all.testcases.DataTypeTests.lambda$5(DataTypeTests.java:1821) ~[test-classes/:?]
	at org.jooq.test.jOOQAbstractTest.bindAndInline(jOOQAbstractTest.java:1010) [test-classes/:?]
	at org.jooq.test.BaseTest.bindAndInline(BaseTest.java:1373) [test-classes/:?]
	at org.jooq.test.all.testcases.DataTypeTests.testJava8LargeYears(DataTypeTests.java:1816) [test-classes/:?]
	at org.jooq.test.jOOQAbstractTest.testJava8LargeYears(jOOQAbstractTest.java:3515) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.jar:4.13]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.jar:4.13]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.jar:4.13]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.jar:4.13]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.13.jar:4.13]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.13.jar:4.13]
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61) [junit-4.13.jar:4.13]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.jar:4.13]
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) [junit-4.13.jar:4.13]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) [junit-4.13.jar:4.13]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) [junit-4.13.jar:4.13]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) [junit-4.13.jar:4.13]
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) [junit-4.13.jar:4.13]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) [junit-4.13.jar:4.13]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) [junit-4.13.jar:4.13]
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) [junit-4.13.jar:4.13]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) [junit-4.13.jar:4.13]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.13.jar:4.13]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.13.jar:4.13]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.jar:4.13]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) [junit-4.13.jar:4.13]
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
Caused by: java.sql.SQLException: Error while writing value at JDBC bind index: 3
	at org.jooq.impl.DefaultBindContext.bindValue0(DefaultBindContext.java:67) ~[classes/:?]
	at org.jooq.impl.AbstractBindContext.bindValue(AbstractBindContext.java:124) ~[classes/:?]
	... 52 more
Caused by: java.sql.SQLDataException: data exception: invalid datetime format
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.5.0.jar:2.5.0]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.5.0.jar:2.5.0]
	at org.hsqldb.jdbc.JDBCPreparedStatement.setParameter(Unknown Source) ~[hsqldb-2.5.0.jar:2.5.0]
	at org.hsqldb.jdbc.JDBCPreparedStatement.setString(Unknown Source) ~[hsqldb-2.5.0.jar:2.5.0]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.setString(DefaultPreparedStatement.java:153) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$DefaultOffsetDateTimeBinding.set0(DefaultBinding.java:2797) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$DefaultOffsetDateTimeBinding.set0(DefaultBinding.java:1) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$AbstractBinding.set(DefaultBinding.java:829) ~[classes/:?]
	at org.jooq.impl.DefaultBindContext.bindValue0(DefaultBindContext.java:62) ~[classes/:?]
	at org.jooq.impl.AbstractBindContext.bindValue(AbstractBindContext.java:124) ~[classes/:?]
	... 52 more
Caused by: org.hsqldb.HsqlException: data exception: invalid datetime format
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.5.0.jar:2.5.0]
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.5.0.jar:2.5.0]
	at org.hsqldb.types.DateTimeType.convertToDatetimeSpecial(Unknown Source) ~[hsqldb-2.5.0.jar:2.5.0]
	at org.hsqldb.types.DateTimeType.convertToType(Unknown Source) ~[hsqldb-2.5.0.jar:2.5.0]
	at org.hsqldb.jdbc.JDBCPreparedStatement.setParameter(Unknown Source) ~[hsqldb-2.5.0.jar:2.5.0]
	at org.hsqldb.jdbc.JDBCPreparedStatement.setString(Unknown Source) ~[hsqldb-2.5.0.jar:2.5.0]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.setString(DefaultPreparedStatement.java:153) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$DefaultOffsetDateTimeBinding.set0(DefaultBinding.java:2797) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$DefaultOffsetDateTimeBinding.set0(DefaultBinding.java:1) ~[classes/:?]
	at org.jooq.impl.DefaultBinding$AbstractBinding.set(DefaultBinding.java:829) ~[classes/:?]
	at org.jooq.impl.DefaultBindContext.bindValue0(DefaultBindContext.java:62) ~[classes/:?]
	at org.jooq.impl.AbstractBindContext.bindValue(AbstractBindContext.java:124) ~[classes/:?]
	... 52 more
```

The formatted timestamp that we produce is `'+10000-01- 1T00:00:00+00:00'`, which is clearly wrong

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.14.0. Backport scheduled for 3.13.2 (#9969)
